### ISSUE TITLE
smime_keys not in $PATH and old path in smime.rc

### ISSUE THREAD

**Issue by mimaoffice** [neomutt/neomutt#1007]
Just some remarks and a question:

1. In one of the last versions of `neomutt` (I thing 20171208), `smime_keys` was installed in `/opt/local/lib/neomutt/`.
2. Now it is installed in `/opt/local/libexec/neomutt/`.
3. In `smime.rc` the command `smime_import_cert_command` has not been updated with the new path (please fix).

Why don't you install `smime_keys` in `bin` as `mutt` does? This would be useful.

Bests, Michele

**Comment by rtlanceroad** [comment]
I also see the problem. When using `./prepare`, those three libraries `pgpewrap` `pgpring` `smime_keys` were installed to `/usr/lib/neomutt/` in the past. but since I update it today, they are installed to `/usr/libexec/neomutt/`. I checked `./configure --help`, there is no option to self define where to put executable libraries. You can see my problem in the footprint from [commit](https://github.com/6c37/crux-ports/commit/5bac6cb95591312db467406bd2a5187709ceec23) I pushed.  Please give an option to do it. Thanks!

**Comment by flatcap** [comment]
Ah, yes.  This is to do with our divorce from Mutt.
We renamed and moved lots of files to avoid clashes with Mutt, so both could be installed at the same time.
Sorry, they files and config are out of sync.

> Please give an option to do it.

The alternative is that we edit the config files at install time to point to the right locations.
I'll discuss it with the other devs.

**Comment by flatcap** [comment]
@rtlanceroad 
I hadn't heard of Crux.
If you want to add a [distro page](https://www.neomutt.org/distro.html) for it, you'd be very welcome. ([web source](https://github.com/neomutt/neomutt.github.io/tree/master/_distro))

**Comment by rtlanceroad** [comment]
@flatcap I would like to but the key point is I can't find a proper sized logo for it. I only find logo [here](https://crux.nu/pub/skins/crux/cruxlogo.png), I believe we only need that tux. I am not familiar with artwork/logo thing and I don't know how to make it proper size.

**Comment by flatcap** [comment]
@rtlanceroad 
I've just cropped, resized and pushed the logo.  It will do for now.
There really don't seem to be any better copies on the internet!
If you add `icon: crux.png` to the header, it will be picked up.

**Comment by rtlanceroad** [comment]
Thanks! PR will be avaliable in a few minutes.

**Comment by mimaoffice** [comment]
@flatcap 
Did you discussed this with the other devs?

**Comment by flatcap** [comment]
@mimaoffice 
Sorry, not yet.  We've all been a bit busy recently.
It **will** get fixed in the next release.
