### ISSUE TITLE
[Regression] Neomutt now lags on sending email

### ISSUE THREAD

**Issue by Dabsen** [neomutt/neomutt#1008]
Mutt (and later neomutt) used to send mail instantaneously with my setup (I am using msmtpqueue). I updated to the latest version from the arch repos yesterday (20171208) from the previous arch repo version (20171013), and now neomutt annoyingly lags whenever I send an email (around 4 seconds; I am using fairly old hardware). Downgrading solves the issue. I tried commenting out the abort_noattach lines in my muttrc and tried with an empty fcc file: no change. On the other hand, with an almost empty .muttrc,

    set sendmail = /usr/local/bin/msmtp-enqueue.sh
    set folder = "~/.mail/"
    set spoolfile = "+gmail/INBOX"
    mailboxes "+gmail/INBOX"

the slowdown is almost unnoticeable. I do have a good number of folder-hooks (and mailboxes) in my muttrc, but it never slowed mutt down before.

**Comment by flatcap** [comment]
Hmm.... Sorry about that.  I can't think of anything obvious that might have cause this.

Would you mind doing some detective work, to help us narrow down the problem?
First, could you try neomutt-20171027.
If you have the time and knowledge to `git bisect` the problem that would be marvellous.

An alternative approach would be to "bisect" your config file.
Cut out / restore sections and try to identify which line(s) might be causing the slowdown.

Thanks.

**Comment by Dabsen** [comment]
Thanks for the prompt reply. Yes, I can do a bisect, but probably not 
this week. I'll come back to you around Christmas, if that's ok.

**Comment by flatcap** [comment]
That's great.  Thanks.

**Comment by Dabsen** [comment]
In fact, I had time to do it today. The culprit is
4aaf1ef7670b37c54320161a8fc3386479588dc0
so my folder-hooks would probably be partly to blame (although there is 
no lag at all when I switch folders in other contexts). Anyway, let me 
know if it's just my machine being slow on a reasonable operation or if 
there's something fishy.

**Comment by Dabsen** [comment]
Btw I suspect this commit is only part of the story. There is no lag 
before it, but it only introduces a 1-2s delay. The lag is significantly 
longer in the latest release.

**Comment by flatcap** [comment]
Ah, that commit make sense.
When you send an email, it's saved to `$record`.
That folder might not be on the same host as the folder you have open, so we need to run the folder-hook twice.  Once for the save folder and again for the current folder.

Are your folder-hooks doing anything unusual?

It might be worth building and running with debug logging enabled, `neomutt -d2` (`~/.neomuttdebug0`)
That might show where the delay is happening.

**Comment by Dabsen** [comment]
Aaah! neomutt calls my folder-hooks on `$record` on the sly! I get it.  
Long story short, I call collapse-all on most folders (for a 
conversation-level view). Without this call, the lag seems to disappear, 
which makes sense as my `$record` folders are big.

Two issues here:
- I never expected my folder-hooks to be run non-interactively (i.e. on 
  folders I would not see open);
- more specifically, I never expected my folder-hooks to be called on 
  `$record`, which is a folder I do not explicitly open in mutt. I 
  clearly didn't even imagine this possibility when writing my 
  folderfilters long ago.
=> My mental model of when folder-hooks would be called was wrong, or 
perhaps became wrong.

Anyway, excluding my various `$record` folders from my collapse-all 
calls solves the issue. Thanks.

**Comment by flatcap** [comment]
Aha!

> I never expected my folder-hooks to be run non-interactively

Yes, it's a bit sneaky.  I'll update the docs to make it clear.

> excluding my various `$record` folders from my collapse-all calls solves the issue

Great.

**Comment by Dabsen** [comment]
Thanks again. The worst of the lag's gone, but it's still noticeable on 
my slowest machine. I find it puzzling. I am not even sure I understand 
why my “fix” helps if the big `$record` folders are not actually opened.  
If I find the time I'll investigate further… Anyway, the current lag is 
not too disturbing.
