### ISSUE TITLE
gmail server side search not working

### ISSUE THREAD

**Issue by kbro237** [neomutt/neomutt#1013]
When I search on a gmail imap account`=/ 'foo'` I get the error message: 

> Server-side custom search not supported: foo

where it used to work.

Could it be that the capabilities offered by Gmail looks like [this](https://developers.google.com/gmail/imap/imap-extensions):

> The support of extensions in this document are indicated by the presence of X-GM-EXT-1 in the list of supported capabilities.

Where as neomutt queries for `X_GM_EXT1` ?

**Comment by flatcap** [comment]
Sorry.  When tidying up I was mislead by a comment by the original author.
It suggested that the docs say `X-GM-EXT-1`, but the server accepts `X_GM_EXT1`.

Would you be able to give branch [issue/1013](https://github.com/neomutt/neomutt/compare/issue/1013) a try?
Thanks.
