### ISSUE TITLE
Cannot create `my_var` with `mutt.set()` in Lua

### ISSUE THREAD

**Issue by woky** [neomutt/neomutt#1017]
With this in `.muttrc`:
```
lua mutt.set("my_var", "foo")
```
NeoMutt fails `Error getting parameter my_var`.

### Use case
```
lua mutt.set("my_var", ...)
set smtp_url=$my_var
```

**Comment by flatcap** [comment]
I went through the code and I don't think 'myvars' _ever_ worked!
I've pushed a fix for both your issues to branch [devel/lua](https://github.com/neomutt/neomutt/tree/devel/lua) -- commit: d014ecba6
I'd be grateful if you could give it a try (and find any other bugs :-)
