### ISSUE TITLE
Unknown command pgpewrap

### ISSUE THREAD

**Issue by antoyo** [neomutt/neomutt#1020]
Hi.

## bug reports

* Expected behavior: send encrypted email
* Actual behavior: cannot send encrypted email
* Steps to reproduce: try to send an email that is both signed and encrypted. I get the error: unknown command `pgpewrap`
* Used program versions: 20171215
* Operating System and its version: ArchLinux (System: Linux 4.14.9-1-ARCH (x86_64))

If I add the directory `/usr/lib/neomutt` to `$PATH`, I can send the email, but I believe this should not be in `$PATH`, right?

Thanks.

**Comment by flatcap** [comment]
Ah.  These helper programs have been moved to avoid a name clash with the mutt package.
The idea was to have `/etc/neomuttrc` point to the right locations so the user wouldn't notice the change.
Have a look for the program in `/usr/lib/neomutt` or `/usr/lib64/neomutt` then adjust your `pgp_encrypt_*` config.

**Comment by antoyo** [comment]
So, the solution is to use absolute paths for `pgp_encrypt_*`?
If yes, you can close this issue.
Thank you.

**Comment by riesebie** [comment]
My version of neomutt is compiled with --gpgme and the only option I've set is `set crypt_use_gpgme=yes` All the other possible options left as default.

**Comment by antoyo** [comment]
@riesebie I didn't know about this option. Thank you!
