### ISSUE TITLE
nvim's filetype does not work

### ISSUE THREAD

**Issue by calmarc** [neomutt/neomutt#1021]
hi all. I have that in my .config/nvim/init.vim
autocmd BufNewFile,BufRead /tmp/neomutt-* set filetype=mail

So when I directly open a file in /tmp/neomut.... it (neovim) does change to filetype=mail.

When I edit a new mail from neomutt, it does not trigger that.

(and with the same setup, it works with ol'mutt).

Any ideas why that does not work?
thanks a lot!

**Comment by chrisbra** [comment]
Recent Vims contain that change to filetype.vim [already](https://github.com/vim/vim/blob/master/runtime/filetype.vim#L916-L917)

Probably missing a runtime update for your nvim. You can however simply copy that mentioned line to your init.vim

**Comment by calmarc** [comment]
Thanks Chrisbra, but I was the problem actually.
vim - was not - configured . So of course I can do whatever I want to neovim .. without any effect, when I still have editor=vim instaed of editor=nvim in muttrc.
(only because I aliased vim to nvim etc. did not help either).
So neomutt opened the fully not configured vim.. that's why.
So everything is all right editor=nvim now.
Problem was me only actually.
thanks again and a good Sunday :)
