### ISSUE TITLE
Messages hidden because of hook

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#1022]
After 4aaf1ef7, I do not see the typical messages after "Sending message...".
For example, I do not see "Mail sent."

Running neomutt with -d2 and checking the debug log shows that the messages are
written, I just don't see them. The log shows:

    [2018-01-10 22:54:49] curses_message() Sending message...
    [2018-01-10 22:54:49] curses_message() Looking up smtp.gmail.com...
    [2018-01-10 22:54:49] curses_message() Connecting to smtp.gmail.com...
    [2018-01-10 22:54:49] curses_message() Authenticating (LOGIN)...
    [2018-01-10 22:54:51] curses_message() Mail sent.

If I comment out the following hook in my .muttrc file, the issue goes away:

    # select first entry, regardless of whether read/old/unread
    folder-hook . 'push <first-entry>'

I think some related issues are #1008, #982, #977, and #931.

I've tested on current master and with the following branch:
https://github.com/neomutt/neomutt/compare/issue/931-sort

but it did not solve this issue (if the hook is not commented out).

I'm using Ubuntu 16.04.

**Comment by flatcap** [comment]
Argh!  Yes, this is that hook again.
The `folder-hook` is called when saving to `$record`.
I still think it's the "right thing to do", but it's causing a heap of problems.

> neomutt/neomutt/compare/issue/931-sort

This was just a fix for a very specific problem of setting sort variables.

Unless I come up with a very clever idea, I'll disable the hook placement for the next release.

**Comment by scottkosty** [comment]
OK thanks for the quick response, and let me know if there are any other details or testing on this issue that would help.

**Comment by scottkosty** [comment]
> Unless I come up with a very clever idea, I'll disable the hook placement for the next release.

Was this disabled in the 2018-02-23 release? No worries if not, I'm just wondering.

**Comment by flatcap** [comment]
Yes, I `#ifdef`d out the two calls in 9b1f8000 (for NeoMutt 2018-02-23).
If someone needs them, they can `#define RECORD_FOLDER_HOOK 1`

I have some code, in the wings, that'll improve the account handling.
When that's merged, this whole problem will disappear.

**Comment by scottkosty** [comment]
Great, thanks @flatcap !
