### ISSUE TITLE
[browser] <change-dir>.. Resolve Parent Directory

### ISSUE THREAD

**Issue by bazzinotti** [neomutt/neomutt#1028]
## bug reports

Using `<change-dir>..` does not resolve the parent directory. Example: it uses `/some/folder/../../another/folder` instead of `/another/folder`.

It is not user friendly.

It might cause adverse behavior. (?)

### Steps to reproduce

* First get into the browser. 
  * Here is one way to get into the browser. Open neomutt. From a folder with >0 messages, press 's' to invoke `<save-message>` and then press '?' to enter the browser.
  * Another way is by attaching a file from the compose menu. Open neomutt. Use the default shortcut 'm' to compose a mail. After exiting your editor, neomutt will be in the compose menu. Use default shortcut 'a' to attach file, then press '?' to enter the browser.

From the browser, use the default shortcut 'c' to invoke `<change-dir>`. Then, press `..<enter>` to access the parent directory. The browser updates to the parent directory, but the directory used by `<change-dir>` is not resolved.

* Example (cwd: `/some/folder`)

With default shortcuts, you would press
`c..<enter>`
You enter the parent directory successfully, but press 'c' again to see the new path is unresolved.

* Expected Directory Output
`/some/`
* Actual Directory Output
`/some/folder/../`

* Used program versions
20171215

* Operating System and its version
Linux 4.14.8-gentoo-r1+ (x86_64)

# Other
`macro browser p "<change-dir>..<enter>" "Goto Parent Directory"`

**Comment by flatcap** [comment]
Thanks for the bug report.

It should be a simple job to insert a few `realpath()`s into the code.
In addition, we could add a new browser function `<go-to-parent>`

**Comment by bazzinotti** [comment]
Dear flatcap, let me give the realpath() a shot :smiley:

I'm new to neomutt, so please be kind.

I've narrowed down the location for `realpath` insertion to https://github.com/neomutt/neomutt/blob/da6c0aadaec4021a584713b7749db864d25d2392/browser.c#L1730-L1754

Particularly L1743-L1744 or L1734-L1736 (to make use of the tmp variable)

I'll add a realpath check around there.

# Symlink Resolution

Neomutt's normal behavior is to not resolve symlinks (tested from the browser). (It also does not show hidden files, and I couldn't see a config setting for that. But it's a little off-topic so I digress).

The problem is that `realpath()` automatically resolves symlinks. There is a coreutils binary called `realpath` that does allow for toggling symlink resolution. I took a look at its source to see if I could gather the relevant C portion to be called from neomutt, but it uses `gnulib` which is an external dep. so why not call `realpath` with `popen`? If that's too compl. then I found a StackOverflow answer providing some code, but I haven't tested it yet. https://stackoverflow.com/questions/4774116/realpath-without-resolving-symlinks#answer-34202207

Solution technical details aside, I hope to get a realpath solution that includes a user config setting to resolve symlinks or not.

What are your thoughts?

## Notes

`man 3 realpath` states passing NULL to resolved_path is the safer option. Don't forget to free() the returned buffer!

I will look into how neomutt responds to errors (errno) to provide a similar error response mechanism.

**Comment by flatcap** [comment]
Hi @bazzinotti, thanks for the offer.  I accept :-)

> Neomutt's normal behavior is to not resolve symlinks (tested from the browser).

There are already a few calls to `realpath()`, so following symlinks shouldn't be a problem.

> (It also does not show hidden files, and I couldn't see a config setting for that

This is controlled by the config item: [$mask](https://www.neomutt.org/guide/reference#mask)

> I hope to get a realpath solution that includes a user config setting to resolve symlinks or not.
> If that's too complicated

Hmm... so our two options are:
- Parse the entire path ourselves, checking for `.`, `..` `//` and conditionally handling symlinks
- Running an external program

I can see the appeal, but I think that's too complicated.

> man 3 realpath states passing NULL to resolved_path is the safer option

Yes.  That only appears in POSIX:2008.  But...
Fortunately the `, NULL)` version has been used upstream, so we should be OK.

There are still lots of old systems running (neo)mutt, so the base standard for code is C99 and POSIX:2001.
There are some exceptions, but generally we try to stick to this.
Overview: https://github.com/neomutt/management/blob/master/standard-functions/README.md

> I will look into how neomutt responds to errors (errno)

Badly, usually :-)

> to provide a similar error response mechanism.

Or something better.

Thanks.

**Comment by bazzinotti** [comment]
Everything is impl'd in the PR. However, using the browser GUI will not unravel symlinks, but using `<chdir>` or `<goto-parent>` will. So if you were to use the GUI with these commands on symlinks it will feel quite strange. I propose to make the browser use `realpath()` as well.

**Comment by flatcap** [comment]
> I propose to make the browser GUI interface use realpath() as well

Yes, please.

**Comment by bazzinotti** [comment]
Based on today's IRC discussion,

__Summary of Final Changes (TODO)__

Since the new mutt_realpath() is providing symlink resolution as an option, it is not 1:1 realpath() impl. The function will thus be renamed to tidy_path.

In devel/realpath branch
* Move muttlib.c:mutt_realpath() to mutt/file.c:tidy_path(), removing IMAP/NOTMUCH conditional code.

* Adjust the test cases and browser.c for this change.

* Add test cases for symlink resolution (I already added non-symlinking tests -- though other original thoughtful path tests are welcome).

* Add an option $browser_resolve_symlinks (see init.h, options.h). This option will be disabled by default, keeping consistent with the default behavior of mutt before this addition.
