### ISSUE TITLE
LONG_STRING too short for Lua interface

### ISSUE THREAD

**Issue by westernmagic** [neomutt/neomutt#1029]
## Calling `mutt.call(command, arg)` uses an unreasonably short buffer

* Expected behavior
I'm trying to use the new Lua interface to generate a list of virtual mailboxes. I generate a arguments for `virtual-mailboxes` and then call the command once with a long string.

* Actual behavior
This works, but **without any warning or message** only makes about half of the mailboxes. This is due to the limited buffer length for `mutt.call` in Lua:
https://github.com/neomutt/neomutt/blob/da6c0aadaec4021a584713b7749db864d25d2392/mutt_lua.c#L60-L66

`LONG_STRING` defined here:
https://github.com/neomutt/neomutt/blob/a3979af4e33b0f0403efd4da04f0bbddd02f2998/conn/connection.h#L32

* Steps to reproduce
Eg. run the follwing lua function:
```lua
function virtual_mailboxes_first()
	local maildir = mutt.get("folder")
	local subdirs = io.popen("find " .. maildir .. "/ -type d -name cur -printf '%h\n'")
	local maildirs = {}
	for subdir in subdirs:lines() do
		local name = subdir:sub(maildir:len() + 2)
		table.insert(maildirs, name)
	end
	subdirs:close()

	function custom_sort(a, b)
		local preffered = {"Inbox", "Flagged", "Drafts", "Sent", "Bin", "Spam", "Archive"}
		local tmp = {}
		for index, value in ipairs(preffered) do
			tmp[value] = index
		end
		preffered = tmp

		if preffered[a] then
			if preffered[b] then
				return preffered[a] < preffered[b]
			else
				return true
			end
		else
			if preffered[b] then
				return false
			else
				return a < b
			end
		end
	end
	table.sort(maildirs, custom_sort)
	
	local result = ""
	for _, value in ipairs(maildirs) do
		result = result .. string.format('"%s" "notmuch://?query=folder:\\"%s\\"" \\ \n', value, value)
	end
	print(result:len())

	mutt.call("virtual-mailboxes", result)
	mutt.set("sidebar_sort_method", "unsorted")
end
```
The argument is in my case 3742 characters long.

* Used program versions
```
NeoMutt 20171215
```

* Operating System and its version
```
System: Linux 4.14.0-pf9 (x86_64)
ncurses: ncurses 6.0.20170902 (compiled with 6.0)
libidn: 1.33 (compiled with 1.33)
hcache backends: gdbm
```

* Suggestions
   - increase buffer size
   - output warning or error message if argument is to long

Will gladly submit a patch if we can agree on a buffer length 😃 

PS. yes I am aware that I can call `virtual-mailboxes` inside the loop.

**Comment by bazzinotti** [comment]
I found similar behavior in my neomutt not compiled with lua support.

In my case, I used `<delete-pattern>` (D) and pasted a long concatenated set of
patterns that was > 1024 bytes (I counted with tools). The string pasted in
full, but the command silently runs with a truncated string cut at the
1024th byte. You can view the truncated string after-the-fact in the
`<delete-pattern>` history by running <delete-pattern> again.


>     • Suggestions
>
>          • increase buffer size
>          • output warning or error message if argument is to[o] long
>

+1

**Comment by bazzinotti** [comment]
If we keep the static buffer size (less thought provoking), then a simple buffer size check in `mutt_str_strncat` will help. I don't know neomutt code well enough to know if other string functions need buffer size checking added.

https://github.com/neomutt/neomutt/blob/da6c0aadaec4021a584713b7749db864d25d2392/mutt/string.c#L361-L388
