### ISSUE TITLE
Problem when send email with outlook

### ISSUE THREAD

**Issue by kureshio** [neomutt/neomutt#1035]
Good evening

I'm with problem when I try send email. I config the mutt with outlook.

Message error: SSL failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**Comment by gahr** [comment]
This looks like your client and the server couldn't agree on the SSL protocol version.

Let's start by looking at the output of your `neomutt -v`

**Comment by gahr** [comment]
And `./neomutt -DS | grep ssl_use`

**Comment by kureshio** [comment]
I use the command neomutt -v
NeoMutt 20171215
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type `neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type `neomutt -vv' for details.

System: Linux 4.14.14-1-ARCH (x86_64)
ncurses: ncurses 6.0.20170902 (compiled with 6.0)
libidn: 1.33 (compiled with 1.33)
hcache backends: gdbm

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 7.2.1 20171224 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn=/usr --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Opções de compilação:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp +resizeterm +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: http://www.neomutt.org/
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

**Comment by kureshio** [comment]
I using neomutt -DS | grep ssl_use

ssl_use_sslv2 não está atribuída
ssl_use_sslv3 não está atribuída
ssl_use_tlsv1 está atribuída
ssl_use_tlsv1_1 está atribuída
ssl_use_tlsv1_2 está atribuída
ssl_usesystemcerts está atribuída

**Comment by zzandland** [comment]
I 

> Hello!
> 
> I'm not sure this helps but I had the same error when I stole an .muttrc file from a webbpage and it turns out that my error was solved by changing:
> `set smtp_url = "smtps://mattemagikern@domain.com:<port>"`
> to:
> `set smtp_url = "smtp://mattemagikern@domain.com:<port>"`
> 
> Also tested to remove the from the domain and it also solved the problem but the smtps can applied!
> 
> Cheerers!

I also confirm that changing protocol from smtps to smpt works like charm! I think Gmail's SMTP protocol doesn't involve any SSL certificate and we are trying to use one.
