### ISSUE TITLE
IMAP timeout causes `Please select mailbox first` error

### ISSUE THREAD

**Issue by stefanv** [neomutt/neomutt#1038]
I am on a somewhat unreliable network, so IMAP often times out.  When I then try to sync my mailbox, I see the following error:

```
imap_copy_messages [a0055 BAD Please select a mailbox first]?
```
Sometimes the line above starts with `imap_fast_trash`.

I'm not sure how to "select a mailbox first" as suggested; opening the folder is not an option, because that would first require syncing the current flags.

<details>
NeoMutt 20171215
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type `neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type `neomutt -vv' for details.

System: Linux 4.12.0-2-amd64 (x86_64)
ncurses: ncurses 6.0.20171125 (compiled with 6.0)
libidn: 1.33 (compiled with 1.33)
hcache backends: tokyocabinet

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 7.2.0-17' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.2.1 20171205 (Debian 7.2.0-17) 

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --libexecdir=/usr/lib --with-mailpath=/var/mail --enable-fcntl --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-yegfMl/neomutt-20171215+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3  -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  +gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta 
  +mixmaster +nls +notmuch -openssl +pgp +resizeterm +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
</details>

**Comment by ElDeveloper** [comment]
I also see this problem sometimes my network is supposed to be reliable (but it's at a university ... so who knows), I almost always see this with the `imap_fast_trash` message. This is also sometimes prefaced by me trying to open an e-mail and seeing an empty message. Then when I try to exit the mailbox or sync I see the problem described above.

Here's my system's info:

<details>
NeoMutt 20171027-131-1646a6-dirty
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type `neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type `neomutt -vv' for details.

System: Darwin 17.3.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
hcache backends: bdb

Compiler:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Configure options: '--with-ssl' '--enable-pop' '--enable-imap' '--enable-smtp' '--with-sasl' '--enable-hcache' '--prefix=/usr/local/' '--disable-doc' '--with-ncurses' '--with-bdb' 'LDFLAGS=-lintl -L/usr/local/lib/ -L/usr/local/opt/openssl/lib' 'CPPFLAGS=-I/usr/local/include/ -I /usr/local/opt/openssl/include'

Compilation CFLAGS: -Wall -pedantic -g -O2 -fno-delete-null-pointer-checks

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +bkgdset +color +curs_set -debug +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool -idn -locales_hack -lua
  +meta -mixmaster +nls -notmuch +openssl +pgp +resizeterm +sasl +smime
  +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: http://www.neomutt.org/
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
</details>

**Comment by ElDeveloper** [comment]
Just in case this helped, I was able to capture this problem on an animated gif:

![problem-mutt](https://user-images.githubusercontent.com/375307/35527472-a9bba89c-04df-11e8-82e7-72f850593c19.gif)

**Comment by ElDeveloper** [comment]
Following up on this issue, this may have something to do with a timed out connection (see logging info below). In this case it seems like the index still had a list of my e-mails but when I tried to open one email neomutt would find an empty file and show me nothing on screen or simply appear as if I hadn't tried to open the email.

```
[2018-02-22 12:24:20] curses_message() Connection to imap.gmail.com timed out
[2018-02-22 12:24:22] curses_message() Looking up imap.gmail.com...
[2018-02-22 12:24:22] curses_message() Connecting to imap.gmail.com...
[2018-02-22 12:24:23] curses_message() SSL/TLS connection using TLS1.2 (ECDHE-RSA/CHACHA20-POLY1305/AEAD)
[2018-02-22 12:24:23] curses_message() Logging in...
[2018-02-22 12:24:25] curses_message() Sorting mailbox...
[2018-02-22 12:24:28] curses_message() Fetching message...
[2018-02-22 12:24:28] curses_message() Fetching message...
[2018-02-22 12:24:28] mutt_file_safe_rename() link (/Users/username/.cache//imaps:email@imap.gmail.com/INBOX/.muttLfxR18/600640573-258118.tmp, /Users/username/.cache//imaps:email@imap.gmail.com/INBOX/600640573-258118.tmp) failed: File exists (17)
[2018-02-22 12:24:29] curses_message() Could not copy message
[2018-02-22 12:24:29] curses_message() Sorting mailbox...
[2018-02-22 12:24:31] curses_message() Copying 2 messages to [Gmail]/Trash...
[2018-02-22 12:24:31] curses_message() imap_fast_trash [a0009 BAD UID COPY not allowed now.]

[2018-02-22 12:24:33] curses_message() Fetching message...
[2018-02-22 12:24:33] mutt_file_safe_rename() link (/Users/username/.cache//imaps:email@imap.gmail.com/INBOX/.muttWm2wAz/600640573-258118.tmp, /Users/username/.cache//imaps:email@imap.gmail.com/INBOX/600640573-258118.tmp) failed: File exists (17)
[2018-02-22 12:24:33] curses_message() Copying 2 messages to [Gmail]/Trash...
[2018-02-22 12:24:34] curses_message() imap_fast_trash [a0012 BAD UID COPY not allowed now.]

[2018-02-22 12:24:36] curses_message() Fetching message...
[2018-02-22 12:24:36] mutt_file_safe_rename() link (/Users/username/.cache//imaps:email@imap.gmail.com/INBOX/.muttVJf1lL/600640573-258118.tmp, /Users/username/.cache//imaps:email@imap.gmail.com/INBOX/600640573-258118.tmp) failed: File exists (17)
```

**Comment by ElDeveloper** [comment]
Another thing that I noticed is that when this type of problem occurs with `gnutls` the index will still be rendered with all the messages but it won't be updated or be usable. Meaning, that when I try to open a message the operation will fail and mutt will display the index again. However, when this happens when compiling with openssl the index just disappears and I have to manually connect again.

The problem may have to do with the logic used to reconnect after a connection times out, seems like it needs to update the rest of the UI afterwards. I seem to recall reading about how the gnutls code in mutt handles timeouts better than the openssl code.

All in all using openssl is better as the GUI isn't misleading.

**Comment by stefanv** [comment]
Was this issue resolved, @flatcap?
