### ISSUE TITLE
Segfault on list-reply

### ISSUE THREAD

**Issue by marcvs** [neomutt/neomutt#1045]
## bug reports

* Expected behavior
hit "L" for "list-reply
create new email to list

* Actual behavior
segfault with error code 139

* Steps to reproduce
hit "L" (capital letter)

* Used program versions
NeoMutt 20171215-138-74922c (=git commit 74922c787a4efae9b8db9b497b680f073050c217, head as of now)

* Operating System and its version
Linux 4.14.0-3-amd64
Debian/testing

**Comment by gahr** [comment]
This is going to be fixed by 97fe396.
