### ISSUE TITLE
Unexpected behavior when whitespace exists in maildir name

### ISSUE THREAD

**Issue by carldavis** [neomutt/neomutt#1046]
I am unable to reference a maildir ("Deleted Items") in a macro if I have a whitespace in the maildir name. I have tried escaping the whitespace, enclosing the macro in single quotes, enclosing the macro in single quotes with the path in double quotes, etc., with all attempt having different but non-functional results.

## steps to reproduce
Create a macro referencing a maildir with whitespace
```macro index d '<save-message>~/Mail/Deleted Items<enter>' "trash"```

Executing the macro results in: 
```Create /Users/cdavis/Mail/Deleted `Items/Items?` ([yes]/no):```

Escaping the whitespace leads to different but still incorrect results:
```macro index d '<save-message>~/Mail/Deleted\ Items<enter>' "trash"```
```Create /Users/cdavis/Mail/Deleted\Items? ([yes]/no):```

## workaround
```ln -s "Deleted Items" DeletedItems```

## version
> System: Darwin 16.7.0 (x86_64)
> ncurses: ncurses 5.7.20081102 (compiled with 5.7)
> hcache backends: tokyocabinet
> 
> Compiler:
> Apple LLVM version 9.0.0 (clang-900.0.37)
> Target: x86_64-apple-darwin16.7.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin
> 
> Configure options: '--prefix=/usr/local/Cellar/neomutt/20171027' '--with-ssl=/usr/local/opt/openssl' '--with-sasl' '--with-gss' '--with-tokyocabinet' '--disable-debug' 'CC=clang'
> 
> Compilation CFLAGS: -Wall -pedantic -g -O2

**Comment by flatcap** [comment]
Thanks for the bug report @carldavis.

I tried every combination of quoting and escaping...

```
macro index <f1> '<save-message>one file<enter>'
macro index <f2> '<save-message>two\ file<enter>'
macro index <f3> '<save-message>three\\ file<enter>'

macro index <f4> "<save-message>four file<enter>"
macro index <f5> "<save-message>five\ file<enter>"
macro index <f6> "<save-message>six\\ file<enter>"

macro index <f7> '<save-message>"seven file"<enter>'
macro index <f8> '<save-message>"eight\ file"<enter>'
macro index <f9> '<save-message>"nine\\ file"<enter>'

macro index <f10> "<save-message>'ten file'<enter>"
macro index <f11> "<save-message>'eleven\ file'<enter>"
macro index <f12> "<save-message>'twelve\\ file'<enter>"
```

Which lead to a variety of strangely-named files...

```
-rw-------. 1 mutt mutt 407 feb  1 16:01 onefile
-rw-------. 1 mutt mutt 407 feb  1 16:01 two\file
-rw-------. 1 mutt mutt 407 feb  1 16:01 three\\file

-rw-------. 1 mutt mutt 407 feb  1 16:01 fourfile
-rw-------. 1 mutt mutt 407 feb  1 16:01 fivefile
-rw-------. 1 mutt mutt 407 feb  1 16:01 six\file

-rw-------. 1 mutt mutt 407 feb  1 16:01 "sevenfile"
-rw-------. 1 mutt mutt 407 feb  1 16:01 "eight\file"
-rw-------. 1 mutt mutt 407 feb  1 16:01 "nine\\file"

-rw-------. 1 mutt mutt 407 feb  1 16:01 'tenfile'
-rw-------. 1 mutt mutt 407 feb  1 16:01 'elevenfile'
-rw-------. 1 mutt mutt 407 feb  1 16:01 'twelve\file'
```
