### ISSUE TITLE
attachment: use external viewer for text/plain

### ISSUE THREAD

**Issue by uinput** [neomutt/neomutt#1047]
Hello,

I would like to be able to open `text/plain` files with vim in the attachment viewer. I thought this line in my `mailcap` should do, but it does not work as expected.
```
text/plain; vim %s; needsterminal
```

It seems like there were a few changes going on discussed in #449 and #555. I also read through the documentation but could not find any definite statement on whether this works or not. So, do you have any advice for me on setting this up, or is it not currently supported?

**Comment by flatcap** [comment]
I'm not sure of the best solution to this, but I got _something_ working.

**neomuttrc** -- Force the mailcap to be used for 'text/plain'
```
auto_view text/plain
```

**mailcap** -- Spawn a new window (sleep, so we have time to open the file before it's deleted)
```
text/plain; gnome-terminal -- vim %s & sleep 2; copiousoutput
```

**Comment by uinput** [comment]
Thank you for your answer! This works so far, but it would also open `text/plain` files when opening the mail in the page view. It's quite convenient to have the mail open in page view, but in some cases it's desirable to open it in vim for further processing. I guess this specific functionality is not supported then?

**Comment by bazzinotti** [comment]
if you remove the copious... flag, then you might get what you want.

On Feb 3, 2018 10:37 AM, "uinput" <notifications@github.com> wrote:

Thank you for your answer! This works so far, but it would also open
text/plain files when opening the mail in the page view. It's quite
convenient to have the mail open in page view, but in some cases it's
desirable to open it in vim for further processing. I guess this specific
functionality is not supported then?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/neomutt/neomutt/issues/1047#issuecomment-362823119>,
or mute
the thread

**Comment by uinput** [comment]
When I remove the `copiousoutput` flag, then the mail will not open in vim if opened from the attachment view.

**Comment by bazzinotti** [comment]
On 03/02/18 11:32 -0800, uinput wrote:
>   When I remove the copiousoutput flag, then the mail will not open in vim
>   if opened from the attachment view.
OK, so keep the copiousoutput flag on that one, but make another entry in your
mailcap for the same MIME type without the copiousoutput flag and that
should affect the pager.

**Comment by uinput** [comment]
Thank you for helping me, really appreciating it.
I tried two setups following your advice. The first will always open the mail in vim, the second will always use `cat` for the output. I also tried a different order, without success.
```
text/plain; cat %s
text/plain; tmux split-window -v view %s && sleep 1 ; copiousoutput
```
```
text/plain; cat %s ; copiousoutput
text/plain; tmux split-window -v view %s && sleep 1
```

**Comment by bazzinotti** [comment]
On 03/02/18 16:14 -0800, uinput wrote:
>   Thank you for helping me, really appreciating it.
The feeling is mutual! :)

I think I may have solved it for you! The normal behavior for the
<enter> and <return> key is to only use the mailcap 'if necessary'.
There is a function / keyboard shortcut to force use of the mailcap
entry when opening attachments. It is 'm' which stands for
<view-mailcap>.

Be sure to use the '?' key on all of the particular menu types in neomutt
to learn what your potential options are. It also lists unmapped
functions.

So you can get by with 'm' or remap that function to <enter> if you'd
like. Let me know if you need help with that.

**Comment by bazzinotti** [comment]
I'm having doubts if that will solve it for you. I'm looking forward to your response.

**Comment by uinput** [comment]
You are my hero, thank you!

> Be sure to use the '?' key on all of the particular menu types in neomutt to learn what your potential options are. It also lists unmapped functions.

This is indeed true. Will do so in the future.

For anyone seeking to get the same behavior, this is the working setup. We set a command for `text/plain` in the mailcap, while binding our keys to `view-mailcap` in the attachment viewer. This will force neomutt using the mailcap file for each mime type, as explained above.
```
bind attach <Enter> view-mailcap
bind attach <Return> view-mailcap
```
```
text/plain; tmux split-window -v view %s && sleep 1 ; copiousoutput
```
