### ISSUE TITLE
Page Up/Down keys suddenly(?) not working

### ISSUE THREAD

**Issue by chrboe** [neomutt/neomutt#1048]
Page Up/Down seems to have randomly stopped working a while ago ("Key is not bound"). I don't know if I messed something up in my configuration, I'll do my best to list all the seemingly relevant settings below.

## Used program versions
* st (simple terminal) 0.7
* zsh 5.3.1
* NeoMutt 20171027

## Operating System and its version
Gentoo Linux, 4.14.5 Kernel

## Config excerpts
My `.muttrc` contains the following keyboard-relevant settings (though none of them have anything to do with Page Up/Down):
```
bind index,pager <F1> sidebar-prev
bind index,pager <F3> sidebar-next
bind index,pager <F2> sidebar-open

bind index     ^[[4~ last-entry

bind pager <up> previous-line
bind pager <down> next-line

bind index - collapse-thread
bind index _ collapse-all

macro index r   '<read-thread><previous-entry><next-new-then-unread>'
bind  index \Cr reply

# extract patches
macro index \Cp "<enter-command>unset wait_key<enter><enter-command>set pipe_decode<enter><tag-prefix><pipe-entry>from-mutt<enter><enter-command>unset pipe_decode<enter><enter-command>set wait_key<enter>" "output git patches"


# 'L' performs a notmuch query, showing only the results
macro index L "<enter-command>unset wait_key<enter><shell-escape>read -p 'notmuch query: ' x; echo \$x >~/.cache/mutt_terms<enter><limit>~i \"\`notmuch search --output=messages \$(cat ~/.cache/mutt_terms) | head -n 600 | perl -le '@a=<>;chomp@a;s/\^id:// for@a;$,=\"|\";print@a'\`\"<enter>" "show only messages matching a notmuch pattern"

# 'a' shows all messages again (supersedes default <alias> binding)
macro index a "<limit>all\n" "show all messages (undo limit)"


macro index,pager \cb "<pipe-message> urlscan<Enter>" "call urlscan to extract URLs out of a message"
macro attach,compose \cb "<pipe-entry> urlscan<Enter>" "call urlscan to extract URLs out of a message"
```

## Extra
Note: Page Up/Down works in other applications such as neovim.

The keycodes of Page Up/Down seem to be the following: (I pressed PgUp, Enter, PgDown)
```
$ cat
^[[5~

^[[6~
```

The PageUp and PageDown functions are bound, according to the help window:
```
<PageUp>         previous-page               move to the previous page
<PageDown>       next-page                   move to the next page
```

`what-key` reports the following for Page Up and Page Down respectively:

```
Char = \x10a, Octal = 412, Decimal = 266
Char = \x10d, Octal = 415, Decimal = 269
```

**Comment by flatcap** [comment]
Thanks for the detailed bug report.
I see the same output in `cat` as you.

I've just tried some different terminals: gnome-terminal, konsole, xterm, eterm, linux vt
and some different shells bash, ksh, tcsh, zsh
but I always get the same result for `what-key`:
```
Char = <PageUp>, Octal = 523, Decimal = 339
Char = <PageDown>, Octal = 522, Decimal = 338
```

What changed recently?
Have you tried other terminals / shells?
Do you get the same behaviour?

**Comment by chrboe** [comment]
Thanks for the swift reply!

I just tried in xterm and it does seem to work there... Curiously, if set `TERM` to a fake value (`TERM=xterm neomutt`) it actually works in st as well, so I'm guessing there's something wrong with either sts terminfo entry or neomutts `$TERM` parsing.

(By the way, `$TERM` for st is `st-256color`)

**Comment by chrboe** [comment]
I just thought of this as well: my `/etc/inputrc` contains the following (I think a lot of applications broke before doing this change):
```
# for linux console and RH/Debian xterm
# allow the use of the Home/End keys
"\e[1~": beginning-of-line
"\e[4~": end-of-line
# map "page up" and "page down" to search history based on current cmdline
"\e[5~": history-search-backward
"\e[6~": history-search-forward
# allow the use of the Delete/Insert keys
"\e[3~": delete-char
"\e[2~": quoted-insert

# gnome / others (escape + arrow key)
"\e[5C": forward-word
"\e[5D": backward-word
# konsole / xterm / rxvt (escape + arrow key)
"\e\e[C": forward-word
"\e\e[D": backward-word
# gnome / konsole / others (control + arrow key)
"\e[1;5C": forward-word
"\e[1;5D": backward-word
# aterm / eterm (control + arrow key)
"\eOc": forward-word
"\eOd": backward-word

# konsole (alt + arrow key)
"\e[1;3C": forward-word
"\e[1;3D": backward-word

# Chromebooks remap alt + backspace so provide alternative (alt + k)
"\ek": backward-kill-word

# fix Home and End for German users
"\e[H": beginning-of-line
"\e[4~": end-of-line

set enable-keypad on
```
Unfortunately I'm not exactly sure what I have changed in this file, the only thing I know for sure is that I added the last line (to fix the broken `End` key behaviour in zsh). I think the rest is actually the default, and I seem to recall neomutt working with this configuration.

**Comment by flatcap** [comment]
I don't _think_ the inputrc will affect neomutt.  We don't use readline.

Decoding my terminfo using `infocmp` I see:
`knp=\E[6~` and `kpp=\E[5~`  Keypad next and prior (a.k.a. page down, up)
I suspect your bindings are different.

**Comment by chrboe** [comment]
Nope, I get the exact same `knp=\E[6~, kpp=\E[5~`.

**Comment by chrboe** [comment]
I just noticed I compiled neomutt using slang instead of (the default?) ncurses. Could that make a difference?

**Comment by flatcap** [comment]
Theoretically, there shouldn't be any differences.
Realistically, there are some subtle differences.

That's quite probably the cause.

**Comment by chrboe** [comment]
I just recompiled with ncurses and the issue seems to be fixed, but I also remembered why I switched to slang in the first place. I'm getting some weird visual artifacts like [these](https://imgur.com/a/4ltBY), and somebody suggested to use slang instead of ncurses to circumvent the problem. Any other known workarounds for that?

**Comment by flatcap** [comment]
> I'm getting some weird visual artifacts like these

Those black regions after the "To" and "Subject"?
I haven't seen that.  Is the problem repeatable, or intermittant?

**Comment by chrboe** [comment]
Yes, it's very repeatable, it happens every time. This is what it's supposed to look like (i.e. what it looks like using slang): https://imgur.com/a/YPlIV
When I scroll around for a bit the black areas disappear completely.

[Here](https://pastebin.com/9tLfws25)'s a pastebin of all my color related configuration.

**Comment by flatcap** [comment]
I've just racked up my monitor's contrast to max, but I don't see it (using your config).
Do you see the same effect in a different terminal?
What's your `$index_format` (I don't think that'll be the cause)

**Comment by chrboe** [comment]
I just tried with xterm(-256color) and the issue appears as well. I should note that the black color is actually the terminals background, it showed up as white in xterm.

```
set index_format = "%2E %Z %{%b %d} %-15.15L %s"
```

Though `index_format` really shouldn't be the cause, since the effect occurs in the sidebar as well.

**Comment by flatcap** [comment]
I've tried with three terminals, but no joy.
I've even looked at the lkml just in case there was something magic going on.

If you really want to find the cause, then I suggest saving a large chunk of lkml to a maildir,
then running neomutt with just your colour config -- try to narrow down what's triggering the problem on your machine, but not mine.

**Comment by chrboe** [comment]
Sounds like a good idea, I'll do that.

I should clarify that this isn't lkml-specific, I just didn't want to show off any private emails in the screenshot. This happens with every mailbox.

**Comment by chrboe** [comment]
Well here's something new... I've narrowed my testing environment down to a single mailbox and this **exact** config:
```
set mbox_type=Maildir

set folder      = ~/testmail;
set spoolfile   = "+INBOX"
set mbox        = "+INBOX"

mailboxes "=INBOX"

#############################################################
#                          PAGER                            #
#############################################################
color hdrdefault        color141        color235
color quoted            color105        color235
color signature         blue            color235
color attachment        color214        color235
color prompt            brightmagenta   color235
color message           brightcolor88   color235
color error             brightred       color235
color indicator         color251        color124
color status            brightgreen     blue
color tree              color128        color235
color normal            color251        color235
color markers           red             color235
color search            color251        color235
color tilde             brightmagenta   color235

#############################################################
#                          INDEX                            #
#############################################################
color index             blue            color235 ~F

# regular mail
color index             color251        color235 "~A"
color index_date        color221        color235
color index_subject     color147        color235 "~A"
color index_flags       color82         color235 "~A"

# unread mail
color index             brightwhite     color235 "~N|~O"
color index_subject     brightcolor147  color235 "~N|~O"
color index_flags       brightcolor82   color235 "~N|~O"

#############################################################
#                        SIDEBAR                            #
#############################################################
color sidebar_ordinary  color147        color235
color sidebar_new       brightcolor147  color235
color sidebar_divider   brightwhite     color235
```

Alas, it showed the same behaviour. Though I noticed that [the artifact only actually appears on read mail](https://imgur.com/a/bU0NT). In fact, changing the regular mail color from `color251` to `brightcolor251` fixes the problem, so I guess has something to do with bold rendering of the font? I'm just confused at this point.

**Comment by chrboe** [comment]
Hah, I think I'm on to something now. The `color normal` statement (i.e. the pager color) seems to somehow clash with the `color index ... "~A"`. If these two are the same color, the bug occurs. Setting the pager color to `color250` and leaving the index color at `color251` "fixes" the problem. However, the black region underneath the sidebar still remains.
