### ISSUE TITLE
Can not be installed in debian using apt install

### ISSUE THREAD

**Issue by eamanu** [neomutt/neomutt#1049]
Hello!

I want to install neomutt in debian,  but seems like it unable to locate the package. 

I run: `sudo apt-get install neomutt`

But, I have this output:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package neomutt
```
My OS is:
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch

There are some problems with the package on debian? 

Regards!

**Comment by riesebie** [comment]
You'll find neomutt in buster/sid only.

**Comment by riesebie** [comment]
Another option would be to build the package yourself: [Selfmade DebianPackage](https://github.com/neomutt/neomutt/tree/distro/debian/debian)

**Comment by eamanu** [comment]
Hello, 

When I run `dpkg-buildpackage -us -uc` I have this output
```
dpkg-buildpackage: source package neomutt
dpkg-buildpackage: source version 1:20171215-1lxtec1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Elimar Riesebieter <riesebie@lxtec.de>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build neomutt-20171215
dpkg-checkbuilddeps: error: Unmet build dependencies: clang-5.0 dh-lua libgnutls28-dev libgpgme-dev libidn11-dev libkrb5-dev libncurses5-dev libncursesw5-dev libnotmuch-dev libqdbm-dev libsasl2-dev w3m
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
```

Then I do: `apt install clang-5.0 dh-lua libgnutls28-dev libgpgme-dev libidn11-dev libkrb5-dev libncurses5-dev libncursesw5-dev libnotmuch-dev libqdbm-dev libsasl2-dev w3m`

But now I have this:
```

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libgpgme-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libgpgme-dev' has no installation candidate

```

**Comment by riesebie** [comment]
Hmm, according to [packages.debian.org](https://packages.debian.org/search?keywords=libgpgme-dev)
libgpgme-dev should be available as version `1.8.0-3+b2 `in stretch. Did you run `apt update` before?

**Comment by eamanu** [comment]
Now I have problem with clang-5.0. On debian is the 3.* version.

**Comment by riesebie** [comment]
To use clang from stable please edit debian/rules. Change
`export CC=/usr/bin/clang-5.0` to `export CC=/usr/bin/clang-3.9`
`export CXX=/usr/bin/clang++-5.0` to  `export CXX=/usr/bin/clang++-3.9`

and in debian/control changeclang-5
`clang-5.0` to `clang-3.9`

To use default gcc remove the export lines from rules and the clang dependency from control ad you're done.
