### ISSUE TITLE
notmuch entire-thread outside a virtual folder

### ISSUE THREAD

**Issue by a3nm** [neomutt/neomutt#105]
When using mutt in a regular folder, I would often like to locate all messages in the thread of a given message that are known to notmuch. However, hitting '+' to call <entire-thread> fails, displaying "No virtual folder, aborting."

I think it would be more helpful if this function (or some other function), when called outside of a virtual folder, retrieved the Message-ID of the current messages (or of all tagged messages), asked notmuch for all messages in their threads, and generated a moved to a new vfolder with this view. I don't think I can script this behavior, because of the need of extracting the Message-Id (barring awful hacks like generating a command in a file that I would then source...).

Do you think it would make sense to add the feature that I describe? Thanks!

**Comment by scottkosty** [comment]
I agree that this would be nice.

**Comment by dnguyen85** [comment]
Would be great if this feature can be implemented

**Comment by flatcap** [comment]
Sorry, this enhancement didn't attract someone to write some code.
This issue will now be closed, but listed on the [Closed Discussions](https://www.neomutt.org/dev/discussions) page.

**Comment by flatcap** [comment]
I _still_ don't use notmuch, but I've created a quick hack -- PR #4897 

Please can you give branch [[devel/notmuch-entire-thread]](https://github.com/neomutt/neomutt/tree/devel/notmuch-entire-thread) a try.

Thanks
