### ISSUE TITLE
Cannot encrypt to self

### ISSUE THREAD

**Issue by antoyo** [neomutt/neomutt#1051]
Hi.
When I follow the instructions [here](https://www.neomutt.org/feature/encrypt-to-self) to encrypt to myself, I get the following warning at startup:
```
pgp_default_key: unknown variable
```
I use this version:
```
NeoMutt 20171215
```
What am I doing wrong?
Thank you.

**Comment by flatcap** [comment]
Ah, sorry about that -- it still works, but the docs are (sort of) wrong.

Upstream made some changes that we've adopted.
They haven't been released yet, but the docs have been updated.
The docs *will* be right, soon.

The docs that come installed with NeoMutt should be correct.
For now, you need:

| Config | Type | Default |
| :--- | :--- | :--- |
| pgp_self_encrypt | boolean | no |
| pgp_self_encrypt_as | string | (empty) |

The next release will use the documented names and have aliases for the old config.

**Comment by antoyo** [comment]
Thanks.
