### ISSUE TITLE
<edit-label> causes email to be deleted

### ISSUE THREAD

**Issue by frnsys** [neomutt/neomutt#1053]
## bug reports

* Expected behavior
    - Use `Y` to trigger `<edit-label>` on an email
    - Add a label to the email
    - Hit `$` to `<sync-mailbox>`
    - Email remains unchanged except for the new label

* Actual behavior
    - Use `Y` to trigger `<edit-label>` on an email
    - Add a label to the email
    - Hit `$` to `<sync-mailbox>`
    - Email is deleted

* Steps to reproduce
    - Use `Y` to trigger `<edit-label>` on an email
    - Add a label to the email
    - Hit `$` to `<sync-mailbox>`

* Used program versions
NeoMutt 20171215

* Operating System and its version
Ubuntu 16.04 (Linux 4.4.0-112-generic (x86_64))

**Comment by flatcap** [comment]
Hmm... that **is** strange.

Is your email local (maildir), or remote (IMAP)?
When you `<sync-mailbox>` does the email:
- become marked 'D' deleted
- disappear from the index, but email still exists
- disappear from the index and actually get deleted from disk

In the <kbd>?</kbd> help, can you check the bindings:
- Y edit-label
- $ sync-mailbox

Please can you paste the output of `neomutt -v`

**Comment by frnsys** [comment]
Thanks for your quick response -- I feel like it might be something on my end but I can't figure out what.

The mailbox is local (synced with `offlineimap`). I do see now that the email is deleted after this message shows up: `Mailbox was externally modified.  Flags may be wrong.`. The only things that I can think of are that maybe `offlineimap` or `notmuch` are interfering?

I don't see a `D` flag show up. It appears to be deleted from the disk.

In the `?` help, the bindings are all fine.

Here's the output of `neomutt -v`:

```
System: Linux 4.4.0-112-generic (x86_64)
ncurses: ncurses 6.0.20160213 (compiled with 6.0)
libidn: 1.32 (compiled with 1.32)

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.6' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker
-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --
disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-a
md64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --wi
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.6) 

Configure options: --disable-doc --ssl --sasl --notmuch

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls -gpgme -gss -hcache -homespool +idn -locales_hack -lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp +resizeterm +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

**Comment by flatcap** [comment]
Ah, I might have a clue about what's going on.

You're using: <kbd>Y</kbd> `<edit-label>` which edits the `X-Label:` header of an email.
(I've just checked) This means you end up with a new email file (new name, new inode).

I suspect this is confusing offlineimap, resulting in the email being deleted.

If you're using notmuch, you'd be better off using notmuch labels `<modify-labels>`.
They're stored in the notmuch database and don't affect the email file.

https://www.neomutt.org/feature/custom-tags

**Comment by frnsys** [comment]
Thanks, I'm trying this out now. It looks as though I can only edit notmuch labels while in a virtual folder (otherwise I get `Folder doesn't support tagging, aborting.`), is it possible to do it from a regular one?

**Comment by flatcap** [comment]
> is it possible to do it from a regular one?

Unfortunately, not.  It's on the wish list.

**Comment by frnsys** [comment]
Ok no problem, I see #742 is open for this. I'll close this one -- thanks!

**Comment by frnsys** [comment]
For anyone who needs it, I managed to get this working well with notmuch's tagging system. My [muttrc with the setup is here](https://github.com/frnsys/dippindots/blob/fa19ba6b905a3da18b3f064e82462096e3a8d580/dots/email/muttrc#L9)
