### ISSUE TITLE
missing docs about notmuch feature

### ISSUE THREAD

**Issue by evgeni** [neomutt/neomutt#106]
Ohai,

when discussing the notmuch feature with jonas in #debian-devel, we noticed that neomutt's README.notmuch is kinda short compared to the original one at https://github.com/karelzak/mutt-kz/blob/master/README.notmuch

I think that most of the content should be copied over and make a nice readme how to use that feature :)

**Comment by flatcap** [comment]
The NotMuch README has been restored.
