### ISSUE TITLE
Key selection cannot be aborted

### ISSUE THREAD

**Issue by afwlehmann** [neomutt/neomutt#1063]
* Expected behavior
When sending a PGP encrypted mail and the receipient's key cannot be determined, it should be possible to cancel the manual key selection process, e.g. in order to postpone the email.

* Actual behavior
The manual key selection cannot be aborted. Instead, one can only exit neomutt.

* Steps to reproduce
Compose mail, select PGP encryption and choose a receipient for which there's no key or the key cannot be automatically determined.

* Used program versions
neomutt 20171215

* Operating System and its version
Arch Linux

**Comment by flatcap** [comment]
Hmm...  there are a few places in (Neo)Mutt where you can use <kbd>Ctrl-G</kbd> to abort / escape from a menu.

**Comment by afwlehmann** [comment]
@flatcap Thanks a lot. Unfortunately that doesn't work either.

**Comment by flatcap** [comment]
I've just run 2017-12-15 and I don't get the same problem.

First, I cleared out my GPG key store, then I tested:
- GPGME enabled
- GPGME disabled
- gpg 1.4
- gpg 2.2

Each time, when I try to send an encrypted email to an unknown recipient, I get a prompt:
```
Enter keyID for john@example.com:
```
If I hit <kbd>Ctrl-G</kbd>, I get the error:
```
No matching keys found for ""
```
But now I'm back at the compose menu.

What are you seeing?

**Comment by afwlehmann** [comment]
@flatcap Ah, now I see. From what I understood at first I tried <kbd>Ctrl</kbd>+<kbd>G</kbd> during key selection, not at the initial prompt (`Enter keyId for ...`). Doing the latter (as described in your example) works perfectly and solves the problem once and for all. For me it was counterintuitive plus <kbd>?</kbd> or <kbd>F1</kbd> won't work at that point. Now that I know, however, it's simple as that. Thanks for taking the time and looking into the matter!

**Comment by flatcap** [comment]
No problem.

There are a couple of things NeoMutt could do:
- An on-screen note: "Ctrl-G to abort"
- Simply quitting the entry on <kbd>enter</kbd>

It's on the todo list, now.
