### ISSUE TITLE
please document notmuch-uri syntax

### ISSUE THREAD

**Issue by jonassmedegaard** [neomutt/neomutt#107]
README.notmuch documents a command "virtual-mailboxes" like this:

    virtual-mailboxes description notmuch-URI { description notmuch-URI ...}

What is in more detail the syntax of notmuch-URI?

Inspired by <https://github.com/karelzak/mutt-kz/blob/master/README.notmuch> I tried either of these:

    virtual-mailboxes "INBOX" "notmuch://query=tag:inbox AND tag:unread AND NOT tag:killed"

    virtual-mailboxes "INBOX" "notmuch://query=tag:inbox%20AND%20tag:unread%20AND%20NOT%20tag:killed"

but they both fail, spewing a bunch of "Error: Database path must be absolute." and then shows a single hit.

**Comment by jonassmedegaard** [comment]
Stupid me, this (with "?query" not "query") works, thanks to evgeni:

    virtual-mailboxes "INBOX" "notmuch://?query=tag:inbox AND tag:unread AND NOT tag:killed"

**Comment by jonassmedegaard** [comment]
Whops - underlying issue of this lacking documentation persist.

**Comment by flatcap** [comment]
I've restored the original NotMuch README and added a section to the main manual.
If that's not enough, re-open this issue and pester me :-)
