### ISSUE TITLE
configure --runstatedir=/run

### ISSUE THREAD

**Issue by riesebie** [neomutt/neomutt#1071]
Debians debhelper compat level 11, dh_auto_configure passes --runstatedir=/run to ./configure. This is not recognised by autosetup. Is there any chance to adapt this? More infos [here](https://lwn.net/Articles/436012/)

**Comment by gahr** [comment]
@msteveb would you be willing to add `runstatedir` to `system`'s module-options?

**Comment by msteveb** [comment]
Sure. Done.

**Comment by riesebie** [comment]
@msteveb Thank you very much! 
But where do I find your contribution?

**Comment by msteveb** [comment]
Over here: https://github.com/msteveb/autosetup/commit/f111a9f34b8793b66090f5cc7426b370caa3d8e5

You just need to update your autosetup to this latest version

**Comment by gahr** [comment]
Thanks @msteveb !
