### ISSUE TITLE
mutt_error, mutt_message and mutt_perror are NULL

### ISSUE THREAD

**Issue by fekir** [neomutt/neomutt#1072]
## bug reports

* Expected behavior: If the config file contains a line with an error, report an error message
* Actual behavior: crash (on cygwin)
* Steps to reproduce: create a neomuttrc with an invalid line and start neomutt
* Used program versions: reproducible with 20180223 and 20171215
* Operating System and its version: Windows 10

It seems to be a cygwin specific issue, since on debian the program seems to works correctly.

While debugging the issue, I noticed that `p mutt_error` displays `(void (*)(const char *, ...)) 0x0`, and `p default_error` prints `No symbol "default_error" in current context.`.

I've compiled neomutt with following additional flags: `-g -O0`

**Comment by fekir** [comment]
Following sample
````
// main.c
#include "func.h"
int main(){
	func("hello");
	return 0;
}
// func.h
void (*func) (const char *message);
// func.c
#include <stdio.h>
static void default_func(const char *message){puts(message);}
void (*func)(const char *) = default_func;
````
indicates that gcc seems to work correctly, since the program did not crash and print hello world.

neomutt uses a similar routine (pointers to static functions), for registering three functions for displaying error messages (see `mutt/message.h` and `mutt/message.c`)

Used version of gcc:  6.4.0

**Comment by fekir** [comment]
Following lines seems to hint that `mutt/messages.c` is correctly compiled and linked to neomutt:

````
...
cc -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR -I. -I. -Wall -g -O0 -MT mutt/message.o -MD -MP -MF mutt/message.Tpo -c -o mutt/message.o mutt/message.c
...
ar cr libmutt.a mutt/base64.o mutt/buffer.o mutt/charset.o mutt/date.o mutt/debug.o mutt/exit.o mutt/file.o mutt/hash.o mutt/idna.o mutt/list.o mutt/mapping.o mutt/mbyte.o mutt/md5.o mutt/memory.o mutt/message.o mutt/mime.o mutt/parameter.o mutt/regex.o mutt/sha1.o mutt/signal.o mutt/string.o mutt/rfc2047.o
ranlib libmutt.a
...
cc -o neomutt.exe mutt_account.o addrbook.o alias.o attach.o bcache.o body.o browser.o buffy.o color.o commands.o complete.o compose.o compress.o conststrings.o copy.o curs_lib.o curs_main.o edit.o editmsg.o enter.o envelope.o filter.o flags.o from.o group.o handler.o hdrline.o header.o help.o history.o hook.o init.o keymap.o main.o mbox.o menu.o mh.o muttlib.o mutt_address.o mutt_socket.o tags.o mx.o newsrc.o nntp.o pager.o parse.o pattern.o pop.o pop_auth.o pop_lib.o postpone.o query.o recvattach.o recvcmd.o rfc1524.o rfc2047.o rfc2231.o rfc3676.o address.o safe_asprintf.o score.o send.o sendlib.o sidebar.o mutt_signal.o resize.o smtp.o sort.o state.o status.o system.o thread.o url.o version.o libmutt.a libncrypt.a libimap.a libconn.a -L/usr/local/lib  -lidn -lncursesw -lintl -liconv
...
````
As far as I saw, there where no errors, warnings or additional informations during these steps.

No strip is taking place after compiling.


The output of `nm libmutt.a | grep error` is
````
                 U regerror
0000000000000008 C mutt_error
0000000000000008 C mutt_perror
                 U strerror
0000000000000008 C mutt_error
0000000000000008 C mutt_perror
0000000000000000 t default_error
00000000000000c0 t default_perror
0000000000000000 D mutt_error
0000000000000010 D mutt_perror
                 U strerror
0000000000000008 C mutt_error
0000000000000008 C mutt_perror
0000000000000008 C mutt_error
0000000000000008 C mutt_perror
                 U regerror
0000000000000008 C mutt_error
0000000000000008 C mutt_perror
````

to provide a comparison, this is the output I get on debian (no stripping too)

````
                 U regerror
0000000000000008 C mutt_error
0000000000000008 C mutt_perror
                 U strerror
0000000000000008 C mutt_error
0000000000000008 C mutt_perror
0000000000000000 t default_error
000000000000017a t default_perror
0000000000000000 D mutt_error
0000000000000010 D mutt_perror
                 U strerror
0000000000000008 C mutt_error
0000000000000008 C mutt_perror
0000000000000008 C mutt_error
0000000000000008 C mutt_perror
                 U regerror
0000000000000008 C mutt_error
0000000000000008 C mutt_perror
````

Since all values between debian and cygwin are equals (except the value of default_perror), I guess that they are fine.


On the other hand, this is the output of `nm neomutt.exe | grep error` (cygwin)

````
0000000100512470 r .rdata$.refptr.mutt_curses_error
00000001005124a0 r .rdata$.refptr.mutt_perror_debug
0000000100512470 R .refptr.mutt_curses_error
00000001005124a0 R .refptr.mutt_perror_debug
0000000100527bd4 I __imp_perror
0000000100527c34 I __imp_regerror
0000000100527d1c I __imp_strerror
00000001004e63d0 T imap_error
000000010045300b T km_error_key
000000010042059d T mutt_clear_error
0000000100420e14 T mutt_curses_error
00000001005252a0 B mutt_error
00000001005252a8 B mutt_perror
000000010042207f T mutt_perror_debug
0000000100421f10 T mutt_show_error
000000010046e230 t nntp_connect_error
00000001004ea570 T perror
000000010048b68c t pop_error
00000001004ea620 T regerror
0000000100483f97 t report_regerror
00000001004ea7f0 T strerror
````

and of `nm neomutt | grep error` (debian)

````
00000000000cbf72 t default_error
00000000000cc0ec t default_perror
                 U ferror@@GLIBC_2.2.5
                 U gai_error@@GLIBC_2.2.5
                 U gai_strerror@@GLIBC_2.2.5
00000000000f20a7 T imap_error
000000000006465c T km_error_key
000000000003389d T mutt_clear_error
000000000003410b T mutt_curses_error
000000000032c778 D mutt_error
000000000032c788 D mutt_perror
00000000000354be T mutt_perror_debug
000000000003535c T mutt_show_error
000000000007e86e t nntp_connect_error
                 U perror@@GLIBC_2.2.5
000000000009a726 t pop_error
                 U regerror@@GLIBC_2.2.5
00000000000933e6 t report_regerror
                 U strerror@@GLIBC_2.2.5
````

There are many differences, from what I can see, (please correct me if I'm wrong)  on cygwin `mutt_error` is 0-init, whereas on debian not.

**Comment by flatcap** [comment]
We haven't changed how we build the library in ages.
When did it last work?

> on cygwin mutt_error is 0-init, whereas on debian not

Hmm... I've found one difference in the code.
Those three variables (function pointers) are missing `extern`.
Try:
```diff
-void (*mutt_error)  (const char *format, ...);
-void (*mutt_message)(const char *format, ...);
-void (*mutt_perror) (const char *message);
+extern void (*mutt_error)  (const char *format, ...);
+extern void (*mutt_message)(const char *format, ...);
+extern void (*mutt_perror) (const char *message);
```

**Comment by fekir** [comment]
As always, great hints.
Adding extern fixed the issue, neomutt did not crash.

AFAIK it never worked on cygwin, unfortunately I did not make any typo in my config when I built it last time.

Will you update the code or should I make a PR?
And would it make sense to make a new (micro-)release to order to fix this bug in cygwin?

Interesting though, that this issue seems to be only present on cygwin and not other platforms.

**Comment by flatcap** [comment]
> Interesting though, that this issue seems to be only present on cygwin and not other platforms.

@gahr and I did find some slight differences at link time, but we thought we'd got them all.

> Will you update the code or should I make a PR?

I've pushed the fix to master.

> And would it make sense to make a new (micro-)release to order to fix this bug in cygwin?

For one commit for one platform...?  I'd rather not, but...
How is the Cygwin build specified?
- Tag? - I could create a neomutt-20180223-cygwin tag
- Commit Hash? - Use fc690bff
- Branch? - I could create a temporary distro/cygwin branch

**Comment by fekir** [comment]
The cygwin build file takes a link to a source zipped file, so it would be great if there would be an official download link.
It is surely possible to patch the "old" release with this new commit, or maybe also use tags or commit hashes, I do not know how (yet), I'll try to see in the guidelines if I can find something.

I know that cygwin is a minor platform, I'm probably still the only user :-), but if someone want's to try it it will give a bad impression if it crashes because of the configuration file.
Since I did not notice it all this time, it might also not be that important, but I'm still a beginner, so my configuration file is very minimal and simple.

I think in the meantime we can close this issue since you already updated master, right?

**Comment by flatcap** [comment]
> The cygwin build file takes a link to a source zipped file

GitHub automatically generates a `.tar` and a `.zip` for all tags.
- https://github.com/neomutt/neomutt/releases/tag/neomutt-20180223
- https://github.com/neomutt/neomutt/archive/neomutt-20180223.zip

Plus I, sign the releases and post the .sig files
- https://github.com/neomutt/neomutt/releases/download/neomutt-20180223/neomutt-20180223.zip.sig
- More details: https://www.neomutt.org/dev/signing

I've just pushed a tag "neomutt-20180223-cygwin", so you can adjust the links above.

> I think we can close this issue since you already updated master

If you're happy, then yes please do.

**Comment by fekir** [comment]
> GitHub automatically generates a `.tar` and a `.zip` for all tags.

Great, did not know it, I thought it was a separate process.
