### ISSUE TITLE
index_format: right justification does not work correctly

### ISSUE THREAD

**Issue by ernix** [neomutt/neomutt#1074]
This might be related to https://github.com/neomutt/neomutt/issues/113

## bug reports

* Expected behavior
```
  F 12/15 11:39 To kojima@inter (  10) hello
```

* Actual behavior
```
  F 12/15 11:39 To kojima@inter (  10) hello- [#   ]>
```

* Steps to reproduce
```
set index_format = "%Z %[%b/%d %H:%M] %-15.15L %?y?[%4.4y]&(%4c)? %s%?M? %\\>- [#%03M]?"
```

Send email with `Subject: hello` to yourself.

* Used program versions
```
$ mutt -v
NeoMutt 20180223
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type `neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type `neomutt -vv' for details.

System: Darwin 16.7.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libiconv: 1.11
hcache backends: tokyocabinet

Compiler:
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Configure options: --prefix=/usr/local/Cellar/neomutt/20180223 --with-ssl=/usr/local/opt/openssl --gss --disable-idn --notmuch --sasl --tokyocabinet --with-ui=ncurses

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/Cellar/neomutt/20180223/include -DNCURSES_WIDECHAR -I/usr/local/opt/openssl/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen -futimens +getaddrinfo
  -gnutls -gpgme +gss +hcache -homespool -idn -locales_hack -lua +meta
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color
  +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/Cellar/neomutt/20180223/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/Cellar/neomutt/20180223/etc"

To learn more about NeoMutt, visit: http://www.neomutt.org/
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

Thanks!

* Operating System and its version
```
$ uname -a
Darwin kojiMac.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64 i386 iMac14,2 Darwin
```

**Comment by gahr** [comment]
Are you perhaps looking for this instead?

`"%Z %[%b/%d %H:%M] %-15.15L %?y?[%4.4y]&(%4c)? %s %>-%?M?[#%03M]?"`

I don't think you can have right-justification inside a conditional.

**Comment by ernix** [comment]
@gahr 
Thank you for your reply.

I'm sure that both of original mutt and previous version of neomutt can describe right-justification inside a conditional.  As @flatcap mentioned in https://github.com/neomutt/neomutt/issues/113#issuecomment-312594428, neomutt needs brackets to be escaped though.

You can see what I expects using original mutt.

```
set index_format = "%Z %[%b/%d %H:%M] %-15.15L %?y?[%4.4y]&(%4c)? %s%?M? %>- [#%03M]?"
```

* Folding threads:
```
  F 12/15 11:39 To kojima@inter (0.1K) hello -------------------------------------------------------------- [#002]
```

* When I unfold them:
```
  F 12/15 11:39 To kojima@inter (0.1K) hello
  F  2/27 09:06 To kojima@inter (0.1K) └*>
```

**Comment by flatcap** [comment]
hi @ernix,

Yes, you're right, something's wrong.
The new format works as you want:
```
set index_format = "%Z %[%b/%d %H:%M] %-15.15L %?y?[%4.4y]&(%4c)? %s%<M? %>- [#%03M]>"
```
but the old format doesn't
```
set index_format = "%Z %[%b/%d %H:%M] %-15.15L %?y?[%4.4y]&(%4c)? %s%?M? %>- [#%03M]?"
```

Internally, it's escaping the `>` in the `%>-` sequence.
This bug was introduced in 39a488d (#1001).

@cyphar Would you mind taking a look.  Thanks.

**Comment by cyphar** [comment]
Alright, so the solution isn't *that* bad, but the problem is that we'd need to handle all expandos in the string (effectively we need to have a way to skip expandos so that we don't look at the them in the loop that does the conversion). The trivial (incorrect) solution would be to just handle `%>X`, because there are other formats like `%{...}` or even fun ones like `%|>` that we need to handle too.

**Comment by flatcap** [comment]
@cyphar 

> so the solution isn't _that_ bad

Yeah, _nearly_ perfect :-)

I put in a nasty one-liner fix (to test things) -- `if (p[-1] == '%')`
Clearly that might under-run, but the solution's (hopefully) fairly simple.

**Comment by flatcap** [comment]
@cyphar Any progress?

**Comment by cyphar** [comment]
At the moment I can't see a way of implementing it without factoring out the expando parsing code entirely. I started working on this but it's quite a lot of changes -- the other option is to do the "simple" thing for now and make it better later...

**Comment by flatcap** [comment]
OK, thanks for looking.
I'll have think, too.
