### ISSUE TITLE
Question: Mutt and NeoMutt

### ISSUE THREAD

**Issue by evelikov** [neomutt/neomutt#1075]
Hi all,

AFAICT NeoMutt originally started as a way to consolidate all the outstanding [non-upstream] Mutt patches. Sort of how wine-staging it is to wine - see [1].

Yet it seems like these days NeoMutt is a proper fork, which rarely (?) pulls from upstream Mutt.
I looked around for some information behind the fork - be that technical, infra, political, other reasons. Can anyone share a link?

Seemingly the main/original NeoMutt developer @flatcap has contributed to Mutt, plus the latter has moved to git. I would love to contribute to the project, although doing the same work twice does not sound too productive.

Or in Tl;Dr: What would it take to merge Mutt and NeoMutt together?

Thanks

[1] https://wine-staging.com/
[2] https://gitlab.com/muttmua/mutt/

**Comment by flatcap** [comment]
Hi @evelikov,

Thanks for your questions.

Starting at the end...

> What would it take to merge Mutt and NeoMutt together?

A change of leadership for Mutt.

> AFAICT NeoMutt originally started as a way to consolidate all the outstanding
> [non-upstream] Mutt patches.

NeoMutt started after my attempts to contribute to Mutt failed.

I liked the idea of Mutt being the "Vim" of the email world, but the code is an awful mess.
Twenty years of neglect -- a lack of design and poor coding practices.

I decided that I could make a difference to Mutt -- I like a challenge :-)

I started with simple fixes, but many times I was rejected.
It felt like they were unwilling to be helped.

After months of this, I decided that I might be able to help by sorting out the patches.
There were lots of them and they were used by many distros.
This would reduce the duplication of work and simplify the distros' maintenance job.

Thus, NeoMutt -- a patchset

The more I tidied, fixed and improved, the more I realised that Mutt was an obstacle to change.
Finally, I gave up maintaining the separate patches and decided to try "fixing" Mutt, too.

Two years later we've become a small team who have made lots of improvements to the code.
There's still a long way to go, though, to make NeoMutt into a modern application.

> [NeoMutt] rarely (?) pulls from upstream Mutt

Not true.  I manually apply **all** of upstream's commits (fairly soon after they land).

The source formatting and layout of the two projects is now radically different.
This makes a simple merge impossible.

Upstream have adopted a few of our ideas/features.
In these cases, I've changed NeoMutt's config/behaviour to match upstream.
This is a slight inconvenience to NeoMutt's users, but is important for inter-operability.

> Yet it seems like these days NeoMutt is a proper fork

Yes, NeoMutt is a fork of Mutt.
That's the simple, understandable, answer.

But, it's where I disagree with some of my fellow NeoMutt friends :-)
As we take all of Mutt's changes, we're effectively an **extension** of Mutt.
A fork would have unique changes on both branches.

> I looked around for some information behind the fork
> be that technical, infra, political, other reasons.

A while back I detailed **ALL** the differences between the two: https://www.neomutt.org/changes/

The political reason is that Mutt is resistant to change.
This probably contributed to a long "dry" period when there was little development.
Their current maintainer, Kevin, is doing a better job of trying to encourage new development.

But many feel that Mutt is still too slow, too conservative.

> What would it take to merge Mutt and NeoMutt together?

Going back to this question...

Here's a plan that would bring the two projects much closer together.

- Reformat the source using `clang-format`
- Unify the naming of:
  * Variables
  * Functions
  * etc
- Group similar functions by file
- Adopt our library functions

The majority of these changes are cosmetic -- we've tidied and documented the code to make it easier to understand.
Making these changes would:
- Massively reduce the differences in the source
- Have no impact on the Mutt users
- Have little risk to the stability of Mutt

> I would love to contribute to the project,

We'd love you to help.
We'll encourage you to help.
We'll help you help us.

Another difference between the projects.

> although doing the same work twice does not sound too productive.

Perfectly understandable.

For anything small, then you could submit it to Mutt and NeoMutt will adopt it.
If you have the ambition to add something great, then NeoMutt's the place for you.

I hope this helps.
Rich (@flatcap)

**Comment by evelikov** [comment]
Thanks for the elaborate answer.

Some specific answers follow:

>> [NeoMutt] rarely (?) pulls from upstream Mutt

> Not true. I manually apply all of upstream's commits (fairly soon after they land).
> The source formatting and layout of the two projects is now radically different.
> This makes a simple merge impossible.

Right, the different layout got me confused there.

> A while back I detailed ALL the differences between the two: https://www.neomutt.org/changes/

I've read through this page over two dozen times - it's beating around the bush, a lot.

> Here's a plan that would bring the two projects much closer together.

Now we're talking...

> Reformat the source using clang-format
> ...
> The majority of these changes are cosmetic -- we've tidied and documented the code to make it easier to understand.

Sure, consistent style is great, but it tends to be biggest bikeshedding topic out there.
I think, I've seen a few cases where NeoMutt changes the existing coding style without much justification. If you're truly ready to more forward, please be expected that not all of those will be merged.

WRT my contribution ... my first attempt is to get the two projects together. I've opened a similar tread on Mutt's tracker [1] . Hopefully both sides will see value and make small compromises for the greater good.

[1] https://gitlab.com/muttmua/mutt/issues/12

**Comment by flatcap** [comment]
> WRT my contribution ... my first attempt is to get the two projects together.

Wow!  You like a challenge!

> > Reformat the source using clang-format

> Sure, consistent style is great, but it tends to be biggest bikeshedding topic out there.

Mutt's code has a very loose style: two space indent, {}s on new lines, but it's very poorly followed.

We actually held off from formatting our source for a long time.
When we did, we chose clang-format settings to most closely match the majority of the Mutt code.
Our developers would have preferred different settings.

Source files have been clang-formatted
Headers have been tided by hand to allow alignment of constants, etc

> I think, I've seen a few cases where NeoMutt changes the existing coding style without much justification.

On the whole, I think we're fairly faithful to Mutt's ideal.
Feel free to point out any specific examples and I'll try to explain any changes we've made.

> If you're truly ready to more forward, please be expected that not all of those will be merged.

They weren't prepared to accept a patch to delete trailing whitespace.
They said they'd fix it as the code was changed.

In practical terms, this means that large parts of the code will never be tidied, documented, reviewed unless they go wrong.

Meanwhile, we've been tidying and renaming things quite aggressively:
If we have config item "apple_banana" then the global variable is called AppleBanana -- no exceptions.
We also unified the names of functions and their parameters.

Each change we make means that it's easier for a new coder to understand.

Plus documentation: https://www.neomutt.org/code/mutt.html

> I've opened a similar tread on Mutt's tracker.

Subscribed

Be aware: Some of the Mutt devs have been openly hostile to NeoMutt.

> Hopefully both sides will see value and make small compromises

It's still possible for the two projects to be reunited, but that chance is getting smaller each day.

We're 2000 commits ahead of Mutt.
We're developing faster than they are.
We have big changes due soon and still more planned.

If we were magically synchronised today, then in six months time the gap would have opened again.

Mutt needs to change at the top.

Accepting a few code changes isn't enough.
They need to be more _accepting_ of change.

> for the greater good

The Mutt community isn't that big.
I regret having to split it with NeoMutt, but I just didn't see any way forward with Mutt.

Judging by the response to NeoMutt, the users want to see change.

**Comment by evelikov** [comment]
Thanks for the input. small suggestion though:

I can see that this is rather sore topic, but please try to keep if brief and on point.
Quite often such huge volume is off-putting, regardless how accurate they are.

**Comment by flatcap** [comment]
Thanks for playing.  Bye!

**Comment by evelikov** [comment]
Playing? It's a bit sad if you truly see it as such.

@flatcap you're quite ambitious and perhaps tad too eager to fix Mutt. To the point that you did not see that topics like coding style are too political and not something focus on. Esp. if you're not a well established contributor or have handful of other successful projects under your belt.

Sure Mutt devs/dev. process might need an improvement, but your call for leadership change seems unjustified and arrogant. The wider community did not agree with your cosmetic proposals.

Sincerely hope that you'll read this in a constructive way and learn to work with people who disagree with you.

HTH
Emil

**Comment by d-k-c** [comment]
You may think that coding style is somehow a political topic, but for many of us picking a coding style and be consistent about it is a way to remove distractions and make the codebase more welcoming to newcomers, a way to say "hey look, we care enough about code quality to fix that little thingie".

I share flatcap's opinion for a leadership change. My reasons are pretty much the same as his, as I hit the same wall when I tried to contribute to Mutt. So you may think that his call for a change is unjustified and arrogant, but fact is that Neomutt is an open and welcoming community thanks to him. Basically, this project is about accepting to make major changes to the codebase in order to move forward, not keeping it in such an obscure state that only one person can make contribution.

If Mutt wants to keep being conservative that's very much okay, but then you must understand that Mutt and Neomutt will always have different goals, and that it goes way deeper than just coding style.

**Comment by evelikov** [comment]
As one gets a few years of experience with a project, let alone maintaining it they starts to see things most clearly.

The newcomers that take feedback seriously produce better quality code and stick around. Many that push for ground breaking or questionable changes quickly run out of steam and disappear... Even if their work gets merged with no questions asked.

Project leader/maintainer should know how to balance between the two and unlike others they should learn quickly.

Everything said - let's bury this topic. Please?

**Comment by hringriin** [comment]
May I politely ask, whether there is a real difference between those two programmes for the users? I have both installed and really cannot tell :-/
What i _can_ tell is, that neomutt kindly mentioned some warnings according some of my keybindings, but, I'm afraid, that is really it, at least from my point of view.

Regards.
