### ISSUE TITLE
Entire UI locks up while downloading IMAP messages

### ISSUE THREAD

**Issue by wrycode** [neomutt/neomutt#1081]
I'm putting this as a feature request, although it's listed as a bug here:
https://dev.mutt.org/trac/ticket/663
on mutt's old bug tracker. I'm aware that neomutt's current code organization might not allow for this to be fully fixed, based on some refactoring talk I saw on other issues.

## Why do you not like the current state?
When reading IMAP emails, if I open an email with a large attachment like a pdf:
- mutt immediately downloads the entire message, attachment included
- I cannot view the actual text (or html) email message until all attachments are downloaded
- the UI locks up completely so I can't switch to another email or anything. There's probably an escape key to cancel the download, or I can use Ctrl^C to exit mutt. For me this is unsatisfactory.

Often when I'm reading these emails, I never intend to download the large attachments anyway, or not immediately. 

I'd like to add that neomutt's header and message caching feature works great (thank you!) so I can view the message later without lag, even after closing mutt. But it's still annoying to have to randomly stop my whole workflow while mutt downloads some pdf I don't intend to read anyway.
## What would you like to see to change?
There are different ways to handle this, but I think the following config options would do nicely:
- set a maximum attachment size to download automatically, otherwise the download has to be initiated manually
- or set a filetype to ignore unless the user initiates the download manually

**Comment by gahr** [comment]
There was an attempt to do this in #786. Do you mind if I close this as duplicated?

**Comment by wrycode** [comment]
Yes, sounds good. I didn't see that issue when I looked through earlier.
