### ISSUE TITLE
test/rfc2047.c doesn't check setlocale return value and requires extra dep

### ISSUE THREAD

**Issue by aradici** [neomutt/neomutt#1088]
the test incorrectly assumes that the setlocale() call succeeds, but if it fals the test will fail when decode is called.

**Comment by aradici** [comment]
Also, probably a better patch is to use the locale provided by libc-bin, which does not require any extra dependency.

**Comment by aradici** [comment]
Patch available here: https://salsa.debian.org/mutt-team/neomutt/blob/master/debian/patches/neomutt-devel/0006-default-setlocale-to-C.patch

**Comment by gahr** [comment]
`C.UTF-8` does not exist on BSDs. How about trying `en_US.UTF-8` first and `C.UTF-8` as a fallback?

**Comment by flatcap** [comment]
Fixed by fee6fb6f
