### ISSUE TITLE
feature-request - make index_label take support pattern

### ISSUE THREAD

**Issue by antognolli** [neomutt/neomutt#109]
index_label is listed in the docs as both a color "object" and "index-object", and if I understood correctly,  index-object's are supposed to support pattern matching. But if I try something like:

`color index_label green default '!~y muted'`

I get the following error:

```
Error in /home/antognolli/mutt-offline, line 78: too many arguments
source: errors in /home/antognolli/mutt-offline
```

**Comment by flatcap** [comment]
Sorry, no, `index_label` doesn't take a pattern.
For now, I'll update the docs to make it a bit clearer.

index-color will get some improvements in the future, since it's becoming quite popular.

**Comment by antognolli** [comment]
Sounds good, thanks for clarifying. It would be a cool feature, but not a must have one.

**Comment by flatcap** [comment]
Sorry, this enhancement didn't attract someone to write some code.
This issue will now be closed, but listed on the [Closed Discussions](https://www.neomutt.org/dev/discussions) page.
