### ISSUE TITLE
unwatched mailboxes in the sidebar

### ISSUE THREAD

**Issue by tecepe** [neomutt/neomutt#1092]
Hi,

I was talking to flatcap in the irc channel about this idea and he suggested to me to bring it to github for discussion. If the solution is not very complicated, I'm thinking to volunteer myself for this job. 

The situation is the following: I use the sidebar mostly to make the access easier to mail folders that I don't need to access them often enough to have a binding, which is the case of my Trash and Drafts folders (for example). When I postpone or delete a message, mutt will notify me some minutes later (mail_check, sync, I'm not sure...) that there is a new message in the Trash folder, which is a complete useless notification.

I was thinking if we could have a mechanism to add folders to the sidebar that is different from the `mailboxes` command, which would avoid the folders of being watched by mutt. In my case, those folders don't need to be updated. flatcap's comment was the following:

> flatcap: a new command, a flag on the folder, and 6 places where the new mail command, or beep on new is called
> flatcap: that would be a simple solution.  not pretty.

I hope to hear from you guys soon. Thank you very much for your hard work.

**Comment by flatcap** [comment]
The goal is to prevent certain folders from notifying the user.

The simple solution is:
- Add a new command to `Commands` in `init.h`
- Add a flag to `struct Buffy` (the folder)
- Change `curs_main.c`, `pager.c` to prevent notification if the flag is set

That would work, but it seems very specific.
If we think up a new folder option, we'd need another command (which wouldn't be combinable).

The `mailboxes` command takes any number of arguments, so we can't simply add a flags field.
We _could_ encode the flags.  Perhaps:
```
mailboxes =folder1(flag1) =folder2(flag2,flag3)
```

At some point, soon, I was planning to add a "named" mailboxes command, which would allow the user to pick a display name for each folder.  Perhaps we want:
```
named_mailbox =folder ["Display Name" [flags]]
```

**Comment by tecepe** [comment]
Thanks for your answer, @flatcap . I believe named_mailbox command with extra flags is very nice idea. I have tried to set the displayed name of a mailbox in the past, but I concluded that mutt didn't offer support for that.

**Comment by MaskRay** [comment]
I want a `new_mail_command` that only send out notification when the mail `To:` or `CC:` me. Will that scenario be covered by the feature?

**Comment by flatcap** [comment]
@MaskRay Probably not.

The new mail command was a simple feature.
By the time it finds out there was new mail, it doesn't know where that mail is (or where it came from).

I'll have another look (but no promises).

**Comment by flatcap** [comment]
Hi @tecepe

As discussed on IRC, here's what we'd like you to create,
and some note on how to do it.

Thanks :-)

## Challenge

Add a new command to set flags/attributes of a mailbox.
Initially, we'll set the name and create a "do-not-disturb" flag.

```
mailbox_flags MBOX { [-+]FLAG[=VALUE] }
```

The mailbox may be in either full form `imaps://...`, or abbreviated `=INBOX`
The flags are space separated and may be prefixed with `+` or `-` and they may have a value `=VALUE`

e.g.

```
mailbox_flags =neo.devel name="Neo Development" -notify
```

## Code

### Command

NeoMutt's commands are defined in the `Commands` array in `init.h`
All of the command handlers, in `init.c` work the same way.
They're given a `struct Buffer` with a string in it.

You can parse the string using `extract_token()` and `MoreArgs()` and the usual C libraries.
There's plenty of examples you can cut'n'paste.

### Folders

The folders are represented by `struct Buffy` -- don't ask :-)
There are functions to canonicalise the mailbox name and get a pointer to the folder.

The `Buffy->desc` is already used by Notmuch as a pretty name, so we can do the same.
If you write to this, it should show up in the sidebar.
We'll need to define some flags and add a flags field to `Buffy` too.

### Notifications

The mail index is handled by `mutt_index_menu()`
The notifications are handled by `BeepNew()` and `NewMailCommand`.

The pager is handled by `mutt_pager()`
The notifications are the same here.

### Other Stuff

NeoMutt's code is still pretty confusing -- lots of oddly named things and poor design.
So, ask lots of questions (either here, or on IRC).

I've created a branch on our neomutt repo.
If you send me your email address, I'll grant you access to commit directly.
(Working on our repo makes collaboration easier)

Thanks again,
@flatcap / rich@flatcap.org

**Comment by flatcap** [comment]
Moving this to the long-term wish list.
