### ISSUE TITLE
status color can't do overlapping matches

### ISSUE THREAD

**Issue by towo** [neomutt/neomutt#1093]
I was trying to go a bit fancy with status bar coloring, but it seems the logic is a bit too straightforward for complex situations (tbh: trying to wedge powerline style segments in there).

The issue can be boiled down to the following:
You cannot have a string twice in any form of matching for `color status`.

Let `set status_format = " NeoMutt | %f | %MM %nN %oO %dD %tT | %s>%S %?V?| %V &?%> %P"`; then:

```
color   status            red        color179      'NeoMutt (.)' 1
color   status            color22    color148      'NeoMutt' 1
```

leads to the pipe being red and the 'NeoMutt' string at default coloring. And:

```
color   status            red        color179      'NeoMutt (.)' 1
color   status            color22    color148      '(NeoMutt)' 1
```

leads to only 'NeoMutt' having the green coloring specified, pipe still at default.

Expected behaviour, of course, would be NeoMutt in green and the pipe in red at the same time.

**Comment by flatcap** [comment]
Hmm... My first thought was WWVD?  What would Vim do?

Basic syntax matches are greedy:
- Match that starts **earliest in the line wins**
- When multiple matches start at the same place, the **longer match wins**

That's the limit for (neo)mutt.

Even in Vim it's tricky to get this behaviour.
`contains` will work:

```vim
syntax match green "NeoMutt "
syntax match red   "NeoMutt | " contains=green
```

It might be possible to fake it with clever choices of characters and non-overlapping colours.
