### ISSUE TITLE
Avoid line breaks in pager to let terminal emulator recognize URLs

### ISSUE THREAD

**Issue by marak8** [neomutt/neomutt#1099]
If there's a long line in pager, NeoMutt inserts a line break at the end of the line. This makes it impossible for the terminal emulator (such as xfce4-terminal) to recognize whole URL and make it clickable. Options `smart_wrap` and `markers` make no difference.

There were other reports in past:
http://mutt-users.mutt.narkive.com/hBmCoxDU/pager-avoid-line-breaks-in-urls
https://bugs.launchpad.net/ubuntu/+source/mutt/+bug/574747

HTML email is bad, but vast majority of online services today send long links in HTML mail, for example password resets.

**Comment by marak8** [comment]
So, it looks like this is a bigger issue
  https://joeyh.name/blog/entry/personal_wishlist___35__304211/

**Comment by flatcap** [comment]
The wrapping settings can make it hard to cut'n'paste a URL from the screen, but NeoMutt can't rely on the terminal to wrap the string -- it might overwrite the sidebar, the status bar, etc.

Recently, I did some experiments with the URL escape sequence.
It's not universally supported, but it should be ignored by lesser terminals.
Note: screen and tmux seem to interfere with it.

See [link-seq.sh](https://github.com/neomutt/test-ansi/blob/master/link-seq.sh) and [lorem.sh](https://github.com/neomutt/test-ansi/blob/master/lorem.sh) in https://github.com/neomutt/test-ansi
Also the 'lolcat' branch of https://github.com/neomutt/neomutt-old

As for adding it to NeoMutt...

When the text is being prepared for the screen we'd have to find, save and mark all the URLs.
This is already done for the syntax highlighting, so it shouldn't be too hard.

Each URL would get a separate ID and each **part** of the URL that's visible would be tagged with the full URL.

I'm busy, but I can mentor a volunteer.

**Comment by floand** [comment]
For me function `<pipe-message>` to pager `less` do the rare job.

**Comment by toogley** [comment]
Workaround: https://www.neomutt.org/contrib/useful-programs#grabbing-urls

**Comment by marak8** [comment]
@toogley I'd not call this workaround. When you get an password reset email, there are often several URLs that don't fit terminal width. You just can't pick the correct URL without content around. @floand solution is what I do though I first pipe it to Perl script which picks first `text/plain` entity. I haven't had time to checkout @flatcap 's work on this yet.

**Comment by toogley** [comment]
@marak8 As far as i understand the desired endresult is to have that url open in your browser. The suggested tools can do that, even for really long URL's. And, for instance, urlscan also provides some context in the message.

**Comment by marak8** [comment]
@toogley Not quite. The desired end result is open *the correct URL* in my browser. I've tried urlscan but it's less than satisfying. I've hard time to orientate in the results. Compare this experience with following links on page in browser with Vimium or even without it. The point here is not to waste time and energy consumed by your brain cells on workarounds. I'm not ranting about NeoMutt, I'm just replying to your comment.

**Comment by alex3kov** [comment]
A lot of news websites and stores send notification about new items in freakishly long URLs. It's a pain to assemble them by hand. Completely agree with @marak8, would be very good to have them clickable from inside neomutt.

**Comment by gahr** [comment]
```sh
% ldd /usr/local/bin/irssi | grep ncurses
        libncurses.so.8 => /lib/libncurses.so.8 (0x80268b000)
```

**Comment by ailin-nemui** [comment]
ok let me clarify it is only using the terminfo part of curses, not the curses screen drawing functions which do end up inserting line breaks

**Comment by antoyo** [comment]
Is this fixed?
If it's not, could we rely on the terminal for newlines to print the URLs when the sidebar is hidden?
What I usually do in terminal applications to click on URLs is to hide the sidebars.

**Comment by flatcap** [comment]
No. Nor is it likely to be fixed before the big colour overhaul, when we can implement the correct escape sequences.  Then the terminal will know the extent of the url.

Note: With so few active developers, this could be years away.

The terminal will only see ONE url, if the text is printed as one continuous string.
Curses won't allow that, it'll truncate the string at the window boundary, so the string gets printed in separate pieces.

If you hide the sidebar, you can still cut'n'paste the url (clumsy, I know) or use urlview/urlscan.

**Comment by ManuGraiph** [comment]
What's the status of this 6 years after? I have the same issue, my urls are being cut adding a '+' symbol at each breakline making it very hard for any terminal feature to get them.

**Comment by flatcap** [comment]
@ManuGraiph 
Still not implemented.
Note, you can hide the `+`s with the config: `set markers = no`

NeoMutt has had a lot of big improvements since this issue was first opened,
but few people have the time, skills and determination to overhaul the Pager.

Currently, top of my todo list is to break the dependencies between the GUI and the backends (Mailboxes).
After that, I may tackle the Pager.

**Comment by ManuGraiph** [comment]
Thanks a lot! I'm just coming back to `neomutt` after a couple months living with `aerc`.
