### ISSUE TITLE
Folders periodically switching places in sidebar

### ISSUE THREAD

**Issue by alexpearce** [neomutt/neomutt#11]
Firstly: this repo is a wonderful effort, thank you for your hard work! My apologies that my first interaction is reporting a problem.

I've modified the [Homebrew formula for mutt](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mutt.rb) to use neomutt, adding the `--enable-sidebar` flag to the call to `./prepare`. The build succeeds, but when I start mutt the first and last folders in the sidebar switch periodically:

![Folder switching](https://cloud.githubusercontent.com/assets/540853/14344973/d4f2ac48-fcaa-11e5-9fa8-5a7e98319b06.gif)

The periodicity seems to take the value of `timeout`, which is set to 3 in my `muttrc`.

I thought the sidebar might be trying to sort the folders by itself, rather than the order defined in the `mailboxes` setting, but setting `sidebar_sort_method = "unsorted"` doesn't change the behaviour (as expected, really, as [the README](https://github.com/neomutt/neomutt/blob/fba0ecd82522c2eacb1aaa70044cae5a77c93acf/README.sidebar) says that “Unsorted isn't” is a known bug).

I usually define my mailboxes by using `tree` and `sed` to scan my Maildir for folders, manually inserting `+gmail/INBOX` before this scan so that it appears at the top of my folder list. For the purposes of debugging this problem, I just define them by hand:

```
mailboxes \
  "+gmail/INBOX" \
  "+gmail/archive" \
  "+gmail/Family" \
  ...
```

If I have only the following mailboxes defined, no folder switching occurs:

```
mailboxes \
  "+gmail/INBOX" \
  "+gmail/archive" \
  "+gmail/FIFO" \
  "+gmail/Family" \
  "+gmail/GitHub" \
  "+gmail/House"
```

If I add one extra folder, the switching occurs:

```
mailboxes \
  "+gmail/INBOX" \
  "+gmail/archive" \
  "+gmail/FIFO" \
  "+gmail/Family" \
  "+gmail/GitHub" \
  "+gmail/House" \
  "+gmail/L"
```

But now it's `INBOX` and `Family` that switch, not the first and last folders! 😄 

My only thought is that "L" follows "I" alphabetically, so maybe that somehow triggers the switching. It I move `INBOX` to come just before `L`, I still see switching, but now it's `archive` and `GitHub` that switch (so still the same indices). So, it's probably not that.

What could be causing this behaviour?

**Comment by flatcap** [comment]
@alexpearce 

> this repo is a wonderful effort, thank you for your hard work!

You're welcome.

> My apologies that my first interaction is reporting a problem.

Not a problem.  Thanks for the very detailed bug report.
I have **no idea** what's going on :-)
I shall investigate.

**Comment by flatcap** [comment]
@alexpearce 
It seems that the sidebar was sorting when it shouldn't have been.
Please try this version:
    https://github.com/neomutt/neomutt/tree/issue/11
    https://github.com/neomutt/neomutt/archive/issue/11.zip

**Comment by alexpearce** [comment]
It does indeed fix the problem 🎉 Thanks very much!

There appears to be a new problem now, that I can't use `<sidebar-prev>`. I have these bindings:

```
bind index,pager <down>   sidebar-next
bind index,pager <up>     sidebar-prev
bind index,pager <right>  sidebar-open
```

`<down>` and `<right>` work as before, but `<up>` appears to be a no-op.

Note that I moved from revision fba0ecd (neomutt-20160404) to revision 7f89df1 (the issue/11 branch), so the regression may not have been introduced by 7f89df.

I can open a new issue for that, or I can try using various other revisions to see when the problems appears, if that would be useful?

**Comment by flatcap** [comment]
@alexpearce 
By stopping the sorting, I accidentally stopped the folder linking.
The new commit should be perfect :-)

**Comment by alexpearce** [comment]
Oh yeah! Nice one 👍

**Comment by alexpearce** [comment]
Perhaps just one final thing while I have your attention 🙇 

When I select a folder in the sidebar with `sidebar-open`, the message counts on folders, except the one I open, go to zero. I think this is because I have multiple accounts and switch between them with macros like this:

```
macro index ,c "<change-folder>+gmail/INBOX<enter>" "change accounts"
```

and then I have folder hooks like this:

```
folder-hook gmail/* source ~/.mutt/accounts/gmail
```

In `~/.mutt/accounts/gmail` I do several things like changing `sendmail`, but I also clear the list of mailboxes with `unmailboxes *` and then set them up again with `mailboxes ...`. This is so only the mailboxes of the 'current account' show in the sidebar.

I think it's the `unmailboxes *` function that clears the message counts in the sidebar, even when I change to folder that belongs to the account I'm already on (the `folder-hook` is called regardless).

So: what I'm wondering is if there's a `sidebar-refresh` function I can call to manually refresh the mailbox counts. I could reduce the `sidebar_refresh_time` to something very small, but that will lead to unnecessary disk reading. It would be ideal if I could manually invoke the sidebar refresh, adding it to my `folder-hook`, then I can keep `sidebar_refresh_time` to something like 60 seconds.

Does such a function exist?

**Comment by flatcap** [comment]
@alexpearce 

> Does such a function exist?

Unfortunately, not.  I've added it to my (long) list of things to do.

What changes did you make to the homebrew script?
Would you be willing to investigate getting NeoMutt accepted into HomeBrew?

Rich.

**Comment by alexpearce** [comment]
Here's the diff, with respect to [the mutt formula](https://github.com/Homebrew/homebrew-core/blob/48e96ec08b3e686b5ed4bdfa4117dd97fee926c7/Formula/mutt.rb), for using the `issues/11` branch:

```diff
1,31c1,5
< # Note: Mutt has a large number of non-upstream patches available for
< # it, some of which conflict with each other. These patches are also
< # not kept up-to-date when new versions of mutt (occasionally) come
< # out.
< #
< # To reduce Homebrew's maintenance burden, new patches are not being
< # accepted for this formula. We would be very happy to see members of
< # the mutt community maintain a more comprehesive tap with better
< # support for patches.
<
< class Mutt < Formula
<   desc "Mongrel of mail user agents (part elm, pine, mush, mh, etc.)"
<   homepage "http://www.mutt.org/"
<   url "https://bitbucket.org/mutt/mutt/downloads/mutt-1.5.24.tar.gz"
<   mirror "ftp://ftp.mutt.org/pub/mutt/mutt-1.5.24.tar.gz"
<   sha256 "a292ca765ed7b19db4ac495938a3ef808a16193b7d623d65562bb8feb2b42200"
<
<   bottle do
<     revision 2
<     sha256 "5bb0c9590b522bbcc38bfecaf0561810db2660792f472aa12a3b6c8f5e5b28d7" => :el_capitan
<     sha256 "8cad91b87b615984871b6bed35a029edcef006666bc7cf3b8f6b8b74d91c5b97" => :yosemite
<     sha256 "c57d868588eb947002902c90ee68af78298cbb09987e0150c1eea73f9e574cce" => :mavericks
<   end
<
<   head do
<     url "https://dev.mutt.org/hg/mutt#default", :using => :hg
<
<     resource "html" do
<       url "https://dev.mutt.org/doc/manual.html", :using => :nounzip
<     end
<   end
---
> class Neomutt < Formula
>   desc "Bringing together all the Mutt code"
>   homepage "http://www.neomutt.org/"
>   url "https://github.com/neomutt/neomutt.git", :revision => "b3a4f10ae09", :branch => "issue/11"
>   version "20160404"
40a15,16
>   conflicts_with "mutt", :because => "both install mutt binaries"
>
44a21
>   option "with-sidebar-patch", "Apply sidebar patch"
96a74
>     args << "--enable-sidebar" if build.with? "sidebar-patch"
```

Running `brew audit --strict --online neomutt` gives:

```
==> brew style neomutt

1 file inspected, no offenses detected

==> audit problems
neomutt:
 * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)

Error: 1 problem in 1 formula
```

We need more friends 😄

[NeoVim](https://neovim.io) has [it's own repo for its Homebrew formula](https://github.com/neovim/homebrew-neovim). Neomutt could do something similar.

**Comment by flatcap** [comment]
Thanks, for the diff.

> NeoVim has it's own repo for its Homebrew formula. Neomutt could do something similar.

Good find.  I'll set up the repo.  If you're happy with their licence, then you can cut'n'paste most of the repo into ours (including the travis config).

> * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
> We need more friends

That's hilarious.
We're well on the way for the watchers and stars.
As for the forks, that could be tricky.  The whole point of the project is to avoid them!

Cheers,
  Rich

**Comment by alexpearce** [comment]
I laughed 😄 

I think the idea with counting forks is to gauge how much external contribution the software gets. People fork, then make PRs to have their changes merged back in to the original.

The license in neovim/homebrew-neovim is fine by me. I'll get the homebrew-neomutt repo set up shortly.

**Comment by ElDeveloper** [comment]
> we need more friends

I think r/vim would be happy to hear about this repo.

**Comment by alexpearce** [comment]
Interesting. Perhaps we should open an issue on ‘launching’ neomutt to increase the visibility? Things looks in pretty good shape already 💪

**Comment by flatcap** [comment]
@ElDeveloper @alexpearce 

> open an issue on ‘launching’ neomutt to increase the visibility?

To collect publicity ideas?  If you wish.
I don't have any social media accounts, so I have little to offer.

For the next release I was planning to announce it on the mutt-users mailing lists.
There are about 1300 people there.

>  Things look in pretty good shape already

Yes they do :-)
