### ISSUE TITLE
UI lockup during stream of error messages

### ISSUE THREAD

**Issue by Austin-Ray** [neomutt/neomutt#1100]
* **Expected behavior**
Responsive UI when a stream of error messages occurs. 
For example, the ability to exit an email quickly via the `q` command while a stream of "Bottom of message is shown" occurs because I was distracted while scrolling down.

* **Actual behavior**
UI locks up when a stream of error messages appears. This prevent subsequent commands from being executed until all error messages have had a chance to appear for 1 second. A git bisect revealed that this behavior was introduced in commit 3e1070ec2a3d1616b8073e660d0459e0be3a7fe8.

* **Steps to reproduce**
 1. Open an email 
 2. Go to the bottom of email
 3. Try to scroll past the bottom so that "Bottom of message is shown" appears
 4. Continuing trying to scroll past the bottom for several seconds (even pressing `j` twice introduces noticeable delay)
 5. Press `q` to exit email
 6. Observe the delay between pressing `q` and exiting the email

* **Used program versions**
NeoMutt 20180223-127-e41a68 (I use the Arch AUR's `neomutt-git` package)

* **Operating System and its version**
Arch

**Comment by flatcap** [comment]
OK, I see what's happening.
I introduced a pause after an error message.
Holding down <kbd>j</kbd> causes a LOT of <kbd>j</kbd>s to fill the input buffer.
That means a LOT of error messages separated by a 1 second pause -- NeoMutt DoS!

I'll put in a check to see if we've got the same error message as before.

**Comment by iliastsi** [comment]
I get the same behavior with the `next-new-then-unread` function on the latest release (NeoMutt 2018-05-12) where this is supposed to be fixed.

**Steps to reproduce:**

1. Press `<Tab>` 5 or more times in the browser, in a folder with no new messages
2. NeoMutt reports `No urnead messages.`
2. Press `j` and observe the delay between pressing `j` and moving to the next message.

Should I open a new bug report for this?

**Comment by gahr** [comment]
This is due to this other message coming up and resetting the timeout:

https://github.com/neomutt/neomutt/blob/af45147b3a3065ac239b2a465fc72e0baf5255d3/curs_main.c#L2403

**Comment by gahr** [comment]
6fe268f fixes this.
