### ISSUE TITLE
sleep after every error makes navigation frustrating

### ISSUE THREAD

**Issue by mrajner** [neomutt/neomutt#1108]
# Description
I move in index view keeping  `j` to scroll down, and when I hit the end the information `You are on last message.` is shown as en error. So the terminal freezes for second or more (accidentaly keeping `j` way too long makes any operation impossible).

I was able to bisect the commit which introduced this problem 3e1070ec2a3d1616b8073e660d0459e0be3a7fe8

I can understand the rationale for longer showing the error, but It probably should not freeze the neomutt. And this example which I provided is not even an error but information message.

**Comment by flatcap** [comment]
Thanks, it's being worked on in #1100 

@royger suggested that those should even **be** error messages.
There's a release due on Friday and this **will** be fixed by then.
