### ISSUE TITLE
nm_hidden_tags: unknown variable on latest version

### ISSUE THREAD

**Issue by edi9999** [neomutt/neomutt#1111]
I have just updated neomutt from : 

```
v1="20170912"
```

to 

```
v2="20180323"
```

Since then, When I start neomutt, I get the message : 

```
Error in /home/edgar/.muttrc, line 14: nm_hidden_tags: unknown variable
source: errors in /home/edgar/.muttrc
```

This worked well in v1.

I didn't find in the changelog (https://github.com/neomutt/neomutt/blob/master/ChangeLog.md) that this option has been deprecated.

* Expected behavior -> It should work as before
* Actual behavior -> Fails with the above error
* Steps to reproduce -> 

Add 

```
# This variable specifies private notmuch tags which should not be printed
# on screen (index, pager).
set nm_hidden_tags = "unread,draft,flagged,passed,replied,attachment,signed,encrypted"
```

to your muttrc

* Used program versions -> shown above
* Operating System and its version -> Fedora release 27 (Twenty Seven)

**Comment by flatcap** [comment]
Ah!  That happened when we made the labelling/tagging more generic.

The Notmuch-specific **nm_hidden_tags** is now **hidden_tags**
(and works on IMAP, too)

Sorry about the lack of notification.

**Comment by edi9999** [comment]
Ok, thanks for the fast reply !
