### ISSUE TITLE
Question: status flag "forwarded"

### ISSUE THREAD

**Issue by theova** [neomutt/neomutt#1114]
Hello there,

first of all: thank you very much for your great work! Neomutt is my daily mail client and I wouldn't like to change it!

Is there a status flag "forwarded" in the index? I would like to have a flag "f" like "r" (replied) "s" (signed) to see if I have already forwarded an email. Is this possible so far?

Best regards

**Comment by flatcap** [comment]
hi @theova 

> thank you very much for your great work

You're welcome.

> Is there a status flag "forwarded" in the index?

No.  It seems that forwarding an email doesn't affect the original.

Maildir supports a 'P' (Passed) flag for forwarded emails.
That would be fairly simple to add.

IMAP doesn't seem to have a default 'forwarded' flag,
but if the server supports custom flags, then we could add one.

**Comment by theova** [comment]
> Maildir supports a 'P' (Passed) flag for forwarded emails.
That would be fairly simple to add.

As I'm using neomutt with offlineimap and maildir, this would be very nice.

I don't know much about mail syncing, so unfortunately I can't help you to extend neomutt. 
But I would like to test it :-)

**Comment by flatcap** [comment]
Moving this to the long-term wish list.
