### ISSUE TITLE
save-hook matching on subject ignored

### ISSUE THREAD

**Issue by agx** [neomutt/neomutt#112]
While I have several save hooks mathing on ~C and ~t on recipients
working nicely, matching on the subject does not work:

    save-hook '~s Pkg-libvirt-maintainers' +foo

does not use 'foo' as default folder when the message subject contains
Pkg-libvirt-maintainers although it should according to:

  http://www.mutt.org/doc/manual/#save-hook →
  http://www.mutt.org/doc/manual/#pattern-hook →
  http://www.mutt.org/doc/manual/#patterns

**Comment by flatcap** [comment]
Hmm... This is strange.  `save-hook` should work on a subject pattern
(and NeoMutt hasn't changed how Mutt handles the save hook).

The first test I did was with:
```
save-hook '~s Pkg-mutt-maintainers' +foo
```

This works as expected.  So, two obvious questions:
- Are you sure that config is being used?
- Is some other hook taking precedence?

Any more information you can find out would help.

**Comment by agx** [comment]
Hmm...I readded the hook in the very same location of my .muttrc and it works now, no idea what changed. Thanks for confirming that it should work, this obviously helped my mutt to believe in itself.
