### ISSUE TITLE
Autocrypt support for subject line and headers

### ISSUE THREAD

**Issue by micressor** [neomutt/neomutt#1121]
I have: 
- [X] searched open and closed issues for duplicates -  Found this #741 
- [X] I have read https://github.com/neomutt/neomutt/blob/master/CONTRIBUTING.md

----------------------------------------

It would be great if NeoMutt would support [Autocrypt](https://autocrypt.org/) for encrypting and decrypting emails using GnuPG/PGP.

Especially the encryption of the subject line - [Memory Hole Protected E-mail Headers](https://github.com/autocrypt/memoryhole).

**Comment by flatcap** [comment]
Hi @micressor 
Unfortunately the situation hasn't changed since that issue.

It's still a reasonable idea.
We're still a small project
We still have few developers.
