### ISSUE TITLE
Support variables "or" conditional

### ISSUE THREAD

**Issue by hsanson** [neomutt/neomutt#1128]
## feature requests

I use notmuch labels with virtual mailboxes in neomutt and it works beautifully.  But displaying the large amount of labels makes the already complex index_format even more difficult to manage. 

* Why do you not like the current state?

I have labels that exclude each other (e.g. inbox, trash, spam). I show either of the three labels if present with  priorities trash > spam > inbox.  To do this using conditionals:

```
tag-formats = "inbox"   "Gi" \
              "deleted" "Gk" \
              "spam"    "Gs"

set index_format = " %<Gk?%Gk&%<Gs?%Gs&%<Gr?%Gr&%1Gi>>>"
```

This works but there is a lot of repeating the same tag-format and the mental map needed to avoid mistakes is huge. This is just a simple example. I have lot more labels for the different services I use (aws, gcloud, docean, youtube, calendar, etc.) and these are also exclusive so I only show one of them if present. My full index format looks like this now:

```
"%2M %<Gk?%Gk&%<Gs?%Gs&%<Gr?%Gr&%1Gi>>> %<GA?%GA&%<GG?%GG&%<Gg?%Gg&%<Gy?%Gy&%<Gc?%Gc&%<GR?%GR&%<Gz?%Gz&%<Ga?%Ga&%1Ge>>>>>>>> %<[y?%<[m?%<[d?%[%-5H:%M]&%[(%-1a)%2d日]>&%[%-5b%2d日]>&%[%y年%b]> %-20.20n %<Y?[%Y]&(%4c)> %s"
```
This configuration ensures a fixed number of labels in the index so the column indentation does not get all messed when a message has lots of labels. 

And this is how it looks on my terminal:

![mutt-screen](https://user-images.githubusercontent.com/900716/38341630-81fc691e-38b4-11e8-8f8c-6d6eefccbdf3.png)

* What would you like to see to change?

Would be nice if we could have "or" conditions. So instead of this:

    %<Gk?%Gk&%<Gs?%Gs&%<Gr?%Gr&%1Gi>>>

We could write:

    "%<%Gk|%Gs|%1Gi>"

That would show the Gk label if present, or Gs if present or Gi if present or a blank space if none is present.

For larger cases the complexity is greatly reduced:

    %<GA?%GA&%<GG?%GG&%<Gg?%Gg&%<Gy?%Gy&%<Gc?%Gc&%<GR?%GR&%<Gz?%Gz&%<Ga?%Ga&%1Ge>>>>>>>>

Becomes

    %<GA|%GG|%Gg|%Gy|%Gc|%GR|%Gz|%Gz|%1Ge>

Once this issue and #243 are solved, managing complex index formats would become way more easier. This is what I want to be able to do in the near future:

````
set index_format = "%2M " 
set index_format += "%<%Gk|%Gs|%Gi>"
set index_format += "%<GA|%GG|%Gg|%Gy|%Gc|%GR|%Gz|%Gz|%Ge> "
set index_format += "%<[y?%<[m?%<[d?%[%-5H:%M]&%[(%-1a)%2d日]>&%[%-5b%2d日]>&%[%y年%b]>"
set index_format += "%-20.20n "
set index_format += "(%4c) "
set index_format += "%s"
```

**Comment by flatcap** [comment]
Moving this to the long-term wish list.
