### ISSUE TITLE
index_format not compatible to mutt

### ISSUE THREAD

**Issue by hagenw** [neomutt/neomutt#113]
I don't know if this is a bug or intended behavior, but there is a difference between mutt and neomutt.

In `.muttrc` I have the following line:

``` config
set index_format="%4C %Z %{%b %d} %-15.15L (%?l?%4l&%4c?) %?M?<%M> ?%s"
```

which should add a `<#number_of_messages_in_thread>` to collapsed threads.
Under `Mutt 1.5.24 (2015-08-30)` it displays the messages like this:

```
 394 r + Aug 16 Name1 Name2   (0,5K) <4> Re: Test
 398 r + Aug 16 Name1 Name2   (0,4K) Test2
```

Under `Mutt 1.6.2-neo (2016-07-23)` it displays the messages like this instead:

```
 394 r + Aug 16 Name1 Name2   (0,5K) <4 > Re: Test
 398 r + Aug 16 Name1 Name2   (0,4K)  >Test2
```

**Comment by flatcap** [comment]
Ah, I see.

The [nested-if patch](http://www.neomutt.org/feature/nested-if/) is interfering with your format.
It introduces the `%< >` format so that you can nest conditions.

For now, you have two choices: different wrapper, or some ugly escaping:
```
set index_format="%4C %Z %{%b %d} %-15.15L (%?l?%4l&%4c?) %?M?[%M] ?%s"
set index_format="%4C %Z %{%b %d} %-15.15L (%?l?%4l&%4c?) %?M?\<%M\\> ?%s"
```

This might take a little thought, and time, to fix.

**Comment by hagenw** [comment]
Thanks, I updated my config.

If this is not going to be fixed, it would be a good idea to update the [manual section](http://www.neomutt.org/manual/reference.html#index-format) accordingly, so that the user knows that `%< >` has a special meaning.

**Comment by flatcap** [comment]
> If this is not going to be fixed

Don't know, yet.  If the user starts a conditional with `$?` it should be possible to allow `<>` _unescaped_.  I'll need to have a good think about all the possibilities.

> update the manual section ... so that the user knows that `%< >` has a special meaning.

I'll do that.  I'm not sure anyone understands the [nested if](http://www.neomutt.org/feature/nested-if/) page anyway.  It was **really** hard to document.

I'll leave this bug open until I've done _something_.

**Comment by demradum** [comment]
Since Debian started introducing neomutt patches this stopped working for me:

`folder-hook "." 'set index_format="$my_rcdir/bin/trimi \"<<%S>>%?M?+& ?%-22.22F │ %s\"|"'`

cat trimi:

`echo "$1" | sed 's/^<<\*>>/*/ ; s/^<<.>>/ /'`

**Comment by mgedmin** [comment]
Another surprised user here with
```
set index_format="%4C%?M?+& ?%Z %[%m-%d] %-15.15F %?M?<%4M>&(%4c)? %s" 
```
which is somehow automagically transformed to
```
index_format="%4C%<M?+& >%Z %[%Y-%m-%d %H:%M] %-15.15F %<M?<%4M>&(%4c)> %s"
```

It would be nice if the bit of code that rewrites `%?x?y&z?` to `%<x?y&z>` would automatically escape `>` inside `y` and `z`.

**Comment by guyzmo** [comment]
@flatcap:
> I'll leave this bug open until I've done *something*.

have you thought of *something* yet? :)

**Comment by flatcap** [comment]
**Update**: I've made some changes.

- If you use the old nested format, Mutt won't change `$index_format` for you
- Updated the docs to explain that angle brackets `<>`s need to be escaped if they occur in a nested-if

I looked at automatically escaping `<>`s if they occurred in an old format string.
Unfortunately, it wasn't going to be an easy job and it would have risked breaking people's `index_format`
