### ISSUE TITLE
Feature request: IMAP labels from multiple mailboxes on the sidebar

### ISSUE THREAD

**Issue by fedejko** [neomutt/neomutt#1131]
Hi,

It would be great if the user could display IMAP labels from different accounts on the sidebar.

This way we could move around folders from different mailboxes without using folder hooks.

Thanks & regards
Darek

**Comment by flatcap** [comment]
Hi @fedejko.

Currently, as you've found, it's not possible.

There are two problems:
- There's no "description" field for the mailboxes
- "$folder" is global to all mailboxes

I'm working on a fix, but unfortunately my time is spread pretty thin.

First, is a new config system (to the users it will be identical).
Next is a new account system.  This will allow account-specific variables.

The goal is a config file like:
```
account Gmail
    set folder   = imaps://imap.gmail.com:993
    set realname = "Richard Russon"
    mailboxes =INBOX =family =friends
    ...

account Work
    set folder   = imaps://linux.com
    set realname = "Rich (FlatCap) Russon"
    mailboxes =INBOX =project1 =project2
    ...
```

This would make configuring NeoMutt simpler and remove the need for
account-/folder-hooks.

**Comment by fedejko** [comment]
Hi,

Thank you for the clarification. Such config file would be most welcome!

Wish you luck with the fix.

Regards
Darek
