### ISSUE TITLE
[Bug] Whitespace in attachment confuses mutt

### ISSUE THREAD

**Issue by RichiH** [neomutt/neomutt#114]
I got an email including an attachment with whitespace in its name, say `file name.pdf`. I looked at said attachment and all was well. I then wrote an email and attached said file, again with the whitespace in its name. I tried to look at it before sending to make sure it was the correct one and mutt opened okular (KDE PDF viewer) for both `~/file` and `name.pdf`, neither of which obviously worked.

**Comment by flatcap** [comment]
That sounded easy to test...  But I can't reproduce it.
I thought it might be a quoting problem in the `mailcap` file.

If I receive `file name.pdf` Mutt replaces the space with an underscore for the filename in /tmp.
If I create an email and attach `file name.pdf`, I get the same result: `/tmp/file_name.pdf`

What is your pdf line of your mailcap?

**Comment by RichiH** [comment]
I was honestly surprised that such a bug would live more than a few weeks, so I assumed I had something weird in my `.mailcap`, alas:

````
~ % cat .mailcap
text/html; w3m -I %{charset} -T text/html; copiousoutput;
~ % 
````

**Comment by flatcap** [comment]
Something's odd.

If the file's text, Mutt will try to display it in the pager.
Otherwise, it calls `mutt_sanitize_filename()` before calling the mailcap handler.
If you don't have a handler, then there's probably one in /etc

Try forcing the issue:

**~/.mailcap**
```
application/pdf; okular %s;
```

**~/.muttrc**
```
set mailcap_path = ~/.mailcap
```

**Comment by RichiH** [comment]
Will do in a few. JFTR, on Debian testing, I have:

````
 ~ % grep -i pdf /etc/mailcap
application/pdf;            okular '%s';        nametemplate=%s.pdf;      test=test "$DISPLAY" != ""
application/x-pdf;          okular '%s';        nametemplate=%s.pdf;      test=test "$DISPLAY" != ""
application/x-gzpdf;        okular '%s';        nametemplate=%s.pdf.gz;   test=test "$DISPLAY" != ""
application/x-bzpdf;        okular '%s';        nametemplate=%s.pdf.bz2;  test=test "$DISPLAY" != ""
application/pdf; okular %s --icon okular -caption Okular; test=test -n "$DISPLAY"
application/x-gzpdf; okular %s --icon okular -caption Okular; test=test -n "$DISPLAY"
application/x-bzpdf; okular %s --icon okular -caption Okular; test=test -n "$DISPLAY"
image/pdf; /usr/bin/display-im6 %s; test=test -n "$DISPLAY"
image/pdf; /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16/display %s; test=test -n "$DISPLAY"
application/pdf; gimp-2.8 %s; test=test -n "$DISPLAY"
image/pdf; display-im6 'pdf:%s'; test=test -n "$DISPLAY"
 ~ % 
````

**Comment by toogley** [comment]
@RichiH is this still relevant for you?

**Comment by RichiH** [comment]
Will confirm tomorrow.

Richard

Sent by mobile; excuse my brevity.

**Comment by flatcap** [comment]
We tried, at the time to repeat this, but failed.
If it happens again, please re-open this issue.

**Comment by knarrff** [comment]
I just came across this, and give the last comment, I'll reopen.

I also did what was originally reported:
- create new email
- attach file with name containing spaces
- try to open that attachment from within mail creation view (email not sent yet), using <ENTER>.

In my case this is a .docx file, and mailcap redirects that to libreoffice:

soffice --nologo --writer '%s'

This is what I see using 'ps -www':

sh -c soffice --nologo --writer ''/home/knarf/file with spaces.docx''

Note: these are not a single " character, but two '' characters.

What happens next can be repeated from the command line using

soffice --nologo --writer ''/home/knarf/file with spaces.docx''

and is: soffice complains about not finding each of the separate components of the name individually: the two ' characters begin and immediately end the quotation.

So it seems that something is quoted twice using single quotation marks, negating that quotation.

**Comment by knarrff** [comment]
As it turns out, I cannot reopen this issue. Could please someone with the rights do so, or I'll have to report this as new bug.

**Comment by knarrff** [comment]
Scratch that, and sorry for the noise. For any future reference: the problem seems to be the MailCap file itself, and mutt seems to do the right thing. For more information, see here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=928037

**Comment by Knusper** [comment]
Sorry for making more noise @knarrff - do you know how one could workaround this, I am also on debian and this hits me from time to time... So I probably have to change something in my ~/.mailcap file?

**Comment by knarrff** [comment]
Yes, for instance, on Debian, /etc/mailcap contains the line

    application/vnd.openxmlformats-officedocument.wordprocessingml.document; soffice --nologo --writer '%s'; edit=soffice --nologo --writer '%s'; test=test -n "$DISPLAY"; description="Office Open XML Document"; nametemplate=%s.docx

This is wrong, as the %s is already quoted. It is the task of the program providing the content of %s to quote that if necessary, not the task of the mailcap entry. Thus, I have in my ~/.mailcap:

    application/vnd.openxmlformats-officedocument.wordprocessingml.document; soffice --nologo --writer %s; edit=soffice --nologo --writer %s; test=test -n "$DISPLAY"; description="Office Open XML Document"; nametemplate=%s.docx

**Comment by Strahinja** [comment]
I'm experiencing this issue with Artix/Arch neomutt package version 20201127-1 (`neomutt -v` gives "NeoMutt 20201127"). My mailcap has:

```
application/msword; /usr/bin/xdg-open %s; nametemplate=%s.docx
application/vnd.openxmlformats-officedocument.wordprocessingml.document; /usr/bin/xdg-open %s; nametemplate=%s.docx
application/*word*; /usr/bin/xdg-open %s; nametemplate=%s.docx
```

and I'm still getting the error about "no mailcap entry".
