### ISSUE TITLE
imap: some (already visited) messages are shown as empty by neomutt but not by mutt

### ISSUE THREAD

**Issue by l29ah** [neomutt/neomutt#1144]
Dunno really how to reproduce, it is correlated to imap reconnecting during the message view or something like that. Then it always show the message as totally empty, and `v` says `text/plain, 7bit, utf-8, 0`. It still shows in the list with its original header (caching issue?).

NeoMutt 20180323-90-193612

**Comment by ElDeveloper** [comment]
I've also seen this problem, haven't been able to isolate a way to reproduce it but I think it has something to do with the IMAP connection timing out.

**Comment by jfmoulin** [comment]
I am hit pretty badly by the problem. All problematic messages are from the same sender (but not all messages from this sender are affected). They were all quite large (some tens of kB to some MB) and had attachments. Before I try to read them a second time, the index shows the messages as having a non zero size. 
I tried to reload them by recreating my local mailbox, the problem persisted.
If the message have been read once, how could it be that it is correlated to an IMAP problem? Are the messages not stored locally anyway?

**Comment by flatcap** [comment]
Sorry I don't have time to investigate, but...
It sounds like the header cache is corrupt.

When you next see the problem, try:
- Delete the header cache (or rename it temporarily)
- Re-open the folder (e.g. `<sidebar-open>`
- Test the email again

Then, try again, fresh:
- Restart NeoMutt
- Open folder
- Test the email

Please, let me know the results.
They'll narrow down the source of the problem.

**Comment by jfmoulin** [comment]
Hi, 
I actually tried removing the header cache and this did not help.
What did help was to remove the bodies cache.
Unfortunately I tried only starting fresh. 

Oh, and thanks a lot for the time you invest in this project!

**Comment by l29ah** [comment]
Looks like the problem occurs when neomutt loses the IMAP connection before you ask it to open the mail. It then tries to reestablish it and returns an empty message.

**Comment by l29ah** [comment]
I can no longer reproduce it.

**Comment by roccoblues** [comment]
Trying to cleanup some older issues here. Can anyone comment if this issue still persists with the latest version? Thanks!
