### ISSUE TITLE
edit_headers and format=flowed (text_flowed=yes)

### ISSUE THREAD

**Issue by jmtd** [neomutt/neomutt#1146]
There is an unfortunate interaction between (neo)mutt's `edit_headers` and format=flowed emails, which can probably be simply fixed.

The headers injected into the buffer by `edit_headers` have a trailing space after them if they are empty (e.g. default for Cc) so if the editor you are using is configured to reflow text according to the format=flowed specification (e.g. vim with set fo+=aw), it will reflow the headers if you edit any of the unpopulated ones.

The fix would simply be to not include a trailing space on headers injected into the buffer by `edit_headers`.

**Comment by gahr** [comment]
Do I understand it correctly that this is causing annoyances only when modifying the headers in the editor? Headers are not automatically collapsed on save, right?

**Comment by jmtd** [comment]
That’s right.
