### ISSUE TITLE
Split up mutt_resize_screen()

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1149]
This is an "easy" task ([find more](https://github.com/neomutt/neomutt/issues?q=label:"good%20first%20issue")) and it's open to everyone.  [_read more..._](https://neomutt.org/dev/easy-tasks)

## Description

This function has both ncurses and slang code in it.  
As only one can be used at a time, this would be better as two functions surrounded by `#ifdef`.

### Part 1: Create ncurses version

Also, rename all the strange variables.

### Part 2: Create slang version

The variables here are globals from slang, so they need to keep their names.

**Comment by parazyd** [comment]
Do you really think it helps? Splitting up this function duplicates most of the code.

**Comment by flatcap** [comment]
Yes.  The two versions are mutually exclusive and behave differently.
The slang version uses **global variables** from slang,
and the curses version uses **local variables** with slang names.

**Comment by flatcap** [comment]
@parazyd 
Please can you create a pull-request with you changes, so far.
Thanks

**Comment by parazyd** [comment]
I haven't had time to test it yet. But I hope to soon.

**Comment by flatcap** [comment]
Ping?

**Comment by flatcap** [comment]
Please can we see some code?

**Comment by parazyd** [comment]
I'll rebase and open a pull request tomorrow :)
