### ISSUE TITLE
Default mailto_allow should include Cc, In-Reply-To, and References

### ISSUE THREAD

**Issue by joshtriplett** [neomutt/neomutt#115]
Mutt's default value for mailto_allow includes only Subject and Body.  I'd like to suggest changing the default to also include Cc, In-Reply-To, and References.

In-Reply-To and References allows mailing list archives to include mailto links that won't break threading.  Debian mailing lists and the Debian bug-tracking system include such links.  Cc allows those links to mail both the list and the author of the mail.

I don't see any obvious way that allowing those additional headers could cause harm, and I think allowing them by default would improve usability.

**Comment by P-EB** [comment]
Sure, that's a great idea!

Would you be ok to design a first patch? We'd be glad to help you browse the code.

**Comment by pali** [comment]
Hello, I suggest to add also `To` header into default allowed list.

When you want to prepare `mailto:` URI when recipient address would contain email address with name in phrase then you need to use syntax: `mailto:?To=Name <test@example.com>` as after `mailto:` can be only email address not name/phrase. Following URI is invalid: `mailto:Name <test@example.com>`.
