### ISSUE TITLE
Eliminate static variable in mutt_addr_mbox_to_udomain()

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1150]
This is an "easy" task ([find more](https://github.com/neomutt/neomutt/issues?q=label:"good%20first%20issue")) and it's open to everyone.  [_read more..._](https://neomutt.org/dev/easy-tasks)

## Description

`mutt_addr_mbox_to_udomain()` returns pointers into a static buffer.

### Part 2: Change the callers to `free()` the strings

There are three callers, all in `mutt/address.c` which will need changing.

**Comment by psyomn** [comment]
Hi, will be working on this! I'll start off by reading the code.

**Comment by flatcap** [comment]
Welcome to Neomutt, @psyomn.

> I'll start off by reading the code.

Good.  The library code in `mutt/` is all fairly tidy.
Feel free to ask lots of questions.

Thanks.

**Comment by psyomn** [comment]
Thanks. I don't think I have write permission on this repo, but my work should be relatively ready. I'll make PR regardless probably tonight. Thanks!
