### ISSUE TITLE
Script the deployment of Code Docs

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1152]
This is an "easy" task ([find more](https://github.com/neomutt/neomutt/issues?q=label:"good%20first%20issue")) and it's open to everyone.  [_read more..._](https://neomutt.org/dev/easy-tasks)

## Description

NeoMutt's uses Doxygen to generate documentation for its code.  
Specially-formatted comment blocks are turns into HTML and linked together.

- https://neomutt.org/code/pages.html

Currently, updating the docs is done by hand, but all the steps could easily be automated and given to Travis.

### Part 1: Clone necessary repos

There are three repos:

- https://github.com/neomutt/neomutt
  Source code.  Check out branch 'doxygen'

- https://github.com/neomutt/neomutt.github.io
  Website.  The `code` dir is a git submodule 

- https://github.com/neomutt/doxygen
  HTML docs.

### Part 2: Generate the docs

There are a few steps to generate the HTML docs (see `.travis.yml`) 
Scripts can be saved in the `.travis` directory.

### Part 3: Update the repos

- Delete all the files in the doxygen repo.
- Copy the docs from the neomutt repo's `html` directory to the doxygen directory.
- Commit those changes
- Commit the submodule change to the website repo

### Part 4: Push the results

To allow automatic pushing to GitHub, it's necessary to create an SSH key and give it permissions.  
This is documented, here:

- https://neomutt.org/dev/deploy

- Push the doxygen changes
- Push the website changes
- Wait patiently
- Check the results on the website

### Part 5: Test on Travis

Once everything's working, change `.travis.yml` to run the script and push everything to GitHub.

- https://travis-ci.org/neomutt/neomutt

**Comment by jamesbvaughan** [comment]
Hey I'm new and interested in working on this! I'm on vacation for the weekend so I probably won't get started before Monday.

**Comment by flatcap** [comment]
Welcome to NeoMutt, @jamesbvaughan 

Great!

This should be a fun one!
All the pieces are there, it just needs a bit of magic.

Feel free to ask lots of questions.

Thanks.

**Comment by jamesbvaughan** [comment]
@flatcap For something like this, is it better to put everything into a script (like "deploy-code-docs.sh") and call that from .travis.yml or to put all the steps directly in .travis.yml?

**Comment by flatcap** [comment]
I think a script (or family of scripts) would be best.
Travis works well when you have a matrix of test cases, but this situation is pretty linear.
Lots of small steps, many of which could fail (and stop the script).

**Comment by flatcap** [comment]
> Where is the .travis directory you mentioned?

The [doxygen] branch has a `.travis` dir, which is backed up in the management repo:
- https://github.com/neomutt/management/tree/master/doxygen

> Which .travis.yml are you referring to in Part 2?

The one in [doxygen] -- https://github.com/neomutt/neomutt/blob/doxygen/.travis.yml
Backup: https://github.com/neomutt/management/blob/master/doxygen/travis.yml

> I started writing a script

That's looking reasonable.
As you're recursively cloning the website, you get the doxygen repo for free as a submodule
Before running doxygen, there's a "prep" script that generates some "Tables of Content"
After running doxygen we need to check there were no warnings.

**Comment by flatcap** [comment]
Fixed by: https://github.com/neomutt/management/commit/0f0a4717b38c6e868d6420333f90c646a7ece1e9
