### ISSUE TITLE
Convert Aliases to use STAILQ

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1153]
This is an "easy" task ([find more](https://github.com/neomutt/neomutt/issues?q=label:"good%20first%20issue")) and it's open to everyone.  [_read more..._](https://neomutt.org/dev/easy-tasks)

## Description

Many NeoMutt structures implement their own linked-list type.  
The Aliases are simply stored as a long linked list.

~`STAILQ` is a singly-linked~
`TAILQ` is a doubly-linked list with pointers to both the head and the tail.  
It's defined in `mutt/queue.h`

### Part 2: Change all users to match

There are plenty of examples in NeoMutt's code of how to iterate through a list.  
~**Note**: When deleting items, use `STAILQ_FOREACH_SAFE()`~

@flatcap: updated:STAILQ -> TAILQ

**Comment by z2v** [comment]
I'll take this issue.

**Comment by flatcap** [comment]
Thanks.
Like the myvars, the alias also uses a singly linked list.
As @gahr points out it might be more efficient to change to a doubly-linked `TAILQ`.
(A user's less likely to `unalias` something, but the lists are much longer)
