### ISSUE TITLE
Convert Myvars to use STAILQ

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1154]
This is an "easy" task ([find more](https://github.com/neomutt/neomutt/issues?q=label:"good%20first%20issue")) and it's open to everyone.  [_read more..._](https://www.neomutt.org/dev/easy-tasks)

## Description

Many NeoMutt structures implement their own linked-list type.  
The Myvars are simply stored as a long linked list.

`STAILQ` is a singly-linked list with pointers to both the head and the tail.  
It's defined in `mutt/queue.h`

### Part 2: Change all users to match

There are plenty of examples in NeoMutt's code of how to iterate through a list.  
**Note**: When deleting items, use `STAILQ_FOREACH_SAFE()`

**Comment by z2v** [comment]
Hello, I would like to try to fix this issue.

**Comment by flatcap** [comment]
Welcome to Neomutt, @z2v 

That's great.

There are only three actions for the myvars:
- Add to the list
- Delete from the list
- Find an item in the list (for display/update)

There's some good example code (that can be cut'n'pasted) in `tags.[ch]`.

Have a look through the code and ask lots of questions.

Thanks.

**Comment by flatcap** [comment]
Wow, you're a quick study!
I'll have a closer look in the morning, but it looks very good.

One cosmetic change.
Please can you add `{}`s to the `FOREACH` macros
(clang-format can't deal with them otherwise)

Then, create a pull-request.
Thanks

**Comment by gahr** [comment]
The pull request is fine and addresses the issue mentioned. However, wouldn't it be better to use a hash table instead of a list?

**Comment by flatcap** [comment]
The only catch with a hash table is its fixed size.
We either have to overallocate, or risk the table filling up and degenerating into a linked list.

Do many people use myvars?
How many myvars are they likely to use?

**Comment by gahr** [comment]
Fair enough - let's keep a linked list until my_ gets more fashioned :)
