### ISSUE TITLE
Support for the IMAP CONDSTORE/QRESYNC extensions

### ISSUE THREAD

**Issue by paravoid** [neomutt/neomutt#1155]
At least in my setup, "Evaluating cache..." is pretty noticeable and can take dozens of seconds, especially on large mailboxes (100k+ messages).

[RFC 7162](https://tools.ietf.org/html/rfc7162) (and its predecessors) describe a couple of IMAP extensions that make resynchronization of mailboxes and flag changes faster and less resource intensive.

Currently, (neo)mutt issues a `UID FETCH 1:%u (UID FLAGS)` when using the header cache (`%u` = number of messages in the folder), which results in a separate line for each of the messages in the folder. In a mailbox with e.g. 100k messages, one gets these kind of bytes on the wire:
```
* 1 FETCH (UID 1 FLAGS (\Seen))
* 2 FETCH (UID 2 FLAGS (\Seen))
…
* 100000 FETCH (UID 100000 FLAGS (\Seen))
```
Assuming all emails in that folder are seen and no other flags are set (which is the best case scenario really), this amounts to 33-43 bytes per message, or ~4MB(!) of data downloaded just to open the folder, every single time one switches to that folder. Also note that Gmail takes ~30s to respond to such a query on a folder with that many messages here (and my internet connection is not the bottleneck).

As I understand it, with CONDSTORE support, a `(CHANGEDSINCE 12345)` would be added to the `UID FETCH` and would return only the changed flags vis-a-vis what the header cache has, which would result into a significant speed improvement and reduced bandwidth usage, especially in large and/or frequently accessed mailboxes.

Thunderbird's wiki has [some useful tips](https://wiki.mozilla.org/Thunderbird:IMAP_RFC_4551_Implementation). One of the ideas there is to potentially initially target only for the "single client" use case, as well as hacks (like message counts) to deal with CONDSTORE's expunged message limitations. QRESYNC should make this not being needed, but note e.g. Gmail supports only CONDSTORE and not QRESYNC :(

P.S. This was also filed as a [mutt upstream bug](https://gitlab.com/muttmua/mutt/issues/26).

**Comment by flatcap** [comment]
It's a nice idea, but...

> This was also filed as a mutt upstream bug.

Which means we'd be foolish to invest any time on it.
If upstream implement it, then NeoMutt will get the feature.
