### ISSUE TITLE
Update vim syntax highlighting for all new options

### ISSUE THREAD

**Issue by darnir** [neomutt/neomutt#116]
Existing syntax highlight files for Vim don't cover all the Mutt options currently.

We should update and provide a newer version. I'll create a branch later today against neomutt-dev and other vim users can start contributing

**Comment by flatcap** [comment]
I haven't checked **Vim**'s version against Mutt lately (it's probably out of date), but our features come with their own `vimrc` addons.  These should be combined into one big `vimrc` at compile time.

**Comment by flatcap** [comment]
I should also mention that all the docs and vimrcs are now in a 'docs' branch.
(merging `doc/manual.xml.head` was becoming a nightmare).

**Comment by darnir** [comment]
* Richard Russon <notifications@github.com> [160819 09:32]:
>I haven't checked **Vim**'s version against Mutt lately (it's probably out of date), but our features come with their own `vimrc` addons.  These should be combined into one big `vimrc` at compile time.
>
Like you say, it's all vimrc configurations. But none of them add the 
syntax highlighting rules.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/neomutt/neomutt/issues/116#issuecomment-240948623

-- 
Thanking You,
Darshit Shah

**Comment by flatcap** [comment]
All of them add the syntax highlighting rules.

Here's the neomutt-dev doc dir: https://github.com/neomutt/neomutt/blob/neomutt-dev/doc

Aren't the vimrc.* files what you're looking for?

**Comment by darnir** [comment]
* Richard Russon <notifications@github.com> [160819 09:32]:
>I haven't checked **Vim**'s version against Mutt lately (it's probably out of date), but our features come with their own `vimrc` addons.  These should be combined into one big `vimrc` at compile time.
>
I didn't know about these. That is exactly what I wanted. We need to 
package it better though and save it in contrib/
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/neomutt/neomutt/issues/116#issuecomment-240948623

-- 
Thanking You,
Darshit Shah

**Comment by flatcap** [comment]
> We need to package it better

Yes, we do :-)

Once it's checked we need to push it upstream to Mutt and Vim.

**Comment by flatcap** [comment]
FYI, Vim's muttrc.vim is up-to-date for Mutt-1.7.0
https://github.com/vim/vim/blob/master/runtime/syntax/muttrc.vim
