### ISSUE TITLE
Logs are rotated twice

### ISSUE THREAD

**Issue by z2v** [neomutt/neomutt#1160]
## bug reports

* Expected behavior
While starting logging system renames old logs (.neomuttdebug3 -> .neomuttdebug4, .neomuttdebug2 -> .neomuttdebug3, ...). After several runs with debugging there should be five files .neomuttdebug[0-4].

* Actual behavior
After several runs with debugging there are only three files: .neomuttdebug[0,2,4]

* Steps to reproduce
Run neomutt with debugging several times.
 
* Used program versions
NeoMutt-20180323-114-bc8636

* Operating System and its version
FreeBSD 12.0-CURRENT

## analyzing
Logging system is started twice:
* https://github.com/neomutt/neomutt/blob/master/main.c#L482
* https://github.com/neomutt/neomutt/blob/master/main.c#L549

So logs are rotated twice as well.

**Comment by z2v** [comment]
Simple demonstration.

* Apply patch

```
diff --git a/mutt_logging.c b/mutt_logging.c
index 94dc8322..7c93875b 100644
--- a/mutt_logging.c
+++ b/mutt_logging.c
@@ -117,6 +117,8 @@ static const char *rotate_logs(const char *file, int count)
   char old[PATH_MAX];
   char new[PATH_MAX];

+  printf("Start rotating logs....\n");
+
   /* rotate the old debug logs */
   for (count -= 2; count >= 0; count--)
   {
@@ -125,9 +127,13 @@ static const char *rotate_logs(const char *file, int count)

     mutt_expand_path(old, sizeof(old));
     mutt_expand_path(new, sizeof(new));
-    rename(old, new);
+    if (rename(old, new) < 0)
+      printf("Rename '%s' -> '%s' failed: %s\n", old, new, strerror(errno));
+    else
+      printf("Successfully renamed %s -> %s\n", old, new);
   }

+  printf("DONE.\n");
   return mutt_str_strdup(old);
 }
```

* Run neomutt, quit. Messages from console:
```
Start rotating logs....
Rename '/home/vovka/.neomuttdebug3' -> '/home/vovka/.neomuttdebug4' failed: No such file or directory
Successfully renamed /home/vovka/.neomuttdebug2 -> /home/vovka/.neomuttdebug3
Rename '/home/vovka/.neomuttdebug1' -> '/home/vovka/.neomuttdebug2' failed: No such file or directory
Successfully renamed /home/vovka/.neomuttdebug0 -> /home/vovka/.neomuttdebug1
DONE.
Start rotating logs....
Successfully renamed /home/vovka/.neomuttdebug3 -> /home/vovka/.neomuttdebug4
Rename '/home/vovka/.neomuttdebug2' -> '/home/vovka/.neomuttdebug3' failed: No such file or directory
Successfully renamed /home/vovka/.neomuttdebug1 -> /home/vovka/.neomuttdebug2
Rename '/home/vovka/.neomuttdebug0' -> '/home/vovka/.neomuttdebug1' failed: No such file or directory
DONE.
Debugging at level 2 to file '/home/vovka/.neomuttdebug0'
```

**Comment by flatcap** [comment]
Ah, yes.  Logging.  It's complicated :-)

1. When NeoMutt starts, we queue up the logs until we know where to save them.
2. After we've processed the command line, we might start logging.
   This allows us to catch problems while processing the config files, etc.
3. After reading all the config, we have a second chance to start the logging.
4. While running the user can `set debug_file = 'another'` and files will be rotated.

Would you be interested in having a look at the problem?

**Comment by z2v** [comment]
I'll take a look. Though not sure how to fix it properly.

**Comment by flatcap** [comment]
Don't spend too long on it.
If you don't see a simple fix, leave it for now and concentrate on the Alias conversion.
