### ISSUE TITLE
Refactor mktemp() to mkstemp()

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1165]
## Description

Many functions use temporary files as one-off storage space.

The old way of doing this was to call `mutt_mktemp()`.  It would return a unique
filename, which the caller would then create, open, use, close and delete.

Now, there's a new library function: `mutt_file_mkstemp()`.  It hides some of
the complexity.  The caller gets a `FILE*` pointer to use and they close it when
they're done.

A few examples of this change can be seen in commit e6cb06f38

There are a lot of calls to `mutt_mktemp()`, so that's a lot of duplicated code.

### Part 1

Find ten simple-looking callers of `mutt_mktemp()`

There are about 90 to choose from.  Most should be pretty simple.
If you find any that look complicated, put their details in a comment, below.

### Part 2

Convert each to use `mutt_file_mkstemp()`

**Comment by larsks** [comment]
>  If you find any that look complicated, put their details in a comment, below.

Well, the very first one I looked at is in `attach.c`:

```c
            mutt_mktemp(tempfile, sizeof(tempfile));
            FILE *tfp = mutt_file_fopen(tempfile, "w");
            if (!tfp)
            {
              mutt_perror(_("Failure to open file to strip headers."));
              mutt_file_fclose(&fp);
              goto bailout;
            }
            mutt_file_copy_stream(fp, tfp);
            mutt_file_fclose(&fp);
            mutt_file_fclose(&tfp);
            mutt_file_unlink(a->filename);
            if (mutt_file_rename(tempfile, a->filename) != 0)
            {
              mutt_perror(_("Failure to rename file."));
              goto bailout;
            }
```

It's complicated because it actually wants to rename the temporary file to replace the original file.  It still makes sense to fix this because the existing `mutt_mktemp_full` function is racy.  One option would be to have `mutt_file_mktemps` accept an optional string buffer parameter; if it's null, do nothing, if it's non-null, fill it in with the temporary filename.

You could even hide this behind a new macro, so that normal callers would use:

    #define     mutt_file_mkstemp() mutt_file_mkstemp_full(NULL, __FILE__, __LINE__, __func__)

And callers that want the filename would use:

    #define     mutt_file_mkstemp_name(buf) mutt_file_mkstemp_full((buf),  __FILE__, __LINE__, __func__)

**Comment by flatcap** [comment]
Yes, that's one of the tricky ones :-)

Ideally, there are two sort of temporary files: disposable and non-disposable.

`mutt_file_mkstemp()` provides the disposable ones.
If something goes wrong and the data is lost, it doesn't matter.

The non-disposable files are created by `mutt_mktemp()` by the compose screen, etc.
They have a longer lifespan and if neomutt were to crash, the user would probably like their work preserved.

**Comment by flatcap** [comment]
I've been looking through some of the `mutt_mktemp()` callers.
Hmm... there might be more awkward cases than I imagined.

**Comment by larsks** [comment]
So then I looked at `commands.c`, which is almost simple, except suddenly a wild function call appears:

```c
rc = mutt_pager(NULL, tempfile, MUTT_PAGER_MESSAGE, &info);                 
```

So here we need the filename just because we want to pass the content through a pager.  The solution here might be a version of `mutt_pager` that takes a file descriptor instead of a filename?

**Comment by larsks** [comment]
And the in `compress.c`, we also want the filename...

So I haven't come across a "simple" case yet :).

I really think everything would be easier if `mutt_file_mkstemp` didn't `unlink()` the file immediately, and instead returned **both** the filename and an open file descriptor.  We could have a `mutt_file_closetemp()` or something that would handle closing and deleting the file.

**Comment by larsks** [comment]
I've created #1176 which has a stub implementation of the suggestion from my previous comment.

**Comment by flatcap** [comment]
Thanks for investigating!

> So I haven't come across a "simple" case yet :).

hehe, \*\*\*\*!

> And the in compress.c, we also want the filename...

Hmm... in this case the user doesn't care about the temp file...

> ... a version of mutt_pager that takes a file descriptor instead of a filename?

Yes.  So the pattern is that the code doesn't **need** the filename, but the code is badly written.

> everything would be easier if mutt_file_mkstemp didn't unlink() the file immediately,
> ... returned both the filename and an open file descriptor

Yes (for now)

> mutt_file_closetemp() that would handle closing and deleting the file

Yes, that's what I've been thinking, too.

> I've created #1176 .. Let me know what you think.

At a quick glance, it looks good.
I'll have a closer look later.

It seems like current `mutt_file_mkstemp()` is the right solution **to aim for**.
Then, as we investigate the callers, we can untangle and convert them to use `FILE*`.

**Comment by toogley** [comment]
@flatcap maybe it makes sense to create an extra issue for those significant mailbox API changes? we might forget otherwise.

**Comment by flatcap** [comment]
@toogley 
I'm not so sure.  Who'd tackle it?  And when?
It'd just be sitting around, collecting dust, until I got sick of seeing it.
Reading through a large bunch of unachievable issues just gets depressing and overwhelming.

**Comment by P-EB** [comment]
@flatcap true, but leaving some potential issues undocumented may also have depressing effects on the long term.

**Comment by flatcap** [comment]
@P-EB 
Every idea goes in "the big list", which is sync'd to https://github.com/neomutt/flatcap-brain-dump
Periodically, I reorganise and regroup the list (and re-prioritise the development direction.

**Comment by P-EB** [comment]
Noted :)
