### ISSUE TITLE
Thread completion from different directory

### ISSUE THREAD

**Issue by tonobo** [neomutt/neomutt#1168]
I'm putting all my "processed" mails to a different folder. This could be called archive. But if anybody replies to an thread, i'd like to see the whole thread in my inbox. Is there any option to add a further thread lookup on another folder?

**Comment by flatcap** [comment]
If your email is on a remote server, then I can't think of a way, but...
if your email is local, then this could be a job for Notmuch.

You could have all your "archived" mails in directories, organised however you like.
You could then have a Notmuch "virtual" folder.

This selects the entire thread of emails matching the query "is:unread"
```
set nm_query_type = threads
virtual-mailboxes "Inbox" notmuch://?query=is:unread
```

More info:
- https://www.neomutt.org/feature/notmuch
- https://notmuchmail.org/
