### ISSUE TITLE
Convert GroupContexts to use STAILQ

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1177]
This is an "easy" task ([find more](https://github.com/neomutt/neomutt/issues?q=label:"good%20first%20issue"+is:open)) and it's open to everyone.  [_read more..._](https://neomutt.org/dev/easy-tasks)

## Description

Many NeoMutt structures implement their own linked-list type.  
The GroupContexts are simply stored as a long linked list.

`STAILQ` is a singly-linked list with pointers to both the head and the tail.  
It's defined in [mutt/queue.h](https://github.com/neomutt/neomutt/blob/master/mutt/queue.h),

### Part 2: Change all users to match

There are plenty of examples in NeoMutt's code of how to iterate through a list.  
For example: [tags.c](https://github.com/neomutt/neomutt/blob/master/tags.c), [tags.h](https://github.com/neomutt/neomutt/blob/master/tags.h)

**Note**: When deleting items, use `STAILQ_FOREACH_SAFE()`

**Comment by yuzibo** [comment]
Hello,
Sorry, but i want to ask clearly question here.
`.struct GroupContext
{
    struct *g;
    STAILQ_ENTRY(GroupContext) entries;
};
STAILQ_HEAD(GroupHead, GroupNode);`
Could you have a glance at the the first step for the issue?
Is this right the first step to do that?
Thank you

**Comment by flatcap** [comment]
Yes, that's right.

**Comment by flatcap** [comment]
This issue is now finished successfully!  Thanks, @yuzibo.
PR #1187 will stay open whilst we do some other work to add tests for the GroupContext code.
