### ISSUE TITLE
Convert Keymaps to use STAILQ

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1179]
This is an "easy" task ([find more](https://github.com/neomutt/neomutt/issues?q=label:"good%20first%20issue"+is:open)) and it's open to everyone.  [_read more..._](https://neomutt.org/dev/easy-tasks)

## Description

Many NeoMutt structures implement their own linked-list type.  
The Keymaps are simply stored as a long linked list.

`STAILQ` is a singly-linked list with pointers to both the head and the tail.  
It's defined in [mutt/queue.h](https://github.com/neomutt/neomutt/blob/master/mutt/queue.h),

### Part 2: Change all users to match

There are plenty of examples in NeoMutt's code of how to iterate through a list.  
For example: [tags.c](https://github.com/neomutt/neomutt/blob/master/tags.c), [tags.h](https://github.com/neomutt/neomutt/blob/master/tags.h)

**Note**: When deleting items, use `STAILQ_FOREACH_SAFE()`

**Comment by z2v** [comment]
I'll take the issue

**Comment by yuzibo** [comment]
Hello,The issue is same to my taken issue:
https://github.com/neomutt/neomutt/pull/1187
I am not hope make noisy for you,but i want to talk about STAILQ usage.
In my case, i encounter segfault :(.
```c
static int parse_alternates(struct Buffer *buf, struct Buffer *s,
                            unsigned long data, struct Buffer *err)
{
  struct GroupContextHead gc = STAILQ_HEAD_INITIALIZER(gc);
  alternates_clean();
  do
  {
  ...
    if (parse_group_context(&gc, buf, s, data, err) == -1)
      goto bail;
   ...
    if (mutt_group_context_add_regex(&gc, buf->data, REG_ICASE, err) != 0)
      goto bail;
...
}
```
Is this right?
Anyway, i will close eye to your the issue.
Thank you

**Comment by z2v** [comment]
@yuzibo Have you changed definintions for `parse_group_context` and `mutt_group_context_add_regex`? What's the type of first their argument in your branch?

**Comment by yuzibo** [comment]
This is my detail code:
in group,h:
```c
struct Group
{
  struct Address *as;
  struct RegexList *rs;
  char *name;
};

/**
 * struct GroupContext - A set of Groups
 */
struct GroupContext
{
  struct Group *g;
  STAILQ_ENTRY(GroupContext) entries;
};
STAILQ_HEAD(GroupContextHead, GroupContext);
...
void mutt_group_context_add(struct GroupContextHead *head, struct Group *group);
int mutt_group_context_add_regex(struct GroupContextHead *head, const char *s,
                                 int flags, struct Buffer *err);
...
```
parse_group_context in init.c:
```c
tatic int parse_group_context(struct GroupContextHead *ctx, struct Buffer *buf,
                               struct Buffer *s, unsigned long data, struct Buffer *err)
{
  while (mutt_str_strcasecmp(buf->data, "-group") == 0)
  {
    if (!MoreArgs(s))
    {
      mutt_str_strfcpy(err->data, _("-group: no group name"), err->dsize);
      goto bail;
    }
    mutt_extract_token(buf, s, 0);
    mutt_group_context_add(ctx, mutt_pattern_group(buf->data));
    if (!MoreArgs(s))
    {
      mutt_str_strfcpy(err->data, _("out of arguments"), err->dsize);
      goto bail;
    }
    mutt_extract_token(buf, s, 0);
  }
  return 0;
bail:
  mutt_group_context_destroy(ctx);
  return -1;
}
```
In fact, here mutt_group_context_add()  not be called at all in parse_group_context.
And both of functions in group.c 
```c
void mutt_group_context_add(struct GroupContextHead *head, struct Group *group)
{
  struct GroupContext *np = NULL;
  STAILQ_FOREACH(np, head, entries)
  {
    if (np->g == group)
      return;
  }
  np = mutt_mem_calloc(1, sizeof(struct GroupContext));
  np->g = group;
  STAILQ_INSERT_TAIL(head, np, entries);
}
...
int mutt_group_context_add_regex(struct GroupContextHead *head, const char *s,
                                 int flags, struct Buffer *err)
{
  int rc = 0;
  struct GroupContext *np  = NULL;
  if (!head)
	  return 0;
  if (!rc)
  {
    STAILQ_FOREACH(np, head, entries)
    {
      if (!rc)
      {
        rc = group_add_regex(np->g, s, flags, err);
      }
    }
  }
  STAILQ_INSERT_TAIL(head, np, entries);
  return rc;
}
```
The original code in master branch is 
```c
struct GroupContext
{
  struct Group *g;
  struct GroupContext *next;
};
void mutt_group_context_add(struct GroupContext **ctx, struct Group *group);
int mutt_group_context_add_regex(struct GroupContext *ctx, const char *s, int flags, struct Buffer *err);
in group.c
void mutt_group_context_add(struct GroupContext **ctx, struct Group *group)
{
  for (; *ctx; ctx = &((*ctx)->next))
  {
    if ((*ctx)->g == group)
      return;
  }
  *ctx = mutt_mem_calloc(1, sizeof(struct GroupContext));
  (*ctx)->g = group;
}
```
Thanks again!

**Comment by flatcap** [comment]
@z2v 
Have you started on this?
Is there anything you need from me?

**Comment by z2v** [comment]
@flatcap not yet, was busy a little bit. I'm going to fix the issue during the next week

**Comment by Kratacoa** [comment]
Is this issue solved?

**Comment by flatcap** [comment]
Hi @Kratacoa 

> Is this issue solved?

No it isn't.  Would you like to have a go at it?
I've moved z2v's work to the branch [devel/keymap](https://github.com/neomutt/neomutt/tree/devel/keymap) (and checked it compiles)

The Keymap has the `STAILQ_ENTRY` member.

https://github.com/neomutt/neomutt/blob/b7dff5d38553acb4ea1a1980345784affebecce7/keymap.h#L46-L56

The remaining jobs are:
- Convert the global `Keymaps` into an array of `KeymapList`
  - Fix `km_init()` to match
  - Fix `mutt_keys_free()` to match
- Find all the functions taking or returning a `Keymap`
  Some will need changing to use `KeymapList`
- Find any functions using the old `Keymap.next` member
  Convert them to use `STAILQ_FOREACH`
- Fix the functions in `keymap.c` that add/remove entries from `Keymaps`

This isn't a big a job as it sounds (plus I'm happy to help guide you).
There aren't many users of the Keymaps and the uses are fairly simple.

Interested?

**Comment by Kratacoa** [comment]
Thank you for the swift response @flatcap !
I'm interested in it as a learning opportunity, but I don't think I'll be able to allocate time to it in the near future as I have my hands packed, unfortunately.. Regardless, I'll contact you for sure if the situation change.

**Comment by flatcap** [comment]
No worries.
There will always be some 'easy' tasks ready when you are.

**Comment by yuzibo** [comment]
Hi, I do not find devel/keymap  branch  on origin .Is there some wrong i made?

**Comment by flatcap** [comment]
After a year of inactivity, I archived it:
https://github.com/neomutt/neomutt-old/tree/issue-1179

**Comment by yuzibo** [comment]
Need i git clone neomutt-old?
I want to hack something on the weekend if you have another issue(not hard).
This task should be @karelzak  :(

**Comment by flatcap** [comment]
> Do need i git clone neomutt-old?

To get the source, yes.
You'll need to rebase it onto the current master.

>  if you have another issue(not hard).

Sorry, not at the moment.

**Comment by yuzibo** [comment]
ok, i will try it.

**Comment by m-sameer** [comment]
Anyone doing this?
I know `C/C++`, but don't know `NeoMutt`'s code base but I can try.

Check [my profile](https://www.github.com/m-sameer) to see my earlier contributions and see if I qualify. 

:upside_down_face:

**Comment by gahr** [comment]
If you are willing to contribute you’re certainly more than welcome! Feel free to reach out on freenode/#neomutt, we’re happy to help get you started! There’s a lot to do!

**Comment by flatcap** [comment]
I've rebased the branch that was started earlier: [[devel/keymaps]](https://github.com/neomutt/neomutt/tree/devel/keymaps).

Have a look at where `struct Keymap` is used and have a think about what needs doing, and...
Please ask lots of questions.

**Comment by flatcap** [comment]
@m-sameer Have you had a chance to look at the code?

**Comment by m-sameer** [comment]
@flatcap I didn't. I will today.
Will respond when I do. 😁

**Comment by yousefakbar** [comment]
Hi! Is this issue still being worked on? I'd love to help out if I can. @flatcap 

I can see @z2v 's commit in the `devel/keymaps` branch and, with a quick study of how (S)TAILQ has been implemented elsewhere in the code, it seems like the work is only just started with initialization of the STAILQ in `keymaps.h`.

Is anyone actively working on this or should I give it a try? 😀

**Comment by flatcap** [comment]
Hi @yousefakbar,

> Is anyone actively working on this

No, it seems not.

> or should I give it a try?

Yes please!

and I'll repeat my advice...

> Have a look at where struct Keymap is used and have a think about what needs doing,

and...

> **Please ask lots of questions.**

You can ask them here or on IRC: #neomutt on irc.freenode.net

Thanks.

**Comment by yousefakbar** [comment]
Sounds good. I'll give it my best shot then.

I suspect I'll have a lot of newbie questions since I've never worked with STAILQ before so I'll be around on IRC to ask questions.

Thank you.

**Comment by flatcap** [comment]
> I've never worked with STAILQ before

[mutt/queue.h](https://github.com/neomutt/neomutt/blob/master/mutt/queue.h) contains a family of similar macros.
They're well written and fairly easy to understand and there are lots of examples in our source.

> I'll be around on IRC to ask questions

Sure, I'm always logged in.  If I'm not awake, feel free to queue-up questions.

**Comment by flatcap** [comment]
@yousefakbar 
The code looks good.
The next step would be to tidy up the branch and create a PR (for review).
I suggest, `git rebase` to both move the commits on top of `master` and also squash them into one commit.
It doesn't make sense to merge the separate (non-working) commits.

```sh
git rebase --interactive master
```

Should do it.

**Comment by yousefakbar** [comment]
Will do. Thanks for the help!
