### ISSUE TITLE
allow changing "default" color of sidebar items?

### ISSUE THREAD

**Issue by tshirtman** [neomutt/neomutt#118]
It's possible to change about every color in sidebar, but not the default one, i'd like to grey out the non-(new,flagged,highlighted or spoolfile) maiboxes, and i don't see any way to achieve that.

I'm using the version currently in debian testing. (Mutt 1.6.2-neo (2016-07-23))

**Comment by flatcap** [comment]
hehe, you're right.  You can't set the colour of "ordinary" mailboxes, but I like your idea.
I shall make some time to make it happen.

**Comment by flatcap** [comment]
I've committed a test version to the [devel7/sidebar-ordinary](https://github.com/neomutt/neomutt/tree/devel7/sidebar-ordinary) branch.

It uses the config: `color sidebar_ordinary FOREGROUND BACKGROUND`

**Notes:**
- This is a development branch of the code and may be unstable.  Beware.
- It may be a while before this gets into NeoMutt
