### ISSUE TITLE
Encapsulate the Progress Bar

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1180]
Looking for something easier?  ([try these](https://github.com/neomutt/neomutt/issues?q=label:"good%20first%20issue"+is:open))

## Description

Wrap up the code for the Progress Bar, reducing the effort for the callers and
unify the logging of progress events.

### Part 1: Review Logging Levels

There are currently 5 debug logging levels, which aren't used consistently.
The new guideline is:
- Level 1-3: General debug info (at the programmer's discretion)
- Level 4: Progress bar, trace info, e.g. "Entering function()"
- Level 5: Data read/written/transferred, or other private info

There are about 65 calls to `mutt_debug()` which need reviewing.
This shouldn't take too long.
For each message decide whether it should be:
- Level 3: General
- Level 4: Progress
- Level 5: Data

### Part 2: Create a LL\_PROGRESS Log Level

Create a new debugging level `LL_PROGRESS` and change the progress bar to use it.

You'll need to alter the logging code, too.
Progress messages should **always** be displayed on screen, but only be written
to file if `$debug_level >= 4`.

Now run `neomutt -d3` with some large folders, etc, and find any other progess
messages that should have their level altered.

Try some large searches, too.

### Part 3: Encapsulate the Progress Bar

Change the code to dynamically `create()` and `destroy()` the Progress object.
This will allow the progress bar to signal when it's done.

Currently, the code is littered with calls to `mutt_window_clearline()` many of
which only exist to clear away the last progress message.

### Future direction

(This isn't required for this issue)

The update frequency for the progress bar is controlled by:
- `net_inc`
- `read_inc`
- `time_inc`
- `write_inc`

It would make sense for this to be handled by the progess bar itself.

**Comment by flatcap** [comment]
> `mutt_expando_format()` takes a `char*` not a `struct Buffer`
> (Is anyone considering to change that?)

Hmm... 500 lines of fragile code, used in over 20 places?
No.  Nobody's had the courage to tackle that.
(I've only standardised the function/variable naming across all callers)

> guess a "good enough" size ... to know if the output was truncated

I don't think truncation is likely; the callers have ample space.
Those formatting a line for the screen are given 1KiB, and those formatting commands are given 8KiB.

> Maybe this should be an Issue?

Hmm... it could certainly do with refactoring, but I think that might require a lot of analysis first.
There are a lot of hard-coded rules and quirks in there.

> I can imagine myself working on it.

Can I instead interest you in a different refactoring job: #1180 - Encapsulate the Progress Bar

Several backends use it, all slightly differently, and they all have to decide whether to log or not.
I'd like all the globals (`$net_inc`, `$read_inc`, `$time_inc`, `$write_inc`) wrapped up and all the decisions made in `progress.c`.

Thanks.

**Comment by nobrowser** [comment]
For me on current master, `grep -e mutt_debug` comes back with 184 matches.  Am I right that this is just because of code additions/changes since April?

**Comment by flatcap** [comment]
After a little experimenting, I think I was referring to just the level 4/5.
Just the ones that might need moving.  `grep -R "mutt_debug([45]" .` gives me 68 matches.
tbh, as long as level 4 is only used for progress info, then we can review the others another time.

**Comment by flatcap** [comment]
Any progress?  Problems?  Questions?
(that's about the limit of my Project Management skills :-)

**Comment by nobrowser** [comment]
Let me get this straight.  You want to replace calls `mutt_progress_int()` and `mutt_progress_update()` with `mutt_debug(LL_PROGRESS)` ? I do not think that is a good idea.  Rather, I would just add the latter call inside the `mutt_progress_*` bodies.

This doesn't preclude any other refactorings of the progress bar code you might want - indeed, it makes them easier, I think.

**Comment by flatcap** [comment]
> You want to replace calls `mutt_progress_int()` and `mutt_progress_update()` with `mutt_debug(LL_PROGRESS)`

No, they should be hidden as you suggest.

I proposed `LL_PROGRESS` as debugging at level 4, so I'd like any existing level 4 messages (there are about 16) moving out of the way.  Initially, only `progress.c` will be using `LL_PROGRESS`.  (We may use `LL_PROGRESS` for other things in the future)

One of the problems with the existing code, is that there's no definitive _end_ to the progress.  A local `Progress` object just goes out of scope.  This lead to a lot of `sleep`s and calls to clear leftover progress messages.

Having distinct `alloc`, `start`, `update` and `end` methods means that listeners can make smarter choices, e.g.  Don't log **every** progress message to disk.

Sorry if I'm not clear -- keep asking questions.
(I write up these tasks having thought about them for long periods).

**Comment by nobrowser** [comment]
I notice that no code actually uses the enum values `LL_DEBUG1` etc., all callers just hardcode a number.  Maybe we should rename all the enums meaningfully then?  Sorry, I know this is a bit out of scope for the issue, but my taste buds revolt at having `LL_DEBUG[1235]` and `LL_PROGRESS` right in the middle set to 4.

**Comment by flatcap** [comment]
> ... bit out of scope ...

Nah.  Fixing things is always in scope.

> no code actually uses the enum values `LL_DEBUG1`

True.  I created them when I refactored the logging code.
The use of logging levels in the code is far from consistent.
I have some ideas for levels, but for now the names are 'generic'.

The question is when should we rename them?
Before or after we've fixed the levels?

Generally, if I fix a 'thing' I like to go through the code and fix **all** instances of that 'thing'.
That's the reason for my suggesting:
1. Clear out level 4 logging
2. Define `PROGRESS`
3. Going forward, only use that level for progress messages

By the time we define the name, it's already consistent.

My ideas for levels are:
1. High level trace, e.g. "saving email X to folder Y"
2. Debug misc, higher level
3. Debug misc, low level (may be function traces)
4. Progress messages
5. Data transfer

**Comment by nobrowser** [comment]
That makes total sense, thanks.  I was just following the roadmap above in the issue, which has defining LL_PROGRESS early on.

**Comment by nobrowser** [comment]
Hi.  Making some turtle-like headway here :-P  But I found something I don't understand.  In `conn/sasl.c `, function `mutt_sasl_start()` ... the type of the callback that SASL library wants doesn't match the type of the function we pass in (hence the need to cast it).  Unless I'm missing something, the `priority` and `message` arguments will be garbage when the function is actually called.

I started fixing it by wrapping `priority` and `message` in a struct and passing a pointer to the struct in `context` , but then I realized the type calls for *no* args at all, not even `context` .

As is it, it is hard to decide at what priority these messages are in fact logged.

**Comment by flatcap** [comment]
hehe, it's a bit complicated.
I traced though it a while back to see what was going on.

`sasl_client_init()` takes an array of callback functions.
They have different prototypes, but what they _do_ have in common in the return value.
So, they're all cast to `int (*proc)(void)`

The one function we want to listen to is the logging callback.

From \<sasl/sasl.h\>:
```c
/* Logging levels for use with the logging callback function. */
#define SASL_LOG_NONE  0  /* don't log anything */
#define SASL_LOG_ERR   1  /* log unusual errors (default) */
#define SASL_LOG_FAIL  2  /* log all authentication failures */
#define SASL_LOG_WARN  3  /* log non-fatal warnings */
#define SASL_LOG_NOTE  4  /* more verbose than LOG_WARN */
#define SASL_LOG_DEBUG 5  /* more verbose than LOG_NOTE */
#define SASL_LOG_TRACE 6  /* traces of internal protocols */
#define SASL_LOG_PASS  7  /* traces of internal protocols, including
         * passwords */

/* logging callback -- this allows plugins and the middleware to
 *  log operations they perform.
 * inputs:
 *  context     -- logging context from the callback record
 *  level       -- logging level; see above
 *  message     -- message to log
 * returns:
 *  SASL_OK     -- no error
 *  SASL_FAIL   -- error
 */
typedef int sasl_log_t(void *context,
           int level,
           const char *message);
#define SASL_CB_LOG     2
```

The prototype for the logging callback has three parameters and the levels are defined as 0 - 7.

I don't know what (or when) events are actually logged from SASL, but I think we want to morph the SASL levels into fewer NeoMutt levels.  Maybe:

| SASL Log Level     | NeoMutt Action  |
| :----------------- | :-------------- |
| `SASL_LOG_NONE  0` | Do nothing      |      
| `SASL_LOG_ERR   1` | NeoMutt level 1 |      
| `SASL_LOG_FAIL  2` | NeoMutt level 1 |      
| `SASL_LOG_WARN  3` | NeoMutt level 1 |      
| `SASL_LOG_NOTE  4` | NeoMutt level 2 |      
| `SASL_LOG_DEBUG 5` | NeoMutt level 3 |      
| `SASL_LOG_TRACE 6` | NeoMutt level 5 |      
| `SASL_LOG_PASS  7` | NeoMutt level 5 |

**Comment by nobrowser** [comment]
Please review commit 7c33ff8081d36847578e21841ee4d8c53e32864e

**Comment by flatcap** [comment]
Yeah, that'll do nicely.
Would you like me to merge that now, or wait for the rest?

**Comment by nobrowser** [comment]
I think this should go in now, thanks.  It is a bit separate from the rest of the issue.

**Comment by flatcap** [comment]
Done.  Thanks.

**Comment by nobrowser** [comment]
Here comes the big awful part :-P  Review at your leisure.
cf1a6c5db4757ebcf8d3a3e066a10df1f1b136f0

**Comment by flatcap** [comment]
That's a nice job.
