### ISSUE TITLE
SSL on https://neomutt.org is broken

### ISSUE THREAD

**Issue by yatesco** [neomutt/neomutt#1186]
Just a note to say SSL on https://neomutt.org is coming up as broken.
![screen shot 2018-05-02 at 16 32 53](https://user-images.githubusercontent.com/181469/39533266-8fd930da-4e26-11e8-8004-3d233b302aac.png)

**Comment by flatcap** [comment]
Thanks, I know.  I broke things last night.
Until yesterday, GitHub didn't support HTTPS on custom domains.
Apparently not today, either :-)

I'm waiting on a support request from GitHub (to tell me what I've done wrong).

**Comment by yatesco** [comment]
(BTW - thanks for neomutt, it looks awesome!)

**Comment by yuzibo** [comment]
Hello, @flatcap 
Maybe try Cloudware :
https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/
I just resolve it on my site:
https://www.aftermath.cn/

**Comment by flatcap** [comment]
hehe, wrong way around :-)
NeoMutt's been using Cloudflare for over a year (because GitHub **didn't** support https).
GitHub has just partnered itself with Let's Encrypt.
[Our website](https://neomutt.org) seems to be working now.

I just need to adjust a few links (I dropped the 'www').

**Comment by flatcap** [comment]
Yeah, it's been long enough.
