### ISSUE TITLE
Missing url highlighting and urlview hotkey from 20160808 -> 20160820

### ISSUE THREAD

**Issue by sadsfae** [neomutt/neomutt#119]
After upgrading to ```neomutt-1.6.2-20160820.fc24.x86_64``` from ```1.6.2-20160808.fc24.x86_64``` the following features seem to be missing for me

- control  + b to open urlview for showing urls in emails no longer works, from ? command help menu.

```
^B    call urlview to extract URLs out of a message
```

- urls in emails are no longer highlighted with a different color in emails.

example before:

![neomutt-before](https://cloud.githubusercontent.com/assets/3940978/17831985/29af5eca-66f0-11e6-999f-26d12c8c1175.png)

example after:

![neomutt-after](https://cloud.githubusercontent.com/assets/3940978/17831989/32698464-66f0-11e6-8222-b9ab91cb9c10.png)

Here's my muttrc (I call mutt via mutt -f /path/to/muttrc)

https://github.com/sadsfae/misc-dotfiles/blob/master/muttrc.txt

I checked through the changelog and and issue #111 and didn't see anything that would affect those, but maybe I missed something?

Thanks.

**Comment by flatcap** [comment]
Hmm... that sounds suspiciously like something I did :-)
The first set of RPMs I created were meant to "Provide: mutt", but they lead to a conflict with urlview.
I immediately, rebuilt the RPMs and deleted the broken build.

Your timing may have been unlucky.

Embarrassing as it is to suggest, but: please can you try:
```
dnf remove urlview neomutt
dnf install urlview neomutt
```

**Comment by sadsfae** [comment]
No luck here, still same thing.  Firing off urlview I get:

```
Key is not bound.  Press '?' for help.
```

url color highlighting is still missing on ```neomutt-1.6.2-20160820.fc24.x86_64```

**Comment by flatcap** [comment]
Thanks.  Worth checking.

Hmm... the colour highlighting and the macro are both defined in `/etc/Muttrc` which NeoMutt installs.  However, NeoMutt hasn't changed that file, or the installation directory.

There're two reasons it wouldn't read that file: `mutt -n` or if it finds a more specific system config file.
NeoMutt will read the first system file it finds:
- /etc/xdg/neomutt/config
- /etc/NeoMuttrc
- /etc/Muttrc-1.6.2-neo
- /etc/Muttrc

Does `/etc/Muttrc` exist?
Does it contain the "urlview" config?
Do any other neomutt-like config files exist in /etc?

**Comment by sadsfae** [comment]
I've always launched mutt with the -F option to point to my configuration file.

```
-=>>which email
alias email='mutt -F ~/.muttrc-local'
	/usr/bin/mutt
```

I do have a /etc/Muttrc and /etc/Muttrc.local present however, I've never modified or changed these and they seem to be provided by neomutt (I've reverted back to ```neomutt-1.6.2-20160808```)
```
-=>>rpm -qf /etc/Mutt*
neomutt-1.6.2-20160808.fc24.x86_64
neomutt-1.6.2-20160808.fc24.x86_64
```

My config is here:
https://github.com/sadsfae/misc-dotfiles/blob/master/muttrc.txt

Beyond that I reference a gpg-specific file and mailcap, nothing out of the ordinary:

https://github.com/sadsfae/misc-dotfiles/blob/master/muttrc-gpg.txt
https://github.com/sadsfae/misc-dotfiles/blob/master/muttrc-mailcap.txt

As I understand it calling mutt with the ```-F``` option will force it to only use that file, so nothing configuration-wise has changed for me between ```neomutt-1.6.2-20160808``` and neomutt-1.6.2-20160820```

Thanks for looking at this.

**Comment by flatcap** [comment]
hi @sadsfae 
I've just made a new release: 20160821.
The COPR build has finished and newly installed version reads `/etc/Muttrc` like it ought to.
Sorry about that.

**Comment by sadsfae** [comment]
@flatcap this fixed both issues I had around urlview and url's showing up.  Thank you!
