### ISSUE TITLE
x-label isn't retained

### ISSUE THREAD

**Issue by rr-** [neomutt/neomutt#1192]
# Bug report

### Steps to reproduce

Using maildir and a trash directory:

1. Receive an e-mail
2. Apply an x-label to it
3. Read the e-mail (<kbd>enter</kbd>)
4. Sync the maildir for good measure (<kbd>$</kbd>)
5. Mark the e-mail as deleted (<kbd>d</kbd>)
6. Sync the maildir to actually delete it (<kbd>$</kbd>)
7. Navigate to the trash directory (<kbd>y</kbd>)
8. Observe how the e-mail in the trash directory is correctly marked as read, but no longer has the x-label

For what it's worth, [here's my muttrc file](https://github.com/rr-/dotfiles/blob/master/cfg/mail/muttrc#L33-L47).

### Expected behavior
X-label is retained

### Actual behavior
X-label is removed / isn't persisted

### Used program versions
NeoMutt 20180323

### Operating System and its version
Linux cyclone 4.15.15-1-ARCH #1 SMP PREEMPT Sat Mar 31 23:59:25 UTC 2018 x86_64 GNU/Linux

**Comment by flatcap** [comment]
Hmm... It seems to work for me.
I have `unignore x-label` in my config, so I can see the labels in the pager as well.

- Maildir mailbox
- `<edit-label>` 'green'
  (Label does not exist on disk)
- `<display-message>` 'X-Label: green'
  (Label does exist on disk)
- `<sync-mailbox>`
- `<delete-message>`
- `<sync-mailbox>`
  (Label now appears in trash folder)
- `<change-folder>trash`
- `<display-message>` 'X-Label: green'

**Comment by rr-** [comment]
After adding `unignore x-label` setting to my `muttrc` file, things seem to work.

**Comment by rr-** [comment]
Removing `unignore x-label` setting seems to consistently trigger the issue again, so looks like that is the solution. Thanks.

**Comment by flatcap** [comment]
> adding unignore x-label setting to my muttrc file, things seem to work.

Hmm... that shouldn't make a difference.

Thanks for letting us know.
