### ISSUE TITLE
error when opening ~/.config/neomutt/neomuttrc

### ISSUE THREAD

**Issue by derrickcope** [neomutt/neomutt#1197]
## bug reports

* Expected behavior
the file should just open

* Actual behavior

I am getting this
"~/.config/neomutt/neomuttrc" 67L, 1938C                                                                  
Error detected while processing /usr/share/nvim/runtime/syntax/neomuttrc.vim:
line  147:
E122: Function <SNR>53_escapesConditionals already exists, add ! to replace it
line  415:
E122: Function <SNR>53_boolQuadGen already exists, add ! to replace it
Press ENTER or type command to continue

* Steps to reproduce
I copied the /etc/neomuttrc file to my .config/neomutt but i still get the same results. I thought it may be a promblem with my config

* Used program versions

NeoMutt 20180323

* Operating System and its version

system: Linux 4.16.8-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libidn: 1.34 (compiled with 1.33)
hcache backends: gdbm

**Comment by yuzibo** [comment]
Hello,
I think there is no problem.You can disable it with '#'.
If you could give us your .neomuttrc file link, that would be great.
Thanks,

**Comment by derrickcope** [comment]
It is a function so should I comment out the entire function? I was afraid it was important.

I will put my config on github and send a link when I get home.

**Comment by flatcap** [comment]
Ah!  This was a mistake we made defining the functions.
You only see an error if you try to view two neomutt config files at once.

We've fixed the problem and it's already been accepted upstream.
So you can either:
- Ignore the error for now (annoying)
  Your distro may update it soon.
- Fix your local copy: change the two function lines to include <kbd>!</kbd>
  `function! s:escapesConditionals(baseName, sequence, alignment, secondary)`
  `function! s:boolQuadGen(type, vars, deprecated)`
