### ISSUE TITLE
<toggle-read> not applied immediately

### ISSUE THREAD

**Issue by l2dy** [neomutt/neomutt#1198]
## bug reports
https://github.com/neomutt/neomutt/blob/neomutt-20180323/curs_main.c#L1539
* Expected behavior
`<toggle-read>` hides read messages.
* Actual behavior
After `<toggle-read>`, new limit is not applied. Then pressing `l` and `<Enter>` (apply current limit) hides read messages.
* Steps to reproduce
* Used program versions
NeoMutt 20180323
* Operating System and its version
macOS 10.13.4

**Comment by gahr** [comment]
@l2dy could you please check whether the devel/issue-1198 branch fixes the issue for you?
