### ISSUE TITLE
hidding sidebar while pager open breaks mail list.

### ISSUE THREAD

**Issue by tshirtman** [neomutt/neomutt#120]
if one toggles side bar visibility while a mail is open, the mailbox rendering is scrambled, the sidebar offset still seems to apply, but not to the selected line, moving the cursor or exiting the mail view fixes the rendering, toggling a second time (without moving) shows the offset also misapplied.

correct rendering:
![1](https://cloud.githubusercontent.com/assets/22759/17837354/76ceadca-67b1-11e6-968a-dca6fe59d8ee.png)

after toggling once (hiding)
![2](https://cloud.githubusercontent.com/assets/22759/17837353/66ae17a0-67b1-11e6-988f-cb3b5714f26c.png)

after toggling again (showing)
![3](https://cloud.githubusercontent.com/assets/22759/17837352/66a91386-67b1-11e6-9423-4f19ca8d5093.png)

**Comment by flatcap** [comment]
Well spotted.  This bug goes back to 2016-07-09.
Fixed in commit https://github.com/neomutt/neomutt/commit/b38c5d72fd7dc7938a4f597e5c2ca498865a5ce0

#### This bug is now fixed and will be in the next release of NeoMutt.
