### ISSUE TITLE
notmuch: vfolder_format is ignored for inactive virtual folders, modify-labels-then-hide doesn't hide

### ISSUE THREAD

**Issue by flokli** [neomutt/neomutt#121]
I configured some virtual-mailboxes and access them using the sidebar. However, it seems like `vfolder_format` is ignored, and I don't see the number of unread messages laying behind this query (only the unread count of the currently opened query is shown in the sidebar).

Additionally, it seems like `<modify-labels-then-hide>` doesn't hide the message ("quasi-delete"), but labels get set.

**Comment by flatcap** [comment]
Sorry it's take a while to get around to this.

The Sidebar display is controlled by `$sidebar_format`
`$vfolder_format` controls the display of the browser, when you do `<change-vfolder>`

To get the most out of the Sidebar, you need to enable a new variable: `$mail_check_stats`
```
set mail_check_stats = yes
set sidebar_format = "%B%?F? [%F]?%* %?N?%N/?%S"
```

For NotMuch, the browser defaults to:
```
set vfolder_format="%2C %<n?%4n/&     >%4m %f"
```

Finally,

> it seems like `<modify-labels-then-hide>` doesn't hide the message

Hmm...  Yes, you're right.  I'll fix that.

**Comment by flokli** [comment]
Since some days, I see the unread count of unopened queries. Don't know if this got fixed because I someday enabled `mail_check_stats`, or by a previous NeoMutt update, but I'm happy it works now :-)

The bug concerning `<modify-labels-then-hide>` is still valid, though.

**Comment by flatcap** [comment]
Hi again @flokli.  There's good news and bad news.

First the bad news: `<quasi-delete>` and `<modify-labels-then-hide>` don't update the index.  They never did.  They only marked emails.  (I checked with the author)

The good news is that you just need to make a small change to your workflow: call `<sync-mailbox>`

**For example:**
```
macro index <f9> "<modify-labels-then-hide>+red<enter><sync-mailbox>"
```
This macro works on individual emails `<f9>`, or a tagged set `;<f9>`

I'll leave this issue open until I get a chance to make the docs clearer.

**Comment by flatcap** [comment]
The `quasi-delete` part of notmuch has been extended recently and the docs updated.
