### ISSUE TITLE
$hostname is empty during the configuration files reading process

### ISSUE THREAD

**Issue by doronbehar** [neomutt/neomutt#1213]
## Expected Behaviour

I want to `source /home/doron/.neomutt/$hostname.rc`. `$hostname.rc` is supposed to be a machine specific rc file which can be synced across different machines along side other machine dependent configuration files.

## Actual Behaviour

I get an error:
```
Error in /home/doron/.neomutt/neomuttrc, line 1: source: file /home/doron/.neomutt/.rc could not be sourced
```

## Steps to Reproduce

Just write something like this in your `neomuttrc`:
```
source ~/$hostname.rc
```
And put a real file in the specified location.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded to version `20180512`. This bug was not present in the previous version.

## NeoMutt Version

```
NeoMutt 20180512
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.16.8-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.34 (compiled with 1.34)
hcache backends: gdbm

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 8.1.0 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn=/usr --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Arch Linux
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? Irrelevant.
* Is your email local (maildir) or remote (IMAP)? Irrelevant.

After `neomutt` starts, running in it's command line `set hostname` gives the correct output but during the configuration reading process this value is missing.

I guess this is related to #1141, #1116 and #1140...

**Comment by Austin-Ray** [comment]
I am able to `git bisect` and confirm that d4be39fae4e246d598897536c3e796e1b0c313ec is the offending commit.

**Comment by flatcap** [comment]
@Austin-Ray 
Hmm...  That change was to fix an annoying problem for some users.
They experienced a **long** delay every startup as NeoMutt tried to determine the FQDN.
(This was due to a common bad network configuration).

Setting `$hostname` manually, causes NeoMutt to avoid the costly DNS lookup.

@doronbehar 
Sorry about that, but I'd rather keep the change I made.

Fortunately, there's a couple of simple ways to get the same effect:
```sh
# Use the Environment Variable:
source $HOSTNAME.rc
# Use the hostname command:
source `hostname`.rc
```

**Comment by Austin-Ray** [comment]
@flatcap Thank you for the explanation. I will close my PR.

**Comment by doronbehar** [comment]
That worked @flatcap, Thanks!

Perhaps this particular use case of variables inside configuration files should be noted in the documentation? How about putting it somewhere along [section 'configuration' under header 24.3](https://neomutt.org/guide/configuration.html#24-3-%C2%A0user-defined-variables)?

**Comment by flatcap** [comment]
> ... should be noted in the documentation?

Yes, that's a good example for the docs.
I've made a note; I'll add it shortly.
