### ISSUE TITLE
Can't add '&type=<threads|messages>' to vfolder query

### ISSUE THREAD

**Issue by jpoimboe** [neomutt/neomutt#1214]
## Expected Behaviour

With the vfolder-from-query command, I added &type=messages to the query in order to override my nm_query_type default of threads, like:

`<vfolder-from-query>neomutt&type=messages`

I expected to see a vfolder of search results.

## Actual Behaviour

The vfolder is empty.  The shown URL is `///home/jpoimboe/Mail?type=threads&query=neomutt%26type=messages`.

Notice the '&' was encoded, which I think was introduced with #603.

## Steps to Reproduce

`<vfolder-from-query>neomutt&type=messages`

## How often does this happen?

- Always

## When did it start to happen?

- When I migrated to neomutt from mutt-kz master

## NeoMutt Version

```
NeoMutt 20180323
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.16.7-300.fc28.x86_64 (x86_64)
ncurses: ncurses 6.1.20180224 (compiled with 6.1)
libidn: 1.34 (compiled with 1.33)
hcache backends: tokyocabinet, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.0.1 20180324 (Red Hat 8.0.1-0.20) (GCC) 

Configure options: --sysconfdir=/etc SENDMAIL=/usr/sbin/sendmail ISPELL=/usr/bin/hunspell --notmuch --tokyocabinet --lmdb --gnutls --sasl --gss --gpgme

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  +gnutls +gpgme +gss +hcache -homespool +idn -locales_hack -lua +meta 
  -mixmaster +nls +notmuch -openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://www.neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```
## Extra Info

* Operating System and its version: Fedora 29
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? maildir

**Comment by Austin-Ray** [comment]
@flatcap: I would like to work on this issue. I have located a place within `nm_uri_from_query` where a fix can be implemented.

My plan of resolution is: 
 * Locate where `type=` statements occur.
 * Set the query type, within the `NmCtxData` struct, to the appropriate value.
 * Remove the`type=` statement from the query portion. 
   This will prevent two `type=` statements from existing (as demonstrated in the *Actual Behavior* section of the report)

Two blockers exist for implementing a solution:

 1. **A way to find a case-insensitive substring.**
    This is useful in the event that a user wants to `tYpE=tHrEaDs` like a lunatic. I know `strcasestr` exists as a GNU extension, but I could neither find a cross-platform solution nor one within `mutt/string.c`. Should an implementation be created in `mutt/string.c`?

 2. **A way to remove the substring.** e.g. `tag:inbox&type=threads` -> `tag:inbox`
    `memmove` seems like the function to use, but I am unsure about its memory safety. I can write a small method to ensure some basic conditions (e.g. the substring exists), but I wanted your opinion first.

Does this seem like a reasonable path, flatcap?

**Comment by flatcap** [comment]
> I would like to work on this issue

Brilliant!  Thanks @Austin-Ray.

> My plan of resolution is:

Sounds reasonable.

> user wants to `tYpE=tHrEaDs` like a lunatic

Hmm... we could either:
1. Document that it's lower case and case sensitive
2. Just lowercase the string before comparison

I prefer 2. -- be generous in what we accept.

> remove the substring
> memmove

Yes, `memmove` is what you want.
It guarantees that overlapping regions will be handled safely.
However, it won't magically NUL-terminate the string.

> Does this seem like a reasonable path?

Yes!  Any questions just ask.
Thanks.

**Comment by Austin-Ray** [comment]
@flatcap : Thanks for the response! I have almost completed a patch to resolve this issue, but I'm having trouble implementing case-insensitive substring searching.

I prefer to write solutions that dogfood existing methods. As such, I have tried to compose a case-insensitive `strstr` implementation using `mutt_str_strdup`, `mutt_str_strlower`, and `strstr` then use pointer arithmetic to work out the position of the substring from a case-sensitive haystack (since notmuch's tags are case-sensitive.)

My implementation is:
```C
char *mutt_str_strcasestr(const char *haystack, const char *needle)
{
   // Duplicate so we don't mess with case-sensitivity of notmuch's tags
   char *haystack_dup = mutt_str_strdup(haystack);
   char *needle_dup = mutt_str_strdup(needle);
  
   // Lower case the duplicates to use strstr
   char *haystack_lower = mutt_str_strlower(haystack_dup);
   char *needle_lower = mutt_str_strlower(needle_dup);

   char *substr_pos = strstr(haystack_lower, needle_lower);
  
   if (substr_pos == NULL)
   {
      return NULL;
   }

   // Pointer arithmetic to work out substring position in case-sensitive haystack
   int index = substr_pos - haystack_lower;
   return &haystack_lower[index]; // could be replaced with (char *) (haystack + index)
}
```

When incorporated into Neomutt, I receive segmentation faults when I call that method, even in tests that I wrote. However, if I write a small C program will the necessary methods, my implementation works fine. 

I'm sure there is something that I am missing due to my inexperience with C or the internals of Neomutt.


No doubt that trying to implement case-insensitive `strstr` has caused me frustration. I wrote an alternative implementation that only uses features in C. This implementation passes all the tests that I have written for `mutt_str_strcasestr`. As an added bonus, this implementation should use less memory as it doesn't duplicate strings. 

```C
char *mutt_str_strcasestr(const char *haystack, const char *needle)
{
  if (haystack == NULL || needle == NULL)
  {
    return NULL;
  }

  size_t haystack_len = strlen(haystack);
  size_t needle_len = strlen(needle);

  // Check size conditions. No point wasting CPU cycles.
  if (haystack_len == 0 || needle_len == 0 || haystack_len < needle_len)
  {
    return NULL;
  }

  // Only check space that needle could fit in.
  // Conditional has + 1 to handle when the haystack and needle are the same length.
  for (int i = 0; i < (haystack_len - needle_len) + 1; i++)
  {
    for (int j = 0; j < needle_len; j++)
    {
      if (tolower((unsigned char) haystack[i + j]) != tolower((unsigned char) needle[j]))
      {
        break;
      }

      // If this statement is true, the needle has been found.
      if (j == needle_len - 1)
      {
        return (char *) (haystack + i);
      }
    }
  }

  return NULL;
}
```

Is there a personal preference for how case-insensitive substring searching should be implemented?

Would a pull request be more suited to this discussion? 

Any guidance on the matter is greatly appreciated.

**Comment by flatcap** [comment]
OK, there are a few problems with the first bit of code.

- The function leaks both of the duplicated strings
- You returned a pointer to the wrong haystack
- It returned a non-const pointer when we were given a const pointer

I can't say for certain why it crashed, but I suspect it was to do with freeing
a pointer that wasn't at the beginning of an allocated block.

Here's a fixed version:

```c
const char *mutt_str_strcasestr(const char *haystack, const char *needle)
{
  char *haystack_dup = mutt_str_strdup(haystack);
  char *needle_dup = mutt_str_strdup(needle);

  // Lower case the duplicates to use strstr
  char *haystack_lower = mutt_str_strlower(haystack_dup);
  char *needle_lower = mutt_str_strlower(needle_dup);

  char *substr_pos = strstr(haystack_lower, needle_lower);
  FREE(&needle_lower);
  if (!substr_pos)
  {
    FREE(&haystack_lower);
    return NULL;
  }

  // Pointer arithmetic to work out substring position in case-sensitive haystack
  ptrdiff_t index = substr_pos - haystack_lower;
  FREE(&haystack_lower);
  return haystack + index;
}
```

- Free the duplicated strings
- Use NeoMutt's `strdup()` so we can drop the NULL checks
- Return a pointer within the given string

---

The second version looks more promising.
I've done a little light tidying:

```c
const char *mutt_str_strcasestr(const char *haystack, const char *needle)
{
  size_t haystack_len = mutt_str_strlen(haystack);
  size_t needle_len = mutt_str_strlen(needle);

  // Check size conditions. No point wasting CPU cycles.
  if ((haystack_len == 0) || (needle_len == 0) || (haystack_len < needle_len))
    return NULL;

  // Only check space that needle could fit in.
  // Conditional has + 1 to handle when the haystack and needle are the same length.
  for (size_t i = 0; i < (haystack_len - needle_len) + 1; i++)
  {
    for (size_t j = 0; j < needle_len; j++)
    {
      if (tolower(haystack[i + j]) != tolower(needle[j]))
        break;

      // If this statement is true, the needle has been found.
      if (j == (needle_len - 1))
        return haystack + i;
    }
  }

  return NULL;
}
```

- const return type
- replace int with size_t in the for loops
- add a few ()s (personal taste)

---

> Would a pull request be more suited to this discussion?

Discussing it here is fine.

Generally speaking, all project members are welcome to create `devel/short-name` branches to work in.
Those are your private space.  I _may_ look, but I won't say anything :-)
Once you're ready for discussion, second-opinions or reviews, then you can create a pull-request.

**Comment by Austin-Ray** [comment]
@flatcap Thanks for looking it over! After seeing the corrected code, I understand why it is the correct way to do so. Unfortunately, the first implementation still does not work so I will be using the second implementation.

I have two questions regarding your edits.

First, the removal of `unsigned char` casts for the `tolower(...)` calls.
```C
if (tolower(haystack[i + j]) != tolower(needle[j]))
```

My understanding is that the `tolower(...)` requires `unsigned char` as input. According to `man tolower`:

> If the argument c  is  of  type char, it must be cast to unsigned char, as in the following example:
>
> char c;
> ...
>res = toupper((unsigned char) c);
>
> This  is necessary because char may be the equivalent signed char, in which case a byte where the top bit is set would be sign extended when converting to int, yielding a value that is outside the range of unsigned char.

So to me, it seems like the `unsigned char` cast is necessary to prevent undefined behavior depending on the implementation of C. Would this be a correct interpretation?

Second, is the return type. This is a purely stylistic question.
```C
const char *mutt_str_strcasestr(const char *haystack, const char *needle)
```
I wanted the method signature to mirror `strstr(...)`'s so it could be a drop-in replacement. Using a `(char *)` cast on the return statement did not give me a `discarded qualifier` warning when the return type was `char *`.  As a C novice, this seems fine to do. Given your experience with C, why is it a bad idea?
