### ISSUE TITLE
Missing translations for "(end)"/"(all)" in the status bar

### ISSUE THREAD

**Issue by mgedmin** [neomutt/neomutt#1217]
status.c, line 259, in status_format_str():
```c
        cp = menu->top ? "end" : "all";
```

pager.c, line 1997, in pager_menu_redraw():
```c
      mutt_str_strfcpy(pager_progress_str, (rd->topline == 0) ? "all" : "end",
```

These are strings displayed to the user and today they cannot be translated, which feels wrong to me.

**Comment by flatcap** [comment]
Yep, they should be translated.

**Comment by flatcap** [comment]
Fixed in 292f17d43 in [translate]

**Comment by mgedmin** [comment]
One half of this issue (in `pager.c`) is fixed.

The other half (in `status.c`) remains untranslatable.

I'll assume closing this was an accident so I'll reopen.

**Comment by mgedmin** [comment]
Also it might be nice to have a L10N note that the translation (in `pager.c`) gets truncated at 3 characters, which was a bit of a surprise to me.

**Comment by flatcap** [comment]
Oops.  I'll fix that.

**Comment by flatcap** [comment]
Made more space (64 bytes) and commented the strings.

**Comment by flatcap** [comment]
Sorry.  I've got the message _this_ time.
Both messages are translated in both places.
