### ISSUE TITLE
Convert RegexList to use STAILQ

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1222]
## Description

Many NeoMutt structures implement their own linked-list type.
The RegexLists are simply stored as a long linked list.

`STAILQ` is a singly-linked list with pointers to both the head and the tail.
It's defined in [mutt/queue.h](https://github.com/neomutt/neomutt/blob/master/mutt/queue.h),

**Note**: This isn't too hard, but there are lots of uses of RegexList.

### Part 2: Change all users to match

There are plenty of examples in NeoMutt's code of how to iterate through a list.
For example: [tags.c](https://github.com/neomutt/neomutt/blob/master/tags.c), [tags.h](https://github.com/neomutt/neomutt/blob/master/tags.h)

**Note**: When deleting items, use `STAILQ_FOREACH_SAFE()`

**Comment by mschilli87** [comment]
see https://github.com/neomutt/neomutt/commit/696e7fa97f527fc1aaafb3f6206da57d923ddcca
