### ISSUE TITLE
Missing folders when switching between IMAP servers

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1225]
The first time NeoMutt connects to a IMAP server, it honours the `set imap_check_subscribed = yes` option and displays the folders in the sidebar.

If you switch to another server, then back again, the folders don't come back.

**.muttrc**
```
account-hook imap://example.org 'source example.org.rc'
account-hook imap://other.com   'source other.com.rc'
macro index <F5> "<change-folder>imap://example.org/INBOX<enter>"
macro index <F6> "<change-folder>imap://other.com/INBOX<enter>"
```

**example.org.rc**
```
set imap_user = "USER"
set imap_pass = "PASSWORD"
unmailboxes *
set folder = imap://example.org/
```

**other.com.rc**
```
set imap_user = "USER"
set imap_pass = "PASSWORD"
unmailboxes *
set folder = imap://other.com/
```

**Actions to repeat**:
- Press <kbd>F5</kbd> -- See `example.org` inbox and folders in sidebar
- Press <kbd>F6</kbd> -- See `other.com` inbox and folders in sidebar
- Press <kbd>F5</kbd> -- See `example.org` inbox ONLY
- Press <kbd>F6</kbd> -- See `other.com` inbox ONLY

**Comment by gahr** [comment]
I'll look into this one

**Comment by gahr** [comment]
This works. The key is to move `unmailboxes` *before* `change-folder`, so it happens only once, and not every time `account-hook` gets called (which can be many).

**.muttrc**
```
account-hook imap://example.org 'source example.org.rc'
account-hook imap://other.com   'source other.com.rc'
macro index <F5> ":unmailboxes *<enter><change-folder>imap://example.org/INBOX<enter>"
macro index <F6> ":unmailboxes *<enter><change-folder>imap://other.com/INBOX<enter>"
```

**example.org.rc**
```
set imap_user = "USER"
set imap_pass = "PASSWORD"
set folder = imap://example.org/
```

**other.com.rc**
```
set imap_user = "USER"
set imap_pass = "PASSWORD"
set folder = imap://other.com/
```
