### ISSUE TITLE
lua version/requirments

### ISSUE THREAD

**Issue by ahmedelgabri** [neomutt/neomutt#1228]
I realized that `neomutt` has support for scripting through `lua` but this is missing from the `homebrew` [formula](https://github.com/Homebrew/homebrew-core/blob/5431542903ee2d6b7b9307165edcde44bcff7b32/Formula/neomutt.rb), so I'm planning to add this to the formula but I don't know which version is needed & if there is anything else I should take care of? 

the plan is to make this an optional flag like so

```
$ brew install neomutt --with-lua
```

**Comment by flatcap** [comment]
hi @ahmedelgabri 

> lua is missing from the homebrew formula

yes... but there's a complication.

When we offered the Formula to upstream Homebrew, they asked us to remove all the conditional parts of the build.
The majority of users use the default settings, so the packagers create a "bottle" for that case.
I think they'd like to see 1 package : 1 bottle.

We _could_ add it to the main Formula, but I'm not sure it's ready for prime time.

> I'm planning to add this to the formula

No need!  We have our own Formula in this repo: https://github.com/neomutt/homebrew-neomutt
It has lots of options including Lua.

It's (mostly) up-to-date; it has the current version of NeoMutt, but is missing a couple of new build options: `--idn2` and `--with-lock`.

I'll happily accept improvements to our Formula :-)

**Comment by ahmedelgabri** [comment]
> When we offered the Formula to upstream Homebrew, they asked us to remove all the conditional parts of the build.

I don't understand this part completely, so they didn't want stuff like this inside the formula or what? https://github.com/neomutt/homebrew-neomutt/blob/ca3d870c8f183d33d8daead3ff17d876d3aa40dc/Formula/neomutt.rb#L40-L62

> No need! We have our own Formula in this repo: https://github.com/neomutt/homebrew-neomutt
It has lots of options including Lua.
>
> It's (mostly) up-to-date; it has the current version of NeoMutt, but is missing a couple of new build options: `--idn2` and `--with-lock`.

Thanks! I didn't know about this one & of course I don't mind contributing to it. I just feel it will be better for everyone if have all of this in homebrew core if possible :)

**Comment by flatcap** [comment]
> so they didn't want stuff like this inside the formula or what?

Exactly.  I didn't enquire why not, but the maintainers were quite insistent.

> look at the vim formula

The existing Formulae still have plenty of options, including mutt!

> of course I don't mind contributing to it

great!

> I just feel it will be better for everyone if have all of this in homebrew core if possible :)

There are quite a few NeoMutt Homebrew users; we can take a poll.
If the consensus is "lua is good", then we'll make the change.

**Comment by ahmedelgabri** [comment]
Cool 👍 

I'll open a PR for `--idn2` & `--with-lock` today or tomorrow but couldn't find any info about the `--idn2`.

 for the `--with-lock` this is good `--with-lock-fcntl` & `--with-lock-flock` as new flags?

**Comment by flatcap** [comment]
IDN support is enabled by default, equivalent to `--idn`
To use the new IDN2 libraries (for IDNA2008 support), it should be as simple as:
`./configure --disable-idn --idn2`
