### ISSUE TITLE
Allow me to pin Important-flagged messages without disturbing sort settings

### ISSUE THREAD

**Issue by runderwo** [neomutt/neomutt#1235]
I want to flag messages as Important and pin them to the top without losing the normal sorting by thread and sort_aux by date.

Currently I would need to use sort or sort_aux to bubble flagged messages to the top as in https://www.linuxquestions.org/questions/linux-software-2/how-to-pin-a-message-on-the-top-in-mutt-274525/

But unfortunately this would force me to either disable threading or lose the sorting of threads by date.

Can't think of anything, but open to ideas

**Comment by gahr** [comment]
Would be nice to have, indeed

**Comment by flatcap** [comment]
Moving this to the long-term wish list.
