### ISSUE TITLE
Remove PgpSignature

### ISSUE THREAD

**Issue by yuzibo** [neomutt/neomutt#1238]
## What would you like to be able to do?

The PgpSignature is only used by the pgpring tool.
The pgpring tool is only needed by users of PGP2 and PGP5.
PGP5 is over twenty years old.

## What needs to change in NeoMutt?

- remove PgpSignature from ncrypt/pgplib.[ch]
- remove pgppubring.c
- update Makefile.autosetup
- remove contrib/pgp2.rc
- remove contrib/pgp5.rc
- remove contrib/pgp6.rc
- update contrib/Makefile.autosetup

## Additional Info

Cited from @flatcap

**Comment by flatcap** [comment]
Merged in cd1f31a86
