### ISSUE TITLE
notmuch: tag completion bugged if tag contains a dash

### ISSUE THREAD

**Issue by guiniol** [neomutt/neomutt#124]
When using 'modify-labels', the autocompletion doesn't handle dashes in the tags properly. For example, let's say I have the following tags: `attachment`, `neomutt-devel`, `neomutt-users`. If I start typing `+neo<TAB>`, here is what the autocompletion will show, in order:
1. `+neomutt-devel`
2. `+neomutt-neomutt-users`
If instead I type `+neomutt-`, here is what I will see:
1. `+neomutt-attachment`
2. `+neomutt-neomutt-devel`
3. `+neomutt-neomutt-neomutt-users`

**Comment by flatcap** [comment]
Please can you test [issue/124](https://github.com/neomutt/neomutt/tree/issue/XXX) and check that you're happy with the result.
```
git clone -b issue/124 https://github.com/neomutt/neomutt.git
cd neomutt
./prepare --enable-notmuch
make
```
