### ISSUE TITLE
Unexpected object file generated and can not be cleaned them

### ISSUE THREAD

**Issue by yuzibo** [neomutt/neomutt#1243]
## Expected Behaviour
I *think* after `make clean`, all object files should be removed at the same time.

## Actual Behaviour
After `make clean`:

```bash
ls *.o
charset.o  mbyte.o  mutt_idna.o  mutt_tags.o  parameter.o  rfc822.o  signal.o
```
In the home dir. And these files generated in mutt/ almost.

## How often does this happen?

- Always

And i open the issue to seek confirm that my thought is right.If yes, i will look into it.
Thanks

**Comment by gahr** [comment]
What's the mtime of those files? I suspect those were generated some time ago, before their respective source files were either moved to `mutt/` or renamed (e.g., `mutt_tags.c` -> `tags.c`).

I usually make distclean before updating, when I know that the update brings some changes in source file names / location.

**Comment by yuzibo** [comment]
Some days ago.
They are generated on 28 May.
Yes,  i think that you said  too.Maybe delete them once, they will never appear again

**Comment by gahr** [comment]
I fear the right question to ask would be: what version were you running on May 28th? :) Good to close I guess?

**Comment by yuzibo** [comment]
Thank you. :)
I will close it now
