### ISSUE TITLE
nntp: Too many open files (errno = 24)

### ISSUE THREAD

**Issue by hvkls** [neomutt/neomutt#125]
(I'm new to github, please bear with me!)

Since 1.7.0, I get "Too many open files (errno = 24)" errors on "change-newsgroup". 

1.6.2 (Release 2016-08-26 - Bug-Fix Release) still works.

Thanks you guys so much for neomutt!

**Comment by flatcap** [comment]
Thanks for the bug-report @hvkls 
I haven't seen this problem before.

> 1.6.2 (Release 2016-08-26 - Bug-Fix Release) still works.

OK, that's good to know.

How many newsgroups are there (roughly)?

Can you tell the output of these two commands:
```
ulimit -Sn
ulimit -Hn
```

They show how many open files you're allowed (soft and hard limits).

> Thanks you guys so much for neomutt!

You're welcome.

**Comment by hvkls** [comment]
I'm subscribed to about a dozen newgroups.

$ ulimit -Sn
256
$ ulimit -Hn
unlimited
$ uname -a
Darwin argo.fritz.box 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

This is Mac OS X 10.11.6.

**Comment by flatcap** [comment]
> $ ulimit -Hn
> unlimited
> Too many open files (errno = 24)

Thanks.  That doesn't make sense :-)
I'll keep thinking.

**Comment by hvkls** [comment]
FYI: Upstream mutt 1.7.0 + patch-1.7.0.vvv.nntp + patch-1.7.0.rr.compressed doesn't have the problem, either.

**Comment by hvkls** [comment]
No change w/ Sep 10, 2016 - Release - NeoMutt 2016-09-10 (1.7.0)

**Comment by flatcap** [comment]
Apologies.  The latest release doesn't contain any attempt to fix your problem.

I ported the NNTP patch to the new version of Mutt and sent my work to Vsevolod (months ago), but I didn't hear back from him.  Clearly our versions differ.

I'm going to have to carefully compare the two versions -- which I've been trying to avoid.
Feel free to keep embarrassing me by asking when it'll be ready :-)

**Comment by hvkls** [comment]
Thanks again, I appreciate it!

**Comment by flatcap** [comment]
Hi @hvkls 
I've started comparing the two nntp versions -- lots more to do.
The first thing that stood out was that I wasn't closing the message handles.
I was sure I'd checked this and found that they were closed automatically -- I may be wrong.

Please can you give this branch: [[issue/125](https://github.com/neomutt/neomutt/tree/issue/125)] a try and see if it fixes your problem.
Cheers.

**Comment by hvkls** [comment]
The "too many open files" error is gone!

But I experience a new mutt error "locale: unknown variable", both with and without "--enable-locales-fix".

Also, instead of umlauts like "ü", in newsgroups and some email messages, I'm presented "�" in the headers and "\374" in the bodies of some messages. Here's more information on one of these messages.

Content-Type: text/plain; charset=ISO-8859-15; format=flowed
Content-Transfer-Encoding: 8bit
User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:10.0) Gecko/20120129 Thunderbird/10.0

Finally, config.log

[config.log.txt](https://github.com/neomutt/neomutt/files/471288/config.log.txt)

**Comment by flatcap** [comment]
> The "too many open files" error is gone!

Hurray!

> new mutt error "locale: unknown variable"

Ah, yes.  That's an upstream Mutt change.
I only skimmed the **long** discussion on the mailing list.
`$locale` has gone in favour of `$attribution_locale`

Please give that a try and let me know if it doesn't work.

You can read more here: https://marc.info/?t=147164329700005&r=1

**Comment by hvkls** [comment]
The new variable seems to set LC_TIME in attributions (On ..., ... wrote). That's not my problem, though. The problem is either 

- mutt is enforcing standards, so lesser clients' faultily declared messages are displayed literally -- there used to be a patch called assumed_charset around to correct such things, once upon a time

- or mutt displays correct messages in a faulty way.

**Comment by flatcap** [comment]
Hmm...  of the 9 upstream commits I merged, only one f28b4ca alters the locale.
There's one line that probably wasn't getting called before:
```
setlocale (LC_ALL, "");
```

I've reverted this commit and pushed it to branch [[issue/125](https://github.com/neomutt/neomutt/tree/issue/125)].
See if this restores your umlauts.

If it does, then we have an upstream problem.
It would be useful if you can provide an email (mbox format) that shows the problem.

**Comment by hvkls** [comment]
No, that doesn't seem to change anything here.

Here comes a message:

Path: news.albasani.net!.POSTED!not-for-mail
Message-ID: <nr0q8p$oi5$1@news.albasani.net>
From: "H. W." <heiko2912@gmail.com>
Newsgroups: de.comp.sys.mac.misc
Subject: Drucker �ber LAN ansprechen
Date: Sat, 10 Sep 2016 13:17:34 +0200
Lines: 28
Organization: albasani.net
Mime-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-15; format=flowed
Content-Transfer-Encoding: 8bit
X-Trace: news.albasani.net
     346Cw2qGpJJXRZVBC/eOLjyVeq6rdeTxaSRAYTs45i+4qgabaP46ni2Y+4vo7uze53CJ8oB+5N9QDAEdjWaANQZbxH3eQ
0yHCK/hvJUN31bOSrVVOX0xMqy8DM3tA3jm
NNTP-Posting-Date: Sat, 10 Sep 2016 11:19:54 +0000 (UTC)
Injection-Info: news.albasani.net;
        logging-data="vXyIBztQq5uDAVhXv8OrEDw6igErhZzGbf1uftFHNpTaxI/wCQnkQQ1G8Av3VuX4Pdco+B03EJo44pp
vDe74xEWI6RL0CM038ItmER3IBBedp1kCu0+WlspKlSXq8+Na";
        mail-complaints-to="abuse@albasani.net"
User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:10.0) Gecko/20120129 Thunderbird/10.0
Cancel-Lock: sha1:9aun9rSwsDu3eofn8BGVP8BKeNY=
Xref: argo.local.lan de.comp.sys.mac.misc:26791

Hallo Leute,

hier laufen u. A. im LAN ein Windows-Rechner und ein MacBook Pro mit OSX
10.11, incl. aller Updates.
Auf dem Windowsrechner ist der Drucker f\374r das LAN freigegeben und so
eingestellt, dass Jeder vollen Zugriff auf den Drucker hat.
In OSX ist der Drucker entsprechend eingerichtet und ich kann auch mittels
vorschau.app, Pages, Numbers, textedit usw. kann auch problemlos gedruckt
werden.
Aber es gibt auf dem Mac 2 Perogramme, die beim besten Willen nicht drucken
wollen: "Awery Design and Print" und "Adobe Acrobat DC". Beide Programme
verlangen  eine Autentifizierung. Allerdings habe ich nirgendwo die
M\366glichkeit gefunden, Benutzername und Passwort einzugeben.
Also habe ich den Drucker gel\366scht und neu eingrichtet, dieses Mal mit
"smb://heiko:kennwort@server/Canon_iX4000

Nach wie vor kann ich problemlos drucken, aber die beiden o. g. genannten
Programme wollen nach wie vor eine Autentifizierung. Allerdings dauert die
Nachfrage der Autentifizierung nun etwa 4 Minuten, bis sie erscheint und eine
weitere Minute sp\344ter wird der Druckvorgang abgebrochen.

Benutzername und Kennwort sind die selben, die ich zum Anmelden  auf den
Windowsrechner nutze und sind eindeutig korrekt.
Hat jemand noch eine Idee, wie ich mein Problem l\366sen kann?

Gru\337
Heiko



Am 24.08.16 um 18:16 sprach Troll Joerg Lorenz:
>> PS: Ein anderes Problem - ein 'mit biblischen Sendungsbewusstsein
>> behafteter Troll' verwendet auch MacSOUP, da landet man schnell
>> ungewollt im Killfile mit dem Viele diesen Troll ausblenden.
>>
> Daf?r brauchst *Du* Deinen Client nicht zu wechseln.

LOL

Hast mal irgendwo mal wieder eine auf deine Finger gepratzelt bekommen 
.... ROTFL

-- 
Fritz
?Die Welt ist gro? genug f?r die Bed?rfnisse aller, aber zu klein f?r 
die Gier Einzelner? - Mahatma Gandhi

**Comment by flatcap** [comment]
I'm not sure that email survived the pasting.  It doesn't matter, I've found an [online copy](https://groups.google.com/forum/message/raw?msg=de.comp.sys.mac.misc/fBUPhC6TT3Y/qROjrYGPBQAJ)

I can't get that email to render correctly in Mutt.  I tried old versions of NeoMutt, then went through the versions of Mutt: 1.7.0, 1.6.2, 1.5.24.

However, using the latest NeoMutt code (including all the Mutt changes), I went to a German newsgroup, then a Slovak one, followed by a Vietnamese group.  All the characters rendered correctly for me in my `en_GB.UTF-8` locale.

Update: I can get the email to render if I **correct** the content type.  The message is in utf-8, but the header says:
```
Content-Type: text/plain; charset="iso-8859-1"
```

Change that to:
```
Content-Type: text/plain; charset="utf-8"
```
and it works correctly.  I'm not sure what Mutt's meant to do with broken headers.  You may want to ask on the mailing list or #mutt on freenode.net

Gruß,
  Rich

**Comment by hvkls** [comment]
Your persistence is unmatched. Please give 1.5.21 a try!

What do you think about the assumed_charset patch I used in the past, https://dev.mutt.org/trac/wiki/MuttFaq/Charset

**Comment by flatcap** [comment]
> Your persistence is unmatched.

Thanks :-)

> Please give 1.5.21 a try!

Alas my history with Mutt doesn't go that far back.

> What do you think about the assumed_charset patch I used in the past

It's been part of Mutt for years, but I don't know anything about it.
Playing with the setting didn't affect the rendering.
However, deleting the "Content-Type:" header line **did** make it render correctly.

The end.

If you have any rendering problems, feel free to open a separate issue.
I'll close this issue on the next NeoMutt release -- probably this evening.
