### ISSUE TITLE
create an smtp_user variable that would allow slashes(/) 

### ISSUE THREAD

**Issue by lrosenman** [neomutt/neomutt#1252]
FreeBSD's mail server allows us to use a "mail principal" (E.G. ler/mail) instead of our bare username (E.G. ler).  This allows a separate password to be used JUST for mail.

## What needs to change in NeoMutt?

allow a smtp_user variable analogous to smtp_password that allows /'s
## Have you tried any alternative methods?

I tried smtp_url=smtp://ler/mail:&lt;password&gt;@smtp.freebsd.org:587

and

smtp_url=smtp://"ler/mail":&lt;password&gt;@smtp.freebsd.org:587

Both failed on failed to find host ler.

**Comment by flatcap** [comment]
Hmm... I can see how that slash might upset our URI parser.
I was going to suggest setting "smtp_user", but it doesn't exist!

Have you tried escaping it?
- `smtp_url=smtp://ler\/mail:<password>@smtp.freebsd.org:587`
or perhaps hex-encoding?
- `smtp_url=smtp://ler%2Fmail:<password>@smtp.freebsd.org:587`

**Comment by lrosenman** [comment]
I did try
`smtp_url=smtp://ler\/mail:<password>@smtp.freebsd.org:587`
with no luck, however:

`smtp_url=smtp://ler%2Fmail:<password>@smtp.freebsd.org:587` does work.

**Comment by lrosenman** [comment]
the 2nd line in your comment was why I filed this as a suggestion

**Comment by louis77** [comment]
$smtp_user was introduced in #2099 and published with the 2020-03-13 release.
