### ISSUE TITLE
trash folder doesn't work

### ISSUE THREAD

**Issue by l2dy** [neomutt/neomutt#1253]
## Expected Behaviour
When `trash` is set, mail is moved to trash folder after marked for deletion.

## Actual Behaviour
When `trash` is set, mail is directly deleted.

## Steps to Reproduce
1. Delete a mail
2. Open the trash folder

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?
20180512

## NeoMutt Version
1c3dbec59739c1db601d667920a14a3b082e6303

## Extra Info

* Operating System and its version
```
ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77
```
* Were you using multiple copies of NeoMutt at once?
No.
* Were you using 'screen' or 'tmux'?
No.
* Is your email local (maildir) or remote (IMAP)?
Local.

**Comment by flatcap** [comment]
Bisecting gives me: 67cb19912 which was a surprise!
