### ISSUE TITLE
`f`orwarding a message doesn't include its attachments

### ISSUE THREAD

**Issue by l29ah** [neomutt/neomutt#1258]
## What needs to change in NeoMutt?

If i `f`orward a message, i generally expect it to include all the attachments or at least asks me whether i want to leave them out, but neomutt silently leaves them. It would be nice if this behaviour could be configurable at least.

## Have you tried any alternative methods?

It is possible to open the message, `v`iew the attachment list, `t`ag the individual attachments and then `f`orward them, but it is really inconvenient, as one must always remember that a simple `f` one's usually using will not do the thing for the messages with attachments, that don't usually come often.

**Comment by mschilli87** [comment]
One workaround is to forward the message as an attachment which will include its own attachments.

**Comment by gahr** [comment]
`set mime_forward=yes` will forward the original message as a message/rfc822 tree

**Comment by sampablokuper** [comment]
IMO, this issue should be reopened, because is not fixed. Neither of the two workarounds suggested is satisfactory, as noted in the feature request that I opened [upstream](https://gitlab.com/muttmua/mutt/issues/97).

Ideally, the issue will end up being fixed in both Mutt and Neomutt. Until the latter is fixed, this issue report should stay open.

**Comment by jaromil** [comment]
Hi there, despite the fixes I think current neomutt (built with git HEAD to 42892c6b5c0b7be8f4de331fca84959c05b96e56) does not forward attachments along with email. I have tried using both settings mentioned here and upstream:
```
set mime_forward = ask-yes
set forward_attachments = yes
```

**Comment by gahr** [comment]
`set mime_forward = no`
`set forward_attachments = yes`

Does forward the original email (in the body) + any attachments of the original email (as attachments).

I guess what you'd like to have is like`mime_forward = yes` where the original email is attached, but including all attachments?
