### ISSUE TITLE
Feature discussion: ignore / kill thread

### ISSUE THREAD

**Issue by kronat** [neomutt/neomutt#126]
I'd love a feature, similar to the gmail "ignore thread", in mutt/neomutt. Basically, it's for threads that you don't want to read: in Gmail, when enabled, it marks as read all the thread, and for any subsequent reply to that thread, mark as read and archive the replies.

What is the opinion of developers? Here are different approaches:
- Feature request on debian (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=153887)
- a patch for mutt 5.21 (https://github.com/aur-archive/mutt-ignore-thread/blob/master/ignore-thread-1.5.21.patch)
- another patch (http://www.gentryx.de/news_mute_a_la_google_mail.html)
- folder hook (http://devnull.li/~jerojasro/blog/posts/mutt_mute_thread/)

**Comment by P-EB** [comment]
That looks interesting. With a specific option giving the archive mailbox it could be really useful. The main thing is to keep track of the ignored threads somewhere (a database, probably) in order to help mutt identify any new message it should mark as read immediately, and move if asked to.

**Comment by flatcap** [comment]
Here are some thoughts:

## One Folder

Either:
- Add a header to an email, e.g. X-Muted: yes
- Add the message id to a database

Both these methods would allow you to mute an entire thread, or even just a
sub-thread where someone goes off-topic.

When a new email arrives, all of its parents are checked for being muted.
Messages addressed to you could be unmuted.

Combine this method with a folder-hook:
- Close all muted threads
- Delete muted threads older than 'n' days

---

## Multiple Folders

Two folders: A viewing folder and an archive.

Muting a thread moves it to the archive.
Any email in the archive is muted.

Any new emails must be checked to see if they're "In-Reply-To" a muted email.
If they are, they too are archived (unless they're addressed to you).

Either
- Need database of message ids
- Read the archive folder

Does the header cache contain the message id?
Could we scan the cache of the archive?

**Comment by kdave** [comment]
I'm interested in the thread ingoring feature (I used to port the patch but it did not work over time).

Let me share some thoughts and requirements that would improve usability (IMHO):

* marking a thread as muted/ignored will lead to any new mail to that thread set as 'read' (expansion status of the thread is unchanged).

* the 'muted' status is persistent, eg. stored in headers

* I don't necessarily need automatic moving to the archive, I can do that manually (so 'limit' should be able to show muted mails), eg. if I want to review "what I missed (or not)"

* (not sure about this) new mail to a mailbox that's not currently open should also mark the messages as muted; alternatively, there would be a command to go through all mails and mark them

* I don't necessarily need the external database of ids (though it could be generated from a mailbox on demand)

* a mail that won't be marked as muted is not a problem, just an inconvenience

IIRC from the patch, it was possible to set a color to the mail (making it a bit more dimmed for example), skip the mails when moving (as if they were deleted, so K or J could be used to enter them), muted threads are by default folded.

**Comment by flatcap** [comment]
It's a good idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).

**Comment by cdown** [comment]
For what it's worth, I made a small script (Gmail-specific, since it uses `X-GM-*` attributes and Gmail's own muting functionality) that can be called from `pipe-message` to do this: https://github.com/cdown/gmute

Obviously it doesn't solve the problem for non-Gmail users, but hopefully this will help out some people who find this issue.
