### ISSUE TITLE
environment variable inside backtick doesn't work anymore

### ISSUE THREAD

**Issue by sileht** [neomutt/neomutt#1262]
The behavior of '$' inside backtick have changed:

## Steps to Reproduce

My environment have `ENV_VAR` set to `foo` and my muttrc have :
```
set my_var = `echo ${ENV_VAR}`
```

## Expected Behaviour

`my_var` should be `foo`

## Actual Behaviour

`my_var` is currently it's empty

## How often does this happen?

- Always

## When did it start to happen?

This behavior change have been introduced by 0597b6375971ca1d3f610fbcc83dd7f1f4e770ca

**Comment by sileht** [comment]
My current workaround is to escape the '$' with '\$'.

But this behavior change is going to break a lot of people I guess. So it should be reverted, or the breakage and the workaround well documented .

**Comment by flatcap** [comment]
I had a think about this...

We're about to pass the string to the shell, so we want NeoMutt config expanded, but not the shell env.

So:
- ```set my_var = `echo $TZ $folder` ```
the shell should see:
- `echo $TZ /home/user/mail`
and `my_var` would be set to
- `Europe/London /home/user/mail`

This means that shell expansions such as `${ACCOUNT:=sileht}` would be correctly expanded by the shell.

**Comment by sileht** [comment]
I just test the fix, with `export ACCOUNT="foobar"` and the muttrc:
```
set my_var = `echo ${ACCOUNT:=sileht}`
```

and I got `foobar:=sileht `instead of `foobar`

**Comment by flatcap** [comment]
Update:
```
set my_var="`echo $TZ ${SHELL} ${TZ2:-missing} $folder`"
```
now makes:
```
my_var="Europe/London /bin/bash missing /home/user/mail"
```
