### ISSUE TITLE
Can't seek to last message in index

### ISSUE THREAD

**Issue by caliston** [neomutt/neomutt#1265]
## Expected Behaviour

Start neomutt with no .muttrc
Neomutt displays the 1998 messages in my /var/spool/mail
Type '1998'
Neomutt should move the selection bar down to the last message in my mailbox

## Actual Behaviour

Neomutt reported 'invalid message number'
If I type '1997' I successfully seek to that message.
If I then press the down arrow, I can move onto message number 1998.
I can then open the message successfully

## How often does this happen?

- Always

## When did it start to happen?

I have compiled and run Neomutt for the first time.
(I'm linking statically and copying binaries across to a machine where I don't have root)

## NeoMutt Version

$ neomutt -v
NeoMutt 20180512
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 3.16.0-6-amd64 (x86_64)
ncurses: ncurses 6.1.20180210 (compiled with 6.1.20180210)
libidn: 1.33 (compiled with 1.33)

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 7.3.0-21' --with-
bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,b
rig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program
-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-bu
ild-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix -
-libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-lib
stdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enab
le-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --e
nable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=
auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --wi
th-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-off
load-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=
x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Debian 7.3.0-21) 

Configure options: --prefix=/u3/theom/local/

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIO
NS__  -DNCURSES_WIDECHAR -I/u3/theom/local//include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls -gpgme -gss -hcache -homespool +idn -locales_hack -lua +meta 
  -mixmaster +nls -notmuch -openssl +pgp -sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/u3/theom/local//share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/u3/theom/local//etc"

## Extra Info

Debian jessie.  I'm using tmux, but trying it without makes no difference.
Mail is all local.

**Comment by mschilli87** [comment]
duplicate of https://github.com/neomutt/neomutt/issues/1261, fixed by https://github.com/neomutt/neomutt/commit/766aec957301a03b3bd058ff8d7bc74724261720?

**Comment by flatcap** [comment]
Thanks for the bug report.
We spotted the bug and fixed it a few days ago.
There's a new release coming out at the end of the week.

**Comment by caliston** [comment]
Thanks, seems like a race condition with the other bug report!
