### ISSUE TITLE
Messages missing gettext() translation

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1276]
Some message strings are missing `_()` gettext translation.

- alias.c: `mutt_message("Trouble adding alias: %s.", strerror(errno));`
- copy.c: `mutt_error("The length calculation was wrong by %ld bytes", fail);`
- init.c: `mutt_error("Error: impossible to build path of '%s'.", rcfile_path);`
- init.c: `mutt_error("Error: Cyclic sourcing of configuration file '%s'.", rcfile);`
- init.c: `mutt_error("Error: %s", err->data);`

There may be others.

---

Please make a branch from **translate** for this work.

**Comment by mgedmin** [comment]
The "length calculation was wrong by %ld bytes" translation ought to use `ngettext`.

**Comment by flatcap** [comment]
Fixed by 8d23f73fc
