### ISSUE TITLE
What the heck is "pkspxycwrap"?

### ISSUE THREAD

**Issue by BertramScharpf** [neomutt/neomutt#1278]
In contrib/gpg.rc and in many configuration examples you can find on the web, there is a parameter that is always commented out:
```
  # set pgp_getkeys_command="pkspxycwrap %r"
```
The line was last edited in July 2001. When I ask Google for the tool "pkspxycwrap" I find an unanswered question on the Debian mailing list from February 2001, but nothing about where I can get this tool.

As far as I see, I can safely remove the option and the whole code using it. Any caveats?

**Comment by flatcap** [comment]
That's a shock.  It looks like someone just hit the keyboard.
It was introduced in 1944343a3 (2001-07-29)
The previous version referenced a `wrap.sh` which has never existed in the source.

The example ought to say: `set pgp_getkeys_command="gpg --recv-keys %r"`

> I can safely remove the option and the whole code using it.

No, the command is still referenced in the code.
- `ci_send_message()`
- `crypt_get_keys()`
- `crypt_pgp_find_keys()`
- `pgp_class_find_keys()`
- `pgp_class_invoke_getkeys()`
- `mutt_pgp_command()` -- used here

Is there anything else that needs fixing in that file?

**Comment by BertramScharpf** [comment]
> Is there anything else that needs fixing in that file?

Not as far as I see now. I'm hopeful that bugs like this one showing up will come to an end in the near future.

The longer I think about it, the more I'm convinced that almost nobody made use of Mutt's encryption facilities in the past.

**Comment by mschilli87** [comment]
@BertramScharpf 
> The longer I think about it, the more I'm convinced that almost nobody made use of Mutt's encryption facilities in the past.

I guess this is also due to confusing documentation.
I set it up someday somehow and it worked for years, then stopped working and I never figured out why and how to fix it. :disappointed:

**Comment by Dabsen** [comment]
> The example ought to say: `set pgp_getkeys_command="gpg --recv-keys %r"`
> 

I am not convinced. The documentation says that this function is intended to find a key from an email address. From the neomuttrc man page:
>
> This  command is invoked whenever NeoMutt needs to fetch the public key associated with an email > address.  Of the sequences supported by $pgp_decode_command, %r is the only printf(3)-like
> sequence used with this format.  Note that in this case, %r expands to the email address, not the 
> public key ID (the key ID is unknown, which is why NeoMutt is invoking this command). 

So `gpg --search-keys %r` would be more appropriate, except that it is an interactive command producing a prompt, which doesn't play nice with Mutt. Perhaps the non-existent wrapper script was designed to get around this issue. Anyhow, I never used this setting; I tried just now, and actually setting it produces the strange result that mutt calls the command whenever it sees a signature, even if the signing key is known to gpg. Something must escape me.

**Comment by mickmattes** [comment]
After ~9 months, I dare to ask: Will we ever see any answer to Dabsen's comment?
