### ISSUE TITLE
Neomutt version missing

### ISSUE THREAD

**Issue by dejadejoder** [neomutt/neomutt#128]
Hi, the mutt version seems to be missing...
```
neomutt-neomutt-20160827$ ./mutt -v
NeoMutt UNKNOWN ()
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.
```
Compiled with:
```
$ ./prepare  --enable-notmuch --enable-compressed --enable-sidebar --enable-hcache
$ make -j4
```

**Comment by flatcap** [comment]
Ah, yes.  Sorry about that.
We've been changing how the version string is created.
It works well if you compile from git :-)
We'll fix it by the next release.

For now, if you:
```
echo 20160827 > .tarball-version
./configure {OPTIONS}
make
```
you'll get a partial version string: "NeoMutt 20160827 ()"

**Comment by dejadejoder** [comment]
Ok, thanks!

**Comment by flatcap** [comment]
The version numbers are fixed for now (all the cleverness is turned off).
