### ISSUE TITLE
Automatic GPG key discovery

### ISSUE THREAD

**Issue by wiktor-k** [neomutt/neomutt#1282]
## What would you like to be able to do?

I'd like NeoMutt to automatically download GPG key using [Web Key Directory protocol](https://datatracker.ietf.org/doc/draft-koch-openpgp-webkey-service/) when composing new e-mail. This  is as easy as calling `gpg --locate-key $EMAIL`. Gpg will fetch the key via *HTTPS* from the *$EMAIL's domain*.

This method of easy & accurate fetching keys is already used by Enigmail (for Thunderbird) and GpgOL (for Outlook).

## What needs to change in NeoMutt?

Enigmail fetches the key when an e-mail address is entered for an newly composed e-mail. NeoMutt can use a similar approach.

## Have you tried any alternative methods?

- Macros
- Hooks
- Scripts

Nope, but I'm open for suggestions how it should be done in a NeoMutt-way.

## Additional Info

[Web Key Directory is a draft](https://datatracker.ietf.org/doc/draft-koch-openpgp-webkey-service/) for a new key discovery scheme (implemented e.g. in new gnupg). It is similar to HKP but instead of querying the keyserver it queries the domain from the UID's e-mail address. The difference is that WKS returns binary data and HKP ASCII-armored.

For example, when looking for key for `Joe.Doe@Example.ORG` the key would be fetched from `https://example.org/.well-known/openpgpkey/hu/iy9q119eutrkn8s1mk4r39qejnbu3n5q`.

Several services (like kernel.org) already have WKD support, for example Linus' key is at: https://kernel.org/.well-known/openpgpkey/hu/pf113mfnx1f3eb1yiwhsipa91xfc7o4x. Some third party services like posteo.de [support WKD too](https://posteo.de/.well-known/openpgpkey/). WKD is also [supported by Enigmail](https://www.gnupg.org/blog/20170803-web-key-in-enigmail.html).

**Comment by wiktor-k** [comment]
From my cursory look it seems setting [`gpgme_set_keylist_mode`](https://www.gnupg.org/documentation/manuals/gpgme/Key-Listing-Mode.html) to `GPGME_KEYLIST_MODE_LOCATE` might help.

I'm checking this right now but currently neomutt built from master can't select a key given my correct key ID (`key not found` even though it's in `gpg -k`, probably problem between keyboard and chair ;) ).

There are some more places where automatic key retrieval could be added, for example `OP_EXTRACT_KEYS` that is frequently used for messages from new contacts could - in case the key is not attached - fetch the key from keyservers (just like `gpg --auto-key-retrieve`)... but that's probably another ticket after I get more familiar with the code structure ;)

**Comment by wiktor-k** [comment]
Hmm I found that [`pgp_getkeys_command`](https://github.com/neomutt/neomutt/blob/c682538594641420c993c56afbf3ceeb0ec39fbe/contrib/gpg.rc#L117) can somehow be abused for key retrieval (using `gpg --locate-key %r`), the output looks bad, and the key is not trusted after import, but exiting, setting ownertrust and re-trying works... somehow.

**Comment by flatcap** [comment]
This was discussed on upstream Mutt's mailing list.
Quite a few people expressed concerns over security.

**Comment by bernhardreiter** [comment]
@flatcap, the concerns about security were addressed on the mutt mailinglist.

The main concern being that someone may learn from network traffic whom a users wants to send an email to. WKD addresses this by: 
 * only the first time
 * the smtp traffic will already reveal on the network when I'm sending an email to a specific host.
 * WKD uses https, so it is only the intention of contacting or verifying a user from the host it contacts.

Additionally adding a way to easily get an OpenPGP pubkey via WKD adds to security, because the chance is higher that the email will get encrypted.

So it is the other way around: **not** adding an easy way to use WKD is a security concern. ;-)
