### ISSUE TITLE
Mailcap bash script not working as expected...

### ISSUE THREAD

**Issue by kflak** [neomutt/neomutt#1287]
Before asking a question, please check:

- NeoMutt Guide: https://neomutt.org/guide/
- Google:        https://www.google.com/

Hi,

First time question here, so please bear with me if I am making a stupid or two... I am having trouble with getting a bash script working in mailcap.

This works in mailcap:
`application/pdf; mkdir -p /tmp/neomutt-arch \; rm /tmp/neomutt-arch/* \; cp %s /tmp/neomutt-arch \; zathura /tmp/neomutt-arch/$(basename %s) &`

However, encapsulating the functionality in a bash script doesn't. The problem seems to be that the file is not copied to the tmp-directory...

```
#!/bin/bash

application=$1
file=$2
tempdir=/tmp/neomutt-arch
newfile=$tempdir/$(basename $file)
mkdir -p $tempdir
rm -f $tempdir/*
cp $file $newfile
$application $newfile
```

and running it from mailcap:

`application/pdf; attachmentlauncher.sh zathura %s &`

I'm doing this on Arch Linux, latest versions of everything.
Any thoughts on why this wouldn't work?

Best,
Kenneth

**Comment by mschilli87** [comment]
@kflak:

1. Does the script work from command line (outside NeoMutt)?
2. Is is executable (`chmod +x`) and on `PATH` (`which attachmentlauncher.sh`)?
3. Do you get any error messages that could help track this down?
4. What makes you think that
 > [t]he problem seems to be that the file is not copied to the tmp-directory...

?

**Comment by kflak** [comment]
Hi,

Thanks for the quick reply!

The script works as intended on the command line, it is executable and in the PATH. The error message I am getting is f.x.:
`error: Unknown file type: 'cannot open '/tmp/neomutt-arch/BoardingPass.pdf' (No such file or directory)'`
BoardingPass.pdf being the attachment in this particular case. 

All other effects of the script work when running it from neomutt: The tmp directory is emptied or created as necessary, and zathura is opening up, however nothing is being copied to the tmp-dir, and I don't really understand why this would be. I have tried to set different tmp directories, to exclude the possibility of it being a permissions issue.

**Comment by flatcap** [comment]
Ah, sometimes NeoMutt is too quick for its own good.
It creates a temp file, runs the mailcap program and deletes the temp file.

Some programs start up really quickly but don't actually open the temp file in time (before it gets deleted).  A common solution is to sleep for a couple of seconds:

Try:
```
application/pdf; attachmentlauncher.sh zathura %s & sleep 2
```

That gives the program a chance to open the file.
Once the file is open, the program usually doesn't care if it gets deleted.

**Comment by kflak** [comment]
Excellent! Thank you very much, that solves the problem. I vaguely remember having read something like that, so I tried sleeping at various points inside the script, didn't think about adding the sleep in the mailcap itself...

**Comment by mschilli87** [comment]
@flatcap: Why would the file be deleted by NeoMutt at all? AFAICT, NeoMutt shouldn't even now of the file in question as `tempdir` is defined *internally* in `attachmentlauncher.sh`. So I would actually expect the file to stick around even after closing NeoMutt until I view the next attachment calling `attachmentlauncher.sh` which would `rm -f $tempdir/*` *before* copying said new attachment to `tmpdir`.

**Comment by flatcap** [comment]
If the user asks to save an attachment, we create the file and the user takes ownership.
(the user gets to choose its name and location)

When viewing a attachment the implication is that this is temporary -- the user might be searching for something -- so we clean up after.  Otherwise /tmp would fill up with files that nobody wants.
(the name might be random, and the location is the tmp dir)

Unless the user asks for a file, it shouldn't persist.

I've experimented with a smarter solution (but I need a volunteer to add it to neomutt), which tracks the process id of the mailcap program.  The file is deleted when the program finishes, or neomutt finishes.

**Comment by mschilli87** [comment]
I understand the general idea but but I figured as `attachmentlauncher.sh` creates *another* copy of that (temporary) attachment file at a location unknown to NeoMutt and tries to open *that* copy, I figured it should overwrite NeoMutts default behaviour.

**Comment by flatcap** [comment]
Yes, the script does things that neomutt can't see, so the _copy_ is safe from deletion.

**Comment by mschilli87** [comment]
Then how come it throws a 'file not found' for the *copy* without the `sleep` call?

**Comment by flatcap** [comment]
Ah, because of the `&`.  The script is being run in the background, so it returns immediately.
NeoMutt's deleting the file before the `cp` can happen.

**Comment by mschilli87** [comment]
@flatcap: Thank you! I completely missed that. Now my sanity is restored. :wink:

**Comment by wgmayer0** [comment]
Thanks @flatcap! I had a post on this that I never got resolved but this solved my problem by adding a sleep!
