### ISSUE TITLE
setenv stopped working

### ISSUE THREAD

**Issue by doronbehar** [neomutt/neomutt#1288]
Since https://github.com/neomutt/neomutt/issues/1014#issuecomment-359039399, I'm dependent on an environmental variable for my mails decryption.

I'm sure `setenv` doesn't do it's job since the last release because the following command fails when `neomutt` is running:
```sh
grep TEST_ENV_VAR /proc/$(pidof neomutt)/environ
```
while your `neomuttrc` has:
```
setenv TEST_ENV_VAR bla
```

**Comment by flatcap** [comment]
> I'm sure setenv doesn't do it's job

Ah, it does and it doesn't.
The variables are set:
- Just before the child is run
- Only in the child process

> ... since the last release

You had me confused for bit there.
I've checked back through all the versions of (neo)mutt.
The variables have always been kept separate from neomutt's _own_ environment.

**Comment by doronbehar** [comment]
Then from some reason I've began to get the same errors as reported initially in #1014. It means the my `pinentry` script reads doesn't have the environment it should.
