### ISSUE TITLE
Saving tagged messages results in duplicates in target folder

### ISSUE THREAD

**Issue by hvhaugwitz** [neomutt/neomutt#129]
Hello,

when moving tagged messages (by typing `;` followed by `s`) the messages are correctly marked as Deleted in the current folder but saved twice in the target folder. 

Using NeoMutt  (1.7.0) on Debian Sid

Best regards

Hannes

**Comment by riesebie** [comment]
* Hannes von Haugwitz <notifications@github.com> [2016-09-01 09:35 -0700]:

> Hello,
> 
> when moving tagged messages (by typing `;` followed by `s`) the
> messages are correctly marked as Deleted in the current folder but
> saved twice in the target folder. 
> 
> Using NeoMutt  (1.7.0) on Debian Sid

Could you please address this in the Debian BTS as well, so that a
possible fix is documented there. Antonio is very active in fixing
debian bugs at the moment.

Elimar
-- 
  355/113: Not the famous irrational number pi,
           but an incredible simulation!
	                -unknown

**Comment by dejadejoder** [comment]
I can confirm this bug (Debian Jessie).
It is not present on official mutt 1.7.0.
Remember to use 'D~=' to remove duplicates until bug is fixed.

**Comment by P-EB** [comment]
Does it happen exclusively with tagged-save or saving a single message result in the same thing?

**Comment by dejadejoder** [comment]
Indeed, it happen exclusively with tagged-save.
Saving a single message doesn't create duplicates.

Pierre-Elliott Bécue <notifications@github.com> | 02/09/2016 - 15:45:45 (-0700):

**Comment by flatcap** [comment]
OK, found it, fixed it.
It was due to a dodgy merge which left two copies of mutt_save_message() in the code.

**Comment by mvdan** [comment]
I just ran into this and was about to open a new issue. You guys are fast at fixing bugs!

**Comment by flatcap** [comment]
@mvdan 

> I just ran into this and was about to open a new issue

Thanks for taking the time to search.

> You guys are fast at fixing bugs!

We try :-)

The next release is planned for the end of the week.

**Comment by hvhaugwitz** [comment]
Thanks for the fix (I successfully tested it on remote IMAP folders).
