### ISSUE TITLE
[Regression] sendmail receives empty message

### ISSUE THREAD

**Issue by protist** [neomutt/neomutt#1295]
## Expected Behaviour

I've previously used a [custom sendmail](https://unix.stackexchange.com/a/241632), which has worked fine with the previous version of Neomutt.

## Actual Behaviour

With the latest version of Neomutt, the sendmail fails silently.

## Steps to Reproduce

Send an email using the above sendmail.

Relevant snippet from `~/.mutt/muttrc`:
```
set sendmail = "~/.local/bin/msmtp_error_checking"
set envelope_from = "yes"
set sendmail_wait=-1
```

Full troubleshooting follows at end of issue report.

## How often does this happen?

- Always

## When did it start to happen?

When I upgraded from 20180622 to 20180716. I attempted installing the old version, and it works fine again.

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.14.55-1-lts (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.34 (compiled with 1.34)
hcache backends: gdbm

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 8.1.1 20180531 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn=/usr --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

The old, working version is identical, except for the version string.

## Extra Info

* Operating System and its version: up-to-date Arch Linux.
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? IMAP

## Troubleshooting

I tested a second, custom script as follows, setting it to `sendmail` in `~/.mutt/muttrc`.

```
#!/bin/bash
echo $@ > /tmp/args
cat >/tmp/piped
```
When I tested the previous version of Neomutt, both files are created as expected, with the message in `/tmp/piped`, and the recipients, etc. in `/tmp/args`. However, in the new version of Neomutt, there are no arguments, nor piped message. Oddly enough, using `msmtp` directly as the `sendmail` works fine in the new Neomutt.

**Comment by flatcap** [comment]
Please can you give branch [issue/1295] a try.

**Comment by protist** [comment]
@flatcap that works perfectly! Thank you for the quick fix.

**Comment by protist** [comment]
This regression has appeared again somewhere before 48b01140f. I don't have time right now to bisect, but I can do it in the next day or so, unless someone already has an idea where it might have been introduced.

**Comment by flatcap** [comment]
Bisected to: 86ec93c1 don't expand commands, leave it to the shell

**Comment by flatcap** [comment]
I've just pushed:
- 0dd652609 fix command/path expansion

which should solve your problem.

**Comment by protist** [comment]
No worries. Thanks again for the quick response! Yes, replacing `~` with `$HOME` fixes it for me in the second latest commit. And that last commit fixes it too (reverting the config to `~` again). Thank you for quick fix!

**Comment by protist** [comment]
Also, these issues are extremely infrequent historically, but I was wondering if it would be worth having some kind of error-checking mechanism if email is not passed to the `sendmail` command. I'm not sure if both the issues in this thread are related, so I'm not sure if this is feasible (or even desirable). I'm just mentioning it because I thought I had sent email to people. I'd then wonder why they hadn't responded, because there was no error in neomutt.

**Comment by flatcap** [comment]
> some kind of error-checking mechanism

Yes.  I'm surprised that there isn't an error when neomutt fails to run a command.
It seems to default to the real sendmail.

That means your 'lost' emails have probably be queued somewhere.

**Comment by protist** [comment]
Ah okay. Would you like me to open up a new issue, or this something that is better left alone?

**Comment by flatcap** [comment]
Yes, please open an issue.  Something needs doing (but I'm not sure what, yet).
