### ISSUE TITLE
Neomutt, IMAP, HTML e-mails and Firefox

### ISSUE THREAD

**Issue by 0x747972** [neomutt/neomutt#1298]
## Expected Behaviour

I try to open an HTML e-mail in Firefox.

## Actual Behaviour

When a Firefox instance is running, the file is non-existant on the first try,
at best it can be opened on the second try, at worst on the n-th try.

## Steps to Reproduce

Write something like "text/html; firefox-bin %s;" to .mailcap

## How often does this happen?

- Always

## When did it start to happen?

This happens since I started reading HTML e-mail with Firefox.

## NeoMutt Version

NeoMutt 20180622
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.15.6-gentoo (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
hcache backends: gdbm, bdb

Compiler:
x86_64-pc-linux-gnu-gcc (Gentoo 7.3.0-r3 p1.4) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/neomutt-20180622 --libdir=/usr/lib64 --disable-doc --enable-nls --disable-notmuch --disable-gpgme --disable-pgp --disable-smime --enable-bdb --enable-gdbm --disable-kyotocabinet --disable-qdbm --disable-tokyocabinet --disable-idn --disable-gss --disable-lmdb --enable-sasl --with-ui=ncurses --sysconfdir=/etc/neomutt --enable-ssl --disable-gnutls

Compilation CFLAGS: -O2 -pipe -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls -gpgme -gss +hcache -homespool -idn -locales_hack -lua +meta 
  -mixmaster +nls -notmuch +openssl -pgp +sasl -smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc/neomutt"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

## Extra Info

Neomutt on gentoo. Only one neomutt session at a time.
I access my mail directly over IMAP with Neomutt. (That might be important.)
If knew what I was talking about, I would guess that this is some kind of race condition.

**Comment by flatcap** [comment]
Hi @0x747972.
What you have there is a timing problem.
Mutt and NeoMutt run the child program, then when it returns, delete the temporary file.
But... programs like firefox return immediately.  Before they've opened the file.

Try adding a sleep to your mailcap:
```
text/html; firefox %s & sleep 2; test=test -n "$DISPLAY"; nametemplate=%s.html; 
```

The reason it works the second time, is that firefox is already up-and-running, so it opens the file immediately.

**Comment by 0x747972** [comment]
Aaaah, I see. So this fixes the problem for me, but it still boggles my mind why it works only on the second time, even with firefox running on the first time the file is opened.

But, Nevermind. Thanks for the support. ;-)

**Comment by 0x747972** [comment]
Oh, sorry for reopening the issue. Would you accept patches which correct this behaviour? In my humble opinion this behaviour is kind of unexpected and annoying...

**Comment by flatcap** [comment]
> this behaviour is kind of unexpected and annoying

Yes it it

> Would you accept patches which correct this behaviour?

That'd be brilliant.

A while ago, I sketched out a solution that I'd like to see: https://github.com/neomutt/test-attach
The main program (creates a file and starts a child worker) -- 10 times.
The main loop then waits.
As each child dies, main notices and deletes the associated file.

How good are your C skills?
I'm happy to guide you around NeoMutt, but I don't have the time to teach you C :-)

**Comment by 0x747972** [comment]
Yeah, I could probably write some C code, but I'm not a really good programmer.
For reference, I have attached the last code I wrote. It doesn't run on x86, though. Only x64

```
/*
 * compile with gcc -Wall -Werror -Wextra -Wpedantic -std=c11 -o selfmod2 selfmod2.c
 *
 * or with
 * gcc -m32 -Wall -Werror -Wextra -Wpedantic -std=c11 -o selfmod2 selfmod2.c
 */

#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/unistd.h>
#include <time.h>

#define X32 1
#define X64 2

int main(int argc, char **argv){
    int fd;
    int arch;
    unsigned char *map;
    unsigned char *ptr;
    struct stat filestat;

    //entrypoint
    unsigned long *e_entry;

    //offsets 
    unsigned long start_offset;
    unsigned long call_offset;
    unsigned long main_offset;
    unsigned long octet_magique;

    (void)argc;//lol

    if(time(NULL)){
        puts("Something!\n");
    }
    else{
        puts("Something else!\n");
    }

    printf("Hold my Beer! I'm %s and I'm going to modify my own binary!\n", argv[0]);
    puts("The next time you execute me I'll output something else.");
    
    fd=open(argv[0], O_RDONLY);
    if(fd == -1){
        perror("The fuck just happened?!");
        exit(EXIT_FAILURE);
    }

    if(stat(argv[0], &filestat)==-1){
        perror("Couldn't stat file.");
        exit(EXIT_FAILURE);
    }

    map=mmap(0, filestat.st_size, PROT_READ | PROT_WRITE, MAP_PRIVATE, fd, 0);
    if(map == MAP_FAILED){
        close(fd);
        perror("mmap() FAIL!");
        exit(EXIT_FAILURE);
    }
    
    if(sizeof(unsigned long)==4){
        arch=X32;
    }
    else if(sizeof(unsigned long)==8){
        arch=X64;
    }

    ptr=map;

    if(*((unsigned int *)ptr)!=0x464c457f){
        close(fd);
        fprintf(stderr, "Not an ELF-file\n");
        exit(EXIT_FAILURE);
    }

    if(arch==X32){
        exit(1);
    }
    else if(arch==X64){
       
        e_entry=(unsigned long *)(ptr+0x18);
        start_offset=*e_entry;
        
        for(unsigned long i=0; *(ptr+start_offset+i)!=0x90; ++i){
            if(*((short *)(ptr+start_offset+i))==0x15ff){
                call_offset=start_offset+i;
                break;
            }
        }
        
        main_offset=call_offset+*((unsigned int*)(ptr+call_offset-4));
        for(octet_magique=main_offset; *(ptr+octet_magique)!=0x74 && *(ptr+octet_magique)!=0x75; ++octet_magique);
        
    }

    
    if(*(ptr+octet_magique)==0x74){
        ++*(ptr+octet_magique);
    }
    else if(*(ptr+octet_magique)==0x75){
        --*(ptr+octet_magique);
    }

    close(fd);
    if(unlink(argv[0])==-1){
        close(fd);
        perror("unlink() FAIL!");
        exit(EXIT_FAILURE);
    }

    fd=open(argv[0], O_WRONLY|O_CREAT, filestat.st_mode);
    if(fd==-1){
        perror("What did just happen?!");
        exit(EXIT_FAILURE);
    }

    if(write(fd, map, filestat.st_size)==-1){
        perror("What did just happen?!");
        exit(EXIT_FAILURE);
    }

    if(munmap(map, filestat.st_size) == -1){
        close(fd);
        perror("mmunmap() FAIL!");
        exit(EXIT_FAILURE);
    }

    close(fd);

    return EXIT_SUCCESS;
}
```

About your solution: Would that actually work? As far as I understand it, the problem exists because firefox returns to early. Waiting for the child (which would be firefox) wouldn't help us here, or would it?

**Comment by flatcap** [comment]
> Would that actually work?

Hmm... you may have a point about firefox.
We wouldn't be able to track it and it wouldn't know to delete the file.
The best we could do, there, is to keep a list of file which we delete on exiting NeoMutt.
(Or we could garbage-collect the list after 'n' minutes)

**Comment by 0x747972** [comment]
Hmm, That was one of my first ideas, too.
I'll start looking into this tomorrow or at the start of this week, but don't expect a patch too soon...
Could you please take a look at my edit in the last post to confirm, that i'm looking at the right piece of code?
Thanks! :-)

**Comment by flatcap** [comment]
Yes, that's the function.
If you haven't debugged a curses app before, [here are some tips](https://neomutt.org/dev/debug).

**Comment by 0x747972** [comment]
Here's a possible solution, but not an elegant one:
https://github.com/neomutt/neomutt/pull/1308

**Comment by timhae** [comment]
Is there a solution for this other than the mailcap workaround?

**Comment by karlsebal-mcs** [comment]
> Is there a solution for this other than the mailcap workaround?

The manual gives a .mailcap example — I would not consider this a workaround, exactly.

https://neomutt.org/guide/mimesupport.html#3-3-1-%C2%A0optional-fields part x-neomutt-keep
https://neomutt.org/guide/reference.html#timeout
