### ISSUE TITLE
Is it possible to make the indicator preserve the index colors?

### ISSUE THREAD

**Issue by lynxcs** [neomutt/neomutt#1299]
Hello,
I've recently started using neomutt and I'm having a blast configuring it and changing it to suit my needs.

In my current setup I change the colors of the index entry dependent on the sender, so I can see important emails at a glance.

The issue (minor at best) is that the indicator displays it's own color, which doesn't look aesthetically pleasing. I read in the guide that it's possible to make the color transparent by using the default / brightdefault colors, yet I can't seem to get that to work.

The best case scenario would be that the same colors are preserved, just brighter.
I hope this is possible and I just overlooked something. I would appreciate any help in fixing this issue / answering this question.

Thank you

**Comment by flatcap** [comment]
Hi @lynxcs 

> I've recently started using neomutt

Welcome!

> ... configuring it and changing it to suit my needs

A lifetime's work :-)

> the indicator displays its own color

Yes, sorry.  That's a limitation of the way NeoMutt handles its colour.
You can set a colour to "default", but that means the _default_ colour and not transparent.

We know how we'd like it to work, but it's a big job and there are higher priority things to fix.

**Comment by lynxcs** [comment]
Ah, that clears things up, it's a shame but I'll live with it.
Thank you for the timely response.
