### ISSUE TITLE
The wiki isn't enabled

### ISSUE THREAD

**Issue by 1ace** [neomutt/neomutt#13]
The project's README mentions the wiki twice, but it isn't enabled on this project.
One of those needs to be fixed :]

**Comment by flatcap** [comment]
Thanks for spotting those.
I moved the wiki to a website (using GitHub pages): http://www.neomutt.org/
I /knew/ I shouldn't have killed the wiki yet.

I'll fix the links.
I'm hoping to make a release later this week.

**Comment by flatcap** [comment]
Well this bug turned out to be more hassle than I imagined.
2 streams x (14 feature branches + 14 merges + 1 main) = 58 commits!
The fixed docs and README will be in the next release.
