### ISSUE TITLE
set pgp_decrypt_command="$pgp_decode_command" no longer works

### ISSUE THREAD

**Issue by norristh** [neomutt/neomutt#1302]
## Expected Behaviour

pgp_decrypt_command takes the value of pgp_decode_command and works to decrypt OpenPGP/MIME emails.

## Actual Behaviour

Multipart MIME PGP emails decrypt normally. OpenPGP/MIME emails don't. Hitting enter on an email from the index does nothing.

If NeoMutt crashed, did your OS create a 'coredump' file?

## Steps to Reproduce

Highlight an OpenPGP/MIME email in the index.

Press enter.

Nothing happens.

## How often does this happen?

- Always, on the two OpenPGP/MIME emails I have. (Most are Multipart MIME.)

## When did it start to happen?

- When I upgraded about 4 days ago

  Not sure what version I used to use, but it should have been up to date for Fedora.

## NeoMutt Version

20180716

## Extra Info

Somewhere I was able to see error message "Error: could not create a PGP subprocess!" which I found on line 965 of the code at https://neomutt.org/code/pgp_8c.html

Eventually I fixed it by changing my config from

set pgp_decrypt_command="$pgp_decode_command"
to
set pgp_decrypt_command="same actual command as my pgp_decode_command"

So I guess the assignment to another variable isn't working? Don't know whether this is a general problem, or something specific to these variables...

**Comment by flatcap** [comment]
What were your decode and decrypt commands before?

The previous Fedora version was 2018-06-22.
Not much changed in the crypto code since then.

Are you technical?  ([build instructions](https://neomutt.org/dev/build))
If so, please could you build branch `issue/1302` and see if that fixes your problem.
