### ISSUE TITLE
Keyword Feature in Brewed Neomutt

### ISSUE THREAD

**Issue by gzagatti** [neomutt/neomutt#1304]
I am quite a new user to `neomutt` and am trying to get my head around it. 

I have been trying to use the [Keywords Feature](https://neomutt.org/feature/keywords) in `neomutt` with: 

```
set keywords_legacy = yes
```

But I am afraid to say that it does not work. I keep getting the following error:

```
keywords_legacy: unknown variable
```

I have installed `neomutt` using `brew install neomutt`.

I am probably missing something, but it would be great to have this feature and be able to parse the labelled messages downloaded from Gmail using `offlineimap`, where I have used the `synclabels = yes` option. Thanks for any help in this solving this problem.

**Comment by gahr** [comment]
Hi, the keywords feature was removed, see #792. The website probably needs updating, too.

**Comment by gzagatti** [comment]
That's a shame, it seemed like a good feature. In any case, reading the PR I was led to the original issue #769 which says that `neomutt` still supports the `X-Label` field. So I simply used the `labelsheader = X-Keywords` in `offlineimap` to remap the labels header to `X-label`. I can now sync the labels back and forth between Gmail and offlineimap.
