### ISSUE TITLE
notmuch: add `modify-thread-labels`

### ISSUE THREAD

**Issue by guiniol** [neomutt/neomutt#131]
And the corresponding `modify-thread-labels-then-hide`

These commands would change the tags of every message in the thread.

Question: should it change the tags of the every **VISIBLE** message in the thread or of the **ENTIRE** thread whether they are visible or not?

I would go with **ENTIRE** thread, but there could also be two sets of commands.

**Comment by P-EB** [comment]
I'd go the easiest of both options. Would it be simple to implement both?

**Comment by guiniol** [comment]
I have no idea. I haven't looked at the code ^^
There's the `entire-thread` commands which display all the messages in a thread (in case some have been filtered out), so I would start there to see how threads work and how to know which ones are displayed (not sure about the last one, the function could pull every message in the thread without checking if they are visible or not).

**Comment by sileht** [comment]
Using <tag-thread> and then <modify-labels-then-hide>, select all messages in the threads and <modify-labels-then-hide> applies new labels to all messages in the threads and then hide them.

(but the code is buggy if the thread is collapsed)

**Comment by flatcap** [comment]
It's useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
