### ISSUE TITLE
Do not sleep after minor errors

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#1311]
## What would you like to be able to do?

I would like to be able to navigate emails in the index without any sleep if I go past the top or bottom. I often "crash" into the top by holding the "k" key (I'm using the term "crash" here in the way that to vertically scroll, you might move your cursor all the way to the right side of the screen and "crash" into the right side). Probably a more elegant way of going to the top is with "=" but for whatever reason I like holding the "k" key. When I get to the top, neomutt gives the message "You are on the first message." and sleeps for 1 second so that I see that message. I would prefer for there not to be any sleep in this case so that I can open the message or do something else.

## What needs to change in NeoMutt?

neomutt introduced a sleep after all errors at 3e1070ec. The logic of the change (at least how I interpret it) seems very reasonable to me: if there is an error, it is important that the user sees the error. Without sleep, the user might perform an action that overwrites the error message and thus the user might not see a potentially important error message. However, in some cases, I think that this sleep is unnecessary. In the use case I discussed above, it is OK if the user does not notice the error message.

I'm not sure what to suggest, since as mentioned above, I think that the change at 3e1070ec is reasonable. I would prefer the behavior before that change, but I don't think it would be good to introduce yet another config just for this, unless others also find the new behavior annoying. The only other thing I can think of is that perhaps each error could be designated as a critical error or a minor error, or "warning". We might want to sleep for different amounts of time depending on the severity and the situation. We could sleep for 0 seconds after the "You are on the first message" message. But for a message like "Your house is about to blow up", we would really want to be sure the user saw it and sleep for e.g. 5 seconds.

## Have you tried any alternative methods?

- Macros
- Hooks
- Scripts

I have not tried any alternative.

## Additional Info

I've tested on current neomutt master, in gnome-terminal and xterm. I'm using Ubuntu 18.04.

**Comment by flatcap** [comment]
I'm pleased with the change you mention.  It removed a lot of complexity from deep parts of the code.
But...  There were a few side-effects, like the one you mention.

I put in an extra check to drop duplicate messages (18385a6436) in neomutt-20180323 and later.
That should prevent the long pauses when you get one message repeatedly.
I'll check your specific case in the morning.

**Comment by scottkosty** [comment]
Sounds good. It is not a major annoyance. Perhaps I will get used to the new behavior.

**Comment by scottkosty** [comment]
It seems another change starting with 3e1070e is that if I start neomutt with a mailbox that is empty, and press "k" a couple of times, a black square appears in the upper-right (on the line of where the first subject line would be). Here is a screenshot:

![screenshot from 2018-08-09 20-20-58](https://user-images.githubusercontent.com/1149353/43932768-f8565242-9c13-11e8-8ff2-5a22114f4472.png)

I'm guessing the black square is completely unrelated to the issue I bring up here, and that it is just a side effect. Nonetheless, since it only appears after 3e1070e I mention it here just in case.

Both of the issues I bring up here are very minor. It is completely fine with me if you decide to close this issue without any change.

**Comment by gahr** [comment]
Maybe “you are on the first message” should be dropped completely as a message / warning / error?

**Comment by dpgao** [comment]
I agree. A beep should be enough in cases like this, just like what Vim does.

**Comment by flatcap** [comment]
> dropped completely

Some feedback would be useful.  A *message* would do.
I wondered why it was an error in the first place...
Errors cause beeps, so perhaps it was to aid users with visual disabilities.

I did plan a review of all the errors, but there aren't many active developers, so I've been too busy.

**Comment by flatcap** [comment]
The black square _looks_ like it's the cursor.
I haven't seen it before (it should be turned off during most index operations),
and I can't repeat it, but I'll keep a watch out.

**Comment by scottkosty** [comment]
Thank you all for the responses! I would note that there is a similar situation when scrolling in the pager and the "Bottom of message is shown" (and also "Top of message is shown") errors.

Please let me know if there's anything I can help test.

**Comment by scottkosty** [comment]
> I can't repeat it, but I'll keep a watch out

No need to think about it. If you were interested, I could make a screencast, but I have the feeling that this square thing is not worth thinking about in the context of the current issue, so perhaps best to ignore it.

**Comment by tdehaeze** [comment]
Is there a way to ignore these minor errors such as "Bottom of message is shown"?
Thanks

**Comment by scottkosty** [comment]
> Is there a way to ignore these minor errors

That is an interesting request also. This ticket is about ignoring the *sleep* on the minor errors, but I also might like to ignore the errors themselves.

**Comment by flatcap** [comment]
@tdehaeze 
No, there's no way to ignore them yet.
At some point we're going to downgrade some of the 'errors'.
Some messages, like "Bottom of message" can probably die.

(We only have a few developers and we're busy making large architectural improvements)

Notes:
- `$sleep_time` controls how long NeoMutt may wait after an error message.
- `<show-log-messages>` (default <kbd>M</kbd>) shows any messages you may have missed

@scottkosty 

> I also might like to ignore the errors themselves

Ooh, you like to live dangerously.

One proposed plan is to add E123 prefixes to all of the error messages, like vim.
If we did that, then having `$error_messages_to_ignore` would be easy.
But... that would require a good audit of all our logging, first.

**Comment by scottkosty** [comment]
> (We only have a few developers and we're busy making large architectural improvements)

Thank you for all of your work!

> > I also might like to ignore the errors themselves
> 
> Ooh, you like to live dangerously.

Indeed :). Interestingly, this behavior contrasts to the first thing that I do when writing a program in every programming language I work with (including C++, R, Bash, and Perl), which is to convert warnings to errors.

**Comment by scottkosty** [comment]
I think on current master this behavior is improved (for my personal preference) for scrolling in the index of messages. However, I still notice it when scrolling e.g., attachments
