### ISSUE TITLE
"Postpone this message?" phrasing is confusing in a way that causes data loss for the unwary

### ISSUE THREAD

**Issue by archenemies** [neomutt/neomutt#1312]
I'm reporting this as a bug rather than a feature request because of the data loss aspect.

I reported it [over 10 years ago](https://marc.info/?l=mutt-dev&m=112834298323170&w=2) to the Mutt list, where after a prolonged discussion it was rejected by Brendan Cully / Thomas Roessler on the grounds that my proposed phrasing change to "Save draft message?" would necessitate changes in the naming of the `$postpone` quad-option configuration variable. It doesn't. Arguably the documentation for that variable should be clarified, but this is already the case (and hence a separate issue).

I reported this to the muttng list but it was ignored. Now I see that there is yet another fork of Mutt so I'm reporting it here.

Note that I am not submitting this issue to improve the usability of the software for myself. The problem is that for *new* users it takes a while to get used to the strange phrasing, and until that time several draft messages may be unintentionally lost. This makes it hard for me to recommend mutt to friends who don't already use it. If you were to fix the problem then I could recommend neomutt instead.

I added a [warning paragraph](https://wiki.archlinux.org/index.php/Mutt#Sending_mails_from_Mutt) to the Mutt ArchWiki page, but I'm afraid that hardly anyone will read it.

## Actual Behaviour

I was trying to change my mind about quitting the "compose" screen while composing a message.

I saw a prompt "Postpone this message?". I wanted to go back to editing the message, which means not postponing it, so I hit "n".

This caused the message I wrote to be deleted.

## Expected Behaviour

As my composition was at risk of being deleted, I would have expected the prompt to communicate this quite clearly.

I would have expected a prompt along the lines of "Save draft message?" or "Save/postpone this message?" or something that makes it clear that hitting 'n' will cause the message to be lost.

## Steps to Reproduce

Try composing a message. When you are at the "Compose" screen, hit "q". You see a prompt "Postpone this message?". Hit "n" and it gets deleted.

## How often does this happen?

- Always

## When did it start to happen?

Decades ago.

## NeoMutt Version

I can provide the version if you like but I think it is unnecessary.

**Comment by gahr** [comment]
I don't see how `s|Postpone this message|Save draft message|` would pessify anything. I'm all for it.

Of course we should not be changing the true-ness logic of the question: `y` should continue to save the draft, and `n` should continue to kill it. But you're not suggesting that we do, so... yeah..

**Comment by flatcap** [comment]
If `$postpone` is set to `ask-yes`, would a menu be better?

- **P**ostpone (save) the message
- **D**elete the message
- **C**ancel (do nothing)

**Comment by alyptik** [comment]
Another possible approach could be, "Postpone this message before returning to folder?" which is just making the message more descriptive yet keeping the wording similar.

**Comment by alyptik** [comment]
@flatcap i also like that approach

**Comment by tasn** [comment]
I also found it terribly confusing. As a workaround I just set it to always postpone for now...
Maybe having "Discard message?" with "yes" discarding the message, and "no" returning back to the message. Essentially forcing people who would like to postpone the message to postpone it with "P"?

**Comment by archenemies** [comment]
Sorry I haven't had time to follow through with this.

@tasn  thank you for the feedback. I've heard from at least one other person (IIRC a Senior Software Engineer at Google) that he also found the wording confusign.

However I don't like your proposal because it will cause messages to be lost by long-time users with muscle-memory for a particular key sequence (e.g. "q" + "y" -> "postpone" becomes "discard" in your proposal).

My proposal was to change the wording to "Save draft message?".

Advantages:

* Users don't have to learn new keystrokes

* No more lost messages. Those users who are accustomed to GUI dialog boxes will understand that "not saving" = "deleting".

Disadvantages:

* Relationship to the "postpone" and "postponed" configuration variables becomes slightly unclear. Users who see "Save draft message?" -> "y" -> "Message postponed" in status line may be confused.

We can fix the disadvantage with a wording like "Save (postpone) draft message?". This seems slightly verbose. I would prefer to just go with "Save draft message?" which @gahr already approved. People will figure it out, it may take them a little time to figure out that the message got saved to `$postponed/` but at least it will still exist on the filesystem somewhere.

I can submit a PR for this if desired. Maybe with a little update to the manpage. I won't be able to update all the foreign language translations of course.

**Comment by flatcap** [comment]
I like the idea of changing 'Postpone' to 'Save (postpone)' to make it clearer
(whilst still being associated with `$postpone`)

<kbd>Ctrl-G</kbd> safely cancels the question without action, but I doubt many users would be aware of that.

**Comment by flatcap** [comment]
@archenemies

> We can fix the disadvantage with a wording like:
> "Save (postpone) draft message?"
  
Yes, that's decided.

> This seems slightly verbose. 
  
A little, but it will do for now.

> I can submit a PR for this if desired. 
> Maybe with a little update to the manpage. 
  
Yes please!     

You may want to mention <kbd>Ctrl-G</kbd> too (there are few references to it in the guide).

> I won't be able to update all the foreign language translations of course.

We have a (small) team of translators to help there.

Any questions, just ask (here, or on IRC).
Thanks.
