### ISSUE TITLE
Key binds with CTRL

### ISSUE THREAD

**Issue by aviofreak** [neomutt/neomutt#1318]
Hi,

I'm using neomutt with OpenBSD and st terminal. I've got key bindings with C-{up,down,right} and when I use them in st I get an error "Key is not bound".

However, the same works if I open tmux inside st, or even after I ssh to 127.0.0.1 on st.

Do you have any idea what can be the reason for this?

I've been searching for this but it seems that my case is unique. I'll be grateful for any help.

Regards
aviofreak

**Comment by aviofreak** [comment]
HA! I solved it!

After running st I checked the value of $TERM and it was "st-256color". In tmux and when I ssh'ed to 127.0.0.1 it was "xterm-256color". That did the trick!

Maybe someone will have similar problem, so I'll leave it here.

All the best!

**Comment by flatcap** [comment]
OK, great.  Thanks for letting us know :-)
