### ISSUE TITLE
<tab>-completion of config values is broken

### ISSUE THREAD

**Issue by heavytull** [neomutt/neomutt#1320]
## Expected Behaviour

":set sendmail="+ "tab" should dump the content of the variable "sendmail" right after the "=" sign.

one way to display the value of a variable in neomutt is to type ":set my_var=" then to hit the "tab" key. It should dump the value right after the "=" sign. That works with the "from" variable but not with "sendmail" variable.

## Actual Behaviour

after typing ":set my_var=" hitting "tab" key does not do anything

If NeoMutt crashed, did your OS create a "coredump" file?

## Steps to Reproduce
type ":set my_var=" and hitting "tab" key

## How often does this happen?

- Always

## When did it start to happen? since 20180716

- When I upgraded
  Which version did you use to use? 20180716

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.4.144 (x86_64)
ncurses: ncurses 5.9.20141206 (compiled with 5.9.20141206)
libidn: 1.34 (compiled with 1.34)
hcache backends: gdbm, bdb, lmdb

Compiler:
cc (GCC) 5.5.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --prefix=/usr --mandir=/usr/man --docdir=/usr/doc/neomutt-20180716 --sysconfdir=/etc/neomutt --with-mailpath=/var/spool/mail --ssl --sasl --gpgme --gnutls --gdbm --bdb --lmdb --build=x86_64-slackware-linux

Compilation CFLAGS: -O2 -fPIC -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo
  +gnutls +gpgme -gss +hcache -homespool +idn -locales_hack -lua +meta
  -mixmaster +nls -notmuch -openssl +pgp +sasl +smime +start_color
  +sun_attachment +typeahead
MAILPATH="/var/spool/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc/neomutt"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```
## Extra Info

* Operating System and its version : slackware64 14.2
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? yes, tmux
* Is your email local (maildir) or remote (IMAP)? remote

**Comment by flatcap** [comment]
Thanks for the bug report.

I've checked the current (devel) version of the code and the problem doesn't happen any more.
I checked the completion on all the different config types.

I'll leave this issue open, for now, in case anyone else notices the problem.
