### ISSUE TITLE
IMAP mailbox status should be synced once in a while

### ISSUE THREAD

**Issue by l29ah** [neomutt/neomutt#1322]
## What would you like to be able to do?

Reading (setting the "read" flag) and removing messages without having to hit `$` to commit changes.

## Additional Info

At the moment if the IMAP connection is flaky, neomutt silently loses any changes of the mailbox state when it tries to reestablish the connection, and won't sync it unless explicitly told so or ordered to exit or change mailbox.

**Comment by l29ah** [comment]
Why was it closed? It's still flaky.

**Comment by rgrig** [comment]
It would be nice to be able to use IMAP mailboxes with flaky connections, and even offline.

**Comment by roccoblues** [comment]
Trying to cleanup some older issues here. Can anyone comment if this issue still persists with the latest version? Thanks!
