### ISSUE TITLE
Limit by id,  special regex character 

### ISSUE THREAD

**Issue by parisni** [neomutt/neomutt#1324]
When using the limit function by id (press l, type ~i <message-id> )
it turns out some message-id containg "+" character won't match
apparently because it is a regex special character.

However, escaping that character does not help "\+" . 

## NeoMutt Version

NeoMutt 20180716-250-046ce3

## Extra Info

* Operating System and its version
linux
* Were you using multiple copies of NeoMutt at once?
no
* Were you using 'screen' or 'tmux'?
no
* Is your email local (maildir) or remote (IMAP)?
maildir

**Comment by gahr** [comment]
Try with a double backslash escape `~l \\+`

**Comment by parisni** [comment]
Double escaping works. Thanks for your help.

**Comment by gahr** [comment]
np
