### ISSUE TITLE
I need some guidance regarding mutt bash script

### ISSUE THREAD

**Issue by fmontaldo** [neomutt/neomutt#1325]
Hi,

I never used mutt and I need to do a bash script in order to clean up mails older that 7 days. I found a possible solution from here:

```sh
#!/bin/bash
#
# Usage: 
# ~r : DELETE
# 1y! : 1 year
# 2y! : 2 years
# 7d! : 7 days
# 30d! : 30 days
#

mailbox="/path/to/user/mailbox"
deletePattern="7d!"

mutt -f $mailbox -F/dev/null -e "push <delete-pattern>~r>${deletePattern}<enter><sync-mailbox>y<enter><exit>q"
```

When the script run it shows me the mutt output. 
Can someone please help me?.

Regards

**Comment by wolfen351** [comment]
Based on what you gave above, I run the command in my bash prompt:

    mutt -f Junk\ E-mail -F/dev/null -e 'push <delete-pattern>~r>30d!<enter><sync-mailbox>y<enter><exit>q'

And received the output: 

42947 kept, 0 deleted.

So I think the script is ok..

**Comment by gahr** [comment]
Why the exclamation mark?  `<delete-pattern>~r>30d` works fine here.
