### ISSUE TITLE
Architectural Changes

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1326]
I have a lot of **big** ideas for NeoMutt, but most of them require changes to the architecture of the code.

Currently the code has a very large overlap between data and display elements.
Separating these two parts will simplify the code.

Everyone's invited to discuss my ideas and ask questions about my plans.

**Comment by flatcap** [comment]
IRC Discussion 2018-07-16

![arch](https://flatcap.org/mutt/neo-arch1.svg)

`<flatcap>` that shows who calls whom, and includes various external connections
`<flatcap>` the browser api doesn't exist (beyond detailed notes)
`<flatcap>` I have some deep questions about the header cache, I think it might be in the wrong place
`<flatcap>` and the header cache is deeply entwined in each mailbox
`<flatcap>` there are a few places where a mailbox gets the cached version, then tweaks it, then gives it to the index
`<flatcap>` I'm wondering if we can eliminate these tweaks, or at least externalise them in some way
`<flatcap>` if we could...  we could move the cache up a level in the diagram.  the mailbox api would talk to it (and the mailboxes would be unaware)
`<gahr>` are you saying that it should be mailbox -> cache -> conn, so the cache should be auto-feeding itself from either local storage or servers?
`<edwinbalani>` not an inline cache then, so to speak :-)
`<flatcap>` the mailbox api checks the cache, otherwise talks to the mailbox
`<flatcap>` ooh, I hadn't thought that far, edwinbalani 
`<flatcap>` as there are various 'level' of retrieval, there'd need to be flags, etc
`<flatcap>` imap has: list of emails, headers, bodystructure, full download
`<flatcap>` I'd be interested to know how much memory the Context actually uses (for a normal mailbox, with 1000 emails)
`<flatcap>` the other hcache thing I noticed was that several structs are being serialised 'whole' meaning which is wasting a few hundred bytes per record

**Comment by flatcap** [comment]
![key](https://flatcap.org/mutt/arch-key.svg)
![arch](https://flatcap.org/mutt/arch.svg)
This one shows the account/mailbox/email data, and three views: sidebar, index, pager
(the faded objects are references to objects in the data tree (left)

**Comment by flatcap** [comment]
### Reorganising Context/Mailbox

The Context (the current mailbox) has duplicate copies of 6 values which are kept in the Mailbox.
These commits de-dupe the Context.

See branch [devel/context](https://github.com/neomutt/neomutt/tree/devel/context)

- 2ffcd7491 Context ptr to Mailbox
  Link the Context to a Mailbox (creating one if necessary)
- 5e926bee6 move realpath
  Use the Mailbox's `realpath`, not the Context's
- 652482abe move path
  Use the Mailbox's `path`, not the Context's
- f58dc5fa3 move msgcount
  etc
- 8201b8c73 move unread
- 51bd2193d move flagged
- b254e2edd move magic

**Comment by elfring** [comment]
Are you going to apply [object-oriented software development](https://en.wikipedia.org/wiki/Object-oriented_programming "Description for object-oriented programming") in a more detailed way?

**Comment by flatcap** [comment]
Yes.

The new config system is a step in that direction.
`parse_set()` used to have to know about every different type of variable.
Now, subsystems can define 'validators' which can check and subtype variables and 'listeners' to be notified of change.

In the (not too distant) future...
Each of the data objects would handle notifications.
If a Mailbox was added to an Account, the Account's listeners would be notified.

**Comment by flatcap** [comment]
We started with Mutt's restrictions: C99 compiler, POSIX:2001 libs.
It doesn't restrict us too much.

> .. another programming language?

Certainly no time soon.
We can simulate all the OO goodness that we need, for now.

Once we've sorted out the worst problems, we could leap forward to C++.
(because I'm a C/C++ programmer)

The std:: libraries would make the code so much tidier.

> How many existing libraries can be reused for the desired software extensions?

Once we drop the restrictions, there are LOTS of libraries we could consider.
[libuv](https://github.com/libuv/libuv) and [libfswatch](https://github.com/emcrisostomo/fswatch) caught my attention.

**Comment by flatcap** [comment]
Convert NeoMutt to C++, piece by piece?
No, thanks.  I think this challenge is hard enough already.

**Comment by elfring** [comment]
Can tools like the following become helpful for the discussed software development challenge?
* [Cross-reference](https://en.wikipedia.org/wiki/Cross-reference "Description for cross-reference")
* [Software refactorings](https://refactoring.com/catalog/ "Catalog of refactorings")
* [Simplified wrapper and interface generator](http://www.swig.org/exec.html "Description for SWIG")

**Comment by flatcap** [comment]
I'm working hard on the first two, but, we're not in a state to provide an external API.
When we have NeoMutt -> Accounts -> Mailboxes -> Emails, etc, we can think about it.
The first to get support will be Lua, which would become very useful.

**Comment by elfring** [comment]
* I have got the impression from [an inheritance graph](https://github.com/neomutt/arch/blob/2e06424e9c6f2813cb5a9871b3e1e180d5d4927b/README.md#what-am-i-looking-at "Display of an object hierarchy") that you could become interested to work more also with [the unified modelling language](https://en.wikipedia.org/wiki/Unified_Modeling_Language "Description for UML"), couldn't you?
* How do you think about to experiment with [model-driven engineering](https://en.wikipedia.org/wiki/Model-driven_engineering "Description for MDE")?
* Can any related development tools help with desired software improvements?

**Comment by flatcap** [comment]
#### Which Mailboxes use which Context members
| Total | member        | Compressed | Imap | Mbox | Maildir | Notmuch | Nntp | Pop |
| :---- | :------------ | :--------- | :--- | :--- | :------ | :------ | :--- | :-- |
| 6     | quiet         | Y          | .    | Y    | Y       | Y       | Y    | Y   |
| 6     | hdrs          | .          | Y    | Y    | Y       | Y       | Y    | Y   |
| 5     | size          | .          | Y    | Y    | Y       | Y       | .    | Y   |
| 5     | readonly      | Y          | Y    | Y    | .       | .       | Y    | Y   |
| 5     | deleted       | .          | Y    | Y    | Y       | .       | Y    | Y   |
| 4     | changed       | .          | Y    | Y    | Y       | .       | Y    | .   |
| 3     | subj_hash     | .          | .    | Y    | .       | .       | Y    | Y   |
| 3     | rights        | .          | Y    | .    | .       | .       | Y    | Y   |
| 3     | mtime         | .          | .    | Y    | Y       | Y       | .    | .   |
| 3     | id_hash       | .          | .    | Y    | .       | Y       | Y    | .   |
| 3     | hdrmax        | .          | Y    | Y    | .       | .       | .    | Y   |
| 2     | vcount        | .          | .    | Y    | .       | .       | Y    | .   |
| 2     | v2r           | .          | Y    | Y    | .       | .       | .    | .   |
| 2     | tagged        | .          | .    | Y    | .       | .       | Y    | .   |
| 2     | new           | .          | .    | Y    | .       | .       | Y    | .   |
| 2     | append        | Y          | .    | Y    | .       | .       | .    | .   |
| 1     | vsize         | .          | .    | Y    | .       | .       | .    | .   |
| 1     | realpath      | Y          | .    | .    | .       | .       | .    | .   |
| 1     | path          | Y          | .    | .    | .       | .       | .    | .   |
| 1     | magic         | .          | .    | .    | .       | Y       | .    | .   |
| 1     | locked        | .          | .    | Y    | .       | .       | .    | .   |
| 1     | label_hash    | .          | .    | Y    | .       | .       | .    | .   |
| 1     | fp            | .          | .    | Y    | .       | .       | .    | .   |
| 1     | compress_info | Y          | .    | .    | .       | .       | .    | .   |
| 1     | closing       | .          | Y    | .    | .       | .       | .    | .   |
| 1     | atime         | .          | .    | Y    | .       | .       | .    | .   |

Some of these should be moved to `struct Mailbox`.
Others should become private data.

**Comment by flatcap** [comment]
@elfring 

> ... an inheritance graph ... unified modelling language, couldn't you?

I created that diagram a long time ago.  I was ignorant of how messed-up the code was.
If I were starting a project, I'd certainly design it from the top-down.
It'd be OO and I'd have lots of pretty diagrams (though I've never been formal enough to use UML).

However, NeoMutt's code is so tangled at the deeper levels, that there's simply no way to refactor it from the top-down.

> Can any related development tools help with desired software improvements?

No.  They can describe the goal, but they can't help us get there.

**Comment by flatcap** [comment]
### Decluttering the Compressed Mailbox

Currently, Compress stores a `CompressInfo` pointer on the `Context`.
This caches the external commands and the MXAPI ops for the child mailbox.
We can't use `Context.data` because the child mailbox might want to use it.
Also, that info should be on the `Mailbox`, now.

The solution is to nest the `Mailbox`s.

`Context` -> Compressed `Mailbox`
- `magic = MUTT_COMPRESED`
- `mx_ops = mx_comp_ops`
- `data = struct CompressInfo`
  - external commands, etc
  - child `Mailbox`

The child `Mailbox`, e.g.:
- `magic = MUTT_MBOX`
- `mx_ops = mx_mbox_ops`
- `data = struct MboxInfo`

This all depends on the mailbox backends being completely separated from the `Context`.

**Comment by elfring** [comment]
>However, NeoMutt's code is so tangled at the deeper levels, that there's simply no way to refactor it from the top-down.

This view can be reasonable. But it seems that you got an intermediate vision.


>No.

I imagine that some higher-level development tools can help more than we might know at the moment.


>They can describe the goal,

This is useful already, isn't it?


>but they can't help us get there.

I got an other view. We are used to the application of different tool boxes.
* Would you like to direct any development attention to corresponding extensions?
* Will any intermediate update steps clarify the current software situation a bit more?

**Comment by elfring** [comment]
>Yes, but they only show an idealised solution -- they ignore all the quirks of the code.

Is a convergence possible from both software design directions?


>I understand where I'm going.

This can be nice already.

:crystal_ball: How do you think about to attract additional contributors by variations and combinations for development approaches?


>… and the email backends …

* Do you care for any progress from other implementations of programs (or libraries) in this application domain?
* Do you eventually know [an existing text-based user interface](https://en.wikipedia.org/wiki/Text-based_user_interface "Description for text-based user interfaces") for these alternatives?

**Comment by flatcap** [comment]
> Is a convergence possible from both software design directions?

I hope so.  Soon.

> ... attract additional contributors ...

It's a nice idea, but I'm struggling to find developers who can even complete simple tasks.
People are busy; they don't understand the complexity; they aren't prepared to ask for help.

> > … and the email backends …

> ... other implementations of programs (or libraries) in this application domain?

When the backends are independent, that might be possible.
I haven't investigated what we could use, though.

> ... any existing text-based user interface ...

Programs like irssi and vim show what _can_ be done.
They use 24-bit colours and handle their own screen drawing, rather than using curses.
I have some proofs-of-concept, but it's a lot of work (and a long way off).

OK.  The End.  Please stop asking difficult questions :-)

**Comment by elfring** [comment]
>Please stop asking difficult questions

I assumed that this dialogue could trigger related software evolution.

**Comment by flatcap** [comment]
While I've been happy to talk about architecture, I'd still rather see code being written.

**Comment by elfring** [comment]
* Can it be occasionally nicer if there would development tools be available which will generate the desired source code for you?
* Do you try to avoid the repetition of questionable code anyhow?

**Comment by flatcap** [comment]
> tools be available which will generate the desired source code

They can work well, when you have a nice plan and a clean sheet.

> Do you try to avoid the repetition of questionable code anyhow?

Too often new code is just cut'n'pasted from old code.
So when I see any bad code, I don't just fix that occurrence, but all occurrences.

**Comment by elfring** [comment]
I got the impression that specific software development tools exist that support also the handling of “blurry ideas” to some degree.
I imagine that there can be a challenge between the selection of the system refactoring for Mutt and the reuse of other popular (or well-known) software components.

**Comment by flatcap** [comment]
hehe, and Mutt certainly is "blurry"

**Comment by flatcap** [comment]
I've moved a LOT of members from Context to Mailbox, but there's still a lot of dubious code in the backends.

This table shows which API functions only need the Mailbox `O` and which rely on the Context and other functions `X`.

| MXAPI function   | imap | pop | nntp | nm | md | mh | mbox | mmdf | comp |
|------------------|------|-----|------|----|----|----|------|------|------|
| mbox_open        | X    | X   | X    | X  | X  | X  | X    | X    | O    |
| mbox_open_append | X    | .   | .    | .  | O  | O  | O    | O    | O    |
| mbox_check       | X    | X   | X    | X  | X  | X  | X    | X    | O    |
| mbox_sync        | .    | O   | X    | X  | X  | X  | X    | X    | O    |
| mbox_close       | X    | O   | O    | O  | O  | O  | X    | X    | X    |
| msg_open         | X    | O   | X    | O  | O  | O  | O    | O    | O    |
| msg_open_new     | X    | .   | .    | .  | O  | O  | O    | O    | O    |
| msg_commit       | X    | O   | .    | O  | O  | O  | O    | O    | O    |
| msg_close        | X    | .   | O    | O  | O  | O  | O    | O    | O    |
| msg_padding_size | .    | .   | .    | .  | .  | .  | O    | O    | O    |
| tags_edit        | X    | .   | .    | O  | .  | .  | .    | .    | O    |
| tags_commit      | X    | .   | .    | X  | .  | .  | .    | .    | O    |
| path_probe       | O    | O   | O    | O  | O  | O  | O    | O    | O    |
| path_canon       | O    | O   | O    | O  | O  | O  | O    | O    | O    |
| path_pretty      | O    | O   | O    | O  | O  | O  | O    | O    | O    |
| path_parent      | O    | O   | O    | O  | O  | O  | O    | O    | O    |

**Comment by flatcap** [comment]
imap's a mess of dependencies.  the other backends aren't so bad.

- pop_mbox_open
  - pop_fetch_headers
    - mx_update_context

- pop_mbox_check
  - pop_fetch_headers
    - mx_update_context

- nntp_mbox_open
  - nntp_fetch_headers
    - mx_update_context

- nntp_mbox_check
  - check_mailbox
    - ctx->tagged
    - ctx->deleted
    - ctx->new
    - mutt_set_flag
    - mutt_clear_threads
      - ctx->tree
      - mutt_hash_destroy
    - mx_update_context
    - nntp_fetch_headers
      - mx_update_context

- nntp_mbox_sync
  - check_mailbox
    - ...

- nntp_msg_open
  - mutt_parse_mime_message
    - mx_msg_open
    - mx_msg_close

- nm_mbox_open
  - mx_update_context

- nm_mbox_check
  - maildir_update_flags
    - mutt_set_flag
  - mx_update_context

- nm_mbox_sync
  - mh_sync_mailbox_message
    - maildir_sync_message
    - mh_sync_message

- nm_tags_commit
  - update_header_flags
    - mutt_set_flag
  - mutt_set_header_color

- maildir_mbox_open
  - maildir_read_dir
    - mh_read_dir
      - maildir_move_to_context
        - maildir_add_to_context
          - mx_update_context

- maildir_mbox_check
  - maildir_update_flags
    - mutt_set_flag
  - maildir_update_tables
    - mutt_sort_headers
    - mx_update_tables
    - mutt_clear_threads
  - maildir_move_to_context
    - maildir_add_to_context
      - mx_update_context

- mh_mbox_sync
  - mh_mbox_check
    - ...
  - maildir_mbox_check
    - ...
  - mh_sync_mailbox_message
    - maildir_sync_message
    - mh_sync_message
  - ctx->deleted

- mh_mbox_open
  - mh_read_dir
    - maildir_move_to_context
      - ...

- mh_mbox_check
  - maildir_update_flags
    - mutt_set_flag
  - maildir_update_tables
    - ...
  - maildir_move_to_context
    - ...

- mbox_mbox_open
  - mbox_parse_mailbox
    - mx_update_context
  - mmdf_parse_mailbox
    - mx_update_context

- mbox_mbox_check
  - mbox_parse_mailbox
    - mx_update_context
  - mmdf_parse_mailbox
    - mx_update_context

- mbox_mbox_sync
  - mutt_sort_headers
  - mx_fastclose_mailbox
  - mbox_mbox_check
    - ...
  - mutt_copy_message_ctx

- mbox_mbox_close
  - ctx->peekonly

- comp_mbox_close
  - ctx->append

**Comment by flatcap** [comment]
Updates:

- Nesting the compressed Mailbox failed.  Miserably.
  We can redirect all the functions, easily enough, but the scalars are a problem.

- Imap complexity.  It's not as bad as I first thought.
  ImapData keeps a Context pointer, but it's not used too much.
  I might save a Mailbox pointer too, so I can reduced the code complexity (and fix the actual problems later)

**Comment by flatcap** [comment]
Updates:
- Renamed `struct Header` to `struct Email`
  This object isn't really a header of anything, but the main representation of an email.
- Unify naming and usage of private data
  Structs `Mailbox` and `Email` allow backend-specific data to be attached.
- Reorganise the backend sources:
  1. static functions
  2. public functions
  3. mxapi functions (in order)

**Comment by flatcap** [comment]
Update:
I've inserted an `Account` object into the IMAP code (it's a dirty hack, so far).
(Technically there are three account objects: a Mailbox-Account, a Connection-Account and a Config-Account -- they'll get merged a bit, later).

Just to get here, has been a struggle.  Too much of the backend code uses global variables, or attaches Account-specific data to Mailboxes.  Hopefully, I can start fixing the scope of the data.

**Comment by flatcap** [comment]
Here are four accounts with mailboxes.
- **apple@10.8.0.1:143/** -- abbot, achebe, asprin, austin, awlinson
- **banana@10.8.0.1/** -- banker, bennet, butterworth, byrum
- **cherry@10.8.0.1:993/** -- cabell, caidin, capote, chalker, cross
- **damson@10.8.0.1/** -- daudet, descartes, drinkwater, dsouza, dumas, dunne

Next, I need to move the `Connection` and `ImapMboxData` (private data) under the `Account`.

![account1](https://flatcap.org/mutt/account1.svg)

**Comment by flatcap** [comment]
Not much progress, lately -- still trying to rearrange Mailboxes and Accounts.

My latest amusing discovery was about the `account-hook`.  For n mailboxes, it'll get called n<sup>2</sup> times!
Every IMAP mailbox path gets expanded which calls `imap_conn_find()` which triggers the hook.
When parsing the `mailboxes` command, we should be searching for Accounts, not Connections.

Another problem is that we're passing around a lot of string paths.
One part of the code calculates something, then another part repeats the process.
I think we might need to change some of the MXAPI functions from using paths to using Mailboxes.

**Comment by flatcap** [comment]
Slow progress.  It's hard to tell if the code is just badly written, or concealing some subtle rules.

The IMAP backend is complicated.  Every action seems to require searching the global list of connections.  The connections aren't shared between `Account`s, so this shouldn't be necessary.

Anyway...  Another week, another diagram.

The `MN`s (`MailboxNodes`) were hidden in the previous diagram.
They allow separate linked lists of `Mailbox`es.

![arch](https://flatcap.org/mutt/account3.svg)

In the future, the `AllMailboxes` won't be needed.  Nor the `Connections`.

**Comment by elfring** [comment]
>Another week, another diagram.

Would you dare to adjust the software implementation by developing together with [XML metadata interchange](https://en.wikipedia.org/wiki/XML_Metadata_Interchange "Description for XML metadata interchange") (in addition to publishing scalable vector graphics)?

**Comment by flatcap** [comment]
Not yet.  Things are changing quickly and I'd rather not spend too much time documenting things that aren't going to stay.

If I had a team of developers, it'd be nice to deconstruct neomutt, understand it, create a detailed plan and execute it.   But I don't.

It's just me and I'm changing things incrementally, as I understand them
(and as I find pieces that can be separated).

The recent diagrams are auto-generated from the running code.
I walk the object tree and generate a `dot` file ([graphviz](https://www.graphviz.org/)) which is then converted to svg.
[Source for the diagram above](https://flatcap.org/mutt/account3.gv)

**Comment by elfring** [comment]
Which development tool did generate helpful dot files for you?

**Comment by flatcap** [comment]
I don't know of any tools to generate dot files.
I either create by them by hand, or use script-fu for the bigger cases.

Doxygen generates inheritance and collaboration diagrams: https://neomutt.org/code/structEmail.html

**Comment by elfring** [comment]
Can doxygen-generated documentation help a bit more in the shown software transformation?

**Comment by elfring** [comment]
>A lot of the complexity won't show up in Doxygen.

Several dependencies are documented by this tool to some degree already, aren't they?


>My time is better spent fixing the code,

Such a view is generally nice.


>so nobody else has to suffer reading it.

I hope that other potential contributors will not suffer from rapid software evolution which you try to demonstrate on your own so far.

**Comment by flatcap** [comment]
> Several dependencies are documented by this tool to some degree already, aren't they?

Some, yes.  I've used Doxygen keywords to show linkage between some objects.

> I hope that other potential contributors will not suffer from rapid software evolution

*sigh*!  It can't be helped.
If we want neomutt to move forward then these changes need to be made.

**Comment by elfring** [comment]
I assume that special development tools can help you (and other participants) to make the software transformation a bit more constructive.

**Comment by flatcap** [comment]
I don't know about _special_ development tools.
Most of the tools I'm using are documented, [here](https://neomutt.org/dev/analysis).
They're good for finding widespread patterns and problems.

Most of my knowledge, though, comes from reading the source for hours and hours.

**Comment by elfring** [comment]
I hope that further higher level development tools can handle more source code transformation so that involved developers (like you) can spent their work capacity in more useful areas if desired (than reading source files alone).
:crystal_ball: Would you treat such files as enjoyable literature?

**Comment by flatcap** [comment]
## Account Development

I've just pushed over 30 commits to `master`.
They introduce an Account object into each of the backends. 

This diagram shows an example of all seven backends in action:
  https://flatcap.org/mutt/account5.svg

The commits also standardise the naming of a lot of functions and
variables that are common to the backends.

The code works, but is NOT STABLE.  Crashes are likely.

## Layout

NeoMutt keeps a list of Accounts.  Each Account can hold many Mailboxes.

An Account has a type and a pointer for backend-private data.
The Account contains everything that's common to ALL Mailboxes, e.g.
connection info.

A Mailbox has a type and many members common to all mailboxes (paths,
message counts, etc).  It also has a pointer for backend-private data.

## How it Works

NeoMutt parses your config.  When it finds a `mailboxes` command, it:

1. Creates a dummy Mailbox using the path
  - Expand any abbreviations, e.g. ~ + ^ (Using HomeDir, Folder, etc)
  - Create the canonical path
  - Identify the type of the Mailbox

Many of these actions are delegated to the backend.
They're performed on a Mailbox so that they only need to happen once.

2. For each Account (already known)
  - Ask Account: Do you understand this path?
    - Yes: Ask Account to add the Mailbox
    - Already exists: Drop the dummy Mailbox, return a real Mailbox

3. Create a new Account with the type of the Mailbox
  - Ask Account to add the Mailbox

## Problems / To do

- Connections
  - Currently, they're stored in a separate list.  This isn't
    particularly useful since they're not shared between Accounts.
  - Plan: split up find-or-open function and move the Connection to the
    private Account object
  - Result: Connections list dies

- Sidebar
  - Currently, this uses the AllMailboxes list, which can lead to some
    strange sorting and indentation.
  - Plan: Refactor the sidebar to use the AllAccounts list
  - Result: AllMailboxes list dies

Questions are welcomed.

**Comment by flatcap** [comment]
The `Connections` list has been dropped, so the object layout looks like:
![imap](https://flatcap.org/mutt/imap.svg)

**Comment by flatcap** [comment]
Many of the MXAPI functions have a `Context` parameter.
This is being phased out in favour of `Mailbox` which doesn't have ties to the UI.

These MXAPI functions don't make reference to `Context`:
- `ac_add()`
- `ac_find()`
- `path_canon()`
- `path_parent()`
- `path_pretty()`
- `path_probe()`

This table shows:
- :x: functions that use the `Context`
- :heavy_check_mark: functions that only need the `Mailbox`
- 'n/a' functions that aren't implements for this backend

| MxAPI / Backend  | **compress**       | **imap**           | **maildir**        | **mmdf**           | **nntp**           | **notmuch**        | **pop**            | **mbox**           | **mh**             |
| :--------------  | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: |
| mbox_open        | :x:                | :x:                | :x:                | :x:                | :x:                | :x:                | :x:                | :x:                | :x:                |
| mbox_open_append | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | n/a                | n/a                | n/a                | :heavy_check_mark: | :heavy_check_mark: |
| mbox_check       | :x:                | :heavy_check_mark: | :x:                | :x:                | :x:                | :x:                | :x:                | :x:                | :x:                |
| mbox_sync        | :x:                | n/a                | :x:                | :x:                | :x:                | :x:                | :heavy_check_mark: | :x:                | :x:                |
| mbox_close       | :x:                | :x:                | :heavy_check_mark: | :x:                | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x:                | :heavy_check_mark: |
| msg_open         | :heavy_check_mark: | :x:                | :heavy_check_mark: | :heavy_check_mark: | :x:                | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| msg_open_new     | :heavy_check_mark: | :x:                | :heavy_check_mark: | :heavy_check_mark: | n/a                | n/a                | n/a                | :heavy_check_mark: | :heavy_check_mark: |
| msg_commit       | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | n/a                | :heavy_check_mark: | n/a                | :heavy_check_mark: | :heavy_check_mark: |
| msg_close        | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| msg_padding_size | :heavy_check_mark: | n/a                | n/a                | :heavy_check_mark: | n/a                | n/a                | n/a                | :heavy_check_mark: | n/a                |
| tags_edit        | :heavy_check_mark: | :heavy_check_mark: | n/a                | n/a                | n/a                | :heavy_check_mark: | n/a                | n/a                | n/a                |
| tags_commit      | :heavy_check_mark: | :heavy_check_mark: | n/a                | n/a                | n/a                | :x:                | n/a                | n/a                | n/a                |

**Comment by flatcap** [comment]
Update: master @ da02b5563

| MxAPI / Backend  | **compress**       | **mbox**           | **mmdf**           | **maildir**        | **mh**             | **notmuch**        | **nntp**           | **pop**            | **imap**           |
| :--------------  | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: | :----------------: |
| mbox_check       | :heavy_check_mark: | :x:                | :x:                | :x:                | :x:                | :x:                | :x:                | :x:                | :heavy_check_mark: |
| mbox_close       | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x:                |
| mbox_open        | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x:                |
| mbox_open_append | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | n/a                | n/a                | n/a                | :heavy_check_mark: |
| mbox_sync        | :heavy_check_mark: | :x:                | :x:                | :x:                | :x:                | :x:                | :x:                | :heavy_check_mark: | n/a                |
| msg_close        | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| msg_commit       | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | n/a                | n/a                | :heavy_check_mark: |
| msg_open         | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| msg_open_new     | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | n/a                | n/a                | n/a                | :heavy_check_mark: |
| msg_padding_size | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | n/a                | n/a                | n/a                | n/a                | n/a                | n/a                |
| tags_commit      | :heavy_check_mark: | n/a                | n/a                | n/a                | n/a                | :heavy_check_mark: | n/a                | n/a                | :heavy_check_mark: |
| tags_edit        | :heavy_check_mark: | n/a                | n/a                | n/a                | n/a                | :heavy_check_mark: | n/a                | n/a                | :heavy_check_mark: |
