### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [neomutt/neomutt#1328]
I would like to point out that identifiers like “[`_IMAP_MESSAGE_H`](https://github.com/neomutt/neomutt/blob/34129a13f8bf7c93658f48a35b08b40339817de2/imap/message.h#L24 "Update candidate")” and “[`_MUTT_ALIAS_H`](https://github.com/neomutt/neomutt/blob/6a51706a5355701216c23345bd78511ef82e3839/alias.h#L23 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by flatcap** [comment]
> ... do not fit to the expected naming convention

Yeah, I kinda knew that in the back of my mind.

I've been aggressively renaming things to try to bring order to the code,
and that was the most common pattern for 'include guards'.

I've made a note to fix this, but it'll be very low priority unless someone reports a build problem...

... or someone has a bit of free time to create a Pull-Request :-)

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/neomutt/neomutt/commit/52283b344e13860421f3db0f7aaf5e80f6a4c555 "tweak #include guards").

Will it make sense to offer such an update also for [the original software](https://gitlab.com/muttmua/mutt/issues "Issue tracking for the Mutt e-mail client")?

**Comment by mschilli87** [comment]
@elfring:
>Will it make sense to offer such an update also for the [original software](https://gitlab.com/muttmua/mutt/issues)?

Maybe https://github.com/neomutt/neomutt/issues/1075 is a good place to get started on this. :wink:

**Comment by flatcap** [comment]
np.  10 minutes with vim and sed whilst watching tv.
