### ISSUE TITLE
request to import muttrc-mode-el subproject

### ISSUE THREAD

**Issue by sten0** [neomutt/neomutt#1330]
Muttrc-mode is like https://github.com/neomutt/neomutt.vim, but for Emacs.  It is currently maintained as part of the `emacs-goodies-el` Debian package, and there is also a copy on emacswiki.org which doesn't meet the criteria for "maintained".  The Debian Emacsen Team is in the process of finding new homes for most useful and popular subpackages from emacs-goodies-el and are removing the unmaintained parts from Debian.  Muttrc-mode is a very simple and mature Emacs addon that will pose a minimal maintenance burden.  Would you please consider creating the project?

I would filter the master branch of emacs-goodies-el's to only include history relevant to muttrc-mode.el, its documentation, and its licensing.  Then I will require a project with a dummy commit to fork from.  Then I'll file a PR, and after merging it should be ready to go.  Additionally, if someone would like to step forward as MELPA (melpa.org) maintainer I would be happy to provide assistance.  I've used muttrc-mode for many years and will maintain the Debian package, and because I am responsible for that package the expectation is that if any issues with the addon emerge, and these issues affect Debian users, then I (or the future maintainer of that package) have to help resolve them.

A Debian user who `apt search mutt` would find the package `elpa-muttrc-mode`.  `apt install elpa-muttrc-mode` installs and configures the package, and syntax highlighting for muttrc in Emacs will then "just work".  The MELPA repository and package.el works like this: http://wikemacs.org/wiki/Package.el  Tldr, it's a package manager for Emacs addons built into Emacs, and MELPA is the most popular repository.

## Have you tried any alternative methods?

Yes, muttrc-mode has been maintained as part of emacs-goodies-el since Tue, 27 Aug 2002.  I asked the Emacsen Team if anyone would want to maintain this package, and also contacted the Debian maintainers for mutt and neomutt some months ago.

## Additional Info

Muttrc-mode is:
Copyright: 2000, 2001, 2002 Laurent Pelecq
                 2009 Kumar Appaiah
License: GPL-2+

**Comment by flatcap** [comment]
Hi @sten0.  Sure.  Anything to help.

I don't use emacs, so I'll have to leave it in your hands.
So...
- Give me a name for the repo
- I'll give you permissions on it
- You can commit what you like
- When you're happy, I'll announce it to the devs

Thanks

**Comment by sten0** [comment]
Hi @flatcap,

Thank you, and sorry for the delay!  Lets go with `muttrc-mode-el` for the repo name.  I haven't yet added any gh-flavoured markdown to README.md, so that's still probably TODO.  Please feel free to nitpick https://github.com/sten0/muttrc-mode-el

**Comment by flatcap** [comment]
Forked: https://github.com/neomutt/muttrc-mode-el
You should now have commit privs to the repo.

If you have any questions about the config variables, commands, functions, etc, just ask.
When you're happy with it, I'll make an announcement.

Thanks.

**Comment by flatcap** [comment]
> ... and there's lots to improve

always :-)

> please go ahead and announce it.

Done: [Twitter](https://twitter.com/NeoMutt_Org), [Website](https://neomutt.org/news), User mailing list.

Many thanks.
