### ISSUE TITLE
Trouble Sending GPG Key

### ISSUE THREAD

**Issue by robjloranger** [neomutt/neomutt#1335]
I didn't want to open a bug report because this is likely configuration related.

I have been experimenting with both `mutt` and `neomutt` with the same results. I can send signed messages and messages with attachments but for some reason when trying to send my public key I get a failure with the following error.

```console
[2018-09-08 10:49:11]<E> smtp_get_resp() SMTP session failed: 554 Error: transaction failed, blame it on the weather: backend: cannot create draft: cannot create attachment: Failed to save attachment
```

I notice that when sending my key (neo)mutt is using TLS per the bottom status line. Normally it is not.

I'm using Proton Mail Bridge so TLS is not needed, is there a way to turn it off during this operation to test?

**Comment by robjloranger** [comment]
update: I disabled `ssl_starttls` and `ssl_force_tls` with the same result.

**Comment by gahr** [comment]
Is using GPGme an option for you? If it is, I'd go with that and forget about plain GPG commands.

**Comment by gahr** [comment]
I would start by replacing all your crypt config with `set crypt_use_gpgme = yes` and see how it goes.

**Comment by robjloranger** [comment]
I'm still getting the same issue, `SMTP session failed: 554 Error: transaction failed, blame it on the weather: backend: cannot create draft: cannot create attachment: Failed to save attachment` and the key being sent is now just a list of key IDs, not a public key block.

**Comment by gahr** [comment]
Looks like a problem with the bridge? I'm not a protonmail user myself, but people have been having this issue:
https://www.reddit.com/r/ProtonMail/comments/792wvj/anyone_having_problems_using_enigmail_with/

**Comment by robjloranger** [comment]
Hmm, I'll have to do some more research. I can send attachments, and signed, encrypted and signed/encrypted emails just fine. Something about trying to send a key. I can send a key as an attachment if I generate it myself.
