### ISSUE TITLE
Segfault with 50034a1da212d029498ca27ffafce8186d6bed45

### ISSUE THREAD

**Issue by nicolasbock** [neomutt/neomutt#1339]
## Expected Behaviour

With the latest master (e7bbfc141c79e3b7f182505815f3d28159b9abf9) neomutt segfaults when starting or sometimes later during normal mail reading actions. I bisected the code and found that by partially reverting 50034a1da212d029498ca27ffafce8186d6bed45 neomutt works again. I don't understand why this partial revert fixes it though.

Thanks!

```
diff --git a/mailbox.h b/mailbox.h
index 29fdf6fd1..973e7de3b 100644
--- a/mailbox.h
+++ b/mailbox.h
@@ -74,8 +74,6 @@ enum AclRights
  */
 struct Mailbox
 {
-  enum MailboxType magic;    /**< mailbox type */
-
   char path[PATH_MAX];
   char realpath[PATH_MAX]; /**< used for duplicate detection, context
                             * comparison, and the sidebar */
@@ -94,6 +92,7 @@ struct Mailbox
   int vcount;               /**< the number of virtual messages */
 
   bool notified;             /**< user has been notified */
+  enum MailboxType magic;    /**< mailbox type */
   bool newly_created;        /**< mbox or mmdf just popped into existence */
   struct timespec mtime;
   struct timespec last_visited;       /**< time of last exit from this mailbox */
```

**Comment by flatcap** [comment]
Thanks for the bug report, @nicolasbock.

> partially reverting [50034a1](https://github.com/neomutt/neomutt/commit/50034a1da212d029498ca27ffafce8186d6bed45) neomutt works again

Yes, there's something quite odd going on -- some devs saw a crash (inc. me), others didn't.
The crash occurs if the `path` isn't the first member in `struct Mailbox`.

I still have a lot of architectural changes to make.  Hopefully, they'll fix things.

**Comment by nicolasbock** [comment]
Doesn't this suggest that there is some incorrect memory access happening inside the struct? Maybe some members are not typed correctly? Or does anything access the struct directly, e.g.

```
struct Mailbox temp;
char *path;
path = &temp;
```

As opposed to

```
path = &temp->path;
```

This is just a really wild guess though :wink:

**Comment by flatcap** [comment]
Something like that, yes.
There's quite a bit of `void*` passing in the mailbox code.
