### ISSUE TITLE
some github links below  neomutt.org are 404

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#134]
Hey,
the links under "Source" on this site: http://www.neomutt.org/contrib.html are 404. They link to 

https://github.com/neomutt/neomutt/tree/contrib/vim-keybindings instead of https://github.com/neomutt/neomutt/tree/neomutt/contrib/vim-keybindings

I would edit that myself and send a pull request, but i don't know how i can edit http://www.neomutt.org/contrib.html, there's no such file.

**Comment by flatcap** [comment]
hi @toogley 
Thanks, fixed.

> I would edit that myself...

The website is a separate repo: https://github.com/neomutt/neomutt.github.io
GitHub use Jekyll to generate the website.
