### ISSUE TITLE
/home/mg/Mail/INBOX is not a mailbox

### ISSUE THREAD

**Issue by mgedmin** [neomutt/neomutt#1341]
## Expected Behaviour

I built myself a newer version of NeoMutt (version f20180716-421-ff8684) from git and ran it on my work server where my mail resides in mbox files.  I expected to continue using it to read my mail, like I used to with the Ubuntu-packaged neomutt 1.6.2-neo (2016-08-21).

## Actual Behaviour

`mutt` produces this error on startup:

    /home/mg/Mail/INBOX is not a mailbox

(/home/mg/Mail/INBOX is, currently, a 0-length regular file because I have no new mail.)

## Steps to Reproduce

1. touch /tmp/empty.mbox
2. mutt -f /tmp/empty.mbox

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?  neomutt 1.6.2-neo (2016-08-21)

## NeoMutt Version

```
NeoMutt 20180716-421-ff8684
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.4.0-135-generic (x86_64)
ncurses: ncurses 6.0.20160213 (compiled with 6.0.20160213)
libidn: 1.32 (compiled with 1.32)
GPGme: 1.6.0
hcache backends: tokyocabinet

Compiler:
cc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --prefix=/usr --sysconfdir=/etc --with-mailpath=/var/mail --mixmaster --gnutls --gpgme --gss --sasl --lua --notmuch --tokyocabinet

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3  -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  +gnutls +gpgme +gss +hcache -homespool +idn +inotify -locales_hack +lua +meta 
  +mixmaster +nls +notmuch -openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Ubuntu 16.04 LTS
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? local

**Comment by mgedmin** [comment]
FWIW a 0-length file is what (this version and actually all versions of) NeoMutt leaves when you delete the last email in a mailbox.

**Comment by mgedmin** [comment]
For the record, the last tagged release (neomutt-20180716) is unaffected.

**Comment by flatcap** [comment]
Thanks @hsanson.
NeoMutt used to have shared code to determine the type, or empty-ness, of a mailbox.
We're currently in the process of splitting that up into mailbox-specific backends.
Ideally (not entirely possible), NeoMutt would know nothing about mailboxes.

**Comment by Austin-Ray** [comment]
@mgedmin does this issue still occur? I just tried your steps and was unable to reproduce.

**Comment by hsanson** [comment]
@Austin-Ray I can confirm this no longer happens on my machine. I am using master branch commit bb8cda3b8 currently.

**Comment by mgedmin** [comment]
I've been told on IRC that I shouldn't expect `master` to be stable, due to the large refactorings that were underway, so I switched to the last release tag and stopped tracking master's changes.

I could build a recent master and test it again, if you wish, but the reproduction steps are rather simple and anyone could verify if the issue still exists or not.  (That is, I don't believe my muttrc had any effect on this bug.)

**Comment by ubuntupunk** [comment]
Confirm this is happening with 20180716, is there something we need to do to mailpath in auto.def?

**Comment by mgedmin** [comment]
Whoa, I never had this bug on neomutt-20180716, which I run daily (but a self-built copy rather than the packaged version from Ubuntu archives, out of inertia).

Ubuntu 18.04 LTS ships neomutt 20171215+dfsg.1-1, so are you building from sources too, @ubuntupunk?  Are you building the neomutt-20180716 tag, or some later version (that will self-identify as 20180716-xxx-xxxxxxx)?

**Comment by ubuntupunk** [comment]
building directly from the released source available on release page.
