### ISSUE TITLE
Neomutt will not start after libidn update 1.34 -> 1.35

### ISSUE THREAD

**Issue by mor3dr3ad** [neomutt/neomutt#1344]
## Expected Behaviour

Neomutt should start up.

## Actual Behaviour

neomutt: error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory

If NeoMutt crashed, did your OS create a 'coredump' file?

## Steps to Reproduce

With latest neomutt version on Arch linux, update the libidn package from 1.34 to 1.35. 

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
After upgrading on Arch linux. 

## NeoMutt Version

NeoMutt 20171027-31-3fe1b1-dirty
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type `neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type `neomutt -vv' for details.

System: Linux 4.18.7-arch1-1-ARCH (x86_64)
slang: 20301
libidn: 1.34 (compiled with 1.33)

Compiler:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 7.2.0 (GCC) 

Configure options: '--with-slang' '--enable-notmuch' '--enable-lua'

Compilation CFLAGS: -Wall -pedantic -g -O2 -fno-delete-null-pointer-checks

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -bkgdset +color -curs_set -debug +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss -hcache -homespool +idn -locales_hack +lua 
  -meta -mixmaster +nls +notmuch -openssl +pgp -resizeterm -sasl +smime 
  -start_color +sun_attachment -typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: http://www.neomutt.org/
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

## Extra Info

* Operating System and its version
Arch linux kernel 4.18.7-arch1-1-ARCH

**Comment by mor3dr3ad** [comment]
The issue can - for now - be resolved by reverting to the 1.34 version of libidn.

**Comment by flatcap** [comment]
Thanks for the bug report, @mor3dr3ad.

A few things stand out...

>  libidn: 1.34 (compiled with 1.33)

That's not good.  Neither are the v**1.35** you expected.

This means the build found v**1.33** libraries,
and NeoMutt found v**1.34** shared libraries when it ran.

> NeoMutt 20171027-31-3fe1b1-dirty

The latest release (2018-07-16) is 9 months newer.  Please can you give that a try.

> slang: 20301

Unless you specifically need slang, we'd recommend using ncurses.
ncurses is more widely used and hence (slightly) better understood.

**Comment by mor3dr3ad** [comment]
Ah sorry, I ran neomutt -v after downgrading to version 1.34. When I upgrade to 1.35 again, neomutt -v will give the same error as above. 

I do not remember why I installed this version, but I guess it is from the official arch linux repositories. Will try to use another release and be back here.

**Comment by mor3dr3ad** [comment]
Sorry all, my fault: I had an old version built from source. My bad (bad _past me_!!). Resolved by getting the official version with pacman

**Comment by flatcap** [comment]
Glad things are working.  Thanks for letting us know.
