### ISSUE TITLE
support notmuch thread reconstruction even when not in vfolder

### ISSUE THREAD

**Issue by zacchiro** [neomutt/neomutt#1345]
I'm the author of [notmuch-mutt](https://notmuchmail.org/notmuch-mutt/), but I've been looking into neomutt's notmuch support as its integration potential is *much* better. Thanks a lot for that. There is a specific use case in which notmuch-mutt user experience is still better, though, and I think it can be easily improved into neomutt.

Specifically, it is useful to be able to reconstruct the full thread of a given message (similar to what `<entire-thread>` does) even when the user is *not* in a vfolder. Currently, trying to use `<entire-thread>` in that situation results in an error: "No virtual folder, aborting.".

Here is what I think should be done instead:

- run a notmuch query on-the-fly filtering on `id:MESSAGE_ID`, where `MESSAGE_ID` is the message identifier of the currently selected message (in the index or pager)
- jump to the vfolder corresponding to the result of that query, similarly to what `<vfolder-from-query>` does
- expand the thread as `<entire-thread>` currently does

I think that doing this would provide a much smoother UX. What do you think?

**Comment by flatcap** [comment]
Hi @zacchiro.  Welcome to NeoMutt!  Sorry for not reaching out to you.

> neomutt's notmuch support as its integration potential is much better.
> Thanks a lot for that.

Hats off to @karelzak

> it is useful to be able to reconstruct the full thread of a given message

> run a notmuch query on-the-fly filtering on id:MESSAGE_ID,
> jump to the vfolder corresponding to the result of that query,
> expand the thread as <entire-thread> currently does

> I think that doing this would provide a much smoother UX. What do you think?

Sounds reasonable (but I'm not a Notmuch expert).

@neomutt/notmuch-users What do you think?
