### ISSUE TITLE
chrome and firefox say https://www.neomutt.org/ is insecure

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#135]
Hey.

both browsers display

https://www.neomutt.org/ as insecure, but
https://neomutt.org/  as secure.

![2016-09-10-055053_1600x900_scrot](https://cloud.githubusercontent.com/assets/9417950/18407775/d993f078-771a-11e6-84d0-0bf68e49db9e.png)

-------

### Versions used
* Mozilla Firefox 48.0.1
* Chromium 52.0.2743.116 Fedora Project

both were started with a clean config.

**Comment by flatcap** [comment]
Unfortunately, I can't fix this directly.
The site is hosted by GitHub and they don't support https on custom domains.
A quick bit of Googling shows that I can set up a CloudFlare CDN account to "wrap" the GitHub pages.

**Comment by pickfire** [comment]
@flatcap Do we really need https, there is no login or authentication required though. I don't find https necessary, it's just adding burdens.

**Comment by flatcap** [comment]
**Need?** No.  But it's free and no burden to us after setup.
CloudFlare "magically" do all the work, we just update the site as normal.

**Comment by pickfire** [comment]
Well, not exactly a burden but just increase add one more round trip time to the users.

By the way, @flatcap I think it you should disable captcha on cloudflare's "magic" for tor users. I hate solving crazy puzzles.

**Comment by flatcap** [comment]
It's enabled for now, but all my original DNS is in place so I can switch it back in a instant.

> Well, about 400ms rtt

Really?  So GitHub's CDN serves you better than CloudFlare?
If you're finding it a pain, I'll go back to just GitHub.

> you should disable captcha on cloudflare's "magic"

There isn't an option to disable it, but I've set it to the max -- once a year.

> for tor users

Do you normally visit our site via TOR? :-)

**Comment by pickfire** [comment]
Nope, just an estimation. I was shocked that it was as low as 109ms (for the highest among 10 packets).

Well, I do use Tor most of the time back then. Now, depends since I can't use Tor on school network.
