### ISSUE TITLE
Installed gpg.rc does not reflect provided libexecdir

### ISSUE THREAD

**Issue by jelly** [neomutt/neomutt#1350]
## Expected Behaviour

Make install'ed gpg.rc and other configuration files contain a paths to pgpewrap which reflect the provided libexecdir in ./configure

## Actual Behaviour

pgpewrap's path is hardcoded to `/usr/libexec/neomutt/pgpewrap`

## Steps to Reproduce

```
./configure --libexecdir=/usr/lib
make install
```

## How often does this happen?

- Always

## NeoMutt Version

```
NeoMutt 20180716
```

## Extra Info

* Arch Linux

**Comment by flatcap** [comment]
Fixed by 224996641
