### ISSUE TITLE
Viewing Attachments immediately deletes temp-file in /tmp/

### ISSUE THREAD

**Issue by whnr** [neomutt/neomutt#1353]
Workflow:
1) Open attachment with mailcap (`xdg-open %s`)
2) File viewer opens and mutt creates tempfile
3) Tempfile is _immediately_ deleted by mutt
4) Fileviewer complains that there is nothing to view

I guess this is even intended behaviour. If yes: Is there a config-switch for this? `set wait-key` does not seem to be it?

**Comment by whnr** [comment]
Hi @flatcap 

Thanks for the quick reply!

> What you need is a sleep:
> This gives the browser a chance to open the file before it's deleted.

This works if the receiving app is either using it's own temp system (Browser) or keeps stuff in RAM. However, there are a few that watch for changes in the files. This will lead images disappearing exactly after "sleep" seconds.

But any change would be a complete rewrite of the way temporary files are handled. It might be best to leave it in the users hands. If one can use mutt she might be able to hack a usable shell script.

I like the workaround with copying away files to another temporary directory, that is removed, when mutt is closed. Credit: https://unix.stackexchange.com/a/109738

**Comment by whnr** [comment]
OK, this is getting a bit weird. Before opening a bug. I want a second opinion. Now I'm copying files away when opening them. When I shutdown neomutt I iissue the following command to clear my temp-files:

    shutdown-hook `rm -f /tmp/mutt/*`

However, the command seems to be issued, when I start neomutt the next time! Is there any known mixup?

**Comment by flatcap** [comment]
Ha!  Brilliant.
It took me a while to understand what was going on and why.

The `startup-hook` and `shutdown-hook` take a **NeoMutt** command, not a shell command.

NeoMutt reads the config file at startup, sees the backticks and executes them in order to get the result.  `rm -f /tmp/mutt/*` doesn't output anything, so NeoMutt sees `shutdown-hook` with no parameters, which gets ignored.

It's a bit of a pain, but you can run external commands like this:
```
startup-hook  'echo `action.sh ARGS`'
shutdown-hook 'echo `action.sh ARGS`'
```

The single quotes prevent the backticks being expanded.
The `echo` command prevents and empty command error (and isn't noticeable).

**Comment by whnr** [comment]
Perfect, that was it.

Using an “! comand.sh” in this context does not work either. That was my first try.

I guess I’d like that information in the documentation. I’ll check the website on how to contribute.

**Comment by flatcap** [comment]
> I’ll check the website on how to contribute.

Thanks for the offer.  Anything you can add would be appreciated.

Currently, the documentation is in DocBook (xml) format in the [source repo](https://github.com/neomutt/neomutt).

https://github.com/neomutt/neomutt/blob/7c9a6d976dbe663761a2d8e4c0654839bb8c1fa3/doc/manual.xml.head#L12393-L12550

(There are plans in progress to make contribution easier)

**Comment by jlapeyre** [comment]
I was struggling to use `startup-hook` and `shutdown-hook` a week or so ago, and gave up.  Instead I run neomutt with a shell script `startmutt`. This also sets my environment preferences that are particular to neomutt, starts and stops polling the imap servers, etc.

**Comment by flatcap** [comment]
Thanks to @0x747972, NeoMutt now has a new method for handling the viewing of attachments.
NeoMutt simply **keeps a list** of them and **deletes them on exit**.

Currently, `master` is unstable and isn't suitable for general use,
but as soon as it is we'll make a release with the new feature.

**Comment by 0x747972** [comment]
While where at it. Maybe we should do that in the signal handlers, too.

**Comment by jolars** [comment]
For anyone who stumbles upon this post, there is a script in https://github.com/LukeSmithxyz/mutt-wizard that deals with this:

https://github.com/LukeSmithxyz/mutt-wizard/blob/bd0075898ae441bb5e59f83d8b34df68b55aafb3/bin/openfile#L1-L10

**Comment by wgmayer0** [comment]
I tried `wait` instead of `sleep` which seems to be working
