### ISSUE TITLE
Scrolling in neomutt hangs every few seconds

### ISSUE THREAD

**Issue by sebastianw** [neomutt/neomutt#1359]
## Expected Behaviour

Scrolling through message list or message itself is smooth.

## Actual Behaviour

Cursor / scrolling hangs every few seconds. CPU spike from neomutt is seen in top.

## Steps to Reproduce

Open a mailbox and scroll up or down for a few seconds (cursor up / cursor down)
After few seconds scrolling will hang for ca. 1 second before resuming. Meanwhile top shows high CPU from neomutt.

## How often does this happen?

- Always

## When did it start to happen?

- Unsure

## NeoMutt Version

NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.9.0-7-686-pae (i686)
ncurses: ncurses 6.0.20161126 (compiled with 6.0.20161126)
libidn: 1.33 (compiled with 1.33)
hcache backends: tokyocabinet

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/6/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=i686-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-targets=all --enable-multiarch --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

Configure options: --build=i686-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/i386-linux-gnu} {--libexecdir=${prefix}/lib/i386-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/lib --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/home/fire/tmp/neomutt/neomutt-20180716+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3  -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo
  +gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta
  +mixmaster +nls +notmuch -openssl +pgp +sasl +smime +start_color
  +sun_attachment +typeahead
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

## Extra Info

* Operating System and its version

Debian Stretch 9.5

* Were you using multiple copies of NeoMutt at once?

No

* Were you using 'screen' or 'tmux'?

tmux

* Is your email local (maildir) or remote (IMAP)?

local (maildir)

**Comment by flatcap** [comment]
Thanks for the bug report, @sebastianw.

That's certainly a bit strange.
NeoMutt reads the directory, then it doesn't really do much when you scroll through the list.

Can you try again using a minimal config file.  Probably just `mailboxes DIR` will do.
If that works smoothly, then see if you can find the line of config causing trouble.

If not, could you downgrade; install an old version and see if that fixes the problem.

Thanks.

**Comment by sebastianw** [comment]
Okay, I narrowed it down. I load a lot of mailboxes, some of them static (with `mailboxes =bla`) and some dynamically by scripts like these:

    source "~/tools/mailbox-gen --mutt|"

As soon as I load these commands in my configuration it gets slow. I ran an strace on neomutt, and when it slows down I see mutt scanning these mailboxes (opening directories, stat64() files in there...) while I scroll. When this happens my scrolling freezes.

This probably happens to update some statistics or see where new mails are?

**Comment by flatcap** [comment]
Ah, I see.  It's not the script, it's the amount of mailboxes.
NeoMutt monitors every mailbox, that's `mailboxes`d.

If you have LOTS of mailboxes, then you could `set mail_check_stats = no` and manually call `<check-stats>` when you want to force an update.

Or you could leave the automatic checking enabled and lower the frequency: `mail_check_stats_interval=300` (5 mins).

**Comment by sebastianw** [comment]
> If you have LOTS of mailboxes, then you could `set mail_check_stats = no` and manually call `<check-stats>` when you want to force an update.

I set `mail_check_stats` to `no` but that did not help. Also the ` mail_check_stats_interval`  is set to 60 seconds but my scrolling freezes circa every five seconds.

**Comment by sebastianw** [comment]
Okay, I found the culprit. `mail_check` is set to 5 (seconds) and when I change that to 60 the freezing goes away. I would love to keep `mail_check` to 5 seconds but without the freezes. ;)

**Comment by flatcap** [comment]
too many config variables... argh!

The current development version of NeoMutt (`master`) has support for 'inotify' (Linux only)
Rather than looking for new changes, the kernel will tell us if something changes.

This would probably solve your problem, but...
`master` may be unstable (I'm making some large architectural changes).
It's unlikely to eat your emails, but it may crash.

**Comment by sebastianw** [comment]
Well I'm quite happy to wait for these changes, it's not something that's really keeping me from using mutt but it gets annoying over time. ;) Or if it bugs me more in the coming weeks I'll try to compile `master` on my Debian box and see how that goes.

**Comment by hsanson** [comment]
I have the same issue since I updated neomutt a few days ago. Navigating the messages in the index in unbearable slow as it hangs for several seconds every few messages scrolled. I navigate using j/k keys only. Even loading the index takes time, I can see the "sorting mailbox" message at the bottom, before this was so fast that I barely saw that message.

I did a git-bisect and found the issue started with commit b71ac2bae5d. Any commit before this one does not present the slowness when scrolling messages in the index.

Here is a minimal configuration that manifests the problem:

```
set nm_query_type = "threads"
set nm_default_uri = "notmuch:///home/Mail"
set virtual_spoolfile=yes

virtual-mailboxes "Inbox"   "notmuch://?query=path:mymail@gmail.com/** AND tag:inbox AND NOT tag:killed AND NOT tag:spam"
virtual-mailboxes "Sent"   "notmuch://?query=path:mymail@gmail.com/** AND tag:replied AND NOT tag:killed AND NOT tag:spam"
virtual-mailboxes "Archive" "notmuch://?query=path:mymail@gmail.com/** AND NOT tag:inbox AND NOT tag:killed AND NOT tag:spam"
virtual-mailboxes "Spam"    "notmuch://?query=path:mymail@gmail.com/** AND tag:spam"
virtual-mailboxes "Trash"   "notmuch://?query=path:mymail@gmail.com/** AND tag:killed AND NOT tag:gitlab AND NOT tag:zabbix"
```

Notes:

 - The slowness only happens if nm_query_type is `threads` and I have more than one virtual mailbox with 10,000+ messages each. 
 - In my case the Archive and Trash inbox contain around 15,000 and 16,000 messages respectively.

**Comment by Austin-Ray** [comment]
@flatcap We should revert that commit until we can fix the issue. It offers little while costing our performance.

It took me using a virtual-mailbox with >80K messages to reproduce the issue, but when it occurred, NeoMutt was completely unusable (it took half a minute to go to the next message.) I think this is exposing an architectural bug in NeoMutt. NeoMutt is repeatedly counting the number of messages for a mailbox instead of recounting on some event. Until that particular architectural detail is addressed, I don't think anyone will mind the sidebar count being slightly off.

**Comment by flatcap** [comment]
@hsanson 
I've reverted that commit.
Please can you give master `8fffcf766` a try.

Thanks.

**Comment by hsanson** [comment]
@flatcap I can confirm that master now works smooth as before. Thanks.
