### ISSUE TITLE
neomutt 2016-09-10: tarname in AC_INIT is not correct

### ISSUE THREAD

**Issue by aradici** [neomutt/neomutt#136]
The latest release has [neomutt] as second last argument of AC_INIT in configure.ac, that causes the docs to be installed in /usr/share/doc/neomutt and the locales to be called neomutt.mo.

Changing it to [mutt] will fix the issue (and it will also make sure that people who have a locale different from English will get the right messages, as the binary generated is still called mutt).

**Comment by aradici** [comment]
bisecting, it seems that the change was introduced in
037b5ed3e863fafb980b7419aa160b2628787e1a

We didn't see in Debian until now because I used to replace the AC_INIT with the one previously present, because of #128, now that #128 is fixed, I keep the AC_INIT and I get the error

**Comment by darnir** [comment]
@flatcap: this was probably introduced when I sent the large pr to change
the branding. Please change it back to mutt for now

Thanking You,
Darshit Shah

**Comment by Knusper** [comment]
Is this the reason that I get the following error when running `make install`:

`for f in COPYRIGHT GPL INSTALL ChangeLog ChangeLog.neomutt README NEWS TODO README.SECURITY README.SSL README.neomutt README.notmuch ; do \
        /usr/bin/install -c -m 644 ../$f /home/knusper/local/share/doc/neomutt ; \
done
/usr/bin/install: der Aufruf von stat für „../README.notmuch“ ist nicht möglich: Datei oder Verzeichnis nicht gefunden
Makefile:643: recipe for target 'install-data-local' failed`

**Comment by riesebie** [comment]
* Knusper <notifications@github.com> [2016-09-11 06:48 -0700]:

> Is this the reason that I get the following error when running `make install`:

No!

> 
> `for f in COPYRIGHT GPL INSTALL ChangeLog ChangeLog.neomutt README NEWS TODO README.SECURITY README.SSL README.neomutt README.notmuch ; do \
>         /usr/bin/install -c -m 644 ../$f /home/knusper/local/share/doc/neomutt ; \
> done

This is the reason:
> /usr/bin/install: der Aufruf von stat für „../README.notmuch“ ist nicht möglich: Datei oder Verzeichnis nicht gefunden

Elimar
-- 
  We all know Linux is great... it does infinite loops in 5 seconds.
        -Linus Torvalds

**Comment by flatcap** [comment]
I've fixed the AC_INIT to use a tarname of "mutt" which means the docs and translations are now in the right places.  Also, the "make dist" tarfile now works correctly.

Commit: e499cf7
