### ISSUE TITLE
notmuch: No progress update when opening large mailbox

### ISSUE THREAD

**Issue by Austin-Ray** [neomutt/neomutt#1368]
## Expected Behaviour

Output progress when opening `virtual-mailboxes`

## Actual Behaviour

NeoMutt keeps progress at `0%` until mailbox is open.

## Steps to Reproduce

1. Open a large `virtual-mailboxes`
2. Look at progress output

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded

Built off of `master`

## NeoMutt Version

```
NeoMutt 20180716-563-d75c33
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.18.16-1-ck (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.35 (compiled with 1.35)
GPGme: 1.12.0
hcache backends: gdbm

Compiler:
Using built-in specs.
COLLECT_GCC=/usr/bin/cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.1 20180831 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn=/usr --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=native -O2 -pipe -fstack-protector-strong -fno-plt -ftree-vectorize -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls +gpgme +gss +hcache -homespool +idn +inotify -locales_hack +lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
`Arch Linux`
* Were you using multiple copies of NeoMutt at once?
No
* Were you using 'screen' or 'tmux'?
No
* Is your email local (maildir) or remote (IMAP)?
Local

Possible offending commits (`git bisect` had a lot of instant crashing commits):

23dc0841d5f3a44fb8323e1a09aec56daa39a22d
eba15daafb8c2a614992aeeaaf263d964e41a1ff
87f487c35b1720e6c69a205c969d4e0e5ddf762f
e46ba978910c911ec57aea7fb7735a5a941717c5
d29c062d9324e8d5c2d78cb8b0d5fe046f64c806

**Comment by flatcap** [comment]
The progress bar seems to work OK for maildir and imap.

**Comment by Austin-Ray** [comment]
> The progress bar seems to work OK for maildir and imap.

Good that the scope is narrowed to (probably) just `virtual-mailboxes`. I'll edit the ticket.

**Comment by Austin-Ray** [comment]
I found why we're printing zero progress, but haven't located the exact point of cause.

https://github.com/neomutt/neomutt/blob/d75c33ecafc2388a3b237ea340728c17a8adf4f6/notmuch/mutt_notmuch.c#L847-L848

The specific part that creates the error is `m->msg_count + mdata->ignmsgcount - mdata->oldmsgcount`. I placed debug statements before this line on both `master` and a known good commit.

 On master, `mdata->oldmsgcount` equals the total number of messages in the mailbox we're opening. On the good commit, it is equal to zero. 

So we end up with a negative number when evaluating the value to pass and `mutt_progress_update(...)` gives us a zero.

An easy solution would be to remove the subtraction of `mdata->oldmsgcount`; however, I do not know if this would be hiding the root cause. It could be that the old code was wrong and we did not see the bug until now.

**Comment by flatcap** [comment]
I zeroed the msg count when opening a mailbox because at that time the msg array is empty.
(that array _used_ to live on `Context`)

So, yes the maths needs fixing.

Also, I see a discrepancy between the sidebar count and the actual result of the query.
(my old progress bar went up to 125% -- Nigel Tufnel lives)

**Comment by Austin-Ray** [comment]
> I zeroed the msg count when opening a mailbox because at that time the msg array is empty.

I checked against the good commit and message count is starts at zero (since that's how many we've loaded so far.) The issue that occurred during the architectural changes is `oldmsgcount` is being set to the total number of messages for a query. 

I wonder if the subsystem used to create and free mbox data whenever so the `oldmsgcount` was normally zero, but the architectural changes kept the mbox data around.

> Also, I see a discrepancy between the sidebar count and the actual result of the query.

Is that happening on the first mailbox? I've noticed that my first mailbox has no unread or total message counts until I swap mailboxes or modify tags.

**Comment by flatcap** [comment]
> > Also, I see a discrepancy between the sidebar count and the actual result of the query.

I only noticed it on a large query.
I wondered if the initial search matched **messages**, but the mailbox displayed **threads**.

**Comment by Austin-Ray** [comment]
> I wondered if the initial search matched messages, but the mailbox displayed threads.

I think that happened before the architectural changes. The `nm_nonctx_get_count(...)` function only counts the number of messages matching a query, but doesn't include non-matching messages in returned threads. We use that number for total message count. When I added correct counting, it killed performance (that was the commit we reverted.)
