### ISSUE TITLE
notmuch: stuck writing to database when opening virtual mailbox after modifying tags

### ISSUE THREAD

**Issue by Austin-Ray** [neomutt/neomutt#1373]
Offending commit: 677b7d46f0002c84711a52fef88d3bed86eb8041

## Expected Behaviour

NeoMutt should open a virtual mailbox after notmuch tags have been modified.

## Actual Behaviour

NeoMutt is stuck with the message "Writing notmuch://some-query" when opening a virtual mailbox after using `modify-labels` or `modify-labels-then-hide` on a message.

## Steps to Reproduce

1. Open `virtual-mailbox`
2. Modify tags on message (sometimes you need to do multiple)
3. Try to change to virtual mailbox

## How often does this happen?

- Always

## When did it start to happen?

After architectural changes

## Extra Info

* Operating System and its version
Arch Linux

* Were you using multiple copies of NeoMutt at once?
No

* Were you using 'screen' or 'tmux'?
No

* Is your email local (maildir) or remote (IMAP)?
Local

**Comment by Austin-Ray** [comment]
Running NeoMutt with debug output level 5, the call that NeoMutt gets stuck in is `nm_db_do_open(...)`. I assume its the call to `notmuch_database_open_verbose(...)`  is the culprit since the timeout is completely ignored and no error messages are displayed.

**Comment by Austin-Ray** [comment]
@flatcap 

I believe I have found the specific spot that leads to writing getting suck. Below is the full function diff from 677b7d4.

```diff
-static notmuch_database_t *get_db(struct NmMboxData *mdata, bool writable)
+static notmuch_database_t *get_db(struct Mailbox *m, bool writable)
{
-  if (!mdata)
+  if (!m || (m->magic != MUTT_NOTMUCH))
+    return NULL;
+  struct Account *a = m->account;
+  if (!a)
+   return NULL;
+  struct NmAccountData *adata = a->adata;
+  if (!adata)
    return NULL;
-  if (mdata->db)
-    return mdata->db;
-  const char *db_filename = get_db_filename(mdata);
+  const char *db_filename = get_db_filename(m);
  if (db_filename)
-    mdata->db = do_database_open(db_filename, writable, true);
+    adata->db = do_database_open(db_filename, writable, true);
-  return mdata->db;
+  return adata->db;
}
```

The specific part is:
```diff
-  if (mdata->db)
-    return mdata->db;
```
When Account was added, the check for existing database was removed. As such, we try to open a database every time. Adding the Account equivalent prevents NeoMutt was getting stuck while writing. 


However, if modifying tags for more than email, the some tags are not properly synced across mailbox, but #1374 occurs every time this happens. I believe #1374 to be a blocker for us to verify for certain that this is the proper fix. Though messed up tags is less of an issue than unable to use NeoMutt.

**Comment by Randalix** [comment]
I think the issue was with notmuch. Maybe another process locked the database. After a reboot everything works as expected.
