### ISSUE TITLE
attach_keyword change string to regex

### ISSUE THREAD

**Issue by mrajner** [neomutt/neomutt#138]
I like new forgotten-attachment settings in .muttrc. However it would be nice if it could support also regex definition in `attach_keyword`, not only single string.
That functionality would be useful for multilingual uses.

**Comment by flatcap** [comment]
That **would** be useful.
@darnir who merged the patch didn't have time to do anything more with it.
I'm sure we'll find some time to extend it.

**Comment by mjk-gh** [comment]
I second the desire to support more than just one keyword,
but would like to propose a (maybe) simpler solution: a
space-separated list of keywords, like so:

> set attach_keywords="Anhang angeh&auml;ngt h&auml;ngt\ an"

(Note the use of backslash in the terminal phrase "h&auml;ngt an",
which is German for "is attached".)

Of course, I would not object to the above being written as

> set attach_keywords="(Anhang|angeh&auml;ngt|h&auml;ngt an)"

if you supported regex, just thought that a space-separated list
might be easier and thus faster to implement. Maybe amend this
patch with regex later and make both co-exist, e.g. by interpreting
"/pattern/" as regex pattern, everything else as string list.

**Comment by flatcap** [comment]
## Help Us

There are plenty of examples, in Mutt, of parsing strings and checking regexes.
These could be copied to extend the "forgotten-attachment" feature.

If you know how to code in C, even a little, then I will be happy to help you make this enhancement become a reality.

Writing code is the guaranteed way to get the feature into NeoMutt :-)

**Comment by flatcap** [comment]
#### This enhancement will be in the next release of NeoMutt.
