### ISSUE TITLE
Pattern type for external indexers

### ISSUE THREAD

**Issue by nobrowser** [neomutt/neomutt#1386]
## What would you like to be able to do?

Use indexers other than notmuch, cleanly and efficiently.

## What needs to change in NeoMutt?

Add a new pattern type (for example ~I).  It would take a command line as its argument.  Running the command line should produce a bunch of message-ids on stdout, separated by white space; the meaning of the pattern would be to match mails whose message-id is one of the bunch.

Example:

`  <limit> ~I snarf_mairix_msgids <enter>`

where `snarf_mairix_msgids` is a wrapper script that prompts for a query string, passes it to mairix, reads the "raw" output from mairix i.e. a list of file names, and gets the message ids from the files.

## Have you tried any alternative methods?

Yes of course - I am aware that this is practically a FAQ.  But all the available solutions are horrible.  Please see the latest thread on neomutt-users and see the solution proposed there.  Shudder.

And do not get me started on notmuch and "virtual folders" :-(

**Comment by nobrowser** [comment]
Yes and yes.  Have you seen the thread in neomutt-users I mentioned above?  Ok Ok here is a link:

[mailman archive](http://mailman.neomutt.org/pipermail/neomutt-users-neomutt.org/2018-November/000434.html)

If you do not find the solution quoted there (and that is essentially the _only_ one existing) to be disgusting, your taste is .. different.  In fact its originator (Pasky of kernel/git fame) admits as much on his blog where he posted it.

**Comment by Austin-Ray** [comment]
> Have you seen the thread in neomutt-users I mentioned above

I had not, sorry, but I just read it. I'm not sure I completely understand it (might be due to it being late on my end.)

This would essentially be applying a filter to a mailbox (maildir/mbox/mh/etc.) based on the results of an external indexer. The benefit would be using an actual mailbox instead of creating and opening a new mailbox with a query's results?

What other benefits are there for this method? Are there any drawbacks?

> If you do not find the solution quoted there ... to be disgusting,

It is quite disgusting. Fortunately, neomutt has `vfolder-from-query` for notmuch :)

**Comment by nobrowser** [comment]
I think you got it.

The benefit is being able to use other indexers in a reasonable way.  For me, mairix at least is much faster than notmuch.  And I like to see the results in the normal mutt way, by flagging or limiting but still staying in the physical folder, to see the matched mails in their context.

The drawback is of course feeping creaturitis :-)  That, and using another letter of the alphabet for the new pattern, one of the last few letters available.

I can think of a way to avoid that last one: instead of introducing a new pattern type, extend the semantics of `=i ` so that a _list_ of message-ids can follow, separated by some character that is invalid in message-ids, such as the comma `,`.  But this would have to be a special case for `=i` because in general there is no safe separator character.

Finally, Nicolas Paris' last post in the list thread [1] proposes maybe a neater way of introducing `~I` which would let neomutt to do the prompt for the query, rather than leaving that to the wrapper script, at the cost of adding a configuration variable.

[1]
http://mailman.neomutt.org/pipermail/neomutt-users-neomutt.org/2018-November/000440.html

**Comment by Austin-Ray** [comment]
I can see the appeal of this feature. 

@flatcap what do you think?

**Comment by flatcap** [comment]
OK, this sounds reasonable.
What's your plan?
What pattern(

**Comment by nobrowser** [comment]
Hi.  I definitely want to follow up .. just a bit sidetracked with life for a day or two.  BRB!

**Comment by nobrowser** [comment]
I'm working on a prototype, implementing the simplest solution (from neomutt POV):

* new pattern type `I` (defined in mutt.h)
* no new config items needed
* code changes:
** in pattern.h , `struct Pattern` gains a new variant in the union which is a list (ie. `ListHead`) of strings
** also, `struct Pattern` gains a new bit flag to indicate that the list variant is present
** in pattern.c `mutt_pattern_comp`, parse the data for `I` into a `struct Pattern` of this new kind,  splitting on commas
** in pattern.c `patmatch`, recognize that a list is present and attempt to match against each string in list,
** in pattern.c `mutt_pattern_exec`, add the obvious case branch for the new type.

BRB :-)

**Comment by flatcap** [comment]
> Nicolas Paris ... proposes ... let neomutt to do the prompt for the query

Or just pass the query direct to the external script

> ... at the cost of adding a configuration variable

The user is only likely to have **one** filter that they use, but that they query often.

I like the idea of having `$external_index_filter`, so that the query becomes just `~I work`

**Comment by nobrowser** [comment]
I don't have a strong opinion either way.  If we do it the lazy way (as I outlined above), users will need a macro anyway to construct the list of IDs; the name of the program can be hidden in that macro.  OTOH if we do it the "right way" (yours), a macro may not be needed but a wrapper script still will be, unless the indexer outputs exactly the format we grok.  So some user work will still be involved.

I think I'll code up both ways and let you pick.

**Comment by nobrowser** [comment]
I now agree with @flatcap that better is better in this case.  So I have done it:

https://github.com/neomutt/neomutt/tree/devel/external-search

Correspoding doc update should follow soonish.

**Comment by gahr** [comment]
I think you're leaking `oldline`. I'm willing to take the pain and open a pull request for you, if you "get your branch info shape, rebase and all" :)

**Comment by nobrowser** [comment]
I am really confused with github (and, probably, git) now.

I have written the documentation bits, and committed them to my branch locally.  Then I switched to master, fetched+merged from github master, switched back to my branch, and rebased vs. master.  Whew!  After all this fiddling, I feel I deserve some rest.  So ... I try to push my branch, and BOOM!

Error: can't push because remote contains commits not in my local branch.  And indeed, 

`git diff devel/external-search origin/devel/external-search`

shows some changes completely unrelated to my work, while

`git diff master devel/external-search`

shows exactly my work and nothing else.  What am I doing wrong?

**Comment by nobrowser** [comment]
Ok, never mind, I deleted the github branch and then pushed again.  I'll try to remember I have to do that from now on, but it feels totally wrong :(

Anyway, the doc bits are in.  Ready to merge as far as I'm concerned.

**Comment by gahr** [comment]
When you rebase you are rewriting history and that requires you to force-push (`push -f`). Is that perhaps the source of the confusion?

**Comment by nobrowser** [comment]
Hi, thanks for the help.  Reading the dense manpage again, maybe --force-with-lease is what I need.
How do other project members handle this situation?

**Comment by flatcap** [comment]
> maybe --force-with-lease is what I need

Yes.  If I understand the man page, it'll detect the dangerous case where the two branches have diverged.

After the remote (GitHub) has been rebased, you can `git pull --rebase` to get your local branch back in sync.

>  How do other project members handle this situation?

Badly :-)
In the past, I have made mistakes where I trampled over somebody's work.
Now, I'm a lot more cautious.

After any large merges, I offer a free rebase service to anyone who asks.

**Comment by Austin-Ray** [comment]
This feature was merged 2018-12-12. Closing.
