### ISSUE TITLE
With multiple accounts, drafts and trash can be saved in incorrect folder

### ISSUE THREAD

**Issue by kylebarbour** [neomutt/neomutt#1391]
## Expected Behaviour

I have a simple mutt setup with two email accounts, and a `folder-hook` to switch `muttrc`s whenever I change between them. When I create a message and postpone it, or delete an email, I expect that this would put the postponed message in the Draft or Trash directory as appropriate in the same account that the message originated from.

## Actual Behaviour

When I create an email and postpone it, and occasionally when I delete emails, they are saved in the Drafts or Trash folders on the wrong account. This does not happen with archiving email, sent email, or other folders.

## Steps to Reproduce

Minimal working example setup:

`.neomuttrc`:

    folder-hook home 'source ~/.neomuttrc.home'
    folder-hook work 'source ~/.neomuttrc.work'
    source ~/.neomuttrc.home

`.neomuttrc.home`:

    set folder = "~/mail/home"
    set spoolfile = "+Inbox"
    set postponed = "+Drafts"
    set trash = "+Trash"

`.neomuttrc.work`:

    set folder = "~/mail/work"
    set spoolfile = "+Inbox"
    set postponed = "+Drafts"
    set trash = "+Trash"

1. Start neomutt.
2. Because of the `source` statement, you'll start in `home`. Change to `work`.
3. Create a new message.
4. Postpone it.
5. Look in the Drafts directory on `work` and note that it's empty. Look in the Drafts directory on `home` and note that it is there.

Note also that `:set folder` echoes `"~/mail/work"` and `:set postponed` echoes `"=Drafts"` which is correct.

I tried using `neomutt -d 2` to see if the debug information would be useful, but it didn't provide any enlightenment to me, unfortunately. It just shows that the message was always saved in the default account, not the account where the draft originated.

## How often does this happen?

Always, except for Trash. I'm not sure how to regularly trigger that.

## NeoMutt Version

```
NeoMutt 20171215
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type `neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type `neomutt -vv' for details.

System: Linux 4.15.0-38-generic (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.0)
libidn: 1.33 (compiled with 1.33)
hcache backends: tokyocabinet

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.2.0-17ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.2.1 20171205 (Ubuntu 7.2.0-17ubuntu1)

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --libexecdir=/usr/lib --with-mailpath=/var/mail --enable-fcntl --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-QqpkFP/neomutt-20171215+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3  -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  +gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta 
  +mixmaster +nls +notmuch -openssl +pgp +resizeterm +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

* OS: Ubuntu Linux 18.04.1 LTS bionic
* Kernel: 4.15.0-38-generic x86_64
* Multiple NeoMutts: no
* Screen multiplexers: occurs both with and without tmux
* Email location: local Maildir

**Comment by gahr** [comment]
Wild guess: isn't `folder-hook home` actually matching both folders, since they're both presumably located in **/home**/kylebarbour/mail?

**Comment by kylebarbour** [comment]
I suppose that's possible &mdash; do you have any guess as to why the rest of the settings work though?

I'll try setting `folder-hook /home/kyle/mail/home` instead and see what happens.

**Comment by kylebarbour** [comment]
@gahr: Unfortunately, that doesn't seem to change anything. Any debugging suggestions?

**Comment by mathsaey** [comment]
I am dealing with the exact same issues. Did you ever manage to find any way to fix this @kylebarbour?

**Comment by jindraj** [comment]
@kylebarbour have you tested it just by executing folder-hook command in neomutt or changed it in the config and run a fresh neomutt instance?

**Comment by kylebarbour** [comment]
Unfortunately, I gave up and used multiple accounts in a different way (two separate .muttrc setups in a tmux window). As far as I know the bug still exists.

@jindraj The latter only.

**Comment by gahr** [comment]
My attempt to reproduce this:

## What I have

```sh
% realpath .
/usr/home/gahr/Mail

% ls -l
total 20
drwxr-xr-x  6 gahr  gahr  512 14 May 10:02 foomail
-rw-r--r--  1 gahr  gahr  117 14 May 10:07 foomail-rc
drwxr-xr-x  6 gahr  gahr  512 14 May 10:06 gmail
-rw-r--r--  1 gahr  gahr  114 14 May 10:07 gmail-rc
-rw-r--r--  1 gahr  gahr  194 14 May 10:06 neomuttrc

% cat neomuttrc 
folder-hook /usr/home/gahr/Mail/gmail   'source /usr/home/gahr/Mail/gmail-rc'
folder-hook /usr/home/gahr/Mail/foomail 'source /usr/home/gahr/Mail/foomail-rc'
source /usr/home/gahr/Mail/gmail-rc

% cat gmail-rc 
set folder = "/usr/home/gahr/Mail/gmail/"
set spoolfile = "+Inbox"
set postponed = "+Drafts"
set trash = "+Trash"

% cat foomail-rc
set folder = "/usr/home/gahr/Mail/foomail/"
set spoolfile = "+Inbox"
set postponed = "+Drafts"
set trash = "+Trash"
```

## What I do

1. start NeoMutt, I'm in gmail/Inbox
2. `:set postponed?` --> `postponed="/usr/home/gahr/Mail/gmail/Drafts"`
3. <kbd>c</kbd>`/usr/home/gahr/Mail/foomail/Inbox`<kbd>enter</kbd>
4. `:set postponed?` --> `postponed="/usr/home/gahr/Mail/foomail/Drafts"`

I cannot reproduce your behaviour, as long as I make sure that when I change folder, I do that in a way that matches the folder hook. If I changed folder to `~/Mail/foomail/Inbox` instead, the folder hook would not trigger.

Can you see any fundamental difference between our setups?

**Comment by mathsaey** [comment]
I should note I did not have any issues with `postponed` mail, as  kylebarbour had. My issue only occurred occasionally, with `trash`. I haven't found a reliable way to reproduce the behavior.

**Comment by roccoblues** [comment]
Closing this old issue because it can't be reproduced.
