### ISSUE TITLE
Sidebar: settings no longer work

### ISSUE THREAD

**Issue by voidzero** [neomutt/neomutt#14]
I upgraded my mutt to 1.6.0 today, using the Gentoo ebuild which provides the neomutt patches. It seems like sidebar related settings are changed, removed, or...? But the docs don't seem to reflect this. Mutt barfed these messages upon startup, these did work on the previous version I used, 1.5.24-r2.

<pre>
sidebar-next: no such function in map
sidebar-open: no such function in map
sidebar-prev: no such function in map
sidebar_delim: unknown variable
sidebar_delim_chars: unknown variable
sidebar_indentstr: unknown variable
sidebar_new: no such object
sidebar_shortpath: unknown variable
sidebar_sort: unknown variable
sidebar_width: unknown variable
</pre>

**Comment by DarkDefender** [comment]
The ebuild for mutt 1.6.0-r1 tells you to checkout this page if you use the sidebar:
http://www.neomutt.org/sidebar-intro.html#intro-sidebar-config-changes

After converting all options I do not have any issues with the sidebar

**Comment by NoAgendaIT** [comment]
Ah, that ebuild is exactly one revision newer than the one I built. Thanks for pointing this out.

Perhaps this can also be reflected in the README.sidebar file? That's where I went to look.

**Comment by voidzero** [comment]
Err, posted with the wrong account, let's retry this one more time.

Yes, that ebuild is exactly one revision newer than the one I built. Thanks for pointing this out.

Perhaps this can also be reflected in the README.sidebar file? That's where I went to look.

I will build the -r1 later. As you can see, the version I'm currently running is complaining about more than is listed on that page, e.g. stuff like sidebar_width not existing.

**Comment by DarkDefender** [comment]
IIRC the 1.6.0 ebuild does not have the sidebar patch.

**Comment by flatcap** [comment]
@DarkDefender Thanks for helping out.
@voidzero Has that fixed the problem?

I've added a note about the config changes to the top of the README.sidebar

**Comment by voidzero** [comment]
Ah, there we go. Yes, with 1.6.0-r1 this does fix it for me. Thanks to you both. :+1:
