### ISSUE TITLE
REAMDE.notmuch is missing in relase tarbal for neomutt-20160910

### ISSUE THREAD

**Issue by Knusper** [neomutt/neomutt#140]
For me the build with `make` will fail because of this.

In ´doc/Makefile.am` we set (line 48-49):

    topsrcdir_DOCFILES = COPYRIGHT GPL INSTALL ChangeLog ChangeLog.neomutt        \
          README NEWS TODO README.SECURITY README.SSL README.neomutt README.notmuch

But in the relase tarball `neomutt-20160910.tar.gz` from https://github.com/neomutt/neomutt/releases/tag/neomutt-20160910 does not contain this file.  In the Source Code tar.gz file on the same page the file is included, though.

**Comment by flatcap** [comment]
Thanks @Knusper 
I've just performed a mass tidy of all the doc files.
I've checked that everything should get installed, does.
Also, the "make dist" tarfile now works correctly.

Commit: e499cf7
