### ISSUE TITLE
Postponed mail are opened only on second try

### ISSUE THREAD

**Issue by sileht** [neomutt/neomutt#1425]
## Expected Behaviour

Open postponed mail on first try

## Actual Behaviour

My postponed message is opened only on second try

## Steps to Reproduce

On imap, when I have postponed mail and I create a new mail:

I press `m` (<mail>), I got `Recall postponed message? ([yes]/no):`
I press `y` -> I got `No postponed messages`
I press `m` -> I got `Recall postponed message? ([yes]/no):`
I press `y` -> I got my postponed message opened

## How often does this happen?

- Always

## NeoMutt Version

20180716-749-3728e4

**Comment by sileht** [comment]
That's one is an important and tricky one.

`mutt_get_postponed()` uses `mx_mbox_open()` without the`APPEND` or `READONLY` flags.

This will hijack the `ImapAccountData` of the currently opened mailbox and **modify it**.

Selected mailbox, max_msn, msn_index got changed and everything next goes wrong.

**My plan:**

Moving max_msn/msn_index and couple of other stuff that are mailbox related from adata to mdata.

Then for any imap command that need a selected mailboxes, we can detected if the current selected is the expected one and switch if needed.

**Comment by flatcap** [comment]
(from IRC)
in fact I did wonder about that entire section of `struct ImapAccountData`, whether it should all be `MboxData` and replace it with `struct Mailbox *selected;`
(but I didn't understand enough imap to think it through)

**Comment by roccoblues** [comment]
I'm trying to cleanup some older issues here. Is this still relevant? Thanks!
