### ISSUE TITLE
Getting UIDL is not supported by server error message

### ISSUE THREAD

**Issue by russurquhart1** [neomutt/neomutt#1427]
Hi,

I had posted this to the neomutt mailing list. I have been using neomutt, with the pop support for my verizon account without issue. About a month or so ago, out of the blue I started getting the "UIDL is not supported by the server" when i would try and get new mail.

I posted this to the neomutt list, and Rich suggested that i start neomutt -d5 and search for "5> CAPA" and submit a Github issue. Here is what i found:

```
[2018-11-09 17:51:36] mutt_socket_readln_d() 9< +OK Maildrop ready, (JPOP server ready).
[2018-11-09 17:51:36] mutt_sasl_setup_conn() SASL protection strength: 0
[2018-11-09 17:51:36] mutt_sasl_setup_conn() SASL protection buffer size: 65536
[2018-11-09 17:51:36] mutt_socket_write_d() 9> CAPA^M
[2018-11-09 17:51:36] mutt_socket_readln_d() 9< +OK CAPA list follows
[2018-11-09 17:51:36] mutt_socket_readln_d() 9< IMPLEMENTATION jpop-0.1
[2018-11-09 17:51:36] mutt_socket_readln_d() 9< TOP
[2018-11-09 17:51:36] mutt_socket_readln_d() 9< USER
[2018-11-09 17:51:36] mutt_socket_readln_d() 9< SASL LOGIN PLAIN
[2018-11-09 17:51:36] mutt_socket_readln_d() 9< .
[2018-11-09 17:51:36] curses_message() Command UIDL is not supported by server.
[2018-11-09 17:51:38] mutt_addr_is_user() no, all failed.
[2018-11-09 17:51:38] mutt_addr_is_user() no, all failed.
```

Any ideas?

Thanks for any and all help

**Comment by flatcap** [comment]
For comparison, here's the log from my Dovecot server:
```
mutt_socket_open() Connected to 10.8.0.1:110 on fd=7
mutt_socket_readln_d() 7< +OK Dovecot ready.
mutt_socket_write_d() 7> CAPA^M
mutt_socket_readln_d() 7< +OK
mutt_socket_readln_d() 7< CAPA
mutt_socket_readln_d() 7< TOP
mutt_socket_readln_d() 7< UIDL
mutt_socket_readln_d() 7< RESP-CODES
mutt_socket_readln_d() 7< PIPELINING
mutt_socket_readln_d() 7< AUTH-RESP-CODE
mutt_socket_readln_d() 7< STLS
mutt_socket_readln_d() 7< SASL
mutt_socket_readln_d() 7< .
```

then after a successful login:

```
mutt_socket_readln_d() 7< +OK Logged in.
mutt_socket_write_d() 7> CAPA^M
mutt_socket_readln_d() 7< +OK
mutt_socket_readln_d() 7< CAPA
mutt_socket_readln_d() 7< TOP
mutt_socket_readln_d() 7< UIDL
mutt_socket_readln_d() 7< RESP-CODES
mutt_socket_readln_d() 7< PIPELINING
mutt_socket_readln_d() 7< AUTH-RESP-CODE
mutt_socket_readln_d() 7< .
```

**Comment by russurquhart1** [comment]
Hi Rich,
Here is smtp_authenticators from my neomuttrc:
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Courier; color: #fff0a5; background-color: #13773d}span.s1 {font-variant-ligatures: no-common-ligatures}set smtp_authenticators="external:anonymous:plain:otp:skey:digest-md5:scram:ntlm:gssapi:browserid-aes128:eap-aes128"
This hasn't changed. I was thinking maybe one of these SASL options is no longer supported?
Are you using a POP server?
Thanks,

Russ
-----Original Message-----

**Comment by russurquhart1** [comment]
I did some searching on the net. It seems that some POP3 servers do NOT support UIDL. (This is optional as I understand.) Is there a way we can put a check for this?

**Comment by flatcap** [comment]
Oh dear.  This code is unchanged from upstream Mutt.

`pop_fetch_headers()` unconditionally sends the `UIDL` command.
That code went in 18 years ago.

I don't know which command we should send instead, or how much work that would be to implement.

**Comment by gahr** [comment]
Sorry for the dumb question @russurquhart1 , but is this preventing you from fetching new mail? Or is this about the error message being annoying?

As I see it, the error message is just telling you that the server doesn't support UIDL. To me it *looks like* the code should handle this case just fine.

**Comment by gahr** [comment]
As confirmed via email, this used to work so apparently something has changed at server side. Most likely I was wrong in assuming we would handle a server not supporting UIDL just fine. I'll look into this.

**Comment by gahr** [comment]
I have investigated further. NeoMutt runs under the assumption that UIDL is available. It is used to match messages from client to server, as NeoMutt doesn't download POP3 messages but acts as a viewer. I have tweaked the code a bit and I reached the point where I'm able to open a mailbox without UIDL support, but things get trickier from there. For example, you cannot delete a message (because there's no way to tell the server which message you want to delete). Sync'ing is also infeasible as it requires trashing the cache and reopening the whole mailbox, which takes a huge amount of time even for reasonably sized mailboxes.

The best we could achieve is a workflow where you download the whole mailbox on the first open, then you stop sync'ing. Not very useful after all. Also, given the general availability of UIDL, I don't think the changes required are worth the effort.

**Comment by russurquhart1** [comment]
Pietro,
Thanks for looking into this, and copying me on the message about this bug. 
I have been really missing my neomutt. Can you explain to me how other email clients, like the Apple Mail app and the web-based AOL mail, that i have been using, are able to access the POP3 account and seemingly circumvent these issues? (I just want to kind of understand.) I had found a thread, where someone else was having a similar problem, with a mail client other than mutt/neomutt, and they looked at the log files the connection was producing, I assume to resolve their issue.
In the final wrap-up, is there any solution for me to be able to use neomutt?
Thanks again for keeping me in the loop and all of your work!

Russ


-----Original Message-----

**Comment by flatcap** [comment]
A Brief History...

The original POP3 protocol (1988) meant you **had to** download all your emails.
In 1994, POP3 was updated to add an optional command `UIDL`.
In 1995, Mutt was born.
In 2000, Mutt gained POP3 support, but the UIDL command was already widespread.

Unfortunately POP3 use isn't very widespread.
We only have a few developers and fixing our POP3 support would be low priority.

Of course, **if anyone wants to volunteer**, we'd be happy to help them.

> is there any **solution** for me to be able to use neomutt

**Yes**.
Before Mutt had POP3 support, it was common to use a tool, such as `fetchmail` to pull the mail into a local mailbox.

**Comment by gahr** [comment]
In addition to @flatcap's comments, 

> Can you explain to me how other email clients, like the Apple Mail app and the web-based AOL mail, that i have been using, are able to access the POP3 account and seemingly circumvent these issues?

I don't know how they do that, but what *I* would do is use the `TOP` command with a small number of rows, hash the result, and use that as a key into a locally downloaded copy of the email. That might not be difficult to implement in NeoMutt...
