### ISSUE TITLE
mutt asks for IMAP password because url_tostring throws away the password

### ISSUE THREAD

**Issue by EdwardBetts** [neomutt/neomutt#1435]
When I run `neomutt  -f imap://user:password@localhost` it asks again for the password. I checked with gdb and I can see `mx_mbox_open` is being passed imap://user@localhost/ as the folder.

main calls mutt_expand_path, which calls mutt_expand_path, which calls mutt_expand_path_regex, which calls imap_path_canon, which calls url_tostring.

I think url_tostring strips out the password.

**Comment by EdwardBetts** [comment]
My muttrc has multiple mailboxes with different passwords. How do I make this work with `set imap_password=foobar` ?

```
mailboxes imaps://edwardbetts:password1@example1.com/
mailboxes imaps://edward:password2@example2.com/
mailboxes imaps://edward:password3@example3.net/
```

Can we warn the user when they try and use an IMAP URL that contains a password?

**Comment by gahr** [comment]
You could use account-hooks for that:
```
account-hook example1 set imap_pass=foobar
account-hook example2 set imap_pass=moobaz
```
