### ISSUE TITLE
segfaults in pager.c (new edition)

### ISSUE THREAD

**Issue by aradici** [neomutt/neomutt#144]
Reported from http://bugs.debian.org/837634
Same as the previous issue, this time it happens when leaving the pager from a composed mail.

Steps to reproduce on an up to date sid:

* install postfix (local only config), mutt and bsd-mailx

* echo Test | mail -s "Test" hvhaugwitz

* run mutt as user hvhaugwitz (without config) and compose mail and open
  composed mail in pager

* echo Test | mail -s "Test" hvhaugwitz

* leave pager by pressing 'i' or 'q'

**Comment by flatcap** [comment]
Hmm... There's good news and bad news.
Following the instructions in a Debian unstable vm:
- Good news: I can reproduce the crash using mutt-1.7.0-4
- Bad news: If I compile from NeoMutt's git (using Debian's configure settings), then it doesn't crash.

Still investigating...

**Comment by rprimus** [comment]
Tue Sep 13 13:09:17 BST 2016

system info:
```
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004
```

neomutt info:
```
/usr/local/Cellar/neomutt/20160910 (122 files, 5.4M) *
  Built from source on 2016-09-11 at 11:18:05 with: --with-gettext --with-notmuch-patch --with-sidebar-patch
```

neomutt-20160910  appears to be crash (SIGSEGV) after reading an email and returning to the pager.

crash info:
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   mutt                                0x000000010eb6321b update_index + 45
1   mutt                                0x000000010eb8dd23 mutt_pager + 4364
2   mutt                                0x000000010eb591b0 mutt_display_message + 1844
3   mutt                                0x000000010eb64aba mutt_index_menu + 4538
4   mutt                                0x000000010eb81b15 main + 5331
5   libdyld.dylib                       0x00007fff888d25ad start + 1
```

**Comment by flatcap** [comment]
Hi @rprimus thanks for the info.
There are two similar problems, here.  I fixed one yesterday.
If your bug's repeatable, please can you give the latest version a try.
Git commit: 6b4c4ca

**Comment by rprimus** [comment]
On Tue, Sep 13, 2016 at 05:59:28AM -0700, Richard Russon wrote:
> Hi @rprimus thanks for the info.
> There are two similar problems, here.  I fixed one yesterday.
> If your bug's repeatable, please can you give the latest version a try.
> Git commit: 6b4c4ca

Tue 13 Sep 2016 14:07:43 BST

Will build and report.

-- 
-primus (Train yourself and be your own master.)
"First solve the problem, then code!"
Narrowness of experience leads to narrowness of imagination.
http://www.catb.org/esr/faqs/smart-questions.html
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

GPG Key: 0x28E92848DB3FB476
Key fingerprint: B0FB C67E 2E7E 7032 7FE6  7FBC 28E9 2848 DB3F B476

**Comment by rprimus** [comment]
On Tue, Sep 13, 2016 at 05:59:28AM -0700, Richard Russon wrote:
> Hi @rprimus thanks for the info.
> There are two similar problems, here.  I fixed one yesterday.
> If your bug's repeatable, please can you give the latest version a try.
> Git commit: 6b4c4ca

Tue 13 Sep 2016 14:45:26 BST

That commit did fix the SIGSEGV I was
experiencing.

Cheers!
> 

-- 
-primus (Train yourself and be your own master.)
"First solve the problem, then code!"
Narrowness of experience leads to narrowness of imagination.
http://www.catb.org/esr/faqs/smart-questions.html
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

GPG Key: 0x28E92848DB3FB476
Key fingerprint: B0FB C67E 2E7E 7032 7FE6  7FBC 28E9 2848 DB3F B476
