### ISSUE TITLE
Binding keys not working as expected

### ISSUE THREAD

**Issue by mathewcohle** [neomutt/neomutt#1448]
## Expected Behaviour

I'm trying to change key bindings, e. g.:
```
bind index,pager \Cj sidebar-next
```

## Actual Behaviour

Mapping before the command (pressing `?` in `index`):

```
... 
<Enter>                                   display-message                                       display a message
^K                                        extract-keys                                          extract supported public keys
<Return>                                  display-message                                       display a message
...
Generic bindings:

<Enter>                                   select-entry                                          select the current entry
^L                                        refresh                                               clear and redraw the screen
<Return>                                  select-entry                                          select the current entry

...
sidebar-next                                                                                    move the highlight to next mailbox
 # i.e. not binded
```
(I'm new to `mutt`, is there a better way to get current bindings?)

When I execute the bind command above it becomes:
```
...
<Enter>                                   sidebar-next                                          move the highlight to next mailbox
^K                                        extract-keys                                          extract supported public keys
<Return>                                  display-message                                       display a message
...
Generic bindings:

<Enter>                                   select-entry                                          select the current entry
^L                                        refresh                                               clear and redraw the screen
<Return>                                  select-entry                                          select the current entry
...
```

Even more strange, `<Enter>` still open a pager (i.e. executes `select-entry` instead of `sidebar-next`). This is not the case if I use mapping from vim-keys.rc:
```
bind index                      \Cm list-reply # Doesn't work currently
```
Which change the behaviour of `<Enter>` in `index` to `list-reply`. 

One observation: I've discussed this issue with my colleague who:

* compiled `mutt` without `sidebar-patch` - the issue not happening
* compiled `mutt` with `sidebar-patch` - the issue above happening
* compiled `neomutt` (which has sidebar patch merged) - the issue above happening

Not sure if the sidebar patch is connected, just reporting in case it might be useful clue.

## Steps to Reproduce

Start `neomutt` and execute the command above

## How often does this happen?

- Always

## When did it start to happen?

I've started to use `neomutt` few days ago.

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.19.2-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.35 (compiled with 1.35)
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.1 20180831 (GCC)

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn=/usr --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo
  -gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color
  +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>


```

## Extra Info

* Operating System and its version
```
$ uname -a
Linux 4.19.2-arch1-1-ARCH #1 SMP PREEMPT Tue Nov 13 21:16:19 UTC 2018 x86_64 GNU/Linux
```

* Were you using multiple copies of NeoMutt at once?
No
* Were you using 'screen' or 'tmux'?
yes, but happens even if I do in plain console (`Konsole`)
* Is your email local (maildir) or remote (IMAP)?
IMAP

As I mentioned above, I'm new to `neomutt` as a user, so do not have any experience with its codebase. However, if somebody point me to suspect parts, I might write the patch to fix this issue :)

Thanks

**Comment by mathewcohle** [comment]
I've noticed that other users experienced the same issue: https://github.com/neomutt/neomutt/issues/56#issuecomment-227056952

**Comment by gahr** [comment]
Turns out, the reason why we're seeing `<Enter>` is that `\C` sequences are stored as integers where `\CA` is 1, `\CB` is 2, etc. Thus, `\CJ` is 10, but 10 is also the character code for `\n`, hence the help menu prints it as `<Enter>`. I'm not sure what it would involve to fix this.

**Comment by flatcap** [comment]
There are a couple of factors a play, here: the terminal and ncurses/slang (which we use to read the keystrokes).

Terminals intercept some of the keys so we never see them, e.g.
- <kbd>Ctrl-C</kbd>
- <kbd>Ctrl-Z</kbd>
- <kbd>Ctrl-Q</kbd> (flow control)
- <kbd>Ctrl-S</kbd> (flow control)
- <kbd>Ctrl-O</kbd> (MacOS eats this)

Then there are some equivalences, as @gahr points out:
- <kbd>Ctrl-I</kbd> = <kbd>\<Tab></kbd>
- <kbd>Ctrl-J</kbd> = <kbd>\<Enter></kbd>
- <kbd>Ctrl-M</kbd> = <kbd>\<Return></kbd>

NeoMutt made the last two equivalent to remove ambiguity between ncurses and slang.

You can check which keys are recognised in NeoMutt by running: `:exec what-key`

**Comment by mathewcohle** [comment]
Great, thanks for the info! 

If there is no reason to have equivalence between `Ctrl-I` = `<Tab>`, etc (if I get it correctly, it's just an implementation detail), then it seems to me that the best thing to is to change the implementation to remove the equivalence.

Otherwise, it would be nice if `neomutt` do not allow to bind for these keys or at least throw a warning that these bindings have "side effects"? I.e. 
```
bind index                      \Cm list-reply
```
also bind `<Return>` to `list-reply`.

@gahr yes, `\Ck` works find but I guess it's just because your and mine keyboard send `<Return>` instead of `<Enter>` when pressing "Enter" key (maybe somebody on Windows would have different experience). That's the reason why `\Cm` changes the behavior of "Enter" key press (as `\Cm` is equivalent to `<Return>` as pointed above).

**Comment by gahr** [comment]
Yeah I think it's reasonable to model ctrl sequences differently, e.g., by setting the high bit.
