### ISSUE TITLE
Neomutt cannot find notmuch database.

### ISSUE THREAD

**Issue by hsanson** [neomutt/neomutt#1455]
Latest master broke my working notmuch configuration. I have several email accounts arranged in a maildir folder structure as below:

```
Mail
   |-  user1@mail.com
   |-  user2@gmail.com
   |-  user3@gmail.com
```

For each account I have a configuration file as below:

```
set nm_default_uri = "notmuch:///home/username/Mail"
set virtual_spoolfile=yes
virtual-mailboxes "Inbox"   "notmuch://?query=path:user1@mail.com/** AND tag:inbox
virtual-mailboxes "Trash"   "notmuch://?query=path:user1@mail.com/** AND tag:trash
virtual-mailboxes "Spam"   "notmuch://?query=path:user1@mail.com/** AND tag:spam
```

As you can see I set the notmuch database location the the parent `Mail` folder so I have one database for all accounts.

## Expected Behaviour

I should be able to open any virtual mailbox without any issues as usual.

## Actual Behaviour

With lastest master, neomutt complains that cannot find the notmuch database. The error makes it clear it is looking for the notmuch database within the each account folder (e.g. user1@mail.com/.notmuch) instead of the correct one in the parent folder (e.g. Mail/.notmuch).

Is like neomutt now ignores the nm_default_uri setting.

## Steps to Reproduce

Open neomutt with a virtual mailbox with nm_default_uri in a different path other than the maildir of the account being opened.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded

After a git bisect it seems the problem appeared after commit 104093500.  I am currently using commit 783243c46 that does not present the problem.

## NeoMutt Version

Latest master 4e05917

**Comment by Austin-Ray** [comment]
Fixed in cef407e
