### ISSUE TITLE
fish: 'neomutt' terminated by signal SIGSEGV

### ISSUE THREAD

**Issue by evanescente-ondine** [neomutt/neomutt#1462]
First time installing and configuring neomutt.
I have:
`fish: 'neomutt' terminated by signal SIGSEGV (Erreur de frontière d'adresse)`
and my .neomuttrc (not .mutt folder, apparently) is:
```
set imap_user = "blabla@gmail.com"
set imap_pass = "blabla"
set folder = "imaps://imap.gmail.com:993"

set smtp_url = "smtps://blabla@smtp.gmail.com:587"
set smtp_pass = "bloblo"
set spoolfile = "+INBOX"
set postponed = "+[GMail]/Drafts"
set header_cache = "~/.mutt/cache/headers"
set message_cachedir = "~/.mutt/cache/bodies"
set record = ""

```
I compiled neomutt.
```
NeoMutt 20180716-881-a37cb3-dirty
Copyright (C) 1996-2016 Michael R. Elkins et autres.
System: Linux 4.9.0-8-amd64 (x86_64)
ncurses: ncurses 6.0.20161126 (compiled with 6.0.20161126)
libidn: 1.33 (compiled with 1.33)
Compiler:
cc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Configure options: 
Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__  -DNCURSES_WIDECHAR -I/usr/include

```

**Comment by evanescente-ondine** [comment]
Need any other information ?
When removing .neomuttrc, NM opens, but of course nothing is set up. And it complains that /var/mail/[my user name here] isn't a mailbox.

**Comment by flatcap** [comment]
Hi @evanescente-ondine.  Sorry this is your first impression of NeoMutt.
Thanks for taking the time to raise an issue.

> NeoMutt 20180716-881-a37cb3-dirty

Ah, this is the problem.
The current version of the code (from git master) is under heavy development -- we're trying to modernise the code.
While we do, it's not suitable for general use.

If you just want to **use NeoMutt**, then many distros already provide a package.
See: https://neomutt.org/distro.html

If you're keen to **build your own** NeoMutt, then I recommend the latest stable release: NeoMutt 2018-07-16.  `git checkout neomutt-20180716` then clean up and rebuild.

If you like **living on the edge**, then we welcome inquisitive testers.
We're developing hard and new code is going in daily.
If you know how to generate a backtrace (after a crash), that would be very useful.

**Comment by evanescente-ondine** [comment]
Sorry, I don't have the knowledge or ability to help much. I'm a real idiot in hacking/anything more complicated than simple command lines. And I tried, I can tell you that.
I have debian stretch and "sudo apt-get -t stretch-backports install "neomutt" says there's nothing. I don't understand. Since there IS something in buster repository. I won't go get the package individually, too much, there's a friggin' bunch of them...
Your version doesn't produce segfault. I should be able to configure gmail from then
Thanks !

**Comment by evanescente-ondine** [comment]
"ssl unavailable". I do have enabled "less secure application".
cannot connect to imap.gmail.com...
