### ISSUE TITLE
batch attachment save fails to preserve directory when attachment is in different MIME part

### ISSUE THREAD

**Issue by libBletchley** [neomutt/neomutt#1466]
In the attachment view there is a tree of files attached, like this:
```
I     1 <no description>                   [multipa/related, 7bit, 25K]
I     2 |-><no description>            [multipa/alternativ, 7bit, 5.2K]
I     3 | |-><no description>           [text/plain, 7bit, utf-8, 1.6K]
I     4 | `-><no description>          [text/html, quoted, utf-8, 3.4K]
I *   5 |->unnamed.gif.png                    [image/png, base64, 1.1K]
I *   6 |->image.png                          [image/png, base64, 6.1K]
I *   7 |->unnamed_(1).gif.png                [image/png, base64, 1.2K]
I *   8 |->Logo.jpg                          [image/jpeg, base64, 7.8K]
I *   9 |->unnamed_(4).gif.png                [image/png, base64, 1.1K]
I *  10 `->unnamed_(3).gif.png                [image/png, base64, 1.3K]
A *  11 contract.pdf                        [applica/pdf, base64, 294K]
```
## Expected Behaviour
When multiple files are tagged followed by the batch saving process (hitting `;`, 's', \<desired directory>) mutt says: `File is a directory, save under it? [(y)es, (n)o, (a)ll]`  When I hit `a` and I expect all files to be saved to the \<desired directory>.

## Actual Behaviour

All the files on the same tree branch as the first file get correctly saved to the \<desired directory>.  But the last file ("`contract.pdf`") is excluded from that branch for some reason, and this apparently causes mutt to "forget" what <desired directory> the user supplied, and so the user is forced to re-enter it.

## How often does this happen?

- On a particular email

If necessary I can try to sanitize the email that triggers this problem for public viewing.  Only on request though.. will take some effort.

This problem would be less annoying if https://github.com/neomutt/neomutt/issues/1465 were implemented, in which case this bug would only be an issue if `save-attach-dir` differed from the desired location.

## NeoMutt Version
NeoMutt 20170113

* Operating System and its version
debian stretch
* Were you using multiple copies of NeoMutt at once?
no
* Were you using 'screen' or 'tmux'?
screen
* Is your email local (maildir) or remote (IMAP)?
local

**Comment by libBletchley** [comment]
I noticed my case has a "multipart related" outer wrapper and thought that might be significant.  But then I found a more typical message structured like yours and was still able to reproduce the bug.  So I guess it's been fixed.

**Comment by gahr** [comment]
Thanks for checking. I'll close this for now, feel free to reopen if you can reproduce with master or the latest release.

**Comment by libBletchley** [comment]
i just noticed a case where the first file in the batch was not pre-pended with the directory after hitting `a`, but it got saved to the desired directory anyway.  So I think all along the problem was not with where it saved but just that sometimes the selected directory is prefixed and sometimes not.

Could be that the bug is still hiding but unrelated to the tree structure.  Guess I'll reopen if I get motivated to create a reproducer (which is quite difficult.. I tried to sanitize a complex MIME message and it was a disaster).
