### ISSUE TITLE
Virtual Mailboxes stopped working.

### ISSUE THREAD

**Issue by hsanson** [neomutt/neomutt#1470]
## Expected Behaviour

I have several virtual mail boxes defined and key bindings to jump to each one:

```
virtual-mailboxes "Inbox"   "notmuch://?query=path:myaccount@gmail.com/** AND tag:inbox AND NOT tag:killed AND NOT tag:spam"
virtual-mailboxes "Sent"   "notmuch://?query=path:myaccount@gmail.com/** AND tag:replied AND NOT tag:killed AND NOT tag:spam"
virtual-mailboxes "Archive" "notmuch://?query=path:myaccount@gmail.com/** AND NOT tag:inbox AND NOT tag:killed AND NOT tag:spam"
virtual-mailboxes "Spam"    "notmuch://?query=path:myaccount@gmail.com/** AND tag:spam"
virtual-mailboxes "Trash"   "notmuch://?query=path:myaccount@gmail.com/** AND tag:killed"

macro index,pager ga "<change-vfolder>Archive<enter>"  "open archive"
macro index,pager gi "<change-vfolder>Inbox<enter>"    "open inbox"
macro index,pager gd "<change-vfolder>Drafts<enter>"   "open drafts"
macro index,pager gs "<change-vfolder>Spam<enter>"     "open spam"
macro index,pager gt "<change-vfolder>Trash<enter>"    "open trash"
macro index,pager gf "<change-vfolder>?"               "open mailbox..."

bind  index c change-vfolder
```

Trying to change to any of the defined virtual boxes throws an error saying "xxxx is not a mailbox". Also using the change-vfolder command to any of the defined virtual boxes will complain that it is not a mailbox.

## Actual Behaviour

Trying to change to any of the defined virtual boxes throws an error saying "xxxx is not a mailbox". Also using the change-vfolder command to any of the defined virtual boxes will complain that it is not a mailbox.

## Steps to Reproduce
Define virtual mailboxes and try to change to any of them. It fails with "xxx is not a mailbox" where xxx is the name of the virtual box.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded

Commit cef407ece

I am unable to git bisect this since all previous versions to this commit do not work with my current configuration (see #1455).

## NeoMutt Version

```
NeoMutt 20180716-880-cef407
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.15.0-39-generic (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.10.0
hcache backends: lmdb

Compiler:
cc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --prefix=/usr --notmuch --lmdb --ssl --sasl --gpgme

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo
  -gnutls +gpgme -gss +hcache -homespool +idn +inotify -locales_hack -lua +meta
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color
  +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

```

**Comment by Austin-Ray** [comment]
Ah, I believe I know what the issue is. 

We removed the special cases for `notmuch` in the browser so that it was treated like every other backend. As such, the browser must be checking on the path (e.g. the notmuch query) so it doesn't find the notmuch mailbox the name is different from the path.

This affects the `named-mailboxes` command as well.

We need to add the behavior of checking on the description in addition to the path.

@flatcap Should we a new method for finding a mailbox by description or add that behavior to `mx_path_probe()` (check path, if no match try description)?

**Comment by flatcap** [comment]
> Should we a new method for finding a mailbox by description

Yes, please.

> or add that behavior to `mx_path_probe()` (check path, if no match try description)?

Hmm... that's an interesting idea.
I'll give it some thought.

**Comment by Austin-Ray** [comment]
@hsanson can you confirm that the behavior has been fixed? 6b9065ab1c5147dc9b2df85b7744b20ddd093726 contained a fix.

**Comment by hsanson** [comment]
@Austin-Ray confirmed works ok now.

**Comment by Austin-Ray** [comment]
@hsanson Glad to hear! Sorry I broke it in the first place!
