### ISSUE TITLE
message security is not set in batch mode

### ISSUE THREAD

**Issue by esovetkin** [neomutt/neomutt#1471]
**How to send encrypted mails with neomutt via the command line?**

The command I use to send a message looks like this:
```
 neomutt -e "set crypt_autopgp=yes" -s "subject" recipient@server.org < message.txt
```

Unfortunately, the above command ignores message security completely, due to the send.c:1922 and further lines:

https://github.com/neomutt/neomutt/blob/ff314a52264f1954799cf016cf6e170120e2e89d/send.c#L1922-L1932

and indeed,  the argument `flags` of the `ci_send_message` function equals 32, that corresponds to the SEND_BATCH value (see send.h:87).

I understand that some 'message security' operations require interactive mode, but in my experience some of them do not and rely on the gpg-agent (for example, signing mails is completely automatic).

At the end of the day, I would like to be able to send encrypted/signed mails via neomutt command line. I could hack a bit and propose a patch, but before that I would like to hear people who understand this part of the code better and hear their thoughts on the matter.

This question relates to #1090.

p.s. All lines numbers are in the context of the 'ff314a52264f' commit.

**Comment by flatcap** [comment]
Aside:  I've edited your code cut'n'paste for an GitHub code-view thing.
- Go to repo's code tab (or a specific commit)
- Select source file
- Highlight lines (click, shift-click)
- Copy link

GitHub displays the link as the source (quite a new feature).

**Comment by esovetkin** [comment]
In fact, by enabling security for the batch mode, several things can happen: 
- mail will be signed and encrypted if it is possible to be done automatically
- in case some user input is needed, `mutt_getch` will exit with code 1, as there is no terminal present.

To me it seems a reasonable behaviour for a batch mode.

I didn't test things for the mailx mode, but it seems this case is the same as the batch mode.

**Comment by esovetkin** [comment]
- The mail get send and encrypted when there is a key present for the 'mail@server.com' with the following command:
```
neomutt -F ~/.mutt/muttrc \
              -e "set crypt_autoencrypt=yes"  \
              -s "test" mail@server.com < ~/test.txt
```

- If no key is present neomutt exists with error code 1.

- I also noticed that `set crypt_autopgp = yes` option does not actually result in the mail being encrypted. But I haven't look why precisely yet.

- I also experience some problems, when mail send with a command executed from crontab, but I guess this is some environment variables problem.

**Comment by esovetkin** [comment]
with this patch mails *sometimes* are not sent. I need to test things
more.

**Comment by flatcap** [comment]
> I need to test things more.

Did you get a chance to test things more?

**Comment by alejandro-colomar** [comment]
Hi!

Was this feature really completed?  The PRs seem to be aborted, and the getting started guide says

> In batch mode, cryptographic operations are disabled, so these options can't be used to sign an email sent via a cron job, for instance.

Do you have any updates about this feature?  I'm very interested in being able to do `git format-patch --stdout  -1 HEAD --to foo@example.com | mutt -H -` and magically send signed patches.

**Comment by flatcap** [comment]
> Was this feature really completed?

No.  It was closed due to inactivity.

Back then, GitHub didn't distinguish between "Close as Completed" and "Close as not Planned".

> Do you have any updates about this feature?

Sorry, no.

The fix in #1476 looks simple enough, but the code around it is pretty ugly.
I'd need someone to dive in and understand the fix and check there wouldn't be any side-effects.

I don't have the time to do it myself,
but I'll happily make time to mentor anyone who volunteers.

**Comment by alejandro-colomar** [comment]
> The fix in #1476 looks simple enough, but the code around it is pretty ugly. I'd need someone to dive in and understand the fix and check there wouldn't be any side-effects.
> 
> I don't have the time to do it myself, but I'll happily make time to mentor anyone who volunteers.

Hmm, I've been searching for signing emails with patches since at least a year ago, so volunteering to add this feature would be appropriate.  Also, I now have a lot of free time, after leaving my job at NGINX recently.  I'll pick up the patch.  :)

Do you have anything in mind that I should test?

**Comment by flatcap** [comment]
> I now have a lot of free time
> I'll pick up the patch. :)

Fantastic!  Thanks!
(I'd already mentally prepared my, "Never mind; Thanks anyway" reply :-)

> Do you have anything in mind that I should test?

hmm...
It's been a while since I've read through the CLI sending code.

I'd start by testing the original "fix" -- see if it works.
Then debug through it so that you know the main path.

`main()` is enormous, but the important bits are:

- Parse the command line
- Read the config
- Set up the any crypto we need
- Send the email

We probably need to identify all the possible ways it could go wrong.
Try to think of a way to test each possible failure.

NeoMutt's code is a lot to take in, so...
Have a poke around and ask lots of questions.

---

I've just sent you an invite to join NeoMutt.
I suggest you create a new branch on the `neomutt` repo, of the form `devel/SHORT-NAME`
Then open a PR and we can continue the discussion there.

---

Useful notes:
- How to [Build and Debug](https://neomutt.org/dev/build) NeoMutt
- [Debugging tools](https://neomutt.org/dev/analysis), e.g. Address Sanitizer
- Social: IRC: `#neomutt` on `irc.libera.chat` ([web client](https://kiwiirc.com/nextclient/irc.libera.chat/#neomutt))
  (most active during European daylight hours)

Thanks! :heart:

**Comment by alejandro-colomar** [comment]
> > I now have a lot of free time
> > I'll pick up the patch. :)
> 
> Fantastic! Thanks! (I'd already mentally prepared my, "Never mind; Thanks anyway" reply :-)

:-}

> 
> > Do you have anything in mind that I should test?
> 
> hmm... It's been a while since I've read through the CLI sending code.
> 
> I'd start by testing the original "fix" -- see if it works. Then debug through it so that you know the main path.

Ok.

> 
> `main()` is enormous, but the important bits are:
> 
>     * Parse the command line
> 
>     * Read the config
> 
>     * Set up the any crypto we need
> 
>     * Send the email

Thanks.

> 
> 
> We probably need to identify all the possible ways it could go wrong. Try to think of a way to test each possible failure.
> 
> NeoMutt's code is a lot to take in, so... Have a poke around and ask lots of questions.

I know how to do that!  :-)

> 
> I've just sent you an invite to join NeoMutt. I suggest you create a new branch on the `neomutt` repo, of the form `devel/SHORT-NAME` Then open a PR and we can continue the discussion there.

I very much prefer discussing with patches on a mailing list.  Do you do that here?  I could adapt to github if necessary... but I don't like github.

> 
> Useful notes:
> 
>     * How to [Build and Debug](https://neomutt.org/dev/build) NeoMutt
> 
>     * [Debugging tools](https://neomutt.org/dev/analysis), e.g. Address Sanitizer
> 
>     * Social: IRC: `#neomutt` on `irc.libera.chat` ([web client](https://kiwiirc.com/nextclient/irc.libera.chat/#neomutt))
>       (most active during European daylight hours)
> 
> 
> Thanks! ❤️

Cheers!
Alex

**Comment by flatcap** [comment]
> I very much prefer discussing with patches on a mailing list

We have a devel mailing list here.
- https://mailman.neomutt.org/mailman/listinfo

Don't worry about the German intro page, it's an English-language list.

> I could adapt to github if necessary... but I don't like github.

I prefer GitHub these days, but I can read mailing lists too :-)

Having the code in our `neomutt` repo would be preferable -- it's easier for other developers to find and follow.
Also, we have lots of CI tools ([Actions](https://github.com/neomutt/neomutt/actions)) that get run on every push.

You wouldn't need to interact with GitHub at all, just push commits.

Note, while you're developing, that branch would be yours to do what you like.
If you want to refactor, rebase, force-push, that's all fine.

**Comment by alejandro-colomar** [comment]
> You wouldn't need to interact with GitHub at all, just push commits.

Yeah, I guess I can do a second push to GH if that helps.  I'll use my own server too.  <https://www.alejandro-colomar.es/src/alx/mutt/neomutt.git/>

> 
> Note, while you're developing, that branch would be yours to do what you like. If you want to refactor, rebase, force-push, that's all fine.

Ok.

> I prefer GitHub these days, but I can read mailing lists too :-)

:-)

> 
> Having the code in our `neomutt` repo would be preferable -- it's easier for other developers to find and follow. Also, we have lots of CI tools ([Actions](https://github.com/neomutt/neomutt/actions)) that get run on every push.
> 

Is it possible to run all (or most) of those locally?  Maybe via something like `make lint && make check`, or any other commands?  I'd like to run them locally before pushing (it's usually way faster, and you're not locked in to a specific CI interface).

**Comment by flatcap** [comment]
> Is it possible to run all (or most) of those locally?

Some, yes.

First, ideally, a build without errors or warnings.
This is getting quite tricky with modern compilers -- suggestions welcome.

## `make test`

There's a `make test` which does some unit tests on libraries.
You'll need some extra files, locally, to run them.
Instructions: https://github.com/neomutt/neomutt-test-files

This only tests library code, so you changes are unlikely to affect the tests.

## clang-format

This isn't tested automatically, but would be appreciated.
We run `clang-format` on all the `*.c` files (config file in the repo)

## Doxygen

All functions and parameters are documented.
config file: https://github.com/neomutt/action-doxygen

## Wide builds

One of the actions performs builds with a wide variety of `configure` options.
Given how configurable the build is, this test is quite useful.

I created a script that mimics that locally using `parallel`:
https://github.com/neomutt/management/tree/main/build

---

These need to go through GitHub

## Static tests

GitHub gives us a few static analyses of the code.

## Expensive tests

There's also:
- a fuzzer that runs on the address parsing code
- coverity static analysis (limited to 3/day)
