### ISSUE TITLE
Set color for selected line in index

### ISSUE THREAD

**Issue by binaryplease** [neomutt/neomutt#1474]
Hello,

I'm tryng to set the color (background and foreground) of the line that is currently focused in the index.
I have tried about every variable's name I could find and can't manage to change it's color.

To be clear: I mean the line that is marked and goes up and down when you press the arrow keys.

Please tell me how to set this.

**Comment by flatcap** [comment]
The name you need is `indicator`, e.g. `color indicator default green`.
But, if `$arrow_cursor` is set you'll only see a coloured arrow.
`set arrow_cursor = no` and it'll highlight the entire line (<kbd>Ctrl-L</kbd> to refresh).

**Comment by binaryplease** [comment]
That doesn't work for me. I added it at the end here:
https://ptpb.pw/Dm85

This is what the focused line looks like:
![image](https://user-images.githubusercontent.com/1719781/49404930-3c3f6780-f751-11e8-90fd-a9ea79bd6ef6.png)

(blue text)

**Comment by flatcap** [comment]
Hmm... that's odd.  Using **only** your config file, I see the colours I'd expect.
`neomutt -n -F binaryplease.rc ~/mail`

![neomutt](https://flatcap.org/mutt/indicator.png)

Do you have any config that's loaded after that file?

**Comment by binaryplease** [comment]
I tested with a minimal configuration:
```
# vim: syntax=muttrc

##### Accounts
folder-hook 'acc1_folder' 'source ~/.config/neomutt/acc1' # Read configuratoin of first account when switching to folder
folder-hook 'acc2_folder' 'source ~/.config/neomutt/acc2' # Read configuratoin of second account when switching to folder

source ~/.config/neomutt/acc1 # Default account
macro index <f2> '<sync-mailbox><enter-command>source ~/.config/neomutt/acc1<enter><change-folder>!<enter>' 
macro index <f3> '<sync-mailbox><enter-command>source ~/.config/neomutt/acc2<enter><change-folder>!<enter>'

macro index,pager <F5> ":source ~/.config/neomutt/neomuttrc\n"              "Reload the muttrc"
bind index G imap-fetch-mail


set pgp_default_key = "D03B218CAE771F77D7F920D9823A6154426408D3"

##### Colors
source ~/.config/neomutt/base16.muttrc

```

The account files only contain authentication/imap specific settings.

**Comment by binaryplease** [comment]
Found the error, someting is problematic in a sidebar config I was loading.
Narrowing it down now.
