### ISSUE TITLE
Index format of single tags are not displayed properly (custom backend-tags feature)

### ISSUE THREAD

**Issue by Amudtogal** [neomutt/neomutt#1477]
## Expected Behaviour

I have set up neomutt with a notmuch database. Using the "Custom backend based tags" feature, the index should show specific symbols that are defined in the *tag-transforms*, when using the `%?GI?%GI& ?` format in the *index_format*.

## Actual Behaviour

It appears, that the single *tag-format* "GI" (or any other) can not be displayed.
When using a format of `%g` (which displays all tags in their defined transform) instead, the tags are displayed properly.
When replacing the format with `%?GI?x?`, the `x` appears in the index.

The tags work as expected in the sidebar and notmuch search in general, so I guess it is not a notmuch/wrong tagging error.

## Steps to Reproduce

- Create a notmuch database and tag some emails with **inbox** and **test**
- have a basic neomuttrc, that opens the notmuch database
- add this to the neomuttrc (see https://neomutt.org/feature/custom-tags#functions for syntax examples)
```
# Custom Tags
tag-transforms "inbox"          "i" \
               "test"           "WORKED" \
tag-formats "inbox"             "GI" \
            "test"              "GT"
set hidden_tags = ""

# Index View Options
set date_format="%d.%m.%y %I:%M"
set index_format = "%2C %Z %D | %?GI?x? | %?GT?%GT& ? | %g | %-60.60s  %-25.25F %>  %c"
```

- check, that the first and second elements surrounded by **|** are not displayed properly, the third does.

## How often does this happen?

- Always

## When did it start to happen?

It never worked (at least for me).

## NeoMutt Version

```
NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.19.4-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.35 (compiled with 1.35)
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.1 20180831 (GCC)

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn=/usr --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo
  -gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color
  +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

* Arch Linux (official pacman release of neomutt)
* Running suckless terminal (guess it is not important, as `%g` works)
* Local maildir
* I tested all of this with a minimal copy of my neomuttrc
* It is not a `color` issue, tested with both theme enabled and disabled.

**Comment by flatcap** [comment]
hi @Amudtogal, your config is _nearly_ correct (you'll kick yourself :-)

There's an extra `\` (backslash) after `"WORKED"` that shouldn't be there.
That means the next line is mis-interpreted as more `tag-transforms`.

If I remove that and tag some things `inbox` and `test`, I see labels of `i` and `WORKED` respectively.

**Comment by Amudtogal** [comment]
Hey @flatcap 
You are absolutely right (smashs head against wall)!
Even better: I thought about this during debugging, but I must have fixed it in the wrong file...
Thank you for the fast answer!
