### ISSUE TITLE
w3m no longer parses HTML URLs on neomutt-1.7.0-20160910.fc24.x86_64

### ISSUE THREAD

**Issue by sadsfae** [neomutt/neomutt#148]
I've noticed that using w3m in mailcap for parsing HTML emails no longer parses them correctly.  This seems to be a recent thing as I've used w3m across the 1.6.2 versions without an issue.

Here is my ~/.mutt/mailcap:

```
text/html; w3m -I %{charset} -T text/html; copiousoutput;
```

Lynx still works as expected however, and they are viewable via urlview.

```
text/html; lynx -display_charset=utf-8 -dump %s; nametemplate=%s.html; copiousoutput
```

I call mutt with -F so I do not use any of the shipped configuration files.

**Comment by flatcap** [comment]
Thanks for the sample email you sent me.
The first thing I did was to view the attachments:
```
I 1 Important Meeting                      [message/rfc822, 7bit, 1.2M]
I 2 └─><no description>                     [multipa/mixed, 7bit, 1.2M]
I 3   ├─><no description>              [multipa/alternativ, 7bit, 4.3K]
I 4   │ ├─><no description>           [text/plain, quoted, utf-8, 1.1K]
I 5   │ └─><no description>            [text/html, quoted, utf-8, 2.9K]
A 6   └─>Important Meeting.docx      [applica/vnd.openxm, base64, 1.2M]
```

Hmm... deeply nested mime attachments.  This may be the problem.
I'll investigate what Mutt does with it, when I get a chance.

**Comment by sadsfae** [comment]
Here's another one, in this example w3m was able to only show the single URL:

```
UrlView 0.9: (1 matches) Press Q or Ctrl-C to Quit!

->    1 www.kinetica.com
```

Whereas lynx shows everything like so:

```
UrlView 0.9: (6 matches) Press Q or Ctrl-C to Quit!

->    1 www.kinetica.com
      2 http://t.hsms10.com/e1t/c/*Vd0_DG4Pf9Z-W60CHPP4QrSQ10/*W2TQcqN1fzbknW5nv0Tn55sfqY0/5/f18dQhb0Sq5D8
      3 http://t.hsms10.com/e1t/c/*Vd0_DG4Pf9Z-W60CHPP4QrSQ10/*W97PP6F2jc63kW7KnRPZ3Y32TQ0/5/f18dQhb0Sjvc8
      4 http://t.hsms10.com/e1t/c/*Vd0_DG4Pf9Z-W60CHPP4QrSQ10/*W5j7tG931hlqrW762dJZ6sHFyH0/5/f18dQhb0Sjvc8
      5 http://t.hsms10.com/e1t/c/*Vd0_DG4Pf9Z-W60CHPP4QrSQ10/*W7x5R4v8RmmBlW5cPK6P6VYzdB0/5/f18dQhb0S5fg8
      6 http://t.hsms10.com/e1t/c/*W6Xhyxh3-bPpTW6JcKh11-prq-0/*W3WjY083xXFT5Vk3LKy7kLqXJ0/5/f18dQhb0S65Q6
X_sHCV12l5z22CFrCVjRNG22tQRTCW8V_PHT4P8GRKW5kgPHS8FbRZdW5wns4Z8qq6nKW6YmDSk3HNq9gW7dt0dy4jjXkmW3h1xv_7dfp9
VW72BJkw8C1pZ1W2bT7Sk4C5z_rW1pKCsP4g29bcW4s6fwY1fn_wkW5tYMB_48vPNHW375X5C3wGt9qW4Wvhk-25BC3FW45jmNh4TdVWDN
5hfzpy9RqyMW5zzFSj1tst7BW3Qxhsf2cGFXYW66z30V8ppWBYVNGz9V8zBFyJW7pFbd069sJ5BW63cp7d3p0k2mW7PkSP74vNwbMN7D2v
DF7hZQlW3g6Wq020crHPW7XZSD86kPHGwW2LK48f83YythW86gv1Y161n_CW7fdNCs6zDvxMW2lYSw76yl4-jW3pZjDW67mnRTW1dWTb57
D-CY_W7lWtrn3p8FdgW8C1d4X2PtqslW844-XS7FMDkxW60p_mP2CTzRZW6xcyY62NYjg6W8vJspL1_ZXLWW47N4p361K93vW3t9S6F11s
_7cW2kGHxV2rbzbpW8hjp3B3dSjBlW3Lt7sk7VJvRxW1QR8Sv76MQRBW8X-9Br3MkJV_W217X0m6bt7BGW5Bpz5h5BB2PzW83XSnw5yFlv
JN1-Bxgxsmq1HW39b7rT6vFMTgVMQr8D6qxTTNW7fTdyB3mbSjSW7_GQL76sP7WRW3ZM8mp6NYtsLW43Lj0J7022dnW2rZS9q11q_dBW91
rw__5f3hQ6W4zF4cc9k0cK_W8NrXDh8YYNx3W6_S04x1vN64XW4BDySf9l0LYDW42bxvc1_-Thmf1m12B604
```
[example-html-email.txt](https://github.com/neomutt/neomutt/files/476780/example-html-email.txt)

The structure looks like:

```
  I     1 <no description>                                                                    [multipa/alternativ, 7bit, 24K] 
  I     2 ├─><no description>                                                             [text/plain, quoted, utf-8, 3.2K] 
  I     3 └─><no description>                                                             [text/html, quoted, utf-8, 20K]
```

**Comment by flatcap** [comment]
OK, bad news.  I've investigated this (and learnt a lot :-)

The important fact is that w3m doesn't create a list of reference links at the
end of the mail and that's the problem.

Here are my results (tested using Mutt-1.7.0 and NeoMutt-20160916):

Mailcap entry:
- **w3m** -- `text/html; w3m -cols ${COLUMNS:-80} -I %{charset} -T text/html; copiousoutput`
- **links** -- `text/html; links -dump -dump-width ${COLUMNS:-80} %s; nametemplate=%s.html; copiousoutput`
- **links-no-ref** -- `text/html; links -dump -no-references -no-numbering -dump-width ${COLUMNS:-80} %s; nametemplate=%s.html; copiousoutput`

| mailcap      | $pipe_decode | auto-view    | piped to less | urlview |
|:-------------|:-------------|:-------------|:--------------|:--------|
| links        | no           | text + links | raw email     | 6 links |
| links        | yes          | text + links | text + links  | 6 links |
| w3m          | no           | text only    | raw email     | 1 link  |
| w3m          | yes          | text only    | text only     | 1 link  |
| links-no-ref | no           | text only    | raw email     | 1 link  |
| links-no-ref | yes          | text only    | text only     | 1 link  |

`w3m` does a good job rendering the html, but it doesn't provide a list of links.
(I can't find any evidence that it **ever** did)

`urlview` is given plain text and works by matching that against a regex.
Without the list of links, it can't find anything.

**Comment by sadsfae** [comment]
@flatcap thank you for looking further into this, it does seem w3m renders HTML emails better for me and I was pretty sure it passed the same links to urlview as lynx but your empirical research has proven otherwise.

For the record I'm using these methods along with ```urlview``` in ```~/.mutt/mailcap```

**lynx**
```
text/html; lynx -display_charset=utf-8 -dump %s; nametemplate=%s.html; copiousoutput
```

**w3m**
```
text/html; w3m -I %{charset} -T text/html; copiousoutput;
```

**Comment by flatcap** [comment]
Not a problem -- I learn something every time :-)

One last comment, before I close the issue -- I did think of a workaround (it's not pretty, and it's not tested).  Create a macro for your urlview that:
- save mailcap setting (use a $my_VARIABLE)
- set alternate mailcap that uses links
- run urlview
- restore mailcap setting

**Comment by bsnjoy** [comment]
in .muttrc change line for urlview - this way you'll pass message date to urlview without w3m modifications:
macro index,pager \cb "<enter-command> unset pipe_decode<enter><pipe-message>urlview<enter>" "get URLs"
