### ISSUE TITLE
Removing notmuch unread tag when opening a message 

### ISSUE THREAD

**Issue by matt-snider** [neomutt/neomutt#1485]
Hi there,

I'm new to neomutt but I've spent a lot of time the last several days configuring it. I've got a setup that includes several mail accounts synchronized with offlineimap and tagged with notmuch. That part seems to be working properly. On the neomutt side, I have several virtual mailboxes to display mail from all accounts based on tags. 

What doesn't seem to work, is removing the `unread` notmuch tag when displaying the message (the \S mail flag is updated). 

Here are some settings that may be relevant:
```
set nm_exclude_tags = ""
set nm_unread_tag = unread
message-hook ~A 'push "<modify-labels>-unread<enter>"'
```

I expected things to work out of the box mostly once `nm_unread_tag` was set, but figured as a last resort `message-hook` would work, but it just hangs and I need to force kill it. Maybe there is an error there.

I assume this is a fairly common configuration, so maybe I'm totally off the mark here.

**Comment by Austin-Ray** [comment]
What version of `neomutt` are you using?

Could you provide all `notmuch`-related configuration from your `neomuttrc` file? Make sure to redacted sensitive information

In your `.notmuch-config`, is `synchronize_flags` set to `true`?

**Comment by matt-snider** [comment]
Hi @Austin-Ray - thanks for the response.

Here are some more details:
* `NeoMutt 20180716` on Arch Linux ([neomutt](https://www.archlinux.org/packages/community/x86_64/neomutt/)). 
* `synchronize_flags` is set to `true`
* `notmuch`-related config from `~/.config/mutt/muttrc`:
    ```
    set vfolder_format = "%6n(%6N) %f"

    set virtual_spoolfile = yes
    virtual-mailboxes "Inbox" "notmuch://?query=tag:inbox&limit=200"
    virtual-mailboxes "Drafts" "notmuch://?query=tag:draft"
    virtual-mailboxes "Sent" "notmuch://?query=tag:sent"
    virtual-mailboxes "Archive" "notmuch://?query=not tag:inbox and not tag:spam"
    virtual-mailboxes "Trash" "notmuch://?query=tag:deleted"
    virtual-mailboxes "Spam" "notmuch://?query=tag:spam"

    set nm_exclude_tags = ""
    set nm_open_timeout = 5
    set nm_query_type = messages
    set nm_record = yes
    set nm_record_tags = "-inbox,archive,sent"
    set nm_unread_tag = unread

    # Also tried this but froze neomutt requiring force kill
    # message-hook ~A 'push "<modify-labels>-unread<enter>"'
    ```
* I've also checked that none of the other neomutt configuration files listed in the `man`-page that have a higher precedent (e.g. `~/.config/neomutt/neomuttrc`) are present

**Comment by matt-snider** [comment]
@Austin-Ray I just tried it, it didn't change anything. So neomutt should normally remove the `unread` tag? If that is the case, I can try going through and commenting other settings out to narrow it down. 

 How about that `message-hook`? Any reason something like that should cause neomutt to freeze? e.g. syntax error in the command

**Comment by Austin-Ray** [comment]
@matt-snider try this minimal configuration to see if it works:

```vim
set folder=/path/to/maildir
set virtual_spoolfile=yes
virtual-mailboxes "Inbox" "notmuch://?query=tag:inbox"
```

you can run the configuration with `neomutt -F /path/to/minimal/config`

It worked for me when I used the `neomutt` package in Arch's repo.

**Comment by matt-snider** [comment]
@Austin-Ray That's great thank you!

I was about to write back saying it didn't work, but it does once neomutt is closed. 

I've found my original config also works as long as the message (with `unread` tag) _also_ has the N new flag - which is normally the case. But, in the test I was doing, I had:

* added the `unread` tag with notmuch
* opened neomutt and the message 
* closed neomutt
* checked via notmuch if the tag was still present

I'm guessing that because this message's flags hadn't changed, and the tag-writes don't happen immediately, neomutt detects no changes and does not do the normal tag writing on close - it prints "Mailbox is unchanged". 

Are any of the following problems or bugs in your opinion:
* Not updating the `unread`-tag at the same time as the N-flag - i.e. immediately, not requiring closing down neomutt
* Not updating the `unread`-tag if the N-flag wasn't changed

I expected the tag updates to occur immediately the same way that the N flag disappears immediately.

**Comment by Austin-Ray** [comment]
> @Austin-Ray That's great thank you!

You're welcome!

> I'm guessing that because this message's flags hadn't changed, and the tag-writes don't happen immediately

Tag writes are deferred since they are an expensive operation. They occur whenever a mailbox is closed (exiting, changing mailbox, etc.) You can trigger tag writes with `sync-mailbox`. If you write a macro or hook to sync the mailbox frequently, you'll probably notice the delay.

> Not updating the unread-tag at the same time as the N-flag - i.e. immediately, not requiring closing down neomutt

The tags are updated, but they're not synchronized with the `notmuch` database for performance reasons until a mailbox is closed or `sync-mailbox` is called. However, the local maildir flag is modified immediately so if `notmuch new` is executed before tag writing, the `unread` properly updated.

A lot of the tradeoffs for `notmuch` are due to performance constraints. Compared to the other local backends, `notmuch` is exceptionally slow, and unfortunately there's not much we can do about it.


On December 10, 2018 6:32:55 PM EST, Matt Snider <notifications@github.com> wrote:
>@Austin-Ray That's great thank you!
>
>I was about to write back saying it didn't work, but it does once
>neomutt is closed. 
>
>I've found my original config also works as long as the message (with
>`unread` tag) _also_ has the N new flag - which is normally the case.
>But, in the test I was doing, I had:
>
>* added the `unread` tag with notmuch
>* opened neomutt and the message 
>* closed neomutt
>* checked via notmuch if the tag was still present
>
>I'm guessing that because this message's flags hadn't changed, and the
>tag-writes don't happen immediately, neomutt detects no changes and
>does not do the normal tag writing on close - it prints "Mailbox is
>unchanged". 
>
>Are any of the following problems or bugs in your opinion:
>* Not updating the `unread`-tag at the same time as the N-flag - i.e.
>immediately, not requiring closing down neomutt
>* Not updating the `unread`-tag if the N-flag wasn't changed
>
>I expected the tag updates to occur immediately the same way that the N
>flag disappears immediately. 
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/neomutt/neomutt/issues/1485#issuecomment-446015189

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by matt-snider** [comment]
@Austin-Ray Sorry to hear that! Thank you so much for looking into it :+1: :smile:

**Comment by ngortheone** [comment]
Hi @matt-snider, @Austin-Ray  
I am planning to setup  neomutt + notmuch. Is this still still an active issue?

**Comment by SirJls** [comment]
Hi @ngortheone, I am still experiencing the same issue. I am currently on: 20201120

**Comment by S1SYPHOS** [comment]
I get the feeling this is still valid for `NeoMutt 20211029` ..

**Comment by roccoblues** [comment]
I'm trying to cleanup some older issues here. Can someone reproduce this with the latest version? Thanks!
