### ISSUE TITLE
Bug: Non-generic handling of certificate verification

### ISSUE THREAD

**Issue by guyest** [neomutt/neomutt#1488]
## Expected Behaviour

When I have a valid certificate issued by an external CA, I expect that certificate to be identified as valid by `neomutt` when it is already identified as such by my local `openssl` given the proper intermediate CA chain is provided.

## Actual Behaviour

1. I have been issued two key-certificate pairs intended for S/MIME encrypt and sign, respectively. To be explicitly clear, either one of them has only encryption or signing capabilities. Due to the way that verification is coded in the provided `/usr/lib/neomutt/smime_keys` script, the validity of these certificates is not properly respected. In fact, one of them is identified as valid and the other is not **but** this is just an accident of the arbitrary order in which the `-purpose` options are passed to the `openssl` binary. It turns out that the `-purpose smimeencrypt` option comes second leading my encryption certificate being marked as valid but the signing certificate fails verification after `smime_keys refresh`:

```
error 26 at 0 depth lookup: unsupported certificate purpose
openssl verify returned exit code 2 with output:
error /home/gmarcus/.smime/certificates/8e8d696c.0: verification failed
```
The problem is traceable to the implementation of `openssl_verify` distributed with `neomutt`. I have exactly zero experience with perl, but at least that much is clear. It seems like a fix here would entail some more careful logic in `openssl_trust_flag` to handle each `-purpose` option individually and only indicate an invalid certificate if **neither** the encryption **nor** the signing `-purpose` can be verified. 

2. There is a related issue regarding the addition of root certificates. The `openssl` documentation states rather clearly that when it is passed a directory via the `-CApath` option, that directory should contain root certificates in the PEM format each with a filename *hash*.0, where *hash* is as usual. This is very nearly what `neomutt` already does when issuing the `smime_keys add_root` command, but the extension of '.0' is missing. This is, indeed, a critical missing piece. The scenario I describe in (1) above is only such because I explicitly ensured a symlink to the certificate added by `smime_keys add_root` was present in the `smime_ca_location` but with the properly adjusted filename. Without this, a different error was raised complaining of missing local issuing certificate. From what I can tell, this part of the fix seems like an awfully easy one. 

As mentioned above, my ineptitude with perl may be more of a liability than this offer is a help, but I am happy to contribute a patch to fix this issue if someone is willing to give a bit of initial guidance. 

## NeoMutt Version

```
NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.19.4-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.35 (compiled with 1.35)
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.1 20180831 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn=/usr --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by roccoblues** [comment]
I'm trying to cleanup some older issues here. Can you still reproduce this issue with the latest version? Thanks!
