### ISSUE TITLE
Feature request: crypt-autoselectkey

### ISSUE THREAD

**Issue by dannyob** [neomutt/neomutt#149]
I just tried switching from my current mess of mutt patches to neomutt (in the Debian build), but neomutt doesn't currently support the crypt-autoselectkey from [this patch from Dale Woolridge](http://www.woolridge.ca/mutt/crypt-autoselectkey.html).

> This patch adds the variable crypt_autoselectkey (default no), which allows forcing mutt to autoselect a key when only (a trusted) one is available in the "PGP keys matching ..." menu.
> It is often the case that a particular recipient (or key-id as selected via crypt-hook) results in a list of selectable keys with only one entry (not counting duplicates for uids). Setting crypt_autoselectkey will automatically select a key if only one matching (and trusted) key exists. 

I find it a useful feature, as I use GPG with Mutt most of the time.

Is there a chance this could be included in Neomutt?

**Comment by flatcap** [comment]
Hi @dannyob, that sounds like a useful patch.

We don't have a lot of developers, so I can't say if/when it will get adopted.

However...  If you're prepared to help, I can spare some time to help you get it integrated.
It's fairly simple:
- Get patch working with latest NeoMutt
- Give it a good test
- Document the new feature ("fill-in-the-blanks" template available)

**Comment by dannyob** [comment]
I'm happy to help -- let me just reach out to Dale and see if it's okay with him; I can do the rest of the legwork I thinkk.

**Comment by flatcap** [comment]
Great.  How are your C skills, btw?  (I probably should have asked sooner :-)

I suggest:
- Fork Neomutt
- Create a [devel/crypt-autoselect] branch (or similar)
- Get patch to a point where it compiles

Then let me know and I'll pull the branch into the neomutt repo.

Any questions, you can ask them here, our IRC channel (#neomutt on freenode.net), or on devel mailing list.

**Comment by dannyob** [comment]
Okay, I got the go-ahead from Dale. Is there a particular style/location you'd like for any tests?

**Comment by flatcap** [comment]
As we discussed on IRC, it's going to be quite hard to test.
If you can come up with a scheme, great.

We definitely need some documentation, explaining in simple terms:
- what the feature does
- when it would be useful
- what problems it can prevent
etc

**Comment by guiniol** [comment]
@dannyob How far along are you on this?
I have a number of people I work with who trigger this case so I would really like a solution ^^

**Comment by dannyob** [comment]
@guiniol I looked into this, and it seemed like the existing neomutt dealt with the situation that autoselect was intended to solve, which I believe is if there's one (and only one) strong key, then mutt should just use that one.

Can you describe what you're seeing with your work colleagues?

**Comment by guiniol** [comment]
@dannyob When I try to send an email to specific colleagues, I am presented with a menu to select a key to encrypt to. All the keys in the menu have the same key id, but the emails differ, which, I guess, is why it's showing them to me. Isn't that the behaviour you were describing?

**Comment by dannyob** [comment]
So looking into the code, it looks like neomutt will show you one key id as you describe if that key isn't "strongly validated". If you sign the key with gpg --sign-key or gpg --lsign-key, you should be able to skip the menu. This was also what autoselect was supposed to do -- I haven't found a situation yet where autoselect doesn't match what neomutt does by default. But I'm still eager to find one!

**Comment by guiniol** [comment]
I checked and the key are signed by me already. Did you configure anything or does it just work by default?

**Comment by flatcap** [comment]
Thanks for the suggestions @dannyob, but nobody seems to have the time to work on it.
This issue will now be closed and listed on the [closed discussions page](https://www.neomutt.org/dev/discussions)
