### ISSUE TITLE
imap: STATUS command is done on selected mailbox

### ISSUE THREAD

**Issue by sileht** [neomutt/neomutt#1494]
Since imap backend doesn't have connection pool anymore, STATUS command are issued while mailbox is selected.

These days, most servers allow this even the RFC doesn't:

My dovecot for example return:

> 5< a0058 OK [CLIENTBUG] Status on selected mailbox completed (0.001 + 0.000 secs)

but return the expected data.

**Comment by flatcap** [comment]
Hmm... lots of questions...

Which command _should_ we send for the selected mailbox?
Where is the status coming from?  `mx_mbox_check_stats()`?

As we know which mailbox is _selected_, can we filter it out?
Or, should we transform the request into [the correct command]?
Or, should we try STATUS first, then fall back to the correct command?

Or, should we undo some of the mxapi stats changes?  (Sorry, @Austin-Ray)
Before those changes, imap was told to 'update all your mailboxes', which allowed it to use the right commands and group the server requests.

**Comment by sileht** [comment]
> Which command _should_ we send for the selected mailbox?

It's EXAMINE, but we don't need to run it or STATUS on selected mailbox, because imap will send us asynchronously EXISTS, EXPUNGE, VANISHED messages that give us the same informations.

> Where is the status coming from? `mx_mbox_check_stats()`?

This is what I need to figure out.

> As we know which mailbox is _selected_, can we filter it out?

We already have this filter in place, but for some reason it doesn't catch it.
When I just start neomutt and wait for check_stats to occurs, everything is fine, the selected mailbox is skipped. I need to figure out what make the filter doesn't work sometimes.

> Or, should we transform the request into [the correct command]?
> Or, should we try STATUS first, then fall back to the correct command?

I don't thing so.

> Or, should we undo some of the mxapi stats changes? (Sorry, @Austin-Ray)

This change looks good.

> Before those changes, imap was told to 'update all your mailboxes', which allowed it to use the right commands and group the server requests.

The server command is still grouped.

imap_mbox_check_stats() pipeline all commands, but return the previous values. Then next imap not queued command will updated all ImapMboxData counters, but this new value will be seen only on next 
imap_mbox_check_stats() call.

Maybe we could not pipe them if that an issue, personally I use 10 seconds for check_stats, so I don't care.

**Comment by sileht** [comment]
Oh, I we fixe it with 8706dd0f :)

**Comment by sileht** [comment]
Sorry for the noise
