### ISSUE TITLE
sidebar_divider_char.. multiple chars?

### ISSUE THREAD

**Issue by voidzero** [neomutt/neomutt#15]
Before mutt 1.6, I used to have this setting set as two characters of which the last was a space, it just adds a little margin. But when I do this now, the first character of the lines in emails are chopped off. Is there any chance to make this possible again? (I had it set to `│ `, but now it *has* to be a single char. It was just more aesthetically pleasing, now it looks a bit too crammed up.)

**Comment by flatcap** [comment]
OK, that's not hard to do.
Bugs take priority, but as soon as I have free time.

**Comment by flatcap** [comment]
Old behaviour restored.  Enjoy.

**Comment by voidzero** [comment]
Much thanks!
