### ISSUE TITLE
Trash improvements project

### ISSUE THREAD

**Issue by 4nd3r** [neomutt/neomutt#150]
1. (optionally?) clear all flags or mark as read before moving to trash
2. add a header telling you the folder the email was in - that way you can undelete to the right place
3. different flags for purged and "trashed" mails would be good as well

**Comment by flatcap** [comment]
The alternative to 1) is to get the trash folder to lie about its contents.
i.e. Trash folder always reports 0 new mails, 0 flagged, etc
That way, if the email is undeleted the flags remain intact.

However the flags are managed, I **never** want to be told: "New mail in =trash"

About 3), there was a long discussion on mutt-dev recently.  Someone wanted to be able to see the **difference between** emails that had been **deleted** and those that had been **saved**.  The discussion ended with the user being told to "just remember" what he'd done.

**Comment by P-EB** [comment]
Regarding 2, it seems to be an issue for me to have a client that alters the text of your emails. I'd say to save such intel in a specific database, using the reference of the email (or its path/name/whatever is relevant).

**Comment by flatcap** [comment]
> Regarding 2, it seems to be an issue for me to have a client that alters the text of your emails

I see your point, but...

The [keywords feature](https://www.neomutt.org/feature/keywords/) alters headers by design.
Also, these are emails you want to **delete**, do you care if the headers changed in a reversable way?

> save such intel in a specific database

This is a better solution, but clearly much more work.
Apart from the original directory, you could store a deletion timestamp (and probably other stuff).

**Comment by flatcap** [comment]
Other notes / ideas:

Add:
- `<empty-trash>` function
- `$empty-trash-confirm` variable quad-type

Changes to the index for the trash folder:
- `$index_format` expando for "original location".  This would allow a user, looking at the trash folder to see where the mail came from.
- Allow the user to sort/filter by "original location"
- Allow the user to sort/filter by "deletion date"

Changes to the status bar (if not too resource-intensive):
- Add status bar expando for: "number of emails in trash"
- Add status bar expando for: "size of trash folder"

Make sure the trash folder plays well with GMail.  There have been reports that trashing an email means it gets archived on GMail.

Add a documentation example for auto-empty, e.g.
`folder-hook =trash 'push <delete-pattern>~d>30d<enter>'`

**Comment by P-EB** [comment]
Hm, I suggest we build some todolist regarding this enhancement. When we're happy with it, we should see who would be ok to implement it.

Cheers!

**Comment by P-EB** [comment]
I opened a project.

We'll design a note by specific improvement/thing to do, and open an issue when somebody wants to work on a note.

**Comment by flatcap** [comment]
It's a good idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
