### ISSUE TITLE
Switching folders using an external program (fzf)

### ISSUE THREAD

**Issue by JoshuaCrewe** [neomutt/neomutt#1515]
This question started on IRC a few weeks ago. The responses on there were very helpful (as it always is!) but there are a few gaps in my knowledge that I would appreciate some help on. Primarily I am happy to know if the approach I am taking is not possible.

**My approach**: 
In Vim I use [FZF](https://github.com/junegunn/fzf.vim) to navigate around a project. The idea is to translate this approach to navigating folders in Neomutt. The workflow would be to map a command to call FZF, fuzzy find the folder I am looking for and feed this back to `<change-folder>`. 

**What I have so far**
From talking on IRC I was pointed to using `:source` and binding that to a keyboard shortcut.
```
# ~/.muttrc

macro index ,o ":source ~/.mutt/scripts/fzffolder|<enter>"
```
This calls a script which sends the appropriate mutt `<change-folder>` command.
```
# ~/.mutt/scripts/fzffolder

#!/usr/bin/env bash

echo "exec change-folder"
```
This script would eventually hold all the logic for calling FZF and passing the chosen folder to the mutt command.

**What I don't know**
The hole in my knowledge comes at the point of passing the desired folder name to `<change-folder>`.  What I thought would be done would be something like : 
```
echo "exec change-folder<enter>+work/INBOX<enter>
```
This results in an error reporting that the file could not be sourced. 

The question is, am I on the right track or is this a bit of a dead end? Should I be passing the result of `fzffolder` back in a different way ?

In closing I would say that I have very much enjoyed this community on IRC and appreciate the time people have taken to give our information and guidance. Thanks!

**Comment by flatcap** [comment]
Hi @JoshuaCrewe 
Ah, I see the same problem.
Because we're running config commands (`exec change-folder`), they aren't expecting user input.

The way round this is to `push` instead.  It puts text into the keyboard buffer, as if it were typed.
Here's my test script:
```sh
#!/bin/bash
echo "push 'c=neo.github<enter>'"
```

It effectively types <kbd>c</kbd> (`<change-folder>`), then the folder name '**=neo.github**' and <kbd>\<Enter></kbd>.

**Warning**: `<push>` is very useful, but it can be risky too.
  If the initial `c` were missing, NeoMutt would interpret the folder name as keystrokes (where `d` means delete :-)

**Comment by JoshuaCrewe** [comment]
@flatcap that is beautiful.

```
#!/usr/bin/env bash

fzf_command='fzf'
fd_command="fd . ${HOME}/.mail/ --type d"

folder="$($fd_command | $fzf_command)"

echo "push 'c$folder<enter>'"
```
This works for me!

As an aside, is it possible to bind the enter key as part of the shortcut ? The following doesn't work but I can't see why. Is Enter a special key, I have been looking at [the key bindings](https://neomutt.org/guide/configuration.html#5-%C2%A0changing-the-default-key-bindings) which does list `<enter>` in there.

```
bind index <Space> noop
macro index <space><enter> ":source ~/.mutt/scripts/fzffolder|<enter>"
```

Thanks a lot of your speedy response.

**Comment by JoshuaCrewe** [comment]
Ahhh yes, thanks for pointing that out. I am little confused though. If I don't have the `<enter>` after the `|` character then the script doesn't get run. It just sits in the command prompt waiting for me to press enter manually. I must be misunderstanding something.

What I was more asking about is using the combination of `<space><enter>` to trigger the script. That combination doesn't call the script as I would expect. Using a different combination does though. So the following will call the script if `<space>q` is called :

```
macro index <space>q ":source ~/.mutt/scripts/fzffolder|"
```

**Comment by flatcap** [comment]
Sorry, I misread your previous question -- you're right, you need the trailing `<enter>`.
I couldn't get an `<enter>` binding to work, but `<return>` does.

```
bind index <space><return> exit
```

**Comment by JoshuaCrewe** [comment]
All the pieces are in place now. Thanks @flatcap for your help on this🥇
