### ISSUE TITLE
Is it expected that now error if status_format is empty?

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#1530]
In my .muttrc I have

`set status_format = ""`

This triggers the following error:

>Option status_format may not be empty

It is easy enough to workaround by setting it to a space:

`set status_format = " "`

The change in behavior doesn't bother me at all, but I just wanted to make sure that it is expected. If it is expected, please close this issue.

```
$ ./neomutt -v
NeoMutt 20180716-1090-49bc89
```

Thanks for all of your time!

**Comment by gahr** [comment]
Commit https://github.com/neomutt/neomutt/commit/cbc52d9f49468710de614f143d912ba3a9df5095 has introduced a bunch of `DT_NOT_EMPTY` restrictions that are not strictly necessary, as a non-empty string doesn't necessarily mean a sensible value (`set attachment_format="foobar"`).

@flatcap I'd just lift the constraints on all of them except for `charset`. That'd be

* alias_format
* attach_format
* compose_format
* date_format
* folder_format
* group_index_format
* index_format
* message_format
* mix_entry_format
* pager_format
* pgp_entry_format
* query_format
* sidebar_format
* status_format
* vfolder_format

**Comment by flatcap** [comment]
> DT_NOT_EMPTY restrictions that are not strictly necessary

true

> I'd just lift the constraints

Actually, I'm leaning the other way

> alias_format, attach_format, folder_format, group_index_format, index_format,
> message_format, mix_entry_format, pgp_entry_format, query_format,
> sidebar_format, vfolder_format
>
> as a non-empty string doesn't necessarily mean a sensible value

True, but en empty format string, in most cases, isn't desirable.

Given an invalid `$index_format` string, we have three choices:

1. Use the string; display garbage in the index
2. Warn the user at time of config (we know the source)
3. Warn the user at time of use (when the index is displayed)

We don't yet validate format strings, but I have some ideas how we could.

> date_format, forward_format

These two, if set invalidly, would cause problems elsewhere that the user may not understand the cause.

> compose_format, pager_format, status_format

These three cases are a little different.

I can see the use-case for setting them to empty, do declutter the screen.
However, I have an alternative suggestion.

- When empty, **do not display the bar at all**

This would be like vim's `set laststatus=0`
This would be a nice 'easy' task for a beginner.

**Comment by scottkosty** [comment]
@gahr @flatcap Wow, you two are amazing! Thanks for the quick response and all of the open discussion and continued work on neomutt. I really appreciate all of your work.
