### ISSUE TITLE
Prefixing "./" to attach save target breaks tag+apply-save

### ISSUE THREAD

**Issue by alvherre** [neomutt/neomutt#1532]
It seems commit 2af1924dc49f ("Add the "attach_save_dir" config variable") breaks the sequence where some attachments are tagged, then apply-save and a directory is entered in the first prompt.  The problem is that for the second and subsequent attachments, the attach_save_dir directory is prepended to the destination, which it should not be.

As an example, I typically enter "/tmp" in the first location to save, mutt tells me this is a directory so do I want to save as a file inside it, I say "all", so it asks "file under directory?" indicating the original file name.  So far so good; first file is saved correctly.  For the next tagged attachment it suggests to save to .//tmp/v1-0001-Ensure-PK-side-action-triggers-for-partitions-aft.patch which is not the intended location ("./" seems to be the default attach_save_dir, then "/tmp" is the directory I entered, then follows the original attachment filename).

I suppose I should set attach_save_dir to "/tmp" and avoid this altogether, but this change broke the existing workflow.

**Comment by gahr** [comment]
I *think* I fixed this in 5d6ed1094cba6abdb4332a03e64c4965da27020f. Sorry for not noticing this issue earlier.
