### ISSUE TITLE
Bind case sensitive control characters

### ISSUE THREAD

**Issue by InspectorMustache** [neomutt/neomutt#1539]
Is there any way to create case sensitive control character keybindings? Ie. bind \<Ctrl-x\> and \<Ctrl-Shift-x\> to two different things? From looking at the docs, I'd guess no:

> Note that the case of x as well as \C is ignored, so that \CA , \Ca , \cA and \ca are all equivalent.

But I was wondering if there is an alternate way of referring to keys which allows this.

Sorry if this has been asked before, I couldn't find anything.

**Comment by flatcap** [comment]
tl;dr No

In NeoMutt you can test which keys are recognised with the command `:exec what-key`

On Linux, running `showkey` as root, I see (heavily filtered):
```
keycode  33 = +f +F

control                 keycode  33 = Control_f
shift   control         keycode  33 = Control_f
alt                     keycode  33 = Meta_f
shift   alt             keycode  33 = Meta_F
control alt             keycode  33 = Meta_Control_f
shift   control alt     keycode  33 = Meta_Control_f
```

In fact `Control_F` (big F) isn't a valid symbol.

This shows that the keyboard maps **don't** distinguish between:
- `<Ctrl>f`
- `<Ctrl><Shift>f`

That said, my terminal uses `<Ctrl><Shift>f`, but I think it may be cheating.
I think it's trapping `<Ctrl>f` and checking if `<Shift>` is also pressed.

Could NeoMutt do that?  Probably.
But we'd need a very brave volunteer to investigate :-)

**Comment by InspectorMustache** [comment]
I see. Thanks for the detailed explanation. Sorry that I can't be more helpful. Were I either brave or knew anything about C, I would volunteer in an instant.
