### ISSUE TITLE
modyfing tags works without tag-prefix

### ISSUE THREAD

**Issue by jindraj** [neomutt/neomutt#1540]
## Expected Behaviour
tag multiple messages
modify tags without using tag prefix `;`
only tags for the message under cursor should be modified

## Actual Behaviour
tag multiple messages
modify tags without using tag-prefix `;`
tags for all tagged messages are modified

when the steps are followed and tag-prefix is used, the behaviour is the same. But correct according to @flatcap.

## Steps to Reproduce
Described in Actual Behaviour

## How often does this happen?
- Always

## When did it start to happen?
I have no Idea. It's working this way maybe since end of December 2018

## NeoMutt Version

```
NeoMutt 20180716-1094-16df3f
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 18.2.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.11
libidn: 1.35 (compiled with 1.35)
hcache backends: tokyocabinet, lmdb

Compiler:
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Configure options: --prefix=/usr/local/Cellar/neomutt/HEAD-16df3f6 --gss --lmdb --notmuch --sasl --tokyocabinet --with-ssl=/usr/local/opt/openssl --debug --with-ui=ncurses

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/Cellar/neomutt/HEAD-16df3f6/include -DNCURSES_WIDECHAR -I/usr/local/opt/openssl/include 

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls -gpgme +gss +hcache -homespool +idn -inotify -locales_hack -lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/Cellar/neomutt/HEAD-16df3f6/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/Cellar/neomutt/HEAD-16df3f6/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info
* Operating System and its version
MacOS 10.14.2
* Were you using multiple copies of NeoMutt at once?
No
* Were you using 'screen' or 'tmux'?
No
* Is your email local (maildir) or remote (IMAP)?
maildir (virtual-mailboxes)

**Comment by jindraj** [comment]
```
bind  index,pager         ,l      modify-tags
macro index,pager         ,a      "<modify-tags-then-hide>-unread -inbox\n<sync-mailbox><check-stats>"        "archive message"
macro index,pager         ,d      "<modify-tags-then-hide>-unread -inbox +trash\n<sync-mailbox><check-stats>" "delete message"
macro index,pager         ,s      "<modify-tags-then-hide>-unread -inbox +spam\n<sync-mailbox><check-stats>"  "mark message spam"
```

Tag multiple messages with `t`, then any of the commands above is applied to all messages without need of the tag-prefix. (asciinema video)[https://asciinema.org/a/rG2TaDN2IzF59C8XNuLyW2aPX]

**Comment by Austin-Ray** [comment]
I'm still unable to reproduce the issue. 

- Have you tried making a minimal `.neomuttrc` file to see if it's a configuration issue?
- Have you tried a different terminal? (doubt this will affect anything, but worth a shot)

I don't have a Mac to debug on so this debugging process may be slow. I apologise for that.

**Comment by jindraj** [comment]
You're right, @Austin-Ray.
I started neomutt like this:
  * `neomutt -F /dev/null -f notmuch:///$NM_DB_PATH?query=tag:Maillists`
  * no config
  * just specified mailbox
  * key bindings for modify-tags added by commandline in running neomutt
 I tagged multiple messages and only the message under cursor has been modified.

I have no clue what in my config is causing it.

**Comment by jindraj** [comment]
That's it. My mistake. I have this settings probably for a long time.
```
$ neomutt -D |grep auto_tag
set auto_tag = yes
```
So this isn't a bug. I'm closing the issue.
