### ISSUE TITLE
Filtering whole message in Compose

### ISSUE THREAD

**Issue by archenemies** [neomutt/neomutt#1542]
In the "Compose" screen there is a key to filter an attachment through a shell command.

Would it make sense to have a key which filters the whole message, including all headers and all attachments, through a command?

I have been investigating how to send email which looks good to Gmail users, e.g. by parsing Markdown and creating an HTML attachment. [Existing solutions](https://dgl.cx/2009/03/html-mail-with-mutt-using-markdown) seem to depend on using a fake Sendmail to create a multipart/alternative structure. However, my reading of #587 is that we can now send multipart/alternative messages natively?

This suggests that a new solution would be possible, in which an outgoing message could be piped through a script which does the Markdown parsing and creates a multipart/alternative text/html attachment, all in the Compose screen. Then it would be easy for users to view the email structure and check that the attachment looks good before sending it, this time with the usual (non-fake) sendmail.

However, the simpler solution would seem to depend on the ability to filter a whole message in Compose, which I don't see exists. I am wondering if I am mistaken and the feature exists already; or if there is a reason why this feature cannot be easily implemented. Thank you.

**Comment by masukomi** [comment]
the recently merged support for multipart/alternative emails has [instructions as part of the commit](https://github.com/neomutt/neomutt/blob/08f686294e95d51ce224fbc1e278c88689af1cde/doc/manual.xml.head#L9939) @archenemies 

It doesn't seem to be quite what you're hoping for, but maybe some clever mutt geek can figure out a macro to automate it.

**Comment by archenemies** [comment]
Thank you. It looks like the support is still pretty lacking, since according to the link you sent, it doesn't allow the multipart message to be postponed.
