### ISSUE TITLE
Unable to write /var/mail/MBOX error

### ISSUE THREAD

**Issue by hsanson** [neomutt/neomutt#1546]
## Actual Behaviour

I can no longer delete email from mbox mailboxes because neomutt complains it cannot write to it.

## Steps to Reproduce

Start neomutt using a very simple configuration file like below:

```
set folder="/var/mail"
set spoolfile="=INBOX"
set mbox="=INBOX"
mailboxes =INBOX
```

Mark an email for deletion (e.g. press d) and then sync the mailbox (e.g. press $) or exit neomutt. When prompted to delete the marked email say yes.

Neomutt will complain that cannot write to the mailbox and the email won't be deleted.

The INBOX file and the /var/mail folder permissions have not changed and work fine with older versions of neomutt:

```
ls -la /var/mail
合計 132
drwxrwsr-x  2 root   mail   4096  1月 24 08:35 .
drwxr-xr-x 13 root   root   4096  1月 14 22:06 ..
-rw-------  1 root   mail  11558  7月  3  2018 root
-rw-------  1 myusername mail 113650  1月 24 01:00 INBOX
```

## How often does this happen?

- Always

## When did it start to happen?

I did a git bisect and found the issue appeared on commit 0e73f44d2c - "mbox_sync: use mailbox notifications".  If I checkout the previous commit b9233cb3e the problem does not happen and can delete emails from the INBOX using the same configuration and mbox file.

**Comment by flatcap** [comment]
Thanks for the bisect.

**Comment by flatcap** [comment]
I've just pushed temporary fix to branch [[issue/1546](https://github.com/neomutt/neomutt/tree/issue/1546)].
It should fix your problem.  I'll fine tune in the morning.
