### ISSUE TITLE
Backspace not recognized althogh decimal and octal values are correct

### ISSUE THREAD

**Issue by whnr** [neomutt/neomutt#1549]
## Expected Behaviour

Using the `<backspace>` key to move up

## Actual Behaviour

Nothing happens. As the key is not recognized correctly.

`<what-key>` shows: `Zeichen = ^?, Oktal = 177, Dezimal = 127`
`showkey -a` in console shows: `^? 	127 0177 0x7f`
=> This should be recognized as `<backspace>`…

## How often does this happen?

Always. With and without tmux.

## NeoMutt Version

````
NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins und andere.
NeoMutt übernimmt KEINERLEI GEWÄHRLEISTUNG. Starten Sie 'neomutt -vv', um
weitere Details darüber zu erfahren. NeoMutt ist freie Software.
Sie können es unter bestimmten Bedingungen weitergeben; starten Sie
'neomutt -vv' für weitere Details.

System: Linux 4.20.3-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.35 (compiled with 1.35)
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.1 20181127 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn=/usr --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Standard Einstellungen:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Einstellungen bei der Kompilierung:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

````

## Extra Info

* Linux denkfabrik 4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64 GNU/Linux
* Using tmux, but same without.

**Comment by flatcap** [comment]
hi @whnr 
I had a bit of an experiment when you first raised this issue (then got busy, sorry).
(Neo)Mutt relies on curses for keyboard events, so I'm not sure what's going on.

When I hit <kbd>BackSpace</kbd>, I see:
- NeoMutt: `<BackSpace>`
- `showkey -a`: `^? 127 0177 0x7f`

Can you check your terminal's settings.
My VTE-based terminal has 'Compatibility' settings for BackSpace and Delete.
- BackSpace generates: 'ASCII DEL'
- Delete generates: 'Escape Sequence'

Also, please can you give upstream Mutt a try, to see if the same effect happens.

**Comment by whnr** [comment]
Hi Richard,

I tried a bit as well based on your suggestions:
- Mutt: Same behaviour
- Terminal: I'm using the Gnome Terminal. An played with the BackSpace 
  generates Setting: Only when I set it to Ctrl+H is it recognized as an 
  `<BackSpace>` in NeoMutt (`showkey` shows it as `^H`)
- When it is set to 'ASCII DEL' it can be forced to `^H` with 
  ctrl+BackSpace

I found a short explanation on this at:
https://stackoverflow.com/questions/418896/how-to-redirect-output-to-a-file-and-stdout
