### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by ettom** [neomutt/neomutt#1550]
Expected behavior
No segfaults.

Actual behavior
Neomutt segfaults. I'm using two mail accounts set up by mutt-wizard. The segfault happens upon quickly switching between mail accounts.
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `neomutt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000047e678 in monitor_resolve (info=info@entry=0x7ffeb0f26050, m=m@entry=0x
303	    info->magic = Context->mailbox->magic;
```

Steps to reproduce
Set up two accounts with mutt-wizard, switch between them.

Used program versions
```
NeoMutt 20180716-1108-40af05

System: Linux 4.15.0-43-generic (x86_64)
ncurses: ncurses 6.0.20160213 (compiled with 6.0.20160213)
libidn: 1.32 (compiled with 1.32)
hcache backends: lmdb

Configure options: --ssl --full-doc --lmdb --notmuch

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls -gpgme -gss +hcache -homespool +idn +inotify -locales_hack -lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp -sasl +smime +start_color 
  +sun_attachment +typeahead 
```

Operating System and its version
Ubuntu 16.04

**Comment by ettom** [comment]
Ok, the segfault doesn't happen if I comment out ```set postponed = "+Drafts"``` sections in the muttrc files that get sourced upon switching between mail accounts.

**Comment by flatcap** [comment]
Sorry for the slow reply, @ettom.
This is a known problem with `master` -- my fault, I'm afraid.
We've been making some large changes to improve the architecture.
This means breaking up a lot of complicated dependencies, which have been around for decades.

Things should be stable again soon (I'll leave this issue open until then).
After which, I'll be focussed on getting a release made.

**Comment by gahr** [comment]
#1631 should fix this - @ettom, could you please give that branch a go ?

**Comment by yousefakbar** [comment]
I recently had this same issue but managed to fix it. Because I have multiple accounts set up in my NeoMutt, I previously had the `unmailboxes *` command inside the account-specific source files.

I moved this command to the neomuttrc file before switching between two folders, and that did the trick for me. 

Example:
`macro index <F1> '<sync-mailbox><enter-command>unmailboxes *<enter><change-folder>path/to/new/inbox<enter>'`
Of course, a folder-hook is in charge of reinstating the new mailboxes of the account I switch to.
