### ISSUE TITLE
[neomuttrc] Cannot source file from folder-hook using relative path

### ISSUE THREAD

**Issue by aearil** [neomutt/neomutt#1557]
When try to set up a folder-hook to source a file from `~/.config/neomutt/`, the hook fails with the following error:
```
Error: issue converting path to absolute (No such file or directory)
```
And the debug log shows:
```
[2019-02-10 20:45:15]<E> source_rc() Error: impossible to build path of 'account.mail'.
[2019-02-10 20:45:15]<E> mutt_folder_hook() source: file account.mail could not be sourced.
```
To reproduce, I used the following minimal test case:
**~/.config/neomutt/test.rc**
```
folder-hook account 'source account.mail'
set mbox_type=Maildir
set folder="~/mail"
mailboxes = `find ~/mail -mindepth 1 -type d ! -name cur ! -name tmp ! -name new -printf '"%p"\0' | xargs -0`
source account.mail
```
**~/.config/neomutt/account.mail**
```
set spoolfile = "+account/Inbox"
```
When I run `neomutt -F ~/.config/neomutt/test.rc` the **account.mail** file gets sourced correctly the first time by the bare source call, but then the folder-hook is triggered and fails.
This setup works correctly when I give an absolute path to the folder-hook command.

**Comment by flatcap** [comment]
Thanks for the detailed bug report, @aearil.

**Comment by aearil** [comment]
Ok, so I think I have narrowed down the source of the issue:

in [init.c at l.778](https://github.com/neomutt/neomutt/blob/c2d423128ae08493845e578a7f9a592b23be304d/init.c#L778), `mutt_path_to_absolute()` uses the first element of `MuttrcStack` as a reference. For a regular source call, that means the path of the parent file (**~/.config/neomutt/neomuttrc** in this case).

However, when a **folder-hook** is later resolved, `MuttrcStack` is empty and cannot provide a reference to `mutt_path_to_absolute()`.

That being said, I still don't know how the issue could be fixed. Maybe keeping a reference to the parent file/parent file path with the hooks could work ?

**Comment by gahr** [comment]
> Maybe keeping a reference to the parent file/parent file path with the hooks could work ?

That might not be enough: hooks can be defined at runtime, at which point you don't have an rcfile to refer to.
