### ISSUE TITLE
Flush Flags

### ISSUE THREAD

**Issue by weilbith** [neomutt/neomutt#1558]
I wonder how can I flush flags for messages without close NeoMutt or switch the mailbox. I tend to keep the window open, but I want that messages that get marked as read (more likely unmarked to be unread) can be recognized as that outside of NeoMutt as well. So I have some other tools to show me unread messages with notifications etc. pp. If I read now a mail in NeoMutt I wan't them to not bother me anymore.
I added a makro running the shell command notmuch new, but this has no effect. As said only if I close the program or switch the box, the flags are added or removed at the mailbox and are visible for external tools.
I was not able to found a function or command at the help nor documentation. Maybe you guys can help me.

**Comment by jindraj** [comment]
`sync-mailbox` which is bound to `$` by default
You can probably schedule it with timeout-hook.

**Comment by weilbith** [comment]
Wow, thanks! :tada: 
Chained it in a macro with a `notmuch new` call.

Talking about the timeout-hook:
I've set `wait_key` to `no`, but if I use the same macro here, I drop in the shell for the `notmuch` call all the time. Can I avoid this? :thinking:
