### ISSUE TITLE
Segmentation fault when using multiple mutt instances and notmuch

### ISSUE THREAD

**Issue by RichiH** [neomutt/neomutt#157]
I sadly can not reproduce it, but I wanted to at least create a paper trail in case someone else sees similar.

Using mutt 1.7.0-5 on Debian, I had three instances of mutt open and jumped between them, searching for various things with the F8 keybinding. I hit F8 in one instance and got an instant segfault. Restarted it and all was well. Some time later, I wanted to search in a different instance, hit F8, segfault. Tried it with the last one and once again, a segfault.

The three restarted instances are working just fine.

I suspect that the notmuch integration synced some state between the three initial instances and that this led to the segfault.

I am aware of how shitty this bug report is, so feel free to close it. Sorry for not being able to be of more use :(

**Comment by P-EB** [comment]
Oh no, let's not close it!

I suggest, if you agree that you compile with -g flag mutt, and you run it in a gdb instance. Next segfault would allow to traceback.

You also can try to dig into coredump directly, as you prefer. :)

**Comment by flatcap** [comment]
OK, thanks for the report.  It's better you raise the issue, than not.

Debian 1.7.0-5 doesn't have the latest changes I made to the pager (in 2016-09-16).
Until everyone has those fixes, I'll treat any crash reports with caution.

**Comment by aradici** [comment]
@RichiH please update to 1.7.0-6, that includes NeoMutt 2016-09-16, it will get to testing today

**Comment by RichiH** [comment]
Will do.

Richard

Sent by mobile; excuse my brevity.
