### ISSUE TITLE
Encapsulate gmtime() and localtime()

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1571]
There are over 20 places where NeoMutt uses these time functions.
It makes sense to wrap these calls in a function and simplify the callers.
  
Some typical patterns are:
  
- `time()` -\> `time_t` \-> `localtime()` -> `struct tm`
  The current time is split into (year, month, day, etc)

- `time_t` -\> `localtime()` -\> `struct tm` -\> `strftime()`
  An existing timestamp is formatted into a string

- `time_t` -\> `gmtime()` -\> `struct tm`
  An existing timestamp is split into (year, month, day, etc)

The second part of this task is to convert to using the thread-safe versions of these two functions:
- `gmtime()` -\> `gmtime_r()`
- `localtime()` -\> `localtime_r()`

**Comment by nocriw** [comment]
Sorry for the delay, it's been a busy week. :sleeping: 

First WIP at 200bdf4 & 0ed5c1e. I used your initial commit 7706112, wrapped the calls into functions and changed it over the code.

Do you want specific functions for the common patterns? 

For example: 
- `struct tm mutt_date_get_current_tm(void)` 
for `time()` -> `time_t` -> `localtime()` -> `struct tm`
- `char *mutt_date_format_time(const time_t *t, char *format)` 
for `time_t` -> `localtime()` -> `struct tm` -> `strftime()`

Or is it ok like this?

**Comment by flatcap** [comment]
> Sorry for the delay, it's been a busy week

No worries

> Do you want specific functions for the common patterns? 

Yes, I think so.

As you've seen in my notes, there's lots of overlap.
This gives me an idea of what the final code might look like.

To get there, I tend to create lots of functions and cut'n'paste a lot.
I'll keep going until I can't simplify the callers any more.
Afterwards, I'll look for common code and try to refactor.

> feedback is much appreciated!

In your functions you pass a pointer to a `time_t`.
That's just a number so we might as well pass by value.

By dropping the `const` we can still pass a pointer to `localtime_r()` and `gmtime_r()`.

```c
struct tm mutt_date_localtime_r(time_t time);
struct tm mutt_date_gmtime_r(time_t time);
```

I've create a branch [devel/time2] that contains your work, but rebased on top of the recent changes to `master`.

```sh
# To update your branch
git fetch origin
git reset --hard origin/devel/time2
```

Any problems, just ask.

**Comment by ghikio** [comment]
Thanks for the general feedback and updating the branch with master flatcap, learning a bit more everyday :)

fb51050 introduces helpers for the common patterns, let me know if anything can be done better.

**Comment by gahr** [comment]
I would get rid of the `_r` suffixes, they don't convey any additional information, as the function returns by value. I suggest

```
mutt_date_gmtime_r      -> mutt_date_gmtime
mutt_date_localtime_r   -> mutt_date_localtime
mutt_date_get_localtime -> mutt_date_localtime_now
```

**Comment by ghikio** [comment]
Thanks @gahr I'll change that. :) I always have a hard time finding good names.

**Comment by ghikio** [comment]
Updated in b9d0f53 & d7764cc

**Comment by flatcap** [comment]
> I always have a hard time finding good names

There's an old saying:

There are 2 hard problems in computer science:
- cache invalidation
- naming things
- off-by-1 errors

**Comment by flatcap** [comment]
This is a list of the number of callers of each of your new functions:

-  9 `mutt_date_localtime()`
-  6 `mutt_date_localtime_now()`
- 10 `mutt_date_localtime_format()`
-  5 `mutt_date_gmtime()`

I'm wondering if we need `mutt_date_localtime_now()`.
Can we just pass a `time_t` of `0` to `mutt_date_localtime()` and have it look up the current time.  Better still, define a "now" constant rather than use `0`.

One of the 5 callers to `mutt_date_gmtime()` also looks up the current time, so it could be converted too.

**Comment by ghikio** [comment]
Updated d3fc129 , thanks for the feedback :)
