### ISSUE TITLE
[DEVEL] We'd like your opinion on these questions

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1572]
Each comment contains a question and offers a suggestion.

You can express your opinion simply by :+1: or :-1: using the 'reaction' button (top right of the comment).

If you have a better idea, please leave a comment.

Thanks.

<sub>This opinion poll is an experiment to encourage feedback.</sub>

**Comment by flatcap** [comment]
## Rename string constants

The code defines constants for allocating some 'standard' sized buffers:

```c
#define SHORT_STRING  128
#define STRING        256
#define LONG_STRING  1024
#define HUGE_STRING  8192
```

But, these names are fairly meaningless (you find yourself looking up the length each time).

### Suggestion 1

Rename them to:

```c
#define STR128    128
#define STR256    256
#define STR1024  1024
#define STR8192  8192
```

### Suggestion 2

Define some constants for specific cases:

```c
#define STR_MAILBOX 4096 // Sufficient for a mailbox path
#define STR_COMMAND 8192 // Sufficient for a command line
```

**Comment by flatcap** [comment]
## Create a **type** for bitfields/flags

Many `struct`s have members that represent a bitfield/flags,
but it's often hard to know that from the name.

```c
struct Mailbox
{
  // ...
  unsigned int rights;
  // ...
};

struct ImapAccountData
{
  // ...
  unsigned int capabilities;
  // ...
};
```

The standard header `<stdint.h>` defines these fixed-size unsigned integer types:

- uint8_t
- uint16_t
- uint32_t

### Suggestion

Define types for bitfield/flags:

```c
typedef uint8_t  FLAGS8;
typedef uint16_t FLAGS16;
typedef uint32_t FLAGS32;
```

**Comment by flatcap** [comment]
## Rename **Config** global variables

There are over 400 config variables in NeoMutt, each of them backed by a global variable in the code.
The global variable's name is the "MixedCase" transform of the "snake_case" config variable.

But... Many of the config variables have short names which make them hard to seach for, e.g.

- Copy
- From
- Help
- Move
- Sort

### Suggestion

Add a prefix to all **Config** global variables, e.g.

- C_Copy
- C_From
- C_Help
- C_Move
- C_Sort

**Comment by flatcap** [comment]
## Stop offering to create `~/Mail`?

This is aimed squarely at developers.
How often have you run NeoMutt only to be prompted to create a directory that you don't want?

### Suggestion

Don't offer to create `~/Mail` on startup

**Comment by gahr** [comment]
> ## Rename string constants
> The code defines constants for allocating some 'standard' sized buffers:
> 
> ```c
> #define SHORT_STRING  128
> #define STRING        256
> #define LONG_STRING  1024
> #define HUGE_STRING  8192
> ```
> 
> But, these names are fairly meaningless (you find yourself looking up the length each time).

I agree those are useless.

> ### Suggestion 1
> Rename them to:
> 
> ```c
> #define STR128    128
> #define STR256    256
> #define STR1024  1024
> #define STR8192  8192
> ```

I don't like this. STR8192 isn't any more useful than plain 8192.

> ### Suggestion 2
> Define some constants for specific cases:
> 
> ```c
> #define STR_MAILBOX 4096 // Sufficient for a mailbox path
> #define STR_COMMAND 8192 // Sufficient for a command line
> ```

Shaky. As a developer implementing a particular piece of code, I probably have a better clue how big a string I need for a particular call. I'd rather just get rid of all defines and use plain numbers in the code.

Of course, we should carry around the actual buffer sizes, not rely on any buffer being at least `STRING` bytes long.

**Comment by flatcap** [comment]
> STR8192 isn't any more useful than plain 8192.

Yeah, true.

> > #define STR_MAILBOX 4096 // Sufficient for a mailbox path
> > #define STR_COMMAND 8192 // Sufficient for a command line

> Shaky.

I still think this is useful, though.

Ages back, I trawled the code tracing all the code paths that had a Mailbox path.
The Mailbox uses `PATH_MAX` (4096), but some of the code was using buffers of `LONG_STRING` (1024), possibly leading to truncation (e.g. Notmuch queries).

**Comment by nobrowser** [comment]
Re: String constants (better title would be "Buffer length constants").  I am with gahr - I do not like either suggestion.  If we *must* keep using fixed size buffers, `PATH_MAX` and the like is the way to go.  But really we should switch to allocated buffers, and start using the talloc library - the greatest thing since C, LOL.  Of course I know this job would dwarf anything @flatcap has yet done, bless his heart.

Re: other points, I am OK with the suggestions, of course they will make merging from mutt even harder than it is now.

**Comment by flatcap** [comment]
> If we _must_ keep using fixed size buffers

For now, yes.
I'm working to reduce the amount of places where the folder path gets passed around and manipulated.  Once that's done, we should be able to have a dynamically allocated string of the right size.

> start using the talloc library

That _is_ nice.  And I notice that it's already a dependency of `libnotmuch.so`.
No promises.
