### ISSUE TITLE
segmentation fault on sending message

### ISSUE THREAD

**Issue by Witcher01** [neomutt/neomutt#1573]
## Expected Behaviour

Sending a message.

## Actual Behaviour

Segmentation fault.

Error Message: `SSL failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number zsh: segmentation fault (core dumped)  neomutt -F /tmp/neomutt`

## Steps to Reproduce

Send a message (presumably over SSL).

## How often does this happen?

- Always. I have tried sending mails with every E-Mail account I have and always get the same behaviour.

## When did it start to happen?

Seemingly random. Neither when I upgraded nor when I changed my config.

## NeoMutt Version

```
NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.20.10-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.35 (compiled with 1.35)
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.1 20181127 (GCC)

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn=/usr --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo
  -gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color
  +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

- Encryption and message signing still works before sending the message. It seems that it's trying to connect to the server over SMTP with SSL but it can't.
- The message is not sent but is copied to the "SENT" folder and accessible through there.
- My E-Mails are stored remotely and I access them by using IMAP.
- First noticed while running neomutt in tmux, but it happens too when I'm not using tmux.
- I don't use multiple instances of neomutt at once.

Thank you for your help!

**Comment by gahr** [comment]
Are you sure your smtp host is set up correctly? Maybe your host doesn't accept connections over ssl, and it uses StartTLS instead?

You should check `smtp_url` (I suppose it starts with `smtps://`), the port it uses (if any), `ssl_force_tls`, and `ssl_starttls`.

**Comment by Witcher01** [comment]
It _should_ be set up correctly, since it only started segfaulting after an update, though I don't remember which update this started happening exactly.

My E-Mail provider does support connections over SSL, as seen [here](https://posteo.de/en/help/how-do-i-set-up-posteo-in-an-email-client-pop3-imap-and-smtp).

**Comment by gahr** [comment]
@Witcher01 can you please post the values for the config settings I've mentioned (remove any username / passwords and insert placeholders instead). As I conjectured, I can reproduce the problem when I try to connect via SSL to a non-SSL endpoint, as in `set smtp_url=smtps://username@posteo.de:587`. Please double check your settings. According to the page you linked, posteo accepts SSL connections to port 465, so `set smtp_url=smtps://username@posteo.de:587` should work fine.

**Comment by Witcher01** [comment]
So I have just checked if sending messages still does not work and it seems to work now. I have not changed any settings whatsoever, which makes me believe that perhaps this was an issue on the side of Posteo.

Nonetheless, I'll post my config values that matter for this issue:
```
set smtp_url = smtps://$my_user@posteo.net:465
set ssl_force_tls = yes
``` 

I'm assuming there are no further problems and I can close this issue. Thank you for your help.
