### ISSUE TITLE
1e0091a8b923db07e4a broke reverse_name / alternates

### ISSUE THREAD

**Issue by anarazel** [neomutt/neomutt#1581]
Hi,

## Expected Behaviour

In a configuration with multiple email addresses I want to use the recipients email address (from alternates) to be the From in a reply. For that purpose I have (much simplified)

```
set from=andres@anarazel.de
set use_from=yes
set reverse_name=yes
alternates andres.freund@enterprisedb.com andres@anarazel.de
```
which used to work.

## Actual Behaviour

Starting with 1e0091a8b923db07e4a I always get the configured address. Commit identified via bisection.

## Steps to Reproduce

Put config equivalent to above in config file, use with -F, hit reply, and notice that the sender will always be the `set from` one, rather than one of the alternates, even if either in To or CC.

## How often does this happen?

- Always

## When did it start to happen?

- 1e0091a8b923db07e4a

Thanks for maintaining neomutt,

Andres

**Comment by anarazel** [comment]
Hm. So, I'm not sure I quite understand that refactoring already. But the direct cause of the issue appears to be this changed hunk:
```diff
 int ci_send_message(int flags, struct Email *msg, const char *tempfile,
-                    struct Context *ctx, struct Email *cur)
+                    struct Context *ctx, struct EmailList *el)
 {
   char buf[LONG_STRING];
   char fcc[PATH_MAX] = ""; /* where to copy this message */
@@ -1767,6 +1755,13 @@ int ci_send_message(int flags, struct Email *msg, const char *tempfile,
   char *err = NULL;
   char *ctype = NULL;
   char *finalpath = NULL;
+  struct EmailNode *en = NULL;
+  struct Email *cur = NULL;
+
+  if (el)
+    en = STAILQ_FIRST(el);
+  if (en)
+    cur = STAILQ_NEXT(en, entries) ? en->email : NULL;
```

`cur` now is only set if `el` has *more* than one entry. But the reply code paths only specify one message:

```diff
       case OP_GROUP_REPLY:
-
+      {
         CHECK_MSGCOUNT;
         CHECK_VISIBLE;
         CHECK_ATTACH;
+        struct EmailList el = STAILQ_HEAD_INITIALIZER(el);
+        el_add_tagged(&el, Context, CUR_EMAIL, tag);
         if (PgpAutoDecode && (tag || !(CUR_EMAIL->security & PGP_TRADITIONAL_CHECKED)))
         {
-          struct EmailList el = STAILQ_HEAD_INITIALIZER(el);
-          el_add_tagged(&el, Context, CUR_EMAIL, tag);
           mutt_check_traditional_pgp(&el, &menu->redraw);
-          el_free(&el);
         }
-        ci_send_message(SEND_REPLY | SEND_GROUP_REPLY, NULL, NULL, Context,
-                        tag ? NULL : CUR_EMAIL);
+        ci_send_message(SEND_REPLY | SEND_GROUP_REPLY, NULL, NULL, Context, &el);
+        el_free(&el);
         menu->redraw = REDRAW_FULL;
         break;
+      }
```

`el_add_tagged()` here just adds `CUR_EMAIL` to the list. Those two things combined mean that previously `cur` (as an argument to `ci_send_message()` was set), and after this change it is not, because for that `el` would need to have two members.

If I just change
```C
    cur = STAILQ_NEXT(en, entries) ? en->email : NULL;
```
to
```C
    cur = STAILQ_NEXT(en, entries) ? NULL : en->email;
```

[group] reply works again for me. Could it be that the check was just inverted, and the intention is just to *not* infer sender via `ReverseName` when the list has *more* than one element? I think that'd be somewhat consistent with the behaviour from before `1e0091a`.

I'll note that just inverting that test would *not* yield behaviour compatible with the previous code. Before when doing a tagged reply one would never get the `ReverseName` etc behaviour, because `cur` would always be NULL (due to `tag ? NULL : CUR_EMAIL`), but afterwards one does get the `ReverseName` behaviour when there's exactly one tagged message.  I suspect that wasn't an intentional behaviour change in a refactoring @flatcap?

**Comment by flatcap** [comment]
Thanks for the analysis, @anarazel.  You're spot on.

A lot of the old code passed `Email *cur` for one message, and relied on using the `Context` to find a list of tagged messages.  That commit (and others), unified the behaviour by passing `EmailList *el` to work with.

> ```c
> cur = STAILQ_NEXT(en, entries) ? NULL : en->email;
> ```

Yep.  That was a quick hack to avoid refactoring a lot of `ci_send_message()`

> just inverting that test would _not_ yield behaviour compatible with the previous code

Yes, the behaviour change was unintentional.
