### ISSUE TITLE
change-label-then-hide and change-tag-then-hide not working

### ISSUE THREAD

**Issue by xanderio** [neomutt/neomutt#1584]
## Expected Behaviour

When changing the notmuch tags on a mail with `change-label-then-hide` or `change-tag-then-hide` the tags shoud get change and the the mail get hidden.

## Actual Behaviour

The tags get change but the mail dose not get hidden.

## Steps to Reproduce

Use `change-tag-then-hide` or `change-label-then-hide` on a piece of mail

## How often does this happen?

- Always

## When did it start to happen?

Since i started to use neomutt.

## NeoMutt Version

```
NeoMutt 20180512-35-4ea3e1
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: FreeBSD 12.0-STABLE (amd64)
ncurses: ncurses 6.1.20190112 (compiled with 6.1.20180728)
libiconv: 1.14
libidn: 1.34 (compiled with 1.34)

Compiler:
FreeBSD clang version 6.0.1 (tags/RELEASE_601/final 335540) (based on LLVM 6.0.1)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin

Configure options: --with-ui=ncurses --notmuch --ssl --gss --sasl --gpgme --lua

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -I/usr/local/include/lua52 -DNCURSES_WIDECHAR -I/usr/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo
  -gnutls +gpgme +gss -hcache -homespool +idn -locales_hack +lua +meta
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color
  +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"
```

## Extra Info

* Operating System and its version
FreeBSD 12.0 STABLE
* Were you using multiple copies of NeoMutt at once?
no
* Were you using 'screen' or 'tmux'?
yes
* Is your email local (maildir) or remote (IMAP)?
local maildir with notmuch mailboxes

**Comment by Austin-Ray** [comment]
Are you using `modify-labels-then-hide` instead of `change-label-then-hide`/`change-tag-then-hide`? The `change-*` commands are not valid in `master`, tag `neomutt-20180512`, or 4ea3e12 (commit of your Neomutt build.)

If you are, please continue reading. Otherwise, can you post the `notmuch`-related portions of your `.neomuttrc` file?

Per the documentation[[0]](https://neomutt.org/feature/custom-tags#4-%C2%A0functions), a `<sync-mailbox>` call is necessary before the modified message will disappear from the UI. By default, `<sync-mailbox>` is bound to `$`.

[0] https://neomutt.org/feature/custom-tags#4-%C2%A0functions

**Comment by xanderio** [comment]
On Tue, 05. Mar 13:30, Austin Ray wrote:
>Are you using modify-labels-then-hide instead of change-label-then-hide/
>change-tag-then-hide? The change-* commands are not valid in master, tag
>neomutt-20180512, or 4ea3e12 (commit of your Neomutt build.)
That was a mistake on my part. I was in fact using 
modify-label-then-hide.

>Per the documentation[0], a <sync-mailbox> call is necessary before the
>modified message will disappear from the UI. By default, <sync-mailbox> is
>bound to $.
Well then everything is working as documented.
>
>[0] https://neomutt.org/feature/custom-tags#4-%C2%A0functions
