### ISSUE TITLE
Virtual-Mailbox with Notmuch and sub-directories not working

### ISSUE THREAD

**Issue by weilbith** [neomutt/neomutt#1588]
I'm about to use `virtual-mailboxes`. Generate a virtual folder by a query is working, since I set the `nm_default_uri` correct. My problem is now that I get the error that it tries to open a _Notmuch_ database that does not exist and I don't know how to avoid. 
The problem is that I'm using multiple accounts with their own configuration files, which I source with a macro (like `macro index <f2> "<sync-mailbox><refresh><enter-command>source $my_acc_private<enter><change-folder>!<enter>"`). In such configuration file (here stored in `$my_acc_private`) I define the `virtual-mailboxes` next to the "normal" `mailboxes`.
So my mail directory looks like this:
```
~/Mail
   |--  .notmuch
   |--  private
   |--  work
   L ...
```

The `$my_acc_private` does also set `folder` to `~/Mail/private` and use the `mbox_type = Maildir`.
So my `nm_default_uri` is set to `notmuch:///home/me/Mail`. Query the database form here works. If I now want to change to a defined `virtual-mailbox` like `notmuch://?query=folder:private and github`, I get the following error message: `Error opening database at /home/me/Mail/private//.notmuch: No such file or directory?`
Of cause this database does not exist. For me it seems like the default URI is extended by the `folder` in same manner. But I like to have a single _Notmuch_ database in the `~/Mail` base directory. So how can I make sure this is working and the correct one is used?

**Comment by weilbith** [comment]
Not sure, but could it be, that I can't tag mails manually (`modify-tags`) does not work for the same reason? Error message is `Folder doesn't support tagging, aborting.`.

**Comment by Austin-Ray** [comment]
I am able to reproduce the issue on `master`, but not on the latest release (`neomutt-20180716`).

What version of `neomutt` are you using, @weilbith?

In the meantime, including `set nm_default_uri=/path/to/mail` as the last line of the sourced file fixes this issue. It'll get `neomutt` and `notmuch` into usable shape until a patch is deployed.

**Comment by weilbith** [comment]
Thanks for your quick response.

I'm using `NeoMutt 20180716` by the _ArchLinux_ package.
But your hint was already enough: the problem was that I sourced my primary account first, before setting the `nm_default_uri`. Switch them in my `muttrc` solved the problem.
Thank you very much for your help!

**Comment by weilbith** [comment]
@Austin-Ray

Anyways, could you give me a quick hint or reference how to solve the problem about `Folder doesn't support tagging, aborting...`?

**Comment by weilbith** [comment]
Okay, seems like tags are visible in `virtual-mailboxes` only. So I must use `set virtual_spoolfile`.
