### ISSUE TITLE
H M L support f

### ISSUE THREAD

**Issue by mightymiff** [neomutt/neomutt#1589]
The [Vi Keys](https://neomutt.org/contrib/vim-keys) page of the guide lists: `Rolling cursors: H, M, L, ^E, ^Y, ^F, ^B, ^D, ^U and of course gg, G`

I am presently concerned with mimicking H, M, L vim-like behavior in neomutt.  M appears to work by default (without being explicitly bound), but H and L do not and are not listed anywhere in the vim-keys.rc file.

How to implement H and L commands to select the first and last entry from the message viewport?

**Comment by flatcap** [comment]
Hi @mightymiff 

The functions you're looking for are already built-in to (Neo)Mutt.
- <kbd>H</kbd> `<top-page>`
- <kbd>M</kbd> `<middle-page>`
- <kbd>L</kbd> `<bottom-page>`

Of course, they can be overridden by other config.
This will restore them:
```
bind index H top-page
bind index M middle-page
bind index L bottom-page
```

**Note**: If config variable `$menu_context` isn't zero, then the menu won't let you select the bottom entry on the screen.

**Comment by mightymiff** [comment]
Exactly what I was looking for @flatcap.  Thank you kindly!  My defaults must have gotten overridden somehow.  All better now.
