### ISSUE TITLE
Repaint problem with $pager_index_lines

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#159]
NeoMutt: 2016-09-16 (doesn't happen in 2016-09-10)
Occurs: always
Steps to reproduce:
- `set pager_index_lines = 10`
- open email
- `set pager_index_lines = 0`

Result:
status bar isn't removed

Expected result:
status bar disappears

**Comment by P-EB** [comment]
What does a git bissect give?

**Comment by flatcap** [comment]
I hadn't got that far.  It was late and I thought to note it down, before I forgot.
(and in case anyone was free to take a look)

**Comment by christopher-john-czettel** [comment]
On 24.09.2016 - 05:09:43, Richard Russon wrote:
> I hadn't got that far.  It was late and I thought to note it down, before I forgot.
> (and in case anyone was free to take a look)

Hi Richard!

If you'd give me a pointer how/where you wanted to implement this, I'd
be willing to give it a shot.

Chris

**Comment by flatcap** [comment]
Thanks!

To start, get the compile the latest source from git.
Check that you can reproduce the bug.

A simple way to home-in on the bug is "git bisect".  neomutt-20160910 worked correctly (check that, too).  This should narrow it down to one commit.

From here, hopefully it will be obvious, what went wrong.
(but Mutt's a complicated beast :-)

I'm in our IRC channel: #neomutt on freenode.net if you want to chat and ask questions.

Cheers, Rich / FlatCap

**Comment by christopher-john-czettel** [comment]
I'll get to it later this afternoon. See you in IRC.

**Comment by christopher-john-czettel** [comment]
Just bisected everything between the release tags, assuming "make clean" does it's job, this is the source:

6b4c4caa801ffe2eefdb3d14273c5f640ea52927 is the first bad commit
commit 6b4c4caa801ffe2eefdb3d14273c5f640ea52927
Author: Richard Russon <rich@flatcap.org>
Date:   Mon Sep 12 22:47:49 2016 +0100

    fix crash when exiting the pager
    
    Make sure we've always got a menu pointer.
    This is a fix for commit:
        "check for new mail while in pager when idle"
    
    Fixes: #143

:100644 100644 6e7f29c3c794cd8b5631c8cea5014b423f563f64 401891885a17b9a7854be7226e640d9a176d46fb M      pager.c
