### ISSUE TITLE
Files included (-i flag) from command line are deleted if used in multipart alternatives

### ISSUE THREAD

**Issue by frabjous** [neomutt/neomutt#1590]
Suppose I have a file `myfile.md` reading something like:
````
hello *world*
````
And then I run from the command line:
`neomutt -E -i "myfile.md" -s "My subject" -- someone@somewhere`

This will start neomutt with myfile.md as the message, which I can then edit. If I simply make my edits, then send as is, then all is well. My edits are even saved to `myfile.md`, as the description for the -E flag in the [command line reference](https://neomutt.org/guide/reference.html) would suggest.

However, suppose instead that after saving my edits to `myfile.md`, from the compose menu, I follow the instructions in the [Mime Support part for guide](https://neomutt.org/guide/mimesupport.html#alternative-order) for converting myfile.md to HTML using e.g., pandoc (as in the example in the guide), and adding the html file as an attachment, and then arranging the email to be sent as a multipart/alternative email, following the instructions in the guide.

In that case, when the email is sent, `myfile.md` is deleted! This was an included file attached from the command line. Under no circumstances should neomutt delete that file.

My `neomutt -v`:

````
NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.20.13-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.1.1 (compiled with 2.1.1)
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.1 20181127 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
````

**Comment by flatcap** [comment]
Thanks for the bug report, @frabjous.
There's a workaround for now, which is to <kbd>u</kbd> (`\<toggle-unlink\>`) on `myfile.md` before grouping the alternatives.  A dash `-` (on the left) means it will be deleted.

I notice that the `-i` file starts with that dash, but it's only deleted if you group the attachments.

**Comment by frabjous** [comment]
Thanks a lot! I can confirm that the workaround works. Still, I hope you can implement something to make the behavior more consistent/transparent. All your work is appreicated!

**Comment by flatcap** [comment]
> I hope you can implement something to make the behavior more consistent/transparent

I'll leave the issue open until we do.

> All your work is appreciated!

You're welcome.

**Comment by dcpurton** [comment]
I had a bit of a look at this.

In this case the attachment not deleted is the one connected directly to email→body.

When you group, the file passed on the commandline is no longer connected directly to email→body, so it's deleted.

But if you put some other attachment in the first place, that one will be left on disk, even if it should be deleted.

It's probably better to set the unlink flag to false for the actual attachment and still unlink email→body if it's unlink flag is true.

The issues are in `compose/functions.c` and that terrifying `mutt_send_message()` function in `send/send.c`…
