### ISSUE TITLE
Implement unbind command

### ISSUE THREAD

**Issue by jindraj** [neomutt/neomutt#1591]
## What would you like to be able to do?
PR: #1599
Create unbind command similar to original [unbind patch](https://web.archive.org/web/20160313160541if_/http://home.uchicago.edu:80/~dgc/mutt/#unbind
) by David Champion.

Could be useful to:
1. **new users** won't be afraid too much of destructing their messages.
2. **advanced users** could use it for multiple rcfiles each with different bindings.

## What needs to change in NeoMutt?
  * create new command, parse function and some logic about bindings
  * parse_keymap (f.e.: reflect unbind command name in error messages)

## Have you tried any alternative methods?
N/A
## Additional Info
- Shoud `unbind` affect macros as well or is it better to implement `unmacro` command?

> 14:37:05          flatcap | As bind and macro are separate, I think unbind and unmacro should be too.

### binding which should be kept:
 - `:` command prompt
 - `q` quitting neomutt 
 … but neomutt won't be usable. missing `m` compose new message,`y` send message  and many other core keys. unbinding all sound cool with complete set of different bindings.

### Syntax
`unbind <menu-name[,…]|*> [<key_sequence>]`

### Examples
- unbind `@` from one, multiple or all menu-names
`unbind index @`
`unbind index,pager @`
`unbind * @`
- unbind all bindings from one, multiple or all menu-names
`unbind index`
`unbind index,pager`
`unbind *`

**Comment by jindraj** [comment]
first steps here: b0c2a7ee30c35b4e7ec1f3c6ebb257300131a021

## what's new
- new command unbind
- `bool bind` to `char *cmd` in `parse_keymap` function  to reflect command name in error messages
- keeps `q` and `:` bound
Keep them bound only when `unbind <menu-name>` (unbinding all key_sequences)
But unbind them when `unbind <menu-name> q` or `unbind <menu-name> :`

## next
- over all keys from keymap
- iterate over all menus when `*` is specified as `menu-name`

**Comment by jindraj** [comment]
It seems that since the syntax of both unbind and unmacro commands is the same It should be sufficient to have only one parse function.

**Comment by flatcap** [comment]
OK, now we've got the syntax, here's a rough plan of how the code should look:

- extract first param (either "index,pager" or "*")
- is it "*"?
  set all_menus = true
- else parse menus (this might fail)
- extract next param (this is optional)
  - is it "*"
    set all_keys = true
  - else key = string
  - is all_menus set AND (key = "q" or ":")
    error
- are there any more args?
  error too many

Now we can perform the work

- is all_menus set?
  loop from 0 to MENU_MAX
    unbind(menu, key)
- else
  loop though 'menu' array
    unbind(menu, key)

We want a function to parse the menus, but NOT extract the key (it's optional).
Cut'n'paste parse_keymap() and strip out the key code.

The two loops that we need work completely differently, so we need an unbind() function to do the actual work.

**Comment by jindraj** [comment]
Writing the parse function from scratch helped me to understand better what's going on.

I have the first part almost done, only parsing menus is missing. From the second part I already have the loop over all_menus with unbinding working. But missing loop over the menu array - because missing parse menu.

Shouldn't be there some block of code with loop over all bindings to unbind when `all_keys==true`?

I'll publish the code later. I'll try to solve the all_menus first. Otherwise there's not much to publish.

**Comment by jindraj** [comment]
km_unbind_all() added in 29d09d2344654d72da0f3c4c36880fe9d7e8b2c9 is pretty almost the same as in dgc's patch. Thanks @flatcap for the hints what has changed since 2002.

Now all cases should be covered:
- all_menus && all_keys
- all_menus && specific key
- specific_menus && all_keys
- specific_menus && specific_key

I kept following keys after km_unbind_all() return/enter/:/?/q for testing purposes. Final list of keys to be kept will be probably changed.
