### ISSUE TITLE
Debian updates invalidate hcache

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#160]
When upgrading Debian versions, sometimes the hcache is invalidated.
The problem seems to occur when the version string changes.

| Debian Version | Version String              |
|:---------------|:----------------------------|
| 1.6.2-3        | Mutt 1.6.2-neo (2016-08-21) |
| 1.7.0-1        | NeoMutt (1.7.0)             |
| 1.7.0-2        | NeoMutt (1.7.0)             |
| 1.7.0-3        | NeoMutt 20160910 (1.7.0)    |
| 1.7.0-4        | NeoMutt 20160910 (1.7.0)    |
| 1.7.0-5        | NeoMutt 20160910 (1.7.0)    |

Create a local maildir mailbox with a lot of emails, e.g. [maildir-100000.tar.xz](https://flatcap.org/mutt/maildir-100000.tar.xz) (3.9MiB)
Enable the hcache, and clear it.

If I run each of the versions of NeoMutt, the first run takes ~8 seconds to fill the cache.  The second run takes ~5 seconds.  This is repeatable.

Running different versions shows the problem:

| First Run | Second Run | Speed | Cache   |
|:----------|:-----------|:------|:--------|
| 1.6.2-3   | 1.7.0-1    | Slow  | Rebuilt |
| 1.7.0-1   | 1.7.0-2    | Fast  | Used    |
| 1.7.0-2   | 1.7.0-3    | Slow  | Rebuild |
| 1.7.0-3   | 1.7.0-4    | Fast  | Used    |
| 1.7.0-4   | 1.7.0-5    | Fast  | Used    |

Somewhere, the NeoMutt version is being used to generate the cache.

To generate the Debian builds, clone their repo:
`git clone https://anonscm.debian.org/git/pkg-mutt/mutt.git`
and run [build-debian.sh.txt](https://github.com/neomutt/neomutt/files/491644/build-debian.sh.txt)

**Comment by P-EB** [comment]
Here are some intel:

1.6.2-3
#define HCACHEVER 0x829b3aff
1.7.0-1
#define HCACHEVER 0x110bbb15
1.7.0-2
#define HCACHEVER 0x110bbb15
1.7.0-3
#define HCACHEVER 0x82e66286
1.7.0-4
#define HCACHEVER 0x82e66286
1.7.0-5
#define HCACHEVER 0x82e66286

HCACHEVER changed both times you met a rebuild.

**Comment by P-EB** [comment]
Ok, the version changes because the script that computes the md5sum takes into account some features that influence hcache.

Between 1.7.0-2 and 1.7.0-3, my reply-with-xorigto feature was added, and it adds a variable in ENVELOPE struct.

The same kind of thing happened between 1.6.2-3 and 1.7.0-1.

So far, there is nothing we should do.

**Comment by P-EB** [comment]
Adding an example to help people understanding.

```1.7.0-3
/* base version: 2
 * ADDRESS: char *personal; char *mailbox; int group; struct address_t *next; unsigned is_intl : 1; unsigned intl_checked : 1;
 * BUFFER: char *data; char *dptr; size_t dsize; int destroy;
 * LIST: char *data; struct list_t *next;
 * ENVELOPE: ADDRESS *return_path; ADDRESS *from; ADDRESS *to; ADDRESS *cc; ADDRESS *bcc; ADDRESS *sender; ADDRESS *reply_to; ADDRESS *mail_followup_to; ADDRESS *x_original_to; char *list_post; char *subject; char *real_subj; char *message_id; char *supersedes; char *date; char *x_label; char *organization; char *newsgroups; char *xref; char *followup_to; char *x_comment_to; BUFFER *spam; LIST *references; LIST *in_reply_to; LIST *userhdrs; LIST *labels; int kwtypes; unsigned int irt_changed : 1; unsigned int refs_changed : 1;
 * PARAMETER: char *attribute; char *value; struct parameter *next;
 * BODY: char *xtype; char *subtype; PARAMETER *parameter; char *description; char *form_name; long hdr_offset; off_t offset; off_t length; char *filename; char *d_filename; char *charset; CONTENT *content; struct body *next; struct body *parts; struct header *hdr; struct attachptr *aptr; signed short attach_count; time_t stamp; unsigned int type : 4; unsigned int encoding : 3; unsigned int disposition : 2; unsigned int use_disp : 1; unsigned int unlink : 1; unsigned int tagged : 1; unsigned int deleted : 1; unsigned int noconv : 1; unsigned int force_charset : 1; unsigned int is_signed_data : 1; unsigned int goodsig : 1; unsigned int warnsig : 1; unsigned int badsig : 1; unsigned int collapsed : 1; unsigned int attach_qualifies : 1;
 * HEADER: unsigned int security : 12; unsigned int mime : 1; unsigned int flagged : 1; unsigned int tagged : 1; unsigned int deleted : 1; unsigned int purge : 1; unsigned int quasi_deleted : 1; unsigned int changed : 1; unsigned int attach_del : 1; unsigned int old : 1; unsigned int read : 1; unsigned int expired : 1; unsigned int superseded : 1; unsigned int replied : 1; unsigned int subject_changed : 1; unsigned int threaded : 1; unsigned int display_subject : 1; unsigned int recip_valid : 1; unsigned int active : 1; unsigned int trash : 1; unsigned int label_changed : 1; unsigned int zhours : 5; unsigned int zminutes : 6; unsigned int zoccident : 1; unsigned int searched : 1; unsigned int matched : 1; unsigned int attach_valid : 1; unsigned int collapsed : 1; unsigned int limited : 1; size_t num_hidden; short recipient; int pair; time_t date_sent; time_t received; off_t offset; int lines; int index; int msgno; int virtual; int score; ENVELOPE *env; BODY *content; char *path; char *tree; THREAD *thread; short attach_total; int refno; void *data; void (*free_cb)(struct header *); char *maildir_flags;
 */
#define HCACHEVER 0x82e66286```
