### ISSUE TITLE
Speed up virtual mailboxes (caching?)

### ISSUE THREAD

**Issue by weilbith** [neomutt/neomutt#1600]
I switched to use primary `virtual-mailboxes`, cause they support custom tags to show at the index window and I can use more virtual folder/mailboxes without the need to create actual IMAP folders.
Unfortunately opening a mailbox (especially on the initial inbox) needs pretty long to load. Same on switching forth and back again. Header caching solved this problem for "normal" Mdirs. To be honest I'm not aware about the features in comparison of all the caching backends. Is it possible to use one to cache the virtual mailboxes as well? Not sure if this works from design.

**Comment by Austin-Ray** [comment]
At the moment, there is no caching for `virtual-mailboxes` within the `notmuch` subsystem. I'll have to investigate further to determine the feasibility of adding it, but thank you for bringing up the idea! It would certainly help with large mailboxes (my archive takes some time to open.)

**Comment by weilbith** [comment]
Hmm okay. So it is a possible future feature. Do we close this issue then? (not sure how your workflow is for such such)

**Comment by flatcap** [comment]
> So it is a possible future feature

Yes.  It's certainly desirable, but I don't know how we can implement it.  Yet.
Ideally, the Notmuch backend should piggy-back on top of the Maildir backend.
That sort of sharing will require a bit of thought.

> Do we close this issue then?

I've added the idea to the [Big List](https://github.com/neomutt/flatcap-brain-dump).
I'll leave the issue open for now, while we're thinking.
If we can't think of a short-term solution it'll get put in the [Hard drawer](https://github.com/neomutt/neomutt/issues?q=label%3Adifficulty%3Ahard+is%3Aclosed).

**Comment by weilbith** [comment]
Okay, so how does the flow looks like?
I image it will call notmuch with the configured query and use its output. 
First point I don't know: do this output is enough already by using the correct constallation of [these parameter](https://www.mankier.com/1/notmuch-search) or do we have to go through each entry in the list and manually load the information?
In case it is the second point, it would be interesting to know where the information are now taken from. If it uses the `--output file` to read each header manually it is slow for sure. But maybe references to the header cache of the Maildir could be used. Not sure if this is in that case faster to filter this cache by the notmuch output.

**Comment by flatcap** [comment]
> how does the flow looks like?

1. user enters query
2. neomutt asks notmuch for matches
   - returns a list of paths
3. neomutt reads the headers of each file to create the index

Step three would be sped up by reading a pre-parsed header from the cache.

> I image it will call notmuch with the configured query and use its output.

Yes, but we're using libnotmuch, so we don't have to read files or parse output.

> is this output enough ...
> or do we have to go through each entry in the result list and manually read

The index contains a lot of info which notmuch can't provide.

**Comment by weilbith** [comment]
So the flow is this:
query -> notmuch response -> bunch of header information

In this case I could imagine a cache of this three parts into any database. The query is key and open a virtual mailbox first checks the database for an entry. If so it first loads the last retrieved header information directly to build the index. In parallel/afterwards it reruns the query and compares the response with the last stored result list. The diff of both could then used to update the header information partially (delete and or extend). Afterwards the index must be updated. No idea if this is incrementally possible.
So we would have a quick initial view plus reading only partially the header after the first time or even just remove cached information.

Again I have no idea how the common backends of NeoMutt are designed, but this would require a document based database I would say. You could also argue that are more lightweighted solution is valuable enough, since the number of virtual mailboxes should be not overreach a few dozen in maximum. So a hash function for queries to a unique identifier, plus two dedicated cache directories storing the notmuch response for the diff as well as the header information in files named by the identifier.
This would be pretty basic.
