### ISSUE TITLE
Enhance user experience when saving attachments

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#1603]
From IRC:

> Anyone got any suggestions on improving the user-experience for saving lots of attachments? At the moment, I view attachments, tag (lots), then `;s`, choose a directory, then I have to confirm every save. Is there a better way just to take all the ones I've tagged and save to directory in one go?

How about we change the logic as follows:

- ask for a directory to save the attachment, default to `attach_save_dir`
- for each attachment
  - ask for a filename only if the attachment doesn't have one
  - ask for a confirmation only if saving the attachment would overwrite an existing file
    - Y -> overwrite this one
    - N -> do not overwrite this one, but keep looping on the other attachments
    - A -> overwrite this one, remember the choice for the other attachments in the loop
    - C -> cancel, quit looping

**Comment by scottkosty** [comment]
All of the proposed features seem to be functions that a file browser is good at. Would it make sense to just outsource everything to a file browser? My personal workflow is to press `[a`, which runs [ripmime](https://github.com/inflex/ripMIME) and opens my file browser (which happens to be ranger). Not sure if others would be satisfied with such a workflow and outsourcing to a file browser, but just thought I would mention an alternative.

**Comment by demure** [comment]
> All of the proposed features seem to be functions that a file browser is good at. Would it make sense to just outsource everything to a file browser? My personal workflow is to press `[a`, which runs [ripmime](https://github.com/inflex/ripMIME) and opens my file browser (which happens to be ranger). Not sure if others would be satisfied with such a workflow and outsourcing to a file browser, but just thought I would mention an alternative.

If outsourcing ends up as the solution, I'd be interesting in neomutt doing a bit of the helping before piping to a filemanager. It looks like `ripmime` is pretty stale, an my googling only turns up a similarly old/obscure munpack/mpack as an alternative.

**Comment by dharrigan** [comment]
I think I was the originator of the discussion on IRC.

Personally, I wouldn't really like outsourcing the functionality of saving an attachment to another program (that I may or may not have installed, and I have to configure with the right incantations to get it to work correctly). I would be happy if I could specify a default save attachment a directory, tag all those attachments to save, execute a "save all" call, and use the logic as described above if there are duplicate filenames.

Yes please!

**Comment by demure** [comment]
#1733 doesn't seem to address a setting, such as the suggested `attach_save_dir`, for setting a default save location?

**Comment by flatcap** [comment]
> `attach_save_dir`

That was added back in November.

**Comment by demure** [comment]
Ah, maybe my current version is out of date then, I wasn't seeing it listed in my `man neomuttrc` or https://neomutt.org/man/neomuttrc 

Thanks.
