### ISSUE TITLE
Don't display certain empty headers using edit_headers

### ISSUE THREAD

**Issue by Steef435** [neomutt/neomutt#1621]
Hi,
## What would you like to be able to do?
I'd like to remove some empty headers from the compose mail generated by edit_headers. I use edit_headers in combination with auto_edit, so I would like e.g. From, To, Subject to show up, but Reply-To and Bcc I'd rather add myself if needed (maybe from the compose menu later).

## What needs to change in NeoMutt?
I think the easiest method is to make some changes in mutt_rfc822_write_header (but I'm new here, so I would like opinions on this!). There's already a separate mode for edit_headers, so there's just another config option needed to choose.

It would require a hefty refactor of the function in order to remove headers even if they're not empty, or to reorder them. But it's easy to just not print one if empty.

The first attempt I made was to introduce one new string setting taking a list of "ignored" headers. It worked, but it implied a lot of parsing overhead for little feature (at least my implementation with limited C knowledge). So I think it would be easier to just add some boolean configuration options: edit_headers_from, edit_headers_to, etc., with a default value to yes for display even if empty. Upside: simple. Downside: 6 new config settings (and more if NNTP included)

## Have you tried any alternative methods?
I'm new to (neo)mutt so I'm not sure if there is a smart way to do this. The only thing I've found so far is to script on the editor-side. Which is certainly doable but not pretty, in my opinion.

What do you think? Is this something you would support and in what form? (maybe there's an easier way to let this be configurable?). If it wasn't clear, I'm willing to write the code myself (in fact, I'm already on it), but I might need some style pointers since this is my first time here.

**Comment by flatcap** [comment]
Here's a non-code solution, if you're a (Neo)Vim user:
```vim
autocmd BufRead ~/.cache/mutt/neomutt-* 1,/^$/g/^\v(Reply-To|Bcc): *$/d
```

When opening a NeoMutt tmp file, delete `Reply-To:` or `Bcc:` lines that are empty.(You'll need to adjust the file location to match your `$tmpdir`)

I'll have a think about the code in the morning.

**Comment by Steef435** [comment]
Thank you for the suggestion! I do use nvim so I can script around it, but I still think it would be nice if neomutt would handle the preference (then again, if I'm the only one who wants this, I guess it's fine like this).

In any case, I suppose it's only worth considering after #1624.

**Comment by flatcap** [comment]
Hi @Steef435,

Thanks for offering to help with the feature, but...

I had a chat with the other developers and sorry we're not convinced this is all that useful.

- User has turned on `$edit_headers` as a convenience
  They can add/remove headers as they wish, but empty headers will automatically be removed

- There aren't _that_ many (empty) headers
  Not much of a problem unless you have a tiny terminal window (drop-down, or perhaps Braille)

- Editor workarounds exist
  - Delete
    ```
    autocmd BufRead ~/.cache/mutt/neomutt-* 1,/^$/g/^\v(Reply-To|Bcc): *$/d
    ```
  - Hide
    ```
    :syntax match hide_header "^\v(cc|bcc|reply-to): *$" containedin=mailHeaderKey
    :highlight hide_header guifg=#606060
    ```

---

> I think the easiest method is to make some changes in mutt_rfc822_write_header()

Yes.  That seems to be the right place.
It's called from quite a few places, so you'd have to be careful not to affect other parts of NeoMutt.

> ... new string setting taking a list of "ignored" headers

Yes, a blacklist.  There's already plenty of code to parse lists.
Another possibility might be a regex.

---

If you think of some killer reason for this feature, please let us know.
But, for now, I'm going to say, no thanks.

P.S. If you'd still like to help, there are some 'easy' issues (that come with help :-), e.g. #1626

**Comment by Steef435** [comment]
Thank you for the elaborate reply!

I've been eyeing some of the issues, but I want to get a bit more familiar with the program as a user first. I'll be back :)
