### ISSUE TITLE
[attribute] for color does not work

### ISSUE THREAD

**Issue by ryvnf** [neomutt/neomutt#1623]
I like to make my color schemes independent of the background/foreground color set, by using attributes like `reverse` and `bold`. So it doesn't rely on the foreground/background being specific colors.

## Expected Behaviour

When reading the [documentation for neomutt](https://neomutt.org/guide/configuration.html#color) I notice that this is possible to specify attributes for the `color` command.

I attempt to make the indicator line reversed using the following:

    color indicator reverse default default

## Actual Behaviour

When trying to do it I get the following error:

    Error in /home/***/.muttrc, line 12: reverse: no such color

**Comment by gahr** [comment]
What version are you running? `color indicator reverse default default` works fine here. Can you double check line 12 of your muttrc?

**Comment by ryvnf** [comment]
neomutt -v

Outputs:

    NeoMutt 20180716
    
    Default options:
      +attach_headers_color +compose_to_sender +compress +cond_date +debug
      +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
      +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
      +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
      +skip_quoted +smtp +status_color +timeout +tls_sni +trash 
    
    Compile options:
      +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo
      -gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta
      -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color
      +sun_attachment +typeahead

**Comment by gahr** [comment]
Support for color attributes was added just a couple of months ago:
https://github.com/neomutt/neomutt/commit/380913b99ead8f3ff557490bb349301774afbdc5
