### ISSUE TITLE
Help Browser - Modernise the directory traversal

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1627]
> The Help Browser is a new feature to bring online help to NeoMutt.
> The code is in the [devel/help](https://github.com/neomutt/neomutt/tree/devel/help) branch.
> 
> It adds a new config variable: `$help_doc_dir` which should point to a copy of the [`test-doc`](https://github.com/neomutt/test-doc) repo.
> Help can be activated by pressing <kbd>Alt-H</kbd>

Task:
- Replace the directory traversal with the `nftw()` function
  It's the modern replacement for the `readdir()` function.

There is some sample code in [this gist](https://gist.github.com/flatcap/f0ee75ee26b30a8cade75c37b55419b5)

**Comment by lukelane124** [comment]
Is the idea of the gist to illustrate how the *readdir* functionality works in the existing architecture?

**Comment by flatcap** [comment]
@lukelane124 
Hmm...
There are three source files in the gist.
I've just renamed the first one to `readdir.c` to be clearer.
The other two `nftw1.c` and `nftw2.c` demonstrate `nftw()` in action.

**Comment by flatcap** [comment]
@lukelane124 
Are you interested in helping?

**Comment by lukelane124** [comment]
@flatcap Yes, sorry for the delayed response I've had an extermely busy ~week~ sprint at work.
However it looks like @0x747972 has pulled the torch out of the ground and gone off to work.

**Comment by 0x747972** [comment]
Yeah, i'll try to work on this issue, as flatcap told me it would be a good issue for me...

**Comment by flatcap** [comment]
Argh!  Sorry, @lukelane124.  Please forgive my impatience.
Let me see what else I can find.

**Comment by lukelane124** [comment]
@flatcap That's no problem. I've actually picked up a new personal project to learn sqlite, so if nothing NEEDs fixing I've got something to keep my occupied. In other words, don't _invent_ something on my behalf, althought I'm sure someone would love to come along and find a new "beginner friendly" issue.

**Comment by flatcap** [comment]
Fixed in ca6a95c19
