### ISSUE TITLE
set pager_index_lines to 0 will cause the mailbox info line to be shown in pager

### ISSUE THREAD

**Issue by aradici** [neomutt/neomutt#163]
Reported in http://bugs.debian.org/838868

It seems that even if pager_index_lines is set to 0 and therefore the index is not shown while reading a mail from the pager, then the bottom line that it is usually shown at the index, it is shown as first line in the pager (the one with "NeoMutt" written on it, mail read, mail count etc).

I believe we need to make sure that if the index is not shown while reading a mail, then nothing related to the index is shown.

This seems to happen starting from 20160916

**Comment by christopher-john-czettel** [comment]
Might this be the bug as 	#159 (that was fixed yesterday)?

**Comment by aradici** [comment]
You are correct, let's resolve
