### ISSUE TITLE
Unknown variable: xlabel_delimiter

### ISSUE THREAD

**Issue by project-repo** [neomutt/neomutt#1633]
Hi,
I recently changed to neomutt from mutt after looking into the differences in the code quality and first off, I would like to give you a huge thanks for your awesome work!

One of the features I have started to use after switching is the X-Label support which I find very useful. While looking for ways to improve my setup I stumbled across [this](https://neomutt.org/feature/keywords) site, explaining the usage of keywords. However, after some research, I discovered that this feature actually no longer exits (At least the variable xlabel_delimiter doesn't).

In order to prevent users from being confused, as to why the settings described in that link are no longer viable, I suggest that this website be either removed, corrected or flagged as out of date.

Please correct me if I overlooked something obvious.
cheers,
project-repo

**Comment by flatcap** [comment]
Sorry for the slow reply, @project-repo.

`X-Label`s are still there, I just checked, but that webpage is obsolete (NeoMutt has rebuilt the label/tagging support).

- To set X-Labels, use `<edit-label>` (<kbd>Y</kbd> by default)
  This can be combined with tagging
- To display X-Labels in the index add `%Y` to `$index_format`
- To display X-Labels in the pager, use the config `unignore X-Label`

**Comment by project-repo** [comment]
Sorry for the even later reply @flatcap ;)

However, I still have a question about the labels.

I was reading through the documentation and somehow I can't find out how to set the delimiter for labels. This would be really practical for autocompletion in particular since right now I can only autocomplete the entire label string. How is it possible to set the label delimiter in neomutt?

Thanks for taking care of the obsolete documentation.

cheers,
project-repo

**Comment by flatcap** [comment]
Those labels are a bit limited.
I think it just stores exactly what you tell it, whether that's `red,blue` or `red blue`.

I've made a note to have a look at it, but it'll be low priority and will have to come after I've refactored the auto-completion code.

**Comment by project-repo** [comment]
OK, thanks
