### ISSUE TITLE
Search for messages from the same topic

### ISSUE THREAD

**Issue by bjesus** [neomutt/neomutt#1636]
Hello,
I recently switched to NeoMutt and loving it everyday a little more. I've started using Notmuch too and the it's great how fast the search is. I tried using threads but never got it to work like I wanted, and I found myself just using `vfolder-from-query`, then typing the subject of the message I'm reading, to get a list of all messages from the thread (they come up because they share the same subject line of course).

I was wondering if there was a way to automate it, meaning to assign a key (macro?) that will automatically create a vfolder with messages with the same topic / messages from the same thread.

Is this possible?

Thank you!

**Comment by gahr** [comment]
You can fake it by turning on threaded mode then issuing `limit-current-thread`. As an example, you could bind a couple of macros to switch to this limit-threaded mode (`tt` ) and back (`nn`):
```
macro index tt ":set sort=threads          <enter>:exec limit-current-thread <enter>"
macro index nn ":set sort=reverse-date     <enter>:exec limit .              <enter>"
```

**Comment by bjesus** [comment]
Thank you! but this doesn't really work for me - `tt` only shows me one message and not the whole thread, because usually I would have only one message from the thread in the `Inbox` folder, and the rest, older messages would be in the `Archive` folder. The search method works well for me because it searches across all folders. Is there a way to have `limit-current-thread` show messages from all folders?

**Comment by flatcap** [comment]
After some discussion on IRC, @jindraj came up with this:
```
macro index,pager ,e "<pipe-message>formail -X from:|awk -F'[<>]' '{print $2}'>/tmp/sender<enter>\ :set my_sender=\"`cat /tmp/sender`\"\nl~f \"$my_sender\"\n"
```
Noting: this should work. But you were talking about limiting by subject, so at header for formail and pattern for limit should be changed to `subject:` and `~s`

**Comment by flatcap** [comment]
My thought went to an enhancement -- fake variables representing the current email
`$THIS_EMAIL.from`, `$THIS_EMAIL.subject`, etc

It gets a bit trickier when fields have multiple entries.
Perhaps searching for `~f $THIS_EMAIL.cc` could be expanded to: `(~f andy | ~f bert | ~f charlie)`

**Comment by gahr** [comment]
> Is there a way to have limit-current-thread show messages from all folders?

No - neomutt works per-(virtual)mailbox.

**Comment by Austin-Ray** [comment]
On 04/05, bjesus wrote:
> I was wondering if there was a way to automate it, meaning to assign a
> key (macro?) that will automatically create a vfolder with messages
> with the same topic / messages from the same thread.

My understanding is you want to find all messages in a thread then
display _only_ those messages.

> Is this possible?

If my understanding is correct, this works on my machine:

`macro index \cl "<entire-thread><limit-current-thread>"`

Let me know if that works.

---

@gahr

> No - neomutt works per-(virtual)mailbox.

That is true, but `notmuch` mailboxes are just saved queries so you can
manipulate neomutt's working copy of the mailbox without messing up the
actual mailbox (assuming you don't modify tags.)

**Comment by bjesus** [comment]
Thanks @Austin-Ray , this works! Initially I get a "No virtual folder, aborting", but I just replaced my Inbox with a virtual Inbox that mirrors it, and now it works. Thank you very much!

I guess we can close the issue, even though it's not exactly a solution to the question in the title.

**Comment by Austin-Ray** [comment]
On 04/06, bjesus wrote:
> I guess we can close the issue, even though it's not exactly a solution to the question in the title.

Ah, I assumed the mailbox was a notmuch mailbox. I'll keep this open a
little longer and see if I find a method that works with physical
mailboxes.

**Comment by roccoblues** [comment]
Closing this old issue because it's is fixed for the original reporter.
