### ISSUE TITLE
Problems with adding university office365 account

### ISSUE THREAD

**Issue by emorevival** [neomutt/neomutt#1639]
How would I go about connecting my uni account when it has to authenticate twice?
By that I mean: first I enter my uni email at office365, then my password, then it redirects me to my uni's authentication system which asks for a username and password - the username is myID@uni.domain and the password is the same password as before. Once that's over, only then it lets you in. Is this even possible to do in mutt? I've been searching for answers all day and I did find some, but none of them helped

**Comment by ismaelpuerto** [comment]
You must create an app password: https://account.activedirectory.windowsazure.com/AppPasswords.aspx

**Comment by emorevival** [comment]
It gives me an error:

This page is only available to users who are required to sign in using additional security verification.

**Comment by wjid** [comment]
I would try using offlineimap or its successor to download your mail locally and then sync NeoMutt with this folder. I recall having this problem when I first started tinkering with NeoMutt and ultimately had to use a VPN which dealt with two-factor authentication.

**Comment by roccoblues** [comment]
I'm trying to cleanup some older issues here. Is this still relevant? Thanks!
