### ISSUE TITLE
Anything like "set ?option" to check "mailboxes" option?

### ISSUE THREAD

**Issue by ahmedelgabri** [neomutt/neomutt#1641]
I can easily check any option & check its current value by doing `:set ?option` is there is anything similar for `mailboxes`? I'm trying to debug an issue in my dynamically generated `mailboxes`

**Comment by flatcap** [comment]
No, there isn't.

The best I can suggest is using the last release (2018-07-16) and `unset folder` and make the sidebar nice and wide.  That should display everything that NeoMutt has received as a `mailboxes` command.

Or...  Throw some `mutt_debug()` statements in a PR :-)

The build from `master` is a little more fussy, so mailbox paths that aren't recognised might be ignored.

Eventually, I'd like the Lua code to be extended -- it only knows about a global 'mutt' object.  Soon we should teach it about `Account`, `Mailbox` and `Email` objects.

**Comment by ahmedelgabri** [comment]
> The best I can suggest is using the last release (2018-07-16) and `unset folder` and make the sidebar nice and wide. That should display everything that NeoMutt has received as a `mailboxes` command.

This didn't help :(

> Or... Throw some `mutt_debug()` statements in a PR :-)

I don't mind trying, but I need lots of help :)

> The build from `master` is a little more fussy, so mailbox paths that aren't recognised might be ignored.

What are the paths that can be not recognised? Because my issue is that I'm setting the mailboxes dynamically using something like this

```sh
tree ~/.mail -d -I "cur|new|tmp|certs|.notmuch" -a -f -i | sed -n -E -e "s|^/Users/ahmed/.mail/?||" -e "/^(Work|Personal)$/d" -e "/^(Work)/{p;}" | sed -E -e 's/(.*)/+"\1"/' | grep -v "\/\."
```

This is working fine outside of neomutt (for all the accounts I have) but working fine with one account inside neomutt. So I wanted to see what's actually getting passed to `mailboxes`

I'm also doing this switch using `lua` 

```lua
mutt.call("mailboxes",
  "`tree ~/.mail -d -I \"cur|new|tmp|certs|.notmuch|Inbox|\\[Gmail\\]\" -a -f -i | sed -n -E -e \"s|^"..os.getenv('HOME').."/.mail/?||\" -e \"/^("..opt.account_name..")$/d\" -e \"/^("..opt.account_name..")/{p;}\" | sed -E -e 's/(.*)/+\"\\1\"/' | tr '\\n' ' ' | grep -v \"\\/\\.\"`"
)
```

**Comment by ahmedelgabri** [comment]
Actually found the issue 🤦🏻‍♂️ the order of `tr` & `grep` in the command was wrong. Sorry.
