### ISSUE TITLE
Translation to French uses months of unequal lengths, causing misalignment in thread hierarchy

### ISSUE THREAD

**Issue by jborme** [neomutt/neomutt#1644]
In the example below, month are févr. (5 chars) and mars (4 chars), causing 1 char misalignment on the last two messages.

```
33812 r   23 févr. 2019 Xxxxxxxx Yyyyy  ( 13K)     └─>
33813   F 24 févr. 2019 To Xxxxxxxx Yyy (3,4K)       ├─>
33814   F 27 févr. 2019 To Xxxxxxxx Yyy (3,3K)       ├─>
33815   F 02 mars 2019 To Xxxxxxxx Yyy (3,1K)       └─>
33816   + 02 mars 2019 Xxxxxxxx Yyyyy  (3,9K)         └─>
```
using: 20180716 under gentoo linux.

What should happen instead (I manually added 1 space between mars and 2019)
```
33812 r   23 févr. 2019 Xxxxxxxx Yyyyy  ( 13K)     └─>
33813   F 24 févr. 2019 To Xxxxxxxx Yyy (3,4K)       ├─>
33814   F 27 févr. 2019 To Xxxxxxxx Yyy (3,3K)       ├─>
33815   F 02 mars  2019 To Xxxxxxxx Yyy (3,1K)       └─>
33816   + 02 mars  2019 Xxxxxxxx Yyyyy  (3,9K)         └─>
```

**Comment by flatcap** [comment]
Let's start with the workaround (then decide whose fault it is :-)

If you change your `$index_format` to split the date, it will look correct:
- `%{%d} %-5{%b} %{%Y}`

I _think_ it's the fault of libc - the standard C library.
NeoMutt doesn't generate those translations, it's done by `strftime(3)`.
It seems that you can't left-align the `%b` format (which is a GNU extension).

**Comment by jborme** [comment]
Thanks, it works great.
