### ISSUE TITLE
neomutt no longer marks replied messages as such

### ISSUE THREAD

**Issue by l29ah** [neomutt/neomutt#1647]
1e0091a8b923db07e4af59f0c98c762786233f32 is the first bad commit

**Comment by flatcap** [comment]
Thanks for the bisect, @l29ah.

2eddd7c fixes the reply bug, but... there seems to be another problem.

After the flag is set, it's not being committed.
If you immediately quit NeoMutt, the flag isn't saved (you have to `<sync-mailbox>`).

**Comment by Austin-Ray** [comment]
On 04/12, Richard Russon wrote:
> After the flag is set, it's not being committed.  If you immediately
> quit NeoMutt, the flag isn't saved (you have to `<sync-mailbox>`).

Reply flag is committed w/ notmuch and maildir backends.

**Comment by flatcap** [comment]
> Reply flag is committed w/ notmuch and maildir backends.

Maybe in combination, but I don't see it with a plain maildir mailbox.
I see `m->changed == false` and `m->append == true` so `mx_mbox_close()` isn't doing anything.

**Comment by Austin-Ray** [comment]
On 04/14, Richard Russon wrote:
> > Reply flag is committed w/ notmuch and maildir backends.
> 
> Maybe in combination, but I don't see it with a plain maildir mailbox.

Standalone maildir commits the reply flag on my machine.

**Comment by flatcap** [comment]
> Standalone maildir commits the reply flag on my machine.

Ah, I know why our tests differ.
I have `set record = '^' # Save outgoing to current mailbox` causing `mutt_write_fcc()` is setting `m->append`.
