### ISSUE TITLE
our coding style -> following upstream coding style, automatically testing for it?

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#165]
Hey.

currently, our overview [neomutt.org/devel](https://www.neomutt.org/devel/) links to a [custom, unfinished coding style](https://www.neomutt.org/devel/coding.html). Altough i like the idea of not allowing trailing whitespace in code, i'd suggest using - or even improving -  the [offical mutt coding style](https://dev.mutt.org/trac/wiki/CodingStyle).

The simple reason for this is, that it may ease code sharing from neomutt into upstream mutt and vice versa.

As the upstream coding style currently doesn't include a rule of whitespace handling (i.e. also it doesn't cover whether to use tabs or spaces for identation), i'd even suggest at least discussing that with upstream mutt.
- I'm wondering, if our codingstyle differs in some way of the upstream one?
- Maybe we should also kind of enforce this coding style by automatically testing/formatting it? Unfortunately, i didn't found a suitable tool for that (in particular, because we're using an kind of custom coding style and not a common one like the linux kernel or google.)
- in general, what are your opinions about this?

**Comment by flatcap** [comment]
We follow upstream's coding style, for now.

Their rules (poorly followed), are:
- Indent is 2 spaces
- Tabs are allowed for indent (8 spaces)
- Put `{}`s on a new line
- Omit `{}`s and `()`s wherever possible (I don't like this)

I have a lot of notes, but I haven't done anything with them, yet.
I'm fairly easy on coding style for NeoMutt.

My personal preference, is:
- If one part of a conditional needs `{}`s, then they all do (balanced)
- In conditionals, put `()`s around complex conditions
- Only use `!` for booleans and pointers

I'm also in favour of aligning code vertically, if it makes it easier to read.

**Comment by toogley** [comment]
Well, i personally don't like allowing spaces **and** tabs as indentation. It will lead inevitable to a lot of git commits, in which the actual change is hard to see, because so much whitespace has changed.

I'd suggest to automatically format the whole source code with every commit by using e.g. [clang-format](http://clang.llvm.org/docs/ClangFormat.html). My point is, i'd love to have a consitent mutt source code. :)

What do you guys think about that?

**Comment by christopher-john-czettel** [comment]
On 27.09.2016 - 12:09:59, Tobias Angele wrote:
> I'd suggest to automatically format the whole source code with every commit by using e.g. [clang-format](http://clang.llvm.org/docs/ClangFormat.html). My point is, i'd love to have a consitent mutt source code. :)

+1

As much as I like the idea, wouldn't this complicate merging with
upstream (if applied to legacy code - I see no problem with "new patches")?

**Comment by toogley** [comment]
@christopher-john-czettel Well, i guess it complicates things if upstream wants to merge our code - but as far as i heard, they aren't very happy with working together with us. So that won't make a big difference.

And merging upstream code into neomutt also isn't much a problem, we can certainly merge a autoformatted version - we would just have to create some scripts or sth like that.

**Comment by christopher-john-czettel** [comment]
On 27.09.2016 - 13:09:34, Tobias Angele wrote:
> @christopher-john-czettel Well, i guess it complicates things if upstream wants to merge our code - but as far as i heard, they aren't very happy with working together with us. So that won't make a big difference.

As far as I remember talking to @flatcap, he hasn't completely given up on trying to convince upstream to work together and at least have small bugfixes available for them. If we decide to explicitly drop that option and go our seperate ways I'd have no reservations to go the autoformatted route (actually I'd appreciate it ;-)).
 
> And merging upstream code into neomutt also isn't much a problem, we can certainly merge a autoformatted version - we would just have to create some scripts or sth like that.

May I suggest that *if* we decide to go this route, we adhere to a more wider used standard and not recreate a own special neomutt standard, maybe something like: https://www.gnu.org/prep/standards/html_node/Formatting.html to make it easier for new devs to join in?

**Comment by flatcap** [comment]
When we get to that point, we'll have a vote<sup>**‡**</sup>
In order:
- Vote
- Document
- Implement
- Enforce


**‡** I may get more votes than other people :-)

**Comment by toogley** [comment]
Hm, it seems the codestyle is really poorly followed. If the mutt mailinglist program confirms my registration, i'll ask upstream about this issue, specifically if they see the poorly followed codingstyle as a problem.

To provide some evidence:

```
~
$ hg clone https://dev.mutt.org/hg/mutt
destination directory: mutt
requesting all changes
adding changesets
adding manifests
adding file changes
added 6817 changesets with 19340 changes to 543 files
updating to branch default
384 files updated, 0 files merged, 0 files removed, 0 files unresolved
~
$ cd mutt
~/mutt
$ indent -nce -bls --braces-after-if-line --brace-indent0 --case-indentation2 --indent-level2  *.c

indent: cryptglue.c:111: Error:Unmatched 'else'
indent: curs_main.c:538: Error:Unmatched 'else'
indent: curs_main.c:876: Error:Unmatched 'else'
indent: curs_main.c:1316: Error:Unmatched 'else'
indent: curs_main.c:1352: Error:Unmatched 'else'
indent: curs_main.c:1354: Error:Unmatched 'else'
indent: curs_main.c:1356: Error:Unmatched 'else'
indent: curs_main.c:1745: Error:Unmatched 'else'
indent: handler.c:1772: Error:Unmatched 'else'
indent: menu.c:1029: Error:Unmatched 'else'
indent: pager.c:2092: Error:Unmatched 'else'
indent: pager.c:2114: Error:Unmatched 'else'
indent: pgp.c:570: Error:Unmatched 'else'
indent: postpone.c:158: Warning:old style assignment ambiguity in "=-".
Assuming "= -"

indent: sha1.c:171: Error:Stmt nesting error.
indent: smime.c:1209: Warning:old style assignment ambiguity in "=-".
Assuming "= -"

indent: smime.c:1829: Warning:old style assignment ambiguity in "=-".
Assuming "= -"
~/mutt
$ hg status | wc -l
114
~/mutt
$ hg diff | wc -l
81123

```

**Comment by toogley** [comment]
I think it makes sense to close this issue in favor of #224.
