### ISSUE TITLE
group-chat-reply does not work

### ISSUE THREAD

**Issue by tuanbass** [neomutt/neomutt#1654]
I have just moved to  neomutt and wonder why didnt find this wonderful mail client earlier. 
However, It makes me a little uncomfortable when "Reply All" a mail. The guys in CC list is not included in the composing mail. 

Scanning through the reference, there is a function "group-chat-reply" with description: "reply to all recipients preserving To/Cc" should be exactly what I need. However, trying to use this function, either using  :exec or binding it to a key, both does not work. 
I scanned through the latest source code, and it looks like the function quite new, and is not implemented fully. 

Am I correct ?

**Comment by gahr** [comment]
`:exec group-chat-reply` seems to work in the pager (not in the index). You can bind it to some key:

```
bind pager g noop  # make sure the original `g` is unbound first
bind pager g group-chat-reply
```

**Comment by gahr** [comment]
Having said that, yes, I think it's completely reasonable to expect that function to work in the index too

**Comment by tuanbass** [comment]
> `:exec group-chat-reply` seems to work in the pager (not in the index). You can bind it to some key:
> 
> ```
> bind pager g noop  # make sure the original `g` is unbound first
> bind pager g group-chat-reply
> ```

@gahr 
You are correct, I didn't notice that it works in pager. Thanks for pointing out. 
Hope it will work also in the index in next release

**Comment by gahr** [comment]
> Hope it will work also in the index in next release

I think it's a very reasonable thing to expect.. I'll look into that

**Comment by tuanbass** [comment]
Thanks, I can use the feature in latest revision.

**Comment by BH1SCW** [comment]
Hi all,

I am lucky to found this page, but when I try:
1, :exec group-chat-reply
2, bind pager g noop  # make sure the original `g` is unbound first
bind pager g group-chat-reply

the cc area is missing, is this feature or bug?
Thanks

my version info:
NeoMutt 20191207

System: Linux 5.13.0-39-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.13.1-unknown
libnotmuch: 5.2.0
hcache backends: tokyocabinet

**Comment by flatcap** [comment]
> the cc area is missing, is this a feature or bug?

Using `<group-chat-reply>` the '**To:**' and `'**Cc:**' fields stay the same
(except that you and the sender swap places).

The '**Cc:**' field will only be empty, if it's empty in the original email.

It seems to be working for me, using the latest version of NeoMutt,
and the code seems to match what I expected.

> NeoMutt 20191207

If possible, I'd try to get a newer version.
We've fixed a lot of bugs and added new features in the last 2.5 years.

**Comment by BH1SCW** [comment]
On 18 May 22 ◦ 03:53, Richard Russon wrote:
> > the cc area is missing, is this a feature or bug?
> 
> Using `<group-chat-reply>` the '**To:**' and `'**Cc:**' fields stay the same
> (except that you and the sender swap places).
> 
> The '**Cc:**' field will only be empty, if it's empty in the original email.
> 
> It seems to be working for me, using the latest version of NeoMutt,
> and the code seems to match what I expected.
> 
> > NeoMutt 20191207
> 
> If possible, I'd try to get a newer version.
> We've fixed a lot of bugs and added new features in the last 2.5 years.
I have update to latest code. It seems Cc works.
current email is group-chat-reply without changing any To or Cc
