### ISSUE TITLE
Variables in muttrc

### ISSUE THREAD

**Issue by aviofreak** [neomutt/neomutt#1660]
Hi,

I've been unsuccessful finding it - maybe because it does not exist - but I would love to have the ability of configuring some "variables" in the neomutt config file. For example similar solution is when you configure a firewall rules in, say, pf.conf - they call it "macros":
```
ext_if = "fxp0"

block in on $ext_if from any to any
```
This way you don't have to do some wicked "find and replace all" when you want to change one thing.

I would love to see similar solution in neomutt - for example when configuring theme colors. Now you specify the color of each element one by one. It would be much easier to do something like this:

```
base_color = "#cccccc"
highlight_color = "#cc0000"

color index_author default $highlight_color
color index_date $base_color default
```

This way you can configure your basic set of few colors, place variables down in the "color..." lines and if you'd like to change one "accent" color, you would change it only in one place.

**Comment by jindraj** [comment]
You can define own vairables with prefix `my_`
```
set my_color_highlight = red
set my_color_base      = blue

color index_author default        $my_color_highlight
color index_date   $my_color_base default
```

Is that sufficient solution?

**Comment by flatcap** [comment]
https://neomutt.org/guide/configuration#set-myvar

**Comment by aviofreak** [comment]
Oh man! Yes, this is it! Thanks a lot!

How have I missed it?
