### ISSUE TITLE
Neomutt fails to work with multiple imap accounts.

### ISSUE THREAD

**Issue by 0x747972** [neomutt/neomutt#1663]
## Expected Behaviour

Upon hitting <kbd>F3</kbd> or <kbd>F4</kbd> Neomutt should log in to account2 or account3.

## Actual Behaviour

Login fails.

## Steps to Reproduce

Use a mutt configuration like provided or like this:
https://gist.github.com/miguelmota/9456162
Try to switch accounts.

## How often does this happen?

- Always.

## When did it start to happen?

- With current master branch. Works in last neomutt release.

## NeoMutt Version

It's in the current master branch.

## Extra Info

The accounts all work by themselves. It's switching between them that doesn't work.
I've attached my muttrc and one of the account configs, but have stripped them of sensitive information. They are pretty much the same as in the example-configuration i've linked to above.

[muttrc.txt](https://github.com/neomutt/neomutt/files/3100335/muttrc.txt)
[account.txt](https://github.com/neomutt/neomutt/files/3100336/account.txt)

**Comment by sileht** [comment]
Does putting the imap user inside the `$folder` url (imaps://myuser@gmail.com@imap.gmail.com:993) and unset `$imap_user` workaround the issue ?

**Comment by 0x747972** [comment]
Yes it does.

**Comment by sileht** [comment]
Maybe it have something to do with https://github.com/neomutt/neomutt/blob/master/imap/util.c#L1167-L1168

**Comment by gahr** [comment]
I thought I'd post what I use, which works fine for me:

https://gist.github.com/gahr/870e866fa9c6bf7e6818cca39b304a40

**Comment by 0x747972** [comment]
Can you confirm that it works with what's in master rn?

**Comment by gahr** [comment]
> Can you confirm that it works with what's in master rn?

Yes

**Comment by gahr** [comment]
@0x747972 any news? Can you please start from scratch with a clean config and see at which point it stops working?

**Comment by 0x747972** [comment]
Hey, sorry for being away so long...
I have just added an account which is not a gmail account to my config.

So switching between this account and the gmail account causes no issues,
however switching between gmail accounts a login failure without "set imap_authenticators = plain" being set and a segfault with it being set.

**Comment by roccoblues** [comment]
I'm trying to cleanup some older issues here. Can you still reproduce this with the latest version? Thanks!
