### ISSUE TITLE
Uncollapsed threads when limiting the displayed messages

### ISSUE THREAD

**Issue by project-repo** [neomutt/neomutt#1667]
Hi guys,

I decided to look into threading in neomutt today and I stumbled upon something which I believe may be unintended behaviour.

Since I often have lengthy threads in my inbox which clutter it up and make it difficult to find messages, I added `set collapse_all=yes` to my neomuttrc, which performed as expected. However, I discovered that when limiting the displayed messages ( pressing `l`), the threads appear to become uncollapsed although the first message in the thread is still matched as a collapsed thread and highlighted accordingly. Is this supposed to happen?

cheers,
project-repo

**Comment by flatcap** [comment]
You're right, `set collapse_all=yes` isn't applied after `<limit>`

But what is the user trying to achieve when they `<limit>`?
They're probably looking for something, so do they really want collapsed threads?

The `<limit>` function is likely to break a lot of threads.
Do we want:
- Just the matching emails and...
  - Disable threading (flat list)
  - Enable threading (may look broken)
- Entire thread of matching emails (like the Notmuch option)
  (This may require a new function)

**Comment by gahr** [comment]
I am also unhappy with the current behaviour, especially when finding myself in an uncollapsed view after exiting a limit via `l.`<kbd>enter</kbd>. I think respecting `set collapse_all=yes` is desirable even when the threads are incomplete (because not all messages match).

**Comment by gahr** [comment]
Can you guys please try out the [devel/issue-1667](https://github.com/neomutt/neomutt/tree/devel/issue-1667) branch? I think it is an improvement.
