### ISSUE TITLE
Attach files using FZF <attach-file> /home/XX/file.txt

### ISSUE THREAD

**Issue by rafaeluriarte** [neomutt/neomutt#1669]
I am trying to use fzf (or any other tool that outputs the file path) to select the files to attach in neomutt but I am having troubles. First, I could not find any function to attach straight a file (something like <attach-file PATH>  and I was trying to to it manually but could not read the stout of the file. I was trying:

<pre>
 <code>   
macro compose H "&ltattach-file> c &ltkill-line> &ltshell-escape> /usr/bin/fzf &ltenter>"
 </code>
</pre>
(this, even if worked, would only change the directory but not select the file)

Any ideas of how to read the stout of the fzf (/home/file.txt) and attach the file?

Thank you

**Comment by gahr** [comment]
How about
```
:macro compose H "<attach-file>`/usr/bin/fzf`<enter>"
```

**Comment by rafaeluriarte** [comment]
I tried it but using `` runs the command while opening mutt and does not do anuthing in the compose section...

**Comment by gahr** [comment]
Ah - I see fzf is an interactive command. You would like to spawn it, have it take control over the terminal, return a result to stdout, and have neomutt intercept that result.. now sure I know how to do that...

**Comment by chrisbra** [comment]
If you are using Vim and have `edit_headers` set, you can make that work from your editor using the `Attach` pseudo header. Have a look at my vim plugin [CheckAttach](https://github.com/chrisbra/CheckAttach/)

**Comment by rafaeluriarte** [comment]
Thank you, the idea is really good (I am having troubles to make it work but I opened an issue in the plugin's page).  However, it would be great to be able to use the FZF directly in mutt for both saving and adding attachment. So, I'd appreciate if someone has an idea for a macros in this case.

**Comment by doronbehar** [comment]
Than this issue should be labeled as a feature request for interactive commands in sub shells inside macros - this is much less specific then the current title which refers to fzf.

**Comment by david-perez** [comment]
I too was missing the ability to have interactive commands in subshells inside macros, so I came up with this ugly hack:
```
macro index L "<enter-command>unset wait_key<enter><shell-escape>echo \"sales@\\njarvis\" | fzf > ~/.cache/mutt_limit<enter><limit>~L \"\`echo \$(cat ~/.cache/mutt_limit)\`\"<enter>"
```
The macro limits the index to show mails sent from addresses containing `sales@` or `jarvis`. The user selects one of the two patterns interactively with fzf (it works with fzf, dmenu or whatever e.g. `echo \"sales@\\njarvis\" | shuf -n 1`) and the choice is written to a file. The macro then cats the file to the limit command. Note that the `cat` part is not executed by neomutt at startup, that is, when hitting L, it won't always limit to whatever was in the file when neomutt started, but it will instead read the updated contents of the file, which contains the choice the choice the user has just made, just what we want!

If you remove the `<enter>` from the macro, neomutt prompts you with
```
Limit to messages matching: ~L "`echo $(cat ~/.cache/mutt_limit)`"
```
which is odd, but when you press enter, the command is properly evaluated.

Cool, I thought, this could be applied anywhere where we need interactive input at runtime to feed to a function in a macro, so the natural modifications to my limit macro to address @rafaeluriarte 's issue yield a macro of the likes:

```
macro compose a "<enter-command>unset wait_key<enter><shell-escape>echo \"file1\\nfile2\" | shuf -n 1 > ~/.cache/mutt_attach<enter><attach-file>\"\`echo \$(cat ~/.cache/mutt_attach)\`\""
```
This would attach `file1` or `file2` randomly. When you execute it neomutt prompts you with
```
Attach file: "`echo $(cat ~/.cache/mutt_attach)`"
```
but sadly, the cat command is not evaluated and instead you get
```
Unable to attach "`echo $(cat ~/.cache/mutt_limit)`"!
```

I've tried with other functions like `change-folder` or `save-message`, but it seems like it only works with `limit`. Why?

**Comment by Galicarnax** [comment]
Any plans on usable integratioin of (neo)mutt with `fzf`? `fzf` integrates with text editors (`vim`), file managers (e.g., `ranger`), and basically anything else capable of interchanging data via standard input/output. Nice uniform workflow across multiple applications. Would be great to see `neomutt` in the list.

Specifically, one could use `fzf` in neomutt to:
- select files to attach
- select directories to save an attachment to
- select an address/alias
- select mailbox to jump to
- ...
(To my knowledge, only the last item in this sample list has been implemented in a usable way - see https://github.com/neomutt/neomutt/issues/1515).

**Comment by jindraj** [comment]
Selecting address from external addressbook works also – see https://github.com/neomutt/neomutt/issues/3#issuecomment-490706985

Doesn't apply for aliases.

**Comment by jamespeapen** [comment]
@rafaeluriarte This solution is based on the one in #1515.


In `muttrc`:

```
macro compose <space>a ":source ~/.config/mutt/scripts/fzfattach|<enter>"
```

`fzfattach`

```bash
#!/usr/bin/env bash

fzf_command='fzf'
fd_command="fd . ~ --type f"

attachment="$($fd_command | $fzf_command)"

echo "push 'a$attachment<enter>'"
```

**Comment by Galicarnax** [comment]
Awesome, thanks!
Though the script didn't work for me in your form (`~` was not expanded to be recognised as a valid path). So I've changed it to
```
attachment="$(fd . ~ --type f | fzf)"
echo "push 'a$attachment<enter>'"
```
and it works.

**Comment by tkapias** [comment]
Thank you for this thread.

I customized it a little more because it was a slow on my $HOME and I think that it should be restricted to a selection of extensions.

The attachment menu "a" work good for other cases.

```muttrc
macro compose \Ca ":source ~/.config/neomutt/scripts/fzfattach.sh|<enter>"
```

```bash
#!/usr/bin/env bash

# cd to the root folder of attachments
cd $HOME

# custom fd (fdfind on debian) for fzf, including only some extentions that I use as attachments
export FZF_DEFAULT_COMMAND='fdfind -t f -e pdf -e png -e jpg -e zip -e tar -e gz -e rar -e html -e md'

attachment=`/usr/bin/fzf --prompt='Choose a file to attach >'`

if [ "${#attachment}" -gt 1 ]; then
  echo "push 'a$attachment<enter>'"
else
  # If you cancel fzf or choose an empty line
  echo "echo 'No attachment selected'"
fi

```

**Comment by jindraj** [comment]
Perhaps one more enhancement. add `-m` fzf option to enable selection of multiple files with <kbd>Tab</kbd>, while loop to read all selected files and get rid of the condition which is not necessary anymore.
```sh
/usr/bin/fzf -m --prompt='Choose a file to attach >' | \ 
while IFS=$'\n' read -r attachment
do
  echo "push 'a$attachment<enter>'"
done
```

**Comment by Galicarnax** [comment]
The hack with `fzf` works for me only if the path does not contain spaces. If using script directly from bash, the paths are echoed correctly, but within `neomutt` something eats up the spaces. Cannot figure out for now how to workaround...

**Comment by jindraj** [comment]
I know what's going on, but I don't know yet how to prevent it happening.

If you remove <enter> and try to attach a single file with spaces in filename: `/tmp/File containing spaces`
You'll get: /tmp/File containing spaces**containingspaces**

Doing this manually, you can see the file is autocompleted once you hit space.

I've tried looking into bindings, but there's nothing relevant bound to Space in any menu, especially not in generic or editor.

**Comment by tkapias** [comment]
I had this problem with a script to change folder with FZF.

It was because of the "push 'c..." commands.

- "c" reset if you input a space, you can try it manually by pressing "c" and inputting anything then a space.
- And it seemed that "push" did not transcribe some special characters like spaces or single quotes.

I did not find any solution, so I cleared all my mailboxes folders path of any space or special characters.

Here for the attachment "a" command, I see that manually if you try to input a space it will try to force you to use autocomplete and if you paste a path it will trim the spaces or bug.

I am looking at how to disable this feature.

**Comment by tkapias** [comment]
Apparently it comes from [mutt_complete()](https://neomutt.org/code/complete_8c.html#a72b3c85bc14241321c26350fd4a26b37)

For now, I don't have a lot of spaces in my paths, but I will try to write something better with <attach-file>.

**Comment by flatcap** [comment]
> something eats up the spaces

Try config:
```
unbind editor <space>
```

One of Mutt's historic and unusual bindings is <kbd>\<space\></kbd> -> `<mailbox-cycle>`.
That function means that if you're changing folder, <kbd>\<space\></kbd> will auto-complete folders with new mail.

Turning it off, will allow you to enter spaces.

**Comment by tkapias** [comment]
Thank you so much @flatcap !

I will try a lot of other things I aborted now.

And thanks to @jindraj for the multiple files part.

~/.config/neomutt/neomuttrc

```bash
# This binding was using <space> for folders auto-completion and breaking a lot of push macros.
unbind editor <space>

# List files in $HOME with selected ext with fzf and send them to compose attachment, use tab to select multiple files in fzf
macro compose \Ca ":source ~/.config/neomutt/scripts/fzfattach.sh|<enter>"
```

~/.config/neomutt/scripts/fzfattach.sh

```Bash
#!/usr/bin/env bash

# cd to the root folder of attachments
cd $HOME

# custom fd (fdfind on debian) for fzf, including only some extentions that I use as attachments
export FZF_DEFAULT_COMMAND='fdfind -t f -e pdf -e png -e jpg -e zip -e tar -e gz -e rar -e html -e md --absolute-path'

/usr/bin/fzf -m --prompt='Choose a file to attach >' | \
  while IFS=$'\n' read -r attachment; do
    echo "push 'a$attachment<enter>'"
  done

```

It works for me !

**Comment by Galicarnax** [comment]
Great, thanks!

**Comment by rafaeluriarte** [comment]
@tkapias Did selecting files with space works for you? I tried here with your configs and I still have the white space problem. Any ideas? Thank you very much

**Comment by tkapias** [comment]
It works for me, to be sure that the script output is correct try to run it directly in your shell and select one or more files with tab.

```bash
$ ~/.config/neomutt/scripts/fzfattach.sh
```

The output should list each file in this form : 

```bash
push 'a/home/user/some file 1.ext<enter>'
push 'a/home/user/some file 2.ext<enter>'
```

**Comment by rafaeluriarte** [comment]
Thank you very much, I had a typo in the muttrc file, now it works!
