### ISSUE TITLE
Right-to-left languages

### ISSUE THREAD

**Issue by hebrewd** [neomutt/neomutt#1671]
## What would you like to be able to do?
Have support for RTL languages in the main view.

## What needs to change in NeoMutt?
Basically, NeoMutt will have to render Right to left Languages properly, right now it renders them from left the right.

## Have you tried any alternative methods?
Yes, setting fribidi as the display filter renders the mails themselves perfectly.
However NeoMutt doesn't seem to offer a way to do the same for the main view itself.

## Additional Info

 Relying on [fribidi](https://github.com/fribidi/fribidi) for that purpose seems like the way to go. It will save the hassle of reading through and understanding the unicode standards for those languages and implementing a renderer from scratch.
The library has a small footprint and is preinstalled on most systems by default.

**Comment by mschilli87** [comment]
@hebrewd: I run NeoMutt in [mlterm](http://mlterm.sourceforge.net/) and can read English, Hebrew, and mixed email just fine in the pager (and compose them via NeoVim).

Still, just like for (Neo)Vim, native support would be great.

That said, have you tried to request this feature over at mutt? If it was implemented there, it would likely find its way here eventually.

**Comment by hebrewd** [comment]
No, I haven't actually, I suppose it is worth a shot. I will give it a try over there first.
