### ISSUE TITLE
Ensuring whether the sidbar is displaying virtual or real mailboxes

### ISSUE THREAD

**Issue by Joshuao95** [neomutt/neomutt#1678]
Hello,

I was wondering if there is any way in the muttrc to specify whether or not the sidebar should be displaying virtual or real mailboxes.
I could just "exec sidebar-toggle-virtual", however I like to maintain multiple accounts by using a macro to source different config files for each user, and if I want some of those to display me the real mailboxes by default, rather than virtual, then the order in which I move around these accounts becomes important.

I do realise I could just bind it to a key, but considering the use case is usually "I want to see virtual folders" or "I want to see real folders", it seems like it would make sense to have an absolute setting for it.
Thanks

**Comment by flatcap** [comment]
hi @Joshuao95 

> specify whether or not the sidebar should be displaying virtual or real mailboxes

Good question.  No there isn't.

You _could_ create a marker for yourself, using a `my_` variable; it'd be a bit ugly.

```
# neomuttrc -- assuming that you start on a normal mailbox
set my_view = 'normal'
macro index <f1> ':source show-virtual.rc<enter>'
```

```
# show-virtual.rc
macro index <f1> ':source show-normal.rc<enter>'
exec sidebar-toggle-virtual
unset my_view
```

```
# show-normal.rc
macro index <f1> ':source show-virtual.rc<enter>'
exec sidebar-toggle-virtual
set my_view = 'normal'
```

(The above is untested, but you get the idea)
Now, you can test which mode you're in:

```
ifdef  my_view source normal.rc
ifndef my_view source virtual.rc
```

---

In the next release of NeoMutt (which _still_ might not be soon), there's no difference between normal and virtual mailboxes.  The plan is to toggle the visibility of **Accounts**, e.g.

```
set account_list=work,home
```

or

```
set account_list+=home
```

But there's still a lot of work to be done.

**Comment by Joshuao95** [comment]
Hi flatcap,

That sounds like a good workaround for now, thanks for that, I don't mind a bit of ugliness :)

I'll look forward to the next release, that feature sounds like it will neaten up my setup a lot, thanks for all the hard work!
