### ISSUE TITLE
NeoMutt not building on Mac OS X 10.5 PPC

### ISSUE THREAD

**Issue by lbschenkel** [neomutt/neomutt#168]
Hi,

I'm the maintainer of the NeoMutt port in MacPorts. Today I got an e-mail from their buildbot notifying that it couldn't be built for Mac OS X 10.5 PPC:
https://build.macports.org/builders/ports-10.5_ppc_legacy-watcher/builds/632

The build output is here:
https://build.macports.org/builders/ports-10.5_ppc_legacy-builder/builds/5905/steps/install-port/logs/stdio

I'm at a loss to explain why the symbols are undefined since they are defined in `lib.c` and `strndup.c` and I can see both files being compiled. I don't know if this is an issue with the port, or NeoMutt, or upstream Mutt. I would appreciate any help on diagnosing/fixing this — I don't think I'll able to do it on my own.

**Comment by flatcap** [comment]
Oh, hello.  I'm the maintainer of NeoMutt :-)

> NeoMutt port in MacPorts

I hadn't heard of that.  In a sentence, what's the difference between Homebrew and MacPorts?  (for a non-Mac user)  We've had Homebrew support almost since the beginning of NeoMutt.

> strndup.c and `safe_malloc()`

First, to get your build working, simply replace `safe_malloc()` with `malloc()`
I made the change to make sure everyone was allocating memory the "Mutt" way.

Why is it failing?  I really don't know.  As you point out lib.h is included and lib.c is compiled and linked in.  `safe_malloc()` is used everywhere in Mutt.  I shall do a little digging and get back to you.

**Comment by flatcap** [comment]
I've found the problem.  It's not with mutt, but with mutt_dotlock and pgpewrap (two helper programs).
Even though they don't use `strndup()` or `strnlen()`, autoconf tries to link them, anyway.

I'll restore `malloc()` and it'll be in the next release -- due in the next few days.

**Comment by lbschenkel** [comment]
Thanks a lot. It's not entirely clear to me if the autoconf bug was introduced in NeoMutt or is it present in upstream Mutt as well? And it's strange that it only triggers in OS X 10.5 PPC but not in any other version or architecture.

Regarding MacPorts and Homebrew, they're just different package managers. MacPorts is the older of the two and both have their legion of fans, not unlike apt vs rpm. :-)

**Comment by flatcap** [comment]
`strndup()` is only used in the notmuch code, so it, and the autoconf "feature", don't appear in Mutt.

I'm surprised the build problem hasn't show up in the Homebrew version, though.  That implies Homebrew's libraries provide `strndup()`, but MacPort's don't.

> Regarding MacPorts and Homebrew, they're just different package managers.
> ... both have their legion of fans, not unlike apt vs rpm. :-)

Ah, I see :-)

**Comment by lbschenkel** [comment]
I believe that Homebrew does not build anything for anything below 10.7. There's an experimental fork called "Tigerbrew" for old versions of macOS.

**Comment by lbschenkel** [comment]
Btw, there's more info in https://trac.macports.org/ticket/52460
You can find there a diff between a successful and a failed build, which clarifies things a bit.

**Comment by lbschenkel** [comment]
FYI, the new release now builds on OS X 10.6. We're still waiting for confirmation on a successful build on 10.5 but since both were failing for the same reason I'm optimistic that we won't find any issues. I'll let you know either way.

**Comment by lbschenkel** [comment]
I'm closing it because the latest version builds now on OS X 10.6 and 10.5, however it crashes on 10.5. I have created a new issue for that: https://github.com/neomutt/neomutt/issues/187
