### ISSUE TITLE
Translation problem: "no binds/macros for this menu" cannot be properly translated

### ISSUE THREAD

**Issue by mgedmin** [neomutt/neomutt#1680]
I was translating

```po
#: icommands.c:268
#, c-format
msgid "%s: no %s for this menu"
```

and I checked the source to see what `%s` will expand to:

```c
    mutt_buffer_printf(err, _("%s: no %s for this menu"),
                       dump_all ? "all" : buf->data, bind ? "binds" : "macros");
```

and I see:

- the word "binds" or "macros" cannot be translated
- some languages may need to use different declensions for "binds"/"macros" in this context rather than in other contexts, so it would be better to translate entire sentences rather than construct them piecemeal.

**Comment by flatcap** [comment]
@reisradomil Would you mind looking at this?
Thanks.

**Comment by reisradomil** [comment]
Will do.

**Comment by reisradomil** [comment]
I've reworded the line in question, see pull-request #1686 for more details.

@mgedmin thanks for reporting this.

**Comment by flatcap** [comment]
I'll re-sync the translations shortly (I've got some large upstream changes to apply, first).
