### ISSUE TITLE
sidebar not displaying anything

### ISSUE THREAD

**Issue by joeg1484** [neomutt/neomutt#1688]
So I installed neomutt and have it working and pulling mail from my server and the sidebar is present, however, none of my folders are showing up. The sidebar is completely blank. But my messages are showing up in the right pane.

OS: Centos 6 using latest version from neomutt repo. Connecting to IMAP servers

Any ideas?
Thanks!
Joe

**Comment by flatcap** [comment]
Hi @joeg1484 

The `mailboxes` command registers your interest in folders.
This list is also used to populate the sidebar.

```
# .neomuttrc
set folder="imap://username@server.com/"
mailboxes +work
mailboxes +friends
...
```

See also:
- [Sidebar Intro](https://neomutt.org/feature/sidebar-intro)
- [Mail checking variables](https://neomutt.org/guide/reference#mail-check-stats)

**Comment by gahr** [comment]
Alternatively to setting `mailboxes` manually, you can have NeoMutt populate them using the list of subscribed mailboxes from IMAP. Use `set imap_check_subscribed=yes` for that.

**Comment by joeg1484** [comment]
> Alternatively to setting `mailboxes` manually, you can have NeoMutt populate them using the list of subscribed mailboxes from IMAP. Use `set imap_check_subscribed=yes` for that.

Thanks for the reply! Ill give this a go...

**Comment by gahr** [comment]
Please let us know if you're still in trouble.
