### ISSUE TITLE
<save-message> now much slower

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#1702]
## Expected Behaviour

For `<save-message>` to be as fast as before.

## Actual Behaviour

`<save-message>` is much slower now. When I use it, it takes a longer time than before, and the following messages are shown:

```
Scanning <path to dir>...
Reading <path to dir>...
Sorting mailbox...
mailbox is unchanged
```

To be clear, by "much slower", I'm talking in relative terms. In absolute terms, it only takes a couple of seconds.

## Steps to Reproduce

I have the following macro in my muttrc:

```
macro index,pager a "<save-message>=skArchive<enter>" "archive"
```

To reproduce, I just need to press `<a>` on a message in a different directory.

## How often does this happen?

- Always

## When did it start to happen?

I tried to "git bisect" but had to "git skip" several commits. The final result of the bisect was the following:

>There are only 'skip'ped commits left to test.
>The first bad commit could be any of:
>b737f6fa067a5c8413707980698bc8e2c11f0ede
>1dd7f017d2e5b86a69feeec4d144d3e9bc8edac1
>c9dd74b97f5e7c48af384adb7d645a7184a639b4
>57a8199dcbf88fa9582ef2cc1ee9ec3bcaaad8b1
>5fba45196b2a23b371389d64f270088c32fb706e
>9f295b0d0698605ad6de02f857ab7936ae8e8f54
>c4519393c670e5198cb3bd5c82e8688916d5fd7b
>dba258fd9b3e1730d9a6d7a46e1c5e54d3179663

I then took a look at those commits and since b737f6fa looked potentially related, I tested neomutt master with it reverted. Note that I had to do the following for a "clean" revert:

```
git revert --strategy-option theirs b737f6fa067a5c8413707980698bc8e2c11f0ede
```

This made my `a` macro very fast again (although I don't understand what the side effects are).

## NeoMutt Version

```
$ mutt -v
NeoMutt 20180716-1748-263be7
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.0.0-13-generic (x86_64)
ncurses: ncurses 6.1.20181013 (compiled with 6.1.20181013)
libidn: 1.33 (compiled with 1.33)
hcache backends: tokyocabinet

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.3.0-6ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1) 

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls -gpgme -gss +hcache -homespool +idn +inotify -locales_hack -lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
$
```

**Comment by scottkosty** [comment]
@flatcap are you able to reproduce this issue? I've avoided "bumping" this issue because the delay is only a couple of seconds for each message, so it really shouldn't bother me. But for some reason it does.

Would it be a bad idea for me to locally (i.e., on my machine) revert b737f6fa?

**Comment by flatcap** [comment]
Sorry for the lack of action, @scottkosty.

I tried it at the time, but I couldn't see any difference, but the difference _was_ there.
Looking more closely, b737f6fa causes neomutt to rescan the target mailbox, causing the slowdown.

However, I don't see the slowdown in `master`, not since @gahr's commit 12e79d65 (two weeks ago).

Please can you give `master` a try.  Thanks.

**Comment by scottkosty** [comment]
@flatcap thanks for the quick reply!

> Please can you give `master` a try. Thanks.

Great, yes I will test in the next week or so and report back here. Thanks.

**Comment by scottkosty** [comment]
@flatcap I think things are better indeed. I still see "Sorting mailbox..." messages when I'm not sure why. But I think we can close this issue since I'm not sure if that's related.

**Comment by flatcap** [comment]
> things are better indeed

Great.

> I still see "Sorting mailbox..."

I'll have a think about that.

> I think we can close this issue

Thanks
