### ISSUE TITLE
Add placeholder to display the list of participants in a folded thread in `index_format`

### ISSUE THREAD

**Issue by guiniol** [neomutt/neomutt#171]
The `%F` placeholder in `index_format` shows the sender of the message (or its recipient if you are the sender). For folded thread, I propose a new placeholder to show all the participants in the thread.

There are a few points to decide.
1. Who are the participants? Only the senders? All the senders and recipients? Do we add cc's? I'm for senders + recipients + cc's.
2. How do we show the participants? I propose this priority: alias > name > email
3. How do we truncate the line? There could be a limit per participant, or only a limit on the line, and the last part could display the number of participants not shown: `flatcap, toogley, (+6)`. I'm for a limit on each participant. It could be set to 0 to have no limit.
4. How do we truncate names? Either initials (eg. `RR`) or full name (eg. `Richard Russ`) or truncate both first and last name (eg. `RicRus`). I think the last one is the best one (thanks @flatcap).
5. How do we display unfolded threads? Do we revert to `%F` behaviour (with aliases if available) or do we display the participants in the mail (instead of the thread)? I would display like to display the participants in the mail, but also somehow show the sender. Something like `flatcap: toogley, guiniol, (+6)`? But if you are the sender, how do we display it? Ideas welcome.

**Comment by toogley** [comment]
If i recall correctly, you know this feature from the sup mailclient. Do you want to add a picture showing what you like there? i think that would be helpful for how the UI would look like and/or improve the clarity for your wish.

**Comment by guiniol** [comment]
Indeed. Here is a screenshot:
![sup screenshot](https://camo.githubusercontent.com/b44946c1c3bec6d091406afe38f176a03a2ab231/68747470733a2f2f7261772e6769746875622e636f6d2f6d6b6c696e696b2f7375702d636f6c6f72736368656d652d776f6d6261742f6d61737465722f73637265656e73686f74732f696e6465782d766965772e706e67)

On the first line, you have a mail sent by yourself (name in parenthesis). The other lines show either one full name (only one sender) or a list of first name truncated if there are more than one sender.

**Comment by flatcap** [comment]
It's a useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
