### ISSUE TITLE
entire-thread jumps to first message in thread

### ISSUE THREAD

**Issue by anarazel** [neomutt/neomutt#1714]
## Expected Behaviour

It used to that showing an entire-thread (with notmuch configured), would fetch all the messages for the thread, keeping focus on the message for which the thread was fetched.

## Actual Behaviour

Now the thread is fetched, and the first message in the thread is focussed. Which makes it much harder to read responses etc, which is what I'm usually trying to do when using entire-thread. I have to resort to afterwards filtering with ~i, and then show all messages again. Pretty cumbersome.

## Steps to Reproduce

configure notmuch + mutt
bind 'entire-thread' do key (bind index,pager . entire-thread)
focus message that's in a thread, but *not* the first message in that thread
use entire-thread 

the thread will be fetched, and the first message in the thread will have the focus.

## How often does this happen?

Always

## When did it start to happen?

Bisected down to 918885f32db41a452c23379c62dd2a9a752930d1 by @gahr. Haven't dug deeper into the issue, but appears to have been an unintended side-effect.

**Comment by gahr** [comment]
Thanks for the detailed report and the bisect, @anarazel . Yep - that was totally unintended. I am not a notmuch user myself, so I must have missed some use case. I'll try and look into it.

**Comment by anarazel** [comment]
Quick note: I've debugged this, writing up explanation right now.

**Comment by gahr** [comment]
Cool - patches are welcome :)

**Comment by anarazel** [comment]
After a bit of debugging, I think the bug currently - the code has changed substantially since the commit pointed out above - resides in the OP_MAIN_ENTIRE_THREAD case of mutt_index_menu():

```C
        int oc = Context->mailbox->msg_count;
        if (nm_read_entire_thread(Context->mailbox, CUR_EMAIL) < 0)
        {
          mutt_message(_("Failed to read thread, aborting"));
          break;
        }
        if (oc < Context->mailbox->msg_count)
        {
          struct Email *oldcur = CUR_EMAIL;

          if ((C_Sort & SORT_MASK) == SORT_THREADS)
            mutt_sort_headers(Context, false);
          menu->current = oldcur->virtual;
```
One can see that `oldcur` is determined *after* the nm_read_entire_thread(). But the latter does a `mutt_mailbox_changed(m, MBN_INVALID);`, which ends up triggering a `mutt_sort_headers()` which in turn does `mutt_sort_threads()`. Thus, by the time `oldcur` is determined, it's already pointing to the start of the thread.

The reason that  918885f triggers this bug is that before that commit - even though it didn't change where `oldcur` is determined, is that previously `nm_read_entire_thread` didn't cause the thread to be recomputed. Therefore, `oldcur` would still point to the message whose thread was just fetched.

The obvious fix seems to be to just move `oldcur` a few lines up. I'll open a PR.

**Comment by anarazel** [comment]
> Cool - patches are welcome :)

There you go ;)

Btw, the fact that there's a `mutt_sort_headers` inside `nm_read_entire_thread()` (via `mutt_mailbox_changed()->ctx_mailbox_changed()->ctx_update()`, and then again in `OP_MAIN_ENTIRE_THREAD` seems superfluous as far as I can tell? I guess the index.c one ought to just be removed now:

**Comment by scottkosty** [comment]
I'm seeing this issue again on current master. Can anyone else reproduce? By the way, for oldish bugs, is it preferred to reopen them or to open a new issue and reference them?

**Comment by scottkosty** [comment]
@anarazel are you able to compile master (or the recent NeoMutt release) to see if you still see an issue? If not, the one I'm seeing might be separate. It would be good to know if there was a regression or not.

**Comment by scottkosty** [comment]
I think the issue I'm seeing is a different one. I'll investigate when I can.
