### ISSUE TITLE
mailto but do not open compose menu

### ISSUE THREAD

**Issue by Eluminae** [neomutt/neomutt#1717]
Hello all !

This questions has been asked many years before but I'm still stuck on a little rock.

```
[Desktop Entry]
Name=neomutt
GenericName=Mail Client
Exec=termite -e neomutt %u
Terminal=false
Type=Application
Categories=Utility;TextEditor;
StartupNotify=false
```

```
[Default Applications]
x-scheme-handler/mailto=neomutt.desktop
```

But the fact is that I fall into the index menu when neomutt starts.
Why am I not prompted for a "subject:" then dropped in my vim email tmp file ?

Ty by advance :D kiss

**Comment by flatcap** [comment]
Ah, I might have an idea.
I think `termite` is seeing it as `-e neomutt` and `%u` something else

Try:
```
Exec=termite -e "neomutt %u"
```

You might also want to add the [NeoMutt config](https://neomutt.org/guide/reference#abort-nosubject): `set abort_nosubject = yes`
to abort quickly if you click on something by mistake.

**Comment by Eluminae** [comment]
It's seems to be the good idea ! I got a little annoying problem

```
$ xdg-open mailto:contact@eddiebarraco.fr                                                                                                                                     
failed to parse command: Text ended before matching quote was found for ". (The text was "neomutt")

```

**Comment by Eluminae** [comment]
I'm trying to backslash additionnals quotes :D

**Comment by Eluminae** [comment]
I tricked my desktop entry using an intermediate script. I do not like this but it works.

How should I configure Exec to work with one line?

**Comment by flatcap** [comment]
Hmm... I don't quite know what's going on.
I _thought_ my `.desktop` was working with and without the quotes,
but it seems that the behaviour is cached.

**Comment by Eluminae** [comment]
My problem is termite that needs quotes. This behavior differ from other terminal emulators.
Waiting for them to implement a solution but this issue is old. Hoping !
