### ISSUE TITLE
'sidebar_whitelist' looks for the path of a virtual mailbox, rather than the friendly name

### ISSUE THREAD

**Issue by doweaver** [neomutt/neomutt#174]
From sidebar.c:352:

`    
if (mutt_find_list (SidebarWhitelist, sbe->buffy->path))
      /* Explicitly asked to be visible */
      continue;
`

If we have a virtual mailbox defined with:
'
virtual-mailboxes "Inbox" "notmuch://?query=tag:inbox AND NOT folder:Trash"
'

The path is "notmuch://?query=tag:inbox AND NOT folder:Trash". What we really want is the "desc", which is "Inbox".

Folder-based mailboxes don't appear to have a "desc", but it seems reasonable to me that we look for the path OR the desc, a la:

`    
if (mutt_find_list (SidebarWhitelist, sbe->buffy->path) || mutt_find_list (SidebarWhitelist, sbe->buffy->desc))
      /* Explicitly asked to be visible */
      continue;
`

**Comment by doweaver** [comment]
In retrospect, it doesn't make much sense to make a change in one patch that's really only relevant if another patch is loaded. Ugliness in config files > cross-polluted code.

**Comment by flatcap** [comment]
It's not a bad suggestion.
There are already plenty of places in the code where we have "#ifdef USE_NOTMUCH".
I'll re-open this issue for now and think about it.
