### ISSUE TITLE
Redrawing window after query_command is executed

### ISSUE THREAD

**Issue by Joshuao95** [neomutt/neomutt#1746]
Hi,

I'd like to use the interactive program fzf in my query_command, what I have actually works fine for producing an address to my query, however it leaves the display of neomutt broken.
Is there anyway to manually add a window redraw to the end of the query_command?

**Comment by flatcap** [comment]
Hi @Joshuao95 
You need the `<refresh>` command.
You can run it manually, any time, by pressing <kbd>Ctrl-L</kbd> (default mapping),
or you can add it to the end of a macro, e.g.
```
macro index,pager ,s "<enter-command>set invsidebar_visible<enter><refresh>" "Toggle sidebar"
```

**Comment by Joshuao95** [comment]
Hmm, I don't seem to be having much luck with those suggestions.

In the query prompt, Ctrl+L for me simply writes an actual "^L" character.
As well I can't seem to find anywhere to put the <refresh> command in a macro to achieve what I want.

I tried:
``` macro query <return> <refresh><return> ```
but that didn't fix anything.
I also tried
```macro editor <Tab> <complete-query><refresh>```
but instead of refreshing the screen once the query_command program returned, it just appended \<redraw-screen\> to the returned address.

I do understand this is a bit of an abuse of the intent of query_command, so I understand it's not supported, I was just hoping there would be some feature I could drag into the mess to help me out :)

**Comment by flatcap** [comment]
> In the query prompt, Ctrl+L for me simply writes an actual "^L" character.

Ah, sorry.  That's not a command line.
When you're looking at the Index, Pager, etc you can hit <kbd>Ctrl-L</kbd> to force a redraw.

> `macro editor <tab> <complete-query><refresh>`

Hmm... that's the same as I came up with, but it works for me.

**Comment by Joshuao95** [comment]
I suppose it has something to do with the interactive nature of fzf, I get the behaviour I described with
``` set query_command= "fzf -q %s" ```
for example.
Does <refresh> actually type the text "<redraw-screen> under the hood and it's expecting a command line or something?

**Comment by flatcap** [comment]
> Does `<refresh>` actually type the text `<redraw-screen>`

Hmm... interesting.  No.

`<redraw-screen>` **only** applies in the Pager (when viewing an email).
`<refresh>` is a generic function and applies in many places

(I hadn't noticed that the Pager had a separate 'clean-up' command before)

**Comment by benmaddison** [comment]
@Joshuao95 see comment https://github.com/neomutt/neomutt/issues/3#issuecomment-723575643 for a workaround to this issue

**Comment by Joshuao95** [comment]
Cheers Ben, good idea!
