### ISSUE TITLE
Autoviewed HTML mail is not quoted when replying

### ISSUE THREAD

**Issue by gadanidis** [neomutt/neomutt#1748]
## Expected behaviour

When using `w3m` to auto-view HTML email as plaintext, replying to the email should quote the text of the email.

## Actual behaviour

The text is not quoted, and all that appears is the below.

```
On Wed, Jun 19, 2019 at 06:46:56PM -0400, [name] wrote:
```
As a workaround, viewing the list of attachments and replying directly to the attachment from there (`v` then `r`) causes the content of the email to be quoted as expected.

## Steps to reproduce

1. Select an HTML-only email in the index, or open it in the pager.
2. Reply or group-reply to the email.

## How often does this happen?

Always, when replying to an HTML-only email.

## When did it start to happen?

~I just switched to NeoMutt from mutt 1.5.24, where quoting HTML email works as expected, so I don't know when the problem was introduced (assuming it is a problem and I'm not missing a config option that would fix this).~

Per my update below, the issue occurs in the current development version (building from master), but not in neomutt-20180716.

## NeoMutt version

```
NeoMutt 20180716-2125-b37a78
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.4.0-142-generic (x86_64)
ncurses: ncurses 6.0.20160213 (compiled with 6.0.20160213)
libidn: 1.32 (compiled with 1.32)
hcache backends: tokyocabinet

Compiler:
cc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --tokyocabinet

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR -I/usr/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls -gpgme -gss +hcache -homespool +idn +inotify -locales_hack -lua +meta 
  -mixmaster +nls -notmuch -openssl +pgp -sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```
## .muttrc and mailcap

Here are the portions of my .muttrc and mailcap files that are relevant.

.muttrc:
```
auto_view text/html
alternative_order text/plain text/enriched text/html     ## save html for last
```

mailcap:
```
text/html; /usr/bin/w3m -I %{charset} -T text/html; copiousoutput;
```

**Comment by cmonghost** [comment]
I built version 20180716 and replying to HTML-only email works as expected under that version, so I'll switch to that version for now. (I tried rebuilding again from master and the issue recurs.)

**Comment by gahr** [comment]
I can reproduce this. I also see the error `mailcap entry for type text/html not found`. Bisecting now....

**Comment by gahr** [comment]
[672a84d9c4110343ab4d43d542b0c0933365d023] looks like a potential culprit

**Comment by gahr** [comment]
@anarazel @flatcap does it make sense to fall-back to editor if a compose entry was not found for the mime type?

**Comment by scottkosty** [comment]
Just a note that I can reproduce this bug, although for me mutt freezes after "r" with a status message of "Including quoted message...". Reverting 672a84d fixes things for me.

**Comment by flatcap** [comment]
@gahr 
> does it make sense to fall-back to editor if a compose entry was not found for the mime type?

That sounds reasonable.

**Comment by anarazel** [comment]
> > does it make sense to fall-back to editor if a compose entry was not found for the mime type?
>  That sounds reasonable.

It does to me too - I'll try to come up with a PR.

**Comment by gahr** [comment]
@anarazel I have reverted 672a84d as it was causing troubles to several users. We would be happy to see https://github.com/neomutt/neomutt/issues/1748#issuecomment-504360466 implemented, though ;)
