### ISSUE TITLE
Create cache directory if it doesn't exist?

### ISSUE THREAD

**Issue by xaverdh** [neomutt/neomutt#1752]
I have `header_cache` and `message_cachedir` set to `~/.cache/mutt`, where `~/.cache` exists, but the `mutt` subdirectory does not. The directories used for mail body and header caching are not created by default, rather neomutt creates two files `mutt` and `mutt-lock` instead. Looks like a fallback of sorts to me. Is this intentional?

**Comment by xaverdh** [comment]
Ah ok, from the [mutt manual](http://www.mutt.org/doc/manual/#cache-dirs):
`If enabled, $header_cache can be used to either point to a file or a directory. If set to point to a file, one database file for all folders will be used (which may result in lower performance), but one file per folder if it points to a directory. `
So it seems the one-file database is indeed a fallback of sorts. It doesn't mention at all what happens when the path does not exist. I guess the default should be to create a directory, rather than falling back to the (lower performing) database scheme?

**Comment by gahr** [comment]
A non-existing path is indeed assumed as a missing file instead of a missing directory. Either has pros and cons, but I wouldn't change the default at this point.

**Comment by xaverdh** [comment]
Ok, if you don't want to change the default, then maybe this should be documented somewhere visible?

**Comment by gahr** [comment]
A small clarification: can you please confirm that the message cache directory `message_cachedir ` **is** created as needed while the header cache directory `header_cache` is not? This is what I can reproduce.
