### ISSUE TITLE
Reply stuck in "Including quoted message...."

### ISSUE THREAD

**Issue by hsanson** [neomutt/neomutt#1754]
## Expected Behaviour

Press r or R to reply a message should open my editor (vim) with the quoted message.

## Actual Behaviour

Editor is never open. I see a message at the bottom that says "Including quoted message..." and stays there until I kill neomutt with signal 15.

## Steps to Reproduce

I use virtual folders only. Some messages seem to work fine but most will get stuck when trying to reply.

## How often does this happen?

Seems to happen with multipart messages that have both plain and html versions.

## When did it start to happen?

- When I upgraded
  Which version did you use to use?
Sorry, I always use latest master branch so I do not remember the version I had before.

## NeoMutt Version

```
NeoMutt 20180716-2137-469d14
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.15.0-51-generic (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.12.0
hcache backends: lmdb

Compiler:
cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --prefix=/usr --notmuch --lmdb --ssl --sasl --gpgme

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo
  -gnutls +gpgme -gss +hcache -homespool +idn +inotify -locales_hack -lua +meta
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color
  +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version 

KDE Neon (latest)

* Were you using multiple copies of NeoMutt at once?

No

* Were you using 'screen' or 'tmux'?

Tmux

* Is your email local (maildir) or remote (IMAP)?

maildir (vfolder)

**Comment by sheoak** [comment]
I don't know if it's related but on my side, when I upgrade to git version and reply to a message, the content is gone (I have set include in my configuration).

**Comment by hsanson** [comment]
After a `git bisect` the problem started with commit:

    672a84d9c4110343ab4d43d542b0c0933365d023

    mime_lookup: use compose mailcap entries when replying 

    Use compose mailcap entries to format attachments when replying to a message

Below is my mailcap in case is useful for replicating the issue:

```
text/html; google-chrome %s & sleep 3; test=test -n "$DISPLAY"; needsterminal;
text/html; w3m -dump -o document_charset=%{charset} '%s'; nametemplate=%s.html; copiousoutput
#text/html; html2text -utf8 -style pretty %s; copiousoutput
application/ics; khal import %s; needsterminal
#application/ics; mutt-ics; copiousoutput
text/calendar; khal import %s; needsterminal
#text/calendar; mutt-ics; copiousoutput
```

**Comment by scottkosty** [comment]
I think this issue is a variant of #1748.

Random git tip below:

> * Which version did you use to use?
>   Sorry, I always use latest master branch so I do not remember the version I had before.

I find "git reflog" to be helpful in this case.

**Comment by hsanson** [comment]
Is it possible to get this commit 672a84d9c4110343ab4d43d542b0c0933365d023 reverted to fix this issue?  Everytime I update my neomutt I have to manually do this in order to use neomutt. This issues does hangs neomutt when replying emails with html attachments.

Reverting the commit fixes the issues and does not seem to affect any other part of neomutt:

```
git revert 672a84d9c4110343ab4d43d542b0c0933365d023
```

**Comment by gahr** [comment]
I reverted 672a84d.
