### ISSUE TITLE
Union mailboxes (several mailboxes that appear as one on the same screen)

### ISSUE THREAD

**Issue by mjsir911** [neomutt/neomutt#1755]
Firstly, thank you for properly implementing accounts now, this is definitely a useful feature.

## What would you like to be able to do?

My specific use case for accounts, coming from a previous gmail user, is that I would like to display all mailboxes on the same screen.

## Have you tried any alternative methods?

My current work-around for this is a combination of offlineimap & notmuch, but it would be nice if I could just do all that straight from neomutt.

Thanks again for this wonderful progress

Related: #1739

**Comment by flatcap** [comment]
In theory, this should be pretty simple.

The 'Union' mailbox would open each underlying mailbox and relay actions from the user.
(This is how I'd like to see the Notmuch mailbox working)

Currently, there's too much mixing of layers between the display and data (and this is proving hard to break up).  This means that Notmuch is a complex mix of delegation and doing things itself.

Adding the Account objects helps to break up some of the dependency problems, but the next step is huge.  I have to break apart the GUI data (the "View") from the Mailbox (the Data or "Model").

**Comment by Slider-Whistle** [comment]
Was this ever implemented?

**Comment by flatcap** [comment]
@Slider-Whistle 
Nope.  Not a chance.

Everyone wants advanced features, but nobody's prepared to help (even with easy tasks).

**Comment by Slider-Whistle** [comment]
Okay, just as long as it's clear. I thought it'd be easier to follow
threads if Sent mail appeared in your Inbox. Since I use mailidir, what
I'll try instead is symlinking both of them to a new directory.

Thanks for the response
