### ISSUE TITLE
Reading all mailboxes on startup

### ISSUE THREAD

**Issue by DoktorScience** [neomutt/neomutt#1761]
I've recently come across NeoMutt. I encounter the problem below, for which I couldn't find any mention in the documentation. I use mbsync to retrieve emails from IMAP servers for two different accounts, and store them in separate directories (each account has a different directory, and each folder in those accounts is mapped to a subdirectory). NeoMutt is configured to read these (Maildir format), and will thus display inbox, archive, drafts and what-not folders as different mailboxes.

I use the sidebar module to display these mailboxes in a convenient way, but, on startup, it seems that NeoMutt will only load the default mailbox, such that in the sidebar, the only mailbox that doesn't appear empty is the default one (the rest have zero mail count, updated only after I load them).

Since, when changing mailboxes, the number of mails in a mailbox seem to be "cached", I was wondering if any mechanism would allow "pre-loading" the mailboxes so that the number of mails is already displayed in the sidebar?

Thanks a lot!

**Comment by tcpaiva** [comment]
I faced the same problem as yours and it was solved with `mail_check_stats`, docs [https://neomutt.org/guide/reference.html#mail-check-stats](here).

**Comment by DoktorScience** [comment]
Thank you very much for your answer, exactly what I was looking for. Solved!
