### ISSUE TITLE
Variable index_hint uninitialized

### ISSUE THREAD

**Issue by fekir** [neomutt/neomutt#1767]
Function `mutt_index_menu`, the variable `index_hint` is initialized if `Context && !attach_msg`.

On line 1721, if `query_quadoption(C_Quit, _("Quit NeoMutt?")) == MUTT_YES`, `!Context || ((check = mx_mbox_close(&Context)) == 0)` is false and `(check == MUTT_NEW_MAIL) || (check == MUTT_REOPENED)` the function `update_index` is called with parameter `index_hint`.

As one of the condition is `query_quadoption(C_Quit, _("Quit NeoMutt?")) == MUTT_YES`, maybe updating the index does not make much sense, otherwise, it could be possible to unconditionally initialize `index_hint` to `((Context->mailbox->vcount != 0) && (menu->current >= 0) && (menu->current < Context->mailbox->vcount)) ? CUR_EMAIL->index : 0;`

Similar consideration holds for line 1857 too.

**Comment by flatcap** [comment]
> `index_hint`

Ugh!  An ugly hack to workaround poor design.
My [magical plans](https://github.com/neomutt/neomutt/issues/1326#issuecomment-416914778) for the future would eliminate the need for this variable.

> index_hint uninitialized

Let's start with `int index_hint = 0;`

In both your examples, we probably don't care about the cursor position any more,
but if you'd like to add some initialisation, to be certain, that'd be good.

Thanks.
