### ISSUE TITLE
What's the purpose of our Wiki?

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#177]
Currently, we have nowhere defined exactly what should be placed in the Wiki and what definitly not. I'd like to define that in this Issue.

**Note**: Please also comment, if you like information (like the introduction of our project) to be placed in two locations. Like having the introduction on both the wiki and our README. If i estimate our documentation problem correctly, we can automate that away.
## introduction of our project

At the moment, the [default wiki page](https://github.com/neomutt/neomutt/wiki) gives an introduction to the whole neomutt project. I don't consider this as very helpful - we have this kind of introduction already on the website and in our README.md. I guess its quite unlikely that people will see our wiki page before the README.md, people would have to follow a specific link to the wiki to see the wiki introduction first, whereas  otherwise they will see the README first.
## Alternative-Release-Procedures

I merged the wiki page into our [Github/devel part on our website](https://www.neomutt.org/devel/github.html) some time ago. Before my change, there was already a similar description, so i thought it would be useful. Afterwards, i deleted the whole page on the wiki, so I guess someone wants it to be there.

So, my Questions are:
- What should be in your opinion be placed onto the wiki?
- What do you think about the existing pages?
- Should some wiki-pages merged somewhere else?

**Comment by pickfire** [comment]
@toogley I found the wiki working fine. What's wrong with it? If you have any idea, just improve it.

**Comment by toogley** [comment]
The problem is mainly duplicated information on the wiki and on other places. If we change/improve e.g. the website, we have to apply that change *manually* on the wiki too.

Generally, i was unsure if the duplication is really wanted/useful.

Am 5. Oktober 2016 15:27:33 MESZ, schrieb Ivan Tham <notifications@github.com>:
>@toogley I found the wiki working fine. What's wrong with it? If you
>have any idea, just improve it.

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by flatcap** [comment]
I've been using the wiki as a bit of a dumping ground, while I decide what to do with things.

As wikis are best for collaborating, it makes sense for docs to be created and developed there, cooperatively.  Then when the doc's done (and stable), promote it to the website.

**Comment by toogley** [comment]
@flatcap But then i don't think placing a NeoMutt welcoming/introduction page there is very useful - it gives the impression that the wiki is a place for "stable" information (i.e. i felt initially like that). However i understand and agree with the rest of your point.

**Comment by flatcap** [comment]
> But then i don't think placing a NeoMutt welcoming/introduction page there is very useful

Fair point.

I've scrapped the front page (just a redirect now) and created an empty sidebar to hide the list of pages.
(the pages are still there, for now).

**Comment by pickfire** [comment]
Well there is also mutt's wiki. It will confuse which doc is the upstream, like doc/, mutt's wiki, neomutt's wiki, neomutt's website.

**Comment by toogley** [comment]
@pickfire Good point. Do you have an idea how we can remove confusion in that regard?

**Comment by pickfire** [comment]
I think I am not that experienced to say about this but generally, one upsteam doc would be nice.

**Comment by toogley** [comment]
Closing this, as the wiki is disabled.
