### ISSUE TITLE
MIME `application/pdf` file not included in counting of attachments when inline

### ISSUE THREAD

**Issue by tcpaiva** [neomutt/neomutt#1782]
## Expected Behaviour

After configuring neomutt with 

```
attachments   +I application/pdf
```

neomutt should include an inline pdf file in the attachments counting.

## Actual Behaviour

`~X` does not include the inline PDF file in the counting 

## Steps to Reproduce

With at least one email with a pdf attached as inline, try to limit to emails with attachment (`~X 1-`). That email will not show up in the results of the limit.

It is worth mentioning that the PDF file is still recognized normally as attachment by neomutt:

```
[-- Attachment #1: <filename> --]
[-- Type: application/pdf, Encoding: base64, Size: 7.9M --]
```

Invoking the PDF file using mailcap works as expected.

I tried with more general rules like 

```
attachments   +I */.*
```

but the result didn't change for the inline PDF file (I was able to see changes in the behavior of neomutt related to other files, however, as expected).

## How often does this happen?

- Always

## When did it start to happen?

From what I was able to check, this happens also for mutt. I hope it is not a configuration problem on my side. I tried to make sure it was not the case.

## NeoMutt Version

NeoMutt 20180716

## Extra Info

* Operating System and its version

Ubuntu 19.04

* Were you using multiple copies of NeoMutt at once?

No

* Were you using 'screen' or 'tmux'?

No

* Is your email local (maildir) or remote (IMAP)?

Local (maildir via isync)

**Comment by gahr** [comment]
It works for me:

I sent myself an email with an inline application/pdf attachment . Adding `attachments +I application/pdf` makes the message show up in `l ~X 1`.

Here's my test email:

```
Fom gahr@gahr.ch Fri Aug 23 15:32:49 2019
Date: Fri, 23 Aug 2019 15:32:48 +0000
From: Pietro Cerutti <gahr@gahr.ch>
To: gahr@gahr.ch
Subject: Inline PDF
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="mtk43en7jdzbakag"
Content-Disposition: inline

--mtk43en7jdzbakag
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Disposition: inline

Inline PDF

--mtk43en7jdzbakag
Content-Type: application/pdf
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable

test=0A
--mtk43en7jdzbakag--
```

Can you please double check your `attachments` list, try with my email above, and report back? Thanks!

**Comment by tcpaiva** [comment]
Indeed, it works for simple attachment structure with inline pdf. Thanks for pointing this out. The following inline pdf is not recognized as attachment even with `attachments +I application/pdf`, though.

![image](https://user-images.githubusercontent.com/4095847/64618527-6b54ca80-d3ae-11e9-8fee-7a67e0a65c0c.png)

**Comment by gahr** [comment]
Yeah a quick glance at the code suggests that it counts only [toplevel](https://github.com/neomutt/neomutt/blob/master/mutt_parse.c#L229) parts.

**Comment by tcpaiva** [comment]
Hi, @gahr . Thanks for your help. 

In the manual, there is the following statement as an example in `7. Attachment Searching and Counting`:

```
# These two lines make NeoMutt qualify MIME containers. (So, for example,
# a message/rfc822 forward will count as an attachment.) The first
# line is unnecessary if you already have "attach-allow */.*", of
# course. These are off by default! The MIME elements contained
# within a message/* or multipart/* are still examined, even if the
# containers themselves don't qualify.
```

If I understand it correctly, the inner element should also be counted, right?

PS: I believe `attach-allow */.*` means `attachments +A */.*` or `attachments +I */.*`

**Comment by gahr** [comment]
/me has little clue, sorry... this requires deeper investigation as per why that `MUTT_PARTS_TOPLEVEL` flag is there, and what happens if we remove it. If you want to experiment on a branch, please feel very welcome to :)

**Comment by flatcap** [comment]
@tcpaiva Have you tested the fix, yet?

**Comment by tcpaiva** [comment]
Sorry for the delay, @flatcap ! Just did! The inline pdf file is now recognized as an attachment. Thank you all very much for looking into this and changing from the previous behavior. =)
