### ISSUE TITLE
Clean the NeoMutt Build

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#179]
_tl;dr_ keep the compiler quiet

Some combinations of configure options cause the compiler to complain.
Most of the warnings are about unused variables.
These can often be fixed by wrapping the variable in a #ifdef block.

Some of the other warnings may require a bit more thought.

The warnings aren't a problem, but they could make a real problem harder to see.

I'd like you to fix the build warnings.

To save a lot of time, I recommend installing `ccache` (a compiler cache).
To test all the build configurations, you can use: [neomutt-test-configs.sh](https://github.com/neomutt/neomutt/files/509638/neomutt-test-configs.sh.txt)

---

**Easy tasks would be perfect for someone new to NeoMutt.**
You won't need to write lots of code, and you won't need any previous knowledge
of the NeoMutt code.  Obviously, you will need to be able to write C code :-)

**Easy tasks also come with a mentor** -- a NeoMutt project member -- who will help
you learn what you need to complete the work.

If you're interested in having a go, leave a comment or speak to us in our
IRC channel: #neomutt on irc.freenode.net

Thank you :heart:

**Comment by darnir** [comment]
I can mentor / help anyone who wishes to look into this. Apart from some idea about the NeoMutt codebase, I also have a decent understanding of the entire build toolchain

**Comment by pickfire** [comment]
Hi, I am a bit new to the codebase but I am not going to take up on this because I just want to see how this is done. I will appreciate if anyone bumps me about this issue.

**Comment by flatcap** [comment]
You will get build warnings if you run `./configure` with these combinations of options
- [ ] --with-included-gettext
- [ ] --without-wc-funcs
- [ ] --disable-fcntl --disable-iconv --disable-nls --with-included-gettext --without-idn --without-wc-funcs --disable-pgp --disable-smime
- [ ] --with-regex
- [ ] --enable-pop --enable-imap --enable-smtp --enable-debug --enable-flock --enable-nfs-fix --enable-mailtool --enable-locales-fix --enable-exact-address --with-homespool --with-domain --with-regex --enable-sidebar --enable-notmuch --enable-gpgme --with-mixmaster
- [ ] --with-ssl --enable-pop
- [ ] --with-ssl --enable-imap
- [ ] --with-ssl --enable-smtp
- [ ] --with-slang
- [ ] --with-nntp
 
(tested with 2016-10-03)

**Comment by kdave** [comment]
Warning: the build config script calls `git clean -xdfq`, any files not tracked in git will be lost (including the script itself if you run it from the neomutt source directory).

**Comment by flatcap** [comment]
@kdave Thanks.  I've added your warning to the text, above.

> including the script itself

hehe, sorry :-)

**Comment by flatcap** [comment]
There are only a few warnings left.
They are where return values from libraries are being ignored.
Each of them would require quite a bit of work.
