### ISSUE TITLE
Neomutt does not follow symlink when invoking sendmail

### ISSUE THREAD

**Issue by wzel** [neomutt/neomutt#1794]
In my `.muttrc`, I set `sendmail` option to point to a symlink to an executable. With that setting, an attempt to send an e-mail was resulting in an error. The error code was 255, if I remember correctly. Once I set `sendmail` directly to the executable, instead, the problem dissapeared. I suspect that neomutt does not follow symlinks when invoking a `sendmail` executable.

**Comment by gahr** [comment]
Was the name of your symlink `sendmail`? On some systems, `sendmail` itself is a symlink to `mailwrapper`, whose behaviour differs based on the name it was invoked with. If you name your symlink something mailwrapper doesn't understand, that might lead to problems.

**Comment by wzel** [comment]
No, I use msmtp. The problem is on GuixSD. That's why I care about using the symlink.

**Comment by roccoblues** [comment]
Hi, I'm trying to cleanup some older issues here. Can you still reproduce this behavior with the latest version? Thanks!
