### ISSUE TITLE
For some freezing bugs, neomutt cannot be terminated with `ctrl+c` or `ctrl+\`

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#1795]
I'm currently affected by #1748, and neomutt frezes with the status message "Including quoted message...". The actual problem is being discussed here, but is there a separate bug which that it is not possible to exit with `ctrl+c` or `ctrl+\`? For example, is neomutt incorrectly blocking interrupt signals or is the handler not working as expected? It seems neomutt interrupts `ctrl+c` to ask if the user wants to exit. Perhaps this depends on the terminal emulator. I'm using gnome-terminal.

I have no idea if this is a concern or not, but I was surprised that I needed to either close the terminal tab from gnome-terminal or kill the process the command line. That said, I don't know much about signal processing. If it's not a concern, please close this issue. Also, I don't know if this could be an upstream issue.

**Comment by flatcap** [comment]
Whatever the terminal, <kbd>Ctrl-C</kbd> should be causing a `SIGINT` signal.

Finding out where in the code it's freezing would be very useful.

Next time it hangs, please can you get a backtrace.
You can attach `gdb` to a running process using its process id, e.g.

`gdb --pid $(pidof neomutt)`

Thanks.

**Comment by scottkosty** [comment]
I'll give that a shot next week and report back.

**Comment by scottkosty** [comment]
I haven't gotten to this issue, but haven't forgotten about it. Also, the commit causing the original bug where I saw this was reverted, so I don't think it's high priority. Note to myself: to reproduce, perhaps I will need to revert 55392f6c.

If anyone views this issue as high priority, let me know and I will be happy to bump it up on my todo list. Otherwise, it might take me a while to get to it.

**Comment by scottkosty** [comment]
I'm going to close this since the original bug that triggered it was fixed. If I can reproduce with a new use case, I'll reopen. Let me know if you think this is important and want me to revert the fix to be able to reproduce and then investigate.
