### ISSUE TITLE
Forgotten Attachment Improvement

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#180]
This feature checks the body of the mail using a regex, e.g. "attach(|ment)"
If the email contains a match, but there's no attachment, notify the user.

This part works fine.  However, due to a bug in the code, the email is still
checked even if the feature is disabled:
```
set abort_noattach = no
```

This simply means that the code in `send.c` needs refactoring.
Look in send.c for the call to `mutt_search_attach_keyword()` in `ci_send_message()`

Additionally, I'd like you to change the search so that it ignores quoted text.
Any lines beginning with the text in `$indent_string` should be ignored.

---
**Easy tasks would be perfect for someone new to NeoMutt.**
You won't need to write lots of code, and you won't need any previous knowledge
of the NeoMutt code.  Obviously, you will need to be able to write C code :-)

**Easy tasks also come with a mentor** -- a NeoMutt project member -- who will help
you learn what you need to complete the work.

If you're interested in having a go, leave a comment or speak to us in our
IRC channel: #neomutt on irc.freenode.net

Thank you :heart:

**Comment by nuclearsandwich** [comment]
I have a plane flight this afternoon where I'll be taking an initial crack at this. Discussing the particulars with flatcap in IRC.
