### ISSUE TITLE
couldn't execute "xmlcatalog": no such file or directory

### ISSUE THREAD

**Issue by Rockenstien** [neomutt/neomutt#1804]
I was running the configure script and everything was running nice then this popped out, I have been searching for the solution for 3 hours. I am a biggest noob you could ever find

**Comment by flatcap** [comment]
> I have been searching for the solution for 3 hours

Sorry about that.

> xmlcatalog

That's checking for dependencies for the docs.
They're in DocBook format (xml), so you'll need to install some packages (depending on your distro):
- `libxml2` or `libxml2-utils`
- `docbook-dtds` or `docbook-xsl`

OR, you can just **not** build the docs:

`./configure --disable-docs ...`
