### ISSUE TITLE
header_cache doesn't save/restore organization properly

### ISSUE THREAD

**Issue by speed47** [neomutt/neomutt#1808]
## Expected Behaviour

hcache is able to save and restore the `Organization` envelope field of emails, so that the `%W` modifier of `index_format` is not empty when cache is used.

## Actual Behaviour

When an e-mail first appears in a Maildir folder, if %W is used, the Organization field is parsed properly and appears on the index. However once the corresponding hcache is saved on disk, and restored later, %W comes back empty.

## Steps to Reproduce

The header_cache configuration parameter is set, and it contains the %W modifier.
The default berkeley db format is used for hcache.

Then, a new email arrives and is stored as a file in a Maildir folder. When this folder is opened in Neomutt, the %W field is correctly parsed and displayed. However if the folder is reopened, then any %W occurence is replaced by an empty string.

Additional info:
- When the header_cache configuration parameter is commented, the bug can't be reproduced.
- Trying this on a folder with just one e-mail, then hex-editing the resulting bdb file (I don't have a bdb editor at hand), it doesn't seem that the value of the Organization field is present. 
- We seem to be missing a `serial_dump_char(env->organization, ...)` after this line:
https://github.com/neomutt/neomutt/blob/a237451ddf17e2109422239f62713085d4b6d740/hcache/serialize.c#L502

## How often does this happen?

Always

## When did it start to happen?

Since I started to add the `Organization` field in my emails through a maildrop rule.
As I wasn't using this feature before, it might have been broken for a while.

## NeoMutt Version

```
NeoMutt 20180716-2137-469d14
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 3.13.0-165-generic (x86_64)
ncurses: ncurses 5.9.20140118 (compiled with 5.9.20140118)
libidn: 1.28 (compiled with 1.28)
hcache backends: bdb

Compiler:
cc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --disable-doc --bdb --mixmaster --gnutls --locales-fix

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR -I/usr/include -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  +gnutls -gpgme -gss +hcache -homespool +idn +inotify +locales_hack -lua +meta 
  +mixmaster +nls -notmuch -openssl +pgp -sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
Ubuntu 14.04
* Were you using multiple copies of NeoMutt at once?
No
* Were you using 'screen' or 'tmux'?
Yes, screen
* Is your email local (maildir) or remote (IMAP)?
Maildir

**Comment by gahr** [comment]
Sounds fair - we just need to make sure to tweak here or there to make sure the current header caches are invalidated. @speed47 do you want to take a chance at implementing this feature?

**Comment by speed47** [comment]
I'm running a modified version of the code that seems to work, the invalidation bit is missing though (and it's critical or we get the expected segfault if previous cache files are here).

We don't seem to have a ready-to-use invalidation function for the cache, that would for example be triggered by a version change in the metadata, or do we?

**Comment by gahr** [comment]
Right, [BASEVERSION](https://github.com/neomutt/neomutt/blob/master/hcache/hcachever.sh#L3) will do it.

**Comment by gahr** [comment]
@speed47 I have pushed some docs on how the hcache works here: https://github.com/neomutt/neomutt/commit/7f0d11c5a56cec27d117593588ccb723d0d4f59c

**Comment by speed47** [comment]
> 
> 
> Right, [BASEVERSION](https://github.com/neomutt/neomutt/blob/master/hcache/hcachever.sh#L3) will do it.

Exactly, that's what I inferred from the code, also thanks for the additional comments, this'll help future contributors looking at hcache.

I've been running the #1811 build since 24 hours, cache was invalidated as expected and %W is always present.
