### ISSUE TITLE
Unable to rebind 'G' key for index

### ISSUE THREAD

**Issue by haximilian** [neomutt/neomutt#1815]
## Expected Behaviour

Running the command `:bind  index G last-item`, and then pressing `?` while looking at my mailbox's index should display "G  last-item", and pressing 'G' should move the cursor to the last item in my mailbox.

## Actual Behaviour

After running the command, `?` still shows "G: imap-fetch-mail", and pressing 'G' while looking at my mailbox does not appear to be doing anything.

## Steps to Reproduce

1. Configure neomutt to use a single Gmail account via IMAP
2. Open neomutt
3. Run the command `:bind index G last-item`
4. Attempt to view the binding by pressing `?`
5. Attempt to use the binding by pressing `G`.

## How often does this happen?

Always

## When did it start to happen?

When I installed neomutt for the first time recently.

## NeoMutt Version

```
NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.2.9-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 9.1.0 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

## Extra Info

* Operating System and its version
Arch Linux (rolling, up to date)
* Were you using multiple copies of NeoMutt at once?
Nope
* Were you using 'screen' or 'tmux'?
tmux
* Is your email local (maildir) or remote (IMAP)?
Remote (Gmail IMAP)

## NOTE
Like I mentioned above, I am **very** new to neomutt, so there's a decent chance that I've just made some stupid mistake.

**Comment by haximilian** [comment]
# UPDATE
I solved my issue: I was trying to bind  'G' to `last-item`, not `last-entry`. I'm closing this issue, although I do think neomutt should have at least given me an error or something, instead of just failing to bind for seemingly no reason.

**Comment by flatcap** [comment]
Glad you got it sort out.
You'll be glad to hear that we've added an error message in the development version:
- Function 'last-item' not available for menu 'index'
