### ISSUE TITLE
set variable = $default

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#182]
In NeoMutt, you can set variables by typing

```
:set VARIABLE_NAME = VALUE
```

When you set a variable, you can type `<tab>` after the equals sign to get the current value.

I'd like you to add a new magic token: `$default`

```
set VARIABLE_NAME = $default
```

This will set the variable to its default value, as defined in the NeoMutt code (init.c).

Additionally, the text stored in the history file will be the actual default value, not the string `$default`.

---

**Easy tasks would be perfect for someone new to NeoMutt.**
You won't need to write lots of code, and you won't need any previous knowledge
of the NeoMutt code.  Obviously, you will need to be able to write C code :-)

**Easy tasks also come with a mentor** -- a NeoMutt project member -- who will help
you learn what you need to complete the work.

If you're interested in having a go, leave a comment or speak to us in our
IRC channel: #neomutt on irc.freenode.net

Thank you :heart:

**Comment by aetherith** [comment]
I'd be interested in giving this a shot. I haven't done a lot of C development outside of embedded platforms and school projects but I'd love to get more involved. I reckon I'll fork the repo and see what I can put together.

**Comment by flatcap** [comment]
Hi @aetherith, welcome to NeoMutt.

First, let's get some code building.  I see you've forked the repo.  In the empty repo.
```
autoreconf -i
./configure --enable-debug [OTHER-OPTIONS]
make
```
I tend to use `cgdb` to debug -- the curses version of GNU Debugger.
Debugging a curses app is fun...  You'll need two windows.

**Window 1**:
```bash
$ tty
/dev/pts/3
# Copy this string into cgdb (below)
$ sleep 1d
# Sleep for a day
```

**Window 2**:
```
$ cgdb mutt
(gdb) tty /dev/pts/3
(gdb) run [MUTT-OPTIONS]
```

You can control mutt in window 1.
Ctrl-C in window 2 will interrupt the debugger (to set breakpoints, etc)  `c<enter>` to continue.

Have a look around in the code, in particular:
- `functions.h` { "enter-command", OP_ENTER_COMMAND, ":" },
  - This is where `:set` begins
- `curs_main.c` switch ... OP_ENTER_COMMAND
  - When you're in the index, this code is active
- `pager.c` switch ... OP_ENTER_COMMAND
  - When you're in the pager, this code is active
- `init.h` and `globals.h`
  - These define mutt's variables, their names, types, default values

**Comment by aetherith** [comment]
@flatcap So I finally had some time to look into this issue without work getting in the way. I think I've got an ok handle on how the program runs a set command and I'm currently working to understand the parse_set() function in init.c. However, because of the mixed indentation the function is a bit of a mangle to read. Is there an opinion on formatting? Should I attempt to correct the whitespace in just that function?

**Comment by flatcap** [comment]
Hi @aetherith, welcome back :-)

> mixed indentation

Yes, twenty years of code has left the code in a bit of a mess.

> Is there an opinion on formatting

Yes and it's one of the many documents I haven't written yet.
Indent is 2 spaces, {} on a new line and no tabs.

> I'm inclined toward Linux kernel style

Tab indents, nestled {}?  Me, too :-)
For now, though, we're dependent on upstream Mutt.

> Should I attempt to correct the whitespace in just that function?

It's tempting to "just clean up a bit" -- I'd **really** love to -- but we're still taking commits from upstream and every little whitespace change will make merging harder.  So, try to keep the changes to a minimum.

> I'm currently working to understand the parse_set() function in init.c

Take notes as you go and feel free to ask lots of questions.
We're starting to add comment blocks to all functions, so you can leave notes for the next person.

**Comment by guyzmo** [comment]
This is already implemented in mutt:

```
:reset variable_name
```

cf documentation: https://www.neomutt.org/guide/configuration.html#set

**Comment by guyzmo** [comment]
…though [your explaination above][0] should make into an FAQ about dev of neomutt.

[0]:https://github.com/neomutt/neomutt/issues/182#issuecomment-253385220

☺

**Comment by flatcap** [comment]
@guyzmo 

> :reset variable_name

Oh, dear.  Thanks for pointing that out.  I really had no idea.
Nor is it the first feature request for something already in Mutt!

> your explaination above should make into an FAQ about dev of neomutt

Yes, it's already in my as-yet-incomplete development guide.
Docs take **SO** long to get right (and I like to get them right).
