### ISSUE TITLE
Release: Makefiles

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1835]
The build machinery contains quite a few lists, e.g. files to be compiled.

- `auto.def`
- `contrib/Makefile.autosetup`
- `doc/Makefile.autosetup`
- `Makefile.autosetup`
- `po/Makefile.autosetup`
- `test/Makefile.autosetup`

Review the file lists:

- Unwrap long lists
- Sort them alphabetically
- Wrap them back to 80 characters

**Comment by ocelotsloth** [comment]
I can take this one.

**Comment by ocelotsloth** [comment]
The real question here is what exactly passing an array to if in TCL actually does, but do you want statements like https://github.com/neomutt/neomutt/blob/14b262b0afd69a824abf669c6052ec1fa5b2650c/auto.def#L502 to be alphabetized as well? I'm uncertain if that changes the actual execution or not.

**Comment by ocelotsloth** [comment]
In doc/Makefile.autoconfig there are a couple different formats being used for file lists in the rules.

The first is one file/rule per line:

https://github.com/neomutt/neomutt/blob/14b262b0afd69a824abf669c6052ec1fa5b2650c/doc/Makefile.autosetup#L49-L52

The second collapses the list and wraps to 80 chars:

https://github.com/neomutt/neomutt/blob/14b262b0afd69a824abf669c6052ec1fa5b2650c/doc/Makefile.autosetup#L90-L92

Do you want to standardize the format? If so which would you prefer?

**Comment by flatcap** [comment]
> I can take this one.

Thanks

> what exactly passing an array to if in TCL actually does

It's checking whether the listed functions exist in the system libraries.

> to be alphabetized as well?
> I'm uncertain if that changes the actual execution or not.

Hmm, yes that should be safe.
Let's give it a try (I'll take the blame if it goes wrong :-)

> In `doc/Makefile.autoconfig` there are a couple different formats being used for file lists in the rules.

Ah, yes.  That's not very consistent.
Let's go for the wrapped version

**Comment by gahr** [comment]
> Sort them alphabetically

Can we decide on a locale? [This](https://github.com/neomutt/neomutt/commit/d20ba87207a981be4066234b258fc01859d4954c#diff-df4b625c5dbbfcd88a1cdc4dc0aa832fL113-R109) suggests a C sorting, while en_GB would suggest the previous version. I'm not being pedantic, just trying to avoid back and forth depending on who sorts :)

**Comment by gahr** [comment]
> @ocelotsloth The real question here is what exactly passing an array to if in TCL actually does

The `[foo bar baz]` syntax in Tcl has procedure call semantics: you're calling the procedure `foo` with arguments `bar` and `baz`. No arrays involved :)

**Comment by flatcap** [comment]
Updated notes to mention sorting in the `C` locale.
