### ISSUE TITLE
Release: Mirrors

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1836]
We have several mirrored repos in the NeoMutt organisation.
Let's keep them in-sync with their upstreams.

:heart: **Create a script** to pull/push each of the repos and keep it in the `management` repo.

| NeoMutt                                  | Upstream                                     |
| :--------------------------------------- | :------------------------------------------- |
| https://github.com/neomutt/acutest       | https://github.com/mity/acutest              |
| https://github.com/neomutt/aur-docker    | https://github.com/WhyNotHugo/docker-makepkg |
| https://github.com/neomutt/autosetup     | https://github.com/msteveb/autosetup         |
| https://github.com/neomutt/homebrew-core | https://github.com/Homebrew/homebrew-core    |
| https://github.com/neomutt/upstream-mutt | https://gitlab.com/muttmua/mutt.git          |
| https://github.com/neomutt/vim           | https://github.com/vim/vim                   |

## Sync 3<sup>rd</sup>-Party Source

Check that we have the latest 3<sup>rd</sup>-party source:

- [x] Acutest
- [x] Autosetup

**Comment by ocelotsloth** [comment]
See PR here: https://github.com/neomutt/management/pull/4

**Comment by flatcap** [comment]
@gahr 
Please can you check that Autosetup is up-to-date (and list the steps you perform).

**Comment by gahr** [comment]
[done](5baaf0b8c4bad4e761c0cc517f7fe7fc97f0bb91). Autosetup is installed by running `/path/to/where/you/cloned/autosetup/autosetup --install` from the root of the NeoMutt repo.

**Comment by roccoblues** [comment]
@flatcap is this still relevant?

**Comment by flatcap** [comment]
nope :-)
