### ISSUE TITLE
Add New Hooks for Startup and Shutdown

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#184]
Create `startup-hook` which is called when all the config has been read, just before the first mailbox is opened.

Create `shutdown-hook` which is called after the mailbox has been closed, just before NeoMutt closes.

These hooks would be very useful for people using notmuch -- to synchronise things before they start and after they've finished

---

**Easy tasks would be perfect for someone new to NeoMutt.**
You won't need to write lots of code, and you won't need any previous knowledge
of the NeoMutt code.  Obviously, you will need to be able to write C code :-)

**Easy tasks also come with a mentor** -- a NeoMutt project member -- who will help
you learn what you need to complete the work.

If you're interested in having a go, leave a comment or speak to us in our
IRC channel: #neomutt on irc.freenode.net

Thank you :heart:

**Comment by pickfire** [comment]
Haha, I am interested in this issue. :)

**Comment by ThomasAdam** [comment]
Right, I've implemented these two hooks.  Will create the branch and add code there in due course, hopefully later on this evening.
