### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1843]
This is an overview of the upcoming Release.
Any questions or suggestions are welcome here.

Making a release can take quite a bit of time.
I've broken down all the tasks that I perform into separate issues:

**Easy**:
- Syntax Highlighting #1837
- Code Testing #1829
- Doxygen #1833
- Mailmap #1834
- Makefiles #1835
- Mirrors #1836
- Translations #1841
- Authors #1828

**Hard**:
- NeoMutt Guide (Website) #1832
- Merge Upstream Changes #1842
- Coverity #1830
- Notes #1839
- Commits #1844

**Post-Release**:
- Distros #1831
- Tagging #1840
- Notifications #1838

If you can think of a way to automate any of these tasks, I'd love to hear it.

(Useful browser plugin: [GitHub Issue Link Status](https://github.com/fregante/github-issue-link-status))

## Project

These issues will be tracked using a [GitHub Project](https://github.com/orgs/neomutt/projects/2).

Some tasks will need doing twice.
Once in preparation for the release and a second time at/after the release.
(typically, the second time will be much simpler and quicker)

**Task status**:
- To Do
- In Progress
- Once - Tasks that will need doing again
- Done

## Extra Tasks

So far, the project only contains the tasks required to make a Release.
We may want to add these issue:

- #1612 Empty / Non Mailboxes no longer shown in sidebar
- #1805 free(): double free detected in tcache 2
- #1824 Continue tidying use of time
- #1825 Add ability to limit levels hidden with toggle-quoted command

What else should be fixed in this release?

## Release Notes

How should we describe this release to the users and packagers?

@gahr has noted:
> we make it *very* clear that we are doing big changes and we're not bullet proof
> we also make it *very* clear that we're very unlikely to damage anyone's storage
> so, if you don't mind occasional harmless crashes, we encourage to use the latest release
> then it'll be on users to push distros to adopt, based on the stable-ness users perceive

What do you think?

**Comment by hvkls** [comment]
#1629 Bogus "New mail" in every mailbox type makes neomutt unusable for me, please add it to the extra tasks list
