### ISSUE TITLE
SCRAM-SHA-1(-PLUS) + SCRAM-SHA-256(-PLUS) supports

### ISSUE THREAD

**Issue by Neustradamus** [neomutt/neomutt#1846]
"When using the SASL SCRAM mechanism, the SCRAM-SHA-256-PLUS variant SHOULD be preferred over the SCRAM-SHA-256 variant, and SHA-256 variants [RFC7677] SHOULD be preferred over SHA-1 variants [RFC5802]".

Can you add support for?
- SCRAM-SHA-1(-PLUS):
-- https://tools.ietf.org/html/rfc5802
-- https://tools.ietf.org/html/rfc6120

- SCRAM-SHA-256(-PLUS):
-- https://tools.ietf.org/html/rfc7677 since 2015-11-02
-- https://tools.ietf.org/html/rfc8600 since 2019-06-21: https://mailarchive.ietf.org/arch/msg/ietf-announce/suJMmeMhuAOmGn_PJYgX5Vm8lNA

I add SCRAM-SHA-512(-PLUS): https://xmpp.org/extensions/inbox/hash-recommendations.html

Linked to:
- https://github.com/scram-xmpp/info/issues/1

**Comment by flatcap** [comment]
Like upstream Mutt, NeoMutt uses the Cyrus library for SASL authentication.

https://gitlab.com/muttmua/mutt/issues/174

**Comment by Neustradamus** [comment]
Please look: https://github.com/cyrusimap/cyrus-sasl/commits/master
- Commits on Sep 4, 2019
- Commits on Sep 2, 2019

**Comment by Neustradamus** [comment]
@flatcap: I wish you a Happy New Year!

For users, it will be easy to have a file with supported protocols.
Some people do not know, there is not a list, it is the problem.
For example, in this file, you can explain that Mutt uses Cyrus SASL :)
And a link to the Cyrus SASL list...

- https://www.cyrusimap.org/sasl/sasl/authentication_mechanisms.html
- https://doc.dovecot.org/configuration_manual/authentication/password_schemes/
