### ISSUE TITLE
Show originating/source mail folder in vfolder-from-query?

### ISSUE THREAD

**Issue by alansz** [neomutt/neomutt#1849]
Hi. I searched around but couldn't find an answer to this. 

Is there a way to show the source mail folder (maildir in my case) for each message in the index of a  vfolder built from a notmuch query or in the pager when viewing a message in a vfolder?

**Comment by Austin-Ray** [comment]
@alansz : Unfortunately, there is not at this time. The email struct only stores the `notmuch` query used to find the email. If you'd like to write a patch, we'd be happy to assist and review it :)
