### ISSUE TITLE
Better default index_format

### ISSUE THREAD

**Issue by pickfire** [neomutt/neomutt#185]
Hi, I was just started using `lists` (still doesn't know what that does) and `subscribe` which seems to be useful telling me that it belongs to a mailing lists.

`%L` freaked me out because I didn't expect that all the mailing lists that were subscribed to display ”To <list-name>” in index. I think that is a feature that confuse new users.

So instead of using `%L`, I would like it rather be `%F`. I need others opinion here, I guess.

**Comment by flatcap** [comment]
It's a useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
