### ISSUE TITLE
Forgotten attachment not working

### ISSUE THREAD

**Issue by arponero** [neomutt/neomutt#1858]
After enabling the forgotten attachment feature in .muttrc, a testing email including the words attach, attached and attachment shouldn't be sent if there is not at least one attachment. I have these lines in my .muttrc:
set abort_noattach = yes
set abort_noattach_regex = "\\<(attach|attached|attachments|adjunto|adjuntos)\\>"

An email with the text "attach attached attachment" is sent, even there is not an attached file.

The email is sent.

## Steps to Reproduce

Create a new email, write attach, attached and/or attachment, save the email and send it.

## How often does this happen?

- Always

## When did it start to happen?

I am trying this feature for the first time.

## NeoMutt Version

```
NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 17.7.0 (x86_64)
slang: 2.2.4
libiconv: 1.16
libidn: 1.35 (compiled with 1.35)
hcache backends: tokyocabinet

Compiler:
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Configure options: --prefix=/opt/local --with-idn=/opt/local --with-ncurses=/opt/local --with-nls=/opt/local --with-ssl=/opt/local --with-notmuch=/opt/local --with-ui=slang --with-slang=/opt/local --with-tokyocabinet=/opt/local

Compilation CFLAGS: -pipe -Os -arch x86_64 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/opt/local/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -bkgdset +color -curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo
  -gnutls -gpgme -gss +hcache -homespool +idn -locales_hack -lua -meta
  -mixmaster +nls +notmuch +openssl +pgp -sasl +smime -start_color
  +sun_attachment -typeahead
MAILPATH="/var/mail"
PKGDATADIR="/opt/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/opt/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
macOS 10.13.6 
* Were you using multiple copies of NeoMutt at once?
No
* Were you using 'screen' or 'tmux'?
I usually use tmux, but the problem persists even running neomutt outside tmux
* Is your email local (maildir) or remote (IMAP)?
local

BTW, all emails are sent as attachments:
-- Attachments
- I     1 ~/tmp/mutt/neomutt-carraca-501-10505-145                                                                                                    [text/plain, 7bit, utf-8, 152]

**Comment by flatcap** [comment]
Hmm... I think I can see a problem, to do with escaping...
Try changing your config to either of these:
```
set abort_noattach_regex = '\<(attach|attached|attachments|adjunto|adjuntos)\>'
set abort_noattach_regex = "\\<(attach|attached|attachments|adjunto|adjuntos)\\>"
```

When NeoMutt reads the config, the contents of:
- Single-quotes `'` are taken literally, so the regex used begins `\<(attach...`
- Double-quotes `"` are interpreted first (so things like `$my_var` would be expanded).
  In your example the regex used begins: `<(attach...` i.e. it's expecting a `<` character.

**Comment by arponero** [comment]
@flatcap Thank you for your prompt reply, but the result is the same with both options... any other idea?

**Comment by flatcap** [comment]
They work for me (but you don't want to hear that :-)

Try checking the value inside NeoMutt, using `:set ?abort_noattach_regex`
You should see:
``
abort_noattach_regex="\\<(attach|attached|attachments|adjunto|adjuntos)\\>"
```

If you do, try setting testing a single word: `:set abort_noattach_regex='adjunto'`
If that works, it may be the regex library that your NeoMutt is built with.
Perhaps try it without the end-of-word markers `\<` and `\>`

**Comment by arponero** [comment]
Wow, it is working now, thanks! 

set abort_noattach_regex = "(attach|attached|attachments|adjunto)"

works like a charm.

I have installed neomutt with port in my mac, so I will report this issue there. Thanks again!

**Comment by flatcap** [comment]
> works like a charm

Great.
Note that there may be false positives, if you're "un**attach**ed".

It's possible that your library uses Perl-style regexes.
You might want to try `\badjunto\b` or `\b(attach|attached|attachments|adjunto)\b`

**Comment by arponero** [comment]
> > works like a charm
> 
> Great.
> Note that there may be false positives, if you're "un**attach**ed".
> 
> It's possible that your library uses Perl-style regexes.
> You might want to try `\badjunto\b` or `\b(attach|attached|attachments|adjunto)\b`

No, that doesn't work either :-(

False positives are not a real issue, because I am using:
`set abort_noattach = ask-yes`

Anyway, I am wondering what is missing in my compilation, regarding the regex library:
````Configure options: --prefix=/opt/local --with-idn=/opt/local --with-ncurses=/opt/local --with-nls=/opt/local --with-ssl=/opt/local --with-notmuch=/opt/local --with-ui=slang --with-slang=/opt/local --with-tokyocabinet=/opt/local

Compilation CFLAGS: -pipe -Os -arch x86_64 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/opt/local/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -bkgdset +color -curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo
  -gnutls -gpgme -gss +hcache -homespool +idn -locales_hack -lua -meta
  -mixmaster +nls +notmuch +openssl +pgp -sasl +smime -start_color
  +sun_attachment -typeahead
````

**Comment by flatcap** [comment]
> I am wondering what is missing in my compilation, regarding the regex library:

Me too.

NeoMutt is built using the system's regex libraries -- for me (Linux), that's `glibc`.
My `man` pages don't actually seem to tell me which patterns that the library accepts.

A quick search tells me that `\<`, `\>` aren't part of the POSIX standard,
but I imagine there's _some_ way of doing that using your library.
Let me know if you find it.

**Comment by svlauer** [comment]
I just ran into the same problem, on OS X 10.15.4, neomutt installed with the homebrew binary (details below).

I checked `man re_format` and discovered that word boundaries are specified with `[[:<:]]` and `[[:>:]]` - using those, the regex works.

```
NeoMutt 20200501
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 19.4.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.11
libidn: 1.35 (compiled with 1.35)
GPGME: 1.13.1
OpenSSL: OpenSSL 1.1.1g  21 Apr 2020
libnotmuch: 5.2.0
storage: tokyocabinet, lmdb

Configure options: --prefix=/usr/local/Cellar/neomutt/20200501 --enable-gpgme --with-gpgme=/usr/local/opt/gpgme --gss --lmdb --notmuch --sasl --tokyocabinet --with-ssl=/usr/local/opt/openssl@1.1 --with-ui=ncurses --lua --with-lua=/usr/local/opt/lua

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/opt/gpgme/include -I/usr/local/opt/libassuan/include -I/usr/local/opt/libgpg-error/include -I/usr/local/Cellar/neomutt/20200501/include -I/usr/local/opt/lua/include/lua5.3 -DNCURSES_WIDECHAR -I/usr/local/opt/openssl@1.1/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn -inotify 
  -locales_hack +lua -lz4 +meta -mixmaster +nls +notmuch +openssl +pgp +regex 
  +sasl +smime -sqlite +start_color +sun_attachment +typeahead -zlib -zstd 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/Cellar/neomutt/20200501/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/Cellar/neomutt/20200501/etc"
```

**Comment by rionda** [comment]
Indeed, using
```
set abort_noattach_regex = "[[:<:]](attach(ed|ments?)?)[[:>:]]"
```
seems to work on MacOS (and the most external '( .. )'  are likely not needed.

I guess my question is: what regular expression syntax is accepted by neomutt, or does it only depend on the underlying regexp library? 
And should the default regexps be converted to POSIX-conforming regexps to maximize (?) portability?

**Comment by gahr** [comment]
Ciao Matteo, we use libc's regex in extended flavour (`REG_EXTENDED`), except for a few fixed regexes, for which we use pcre2 if the `--pcre2` configure flag is specified.

**Comment by rionda** [comment]
Thanks Pietro, then perhaps it would be good to use POSIX syntax in default regexps?

**Comment by gahr** [comment]
extended syntax *is* part of POSIX.. what do you mean?

**Comment by svlauer** [comment]
The problem is that different libc implementations all implement (hopefully) the POSIX standard, but  word boundaries are not part of this standard, so they are free to implement different ways to specifying them. 

The GNU libc (used, for example, on (most?) Linuxes) uses  `\<`, `\>`, while the FreeBSD libc (used on OSX, for example) uses `[[:<:]]`, `[[:>:]]`.

So I guess, the answer is: Avoid non-POSIX extensions in your regexes, or find out which ones are used by your system's libc.

**Comment by gahr** [comment]
Oh, you mean our use of `\\<` in the default value for `abort_noattach_regex`? Yeah, that's unfortunate. I don't know how it can it be done with plain POSIX?

**Comment by gahr** [comment]
Yeah I see - in `man 7 re_format` on FreeBSD I read that `\<` is supported, too. I haven't tried it, though. I wouldn't know how to do word-separators in plain POSIX :(

**Comment by svlauer** [comment]
I don't know, either ...

My "you" was meant to refer to the user - they either have to stick to plain POSIX or find out which flavors are supported (does `man re_format` also work on Linux/glibc-based systems?).

But yeah, it probably would be good to have the default value for `abort_noattach_regex` be plain POSIX, even if it means that it is not as powerful as it could be.

**Comment by rionda** [comment]
Yes, or add a note in the guide/manpage or something to make the users aware of the issue (it took me a while, but eventually found this github issue). 
The even better solution would be to have the default value use the right word-separators detected at build time, if possible.

**Comment by rionda** [comment]
By the way according to `re_format(7)` on MacOS, `\<` and `\>` would be available on MacOS if the `REG_ENHANCED` flag was passed to one of the variants of the `regcomp()` function. I don't know what neomutt uses, but perhaps it may be considered to pass this flag, at least on MacOS (and I imagine the BSDs).

**Comment by svlauer** [comment]
I am not sure about the consequences of using the REG_ENHANCED flag (generally or only on OSX/BSD), so maybe this is a solution.

After thinking about it, I don't think it is possible to define word boundaries in POSIX extended, as one would need lookahead for that. 

But it is not difficult to write a POSIX extended expression that is functionally equivalent for certain cases. According to the [`re_format (7)`](https://www.freebsd.org/cgi/man.cgi?query=re_format&sektion=7&n=1):
> A word is defined as a sequence of word characters which is neither preceded nor followed by word characters.  A word character is an alnum character (as defined by ctype(3)) or an underscore.

So the following should be functionally equivalent to the current default value of `abort_noattach_regex`:

```
(^|[^[:alnum:]_])attach(|ed|ments?)($|[^[:alnum:]_])
```
(I say "functionally equivalent", because the two regexps are not strictly equivalent - my version will include the first/last non-word-character (if present) in a match, the original will not. But they are equivalent if one justs asks (as neomutt does) "is there a match for this RE in the string?".)

If something like the above is used as the new default, I suggest also changing `attach` to `[Aa]ttach`, to catch beginning-of sentence uses ("Attached is ..."), so:
```
(^|[^[:alnum:]_])attach(|ed|ments?)($|[^[:alnum:]_])
```

(Sorry, I cannot roll a pull request, as I don't speak C.)

**Comment by rionda** [comment]
According to the guide, the match is case-insensitive if the regexp does not contain capital letters, so there should not be a need for `[Aa]`. 

By the way, `(^|[^[:alnum:]_])attach(|ed|ments?)($|[^[:alnum:]_])` is not valid for me on MacOS: neomutt complains of an empty subexpression (probably the one before `ed`).

**Comment by svlauer** [comment]
> According to the guide, the match is case-insensitive if the regexp does not contain capital letters, so there should not be a need for `[Aa]`.

Ah, I did not think of this. You are right.
 
> By the way, `(^|[^[:alnum:]_])attach(|ed|ments?)($|[^[:alnum:]_])` is not valid for me on MacOS: neomutt complains of an empty subexpression (probably the one before `ed`).

Ah, I was too quick: I copied what I thought was the default value from the [`abort_noattach` doc](https://neomutt.org/guide/reference.html#3-3-%C2%A0abort_noattach), but that was actually an example.

The documented default value for [`abort_noattach_regex`](https://neomutt.org/guide/reference.html#3-4-%C2%A0abort_noattach_regex) is `\<(attach|attached|attachments?)\>`, so the revised, POSIX-only version would be:

```
(^|[^[:alnum:]_])(attach|attached|attachments?)($|[^[:alnum:]_])
```
Thanks for pointing out my mistake!

**Comment by rionda** [comment]
We can likely use `(^|[^[:alnum:]_])(attach(ed|ments?)?)($|[^[:alnum:]_])` also.

**Comment by svlauer** [comment]
Yep, that would be the "corrected" version of the example. (Corrected in the sense that it is valid cross-platform --- I assume that implementations differ on whether they allow empty disjuncts in a group instead of making the group optional.)

(Aside: Geez, you think this stuff would be half-way standardized ...)

**Comment by roccoblues** [comment]
Hi, I'm trying to cleanup some older issues here. Is this still an issue with the latest version? Thanks!
