### ISSUE TITLE
nm_record and nm_record_tags

### ISSUE THREAD

**Issue by imr0** [neomutt/neomutt#1867]
Hi,

I am trying to get neomutt to add sent e-mail to the notmuch database but so far I am quite unsuccessful. If I understand the relevant documentation correctly, this should be achieved for example by the following settings:

```
set record = $MAIL/sent
set nm_record = yes
set nm_record_tags = sent
```

After sending a mail, I can indeed see it being appended to the file `$MAIL/sent` however executing the command `notmuch search tag:sent` does not show the message. In fact the message is not present in the notmuch database at all.
Is there something I am misunderstanding or did not consider?

I am using:
  notmuch version 0.29.1,
  current neomutt-git build from the AUR

**Comment by Austin-Ray** [comment]
@imr0 Have you tried syncing the mailbox before executing `notmuch search tag:sent`?

While I have not used the `nm_record` functionality, the `notmuch` backend tends to delay writes the database until the mailbox is opened/closed or a manual mailboxes sync runs.

**Comment by imr0** [comment]
Thanks for the suggestions. I tried manually syncing the mailbox after sending a mail but it still does not appear in the notmuch database. However, I can basically achieve the behaviour I want by adding:
```
set sendmail = nm_sendmail.sh"
```
where `nm_sendmail.sh` is a script that simply consists of
```
#!/bin/bash
tee >(notmuch insert --folder=record --create-folder +sent -new)  | sendmail $*
```

This is script I found at [https://notmuchmail.org/mutttips/](https://notmuchmail.org/mutttips/) but some modifications were needed so that I could use it with the most recent version of notmuch. It adds outgoing mail to the notmuch database into the folder `record` relative to where the `.notmuch` folder is located. A workaround, but works nicely.

**Comment by Austin-Ray** [comment]
I'm glad you were able to find a workaround while we try to fix the bug.

**Comment by showermat** [comment]
I'm having the same problem.  Mail is written to the record file successfully, but Notmuch appears never to see it.  I'm using Neomutt's built-in SMTP client rather than Sendmail, so imr0's solution is less practical for me.  I thought I could use a `send-hook` to pipe sent mail to `notmuch insert`, but it looks like hooks are too limited for that.

Any pointers on how I might debug this issue?

**Comment by Joshuao95** [comment]
I had a look at why it wasn't working (for me), and it was seems like you need to be in a notmuch-type mailbox (A virtual mailbox I assume) for this to work, which I wasn't.

Is there a thought-out reason for this requirement?

**Comment by snicket2100** [comment]
I am having the same problem, looks like `nm_record_message` doesn't even make it to the `mutt_debug(LL_DEBUG1, "nm: record message: %s\n", path);` line. My all mailboxes are virtual though I think, so maybe it's not the same problem @Joshuao95 is experiencing..?

**Comment by Joshuao95** [comment]
To be clear, I didn't get it working with a virtual mailbox (I never tried), I just noticed that it definitely wouldn't work for a non-virtual one.
