### ISSUE TITLE
neomutt crashing on OS X 10.5 PPC

### ISSUE THREAD

**Issue by lbschenkel** [neomutt/neomutt#187]
This was reported on MacPorts' Trac issue tracker:
https://trac.macports.org/ticket/52460#comment:12

It looks like a null point dereference on `realpath()` invoked by `mx_open_mailbox()`.

**Comment by lbschenkel** [comment]
I'm taking a wild guess here and assuming that `safe_strdup` on https://github.com/neomutt/neomutt/blob/0dc14e3e1d15750798a2985dd0da11f46ad20409/mx.c#L624 or https://github.com/neomutt/neomutt/blob/0dc14e3e1d15750798a2985dd0da11f46ad20409/mx.c#L626 is returning NULL.

**Comment by flatcap** [comment]
Mutt's `safe_strdup()` only returns NULL if the input is NULL.

The only way to get to that point in the code is if both `$spoolfile` and `$folder` are not set.

Looking at the code for `realpath()` the first thing I see is a check for a NULL parameter, with the comment:
```
/* As per Single Unix Specification V2 we must return an error if
   either parameter is a null pointer. */
```
This means, the bug may exist in upstream Mutt, but it's only MacOS version that crashes.
Confirmed.  If NeoMutt crashes, Mutt-1.7.0 would crash in the same place.

**Comment by flatcap** [comment]
@lbschenkel 
I've found and fixed a few problems.  Please can you test the version in branch [issue/187](https://github.com/neomutt/neomutt/tree/issue/187) -- or build it for the original reporter to test.

**Comment by flatcap** [comment]
Yes, Friday evening.

**Comment by lbschenkel** [comment]
Unfortunately I was not able to test your branch (I don't have access to that platform) nor coordinating with the original reporter, but I agree with your assessment and the fix and I think it's very unlikely that the problem is not addressed. Since there'll be a new release soon I'll wait for it and then I'll notify the original reporter asking for him to re-test.
