### ISSUE TITLE
'color sidebar_new yellow default' stops working after 07c35df960d2f3

### ISSUE THREAD

**Issue by dzickusrh** [neomutt/neomutt#1875]
## Expected Behaviour

I load up neomutt and it shows me all the virtual folders that have new mail as yellow else white.

## Actual Behaviour

All the virtual folders show up as white.
Reading the commit 07c35df960d2f3 shows this is an expected change.  However, running mbsync and downloading new email, I would have expected mailboxes with 'new additions mail'  to be colored yellow (not every mailbox with unread email) [I *think* that was the intent of the change].  But I do not see _any_ virtual folders colored yellow, even though about 50 mails were added across the folders.

Reverting that commit restored the behaviour I was used to seeing.

Steps to reproduce:
* load neomutt with sidebar and virtual folders
* notice all folders are white
* download new mail
* notice no new colors

**Comment by Austin-Ray** [comment]
@flatcap Can confirm this issue. I think it's best to revert 07c35df like @dzickusrh did or expand colors to include an unread highlight.

**Comment by emtiu** [comment]
I've been using `color sidebar_new yellow default` to highlight all folders with unread mail. Bug or not, I would like to keep this functionality. So, as @Austin-Ray suggests, implementing `color sidebar_unread` would be most appreciated.

**Comment by dzickusrh** [comment]
Hi,

It seems like one of my problems was addressed with sidebar_unread.  Which is fine.

But I am still scratching my head over what sidebar_new is supposed to do.  I am not sure that works as intended.  Can someone explain to me how that is expected to work?  Perhaps I am using it wrong.

**Comment by flatcap** [comment]
Historically, Mutt has had a 'N' new-ness indicator that was separate from having new mail.
This indicator meant that something needed your attention.

It shows up in:
- `$status_format` as `%b` (number of mailboxes)
- `$folder_format` as `%N`
- `$sidebar_format` as `%n`
- `<mailbox-list>` command -- 'New mail in +work'
- `<sidebar-next-new>` and `<sidebar-prev-new>`
- 'c' (`<change-folder>`) defaults to the next mailbox

When you open one of these Mailboxes, the flag is cleared.
If you have `$mark_old = no`, then the Emails will stay New, but NeoMutt assumes you don't want to be notified again.

When new mail arrives, that flags a Mailbox as needing attention, again.

There's also the `$mail_check_recent` option which forces NeoMutt to consider New Email as attention-worthy.

Got that?  ;-)

I _think_ I understand, myself.
I _think_ I've got it working as it used to work.

**Comment by dzickusrh** [comment]
Hi,

Ok, that is what I thought too.  And I like that idea as I have a few dozen virtual folders mapped to mailing lists with a never ending list of new unread email.   Separating those folders from ones that actually had an update through mbsync sounds useful.

For some reason, I don't have the colors changing for me on those updates.  I probably have my muttrc misconfigured (it is pretty lengthy).  Is it enough to just have

color sidebar_new yellow default

?

**Comment by flatcap** [comment]
> Is it enough to just have `color sidebar_new yellow default`

It _should_ be, but I don't know how it interacts with Notmuch and mbsync/offlineimap.
So, please keep raising issues until I get it right :-)

**Comment by dzickusrh** [comment]
Hmm, it seems to work with my 'mailboxes =INBOX' command but not the virtual folders.

I doubt mbsync/offlineimap will interfere here.  Thanks for your patience! :-)
