### ISSUE TITLE
ctrl+c 

### ISSUE THREAD

**Issue by fekir** [neomutt/neomutt#1877]
## Expected Behaviour

While fetching message headers, pressing `ctrl+c` prompts following question

`Abort download and close mailbox? ([yes]/no):`

When pressing `y` or simply enter, the expected behavior would be for `neomutt` to close itself

## Actual Behavior
neomutt opens an empty mailbox (at least in my case the sidebar was filled with the correct folder names) and shows a red message "Error opening mailbox"`

## Steps to Reproduce

Open neomutt
press ctrl+c while loading headers
press enter

## How often does this happen?

- Always

## When did it start to happen?

When I compiled  `2019-10-25` for cygwin.

It might be related to https://github.com/neomutt/neomutt/commit/56fafc676d4a2220010b9db84b4cd851088b4269, as mentioned in https://github.com/neomutt/neomutt/pull/1852 when I found another inconsistent behavior, but I did not test it.

## NeoMutt Version

```
NeoMutt 2019-10-25
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: CYGWIN_NT-10.0-17134-WOW64 3.0.7-338.i686 (i686)
ncurses: ncurses 6.0.20171125 (compiled with 6.1.20190727)
libiconv: 1.14
libidn: 1.33 (compiled with 1.33)
GPGme: 1.9.0
hcache backends: bdb

Compiler:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-pc-cygwin/7.4.0/lto-wrapper.exe
Target: i686-pc-cygwin
Configured with: /cygdrive/i/szsz/tmpp/gcc/gcc-7.4.0-1.i686/src/gcc-7.4.0/configure --srcdir=/cygdrive/i/szsz/tmpp/gcc/gcc-7.4.0-1.i686/src/gcc-7.4.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=i686-pc-cygwin --host=i686-pc-cygwin --target=i686-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-arch=i686 --with-tune=generic --disable-sjlj-exceptions --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --enable-libada --disable-symvers --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
Thread model: posix
gcc version 7.4.0 (GCC)

Configure options: --gnutls --sasl --bdb --gpgme --gss --pgp --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info

Compilation CFLAGS: -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/cygdrive/c/Users/admin/Desktop/cygport/neomutt-2019-10-25-1.i686/build=/usr/src/debug/neomutt-2019-10-25-1 -fdebug-prefix-map=/cygdrive/c/Users/admin/Desktop/cygport/neomutt-2019-10-25-1.i686/src/neomutt-2019-10-25=/usr/src/debug/neomutt-2019-10-25-1 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn -inotify
  -locales_hack -lua +meta -mixmaster +nls -notmuch -openssl +pgp +sasl +smime
  -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
Windows 10 x64, the issue is reproducible boht on cygwin x64 and cygwin x86
* Were you using multiple copies of NeoMutt at once?
No
* Were you using 'screen' or 'tmux'?
No
* Is your email local (maildir) or remote (IMAP)?
IMAP (Gmail, if it makes any difference)

**Comment by flatcap** [comment]
I'm not quite sure what you want here.

<kbd>Ctrl-C</kbd> is caught by the terminal, which generates a `SIGINT` signal, which NeoMutt traps.
This means it's ideal for interrupting 'actions'.

When there's no action in progress, having <kbd>Ctrl-C</kbd> as "Quit NeoMutt" is also useful (for beginners).

But... the current code in master already seems to work as I'd expect.

Clear the cache and open a large IMAP folder:

- Pressing <kbd>Ctrl-C</kbd> asks: '**Abort download and close mailbox?** '
- A second <kbd>Ctrl-C</kbd> asks: '**Exit NeoMutt?**'

Here are the four possibilities:

1. <kbd>Ctrl-C</kbd>, <kbd>y</kbd> -- Download is aborted, folder empty, NeoMutt still running
2. <kbd>Ctrl-C</kbd>, <kbd>n</kbd> -- Download continues, folder populated, NeoMutt still running
3. <kbd>Ctrl-C</kbd>, <kbd>Ctrl-C</kbd>, <kbd>y</kbd> -- Exit NeoMutt immediately
4. <kbd>Ctrl-C</kbd>, <kbd>Ctrl-C</kbd>, <kbd>n</kbd> -- Download continues, folder populated, NeoMutt still running

**Comment by flatcap** [comment]
> Does pressing `Ctrl-C`, `y` leave the program in any useful state?

It seems so (but I haven't investigated deeply).

From the empty folder, both these reopen the folder correctly.
- `<sidebar-open>`
- <kbd>c</kbd><kbd>^</kbd><kbd>\<Enter\></kbd>
