### ISSUE TITLE
Sidebar multiple accounts headers

### ISSUE THREAD

**Issue by Ergus** [neomutt/neomutt#1879]
Hi:

Up to yesterday I had configurations like this:
```
mailboxes "+== GMAIL =="\
		  +INBOX \
		  '+[Gmail].Sent Mail' \
		  +[Gmail].Drafts \
		  +[Gmail].Bin
```
To have headers multiple mail accounts. This allows to have a line with the account name between the accounts in the sidebar. After the last changes the header disappeared and I am not able to add the `named separatos` anymore. I have tried with the new command `named-mailboxes`. But I cant make it work. Do you have a new method to do so?

**Comment by Austin-Ray** [comment]
This looks like a duplicate of #1612, which we hadn't fixed before the new release. There's a workaround in the thread https://github.com/neomutt/neomutt/issues/1612#issuecomment-476865230 if you don't mind adding a symlink.

**Comment by Ergus** [comment]
Hi:
This was workin before... Just now it broke after the update. I already implemented your workaround.
