### ISSUE TITLE
wrapmargin=4 wraps at 4 columns in the pager

### ISSUE THREAD

**Issue by sthen** [neomutt/neomutt#1883]
## Expected Behaviour

wrapmargin=4 works like wrap=-4

## Actual Behaviour

wrapmargin=4 works like wrap=4, wrapping at 4 columns wide in the pager

## Steps to Reproduce

Update to 2019-10-25, use a config with wrapmargin=4

## How often does this happen?

Always

## When did it start to happen?

When I upgraded from 20180716 to 2019-10-25

## NeoMutt Version

```
NeoMutt 2019-10-25
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: OpenBSD 6.6 (amd64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.16
libidn2: 2.0.0 (compiled with 2.0.0)
GPGme: 1.13.1
hcache backends: kyotocabinet

Compiler:
OpenBSD clang version 8.0.1 (tags/RELEASE_801/final) (based on LLVM 8.0.1)
Target: amd64-unknown-openbsd6.6
Thread model: posix
InstalledDir: /usr/bin

Configure options: --mandir=/usr/local/man --with-ui=ncurses --docdir=/usr/local/share/doc/neomutt --with-lock=flock --idn=0 --idn2 --fmemopen --ssl --gpgme --kyotocabinet

Compilation CFLAGS: -O2 -pipe -g  -I/usr/local/include -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set -fcntl +flock +fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss +hcache -homespool +idn -inotify 
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp -sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
* Were you using multiple copies of NeoMutt at once?
* Were you using 'screen' or 'tmux'?
* Is your email local (maildir) or remote (IMAP)?

OpenBSD -current amd64, no multiple copies of NeoMutt, same with/without tmux, imap maildir.

**Comment by flatcap** [comment]
Ah, `wrapmargin` was documented as **deprecated** in 2007 (pre-NeoMutt).

The behaviour change is due to my config code improvements (clearing up all the custom handling).
I _could_ restore the behaviour, but I'd prefer not to
(unless you think it will impact a lot of users).

**Comment by sthen** [comment]
On 2019/10/27 07:22, Richard Russon wrote:
> Ah, wrapmargin was documented as deprecated in 2007 (pre-NeoMutt).
> 
> The behaviour change is due to my config code improvements (clearing up all the custom
> handling).
> I could restore the behaviour, but I'd prefer not to
> (unless you think it will impact a lot of users).

It's in various example configs that have been passed around (and is
still present in sample.neomuttrc-tlr in the NeoMutt distribution) so
it's probably not that uncommon. Perhaps it would be better to just
remove wrapmargin completely? An "unknown variable" would be more
user-friendly than leaving them to track it down (it took me a while
to realise that the wrapping might have been due to a config setting
rather than an incompatibility with something in OpenBSD, I didn't
spot the offending line until a few iterations of binary search
through my config).

**Comment by flatcap** [comment]
> It's in various example configs

ok, I'll clobber those

> Perhaps it would be better to just remove wrapmargin completely?

Probably.  Yeah, I'll do that.

> ... it took me a while to realise ...

Sorry about that.

**Comment by sthen** [comment]
On 2019/10/27 09:58, Richard Russon wrote:
>     ... it took me a while to realise ...
> 
> Sorry about that.

Oh, no worries at all! Considering how much work you've put in since the last
release I was pleasantly surprised that this was the only thing I've bumped
into :)
