### ISSUE TITLE
Problem with enter in the minibuffer.

### ISSUE THREAD

**Issue by Ergus** [neomutt/neomutt#1884]
## Expected Behaviour

When try to compose a message the "minibuffer" should react to Enter.

I was trying to create a message from scratch. And after introducing the email address and enter it should ask for the subject or go to the editor. But enter does nothing.

## Actual Behaviour

The sequence: **m mail@mail.com Enter** should go to the **subject:** dialog but it does nothing at all. If I type a letter or anything else it works as expected. But not enter or

## Steps to Reproduce

m mail@mail.com Enter

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

neomutt-20180716

## NeoMutt Version

NeoMutt 2019-10-25
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.7-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 9.2.0 (GCC)

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime
  -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

## Extra Info

* Operating System and its version
Linux 5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019 x86_64 GNU/Linux

* Were you using multiple copies of NeoMutt at once?
No

* Were you using 'screen' or 'tmux'?
Yes tmux in xterm, but the problem happens also without tmux.

* Is your email local (maildir) or remote (IMAP)?
Local mail

**Comment by flatcap** [comment]
Hmm... that's very strange.
Can you try running without any config: `neomutt -n -F /dev/null`
Also, try a different terminal to see if that makes a difference.

**Comment by Ergus** [comment]
Hi:

With the empty config it works fine. But my actual config is a bit large now. Do you know what sentensies could introduce this issue?

**Comment by flatcap** [comment]
I've narrowed it down to just `:reset charset`
I'm still investigating, but that gives you two workarounds:
- Start with no system config (so you don't need the `reset all`)
  `neomutt -n`
- Set the `charset` after the `reset all`
  `set charset='utf-8'`
