### ISSUE TITLE
IMAP mailboxes require login

### ISSUE THREAD

**Issue by klartext** [neomutt/neomutt#1894]
I'm forced to open any mailboxes that are mentioned in the rc-file as mailboxes.
Old behaviour: I needed to login only where I open with -f the imap mailbox.
Now I have to access all mailboxes.
Even, when I just want to open a local file as mailbox, I'm forced to login to any known mailbox.

Very annoying.

Unwanted behaviour started with Arch-package 20191025, so it's the new neomutt release.

**Comment by klartext** [comment]
Output of "neomutt -v":

```
NeoMutt 2019-10-25
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.7-arch1-1-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 9.2.0 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

Problem started with upgrade to NeoMutt 2019-10-25.

Always reproducible.

**Comment by klartext** [comment]
Is here a workaround known?
Otherwise I will stay with the july 2018 release. :-(

**Comment by gahr** [comment]
Can you try to reproduce the problem with a minimal config file and post it here?

**Comment by klartext** [comment]
While trying to create a minimal example for the config-file, I found another issue.
In my .muttrc I have the line

```
mailboxes ~/Mail/
```
With NeoMutt 20200814 I get the error message "Unknown Mailbox" for this dir.
So the syntax seems to have changed in the meanwhile (this was not the case when I opened this issue, so newer release, newer problems).
So I could not enter the stage of this issue, because another issue came in before.

**Comment by klartext** [comment]
It seems like a mailboxes-entry to imaps-server is enough to force opening it, even though just using
'''
neomutt -f Mail/mbox
```
so just looking at alocal filke forces to login on imaps-folder.

**Comment by klartext** [comment]
I used git bisect to locate the problem.
Here is the result:

```
d540e98e3e932d88b585eb8e8b7c2d3bce27790c is the first bad commit
commit d540e98e3e932d88b585eb8e8b7c2d3bce27790c
Author: Mehdi Abaakouk <sileht@sileht.net>
Date:   Thu Nov 8 10:55:03 2018 +0100

    imap: remove imap_conn_find in imap_mbox_open_append
    
    All code using imap_conn_find is currently broken.
    
    This change is the first part of moving out imap_conn_find.
    
    To do so, a new function mail_prepare_mailbox() will setup the
    ImapAccountData structure.
    
    This method will be used in imap_access()/imap_mbox_open()/imap_mbox_open_append().

 imap/imap.c | 212 ++++++++++++++++++++++++++++++++++--------------------------
 1 file changed, 122 insertions(+), 90 deletions(-)
```

**Comment by klartext** [comment]
Tried neomutt-Arch package 20201120-1. Problem occurs here.
Then did checkout neomutt from github-repo, with git tag '20201120'.

Normal ./configure and compiled the project - problem does NOT occur.
Tried the configure-options from the Arch-compile.

I found out: the problem only occurs when --ssl switch for configure is set.

**Comment by klartext** [comment]
Want to add: there is a second side-effect, which occurs, and was not mentioned so far: with the open-all-mailboxes-even-if-only-one-is-selected-with'-f'-switch also occurs inverted colors.
Instead of black on white, colors are white on black, when the folder-open-problem occurs.

**Comment by klartext** [comment]
pacman says about the arch-compile ( 20180716-8, which worked correctly, it did not contain commit d540e98e3 )
```
Depends On      : glibc  gpgme  lua  notmuch-runtime  krb5  openssl  libsasl  ncurses  libidn2  lmdb  gdbm  kyotocabinet
```

I used
```
./configure --lua --sasl --ssl --gpgme --notmuch --gdbm --lmdb --kyotocabinet --disable-idn --idn2
```
and then removed one switch at the time. (compiling with "HEAD detached at 20201120")

And as mentioned above, when removing --ssl the problem disappeared (both problems disappered: the mailbox-open and color-issue).

**Comment by gahr** [comment]
Hi @klartext , thanks for the investigation. I have re-read your comments carefully but I am not sure I compeletely understand what's happening. Let me try to rephrase it.

So, you have a mixture of local and IMAP mailboxes declared with the `mailboxes` command. When you compile without SSL support, you need to enter your IMAP credentials only when you select one of the IMAP mailboxes. If you compile with SSL support, NeoMutt will ask for your IMAP credentials as soon as it starts up, even if you don't want to select an IMAP mailbox. Is that correct?

It is expected that specifying an IMAP mailbox using `mailboxes` causes a login into the IMAP account. That is because mailboxes are watched and checked for new messages. That being said, are you using SSL to access your account? How can it work both with and without SSL compiled in?

Can you provide a minimal config file that exhibits the behaviour?

**Comment by klartext** [comment]
> Hi @klartext , thanks for the investigation. I have re-read your comments carefully but I am not sure I compeletely understand what's happening. Let me try to rephrase it.

In neomutt-20201120, when I use -f option to open a specific mailbox-file on my disc, it will be just opened.
With later versions of neomutt - with the same .muttrc file - the behaviour changed.
I'm not able to just open just the one mailbox file anymore. Instead I'm forced to open any mailboxes, which is mentioned in the .muttrc-file.
Yes, there are Mailbox-Entries for IMAP in the .muttrc-file.
But I used the same .muttrc with neomutt-20201120 or newer versions.
And the problem (forced to open any IMAP-mailbox, even though I select one specific mbox-file on my local disc, accompanied with inverted colors) does not occur in neomutt-20201120 or earlier versions.

Somehow the problem is also bound to using -ssl in compilation in the newer neomutt-versions.
With neomutt-20201120 (Arch-package; it's also built with --ssl) the problöem does not occur.

With the stuff I used from github (520d3aa8c31) the problem does occur. But when removing --ssl from config settings, the problem disappears.

The .muttrc contains entries like
```
mailboxes "imaps://username@IMAPSSERVER/Folder"
```
but these entries were there all the time.

Somehow the commit d540e98e3e932d88 together with --ssl in config creates the problem.

If -f switch would make neomutt just open this one specified file, the problem would be gone.
But it's somehow strange, why adding or removing the --ssl has sich strange effects.
And also all this did not occur in earlier neomutt versions.

**Comment by gahr** [comment]
Two questions:

1. when you build without the `--ssl` option, I expect that `mailboxes imaps://username@IMAPSSERVER/Folder` generates an error `SSL unavailable, can't connect to IMAPSSERVER`. Then the message disappears and you land in the mailbox you're opening. Is that what you mean by "it works"?
2. when you say "forced to open any mailboxes", do you mean you are asked to type in your credentials, then you still land in the correct mailbox? If that's the case, I think it's a consequence of a rework of accounts/mailboxes. I am not sure I would consider it a bug per se, but I'll let @sileht comment.

**Comment by klartext** [comment]
The different Arch-packages have been created with different libraries:

```
Name            : neomutt
Version         : 20201120-1
Description     : A version of mutt with added features
Architecture    : x86_64
URL             : https://neomutt.org/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : glibc  gpgme  lua53  notmuch-runtime  krb5  gnutls  sqlite  libsasl  ncurses  libidn2  lmdb  gdbm  kyotocabinet  lz4  zlib  zstd
Optional Deps   : python: keybase.py [installed]
                  perl: smime_keys [installed]
                  ca-certificates: default CA certificates [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 8,49 MiB
Packager        : Maxim Baz <pgp@maximbaz.com>
Build Date      : Sa 21 Nov 2020 11:54:23 CET
Install Date    : Di 01 Dez 2020 12:39:48 CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```


```
Name            : neomutt
Version         : 20180716-8
Description     : a version of mutt with added features
Architecture    : x86_64
URL             : https://neomutt.org/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : glibc  gpgme  lua  notmuch-runtime  krb5  openssl  libsasl  ncurses  libidn2  lmdb  gdbm  kyotocabinet
Optional Deps   : python: keybase.py [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 8,04 MiB
Packager        : Alad Wenter <alad@archlinux.org>
Build Date      : Mi 31 Jul 2019 16:12:06 CEST
Install Date    : Di 01 Dez 2020 12:40:44 CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

2020-version: bad
2018-version: good

**Comment by klartext** [comment]
I have created screencasts with asciinema, which show the good and bad behaviour:

https://www.first.in-berlin.de/mixed/nmok.cast
https://www.first.in-berlin.de/mixed/nmbad.cast

**Comment by gahr** [comment]
Ok, what you are seeing is expected. The fact that you add IMAP `mailboxes` means NeoMutt will need to access them (i.e., make a login) on startup.

**Comment by gahr** [comment]
I see your "good" package depends on gnutls instead of openssl, so I think you have TLS enabled anyway, just using two different providers.

**Comment by klartext** [comment]
I see no reason, why using -f on the command line should not overwrite the .muttrc Mailbox-Settings.

Manpage:

```
-f mailbox
              Specify a mailbox (as defined with mailboxes command) to load
```

IMO the 2018-version behaved as expected.

I added for testing purpose the ~/Mail/spam as mailboxes-entry.
With -f ~/Mail/spam it should be selected.
In the 2020-neomutt, nevertheless the OTHER mailboxes (Imap) need the password.
So the -f option seems not to help here.
Maybe it opens that Mailbox, but first, seem to access other mailboxes, not the one requested with -f. 

If -f option does not change anything, for what is it good for?
If it works, but the -f is evaluated too late, this awkward behaviour comes up.
If mailboxes-entries mean to open any of these, the -f option at least should be processed (and be shown) first.
It should be possble to overwrite the mailboxes-directives with -f (or some other switch).
Command line over config-file.

Or mailboxes vs Mailboxes in muttrc, where mailboxes can be overwritten with -f and only -f <mailbox> will be selected.
---
BTW: Was there ticket/ISSUE, which addressed the (imo prefereable) behaviour of the 2018-neomutt as bug?
Or was it just changed without need? (or by accident?)
---
What can I gain from the "two different providers" and does that mean that --ssl just says, that ssl is used, but not which implementation?
Could changing the provider solve (by miracle) solve my issues?

And if that works: how would that comply the "expected behaviour"?

---

Why is the "expected behaviour" expected when compiling neomutt (current stuff from this repo, as mentioned above) with --ssl
and why is "the old behaviour" (the not expected one) being accepted as "expected", when --ssl is not used?

Is it mentioned in the manpages that evaluation of mailboxes-command in .muttrc depends on enabling/disabling -ssl?

**Comment by gahr** [comment]
> I see no reason, why using -f on the command line should not overwrite the .muttrc Mailbox-Settings.

I think the only reason is that it wasn't implemented that way :) -f just overwrites `folder`, but you might still want to switch to other folders you have defined with `mailboxes` commands. The `-f` switch selects **which** mailbox to open; it does not redefined the **entire set** of mailboxes.

> It should be possble to overwrite the mailboxes-directives with -f (or some other switch).
Command line over config-file.

This would be a feature request. Are you willing to work on that? I can support you getting started.

You can read `ssl` as `OpenSSL`, and `gnutls` as... `GnuTLS`. But I don't think they affect this behaviour. Are you saying you are not getting the user/password prompt for IMAP mailboxes when using `--gnutls`?

**Comment by klartext** [comment]
> > I see no reason, why using -f on the command line should not overwrite the .muttrc Mailbox-Settings.
> 
> I think the only reason is that it wasn't implemented that way :) -f just overwrites `folder`, but you might still want to switch to other folders you have defined with `mailboxes` commands. The `-f` switch selects **which** mailbox to open; it does not redefined the **entire set** of mailboxes.

OK, it selects, **which** folder to open.
So why should it open the other folders too?
If they all (from .muttrc-file ) should be opened, -f switch would not be needed.



> 
> > It should be possble to overwrite the mailboxes-directives with -f (or some other switch).
> > Command line over config-file.
> 
> This would be a feature request. Are you willing to work on that? I can support you getting started.

This feature (-f overrides mailboxes-settings in .muttrc) worked in the 2018-version until the above mentioned imap-specific commit was added.

> 
> You can read `ssl` as `OpenSSL`, and `gnutls` as... `GnuTLS`. But I don't think they affect this behaviour. Are you saying you are not getting the user/password prompt for IMAP mailboxes when using `--gnutls`?

I Did not tried it so far. But I thought you would imply this behavior, when you mentioned that different ssl-providers were used between 2018- and 2020-version. Seems this is not what you meant.

**Comment by gahr** [comment]
Ok let’s try to wrap it up.

1. A `mailboxes` command now implies “accessing” the mailbox as soon as the command is parsed. This does not mean “opening” or “selecting” the mailbox, but it requires a login to the IMAP server. You are correct: this is something that has changed in the commit you mentioned. This is independent from a `-f` argument, which only specifies which mailbox to open in the index.

2. Building without TLS (openssl or gnutls) means you’ll get an early failure when trying to “access” the `imaps://` mailbox. As a result, you won’t get asked for a password and everything seems to work by your expectation. Let’s forget about TLS as it’s only an accidental behaviour.

I am not in the position to say whether 1) is easily worked around to cover your use case, but I can think of reasons why it is the way it is now (e.g., to check mailboxes for new messages). We can perhaps think of ways to facilitate the `-f` case, but I don’t see this as a simple bug that needs to be reverted. The new way of handling `mailboxes` has its own rationale.

**Comment by klartext** [comment]
So, you mean after all the discussion, the behaviour I want is rather a feature request (as you suggested somehwere above)?

**Comment by klartext** [comment]
>     2. Building without TLS (openssl or gnutls) means you’ll get an early failure when trying to “access” the `imaps://` mailbox. As a result, you won’t get asked for a password and everything seems to work by your expectation. Let’s forget about TLS as it’s only an accidental behaviour.


Just using ./configure without any additional switches creates a neomutt, that just opens my local folder (with -f switch), without any error messages. The "early failure" does not show up. So I can't see it as a failure.

Otherwise there needs to be an error message, reporting that mailboxes-entries with imaps can't be used, when ssl is not compiled in.

**Comment by gahr** [comment]
> So, you mean after all the discussion, the behaviour I want is rather a feature request (as you suggested somehwere above)?

Yeah I think so. It is unfortunate that your workflow was broken by that change, sorry for that, but I don’t quite see it as a bug.

> Just using ./configure without any additional switches creates a neomutt, that just opens my local folder (with -f switch), without any error messages. The "early failure" does not show up. So I can't see it as a failure.

I think I tested exactly this earlier today and saw the error message, but I’ll dig more tomorrow.

**Comment by gahr** [comment]
> I think I tested exactly this earlier today and saw the error message, but I’ll dig more tomorrow.

I confirm. I built without openssl support, and neomutt errors with `SSL is unavailable, can't connect to example.com`.

If you don't see the error interactively, please run with `-d1` and see the first lines of the generated ~/.neomuttdebug0 file. Example:

```
  4 [2020-12-02 15:40:05]<E> mutt_conn_new() SSL is unavailable, can't connect to example.com
```

**Comment by klartext** [comment]
And... how to implement my feature wishes?
Any hints on how/where to start?

**Comment by klartext** [comment]
The problem occurs with "NeoMutt 20201127" (current Arch install).

Tried now using imap_user and imap_pass instead of my former way of handling it (with typing pass by hand).

Occurrence of the problem depends on the order of imap-settings and mailbox-definitions in the config.

When mailbox-entries are before the imap_user and imap_pass, the problem occurs (but not with the old version mentioned above).

When mailbox-settings follow imap_user and imap_pass, the annoying behaviour disappears also in the current neomutt (and it did not occur with the old version).

So the occurrence of the mandatory-login-problem depends on the order of config-settings.

**Comment by gahr** [comment]
That's expected, then: you need authentication details before you can add a `mailbox`.

**Comment by gahr** [comment]
As I mentioned on Nov 30:

> It is expected that specifying an IMAP mailbox using mailboxes causes a login into the IMAP account.
