### ISSUE TITLE
Segment Fault When Starting Neomutt 20191025

### ISSUE THREAD

**Issue by toogad** [neomutt/neomutt#1904]
## Expected Behaviour
Normal start.

## Actual Behaviour
After upgrading to 20191025, Neomutt fails to start normally. Instead, segmentation fault is encountered every time.

When I start with "sudo neomutt", it tries to create "/root/Mail".

## How often does this happen?

- Always

- After I upgraded

## Extra Info

* [Manjaro Linux with Xfce. Kernel 5.3.7-2-Manjaro]
* Were you using multiple copies of NeoMutt at once? [NO]
* Were you using 'screen' or 'tmux'? [TMUX]
* Is your email local (maildir) or remote (IMAP)? [IMAP]

**Comment by flatcap** [comment]
Sorry to hear that, @toogad 

Do you have any alias groups in your config?
(we've already found a fixed a crash caused by them)

Does running without any config work?  (not crash)
`neomutt -n -F /dev/null`

If that works, please can you try to narrow down which line of config might be causing the problem
(typically, you comment out half your config file, to 'bisect' the problem)

> When I start with "sudo neomutt", it tries to create "/root/Mail".

That's not surprising.  Without any config, Mutt would default to creating you a Mail directory.

**Comment by toogad** [comment]
Richard,

I just tried   neomutt -n -F /dev/null

There was still the seg fault.

I also tried to get the debugging log, but couldn't find the log file. I
guess my neomutt was not compiled with debugging options?

Will go into the .neomuttrc to comment out some sections and update you
later.

Thanks.
kai

**Comment by flatcap** [comment]
> There was still the seg fault.

Hmm... that's new

> I also tried to get the debugging log, but couldn't find the log file.

There's built-in logging, that might help: `neomutt -d5`
Then have a look in `~/.neomuttdebug0`

But if you know how to get a backtrace that would be very useful (don't worry if you don't).

**Comment by toogad** [comment]
Richard,

The alias group in my .neomuttrc did create the problem. 

My .neomuttrc sources in the alias groups from ~/.neomutt/aliases .

Regards,
kai

> Sorry to hear that, @toogad
> 
> Do you have any alias groups in your config?
> (we've already found a fixed a crash caused by them)
> 
> Does running without any config work? (not crash)
> `neomutt -n -F /dev/null`
> 
> If that works, please can you try to narrow down which line of config might be causing the problem
> (typically, you comment out half your config file, to 'bisect' the problem)
> 
> > When I start with "sudo neomutt", it tries to create "/root/Mail".
> 
> That's not surprising. Without any config, Mutt would default to creating you a Mail directory.

**Comment by flatcap** [comment]
> The alias group in my .neomuttrc did create the problem.

OK, good.  That's already fixed, and there'll be a new release soon.

**Comment by toogad** [comment]
Perfect. Thanks.
