### ISSUE TITLE
Quick way to skip sending empty mail

### ISSUE THREAD

**Issue by kdave** [neomutt/neomutt#191]
Say I don't want to send a mail, then I can exit the editor, press 'q' in the compose screen, confirm that I don't want to postpone the mail and go back to index.

Desired behaviour: let composer check if the text of the mail is empty and then skip asking, ie. go directly to index. The test could be simple, empty file (or just whitespace), or parse the file and look if body is empty.

A non working attempt (send.c::ci_send_message):

```

     fcc_error = 0; /* reset value since we may have failed before */
     mutt_pretty_mailbox (fcc, sizeof (fcc));
+    if (msg->lines == 0) {
+      /* abort */
+      mutt_message _("Mail empty, sending aborted.");
+      goto cleanup;
+    }
     i = mutt_compose_menu (msg, fcc, sizeof (fcc), cur);
     if (i == -1)
     {
```

**Comment by 4nd3r** [comment]
I often use templates (Esc e), but sometimes change my mind and cancel sending.
and with template, message is not empty. can we detect it somehow?

**Comment by flatcap** [comment]
There's also the case of `$edit_headers = yes`

A simple idea might be to check the timestamp on the temporary file.

**Comment by kdave** [comment]
For the record, I do have edit_headers = yes, and autoedit =  yes.

The possible checks:
* file is empty
* tiimestamp changed
* file contents haven't changed (checksum or save a copy of the original file)

I think the timestamp is good enough for starters, though it still should check whether the file is empty (eg. delete contents and save and exit).

**Comment by kdave** [comment]
Actually, mutt detects an unmodified mail, seems it's time based (saving the file again will go to compose screen).

**Comment by guyzmo** [comment]
it's already doing that per default for me. If I do not edit a mail, I get straight back to the index with the `Aborted unmodified message.` message.

I believe it's the `set abort_unmodified=yes` option (even though I have it commented out in my config, so I guess it's the default behaviour).

**Comment by sileht** [comment]
I already have the described behavior by default.

And yes it's mtime based and controllable by `abort_unmodified`

* file is empty -> I can propose it, it's trivial, and obvious that empty file is not something we want to send
* tiimestamp changed  -> It's already done
* file contents haven't changed -> the editor should not change mtime (my vim doesn't change mtime even if I do :wq)

**Comment by sileht** [comment]
The feature itself is already implemented  (set abort_unmodified=yes) and based on modified time.

We can't looks at empty file within neomutt, sending a empty email is a valid use case, for example mailing-list (un)subcribe (more detail in PR #457)

Also it already possible to customize the behavior by using a script as editor with `set editor = 'mycustommuttedit'`

```
$ cat mycustommuttedit
#!/bin/bash
mail="$1"
cp "$mail" "${mail}.mod"
trap "rm -f ${mail}.mod" EXIT
$EDITOR "${mail}.mod"
if [[ -s "${mail}.mod" ]] && [[ $(md5sum "${mail}") != $(md5sum "${mail}.mod") ]] ; then
    cp -f "${mail}.mod" "$mail"
fi
```
