### ISSUE TITLE
After 10-25 update, sidebar don't show some fake mailboxes

### ISSUE THREAD

**Issue by xiangsheng** [neomutt/neomutt#1911]
## Expected Behaviour

I use some fake mailboxes like `mailbox ="======"` as separators between different mailboxes.

## Actual Behaviour
After the latest update, in the sidebar, all of these fake mailboxes are gone. Only the true mailboxes of a IMAP account are left.

**Comment by flatcap** [comment]
Sorry about that @xiangsheng.
There's a brief explanation and a workaround, here: #1901

**Comment by xiangsheng** [comment]
@flatcap Thank you for your kind reply. The workaround in #1901 does work. I only notice a small problem. If I want to use a same separator twice, it only appears in the sidebar for once. But somehow I can understand it. As it is treated as a true mailbox, we don't need a mailbox shown up twice, right?

**Comment by flatcap** [comment]
Ah, yes.  NeoMutt will de-duplicate the list, but you can use `named-mailboxes` with the same description, as long as each divider has a separate file.

```
touch div1 div2
```

```
mailboxes apple banana cherry
named-mailboxes "---------" div1
mailboxes damson endive fig
named-mailboxes "---------" div2
mailboxes guava haw ilama
```

**Comment by xiangsheng** [comment]
That's true. Thanks!
