### ISSUE TITLE
Segfault for OP_COPY_MESSAGE with dest=src in mbox

### ISSUE THREAD

**Issue by luchr** [neomutt/neomutt#1913]
Problem with Neomutt 2019-10-25; Line numbers below refer to commit 3cd616659.

## Steps to reproduce

Take an mbox-file `testmailbox` with an email inside. Start neomutt

```
neomutt -n -f testmailbox
```

Press 'C' to start OP_COPY_MESSAGE and choose as destination the same mbox-file and confirm "yes" for append. Then I get a segfault.

## Expected Behaviour

no segfault

## Actual Behaviour

segfault

## Analysis; Why?

I hope this time-based analysis helps because one can see where src=dest is open WRONLY and then the next `fgets` on src fails.

```
in mutt_index_menu  at index.c:2657  call to mutt_save_message
  in mutt_save_message at commands.c
    line 1109 call to mx_mbox_open
      in mx_mbox_open at mx.c:314 call to mx_open_mailbox_append
        in mx_open_mailbox_append at mx.c
          line 193 m->append = true
          line 241 call to m->mx_ops->mbox_open_append
            in mbox_mbox_open_append at mbox/mbox.c:991 call to mutt_file_fopen with mode='w'
              in mutt_file_fopen at mutt/file.c
                line 598: flags |= O_WRONLY
                line 601: call to mutt_file_open
                line 604: call to fdopen(fd, mode='w')   [*]
    line 1132 call to mutt_save_message_ctx
      in mutt_save_message_ctx at commands.c:985 call to mutt_append_message
        in mutt_append_message at copy.c:886 call to append_message
          in append_message at copy.c:848 call to fgets on fp_in which was opened O_WRONLY [*]
            results in error (errno=9: Bad file descriptor) and return -1 propagated up
    line 1132 call returns -1 
    line 1136 call to mx_mbox_close
  mutt_save_message returns -1  next in loop 
line 1149: check for new mail
line 1154: mx_mbox_check
  in mx_mbox_check at mx.c:1035 call to m->mx_ops->mbox_check
    in mbox_mbox_check at mbox/mbox.c
      line 1112: fgets return NULL => modified = true
      line 1122: call to reopen_mailbox 
        in reopen_mailbox at mbox/mbox.c:582: call to mailbox_changed(m, MBN_CLOSED)
         -> ctx_mailbox_observer at context.c:304 ctx_cleanup sets Context->mailbox=NULL
line 1155: Context->mailbox is now NULL 
line 1171: Mailbox was externally modified
line 1201: Context->mailbox->quiet = true; Segfault because Context->mailbox=NULL
```

**Comment by flatcap** [comment]
Wow @luchr, that's a brilliant bug-report.
Verified, fixed and tested within minutes :-)

Many thanks :-)

**Comment by luchr** [comment]
Thank you for your very fast reply. Unfortunately the situation with reading + writing + reading + writing + ...  is a little bit more "subtle", see an example at the pull request https://github.com/neomutt/neomutt/pull/1916#issuecomment-548772939

**Comment by luchr** [comment]
The crucial difference why this works in NeoMutt 2018-07-16 (o) but not in the new release (n) is in the `mx_mbox_open` function:

In (o) a complete new Context was created and flags (like `readonly`, `peekonly`) and filepointer `fp` were bound to the new context and were only used for/with the new Context. Hence a separate filepointer `fp` for appending/writing was created.

In (n) a complete new Context is created, but the flags and filepointer `fp` are bound to the `struct Mailbox` input argument. And `mx_mbox_open` tries to (re-)use this `struct Mailbox` which fails.

Are there any functions in (n) to (temporarily) create a new `struct Mailbox` object [based on the given mailbox object] to have a second (independent) filepointer `fp`?

**Comment by flatcap** [comment]
Hi @luchr.  Thanks for the extra debugging / suggestions.
I haven't forgotten you, I've just been a little busy with other bugs.
There **won't** be a release until I fix this bug.

---

I made one small step forward, which was to open a new read-only `FILE` ptr for each `msg_open()`.
Anyone wanting to add to the mailbox calls `msg_open_append()` which gets a copy of the read-write Mailbox `FILE` ptr.

This stops the gruesome interleaving of text that you pointed out, but internally the Mailbox gets confused about how many Emails are present.

---

Given what a mess the Mutt code is, you've shown some impressive debugging skills :-)

The original code had a separate Mailbox for each opening.
Imagine:
- User has a Mailbox open
- They go to compose an Email
- They want to attach an Email, so NeoMutt opens the Mailbox again
  This second Mailbox is completely independent of the first
- Some new mail arrives

Now, we're left with an ugly mess trying to merge the two Mailboxes.
By only using one Mailbox, there's no confusion.
The catch is that the Mailbox contains a lot of GUI information that shouldn't be there.
I'm planning to separate _that_ into a MailboxView.

**Comment by luchr** [comment]
No need to hurry (in my opinion); I've seen all the other bugs. Slow and robust fixes are better than fast instable ones.

Please tell, if I can help somehow here. I've experience in C [and I like gdb]. But this bug is the first time, where I've taken a look at neomutt's source-code. My only apology as long time neomutt user for looking that late is: "better late than never"  ;-)

I like the idea to have exactly one mailbox object (per Mailbox) and hence avoid (state-)confusions.
