### ISSUE TITLE
different sorting for attachment browser

### ISSUE THREAD

**Issue by 4nd3r** [neomutt/neomutt#192]
for example: I want my IMAP mailboxes unsorted, but files in attachment browser reverse-date.

`sort_attach_browser` or `sort_browser_attach`?

currently possible with macro, for example:
`macro compose a <enter-command>set\ sort_browser=reverse-date<enter><attach-file>?<change-dir><kill-line>~/Desktop<enter>`

**Comment by flatcap** [comment]
It's a useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
