### ISSUE TITLE
refreshing the screen with Ctrl-L doesn't fix display corruption

### ISSUE THREAD

**Issue by mgedmin** [neomutt/neomutt#1924]
## Expected Behaviour

Pressing ^L redraws the entire screen

## Actual Behaviour

Pressing ^L appears to do nothing

## Steps to Reproduce

- run neomutt under gdb
- try to use it
- whenever I view a message with an HTML body, my auto_view + mailcap configuration causes a w3m -dump to be spawned in a subprocess, which causes gdb to print some messages on screen, corrupting neomutt's output
- press ^L hoping to get the screen redrawn

## How often does this happen?

- Always

## When did it start to happen?

I'm not sure; I rarely use gdb.  The recent neomutt versions have been rather crashy, which is why gdb and why I noticed this.

## NeoMutt Version

```
NeoMutt 20191102-3-b486e3
Copyright (C) 1996-2016 Michael R. Elkins ir kiti.
NeoMutt ateina ABSOLIUČIAI BE JOKIOS GARANTIJOS; dėl smulkmenų paleisk 'neomutt -vv.'
NeoMutt yra laisva programinė įranga, ir tu gali laisvai ją platinti su tam
tikromis sąlygomis; rašyk 'neomutt -vv' dėl smulkmenų.

System: Linux 5.3.0-19-generic (x86_64)
ncurses: ncurses 6.1.20190803 (compiled with 6.1.20190803)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.12.0
hcache backends: tokyocabinet

Compiler:
cc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --prefix=/usr --sysconfdir=/etc --with-mailpath=/var/mail --mixmaster --gnutls --gpgme --gss --sasl --lua --notmuch --tokyocabinet --full-doc

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Įprastos parinktys:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Kompiliavimo parinktys:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

Jei norite daugiau sužinoti apie NeoMutt, aplankykite https://neomutt.org
Jei radote NeoMutt klaidą, praneškite apie ją
    https://github.com/neomutt/neomutt/issues
arba paštu į <neomutt-devel@neomutt.org>

```

## Extra Info

* Operating System and its version: Ubuntu 19.10
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? local

**Comment by mgedmin** [comment]
A workaround is to resize the terminal, which makes neomutt redraw everything correctly.

(Another workaround I've used in the past was to do ^Z, fg, but is annoying under gdb, which intercepts the SIGSTOP and starts interactive debugging.)

**Comment by flatcap** [comment]
I've added a `refresh()` command to the screen clear function.
Please can you see if branch [[devel/refresh]](https://github.com/neomutt/neomutt/tree/devel/refresh) fixes the problem.

**Comment by mgedmin** [comment]
It works so well I don't even get the display corruption!  gdb's "detached from pid nnn" messages flash very briefly and the screen gets redrawn instantly.

**Comment by flatcap** [comment]
Great!  Merged.

---

Cause:
I did some refactoring (9f906b87d) to try to separate the curses code.
This is leading towards better modularisation.
