### ISSUE TITLE
index_format %c reports wrong sizes

### ISSUE THREAD

**Issue by protist** [neomutt/neomutt#1925]
## Expected Behaviour
* Look in NeoMutt's index at an email that is 618 bytes.
* In previous versions of NeoMutt (e.g. b6a602e8a), the correct size is displayed, i.e. `618`.

## Actual Behaviour
* In NeoMutt 20191102, the wrong size is displayed, i.e. `5.5k`.

## Steps to Reproduce
Include `%c` in `index_format`, e.g.
```
set index_format="%4C %Z│%[%a %e %b %y %l:%M%P]│%-15.15L│%4c│%s"
```
Open NeoMutt and compare sizes between versions.

## More information
* I have also confirmed that the email is indeed the smaller size reported in the older version.
* The couple of emails I tested are not multipart, but plain text.

## How often does this happen?
In 19/20 emails that I checked, the size reported in the buggy version is larger.

## When did it start to happen?

- When I upgraded from unstable b6a602e8a to stable 20191102. (I also tried the latest 6a0e1814a, and the bug is there too.)

I'm happy to git bisect if necessary, but just wanted some feedback first in case this was already known or a dupe.

## NeoMutt Version

```
PUT YOUR "neomutt -v" OUTPUT HERE
NeoMutt 20191102
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.7-arch1-2-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
gcc version 9.2.0 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Arch Linux
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? maildir

**Comment by flatcap** [comment]
I hadn't noticed any problems with the sizes.

> Look in NeoMutt's index at an email that is 618 bytes.

Do you have a sample email that demonstrates the problem?
(some junk mail, something non-personal)

If you rename the file to `.txt`, you can attach it to a github comment.

> I'm happy to git bisect

That would be very helpful, if you have the time.

PS.  I've edited your message to strip the 'g' from the beginning of the git commits -- raw commit hashes are auto-linked by github.

**Comment by protist** [comment]
Aha, I've done some more troubleshooting. I suspect newer versions of NeoMutt include email headers in the size calculation, whereas previous versions did not? (When I posted the original issue, I had used a ripmime macro to save the email… which doesn't include the headers.)

> Do you have a sample email

Yep, [here's one](https://github.com/neomutt/neomutt/files/3803899/email.txt). With the current version of NeoMutt, the size is 3.9K, which corresponds to the total email including headers. With an older NeoMutt, e.g. b6a602e8a, the size is shown as 730, which is equivalent to the email with headers removed.

I'm not sure if relevant, but I can confirm this with a minimal `~/.mutt/muttrc`
```
set mbox_type    = Maildir
set folder       = ~/.mail
set spoolfile    = +main/Inbox
set index_format ="%4C %Z│%[%a %e %b %y %l:%M%P]│%-15.15L│%4c│%s"
```

> I've edited your message

Thank you. I forgot to strip out the `g`.

I'm still happy to git bisect, but I'm not sure which behaviour is preferred, so I won't waste my time just yet. Given that many of the headers are often to do with `Return-Path` and spam info, my inclination would be that the size should not include the headers. However, it depends on what the displayed size is meant to indicate, i.e. how much the sender has typed (probably my interpretation), or how much space the email takes on disk (perhaps less important)?

**Comment by flatcap** [comment]
It starts with ae87f840f.

Before that, the index and status bar showed different 'sizes' for an email.
The index showed the 'content size', the status bar the 'raw size'.

> what the displayed size is meant to indicate,
> i.e. how much the sender has typed (probably my interpretation)

That's reasonable

At the risk of complicating `$index_format` any further, we could:
- Restore `%c` to 'content size'
- Add `%cr` 'raw size'

**Comment by gahr** [comment]
I think `%c` is "more correct" now, by counting the full size of an email, including headers and body. If there's need for it, we could add another indicator to count only the "body" part. However, that would get complicated soon: what would we want to show in the case of MIME multiparts? Do we include the headers of each MIME subpart? I think "body" is something which doesn't really relate to what one would expect as "how much the sender has typed".

**Comment by protist** [comment]
I don't feel very strongly about it. As above, I tend towards expecting `%c` to be 'content size', but I can understand your reasons @gahr. I agree multiparts are confusing. If it contained just plain text and html, I'd just use the former, since that's what's displayed, but that only covers the simplest scenario.
