### ISSUE TITLE
sort and sort-reverse prompts broken

### ISSUE THREAD

**Issue by 4nd3r** [neomutt/neomutt#193]
press `y`, then `o` or `O`, observe.

![scrot-1476113618](https://cloud.githubusercontent.com/assets/7166727/19241626/f7c9dfd4-8efe-11e6-98e0-137e1b3f1638.png)
![scrot-1476113626](https://cloud.githubusercontent.com/assets/7166727/19241627/f7d5a152-8efe-11e6-9571-a75f808ab315.png)

**Comment by flatcap** [comment]
Hmm... You know what I'm going to say: it works for me:
```
Sort by (d)ate, (a)lpha, si(z)e, d(e)scription, (c)ount, ne(w) count, or do(n)'t sort? 
Reverse sort by (d)ate, (a)lpha, si(z)e, d(e)scription, (c)ount, ne(w) count, or do(n)'t sort? 
```
Can you try using a different locale? -- See if the strings are mangled before printing.
Failing that, can you bisect back to where the problem was introduced.

**Comment by 4nd3r** [comment]
this isn't neomutt issue.

this happens when:

1. mutt is compiled with slang
2. and used in xterm
3. which is running in i3 window manager
4. with split windows

probably my esotertic xterm configuration and/or slang and/or i3 issue. sorry for the noise.
