### ISSUE TITLE
A non-incremental terminal resize causes neomutt screen update issues

### ISSUE THREAD

**Issue by thomergil** [neomutt/neomutt#1931]
## Expected Behaviour

When using neomutt in iTerm2 on a Mac, using a keystroke that resizes the iTerm2 window, I would expect neomutt to redraw correctly.

## Actual Behaviour

When using a keystroke to change the size of an iTerm2 window to fewer lines and more columns, the bottom few 4-5 lines of neomutt remain black and can only be forced to be redrawn by going to entirely different neomutt screen (e.g., help [using the '?' key] and back). Just scrolling up and down the main index window does not fix the problem.

This problem does not happen when manually resizing the iTerm2 window by grabbing it at the bottom right of the window and then resizing it.

## Steps to Reproduce

Using iTerm2 in combination with BetterSnapTool (or likely any utility that can resize windows non-incrementally). With neomutt in the index view, then using a keystroke, change the iTerm2 window from tall and narrow to short and wide. The bottom few lines are black and should be redrawn. Resizing it back to its original size fixes the problem. Going to the help screen with '?' and out of it again also fixes the problem.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded to 20191102 from a mid-2018 version.

## NeoMutt Version

```
NeoMutt 20191102-3-b486e3
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 18.7.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.11
libidn: 1.35 (compiled with 1.35)
GPGme: 1.13.1
hcache backends: tokyocabinet, lmdb

Compiler:
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Configure options: --prefix=/Users/macuser/install/ --enable-gpgme --with-gpgme=/usr/local/opt/gpgme --gss --lmdb --notmuch --sasl --disable-doc --disable-nls --tokyocabinet --with-ssl=/usr/local/opt/openssl@1.1 --with-ui=ncurses

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/opt/gpgme/include -I/usr/local/opt/libassuan/include -I/usr/local/opt/libgpg-error/include -I/Users/macuser/install//include -DNCURSES_WIDECHAR -I/usr/local/opt/openssl@1.1/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn -inotify 
  -locales_hack -lua +meta -mixmaster -nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/Users/macuser/install//share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/Users/macuser/install//etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
MacOS 10.14.6
iTerm2 3.3.6

* Were you using multiple copies of NeoMutt at once?
No

* Were you using 'screen' or 'tmux'?
No

* Is your email local (maildir) or remote (IMAP)?
IMAP

**Comment by flatcap** [comment]
I've added a `refresh()` command to the screen clear function.
Please can you see if branch [[devel/refresh]](https://github.com/neomutt/neomutt/tree/devel/refresh) fixes the problem.

**Comment by thomergil** [comment]
@flatcap, thank you. That did not solve the issue.

**Comment by flatcap** [comment]
OK, thanks for testing.
I'll keep thinking.

**Comment by thomergil** [comment]
<img width="1274" alt="Screen Shot 2019-11-04 at 9 27 51 PM" src="https://user-images.githubusercontent.com/1020105/68155535-326a4980-ff4a-11e9-8679-f52c893f1cd0.png">

**Comment by flatcap** [comment]
Please can you try [[devel/refresh]](https://github.com/neomutt/neomutt/tree/devel/refresh)
That's a new branch, with some more aggressive screen clearing.
Thanks.

**Comment by thomergil** [comment]
That sort of fixes it, sort of. (I also learned something new about the bug in the process: pressing the resize shortcut twice fixes the problem. On the first resize it gets weird, but on the second "resize" (which isn't really a resize because the size of the window stays the same), the issue resolves itself.)

However, the behavior of ^L changed, in a good way: that did not fix the problem on master, but it does fix the problem on devel/refresh.

All in all, in summary:

master: do window resize shortcut once, problem.
master: press ^L, nothing happens, still a problem.
master: do window resize shortcut again, problem solved.

devel/refresh: do window resize shortcut once, problem.
devel/refresh: press ^L, problem solved.

I suspect this is not worth spending a lot more time on. I think anyone used to working with a terminal is willing to press ^L to redraw. Now that that works, that's good enough for me.
