### ISSUE TITLE
Failure to start if configuration file is a symbolic link

### ISSUE THREAD

**Issue by jbernard** [neomutt/neomutt#1933]
When using the `-F` argument, if the configuration file is a symbolic link, neomutt exits with “No such file or directory” when the symbolic link is valid.  If the argument to `-F` is changed to the target of the symlink, startup succeeds.   This appeared sometime between the 1025 and 1102 releases.

**Comment by flatcap** [comment]
Please can you give the branch [[fix-relative-symlink-resolution-2]](https://github.com/neomutt/neomutt/tree/fix-relative-symlink-resolution-2) a try.

**Comment by jbernard** [comment]
resolved with realpath, thanks!
