### ISSUE TITLE
Pressing "." reports "New mail in +INBOX" even though there isn't

### ISSUE THREAD

**Issue by thomergil** [neomutt/neomutt#1938]
## Expected Behaviour

When there is no new mail, pressing '.' should not tell me there is new mail.

One could argue that neomutt should only ever report on new mail when there are emails with the 'N' flag set. The current behavior does not do that, as it still reports new mail even if zero emails have the 'N' flag set, even after syncing it (using '$'). That in itself already constitutes a bug.

But previous versions of (neo)mutt had more subtle and more desirable behavior. It would stop reporting new mail once the user had opened the folder with new mail in it. I like to leave mails unread, but I don't want neomutt to continuously report those folders as having new mail in it.

All in all: neomutt should inform me of folders that have **new mail since I last opened the folder**. Once I open the folder it should consider that folder as not having new mail, even if individual emails in that folder still have the 'N' flag set.

## Actual Behaviour

1) neomutt reports on a folder as having new mail, even though that folder has not received any new mail since I last opened it.

2) More problematic: neomutt reports on a folder having new mail upon pressing '.' even though there are zero new emails in that folder. 

## Steps to Reproduce

Wait for a folder to receive new mail and for neomutt to report that that folder has new mail (obviously the folder needs to be in `mailboxes`). Read the mail. Sync the folder with '$'. Press '.' Notice how neomutt still reports that folder as having new mail.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded to 20191102.
## NeoMutt Version

```
NeoMutt 20191102
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 18.7.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.11
libidn: 1.35 (compiled with 1.35)
hcache backends: tokyocabinet, lmdb

Compiler:
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Configure options: --gss --lmdb --notmuch --sasl --tokyocabinet --with-ui=ncurses --disable-doc --disable-nls --with-ssl=/usr/local/opt/openssl@1.1 --prefix=/Users/macuser/install/

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/Users/macuser/install//include -DNCURSES_WIDECHAR -I/usr/local/opt/openssl@1.1/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme +gss +hcache -homespool +idn -inotify 
  -locales_hack -lua +meta -mixmaster -nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/Users/macuser/install//share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/Users/macuser/install//etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version

MacOS 10.14.6

* Were you using multiple copies of NeoMutt at once?

Yes, but different IMAP accounts, different folders. They do not intersect whatsoever. Previous versions of neomutt did not have this problem, with the same setup.

* Were you using 'screen' or 'tmux'?

No

* Is your email local (maildir) or remote (IMAP)?

IMAP

**Comment by roccoblues** [comment]
Hi, I'm trying to cleanup some older issues here. Can you still reproduce this behavior with the latest version? Thanks!
