### ISSUE TITLE
ability to set attach-file starting directory and save-entry destination directory

### ISSUE THREAD

**Issue by 4nd3r** [neomutt/neomutt#194]
currently possible with macros:
`macro compose a <attach-file>?<change-dir><kill-line>~/Desktop<enter>`
`macro attach s <save-entry><bol>~/Desktop/`

**Comment by flatcap** [comment]
It's a useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
