### ISSUE TITLE
Segfault upon sourcing different account settings

### ISSUE THREAD

**Issue by mattiasgiese** [neomutt/neomutt#1940]
## Expected Behaviour

I have two accounts configured in neomutt. See
https://github.com/mattiasgiese/dotfiles/blob/master/muttrc
and https://github.com/mattiasgiese/dotfiles/tree/master/mutt for details

Normally, upon pressing ALT+2 (or ALT+1) mutt should source a config file in order to use another account.

## Actual Behaviour

neomutt segfaults

If NeoMutt crashed, did your OS create a 'coredump' file?

Yup

## Steps to Reproduce

Start mutt with the supplied config, press ALT+2 to switch to another account

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded from 20191025 to 20191102

## NeoMutt Version

20191102
```
NeoMutt 20191102
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.8-arch1-1 (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
gcc version 9.2.0 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

## Extra Info

* Operating System and its version
Archlinux current

* Were you using multiple copies of NeoMutt at once?

Nope

* Were you using 'screen' or 'tmux'?

Nope

* Is your email local (maildir) or remote (IMAP)?

maildir

**Comment by noctux** [comment]
Not 100% sure whether it is the same bug, but for me, the same release and build (20191102-1) segfaulted as well in account/mailbox related code. Backtrace from gdb was:

```
Thread 1 (Thread 0x7ffff64617c0 (LWP 504211)):
#0  0x00007ffff77bab51 in __memset_avx2_erms () at /usr/lib/libc.so.6
#1  0x000055555564fbd8 in mutt_buffer_reset ()
#2  0x0000555555650142 in mutt_buffer_strcpy ()
#3  0x00005555555a6b71 in parse_mailboxes ()
#4  0x00005555555a7e93 in mutt_parse_rc_line.part ()
#5  0x00005555555a81f3 in source_rc ()
#6  0x00005555555a9010 in mutt_init ()
#7  0x00005555555711ea in main ()
```

Current master does not exhibit the issue, according to git bisect, this issue was fixed in b486e37c1d5b5ea1b426f844a01c39c2827832dc. Repackaging with this patch fixes the issue for me in the package as well.

I'm attaching a modified PKGBUILD if you want to give it a shot. If this fixes the issue, maybe this patch should go into a bugfix release so that it gets picked up broadly?

Attachments (please excuse the .txt... Iroinc that a code hosting for developers blacklists .patch files):
 - [PKGBUILD: adapted from https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/neomutt](https://github.com/neomutt/neomutt/files/3813140/PKGBUILD.txt)
 - [0001-fix-crash-in-mutt_extract_token.patch: Straight export of b486e37c1d5b5ea1b426f844a01c39c2827832dc from this repo](https://github.com/neomutt/neomutt/files/3813145/0001-fix-crash-in-mutt_extract_token.patch)

**Comment by mattiasgiese** [comment]
Commit b486e37c1d5b5ea1b426f844a01c39c2827832dc fixed the issue. Switching back and forth works like a charm now! Thank you very much for your effort!

**Comment by flatcap** [comment]
@noctux Thanks for your help

There'll be a new release containing all the latest fixes (hopefully) at the end of the week.

**Comment by noctux** [comment]
@flatcap: No need to. It should more likely be a thank _you_ for taking good care of neomutt :)

> There'll be a new release containing all the latest fixes (hopefully) at the end of the week.

Sound good

**Comment by mattiasgiese** [comment]
This still happens with neomutt 20191111.
