### ISSUE TITLE
bdb libraries path not discovered correctly

### ISSUE THREAD

**Issue by 4nd3r** [neomutt/neomutt#1942]
## Expected Behaviour

`./configure --prefix=/usr/local --bdb` exits without error.

BDB libraries are searched from `/usr/include` first, then `/usr/local/include` etc.

## Actual Behaviour

`./configure --prefix=/usr/local --bdb` exits with error.

Only `/usr/local` prefix is used for searching BDB libraries.

## Steps to Reproduce

```
$ sudo apt install libdb5.3-dev
$ ./configure --prefix=/usr/local --bdb
...
Checking for BerkeleyDB in /usr/local/include/...no
Checking for BerkeleyDB in /usr/local/include/db-5-3...no
Checking for BerkeleyDB in /usr/local/include/db53...no
Checking for BerkeleyDB in /usr/local/include/db5.3...no
Checking for BerkeleyDB in /usr/local/include/db-5...no
Checking for BerkeleyDB in /usr/local/include/db5...no
Checking for BerkeleyDB in /usr/local/include/...no
Checking for BerkeleyDB in /usr/local/include/db-6-2...no
Checking for BerkeleyDB in /usr/local/include/db62...no
Checking for BerkeleyDB in /usr/local/include/db6.2...no
Checking for BerkeleyDB in /usr/local/include/db-6...no
Checking for BerkeleyDB in /usr/local/include/db6...no
Checking for BerkeleyDB in /usr/local/include/...no
Checking for BerkeleyDB in /usr/local/include/db-4-8...no
Checking for BerkeleyDB in /usr/local/include/db48...no
Checking for BerkeleyDB in /usr/local/include/db4.8...no
Checking for BerkeleyDB in /usr/local/include/db-4...no
Checking for BerkeleyDB in /usr/local/include/db4...no
Error: Unable to find BerkeleyDB
```
Running `./configure --prefix=/usr/local --bdb --with-bdb=/usr` succeeds.

Other options don't require `--with-X=path` when `--prefix=/usr/local` is used.

**Comment by gahr** [comment]
I’m not sure we should look in /usr by default, if prefix is /usr/local. That being said, some other dependencies might work the way you expect because of some custom config tool (i.e., gpgme-config) or a simple header/library pair being in PATH or in the compiler’s default search path.

Discovery of BDB is rather involved, so we do everything manually.

It should be easy to include /usr by default but as I said, I’m not sure it would be correct to do so.

Given that —with-bdb=/usr is available exactly for your use case, I’d lean towards “not a bug”.

What do you think?

**Comment by 4nd3r** [comment]
:man_shrugging:

**Comment by Austin-Ray** [comment]
>I’m not sure we should look in /usr by default, if prefix is /usr/local [...] It should be easy to include /usr by default but as I said, I’m not sure it would be correct to do so [...] Given that —with-bdb=/usr is available exactly for your use case, I’d lean towards “not a bug”.

I agree with this logic that it's not a bug.

On November 5, 2019 5:24:20 PM EST, Pietro Cerutti <notifications@github.com> wrote:
>I’m not sure we should look in /usr by default, if prefix is
>/usr/local. That being said, some other dependencies might work the way
>you expect because of some custom config tool (i.e., gpgme-config) or a
>simple header/library pair being in PATH or in the compiler’s default
>search path.>
>>
>Discovery of BDB is rather involved, so we do everything manually.>
>>
>It should be easy to include /usr by default but as I said, I’m not
>sure it would be correct to do so.>
>>
>Given that —with-bdb=/usr is available exactly for your use case, I’d
>lean towards “not a bug”.>
>>
>What do you think?>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/neomutt/neomutt/issues/1942#issuecomment-550050455

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by 4nd3r** [comment]
if you say so.
