### ISSUE TITLE
When opening an email with an attachment, it downloads it twice

### ISSUE THREAD

**Issue by thomergil** [neomutt/neomutt#1949]
## Expected Behaviour

Open an email with an attachment. I expect neomutt to download the attachment once, then display the email.

## Actual Behaviour

After starting neomutt, open an email with an attachment. Notice that progress ("Fetching message...") goes from 0% to 100% twice--slowly for large attachments. After the first time, it only downloads the attachment once. Close neomutt, start it again, open the same email with the attachment, it downloads it twice again.

## Steps to Reproduce

See above.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded to 20191102

## NeoMutt Version

```
NeoMutt 20191102-2513-1d5e12
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 18.7.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.11
libidn: 1.35 (compiled with 1.35)
hcache backends: tokyocabinet, lmdb

Compiler:
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Configure options: --gss --lmdb --notmuch --sasl --tokyocabinet --with-ui=ncurses --disable-doc --disable-nls --with-ssl=/usr/local/opt/openssl@1.1 --prefix=/Users/macuser/install/

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/Users/macuser/install//include -DNCURSES_WIDECHAR -I/usr/local/opt/openssl@1.1/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme +gss +hcache -homespool +idn -inotify 
  -locales_hack -lua +meta -mixmaster -nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/Users/macuser/install//share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/Users/macuser/install//etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version

MacOS 10.14.6

* Were you using multiple copies of NeoMutt at once?

No.

* Were you using 'screen' or 'tmux'?

No.

* Is your email local (maildir) or remote (IMAP)?

IMAP.

**Comment by flatcap** [comment]
I've reproduced the problem and found the cause, though fixing it may take some time.

**Workaround**:
- Enable the message cache, e.g. `set message_cachedir = '~/.cache/mutt'`
- Periodically tidy old entries: `find ~/.cache/mutt -type f -mtime +30 delete`
  (over a month old)

---

When you `<display-message>` the Email is downloaded and saved to a file.
Historically, this file would be added to an internal IMAP cache (now gone).
The cache was small, limited and duplicated code in the message cache.
When NeoMutt tries to display the message, the saved file isn't used the Email gets downloaded again.

**Comment by louis77** [comment]
I noticed that I have the same issue. Regarding to the last comment, the problem is not that the email gets loaded _again_ because it was not cached, but it is acutally loaded _twice_:

```
[2020-09-17 21:11:08]<1> mutt_index_menu() Got op OP_DISPLAY_MESSAGE (75)
[2020-09-17 21:11:08]<M> imap_msg_open() Fetching message...
[2020-09-17 21:11:08]<E> mutt_bcache_put() Can't create /home/louis/.cache/mutt/imaps:louis@domain.host@imap.mailer.com/INBOX/: Not a directory
[2020-09-17 21:11:09]<M> imap_msg_open() Fetching message...
[2020-09-17 21:11:09]<E> mutt_bcache_put() Can't create /home/louis/.cache/mutt/imaps:louis@domain.host@imap.mailer.com/INBOX/: Not a directory
[2020-09-17 21:11:10]<1> mutt_copy_hdr() WEED is set
[2020-09-17 21:11:10]<1> sb_window_observer() state
```

This happens when the message is opened the first time after restarting neomutt. Subsequent opens only load the message once:

```
[2020-09-17 21:20:27]<1> mutt_index_menu() Got op OP_DISPLAY_MESSAGE (75)
[2020-09-17 21:20:27]<M> imap_msg_open() Fetching message...
[2020-09-17 21:20:27]<E> mutt_bcache_put() Can't create /home/louis/.cache/mutt/imaps:louis@domain.host@imap.mailer.com/INBOX/: Not a directory
[2020-09-17 21:20:28]<1> mutt_copy_hdr() WEED is set
[2020-09-17 21:20:28]<1> sb_window_observer() state
```

**Comment by louis77** [comment]
Ok, I found the source:
https://ircnow.org/kb/doku.php?id=openbsd:mutt

I remember that I used this template to setup my imap config for `neomutt` and perhaps other do too.
So should neomutt perhaps check if those two config variables are pointing to the same path and show a warning on startup?

**Comment by louis77** [comment]
Probable reason for the loading-twice behaviour:

https://github.com/neomutt/neomutt/blob/e326a80e6e952c9019de8b8f0782382124f07481/imap/message.c#L1985

Here the error code returned is not checked. In the subsequent lines therefore the retry-mechanism is triggered.

**Comment by louis77** [comment]
Why is `neomutt` fetching the message twice when opened first?

First open:
```
mutt_display_message()
   --> mutt_parse_mime_message()    (to make sure headers are complete)
       --> imap_msg_open()          (fails to cache, but puts headers in struct)
   --> mutt_copy_message()          (to load the actual message)
       --> imap_msg_open()          (not in cache, re-fetch and use tmp file)
```

Second open:
```
mutt_display_message()
   --> mutt_parse_mime_message()    (to make sure headers are complete)
                                    (headers are complete, nothing to do)
   --> mutt_copy_message()          (to load the actual message)
       --> imap_msg_open()          (not in cache, re-fetch and use tmp file)
```
