### ISSUE TITLE
neomutt-20191111: SIGSEGV in index.c:1198

### ISSUE THREAD

**Issue by eku** [neomutt/neomutt#1957]
## Expected Behaviour

Run neomutt on default folder /var/spool/mail/xyz

## Actual Behaviour

SIGSEGV whenever a new mail arrives.

## Steps to Reproduce

Just run neomutt an keep it open. Wait until mailbox is updated by new mail.

## How often does this happen?

- Always

## When did it start to happen?

Since 2019 release. 2018 was good.

## NeoMutt Version

neomutt-20191111

## Extra Info
```
Core was generated by `neomutt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  mutt_index_menu () at index.c:1198
1198            bool q = Context->mailbox->quiet;
```

* Operating System and its version: Fedora 30  x64
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? screen
* Is your email local (maildir) or remote (IMAP)? maildir

**Comment by flatcap** [comment]
Hmm...
Stopping it crashing is simple enough, but I want to know what's failing just before.
I've pushed a quick fix to branch [[devel/issue-1957]](https://github.com/neomutt/neomutt/tree/devel/issue-1957)

> Is your email local (maildir) or remote (IMAP)?
> > maildir

Is it?

> Run neomutt on default folder /var/spool/mail/xyz

Or is it a single file in 'mbox' format?

Either way, I can't repeat the problem

Please can you run `neomutt -d5` and have a look at the log `~/.neomuttdebug0`

Thanks.

**Comment by eku** [comment]
> I've pushed a quick fix to branch [[devel/issue-1957]](https://github.com/neomutt/neomutt/tree/devel/issue-1957)

I'm a bit lost. How do I compile neomutt. Could not find any information on that.

**Comment by flatcap** [comment]
> I'm a bit lost

Sorry, I didn't mean to assume.

> How do I compile neomutt.

To get that branch:

- `git clone -b devel/issue-1957 https://github.com/neomutt/neomutt`

There are guides:
- https://neomutt.org/distro/fedora
- https://neomutt.org/dev/build

As you've got your mail locally, you probably don't need any `configure` options, except `--disable-doc`.
You can ignore the config warnings on startup.

Any questions, just ask.
I'm also in `#neomutt` on irc.freenode.net

**Comment by eku** [comment]
After new mail arrived...

```
[2019-11-11 15:50:10]<5> mutt_addr_is_user() no, all failed
[2019-11-11 15:50:10]<5> mutt_addr_is_user() no, all failed
[2019-11-11 15:50:10]<5> mutt_addr_is_user() no, all failed
[2019-11-11 15:50:10]<5> mutt_addr_is_user() no, all failed
[2019-11-11 15:50:10]<5> mutt_addr_is_user() no, all failed
[2019-11-11 15:50:10]<5> mutt_addr_is_user() no, all failed
[2019-11-11 15:50:12]<3> mutt_index_menu() [1287]: Got op 190
[2019-11-11 15:50:12]<M> mx_mbox_close() Mailbox unverändert
[2019-11-11 15:50:12]<M> mx_mbox_close() Mailbox unverändert
```

After that it does no longer respond to key presses. Had to kill the process.

**Comment by flatcap** [comment]
I've updated the branch with a \*\*\*\*-ton of debugging messages.
They won't fix your problem, but hopefully they'll help me find the source.

Please can you give it a try.

First update your branch:

```sh
# this should do it
git pull --rebase

# failing that
git fetch origin
git reset --hard origin/devel/issue-1957
```

then, rebuild:
```sh
make clean
make
```

Then run: `neomutt -d2` and paste the logs, here.
Please check the logs before posting for any private info.

Also, please can you try copying a few emails to a separate file, e.g. 'C' to copy to `test.mbox`
Then run neomutt with no config again, but with just those emails:

```
neomutt -d2 -n -F /dev/null -f test.mbox
```

I'm wondering if there's something in one of your emails that causing problems.
Do you have a lot?

**Comment by eku** [comment]
@flatcap 
> Do you have a lot?

Not that much. Logfile attached. I remove the lines with ```write_header``` for privacy.

The freshly built binary crashes with 
[neomutt_debug2.zip](https://github.com/neomutt/neomutt/files/3854238/neomutt_debug2.zip)
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000453268 in mutt_pager (banner=banner@entry=0x0, fname=<optimized out>, 
    flags=flags@entry=66, extra=<optimized out>) at pager.c:2417
2417                rd.menu->current =
```
when new mail arrives.

**Comment by flatcap** [comment]
Sorry, for the slow reply -- busy fixing bugs.

Thanks for the debug log, that gave me the clue I needed.
When _your_ new mail arrives, I think it's creating a new file: copy, add, move into place.
Now, I can repeat your crash reliably.

**Comment by eku** [comment]
@flatcap  I'm running sendmail with procmail for receiving emails.

**Comment by flatcap** [comment]
I've updated the fix in branch [[devel/issue-1957]](https://github.com/neomutt/neomutt/tree/devel/issue-1957)
'mbox' seems to work correctly, now.

Please can you give it a try.

**Comment by eku** [comment]
@flatcap  the new version does no longer crash when new mails arrives. At least till now ;)
