### ISSUE TITLE
Removing label via edit-label then sync-mailbox does not remove X-Label

### ISSUE THREAD

**Issue by rypervenche** [neomutt/neomutt#1961]
## Expected Behaviour
Add an X-Label to an email via edit-label then sync-mailbox. Try to remove said X-Label via edit-label then sync-mailbox again. Refreshing my `~y labelname`, the email should not show up there and there should no longer be an X-Label in that email's headers.

## Actual Behaviour
After having successfully added an X-Label to an email and syncing with my IMAP server, I later try to remove said label by running edit-label, deleting the existing label, pressing enter, and then running sync-mailbox. I do this while having my email sorted with `~y labelname`. The email disappears from the list after the sync, however when I rerun the `~y labelname`, it comes right back up. Looking at the headers of the email, the X-Label is still there. I'm not quite sure what order of actions makes it work, but after many attempts it will eventually work, however I'm not sure what I've done differently.

## Steps to Reproduce
Add an X-Label to an email via edit-label then sync-mailbox. Try to remove the X-Label via edit-label and then sync-mailbox again. When either viewing the headers of the email or sorting via `~y` it still shows that the email has that X-Label in the headers.

## How often does this happen?
Seems to be almost always

## When did it start to happen?
It's possible that it's always done this. I haven't always used X-Labels.

## NeoMutt Version

```
NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.19.81-gentoo-mercure (x86_64)
slang: 2.3.2
libidn: 1.35 (compiled with 1.35)
hcache backends: lmdb

Compiler:
x86_64-pc-linux-gnu-gcc (Gentoo 9.2.0-r1 p2) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/neomutt-20180716-r1 --libdir=/usr/lib64 CCACHE=none --enable-doc --enable-nls --disable-notmuch --enable-gpgme --disable-pgp --disable-smime --disable-bdb --disable-gdbm --disable-kyotocabinet --disable-qdbm --disable-tokyocabinet --enable-idn --disable-gss --enable-lmdb --enable-sasl --with-ui=slang --sysconfdir=/etc/neomutt --enable-ssl --disable-gnutls

Compilation CFLAGS: -march=native -O2 -pipe -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -bkgdset +color -curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo
  -gnutls +gpgme -gss +hcache -homespool +idn -locales_hack -lua -meta
  -mixmaster +nls -notmuch +openssl -pgp +sasl -smime -start_color
  +sun_attachment -typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc/neomutt"
```

## Extra Info

On Gentoo Testing. Only one copy of neomutt at a time. No tmux. via IMAP.

**Comment by roccoblues** [comment]
Hi, I'm trying to cleanup some older issues here. Can you still reproduce this behavior with the latest version? Thanks!
