### ISSUE TITLE
Whole screen often flashes when navigating between emails

### ISSUE THREAD

**Issue by protist** [neomutt/neomutt#1966]
## Expected Behaviour

Have an email open, then navigate to another email with `j` or `k`.

## Actual Behaviour

The whole screen often flashes when changing emails. This occurs intermittently, but can occur with any email. However, it appears to flash more regularly with "difficult" emails, e.g. PGP-decrypted emails or w3m-converted html emails.

## When did it start to happen?

A git bisect shows the first bad commit is 3d2a85eb39a03391464a1a1254f769cace93d340.

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20180716-2536-3d2a85
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.11-arch1-1 (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
cc (GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/bin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: up-to-date Arch Linux
* Were you using multiple copies of NeoMutt at once? Tested and confirmed both ways.
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? Local maildir.

**Comment by flatcap** [comment]
@protist @thomergil
Please can you try the latest [[devel/refresh]](https://github.com/neomutt/neomutt/tree/devel/refresh)

`mutt_window_clear_screen()` contains two methods of wiping the screen, but these actions are cached.
It's the `refresh()` that actually makes the screen clear.

As `refresh()` is called in other places, after drawing, I think this is causing the flickering.

Please can you check:
- @protist that the flicker is gone
- @thomergil that your screen resize problem isn't made worse

Thanks

**Comment by protist** [comment]
@flatcap unfortunately the flicker is still present in [devel/refresh] f347d565b.

**Comment by flatcap** [comment]
@protist 
OK, thanks.  I'll keep thinking.

**Comment by thecsw** [comment]
@flatcap Hey there! I opened the issue about broken mailboxes in the latest release #1958 
I just want to say that I fixed it by declaring named mailboxes and latest release was working fine. However, I'm still using the old 20191102 release, as the latest one makes my screen flash every time I switch mailboxes, which is *very* annoying and *maybe* even dangerous for some people. I hope this problem gets resolved. Thanks

**Comment by protist** [comment]
@thecsw Thank you for the comment. I actually did mean to mention this in the original report, but yes, when cycling quickly through messages, it certainly seems like it might need an epilepsy warning!

**Comment by thecsw** [comment]
@protist sure! 
While we're here, I was curious if you know about a way to make neomutt show reply threads in stairs? I've seen people having it but I could never find any documentation about it.
By stairs, I mean threads going like
```
original message
    --> reply
        --> another reply
```

**Comment by protist** [comment]
@thecsw that's [`sort=threads`](https://neomutt.org/guide/reference.html#3-388-%C2%A0sort). I actually use a [macro](https://gitlab.com/muttmua/mutt/wikis/ConfigTricks#abuse-macros-as-variables) to let me toggle between threaded and un-threaded views.

**Comment by thecsw** [comment]
@protist Thank you! I finally found my sweetspot with `sort=reverse-threads` and `set sort_aux=last-date-received`
