### ISSUE TITLE
Virtual folders conflict with trash folder.

### ISSUE THREAD

**Issue by hsanson** [neomutt/neomutt#1975]
## Expected Behaviour
Refreshing the index should remove deleted messages and show new ones.

## Actual Behaviour

Sometimes when refreshing the index (e.g. pressing $) to remove marked for deletion messages I get the following error:

```
Unable to write notmuch://?query=tag:inbox AND NOT tag:killed AND NOT tag:spam
```

## Steps to Reproduce

Unfortunately I am unable to replicate this reliable. Leaving neomutt open for extended time seems to trigger this. Closing and reopening it fixes the problem for a while.

## How often does this happen?

- Sometimes

## NeoMutt Version

```
NeoMutt 20191111
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.15.0-70-generic (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.12.0
hcache backends: lmdb

Compiler:
cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --prefix=/usr --notmuch --lmdb --ssl --sasl --gpgme

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

コンパイル時オプション:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

I use mainly virtual folders with neomutt. The main part of my config below:

```
unmailboxes *
unvirtual-mailboxes *

set virtual_spoolfile=yes
set mbox_type=Maildir
set folder="$HOME/Mail/$from"
set record="$HOME/Mail/$from/Sent"

virtual-mailboxes "$from/Inbox"   "notmuch://?query=path:$from/** AND tag:inbox AND NOT tag:killed AND NOT tag:spam"
virtual-mailboxes "$from/Sent"   "notmuch://?query=path:$from/** AND tag:replied AND NOT tag:killed AND NOT tag:spam"
virtual-mailboxes "$from/Archive" "notmuch://?query=path:$from/** AND NOT tag:inbox AND NOT tag:killed AND NOT tag:spam"
virtual-mailboxes "$from/Spam"    "notmuch://?query=path:$from/** AND tag:spam"
virtual-mailboxes "$from/Trash"   "notmuch://?query=path:$from/** AND tag:killed"

set spoolfile="$from/Inbox"

bind  index c noop
bind  index c change-vfolder

macro index,pager a "<enter-command>unset resolve<enter><tag-prefix><modify-labels-then-hide>-inbox -spam -killed<enter><enter-command>set resolve<enter><tag-prefix><undelete-message>" "archive message"
macro index,pager i "<enter-command>unset resolve<enter><tag-prefix><modify-labels-then-hide>+inbox -spam -killed<enter><enter-command>set resolve<enter><tag-prefix><undelete-message>" "unarchive message"
macro index,pager s "<enter-command>unset resolve<enter><tag-prefix><modify-labels-then-hide>-inbox +spam -killed<enter><enter-command>set resolve<enter><tag-prefix><undelete-message>" "mark spam message"
macro index,pager d "<enter-command>unset resolve<enter><tag-prefix><modify-labels-then-hide>-inbox -spam +killed<enter><enter-command>set resolve<enter><tag-prefix><delete-message>" "delete message"
```

**Comment by jindraj** [comment]
This is what I see in debug log when this happens. I'm trying to change folder - so sync on current folder is called. I'll recompile neomutt with debug and try to attach `lldb` to the process next time.

```
[2019-11-23 15:42:16]<3> mutt_index_menu() [1281]: Got op 231
[2019-11-23 15:42:16]<M> sync_mailbox() Writing notmuch://?query=tag:unread NOT query:junk...
[2019-11-23 15:42:16]<1> nm_mbox_sync() nm: sync start
[2019-11-23 15:42:16]<4> mutt_progress_update() updating progress: 0
[2019-11-23 15:42:16]<4> mutt_progress_update() updating progress: 0
[2019-11-23 15:42:16]<P> maildir_sync_message() rename: No such file or directory (errno = 2): No such file or directory
[2019-11-23 15:42:16]<1> nm_mbox_sync() nm: .... sync done [rc=-1]
[2019-11-23 15:42:16]<E> sync_mailbox() Unable to write notmuch://?query=tag:unread NOT query:junk
[2019-11-23 15:42:16]<2> nm_db_get_filename() nm: db filename '/Users/jindraj/.mail/gmail'
[2019-11-23 15:42:16]<2> nm_db_get_mtime() nm: checking '/Users/jindraj/.mail/gmail/.notmuch/xapian' mtime
[2019-11-23 15:42:16]<2> nm_mbox_check() nm: check unnecessary (db=1574520125 mailbox=1574520125)
[2019-11-23 15:42:16]<5> mutt_addr_is_user() no, all failed
[2019-11-23 15:42:16]<5> mutt_addr_is_user() no, all failed
[2019-11-23 15:42:16]<5> mutt_regexlist_match() neomutt@noreply.github.com matches @noreply.github.com
[2019-11-23 15:42:16]<5> mutt_addr_is_user() no, all failed
[2019-11-23 15:42:16]<5> mutt_regexlist_match() neomutt@noreply.github.com matches @noreply.github.com
[2019-11-23 15:42:16]<5> mutt_addr_is_user() no, all failed
[2019-11-23 15:42:16]<5> mutt_regexlist_match() neomutt@noreply.github.com matches @noreply.github.com
[2019-11-23 15:42:16]<5> mutt_addr_is_user() no, all failed
[2019-11-23 15:42:16]<5> mutt_addr_is_user() no, all failed
[2019-11-23 15:42:16]<5> mutt_regexlist_match() neomutt@noreply.github.com matches @noreply.github.com
```

**Comment by hsanson** [comment]
How to reproduce the problem:

1. Open a virtual folder (e.g.  notmuch://?query=tag:inbox  AND NOT tag:killed AND NOT tag:spam)
2. Change a message tag with `push "<modify-labels-then-hide>-inbox +killed<enter>`
3. Remove the actual message from maildir folder.  I have a script that runs periodically and will move all messages with killed tag to a trash folder. 
4. Refresh the index, neomutt will complain it cannot write to virtual folder.
5. Restore original labels back with `push "<modify-labels-then-hide>+inbox -killed<enter>`
6. Refresh the index, no error occurs now.

Notes:
  - I have `unset trash` on my config so neomutt should not be trying to move around trashed messages.
  - I also tried setting and unsetting maildir_trash. In both cases the problem persist.

Theory:
  - neomutt struggles when it refreshes the index if the messages with changed tags do not exist physically on disk.

**Comment by Austin-Ray** [comment]
@jindraj , @hsanson : I changed the notmuch backend's sync behavior to warn the user of an error instead of aborting the sync. Could you try out `devel/notmuch-sync` branch to see if it stops the message from appearing?

Please note that is only a first step in correcting the problem. Ideally, we prevent the error from ever occurring. This just makes a note of the error then warns the user instead of aborting.

**Comment by jindraj** [comment]
> @jindraj , @hsanson : I changed the notmuch backend's sync behavior to warn the user of an error instead of aborting the sync. Could you try out `devel/notmuch-sync` branch to see if it stops the message from appearing?
> 
> Please note that is only a first step in correcting the problem. Ideally, we prevent the error from ever occurring. This just makes a note of the error then warns the user instead of aborting.

I applied your changes on top of devel/apple since I'm having problem building neomutt lately on macOS. I'll be using this for a while to see how it behaves and let you know.

**Comment by Austin-Ray** [comment]
@jindraj : How's your testing going? From my end, it's been pretty successful so far.

**Comment by jindraj** [comment]
> @jindraj : How's your testing going? From my end, it's been pretty successful so far.

So far so good. I believe it would throw an error in the time I'm using your change.

**Comment by jindraj** [comment]
ok, here we go. Now I'm starting to be sceptic whether I'm running neomutt with or without your changes 😕 How about You have you encountered the issue?
```[19:01:59]<M> Writing notmuch://?query=tag:unread NOT query:junk...
[19:01:59]<E> rename: No such file or directory (errno = 2): No such file or directory
[19:01:59]<E> Unable to sync 1 messages due to external mailbox modification
[19:01:59]<E> Unable to write notmuch://?query=tag:unread NOT query:junk```

**Comment by hsanson** [comment]
I can confirm the issues is still present. I follow the same steps I described before and I still get the "Unable to write notmuch..." error using this branch.

> How to reproduce the problem:
> 
> 1. Open a virtual folder (e.g.  notmuch://?query=tag:inbox  AND NOT tag:killed AND NOT tag:spam)
> 2. Change a message tag with `push "<modify-labels-then-hide>-inbox +killed<enter>`
> 3. Remove the actual message from maildir folder.  I have a script that runs periodically and will move all messages with killed tag to a trash folder.
> 4. Refresh the index, neomutt will complain it cannot write to virtual folder.
> 5. Restore original labels back with `push "<modify-labels-then-hide>+inbox -killed<enter>`
> 6. Refresh the index, no error occurs now.
> 
> Notes:
> 
> * I have `unset trash` on my config so neomutt should not be trying to move around trashed messages.
> * I also tried setting and unsetting maildir_trash. In both cases the problem persist.
> 
> Theory:
> 
> * neomutt struggles when it refreshes the index if the messages with changed tags do not exist physically on disk.

**Comment by Austin-Ray** [comment]
Apologies for the delay in responding to this issue. 

I hope I didn't misrepresent my patch. It's purpose is not to prevent the error, but to stop leaving the user in a nearly unrecoverable state. Neomutt just logs that the error's occurrence and moves on. The previous behavior had Neomutt encounter the error and stop, which prevented the user from leaving the mailbox unless they knew the specific email that caused the error.

I'm still working on how to fix the root cause, but it's possible to improve user experience in the meantime.

**Comment by hsanson** [comment]
Oh, I should read more carefully.  Yes, this improves the user experience. Without this patch when the error occurs I cannot refresh the index and cannot change to other virtual mailboxes.  I have to exit neomutt and start it again in order to get it working  back to normal. With this patch, even if the error occurs, the index does update properly and I can change mailboxes. No need to restart neomutt to continue reading my mail.

**Comment by Austin-Ray** [comment]
I've rebased my branch onto master and added two more patches:

 1.  Ensure file path is updated when modifying tags (this solves a related problem where file is moved underneath neomutt due to maildir flag changes.)
 2. During mailbox sync, if we're unable to sync the email's file path, query notmuch for a new path. Since notmuch is our source of truth, it should be aware of it.

Patch 2 should get rid of the unable to sync message. Please test it out if you have some time and let me know if it helps.

@hsanson 

> Remove the actual message from maildir folder. I have a script that runs periodically and will move all messages with killed tag to a trash folder.

Can I see the script? I realized I've never asked.

**Comment by hsanson** [comment]
Is a 224 lines bash script that has been evolving for many many years....  Here I have removed some parts and left the important ones.

In short this script does for each mailbox I have configured:

  1. Move mails between maildir folders based on notmuch tags.
      Anything with "inbox" tag is moved to the Inbox maildir
      Anything with "spam" tag is moved to the Spam maildir
      and so on....
       The move_xxx methods are in charge of the magic.
  2. Call mbsync to sync the maildirs with the remote IMAP server.
  3. Call notmuch new to index new emails
  4. Assign labels based on maildir
      Anything new in the Inbox maildir is assigned "inbox" label
      Anything new in the Spam maildir is assigned "spam" label
      and so on...
  5. Finally remove the "new" tag from all emails.

```sh
#!/usr/bin/env bash

MAILDIRS=$1
MAILDIRS=${MAILDIRS:="emai1@email.com email2@email.com"}

NOTMUCH=/usr/bin/notmuch
MBSYNC=/usr/bin/mbsync
NMCLI=/usr/bin/nmcli
NOTIFY_SEND=/usr/bin/notify-send
FFPLAY=$(which ffplay)
RINGTONE="$HOME/.config/alot/mutt.ogg"
ICON="$HOME/.config/alot/mutt.png"

LOCKFILE=/var/lock/$(basename "$0")
LOCKFD=99

# PRIVATE
_lock()             { flock "-$1" "$LOCKFD"; }
_no_more_locking()  { _lock u; _lock xn && rm -f "$LOCKFILE"; }
_prepare_locking()  { eval "exec $LOCKFD>\"$LOCKFILE\""; trap _no_more_locking EXIT; }

# Moves all messages accordingly to the notmuch labels they have.
# IMPORTANT: The order in which these must be called is important. Changing the
# order can result in message loss.
_move_all() {
  _move_spam "$1"
  _move_trash "$1"
  _move_sent "$1"
  _move_inbox "$1"
  _move_archive "$1"
}

# Moves a single email from $1 to $2 removing the UID to avoid duplicate UID
# issues when running mbsync.
_move_mail() {
  FILE=${1##*/}
  FILE_NOUID=${FILE/,U=[0-9]*:/:}
  FILE_NOUID=${FILE_NOUID/,U=[0-9]*/}
  echo "  moving $1 to $2"
  mv -f "$1" "$2/$FILE_NOUID"
}

# Copies a single email from $1 to $2 removing the UID to avoid duplicate UID
# issues when running mbsync.
_copy_mail() {
  FILE=${1##*/}
  FILE_NOUID=${FILE/,U=[0-9]*:/:}
  FILE_NOUID=${FILE_NOUID/,U=[0-9]*/}
  echo "  copying $1 to $2"
  cp -f "$1" "$2/$FILE_NOUID"
}

_move_archive() {
  echo "Archiving $1"

  # Ensure all non inbox emails exist also in Archive
  FILES=$(notmuch search --output=files path:"$1"/** AND NOT tag:inbox AND NOT tag:spam AND NOT tag:killed AND NOT tag:sent | grep "$1" | grep -v Archive)
  for i in $FILES; do _move_mail "$i" ~/Mail/"$1"/Archive/cur; done

  # Remove all non inbox messages from Inbox
  notmuch search --output=files path:"$1"/** AND folder:"$1"/Inbox AND NOT \
    tag:inbox | grep "$1" | grep -v Archive | xargs -I{} rm -f {}

}

_move_sent() {
  echo "Moving sent $1"
  FILES=$(notmuch search --output=files path:"$1"/** AND NOT tag:spam AND NOT tag:killed AND tag:sent | grep "$1" | grep -v Sent)
  for i in $FILES; do _move_mail "$i" ~/Mail/"$1"/Sent/cur; done
}

_move_inbox() {
  echo "Moving inbox $1"
  FILES=$(notmuch search --output=files path:"$1"/** AND NOT tag:killed AND NOT tag:spam AND tag:inbox AND NOT tag:sent | grep "$1" | grep -v Inbox)
  for i in $FILES; do _move_mail "$i" ~/Mail/"$1"/Inbox/cur; done
}

_move_spam() {
  echo "Moving spam $1"
  FILES=$(notmuch search --output=files path:"$1"/** AND tag:spam  AND NOT tag:killed | grep "$1" | grep -v Spam)
  for i in $FILES; do _move_mail "$i" ~/Mail/"$1"/Spam/cur; done
}

_move_trash() {
  echo "Moving trash $1"
  FILES=$(notmuch search --output=files path:"$1"/** AND tag:killed | grep "$1" | grep -v Trash)
  for i in $FILES; do _move_mail "$i" ~/Mail/"$1"/Trash/cur; done
}

## Remove specific emails.
## Gmail accounts delete messages in the Trash/Spam folders so no need to worry
## about them.
## https://wiki.archlinux.org/index.php/Notmuch
_delete_old() {
  echo "Deleting old mails in $1"
  $NOTMUCH search --format=text0 --output=files "path:$1/**" AND tag:zabbix AND tag:killed AND date:..10day | xargs -0 --no-run-if-empty rm -v
  $NOTMUCH search --format=text0 --output=files "path:$1/**" AND tag:gitlab AND tag:killed AND date:..10day | xargs -0 --no-run-if-empty rm -v
  $NOTMUCH search --format=text0 --output=files "path:$1/**" AND tag:killed AND date:..6month | xargs -0 --no-run-if-empty rm -v
  $NOTMUCH search --format=text0 --output=files "path:$1/**" AND tag:spam AND date:..1month | xargs -0 --no-run-if-empty rm -v
  $NOTMUCH new
}


_alert() {
  NEW_MAILS=$(notmuch count path:"$1"/** AND tag:new AND tag:inbox)

  if [ "$NEW_MAILS" -gt 0 ]
  then
    $NOTIFY_SEND -a neomutt -t 7000 --icon="$ICON" "MAIL - $1" "$NEW_MAILS new mails."
    $FFPLAY -vn -nodisp -hide_banner -autoexit -t 0.7 "$RINGTONE" &>/dev/null &
  fi
}

# ON START
_prepare_locking

# PUBLIC
exlock_now()        { _lock xn; }

exlock_now || exit 0

STATE=$(LANG=us $NMCLI networking connectivity)

if [ "$STATE" != 'full' ]
then
  echo "##### No network, skip ######"
  exit 0
fi

_delete_old email1@email.com

for mailbox in $MAILDIRS
do

  mkdir -p "$HOME/Mail/$mailbox"

  #echo "####### Sync Maildirs $mailbox ###########"
  _move_all "$mailbox"

  echo "####### Sync IMAP $mailbox ###########"
  timeout 1000 $MBSYNC -V "$mailbox"
  CODE=$?

  if [ $CODE -eq 124 ]
  then
    echo "###### WARN mbsync for $mailbox timed out"
    continue
  fi

  if [ $CODE -lt 0 ]
  then
    echo "###### WARN mbsync for $mailbox failed with exit code $CODE"
    continue
  fi

  echo "####### Indexing Mails $mailbox ###########"
  $NOTMUCH new

  echo "####### Sync Labels $mailbox ###########"
  $NOTMUCH tag -inbox -killed -spam -- folder:"$mailbox/Archive"
  $NOTMUCH tag +inbox -killed -spam -- folder:"$mailbox/Inbox"
  $NOTMUCH tag -inbox +killed -spam -- folder:"$mailbox/Trash"
  $NOTMUCH tag -inbox -killed +spam -- folder:"$mailbox/Spam"
  $NOTMUCH tag +draft -- folder:"$mailbox/Drafts"
  $NOTMUCH tag -inbox +sent -- folder:"$mailbox/Sent"

  echo "####### Notifications ############"
  _alert "$mailbox"

  $NOTMUCH tag -new -- tag:new

done

exit 0
```

**Comment by hsanson** [comment]
So far this branch is working fine for me.
