### ISSUE TITLE
Empty mailboxes keep new flag

### ISSUE THREAD

**Issue by jo-so** [neomutt/neomutt#1978]
Since 314b763381858f78feb9a8f740442a0db3b6e78b, the new flag doesn't get removed from the mailbox.

1. Open neomutt and go to a mailbox with unread messages.
1. Read all messages by opening them
1. Go to another mailbox
1. Open the folder view of your mailboxes and the new flag is still there.

**Comment by flatcap** [comment]
Hmm... I'm not seeing that.

Is your email Imap or Maildir?
Is `mail_check_recent` set?
Which version are you using?  2019-11-11, or `master`?
(I made a commit after the release, c61967a1c, that I thought fixed everything)

**Comment by jo-so** [comment]
Richard Russon hat am Mi 20. Nov, 04:53 (-0800) geschrieben:
> Hmm... I'm not seeing that.
> 
> Is your email Imap or Maildir?

I'm using Maildir

> Is `mail_check_recent` set?

No, it's unset.

> Which version are you using?  2019-11-11, or `master`?

I'm using 2019-11-11, but it also happens with
fb79313caba4093c0b4071dc2c94724660fe9659
