### ISSUE TITLE
new_mail_command doesn't work.

### ISSUE THREAD

**Issue by kchibisov** [neomutt/neomutt#1979]
I've recently updated to the recent version and noticed that my `new_mail_command` doesn't work any more for me. It was working fine for a long time on version 2018-07-16.

So, I've decided to bisect and stop at  9d35ea3bf3149c22f748a697896f0a2e7c094ea3
The commit could be a bit off, but it was working here  e0738e82938957f0d55c79b749f3c87a2d339e85 at least(the commits in between are crashing neomutt on new mail).

Arch Linux, was building with this command to bisect
`./configure --with-ui=ncurses --disable-doc --ssl --sasl --lmdb`

## Steps to Reproduce

I'm using these setting that could be relevant.
```
set mail_check_stats = yes
set mail_check_stats_interval = 1
set mail_check = 5
set new_mail_command="notify-send -t 3000 --icon /usr/share/pixmaps/Alacritty.svg '%?n?%n new messages.?' &"
```

setup new_mail_command and get a mail.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded

## NeoMutt Version
current version I run.

```
NeoMutt 20191111-23-fb7931
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.11-arch1-1 (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
gcc version 9.2.0 (GCC)

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime
  -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

I'm using offlineimap + maildir backend in neomutt.

**Comment by flatcap** [comment]
Thanks for the bisect, @kchibisov, they're always a great help.

Now, about the new mail command.  I think it **is** working, but there are a few problems.

The command isn't very well written.  It's piggy-backed on top of Mutt's beep-on-new-mail.
By the time the command is called, it doesn't know _which_ mailbox has the new mail.

Using your example, I didn't get a notification when the mail arrived in a different mailbox,
but I did see an error message from `notify-send` -- 'No summary specified.'
The `%n` conditional sees zero new emails in the current mailbox, so the string is empty so `notify-send` fails.
Changing the string to `NeoMutt: %?n?%n new messages.?` means it works (but it still doesn't know how many emails).

In the not-too-distant future, the new mail command **will** have access to the mailbox details.

Your issue has highlighted one other bug, though.
There's a delay (`$mail_check` seconds) between the mail arriving and the notification being sent.
That needs investigating.

**Comment by kchibisov** [comment]
>Changing the string to NeoMutt: %?n?%n new messages.? means it works (but it still doesn't know how many emails).

FWIW I can't get `set new_mail_command="ABSOLUTE_PATH_TO_SCRIPT"` to work reliably either, even if I wait like a minute (have 5 secs check). I mean it worked like 2/5 times for me, but not **always**.

P.s.
I have 4 mail boxes, but I'm always getting a mail in the currently selected mailbox.

**Comment by gahr** [comment]
@kchibisov Could you please give the branch ` devel/issue-1979` a try? Thanks!
