### ISSUE TITLE
Add a Github hook to generate new documentation if sth in the neomutt/docs folder has changed.

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#198]
Currently, parts of our documentation (e.g. [our features page on neomutt.org](https://www.neomutt.org/features.html)) are autogenerated from the [manual.xml.head file and others](https://github.com/neomutt/neomutt/blob/neomutt/doc/manual.xml.head). 

I like the idea of having a script which builds on every commit - where sth in the docs folder has changed - the new documentation and commits that onto our website repository. To avoid confusion, it would make sense imho, if we prefix every of such commits with sth like `[Automatic Update]:`

What do you think about this idea?

**Comment by flatcap** [comment]
It's a great idea.  There are two ways it could be done:
- [GitHub Webhooks](https://developer.github.com/webhooks/)
- [TravisCI](https://travis-ci.org/neomutt/neomutt)

## GitHub Webhooks

This provides hooks perform an HTTP POST to a given address.
For this we'd need a web server.

BTW, if anyone wants to experiment with these hooks, I'll happily set them up.

## TravisCI

Travis is already called on every commit.  Adding an extra job to push the docs is simple enough.
The private ssh key required to do the push securely, can be encrypted in Travis.

## Scripting

The trickly bit is getting the docs in a state that could be scripted.
I think I'm close for the main manual: [docbook](https://github.com/neomutt/docbook).

**Comment by toogley** [comment]
> The trickly bit is getting the docs in a state that could be scripted.
> I think I'm close for the main manual: docbook.

I'm confused by that. [In this issue](https://github.com/neomutt/neomutt/issues/166#issuecomment-254038699), you said:

> The only bits that are generated, currently, are:
>
>  *  NeoMutt Manual (guide)
>  *   Feature Pages

So, what is missing in this regard?

**Comment by flatcap** [comment]
The docs (manual and features) on the website currently are generated by an ugly script.
The results need "adjustment" to fit into separate directories (as I'd like).

The [docbook repo](https://github.com/neomutt/docbook) is an experiment to simplify the process.
The [XSLT](https://en.wikipedia.org/wiki/XSLT) which controls the conversion from DocBook to HTML is quite configurable.  I didn't know that until recently.

By tweaking the ids within the DocBook, I can create the structure I want.
Other variables control which elements are displayed in the Tables-of-Content.  I haven't experimented with that yet.
