### ISSUE TITLE
Failure to purge emails from named mailbox upon folder change

### ISSUE THREAD

**Issue by hakova** [neomutt/neomutt#1984]
## Expected Behaviour

Mark certain emails for deletion in a named mailbox. Switch to a different folder. Expect to see a prompt at the bottom of the screen for purging marked emails in the present folder before switch actually occurs.

## Actual Behaviour

Sometimes, but not always, the prompt does not appear and folder switches without the prompt. Going back to the initial folder reveals that the marked emails were not purged, and the deletion marks have been removed from them.

If NeoMutt crashed, did your OS create a 'coredump' file?

Neomutt does not crash with this behavior.

## How often does this happen?

- Sometimes, and inconsistently. I have mostly named mailboxes and hence the description above. I haven't tried if similar behavior is observed in regular mailboxes or not.

## When did it start to happen?

- When I upgraded to 20191111-1 (arch package)
  I did not observe this on the previous version (20191102-1)

## NeoMutt Version
20191111
```
$ neomutt -v
NeoMutt 20191111
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.19.84-1-MANJARO (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
gcc version 9.2.0 (GCC)

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime
  -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

Any pointers will be appreciated. I am happy to help provide more information as needed.

**Comment by hakova** [comment]
It is like sync-mailbox command is not executed when exiting the folder for named-mailboxes. When I test this for the mailboxes descriptor instead of named-mailboxes, neomutt behaves as expected, i.e. prompts for purging the tagged emails for deletion.

**Comment by flatcap** [comment]
Sorry about that, @hakova, but good news.  I think we've already fix this bug.

If you're technical and have a moment, please can you build NeoMutt from `master`.
It would be helpful if you could check that your problem's fixed.

If not, don't worry.  There's a new release planned in a few days.

**Comment by hakova** [comment]
No worries Richard, thank *you* for your prompt response and even more
*thank you* for your fix!

I think I will just wait out for the new release :). I believe I can
build NeoMutt with a little help, but I am not sure if I can remove the
built version when the new release arrives, for my set up to stay sane
and upgradeable.

Thanks again for making this project available and well-maintained!

**Comment by Austin-Ray** [comment]
Hi @hakova, does the 20191207 release resolve the issue?

**Comment by hakova** [comment]
Hi Austin,

On 20/01/08 04:57PM, Austin Ray wrote:
> Hi @hakova, does the 20191207 release resolve the issue?
>
Unfortunately, I 20191207 release did not resolve the issue. I still
have to use sync-mailbox command when switching certain mailboxes.
Patiently waiting for the next release :).

**Comment by roccoblues** [comment]
Hi, I'm trying to cleanup some older issues here. Can you still reproduce this behavior with the latest version? Thanks!
