### ISSUE TITLE
Segmentation fault on sending email.

### ISSUE THREAD

**Issue by nkakouros** [neomutt/neomutt#1990]
## Expected Behaviour

I was trying to send an email.

## Actual Behaviour
The email gets sent, but neomutt crashes.

If NeoMutt crashed, did your OS create a 'coredump' file?

I don't know. I only get:

```
Segmentation fault (core dumped)
```

## Steps to Reproduce

- Install neomutt
- Install msmtp
- Install offlineimap
- In neomuttrc add only the mailbox config
- Send a new email

## How often does this happen?

- Always

## When did it start to happen?

On first try ever.

## NeoMutt Version

```
NeoMutt 20191111-39-6a98d5
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.12-arch1-1 (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
cc (GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/bin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
Arch linux latest

* Were you using multiple copies of NeoMutt at once?
No.

* Were you using 'screen' or 'tmux'?
No.

* Is your email local (maildir) or remote (IMAP)?
maildir

I also installed and tried with mutt, using the exact same config. The mail there was also sent succesfully, but mutt did not crash. Instead, I got the following error:

```



-- Mutt: Compose  [Approx. msg size: 0.1K   Atts: 1]------------------------------------------
Fcc failed. (r)etry, alternate (m)ailbox, or (s)kip?
```

I am a totally new neomutt (or mutt) user, so please bare with me.

**Comment by flatcap** [comment]
Sorry about that, @nkakouros.
Thanks for the bug report.

I can't repeat this, either with my 'normal' config, or no-config-at-all.
Please can you paste your config.

> Segmentation fault (core dumped)

How technical are you?
Would you be able to run NeoMutt in a debugger?  (to get a backtrace)

---

btw, Arch seems to be building from our development version (`master`).
Generally, that's stable enough, but it's under heavy development, so occasionally things break.
The latest release is '2019-11-11'.

**Comment by nkakouros** [comment]
I sent you the output of strace. Is this useful?

I tried installing both the stable version and the latest dev version and they both had the same behavior.

My config file is:

```
bind index,pager \Cb sidebar-toggle-visible

# IMAP: offlineimap
set folder = "~/Documents/mail/"
source ~/.config/neomutt/mailboxes
set spoolfile = "+account/INBOX"
set record = "+account/Sent\ Items"
set postponed = "+account/Drafts"
```

**Comment by nkakouros** [comment]
Actually, I added `set copy=no` to my neomuttrc and the segmentation fault is gone. So the error that mutt is emitting must be what crashes neomutt. 

But why am I getting that fcc error in the first place? The mail folder has the correct permissions for my user, so I don't know why neomutt cannot write the sent email.

**Comment by flatcap** [comment]
> `set copy=no` ... and the segmentation fault is gone

Thanks, that ties in nicely with the `strace` output you sent me.
Somewhere deep in the 'fcc' code is going wrong (and that code has changed recently).

Are there emails in `+account/Sent\ Items` ?
Can you 'c' copy emails to `+account/Sent\ Items` ?
What's `neomutt -Q mbox_type` ?

**Comment by nkakouros** [comment]
I started with a new muttrc and configured 2 accounts this time. Sending works fine now. I don't know what I changed exactly but I 'm glad I don't get errors. Leaving this open for the segmentation fault. Thank you for your support.

**Comment by flatcap** [comment]
Good.  I'm glad things are working.
I'll keep searching for the bug.
