### ISSUE TITLE
Add contrib/ folder under /usr/share during build

### ISSUE THREAD

**Issue by nkakouros** [neomutt/neomutt#1994]
## What would you like to be able to do?

I am not sure I should ask for this here or to my distribution's package maintainers. I noticed that there are some nice files under `contrib/` in the repository. I tried to locate them in my file system but I couldn't. Such files are usually under `/usr/share/`. If there were there I could easily eg source a colorscheme in my neomuttrc. Could the makefile include this?

**Comment by flatcap** [comment]
Hmm... the default install definitely installs the contrib files.
On my machine, under `/usr/share/doc/neomutt/`, I see dirs:

- `colorschemes`
- `hcache-bench`
- `keybase`
- `logo`
- `lua`
- `samples`
- `vim-keys`

In the other issue, you mentioned Arch.
@neomutt/arch-users Where does the contrib do?

**Comment by protist** [comment]
I can confirm that these directories are also installed in Arch both with `neomutt` from the official repos and also `neomutt-git` from AUR.

**Comment by protist** [comment]
Also, I'm not sure if you know, @nkakouros, but you can list the files that are installed by the package with `pacman -Ql neomutt`.

**Comment by nkakouros** [comment]
Thank you both for the replies. I didn't know about the pacman command, it is very helpful!
