### ISSUE TITLE
verify server connection security before typing the password

### ISSUE THREAD

**Issue by sfindeisen** [neomutt/neomutt#1996]
The idea is to have more information about the current mail server connection security when typing in the password. Currently there is just 1 line of status which changes very quickly, so when the password prompt appears, SSL information is already gone.

## What would you like to be able to do?

I would like to be able to verify the protocol that is being used to send my password out, and other connection information.

## What needs to change in NeoMutt?

I think this could be addressed in at least 2 ways:

1. implement a message+command console (multiline) for messages and commands to stay
2. add (customizable?) connection information to the password prompt.

## Have you tried any alternative methods?

Not really. I am new to (neo)mutt. I know there are config variables like `ssl_force_tls` or `ssl_use_sslv2`, which is good, but could be improved.

**Comment by flatcap** [comment]
That's sounds reasonable.

What info would you like to see?
Are you a crypto-wizard?  Do you know what info you want?
If not, try running neomutt with all the debugging info enabled: `neomutt -d6` then look through `~/.neomuttdebug0`

How much information are we talking about?
A line or two? -- We could display it temporarily over the status bar.
A page or two? -- We could use the pager.

**Comment by gahr** [comment]
@sfindeisen under which user case you are **not** sure of how secure your connection is?

Aren't' `imaps://`  / `smtps://` / `pops://` / `ssl_force_tls` enough?

**Comment by roccoblues** [comment]
No feedback for >4 years. Closing.
