### ISSUE TITLE
send commands to remote instance [feature request]

### ISSUE THREAD

**Issue by 257** [neomutt/neomutt#2]
i have explained it here before:
http://marc.info/?l=mutt-users&m=142428524814610&w=2

> ...the notino exist in browsers (elinks, firefox) but i was wondering if
one could send remote commands to a running instance of mutt? for example
to send mailto: uri action from a browsers.

any plans for this? if not any desire/idea for implementing it? sockets, msgpack and so on come to mind...

**Comment by flatcap** [comment]
@257 
Not only does that sound useful, it sounds like something **I'd** use.
However, I don't have time to write it myself.

At the moment, NeoMutt is a project of one person.
My first priority is to get all the existing patches and bug-fixes in an acceptable form (and there are quite a lot of them).

If anyone wants to have a go at creating this feature, I'd like to hear from you.

**Comment by flatcap** [comment]
This issue has been closed -- Sorry, but there isn't enough interest in it at the moment.

The idea's now listed on the [Blue Sky Ideas](https://github.com/neomutt/neomutt/wiki/Blue-Sky-Ideas) page.

If, in the future, someone wants to add this feature we will re-open this issue.
