### ISSUE TITLE
new-mail notifies on "save to inbox"

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#20]
I have `set record = "^^"` set to save my outgoing emails in the current mailbox.
If that mailbox is my inbox, "new-mail" notifies me.

**Comment by P-EB** [comment]
Is there a way for mutt to mark the new mail as read?

**Comment by flatcap** [comment]
The mail appears 'read', but Mutt still tells me "New mail in this mailbox."

It's not just limited to the inbox and it doesn't matter how you specify the mailbox.
If I'm in mailbox: `=neo.devel` then these show the same problem:
- `set record = "^^"`
- `set record = "=neo.devel"`

**Comment by P-EB** [comment]
Oh.

So somewhere, the new mail feature is not smart enough. That might be an interesting work case.

**Comment by SantiagoTorres** [comment]
We introduced the new-mail feature code in the same place as the "beep" feature is located. This seems to be an issue with the way mutt handles multiple mailboxes.

I believe that if we hook new-mail into `mx_check_mailbox` we could have a better behavior . We'll dig into this shortly.

**Comment by P-EB** [comment]
I personally guess that it's related to the fact that someplace in `imap/command.c` around line 285.

Count is checked against ctx->msgcount. As a new message was placed in the box (via fcc), I guess ctx->msgcount is not updated. Both counts differ, and so mutt believes that there is new messages.

**Comment by P-EB** [comment]
@SantiagoTorres do you have any news regarding this matter?

If not, I'll try to design a patch to test my theory.
