### ISSUE TITLE
quasi-delete and index behaviour

### ISSUE THREAD

**Issue by xunam** [neomutt/neomutt#200]
Hi,

It would be nice if the `quasi-delete` feature was  closer to standard deletion than it currently is. The features I am thinking of are
- allow specific coloring for quasi-deleted entries in an index, in order to provide visual feedback like for actually deleted entries,
- allow skipping over quasi-deleted entries when navigating, as for deleted ones.

This would correspond to the usage pattern in conjunction with notmuch as I understand it. Typically, when browing through the `inbox` tag, one archives messages by removing the `inbox` tag, possibly adding other tags, then quasi-deleting the message to reflect the change. This is much like saving a message to another box in the traditional workflow using concrete mailboxes.

Does that make sense to you?

By the way, the `quasi-delete` feature is mysterious since it is also quasi-undocumented: as far as I can tell, the only effect quasi-deleting a message is that this message will disappear from the index at the next mailbox synchronisation, but this is behaviour is not explicitly specified.

**Comment by toogley** [comment]
I've never used the `quasi-delete` function, but it seems to be an useful addition. :+1: 

> By the way, the quasi-delete feature is mysterious since it is also quasi-undocumented: as far as I can tell, the only effect quasi-deleting a message is that this message will disappear from the index at the next mailbox synchronisation, but this is behaviour is not explicitly specified.

Where would you like to see a better Dokumentation?

**Comment by toogley** [comment]
(The assignation to myself is btw. an mistake. Unfortunately, I can't remove this self-assignation currently on this Computer o.O)

**Comment by xunam** [comment]
Well, the only documentation is that on the [feature page](https://www.neomutt.org/feature/quasi-delete/) and it boils down to one sentence:

> The “quasi-delete” function marks an email that should be hidden from the index, but NOT deleted.

This use of “should” is unclear: is it hidden or not? When you call this function, nothing visible happens, while one would expect the message to be hidden from the index. The relationship with `sync-mailbox` is not mentioned.

**Comment by flatcap** [comment]
Hi @xunam 

> It would be nice if the quasi-delete feature was closer to standard deletion

Yes, good call.

> allow specific coloring for quasi-deleted entries in an index, 

Good.  It would have to be a separate colour name.
It would be important for the user to be able to distinguish deleted from quasi-deleted.
Additionally, we could add a flag to the index 'Q', like 'D' for deleted.

> allow skipping over quasi-deleted entries when navigating, as for deleted ones.

Good.

> This would correspond to the usage pattern ...

That's right.  It's a sort of email triage -- a quick categorisation of emails.

> .. the quasi-delete feature is mysterious since it is also quasi-undocumented: ...

Ooh, harsh!  But fair :-)

Adding a bit to the docs would be a good start, but what we really need is a HowTo.
A doc talking the user through a simple workflow, explaining why it would be useful to them.

> > The “quasi-delete” function marks an email that should be hidden from the index, but NOT deleted.

> This use of “should” is unclear: is it hidden or not?

The "should" implied a future condition, that might happen.
The email WILL be hidden when `<sync-mailbox>` is called.
The text should be updated.
