### ISSUE TITLE
Lua and Autocrypt support on Fedora COPR

### ISSUE THREAD

**Issue by darnir** [neomutt/neomutt#2006]
## What would you like to be able to do?

Please support Lua and autocrypt on the Fedora COPR builds.
Both have been around for a quite a while now (Lua especially) and are fairly stable.

## Have you tried any alternative methods?

- Macros
- Hooks
- Scripts

**Comment by flatcap** [comment]
I thought about adding Autocrypt, last night, when I was building the RPMs.
It should just be a tweak to the `.spec` file -- configure options and build dependencies.

The main reason I haven't, is time.
Maintaining the COPR takes up so much ****ing time.

I'm happy for the changes to happen, but somebody else needs to make them.
I'm currently working on some instructions for the COPR builds, but they'll take time, too.

I can point them to all the files they'll need and give them access to my two COPR repos:

- https://copr.fedorainfracloud.org/coprs/flatcap/neomutt/
- https://copr.fedorainfracloud.org/coprs/flatcap/neomutt-test/

Go to the 'Settings' tab and request permissions to join.

**Comment by darnir** [comment]
I've never done COPR builds before, but I don't mind helping out. What's needed?

**Comment by flatcap** [comment]
Done in https://github.com/neomutt/copr-neomutt/commit/e136c99446ef042eaf48c181e27e4b70d0f7ecdd
Support will appear in the next release.
