### ISSUE TITLE
Configuartion 'record' does no longer work

### ISSUE THREAD

**Issue by eku** [neomutt/neomutt#2017]
## Expected Behaviour

Any outgoing mail is recorded to the file configured by ```record```.

## Actual Behaviour

Does not record at all.

## Steps to Reproduce

Send an email. Check file specified by ```record``` for a copy.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Don't know. At least the 2018 version worked. Latest from 29.11.2019 is broken.

## NeoMutt Version

```
NeoMutt 20191129
System: Linux 5.3.12-200.fc30.x86_64 (x86_64)
ncurses: ncurses 6.1.20180923 (compiled with 6.1.20180923)
libidn: 1.35 (compiled with 1.35)
GPGme: 1.12.0
hcache backends: tokyocabinet, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC) 

Configure options: --sysconfdir=/etc SENDMAIL=/usr/sbin/sendmail ISPELL=/usr/bin/hunspell --notmuch --tokyocabinet --lmdb --gnutls --sasl --gss --gpgme

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Standard Einstellungen:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Einstellungen bei der Kompilierung:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

* .muttrc
  ```set record=+Sent ```

* Operating System and its version
 Fedora 30
* Were you using multiple copies of NeoMutt at once?
no
* Were you using 'screen' or 'tmux'?
screen
* Is your email local (maildir) or remote (IMAP)?
mbox

**Comment by flatcap** [comment]
Can you check that you also have: `set copy = yes`
Can you change folder to `+Sent` ?

**Comment by eku** [comment]
@flatcap yes and yes.

**Comment by flatcap** [comment]
Sorry, I can't repeat this.
I've started with an minimal config and performed these tests:

I created two folders `inbox` and `save`.
`set record = 'save'`
Each test is a fresh run of NeoMutt.

Test cases:

| `save` folder is | `save` folder visited | email sent from |
|------------------|-----------------------|-----------------|
| empty            | no                    | `inbox`         |
| empty            | yes                   | `inbox`         |
| not empty        | no                    | `inbox`         |
| not empty        | yes                   | `inbox`         |
| empty            | yes                   | `save`          |
| not empty        | yes                   | `save`          |

All six tests put the outgoing email in `save` and the email arrives at the destination.

Please can you test again with minimal config.

**Comment by eku** [comment]
@flatcap my configuration works with ```Mutt``` and worked with ```Neomutt``` 2018 release. I don't know where to start. Would it be enougth to enable debugging or do I have to start tests with an almost empty configuration and adding more and more options from my original configuration? Looks like a heavy time consuming approach.

**Comment by gahr** [comment]
@eku can you please provide the output of `neomutt -D -S`? Please carefully review the output and feel free to modify sensitive information such as email addresses.

**Comment by roccoblues** [comment]
No feedback for >4 years. Closing.
