### ISSUE TITLE
Alternative to sidebar-toggle-virtual

### ISSUE THREAD

**Issue by jpoimboe** [neomutt/neomutt#2023]
After updating I've noticed that `sidebar-toggle-virtual` has stopped working.  Instead the virtual mailboxes are listed after the real ones in a single sidebar.  That seems to have been intentional (commit fdee156e766d92598dd6db2e9f5ea723888c6ae1).

Is there some replacement for the old functionality?  At the very least it would be useful if they could be sorted so that the virtual mailboxes come first.  Or if the real mailboxes could even be hidden altogether somehow.

Also, I've noticed that `color sidebar_new` seems to have stopped working for virtual mailboxes.

I'm using neomutt-20191129-1.fc30.x86_64 from Fedora 30.

**Comment by flatcap** [comment]
> the virtual mailboxes are listed after the real ones in a single sidebar

Yes, a lot's changed in the 'year of development'
Notmuch was maintained as a separate patch for a long time, so it wasn't tightly integrated to Mutt.  Now, it works like other mailboxes.

The order will depend on the order of `mailboxes` commands and `$sidebar_sort_method`.

> Is there some replacement for the old functionality?

Not yet.  If you use `account-` or `folder-hooks`s with `unmailboxes *; mailboxes ...` you can achieve something similar.

> if the real mailboxes could even be hidden altogether somehow

Soon.  A few things have to be put in place first.
Most importantly, 'Named Accounts'.

My plan is to have config: `set visible_accounts = 'home,work'`
Each name would control the display of an Account (a set of Mailboxes).

> `color sidebar_new` seems to have stopped working for virtual mailboxes

OK, I'll poke @Austin-Ray to have a look.

**Comment by jpoimboe** [comment]
> > `color sidebar_new` seems to have stopped working for virtual mailboxes
> 
> OK, I'll poke @Austin-Ray to have a look.

Hm, even worse, trying to open a virtual mailbox causes a crash:
```                                            
Stack trace of thread 30235:
#0  0x00000000004ca21a email_free (neomutt)
#1  0x0000000000452f11 mx_mbox_open (neomutt)
#2  0x0000000000431152 main_change_folder (neomutt)
#3  0x00000000004323ed mutt_index_menu (neomutt)
#4  0x000000000040b2ca main (neomutt)
#5  0x00007fa21924ff43 __libc_start_main (libc.so.6)
#6  0x000000000040bfae _start (neomutt)

```

**Comment by flatcap** [comment]
Ah, sorry about that.  That's a known and already fixed problem.
I'm planning another release on Friday evening.

**Comment by jpoimboe** [comment]
> Ah, sorry about that. That's a known and already fixed problem ([e22f6a1](https://github.com/neomutt/neomutt/commit/e22f6a1ad4f83942a7ea2240337b99a2ee9a3e89)).
> I'm planning another release on Friday evening.

Good to know, thanks!

**Comment by Austin-Ray** [comment]
Hi Josh,

> Also, I've noticed that `color sidebar_new` seems to have stopped
> working for virtual mailboxes.

If it's only the unread color that's missing, try using
`sidebar_unread`. There was change in distinction between new (never
seen before) and unread.

If it's neomutt failing to notify you of new mail in a virtual mailbox,
that will take some time to debug.

**Comment by jpoimboe** [comment]
> If it's only the unread color that's missing, try using `sidebar_unread`. There was change in distinction between new (never seen before) and unread.

Yes, changing sidebar_new -> sidebar_unread in my config fixed the issue.  Thanks!

**Comment by roccoblues** [comment]
Hi, I'm trying to cleanup some older issues here. If I understand this thread correctly, a part of it was fixed and the other is more of a feature suggestion.

I'll close this issue. Please feel free to open a discussion with the feature suggestion if it's still relevant. Thanks!
