### ISSUE TITLE
Mailboxes from IMAP does not handle non-ASCII characters

### ISSUE THREAD

**Issue by ronisbr** [neomutt/neomutt#2024]
## Expected Behaviour

I am listing automatically the mailboxes from my local maildir directory. However, all mailboxes that contains non-ASCII characters must be presented correctly.

## Actual Behaviour

For example, the mailboxes "Avaliações" is shown as "Avalia&AOcA9Q-es".

## Steps to Reproduce

Add a mailbox to IMAP with non-ASCII characters and see the automatically listing.

## How often does this happen?

- Always

## When did it start to happen?

Always.

## NeoMutt Version

```
NeoMutt 20191111
Copyright (C) 1996-2016 Michael R. Elkins e outros.
NeoMutt vem ABSOLUTAMENTE SEM GARANTIAS; para mais detalhes digite 'neomutt -vv'.
NeoMutt é um programa livre, e você é encorajado a redistribuí-lo
sob certas condições; digite 'neomutt -vv' para os detalhes.

System: Darwin 19.0.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.11
libidn: 1.35 (compiled with 1.35)
GPGme: 1.13.1
hcache backends: tokyocabinet, lmdb

Compiler:
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Configure options: --prefix=/usr/local/Cellar/neomutt/20191111 --enable-gpgme --with-gpgme=/usr/local/opt/gpgme --gss --lmdb --notmuch --sasl --tokyocabinet --with-ssl=/usr/local/opt/openssl@1.1 --with-ui=ncurses

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/opt/gpgme/include -I/usr/local/opt/libassuan/include -I/usr/local/opt/libgpg-error/include -I/usr/local/Cellar/neomutt/20191111/include -DNCURSES_WIDECHAR -I/usr/local/opt/openssl@1.1/include

Opções pré-definidas:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Opções de compilação:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn -inotify
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime
  -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/Cellar/neomutt/20191111/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/Cellar/neomutt/20191111/etc"

Para saber mais sobre o NeoMutt, visite: https://neomutt.org
Se você encontrar um problema no NeoMutt, por favor crie um 'issue' em:
    https://github.com/neomutt/neomutt/issues
ou envie um email para: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version macOS Catalina
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? Local (maildir)

**Comment by gahr** [comment]
Hi @ronisbr - do I understand correctly that you're sync'ing from IMAP to a local maildir using some external software like mbsync and are using NeoMutt only to open the local maildir? If that's the case, our IMAP code is not involved, and I'd have a look at the filesystem and see how the mailbox is named there. I conjecture the external tool you're using doesn't properly unencode the mailbox name it receives from the IMAP server.

I have tested creating a mailbox named Avaliações and accessing through our IMAP code, and I see the proper decoding happening and the original name Avaliações being displayed in our UI.

**Comment by ronisbr** [comment]
Hi @gahr 

Yes, you are right. I am syncing using `mbsync` and the folder name in Maildir is not "correct". I thought this is the correct specification of Maildir folders and the mail client should be responsible to convert them. Am I wrong?

**Comment by gahr** [comment]
I don't think Maildir specifies any encoding on the folder names. The conversion from utf-7 to utf-8 should be done by mbsync.
