### ISSUE TITLE
How to map Control-F13?

### ISSUE THREAD

**Issue by nkakouros** [neomutt/neomutt#2027]
I have set up my terminal emulator to emit a `<C-F13>` (using vim notation) when I press a combination of keys. 

In vim, when I press `<C-v>` and then the combination of keys, I see `<C-F13>`.

In bash, when I press <C-v>` and then the combination of keys, I see `^[[25;5~]`.

In neomutt, I see the same as bash.

In my neomuttrc, I have tried:

```
bind index,pager \C\<F13> sidebar-prev
```

But this doesn't work, although I see that exact mapping when pressing `?` in the pager view.

I also tried:

```
bind index,pager \C<F13> sidebar-prev
```

but then I get an error:

```
Warning in /.../neomuttrc, line 29: Binding '|F13>' will alias '|'  Before, try: 'bind pager | noop'  https://neomutt.org/guide/configuration.html#bind-warnings
```

If I add `bind pager | noop` then I see the literal `|F13>` when I press `?`.

How could I add such a binding?

**Comment by zsugabubus** [comment]
Try `:exec what-key`. It will show what you press.

**Comment by nkakouros** [comment]
Thanks a lot for the tip. When I use that command and pressing `Control+Shift+P` (the "strange" shortcut I want to bind and for which I have set up my terminal to emit `Control-F13`), I get the following:

```
Char = ~, Octal = 176, Decimal = 126
```

As shown, `<C-F13>` is interpreted by neomutt as being `~`. Binding `\176` indeed binds tilde, but it does not bind `Control-Shift-P`.

**Comment by flatcap** [comment]
Hmm... mappings can be tricky.  The terminal settings can affect what you need to map.
Also, the terminal or window manager may eat some combinations, like <kbd>F11</kbd> (for full-screen).

For `gnome-terminal` (any VTE-based terminal), when I run `:exec what-key` I see:

- Normal Function keys: <kbd>F1</kbd>, <kbd>F2</kbd>, <kbd>F3</kbd> ...  <kbd>F12</kbd>
- Shift + Function keys <kbd>F13</kbd>, <kbd>F14</kbd>, <kbd>F15</kbd> ...  <kbd>F24</kbd>
- Control + Function keys: <kbd>F25</kbd>, <kbd>F26</kbd>, <kbd>F27</kbd> ...  <kbd>F36</kbd>
- Control + Shift + Function keys: <kbd>F37</kbd>, <kbd>F38</kbd>, <kbd>F39</kbd> ...  <kbd>F48</kbd>

I can map them using:

- `macro index <F1> ...`
- `macro index <F13> ...`
- `macro index <F25> ...`
- `macro index <F37> ...`

As for `Control+Shift+P` that's tricky.  Many terminals don't distinguish between: <kbd>Ctrl-P</kbd> and <kbd>Ctrl-Shift-P</kbd>.

**Comment by nkakouros** [comment]
Yes, my terminal (konsole) does not distinguish between <kbd>Ctrl-P</kbd> and <kbd>Ctrl-Shift-P</kbd>. 

So, using konsole settings, I have set up <kbd>Ctrl-Shift-P</kbd> to emit a different code instead of emitting the same one as <kbd>Ctrl-P</kbd>. The code I have set up to be emitted is the one corresponding to <kbd>Ctrl-F13</kbd>.

Most keyboards do not have an <kbd>F13</kdb> key but it is still valid.

The way I have set it up is by adding a line to the config file of console that says:

```
key P+Shift+Ctrl : "\E[25;5~" # <C-F13>
```

You can see that <kbd>Ctrl-<F13></kbd> corresponds to the ANSI escape sequence `\E[25;5`.

Testing with bash (pressing <kbd>Ctrl-V</kdb> and then <kbd>Ctrl-Shift-P</kbd>), show that Ansi escape sequence successfully.

Testing with vim/neovim (pressing in normal mode <kbd>:<\kbd><kbd>Ctrl-V</kbd><kbd>Ctrl-Shift-P</kbd>) shows <kbd>Ctrl-F13</kbd>, which is correct.

I could very likely be wrong, but due to the above, there is sth strange with the way neomutt interprets input. The way I understand neomutt's behavior is that:

1. when using `what-key`, it believes it received <kbd>~</kbd>, although my terminal emulator emitted <kbd>Ctrl-F13</kbd>
1. when trying to bind `\C<F13>` or `\C\<F13>`, neomutt either does not understand this notation (<kbd>Ctrl</kbd> together with function keys) or it does not understand <kbd>F13</kdb>.

**Comment by roccoblues** [comment]
Hi, I'm trying to cleanup some older issues here. Is this still relevant? Thanks!
