### ISSUE TITLE
Surprising preconditions for IMAP browser state flag

### ISSUE THREAD

**Issue by Bob131** [neomutt/neomutt#2029]
I was investigating a potential bug in which the IMAP browser stuff doesn't appear to get invoked when listing options for changing folders, but reading [`mutt_buffer_select_file()`](https://github.com/neomutt/neomutt/blob/c5f0d09a72138a37e0d604a1adca9e0a9da5cd99/browser.c#L1152) made me pretty confused:

 - [`mutt_index_menu()` calls `mutt_buffer_enter_fname()`](https://github.com/neomutt/neomutt/blob/c5f0d09a72138a37e0d604a1adca9e0a9da5cd99/index.c#L2433) with `mailbox = true` and no flags. Makes sense so far.
 - [`mutt_buffer_enter_frame_full()` calls `mutt_buffer_select_file()`](https://github.com/neomutt/neomutt/blob/c5f0d09a72138a37e0d604a1adca9e0a9da5cd99/curs_lib.c#L732), with `flags` defaulting to `MUTT_SEL_FOLDER` (a bit surprising, but okay) and `mailbox` translated to `flags | MUTT_SEL_MAILBOX`. I'm still following...
 - [`mutt_buffer_select_file()`](https://github.com/neomutt/neomutt/blob/c5f0d09a72138a37e0d604a1adca9e0a9da5cd99/browser.c#L1152) assigns truth to local variable `mailbox` if `MUTT_SEL_FOLDER` and `MUTT_SEL_MAILBOX` are set in `flags`. In our case this is true, but I'm not sure what the motivation is here. Later, all the IMAP-related stuff is only called if `mailbox` is _false_, which is about the opposite of what I would have expected. Digging through the commit history didn't help much, since the same logic seems to have been around since the initial commit! (although then the `mailbox` variable was, also fairly confusingly, named `buffy`)

I can't help but think there's been some terminological confusion at some point. Perhaps:
 - The browser code interprets `SEL_FOLDER` as referring to a filesystem folder whereas the curses code interprets it some other way?
 - The index code interprets `mailbox` as referring to a general mail receptacle whereas the browser code interprets `SEL_MAILBOX` as an mbox?

I'm wondering if someone could provide some guidance wrt what's happening in there. Thanks.

**Comment by roccoblues** [comment]
Hi, I'm currently cleaning up some older issues here. Is this still relevant? Thanks!

**Comment by Bob131** [comment]
I'm not sure, I haven't used neomutt for quite some time.  Sorry not to
be more helpful.
