### ISSUE TITLE
Website is misleading for new-mail docs

### ISSUE THREAD

**Issue by SevereOverfl0w** [neomutt/neomutt#203]
Alternative title: new-mail expansions are incorrectly scoped.

https://www.neomutt.org/feature/new-mail/

The suggested notify-send command here words it such that it seems that "%f" is the folder the email was received to. This is not the case, "%f" expands to the currently active folder. The same is true for the unread counts.

It would be helpful if the wording was changed to be less useful, but also promises less.

It would be better if there were some new expansions for this command as opposed to using the status_command, which only gives a window into the currently active mailbox. It would be nice, for example, to have a count of unread emails in mailboxes the sidebar knows about / are in a particular list.

**Comment by flatcap** [comment]
Hi @SevereOverfl0w, thanks for the bug report.
I've flagged this as a bug, for now.  The docs are misleading and need fixing.
When that's done, we can change this to an enhancement request -- it shouldn't be too hard to add the extra "expandos".

**Comment by toogley** [comment]
I guess this bug can't be fixed without adding an additional `status_format` variable, right? (for the folder which got new mail)

**Comment by flatcap** [comment]
Having looked through the code, I've changed my mind -- I don't think it will be easy.

When mutt checks for new mail, it does it in a completely opaque way -- extracting a list of folders that have new mail would require a **lot** of changes.

If we go in this direction, we could add some other options:
- One call (new mail somewhere)
- One call per folder
- One call per mail

Possibly, we'd a limit on the number/frequency of the notifications.

**Comment by flatcap** [comment]
I've added a note to the docs explaining that the `%f` expando isn't useful.
Any further improvements will require major changes.
