### ISSUE TITLE
No change to folder unless all messages have been marked read

### ISSUE THREAD

**Issue by patrickbenkoetter** [neomutt/neomutt#2031]
## Expected Behaviour

When I choose "c" to change to another folder with unread messages, neomutt should list the next folder with unread messages and let me choose to go there.

## Actual Behaviour

Instead neomutt will keep offering me the folder it is currently in over and over again when I choose "c" to change folders. It will remain this way until I have marked all messages as read, even the ones it should mark as "O"mitted. Once all messages have been marked as read it will offer the next folder with unread messages on the list.

## Steps to Reproduce

1. Open a Mailbox with two folders containing unread messages
2. Type "c" for a listing with folders containing unread messages
3. Find the name of the folder neomutt is currently in as first item on the list of "change to" folders

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded to NeoMutt 2019-10-25.
  Which version did you use to use?

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.2-arch1-1 (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGme: 1.13.1
libnotmuch: 5.2.0
hcache backends: kyotocabinet, gdbm, lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

* Operating System and its version
  Arch Linux, current
* Were you using multiple copies of NeoMutt at once?
  No
* Were you using 'screen' or 'tmux'?
  No
* Is your email local (maildir) or remote (IMAP)?
  My email is remote via IMAP

**Comment by gahr** [comment]
I was able to reproduce this.

**Comment by gahr** [comment]
Actually, I wasn't. What I was seeing happening is that mailboxes don't get automatically checked on startup, so it might take a while (depending on your config) to get the "New mail in ..." message. Other than that, I see <kbd>c</kbd> suggesting the next mailbox with unread messages even when there are still new messages in the current mailbox.

**Comment by patrickbenkoetter** [comment]
Unfortunately hitting c doesn't change the behaviour for me. Even if I wait a few minutes it will still suggest the mailbox I am in. Only after a second 'visit' to the same mailbox and only after all messages have been marked 'read' it will offer to change to the next mailbox with unread messages.

**Comment by gahr** [comment]
Is this still happening with a newer release?

**Comment by patrickbenkoetter** [comment]
Thank you for asking. As of NeoMutt 20200320 the problem has gone. Thank you!
