### ISSUE TITLE
Again: nntp: Too many open files (errno = 24)

### ISSUE THREAD

**Issue by hvkls** [neomutt/neomutt#204]
NeoMutt 20161014 (1.7.1).

This is a follow-up to #125 ; my configuration hasn't changed since.

Mutt starts OK. When left open over night while browsing a newsgroup, it complains about "Too many open files (errno = 24)". Feels like a leak!

**Comment by flatcap** [comment]
Thanks for the report @hvkls, sorry it's still not fixed.
Looking through the source, nntp opens/closes files in a LOT of places.
Clearly, they're not all matched.
I'll put in some logging and create a test version for you, later today.

**Comment by flatcap** [comment]
Found it.  This bug was leaking references to ~/.newsrc
Every `$nntp_poll` (60) seconds it leaked a ref (1440 per day).

**Comment by hvkls** [comment]
Thanks, I'll give it a try and report back!

**Comment by hvkls** [comment]
It works. Thank you, I hope you could use search & replace on that code!
