### ISSUE TITLE
listing mailboxes no longer works

### ISSUE THREAD

**Issue by schmeisers** [neomutt/neomutt#2042]
## Expected Behaviour

After pressing `c` to change mailbox, pressing `TAB` lists mailboxes in my "folder" variable.

## Actual Behaviour

No mailboxes are listed.

## Steps to Reproduce

Press `c` then `TAB`

## How often does this happen?

- Always

## When did it start to happen?

After upgrading to the 2019 versions.

**Comment by gahr** [comment]
Please provide a stripped down version of your config file that exhibits this behavior and list exactly the keys you press: <kbd>c</kbd> should pre-fill the prompt with the next mailbox with unread messages. If you type <kbd>Tab</kbd> next, it should just confirm the suggestion and still keep you at the prompt.

**Comment by schmeisers** [comment]
My stripped down config...

    set mbox_type = "Maildir"
    set folder = "~/.mail"
    set spoolfile = "+INBOX"

When I press `c` I am prompted for a mailbox:

    Open mailbox ('?' for list):

Then if I press `tab` I am presented with the directory browser for my mail directory:

    -- NeoMutt: Directory [~/.mail], File mask: !^\.[^.]

however the listing is empty.  In the 2018 versions, it lists my mailboxes in ~.mail.

**Comment by gahr** [comment]
I think this might be related to a change in how we handle mailboxes. Please read flatcap's comment here: https://github.com/neomutt/neomutt/issues/1958#issuecomment-554318391

**Comment by gahr** [comment]
Fixed in master. Thanks!
