### ISSUE TITLE
unstable alphabetic sorting

### ISSUE THREAD

**Issue by phmarek** [neomutt/neomutt#205]
When there are mailbox names like `shared-Inbox` in use,  512a6d428 causes unstable sort results. Just switching `toggle-mailboxes` makes a subset of the sidebar (3 mailboxes) rotate around each other.

Another question about sorting: Previously I had marked several IMAP folders with a "_" prefix, to have them first within their subfolders. With 5e146b1d9 that got broken; how can I get the old behaviour back?

**Comment by gahr** [comment]
@phmarek Can you please check if the commit mentioned above solves the issue for you? I tested with a folder named "Shared-Inbox" and it works fine for me.

**Comment by gahr** [comment]
@phmarek you can also check the [devel/inbox-first](/neomutt/neomutt/tree/devel/inbox-first) branch.

**Comment by phmarek** [comment]
The "/inbox" patch works for me.

**Comment by gahr** [comment]
Let's keep this open until it's merged, thanks for testing!
