### ISSUE TITLE
Limit mails to those with more than one recipients (in To: header)

### ISSUE THREAD

**Issue by sweenu** [neomutt/neomutt#2051]
I tried several regex patterns but couldn't find a way to limit mails to those with at least 2 different recipients in their `To:` header.

Is there a way to do such a thing?

**Comment by jindraj** [comment]
This should do the thing:
hit `l` to run _\<limit\> function_ and enter filter similar to following:
```~C first@example.com | ~C second@example.com```
or
```~C "first@example.com|second@example.com"```

`~C` matches **To:** and **Cc:** headers
First example translated to english: match To/CC with value first@example.com OR match To/CC with value second@example.com
Second example translated to english: match To/CC with regular expression matching pattern
>Note : If a regular expression contains parenthesis, or a vertical bar (“ | ”), you must enclose the expression in double or single quotes since those characters are also used to separate different parts of NeoMutt's pattern language. [1]


See neomuttrc(5) **PATTERNS** section more specifically:

- [Pattern Modifier](https://neomutt.org/man/neomuttrc#pattern-modifier)

- [Nesting and Boolean Operators](https://neomutt.org/man/neomuttrc#nesting-and-boolean-operators)

[1] citation from neomuttrc(5) **Nesting and Boolean Operators**

**Comment by Sweenu** [comment]
Thank you for your answer. I wasn't clear enough in my question I think.
My goal is to get any mail that I received, that were also sent to other people.
So I'm looking for a pattern that matches mails where the `To:` header looks something like:
```
To: Me <my@address.com>, someone else <their@address.com>, ...
```
and do not match mails with a `To` header like this:
```
To: me <my@address.com>
```

In your example, I need to put in a second specific address, but in my case, I want to match with any other address besides mine.

**Comment by jindraj** [comment]
I tried to create a limit witch would match messages to you and messages to any other address different than yours.
```~C my@example.com ~C "((?!my@example.com).)+"```
But neomutt regular expressions either doesn't know lookarounds or I'm doing something wrong. either way the `?` in the regex is considered as a repetition operator which is not correct.

**Comment by chrisbra** [comment]
that's because mutt and neomutt use [POSIX extended regular expressions](https://www.regular-expressions.info/posix.html), which do not support sophisticated features like look-around assertions.

**Comment by gahr** [comment]
It's not much about lookarounds; it's about the `~C` pattern modifier looking at each address in the `To` and `Cc` headers independently. I don't see a way to achieve what you want.
