### ISSUE TITLE
how to request return receipt or delivery status notification when sending mail?

### ISSUE THREAD

**Issue by sfindeisen** [neomutt/neomutt#2052]
When sending a message, how do I request return receipt or delivery status notification? Is there a way to set the corresponding headers?

Thanks

**Comment by jindraj** [comment]
See man pages neomuttrc(5) and look for configuration options: **dsn_notify** and **dsn_return**

**Comment by gahr** [comment]
You can ask for MDN by adding the `Disposition-Notification-To: <your email address here>` header to outgoing messages. You can do so by using [`my_hdr`](https://neomutt.org/guide/configuration.html#my-hdr).
