### ISSUE TITLE
Status bar on bottom in AUR git version 

### ISSUE THREAD

**Issue by kflak** [neomutt/neomutt#2060]
## Expected Behaviour

Status bar on top of the index

## Actual Behaviour

Status bar is on the bottom of the page (!) when using the neomutt-git package from AUR

## Steps to Reproduce

Install neomutt from Arch User Repository with the neomutt-git package instead of neomutt from the community repo.

## How often does this happen?

- Always

## When did it start to happen?

After I tried installing the git version.

## NeoMutt Version

```
PUT YOUR "neomutt -v" OUTPUT HERE
```
Community package:
```
System: Linux 5.4.5-rt3-1-rt (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGme: 1.13.1
libnotmuch: 5.2.0
hcache backends: kyotocabinet, gdbm, lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```
AUR package:
```
System: Linux 5.4.5-rt3-1-rt (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGme: 1.13.1
libnotmuch: 5.2.0
hcache backends: kyotocabinet, gdbm, lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/bin/sendmail"
SYSCONFDIR="/etc"
```
## Extra Info

* Operating System and its version: Arch Linux 5.4.5-rt3-1-rt
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? IMAP

**Comment by flatcap** [comment]
Er, that's the default position for the status bar ([diagram of layouts](https://github.com/neomutt/gfx/tree/master/layout#plain-index-view)).

There's a config variable `status_on_top` that swaps the positions of the status bar, pager bar and help line.

Have a look at: `neomutt -Q status_on_top`

**Comment by kflak** [comment]
Ah, that's a bit embarrasing... I guess I should add a bit of information, then: the AUR package seems not to respect the `status_on_top` variable, which I have sett in `muttrc`. Output from `neomutt -Q status_on_top` is `set status_on_top = yes', but the status bar is still on the bottom of the page, stacked on top of the help bar, which is not exactly what I would expect. Unsetting status_on_top delivers the default view, with the help bar on top and status bar below.

**Comment by flatcap** [comment]
OK, that means the new window code is broken somewhere.
Which **exact** version of neomutt have you built?  (first line of neomutt -v)
(you've edited that out of the version info, above)

Please can you try a minimal config, `test.rc`
```
set status_on_top = yes
```

then run, `neomutt -n -F test.rc`
Does _that_ look correct?
If so, please can you try to work out which of your other config lines is causing the interference.

Also, does neomutt work correctly when toggling the value:
```sh
# No config
neomutt -n -F /dev/null
```
then several:
```
:toggle status_on_top
```

**Comment by kflak** [comment]
OK, getting a bit further:

The minimal config file has the same issue: status line stacked on top of help when `status_on_top = yes`. However, running `toggle status_on_top` seems to shake things loose, and the placement works as advertised from there on. This also applies to my regular setup.

**Comment by flatcap** [comment]
It's ok.  I can see the problem now.

**Comment by flatcap** [comment]
Please can you give branch [[devel/status](https://github.com/neomutt/neomutt/tree/devel/status)] a try.
(The base windows were being created **before** the config was read)

**Comment by kflak** [comment]
Works! However, color scheme and options seem to be reset to the default state. Is that intentional?

**Comment by flatcap** [comment]
> Is that intentional?

No.  Sorry, the fix needs a little more thought.

**Comment by flatcap** [comment]
Happier now.
Oh and the colours/options have their default values because of the `-n` (don't read `/etc/neomuttrc`)

**Comment by kflak** [comment]
Cool, thanks for the quick fix!
