### ISSUE TITLE
display both renamed and original file path in attachement

### ISSUE THREAD

**Issue by charlie45000** [neomutt/neomutt#2067]
Hi,

I'm currently trying to configure neomutt on my computer and I am currently trying to get both the renamed attachment name (the one that will be sent) and the real path in the file system.

I tried to seek for that on the internet, but only found a mail in the mutt mail archive server (with no responses). I also tried to get into the source code, but I can't find how this name is displayed on the screen.

Do you know if it could be possible (and if yes, how exactly?)
Thank your for your help!

**Comment by Austin-Ray** [comment]
Attach format specification is available here: https://neomutt.org/guide/reference.html#3-17-%C2%A0attach_format

For full system path, you probably want `%f`

**Comment by charlie45000** [comment]
Thank you very much! I searched in the wiki but didn't find this...
