### ISSUE TITLE
Display mailbox name in the sidebar

### ISSUE THREAD

**Issue by charlie45000** [neomutt/neomutt#2068]
Hi,
I recently started to use neomutt after watching a video of luke smith and saw somthing in his configuration that I couldn't reproduce the email account name in the sidebar:
[luke's sidebar in mutt](https://i.ibb.co/yXV6Nzd/mutt.png)

I looked everywhere to find that functionality, but I couldn't find it (I may not fully understand what this is and I didn't use the good keywords.)

Do you know how to have that displayed?
Thank you for your help

**Comment by Austin-Ray** [comment]
> I couldn't reproduce the email account name in the sidebar

Do you consider "mutt" to be the account name? If so, there's instructions available here: https://github.com/neomutt/neomutt/issues/1901#issuecomment-547676531

**Comment by charlie45000** [comment]
so if if want both the account name and the == line, I have no other choices than creating two files?

**Comment by Austin-Ray** [comment]
Yes, Neomutt uses the mailbox path to distinguish distinct mailboxes so there's no duplicates.

**Comment by charlie45000** [comment]
Ok, thank you for your help (it would be great to be able to add information in the sidebar.
