### ISSUE TITLE
How to use ueberzug instead of w3m for image previews?

### ISSUE THREAD

**Issue by Kabouik** [neomutt/neomutt#2071]
I am new to Neomutt and was wondering if one can we use [Ueberzug](https://github.com/seebye/ueberzug) instead of w3m to view image attachments. It seems to be more robust and to be compatible with more terminal emulators, yet I failed to find information on how to combine it with Neomutt or Mutt.

**Comment by Galicarnax** [comment]
Not directly an answer to your question... but if you don't mind using [kitty](https://github.com/kovidgoyal/kitty), then not only you'll have robust [image previews](https://sw.kovidgoyal.net/kitty/kittens/icat.html), you'll also have very nice and honest previews of PDF-attachments [inside the terminal](https://github.com/dsanson/termpdf).

**Comment by Kabouik** [comment]
Interesting, it looks very good. I didn't know about a kitty terminal emulator. The only KiTTY application I knew about was a fork of PuTTY for ssh and telnet. Maybe it's both are related.

I have moved to [nmail](https://github.com/d99kris/nmail) because I was kind of overwhelmed by the Neomutt/Mutter workflow and keybindings (which does not mean those are unnecessarily complicated, just that for a beginner, nmail is a very good entry to console e-mail clients). I also like how it handles attached files as temporary files instead of saving them for good, and allows to display html messages in Lynx or in the browser. I still keep an eye on Neomutt of course, I am still very interested in it and want to follow its development, plus I believe Ueberzug support would still be a nice addition.

**Comment by nabaco** [comment]
@Galicarnax could you please elaborate on how to configure such a setup?

**Comment by Galicarnax** [comment]
Create the script (e.g., called `icat.sh`):
```bash
#!/usr/bin/bash

kitty +kitten icat "$1"
read -n 1 -s -r -p "Press any key to continue"
```
Then in neomutt's mailcap put this line:
```
image/jpeg; /path/to/icat.sh %s
```
Then running `neomutt` in `kitty`, you should be able to view attached images directly in terminal.

Similarly for PDF. Install `termpdf`, and put this into maillcap:
```
application/pdf; termpdf %s
```
The path to mailcap file should be indicated in neomutt's config like so:
```
set mailcap_path = "/path/to/mailcap"
```
