### ISSUE TITLE
$move is broken on IMAP

### ISSUE THREAD

**Issue by freshprince** [neomutt/neomutt#2081]
## Expected Behaviour

With `$move=yes` read mail in my `$spoolfile=+INBOX` should be moved to `$mbox=+Mails`.

## Actual Behaviour

Since neomutt-20191025 this doesn't work anymore. There's a message about moving a mail but the  mail is still there flagged and the Mailbox is in a weird state. I usually need to set `%` and switch mailbox to fix it.

## Steps to Reproduce

My minimal config:

```
./neomutt -F /dev/null -f imaps://...@imap-mail.outlook.com -e 'set imap_pass="..."' -e 'set imap_check_subscribed' -e 'set folder="imaps://...@imap-mail.outlook.com/"' -e 'set spoolfile=+INBOX' -e 'set mbox=+Mails' -e 'set move=yes'
```
Have a read mail in `+INBOX` and try to switch the mailbox or quit.

## How often does this happen?

Always. I could reproduce this one on all IMAP accounts I have.

## When did it start to happen?

5634417a3163bd0ab1d4cf354bf76a713dafe96a is the commit that introduced this bug.

## NeoMutt Version

```
NeoMutt 20180716-1121-563441
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.10_1 (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.35 (compiled with 1.35)
GPGme: 1.13.1
hcache backends: gdbm

Compiler:
cc (GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --ssl --gpgme --notmuch --gdbm --lua --sasl

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3  -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls +gpgme -gss +hcache -homespool +idn +inotify -locales_hack +lua +meta 
  -mixmaster +nls +notmuch +openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by liskin** [comment]
It seems in 20200619 the `move` setting is ignored entirely. :-(

**Comment by freshprince** [comment]
> It seems in 20200619 the `move` setting is ignored entirely. :-(

I cannot confirm this. $move works fine for me.

**Comment by liskin** [comment]
> I cannot confirm this. $move works fine for me.

It must be something in my muttrc then. Your minimal example works fine, but my old muttrc doesn't. :-(

**Comment by liskin** [comment]
Okay, so it only works with `set folder=imaps://username@server`, but doesn't with `set folder=imaps://server` and `set imap_user=username`.

**Comment by liskin** [comment]
Opened https://github.com/neomutt/neomutt/issues/2379 for this.
Thanks for letting me know that there exists a configuration where `move` works.
