### ISSUE TITLE
update_index() never gets called in index.c

### ISSUE THREAD

**Issue by sassmann** [neomutt/neomutt#2083]
Found a condition that can never be true.

https://github.com/neomutt/neomutt/blob/12d1180dc98019c5a4e040e3f53071b86e5af7ab/index.c#L741-L749

`mx_mbox_close()` only returns -1 or 0, so `check` gets assigned -1 or 0.

This condition can never be met as `MUTT_NEW_MAIL` has a value of 1 and `MUTT_REOPENED` has a value of 3.
Are we missing a `check = mx_mbox_check()` perhaps?

Similar situations here:

https://github.com/neomutt/neomutt/blob/12d1180dc98019c5a4e040e3f53071b86e5af7ab/index.c#L1836-L1841

https://github.com/neomutt/neomutt/blob/12d1180dc98019c5a4e040e3f53071b86e5af7ab/index.c#L1985-L1989

https://github.com/neomutt/neomutt/blob/12d1180dc98019c5a4e040e3f53071b86e5af7ab/index.c#L2030-L2048

**Comment by flatcap** [comment]
Good catch!  Thanks, @sassmann 

---

P.S.  I've edited your post a little to show the source directly.

- '**Shift-Click**' to highlight a range of lines
- Click on the **`...`** in the margin
- Select '**Copy Permalink**'
- **Paste** link into a comment

**Comment by sassmann** [comment]
Thanks Rich, I wasn't aware of that.
