### ISSUE TITLE
How does index_tag work?

### ISSUE THREAD

**Issue by arponero** [neomutt/neomutt#2087]
Hi all,

I would like to have different colors for different notmuch tags, so I guess index_tag might does this work, but I don't get the results I was expecting.

In my workflow, I mark all new messages with the **inbox** tag using notmuch. To process my emails, I have a macro to remove the inbox tag, adding the **archive** tag to the email at the same time.

I would like to highlight those emails with the **archive** tag just after the previous change, so I guess the following configuration would do the work:

`color index_tag red default "archive"`

But it doesn't work. Do you know why?

Furthermore, it would be great to show all notmuch tags per message. Is this possible? How?

Thanks and best regards,
Jaime

**Comment by arponero** [comment]
I finally understand the documentation here:
https://neomutt.org/feature/custom-tags
so I will close this issue.

**Comment by noahrama** [comment]
this is confusing. Is the idea that we hide the tags we want to custom color, and then add them with %G in the index_format if they exist? 

could regex even handle this?
