### ISSUE TITLE
Get unread count outside of neomutt

### ISSUE THREAD

**Issue by AdrienLemaire** [neomutt/neomutt#2089]
I would like to show the unread emails count on my waybar only when I get a certain number of unread emails (eg 50).

I couldn't find any good parameter for such a query with `neomutt --help`.

* `neomutt -D` doesn't return a unread count variable to display with `neomutt -Q`
* only `neomutt -B` seems to return to stdout otherwise, and I couldn't find a [function](https://neomutt.org/guide/reference.html) to use with `neomutt -e`  (tried things like `neomutt -B -e "printf('%u')"`)

I found the [new-mail](https://neomutt.org/feature/new-mail) feature, which can do the trick (update a file with the unread count, and have my bar listen to that file then only display the count if > 50), but this sounds suboptimal.
Isn't there a better way to do it?

**Comment by flatcap** [comment]
Unfortunately, not yet.

We're trying to sort out the code, which is still pretty tangled.
We're hoping to create tidy, self-contained libraries for each mailbox type.
When they're done, it'll be easy to write useful helper programs to extract that sort of data.

**Comment by plokid** [comment]
Is this question working on?

**Comment by flatcap** [comment]
No, not directly.

NeoMutt is a **LOT** of code; there's a lot to fix.
I don't have a team of developers, I'm just one man working in my free time.
There are a couple of other developers who help me, who also have little free time.

Fixing the architectural problems in NeoMutt is my highest priority.
But this is hard work and I'm not getting much help.

When completed, _that_ would make this issue easy to solve.
But until then, this issue is very low priority.

**Comment by roccoblues** [comment]
Hi, I'm currently cleaning up some older issues here. Is this question still relevant? Thanks!

**Comment by plokid** [comment]
@roccoblues I write a script to do that, and it works really well. So I believe this question could be close.

**Comment by Ahwxorg** [comment]
> [@roccoblues](https://github.com/roccoblues) I write a script to do that, and it works really well. So I believe this question could be close.

Could you share that script perhaps?

**Comment by alexindigo** [comment]
> Hi, I'm currently cleaning up some older issues here. Is this question still relevant? Thanks!

@roccoblues would be a useful thing to have for others, who didn't write a whole script, just to check how many new emails available. And even not clear what that script is.

**Comment by Ahwxorg** [comment]
> > Hi, I'm currently cleaning up some older issues here. Is this question still relevant? Thanks!
> 
> [@roccoblues](https://github.com/roccoblues) would be a useful thing to have for others, who didn't write a whole script, just to check how many new emails available. And even not clear what that script is.

+1!
