### ISSUE TITLE
Rewrite Script for generating Documentation -> Python?

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#209]
Hey.

the ideal solution for generating our documentation (which i use in a very stretched sense here) would be one script which generates everything from one source. That means, this script would **in the final version** generate from `manual.xml.head` :
- the List of Features in our README.md on our Github Repo
- the List of Features on our Website (neomutt.org/features)
- the manpage of neomutt
- the Manual on our Website
- the sphinx source Code documentation on our website
- the List of names related to Neomutt/mutt

The idea is of course to build a very readable/maintainable script, so that it can easily extended to further needs. That's also the reason why i think about using Python instead of e.g. a Makefile or bash. It's just my own feeling, but i think using sth similar to python would increase the readability, as it has a better, stricter type system (which results in more expressive error messages) better support external libraries and in general is more powerful.

**However, i'm very unsure if I'm correct with my feeling in that regard.**

What are your opinions on this idea? Does it make even sense?

**Comment by pickfire** [comment]
@toogley, I suggest using Makefile whether we use shell script or python. It's for reducing the load for rebuilding purposes.
