### ISSUE TITLE
Browse into mailbox subdirectory

### ISSUE THREAD

**Issue by sekoenig-de** [neomutt/neomutt#2094]
Hi,

I am using a Maildir structure with multiple nested folders (synced via mbsync).  For example, let's assume I have a hiearchy like this

+ INBOX
+ Conferences
+ - - TEST-2020
+ ...

Now, from the index in INBOX I want to save a message to Conferences/TEST-2020.  From the browser, I can select Conferences, but I am unable to go inside (Enter selects Conferences and = doesn't work) to select TEST-2020.  I am not sure if this is a bug or if I am doing something wrong.

As a workaround I find I can use <Tab> to get a list of all my mailboxes and then select Conferences/TEST-2020.  However, this is tedious because browsing always starts at the beginning of the list, which is quite long.  Is there a way to set the initial focus to the last selected folder?

I am using Neomutt on Debian bullseye (testing), i.e., version 20191111 with ncurses 6.1.20191019 at the moment.

Any help would be greatly appreciated!

Thanks,

Sebastian

**Comment by flatcap** [comment]
Hi @sekoenig-de 
You're looking for the `<descend-directory>` directory function.

When you hit <kbd>\<Enter\></kbd> the browser does `<select-entry>`
If you have nested folders, then you will need `<descend-directory>` to **go into** the directory.

By default, this function isn't bound to a key, so add this to your config:
(I've picked <kbd>g</kbd> for 'goto', but any unused key will do)
```
bind browser g descend-directory
```

**Comment by sekoenig-de** [comment]
Thanks @flatcap, that is exactly what I was looking for!  Together with `<goto-parent>` navigation works nicely now.  While now I am trying to find a way to hide the internal parts of the Maildir structure (cur, new, tmp) and the dotfiles from mbsync, my immediate issue is resolved and I think this can be closed here.
