### ISSUE TITLE
order mailboxes by modification time

### ISSUE THREAD

**Issue by mhinsch** [neomutt/neomutt#2096]
## What would you like to be able to do?

I would like to be able to configure the sidebar to show mailboxes in order of modification time, so that most recently used ones show up at the top. Alternatively/in addition it would be great to have a cut-off as well, i.e. mailboxes unmodified for more than x days will not be shown.

## What needs to change in NeoMutt?

An additional option for sidebar_sort_method would be needed. The code looks pretty clean, so *if* there is a straightforward way to get a mailboxes mtime this shouldn't be too difficult. If someone points me to the right place(s) I'll be happy to give it a go myself.

## Have you tried any alternative methods?

For now I am using *sort_method=new (Incidentally new and unread seem to be identical in this context. Is that on purpose?), but that's rather unsatisfactory as I have plenty of mailboxes that contain huge numbers of unread mails but that I haven't touched in ages (yes, I am not terribly well organised).

**Comment by flatcap** [comment]
Hi @mhinsch 

>  I have plenty of mailboxes that contain huge numbers of unread mails
> I am not terribly well (organised)

Sounds like you should investigate [Notmuch](https://neomutt.org/feature/notmuch) :-)

> configure the sidebar to show mailboxes in order of modification time

OK, that sounds reasonable.
Maildir and Mbox store the modification time in [`struct Mailbox`](https://github.com/neomutt/neomutt/blob/9e4a65ab2a08ada347e95f5f71c420325409a118/core/mailbox.h#L106), so sorting them should be pretty simple. 

But... it won't work for other mailbox types: IMAP, NNTP, Notmuch.
Perhaps that doesn't matter.

> If someone points me to the right place(s) I'll be happy to give it a go myself.

Certainly.

First you'll need to Fork the [neomutt repo](https://github.com/neomutt/neomutt), create a branch and build NeoMutt.
See:
- [Build guide](https://neomutt.org/dev/build/build)
- [Distro Specific build dependencies](https://neomutt.org/distro) -- some pages are more helpful than others
- [Debugging NeoMutt](https://neomutt.org/dev/build/debug)

You'll need to add a new sort method:
- https://github.com/neomutt/neomutt/blob/master/config/sort2.h#L48
- https://github.com/neomutt/neomutt/blob/master/config/sort.c#L116

Sidebar:
- Update [cb_qsort_sbe](https://github.com/neomutt/neomutt/blob/master/sidebar.c#L297)

Update the docs:
- Section: [intro-sidebar-features](https://github.com/neomutt/neomutt/blob/master/doc/manual.xml.head#L497)
- Table: `table-sidebar-sort` L16302
- Config: `sidebar-neomuttrc` L16394

There's a lot to take in when getting started with NeoMutt, so: **Ask lots of questions**
(here, or on irc: **#neomutt** on **`irc.freenode.net`**)

When you've made your first commit, you can create a [Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request).
That'll allow us to help you and encourage others to contribute :-)

**Comment by mhinsch** [comment]
Hi @flatcap,

Thanks for the comprehensive introduction. I've started the implementation [here](https://github.com/mhinsch/neomutt/tree/sidebar_sort_mdate). I've reused the `date` sort flag as it's used pretty much equivalently in the browser, so the changes are quite minimal. 

Unfortunately, however, it doesn't appear to be working ATM. The log confirms that `cb_qsort_sbe` is called with the right settings (`ssm == 1` in `sidebar.c:453`), but my sidebar still shows up in what appears to be essentially random order.

I can dig deeper and check which mtime values the sort function sees, but maybe someone with more experience with the code base immediately sees the issue.

**Comment by mschilli87** [comment]
@mhinsch: I think it would be easier to review/discuss any details if you [opened a pull request](https://github.com/mhinsch/neomutt/pull/new/sidebar_sort_mdate).
You could make it a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to stop it from being merged prematurely.

Oh, and first of all thank you for your contribution to NeoMutt. :heart:

**Comment by mhinsch** [comment]
Just a quick update on that:

Adding some debugging messages shows that the sort function sees `mtime==0` for all maildirs on startup. Switching between maildirs appears to change that particular maildir's mtime and accordingly leads to a different order in the sidebar. All other maildirs still show `mtime==0`, however.

**Comment by flatcap** [comment]
Hmm...
In maildir, `Mailbox.mtime` is updated in [`maildir_update_mtime()`](https://github.com/neomutt/neomutt/blob/master/maildir/shared.c#L302), which is only called by [`mh_read_dir()`](https://github.com/neomutt/neomutt/blob/master/maildir/shared.c#L795) (reading the directory) and [`mh_mbox_sync()`](https://github.com/neomutt/neomutt/blob/master/maildir/shared.c#L1704) (syncing the directory).

If you've got `set mail_check_stats = yes`, then that'll happen quite soon after starting, but not immediately.

Perhaps adding `maildir_update_mtime(m);` to [`maildir_ac_add()`](https://github.com/neomutt/neomutt/blob/master/maildir/shared.c#L1639) will help.

That's called when the Mailbox is added to the Account, before anything's displayed on screen.

**Comment by roccoblues** [comment]
Hi, I'm currently cleaning up some older issues here. Is this still relevant? Thanks!
