### ISSUE TITLE
Open virtual mailbox on mutt startup with -f "mailbox" does nothing (exit code 0 without any additional logs)

### ISSUE THREAD

**Issue by edi9999** [neomutt/neomutt#2101]
#  Expected Behaviour

I have the following in my .muttrc : 

```
virtual-mailboxes "personal" 'notmuch://?query=path:personal/**'
virtual-mailboxes "ninja-sent" 'notmuch://?query=path:jsninja/** and from:HIDDEN'
```

By default, when I open mutt, the opened virtual mailbox is "personal".

I would like to open the mailbox "ninja-sent" from my terminal, without having to do keystrokes within mutt.

I'm running : 

```
neomutt -f "ninja-sent"
```

I would expect that neomutt opens the mailbox (virtual-mailbox) "ninja-sent"

## Actual Behaviour

However, the command exits with status code 0 without any additional information.

## Steps to Reproduce

See above with the .muttrc

## How often does this happen?

- Always

## When did it start to happen?

- I think it always did, I never managed to configure it.

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.15.0-74-generic (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.33 (compiled with 1.33)
libnotmuch: 5.0.0

Configure options: --enable-notmuch --enable-debug

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss -hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch -openssl +pgp -sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version :Ubuntu 18.04.2 LTS
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? Yes
* Is your email local (maildir) or remote (IMAP)? local with notmuch

**Comment by Austin-Ray** [comment]
At this time, the `-f` is limited to `mailboxes`, and doesn't not work for the names of `named-mailboxes` or `virtual-mailboxes` declarations. 

You could use the full notmuch query, but that's a bit cumbersome outside of scripts/aliases.
