### ISSUE TITLE
Neomutt unable to open IMAP folders other than +INBOX

### ISSUE THREAD

**Issue by steevmi1** [neomutt/neomutt#2110]
## Expected Behaviour

Able to change from the +INBOX folder to any other folder while connected to an IMAP server.

## Actual Behaviour

The folder does "open", but shows no messages. Either one or more single-digit numbers or non-ASCII characters print (the same number, on one or more lines). After this, the +INBOX is also similarly unaccessible.

Neomutt doesn't crash consistently due to this, but seems to crash more frequently. Core file is dropped on OpenBSD, not on OS X. 

## Steps to Reproduce

Connect to IMAP server
Switch to any folder

## How often does this happen?

- Always

When connecting to IMAP hosted at the ISP pair.com, using IMAP from google.com is so far unaffected.

## When did it start to happen?

- When I upgraded

With the 2019-11-29 release.

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: OpenBSD 6.6 (amd64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.16
libidn2: 2.3.0 (compiled with 2.3.0)
GPGme: 1.13.1
hcache backends: kyotocabinet

Configure options: --mandir=/usr/local/man --with-ui=ncurses --docdir=/usr/local/share/doc/neomutt --with-lock=flock --idn=0 --idn2 --fmemopen --ssl --autocrypt --gpgme --sqlite --sasl --kyotocabinet

Compilation CFLAGS: -O2 -pipe -g  -I/usr/local/include -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set -fcntl +flock +fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss +hcache -homespool +idn -inotify 
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +sasl +smime 
  +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
OpenBSD -current, have upgraded since the issue started.
OS X Mojave
* Were you using multiple copies of NeoMutt at once?
No
* Were you using 'screen' or 'tmux'?
With and without tmux
* Is your email local (maildir) or remote (IMAP)?
IMAP

**Comment by steevmi1** [comment]
For the record, I also can reproduce this when using straight mutt as well.

**Comment by mschilli87** [comment]
@steevmi1: In this case you might want to report the issue upstream (cross-linking the cross-post, of course) to get it fixed for everybody: NeoMutt merges mutt's bugfixes, so it would benefit more people.

**Comment by gahr** [comment]
I have seen this a couple of times when attaching to my tmux session in the morning. I guess it's due to some message from the IMAP server we don't handle as well as we should. So far I was unable to find a pattern or to replicate it. Is it consistently reproducible with pair.com ? Can you create an IMAP account for me to test?

**Comment by gahr** [comment]
@steevmi1 ping - can you create an account for me on pair.com?

**Comment by sappel34** [comment]
This seems not be specific to pair.com I have exactly the same behaviour when connecting to our business office365 IMAP account.

**Comment by sappel34** [comment]
Hint: This bug occurs ONLY with the following config:

`set imap_check_subscribed="yes"`

As soon as I set it to "no" and add mailboxes manually to sidebar everything works as expected.

**Comment by steevmi1** [comment]
@sappel34 that looks to have helped -- turning that off I can switch back and forth between folders. Thanks!

@gahr Apologies for not replying sooner -- been a bit busy and haven't had time to look at this until now. Do you want to leave this open to keep looking at this issue?

**Comment by gahr** [comment]
I cannot reproduce with my hotmail account: here's my config:

```
set folder    = imaps://$my_hotmail_user@outlook.office365.com
set spoolfile = +INBOX
set postponed = +Drafts
set record    = +Sent
set trash     = +Trash

set imap_check_subscribed = yes
set imap_authenticators = plain
```

**Comment by steevmi1** [comment]
@gahr Apologies for the delay.

I'm wondering if either neomutt or the remote server may be getting confused -- I now have three different configuration files for logging into that server -- one for my "master" account at PAIR, one for my main hosted account, and one for a new mailbox I created for testing this. Which ever one I set as the primary login works, but I'm no longer able to log into the other two. For the virtual mailboxes, whichever one I log into first is the one that "works", even if I log into one of the other accounts.

**Comment by scottkosty** [comment]
I'm guessing not, but just in case: could this issue be related to #2225? The only reason I ask is because I see `imap_check_subscribed` playing a role over there also. Taking another wild stab, is it possible that the reason gahr can't reproduce is because of no folder with a space in it?

**Comment by GideonWolfe** [comment]
> The folder does "open", but shows no messages. Either one or more single-digit numbers or non-ASCII characters print (the same number, on one or more lines). After this, the +INBOX is also similarly unaccessible.

Author of #2225 here, am experiencing all of this, could this be linked to #2145 ? So many things go wrong when I change an IMAP folder it seems.

**Comment by gahr** [comment]
@steevmi1 Thansk for the test account you provided off-line. I was able to reproduce. Inbox opens fine and it contains a single message. Trying to change into any of the subscribed folders fails.

I see a couple of things.
1. the IMAP server uses a forward-slash `/` as a path separator
2. the IMAP server sends this list of subscribed folders: INBOX.Drafts, INBOX.Sent, INBOX.Junk, INBOX.Trash
3. we fail to understand that dot `.` is not a path separator, so when we try to open the `INBOX.Sent` mailbox, we actually issue `a0014 SELECT "INBOX/Sent"`, which fails.

**Comment by gahr** [comment]
As a workaround, you can fix this by setting `set imap_delim_chars = "/"`.

I think we should fix `imap_fix_path` to only use the delimiter provided by the server. I'll have to ponder this a bit more.

**Comment by gahr** [comment]
Up. So I don’t forget about this (again).

**Comment by ryanakca** [comment]
I too am experiencing this bug with my own IMAP server. I tried applying the patch from #2298 , but still experience the issue with it. Here is a minimal config file that I can use to reproduce the issue. My mail server uses "." as its hierarchical delimiter.

```
set imap_user = 'rak';
set folder = 'imaps://imap.rak.ac/';
set spoolfile = '+Virtual.INBOX';
set imap_check_subscribed = yes;
```

**Comment by gahr** [comment]
So, `folder` is parsed before a connection to the IMAP server is attempted. At that point, we don't have the server's delim, so all we can do is trying using `imap_delim_chars`.

Because it is `/.` (unless you changed it), we end up recognizing the first dot in `Virtual.INBOX` as a delimiter, which we keep. You don't seem to mention other delimiters anywhere.

I don't see where's the problem in this case. What are the symptoms? Any logging / error messages?

**Comment by ryanakca** [comment]
The symptoms are that neomutt displays garbage on the screen and does not actually open the mailbox.

neomutt prompts me for my password, connects, closes the mailbox, reconnects, and then shows the following:

![2020-04-28-072618_837x376_scrot](https://user-images.githubusercontent.com/99287/80482105-a0a02f80-8921-11ea-838f-b09c10965e57.png)

Here are the log messages:

![2020-04-28-072624_837x376_scrot](https://user-images.githubusercontent.com/99287/80482107-a138c600-8921-11ea-86e4-21fb2dfdaa75.png)

Attached is an appropriately sanitized copy of a debug file created by passing neomutt the `-d 5` option.
[neomuttdebug0.txt](https://github.com/neomutt/neomutt/files/4545487/neomuttdebug0.txt)

**Comment by gahr** [comment]
Thanks - I realize I created some confusion here. We have two issues:

1. messy index lines on startup, which is being mostly tracked at #2145 
2. unable to change folders because of a separator issue, which I'm fixing here

Do you also experience 2.?

**Comment by gahr** [comment]
I think in this case the problem is that you're subscribed to a mailbox `Lists.ABC` that doesn't exist anymore on the server, see
`[2020-04-28 07:24:41]<5> mutt_socket_readln_d() 4< a0020 NO Mailbox doesn't exist: Lists.ABC (0.001 + 0.000 secs).`
on line 341.


Could you please try to unsubscribe from that mailbox, e.g., from within NeoMutt: `:unsubscribe-from Lists.ABC`. Quite / reopen NeoMutt and see if the problem goes away.

**Comment by ryanakca** [comment]
Unsubscribing from that mailbox (and from other non-existent mailboxes) seems to have fixed the issue. 

Previously, attempting to open non-top-level mailboxes would cause the "attempt to change, mailbox closed, reconnect, messy index lines" cycle, but I could successfully open "+INBOX", "+Spam", "+Bin", etc.

**Comment by gahr** [comment]
@steevmi1 could you please try building the branch [devel/issue-2110](https://github.com/neomutt/neomutt/tree/devel/issue-2110) and see whether it fixes the issue for you?
