### ISSUE TITLE
How to empty the recycle bin?

### ISSUE THREAD

**Issue by therealmaxmoon** [neomutt/neomutt#2112]
I am really new to neomutt, but I read the manual, the guide and tried many configs and I still have a lot of questions. I hope it is ok to put them all here in Github, because I couldn't find a forum or similar.

The first thing is, that I really want to figure out a way, how I can delete (move to trash) messages, which are older than 90 days and are NOT in Archive?

After moving some mails to trash by hand, I tried to empty the trash. But how? 
Is it like something fancy like tagging all messages in trash and purge them?
Another way I was thinking of, is just to do a cronjob to rm mailboxname/trash/cur. But I don't understand the concept of it, because even the trash has new, cur & tmp and maybe I would break something, if I just delete those by hand?

Thanks for your help :)

**Comment by gahr** [comment]
>  I hope it is ok to put them all here in Github, because I couldn't find a forum or similar.

Hi, our [mailing lists](https://neomutt.org/#mailing-lists) and [IRC channel](https://neomutt.org/#irc---ircircfreenodenetneomutt) might be a better place for user questions.

> how I can delete (move to trash) messages, which are older than 90 days and are NOT in Archive?

See the [Pattern Modifier](https://neomutt.org/guide/advancedusage.html#3-%C2%A0patterns-searching-limiting-and-tagging) chapter of our guide. The `delete-pattern` command allows you to delete messages matching any pattern. I usually use the `~r` pattern (date-received) to flush old emails: `<delete-pattern>~r >90d`.

> Is it like something fancy like tagging all messages in trash and purge them?

Yeah, I have a macro to delete all emails and sync the mailbox which is based on the `.` pattern:
```
macro index      ,D '<delete-pattern>.<enter><sync-mailbox>y'    'Delete all'
```
