### ISSUE TITLE
exiting urlview/urlscan breaks pipe macro, only if browser wasn't open

### ISSUE THREAD

**Issue by rpolve** [neomutt/neomutt#2114]
## Expected Behaviour

Successfully complete macro by setting pipe_decode to $my_pipe_decode and unsetting my_pipe_decode

## Actual Behaviour

While returning to Neomutt, it will try to append (s) to "et pipe_decode=\$my_pipe_decode; unset my_pipe_decode"

## Steps to Reproduce

With this macro:

```# simulate the old url menu
macro index,pager,attach,compose \cb "\
<enter-command> set my_pipe_decode=\$pipe_decode pipe_decode<Enter>\
<pipe-message> urlview<Enter>\
<enter-command> set pipe_decode=\$my_pipe_decode; unset my_pipe_decode<Enter>" \
"call urlview to extract URLs out of a message"
```

Close browser, press ctrl+b, select url
Browser will open
Return to urlview, press either q or ctrl+c

## How often does this happen?

Always

## When did it start to happen?

The first time I tried opening a url with the browser closed

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.5.2-arch1-1 (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGme: 1.13.1
libnotmuch: 5.2.0
hcache backends: kyotocabinet, gdbm, lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

## Extra Info

* arch linux 5.5.2-arch1-1
* was not using multiple copies of NeoMutt at once
* was not using neither 'screen' or 'tmux'
* my email is stored local
* urlview 0.9-13

**Comment by xavierbaez** [comment]
I have the same problem.

**Comment by Austin-Ray** [comment]
I'm able to consistently reproduce this error. Furthermore, I've limited it down just the pager. Macro works correctly on index, attachments, and compose views.

@flatcap : Any ideas where to start debugging first?

As a temporary workaround, changing `<pipe-message> urlview<Enter>\` to `<pipe-message> urlview<Enter> \` made it work on the pager. Looks like neomutt eats a character.

**Comment by xavierbaez** [comment]
@Austin-Ray thanks, that fixed the bug. Please let us know when the bug is part of the package so I can download the updated version.

**Comment by roccoblues** [comment]
Hi, I'm currently cleaning up some older issues here. Can you still reproduce this with the latest version? Thanks!
