### ISSUE TITLE
What do all the index flags mean?

### ISSUE THREAD

**Issue by therealmaxmoon** [neomutt/neomutt#2115]
My emails have several flags, like N, F, +, T, C, r, etc. Only N and r are obvious, but what do all the others mean? I couldn't find anything on the neomutt website, only this:

`index_flags | pattern | Flags in the index`

Does someone has a list?

Thanks a lot :)

**Comment by mschilli87** [comment]
http://www.mutt.org/doc/manual/#tab-msg-status-flags
