### ISSUE TITLE
How to execute a command in background (without output)

### ISSUE THREAD

**Issue by therealmaxmoon** [neomutt/neomutt#2116]
I am trying to trigger mbsync in background, but I am not interested in the output and I don't want to be distracted while reading mails and I don't want to wait for mbsync to read mails again. So I tried to redirect all output to /dev/null, which works find in the terminal and in a bash script, but in neomutt it shows the output of mbsync in the first line overlapping the mailbox and the first email.

`macro index O "<shell-escape>mbsync -a &> /dev/null &<enter>" "run mbsync in background"`

Is there a nicer way to execute something in the background?

**Comment by jindraj** [comment]
Try `mbsync -a -q -q`  [mbsync(1)](http://isync.sourceforge.net/mbsync.html)

**Comment by therealmaxmoon** [comment]
I think 1 `-q` is enough to quiet the output of mbsync :)

But I was just wondering why I can't redirect all output to /dev/null. The correct way would be: 

`macro index O "<shell-escape>mbsync -a > /dev/null 2>&1 &<enter>" "run mbsync in background"`

Looks weird, but it works. But `-q` would be much shorter.

Thanks a lot.
