### ISSUE TITLE
sidebar: setting sidebar_highlight to underline not possible?

### ISSUE THREAD

**Issue by quite** [neomutt/neomutt#212]
It doesn't seem to be possible to set `sidebar_highlight` to underline (except when in mono mode). Can this be made possible? Or is there even a general problem that underline, bold etc attributes cannot be used in color mode?

As for `sidebar_indicator`, it seems to be hard set to `A_UNDERLINE `in code

**Comment by flatcap** [comment]
@quite There is a way...

The default attribute for the sidebar highlight is an underline.
If you don't set a colour, then it remains an underline.

> is there even a general problem that underline, bold etc attributes cannot be used in color mode?

Yes, this is how Mutt works, but there's no real reason.
Fixing the problem probably wouldn't be easy (though I haven't investigated this deeply).

**Comment by quite** [comment]
Ah, I mixed them up. Certainly highlight is underline by default. It was
indicator I wished to have underline. But I understand the general problem
now...

**Comment by flatcap** [comment]
If you want the (this mailbox is open) **indicator** to be an underline, you'll have to change the code, for now.  A small change to `color.c` will do it:
```diff
diff --git i/color.c w/color.c
index 7ce67c6..dd9b425 100644
--- i/color.c
+++ w/color.c
@@ -178,7 +178,8 @@ void ci_start_color (void)
   ColorDefs[MT_COLOR_SEARCH] = A_REVERSE;
   ColorDefs[MT_COLOR_MARKERS] = A_REVERSE;
 #ifdef USE_SIDEBAR
-  ColorDefs[MT_COLOR_HIGHLIGHT] = A_UNDERLINE;
+  ColorDefs[MT_COLOR_HIGHLIGHT] = A_REVERSE;
+  ColorDefs[MT_COLOR_SB_INDICATOR] = A_UNDERLINE;
 #endif
   /* special meaning: toggle the relevant attribute */
   ColorDefs[MT_COLOR_BOLD] = 0;
```
