### ISSUE TITLE
pager_index_lines and reverse sort leads to repeated key actions

### ISSUE THREAD

**Issue by yourealwaysbe** [neomutt/neomutt#2122]
## Expected Behaviour

Using the config file

    set pager_index_lines=10
    set sort=reverse-date

1. Open a mailbox, say imap://mymail.com.
2. Select an email and view in the pager.
3. Interface handles new mails arriving gracefully.

## Actual Behaviour

When new emails arrive, the last keypress in the pager appears to be repeated. E.g. if you copy yourself in on an email reply and send, neomutt repeats the "reply" keypress when the reply arrives in your inbox.

## Steps to Reproduce

1. Open a local mailbox (say /mail).
2. Select an email and view in the pager.
3. In the pager still, attempt to compose or reply to an email. Abort this at the send screen as there's no SMTP configured. This returns you to the pager.
4. Send a mail to /mail from elsewhere.
5. Press an arrow key in the pager if required so neomutt notices the new email.
6. neomutt will begin composing an email again.

## How often does this happen?

Always

## When did it start to happen?

- When I changed my config

I started setting pager_index_lines to a non-zero value.

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.5.1-arch1-1 (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGme: 1.13.1
libnotmuch: 5.2.0
hcache backends: kyotocabinet, gdbm, lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Linux csmattpp 5.5.1-arch1-1 #1 SMP PREEMPT Sat, 01 Feb 2020 16:38:40 +0000 x86_64 GNU/Linux
* Were you using multiple copies of NeoMutt at once? **No**
* Were you using 'screen' or 'tmux'? **No**
* Is your email local (maildir) or remote (IMAP)? **maildir**

edit: updated as experiments today only work with maildir.

**Comment by yourealwaysbe** [comment]
A git bisect identifies the bug as beginning at commit 918885f32db41a452c23379c62dd2a9a752930d1, which is "recompute and re-thread everything in mx_update_context".

**Comment by roccoblues** [comment]
Hi, I'm currently cleaning up some older issues here. Can you still reproduce this with the latest version? Thanks!

**Comment by yourealwaysbe** [comment]
Couldn't reproduce.

However, with reverse date sort and the pager view, suppose you're viewing the 10th email in the list and you have pager_index_lines=10. You can see the email you're viewing is also selected in the index. When a new mail arrives it gets inserted at the top of the index (reverse date), which bumps all the other emails down a line. The selection highlighting stays at position 10, which is no longer the mail you're actually viewing. I could make another bug report for this (not that it bothers me much)?

**Comment by roccoblues** [comment]
Thank you for the quick feedback!

I know that @flatcap has a long term plan to separate the GUI mails better from the backend. That is a big refactoring that will take a while. I think that this could be fixed by that.

I wouldn't open an issue if it doesn't bother you much. I doubt that anyone will look into it before the refactoring is finished.
