### ISSUE TITLE
Can't build neomutt from master

### ISSUE THREAD

**Issue by therealmaxmoon** [neomutt/neomutt#2124]
After executing `./configure && make` I get the following message and I don't understand it.

```
msgfmt -c -o po/sk.mo po/sk.po
msgfmt -c -o po/sv.mo po/sv.po
msgfmt -c -o po/tr.mo po/tr.po
msgfmt -c -o po/uk.mo po/uk.po
msgfmt -c -o po/zh_CN.mo po/zh_CN.po
msgfmt -c -o po/zh_TW.mo po/zh_TW.po
mkdir -p doc
cc -I. -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__   \
    -o doc/makedoc ./doc/makedoc.c
( sed -e "s/@VERSION@/2019-12-07/; s!/usr/libexec!~/.local/libexec!g" \
    ./doc/manual.xml.head && \
    cc -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__  -D_MAKEDOC -E -C -I. ./mutt_config.c | doc/makedoc -s && \
    cc -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__  -D_MAKEDOC -E -C -I. ./functions.c | \
    perl ./doc/gen-map-doc ./doc/manual.xml.tail \
    ./opcodes.h \
) > doc/manual.xml
map smime undefined at ./doc/gen-map-doc line 64, <XML> line 23.
map mixmaster undefined at ./doc/gen-map-doc line 64, <XML> line 24.
map autocrypt account undefined at ./doc/gen-map-doc line 64, <XML> line 26.
xsltproc --nonet -o doc/ ./doc/chunk.xsl doc/manual.xml > /dev/null 2>&1
make: *** [Makefile:589: doc/index.html] Error 5
```

Thank you for your help.

**Comment by flatcap** [comment]
The build's failing whilst building the docs.
There are a couple of things going on here:

> map smime undefined at ./doc/gen-map-doc line 64, <XML> line 23.
> map mixmaster undefined at ./doc/gen-map-doc line 64, <XML> line 24.
> map autocrypt account undefined at ./doc/gen-map-doc line 64, <XML> line 26.

These are just warnings.  They can be ignored.
When the docs are built, they only include the features that you've enabled in the `configure` options.  Mostly.

> xsltproc --nonet -o doc/ ./doc/chunk.xsl doc/manual.xml > /dev/null 2>&1

To process the DocBook xml into help, we need `xlstproc` and also the DocBook DTDs (a set of rules for XML -\> HTML transformation).
Install the docbook-xsl` package (or `docbook-dtds` depending on your distro).

Alternatively, you can `./configure --disable-doc` to just build the code.

**Comment by flatcap** [comment]
If you have any other problems, feel free to reopen this issue.
