### ISSUE TITLE
How to set 'from' if mailbox is virtual (notmuch)

### ISSUE THREAD

**Issue by therealmaxmoon** [neomutt/neomutt#2125]
I have several mailboxes and with the following command I can show all unread mails:

`virtual-mailboxes "Unread" "notmuch://?query=tag:unread"`

But if I want to reply to a message, the from field is filled with username@hostname instead of the email address, which was it sent to.

Because it contains a lot of email addresses, I can't just hard code `set from=real@address.tld` into `folder-hook Unread`

Is there a dynamic way to do it?

**Comment by Austin-Ray** [comment]
You can use the `reverse_name`[0] configuration option.

[0] https://neomutt.org/guide/reference#3-316-%C2%A0reverse_name

**Comment by therealmaxmoon** [comment]
Nice, the following lines work if they are in the file for the folder-hook for Unread

```
alternates mailbox1@domain.tld mailbox2@domain.tld mailbox3@domain.tld
set reverse_name=yes
set reverse_realname=yes
```

Thanks a lot :)
