### ISSUE TITLE
Please provide an alias for pgp_sign_as

### ISSUE THREAD

**Issue by agx** [neomutt/neomutt#213]
In https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841826 I learned that pgp_sign_as also affects pgp_encrypt_self where it picks the _encryption_ key (rather than the signing key). What about providing an alias:

pgp_default_key

That better matches usage for encryption and signing.

**Comment by flatcap** [comment]
It's a useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
