### ISSUE TITLE
Recent refactoring appears to have broken OAUTHBEARER

### ISSUE THREAD

**Issue by fourjay** [neomutt/neomutt#2130]
## Expected Behaviour

Use the previously working OAUTHBEARER support 

## Actual Behaviour

Using the walkthrough with the google authenticator has been working for a while

pulling latest code with
```
make distclean
configure
make
sudo make install
```
and re-launching neomutt briefly flashes
``No authenticators available or wrong credentials``
Then shows
``No mailbox is open``

reverting to commit ce1173f7c5b6886f5e01613265f576caf0726747 and the previously configured external OAUTH support works again.

## How often does this happen?

- Always

## NeoMutt Version

```
NeoMutt 20191207-168-c45f47
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.12.14-lp151.28.36-default (x86_64)
ncurses: ncurses 6.1.20180317 (compiled with 6.1.20180317)
libidn: 1.34 (compiled with 1.34)
hcache backends: kyotocabinet

Configure options: --kyotocabinet --ssl --disable-doc

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR -I/usr/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn +inotify
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp -sasl +smime
  -sqlite +start_color +sun_attachment +typeahead -zlib
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

* Operating System and its version

opensuse leap 15.1

* Were you using multiple copies of NeoMutt at once?

no

* Were you using 'screen' or 'tmux'?

Yes, but tried outside of tmux, and the same issue.

* Is your email local (maildir) or remote (IMAP)?

IMAP

**Comment by jindraj** [comment]
I did git bisect and c4b3201e81cbf9cbffbb23cc5b754cb917e2d8c7 is the first bad commit`

**Comment by flatcap** [comment]
Please can you give [[devel/oauth1]](https://github.com/neomutt/neomutt/compare/devel/oauth1) a try.
I've reverted the code which assembles the encoded token.

**Comment by jindraj** [comment]
I'm unable to compile the [devel/oauth1](https://github.com/neomutt/neomutt/compare/devel/oauth1)

**Comment by jindraj** [comment]
```[2020-02-14 15:14:50]<2> imap_authenticate() Trying user-defined imap_authenticators
[2020-02-14 15:14:50]<2> imap_authenticate() Trying method oauthbearer
[2020-02-14 15:14:50]<M> imap_auth_oauth() Authenticating (OAUTHBEARER)...
[2020-02-14 15:14:50]<1> mutt_account_getlogin() Couldn't get user info
[2020-02-14 15:14:50]<2> mutt_sasl_client_new() SASL local ip: CENSORED;60720, remote ip:2a00:1450:400c:c0a::6d;993
[2020-02-14 15:14:50]<2> mutt_sasl_client_new() External SSF: 256
[2020-02-14 15:14:50]<2> mutt_sasl_client_new() External authentication name: CENSORED@gmail.com
[2020-02-14 15:14:50]<2> mutt_sasl_cb_authname() getting user for imap.gmail.com:993
[2020-02-14 15:14:50]<2> imap_auth_sasl() oauthbearer unavailable
[2020-02-14 15:14:50]<E> imap_authenticate() No authenticators available or wrong credentials```

**Comment by flatcap** [comment]
> Couldn't get user info

Ah!  I see.
Oauth is looking for `$imap_login`, but if that doesn't exist it should use `$imap_user` instead.
Please can you give [[devel/oauth2]](https://github.com/neomutt/neomutt/tree/devel/oauth2) a try.

**Comment by jindraj** [comment]
the muttdebug tells me the same.

**Comment by flatcap** [comment]
hmm... that implies that neither `$imap_login` nor `$imap_user` are set.

**Comment by jindraj** [comment]
… well I should have shared config i'm testing with.
```
# this is just to get my normal config 
source ~/.neomutt/neomuttrc
# to cleanup the sidebar
unmailboxes * 
#i already use SMTP with OAUTH
set imap_oauth_refresh_command=$smtp_oauth_refresh_command 
set imap_authenticators=$smtp_authenticators
# and here we go. no $imap_login nor $imap_user.
set folder= imaps://CENSORED@gmail.com@imap.gmail.com:993/
set imap_list_subscribed =yes
set imap_check_subscribed=yes
mailboxes +INBOX
```
I'm not using imap normally. Maybe I'm doing something wrong, but this worked fine before.

**Comment by flatcap** [comment]
I think I understand.

Before the changes, there were two copies of the credentials (one in IMAP, one in the Connection).
I think that IMAP was parsing the connection string: `imaps://CENSORED@gmail.com@imap.gmail.com:993/` saving the results and using them later.

OK, that'll take me a little longer to think through and fix.

**Comment by flatcap** [comment]
@fourjay 
Please can you give branch [[devel/oauth]](https://github.com/neomutt/neomutt/tree/devel/oauth) a try. ([Pull Request](https://github.com/neomutt/neomutt/pull/2134))
It should fix your problem.

**Comment by fourjay** [comment]
It works :-)
It shows:
``Press any key to continue...``
Then, once pressed, a message flashes about gpgme, with a reference to not being set and an all caps GPGME reference following.
I'm not sure how to capture the message (is there a command like "messages" to display the last error?)
After that flash it does auth me to Google (thanks)

**Comment by flatcap** [comment]
> It works :-)

Great, I'll merge the fix.

> an all caps GPGME reference

To capture the message, you can run with debugging enabled `neomutt -d6` which will log to `~/.neomuttdebug0`
You can also view the logs live in NeoMutt, by pressing <kbd>M</kbd> (`<show-log-messages>`).

We _have_ just changed GPGme to be enabled by default.
It shouldn't cause any problems.  You could try `set crypt_use_gpgme = no`

**Comment by BH1SCW** [comment]
> [2020-02-14 15:14:50]<2> imap_authenticate() Trying method oauthbearer
> [2020-02-14 15:14:50]<M> imap_auth_oauth() Authenticating (OAUTHBEARER)...
> [2020-02-14 15:14:50]<1> mutt_account_getlogin() Couldn't get user info
> [2020-02-14 15:14:50]<2> mutt_sasl_client_new() SASL local ip: CENSORED;60720, remote ip:2a00:1450:400c:c0a::6d;993
> [2020-02-14 15:14:50]<2> mutt_sasl_client_new() External SSF: 256
> [2020-02-14 15:14:50]<2> mutt_sasl_client_new() External authentication name: CENSORED@gmail.com
> [2020-02-14 15:14:50]<2> mutt_sasl_cb_authname() getting user for imap.gmail.com:993
> [2020-02-14 15:14:50]<2> imap_auth_sasl() oauthbearer unavailable
> [2020-02-14 15:14:50]<E> imap_authenticate() No authenticators available or wrong credentials```

Hi  developer
I got almost the same log with your  log,  I don't change anything, it just does not work this morning here is my log

[2022-04-29 10:36:28]<3> imap_cmd_step() IMAP queue drained
[2022-04-29 10:36:28]<2> imap_authenticate() Trying user-defined imap_authenticators
[2022-04-29 10:36:28]<2> imap_authenticate() Trying method oauthbearer
[2022-04-29 10:36:28]<M> imap_auth_oauth() Authenticating (OAUTHBEARER)...
[2022-04-29 10:36:28]<E> mutt_account_getoauthbearer() Command returned empty string
[2022-04-29 10:36:28]<2> mutt_sasl_client_new() SASL local ip: 10.248.194.188;58418, remote ip:142.250.157.108;993
[2022-04-29 10:36:28]<2> mutt_sasl_client_new() External SSF: 256
[2022-04-29 10:36:28]<2> mutt_sasl_client_new() External authentication name: bh1scw@gmail.com
[2022-04-29 10:36:28]<2> mutt_sasl_cb_log() SASL: No worthy mechs found
[2022-04-29 10:36:28]<2> imap_auth_sasl() oauthbearer unavailable
[2022-04-29 10:36:28]<E> imap_authenticate() No authenticators available or wrong credentials
[2022-04-29 10:36:28]<2> mutt_window_reflow() entering
[2022-04-29 10:36:28]<3> imap_adata_find() no ImapAccountData found
[2022-04-29 10:36:28]<3> mutt_num_postponed() using old IMAP postponed count
[2022-04-29 10:36:30]<3> mutt_index_menu() [1336]: Got op 190
[2022-04-29 10:36:30] Closing log.


I am not sure if this is related with Google because I saw below on OAuth consent screen

Token grant rates limit how quickly your application can get new users.
Your current per minute token grant rate limit is 100 grants per minute. The per minute token grant rate resets every minute.

Thanks

**Comment by BH1SCW** [comment]
I have found the root cause,  I need to refresh the key！　　=。＝！
