### ISSUE TITLE
"Key is not bound" message may print raw control characters

### ISSUE THREAD

**Issue by bradking** [neomutt/neomutt#214]
When using a control character in the help key binding:

```
bind generic \Ch help
```

pressing an unbound key combination prints a control character to the terminal without any encoding.

From a quick glance at the code I believe [this line](https://github.com/neomutt/neomutt/blob/neomutt-20161014/keymap.c#L861) needs to first encode the control character in human-readable form (e.g. `\Ch`).

**Comment by flatcap** [comment]
Thanks @bradking.

**Comment by bradking** [comment]
@flatcap sorry about this, but I misrepresented the problem in this report.  `km_expand_key` was already called earlier in `km_error_key` before your change.

See #215 for a more accurate report of the problem.
