### ISSUE TITLE
Segfault in header cache compression

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#2148]
Sorry I failed to see this when reviewing #1922 some months ago.

The compression functions return NULL if the input buffer is too short to be (effectively) compressed ([lz4](https://github.com/neomutt/neomutt/blob/b49866857ed56b536265da80fde69d4bd192e110/hcache/compr_lz4.c#L61-L62), [zlib](https://github.com/neomutt/neomutt/blob/b49866857ed56b536265da80fde69d4bd192e110/hcache/compr_zlib.c#L62-L63), [zstd](https://github.com/neomutt/neomutt/blob/b49866857ed56b536265da80fde69d4bd192e110/hcache/compr_zstd.c#L94-L95)).

Caller code [does not check](https://github.com/neomutt/neomutt/blob/b49866857ed56b536265da80fde69d4bd192e110/hcache/hcache.c#L557) the return value, and feeds it blindly into the header cache backend, causing a segfault.

This happens at every mailbox open, when storing the mailbox' UIDVALIDITY (a 4-bytes integer).

I remember testing the header cache compression mechanism while back and noticing a huge decrease in on-disk size. I wonder how we missed this.

@mcmilk what do you suggest?

Edit: fixed link to pull req.

**Comment by mcmilk** [comment]
Maybe I had some more variables for this in my first pull requests ... but then we have optimized the things ;-)

I will create a small bug fix for it ...
