### ISSUE TITLE
Infinite loop when pager help is bound to a control sequence

### ISSUE THREAD

**Issue by bradking** [neomutt/neomutt#215]
When using

```
bind pager \Ch help
```

pressing an unbound key within the pager produces an infinite loop.

This appears related to commit 6d9c6c36f7c45f62e4f583cd9c985df8e6e5afbc (Fix infinite loop when help is bound to a named key combination, 2016-05-24).

**Comment by flatcap** [comment]
OK, a quick test shows that this bug exists in upstream mutt, versions 1.7.1 and default (latest dev version).

I'll see what I can do.

**Comment by toogley** [comment]
(just to provide clarity: **I** did change the labels, not @bradking - i guess Github has made an error here.)

**Comment by guyzmo** [comment]
I just tried the issue and could reproduce it.

@bradking what was your intent in using `\Ch` as binding?
Having <kbd>\\</kbd> followed by <kbd>C</kbd> followed by <kbd>h</kbd> as a key sequence to open help?

Has a bug been opened on upstream?

**Comment by bradking** [comment]
@guyzmo my goal was to bind `Ctrl-h` as help.  The `\C` part means `Ctrl-` IIRC.  I'm not aware of any upstream report.

**Comment by flatcap** [comment]
I can no longer repeat this problem with the latest versions of Mutt or NeoMutt.
