### ISSUE TITLE
How to delete a message that is open?

### ISSUE THREAD

**Issue by thepenguinthatwants** [neomutt/neomutt#2158]
Hi guys!

I've being using neomutt for a while now. I have always deleted messages from index list. But I was wondering if its possible to somehow bind neomutt to delete a message straight from the opened mail?

**Comment by Austin-Ray** [comment]
I'm able to delete the current message in the pager with `d` without any additional configuration.

If that doesn't work, you could try a macro such as `macro pager d "qd"` to exit the pager and mark the message as deleted.

**Comment by flatcap** [comment]
Most screens in NeoMutt allow you press <kbd>?</kbd> for help.
That'll list all the key bindings that are active, including macros, and also functions that aren't yet bound.

<kbd>q</kbd> to quit the help
<kbd>/</kbd> to search the help
