### ISSUE TITLE
Local Directory File List is Empty when Trying to Attach a file

### ISSUE THREAD

**Issue by NWuensche** [neomutt/neomutt#2159]
## Expected Behaviour

I write an E-Mail and want to attach a file with `a`. When I press `?`, it should show all files in the current local directory and I can add the x-th file

## Actual Behaviour

I write an E-Mail and want to attach a file with `a`. When I press `?`, the list of files in my local directory is empty. However, if I add the position of a file by hand (/home/user/f.pdf), neomutt does attach the file to e-mail. 

## Steps to Reproduce

Writing E-Mail, try to attach file with `a`, open list with `?`

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded from 20180716-8 to current version

## NeoMutt Version

```
PUT YOUR "neomutt -v" OUTPUT HERE
```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.5.4-arch1-1 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.1.20180127)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGme: 1.13.1
libnotmuch: 5.2.0
hcache backends: kyotocabinet, gdbm, lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

## Extra Info

* Operating System and its version
Arch Linux 
* Were you using multiple copies of NeoMutt at once?
No 
* Were you using 'screen' or 'tmux'?
Yes, tmux, but it also occurs without tmux
* Is your email local (maildir) or remote (IMAP)?
IMAP

Thank you nevertheless for this awesome E-Mail client!

**Comment by scottkosty** [comment]
Thanks for the nice clear bug report. I can't reproduce on current master or on the version you see the bug with (20191207), so our setups must be different somehow. Can you reproduce the bug if you use only a very simple neomuttrc file?

And just to get more potentially useful information for when the neomutt experts take a look at this, when you are typing in the path to the prompt, does tab expansion work when completing the filename?

**Comment by JadowityHerbatnik** [comment]
I'm experiencing the same bug. I have two accounts with the exact same `muttrc` configuration, except for different mailboxes names. I noticed that this bug only happens on one of these two accounts and after it does, it stops working on the other account as well (until I restart neomutt), so apparently something "breaks" the file explorer. The tab expansion does work always though.

**Comment by NWuensche** [comment]
So my muttrc looks almost like the first five lines in the Arch-Mutt Summary: https://wiki.archlinux.org/index.php/Mutt#Summary . So I can't delete more. The tab expansion also works for me, but only for folders, not for filenames.

**Comment by arappe** [comment]
I think I have some information that unifies the findings of JadowityHerbatnik and NWuensche.
If I run Neomutt with no arguments (so no muttrc file) I find that file completion works completely normally (list of relevant files appears when trying to attach). I suggest trying this (even though it does not permit sending or receiving mail). You can prepare an email and see whether tab expansion works.

I then found that the minimal config file found at https://wiki.archlinux.org/index.php/Mutt#Summary works well preserving file completion.

Finally, I was able to take my previous 300-line muttrc file and add 
mailboxes       = +INBOX
restoring tab expansion for folders and files.

I hope this helps.

**Comment by NWuensche** [comment]
@arappe 's Answer works for me, thank you so much!
