### ISSUE TITLE
Symlink attachments should be attached as the actual link name, not the target

### ISSUE THREAD

**Issue by protist** [neomutt/neomutt#2168]
## Expected Behaviour

When creating an attachment, symlinks should be attached under the actual link name, not the target.

## Actual Behaviour

The target name is used, not the actual link name. This is important because I often use symlinks to sanitise filenames in outgoing emails.

## To reproduce
1. Create symlink
```
$ touch /tmp/foo
$ ln -s /tmp/foo /tmp/bar
```
2. Compose a new mail in Neomutt
3. Attach `/tmp/bar`
4. Observe attachment of `/tmp/foo`

## How often does this happen?

Always

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.5.8-arch1-1 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.1.20180127)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGme: 1.13.1
libnotmuch: 5.2.0
hcache backends: kyotocabinet, gdbm, lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: up-to-date Arch Linux
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? Local maildir.

**Comment by gahr** [comment]
> symlinks should be attached under the actual link name, not the target.

Out of curiosity (I haven't checked yet), is this based on what other mailers do, what NeoMutt used to do, or how you'd design the feature?

**Comment by protist** [comment]
> Out of curiosity (I haven't checked yet), is this based on what other mailers do, what NeoMutt used to do, or how you'd design the feature?

I actually just meant the third, but I just checked, and it's yes to all three! Thunderbird does this, and NeoMutt used to do this. I did a `git bisect`, and I tracked the first bad commit to ad00c1bf0efca24eb9930a5cf5096f585ba7688d. (This commit is also the first to fail to source my symlinks in `~/.muttrc`, so there's something fishy about it!)

**Comment by gahr** [comment]
Thanks, that's very helpful!
