### ISSUE TITLE
neomutt creates invalid mbox when copying mails maildir to mbox by using translated dates in 'From' line.

### ISSUE THREAD

**Issue by castilma** [neomutt/neomutt#2171]
## Expected Behaviour

When I copy (through neomutt) mails (which have no 'From ' line) from a Maildir-type mailbox to an mbox-type mailbox, neomutt adds a 'From ' line with a translated date. I expect to view the mail through neomutt in the mbox-type mailbox. 

## Actual Behaviour

But I have a german system, and it writes lines like `From mcd@arctic.box Mo Mär  9 12:03:19 2020`, and neomutt doesn't list that message, when I open the mailbox with neomutt. AFAIK, the date has to be in english in the mbox format.

When opening an example file with mutt -d 1 -f2mar.txt I get this log:
```
2020-03-11 19:18:12] NeoMutt-20191207 debugging at level 1
[2020-03-11 19:18:12]<M> log_file_open() Schreibe Fehlersuche der Stufe 1 nach Datei '/home/mcd/.neomuttdebug0'
[2020-03-11 19:18:12]<1> getdnsdomainname() Hostname: box
[2020-03-11 19:18:12]<1> mutt_folder_hook() folder-hook '.' matches '2mar.txt'
[2020-03-11 19:18:12]<M> mx_mbox_open() Lese /home/mcd/misc/bug.d/mutt/2mar.txt...
[2020-03-11 19:18:12]<M> mutt_progress_update() Lese /home/mcd/misc/bug.d/mutt/2mar.txt... 0
[2020-03-11 19:18:12]<1> is_from()  expected weekday, got: Mo Mär  9 12:03:19 2020

[2020-03-11 19:18:12]<M> mutt_sort_headers() Sortiere Mailbox...
[2020-03-11 19:18:13]<M> mx_mbox_close() Mailbox unverändert
[2020-03-11 19:18:13] Closing log.
# vim: syntax=neomuttlog
```

If NeoMutt crashed, did your OS create a 'coredump' file?
N/A

## Steps to Reproduce
Copy a mail from a maildir (without From_ line) to an mbox and then try to list that mailbox with neomutt.

## How often does this happen?
Always.

## When did it start to happen?

I just recently tried to use a mbox to reduce the time needed to list a mailbox and found, that the old mails I wanted to copy over weren't listed.

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins und andere.
NeoMutt übernimmt KEINERLEI GEWÄHRLEISTUNG. Starten Sie 'neomutt -vv', um
weitere Details darüber zu erfahren. NeoMutt ist freie Software.
Sie können es unter bestimmten Bedingungen weitergeben; starten Sie
'neomutt -vv' für weitere Details.

System: Linux 5.5.8-artix1-1 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.1.20180127)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGme: 1.13.1
libnotmuch: 5.2.0
hcache backends: kyotocabinet, gdbm, lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Standard Einstellungen:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Einstellungen bei der Kompilierung:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

I think the problem started with this [commit](https://github.com/neomutt/neomutt/commit/a03dbb4bcb5812cf12dc5de2459606156e12f83e). POSIX may recommend strftime over ctime and asctime, but POSIX is, well, POSIX: ctime is defined to always use english day and month abbreviations. But [strftime](http://man7.org/linux/man-pages/man3/strftime.3.html) uses the locale dependent day and month names.

I accidentaly reported this first on the mutt [issue page](https://gitlab.com/muttmua/mutt/-/issues/213).

* Operating System and its version Artix linux, up-to-date
* Were you using multiple copies of NeoMutt at once? yes.
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? maildir/mbox

**Comment by jindraj** [comment]
there's `if(!mutt_date_is_day_name())` inside `is_from()`, quick looking into `mutt_date_is_day_name()`
```c
bool mutt_date_is_day_name(const char *s)
{
  if (!s || (strlen(s) < 3) || (s[3] == '\0') || !IS_SPACE(s[3]))
    return false;

  for (int i = 0; i < mutt_array_size(Weekdays); i++)
    if (mutt_str_startswith(s, Weekdays[i], CASE_IGNORE))
      return true;

  return false;
}
```

Weekdays array is at the beginning of the mutt/date.c
```c
static const char *const Weekdays[] = {
  "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat",
};```

Can this even work with any non-english locale?

**Comment by flatcap** [comment]
> Can this even work with any non-english locale?

No.  It's not meant to.
When NeoMutt saves the email, it shouldn't write the date in the local format.

**Comment by flatcap** [comment]
Caused by: a03dbb4bcb5812cf12dc5de2459606156e12f83e.

**Comment by flatcap** [comment]
@castilma Thanks for the bug report and logs.

If you're happy building your own NeoMutt, please can you give branch [[devel/issue-1271]](https://github.com/neomutt/neomutt/tree/devel/issue-2171) a try.

**Comment by castilma** [comment]
The problem persists. Weird.
my locale:
```
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

**Comment by flatcap** [comment]
Great.
