### ISSUE TITLE
main() Error initializing terminal

### ISSUE THREAD

**Issue by predmijat** [neomutt/neomutt#2176]
## Expected Behaviour

no errors when sending an email from terminal with "echo ... | neomutt ..."

## Actual Behaviour

error: "Error initializing terminal"
no email is sent.

## Steps to Reproduce

send an email from terminal with "echo ... | neomutt ..."

## How often does this happen?

- Always

## When did it start to happen?

I noticed it last night (so I'm guessing since "NeoMutt 2020-03-13")

## NeoMutt Version

```
NeoMutt 20200313
```

## Extra Info

* Operating System and its version: both macOS Catalina 10.15.3 and Arch Linux 5.5.8-arch1-1
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? IMAP

Output with -d6:
```
[2020-03-15 13:28:15] NeoMutt-20200313 debugging at level 6
[2020-03-15 13:28:15]<M> log_file_open() Debugging at level 6 to file '/Users/predmijat/.neomuttdebug0'

WARNING:
    Logging at this level can reveal personal information.
    Review the log carefully before posting in bug reports.

[2020-03-15 13:28:15]<M> imap_auth_plain() Logging in...
[2020-03-15 13:28:15]<E> main() Error initializing terminal
[2020-03-15 13:28:15] Closing log.
# vim: syntax=neomuttlog
```

**Comment by flatcap** [comment]
Hmm... caused by 331702b6a96da072d031a38890b3f1c5d1273afb
