### ISSUE TITLE
Delete message, open new folder problems.

### ISSUE THREAD

**Issue by mlmatlock** [neomutt/neomutt#2181]
## Expected Behaviour

Delete a message in the index.  Select different folder in sidebar (using F5/F6), C-o to open new folder.  Message deleted, and new folder opens.

## Actual Behaviour

New folder does not open, message does not get deleted.  Need multiple F5/6 and C-o to get desired behaviour.

## Steps to Reproduce

See what went wrong, above.

## How often does this happen?

- Always

## When did it start to happen?

Upgraded to 20200313 from 20191207

## NeoMutt Version

```
neomutt -v
NeoMutt 20200313
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.5.9-arch1-2 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGme: 1.13.1
libnotmuch: 5.2.0
hcache backends: kyotocabinet, gdbm, lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua -lz4 +meta -mixmaster +nls +notmuch -openssl +pgp +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead -zlib -zstd 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

* Operating System and its version

Arch Linux

* Were you using multiple copies of NeoMutt at once?

No

* Were you using 'screen' or 'tmux'?

No

* Is your email local (maildir) or remote (IMAP)?

IMAP (gmail)

Git Bisect Accomplished.  Result: 95c365f5d03f19dd5ebd3f8980e575f5b38e1e81

```
95c365f5d03f19dd5ebd3f8980e575f5b38e1e81 is the first bad commit
commit 95c365f5d03f19dd5ebd3f8980e575f5b38e1e81
Author: Richard Russon <rich@flatcap.org>
Date:   Fri Jan 17 00:21:39 2020 +0000

    propagate result of sync_mailbox()
    
    An upstream refactoring meant that the return values of
    mh_mbox_sync()/imap_sync_mailbox() weren't being propagated.

 imap/imap.c      | 13 +++++++++----
 maildir/shared.c | 17 ++++++++++++-----
 mx.c             | 14 ++++++++++++++
 3 files changed, 35 insertions(+), 9 deletions(-)
```

**Comment by flatcap** [comment]
Thanks for the bug report and bisect, @mlmatlock.
I've pushed 3dae09ca93 which fixes a similar-sounding problem with sync/trash.
Please can you give master a try to see if that fixes your problem.
Thanks.

**Comment by mlmatlock** [comment]
Hi @flatcap,

Unfortunately, it didn't work.

I've uploaded a few screenshots detailing my issue:

https://github.com/mlmatlock/screenshots

The filenames [1,6]-*.png are in sequential order.

**Comment by flatcap** [comment]
Please can you give branch [[devel/issue-2181]](https://github.com/neomutt/neomutt/tree/devel/issue-2181) a try.
`imap_sync_mailbox()` can return flags which may be confusing `mx_mbox_close()`.

**Comment by mlmatlock** [comment]
Branch devel/issue-2181 is working as expected now.

Thank you!
