### ISSUE TITLE
How to mark en email without opening it, like opposite of N to mark it unread?

### ISSUE THREAD

**Issue by c02y** [neomutt/neomutt#2185]
## What would you like to be able to do?
I'd like to mark an email read without opening it, just like opposite of N to make it unread.

## What needs to change in NeoMutt?
Provide a function and bind for the action that mark an email read.

**Comment by mschilli87** [comment]
How about clearing the new flag? <kbd>Ctrl</kbd>+<kbd>W</kbd> followed by <kbd>N</kbd> does that with default bindings.

**Comment by c02y** [comment]
Didn't notice the `clear-flag` function, thanks, `W->N` will do.
