### ISSUE TITLE
Can't OpenSSL Subprocess when forwarding S/MIME mail (for one particular email)

### ISSUE THREAD

**Issue by sadsfae** [neomutt/neomutt#219]
I get the following error after upgrading to `neomutt-1.7.1-20161028.fc24.x86_64` when trying to forward an email with an MIME attachment.  However this also happens on `neomutt-1.7.1-20161014.fc24.x86_64`  This may not be a mutt issue, but thought I'd file here just in case.

When I hit send to forward along a particular message I get the error:

```
Can't open OpenSSL subprocess!: Success (errno = 0)
```

I've also gotten this error on `neomutt-1.7.1-20161014.fc24.x86_64` after dnf downgrading to it.

This looks similiar to [this issue](https://www.mail-archive.com/mutt-users@mutt.org/msg45167.html) but maybe it's just me?

Here's an strace of mutt

```
open("/tmp/mutt-oberschnutz-1000-3833-1309956995790919976", O_RDONLY) = 7
rt_sigaction(SIGINT, {0x5624387dbd90, [], SA_RESTORER, 0x7fc8471fb770}, NULL, 8) = 0
fstat(7, {st_mode=S_IFREG|0600, st_size=13639, ...}) = 0
read(7, "Return-Path: memo-list-bounces@r"..., 4096) = 4096
write(5, "Content-Type: multipart/mixed; b"..., 4096) = 4096
read(7, "plications consuming LDAP data,\n"..., 4096) = 4096
write(5, "t.com, it-iam-announce-list@XXXX"..., 4096) = 4096
read(7, " walrus\n########################"..., 4096) = 4096
write(5, "ovember 17th cutover.\n\n\n\n--=20\n#"..., 4096) = 4096
read(7, "WyNMwH1RNfGaVS8MTTALP1hgp8LW8vEv"..., 4096) = 1351
read(7, "", 4096)                       = 0
read(7, "", 4096)                       = 0
write(5, "N5MHcwHQYDVR0OBBYE\nFDDeBFShhgKfE"..., 1811) = 1811
rt_sigaction(SIGINT, {0x5624387dbd90, [], SA_RESTORER|SA_RESTART, 0x7fc8471fb770}, NULL, 8) = 0
close(7)                                = 0
write(5, "\n--vemjp4szliyfttnj--\n", 22) = 22
close(5)                                = 0
open("/.index", O_RDONLY)               = -1 ENOENT (No such file or directory)
write(1, "\7", 1)                       = 1
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=37, ws_col=136, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(1, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost isig -icanon -echo ...}) = 0
write(1, "\0337\33[?47h\33[1;37r\33[m\33[m\33[4l\33[H\33[2J"..., 1516) = 1516
write(1, "\7", 1)                       = 1
write(1, "\r\33[31m\33[1mCan't open OpenSSL sub"..., 67) = 67
close(6)                                = 0
```

Subsequent tries forwarding other messages work fine, one thing to note in this case it prompted me for `Enter S/MIME passphrase:` whereas when I normally send email it says "enter GPG Passphrase" as I sign all outgoing messages.  This seems to be with only one particular email.

It still prompts me for this even if I turn off my GPG autosign.

Here is the email breakdown:

```
  I     1 <no description>                                     [multipa/signed, 7bit, 9.9K] 
  I     2 ├─><no description>                              [text/plain, quoted, utf-8, 4.8K] 
  A     3 └─>S/MIME Cryptographic Signature   [applica/pkcs7-sign, base64, 4.6K] 
  I     4 <no description>                                     [text/plain, 7bit, us-ascii, 0.2K] 
```

Maybe I'm doing something wrong or need an additional S/MIME setting in my muttrc?

**Comment by gahr** [comment]
I have a similar experience. When forwarding a S/MIME signed message, mutt thinks I want to sign with S/MIME, although I have no S/MIME keys setup.

**Comment by gahr** [comment]
@sadsfae do you happen to have `crypt_autosmime` set to `yes` (the default), and does unsetting it help?

**Comment by flatcap** [comment]
This issue has been quiet for a while, now.
Hopefully this means there haven't been any further problems.
Intermittent problems, like this, are hard to debug, but each release of NeoMutt adds more fixes and checks.
If the problem reoccurs, please re-open this issue.
