### ISSUE TITLE
Weird/extra characters are passed to a filter in index_format

### ISSUE THREAD

**Issue by deramed** [neomutt/neomutt#221]
I've got this index_format:

`folder-hook "." 'set index_format="$my_rcdir/bin/trimi \"<<%S>>%?M?+& ?%-22.22F │ %s\"|"'`

And this is what is being passed to `trimi`:

`<<^N^]-^N^[>> ^N^\To John Friend    ^N^[ │ ^N^^Re: Subject...^N^[`

It seems that every `%format string` is being encompassed by  those ^N,^] etc.

<^N>  14,  Hex 0e,  Octal 016
<^]>  29,  Hex 1d,  Octal 035 
<^[>  27,  Hex 1b,  Octal 033
<^^>  30,  Hex 1e,  Octal 036

**Comment by flatcap** [comment]
Ah, I think I see what's going on.

Those random characters are the codes inserted by the "index-color" feature.
They should be disabled when piping the format to a command.

**Comment by deramed** [comment]
Sounds plausible.

Just for reference: https://github.com/neomutt/neomutt/issues/113#issuecomment-242920234

**Comment by nobrowser** [comment]
Hmm, the index-color patch looks like exactly what I was talking about here:

https://marc.info/?l=mutt-users&m=147517183208508&q=raw

Strange that I didn't even get a single reply then.  Maybe I should switch to actually using neomutt, at last   {8~0
