### ISSUE TITLE
Is it able to show the mailing list to the sidebar like Inbox of Gmail

### ISSUE THREAD

**Issue by c02y** [neomutt/neomutt#2216]
I personally set filters in Gmail to move all emails from a mailing list(I got multiple mailing lists) to skip the Inbox and give them a label which will be displayed in the sidebar in Gmail webpage like Inbox/Starred. 

Is it able to display all emails from a mailing list to the sidebar of neomutt like Inbox of Gmail (multiple folders in sidebars of neomutt for multiple mailing lists)?

**Comment by jindraj** [comment]
What are your neomutt mailboxes? IMAP, local maildirs, notmuch virtual mailboxes, or something else?
Is this result yout want? Screenshot below stolen from PR2205.
![img](https://user-images.githubusercontent.com/1640737/77494442-1fceaf00-6e1c-11ea-86b2-80bc013ed3ff.png)

**Comment by c02y** [comment]
Yes, the structure in the image is what I need, take Linux Kernel for example, could you please share your part of configuration?

I'm using imap (set folder = "imaps://imap.gmail.com/") if I understood it correctly.

**Comment by jindraj** [comment]
1. enable sidebar indenting and display only short path
```
set sidebar_short_path        = yes
set sidebar_folder_indent     = yes
```
2. add new mailboxes which you want:
```
named-mailboxes "lists"              SOMELABELX
named-mailboxes "lists/linux"        SOMELABELXY
named-mailboxes "lists/linux/kernel" SOMELABELXYZ
…
```

**Comment by c02y** [comment]
I'm sorry, I don't get it, how can I exactly bind the folder name/label name with the mailing list I subscribed?

For instance, these are mailing lists I subscribed: 
~~~
subscribe linux-kernel@vger.kernel.org linux-newbie@vger.kernel.org linux-api@@vger.kernel.org
subscribe kernelnewbies@kernelnewbies.org
subscribe python-announce-list@python.org python-list@python.org
subscribe tmux-users@googlegroups.com
~~~
In Gmail webpage, each line is one label in the sidebar.

How can I bind each subscribe line into one folder into the sidebar of neomutt?

**Comment by jindraj** [comment]
AFAIK you can't create mailbox out of subscribe config options.

But You can label messages from those maillists by automatic rules in GMail.
On GMail side tt doesn't need to be nested and label names don't need to match the names – since you can name it using named-mailboxes.
The short names and indenting works only in current master atm. 


labels in gmail
```
lists
lists/linux
lists/linux/kernel
…
```

than having neomutt configuration like 
```
named-mailboxes "lists"              =[Gmail].lists
named-mailboxes "lists/linux"        =[Gmail].lists.linux
named-mailboxes "lists/linux/kernel" =[Gmail].lists.linux.kernel
```
Should result in what you want in sidebar. I didn't test the configuration. I believe it works.

**Comment by c02y** [comment]
Sorry, the sidebar successfully displays the folders but the folders cannot be opened and it says "[NONEXISTENT] Unknown Mailbox ..."

**Comment by jindraj** [comment]
ok, try it wihtout [Gmail]. Just tested it and it works. I don't have any nested labels so I can't test them. I don't know if the dot as separator works or if you can use slash or something else.
eg:
`named-mailboxes "lists"              =lists`

**Comment by c02y** [comment]
WOW, it works, thanks a lot. :+1:
