### ISSUE TITLE
What prevents us from Unit Testing our C code directly? (instead of using lua for that)

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#222]
In [#153](https://github.com/neomutt/neomutt/issues/153), we discussed the advantages of integrating lua, which would also allow us to unit test our Code.

I'm curious, why we don't start *now* unit testing our C code directly - That means by using an [C Unit testing frameworks](https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#C).

I'm not saying we should forget about integrating lua - or forget about using lua unit tests later. I'm just curious about why we don't use some C unit testing framework to bridgeover until lua is usable within neomutt.

**Comment by flatcap** [comment]
Using lua would only be a poor man's solution to testing -- a simple way to inject/extract data.

> why we don't start **unit testing** our C code directly

**Time**

To start with, it would only be possible to test the simplest parts of Mutt.  This would take time to set up, but we wouldn't really get much benefit from it.

Looking back at some of the bugs we've fixed, I'm not sure how I would have written a test to detect the problem.

**Complexity**

This is the killer.  In an ideal world, a function would have defined inputs, outputs and errors.  It would be self-contained and have no side-effects.  It would be easy to test.

In Mutt, the functions have grown large and ugly.  They are poorly-defined, rely on large numbers of global variables and have side-effects.

**Scripting**

I think a simple starting place would be to script the app as a whole (using something like [expect](https://en.wikipedia.org/wiki/Expect)).
Unfortunately, I haven't found a tool that can "run" a curses app.

We'd need to be able to inject keypresses and listen to events / questions.

---

But enough of my pessimism.  Tell me how it **can** be done.

**Comment by toogley** [comment]
Ah, okay.  Thanks for the explanation.

> But enough of my pessimism. Tell me how it **can** be done.

The intention of this question wasn't to improve sth, rather to understand the current state. :) That means, i also don't have a good solution for that. (at least not at the moment.)

**Comment by ThomasAdam** [comment]
You're never going to be able to use `expect` to test mutt.

Note that there's a difference between functional testing and unit testing, and from what I've been reading in the discussions here, those two have gotten muddled.  Unit-testing is about code-coverage, and manipulating mutt at run-time is functional.

That said, I think that lua is a poor choice for unit-testing when there's frameworks out there already for C which you could use.  If you want to try and manipulate mutt in an automatic way then you would have to use something else.

**Comment by guyzmo** [comment]
I believe that the main issue we're having with the code base comes from that fact:

> In Mutt, the functions have grown large and ugly. They are poorly-defined, rely on large numbers of global variables and have side-effects.

I'm not an unit-testing radicalist, and I'd rather target a 50% or less coverage, as long as within this coverage you cover all the paths and make sure that you're covering the core most important building blocks that ensure the rest of your code is rather rock solid.

But then, that would mean a rather ambitious refactoring of the code base… and it's likely to mean breaking backward compatibility and application of patches from the upstream.

**Comment by toogley** [comment]
closing in favor of [#414](https://github.com/neomutt/neomutt/issues/414)
