### ISSUE TITLE
Newlines in header lines (e.g., subject, User-Agent) not removed for first view of first message

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#2222]
To reproduce,

1. Send yourself an email with a subject line long enough that the header will be multiple lines.
2. Start mutt and open the message. It's important to not change folders or open a different message before.

## Expected Behaviour

The display of the subject line should be the same on the first view of the message as on the second view.

## Actual Behaviour

The first view has the subject line broken. If I do simply `<sync-mailbox>` or just `<exit><Return>`, the subject line is displayed as one line (which is what I would expect on the first view).

Here is the screen on first view:
![first](https://user-images.githubusercontent.com/1149353/77851414-12f8e500-71a7-11ea-850f-fe07de55f6dc.png)
Here is the screen on the second view:
![second](https://user-images.githubusercontent.com/1149353/77851416-15f3d580-71a7-11ea-84d5-16302203cb34.png)

## How often does this happen?

Whenever the first message I open after starting NeoMutt has a subject line that has multiple lines.

## When did it start to happen?

A bisect gives the following:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
1243cfb1abcd37b9f8053dcd989c978b923333e2
537ecd47862213487fd24005f9b6fbe38cb17ac7
553c0dc04b6379d5aa7996a43d4aa8e19106fd4f
We cannot bisect more!
```

Here is a minimal config with which I can reproduce the problem:

```
set realname = 'Scott Kostyshak'
set imap_user = 'scott.kostyshak@gmail.com'
set imap_pass = `gpg --use-agent --quiet --batch -d ~/.mdp/per.gpg`

set folder = "~/.mail"

set smtp_url = "smtp://scott.kostyshak@smtp.gmail.com:587/"
set smtp_pass = $imap_pass

set spoolfile = +INBOX
```

## NeoMutt Version

```
NeoMutt 20200320-39-f49faa
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.0-42-generic (x86_64)
ncurses: ncurses 6.1.20190803 (compiled with 6.1.20190803)
libidn: 1.33 (compiled with 1.33)
OpenSSL: OpenSSL 1.1.1c  28 May 2019
libnotmuch: 5.2.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua -lz4 +meta -mixmaster +nls +notmuch +openssl +pgp +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead -zlib -zstd 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Is your email local (maildir) or remote (IMAP)?

Maildir (although I can also reproduce with IMAP)

**Comment by flatcap** [comment]
Please can you give branch [[devel/folding]](https://github.com/neomutt/neomutt/tree/devel/folding) a try.

**Comment by scottkosty** [comment]
Tested and works well. I no longer see the issue. Thank you for fixing it!
