### ISSUE TITLE
Website page for New Mail feature lists closed issue #20 as known bug

### ISSUE THREAD

**Issue by jlmuir** [neomutt/neomutt#223]
The [website page for the New Mail feature](https://www.neomutt.org/feature/new-mail) lists issue #20 as a known bug, but I think it should not list that since the issue has been fixed and closed.  (Sorry to not create a pull request for this, but I couldn't easily figure out where the source for that page is.)

**Comment by flatcap** [comment]
> the issue has been fixed and closed

Well spotted.

> I couldn't easily figure out where the source for that page is.

hehe, the source is [doc/manual.xml.head](https://github.com/neomutt/neomutt/blob/neomutt/doc/manual.xml.head#L11487-L11498)
The DocBook source is compiled into the manual and then converted to a webpage.

**Comment by flatcap** [comment]
Fixed in 5544fe5
