### ISSUE TITLE
cannot pipe </dev/null for message body

### ISSUE THREAD

**Issue by noahrama** [neomutt/neomutt#2243]
## Expected Behaviour
i should be able to:
mutt -s 'test' email@email.com </dev/null
## Actual Behaviour
when i pipe </dev/null, it fails

## Steps to Reproduce
mutt -s 'test' email@email.com </dev/null
with version > NeoMutt 20191207

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded from NeoMutt 20191207

## NeoMutt Version
latest
NeoMutt 20200320
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.6.2-arch1-2 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.13.1
GnuTLS: 3.6.12
libnotmuch: 5.2.0
hcache backends: kyotocabinet, gdbm, lmdb
hcache compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +lz4 +meta -mixmaster +nls +notmuch -openssl +pgp +sasl
  +smime +sqlite +start_color +sun_attachment +typeahead +zlib +zstd
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

## Extra Info
Linux Archlinux 5.6.2-arch1-2 #1 SMP PREEMPT Sun, 05 Apr 2020 05:13:14 +0000 x86_64 GNU/Linux

**Comment by gahr** [comment]
The regression was introduced by https://github.com/neomutt/neomutt/commit/b113e9e986330992d06a6470f4b1e6423d76864b#diff-c24730921dd546803ed551b31edd2cb0R2170 - if we can't read at least one byte from stdin, we fail. @flatcap why? :)

**Comment by flatcap** [comment]
Issue #2138 led me to fixes #2143 and #2177 

They wanted NeoMutt to fail rather than send an empty email.
You want NeoMutt to send an empty email rather than failing.

Hmm...

**Comment by flatcap** [comment]
I've been carefully re-reading the code and trying some experiments.
Unfortunately, I can't distinguish between the two cases:
- Failed `xdg-open` (with no terminal)
- CLI NeoMutt using `/dev/null`

The first case, caused by a mis-configuration, sends out an empty email.
I'd like to avoid this, if possible.

Using `/dev/null`, has a reasonable use-case, e.g. sending automated notifications, but it also has a simple workaround:
```sh
echo | neomutt -s "subject" user@example.com
```

I'll add an error message to make this clearer.
