### ISSUE TITLE
NeoMutt slow on sending mails

### ISSUE THREAD

**Issue by ichirou2910** [neomutt/neomutt#2248]
Hi devs. Firstly thank you for making this awesome app. Now that I can stay in my terminal and not have to switch to a browser to check and answer mails. While my experience with Neomutt is good overall, there is this thing that annoys me a bit, which is **mail sending speed.**
My account is gmail (in case it's related to the problem). I wrote a simple mail, basically "I'm using mutt. It's great". Just that, and it took 1 minute to send successfully, which is just too slow! On my browser it just sent right away. Is there anything I can do to improve this? I actually don't mind if the difference is small, but this is just to big.

## Expected Behaviour
Mutt sends the message right away

## Actual Behaviour
Took about 1 minute to send the mail

## Steps to Reproduce
Send a simple mail. Mine just contains 1 line to test.

## How often does this happen?

- Always

## When did it start to happen?

- Since I started using NeoMutt

## NeoMutt Version

```
NeoMutt 20200320
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.6.2-arch1-2 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.13.1
GnuTLS: 3.6.12
libnotmuch: 5.2.0
hcache backends: kyotocabinet, gdbm, lmdb
hcache compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls
 --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr
/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +lz4 +meta -mixmaster +nls +notmuch -openssl +pgp +sasl
  +smime +sqlite +start_color +sun_attachment +typeahead +zlib +zstd
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

## Extra Info

* Operating System and its version
Arch Linux
* Were you using multiple copies of NeoMutt at once?
No
* Were you using 'screen' or 'tmux'?
Yes
* Is your email local (maildir) or remote (IMAP)?
IMAP

**Comment by scottkosty** [comment]
I have not experienced this issue with remote IMAP (or local) usage of NeoMutt.
Have you used a previous version of NeoMutt (or Mutt) where you did not see this problem? Or is this the first time you're using NeoMutt?

I agree, 1 minute is too long and not expected for short messages.

Also, it might be helpful to post output form using `neomutt -d <level>` (after double-checking there is nothing private in the log).

**Comment by gahr** [comment]
Are you using smtp or sendmail?

**Comment by ichirou2910** [comment]
Thanks for the response guys
@scottkosty Which level should I put there? I tried putting 1 and [here](https://pastebin.com/J1p3cfLM) is the result (sent another test mail)
@gahr I use SMTP

**Comment by flatcap** [comment]
Please can you try that again with `neomutt -d6`
We just need the bit between "Sending message..." and "Mail sent".
**Note**: please check there's no personal info in the log, before posting.

**Comment by ichirou2910** [comment]
Hi guys, so I tried things again. Then I found the problem. It's not neomutt but rather the internet connection :disappointed: I contacted the ISP and they refreshed the bandwidth for me and now neomutt sends mail immediately as expected. Really sorry for the trouble guys. I'm closing this issue.

**Comment by scottkosty** [comment]
@ichirou2910 no problem! Glad you got things figured out. Thanks for keeping us updated.
