### ISSUE TITLE
How to configure proper utf-8 support?

### ISSUE THREAD

**Issue by agowa338** [neomutt/neomutt#2249]
Hi, I've problems configuring proper utf-8 support.

I set charset to "utf-8" and now unicode is no longer shown as "???" but instead as hex e.g. \342\232\240 instead of ⚠.

If I change the pager to "more" or "less" it is also shown properly. How do I configure the inbuild pager to render unicode properly?

**Comment by flatcap** [comment]
Hmm... that's odd.
Please can you paste the output of: `neomutt -v` and `locale`

Also, save this test mailbox: https://flatcap.org/mutt/test.mbox
And try NeoMutt with zero config:

`neomutt -n -F /dev/null -f test.mbox`

**Comment by agowa338** [comment]
I renamed my .neomutt folder to .neomutt2 (for zero config)
And than with your file and command I get:

![image](https://user-images.githubusercontent.com/2544867/78892666-11160800-7a6a-11ea-8614-cf677247647d.png)
![image](https://user-images.githubusercontent.com/2544867/78892701-22f7ab00-7a6a-11ea-9333-03810adc9462.png)

**Comment by flatcap** [comment]
>  Please can you paste the output of: `neomutt -v` and `locale`

**Comment by agowa338** [comment]
Runing these commands using a clean configuration I suppose?

`neomutt -v`:
```
NeoMutt 20200320
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.5.13-arch2-1 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.13.1
GnuTLS: 3.6.12
libnotmuch: 5.2.0
hcache backends: kyotocabinet, gdbm, lmdb
hcache compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +lz4 +meta -mixmaster +nls +notmuch -openssl +pgp +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead +zlib +zstd 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```
and
`locale`:
```
LANG=en_US.UTF-8
LC_CTYPE=C
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by gahr** [comment]
your LC_CTYPE is C. What happens if you set LC_ALL to en_US.UTF-8?

**Comment by agowa338** [comment]
Doesn't change anything, same result.

**Comment by flatcap** [comment]
Did you **`export`** the variable?

If you do, then the locale will be given the new processes.
```sh
export LC_ALL=en_US.UTF-8
neomutt
```

You can check the settings by running `locale` again.

Alternatively, you can set the value for just NeoMutt:
```sh
LC_ALL=en_US.UTF-8 neomutt
```

If I change my `LC_CTYPE` to `C`, I see exactly the same as you.

**Comment by agowa338** [comment]
Ok, you're right that fixes it, apparently while trying to debug I've added "de_DE.UTF-8" to another option and that causes the same error as long as "locale-gen" hasn't been run.
So by trying to diagnose this issue I accidentally introduced another bug that caused the same problem.
