### ISSUE TITLE
can't specify --prefix with --lua

### ISSUE THREAD

**Issue by howlett** [neomutt/neomutt#2251]
## Expected Behaviour
./configure behaves the same way when --prefix is sued when searching for lua

## Actual Behaviour
./configure fails to find lua even when it is found without --prefix

I couldn't build neomutt or install in the desired directory - even with DEST_DIR

## Steps to Reproduce
./configure --prefix $HOME/usr --lua

## How often does this happen?

- Always

## When did it start to happen?

as far as I can tell with regressing the git tags, since configure has been supported? at least 2017 timeframe.

## NeoMutt Version

Tried various tags, including latest.
``## Extra Info

* Operating System and its version - Linux debian testing
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? Doesn't matter.

**Comment by flatcap** [comment]
There are separate option library paths, try `--with-lua=path`

I can't remember the reason for the separation, something to do with how some distros perform their builds (maybe :-)

**Comment by howlett** [comment]
I don't want a lua path, it's taking the lua path from --prefix and is unable to find lua which is installed in the regular system directory

**Comment by flatcap** [comment]
We already search in a LOT of places (due to all the different distro layouts).
Curently, it searches (relative to the --prefix)
```
Checking for include/lua53/lua.h...no
Checking for include/lua5.3/lua.h...no
Checking for include/lua-53/lua.h...no
Checking for include/lua-5.3/lua.h...no
Checking for include/lua/lua.h...no
Checking for include/lua.h...no
Checking for include/lua52/lua.h...no
Checking for include/lua5.2/lua.h...no
Checking for include/lua-52/lua.h...no
Checking for include/lua-5.2/lua.h...no
Checking for include/lua/lua.h...no
Checking for include/lua.h...no
```

Where are your lua headers/libraries?

**Comment by howlett** [comment]
Okay, I'm not being clear.  When I don't use --prefix, lua is found.  When I do use --prefix lua is not found as it seems the lua_prefix is set to the value passed with --prefix.  This is just debian testing by the way.

> {tags/20200320//neomutt} $ ./configure --prefix=$HOME/usr --lua
Host System...x86_64-pc-linux-gnu
Build System...x86_64-pc-linux-gnu
C compiler... cc  -O2 -g -Wall
C++ compiler... c++  -O2 -g -Wall
Build C compiler...cc
Checking for stdlib.h...ok
Checking whether the C compiler accepts -std=c99...yes
Checking for install...ok
Checking for sendmail...no
Checking for minix/config.h...not found
Checking for sys/types.h...ok
Checking for sys/param.h...ok
Checking endian...little
Checking for sys/types.h...(cached) ok
Checking if -D_FILE_OFFSET_BITS=64 is needed...no
Checking for signal.h...ok
Checking for sys_siglist...ok
Checking for ioctl.h...not found
Checking for sys/ioctl.h...ok
Checking for syscall.h...ok
Checking for sys/syscall.h...ok
Checking for sysexits.h...ok
Checking for clock_gettime...ok
Checking for fgetc_unlocked...ok
Checking for futimens...ok
Checking for getaddrinfo...ok
Checking for getsid...ok
Checking for iswblank...ok
Checking for mkdtemp...ok
Checking for strsep...ok
Checking for utimesnsat...not found
Checking for vasprintf...ok
Checking for wcscasecmp...ok
Checking libs for gethostent...none needed
Checking libs for setsockopt...none needed
Checking libs for getaddrinfo_a...-lanl
Checking for struct timespec...ok
Checking for struct stat.st_atim.tv_nsec...ok
Checking for xsltproc...ok
Checking for DocBook DTDs...yes
Checking for inotify_add_watch...ok
Checking for inotify_init...ok
Checking for inotify_rm_watch...ok
Checking for inotify_init1...ok
Checking for sys/inotify.h...ok
Checking for include/lua53/lua.h...no
Checking for include/lua5.3/lua.h...no
Checking for include/lua-53/lua.h...no
Checking for include/lua-5.3/lua.h...no
Checking for include/lua/lua.h...no
Checking for include/lua.h...no
Checking for include/lua52/lua.h...no
Checking for include/lua5.2/lua.h...no
Checking for include/lua-52/lua.h...no
Checking for include/lua-5.2/lua.h...no
Checking for include/lua/lua.h...no
Checking for include/lua.h...no
Error: Unable to find Lua
Try: 'configure --help' for options

vs

> {tags/20200320//neomutt} $ ./configure --prefix=$HOME/usr
Host System...x86_64-pc-linux-gnu
Build System...x86_64-pc-linux-gnu
C compiler... cc  -O2 -g -Wall
C++ compiler... c++  -O2 -g -Wall
Build C compiler...cc
Checking for stdlib.h...ok
Checking whether the C compiler accepts -std=c99...yes
Checking for install...ok
Checking for sendmail...no
Checking for minix/config.h...not found
Checking for sys/types.h...ok
Checking for sys/param.h...ok
Checking endian...little   
Checking for sys/types.h...(cached) ok
Checking if -D_FILE_OFFSET_BITS=64 is needed...no
Checking for signal.h...ok
Checking for sys_siglist...ok
Checking for ioctl.h...not found
Checking for sys/ioctl.h...ok
Checking for syscall.h...ok
Checking for sys/syscall.h...ok
Checking for sysexits.h...ok
Checking for clock_gettime...ok
Checking for fgetc_unlocked...ok
Checking for futimens...ok
Checking for getaddrinfo...ok
Checking for getsid...ok
Checking for iswblank...ok
Checking for mkdtemp...ok
Checking for strsep...ok
Checking for utimesnsat...not found
Checking for vasprintf...ok
Checking for wcscasecmp...ok
Checking libs for gethostent...none needed
Checking libs for setsockopt...none needed
Checking libs for getaddrinfo_a...-lanl
Checking for struct timespec...ok
Checking for struct stat.st_atim.tv_nsec...ok
Checking for xsltproc...ok
Checking for DocBook DTDs...yes
Checking for inotify_add_watch...ok
Checking for inotify_init...ok
Checking for inotify_rm_watch...ok
Checking for inotify_init1...ok
Checking for sys/inotify.h...ok
Checking for GNU gettext in /home/jedix/usr...no
Checking for GNU gettext in libintl...no
Checking for GNU gettext in libc...yes
Checking for bind_textdomain_codeset...ok
Checking for msgfmt...ok
Checking for msgmerge...ok
Checking for xgettext...ok
Checking libs for tgetent...no
Checking libs for tgetent...(cached) -ltinfo
Checking libs for waddnwstr...-lncursesw
Checking libs for bkgdset...none needed
Checking libs for curs_set...none needed
Checking libs for meta...none needed
Checking libs for start_color...none needed
Checking libs for typeahead...none needed
Checking libs for use_default_colors...none needed
Checking for use_extended_names...ok
Checking for ncursesw/ncurses.h...ok
Checking for iconv() in /home/jedix/usr...no
Checking for iconv() in libiconv...no
Checking for iconv() in libc...yes
Checking whether iconv() needs const...no
Checking for stringprep.h...ok
Checking for idna.h...ok
Checking libs for stringprep_check_version...-lidn
Checking for idna_to_unicode_utf8_from_utf8...not found
Checking for idna_to_unicode_8z8z...ok
Checking for idna_to_ascii_from_utf8...not found
Checking for idna_to_ascii_8z...ok
Checking for idna_to_ascii_lz...ok
Checking for idna_to_ascii_from_locale...not found
Created Makefile from Makefile.autosetup
Created config.h
Created .clang_complete from .clang_complete.in
Summary of build options:
  Version:               20200320
  Host OS:               linux-gnu
  Install prefix:        /home/jedix/usr
  Compiler:               cc
  CFlags:                 -O2 -g -Wall -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR -I/home/jedix/usr/include
  LDFlags:               -L/home/jedix/usr/lib
  Libs:                  -lidn -lncursesw -ltinfo -lanl
  GPGME:                 no
  PGP:                   yes
  SMIME:                 yes
  Notmuch:               no
  Header Cache(s):
  Header Compression(s):
  Lua:                   no

**Comment by gahr** [comment]
What you want is an `—install-prefix` that doesn’t modify the (default) `—prefix used for search paths, right?

Only lua is failing in your case because the rest is found in libc, but you’d experience the same problem if you tried `—gpgpme`, `—lmdb`, or any other 3rd party dependencies not found in libc.

Is this a correct description?

**Comment by gahr** [comment]
So we use `--prefix` as a prefix for both *searching* and *installing*. The assumption is that you rarely want to have them different: in a chain of dependencies, you want the whole blocks to have the same prefix so the next one can find the previous one etc.

Please use `DESTDIR` as a prefix-of-the-prefix.

Edit: I thought I'd documented that somewhere. Please look at INSTALL.md, section Configure, just below the list of config options.
