### ISSUE TITLE
Can not attach key: gpgme_op_export_keys not supported

### ISSUE THREAD

**Issue by reox** [neomutt/neomutt#2254]
## Expected Behaviour

Be able to attach public key.

## Actual Behaviour

Give error message:

```gpgme_op_export_keys not supported```

## Steps to Reproduce

* attach public key
* boom

## How often does this happen?

- Always

## When did it start to happen?

I don't know exactly, pretty much tried it today for the first time.

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.0-4-amd64 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.13.1-unknown
libnotmuch: 5.2.0
hcache backends: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-bCiSXv/neomutt-20191207+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +sasl +smime
  -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

## Extra Info

* Debian bullseye/sid
* no
* no
* IMAP

I looked at the code and also passed commits, and it looks like the preprocessor define here:
https://github.com/neomutt/neomutt/blob/88aa4058f84db04120809c595dbb41257961f080/ncrypt/crypt_gpgme.c#L5472
was removed from several other locations. I could find only one other reference in the gpgme changelog, that this define is not necessary any more.
If this is actually not a bug and the define is still needed, please excuse my ignorance :)

**Comment by flatcap** [comment]
This is odd.

You're right that some of the `#ifdef`s were removed.  Rather than being scattered through the code, they were concentrated on the single call to the `gpgme_op_export_keys()` function.

But... There is a test in the build that checks for that function.
You should only see that error message if your gpgme libraries are really old, but they're not.
(we need that check, because some long-term-support distros **don't** have that function).

**Comment by reox** [comment]
Okay I see. Maybe I should file a bugreport in debian?

Indeed, if you look at the buildlog, it says it can not find the function: https://buildd.debian.org/status/fetch.php?pkg=neomutt&arch=amd64&ver=20191207%2Bdfsg.1-1.1&stamp=1585103877&raw=0
```
Checking for GPGMe...Checking for gpgme_op_export_keys...not found
1.13.1-unknown
```

**Comment by flatcap** [comment]
Thanks for investigating.

I've found the problem, it's a bug in NeoMutt's build script (since fixed).
This change should fix things:

```diff
     # RHEL6 doesn't have this function yet
-    cc-check-functions gpgme_op_export_keys
+    cc-check-function-in-lib gpgme_op_export_keys gpgme
```

Better still, would be to upgrade to NeoMutt 2020-03-20 :-)

**Comment by reox** [comment]
Nice! I hope that the maintainer uploads that soon ;)

**Comment by gahr** [comment]
I guess this can be closed?
