### ISSUE TITLE
Default S/MIME signature verification is insecure

### ISSUE THREAD

**Issue by pali** [neomutt/neomutt#2255]
When `crypt_use_gpgme` is turned off and when by default is `smime_verify_command` option is set to `openssl smime -verify -inform DER -in %s %C -content %f` then neomutt for S/MIME verification just print `Verification successful` without any information who signed email by which certificate or when certificate expire. Sender can sign email by totally different certificate and user of neomutt has no clue that such thing happened. Which is insecure.

## Expected Behaviour

Neomutt for S/MIME signature verification should print information who signed email and by which certificate. Similar like for PGP.

## Actual Behaviour

Only `Verification successful` or `Verification failure` is printed without information about certificate.

## Steps to Reproduce

Open any S/MIME signed email with `crypt_use_gpgme` turned off and with default `smime_verify_command` option.

## How often does this happen?

- Always

## When did it start to happen?

- Always

## NeoMutt Version

```
NeoMutt 20180716
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.19.0-8-amd64 (x86_64)
ncurses: ncurses 6.1.20181013 (compiled with 6.1.20180714)
libidn: 1.33 (compiled with 1.33)
hcache backends: tokyocabinet

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 7.3.0-25' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Debian 7.3.0-25) 

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/lib --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-oDMtzm/neomutt-20180716+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3  -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  +gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua +meta 
  +mixmaster +nls +notmuch -openssl +pgp +sasl +smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

## Extra Info

Creating a new script called `openssl-smime-verify` with following content:
```bash
#!/bin/bash
signature="$1"
content="$2"
shift 2
openssl smime -verify -inform DER -in "$signature" $@ -content "$content"
ret="$?"
exec 0<> <(:)
openssl x509 -in "/proc/$$/fd/0" -subject -issuer -email -dates -noout >&2 &
openssl smime -verify -inform DER -in "$signature" $@ -content "$content" -noverify -signer "/proc/$$/fd/0" -out /dev/null 2>/dev/null
exec 0>&-
exit "$ret"
```
and setting `smime_verify_command` to `openssl-smime-verify %s %f %C` fixes this problem.

After `Verification successful` line there is also information about subject, issuer email addresses and validity of certificate. E.g.:

```
Verification successful
subject=...CN = ...
issuer=...CN = ...
email1
email2
notBefore=...
notAfter=...
```

So user of neomutt will see which certificate signed S/MIME email. Similar like for PGP signed emails.

Please fix default option of `smime_verify_command` to something more secure like my above `openssl-smime-verify` script as current default value is really insecure.

**Comment by gahr** [comment]
I thought the idea of S/MIME is that you rely on a CA to authenticate a certificate, so you don't have to look at it and "manually figure out" whether you deem it ok (secure) or not.

I understand that you'd like to see more info regarding a certificate, but what is "insecure" in now showing details about a cert?

Do you "show certificate details" each time you open a web page over HTTPS, or do you rely on your CA root certs to do that for you?

We accept pull requests :)

**Comment by pali** [comment]
> I thought the idea of S/MIME is that you rely on a CA to authenticate a certificate, so you don't have to look at it and "manually figure out" whether you deem it ok (secure) or not.

And is this idea correct?

Why then gpgme implementation of S/MIME shows this information?

> Do you "show certificate details" each time you open a web page over HTTPS, or do you rely on your CA root certs to do that for you?

No, but web browser checks that hostname matches email address in certificate

> but what is "insecure" in now showing details about a cert?

That I do not see a check that e.g. sender address matches to email address in certificate.

**Comment by gahr** [comment]
The verification of the sender should be displayed in the pager. Is that not the case?

**Comment by gahr** [comment]
You'd either get `S/MIME signature successfully verified` or `S/MIME certificate owner does not match sender`.

**Comment by pali** [comment]
> You'd either get `S/MIME signature successfully verified` or `S/MIME certificate owner does not match sender`.

See `Actual Behaviour` in my first post: Only `Verification successful` or `Verification failure` is printed without information about certificate.

There is no string `S/MIME signature successfully verified`. This is why I reported this issue.

**Comment by gahr** [comment]
Do you mean in the status bar, as a message, or before the body of the email in the pager? I mean the latter.

**Comment by pali** [comment]
Before the body of the email.

But now I see what you mean, it is in status bar which is overwritten by pressing any arrow/navigation key.

**Comment by Neustradamus** [comment]
Any news on it?

**Comment by gahr** [comment]
No, I think I forgot to close this: the information is there, although not where @pali would have expected it. I think we can of course do better in providing this sort of info and patches are always welcome, but I don't think there's a bug here.

If you feel like it, please open an "enhancement" issue detailing what you'd like to see where.

**Comment by gahr** [comment]
Oh, I forgot to mention: there's little chance anybody here will focus on anything non gpgme at the moment.

**Comment by pali** [comment]
I do not know if you have not caught it I have already provided fix for it in description.
