### ISSUE TITLE
Add an option to automatically collapse all threads

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#226]
Let's discuss whether we want an option to automatically collapse all threads when entering a folder. This would save us from the ubiquitous, slow, and randomly failing `folder-hook . exec collapse-all`.

**Comment by gahr** [comment]
Naïve implementation based on my scarce knowledge of curs_main... feel free to comment and improve :)

**Comment by toogley** [comment]
Could you please add documentation/explaning comments for your changes?

**Comment by gahr** [comment]
My changes involve factoring out code into collapse_all and adding three calls to this new function. Not sure how much / what is not self-explanatory.

**Comment by toogley** [comment]
I think i understood most of it (after a short look), but i guess i would have to invest more time to understand it better. I think this time could be reduced if the code is also explained in comments and such.

Additionally, at least the above would make sense for the general behavior and its parameters, as i thought we [wanted](https://github.com/neomutt/neomutt/issues/199) to introduce code documentation via doxygen later.

**Comment by gahr** [comment]
Yeah, all I did is move a block of code inside a new function. I haven't paid to much attention of what was inside the block, but I could go through it and try to add a few comments here and there if needed.
