### ISSUE TITLE
notmuch and mail_check

### ISSUE THREAD

**Issue by tamis-laan** [neomutt/neomutt#2267]
I'm using neomutt in conjunction with notmuch. I have set a number of virtual mailboxes by following the notmuch guide in the neomutt documentation. When I startup neomutt everything works fine, the virtual mailboxes show up correctly, etc etc. However when I receive new mail it doesn't show in neomutt. I have set mail_chek to 60 seconds but the virtual mailboxes do not update. 

Is this by design or am I missing something?

**Comment by scottkosty** [comment]
I don't use Notmuch in the way that you are using it so I won't be of much help. But for the virtual mailboxes to update, I suppose that NeoMutt would need to run "notmuch new" after receiving new mail, or perhaps NeoMutt would just have to allow you to set a hook that does that, and then NeoMutt would need to detect (e.g., with inotify) if the NotMuch data base changed.

I don't think the above helps much, but I log those thoughts just in case they help a non-Notmuch NeoMutt expert understand your desired workflow.

**Comment by roccoblues** [comment]
Hi, I'm currently cleaning up some older issues here. Can you still reproduce this with the latest version? Thanks!
