### ISSUE TITLE
sidebar not indented with multiple imap accounts

### ISSUE THREAD

**Issue by reox** [neomutt/neomutt#2272]
I have two IMAP accounts set up using folder hooks and two configuration files like this:

```
source ~/.mutt/account_a
folder-hook $folder 'source ~/.mutt/account_a
source ~/.mutt/account_b
folder-hook $folder 'source ~/.mutt/account_b
macro index,pager <f2> '<sync-mailbox><refresh><enter-command>source ~/.mutt/account_a<enter><change-folder>!<enter><check-stats>'
macro index,pager <f3> '<sync-mailbox><refresh><enter-command>source ~/.mutt/account_b<enter><change-folder>!<enter><check-stats>'
```

The account files look like this:
```
unmailboxes *

set folder    = 'imap://user@imapserver/'
set spoolfile = $folder
set record    = "+INBOX.Sent"
set postponed = "+INBOX.Drafts"
set trash     = "+INBOX.Trash"


account-hook $folder "set imap_user=user; set imap_pass=1234"

send-hook . 'set from=user@domain'

set signature="~/.mutt/signature_a"

color status black blue

set imap_check_subscribed=yes
mailboxes $folder
```

So far, all the switching works fine. However I have troubles getting the indentation of the mailbox work correctly. Furthermore, it is different between the two servers.
The first server has the folders sorted like seen in the file above.
The other server however uses a folder structure like this:
```
set spoolfile = $folder
set record    = "+Sent"
set postponed = "+Drafts"
set trash     = "+Trash"
```

While The indentation works for server A, it does not for server B. Here, I only see a flat hierarchy of all folder (including subfolders). If I add `mailbox $folder` to server B, I see INBOX twice, while the first one is marked as active. If I remove the line, I still see all folders (and only one INBOX) but there is no active mailbox marked in the sidebar.
I have the feeling that `imap_check_subscribed` might cause issues here and double checked that the mailboxes are indeed subscribed. Now, the real funny part is, if I go into the mailbox overview and press `s` on a mailbox to subscribe it, it will be added to the sidebar - correctly intended! But if I switch accounts and go back to server B, all is gone and I see the flat list again.
Btw: Can you see in neomutt which mailboxes are subscribed? I just checked that in roundcube right now...

I do not really want to add all imap mailboxes to the `mailboxes` manually, there are quite a few...
Is there anything that could work?

**Comment by reox** [comment]
Uhhm that is odd... I played around with it and noticed that if I not shorten the mailboxes in the sidebar, it would print `imap://servername/` and not `imap://username@servername`.
Which remembered me at this issue here: https://github.com/neomutt/neomutt/issues/2175
So if I specify `set folder = `imap://servername/` for account B but not for A it works!
Looks like there is some inconsistency?! Btw I'm using neomutt 20191207

**Comment by jindraj** [comment]
Yes this is kind of "known issue" Yesterday we've met 2 people on IRC with the same problem. Also discussed [here](https://unix.stackexchange.com/a/580454/85046) on unix.stackexchange.com

**Comment by reox** [comment]
Okay, I changed it to `$imap_user` but this leads to neomutt asking for the password, because basically I have now a dependcy loop:

```
account-hook $folder "set imap_user=user; set imap_pass=1234"
set folder    = 'imap://$imap_user@imapserver/'
```
As the folder is not set yet, $imap_user is empty, and can not be used in the folder variable...
So that does not really work.

Yet another question: Why exactly do I need the `folder-hook` in this configuration? Because in the macro, the file is sourced anyways... If I remove the lines, everything still works but is even faster, as the file is not sourced twiced.

And yet another question regarding the indentation: I have at account B some mailboxes also under INBOX. i.e. INBOX.foo, INBOX.bar. However, they are not displayed indented under INBOX but somewhere else.
I fiddled with the sorting mode, but that does not solve it.
Or is this also related to the bug with the indentation level and usernames in folders?

**Comment by jindraj** [comment]
The others didn't use account-hooks for settings. But instead bound macros to source files so it was a little different setup. 

Ad indentation. Do you have
```ini
set sidebar_folder_indent = yes
set sidebar_indent_string = "  "
set sidebar_delim_chars   = "/."
```

**Comment by reox** [comment]
> Ad indentation. Do you have
> 
> ```ini
> set sidebar_folder_indent = yes
> set sidebar_indent_string = "  "
> set sidebar_delim_chars   = "/."
> ```

yes I have that.
Right now, the indentation works if I switch to account A and back to B.
However on A it never works right now... But I'm also in the version were the fix was not applied yet.

**Comment by jindraj** [comment]
is there any change within these configuration directives right after neomutt fresh starts and after you change an account?

**Comment by reox** [comment]
Not that I'm aware of. All I change is in the account settings, which I have posted in the very first entry

**Comment by flatcap** [comment]
Bisected to 8431155f4cb314e29929e275b11fefa676bf01b8
