### ISSUE TITLE
20200417 update breaks quoting in notmuch URIs

### ISSUE THREAD

**Issue by rustbuckett** [neomutt/neomutt#2275]
## Expected Behaviour

Virtual Mailboxes should load based on notmuch URI for folders with spaces is the path. For example: 
`"Sent Mail"             'notmuch://?query=folder:"gmail/Sent Mail"'`

## Actual Behaviour

Folder does not load and switching to it in the sidebar causes crash. Running `neomutt -d 2` reveals:
`<E> nm_mbox_check_stats() failed to parse notmuch url: notmuch://?query=folder:"gmail/Sent Mail"`
Changing the line in my config to:
`"Sent Mail"             "notmuch://?query=folder:gmail/Sent%20Mail"`
will load the folder and not generate and error, but the contents are not correct. Changing other URIs in this fashion has very mixed results, the most common being an empty folder/result. Escaping the spaces with '\' does not work either.

Neomutt said that it core dumped, but I don't know where to find it.

## Steps to Reproduce

Use a mix of single and double quotes to define notmuch URI for folder: query with spaces in the path. 

## How often does this happen?

This happens every time I open neomutt. Reverting to 20200320 loads virtual mailboxes as expected.

## When did it start to happen?

This started happening when I upgraded to 20200417.

## Extra Info

I'm using Arch Linux with maildir and notmuch 0.29.3. I'm happy to provide additional information upon request.

**Comment by gahr** [comment]
The URL parsing code parses the string `notmuch://?query=folder:gmail/Sent Mail` just fine, so I guess it's a matter of how to set that in the config.

Two things I'm perplexed about:

* This should work, as far as the URI code is concerned:
`'notmuch://?query=folder:gmail/Sent Mail'`
* This should work too, and produce the exact same result:
`'notmuch://?query=folder:gmail/Sent%20Mail'`

Can anybody with notmuch-foo please look at this?

**Comment by rustbuckett** [comment]
Would enclosing the URI in single quotes versus double quotes make a difference? When I changed the space to %20, I also changed the quotes from single to double.

**Comment by gahr** [comment]
We became stricter on the URIs we accept, and the query `query=folder:"gmail/Sent Mail"` contains invalid characters for that particular part of an URI.

The workaround is to pct-encode the query:

```
named-mailboxes "Sent Mail" notmuch://?query=folder%3A%22gmail%2FSent%20Mail%22
```

Agreed, this is ugly. Maybe we could have the notmuch backend pct-encode queries before they're passed to url to parse?

**Comment by gahr** [comment]
With #2286 I can define the same query in both ways:

```
named-mailboxes gmailsent1 'notmuch://?query=folder%3A%22%5BGmail%5D%2FSent%20Mail%22'
named-mailboxes gmailsent2 'notmuch://?query=folder:"[Gmail]/Sent Mail"' 
```
