### ISSUE TITLE
Issue when there is hash tag '#' in mailto: link

### ISSUE THREAD

**Issue by OliverLew** [neomutt/neomutt#2276]
This happpens only with neomutt but not mutt, tested with the latest release.

For example, start a simple email with

```
neomutt "mailto:a@b?subject=#"
```

## Expected Behaviour

Neomutt will start with recipient `a@b` and subject `#`

## Actual Behaviour

Neomutt start with this:
```
To: mailto: , a@b?subject=#
```

It goes wrong as long as `#` is in the `mailto:` link, no matter which part it is in.

## Steps to Reproduce

See above, it should be reproducible.

## How often does this happen?

- Always

<details>

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

- When I changed my config
  Can you narrow down **what** you changed?

## NeoMutt Version

```
NeoMutt 20200417
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.28-2-lts (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.13.1
GnuTLS: 3.6.13
libnotmuch: 5.2.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +lz4 +meta -mixmaster +nls +notmuch -openssl +pgp +sasl
  +smime +sqlite +start_color +sun_attachment +typeahead +zlib +zstd
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
  Arch Linux
* Were you using multiple copies of NeoMutt at once?
  No
* Were you using 'screen' or 'tmux'?
  No
* Is your email local (maildir) or remote (IMAP)?
  Does not matter here

</details>

**Comment by gahr** [comment]
So, technically speaking, this is not a valid URI. The pound terminates the query part and starts the fragment part, which we never use in NeoMutt. I am a bit reluctant to let the pound sneak into the query part.

The correct way to specify that URI is `mailto:a@b?subject=%23`, which will be parsed into a subject of `#`.

Will that work for you?

**Comment by OliverLew** [comment]
Thanks for the explanation and yeah I can accept that. Although I have to change my script which spawns neomutt.

So I guess it is the responsibility for web designers (since almost all mailto links exist on web pages) to provide a strictly valid URI so that neomutt can work with it perfectly?

**Comment by gahr** [comment]
Yeah you do have a point indeed. I'm struggling to decide whether we'll ever need to support `scheme://host/?key1=val1&key2=val2#fragment` and parse `key2`'s value as `val2` instead of `val2#fragment`.

**Comment by gahr** [comment]
RFC6068 says:

"Therefore, fragment identifiers are meaningless, SHOULD NOT be used on 'mailto' URIs, and SHOULD be ignored upon resolution.  The character "#" in &lt;hfvalue&gt;s MUST be escaped as %23."

We think the cases where a pound sign happens unescaped in a mailto URI are few enough not to warrant a diversion from the specs in our parsing of URIs.
