### ISSUE TITLE
Folder names are encoded strange way for gmail in cyrillic

### ISSUE THREAD

**Issue by asm0dey** [neomutt/neomutt#2282]
I have my Gmail in russian and some folder are named in russian too, and they have extremely strange names:

```
=[Gmail]/&BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-/
=[Gmail]/&BB8EPgQ8BDUERwQ1BD0EPQRLBDU-/
```

and so on.
Is there any way to fix it?

**Comment by gahr** [comment]
It is expected that IMAP encodes characters outside the 7-bit range using a modified version of the base64 encoding algorithm.

However, as far as I could see, GMail supports the UTF-8 IMAP extension, so if you 

* have `imap_rfc5161` set to true (this is the default)
* have a utf-8 (ish) charset in your LC_ALL environment

you should receive UTF-8 names directly.

**Comment by gahr** [comment]
What's your locale setting? I suspsect it's some local cyrillic codepage? I can try to investigate what happens in such a case.

**Comment by asm0dey** [comment]
My locale is as following:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

and my `imap_rfc5161` is set to `yes`.

**Comment by gahr** [comment]
Can you try to set LC_ALL to something utf-8 too?

**Comment by asm0dey** [comment]
On what level should I do it? Will it be enough to run `LC_ALL=en_US.UTF-8 neomutt`?

**Comment by asm0dey** [comment]
Yep, it works on this level

**Comment by asm0dey** [comment]
Oops, not, sorry, didn't help.

**Comment by asm0dey** [comment]
![image](https://user-images.githubusercontent.com/1297282/79971377-e0d45d80-849c-11ea-9bc8-1d75751b4ac6.png)
Looks like this

**Comment by gahr** [comment]
What's `:set charset?` from within NeoMutt?

**Comment by gahr** [comment]
The only reason I can think of that we might end up not trying to decode an utf-7 string is that
1. urf-8 is not enabled in the session (hence the question above regarding `charset`
2. the response comes in as a literal string, which we don't try to unmunge

**Comment by gahr** [comment]
Can you please run neomutt -d 6 and provide the output ~/.neomuttdebug0 ?
Please remove any sensitive information, such as lines with AUTHENTICATE in them.

**Comment by asm0dey** [comment]
> What's :set charset? from within NeoMutt?

`charset="utf-8`

> Can you please run neomutt -d 6 and provide the output ~/.neomuttdebug0 ?

Here is it: https://gist.github.com/asm0dey/cb1a3c24d4d11715c0cab70ddcd6d635

**Comment by gahr** [comment]
I see you're using a local maildir which is sync'd with GMail using some external tool (offlineimap, mbsync?).

It's the tool's job to properly decode mailbox names when it syncs from IMAP. Not our fault here.

**Comment by asm0dey** [comment]
Yes, I'm using mbsync. Thank you for pointing to the problem.

**Comment by gahr** [comment]
https://sourceforge.net/p/isync/bugs/47/
