### ISSUE TITLE
Spoiled screen

### ISSUE THREAD

**Issue by em230418** [neomutt/neomutt#2287]
Hi, all!

Using outlook.com mail account. Bad mobile internet. I login in neomutt, do nothing, sometimes it reconnects (status bar saying Logging in...) after reconnect probably done this what happenes

## Expected Behaviour

I am able to navigate in messages.

## Actual Behaviour

I am NOT able to navigate in messages and screen shows this: http://i.imgur.com/BLc8XWr.png

## Steps to Reproduce

Login to outlook.com account, have messages there. Probably you don't need bad internet 'cos does connection timeout frequently on good internet.

## How often does this happen?

- Always

## When did it start to happen?

I was using mutt from debian stretch. https://packages.debian.org/stretch/mutt
It didn't have such bug.

Then I tried out neomutt from here, and compiled from sources.

## NeoMutt Version

```
NeoMutt 20200320
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.19.0-0.bpo.8-amd64 (x86_64)
ncurses: ncurses 6.0.20161126 (compiled with 6.0.20161126)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.12.0
GnuTLS: 3.5.8
libnotmuch: 5.2.0
hcache backends: tokyocabinet

Configure options: --gpgme --sasl --mixmaster --tokyocabinet --mixmaster --notmuch --prefix=~/.local --gnutls

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I~/.local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua -lz4 +meta +mixmaster +nls +notmuch -openssl +pgp +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead -zlib -zstd 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="~/.local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="~/.local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
Debian Stretch with backports

* Were you using multiple copies of NeoMutt at once?
No

* Were you using 'screen' or 'tmux'?
No. I am using i3.

* Is your email local (maildir) or remote (IMAP)?

IMAP.

**Comment by em230418** [comment]
As an addition. After screen gets spoiled, I can't quit using q button while I am able on "normal" screen.

**Comment by jindraj** [comment]
#2145 duplicate?
You can try
- to redraw using `ctrl-L` to be able to continue working with affected neomutt instance.
- or try flatcaps [tip](https://github.com/neomutt/neomutt/issues/2145#issuecomment-599065282) if it helps in the meantime until it's fixed

**Comment by gahr** [comment]
> #2145 duplicate?

Yes
