### ISSUE TITLE
Translating NeoMutt

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#229]
Do **you** speak a language other than English?
Would you like to help other speakers of that language?

As we added [new features](https://www.neomutt.org/feature.html) to NeoMutt, our translation files have become out-of-date.

- https://www.neomutt.org/translate

The translations are broken down into simple sentences or phrases.
They are categorised as:

- **Complete**: A correct translation exists
- **Fuzzy**: The translation needs checking (but probably correct)
- **Incomplete**: No translation exists
    
You **do not** need any coding skills to help with the translations.

If you are interested, leave a comment, or contact: Rich Russon <rich@flatcap.org>

Thanks :-)

**Comment by flatcap** [comment]
## Translations Started

- **German** -- Andre and Andy
- **French** -- Guillaume

Thanks guys.  I'll update this list as we get more volunteers :-)

**Comment by mgedmin** [comment]
I cannot commit to doing a full translation, but I would like to at least fix some problems with **Lithuanian**.
E.g. currently it's nearly impossible for me to disable PGP signing, since the "PGP (e)ncrypt, (s)ign, sign (a)s, (b)oth, s/(m)ime or (c)lear?" prompt is untranslated, but the response letters ("esabmc") *are* translated (to "usablp"?!).

**Comment by flatcap** [comment]
@mgedmin Thanks, that would be brilliant!

You'll just need to edit `po/lt.po` -- https://www.neomutt.org/dev/translate-strings

IIRC, there are about 15 prompts and variations for the 'letter' menus.
They're the trickiest part of the translations to get right.
They're all commented, now, but if you have any problems just ask.

> I cannot commit to doing a full translation

Not a problem.  If you can translate 13 strings then you'll overtake Galician on the [leaderboard](https://www.neomutt.org/translate) :-)

For tasks like this, I often use 'TV time' (programmes that don't require my full attention).

I've just updated the [translate](https://github.com/neomutt/neomutt/tree/translate) branch. Please make your changes there.
