### ISSUE TITLE
Latest master slows down hcache immense

### ISSUE THREAD

**Issue by riesebie** [neomutt/neomutt#2290]
Running  05ed8b457b6384ae7e4e95ce49db462e551db9d2 with lmdb slows down header-cache a lot even after rebuilding the hcache dir.

**Comment by flatcap** [comment]
Hmm... I don't see it.
With that build and about ~33K emails
- Build cache: ~6s
- Read from cache: <0.5s

**Comment by riesebie** [comment]
Well I've had to switch to the folders a few times to get the old speed back. Looks like the cache isn't ready after first initialization.
