### ISSUE TITLE
Regressions in sidebar rendering since 2020-04-24

### ISSUE THREAD

**Issue by maximbaz** [neomutt/neomutt#2293]
Relevant piece of config:

```
set folder = "~/.mail/maximbaz"
set mbox_type = Maildir
set spoolfile = "+INBOX"
set record = "+Sent"
set postponed = "+Drafts"
set trash = "+Trash"

unmailboxes *
unvirtual-mailboxes *

mailboxes =INBOX =Archive/2019 =Drafts =Sent =Junk =Trash
```

## Expected Behaviour

In all previous versions including 2020-04-17:

![image](https://user-images.githubusercontent.com/1177900/80236191-18890400-865b-11ea-9a35-19ad017ee644.png)

## Actual Behaviour

In 2020-04-24:

![image](https://user-images.githubusercontent.com/1177900/80236101-f3949100-865a-11ea-8661-ade51fff5403.png)

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20200424
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.6.6-arch1-1 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.13.1
GnuTLS: 3.6.13
libnotmuch: 5.2.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +lz4 +meta -mixmaster +nls +notmuch -openssl +pgp +regex 
  +sasl +smime +sqlite +start_color +sun_attachment +typeahead +zlib +zstd 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Arch Linux
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? Maildir

**Comment by riesebie** [comment]
It's a new feature. To get your old behavior you need to `set sidebar_short_path=yes`

**Comment by maximbaz** [comment]
Ooh, sorry! I checked release notes but haven't realized there are any new features in this release. Might be worth adding a hint about this 😉 Thanks in any case, closing!

**Comment by maximbaz** [comment]
By the way `sidebar_short_path` doesn't bring exactly the same behavior, I used to have `Archive/2019` but now it shows up as `2019` only - it's fine for me, but might confuse some people.

**Comment by riesebie** [comment]
> Ooh, sorry! I checked release notes but haven't realized there are any new features in this release. To be honest, it seems to be an overhauled feature ;-)

**Comment by gahr** [comment]
I guess the sidebar logic will need to undergo anothe cycle of polishing - some other time.

**Comment by grawlinson** [comment]
Chiming in to say that this issue should be re-opened due to a functionality regression.

My sidebar now lists an absolute path for each mailbox, and none of `sidebar_short_path` or `sidebar_component_depth` work.

**Comment by maximbaz** [comment]
Could you post the details here as in an issue template, your relevant part of config, expected and actual behavior? I can try to reopen and we will let maintainers respond and close the issue again if they deem necessary.

**Comment by grawlinson** [comment]
_**Note**: Account names and folder count have been truncated for simplicity._

Relevant configuration:

```
mailboxes `find ~/.mail/ -type d -name cur | sort | sed -e 's:/cur/*$::' -e 's/ /\\ /g' | tr '\n' ' '`
```

Also note that it is currently 2140, and I'm usually in bed by 2100 so I apologise if this is incomplete. Please let me know if something is missing from configuration or behaviour.

## Expected Behaviour

Sidebar should look like this:
```
account1/INBOX    |
account2/INBOX    |
account3/INBOX    |
```

## Actual Behaviour

Sidebar now looks like this:
```
/home/user/.mail/acc|
/home/user/.mail/acc|
/home/user/.mail/acc|
```

With `set sidebar_short_path`, it turns out like this:

```
INBOX          |
INBOX          |
INBOX          |
```

Setting `sidebar_component_depth` to any integer value of (0,1,2,3) does not change anything, it still looks like the above INBOX codeblock.

**Comment by mvdan** [comment]
I am seeing the same breakage as @grawlinson. I used to have some sidebar entries like `Inbox` and `../foo/Inbox`. Now I can only have them as absolute paths (far too long) or as just basenames (making the two examples from earlier duplicates).

**Comment by mat813** [comment]
Mmmm, I see the same breakage, the man page says : `By default the sidebar will show the mailbox's path, relative to the $folder variable.`  but it is not shortened relative to, the full path is always displayed.

**Comment by bapt** [comment]
I confirm the analysis by @mat813, I got the problem with imaps, gmail, and local folder

**Comment by graywolf** [comment]
Same issue here. Given config file:

```
named-mailboxes "+--- Main --------+" ~/.mutt/div_main
mailboxes "=inbox"
mailboxes "=arch"

named-mailboxes "+--- Phabricator -+" ~/.mutt/div_phab
mailboxes "=maniphest.interest"
mailboxes "=maniphest.other"
mailboxes "=maniphest.arch"

named-mailboxes "+--- Gitlab ------+" ~/.mutt/div_gitlab
mailboxes "=gitlab"
mailboxes "=gitlab.arch"

named-mailboxes "+--- Other -------+" ~/.mutt/div_other
mailboxes "=sent"
mailboxes "=drafts"

named-mailboxes "+--- Other-other -+" ~/.mutt/div_other-other
mailboxes "=spam"
mailboxes "=trash"
```

Produces this under ..17:

```
+--- Main --------+        0
inbox                      4
arch                    2777
+--- Phabricator -+        0
maniphest.interest     59/59
maniphest.other        70/73
maniphest.arch         73512
+--- Gitlab ------+        0
gitlab                     0
gitlab.arch             1074
+--- Other -------+        0
sent                     175
drafts                     0
+--- Other-other -+        0
spam                       0
trash                      0
```

But under ..24 (*with* `set sidebar_short_path=yes`):

```
+--- Main --------+        0
/home/dir/.mails/user.name_4
/home/dir/.mails/user.na2777
+--- Phabricator -+        0
/home/dir/.mails/user.n59/59
/home/dir/.mails/user.n70/73
/home/dir/.mails/user.n73512
+--- Gitlab ------+        0
/home/dir/.mails/user.name_0
/home/dir/.mails/user.na1074
+--- Other -------+        0
/home/dir/.mails/user.nam175
/home/dir/.mails/user.name_0
+--- Other-other -+        0
/home/dir/.mails/user.name_0
/home/dir/.mails/user.name_0
```

Sadly, that is not really useable :/

**Comment by mattpallissard** [comment]
I'm seeing the same thing. folders changed from

```
my.folder.name                  0/0 |
```
to
```
imap://user@fqdn/my.folder.name 0/0 |
```

setting sidebar_short_path alone doesn't seem to render the desired result.

```
name                            0/0 |
```

I do have a workaround. As I have '.' delimited imap boxes so I was able to hack around it with

```
set sidebar_short_path=yes
set sidebar_delim_chars="/"
```

This is less than ideal though, as mixing delimiters is no longer possible.

**Comment by Austin-Ray** [comment]
I pushed a small fix that worked locally after limited test. Would anyone be willing to try a build from the `devel/issue-2293` branch?

Using this minimal config (`test/test` is just an empty file):
```
set folder="~/mail/austin@austinray.io"
set sidebar_visible=yes
unmailboxes *
mailboxes =INBOX =test/test
```
My sidebar looked like:

![image](https://user-images.githubusercontent.com/1640737/80552744-8ef86f80-8995-11ea-9712-2995fa328112.png)

**Comment by mattpallissard** [comment]
That seems to do the trick for me.  Thanks @Austin-Ray.

**Comment by bapt** [comment]
I can confirm it works for me

**Comment by grawlinson** [comment]
Just tested the devel/issue-2293 branch, works for me!

I really appreciate you spending your time on this, Austin. :)

**Comment by mgedmin** [comment]
Another user here, same problem.  devel/issue-2293 fixes the issue for me.
