### ISSUE TITLE
Mnemoize mutt_yesorno's return value on abort (Ctrl-G)

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#231]
`int mutt_yesorno (const char *msg, int def)` can return three values:

`-1` -> if the user aborts the prompt using Ctrl-G (currently not mnemoized)
`  0` -> if the user answers no (`MUTT_NO`)
`  1` -> if the user answers yes (`MUTT_YES`)

This issue is to keep track of the work on mnemoizing `-1` as `MUTT_ABORT`.

**Comment by d-k-c** [comment]
This function is called mutt_yesorno, and not mutt_yesornoorabort; I think we should try to make functions consistent with their names. To me, it would make more sense to try to get rid of the abort answer altogether. There are only a few places where abort is handled differently than 'yes' or 'no', I think it's worth fixing them.

**Comment by gahr** [comment]
The biggest challenge you'll face if you want to go down that path is that you'll have to invert the meaning of a few questions. This breaks finger memory.

**Comment by gahr** [comment]
@flatcap Ready for merging.
