### ISSUE TITLE
Solarized color scheme not working

### ISSUE THREAD

**Issue by hasufell** [neomutt/neomutt#2313]
## Expected Behaviour

Solarized color scheem working.

## Actual Behaviour

Brownish/greyish colors.

![mutt_solarized](https://user-images.githubusercontent.com/1241845/80927614-36631100-8d9f-11ea-9252-e1ce425bbfd2.png)

## Steps to Reproduce

1. Use the following config: https://gist.github.com/hasufell/fe227d5dfb0b5f2de63b98f190abc6a7#file-gistfile1-txt
2. Start neomutt

## How often does this happen?

- Always

## NeoMutt Version

https://gist.github.com/hasufell/fe227d5dfb0b5f2de63b98f190abc6a7#file-gistfile2-txt

## Extra Info

* OS: Exherbo
* Terminal: sakura (with the following [config](https://gist.github.com/hasufell/5816c3235fb4626e83de4d9d4ea44267))
* No tmux

**Comment by hasufell** [comment]
Same with slang:

![mutt_color_slang](https://user-images.githubusercontent.com/1241845/81404241-4da25580-9135-11ea-8d3b-ce278808e091.png)

**Comment by nkakouros** [comment]
I have the same issue. Using konsole.

I tried the 16 bit versions of solarized (from [here](https://github.com/altercation/mutt-colors-solarized)) and they work fine.

**Comment by hasufell** [comment]
> I tried the 16 bit versions of solarized (from here) and they work fine.

Tried that too, doesn't work either.

**Comment by hasufell** [comment]
I stopped trying.
