### ISSUE TITLE
set auto_subscribe is not functional

### ISSUE THREAD

**Issue by nobrowser** [neomutt/neomutt#2321]
## Expected Behaviour

I was trying to use the documented `set auto_subscribe=yes` command in my configuration file to be able to reply to mailing list messages conveniently, without necessarily committing to subscribe to them.

I often follow a list for a while in a lurk mode to see if it is worth being on it. Sometimes it isn't, so I have to undo whatever setup I did to be on the list; undoing a specific neomutt entry for the list would just add to the chore.

This has never before been necessary - it just worked even _without_ an additional variable `auto_subscribe`. I could accept the variable, if I were able to set it once and forget it; but apperently I misunderstood the doc, and there is still something else I must do.

## Actual Behaviour

I entered a folder that I dedicated to a list; I selected a message and I verified that it had a `List-Post:` header. I hit `L` for a list reply, and neomutt says "No mailing lists found".

## Steps to Reproduce

As above

## How often does this happen?

- Always on a list message

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

20180716 (with backported patches)

## NeoMutt Version

```
NeoMutt 20200501
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.19.0-8-amd64 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.35 (compiled with 1.35)
storage: tokyocabinet

Configure options: --prefix=/home/linuxbrew/.linuxbrew/Cellar/neomutt/20200501 --disable-doc --disable-inotify --disable-pgp --disable-smime --disable-nls --tokyocabinet --with-ui=ncurses

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR -I/home/linuxbrew/.linuxbrew/Cellar/neomutt/20200501/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn -inotify 
  -locales_hack -lua -lz4 +meta -mixmaster -nls -notmuch -openssl -pgp +regex 
  -sasl -smime -sqlite +start_color +sun_attachment +typeahead -zlib -zstd 
MAILPATH="/var/mail"
PKGDATADIR="/home/linuxbrew/.linuxbrew/Cellar/neomutt/20200501/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/home/linuxbrew/.linuxbrew/Cellar/neomutt/20200501/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
debian buster, but neomutt installed with linuxbrew

* Were you using multiple copies of NeoMutt at once?
no

* Were you using 'screen' or 'tmux'?
no

* Is your email local (maildir) or remote (IMAP)?
local maildir

### Extra extra info

I run neomutt with `-n`, so there isn't a chance of the linuxbrew config interfering with mine.

**Comment by gahr** [comment]
The reason is #2320.

**Comment by nobrowser** [comment]
But @gahr, I said I have added this to my config:

set auto_subscribe=yes

that is how this issue is different from @2320

If something else is needed to get this to work, it is not documented

**Comment by gahr** [comment]
Doesn't the patch for 2320 fix your use case too? The problem wasn't auto_subscribe but the fact that we couldn't parse the address in List-Post

**Comment by nobrowser** [comment]
I see, thanks.  I had not read your comment on #2320 before posting mine, sorry. Lately I've started to assume the worst before it happens :-(
