### ISSUE TITLE
Editing a message "forgets" all  tags

### ISSUE THREAD

**Issue by nobrowser** [neomutt/neomutt#2333]
## Expected Behaviour

Delete a bunch of messages that I had pre-tagged

## Actual Behaviour

Before going ahead with the deletion, I edited (with `e`) an unrelated message, in a different thread of the same folder. All the messages that I'd tagged still had a `*` next to them. But when I typed `; d`, Neomutt said "No tagged messages" - and still kept the `*` next to the messages.

## Steps to Reproduce

As above

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
20180716

## NeoMutt Version

```
NeoMutt 20200501
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.19.0-9-amd64 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.35 (compiled with 1.35)
storage: tokyocabinet

Configure options: --prefix=/home/linuxbrew/.linuxbrew/Cellar/neomutt/20200501 --disable-doc --disable-inotify --disable-pgp --disable-smime --disable-nls --tokyocabinet --with-ui=ncurses

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR -I/home/linuxbrew/.linuxbrew/Cellar/neomutt/20200501/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn -inotify 
  -locales_hack -lua -lz4 +meta -mixmaster -nls -notmuch -openssl -pgp +regex 
  -sasl -smime -sqlite +start_color +sun_attachment +typeahead -zlib -zstd 
MAILPATH="/var/mail"
PKGDATADIR="/home/linuxbrew/.linuxbrew/Cellar/neomutt/20200501/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/home/linuxbrew/.linuxbrew/Cellar/neomutt/20200501/etc"

```

* Operating System and its version
Debian buster

* Were you using multiple copies of NeoMutt at once?
No

* Were you using 'screen' or 'tmux'?
No

* Is your email local (maildir) or remote (IMAP)?
Local

**Comment by flatcap** [comment]
Please can you give [[devel/tagged]](https://github.com/neomutt/neomutt/tree/devel/tagged) a try.
It works for me and I think it's the right fix.
I'll have another look in the morning.

**Comment by nobrowser** [comment]
> Please can you give [[devel/tagged]](https://github.com/neomutt/neomutt/tree/devel/tagged) a try.
> It works for me and I think it's the right fix.
> I'll have another look in the morning.

Yup, in a quick test it's all fixed.  Thanks for getting to it so swiftly.
