### ISSUE TITLE
Macro + folder-hook :: Macro does not always expand

### ISSUE THREAD

**Issue by lcrockett** [neomutt/neomutt#2335]
# Description

Using `folder-hooks` in combination with local `Maildir` mail store format. When having a `my_` variable set using a `folder-hook` it is possible to have that variable expand when triggering a macro using `<enter-command>`. However, using the same setup and when triggering a macro using `<save-message>` the macro is not expanded.

# Expected behaviour

I would expect both macros to be expanded upon getting called. Additionally, I would expect both macros to behave the same when it comes to expanding variables at 'runtime'.

# Actual behaviour

##  A) Both macros get expanded OK

1) ~/.neomuttrc
```muttrc
folder-hook google-username-w9b/* set my_miauw = "google-username-w9b"
folder-hook google-username-w9b/* macro index a "<save-message>+$my_miauw/Archives<return><sync-mailbox><check-stats>"

folder-hook microsoft-username-a0m/* set my_miauw = "microsoft-username-a0m"
folder-hook microsoft-username-a0m/* macro index a "<save-message>+$my_miauw/Archives<return><sync-mailbox><check-stats>"

macro index x '<enter-command>echo "DEBUG :: mailbox-$my_miauw-listing :: DEBUG"<enter>'
```

2) Start NeoMutt
2.a) First mailbox by default (using `set spoolfile`) is `google-username-w9b`
3) Trigger macro `x` -> expands OK
4) Trigger macro `a` -> expands OK

##  B) Only macro `x` is expanded OK

1) ~/.neomuttrc
```muttrc
folder-hook google-username-w9b/* set my_miauw = "google-username-w9b"
folder-hook microsoft-username-a0m/* set my_miauw = "microsoft-username-a0m"

macro index a "<save-message>+$my_miauw/Archives<return><sync-mailbox><check-stats>"
macro index x '<enter-command>echo "DEBUG :: mailbox-$my_miauw-listing :: DEBUG"<enter>'
```

2) Start NeoMutt
2.a) First mailbox by default (using `set spoolfile`) is `google-username-w9b`
3) Trigger macro `x` -> expands OK
4) Trigger macro `a` -> expands NOT_OK

# Expected behaviour

I am looking for a setup in which I only have to set a 'dynamic' macro once and have it re-use a `my_` variable

**Comment by flatcap** [comment]
Thanks for the detailed bug report, @lcrockett.

When the `folder-hook` is used, it's treated as a line of config which is getting the variable expansion.
In the macro, we're just feeding keystrokes into NeoMutt and `<save-message>` doesn't do the variable expansion.

I've created a fix for 'save', but it will probably need applying to lots of commands to be consistent.

**Comment by lcrockett** [comment]
Perfect, i'll be happy to test as soon as a new Homebrew sourced NeoMutt version becomes available.

I agree with your last point, `<save-message>` is one of many where a fix for proper variable expansion would likely be desired.

**Comment by flatcap** [comment]
Update: I spent a day analysing all the functions and all the user entry in NeoMutt.
There are [61 functions](https://gist.github.com/flatcap/db27f2e07f1d2029e6ce62b9d32375f1) that will probably need altering to be consistent.
Unsurprisingly, this is going to take more thought (and time), to do right.

**Comment by lcrockett** [comment]
Cheers on the update, that is much appreciated. For the meantime i'll go with external scripts that return NeoMutt commands upon execution, leveraging the `setenv` directive to pass on the same information I was trying to use by setting it via the `set` directive. It gets the job done, for now.

I might be experiencing a similar issue in terms of behaviour using the `send-hook` directive, i'll create a separate issue for that one though.

**Comment by roccoblues** [comment]
Hi, I'm currently cleaning up some older issues here. Can you still reproduce this with the latest version? Thanks!
