### ISSUE TITLE
passwords with quotes are maimed when put in config file

### ISSUE THREAD

**Issue by karlsebal** [neomutt/neomutt#2337]
## Expected Behaviour

Login succeeds even with a password containing quotes in config file.

## Actual Behaviour

NeoMutt kills the quote in `set imap_pass=` and `account-hook $folder imap_pass=`

_Giving the password manually succeeds._

## Steps to Reproduce

- put the line `imap_pass='pass"word'` or `imap_pass="pass\"word"` into .neomuttrc for an account.
- start neomutt with debug level 6
- you will see account_hook messages with and mutt_socket_write_d() without the quote.

## How often does this happen?

- Always when trying to obtain the password 

## When did it start to happen?

- When I upgraded
  Which version did you use to use?
  20171215

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.0-29-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.13.1-unknown
libnotmuch: 5.2.0
hcache backends: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster
--sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-WmwApX/neomutt-20191207+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +sasl +smime
  -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"


## Extra Info

* Operating System and its version:  Ubuntu 20.04 LTS
* Were you using multiple copies of NeoMutt at once? No.
* Were you using 'screen' or 'tmux'? No.
* Is your email local (maildir) or remote (IMAP)? Remote.

**Comment by karlsebal** [comment]
problem seems to be the external program (`secret-tool`). So my report is faulty and I am closing it…

**Comment by flatcap** [comment]
Great! (sort of :-)
Thanks for letting us know.

**Comment by cyphar** [comment]
I have the same issue and it's not a problem with an external tool. Mutt mangles passwords with quotes.

```
% grep smtp_pass .mutt/muttrc-personal
set smtp_pass=`keepassxc-helper "/Shared/Email/Mailbox"`
% keepassxc-helper "/Shared/Email/Mailbox"
K6d@FD{4.Ai:"!#TGu-BBR]3ggpdze}y.6bPgW(W
% pmutt -n -Q smtp_pass
set smtp_pass = "K6d@FD{4.Ai:!#TGu-BBR]3ggpdze}y.6bPgW(W"
```

Note that the quote was stripped after parsing.

**Comment by karlsebal** [comment]
Reinvestigating the issue: 

I actually have to 

```set smtp_pass="'`password-providing-program-or-script `'"```

where in earlier versions the singe quotes had not been necessary. This does not follow the behaviour described [in mutt’s manual](http://www.mutt.org/doc/manual/#ex-backtick-dblquotes) because quotes should remain uninterpreted.

As described above, mutt_account_hook interprets correctly `mutt_account_hook()     set imap_user=user@for.example imap_pass=spam"eggs` but mutt_socket_write does not: `mutt_socket_write_d() 6> a0002 LOGIN "user@for.example" "spameggs"^M`

`$` is retained as expected. Putting single quotes inside the double quotes is a workaround.
