### ISSUE TITLE
Allow Mutt to read multiple config files at startup

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#234]
Currently, Mutt will only read one config file from the command line.

**Example**:

```
mutt -F apple.rc -F banana.rc -F cherry.rc
```

Only `cherry.rc` is read and acted upon.

**Comment by ThomasAdam** [comment]
Yup -- and the resultant patch should make use of the same mechanism that `source` allows for in `.muttrc`.

**Comment by d-k-c** [comment]
I am factorizing config lookups in mutt. Once this is done, I'll do this

**Comment by guyzmo** [comment]
looks like that has been stalled for quite some time, and because it was easy, I just did it ☺
