### ISSUE TITLE
[Feature Request] Thunderbird-like sorted threads

### ISSUE THREAD

**Issue by BlackLotus** [neomutt/neomutt#2342]
Threaded view with sorting like thunderbird.
The default threading in thunderbird (View->Sort by->Threaded, Date, Ascending) is perfect for me.
Newest messages are at the top of the inbox.
Threads start with the oldest message and the bottom message of the thread is the newest message.
Right now the default neomutt behaviour is that single answers are orderd from newest to oldest.
Here are a few neomutt settings that come close, but are not quite right.
```
set sort=threads
set sort_aux = date
````
## What needs to change in NeoMutt?
Probably just another option for sort_aux.

## Have you tried any alternative methods?
I tested every combinaton of thread and reverse-thread with these options
```
#set sort_aux = reverse-date
#set sort_aux = reverse-last-date
#set sort_aux = reverse-last-date-received
#set sort_aux = reverse-date-received
#set sort_aux = date
#set sort_aux = last-date
#set sort_aux = last-date-received
#set sort_aux = date-received
```
## Additional Info
Here an example how thunderbird sorts a thread
![thunderbird-threads](https://user-images.githubusercontent.com/20885/81870095-7f704d80-9575-11ea-9abb-0aaa078be205.png)

**Comment by gahr** [comment]
Do `sort = reverse_threads` together with `sort_aux = last_date` kind of give you what you're looking for?

**Comment by Austin-Ray** [comment]
@gahr : no, that makes threads appear upside-down (new message at top, thread root at bottom).

From a logical view, sorting seems broken.

With `sort=reverse-threads; sort_aux=date`, I'd expect threads to be newest to oldest and messages _under_ the thread root to be sorted by date; however, the `reverse` option just seems to flip the index entries so the thread root is at the bottom.

**Comment by BlackLotus** [comment]
I found some comments that suggest that it's known to be broken (like the wrongly reversed order of the maildir), but won't be fixed to don't break working setups. That's why I suggest adding a new sorting method that acts "correctly" like thunderbird.

**Comment by cwfoo** [comment]
Similar question from the Mutt mailing list: [sort/sort_aux different for sorting threads and sorting within threads](https://marc.info/?l=mutt-dev&m=115758586608122) (2006-09-06).

**Comment by ebblake** [comment]
(salvaging the most relevant parts of #2970):
## What needs to change in NeoMutt?
We need a new config variable to make inter-thread sorting orthogonal from intra-thread sorting.  I propose that the existing sort_aux be used to specify only intra-thread sorting, then we add:
set sort_thread = ...
to control inter-thread sorting.  For backwards compatibility, sort_thread will default to thread, which is a special case meaning use sort_aux to control inter-thread sorting.

Then, my example would become:
set sort=thread sort_thread=last-date sort_aux=date
```
08:00 [PATCH 0/2] cover letter A
08:01 +>[PATCH 1/2] foo
09:00 |  +>Re: [PATCH 1/2] late review, with suggestion for fix
08:02 +>[PATCH 2/2] bar
08:30 |  +>Re: [PATCH 2/2] early review, this one's good
08:31 +>Re: [PATCH 0/2] - looks like a good start, but I'm still reviewing
07:00 patch proposal
07:30 +>Re: patch proposal - go for it
08:03 +>Re: patch proposal - see v1 for implementation
10:04   +>Re: patch proposal - see v2 for implementation
10:00 [PATCH v2 0/2] cover letter B
10:01 +>[PATCH v2 1/2] fixed foo
10:15 | +>Re: [PATCH v2 1/2] yep that's better
10:02 +>[PATCH v2 2/2] bar
10:30 +>Re: [PATCH v2 0/2] series is good to go
```

**Comment by ebblake** [comment]
With #2991, your desired configuration should be
```
set sort=threads
set sort_thread=reverse-last-date
set sort_aux=date   # this one is already the default
```

**Comment by ebblake** [comment]
With the latest updates to #2991, your desired configuration should now be
```
set use_threads=yes
set sort=reverse-last-date
set sort_aux=date   # this one is already the default
```
