### ISSUE TITLE
Issues with old macros in the new version

### ISSUE THREAD

**Issue by Surgams** [neomutt/neomutt#2346]
Hi there,
I updated from version neomutt-20180716 to verion neomutt-20200501 on FreeBSD. Everything seems to work fine except those macros. They don't work properly now.

```
# move messages
 macro index s "<enter-command> macro browser \\<return\\>'<select-entry><sync-mailbox>'<enter><save-message>?"

# copy messages
macro index 'c' '<change-folder>?<change-dir><home>^K=<enter>'
# delete message and sync
macro index,pager p "<delete-message><sync-mailbox>" "purge messages"

# move to trash
macro  index D "<save-message>=Trash\n<sync-mailbox>"
```

Like the purge one it deletes  messages and mark them as 'D' but they don't go from the display, same for move messages, the macro does move the messages but won't remove it from inbox display. The only way to update the display is by changing folder and return back to my original folder

My question is what I need to change in those macros to work now?

**Comment by gahr** [comment]
> Like the purge one it deletes messages and mark them as 'D' but they don't go from the display

This is the behaviour if `delete` is set to `no`. What does `:set delete?` tell you?

**Comment by bluecub** [comment]
Hi @gahr 
it returns delete="yes"

**Comment by roccoblues** [comment]
Hi, I'm currently cleaning up some older issues here. Can you still reproduce this with the latest version? Thanks!
