### ISSUE TITLE
Who is "formatstrings-size"?

### ISSUE THREAD

**Issue by nabijaczleweli** [neomutt/neomutt#2348]
The manpage references it a bunch, saying "see formatstrings-size", but none of `formatstrings-size`/`formatstrings`/`format strings` searches there gave me much. GitHub search gave me just the manpage text, Google likewise.

**Comment by flatcap** [comment]
It's referring to the ["29.6 **Bytes size display**"](https://neomutt.org/guide/configuration#formatstrings-size).
That string is a link name and isn't visible.

**Comment by nabijaczleweli** [comment]
I'm generally unfamiliar with how the manpage is generated, so pardon my ignorance, but would it make sense to either include the URL inline or, for example, "formatstrings-size: <URI>" in the footer?
