### ISSUE TITLE
'mutt -D' chokes on status-color config

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#235]
`mutt -D` reads the user's config files and displays all the variables.

Unfortunately, it gets confused when it reads config for the [status-color](https://www.neomutt.org/feature/status-color) feature.

To demonstrate the bug, create `sample.rc`

```
# sample.rc
color status default blue 'inbox'
```

Then run:

```
mutt -n -F sample.rc -D
```

Result: "Error in sample.rc, line 2: inbox: unknown command"

**Comment by gahr** [comment]
@flatcap Please disregard the nonsense in [30bb17d], was never supposed to be committed. [461deba] is a workaround.

**Comment by gahr** [comment]
@flatcap The workaround is mergeable.
