### ISSUE TITLE
POLL: Code Tidying

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#2350]
Your thoughts are welcomed...

## Empty `for` / `while`

Currently the code has ~50 empty `for` or `while` loops.
They look like:

```c
for (; list[i]; i++)
  ;
some_function();
```

`clang-format` ensures that the `;` is on a separate line.
I've created some alternatives.

### Blank line

Insert a blank line after the `;` to emphasise the loop.
See branch [[devel/nothing1]](https://github.com/neomutt/neomutt/tree/devel/nothing1)

```c
for (; list[i]; i++)
  ;

some_function();
```

### Comment

Add a comment to make the empty loop more visible.
See branch [[devel/nothing2]](https://github.com/neomutt/neomutt/tree/devel/nothing2)

```c
for (; list[i]; i++)
  ; // do nothing
some_function();
```

### Braces

Add `{}`s to make the empty loop visible.
See branch [[devel/nothing3]](https://github.com/neomutt/neomutt/tree/devel/nothing3)

```c
for (; list[i]; i++)
{
}
some_function();
```

**Comment by mschilli87** [comment]
```c
for (; list[i]; i++)
  /* do nothing */ ;
some_function();
```

or even

```c
for (; list[i]; i++)
{
  // do nothing
}
some_function();
```

The more explicit the better, IMHO.

Heck, if you ask me, both of the above would even benefit from also throwing in the extra line on top:

```c
for (; list[i]; i++)
{
  // do nothing
}

some_function();
```

This is not code golf after all. :wink:

**Comment by gahr** [comment]
+1 for explicit

```c
// in some .h
#define noop

// in some .c
for (; list[i]; i++)
  noop;
```

Then the usual clang-format can kick in and add braces if we want it to.

**Comment by jindraj** [comment]
+1 for braces with a comment inside.

**Comment by gahr** [comment]
The downside of having only a comment is that you can't put a breakpoint on it.

**Comment by flatcap** [comment]
> The downside of having only a comment is that you can't put a breakpoint on it.

It turns out you can't breakpoint a plain `;` either, even at `-O0`.

**Comment by flatcap** [comment]
> This is not code golf after all

True, but vertical screen space is limited, so I'd rather not waste 4 lines that do precisely nothing :-)

**Comment by gahr** [comment]
Then I suggest a `void noop(void);` that does nothing, so you can breakpoint on it :)

**Comment by flatcap** [comment]
Thanks for all your suggestions.

I'm going to combine the first two:
- A clear comment: `// do nothing`
- A little emphasis: a blank line

`clang-format` will compact the line if it's at the end scope.
