### ISSUE TITLE
Hide sensitive config

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#236]
When fixing a bug, or helping a beginner, it's useful to see their config.
However, some items shouldn't be made public.

This user performs a safe -C config dump:

```
mutt -C | grep imap | sort
```

```
imap_authenticators=""
imap_check_subscribed is unset
imap_delim_chars="/."
imap_headers=""
imap_idle is set
imap_keepalive=120
imap_list_subscribed is unset
imap_login=""
imap_passive is set
imap_pass="**XXX**"
imap_peek is set
imap_pipeline_depth=15
imap_servernoise is set
imap_user="**XXX**"
```

By tagging certain config items (in `init.h`) as "sensitive", they can be obscured.

**Comment by gahr** [comment]
@flatcap are you proposing a new -C option that would work like -D but with the sensitive config items obscured, or was -C a typo and you're proposing to modify -D's behavior?

In any case, I find this useful to the extent that we have a way to dump both the clear and the obscured versioned.

**Comment by flatcap** [comment]
> are you proposing a new option?

That was my original idea -- we don't want to break `-D`

However, now I see two possibilities:
- `-C` -- a new option with new behaviour
- `-D -S` -- an extra option meaning make the output 'safe'

Both methods seem fine to me.

**Comment by gahr** [comment]
I don't have a strong opinion either, just wanted to make sure I understood your proposal ;)

**Comment by gahr** [comment]
Ouch, we now have two possible implementations to chose from...

**Comment by guyzmo** [comment]
better have two than none ☺

cf my comments on your branch, my preference would be:

- to have `-DS` instead of `-C` ;
- to have a non `R_` prefixed name for the `R_SENSITIVE` flag.

@flatcap comments? ☺
