### ISSUE TITLE
send2-hook + push :: Push directive keeps NeoMutt hanging indefinitely

### ISSUE THREAD

**Issue by lcrockett** [neomutt/neomutt#2362]
# Description

Using `send2-hook` in combination with the `push` directive to change GPG signing behaviour. When configuring NeoMutt to execute a `push` based on a `send2-hook` NeoMutt hangs indefinitely while executing? the `push` directive. The `send2-hook` is triggered during a compose while changing the `To:` header based on a `~t` condition.

# Expected behaviour

I would expect the `push` directive to execute and return NeoMutt. With the configuration outlined below i'm trying to achieve recipient based GPG signing of email messages.

# Actual behaviour

##  NeoMutt hangs as soon as the `To:` header changes

1) ~/.neomuttrc
```muttrc
send2-hook "~t miauw@domain\\.tld" "push '<gpg-menu>s'"
```
2) Start NeoMutt
3) Compose message to `bla@domain.tld`
4) While in the `compose` menu, change the `To:` address
4.a) `:push <edit-to>`
4.b) `miauw@domain.tld`
5) NeoMutt executes the `push` directive and hangs. The menu doesn't change, the command stays put in the command line showing `To: miauw@domain.tld`
6) Hear the fans of the workstation spin up as NeoMutt starts eating up CPU cycles

**Comment by flatcap** [comment]
> `send2-hook "~t miauw@domain\\.tld" "push '<gpg-menu>s'"`

Ah!  I'll take a closer look later, but here's what I think's happening:

- Edit `To:`, which triggers the `send2-hook`
- `send2-hook` PGP signs email, which triggers the `send2-hook`
- `send2-hook` PGP signs email, which triggers the `send2-hook`
- ...

Your hook _might_ work if you add `!~g` (message isn't signed).

Fixing the problem means either:
- Stopping hooks triggering other hooks (a feature which some people may rely on)
- Detecting/breaking infinite loops in hooks (somehow)

**Comment by lcrockett** [comment]
Bingo, it turns out that indeed the hook was triggered repeatedly due to the missing `!~g` conditional. Adding it to the hook has resolved the issue and concluded that there's no real problem to resolve.

Using the `send-hook` i've been able to achieve (initial) sender based GPG signing:
`send-hook '! ~g ~f user@domain.tld' "push '<pgp-menu>s'"`

Cheers on your prompt suggestion !
