### ISSUE TITLE
group-alternatives creates an invalid email

### ISSUE THREAD

**Issue by jcdubacq** [neomutt/neomutt#2364]
Hello,

I am using NeoMutt 20191207 (debian unstable version as of early June 2020).

When I try to use group-alternatives while composing an email, I get an invalid email with messages such as  "Alternatives for "/tmp/user/1000/neomutt |multipa/alternativ, x-unkn, 134215500M]"
or even in the bottom status line : Can't stat (null): Bad address

How to get this behaviour?

First, I start neomutt with a 
LC_ALL=C neomutt -F /dev/null
m (for mail)
To: test
Subject: test
(jump into vi, edit file, record content "test", then hit :wq)
a (to attach file)
attach any file (html preferably, but I tried others, same result)
T (tag-entry)
up (previous-entry)
T (tag-entry)
& (group-alternatives)

...see problematic file with   1 Alternatives for "/tmp/user/1000/neomutt                                                                   [multipa/alternativ, x-unkn, 134212163M] displayed and Can't stat (null): Bad address in the bottom of the window.

If I can help, please tell me.

**Comment by jcdubacq** [comment]
I made a live demo here : [https://youtu.be/GITEPi8raSE](https://youtu.be/GITEPi8raSE)

**Comment by flatcap** [comment]
Thanks for the detailed bug report, @jcdubacq.
Sorry it's taken a while to get to you (we don't have many developers).

As far as I can tell, the email is actually OK.
I've sent a few emails with varying numbers and types of alternatives and they arrived looking OK.

As for the Compose screen, urgh!  Something's badly wrong.  I shall investigate.

**Comment by dcpurton** [comment]
I reported this to the Debian bug tracker before finding this bug report.

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=963542.

**Comment by roccoblues** [comment]
Hi, I'm currently cleaning up some older issues here. Can you still reproduce this with the latest version? Thanks!
