### ISSUE TITLE
Colour tagged emails

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#237]
Add a new colour for tagged emails (to make them easier to see).

This would have a higher priority than other colours, except for the indicator.

**Comment by a3nm** [comment]
Can't this be done simply using the existing configuration mechanism? E.g., "color index white green ~T"

**Comment by flatcap** [comment]
hehe, ah yes.  Well spotted!
I'll close this issue and we'll never speak of it again :-)
