### ISSUE TITLE
I found a security issue and don't know how to report it.

### ISSUE THREAD

**Issue by duesee** [neomutt/neomutt#2373]
Should I open an issue here or write an email to someone? I would also suggest to provide a security policy here.

**Comment by flatcap** [comment]
Thanks for your discretion :-)

I'm the maintainer of NeoMutt.
Please can you email me directly: rich@flatcap.org

>  I would also suggest to provide a security policy here.

Thanks.  I will do.

**Comment by flatcap** [comment]
I've added a (very) basic [security page](https://github.com/neomutt/neomutt/security/policy), and jazzed up the [issue templates](https://github.com/neomutt/neomutt/issues/new/choose).
