### ISSUE TITLE
Viewing calendar events

### ISSUE THREAD

**Issue by tom-doerr** [neomutt/neomutt#2374]
I'm trying to view calendar events in neomutt (` [text/calendar, base64, utf-8,... ]`), but neomutt doesn't display them.
Do I really have to install a plugin for that?
Installing a plugin takes time, adds complexity and makes it more difficult to switch to a new system.
Also I missed meetings because I wasn't aware that neomutt just doesn't display the calendar events.
Is there any way to use neomutt to view those calendar events?

**Comment by gahr** [comment]
You can view ical files directly in the pager. You need to:

1. add a mailcap entry that specifies `copiousoutput`
```
text/calendar; /bin/cat; copiousoutput;
```

2. add the mime type to auto_view
```
auto_view text/calendar
```
