### ISSUE TITLE
-Wformat-truncation warnings from alias.c

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#2378]
When compiling current master, I get the following:

```
alias/alias.c: In function ‘alias_create’:
alias/alias.c:474:45: warning: ‘%s’ directive output may be truncated writing up to 1023 bytes into a region of size 124 [-Wformat-truncation=]
  474 |     snprintf(prompt, sizeof(prompt), "[%s = %s] %s", alias->name, buf, _("Accept?"));
      |                                             ^~                    ~~~
alias/alias.c:474:5: note: ‘snprintf’ output 7 or more bytes (assuming 1030) into a destination of size 128
  474 |     snprintf(prompt, sizeof(prompt), "[%s = %s] %s", alias->name, buf, _("Accept?"));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
alias/alias.c:469:45: warning: ‘%s’ directive output may be truncated writing up to 1023 bytes into a region of size 124 [-Wformat-truncation=]
  469 |     snprintf(prompt, sizeof(prompt), "[%s = %s # %s] %s", alias->name, buf,
      |                                             ^~                         ~~~
alias/alias.c:469:5: note: ‘snprintf’ output 10 or more bytes (assuming 1033) into a destination of size 128
  469 |     snprintf(prompt, sizeof(prompt), "[%s = %s # %s] %s", alias->name, buf,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  470 |              alias->comment, _("Accept?"));
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I checked upstream mutt and don't see those warnings there, although I see many other compile warnings that NeoMutt does not have.

I can add information on configuration settings and compiler version, etc. if it would be helpful.

**Comment by flatcap** [comment]
Thanks, @scottkosty.

It's fairly harmless (and one I chose to ignore: `-Wformat-truncation=0` :-)
However, the last time I looked there were lots more of them.

> I checked upstream mutt and don't see those warnings there

I saw a few with upstream, too.

Do you have a second to work out a fix?
Cheers.

**Comment by scottkosty** [comment]
@flatcap thanks for the quick reply.

> It's fairly harmless (and one I chose to ignore: `-Wformat-truncation=0` :-)
> However, the last time I looked there were lots more of them.

Good to know!

> Do you have a second to work out a fix?

Not now but I'm happy to look at it later -> assigning to myself, although if anyone is interested, please go ahead :)

**Comment by flatcap** [comment]
Done

**Comment by scottkosty** [comment]
@flatcap Thanks. In the future when I have more time I'll try to propose fixes to warnings instead of opening issues.

**Comment by flatcap** [comment]
Great :-)
Also, I've always got some "easy" tasks that need doing - fixes, minor refactoring, etc

**Comment by scottkosty** [comment]
Sounds good! I hope to ask you for some of those tasks someday, but probably not anytime soon.
