### ISSUE TITLE
"configure --enable-all" build all features

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#238]
When `./configure` is run it checks to see if the user has the libraries installed to match the options.
This means it's safe to enable everything.

`configure` needs a `--enable-all` option that will enable everything it can (or a sensible default where there's a choice).

If you're not familiar with "autoconf", this is not the job for you.

**Comment by darnir** [comment]
How do we define a "sensible" default? For example we have multiple hcache backends. Which one of them is a "sensible" default?

**Comment by flatcap** [comment]
We want to please as many people as possible, as simply as possible.

For now, I think the "tokyocabinet" is the sensible choice.  It's been Mutt's default for years.

In the future, when @gahr finishes his work on [refactoring the hcache](https://github.com/neomutt/neomutt/issues/216), it may be "sensible" to choose a couple of backends, e.g. tokyo and lmdb.

How easy would it be to override our "default" behaviour?
e.g.
```
./configure --enable-all --without-tokyo --with-lmdb
```

**Comment by darnir** [comment]
We can default to Tokyo then.

About overriding the defaults, it can be done with a little bit of work. Shouldn't be too much though. I'll look into this when I find some time

**Comment by somini** [comment]
I'm using `--enable-everything` as commited in #264, but since I don't have all the 6 header dev libraries installed I have to manually `--without-HCACHE_BACKEND` each one.

I'm not familiar with autoconf, but is it possible to make it so that missing hcache backends are a warning, unless you are missing all of them?

**Comment by flatcap** [comment]
My original vision for the `--enable-everything` was to enable all the options for which there were libraries.  This would give developers an easy shortcut for building NeoMutt.  I liked this idea and I'd like to add more options to it.  Everything means everything!

However, some others argued, quite rightly, that different people would get different builds from the same single option.  This would make debugging harder.

Now that @darnir has done the hard work of sorting out `configure.ac`, adding options and changing the behaviour is much simpler.

Currently, `mutt -v` only shows: `Configure options: '--enable-everything'`

If can we change that to show an expanded list of all the options that are actually enabled, then we can reproduce the build exactly.

Then, the options don't need to be mandatory.

**Comment by somini** [comment]
That makes sense,thanks for the explanation .
