### ISSUE TITLE
browser search matches non-visible fields

### ISSUE THREAD

**Issue by mschiff** [neomutt/neomutt#2386]
## Expected Behaviour

When searching a mailbox in the mailbox browser, the cursor should jump to the first matching mailbox

## Actual Behaviour

The cursor jumps to a mailbox which is unrelated and does not match the search in any way

## Steps to Reproduce

In a folder-hook, do the following.

```
unmailboxes = *
named-mailboxes = +INBOX 'Mailbox INBOX' +Trash 'Mailbox Trash' +Junk 'Mailbox Junk' +INBOX/lists/dovecot 'Mailbox INBOX/lists/dovecot' +Drafts 'Mailbox Drafts' +Archiv 'Mailbox Archiv' +Sent 'Mailbox Sent'
```

Now in the mailbox browser, when searching for "Tra" it will jump to folder `Junk` when you press `<enter>`

(Yes, just prepending 'Mailbox ' before each name is stupid but I did this to test named-mailboxes because it seemed to me, that it does work like `named-mailboxes mailbox description [mailbox description ... ]` instead of `named-mailboxes description mailbox [description mailbox ... ]`, like written in the man-page. When using `'Mailbox INBOX' +INBOX`neomutt will show errors on startup)

## How often does this happen?

- Always

## When did it start to happen?

- When I changed my config to use named-mailboxes instead of mailboxes

## NeoMutt Version

This is a build from branch `devel/change-folder`

```
NeoMutt 20200619-3-319102
Copyright (C) 1996-2016 Michael R. Elkins und andere.
NeoMutt übernimmt KEINERLEI GEWÄHRLEISTUNG. Starten Sie 'neomutt -vv', um
weitere Details darüber zu erfahren. NeoMutt ist freie Software.
Sie können es unter bestimmten Bedingungen weitergeben; starten Sie
'neomutt -vv' für weitere Details.

System: Linux 5.7.1-gentoo-x86_64 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
GPGME: 1.13.1
OpenSSL: OpenSSL 1.1.1g  21 Apr 2020
libnotmuch: 5.2.0
storage: gdbm, lmdb

Configure options: --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/neomutt-99999999 --libdir=/usr/lib64 CCACHE=none --full-doc --enable-nls --enable-notmuch --enable-gpgme --disable-pgp --disable-smime --disable-bdb --enable-gdbm --disable-kyotocabinet --disable-qdbm --disable-tokyocabinet --disable-idn --disable-gss --enable-lmdb --disable-sasl --with-ui=ncurses --sysconfdir=/etc/neomutt --enable-ssl --disable-gnutls

Compilation CFLAGS: -O2 -pipe -march=skylake -O2 -pipe -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Standard Einstellungen:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Einstellungen bei der Kompilierung:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls +gpgme -gss +hcache -homespool -idn +inotify
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl -pgp +regex -sasl
  -smime -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc/neomutt"
```

## Extra Info

* Operating System and its version **Gentoo**
* Were you using multiple copies of NeoMutt at once? **yes**
* Were you using 'screen' or 'tmux'? **no**
* Is your email local (maildir) or remote (IMAP)? **local maildir**

**Comment by gahr** [comment]
> Yes, just prepending 'Mailbox ' before each name is stupid but I did this to test named-mailboxes because it seemed to me, that it does work like named-mailboxes mailbox description [mailbox description ... ] instead of named-mailboxes description mailbox [description mailbox ... ], like written in the man-page. When using 'Mailbox INBOX' +INBOXneomutt will show errors on startup)

No, it's the other way around. First the descriptive name, then the mailbox path. You're confused because `named-mailboxes` is a command, not a variable.

This
```
named-mailboxes = +INBOX 'Mailbox INBOX' +Trash 'Mailbox Trash'
```

assigns the name `=` to the mailbox `+INBOX`, 
assigns the name `Mailbox INBOX` to the mailbox `+Trash`
...
