### ISSUE TITLE
SubjectRX - Modify the subject (by regex) before display

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#239]
The original patch and discussion is on the mutt-dev mailing list:

- https://marc.info/?l=mutt-dev&m=147260817130074&w=2
- https://marc.info/?l=mutt-dev&m=147267959218226&w=2
- https://marc.info/?l=mutt-dev&m=147476590903228&w=2

Most mailing lists change the subject of the email.
Many users filter their mail into different folders.

This patch allows the user to modify the email's subject (saving space and reading time):

- Subject: [neomutt-devel] NeoMutt 2016-10-14 (1.7.1)

becomes:

- Subject: NeoMutt 2016-10-14 (1.7.1)

**Comment by nobrowser** [comment]
Heh.  This is probably the most asked-for feature in **all** MUAs, ever.  I myself asked about it on mutt-users shortly after adopting mutt.

I currently have a bad-ass perl script clean up that gunk at delivery time (I'll make it a gist, someday).  It is smarter than just removing the tag: whenever the tag removal leads to bunched up "Re:" and "Fwd:" it removes the extra occurrences of those, too.  I would probably not switch to the mutt based way unless it was as smart.

**Comment by nobrowser** [comment]
Also (sorry to come back to this): a good part of the problem here goes beyond reading.  The greater part is that the gunk accumulates when replying (depending on how stupid the mailing list manager is).  Consider:

Subject: my nice subject

Subject: [ML gunk] my nice subject

Subject: Re: [ML gunk] my nice subject

Subject: [ML gunk] Re: [ML gunk] my nice subject

Subject: Re: [ML gunk] Re: [ML gunk] my nice subject

et cetera et cetera ...

A change that just elides the gunk on display doesn't address this.

**Comment by guyzmo** [comment]
I actually don't consider the `[ML gunk]` as a problem, but as a feature to easily `limit` or `tag` my mail by mailing list once loaded in the browser, like a second tier query after notmuch's.

I actually have very few mailing lists where mails get ill formatted that way, hopefully the most used ones (mailman, sympa and googlegroups) avoid the repeating of the "gunk" pretty well IMHO.

Though, regarding adding a subject-regexp, even if my personal feeling is that it's far from a must have, I'm not opposed to include that. It's definitely not the kind of trivial task we could realistically offload to a script at some point (except if the day we implement lua hooks, we find out they're actually super-super-fast ☺).

Regarding reply, I believe neomutt has no role to play. If you want to clean the title, you can easily do that with a few lines of vim-script using a mail autocommand. Or if you want to fix it within mutt, you can always edit the mail using the `:edit` command. You can pass the mail through some `sed` or `python` magic that way.

**Comment by nobrowser** [comment]
> You can pass the mail through some sed or python magic that way.

That's what I already do, except on the original mail :)

I guess my position on this is, go ahead and add a display hook, but better not make me do any reconfiguration work when it lands, because it doesn't solve a problem I have.

**Comment by flatcap** [comment]
This patch has been adopted by upstream mutt.
It hasn't been merged into neomutt yet.
This can be closed when #334 is closed.
