### ISSUE TITLE
Save message and TAB completion.

### ISSUE THREAD

**Issue by ZaxonXP** [neomutt/neomutt#2395]
For some of the e-mails I have defined save hooks as I expect to receive the e-mails often. 

For other however I do: press `s`  then `?` then `/` then type the folder I want to save the e-mail to and then press `Enter` to find the folder, then another `Enter` to save the message.

Would it be possible to set up `neomutt` to do the following:
press `s` then type the part of the search folder, then press `TAB` key. This should display subset of mailboxes/folders to select or select the folder in case there is only one matching the search string.

Is this possible in the current version of the neomutt or it is a feature which has to be requested?

Kind regards,
Piotr

**Comment by gahr** [comment]
Would this do?
```
bind index s noop
macro index s <save-message>/partial/path<tab><tab>
```

**Comment by ZaxonXP** [comment]
I have to modify it to the:
```
bind index s noop
macro index s <save-message>/partial/path<tab><tab>/
```
And it will do the trick. :)

Many thanks!

Kind Regards,
Piotr

**Comment by gahr** [comment]
yup I forgot the ending slash: `macro index s <save-message>/partial/path/<tab><tab>`

**Comment by ZaxonXP** [comment]
I think I even like more the following:
```
macro index s <save-message>/home/user/Mail/GMail/<tab><tab>m
```
However I would like to know how to delete the standard mask or previously entered mask?

By default it is `!^\.[^.]`.

**Comment by ZaxonXP** [comment]
I think this will be my final:
```
macro index s <save-message>/home/user/Mail/GMail/<tab><tab>m^c
```

**Comment by flatcap** [comment]
> how to delete the standard mask or previously entered mask?

To clear the input, type <kbd>Ctrl-u</kbd>
In NeoMutt config that'll look like:
```
macro browser <f1> "m\Cu"
```
