### ISSUE TITLE
Out of memory error on sending

### ISSUE THREAD

**Issue by fourjay** [neomutt/neomutt#2396]
## Expected Behaviour
Send mail (via ouath bearer)

Initiating a new message runs out of memory

## Actual Behaviour

mutt silently exits before editor is is displayed

mutt -d 5, last few lines
[2020-06-26 14:18:03]<5> mutt_addr_is_user() no, all failed
[2020-06-26 14:18:03]<5> mutt_addr_is_user() no, all failed
[2020-06-26 14:18:03]<5> mutt_addr_is_user() no, all failed
[2020-06-26 14:18:06]<1> mutt_index_menu() Got op OP_MAIL (123)
[2020-06-26 14:18:06]<3> mutt_mktemp_full() send.c:1975: mutt_mktemp returns "/tmp/neomutt-joe-27718-19938-14740582641857470839"
[2020-06-26 14:18:17]<E> mutt_mem_malloc() Out of memory

## Steps to Reproduce

Latest code pulled from git
Using OUATHBEARER (google)
using zstd compression

## How often does this happen?
- Always

## When did it start to happen?

After commit 11a28c3c42b45f9bce9c954a0b8ee00a4ec83fd8
(this commit works a normal)

## NeoMutt Version

```
PUT YOUR "neomutt -v" OUTPUT HERE
```
NeoMutt 20200626-30-76c339
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.12.14-lp151.28.48-default (x86_64)
ncurses: ncurses 6.1.20180317 (compiled with 6.1.20180317)
libidn: 1.34 (compiled with 1.34)
GPGME: 1.10.0
OpenSSL: OpenSSL 1.1.0i  14 Aug 2018
storage: kyotocabinet
compression: zlib, zstd

Configure options: --kyotocabinet --ssl --disable-doc --zstd --zlib --gpgme

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls +gpgme -gss +hcache -homespool +idn +inotify
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +regex -sasl
  +smime -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

<!-- This info might help us narrow down the source of the problem. -->

* Operating System and its version 
opensuse 15.1
* Were you using multiple copies of NeoMutt at once?
no
* Were you using 'screen' or 'tmux'?
tmux
* Is your email local (maildir) or remote (IMAP)?
IMAP

**Comment by fourjay** [comment]
commit c4029fcede2153d8181792a71f92cdeeb2fd50e1 seems to fix this :-)

**Comment by flatcap** [comment]
> commit [c4029fc](https://github.com/neomutt/neomutt/commit/c4029fcede2153d8181792a71f92cdeeb2fd50e1) seems to fix this :-)

Brilliant.
