### ISSUE TITLE
Please consider making <return> and <enter> separate key bindings

### ISSUE THREAD

**Issue by ilintault** [neomutt/neomutt#24]
Thanks for neomutt.

Here is a patch that separates the return and enter keys so they can be bound separately.

https://dev.mutt.org/trac/attachment/ticket/3494/mutt-return-enter.patch

Thanks!

**Comment by flatcap** [comment]
Hi @ilintault I haven't forgotten you.  I'm busy fixing bugs and trying to help distros get up-to-date.
The patch looks sensible, but before I merge it, I want to make sure I understand the implications.
I shall try to make some time this coming week.

**Comment by ilintault** [comment]
Thank you for considering it.  It's a useful patch that allows mapping of Ctrl-J/Enter (ASCII 10) and Ctrl-M/Return (ASCII 13) separately.

**Comment by flatcap** [comment]
Ncurses can now differentiate between <return> and <enter>.
It seems that slang already worked without the patch.
