### ISSUE TITLE
Uncollapse thread on new mail

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#240]
The original patch and discussion is on the mutt-dev mailing list:

- https://marc.info/?t=147176968400001&r=1&w=2
- https://marc.info/?l=mutt-dev&m=147260853930132&w=2

Give the user more control over when threads are opened/closed.

**Comment by nobrowser** [comment]
Hmm odd - I thought it already worked that way.  But oh wait, I actually never get new mail in an async manner, I always download it with a shell escape.  So I guess that's different?

**Comment by flatcap** [comment]
Yes, it does.
