### ISSUE TITLE
sidebar-open not working anymore

### ISSUE THREAD

**Issue by sivizius** [neomutt/neomutt#2400]
## Expected Behaviour
When Executing the <sidebar-open> command, the currently selected mailbox in the sidebar should open.

## Actual Behaviour
Since my last update (20200619), when I execute this command (either by my shortcut or by typing `:exec sidebar-open`), the folder-hook gets executed and then it switches to the very first mailbox in the sidebar and shows nothing (even this mailbox will not be shown).

If NeoMutt crashed, did your OS create a 'coredump' file?

## Steps to Reproduce
Executing `:exec sidebar-open`.

## How often does this happen?
Always

## When did it start to happen?
Since last update (NeoMutt 20200619), I do not remember the version I had before.

## NeoMutt Version

```
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.7.4 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.35 (compiled with 1.35)
GPGME: 1.13.1-unknown
OpenSSL: OpenSSL 1.1.1g  21 Apr 2020
libnotmuch: 5.2.0
storage: lmdb
compression: zlib

Configure options: --prefix=/nix/store/wsmxvnwz48dpici3cnql7dnpbk8r7sjg-neomutt-20200619 --enable-autocrypt --gpgme --gss --lmdb --notmuch --ssl --sasl --with-homespool=mailbox --with-mailpath= --disable-include-path-in-cflags ac_cv_path_SENDMAIL=sendmail --zlib

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache +homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="mailbox"
PKGDATADIR="/nix/store/wsmxvnwz48dpici3cnql7dnpbk8r7sjg-neomutt-20200619/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/nix/store/wsmxvnwz48dpici3cnql7dnpbk8r7sjg-neomutt-20200619/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info
Changing mailboxes via `exec change-folder` and shortcuts using this command does work.
 

* Operating System and its version: NixOS 20.09pre231796.22a81aa5fc1 (Nightingale)
* Were you using multiple copies of NeoMutt at once? Nope
* Were you using 'screen' or 'tmux'? Nope
* Is your email local (maildir) or remote (IMAP)? local

**Comment by sivizius** [comment]
Maybe a duplicate of https://github.com/neomutt/neomutt/issues/2382 ? sounds like, it might be fixed in the release 2 days ago?

**Comment by gahr** [comment]
Looks like it. Feel free to reopen if it's not solved by that.

**Comment by sivizius** [comment]
Thanks, the new version solved the issue.
