### ISSUE TITLE
Using "<enter-command>echo" in macros doesn't seem to work

### ISSUE THREAD

**Issue by rionda** [neomutt/neomutt#2404]
## Expected Behaviour

Point 17 on the "Advanced usage" chapter of the guide suggests the following use of `<enter-command>echo` in a macro:

```
macro index ,a "<save-message>=archive<enter><enter-command>echo 'Saved to archive'<enter>"
```

The expected behavior is that 'Saved to archive' is printed when invoking the macro. 

## Actual Behaviour

When invoked, the macro seems to stop after `echo`: `echo` is shown in the editor line and I could enter a string to be echoed. No message 'Saved to archive' is printed.

## Steps to Reproduce

Create the macro above, invoke it.

## How often does this happen?

- Always

## When did it start to happen?

- When I changed my config by adding the macro.

## NeoMutt Version

```
NeoMutt 20200501
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 19.5.0 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libiconv: 1.16
libidn: 1.35 (compiled with 1.35)
GPGME: 1.13.1-unknown
OpenSSL: OpenSSL 1.1.1g  21 Apr 2020
libnotmuch: 5.2.0
storage: kyotocabinet

Configure options: --prefix=/opt/local --with-idn=/opt/local --with-ncurses=/opt/local --with-nls=/opt/local --with-ssl=/opt/local --with-gpgme=/opt/local --with-kyotocabinet=/opt/local --with-notmuch=/opt/local --with-sasl=/opt/local

Compilation CFLAGS: -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/opt/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss +hcache -homespool +idn -inotify 
  -locales_hack -lua -lz4 +meta -mixmaster +nls +notmuch +openssl +pgp +regex 
  +sasl +smime -sqlite +start_color +sun_attachment +typeahead -zlib -zstd 
MAILPATH="/var/mail"
PKGDATADIR="/opt/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/opt/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
o
```

## Extra Info

* Operating System and its version  MacOS Catalina
* Were you using multiple copies of NeoMutt at once? NO
* Were you using 'screen' or 'tmux'? tmux, but I doubt it matters
* Is your email local (maildir) or remote (IMAP)? maildir

**Comment by gahr** [comment]
Does a simple `:macro index a "<enter-command>echo 'Saved to archive'<enter>"` work? It does here. If it doesn't, could you please try with the latest version?

**Comment by gahr** [comment]
Oh, I can reproduce it with the full macro.

**Comment by rionda** [comment]
Thanks for checking. Please let me know if I should try anything.

**Comment by gahr** [comment]
We figured that out - you probably have `confirmappend` set to true (the default). It'll ask you for a confirmation upon saving a message to a mailbox. The prompt will read everything up to a `y`, a `n`, or an `<enter>`, which it finds in your next command. This should work for you (see the additional enter).

```
macro index ,a "<save-message>=archive<enter><enter><enter-command>echo 'Saved to archive'<enter>"
```

**Comment by rionda** [comment]
No, I don't have `confirmappend` set to true: I have `unset confirmappend` in my `.muttrc`.

**Comment by gahr** [comment]
I can't reproduce it without `confirmappend`. Can you try building up your config piece by piece until you find the offending part?

**Comment by rionda** [comment]
I'll see what I can do, thanks.

**Comment by gahr** [comment]
I just realized we were replicating a different behaviour with `confirmappend`, namely, you wouldn't get the message but you woulnd't get a `echo` handling in the prompt either.

Which makes us think that somehow the rest of your `echo 'Saved to archive'<enter>"` line is being eaten up by something. Any weird unicode spacing characters or something?

**Comment by rionda** [comment]
No, simple space.

**Comment by rionda** [comment]
Here are some additional details, that I guess I should have reported earlier (sorry Pietro!): the macro works when it is defined outside of a `folder-hook`, but if I defined it in a `folder-hook` as in
```
folder-hook foo/* macro index ,a "<save-message>=archive<enter><enter-command>echo 'Saved to archive'<enter>"
```
it doesn't work anymore (in the way described in the original report.

**Comment by gahr** [comment]
ah - now we can reproduce it.

**Comment by gahr** [comment]
Can you please try: 

```
folder-hook foo/* "macro index ,a \"<save-message>=archive<enter><enter-command>echo 'Saved to archive'<enter>\""
```

**Comment by rionda** [comment]
It seems to work.

**Comment by gahr** [comment]
I think [this](https://neomutt.org/guide/advancedusage.html#17-%C2%A0echoing-text) is the example in the advanced guide you're referring to:
```
macro index ,a "<save-message>=archive<enter><enter-command>echo 'Saved to archive'<enter>"
```

The `macro` command takes the sequence of actions as a single argument, hence the need for quotes if there are spaces. I don't see anything that needs fixing in that example.

In your case, you want to wrap the whole macro inside a `folder-hook`, which again takes its command as a single argument and thus needs quotes, see examples [here](https://neomutt.org/guide/configuration.html#8-%C2%A0setting-variables-based-upon-mailbox), e.g., 

```
folder-hook work "set sort=threads"
```

Now, if you want to put your macro inside a folder-hook, you'll need to quote the arguments of both, hence:

```
folder-hook foo/* "macro index ,a  \"<save-message>....\""
```

Yeah, we could feature an example somewhere in the manual, but I guess there's a limit how far you want to go when it comes to giving examples ;) We welcome pull requests though.
