### ISSUE TITLE
Is it possible to save the raw e-mail into a file instead of sending it to an address?

### ISSUE THREAD

**Issue by Konstantinusz** [neomutt/neomutt#2407]
I would like to save the compiled e-mail message into a file, together with the base64 encoded image attachements, to patch it with Content-ID tags (CID). This is needed to place images inline in the HTML e-mail.

**Comment by gahr** [comment]
I think what I would do is save the draft to some mbox. From within the compose menu `set postponed=~/saved-email` then  <kbd>q</kbd> and answer <kbd>y</kbd> at the prompt `Save (postpone) draft message? ([yes]/no):`.

**Comment by gahr** [comment]
Please reopen if the answer is not satisfactory to you.
