### ISSUE TITLE
Call the timeout hook from the pager

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#241]
The new [timeout hook](https://www.neomutt.org/feature/timeout) isn't called when the pager is open.

This should be a simple change to `pager.c`

**Comment by ThomasAdam** [comment]
I'll pick this up since I've been looking at hooks.

**Comment by flatcap** [comment]
@neomutt/reviewers please review

Steps to test:
- run mutt
- open email (go to pager)
- create hook: `timeout-hook 'exec previous-undeleted'`
- wait for timeout

Expected result:
- selected email changes every `timeout` seconds
- continues changing selection when you return to the index
