### ISSUE TITLE
Group-chat-reply error

### ISSUE THREAD

**Issue by chekmanh** [neomutt/neomutt#2416]
## Expected Behaviour

Group-chat-reply should keep cc in cc

## Actual Behaviour

Using Group-chat-reply takes every address in cc and puts them in the to: field

## Steps to Reproduce

use Group-chat-reply

## How often does this happen?

- Always

## When did it start to happen?

- Always

## NeoMutt Version

```
Archlinux
 System: Linux 5.7.5-arch1-1 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.13.1
GnuTLS: 3.6.14
libnotmuch: 5.2.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd
```

## Extra Info

* Archlinux (newest Version)

Sry, I already have a solution, but I don't know how to submit it. 
```
diff --git a/send/send.c b/send/send.c
index b465497c8..a1c470cd1 100644
--- a/send/send.c
+++ b/send/send.c
@@ -757,9 +757,10 @@ int mutt_fetch_recips(struct Envelope *out, struct Envelope *in, SendFlags flags
       /* if(!mutt_addr_is_user(in->to)) */
       if (flags & SEND_GROUP_REPLY)
         mutt_addrlist_copy(&out->cc, &in->to, true);
-      else
-        mutt_addrlist_copy(&out->to, &in->cc, true);
-      mutt_addrlist_copy(&out->cc, &in->cc, true);
+      else {
+        mutt_addrlist_copy(&out->to, &in->to, true);
+        mutt_addrlist_copy(&out->cc, &in->cc, true);
+      }
     }
   }
   return 0;


```

**Comment by flatcap** [comment]
Hi @chekmanh, did you mean to close the issue?
If not, you can reopen it using a button, below.

**Comment by chekmanh** [comment]
@flatcap yeah, there was an update that fixed everything

**Comment by flatcap** [comment]
Ah!  Glad to hear it :-)
