### ISSUE TITLE
Eliminate strndup and strnlen from notmuch

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#242]
Notmuch uses `strndup()` in 5 places.

`strndup()` doesn't guarantee that the string will be NULL-terminated.
They would be better replaced by `strfcpy()`.

When they are replaced, both `strndup.c` and `strnlen.c` could be dropped from the build.

**Comment by ThomasAdam** [comment]
Hmm.  I'd argue stfcpy() should then be changed to using strlcpy() with a compat layer for those systems which don't have strlcpy() at all.  This is a much harder sell, upstream though, I appreciate that.

I appreciate that's a larger change.  Has anyone bothered to audit whether strfcpy() and the return value/sizeof parameters are correct across the whole lot?  Mechanically-changing this is one thing, but an appraisal of its use is even more valuable.

**Comment by flatcap** [comment]
`strfcpy()` is Mutt's version of `strlcpy()` and has existed for a **LONG** time.
There are over 400 calls to it.  **NONE** of the callers use the return value.

But this is an aside.  We're not changing that.  Not today.

Changing notmuch will bring it into line with Mutt and remove a couple of dependencies.

**Comment by darnir** [comment]
I thought this was done?

**Comment by flatcap** [comment]
No.  The issue is about notmuch's use of `strndup()` and `strnlen()`.
Noone else uses them, but they add two files to the build.

The comments above are just an aside.

**Comment by karelzak** [comment]
> Notmuch uses strndup() in 5 places.
> strndup() doesn't guarantee that the string will be NULL-terminated.

Are you sure? Maybe the evil is strncpy() and strndup() is safe :-)

**Comment by timkuijsten** [comment]
> strndup() doesn't guarantee that the string will be NULL-terminated.

Both the included strndup.c and IEEE Std 1003.1-2008 (macOS, OpenBSD, FreeBSD, Linux) guarantee that the string is NUL-terminated.

That said, I can see the point of unification.

**Comment by flatcap** [comment]
Sorry for the slow reply.
@timkuijsten Yes, thanks for point out the obvious.  Of course it does.  I don't know what I was thinking.

As for replacing `strndup()`, it turns out that mutt already has a near-identical function `mutt_substrdup()`.
