### ISSUE TITLE
changing $pager_index_lines doesn't work correctly

### ISSUE THREAD

**Issue by mgedmin** [neomutt/neomutt#2426]
## Expected Behaviour

I have macros like this:

```
macro pager \e8 ':set pager_index_lines=10<enter>'          "show more context"
macro pager \e9 ':set pager_index_lines=4<enter>'           "show some context"
macro pager \e0 ':set pager_index_lines=0<enter>'           "don't show context"
```

When I'm reading an email I expect that pressing Alt-9 will show me the surrounding messages at the top.
![Ekrano nuotrauka iš 2020-07-14 11-04-53](https://user-images.githubusercontent.com/159967/87401012-4169c700-c5c2-11ea-9af0-602bd49fe606.png)

(currently this folder has only one message)

## Actual Behaviour

When I press Alt-9, I get to see one index line at the bottom of my message:
![Ekrano nuotrauka iš 2020-07-14 11-04-18](https://user-images.githubusercontent.com/159967/87400695-cef8e700-c5c1-11ea-846d-7d230571e546.png)

(in a folder with more messages I also see only one line, but in a different position on screen).

## Steps to Reproduce

Open a folder with at least one email message, view the message, then do `:set pager_index_lines=1` (or any other number other than 0).

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?  20200501

## NeoMutt Version

```
NeoMutt 20200626-106-5e927c
Copyright (C) 1996-2016 Michael R. Elkins ir kiti.
NeoMutt ateina ABSOLIUČIAI BE JOKIOS GARANTIJOS; dėl smulkmenų paleisk 'neomutt -vv.'
NeoMutt yra laisva programinė įranga, ir tu gali laisvai ją platinti su tam
tikromis sąlygomis; rašyk 'neomutt -vv' dėl smulkmenų.

System: Linux 5.4.0-40-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.13.1-unknown
GnuTLS: 3.6.13
libnotmuch: 5.2.0
storage: tokyocabinet

Configure options: --prefix=/usr --sysconfdir=/etc --with-mailpath=/var/mail --mixmaster --gnutls --gpgme --gss --sasl --lua --notmuch --tokyocabinet --full-doc

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Įprastos parinktys:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Kompiliavimo parinktys:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +regex +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

Jei norite daugiau sužinoti apie NeoMutt, aplankykite https://neomutt.org
Jei radote NeoMutt klaidą, praneškite apie ją
    https://github.com/neomutt/neomutt/issues
arba paštu į <neomutt-devel@neomutt.org>
```

but I first noticed the bug on 20200626-41-c4029f.

## Extra Info

* Operating System and its version: Ubuntu 20.04 LTS
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? local

**Comment by mgedmin** [comment]
git bisect points to either cc7d36a996831f4b93e236b343ff3d496d7b4f1f and 7dbf91e36153d137119196353ef42fa2d523074d.  

6903455e6 is the last good commit, cc7d36a99 fails to display the message entirely, and 7dbf91e36 displays the index in the wrong location.

**Comment by mgedmin** [comment]
Workaround: change pager_index_lines when you're in the index rather than in the page.

Note: older versions of neomutt had an off-by-one error(?) where setting pager_index_lines=4 would show me three lines of index and a status bar.  Newer neomutt versions show 4 lines of index and a status bar.  This may be mildly annoying for users (like myself) who share their ~/.muttrc between machines that might have different versions of (neo)mutt installed.

**Comment by flatcap** [comment]
Please can you give [[devel/pager]](https://github.com/neomutt/neomutt/tree/devel/pager) a try.

(I was recursively **hiding** windows, but only **showing** the parent)

> Note: older versions of neomutt had an off-by-one error

Ooh, well spotted.
That's because the Index and Index Bar are now separate windows.

It turns out, that the behaviour is documented.  Who knew? :-)

> One of the lines is reserved for the status bar from the index,
> so a setting of 6 will only show 5 lines of the actual index.

Intuitively, a setting of `n` should show `n` lines,
so I'm inclined to keep NeoMutt's behaviour and fix the docs.

> This may be mildly annoying for users who share their ~/.mutt/
> between ... different versions of (neo)mutt

I'll have a think.

It's likely that this will affect the sidebar, in the future, too.
I'm considering making the sidebar divider into a separate window.
This would make splitting windows easier to manager (e.g. for widescreen view).
