### ISSUE TITLE
~N/~F search criteria in postpone view disallowed?

### ISSUE THREAD

**Issue by nabijaczleweli** [neomutt/neomutt#2428]
After pressing `<recall-message>` in an index view, the postpone view shows up, with a relatively normal index listing; it doesn't include `<next-new-then-unread>`, but does include `<search>`, and I started to use `git format-patch >> ~/mail/mailboxes/Drafts/messages` a lot more recently, so I'd thought I'd try to emulate the former by macroing `/~N<Enter>`; however, to my surprise, that returns "Not found", regardless of mails marked N, as does flagging some drafts and searching for `~F`.

Is this by design? If so, can the design be amended?

![Demonstrative recording](https://user-images.githubusercontent.com/6709544/87605441-0e761f00-c6f9-11ea-939b-7db0c0ab0baa.gif)

**Comment by flatcap** [comment]
Hmm... strange.

After a bit of investigation, I see the problem.
The postpone menu doesn't implement its own search, so we only get the basic feature.
The basic search just looks for a regex match against the plain text (as seen on-screen).

The index menu calls `mutt_search_command()`, so it can search the data more accurately.
The solution might be as simple as cut'n'pasting these lines into `select_msg()`:

https://github.com/neomutt/neomutt/blob/cd4342b578a916e1d642cc2afb5fea6a088b7f4a/index.c#L1918-L1932

Unfortunately, I don't have time investigate, atm.

**Comment by nabijaczleweli** [comment]
Thanks, that's exactly the pointer I needed!

PR in #2432
