### ISSUE TITLE
HCache Database Benchmarks

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#244]
NeoMutt now has 6 header-cache backends:

- Tokyo Cabinet
- Kyoto Cabinet
- LMDB
- QDBM
- GDBM
- BDB (Berkeley)

Which is fastest?

They need to be tested with **LARGE** numbers of emails of different sizes.
Care needs to be taken to rule out differences in disk speed, vm cache, etc.

**Comment by pickfire** [comment]
@flatcap Nice, interesting. Can I join to test this benchmark? Hope this is real quick that I can even do it on pi.

**Comment by neverpanic** [comment]
I did some benchmarking for LMDB back when I finished it using `time mutt -f ~/Maildir/a-big-folder -e 'exec exit'`.

**Comment by sassmann** [comment]
Did some basic testing to get an idea of the performance gain, all results are with a pre-filled cache on SSD and after several repetitions.

Maildir with 23k messages
real    0m0.974s none
real    0m0.765s tokyocabinet
real    0m0.821s kyotocabinet
real    0m0.629s bdb
real    0m0.559s lmdb

Maildir with 83k messages
real    0m3.201s none
real    0m2.062s tokyocabinet
real    0m2.359s kyotocabinet
real    0m1.635s bdb
real    0m1.491s lmdb

**Comment by neverpanic** [comment]
I think another interesting metric would be the size of the cache file with these mailboxes. For example, tokyocabinet and kyotocabinet support compressed storage, which will probably mean much smaller storage than, for example, lmdb.

Especially for people on machines with SSDs where storage is more expensive this might be relevant. Ideally, we'd turn these numbers into an article on the neomutt website afterwards.

**Comment by sassmann** [comment]
While we're at it, I was wondering if we couldn't add an option to mutt which keeps mail headers in memory (up to a specified size). Then switching between mailboxes should be almost instantaneous, once they've been loaded once.
Some people achieve this by running a separate mutt for every mailbox in a screen session.

**Comment by toogley** [comment]
@sassmann I agree with you - but i think that should go into a separate issue.

**Comment by gahr** [comment]
# Setup
## Data
`maildir` directory with 83975 messages ([freebsd-hackers](https://lists.freebsd.org/mailman/listinfo/freebsd-hackers) mailing list, 2010-2016)

## Software
NeoMutt 20170113-54-1b6ae3-dirty (1.7.2), with the modifications in #335.
bdb 5.3.28
gdbm 1.12
qdbm 1.8.78
kyotocabinet 1.12.76
lmdb 0.9.18
tokyocabinet 1.4.48

## Environment
### muttrc
```
set spoolfile=maildir
set header_cache_backend=$my_backend
set header_cache=hcache-$my_backend
folder-hook . exec exit
```
### benchmark driver (run.sh)
```sh
#!/bin/sh
BACKENDS="bdb gdbm qdbm lmdb kyotocabinet tokyocabinet"
RCFILE=muttrc

truncate -s0 result-populate.txt result-reload.txt

for b in $BACKENDS; do
    rm -f hcache-${b}*
    # do it twice - the first will populate the cache, the second will reload it
    t1=$(/usr/bin/time mutt -P "set my_backend=$b" -F $RCFILE 2>&1 > /dev/null)
    t2=$(/usr/bin/time mutt -P "set my_backend=$b" -F $RCFILE 2>&1 > /dev/null)
    s=$(stat -f "%z" hcache-${b})
    echo "$b $s $t1" >> result-populate.txt
    echo "$b $s $t2" >> result-reload.txt
done
```
# Results (spaces added for eye-sanity)
## Populate
```
bdb             94699520         9.29 real         4.39 user         2.88 sys
gdbm            88621056        13.32 real         4.44 user         4.04 sys
qdbm            25010176        11.16 real         5.79 user         2.95 sys
lmdb           140599296         8.92 real         4.05 user         2.93 sys
kyotocabinet    27105792        13.35 real         7.63 user         2.82 sys
tokyocabinet    20653568        11.77 real         6.45 user         2.77 sys
```
## Populate
```
bdb            94699520         1.88 real         0.95 user         0.52 sys
gdbm           88621056         2.44 real         0.93 user         0.51 sys
qdbm           25010176         2.13 real         1.22 user         0.44 sys
lmdb          140599296         2.00 real         1.16 user         0.40 sys
kyotocabinet   27105792         3.18 real         1.93 user         0.56 sys
tokyocabinet   20653568         2.53 real         1.34 user         0.64 sys
```

**Comment by gahr** [comment]
## Update with new script to also analyze the results of several runs

```sh
#!/bin/sh
BACKENDS="bdb gdbm qdbm lmdb kyotocabinet tokyocabinet"
RCFILE=muttrc
TIMES=10

truncate -s0 result-populate.txt result-reload.txt

# generate
for i in `jot $TIMES 1`; do
    for b in $BACKENDS; do
        rm -f hcache-${b}*
        # do it twice - the first will populate the cache, the second will reload it
        t1=$(my_backend=$b /usr/bin/time mymutt -F $RCFILE 2>&1 > /dev/null)
        t2=$(my_backend=$b /usr/bin/time mymutt -F $RCFILE 2>&1 > /dev/null)
        s=$(stat -f "%z" hcache-${b})
        echo "$b $s $t1" >> result-populate.txt
        echo "$b $s $t2" >> result-reload.txt
    done
done

rm hcache-*

# analyze
extract()
{
    grep $2 result-$1.txt | awk "{print \$$3}" | xargs
}

avg()
{
    echo "6 k 0 $@ $(jot -b + $TIMES 1) $TIMES / p" |  dc
}

for f in populate reload; do
    echo "*** $f"
    for b in $BACKENDS; do
        real=$(avg $(extract $f $b 3))
        user=$(avg $(extract $f $b 5))
        sys=$(avg $(extract $f $b 7))
        echo "$b $real real $user user $sys sys"
    done
done
```

### Results
```
*** populate                                                                                                                                                    
bdb           9.834000 real 4.651000 user 3.032000 sys                                                                                                                    
gdbm         12.937000 real 4.629000 user 3.800000 sys                                                                                                                  
qdbm         11.242000 real 5.937000 user 2.874000 sys                                                                                                                  
lmdb          9.215000 real 4.275000 user 2.918000 sys                                                                                                                   
kyotocabinet 14.244000 real 8.137000 user 3.006000 sys                                                                                                          
tokyocabinet 11.839000 real 6.481000 user 2.763000 sys                                                                                                          
*** reload                                                                                                                                                      
bdb          2.200000 real 1.108000 user .611000 sys                                                                                                                     
gdbm         2.636000 real 1.007000 user .532000 sys                                                                                                                    
qdbm         2.571000 real 1.445000 user .568000 sys                                                                                                                    
lmdb         1.999000 real .988000 user .572000 sys                                                                                                                     
kyotocabinet 3.072000 real 1.773000 user .633000 sys                                                                                                            
tokyocabinet 2.597000 real 1.423000 user .607000 sys  
```

**Comment by riesebie** [comment]
@gahr :thumbsup: ;-)

**Comment by flatcap** [comment]
My results for 10 iterations on 100,000 emails:

## populate
database     | real      | user      | sys      |
:------------|----------:|---------: |---------:|
bdb          | 3.529000  | 1.820000  | 0.597000 |
lmdb         | 3.564000  | 1.720000  | 0.642000 |
qdbm         | 3.584000  | 2.886000  | 0.618000 |
tokyocabinet | 3.679000  | 2.927000  | 0.731000 |
gdbm         | 4.341000  | 2.091000  | 1.223000 |
kyotocabinet | 5.160000  | 3.841000  | 1.291000 |

## reload
database     | real      | user      | sys      |
:------------|----------:|---------: |---------:|
lmdb         | 0.966000  | 0.766000  | 0.183000 |
bdb          | 1.060000  | 0.858000  | 0.192000 |
gdbm         | 1.179000  | 0.966000  | 0.188000 |
tokyocabinet | 1.321000  | 1.128000  | 0.183000 |
qdbm         | 1.331000  | 1.137000  | 0.184000 |
kyotocabinet | 1.417000  | 1.203000  | 0.202000 |

**Comment by flatcap** [comment]
This now has a permanent home: https://www.neomutt.org/contrib/hcache-bench

**Comment by derekbsnider** [comment]
Just to add, both tokyocabinet and kyotocabinet were written by the author of qdbm, as successors (qdbm -> tokyocabinet -> kyotocabinet), and strangely enough the performance of each is successively slower. They may be feature improvements, but for a database, performance is paramount. QDBM is seriously underrated.

BTW, was this benchmark done with qdbm-1.8.78?

For the record, qdbm-1.8.74 seems to be the last "stable" version of the code, and all versions thereafter seem to be prone to database corruption (with Mikio Hirabayashi, latest is certainly not the greatest).

**Comment by GiorgosXou** [comment]
**For future visitors:** those are "B+Tree" and not "Hash" based benchmarks.

- ***Additional references:***
- - [...benchmarks of some embedded databases with Python](https://charlesleifer.com/blog/completely-un-scientific-benchmarks-of-some-embedded-databases-with-python/)
- - [Are there any known benchmarks/statistics on UnQLite?](https://dba.stackexchange.com/questions/98041)
- - [Kyoto Cabinet ingestion rate measurement][71]
- - [HaloDB against RocksDB and KyotoCabinet][68]
- - [LevelDB vs Kyoto Cabinet my findings][70]
- - [KVS VS Tokyo VS Kyoto VS Tkrzw][96]
 

*<sub>(As of my understanding + by [this](https://github.com/neomutt/neomutt/blob/d3e66a66e1aada89da0b9ac0ab1965226a3d55a5/store/kc.c#L52) shallow hint [`kct` = kyotocabinet-tree])</sub>*

[71]: https://cedanet.com.au/ceda/libs/cxLss/performance/kyoto-cabinet-performance.php '2024-10-06 07:17:11 PM'
[70]: https://www.tumblr.com/maxpert/8330476086/      '2024-10-06 07:10:32 PM'
[68]: https://github.com/yahoo/HaloDB/blob/master/docs/benchmarks.md '2024-10-06 06:47:01 PM | No idea if B+Tree or hash based benchmarks'
[96]: https://github.com/Hino-T-apw/kvs-benchmark-2026 '2026-07-03 06:31:21 PM'
