### ISSUE TITLE
Unicode and sidebar patch with overflowing lines bleeds into sidebar itself

### ISSUE THREAD

**Issue by ThomasAdam** [neomutt/neomutt#245]
I've noticed that unicode characters and sidebar patch sometimes leads to overflowing characters into the sidebar patch.  See screenshot below.  Beyond reporting this, I've done nothing to investigate why.
![unicode-oops](https://cloud.githubusercontent.com/assets/101281/20318153/082c4118-ab61-11e6-8550-4fad846bf9d1.png)

**Comment by flatcap** [comment]
Hmm... that's the pager's fault.

Please can you do a few things:
- save the email into mbox format
- run neomutt without any config and see if the problem still exists
- see what happens when you `set sidebar_on_right` (I'm curious :-)

As the email's spam, please attach it to this issue so others can try to replicate the problem.

**Comment by ThomasAdam** [comment]
Yes, the problem still exists, even with no config.  This isn't surprising given this will be some sort of unicode problem.  Sidebar on right also shows this.
![sor](https://cloud.githubusercontent.com/assets/101281/20451302/98820de8-adef-11e6-9f5f-8a350e712b43.png)

**Comment by flatcap** [comment]
Please can you attach the email to this issue? (so others can test the problem)

**Comment by gahr** [comment]
I have a utf-8 demo mail that I use for this kinds of test. I cannot reproduce it. @ThomasAdam could you please confirm that you're still seeing this behaviour with the latest release of NeoMutt?

**Comment by ThomasAdam** [comment]
Sorry it's taken me so long to get back to you.

It is still happening.  The email is attached.
[problem_email.txt](https://github.com/neomutt/neomutt/files/753284/problem_email.txt)

**Comment by gahr** [comment]
I can reproduce, after I change the `Content-Transfer-Encoding` header from `base64` to `8bit`(the file you posted is not base64-encoded). I will track this down.

**Comment by gahr** [comment]
The problem is with the pager which is unable to properly display `'FULLWIDTH COMMA' (U+FF0C)`, which is the 7th character (counting form 1) on line 108 (婚姻是一本书，...).

**Comment by gahr** [comment]
Also confirmed with mutt-1.7.2

**Comment by gahr** [comment]
The `--enable-locales-fix`configure switch seems to solve this problem. @ThomasAdam could you please check with a build with that flag enabled?

**Comment by ThomasAdam** [comment]
Yep; seems to fix the issue.

**Comment by gahr** [comment]
@ThomasAdam could you please also check without the switch and with the patch in 1ff0351?

**Comment by ThomasAdam** [comment]
@gahr -- looks good.  Tested it.  This seems to fix it.  Thanks.

**Comment by flatcap** [comment]
The test email just renders as garbage unless, as @gahr suggested I change the `Content-Transfer-Encoding`.  Then, it renders correctly.  I can't reproduce the problem at all.

I tried with and without `--enable-locales-fix` and plain neomutt and plain mutt, but those wide commas always render correctly for me.

Aside from that, the code change looks reasonable.

**Comment by gahr** [comment]
@flatcap most likely your locale definitions are better than ours. Could you please try to compile this program and run it with `0xFF0C` as its first argument?

```c
#include <locale.h>
#include <stdio.h>
#include <wchar.h>
#include <wctype.h>

int main(int argc, char **argv)
{
    if (argc != 2)
    {
        fprintf(stderr, "Usage: %s 0xabcd\n", argv[0]);
        return 1;
    }

    setlocale(LC_CTYPE, "");
    const char * loc = setlocale(LC_CTYPE, NULL);
    wchar_t wc = 0;
    sscanf(argv[1], "%x", &wc);
    wprintf(L"locale: %s\n"
             "  char: %x\n"
             " print: %d\n"
             " width: %d\n"
             " glyph: <%lc>\n",
             loc, wc, iswprint(wc), wcwidth(wc), wc);
    return 0;
}
```

Here I get:

```
locale: en_GB.UTF-8
  char: ff0c
 print: 0
 width: 2
 glyph: <，>
```

So, the terminal can print the full-width comma just fine, but `iswprint` returns 0 (non printable).

**Comment by flatcap** [comment]
I get:
```
locale: en_GB.UTF-8
  char: ff0c
 print: 1
 width: 2
 glyph: <，>
```
