### ISSUE TITLE
x-label: adding multiple labels to multiple messages broken

### ISSUE THREAD

**Issue by qwence** [neomutt/neomutt#246]
Steps to reproduce:

1. Tag a bunch of messages in the index
2. Hit ;y (I have edit-label bound to y) and type "tag1, tag2" (without the quotes)
3. The first message has both labels, but subsequent messages only have tag1.

I can observe this using a .muttrc containing only the line "bind index,pager y edit-label".

Version: NeoMutt 20161104 (1.7.1) (containing patch-keywords-neomutt)

**Comment by flatcap** [comment]
It turns out that never worked.  It does now :-)
