### ISSUE TITLE
index colors: some highlighting rules leave an ugly box around the tree symbol

### ISSUE THREAD

**Issue by qwence** [neomutt/neomutt#247]
This isn't just a neomutt issue -- it also happens in vanilla mutt. The basic issue is illustrated in this screenshot:

![tree](https://cloud.githubusercontent.com/assets/76760/20343636/07ae655a-abe7-11e6-80dd-9dacd10a0dac.png)

which is achieved with just the color settings

    color index         brightcolor232    color181        "~F"
    color tree          color249        default
    color indicator     color232        color249

There are two things to notice:
(1) The pink messages are flagged messages, so the first color rule is in effect. It successfully applies the desired color scheme to everything except this ugly box around the tree symbol, which is left colored by the second color rule. (This has nothing to do with this using "default" there -- it still happens if I put a random color there.)

(2) The last line there is where my indicator is. Somehow this gets it right: the entire line, including the area around the tree symbol, is colored according to the last color rule.

What I would like is for the first highlighting rule (the one matching ~F) to work the way the indicator color rule works: it colors the entire line, including the tree symbol.

Version: NeoMutt 20161104 (1.7.1)
$ mutt -v|grep -i color
-SUN_ATTACHMENT +HAVE_BKGDSET +HAVE_COLOR +HAVE_CURS_SET +HAVE_GETADDRINFO 
+HAVE_LIBIDN +HAVE_META -HAVE_REGCOMP +HAVE_RESIZETERM +HAVE_START_COLOR 
patch-attach-headers-color-neomutt
patch-index-color-neomutt
patch-status-color-neomutt

**Comment by flatcap** [comment]
Technically this is a bug, but it's unlikely to be fixed.

Mutt's colour handling is at fault here.  All colours have both foreground and background.  Ideally, you'd want to be able to set just one aspect and have the other "bleed" through from default settings, e.g.
```
color the_whole_line fg=white bg=pink 
color tree_object    fg=green
```
The tree would now be white on a pink background.

We'll keep thinking...

**Comment by qwence** [comment]
I suppose that would be ideal, but I'd also be satisfied by having a black (~F rule foreground) tree character on a pink background (i.e. just using the ~F rule, and ignoring the tree rule, in the same way that the indicator ignores the tree rule). This is probably a lot more practical, right?

**Comment by iKarith** [comment]
You could introduce a new color of "inherit" for things like this?

**Comment by flatcap** [comment]
> a new color of "inherit"

Yes, that's on my "would-like-to-have" list.  Unfortunately, it's a big problem to achieve.

The colours are cached by Mutt as pairs (foreground, background).
This would mean making significant changes to how the colours are parsed, stored and displayed.

**Comment by flatcap** [comment]
Even though this is a bug, this issue has been closed.

To fix it will require major changes to mutt.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).

**Comment by qwence** [comment]
2d51490b36 fixes the immediate issue I reported (though I suppose this thread also contains suggestions for further improvements). Thanks!

**Comment by toogley** [comment]
@qwence thanks for reporting back. :)
