### ISSUE TITLE
Key bindings using "Option/Alt" key not working

### ISSUE THREAD

**Issue by mbuelte** [neomutt/neomutt#249]
I just switched to neomutt a few days ago and I recognized, that my Option/ALT key bindings didn't work. Mutt always shows the error message "Key is not bound."..

Maybe I missed a notice in the documentation? 

I'm using neomutt version 20161104 (1.7.1) as it comes directly out of the Arch repository.

And my current bindings looks like this for example:
```
macro index,pager \ew  "<change-folder>?<toggle-files><enter>"
macro index,pager \ef  "|~/.mutt/utils/view-x-face<enter>"
```

**Comment by toogley** [comment]
Hey,

> macro index,pager \ew  "<change-folder>?<toggle-files><enter>"
> macro index,pager \ef  "|~/.mutt/utils/view-x-face<enter>"

according to the upstream manual [1] (i don't think we changed the behavior of mutt in that regard), \e is the <escape> key and not ALT. However, i don't
know, how you can set ALT in a keykombination.


[1]: http://www.mutt.org/doc/manual/#tab-key-names

regards,
Tobias Angele.

**Comment by toogley** [comment]
(I just asked on the #mutt IRC channel, and they informed me that the ESC key is essentially the same as the ALT key. Sorry for the misinformation^^)

Also, I checked both macros - they work on my machine (same neomutt version). Can you reproduce your issue with a clean `muttrc`?

**Comment by mbuelte** [comment]
Hey, thank you for the fast reply!
Sorry, I thought it was common that '\e' also match the ALT key. I'm using it regulary with a lot of key bindings.

And you were right. With a minimal muttrc, all of my alt-key combos are working like before the switch to neomutt. Thats's weird. I'll take a deeper look into my old configuration - it's pretty large. There must be one thing that makes neomutt stroke.

**Comment by mbuelte** [comment]
I got it! You can delete this issue. It was my fault, sorry!
An old "testing" configuration were included into the main muttrc.
In this particular case, the following attempt leads to the problem:
    `macro index <Esc> "\cg"`
It seems the old mutt simply ignores it at all. And neomutt does it well.
