### ISSUE TITLE
sidebar breaks some fields in compose view

### ISSUE THREAD

**Issue by Wonko7** [neomutt/neomutt#25]
Hi all, 

I'm using mutt 1.6.1 & the sidebar patch on gentoo. When the sidebar is visible, in the compose view (just before hitting Y to send an email) the "subject" & "sign as" fields are drawn "under" the sidebar (the rest are aligned as expected). 

The attachment list is drawn as if it had the whole screen width to draw, so that the attachment type is cropped at the end of the line. 

FWIW, I'm using the following flags for the mutt ebuild: berkdb crypt doc gdbm gpg imap libressl nls sasl sidebar smime smtp ssl -debug -gnutls -idn -kerberos -mbox -nntp -pop -qdbm -selinux -slang -tokyocabinet

I tried building both against ncurses & slang, with only sidebar_visible = yes & account config with the same results.

Is this reproducible on your end?

**Comment by Wonko7** [comment]
A bit more info from the patch we use on gentoo: 
from neomutt-patches-20160416
made to apply on Gentoo patchset

So if this is not reproducible for you, I'll go see the gentoo guys instead.

**Comment by flatcap** [comment]
@Wonko7  Thanks for the detailed bug report.

The latest version of Gentoo (1.6.1-r0) **doesn't** contain the latest version of the sidebar. Yet.
Sorry about that.  @grobian  and I are working on it.

Everything looks OK in NeoMutt 2016-05-02.
If you know what to do, and have the time, please give it a try.
Source: https://github.com/neomutt/neomutt/releases
```
./prepare --enable-sidebar
make
```

**Comment by Wonko7** [comment]
Ok, thanks, great work by the way.

**Comment by grobian** [comment]
I'm planning to work on sidebar-win this weekend releasing a new mutt version with the latest version.

**Comment by grobian** [comment]
can you please check if mutt-1.6.1-r1 works better for you?

**Comment by Wonko7** [comment]
That was fast! Everything is fixed, thanks a lot.
