### ISSUE TITLE
Do not force unsigned chars as param to mutt_to_base64

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#250]
`mutt_to_base64` takes `unsigned char` as input and output parameters. This forces callers to cast their (usually) simple `char` buffers, example:

````c
mutt_to_base64 ((unsigned char*) ibuf, (unsigned char*) obuf, strlen (obuf),
               sizeof (ibuf) - 2);
````

Let's change `mutt_to_base64`'s signature and do the casting inside. While at it, also return the numbers of characters written to the output buffer, so anybody needing that information can avoid having to call `strlen`.

````diff
diff --git a/base64.c b/base64.c
index fd3ffb8..d2ad0c0 100644
--- a/base64.c
+++ b/base64.c
@@ -49,9 +49,10 @@
 #define BAD     -1

 /* raw bytes to null-terminated base 64 string */
-void mutt_to_base64 (unsigned char *out, const unsigned char *in, size_t len,
-                    size_t olen)
+size_t mutt_to_base64 (char *out, const char *cin, size_t len, size_t olen)
 {
+  unsigned char *begin = (unsigned char *)out;
+  const unsigned char *in = (const unsigned char *)cin;
   while (len >= 3 && olen > 10)
   {
     *out++ = B64Chars[in[0] >> 2];
@@ -77,6 +78,7 @@ void mutt_to_base64 (unsigned char *out, const unsigned char *in, size_t len,
     *out++ = '=';
   }
   *out = '\0';
+  return out - (char *)begin;
 }

 /* Convert '\0'-terminated base 64 string to raw bytes.
````

**Comment by gahr** [comment]
(rebased on top of neomutt, as I originally branched off the wrong branch)

**Comment by d-k-c** [comment]
Is the cast necessary, as bitshifts and bitmasks garanty that the result is in [0;63]?

Also, it would be nice to explicit in the function comment if the return value includes the '\0' or not.

**Comment by gahr** [comment]
Yes the casts are needed: left shifts on a signed negative value are undefined behaviour; right shifts or such a value are implementation defined.

Even if the results would be specified, it would not be what we want here. We need bytes in the range 0-254, not chars in the range -128-127.

**Comment by gahr** [comment]
@flatcap Ready for merging.
