### ISSUE TITLE
Make mutt_yesorno only return 'yes' or 'no'

### ISSUE THREAD

**Issue by d-k-c** [neomutt/neomutt#251]
This function, despite its name, can also return -1 (meaning abort) when user hits ctrl-G, but the prompt only show the yes or no options, so the 'abort' cannot be easily discovered. 

Also, some callers handle this case, some don't (it's then treated as 'no'). It would be better to make it consistent by removing the 'abort' case.

By taking a quick look at the callers that handle 'abort', they all expect 'yes' to continue their normal flow, ie. there are no questions like "Do you want to abort? [Y/n]", so the questions could be kept.

**Comment by toogley** [comment]
What about explicitly tell the user about ctrl-G ? Like 

> Do you want to continue? [Y/n/ctrl-G to abort]

or sth similar?

**Comment by d-k-c** [comment]
That could be an option, but there are two main points that make me prefer getting rid of abort:

- the questions are phrased to be yes-no questions, so it's weird to allow a third possible answer.
- somewhat related, the scope of abort is undefined. Sometimes it's like answering 'no', sometimes it stops an action whose scope is broader than the question

**Comment by guyzmo** [comment]
sorry, but removing `C-g` would be a huge change in behaviour to me. Whenever I press something I did not want to that gets me into a menu I did not expect, I press `C-g` to abort, knowing that it will abort without any modification, and get me back to a normal state.

I can't remember how I learned about `C-g` but it's like `C-c` or `C-z`, it's something I know and have been using for a couple of decades and having it removed would bother me, and I guess I wouldn't be the only one.

In `yes`/`no` questions, `C-g` should always default to the option that won't mutate the state, or get you to a next step.

**Comment by nobrowser** [comment]
I agree with @guyzmo that the option of hitting C-g should stay.  But maybe we could design some framework to handle it generically.  Something like longjmp or exceptions, I guess, and it should be a compile-time error if the caller leaves the behavior unspecified, even if it's the same as "no".

**Comment by guyzmo** [comment]
I agree with that option, and maybe rename `mutt_yesno` to `mutt_yesnoabort` or because there's a `mutt_quad` maybe call it `mutt_tri`? ☺

**Comment by d-k-c** [comment]
There is a discoverability issue: most users aren't aware of that option, and I wasn't before digging into the code. Adding `C-g to abort` to the prompt would, imo, take many chars on the screen for not much benefit.

These prompts are used to ask for confirmation, the difference between "no" and "abort" is really ambiguous. Moreover, in some cases it's already the same as asnwering no, in other cases it does something different, so there is no clear rules about how it should behave.

So making `C-g` as an shortcut to `no` would be fine, but imo keeping it as a third possible answer to a confirmation question is just an ugly hack on UX issues.

**Comment by toogley** [comment]
Hm, what about writing in the docs somewhere that every prompt "ok? yes/no" can be aborted via `strg-g` ? Maybe also with an explanation what that exactly means and how it differs from the `no` answer? (to address @d-k-c concerns)

**Comment by guiniol** [comment]
Actually, C-G aborts just about any prompt and is not the same as a `no` unless `no` meant `do nothing`, if I'm not mistaken.

**Comment by toogley** [comment]
@guiniol yep, but that only changes my argument a bit. Essentially it can be still applied.

**Comment by guiniol** [comment]
@toogley My remark was mostly a reaction to the `make C-g a shortcut to no`, which I don't think is a good idea.

**Comment by d-k-c** [comment]
@guiniol but that's my point, in some cases it's already the same as no, so what `C-g` does is inconsitent at best.

Anyway I seem to be the only one bothered by that, so let's keep it the way it is (or eventually rename mutt_yesorno to something more explicit) and move to more important things?

**Comment by guyzmo** [comment]
@d-k-c it's not because today most are unaware of it, it's not a common idiom in text user interfaces, that was known and considered the norm *back in the days*. Most of the time it's acting the same as `C-c`, but without the risk of sending a SIGINT. All in all, `C-g` has the same meaning in many different applications, from `less` to `vim`, and yes including `mutt`. TBH, I've learned that so long ago, that I can't tell how I learned about it, but now in any application I first try `C-g` before issueing an `<esc>` or a `C-c`…

Though, renaming from `mutt`_yesno` to `mutt_tri` or `mutt_yesnoabort` makes sense to me.

**Comment by guiniol** [comment]
@d-k-c I don't understand how it's inconsistent. `C-g` always aborts any prompt. In some cases this can also be achieved by answering `no`, but it also aborts the prompt asking you for the subject of your new mail for example.

**Comment by nobrowser** [comment]
@guyzmo : you forgot emacs - how dare you :-)

**Comment by guyzmo** [comment]
ema…what?

do you mean:

```
E  M  A  C  S
s  e  l  o  h
c  t  t  n  i
a  a     t  f
p        r  t
e        o
         l

```

**Comment by nobrowser** [comment]
LOL - I didn't know that one.

But mutt's bindings are not that far behind.

**Comment by guyzmo** [comment]
maybe yours, but I try to make mine with a modal mindset.

**Comment by guyzmo** [comment]
ok, to sum up this discussion:

1. @d-k-c  wants to get rid of `C-g`
2. @tooley, @guiniol, @nobrowser, @guyzmo say it shall stay.
3. @toogley suggests to either change the prompt to include C-g in choices or at least the documentation
4. @nobrowser and @guyzmo suggest we could internally make this explicit by changing `mutt_yesorno` into `mutt_tri` or `mutt_yesnoabort` that shows there's an abort option to be taken care of.

All in all, this issue shall be closed. Maybe ④ or ⑤ should lead to a new issue.
