### ISSUE TITLE
UTF-8 attachment names from Outlook aren't decoded

### ISSUE THREAD

**Issue by nabijaczleweli** [neomutt/neomutt#2539]
## Expected Behaviour

UTF-8-encoded attachments to be decoded to `zęta.png` instead of `=?utf-8?Q?z=C4=99ta.png?=`

## Actual Behaviour

Aren't.

## Steps to Reproduce

Download this mailbox: [zęta.mbox.gz](https://github.com/neomutt/neomutt/files/4960828/zeta.mbox.gz), ungzip it, open in neomutt.

Mail with subject "zęta" was sent with Outlook, the MIME delimiter is
```
------=_NextPart_000_0008_01D6604B.707A8660
Content-Type: image/png;
	name="=?utf-8?Q?z=C4=99ta.png?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="=?utf-8?Q?z=C4=99ta.png?="
```
and neomutt shows it as that string verbatim.

Mail with subject "zęta 2" was sent with NeoMutt, the MIME delimiter is
```
--ojrk22ledcbbpalg
Content-Type: image/png
Content-Disposition: attachment; filename*=utf-8''z%C4%99ta%2Epng
Content-Transfer-Encoding: base64
```
which shows up correctly as "zęta.png"

## How often does this happen?

- Always

## When did it start to happen?

dunno

## NeoMutt Version

```
NeoMutt 20200626
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.19.0-9-amd64 (x86_64)
ncurses: ncurses 6.1.20181013 (compiled with 6.1.20181013)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.12.0
GnuTLS: 3.6.7
libnotmuch: 5.2.0
storage: tokyocabinet
compression: zlib, zstd

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet --zlib --zstd --testing

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/home/nabijaczleweli/backports/build-output/neomutt-20200626+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +regex +sasl
  +smime -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Buster
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? Either

**Comment by flatcap** [comment]
Ah!  From the docs:

---

- `$rfc2047_parameters`                                                                                                          
                                                                                         
When this variable is _set_, NeoMutt will decode RFC2047-encoded MIME parameters. 
 You want to set this variable when NeoMutt suggests you to save attachments to files named like:                                                                            
`=?iso-8859-1?Q?file=5F=E4=5F991116=2Ezip?=`
                                                                                                                                                                             
When this variable is _set_ interactively, the change won't be active until you change folders.                                                                             
                                                                                                                                                                             
Note that this use of RFC2047's encoding is explicitly prohibited by the standard,                                                                                          
but nevertheless encountered in the wild.                                                                                                                                   
                                                                                                                                                                             
Also note that setting this parameter will _not_ have the effect that NeoMutt _generates_ this kind of encoding.                                                            
Instead, NeoMutt will unconditionally use the encoding specified in RFC2231.

**Comment by flatcap** [comment]
With that set, your attachment name is displayed correctly.

**Comment by nabijaczleweli** [comment]
Oh, thanks! I searched the manpage for "=?utf" and "Outlook", but that didn't do me much good.
