### ISSUE TITLE
Moving messages to trash is slow

### ISSUE THREAD

**Issue by darnir** [neomutt/neomutt#254]
When moving a large set of messages from one folder to Trash, the operation is very slow. This is particularly the case when the mailboxes are all local storage instead of IMAP.

The problem is that Mutt creates a new file for each message that has to be moved and copies the data into it. All potentially expensive operations. We should be able to identify this case and use a shorter and more efficient approach, i.e. Simply renaming the files. 

A simpler and even faster approach exists, but that is for a very specific set of options. For when a user is on a *nix system, with local maildir files, then they simply need to be hard linked into the trash folder. But that's a very specific optimization that would require fairly complicated rewriting of the mutt logic

**Comment by P-EB** [comment]
I suggest we work only on the moving idea you expressed.

Premature optimization would cause us a lot of pain I guess.

**Comment by flatcap** [comment]
It's a good idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
