### ISSUE TITLE
Problems working with a mail that has "To: unlisted-recipients:; (no To-header on input)"

### ISSUE THREAD

**Issue by ukleinek** [neomutt/neomutt#2548]
Disclaimer: I already reported this issue downstream in the Debian bug tracker. See https://bugs.debian.org/966389. The nice people in #neomutt asked to report here, too.

I got a mail (https://www.spinics.net/lists/linux-pwm/msg13231.html). In the file there is a To: header, but this is empty.

## Expected Behaviour

When opening the containing Maildir, everything is fine. The mail is shown as:

    Date: Fri, 24 Jul 2020 23:36:51 +0200
    From: Martin Botka <martin.botka1@gmail.com>
    To:
    Cc: Fenglin Wu <fenglinw@codeaurora.org>, Konrad Dybcio <konradybcio@gmail.com>, Martin Botka <martin.botka1@gmail.com>,
            Jacek Anaszewski <jacek.anaszewski@gmail.com>, Pavel Machek <pavel@ucw.cz>, Dan Murphy <dmurphy@ti.com>, Rob Herring
            <robh+dt@kernel.org>, Thierry Reding <thierry.reding@gmail.com>, Uwe Kleine-König <u.kleine-koenig@pengutronix.de>,
            Lee Jones <lee.jones@linaro.org>, linux-leds@vger.kernel.org, devicetree@vger.kernel.org,
            linux-kernel@vger.kernel.org, linux-pwm@vger.kernel.org
    Message-Id: <20200724213659.273599-2-martin.botka1@gmail.com>
    Subject: [PATCH RCC 1/6] pwm: Add different PWM output types support
    
    ....

as expected. Also when doing "reply-to-all" with (edit_headers on) everything is fine: Martin Botka is in To:, all the guys that were on Cc: in the original are added to Cc: (apart from me). That's how I want it.

## Actual Behaviour

However if I look at the mail in

    $ mutt-work -f notmuch://?query=id:20200724213659.273599-2-martin.botka1@gmail.com

it looks as follows:

    Date: Fri, 24 Jul 2020 23:36:51 +0200
    From: Martin Botka <martin.botka1@gmail.com>
    To: unlisted-recipients: no To-header on input <;
    Cc: Fenglin Wu <fenglinw@codeaurora.org>, Konrad Dybcio <konradybcio@gmail.com>, Martin Botka <martin.botka1@gmail.com>,
            Jacek Anaszewski <jacek.anaszewski@gmail.com>, Pavel Machek <pavel@ucw.cz>, Dan Murphy <dmurphy@ti.com>, Rob Herring
            <robh+dt@kernel.org>, Thierry Reding <thierry.reding@gmail.com>, Uwe Kleine-König <u.kleine-koenig@pengutronix.de>,
            Lee Jones <lee.jones@linaro.org>, linux-leds@vger.kernel.org, devicetree@vger.kernel.org,
            linux-kernel@vger.kernel.org, linux-pwm@vger.kernel.org
    Message-Id: <20200724213659.273599-2-martin.botka1@gmail.com>
    Subject: [PATCH RCC 1/6] pwm: Add different PWM output types support
    Tags: inbox patchwork pw-linux-pwm pw-linux-pwm-new to-me

which is a bit annoying but not grave.

However on "reply-to-all" the mail looks as follows in my editor:

    From: Uwe Kleine-König <u.kleine-koenig@pengutronix.de>
    To: Martin Botka <martin.botka1@gmail.com>
    Cc: no To-header on input <;, Fenglin Wu <fenglinw@codeaurora.org>,
        Konrad Dybcio <konradybcio@gmail.com>,
        Jacek Anaszewski <jacek.anaszewski@gmail.com>,
        Pavel Machek <pavel@ucw.cz>, Dan Murphy <dmurphy@ti.com>,
        Rob Herring <robh+dt@kernel.org>,
        Thierry Reding <thierry.reding@gmail.com>,
        Lee Jones <lee.jones@linaro.org>, linux-leds@vger.kernel.org,
        devicetree@vger.kernel.org, linux-kernel@vger.kernel.org,
        linux-pwm@vger.kernel.org
    Bcc:
    Subject: Re: [PATCH RCC 1/6] pwm: Add different PWM output types support
    Reply-To:
    In-Reply-To: <20200724213659.273599-2-martin.botka1@gmail.com>
    
    ...

and if I don't touch this, just write my mail, save and quit the editor, on return to neomutt, the Cc: field is empty.

## Steps to Reproduce

I assume my description is good enough and I expect it to reproduce on each mail with an empty To: header. Tell me if you need a bounce.

## How often does this happen?

Always on Martin's mails in this thread.

## NeoMutt Version

This is neomutt 20200626+dfsg.1-1 from Debian/testing.

```
NeoMutt 20200626
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.19.0-9-amd64 (x86_64)
ncurses: ncurses 6.1.20181013 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.13.1-unknown
GnuTLS: 3.6.14
libnotmuch: 5.2.0
storage: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet --sqlite --autocrypt

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-Ngf0Dg/neomutt-20200626+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +regex +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Debian, a mix of stable, testing and unstable.

* Were you using multiple copies of NeoMutt at once? no

* Were you using 'screen' or 'tmux'? no

* Is your email local (maildir) or remote (IMAP)? local Maildir

**Comment by Austin-Ray** [comment]
Removed `notmuch` label since I can reproduce in a `maildir`. So it's not `notmuch`-specific (but thanks for using `notmuch`! apologies that `neomutt` can't handle this use case.)

I was able to download the email with this link (LKML bouncer wasn't working): https://patchwork.ozlabs.org/project/linux-pwm/patch/20200724213659.273599-2-martin.botka1@gmail.com/mbox/

@flatcap : We'll need your assistance on this since it's how neomutt handles the headers. I haven't interacted with that portion of the code.

**Comment by ukleinek** [comment]
I looked at this again, because for me this didn't reproduce with Maildir. My initial assumption that this triggers on an empty "To;" header is wrong. I have two copies of this mail (one I got directy and the other via the mailing list):

    uwe@taurus:~$ notmuch-work search --output=files id:20200724213659.273599-2-martin.botka1@gmail.com
    /home/uwe/Maildir-work/cur/1595689134.29583_3.taurus,U=45957:2,RS
    /home/uwe/Maildir-work/.lists.linux-pwm/cur/1595689160.29583_150.taurus,U=5095:2,RS
    uwe@taurus:~$ grep To: /home/uwe/Maildir-work/cur/1595689134.29583_3.taurus,U=45957:2,RS
    To: 
    In-Reply-To: <20200724213659.273599-1-martin.botka1@gmail.com>
    uwe@taurus:~$ grep To: /home/uwe/Maildir-work/.lists.linux-pwm/cur/1595689160.29583_150.taurus,U=5095:2,RS
    In-Reply-To: <20200724213659.273599-1-martin.botka1@gmail.com>
    To:     unlisted-recipients:; (no To-header on input)

The latter was obviously modified by the mailing list software and that's what mutt picks up and then chokes on.

So with now looking at the right file I confirm @Austin-Ray 's finding.

    mkdir -p tmpmaildir/{cur,new,tmp}
    curl https://lore.kernel.org/linux-devicetree/20200724213659.273599-2-martin.botka1@gmail.com/raw > tmpmaildir/cur/tralala:2
    mutt-work -f tmpmaildir

indeed behaves bogus.

Thanks @Austin-Ray for taking the time and effort to work on my report.

**Comment by gahr** [comment]
So I guess what you're saying is

* Expected behaviour
```
To: unlisted-recipients:; (no To-header on input)
```

* Actual behaviour
```
To: unlisted-recipients: no To-header on input <;
```

I am not totally positive that what's found in the email is a valid To header. We can probably double check that.

**Comment by ukleinek** [comment]
@gahr I don't care much about the display, but hitting "reply-to-all" and not modifying Cc: should not result in an empty Cc: for sure.
(That is what bite me more than once.) Also if the content is found to be invalid---I didn't check either---(neo)mutt should handle it somehow saner.

**Comment by gahr** [comment]
I don't get an empty cc, but:

```
          To: Martin Botka <martin.botka1@gmail.com>                                                                                                                 
          Cc: no To-header on input <;, Fenglin Wu <fenglinw@codeaurora.org>, Konrad Dybcio <konradybcio@gmail.com>, Jacek Anaszewski <jacek.anaszewski@gmail.com>,  
              Pavel Machek <pavel@ucw.cz>, Dan Murphy <dmurphy@ti.com>, Rob Herring <robh+dt@kernel.org>, Thierry Reding <thierry.reding@gmail.com>,                 
              Uwe Kleine-König <u.kleine-koenig@pengutronix.de>, Lee Jones <lee.jones@linaro.org>, linux-leds@vger.kernel.org, devicetree@vger.kernel.org,           
              linux-kernel@vger.kernel.org, linux-pwm@vger.kernel.org 
```

I'll double check what we can do with that address

**Comment by gahr** [comment]
The email address is valid: it's a group named `unlisted-recipients` with an empty list of mailboxes in it (between `:` and `;`) followed by the comment in parentheses `no To-header on input`.

We fail to parse it correctly, and end up creating the group with a single address `no To-header on input` in it.

**Comment by gahr** [comment]
@ukleinek could you please try to  devel/issue-2548 branch?

**Comment by ukleinek** [comment]
> I don't get an empty cc, but:
> 
> ```
>           To: Martin Botka <martin.botka1@gmail.com>                                                                                                                 
>           Cc: no To-header on input <;, Fenglin Wu <fenglinw@codeaurora.org>, Konrad Dybcio <konradybcio@gmail.com>, Jacek Anaszewski <jacek.anaszewski@gmail.com>,  
>               Pavel Machek <pavel@ucw.cz>, Dan Murphy <dmurphy@ti.com>, Rob Herring <robh+dt@kernel.org>, Thierry Reding <thierry.reding@gmail.com>,                 
>               Uwe Kleine-König <u.kleine-koenig@pengutronix.de>, Lee Jones <lee.jones@linaro.org>, linux-leds@vger.kernel.org, devicetree@vger.kernel.org,           
>               linux-kernel@vger.kernel.org, linux-pwm@vger.kernel.org 
> ```

That's how it looks for me in the editor, too. But on return to neomutt Cc: is empty.

Best regards
Uwe

**Comment by ukleinek** [comment]
> @ukleinek could you please try to devel/issue-2548 branch?

This ends up with:

    Cc: ;, Fenglin Wu <fenglinw@....

for me. Is that what you expect?
