### ISSUE TITLE
mutt mangles passwords with quotes

### ISSUE THREAD

**Issue by cyphar** [neomutt/neomutt#2551]
This is basically the same issue as #2337 but it's definitely happening in mutt and not an external tool.

## Expected Behaviour

Use a password with `"` characters.

## Actual Behaviour

Mutt appears to strip them after substitution into the config file, resulting in authentication errors.

## Steps to Reproduce

```
% grep smtp_pass .mutt/muttrc-personal
set smtp_pass=`keepassxc-helper "/Shared/Email/Mailbox"`
% keepassxc-helper "/Shared/Email/Mailbox"
K6d@FD{4.Ai:"!#TGu-BBR]3ggpdze}y.6bPgW(W
% mutt -n -Q smtp_pass
set smtp_pass = "K6d@FD{4.Ai:!#TGu-BBR]3ggpdze}y.6bPgW(W"
```

`keepassxc-helper` is a program I use which fetches my password from my KeepassXC password manager. It doesn't mangle quotes (as you can see above), but after `mutt` does the command substitution the `"` character disappears. As a result, you get authentication errors when trying to send emails.

Note that on openSUSE, `mutt` is actually Neomutt.

## How often does this happen?

- Always

## When did it start to happen?

- When I changed my password to include `"`.

## NeoMutt Version

```
% mutt -v
NeoMutt 20200626
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.7.7-1-default (x86_64)
ncurses: ncurses 6.2.20200613 (compiled with 6.2.20200613)
libidn: 1.35 (compiled with 1.35)
GPGME: 1.13.1
GnuTLS: 3.6.14
libnotmuch: 5.2.0
storage: kyotocabinet, lmdb

Configure options: --prefix=/usr --docdir=/usr/share/doc/packages/neomutt --with-mailpath=/var/mail --kyotocabinet --lua --lmdb --gnutls --gpgme --notmuch --sasl --gss --idn --mixmaster

Compilation CFLAGS: -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +regex +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* **Operating System and its version:** openSUSE Tumbleweed
* **Were you using multiple copies of NeoMutt at once?** Yes, but it happens if you just use one.
* **Were you using 'screen' or 'tmux'?** `tmux`
* **Is your email local (maildir) or remote (IMAP)?** maildir

**Comment by gahr** [comment]
The solution I use is to wrap your pass cmd in a script that adds the necessary single quotes:
```sh
#!/bin/sh
echo "'`keepassxc-helper $0`'"
```
so NeoMutt receives the properly quoted string `'K6d@FD{4.Ai:"!#TGu-BBR]3ggpdze}y.6bPgW(W'`.

I understand is not optimal, but it's hard to generalize what needs to be done with the result of a backtick command in a way that works for everyone.

**Comment by gahr** [comment]
I would say this is working as designed: the output from the backtick'd program is reinterpreted as the test of a normal variable, without any additional quoting. Changing this might break existing behaviour.

**Comment by cyphar** [comment]
Looking at the manual, this is [actually documented](http://www.mutt.org/doc/manual/#ex-backtick-dblquotes) and the suggested solution is this:

```
# note the double-quotes around the backticks
set smtp_pass="`keepassxc-helper "/Shared/Email/Mailbox"`"
```

I just tried it and it worked.

**Comment by gahr** [comment]
> I should've RTFM I guess

I should have, too :)

**Comment by karlsebal** [comment]
I actually have to 

```set smtp_pass="'`password-providing-program-or-script `'"```

where in earlier versions the singe quotes had not been necessary.
