### ISSUE TITLE
Mouse scrolling incorrectly in pager on macOS 10.15

### ISSUE THREAD

**Issue by bmclean2** [neomutt/neomutt#2557]
#2015 Expected Behaviour

Scrolling in the pager using trackpad/mouse should be going to next/previous line

## Actual Behaviour

Scrolling instead goes to next/previous email

## Steps to Reproduce

If have the following lines in my config

bind index \031 previous-undeleted
bind index \005 next-undeleted
bind pager \031 previous-line
bind pager \005 next-line

I'm on a Macbook Pro running 10.15 using Alacritty terminal. Mouse scrolling works as expected in man, less, vim, and the index in neomutt. The same issue exists in Terminal.app and iTerm2.

## How often does this happen?

Always

## When did it start to happen?

Ever since I started using Neomutt

## NeoMutt Version

NeoMutt 20200626
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 19.5.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.11
libidn: 1.35 (compiled with 1.35)
GPGME: 1.13.1
OpenSSL: OpenSSL 1.1.1g  21 Apr 2020
libnotmuch: 5.2.0
storage: tokyocabinet, lmdb

Configure options: --prefix=/usr/local/Cellar/neomutt/20200626 --enable-gpgme --with-gpgme=/usr/local/opt/gpgme --gss --lmdb --notmuch --sasl --tokyocabinet --with-ssl=/usr/local/opt/openssl@1.1 --with-ui=ncurses --lua --with-lua=/usr/local/opt/lua

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/opt/gpgme/include -I/usr/local/opt/libassuan/include -I/usr/local/opt/libgpg-error/include -I/usr/local/Cellar/neomutt/20200626/include -I/usr/local/opt/lua/include/lua5.3 -DNCURSES_WIDECHAR -I/usr/local/opt/openssl@1.1/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn -inotify
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl
  +smime -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/Cellar/neomutt/20200626/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/Cellar/neomutt/20200626/etc"

**Comment by flatcap** [comment]
Hi @bmclean2,

> Mouse scrolling works as expected in man, less

Really?  They don't for me.
If you page down a few times, then scroll backwards, it works but that's the **terminal** being scrolled, not _less_.

> vim

Fair enough, that has full mouse support.

> Expected Behaviour
> Scrolling in the pager using trackpad/mouse should be going to next/previous line

Mutt and NeoMutt don't support the mouse.  They never have.
<sub>but if you look very hard you _might_ find evidence of change (but that's some time away)</sub>

> and the index in neomutt

However, ncurses (which manages the key presses) magically transforms the scroll-wheel into <kbd>\<Up\></kbd> and <kbd>\<Down\></kbd>.

> `bind index \031 previous-undeleted`
> `bind index \005 next-undeleted`
> `bind pager \031 previous-line`
> `bind pager \005 next-line`

Hmm... those don't work for me, but _these_ do:

```
bind index <down> previous-undeleted
bind index <up>   next-undeleted
bind pager <down> next-line
bind pager <up>   previous-line
```

P.S.  I guess the reference to Pull-Request 2015 is a typo (at the very beginning of your issue).

**Comment by bmclean2** [comment]
> Hi @bmclean2,

> Really? They don't for me.
> If you page down a few times, then scroll backwards, it works but that's the **terminal** being scrolled, not _less_.

Yep, they work for me. If I understand you correctly, in man or less you aren't able to scroll down with the mouse upon opening the program—I am able to.
 
> However, ncurses (which manages the key presses) magically transforms the scroll-wheel into <Up> and <Down>.

> Hmm... those don't work for me, but _these_ do:
> 
> ```
> bind index <down> previous-undeleted
> bind index <up>   next-undeleted
> bind pager <down> next-line
> bind pager <up>   previous-line
> ```

These work, thanks! I got the other codes from Luke Smith's Mutt Wizard. Is there any way these mouse wheel bindings could be added to the Configuration page on neomutt.org? 

> P.S. I guess the reference to Pull-Request 2015 is a typo (at the very beginning of your issue).

Yep, sorry.

**Comment by flatcap** [comment]
> scroll down with the mouse upon opening the program—I am able to

Oh, that's good :-)
I wonder how that works

> These work, thanks!

Great

**Comment by axelsimon** [comment]
@flatcap I would argue that this is still a bug.

If by mistake you wheel in an email, you end up loading the next 15 emails, without any clear indication of how to stop this. If,`$DEITY` forbid, one of those emails has a large attachment, then #2004 kicks in and you may as well go get a cup of tea :)

If you use <kbd>ctrl</kbd>+<kbd>c</kbd> you can stop the loading of the next email(s), but that's far from obvious.

I suggest if possible that neomutt make ncurses not catch any mouse wheel input by default, unless specifically configured by the user, as the default behaviour is just very unlikely to be desirable by anyone.

**Comment by flatcap** [comment]
> I would argue that this is still a bug.

It's a _feature_ that's been in (Neo)Mutt forever...
(though the word 'mouse' doesn't appear anywhere in the source or docs)

> default behaviour is just very unlikely to be desirable by anyone

Yeah, probably true.

> If by mistake you wheel in an email, you end up loading the next 15 emails

Adding this config prevents that problem:
You won't leave the pager, unless you `<next-entry>`, `<previous-entry>` or `<quit>`

```
set pager_stop = yes
bind pager <down> next-line
bind pager <up>   previous-line
```

This makes the mouse behave predictably in the Index and Pager.
I'd rather recommend this to users, than alter default bindings, disable the mouse,
or add a mouse config that will change in the not-too-distant future.
