### ISSUE TITLE
Does not build in MacOS 10.5

### ISSUE THREAD

**Issue by lbschenkel** [neomutt/neomutt#2569]
Hi, I'm the downstream maintainer of NeoMutt for MacPorts. I got a report from an user that NeoMutt `20200501` does not build in MacOS 10.5 due to missing symbol `strndup` [1][2]. This was addressed downstream by using `legacysupport` [3].

Reporting it here because this might be something you want to fix upstream, depending on how badly you want NeoMutt to keep building in old systems.

[1] https://trac.macports.org/ticket/60898
[2] https://trac.macports.org/attachment/ticket/60898/main.log
[3] https://github.com/macports/macports-legacy-support

**Comment by gahr** [comment]
You are right - strndup is in POSIX:2008, which we never explicitely states as a dependency. I'll come up with a fallback.

**Comment by lbschenkel** [comment]
OK. Regarding downstream packaging in MacPorts, I can keep using `legacysupport` which is nice for me as a maintainer because it'll automatically provide common missing symbols in old systems and reduce the likelihood of breaking, but that also means that'll hide problems like this in upstream code. Do you have any opinion as the upstream maintainer?

**Comment by gahr** [comment]
I think it's best if you'd build without legacysupport and report failures to us, if you have access to older macs.

**Comment by lbschenkel** [comment]
> I think it's best if you'd build without legacysupport and report failures to us, if you have access to older macs.

I actually don't, so I have to rely on users reporting to me that is broken. So there may be a long interval between someone reporting that to me (if they do report at all), I relaying this upstream, and that getting fixed. I'm afraid that `legacysupport` enabled is what's best for users in these circumstances, even if it's worse for us.

**Comment by gahr** [comment]
That makes sense.

**Comment by flatcap** [comment]
@lbschenkel 
Ages ago, the [[devel/macports]](https://github.com/neomutt/neomutt/tree/distro/macports) branch stopped building (for non-code reasons).
([Travis build log](https://travis-ci.com/github/neomutt/neomutt/builds/178731365))

Would you have some time to take a look and fix it?
Thanks.

**Comment by lbschenkel** [comment]
I may, but probably not today (or even this week).

**Comment by flatcap** [comment]
Thanks.  There's no rush.
