### ISSUE TITLE
Allow use of password managers

### ISSUE THREAD

**Issue by mdosch** [neomutt/neomutt#2570]
From your website:

```
imap_pass

Type: string
Default: ""

Specifies the password for your IMAP account. If unset , NeoMutt will prompt you for your password when you invoke the <imap-fetch-mail> function or try to open an IMAP folder.

Warning : you should only use this option when you are on a fairly secure machine, because the superuser can read your neomuttrc even if you are the only one who can read the file.
```

## What would you like to be able to do?

I'd like to be able to invoke my password manager instead of storing it in plaintext, e.g. like:

```
imap_pass eval_password pass email/me@example.com
```

This is already supported in the TUI XMPP client profanity with [`eval_password` setting in `account`](https://profanity-im.github.io/guide/090/reference.html#account).

## What needs to change in NeoMutt?

I don't know what needs to be done to support this.

## Have you tried any alternative methods?

Right now I'm not connecting directly via IMAP but fetch my email with mbsync and send them with msmtp which both support password managers.

## Additional Info

none

**Comment by jindraj** [comment]
This is already possible. See unix stackexchange [answer](https://unix.stackexchange.com/a/20572/85046)

**Comment by mdosch** [comment]
Thanks for the answer, I didn't know it's already possible. Maybe this could be added to the docs?

**Comment by jindraj** [comment]
It's already there - [docs](https://neomutt.org/guide/configuration#3-%C2%A0syntax-of-initialization-files), or open neomuttrc(5) man pages and search for backticks.
