### ISSUE TITLE
Unsubscribe from browser crashes sidebar

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#2575]
## Expected Behaviour

Unsubscribing from a mailbox from within the browser view should not crash the sidebar.

## Actual Behaviour

Unsubscribing from a mailbox from within the browser crashes the sidebar the next time the sidebar is displayed. This happens because the `win_sidebar` variable is `NULL` when unmailboxes is reached from within the browser window, hence the sidebar fails to update its data. This results in the sidebar having a dangling pointer to a mailbox that does not exist anymore.

https://github.com/neomutt/neomutt/blob/887428a38f845f9eaca80c3e05e0c2aedb137669/command_parse.c#L1970-L1971

## Steps to Reproduce

1. Open NeoMutt
2. From the index view, `:subscribe-to +Bar`
3. `c?`
4. `:unsubscribe-from +Bar`
5. `q` --> CRASH

## How often does this happen?

- Always

## When did it start to happen?

Bisect points to aeafcb0.

**Comment by gahr** [comment]
Bisect points to aeafcb065f45cd44cbcffbf1dadd780c3d684e56.

**Comment by flatcap** [comment]
I can imagine what's going wrong, but I can't repeat it.
I'm using a minimal config:
```
set imap_user = "USER"
set imap_pass = "PASS"
set imap_check_subscribed = yes

set folder = imap://example.com/
set spoolfile = "+INBOX"

set sidebar_visible = yes
```

After quitting the browser, the mailbox is still there in the sidebar and I can open it.
