### ISSUE TITLE
Garbled index with unicode strings

### ISSUE THREAD

**Issue by somini** [neomutt/neomutt#258]
There's a bug when including unicode characters in the `to_chars` variable. Mutt seemingly doesn't split the string properly and the result is a garbled characters. I've attached a screenshot with the characters produced.
![2016-11-28t01 39 10 00 00](https://cloud.githubusercontent.com/assets/1750665/20653868/816ca514-b50b-11e6-8d77-72d58989e64d.png)

The relevant entries in my muttrc:

    set index_format = "%F %T[%Z] %s"
    set to_chars = " ↓⇊↯↑L"
    set sidebar_format = "%B%<N?☼%N>%* %<S?%<F?%F★>%S>"

I'm using urxvt on Arch Linux.
```
~ mutt -v
NeoMutt 20161104 (1.7.1)
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.

System: Linux 4.8.8-2-ARCH (x86_64)
libidn: 1.33 (compiled with 1.33)
hcache backend: GDBM version 1.12. 16/05/2016 (built May 31 2016 18:36:34)

Compiler:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.2.1 20160830 (GCC) 

Configure options: '--prefix=/usr' '--sysconfdir=/etc' '--enable-debug' '--enable-pgp' '--enable-gpgme' '--enable-notmuch' '--enable-pop' '--enable-imap' '--enable-smtp' '--enable-hcache' '--enable-sidebar' '--enable-compressed' '--with-gss=/usr' '--with-ssl=/usr' '--with-sasl' '--with-curses=/usr' '--with-regex' '--with-idn' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2'

Compilation CFLAGS: -Wall -pedantic -Wno-long-long -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-delete-null-pointer-checks

Compile options:
+CRYPT_BACKEND_CLASSIC_PGP +CRYPT_BACKEND_CLASSIC_SMIME +CRYPT_BACKEND_GPGME 
+DEBUG -DL_STANDALONE +ENABLE_NLS -EXACT_ADDRESS -HOMESPOOL -LOCALES_HACK 
-SUN_ATTACHMENT +HAVE_BKGDSET +HAVE_COLOR +HAVE_CURS_SET +HAVE_GETADDRINFO 
+HAVE_GETSID +HAVE_ICONV +HAVE_LANGINFO_CODESET +HAVE_LANGINFO_YESEXPR 
+HAVE_LIBIDN +HAVE_META -HAVE_REGCOMP +HAVE_RESIZETERM +HAVE_START_COLOR 
+HAVE_TYPEAHEAD +HAVE_WC_FUNCS +ICONV_NONTRANS +USE_COMPRESSED +USE_DOTLOCK 
+USE_FCNTL -USE_FLOCK -USE_FMEMOPEN +USE_GNU_REGEX +USE_GSS +USE_HCACHE 
+USE_IMAP +USE_NOTMUCH -USE_NNTP +USE_POP +USE_SASL -USE_SETGID +USE_SIDEBAR 
+USE_SMTP -USE_SSL_GNUTLS +USE_SSL_OPENSSL 
-DOMAIN
-MIXMASTER
-ISPELL
SENDMAIL="/usr/sbin/sendmail"
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/mutt"
SYSCONFDIR="/etc"
EXECSHELL="/bin/sh"

patch-attach-headers-color-neomutt
patch-compose-to-sender-neomutt
patch-compress-neomutt
patch-cond-date-neomutt
patch-encrypt-to-self-neomutt
patch-fmemopen-neomutt
patch-forgotten-attachments-neomutt
patch-ifdef-neomutt
patch-index-color-neomutt
patch-initials-neomutt
patch-keywords-neomutt
patch-kyoto-neomutt
patch-limit-current-thread-neomutt
patch-lmdb-neomutt
patch-multiple-fcc-neomutt
patch-nested-if-neomutt
patch-new-mail-neomutt
patch-nntp-neomutt
patch-notmuch-neomutt
patch-progress-neomutt
patch-quasi-delete-neomutt
patch-reply-with-xorig-neomutt
patch-sensible-browser-neomutt
patch-sidebar-neomutt
patch-skip-quoted-neomutt
patch-smime-encrypt-self-neomutt
patch-status-color-neomutt
patch-timeout-neomutt
patch-tls-sni-neomutt

To learn more about NeoMutt, visit: http://www.neomutt.org/
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by somini** [comment]
I forgot to mention that the problem doesn't seem to be related to my unicode terminal configuration, because the sidebar works well with the unicode characters in in `sidebar_format`.

**Comment by flatcap** [comment]
Mutt can't do that, but now NeoMutt can!
I'm even thinking of adopting your choice of `$to_chars` :-)

If you know how and are able to test this, I'd appreciate it.
The code is in the [issue/258] branch.

**Comment by darnir** [comment]
Worked for me.

@somini : I'm copying your `$to_chars` as well. Thanks!

**Comment by nobrowser** [comment]
Speaking of to_chars: has neomutt staff considered adding my from_chars?

https://github.com/nobrowser/mutt/commit/4ab95c14b7d6522ec582c9fa6c0f51c2de03bcaf

**Comment by somini** [comment]
Works for me, many thanks for the fast reply.

I'm just starting on mutt, but the %Z format baffled me, and I found no other way of including character on the format string depending on message flags, like read/unread.

**Comment by flatcap** [comment]
@nobrowser 

> has the neomutt staff...

I thought we were an Autonomous Collective :-)

I/We weren't aware of your patch.  I'm looking at it now.
I'm just going to tweak it to allow Unicode characters.

I'll probably merge them both for the next release.

Thanks.

**Comment by somini** [comment]
Maybe I should open another issue, but is there a way to customize the "new", "important" and such flags?

**Comment by flatcap** [comment]
Hmm... They're hardcoded in `hdrline.c`.
It wouldn't be a difficult change, but I don't have time for it at the moment.
I didn't have time for this either :-)

Create a new issue asking for an enhancement and explain your idea.

**Comment by somini** [comment]
Maybe I'll make it my first PR... Thanks for everything.

**Comment by flatcap** [comment]
That'd be brilliant.  If you need any help understanding Mutt, just ask.
We're also quite active in our IRC channel: #neomutt on irc.freenode.net

**Comment by nobrowser** [comment]
flatcap, if you need more support from me (like a PR) just ask. It wouldn't be my first :-)

**Comment by nobrowser** [comment]
I can't really carry a conversation on IRC at my age, though.  Sorry about that.

**Comment by flatcap** [comment]
@nobrowser 

> if you need more support from me (like a PR) just ask

Thanks, will do.

If you have any more patches, that we should know about, please let us know.
Alternatively, we've got plenty of [easy(-ish) jobs](https://github.com/neomutt/neomutt/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Aeasy%20no%3Aassignee) up for grabs.

> I can't really carry a conversation on IRC at my age, though

Not a problem.  I'm happy to converse, here, in the issues, or on our [mailing lists](http://mailman.neomutt.org/mailman/listinfo)

**Comment by flatcap** [comment]
@nobrowser 
I've committed your feature.  Thanks.
I made a few slight tweaks, notably:

- Altered to allow unicode characters
- Added a space after the prefix char (^M still means no prefix, no space)

The added space means that you can now use wider characters such as ◎, ☼, ★
(Wider meaning taking two screen columns)

I _did_ notice one slight bug in ncurses.
If you mix wide (★) and narrow (↯) characters, it leads to some visual artifacts.
