### ISSUE TITLE
Reply-To: isn't honored

### ISSUE THREAD

**Issue by riesebie** [neomutt/neomutt#2581]
Replying to a mail with an Reply-To: header replies to From:

## Expected Behaviour

Reply to Reply-To: Address

## How often does this happen?
- Always

## When did it start to happen?

Running  NeoMutt 20200807

**Comment by gahr** [comment]
I cannot reproduce this:

```
$ cat <<EOF > test-mbox
From foo@example.com Fri Sep  8 01:48:47 2000
Message-Id: <foobar.example.com>
To: foo@example.com
Subject: Foo bar
Reply-To: bar@example.com
Date: Fri, 08 Sep 2000 01:48:45 -0700
From: Baz <baz@example.com>
Status: RO
Content-Length: 12
Lines: 1

Foo bar baz

EOF

$ neomutt -F /dev/null -n -f test-mbox -e "push r"
```

Result in neomutt showing a prompt `Reply to bar@example.com? ([yes]/no):`.

Do you get different results with this simple setup? If you don't, you'll have to be a bit more precise about your setup, config, etc.

**Comment by riesebie** [comment]
Take the attached mail as an example. It is from a public mailing list
[reply-test-mbox.gz](https://github.com/neomutt/neomutt/files/5063466/reply-test-mbox.gz)

**Comment by flatcap** [comment]
Hmm... that's not a valid mbox.
If I remove the `[...]` then reply, I get asked to use the `Reply-To:` address.

This is using NeoMutt 2020-08-07, with zero config:  `neomutt -n -F /dev/null -f reply-test-mbox`

```
Reply to support@hostsharing.net? ([yes]/no):
```

Answer `y`

```
To: Öffentliche_Mailingliste_zur_technischen_Unterstützung_Community_Support <support@hostsharing.net>
```

**Comment by riesebie** [comment]
Well, I've ` set ignore_list_reply_to = yes`. Unsetting gets me back to the `Reply-To:` header. But I am using this for ages and for instance in other mailing lists the `Reply-To:` address is honored. Anyway I'll unset `ignore_list_reply_to`.
