### ISSUE TITLE
Add validators for {imap,pop,smtp,nntp}_authenticators

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#2583]
The config system can already validate several types of data.
For cases when it can't, we can use a validator function.

For example:

https://github.com/neomutt/neomutt/blob/797b99985644a23045b71bca8aef552a743bdb55/send/config.c#L269-L271

When setting `$wrap_headers`, the config system checks the variables type:
- Number, `DT_NUMBER`
- May not be negative, `DT_NOT_NEGATIVE`

If these tests are passed, the config system then calls the validator function which adds extra constraints
(the number must be between 78 and 998).

https://github.com/neomutt/neomutt/blob/797b99985644a23045b71bca8aef552a743bdb55/send/config.c#L40-L53

---

There are four authenticator config variables that aren't validated in any way.
- [`$imap_authenticators`](https://github.com/neomutt/neomutt/blob/master/imap/config.c#L74-L76), which is limited to [`imap_authenticators[]`](https://github.com/neomutt/neomutt/blob/master/imap/auth.c#L57-L72)
- [`$pop_authenticators`](https://github.com/neomutt/neomutt/blob/master/pop/config.c#L53-L55), which is limited to [`pop_authenticators[]`](https://github.com/neomutt/neomutt/blob/master/pop/auth.c#L380-L386)
- [`$smtp_authenticators`](https://github.com/neomutt/neomutt/blob/master/send/config.c#L241-L243), values are mentioned in [`smtp_auth()`](https://github.com/neomutt/neomutt/blob/master/send/smtp.c#L606)
- [`$nntp_authenticators`](https://github.com/neomutt/neomutt/blob/master/nntp/config.c#L81-L83), values are [mentioned here](https://github.com/neomutt/neomutt/blob/master/nntp/nntp.c#L602)

Challenge:
- Create an array of valid values for smtp and nntp
- Add a validator function for each config variable

Each config variable is a colon-separated list of strings.
There are functions in [`mutt/slist.c`](https://github.com/neomutt/neomutt/blob/master/mutt/slist.c) and [`config/slist.c`](https://github.com/neomutt/neomutt/blob/master/config/slist.c) that will help parse the strings.

**Comment by yousefakbar** [comment]
> Create an array of valid values for smtp and nntp

@flatcap  For nntp, what kind of array is preferred? Below is the array I made for smtp_authenticators:

https://github.com/neomutt/neomutt/blob/ad2aa0c888c13a95309fd0f8fc2a1bf9428ac3c8/send/smtp.c#L618-L626

NNTP does not have individual authentication functions like `smtp_auth_sasl` etc. They all seem to be contained in one function [`nntp_auth`](https://github.com/neomutt/neomutt/blob/ad2aa0c888c13a95309fd0f8fc2a1bf9428ac3c8/nntp/nntp.c#L528).

What is the desired approach here? Should I just implement an array of strings corresponding to accepted auth methods? Or does this warrant some change to the `nntp_auth` function to keep it consistent with the rest of the protocol authentication functions?

**Comment by flatcap** [comment]
> Should I just implement an array of strings corresponding to accepted auth methods?

Yes, that sounds good.

> NNTP does not have individual authentication functions like `smtp_auth_sasl`
> Or does this warrant some change to the `nntp_auth` function to keep it consistent with the rest of the protocol authentication functions?

Leave it for now.  I've made a note (to think about it :-)
(The NNTP backend needs a lot of love)
