### ISSUE TITLE
Formatting of fake mailboxes in sidebar

### ISSUE THREAD

**Issue by protist** [neomutt/neomutt#2586]
I'm trying to use fake mailbox names in the sidebar. In `~/.mutt/muttrc`:
```
named-mailboxes 'Inbox' '+dummy_dividers/Inbox' \
  '  main' +alias-inbox/main \
  '  work' +alias-inbox/work \
  '  admin' +alias-inbox/admin \
  'Archives' '+dummy_dividers/Archives' \
  '  main' +alias-archives/main \
  '  work' +alias-archives/work \
  'Sent' '+dummy_dividers/Sent' \
  '  main' +alias-sent/main \
  '  work' +alias-sent/work
```

I also have mail counts next to each entry:
```
set sidebar_format = '%D%* %?N?%N/?%S'
```
In neomutt, this renders as follows:
```
Inbox          0
  main        17
  work      1/26
  admin        1
Archives       0
  main      5225
  work      3484
Sent           0
  main      5225
  work      9283
```

Is it possible to tweak the formatting of the fake entries? Specifically, could we (1) remove the `0` count, and (2) make them stand out more, e.g. with some colouring?

EDIT: Actually in the example above, the ordering is wrong, with almost all of the fake mailboxes are at the end.

```
Inbox          0
  main        17
  work      1/26
  admin        1
  main      5225
  work      3484
  main      5225
  work      9283
Archives       0
Sent           0
```
I tried to remove all extraneous items from my `muttrc`, but the order is still all mixed up. I tried an explicit `set sidebar_sort_method = unsorted`, but it made no difference.

**Comment by tonymugen** [comment]
Similar issue: as of version 20200814-1 the fake mailboxes are all at the end in the sidebar unless listed ahead of all real mailboxes (in that case they are on top).

**Comment by flatcap** [comment]
When you add Mailboxes (named, real, fake), their order is preserved.
This is what you see in the sidebar.

But, if you set `$sidebar_sort_method`, the original order is lost and you can't get it back (yet).

**Comment by protist** [comment]
@flatcap Sorry, this issue got all confused! I actually didn't have `$sidebar_sort_method` anywhere originally, when the order was mixed up. However, I tried to add it later to troubleshoot. Without `$sidebar_sort_method`, the order is still mixed up.

**Comment by flatcap** [comment]
As for highlighting.  Not yet.
The `0` (zero) can easily be hidden by using another conditional in the format string:
```
set sidebar_format = '%D%* %<N?%N/>%<S?%S>'
```

Which says:
- `%<N?%N/>` if there are new emails, print the number and a `/`
- `%<S?%S>` if there more than zero emails, print the number

**Comment by flatcap** [comment]
@protist 
Then I don't know.
I copied your mailbox layout and used a minimal config file and my mailboxes were in the correct order
(using NeoMutt 2020-08-17)

**protist.rc**
```
set folder=.
set sidebar_visible=yes

named-mailboxes 'Inbox' '+dummy_dividers/Inbox' \
  '  main' +alias-inbox/main \
  '  work' +alias-inbox/work \
  '  admin' +alias-inbox/admin \
  'Archives' '+dummy_dividers/Archives' \
  '  main' +alias-archives/main \
  '  work' +alias-archives/work \
  'Sent' '+dummy_dividers/Sent' \
  '  main' +alias-sent/main \
  '  work' +alias-sent/work
```

Then run `neomutt -n -F protist.rc`

```
Inbox
  main
  work
  admin
Archives
  main
  work
Sent
  main
  work
```

**Comment by protist** [comment]
>  The `0` (zero) can easily be hidden by using another conditional in the format string:

That works fantastically. Thank you!

> Then I don't know.
> I copied your mailbox layout and used a minimal config file and my mailboxes were in the correct order
> (using NeoMutt 2020-08-17)

Thanks for checking @flatcap. Let me do some more troubleshooting and get back to you.

**Comment by protist** [comment]
Okay, so firstly, using the identical rc and command as you, the order is mixed up on my system.

```
Inbox
  main
  admin
  main
  main
  work
Archives
  work
Sent
  work
```

(FWIW this is the latest tagged release, i.e. 20200814, not 20200817, right?)

If I revert to 20200626, the order is as expected.

I then did a `git bisect`. The first bad commit was aeafcb065f45cd44cbcffbf1dadd780c3d684e56.

**Comment by flatcap** [comment]
> (FWIW this is the latest tagged release, i.e. 20200814, not 20200817, right?)

*ahem*, I've fixed my typo

>  the order is mixed up on my system

What type of mailbox... oh.
I think I know what's going on (for you too @tonymugen).

The mailboxes are being grouped by *type*, into Account objects.

If your mail is in Maildir directories, but the fake entries are Mbox files, then you'll end up with some odd sorting.

**Workaround**: change `dummy_dividers/Archives` (file) into three dirs:
(assuming your folders are in Maildir format)

- `dummy_dividers/Archives/cur`
- `dummy_dividers/Archives/new`
- `dummy_dividers/Archives/tmp`

> If I revert to 20200626, the order is as expected.

Yes, I see that too

> `git bisect`. The first bad commit was [aeafcb0](https://github.com/neomutt/neomutt/commit/aeafcb065f45cd44cbcffbf1dadd780c3d684e56)

Thanks, I'll have a think about what to do.

**Comment by protist** [comment]
Aha! Yes, that works perfectly. Thank you! Yes, your presumptions were correct.

You probably worked it out, but to created the fake entries, I just `touch`ed an empty file into existence. I'm presuming that this is the only way of faking sidebar entries, with a blank file or maildir directory?

**Comment by flatcap** [comment]
> I'm presuming that this is the only way of faking sidebar entries, with a blank file or maildir directory?

Yes, for now.
I have some ideas, but they'll need a little more thought first.

**Comment by tonymugen** [comment]
Confirming that the workaround works for me, too. Thanks, @flatcap

**Comment by xiangsheng** [comment]
I use a fake mailbox named "============" as a separator. Now, it seems that only one such separator can appear in the sidebar. Any workaround?

**Comment by mschilli87** [comment]
Maybe

```
"============"
"============ "
"============  "
```
?

**Comment by protist** [comment]
I think you need a different "real" mailbox for each. e.g.
```
named-mailboxes \
  '========' +dummy_dividers/sep1 \
  '========' +dummy_dividers/sep2
```

@flatcap Do you want me to close this issue? We got a bit sidetracked, but the only outstanding part is potentially colouring items in the sidebar.

**Comment by flatcap** [comment]
> Do you want me to close this issue?

Yes please.

> We got a bit sidetracked

Not a problem :-)

> colouring items in the sidebar

I haven't thought about this before.

Have a think about what you want to colour.
How would you configure it?
There's the [Status Colour feature](https://neomutt.org/feature/status-color) -- might _that_ be a model?

When you've got some ideas, raise an Enhancement issue and we can discuss how it'd all work
(and try to encourage a developer to take on the task :-)

> Oh, and also a easier way to fake mailboxes,
> and fixing the maildir/mbox ordering issue

I have ideas, but I'm still thinking about them.
