### ISSUE TITLE
Same-msgid message scrolling broken

### ISSUE THREAD

**Issue by nabijaczleweli** [neomutt/neomutt#2588]
## Expected Behaviour

Scrolling past same-msgid messages, it should work as normal.

## Actual Behaviour

Given two same-msgid messages:
| Opened     | Direxion | What                                                          | Should it do this |
| ---------- | ---------| ------------------------------------------------------------- | ----------------- |
| top one    | up       | scrolls off                                                   | yes               |
| top one    | down     | scrolls to bottom one                                         | yes               |
| bottom one | up       | scrolls past the top one, onto the message before the top one | no                |
| bottom one | down     | no scroll                                                     | no                |

Also, when on the bottom one quitting leaves the index cursor on the top one.

Have a video: https://youtu.be/Kj5tVdmHPt4

## Steps to Reproduce

Trivially: send a mail to yourself, or copy this mbox into a folder: [dupe.gz](https://github.com/neomutt/neomutt/files/5078527/dupe.gz).

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

Regression against 2020-06-26.

## NeoMutt Version
2020-08-14 + #2585 
```
NeoMutt 20200814
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.19.0-10-amd64 (x86_64)
ncurses: ncurses 6.1.20181013 (compiled with 6.1.20181013)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.12.0
GnuTLS: 3.6.7
libnotmuch: 5.2.0
storage: tokyocabinet
compression: zlib, zstd

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet --zlib --zstd --testing

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/home/nabijaczleweli/backports/build-output/neomutt-20200814+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +regex +sasl
  +smime -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Buster
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? either

**Comment by gahr** [comment]
This is definitely due to #2413. I don't know how it should be fixed right now, but I'll have a closer look next week.

**Comment by gahr** [comment]
This was actually introduced by my previous PR, #2411. I am still thinking of a sane way to fix this.

**Comment by nabijaczleweli** [comment]
This bit me once more just now, and a bit worse than before, this time on mails that *had no msgid* (okay, the cover letter did, but the rest didn't): [v4.gz](https://github.com/neomutt/neomutt/files/5125523/v4.gz)

And another video: https://youtu.be/240bXc-lKi4

**Comment by gahr** [comment]
I am not sure an email without a message-id is a "legitimate use-case". [RFC2822, 3.6.4](https://tools.ietf.org/html/rfc2822#section-3.6.4) says *Though optional, every message SHOULD have a "Message-ID:" field.* (see [RFC2119, 3](https://tools.ietf.org/html/rfc2119#section-3) for what SHOULD means in this context).

 I am still unsure on the proper way to fix this bug. I recognize duplicate msg-id could be a thing, but I am a bit less keen on fixing the missing msg-id case.

**Comment by nabijaczleweli** [comment]
2c01acf07a602ab540ca6dd7ced06fffeb541e93 from `devel/issue-2588` works a treat

**Comment by gahr** [comment]
Thanks - it's a step forwards but it still has issues, I am on it.
