### ISSUE TITLE
Address Book - Live Sorting

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#2589]
The Address Book shows a list of email aliases.
You can open the Address Book by composing an email: <kbd>m</kbd> (`<mail>`) and <kbd>\<Tab\></kbd> (`<complete>`).

<img width="400" src="https://raw.githubusercontent.com/neomutt/gfx/master/screenshots/screenshot/dlg-alias-100.svg">

The sort order is controlled by `$sort_alias`.

Curently, if you change the sort order, whilst in the Address Book, nothing happens.

## Task 1

Add an 'observer' function that listens for any config changes.
We already have one observer, that listens for changes to the alias data:

https://github.com/neomutt/neomutt/blob/5abcbeda3759228887ebf0c83c98333676d197c5/alias/dlgalias.c#L205

Add one that listens for `DT_CONFIG`.
If it receives a notification, check that it's for `$sort_alias` and then sort the data.

## Task 2

Add two functions to make sorting easier.

The Index View (email list) has two functions `<sort-mailbox>`, `<sort-reverse>`
They show a menu: `Rev-Sort (d)ate,(f)rm,(r)ecv,(s)ubj,t(o),(t)hread,(u)nsort,si(z)e,s(c)ore,s(p)am,(l)abel?`

Create two new alias functions: `<sort-alias>` and `<sort-alias-reverse>` that set `$sort_alias`.

**Comment by RomeuG** [comment]
Hello!

About this line in the issue:

`Create two new alias functions: <sort-alias> and <sort-alias-reverse> that set $sort_alias.`

Shouldn't both alias functions be '<sort-alias-address>` and `<sort-alias>` ?

I am saying this because `$sort_alias` has no reverse in the documentation:

```
       sort_alias
              Type: sort order
              Default: alias

              Specifies how the entries in the "alias" menu are sorted.  The following are legal values:
              ‐ address (sort alphabetically by email address)
              ‐ alias (sort alphabetically by alias name)
              ‐ unsorted (leave in order specified in .neomuttrc)
```

Thanks!

**Comment by flatcap** [comment]
Hi @RomeuG,

> Shouldn't both alias functions be `sort-alias-address` and `sort-alias` ?

They _could_ be, but I had something different in mind.
My `<sort-alias>` would bring up a menu to choose from.

> I am saying this because `$sort_alias` has no reverse in the documentation:

Not yet :-)

There are a lot of screens in NeoMutt and they all work _slightly_ differently.
This issue would add sorting functions, a reverse-sort option and maybe even a 'limit' command.
That would make it work much more like the Index screen.

Once done, it'd be easy to do the same for the Query screen.

Are you interested in a challenge?

**Comment by RomeuG** [comment]
Indeed I am! I have done task 1.
I will be doing task 2.

I will keep in mind what you said about the functions.
Any other suggestions?

I am still trying to understand the general codebase, although the first task was very easy.

**Comment by flatcap** [comment]
> Indeed I am! I have done task 1

Brilliant!

> Any other suggestions?

Nothing at the moment.

> I am still trying to understand the general codebase

It's a lot to take in, so feel free to ask lots of questions.

**Comment by flatcap** [comment]
> Any other suggestions?

One other thing from my notes: the actual sort function.
Currently, we use `mutt_istr_cmp()` -- a case-insensitive sort.
This means that my poor friend Øyvind ends up at the end of the list.

I think we should sort the aliases and addresses using `mutt_str_coll()` -- a [collation sort](https://en.wikipedia.org/wiki/Collation).

**Comment by RomeuG** [comment]
Hello!

I want to take my time doing this, I want to do it right.

Also, it makes sense to create a new function similar to `mutt_select_sort` but specific for the alias window, correct?

Thanks!

**Comment by flatcap** [comment]
> create a new function similar to `mutt_select_sort` but specific for the alias window

Yep, that's sounds great.

**Comment by RomeuG** [comment]
Just one last question for the day:

How would I go on about adding strings like `_("")` and updateing the po files?
I do understand it uses gettext, but what about the automatic way of building this?
I see there is something called autosetup, but probably I am missing something?

Thanks!

**Comment by flatcap** [comment]
> How would I go on about adding strings like `_("")` and updating the po files?

`make update-po` re-syncs the po files to the source, but you don't need to do that.

The po files contain the source file locations of the strings, in `#:` comments.
Running `make update-po` creates an **enormous** diff even if no strings have changed.

Because of this, the translators have a separate branch [[translate]](https://github.com/neomutt/neomutt/tree/translate), which I sync every few weeks.

> there is something called autosetup

That's the machinery that powers `./configure` and `auto.def` contains our configuration options.
