### ISSUE TITLE
Build system change makes difficult to find requirements if relative to subdir

### ISSUE THREAD

**Issue by Vaelatern** [neomutt/neomutt#259]
`configure: error: You need Tokyo Cabinet, Kyoto Cabinet, QDBM, GDBM, Berkeley DB or LMDB for hcache`
This error only appears in the latest release (20161126) and did not previously. Ironically, I suspect it to be the fault of this changelog item `Improve discovery for the Berkeley Database (@gahr)`.

**Comment by Vaelatern** [comment]
I suspect this commit f97a4c47816d2c984d7ec6d001c7042e42b4b324 does not account for enough, and will be exploring further.

**Comment by flatcap** [comment]
Hi @Vaelatern.

> difficult to find requirements if relative to subdir

Sorry, I don't understand.  We've had some bugs before where a distro was building _out-of-tree_.
If that's what you're doing, please can you give me some instructions to follow.

> ... and will be exploring further

Thanks.

**Comment by Vaelatern** [comment]
I have solved by attaching `--with-gdbm` to the configure arguments. It should be noted that this option is marked `(default)` in the `./configure --help` output, but I am now considering this issue closed, as the build system does work as it was told to.
