### ISSUE TITLE
named-mailboxes broken between 20200626…20200807

### ISSUE THREAD

**Issue by flokli** [neomutt/neomutt#2593]
## Expected Behaviour

I use the `named-mailboxes` feature to give some notmuch queries nicer names:

```
named-mailboxes \
       " 💩 flokli 💩"            "notmuch://?query=tag:flokli and (tag:inbox or tag:new)" \
       "  - FollowUp"              "notmuch://?type=messages&query=tag:flokli and tag:followup" \
       "  - Hold"                  "notmuch://?type=messages&query=tag:flokli and tag:hold" \
…
```

This worked for quite some time

## Actual Behaviour
Upgrading from 20200626 to 20200807 seems to have broken this. Instead of the descriptions, I now see the query with `notmuch://?` stripped as descriptions.

## Steps to Reproduce
See config snippt from above

## How often does this happen?

- Always

## When did it start to happen?

updating to 20200807 from 20200626

## NeoMutt Version

```
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.7.13 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.36 (compiled with 1.36)
GPGME: 1.14.0-unknown
OpenSSL: OpenSSL 1.1.1g  21 Apr 2020
libnotmuch: 5.3.0
storage: lmdb
compression: zlib

Configure options: --prefix=/nix/store/h4qw91d8d2s7hgrfj5679xna30rgvbyz-neomutt-20200814 --enable-autocrypt --gpgme --gss --lmdb --notmuch --ssl --sasl --with-homespool=mailbox --with-mailpath= --disable-include-path-in-cflags ac_cv_path_SENDMAIL=sendmail --zlib

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache +homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="mailbox"
PKGDATADIR="/nix/store/h4qw91d8d2s7hgrfj5679xna30rgvbyz-neomutt-20200814/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/nix/store/h4qw91d8d2s7hgrfj5679xna30rgvbyz-neomutt-20200814/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* NixOS unstable
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? Notmuch

**Comment by Austin-Ray** [comment]
In `sidebar_format`, change `%B` to `%D`. There was a patch that fixed a bug where named-mailboxes didn't respect `%B` which is for mailbox paths.

**Comment by flokli** [comment]
This worked for me, thanks!

Is there any chance things requiring config change could be added to the changelogs?

Also ran into `pgp_replysign` suddenly habing disappeared.

**Comment by flatcap** [comment]
> Is there any chance things requiring config change could be added to the changelogs?

There's a "Changed Config" section in the recent Release Notes / Changelogs.
I try to remember everything.

> Also ran into `pgp_replysign` suddenly having disappeared.

Interesting.  You've discovered a bug in some recent changes to the send code (I've just pushed a fix).

However... `pgp_replysign` was [deprecated](https://github.com/neomutt/neomutt/commit/49dea5cb6747ff8573ef984180e8338dcbbdd7fa) in **2002** by **mutt** (in favour of `crypt_replysign`).

**Comment by flokli** [comment]
Heh, maybe we should show warnings during startup when deprecated options are used, thus nagging users more in keeping their configs up2date.

**Comment by flatcap** [comment]
> maybe we should show warnings during startup when deprecated options are used

Yes, we had a plan for that (not yet implemented).
Over the course of many months / releases:

The first stage would be a warning, giving the new config name (and continue to neomutt).
The second stage would be an error, giving the new config name (and fail to start).
The final stage would be a complete removal of the config name.

I've made myself a note to revisit the idea.
