### ISSUE TITLE
Version 20200814 virtual mailbox names in sidebar are showing the query strings instead of the names

### ISSUE THREAD

**Issue by kailiu42** [neomutt/neomutt#2595]
## Expected Behaviour

The mailbox name should be the name part designated by the virtual-mailboxes command.

## Actual Behaviour

The mailbox name showed in the sidebar is the query string, e.g. query=xxxx.

## Steps to Reproduce

Set up a virtual mailbox by using `virtual-mailboxes "mb name" "query=xxx"`, to show notmuch query results.

## How often does this happen?

Always.

## When did it start to happen?

The same configuration has no problem with v20200626 and previous versions. The 20200814 version always has the problem.

## NeoMutt Version

```
NeoMutt 20200814
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.4.0-19041-Microsoft (x86_64)
ncurses: ncurses 6.2.20200711 (compiled with 6.2.20200711)
libidn: 1.35 (compiled with 1.35)
GPGME: 1.14.0
GnuTLS: 3.6.14
libnotmuch: 5.2.0
storage: kyotocabinet, lmdb
compression: zlib

Configure options: --prefix=/usr --docdir=/usr/share/doc/packages/neomutt --with-mailpath=/var/mail --kyotocabinet --lua --lmdb --gnutls --gpgme --notmuch --sasl --gss --idn --mixmaster --zlib

Compilation CFLAGS: -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +regex +sasl
  +smime -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

OS is openSUSE-Tumbleweed on WSL.

**Comment by jindraj** [comment]
dupelicate #2593

**Comment by kailiu42** [comment]
Oops, didn't notice that it's the same bug.

So is the %B->%D change the solution or just a workaround?

**Comment by kailiu42** [comment]
And after change to %D in `sidebar_format`, I noticed that the virtual mailboxes got some weird indention.

It's like this in 20200626 and it's correct, as there is no child/parent relationship among these mailboxes.
```
vbox 1
vbox 2
vbox 3
vbox 4
```

And now it's:
```
vbox 1
  vbox 2
 vbox 3
vbox 4
```

I use a single space as indent string in sidebar, so the second one got two spaces and the third one got one.

**Comment by jindraj** [comment]
there's a fix in https://github.com/neomutt/neomutt/tree/devel/sidebar-operates-on-what-user-sees by @Austin-Ray and mentioned here: #2585  but it's not merged to master yet.

**Comment by kailiu42** [comment]
Thanks. After applied a6f91bc9c890581cff189e143d86e656cab6d2dc the indention problem is gone.

**Comment by jindraj** [comment]
Well It's not clear if it'll be merged into master, but there are plans to refactor sidebar. Still this is a duplicate issue. I'll mark it as duplicate and close it.

**Comment by kailiu42** [comment]
> Well It's not clear if it'll be merged into master, but there are plans to refactor sidebar.

Understood. Just have to make it more usable for myself at least.

**Comment by javigon** [comment]
Hi all,

This seems to be still an issue. Does anyone know why [1] is not merged?

[1] https://github.com/neomutt/neomutt/commit/a6f91bc9c890581cff189e143d86e656cab6d2dc

**Comment by kailiu42** [comment]
No I didn't anymore. If I recall correctly, it didn't apply cleanly on later versions. And I eventually commented out my virtual mailboxes in configuration as I found myself not using them very often.

**Comment by javigon** [comment]
Thanks @kailiu42. I ended up removing "sidebar_folder_indent" and use tabs to create a structure on virtual mailboxes.
