### ISSUE TITLE
Segfault when using Notmuch entire-thread in NeoMutt 2020-08-14

### ISSUE THREAD

**Issue by diabonas** [neomutt/neomutt#2597]
## Expected Behaviour

When using the Notmuch function `<entire-thread>` on a message, I expect a virtual folder containing the entire thread of this message.

## Actual Behaviour

Instead, NeoMutt segfaults with the following core dump:

```
#0  0x00007fc4be57a4b5 __strlen_avx2 (libc.so.6 + 0x1624b5)
#1  0x00007fc4be6cb125 notmuch_database_find_message (libnotmuch.so.5 + 0x11125)
#2  0x0000565285c22ea3 n/a (neomutt + 0xa4ea3)
#3  0x0000565285c26bba n/a (neomutt + 0xa8bba)
#4  0x0000565285bc9857 n/a (neomutt + 0x4b857)
#5  0x0000565285ba0ea3 n/a (neomutt + 0x22ea3)
#6  0x00007fc4be43f002 __libc_start_main (libc.so.6 + 0x27002)
#7  0x0000565285ba17fe n/a (neomutt + 0x237fe)
```

## Steps to Reproduce

1. Setup Notmuch.
2. Bind the `<entire-thread>` function to a key in `~/.config/neomutt/neomuttrc`, e.g. `bind index,pager + entire-thread`.
3. Press the selected key on any mail in the index.
4. Observe NeoMutt crashing with a segfault.

## How often does this happen?

Always

## When did it start to happen?

When I upgraded from NeoMutt 2020-06-26 to the current NeoMutt 2020-08-14.

## NeoMutt Version

```
NeoMutt 20200814
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.8.1-arch1-1 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.14.0
GnuTLS: 3.6.14
libnotmuch: 5.2.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +regex +sasl
  +smime +sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

* Operating System and its version: **Arch Linux (rolling release)**
* Were you using multiple copies of NeoMutt at once? **No**
* Were you using 'screen' or 'tmux'? **No**
* Is your email local (maildir) or remote (IMAP)? **local maildir**

## Analysis

This appears to be related to the caching introduced in commit 467c06ccc23bf2eb58c32f842fe649f315d13602 (#2413): `cur.e` does not appear to be initialised when calling `nm_read_entire_thread` in https://github.com/neomutt/neomutt/blob/0b8cf5d5c18c6a407a098c3a23930964cba16982/index.c#L2188 leading to a segfault in libnotmuch. A quick fix for the issue is to restore the old behaviour by replacing `cur.e` with `e_oldcur` in l. 2188, but this is probably not in the spirit of the caching that the commit tries to achieve.

**Comment by jindraj** [comment]
I have very similar setup to yours: Neomutt with notmuch virtual mailboxes.

I'm on current master and I'm not able to reproduce it. I also tried 731a200 (commit of the 2020-08-14 release) with the same result.

If this is header cache related, can you try `unset header_cache` and then execute `entire-thread` function?

**Comment by diabonas** [comment]
Indeed, after removing `set header_cache` from the configuration file, `entire-thread` at least does not crash any more.

On the other hand, the feature still does not quite work as expected: when using it on an e-mail from a normal (non-virtual) mailbox folder, a virtual mailbox is shown that only contains the message itself, and the error "Failed to read thread, aborting" is shown. After using `entire-thread` once more on the message in the virtual mailbox, the full thread is shown.

**Comment by jindraj** [comment]
@diabonas So removing the cache file(s) and rebuilding cache by opening all your folders should resolve the original issue.

> On the other hand, the feature still does not quite work as expected: when using it on an e-mail from a normal (non-virtual) mailbox folder, a virtual mailbox is shown that only contains the message itself, and the error "Failed to read thread, aborting" is shown. After using `entire-thread` once more on the message in the virtual mailbox, the full thread is shown.

I'm not sure whether this is supposed to work across different mailbox backends. Maybe someone else will shed more light on it.

**Comment by diabonas** [comment]
> @diabonas So removing the cache file(s) and rebuilding cache by opening all your folders should resolve the original issue.

I confirm that rebuilding the cache fixes the issue even when `header_cache` is set, thank you very much for your help!

> > On the other hand, the feature still does not quite work as expected: when using it on an e-mail from a normal (non-virtual) mailbox folder, a virtual mailbox is shown that only contains the message itself, and the error "Failed to read thread, aborting" is shown. After using `entire-thread` once more on the message in the virtual mailbox, the full thread is shown.
> 
> I'm not sure whether this is supposed to work across different mailbox backends. Maybe someone else will shed more light on it.

Using `entire-thread` twice is certainly a workable, if somewhat annoying solution. I'll note that this was not necessary in NeoMutt 2020-06-26, using `entire-thread` once was enough to show the thread without getting the intermittent "Failed to read thread, aborting".

**Comment by gfarrell** [comment]
I was having a similar issue, when trying to read the thread I got "Failed to read thread, aborting". I have removed the cache files, and then tried `entire-thread` twice and got a segfault. I'm going to see if reverting to 2020-06-26 helps.

**Comment by gfarrell** [comment]
Can confirm that rolling back to 20200626-2 fixes the segfault issue for me.

**Comment by logico-dev** [comment]
Confirm on Debian 10 (buster), segfault with and without notmuch.

```
NeoMutt 20200821-36-758d45
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.19.0-10-amd64 (x86_64)
ncurses: ncurses 6.1.20181013 (compiled with 6.1.20181013)
libidn: 1.33 (compiled with 1.33)
libnotmuch: 5.2.0

Configure options: --notmuch --disable-doc --with-notmuch=/usr/local/src/notmuch

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/src/notmuch/include -DNCURSES_WIDECHAR -I/usr/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls -gpgme -gss -hcache -homespool +idn +inotify
  -locales_hack -lua +meta -mixmaster +nls +notmuch -openssl +pgp +regex -sasl
  +smime -sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

**Comment by scottkosty** [comment]
Can anyone reproduce on 2020-09-25?

**Comment by diabonas** [comment]
I can still reproduce the crash with `neomutt 20200925-1` from Arch Linux when `header_cache` is set. Unlike my previous report in https://github.com/neomutt/neomutt/issues/2597#issuecomment-675397993, disabling and removing the cache, then setting `header_cache` again does not appear to fix the problem any more, NeoMutt still crashes even with the fresh cache file. I am not sure whether this problem is actually specific to the new version, it might have been present in older versions already, but not triggered by the specific email I executed `entire-thread` on.

The orthogonal issue reported in https://github.com/neomutt/neomutt/issues/2597#issuecomment-675392829 that `entire-thread` now needs to be executed twice for email from non-virtual folders still exists in NeoMutt 2020-09-25 as well.

**Comment by scottkosty** [comment]
Thanks for those updated comments. Let's see if @Austin-Ray has an idea. Austin has worked some magic on solving previous notmuch issues.

**Comment by Austin-Ray** [comment]
> The orthogonal issue reported in #2597 (comment) that entire-thread now needs to be executed twice for email from non-virtual folders still exists in NeoMutt 2020-09-25 as well.

Opened #2674 addressing the double `entire-thread` issue. Please test and report back.

Haven't been able to reproduce the crash on my end. Can someone experiencing it provide logs with `-d 5`? Also see if #2674 stops the crashes.

Thanks!

**Comment by diabonas** [comment]
> Opened #2674 addressing the double `entire-thread` issue. Please test and report back.

Awesome, thank you very much for the fix! I confirm that this PR fixes the described issue.

> Haven't been able to reproduce the crash on my end. Can someone experiencing it provide logs with `-d 5`? Also see if #2674 stops the crashes.

I have tested your PR with the current master branch as well as cherry-pick on top of NeoMutt 2020-09-25 and couldn't provoke a crash any more. On the other hand, the unpatched NeoMutt 2020-09-25 still exhibits crashes when executing `entire-thread` on some emails, so I assume the PR fixes the segfault issue as well.

**Comment by Austin-Ray** [comment]
> Awesome, thank you very much for the fix! 

@diabonas : The credit should be yours. In my hasty reading of this ticket, I overlooked your analysis section, which had the exact fix.  I merely came to the same conclusion as you. Apologies for not being more thorough so that you may be the one to receive credit. I'll make sure the next set of release notes properly attributes the fix to you.

**Comment by diabonas** [comment]
No worries, I just played around with the code from the bisected commit until it stopped crashing, so having somebody more familiar with the NeoMutt source code than I am come up with the same solution is certainly valuable in itself :)

Since #2674 has been merged now, solving both issues described in this ticket, I am going to close it as solved.

**Comment by CabalCrow** [comment]
I get a segfault when running the entire-thread command on this version:
```
NeoMutt 20240425
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.6.32-1-lts (x86_64)
ncurses: ncurses 6.5.20240427 (compiled with 6.4.20230520)
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.23.2
GnuTLS: 3.8.5
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --ubsan --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/neomutt/src=/usr/src/debug/neomutt -flto=auto -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.3 -I/usr/include -I/usr/include -I/usr/include -DNCURSES_WIDECHAR -I/usr/include -I/usr/include/p11-kit-1 -I/usr/include -I/usr/include -fsanitize=undefined -fno-omit-frame-pointer -fno-common -g -O0

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme 
  -gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster 
  +nls +notmuch -openssl +pgp +regex +sasl +smime +sqlite +truecolor 

Devel options:
  ubsan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```
