### ISSUE TITLE
Sending email on CL no longer works with neomutt -H - < message.txt

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#2606]
## Expected Behaviour

I used to be able to send email with the following:

    neomutt -H - < message.txt

## Actual Behaviour

This now gives the following error:

    Refusing to send an empty email
    Try: echo | neomutt -s 'subject' user@example.com

Note that message.txt is not empty; it is a valid message complete with headers.

## How often does this happen?

- Always

## When did it start to happen?

I can bisect if it it would help. Note that the following seems related: f9476b4f5bf3027cd69129d37ac6635e535697f9, although I think that's just the error reporting. I don't think it was working for this use case before that commit; it just didn't give an error.

## NeoMutt Version

```
NeoMutt 20200821
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.0-64-generic (x86_64)
ncurses: ncurses 6.1.20190803 (compiled with 6.1.20190803)
libidn: 1.33 (compiled with 1.33)
OpenSSL: OpenSSL 1.1.1c  28 May 2019
libnotmuch: 5.2.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"
```

**Comment by scottkosty** [comment]
I think that being able to send an email where the "to:" and "subject:" are specified in the headers is a nice feature of Mutt. Is it possible to do it somehow in the new NeoMutt approach without repeating them in the command and without having to edit the email before sending?

If needed, I can write a wrapper. I just wanted to double-check though that it's necessary since there aren't too many features that Mutt has that NeoMutt doesn't have, although I definitely understand that in some cases it's need to remove a feature to be able to fix bugs or add other features (as you mentioned above the related issues). Is this case one of those necessary sacrifices?

**Comment by scottkosty** [comment]
@ngortheone Do you by chance have any thoughts on this issue? (I ask because I saw your commit 0ab694d9)

**Comment by ngortheone** [comment]
@scottkosty, I can't give you a good answer. My commit only updated man section, porting words from mutt's manual. 
I do not (yet) know enough of neomutt code to tell if this works as desired or not. I'd defer this to @flatcap who gave me this task to port the man page wording.

One observation though. Manual says:
> Although it is not an mbox file, if an mbox `From` line is present, it will be silently discarded.

And your message txt has `From: Scott Kostyshak <scott.kostyshak@gmail.com>`
So it does what the fine print says :)

I believe this intentional corner case was introduced to prevent from accidentally sending an mbox file (mbox is a mail storage format that stores all emails in a single file)

**Comment by ngortheone** [comment]
Thinking more about this, I think the error message could be a bit more user friendly.

It silently discards your input, because it has "From" field in it. Then it tries to send an email, but there is no contents, and so you get `Refusing to send an empty email`

IMHO there should be an explicit message saying something like to prevent confusion
> Input is discarded because it contains From: field. Please read neomutt(1) for more details

**Comment by scottkosty** [comment]
@ngortheone Thanks for taking a look! I'm fine either way. We might want to just close this as "wontfix" and document this somewhere as a feature that Mutt has that NeoMutt does not have. Is there already such a list somewhere?

**Comment by alejandro-colomar** [comment]
Oops, I forgot to mention this issue in the commit message for <https://github.com/neomutt/neomutt/commit/2cdc72afd57a8733f0da0abe8a86fbfbbea6afbb>, and CC you in it too.  Anyway, the issue has been fixed by that commit.
