### ISSUE TITLE
Prompts for password when switching mailboxes with imap

### ISSUE THREAD

**Issue by SamAxe** [neomutt/neomutt#2616]
I'm not sure if this is a bug/regression or user error.  Documenting here for benefit of others or future sleuthing if it turns out to be a bug.

I'm using offline imap.

Every time I switch mailboxes, it prompts for a password.

This behavior changed with a859347a49c1db0130595185fd1eab2cbf9ba388

If I revert the imap/imap.c portion and keep the mx.c/.h changes, it works as before on trunk as of 758d453f0326ee1e8f6b69931277820117e62c88

```
# a859347a49c1db0130595185fd1eab2cbf9ba388 is the first bad commit
# commit a859347a49c1db0130595185fd1eab2cbf9ba388
# Author: Pietro Cerutti <gahr@gahr.ch>
# Date:   Tue Jul 28 07:51:35 2020 +0000
# 
#     Fix retrieval of drafts when "postponed" is not in the mailboxes list
# 
#     Incidentally, this also allows to have "postponed" on a different
#     account.
# 
#     Fixes #2430
# 
#  imap/imap.c | 26 +++++++++++++++++---------
#  mx.c        | 54 +++++++++++++++++++++++++++++++++++++-----------------
#  mx.h        | 11 ++++++-----
#  3 files changed, 60 insertions(+), 31 deletions(-)
```

**Comment by gahr** [comment]
Sorry for the regression. Are you using imap (neomutt connects to a server) or offlineimap (neomutt sees a local maildir)?

Can you please post the parts of your config pertaining to defining accounts / urls / spoolfile / folder / mailboxes?

**Comment by SamAxe** [comment]
I think I'm using the 'neomutt sees a local maildir' version, though I've gone back and forth over the years.

imap_user = "..."
spoolfile = "+INBOX"
folder = ~/Maildir/active"
mailboxes    ~/Maildir/<folder1>  \
 ~/Maildir/<folder2> \
 etc

**Comment by gahr** [comment]
What exactly does the password prompt says, and why do you set imap_user if you’re not accessing imap?

**Comment by gahr** [comment]
My hunch is that somewhere you’re still adding an imap path to your mailboxes. You’re defining imap_user but not imap_pass so each time it tries to STATUS that mailbox it asks you for a pass.

**Comment by SamAxe** [comment]
imap_user was just left over from previous configuration where I connected to imap service.
I did have an imap path in postponed that was sneaking in.
With imap_user and the postponed set to local path, it stops prompting me.

Thank you for your help.
