### ISSUE TITLE
Translation bug: "Unable to sync %d messages ..." should use ngettext

### ISSUE THREAD

**Issue by mgedmin** [neomutt/neomutt#2618]
Here's a message that isn't using `ngettext` but should be:

https://github.com/neomutt/neomutt/blob/758d453f0326ee1e8f6b69931277820117e62c88/notmuch/notmuch.c#L2455-L2456

(I checked all the untranslated/fuzzy entries in `lt.po` and this was the only issue of this kind.)

**Comment by jindraj** [comment]
That's because 731a3d9cb226086e2c899b423076b5822e5c8824 it was merged to the master few days ago and translators didn't translate the message yet. It's missing in all po files except en_GB.po.

**Comment by mgedmin** [comment]
I think you misunderstood this bug report.

The problem is not missing translation strings in po files (I'm the lt_LT translator and I write those strings).  The problem is that the message is using `gettext()` instead of `ngettext()` so it doesn't handle plural forms correctly.  This is also a problem in English ("1 messages"), but it's more apparent in other languages.

**Comment by jindraj** [comment]
ah, Now I understand.
