### ISSUE TITLE
Locale and header_cache unknown

### ISSUE THREAD

**Issue by yfery** [neomutt/neomutt#262]
I just build neomutt from source and some errors raise at neomutt startup 

> Error in /home/king/.muttrc, line 35 : locale : unknown variable
> Error in /home/king/.muttrc, line 87 : header_cache : unknown variable

Muttrc entries:

> set locale="fr_FR.utf8" 
> set header_cache = ~/.mutt/cache

My configure line raised a warning about hcache flag

> ./configure -v --prefix=/usr --libexecdir=/usr/lib --without-included-gettext --libdir=/usr/lib --enable-nls --enable-debug --sysconfdir=/etc --with-docdir=/usr/share/doc/mutt-1.7.0 --enable-external-
dotlock --enable-imap --enable-hcache --enable-smtp --with-ssl --with-sasl --enable-sidebar
> configure: WARNING: unrecognized options: --enable-hcache

I saw some changes about header cache in Changelog, but I didn't found any documentation about replacing --enable-hcache flag by anything else.
And found nothing about locale variable. 

> king@Aluminium /opt/neomutt neomutt* $ mutt -v
> NeoMutt 20161126 (1.7.1)
> Copyright (C) 1996-2016 Michael R. Elkins et autres.
> Mutt ne fournit ABSOLUMENT AUCUNE GARANTIE ; pour les détails tapez `mutt -vv'.
> Mutt est un logiciel libre, et vous êtes libre de le redistribuer
> sous certaines conditions ; tapez `mutt -vv' pour les détails.
> 
> System: Linux 4.4.26-v7+ (armv7l)
> 
> Compiler:
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
> Target: arm-linux-gnueabihf
> Configured with: ../src/configure -v --with-pkgversion='Raspbian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --
> program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable
> -nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disa
> ble-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-
> jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
> Thread model: posix
> gcc version 4.9.2 (Raspbian 4.9.2-10) 
> 
> Configure options: '-v' '--prefix=/usr' '--libexecdir=/usr/lib' '--without-included-gettext' '--libdir=/usr/lib' '--enable-nls' '--enable-debug' '--sysconfdir=/etc' '--with-docdir=/usr/share/doc/mutt-1.7.0' '--enable-external-dotlock' '--enable-imap' '--enable-hcache' '--enable-smtp' '--with-ssl' '--with-sasl' '--enable-sidebar'
> 
> Compilation CFLAGS: -Wall -pedantic -Wno-long-long -g -O2
> 
> Options de compilation :
> +CRYPT_BACKEND_CLASSIC_PGP +CRYPT_BACKEND_CLASSIC_SMIME -CRYPT_BACKEND_GPGME 
> +DEBUG +DL_STANDALONE +ENABLE_NLS -EXACT_ADDRESS -HOMESPOOL -LOCALES_HACK 
> -SUN_ATTACHMENT +HAVE_BKGDSET +HAVE_COLOR +HAVE_CURS_SET +HAVE_GETADDRINFO 
> +HAVE_GETSID +HAVE_ICONV +HAVE_LANGINFO_CODESET +HAVE_LANGINFO_YESEXPR 
> -HAVE_LIBIDN +HAVE_META +HAVE_REGCOMP +HAVE_RESIZETERM +HAVE_START_COLOR 
> +HAVE_TYPEAHEAD +HAVE_WC_FUNCS +ICONV_NONTRANS -USE_COMPRESSED +USE_DOTLOCK 
> +USE_FCNTL -USE_FLOCK -USE_FMEMOPEN -USE_GNU_REGEX -USE_GSS -USE_HCACHE 
> +USE_IMAP -USE_NOTMUCH -USE_NNTP -USE_POP +USE_SASL +USE_SETGID +USE_SIDEBAR 
> +USE_SMTP -USE_SSL_GNUTLS +USE_SSL_OPENSSL 
> -DOMAIN
> -MIXMASTER
> -ISPELL
> SENDMAIL="/usr/sbin/sendmail"
> MAILPATH="/var/mail"
> PKGDATADIR="/usr/share/mutt"
> SYSCONFDIR="/etc"
> EXECSHELL="/bin/sh"
> 
> patch-attach-headers-color-neomutt
> patch-compose-to-sender-neomutt
> patch-compress-neomutt
> patch-cond-date-neomutt
> patch-encrypt-to-self-neomutt
> patch-fmemopen-neomutt
> patch-forgotten-attachments-neomutt
> patch-forwref-neomutt
> patch-ifdef-neomutt
> patch-index-color-neomutt
> patch-initials-neomutt
> patch-keywords-neomutt
> patch-kyoto-neomutt
> patch-limit-current-thread-neomutt
> patch-lmdb-neomutt
> patch-multiple-fcc-neomutt
> patch-nested-if-neomutt
> patch-new-mail-neomutt
> patch-nntp-neomutt
> patch-notmuch-neomutt
> patch-progress-neomutt
> patch-quasi-delete-neomutt
> patch-reply-with-xorig-neomutt
> patch-sensible-browser-neomutt
> patch-sidebar-neomutt
> patch-skip-quoted-neomutt
> patch-status-color-neomutt
> patch-timeout-neomutt
> patch-tls-sni-neomutt
> patch-trash-neomutt

**Comment by flatcap** [comment]
Hi @yfery 

> I saw some changes about header cache in Changelog

Ah, I'm glad to see someone reads my release notes :-)

Where did you get your source from?

Judging by the error, I think you have the latest development version from git.
It works, but the changes haven't been documented yet.

`--enable-hcache` is no longer needed, but you must specify one (or more) of the database backends, e.g.
- `--with-tokyo-cabinet`  (this is the usual choice)
- `--with-lmdb`

As for `$locale`, that was removed by upstream Mutt (a few versions ago) -- it's not needed any more.
Mutt already checks your locale settings and this variable was just misleading.

**Comment by yfery** [comment]
It's me again :)

> Where did you get your source from?

You're right, a fresh git clone

So, I remove `--enable-hcache` from `configure` and add `--with-tokyocabinet` (without hypen between tokyo and cabinet) 

If I understand correctly, I have to add `set header_cache_backend=tokyocabinet` in my muttrc. 

Same issue at mutt startup: 
`Error in /home/king/.muttrc, line 88 : header_cache_backend : unknown variable`

I think there's another problem in my compilation options. In my `mutt -v` I have: `-USE_HCACHE `

I can't find the compilation flag to have `+USE_HCACHE `

**Comment by flatcap** [comment]
> --with-tokyocabinet (without hypen between tokyo and cabinet)

Ah, that was a test :-)

> -USE_HCACHE
> header_cache_backend : unknown variable

The unknown variable make sense, if there's no hcache, but just adding `--with-tokyocabinet` should be enough -- it should give you `+USE_HCACHE`.  At least it worked in my test, just now.

One reason for this might be that you're missing the devel libraries for that database.
Make sure you've got `libtokyocabinet-dev` installed.

Failing that, please post your entire configure line and I'll give it a try.

**Comment by riesebie** [comment]
* yfery <notifications@github.com> [2016-12-01 07:50 -0800]:

> It's me again :)
> 
> > Where did you get your source from?
> 
> You're right, a fresh git clone
> 
> So, I remove `--enable-hcache` from `configure` and add
> `--with-tokyocabinet` (without hypen between tokyo and cabinet) 
> 
> If I understand correctly, I have to add `set
> header_cache_backend=tokyocabinet` in my muttrc. 
> Same issue at mutt startup: `Error in /home/king/.muttrc, line 88
> : header_cache_backend : unknown variable`

Thats not needed. Just set
header_cache -> the dir where you store your cache

NeoMutt knows what hcache backend to use from your compile option.

> 
> I think there's another problem in my compilation options. In my
> `mutt -v` I have: `-USE_HCACHE `

To compile tokyocabinet hcache you need the dev headers. i.e.
libtokyocabinet-dev.

Elimar
-- 
  355/113: Not the famous irrational number pi,
           but an incredible simulation!
	                -unknown

**Comment by yfery** [comment]
you're right, by installing ` libtokyocabinet-dev ` and adding ` set header_cache_backend=tokyocabinet ` in muttrc, everything goes fine. \o/

Thanks both of you !
