### ISSUE TITLE
Refactor - Reduce the scope/dependencies of some Validator functions

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#2625]
Config variables can be defined with a validator function.
Most validators are specific to a config variable.

## Task 1

Reduce the scope of some validator functions.

These functions are defined in [`init.c`](https://github.com/neomutt/neomutt/blob/master/init.c#L1542)

- `charset_validator()`
- `compress_level_validator()`
- `compress_method_validator()`
- `hcache_validator()`
- `multipart_validator()`
- `pager_validator()`
- `reply_validator()`

Find out where each function is used and move it there.
Make sure any function prototypes are updated/removed as necessary.

## Task 2

Eliminate the dependencies of `charset_validator()`.

This validator function makes reference to two specific config variables:
- [`$charset`](https://github.com/neomutt/neomutt/blob/master/init.c#L1550)
- [`$send_charset`](https://github.com/neomutt/neomutt/blob/master/init.c#L1558)

Rather than refer to the config variable, we'll use a flag to control the behaviour.
- `DT_CHARSET_SINGLE`
- `DT_CHARSET_STRICT`

We can copy the values from `config/sort2.h`.
Next, add these flags to the config definitions in `mutt_config.c`
Finally, change `charset_validator()` to use these flags.

## Task 3

Move `charset_validator()` into libmutt.

Now that this function is dependency free, move it into `mutt/charset.c`

**Comment by louis77** [comment]
If nobody has started with this yet, I would like to take on the task. That goes well with my "refresh C" plans. Thanks for the well documented issue!

**Comment by flatcap** [comment]
Ping?

**Comment by louis77** [comment]
Pong! I'll be back on IRC today or tomorrow night with some questions.

**Comment by louis77** [comment]
As requested by @flatcap in IRC, the `charset_validator` is now moved to `config/charset.c` instead of `mutt/charset.ch` to reduce dependencies that would otherwise have moved into libmutt.
