### ISSUE TITLE
Index Limit broken by arrival of new mail

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#2631]
**Steps to reproduce**:
- NeoMutt Index view
- Apply `<limit>` that shows some emails
- Wait for new mail to arrive

**Results**:
- All of the emails (or all but one) disappear from the limited view

**Expected Results**:
- Existing emails remain
- New email is added to view, if it matches the limit

**Note**:
- Reapplying the limit `<limit><enter>` corrects the view

Bisecting, leads to: 2dce94a08 Track currently selected email by msgid

**Comment by gahr** [comment]
This only happens if the new email would be included in the limit. Receiving an email that wouldn't, works fine.

**Comment by gahr** [comment]
I still wasn't able to replicate this exact problem. What I was able to see is that the limit doesn't get updated when new mail that matches arrives. This is fixed by #2634.

What's your sort, sort_aux and a pattern that exhibits this behaviour?

**Comment by gpenghe** [comment]
I reported this issue in IRC. It works beautifully now. Thanks @gahr and @flatcap!
