### ISSUE TITLE
Cannot write to mailbox. 

### ISSUE THREAD

**Issue by rewolff** [neomutt/neomutt#2635]
## Expected Behaviour

I read mail with two neomutt instances on the same mailbox. I will accept that not all flags can be maintained correctly between the two, but things have worked with "mutt" like this for years. 

<!- What were you trying to do? -->

reading mail and then updating the mailbox. 

## Actual Behaviour

On one of them I now get: 
   Unable to write /home/wolff/Maildir

when syncing ($) or quitting neomutt. 

I get the error message: 
  Unable to write /home/wolff/Maildir

## Steps to Reproduce

I have run strace against the offending neomutt. It tries to move one of the files in the maildir somewhere but that fails because the source file no longer exists. I strongly suspect that the other instance moved or deleted that file. 

The "file disappeared" situation should be recognized and accepted as "normal". It now blocks all other updates to the mailbox and prevents me from opening another mailbox or quitting normally. 

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  I used mutt before. neomutt 20191207

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.0-42-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.13.1-unknown
libnotmuch: 5.2.0
hcache backends: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-WmwApX/neomutt-20191207+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Ubuntu 20.04
* Were you using multiple copies of NeoMutt at once? yes. 
* Were you using 'screen' or 'tmux'? no. 
* Is your email local (maildir) or remote (IMAP)? yes, maildir.

**Comment by gahr** [comment]
Hi, thanks for trying out NeoMutt. Any chance you could try a more recent version and report whether the bug is still there?

**Comment by rewolff** [comment]
Apparently: yes, I can compile the current git version of neomutt. 
It seems ubuntu has acouple of patches installed that are not standard: 
```
Error in /etc/neomuttrc, line 38: mixmaster: unknown variable
Error in /etc/neomuttrc, line 41: ssl_ca_certificates_file: unknown variable
```
The SSL thing seems important to me. Oh! Wait! I only use local mailboxes, so SSL certificates for IMAPS don't matter to me. Good. 

Where the distro neomutt showed the number of messages in each mailbox at startup, the githuib version shows the number of messages as "0" until I open that mailbox. 

Now, I'll have to "go about my business" and see if it happens again. Not sure what triggers it precisly: probably something like reading and deleting on one computer and then doing something with that message on the other. (Neomutt running on the mailserver, but displaying on different computers).

**Comment by rewolff** [comment]
FYI: I compiled neomutt then forgot about it and started to use the system installed one. 

Now one says: I have 34 new messages, and syncing the mailbox does nothing I cannot access the already-deleted-with-the-other-instance messages, In the past when I was still using "mutt", this would work, an explicit mailbox sync would suddenly delete the message that the other instance had deleted: Avoiding the problem of accessing messages that no longer exist.

**Comment by flatcap** [comment]
er, that's quite a long sentence.
Please can you help us understand it.

Which version (or versions) are you using?
What steps are you performing _in which versions_?
What are you expecting to see?
What are you actually seeing?

**Comment by rewolff** [comment]
In old mutt when I had two instances running, I would process emails in one location and when I touched the other one in the other location, the deleted/saved messages would update. 

That would result in serveral problems not occurring, that I do see with neomutt: 
1) As reported originally Neomutt can enter a state where it won't accept a "write-to-mailbox" because one of the files in the maildir that it expects is no longer there. 
2) I can select a message and then get an "unable to access file". 

The version I am using this morning was again theone that comes with Ubuntu 20.04. "Already quite old" according to someone above this message. 

So... my apologies, for using an older version. I have now taken measures to use "latest neoimutt" by default, so I'll report again when I again see this happening in the latest version. 

I am personally guessing that the problems shown here also apply to the latest version, so I'm already documenting what I see happening in the older version expecting that it will also happen the coming week when I am using "latest git". 

Until that time, you can safely ignore me as I'm reporting stuff about a "too old" version.

**Comment by gahr** [comment]
Could we summarize the issue as being related to plain Mutt refreshing "faster" or "more often" than NeoMutt? Can you try to tweak the `mail_check` and `timeout` settings?

**Comment by rewolff** [comment]
I don't think so. I think that when mutt encounters a file that no longer exist it instantly triggers a "check" that notices: "hey nolonger there" and then doesn't offer me the option to try to look at the file, or try to process that file (rename/move somewhere else).

**Comment by rewolff** [comment]
Update: It is starting to look like it has been fixed since 2019.

**Comment by rewolff** [comment]
I can no longer reproduce this with current Neomutt. Sorry for the noise.

**Comment by flatcap** [comment]
No problem.  Glad things are working for you :-)
