### ISSUE TITLE
change sidebar texts. 

### ISSUE THREAD

**Issue by rewolff** [neomutt/neomutt#2636]
In mutt I could see the mailbox name and the number of messages in each mailbox. Neomutt formats things differently and I cannot see the mailbox names anymore. :-( 

## Have you tried any alternative methods?

I haven't been able to find how to change the displayed texts in the sidebar. 

![neomutt](https://user-images.githubusercontent.com/1678121/92235116-79e79c00-eeb3-11ea-8ce6-49eea4f86f22.png)

**Comment by louis77** [comment]
The parameter to format the sidebar is `sidebar_format`, i.e.

`set sidebar_format = "%B%?F? [%F]?%* %?N?%N/?%S"` 

(which is was I use).

There is a full documentation for the formatting options at
https://neomutt.org/guide/gettingstarted.html#intro-sidebar-format

Can you try that?

**Comment by rewolff** [comment]
OK! Better! 
But not yet "usable": I usually start mutt/neomutt from my homedir, but sometimes from somewhere else, so I have to specify the mailboxes with the full path. And both the %B and %D seem to try to print the full pathname. 
One of these should simply print the last path component of the mailbox path, or a new % -expansion can be made that provides this functionality. (to keep backward compatiblity for others who have grown used to the current situation).

**Comment by gahr** [comment]
Please do have a look at https://neomutt.org/feature/sidebar. It mentions several configuration options, including `sidebar_short_path`.

**Comment by rewolff** [comment]
That does the trick. Thanks.
