### ISSUE TITLE
Refactor the Color Event

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#2640]
After commands are processed, NeoMutt sends out [Event notifications](https://github.com/neomutt/neomutt/blob/master/mutt/notify_type.h#L31).
These notifications have a type, a subtype and an Event object.

e.g.
- Type: `NT_MAILBOX` - Something happened to a Mailbox
- Subtype: `NT_MAILBOX_ADD` - A new Mailbox was added
- Event: `struct EventMailbox` - Which contains the Mailbox object

## Task

Make the Color notification work the same way.

- Add `NT_COLOR_SET` and `NT_COLOR_RESET`
- Add a `struct EventColor` (containing the colour id, e.g. `MT_COLOR_INDEX`)
- Update the observers so that they work correctly
  (look for `notify_observer_add()` and `NT_COLOR`)

**Comment by louis77** [comment]
Issue was addressed in PR #2643 .
