### ISSUE TITLE
Refactor the Commands list

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#2641]
All of NeoMutt's commands are stored in one large static array: [`Commands`](https://github.com/neomutt/neomutt/blob/master/mutt_commands.c#L50).

Each time a new feature adds a command, this central point needs to be updated.
This makes the `mutt_commands.c` file into a dependency nightmare.

## Task 1

Create a new Command dynamic array, using the new [`ARRAY` functions](https://github.com/neomutt/neomutt/blob/master/mutt/array.h)

- Create setup and shutdown functions to control its lifespan (and free any memory)

- Initialise the `ARRAY` with the contents of the original `Commands`

- After adding to the `ARRAY`, sort it by command name

## Task 2

Break up the dependencies.

There are four features that define their own commands
(look for `USE_COMP_MBOX`, `USE_IMAP`, `USE_LUA` and `USE_SIDEBAR`)

All of the commands in these `#ifdef`s should be moved out to the feature's source dir.
Each feature will need an `init()` function that registers their commands.

**Comment by louis77** [comment]
I've commited the first draft of this. Commands for the following features were moved:

- `USE_COMP_MBOX`
- `USE_IMAP`
- `USE_SIDEBAR`

Questions so far:

1. Is the overall approach ok?
2. What about `USE_NOTMUCH`?
3. `USE_LUA` is different that the other features. Should I move the commands to `mutt_lua.c`?

**Comment by flatcap** [comment]
Yes, that's looking very nice.

1. Yes
2. Yes.  How did I miss that from the list?
3. Yes

Thanks :-)
