### ISSUE TITLE
influence which mail in a collapsed thread that is used to represent the thread

### ISSUE THREAD

**Issue by quite** [neomutt/neomutt#265]
Currently, the first mail in a collapsed thread is used to represent the thread. I would enjoy an option to use the last (by received or so), or even optionally the last unread (which would be a possibility given `set collapse_unread`).

**Comment by flatcap** [comment]
It's a useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
