### ISSUE TITLE
IMAP expunge reverses reverse-mailbox-order

### ISSUE THREAD

**Issue by vt-alt** [neomutt/neomutt#2651]
## Problem

Neomutt is configured with `reverse-mailbox-order/last-date-received` and IMAP.

When user marks for deletion some email(s) and press `$` sort order is reversed (without updating its description on the screen).
And it feels like new mail aren't arriving - requiring exit and launch `neomutt` again to see new mail.

## How often does this happen?

- Always

## When did it start to happen?

User upgraded from `20171215` and tried `20200821`, `20200814`, and `master` with the same effect.

## NeoMutt Version

`master` version on debian9:
~~~
$ ./neomutt -v
NeoMutt 20200821-85-4bcb54
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.9.0-3-amd64 (x86_64)
ncurses: ncurses 6.0.20161126 (compiled with 6.0.20161126)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.8.0
OpenSSL: OpenSSL 1.1.0l  10 Sep 2019
libnotmuch: 4.4.0
storage: lmdb

Configure options: --prefix=/opt/neomutt --disable-nls --gpgme --notmuch --lua --with-lua=/usr --lmdb --ssl --sasl

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/opt/neomutt/include -I/usr/include/lua5.3 -DNCU
RSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster -nls +notmuch +openssl +pgp +regex +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/opt/neomutt/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/opt/neomutt/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
~~~

**Comment by gahr** [comment]
I can reproduce the order reversing, but I keep getting new mail, although it appears at the "wrong" end of the index.

1. reverse-mailbox-order gives me new mail on top
2. deletion inverses the order and places me at the bottom
3. new mail still arrives at the top

**Comment by vt-alt** [comment]
You are right, new mail is arriving, but it's on the wrong side of index, so user may not notice it.

**Comment by vt-alt** [comment]
Yes, with `sort=last-date-received` it behaves normally, problem happens only with `sort=reverse-mailbox-order`.

By `reverse-mailbox-order/last-date-received` I meant what is displayed on the screen where `last-date-received` is `sort_aux`, and probably it's not related to the issue.

**Comment by gahr** [comment]
Thanks - yes, sort_aux is only used with threading.

**Comment by gahr** [comment]
Can you please give the branch devel/issue-2651 a try? Thanks!

**Comment by vt-alt** [comment]
Just tried `devel/issue-2651` and it looks like problem is fixed. Thanks much!
