### ISSUE TITLE
setting of mime type of files to be attached

### ISSUE THREAD

**Issue by user1850133** [neomutt/neomutt#2657]
Only a few file types seem to be recognised by neomutt and therefore the right mime type is being set for them when such files are attached during mail composition. Among these so far i found that only text and pdf files are honoured. Others such as images (jpg, and png AFAIK), multimedia (mp3, flac, mkv), compressed (zip, tar, gz) files are not and are given the mime type "applica/octet-stre".

**Comment by flatcap** [comment]
Solved, with help from the Guide: https://neomutt.org/guide/mimesupport
