### ISSUE TITLE
Archiving email breaks the metadata

### ISSUE THREAD

**Issue by Jonassenher** [neomutt/neomutt#2663]
## Expected Behaviour

Often I move an email to a different folder in Neomutt, e.g. when archiving, which I do with all of my email, and then sync the mailbox again again. When I log back into outlook.com to check my email in that way, or on my mobile app, I want to see the metadata of the emails as they were, as it is done on any other email client that I have used.

E.g., say "Email A" was sent and received the 15th of September, then I read it and archived it the 20th of September, I want it to still show up with the date of 15th of September on outlook.com and my mobile app.

## Actual Behaviour

The metadata of emails appears with the wrong date on outlook.com and my mobile app. For the example above, neomutt would still displays the email correctly with the 15th of September, but on outlook.com and on the mobile app however, it is changed to the 20th of September.

It seems like Neomutt's internal process makes the email client think that the email was permanetly deleted and then another email appeared in the archive folder, so it assigns the "new" email to the new date.

## Steps to Reproduce

Supposing you are using an email server that provides a web interface (don't know what the alternative is, but still), open your neomutt in index view, then archive an email with esc+M+a. Sync your mailbox. Log in to the web interface, and go to the archives folder. Notice how now the date of archiving is now displayed instead of the actual date of the email.

## How often does this happen?

Always.

## When did it start to happen?

Always.

## NeoMutt Version

```
NeoMutt 20200821
Copyright (C) 1996-2020 Michael R. Elkins m.fl.
Der følger ABSOLUT INGEN GARANTI med NeoMutt; tast 'neomutt -vv' for detaljer.
NeoMutt er et frit program, og du er velkommen til at redistribuere det
under visse betingelser; tast 'neomutt -vv' for detaljer.

System: Linux 5.8.6-1-MANJARO (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.14.0
GnuTLS: 3.6.14
libnotmuch: 5.2.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Tilvalg ved oversættelsen:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +regex +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Using an up-to-date version of Manjaro, KDE Plasma edition
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? Don't know what this means.
* Is your email local (maildir) or remote (IMAP)? Using IMAP and all of that.
* Btw I'm also using Mutt-Wizard.

**Comment by Jonassenher** [comment]
I realize that esc+M+a seems to be a feature of Mutt-Wizard, that corresponds to the command `<change-folder>=Archive<enter>`, where "Archive" is the name of the archives folder, or any folder you want to move the email to.

**Comment by gahr** [comment]
Hi @Jonassenher, are you sure the macro isn't `<save-message>...` instead of `<change-folder>...` ? I know Office365 is weird, but I also have an account @hotmail.com and I wasn't able to reproduce.

What I did:
1. pick an email from some time ago, Feb. 10 2019
2. `:exec save-message` to `+Archive`
3. sync / quit neomutt
4. login to https://outlook.live.com
5. check the msg in Archive

The date is correct. Where are you seeing bogus "metadata"?

**Comment by gahr** [comment]
@Jonassenher any news?

**Comment by Jonassenher** [comment]
Hi @gahr, following exactly the same procedure as you describe, the message appear in Archive in https://outlook.live.com with the **wrong** date.

The bogus metadata is, again, the date.

**Comment by gahr** [comment]
I don't know mutt-wizard, but I understand `mw sync` calls mbsync underneath, thus I assume you're not connecting to IMAP directly with NeoMutt, but are using a local Maildir sync'd with mbsync. I don't think the metadata issue has anything to do with NeoMutt.

**Comment by Jonassenher** [comment]
@gahr Thank you, I didn't know that. How do you sync your email, using Neomutt directly?

**Comment by gahr** [comment]
I don't sync emails, I just use NeoMutt to connect to the IMAP server:
`set folder = imaps://username@server`
