### ISSUE TITLE
Add a Contract to the Mailbox API

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#2665]
## MXAPI (Mailbox API)

The MXAPI (Mailbox API) is a set of functions that each backend (Imap, Maildir, etc) supports.
They're documented in `struct MxOps`:

https://github.com/neomutt/neomutt/blob/d9cb4825bec1c833229d51acc9a0976e6c31ca7e/mx.h#L104-L291

The frontend calls wrapper functions in `mx.c` that call the relevant backend function. e.g.

The frontend:
https://github.com/neomutt/neomutt/blob/d9cb4825bec1c833229d51acc9a0976e6c31ca7e/index.c#L753

calls:
https://github.com/neomutt/neomutt/blob/d9cb4825bec1c833229d51acc9a0976e6c31ca7e/mx.c#L400

ending up in the backend
https://github.com/neomutt/neomutt/blob/d9cb4825bec1c833229d51acc9a0976e6c31ca7e/imap/imap.c#L1909-L1912

## Contract

Each function is documented, but I'd like to go further and add a Contract to the docs.

In most functions, it's important to check pointer parameters before using them.
For these API functions, we know that they'll only be called by the wrappers in `mx.c`
We can write a Contract in the docs declaring that certain conditions will be met.

Here's one from `config/set.h`
https://github.com/neomutt/neomutt/blob/d9cb4825bec1c833229d51acc9a0976e6c31ca7e/config/set.h#L127-L141

When `native_set()` is called, we guarantee that `cs`, `var` and `cdef` will not be NULL.

In my [devel/path](https://github.com/neomutt/neomutt/tree/devel/path) branch, you can see a more complex example:

https://github.com/neomutt/neomutt/blob/5f0f022752aa895a8d40ccbb8c586831d3b4a49d/mx.h#L306-L322

## Research

There are 19 functions in `MxOps`:

- Create a list of the API functions in `MxOps`
- For each, find where it's called from (in `mx.c`).

There are 9 backends implementing `MxOps`:

- Create a list of all the API users (Imap, etc)
- For each, list which functions are called

## Tasks

- For each caller, check that the pointers cannot be `NULL`
- Add a Contract for each pointer
- For each backend function, remove any unnecessary checks

**Comment by brunnre8** [comment]
Hi Rich, please assign me to it.

**Comment by flatcap** [comment]
Thanks, that looks good -- It'll take me a little while to review it.

The next challenge is to add to the MXAPI.

I'd like you to add a function: `int path_is_empty(const char *path)`
This will replace the backend-specific code in `mx_check_empty()`.
I suggest that we rename `mx_check_empty()` to `mx_path_is_empty()` for consistency.

Please create a new branch for this task, but starting on top of your "contract" changes.

**Note**: You can create branches on the `neomutt` repo, of the form `devel/[SHORT-NAME]`
Using the `neomutt` repo makes it easier for others to collaborate and review.
