### ISSUE TITLE
lmdb hcache can fail with mdb_put: MDB_MAP_FULL: Environment mapsize limit reached

### ISSUE THREAD

**Issue by neverpanic** [neomutt/neomutt#267]
I recently started seeing `mdb_put: MDB_MAP_FULL: Environment mapsize limit reached` for the lmdb backend of the header cache. clibs/lmdb#1 is about the same problem and suggests we need to call `mdb_env_set_mapsize()` with a larger value, see http://lmdb.tech/doc/group__mdb.html#gaa2506ec8dab3d969b0e609cd82e619e5.

I'm documenting this so we're aware of this and it can be googled.

**Comment by flatcap** [comment]
Hmm... that's a bit worrying.  In `hcache-lmdb.c` we set the size to 1GiB.
```c
#define LMDB_DB_SIZE (1024 * 1024 * 1024)
mdb_env_set_mapsize(ctx->env, LMDB_DB_SIZE);
```

Please tell me your cache isn't _this_ big.

**Comment by neverpanic** [comment]
It is actually this big, sorry. That's about 425000 mails.

**Comment by flatcap** [comment]
Wow!

Well, I'll double the size.  Fortunately that won't impact other users.
(and you can reopen this bug when you get to 1 million emails).
