### ISSUE TITLE
Sidebar navigation (F5/F6) somewhat broken

### ISSUE THREAD

**Issue by mlmatlock** [neomutt/neomutt#2670]
## Expected Behaviour

Use F5/F6 key to navigate unread messages in sidebar.

## Actual Behaviour

If a message is opened, then re-flagged as 'New', then (for example) you move to the top of the folder hierarchy...then hit F5, it will skip to the first *unopened/unread* folder.

## If NeoMutt crashed, did your OS create a 'coredump' file?

No crash, but do have a bisect.

## Steps to Reproduce

Sample hierarchy:

INBOX - 1 new

Junk - 2 new

List1 - 3 new

List2 - 1 new

List3 - 5 new

Open List2.  Read message, decide I want to re-tag it as new (w-N).  Side bar reflects above.  

F8 to INBOX...subsequent F5 will move to:

Junk

List1

List3

If I get to List3, F6 *will not* move up to List2

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded from 2020-08-21 to 2020-09-25
  

## NeoMutt Version

```
NeoMutt 20200925
```

## Extra Info

* Operating System and its version

Arch Linux

* Were you using multiple copies of NeoMutt at once?

No

* Were you using 'screen' or 'tmux'?

No

* Is your email local (maildir) or remote (IMAP)?

IMAP (GMail/Cox)

**Bisect Results**

`7e743a9fe63bea20d20070e34c86837083790005 is the first bad commit
commit 7e743a9fe63bea20d20070e34c86837083790005
Author: Pietro Cerutti <gahr@gahr.ch>
Date:   Mon Aug 10 13:04:15 2020 +0000

    Convert Sidebar entries to ARRAY

 sidebar/functions.c | 154 +++++++++++++++++++++++++++++++---------------------
 sidebar/private.h   |   4 +-
 sidebar/sidebar.c   | 150 +++++++++++++++++++++++++++-----------------------
 sidebar/wdata.c     |  14 +++--
 4 files changed, 184 insertions(+), 138 deletions(-)`

**Comment by gahr** [comment]
Thanks for the detailed report, I’ll have a look.
