### ISSUE TITLE
Some redraws started blanking screen, causing tiring blinking

### ISSUE THREAD

**Issue by nabijaczleweli** [neomutt/neomutt#2672]
Since upgrading from 20200821 to 20200925, a *lot* of operations briefly blank the screen – `<imap-fetch-mail>` when there's new mail and it has to redraw, switching mailboxes, &c.

I mostly use NeoMutt in fullscreen and this exacerbates it, as most of my screen, save the sidebar, goes black, then white with text. This is *very* tiring on the eyes; thank dog I'm not photosensitive.

This also makes NeoMutt *feel* much slower, if only because there is no data on the screen for prolonged periods — on IMAP to localhost it's a few frames, but when going out to GMail it's up to a quarter/half-second every time.

Bisect says that 728a2e30e829f87e80b061999a4356e1214107da is the first bad commit.

**Comment by flatcap** [comment]
Ironically, that commit is a step towards fewer redraws.

The "perfect" situation I'm aiming for is:
- Events happen, which flag Windows as needing changes
- Flagged Windows are told to `recalc()` (this can be time-consuming)
- Flagged Windows are told to `redraw()` (this should be **instant**)

The screen isn't cleared at any time.
Windows are expected to fill their entire region on `repaint()`.

Unfortunately, bits of the code (pager) are still doing \*\*\*\* like:
```c
mutt_window_move_abs(0, 0);
mutt_window_clrtobot();
```

I'll start digging.

**Comment by flatcap** [comment]
List of naughty code:

- `menu_redraw_full()`
- `mutt_menu_pop_current()`
- `pager_custom_redraw()`

**Comment by flatcap** [comment]
Please can you give branch [[devel/repaint]](https://github.com/neomutt/neomutt/tree/devel/repaint) a try.

It eliminates the wiping of the entire screen.
It may not fix _your_ problem, but it needed doing.

**Comment by nabijaczleweli** [comment]
The only change I see with my bare eyes is that the divider between the index and the sidebar persists on `devel/repaint` but is cleared on `master`.

**Comment by flatcap** [comment]
OK, thanks.
I've tried inserting some `sleep()`s, but I haven't managed to reproduce the problem yet.

I'll add some debugging to the Window painting, when I have second.

**Comment by flatcap** [comment]
I've pushed:
- sub-second logging
- debugging for all the window redrawing

Please can you **`./configure --debug-window`** to enable it.

Then, can you post some logs where's there's been a slow refresh.
The critical bits will probably be between:

```
window_redraw() ------------------------------------------------------------
window_redraw() Begin redraw for Root Dialog
```
and
```
window_redraw() End redraw for Root Dialog
window_redraw() ------------------------------------------------------------
```

Thanks.

**Comment by nabijaczleweli** [comment]
Toward the end, as I went between two far-away mailboxes, the screen was blank for a long time each time: [.neomuttdebug0.gz](https://github.com/neomutt/neomutt/files/5298935/neomuttdebug0.gz)

And between two on localhost IMAP; less pronounced, didn't always blink, but did a few times: [.neomuttdebug1.gz](https://github.com/neomutt/neomutt/files/5298949/neomuttdebug1.gz)

Knowing nothing about the code behind this, this jumps out a few times in the second log as having the longest individual time, and 30ms is just about the right time for how long the blink was as I saw it:
```
[2020-09-29 14:29:17.9721]<2> window_recalc() Begin recalc for Sidebar
[2020-09-29 14:29:17.9753]<2> window_recalc() End recalc for Sidebar
```

With the corresponding in the first log:
```
[2020-09-29 14:23:09.9453]<2> window_recalc() Begin recalc for Sidebar
[2020-09-29 14:23:09.9525]<2> window_recalc() End recalc for Sidebar
```

**Comment by nabijaczleweli** [comment]
Haven't encountered this in recent memory

**Comment by nabijaczleweli** [comment]
20230322 brought this back in a minor way – screen blanked when switching mailboxes – but it's like fine.
