### ISSUE TITLE
neomutt-20200925-1.fc33.x86_64: shutdown-hook no longer works

### ISSUE THREAD

**Issue by sanjayankur31** [neomutt/neomutt#2676]
## Expected Behaviour 

I just noticed that my shutdown-hook does not seem to work any more. I run my fetch-mail script to sync when I close neomutt. So the neomuttrc has:

```
# Sync mail on close
shutdown-hook 'echo `fetch-mail.sh -q`'
```

The script itself is here (is just calls offlineimap etc.):
https://github.com/sanjayankur31/100_dotfiles/blob/master/bin/fetch-mail.sh

## Actual Behaviour

The script doesn't seem to be called on shutting down neomutt anymore. No crash here.

## Steps to Reproduce

- Install neomutt
- create a test script somewhere in PATH that says "Test neomutt!"
- add a shutdown-hook to neomuttrc to run the script: `shutdown-hook 'echo `test-neomutt.sh`'
- start neomutt, close

On close, "Test neomutt!" should be shown in the terminal, but isn't.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

I'm not sure, unfortunately. I only noticed it this morning. Perhaps with the latest update? I haven't changed my neomutt config recently.

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20200925
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.8.11-300.fc33.x86_64 (x86_64)
ncurses: ncurses 6.2.20200222 (compiled with 6.2.20200222)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.14.0
GnuTLS: 3.6.14
libnotmuch: 5.2.0
PCRE2: 10.35 2020-05-09
storage: tokyocabinet, lmdb
compression: lz4, zlib, zstd

Configure options: --sysconfdir=/etc SENDMAIL=/usr/sbin/sendmail ISPELL=/usr/bin/hunspell --notmuch --tokyocabinet --lmdb --lz4 --zlib --zstd --gnutls --sasl --gss --gpgme --disable-idn --idn2 --autocrypt --lua --pcre2

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pcre2 +pgp +sasl
  +smime +sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

## Extra Info

* Operating System and its version: Fedora 33 (beta at the moment)
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? tmux with byobu
* Is your email local (maildir) or remote (IMAP)? maildir, that is synced with offlineimap.

**Comment by flatcap** [comment]
Sorry about that.
I accidentally trampled over the `shutdown-hook` call whilst refactoring the sidebar.
Fixed.

**Comment by sanjayankur31** [comment]
No worries! Thanks very much for the quick fix! :smiley:

**Comment by sanjayankur31** [comment]
@flatcap : sorry, any chance of an update to the Fedora copr with this fix? I just realised that COPR doesn't keep the previous builds so one can't downgrade there

**Comment by flatcap** [comment]
OK, just this once, as you kindly mentioned NeoMutt in your Fedora Magazine interview :-)
NeoMutt 2020-09-28

**Comment by sanjayankur31** [comment]
haha, thanks very much :)
