### ISSUE TITLE
<tag-prefix><save-message> doesn't work in NeoMutt 20200925

### ISSUE THREAD

**Issue by mgedmin** [neomutt/neomutt#2679]
## Expected Behaviour

I was trying to save a bunch of messages into an archive folder, so I tagged them and pressed `;s` like I always do.

## Actual Behaviour

Nothing happened.  Instead of the "Save to mailbox" prompt I got nothing.  The `;` showed a `tag-` message in the status bar, and the `s` made it go away.

## (Updated) Steps to Reproduce

1. Open a mailbox with new mail
2. Limit to ~N
3. Read some messages
4. Tag some of the messages you read
5. Press `;s`

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use? **20200821**

## NeoMutt Version

```
NeoMutt 20200925
Copyright (C) 1996-2020 Michael R. Elkins ir kiti.
NeoMutt ateina ABSOLIUČIAI BE JOKIOS GARANTIJOS; dėl smulkmenų paleisk 'neomutt -vv.'
NeoMutt yra laisva programinė įranga, ir tu gali laisvai ją platinti su tam
tikromis sąlygomis; rašyk 'neomutt -vv' dėl smulkmenų.

System: Linux 5.4.0-48-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.13.1-unknown
GnuTLS: 3.6.13
libnotmuch: 5.2.0
storage: tokyocabinet

Configure options: --prefix=/usr --sysconfdir=/etc --with-mailpath=/var/mail --mixmaster --gnutls --gpgme --gss --sasl --lua --notmuch --tokyocabinet --full-doc

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Įprastos parinktys:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Kompiliavimo parinktys:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +regex +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

Jei norite daugiau sužinoti apie NeoMutt, aplankykite https://neomutt.org
Jei radote NeoMutt klaidą, praneškite apie ją
    https://github.com/neomutt/neomutt/issues
arba paštu į <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version  **Ubuntu 20.04**
* Were you using multiple copies of NeoMutt at once?  Not this time/
* Were you using 'screen' or 'tmux'?  No.
* Is your email local (maildir) or remote (IMAP)?  Local maildir.

**Comment by mgedmin** [comment]
Trying other tag-prefixed commands I see that e.g. `;|` will ask me for a filter command, but then will not run it.  `;d` and `;C` does nothing, just like `;s`.  `;p` asks for confirmation, and if I confirm, it says "messages could not have been printed".  Even `;t` doesn't untag anything.

**Comment by gahr** [comment]
I cannot reproduce this, I use tag-save every day :/

**Comment by mgedmin** [comment]
I did a git bisect, failed to find the bad commit, and now I can't reproduce it with 20200925 either!

**Comment by mgedmin** [comment]
Originally this happened when I read some mail in one folder, switched to another, read more messages, saved a few, then started tagging a bunch of similar cron problem emails for saving and suddenly `;s` failed to work.

**Comment by mgedmin** [comment]
Ran neomutt under valgrind, failed to reproduce the bug, but found

> ERROR SUMMARY: 337 errors from 5 contexts (suppressed: 0 from 0)

[valgrind.log](https://github.com/neomutt/neomutt/files/5309981/valgrind.log) attached, but the errors do not seem to be relevant (they're all invalid reads, so shouldn't be causing any memory corruption).

**Comment by mgedmin** [comment]
This never happened again, and I've seen no hints of memory corruption anywhere despite running with ASAN.

I don't think it's useful to keep this bug open.

**Comment by mgedmin** [comment]
This happened again, in 20200925-51-9c0d566.  I have the process still running and can attach to it with gdb, if only I knew what to look for.

**Comment by mgedmin** [comment]
So I'm in pdb trying to step through and see what happens if I press `;t` while I have two messages tagged.

What happens is this loop
https://github.com/neomutt/neomutt/blob/81dfb6aa574c47b529b2fa7b4edb0f1c1a5a0fa3/index.c#L1928-L1935

goes through all 106 messages without once entering the body of `if (e->visible)`.

I have an active limit pattern (~N) that match 6 out of 106 messages.

**Comment by mgedmin** [comment]
I can change the limit pattern to ~A and then everything works fine.

**Comment by mgedmin** [comment]
Okay, I have new steps to reproduce:

1. Open a mailbox with some new mail
2. Limit to ~N
3. Tag some messages
4. Read some of the tagged messages

Now any tag-prefixed command takes effect only on those messages that are still unread!

**Comment by mgedmin** [comment]
git bisect says

86afffa524992e2ddda49a1f09c477cf1d4dc88f is the first bad commit
commit 86afffa524992e2ddda49a1f09c477cf1d4dc88f
Author: Pietro Cerutti <gahr@gahr.ch>
Date:   Fri Sep 4 07:39:00 2020 +0000

    Make sure all mail gets applied the index limit
    
    Fixes #2631

 index.c | 14 ++++++--------
 1 file changed, 6 insertions(+), 8 deletions(-)

**Comment by gahr** [comment]
Thanks for the bisect, I'll look into this

**Comment by mgedmin** [comment]
Uh, I'm seeing this again with 20201127.

**Comment by gahr** [comment]
@mgedmin mind to open a new issue with fresh info and details? I am pretty sure we haven't broken this same thing between 1120 and 1127.

**Comment by mgedmin** [comment]
Fair enough!

(also, I can't reproduce on git master, which is good enough for now.)
