### ISSUE TITLE
Can't enable flatcap/neomutt for dnf copr

### ISSUE THREAD

**Issue by FrazerClews** [neomutt/neomutt#2687]
## Expected Behaviour

`dnf copr enable flatcap/neomutt` would enable the NeoMutt COPR

## Actual Behaviour

Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.

Do you really want to enable copr.fedorainfracloud.org/flatcap/neomutt? [y/N]: **y**
**Error: This repository does not have any builds yet so you cannot enable it now.**

If NeoMutt crashed, did your OS create a 'coredump' file?

## Steps to Reproduce

`sudo dnf copr enable flatcap/neomutt`

## How often does this happen?

- Always

## When did it start to happen?

- First time using it

## Extra Info

* Operating System and its version: Fedora 32
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? N/A

**Comment by flatcap** [comment]
Hmm... that's odd.
The builds are definitely still there, I've just checked:
- https://copr.fedorainfracloud.org/coprs/flatcap/neomutt/builds/

I've also just checked the install.
From a clean minimal install of Fedora 32,
```
$ dnf copr enable flatcap/neomutt

Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.

Do you really want to enable copr.fedorainfracloud.org/flatcap/neomutt? [y/N]: y

Repository successfully enabled.
```

Can you try clearing things out and trying again.
- `dnf copr remove flatcap/neomutt`
  (make sure that `/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:flatcap:neomutt.repo` is gone)
- `dnf clean all`
  (clear out caches)
- `dnf update`

Then re-try the `dnf copr enable`

**Comment by FrazerClews** [comment]
Still having the same issue I am afraid, I am running Fedora 32 through WSL if that maybe an issue?

**Comment by flatcap** [comment]
> I am running Fedora 32 through WSL

fascinating :-)

> Still having the same issue

OK.  the `copr` command is just a helper. Perhaps it's trying to do something odd.
Let's try it manually.
As `root`:
```
cd /etc/yum.repos.d/
wget https://copr.fedorainfracloud.org/coprs/flatcap/neomutt/repo/fedora-32/flatcap-neomutt-fedora-32.repo
dnf update
dnf install neomutt
```

**Comment by flatcap** [comment]
Hmm... I've had a thought.
The repo file (`flatcap-neomutt-fedora-32.repo`) that gets installed has a couple of variables in it:
```
baseurl=https://download.copr.fedorainfracloud.org/results/flatcap/neomutt/fedora-$releasever-$basearch/
```

I wonder if there's something strange with your Fedora install.
You could try filling in the blanks:

```
baseurl=https://download.copr.fedorainfracloud.org/results/flatcap/neomutt/fedora-32-x86_64/
```

**Comment by FrazerClews** [comment]
Yeah 

> > I am running Fedora 32 through WSL
> 
> fascinating :-)
> 
> > Still having the same issue
> 
> OK. the `copr` command is just a helper. Perhaps it's trying to do something odd.
> Let's try it manually.
> As `root`:
> 
> ```
> cd /etc/yum.repos.d/
> wget https://copr.fedorainfracloud.org/coprs/flatcap/neomutt/repo/fedora-32/flatcap-neomutt-fedora-32.repo
> dnf update
> dnf install neomutt
> ```

Yeah this worked, thanks

**Comment by flatcap** [comment]
Brilliant :-)
