### ISSUE TITLE
neomutt-patches-20160502 doesn't apply cleanly over mutt-1.6.1

### ISSUE THREAD

**Issue by paravoid** [neomutt/neomutt#27]
This does not work:
```
$ wget https://github.com/neomutt/neomutt/releases/download/neomutt-20160502/neomutt-patches-20160502.tar.gz
$ wget ftp://ftp.mutt.org/pub/mutt/mutt-1.6.1.tar.gz
$ tar -xzf mutt-1.6.1.tar.gz
$ tar -xzf neomutt-patches-20160502.tar.gz
$ cd mutt-1.6.1/
$ QUILT_PATCHES=../neomutt-patches-20160502 quilt --quiltrc /dev/null push -a
```

Patch 02-04 apply with offset and sometimes fuzz, patch 05 ultimately fails.

**Comment by flatcap** [comment]
@paravoid 
Ah, yes.  I'm not sure what I can do about that.

The patches are separate so anyone can pick and mix the ones they want.
Each patch will apply cleanly to 1.6.1, but some combinations of patches will need adjustment.

The neomutt patch is all the patches correctly assembled in the numbered order.
It, too, applies cleanly to 1.6.1.

For me, it's easy.  Each patch is: `git diff mutt-1.6.1 XXX`
I only have to worry about adjustment for the first merge into [neomutt].

The current repo gives me independent features with a full history.

I want to try to please everyone, but I don't want each release to take me a week's work.

---

Feel free to throw lots of patch management ideas at me, now.

I'm hoping for something git-aware.
I want the patches to be version controlled
I'd like all the work to happen by magic :-)

---

I'm off to experiment with quilt/guilt/topgit/stgit/git.

**Comment by flatcap** [comment]
@paravoid 
The new release contains two sets of patches:
- **neomutt-patches** -- Separate feature patches, each against Mutt-1.6.1
- **neomutt-distro** -- Ordered patchsets (features and bugfixes) based on Mutt-1.6.1

To reduce confusion, the separate patches are no longer numbered and there's no series file.
