### ISSUE TITLE
sidebar_short_path not shortening the path

### ISSUE THREAD

**Issue by Knusper** [neomutt/neomutt#270]
I just upgraded from NeoMutt 2016-11-04 to 2016-11-26 and suddenly my sidebar became much uglier.

Before it was:

    mailbox1/Inbox
    mailbox1/junk
    mailbox1/sent
    mailbox2/Inbox
    mailbox2/junk
    mailbox2/sent

and now it became:
 
    /home/knusper/Mail/mailbox1/Inbox
    /home/knusper/Mail/mailbox1/junk

etc.

I set and unset the variable `sidebar_short_path`, but it has absolutely no effect.

In my .muttrc I have:

    set folder=~/Mail/   
    mailboxes "+/mailbox1/Inbox" \
              "+/mailbox1/junk"
    
and so on...

From what I read in the documentation, the variable `sidebar_short_path` should prevent exactly this.

**Comment by flatcap** [comment]
Hmm... I haven't knowingly altered the sidebar parsing code.
I've just done a quick check and I can't reproduce your problem.

Using this basic config (`knusper.rc`):
```
set sidebar_visible
set folder=~/Mail/   
mailboxes +/mailbox1/Inbox
mailboxes +/mailbox1/junk
mailboxes +/mailbox1/sent
mailboxes +/mailbox2/Inbox
mailboxes +/mailbox2/junk
mailboxes +/mailbox2/sent
```

I tried both:
- `neomutt-20161104 -n -F knusper.rc`
- `neomutt-20161126 -n -F knusper.rc`

and both showed:
```
/mailbox1/Inbox
/mailbox1/junk               
/mailbox1/sent               
/mailbox2/Inbox              
/mailbox2/junk               
/mailbox2/sent 
```

Please can you give this minimalist config a try.

**Comment by gahr** [comment]
@Knusper Are you able to reproduce with a newer version of neomutt?
Also, what's your `sidebar_delim_chars` variable set to?

**Comment by Knusper** [comment]
I will get back to you on the weekend regarding testing with a newer version.

`sidbar_delim_chars = '|'`

**Comment by gahr** [comment]
@Knusper that's why, then. `sidebar_delim_chars` is what is used as a path separator when shortening the paths. Please set it to `'./'`.

**Comment by Knusper** [comment]
OK - `sidebar_delim_chars = '/'` and `set_short_path=no` produces nearly what I want.  But I also have to make `mailboxes +mailbox1/Inbox` instead of `+/mailbox1/Inbox` to remove the trailing slash.   Anyway, now it works again. And I think this bug is invalid, it was just strange that it worked before with my wrong configuration.  The reason I probably got confused was, that `sidebar_delim` sounds very similar to `sidebar_delim_chars` - and  `sidebar_delim` now got renamed to `sidebar_divider_char` ... and instead of `divider` I just added `delim`... does that make sense...

**Comment by gahr** [comment]
Yep that explains. Thanks!
