### ISSUE TITLE
Viewing calendar invitations automatically along with text of email

### ISSUE THREAD

**Issue by protist** [neomutt/neomutt#2709]
I have neomutt set up to display calendar events inline using [mutt-ics](https://github.com/dmedvinsky/mutt-ics). i.e., in `~/.mutt/muttrc`:
```
auto_view text/calendar application/ics
alternative_order  text/calendar text/plain text/enriched text/html
set mailcap_path = ~/.mutt/mailcap
```
And in `~/.mutt/mailcap`:
```
application/ics; mutt-ics; copiousoutput
```
In the following email (from the dreaded Zoom), the calendar and text are alternatives:
```
->   I     1 <no description>                                          [multipa/alternativ, 7bit, 6.7K]
     I     2 ├─><no description>                               [text/plain, quoted, windows-1252, 0.8K]
     I     3 ├─><no description>                                [text/html, quoted, windows-1252, 1.7K]
     I     4 └─><no description>                                   [text/calendar, base64, utf-8, 3.7K]
```
With my `alternative_order` setting above, this preferences `text/calendar` over `text/plain`. It seems like I can only show one or the other.

Is there a way to show both calendar and email (`text/plain`) together in the same pager window? Failing that, is there a way to mark the email somehow to show there is a `text/calendar` attachment?

**Comment by gahr** [comment]
I suggest
```
set implicit_autoview=yes
message-hook . 'set show_multipart_alternative=info'
message-hook '~b text/calendar' 'set show_multipart_alternative=inline'
```

**Comment by protist** [comment]
Thanks @gahr, that's a pretty good workaround. I wasn't familiar with `show_multipart_alternative`. I'm tempted to leave that on all the time, because I often miss attached images, pdfs, etc. Is there a way to show all alternatives, with the exception of `text/html` if there is `text/plain` present?

**Comment by gahr** [comment]
>  Is there a way to show all alternatives, with the exception of text/html if there is text/plain present?

I can't think of a way off hand. I'll let you go through the docs...
