### ISSUE TITLE
set in-reply-to when forwarding a message

### ISSUE THREAD

**Issue by zacchiro** [neomutt/neomutt#2712]
## What would you like to be able to do?

When forwarding a message, it would be nice to (optionally?) set in-reply-to in the composed email to the message being forwarded. That would make the new forward email appear in the thread with the forwarded message by default. And even when strict_threads is not in use, having a real in-reply-to link between the new message and the forwarded message would be useful, e.g., when mutt is not the only MUA used on the mailbox that will keep the new and the forwarded message.

## What needs to change in NeoMutt?

A new option could be added, maybe defaulting to "no", to add the in-reply-to link when forwarding messages.

## Have you tried any alternative methods?

I haven't found a way to do this with macros.
For now I have an editor hook that, when composing the forward message, adds the header (as I'm also using edit_headers). But that still feels a bit too manual for my taste. Also, it is editor-specific (emacs in my case).

## Additional Info

I've found a [14-year old feature request](https://mutt-users.mutt.narkive.com/1ciYnxvt/threading-forwarded-messages) about this, with no satisfying solution AFAICT.

Thanks a lot for maintaining neomutt !

**Comment by gahr** [comment]
Hi @zacchiro, what exactly is the use case? I guess it makes sense if your fcc is set to the folder that contains the original message, so you could thread together the original message sent to you and the one you created as a forward. However, I'm a bit reluctant to include references to message ids in emails you send to a 3rd person that does not have the original message (if it does have the original message, why forward it ?).

**Comment by zacchiro** [comment]
On Wed, Oct 21, 2020 at 03:36:33AM -0700, Pietro Cerutti wrote:
> Hi @zacchiro, what exactly is the use case? I guess it makes sense if
> your fcc is set to the folder that contains the original message, so
> you could thread together the original message sent to you and the one
> you created as a forward. However, I'm a bit reluctant to include
> references to message ids in emails you send to a 3rd person that does
> not have the original message (if it does have the original message,
> why forward it ?).

First, thanks a lot for your feedback!

My use case is threading messages related to the same conversation. From
the user point of view, a forward is a "spin-off" of a conversation
getting someone else in the loop (and also removing someone else), but
it's still part of the same "thread" as an organization unit.

This is in part achievable via Mutt's non strict threads, but that's a
mutt-specific thing, so the real structure of the information (as
represented in a mbox, which for me is a portable thing) is lost.

In fact, I'm right now either adding the in-reply-to by hand when
forwarding, or a posteriori link together the forward email with the
forwarded message (using &). What I'd like to have is a way to tell mutt
"please automate this thing for me".

You have a point about leaking the Message-Id, but it'd be optional, and
opt-in, so I don't see the problem with that.

Cheers

**Comment by flatcap** [comment]
One possibility is to only add the Message-Id to the fcc (the saved copy).
Your email gets threaded and no information is leaked.

The original poster talks about using a Bcc to himself -- my suggestion wouldn't work there.

**Comment by gahr** [comment]
> a forward is a "spin-off" of a conversation
getting someone else in the loop (and also removing someone else), but
it's still part of the same "thread" as an organization unit.

This looks to me very much like a "group-reply" (or "group-chat-reply" if you don't want to include everybody by default) + adjusting the recipients manually.

I am still unconvinced that a forward should keep references to the original message...

**Comment by zacchiro** [comment]
On Thu, Oct 22, 2020 at 04:34:15AM -0700, Pietro Cerutti wrote:
> This looks to me very much like a "group-reply" (or "group-chat-reply"
> if you don't want to include everybody by default) + adjusting the
> recipients manually.

I disagree on the basis that when you forward, you most motably forward
attachments, which you very much don't do when group replying.

> I am still unconvinced that a forward should keep references to the
> original message...

That's fine.

What I don't get is the ground for your objection to this being an
opt-in feature.

**Comment by gahr** [comment]
> I disagree on the basis that when you forward, you most motably forward
attachments, which you very much don't do when group replying.

Good point.

> What I don't get is the ground for your objection to this being an
opt-in feature.

I think I'm just trying hard to see whether the use case can be accomodated without an additional config variable :)

**Comment by gahr** [comment]
ehm.. this is a bit embarassing, but `set forward_references = yes` probably does what you want ;)

**Comment by zacchiro** [comment]
On Thu, Oct 22, 2020 at 06:24:28AM -0700, Pietro Cerutti wrote:
> ehm.. this is a bit embarassing, but `set forward_references = yes`
> probably does what you want ;)

Uh?

I don't have it in my mutt manual, and I had checked all forward_*
options before submitting this feature request. What am I missing?

**Comment by gahr** [comment]
What version are you using?

**Comment by gahr** [comment]
This was implemented in #252.

**Comment by zacchiro** [comment]
OK, I figure out what was going on!
I'm using neomutt 2020-06-26, but I had checked the *mutt* manual (version 1.14.6), which doesn't have that option.
Hence my mistake. So, false alarm, all is good, I'm closing this now.

… and thanks for the great `forward_references` feature, I love it :-)
