### ISSUE TITLE
Constantly asking for keyID when replying to encrypted email

### ISSUE THREAD

**Issue by frddbbbl** [neomutt/neomutt#2720]
Hi, recently my neomutt (i dont belive i have made any changes since it started happening) has started asking for an emails keyid when replying to an encrypted email. i had this problem a long time ago with mutt and dont remember what the solution was. typically it used to just automatically encrypt them.
my .gpgrc setup is:
```
set pgp_sign_as = 0x2C2CD561
set crypt_use_gpgme = yes
set crypt_autosign = yes
set crypt_verify_sig = yes
set crypt_replysign = yes
set crypt_replyencrypt = yes
set crypt_replysignencrypted = yes
```
and the (possibly) relevant sections of my .muttrc are:
```
source ~/.gpgrc
source /usr/share/doc/neomutt-20180716/samples/colors.linux
set folder = ~/mail
set header_cache = ~/.mutt/cache/headers
set message_cachedir = ~/.mutt/cache/bodies
set certificate_file = /etc/ssl/certs/ca-certificates.crt
set mailcap_path = ~/.mutt/mailcap
set tmpdir = ~/.mutt/tmp

#basic options
set wait_key = no
set mbox_type = Maildir
set timeout = 3
set mail_check = 0
set delete
set quit
set thorough_search
set mail_check_stats
set sleep_time = 0
unset confirmappend
unset move
unset mark_old
unset beep_new

#compose options
set envelope_from
set edit_headers
set fast_reply
set fcc_attach
set forward_format = "Fwd: %s"
set forward_decode
set attribution = "0n %d, %n wrote:"
set reply_to
set reverse_name
set include
set forward_quote
set editor = "mg"
set text_flowed
unset sig_dashes
unset mime_forward
#email headers and attachments
ignore *
unignore from: to: cc: bcc: date: subject:
unhdr_order *
hdr_order from: to: cc: bcc: date: subject:
alternative_order text/plain text/enriched text/html
auto_view text/html
```

thanks for your time.

**Comment by gahr** [comment]
Hi @frddbbbl - I understand you are trying to both sign and encrypt the reply. Is it asking for the key to use for which operation? If it's asking for the public key of your recipient, is it possible that your recipient has updated his/her key and you now have two keys for the same email address in your keyring?

**Comment by frddbbbl** [comment]
Hi, It is asking for the recipients ID, the recipients I've had issue with so far both use googlemail. I'm quite hazy about how the keyring works for neomutt but will look at it today.
Cheers
Freddie

**Comment by gahr** [comment]
The keyring is not neomutt-specific. Please have a look at the output of `gpg -k | grep -B1 <recipient@gmail.com>` to see how many public keys you have for that recipient. If you have more than one, NeoMutt will ask which to use.

**Comment by frddbbbl** [comment]
Oh ok, the reason I thought it might have been separate is the only key in gig -k is my own.there is none of any recipients. Maybe it is worth mentioning that one of  my emails, countermail, is encrypted. however I still get the issue when trying to send with non encrypted email I use

**Comment by gahr** [comment]
mh.. that's the issue: how can you encrypt to recipients if you don't have the recipients' public keys in your keyring?

**Comment by frddbbbl** [comment]
why would it be that I used to be able to send encrypted email to them but recently have not been able to? and how would I get someones public key for there gmail account?

**Comment by brunnre8** [comment]
gmail doesn't do gpg encryption by default.

You'll need to fetch the key by whatever means the person you are trying to communicate with set up... be that a key server or a personal website etc

**Comment by frddbbbl** [comment]
The people who are communicating with me are my parents so definitely haven't set up a keyid haha. the emails I receive from the are encrypted but I believe this is done by my email server when it receives them, not by the person themselves

**Comment by brunnre8** [comment]
protonmail? yeah but that's after receiving the mails in plain text (over TLS if it could, plain, plain if it couldn't)

**Comment by frddbbbl** [comment]
countermail, but I think it is essentially the same. so do I just need to change my gpgrc to not automatically encrypt emails?

**Comment by brunnre8** [comment]
well, unless you have the private key available you can't encrypt can you?

So in essence yes.
Keep in mind gpg isn't *that* widespread. And if you interact with mailing lists etc useless.

**Comment by frddbbbl** [comment]
Sorry, I mean automatically encrypt if the key was available and do nothing if its not.
Cheers,
Freddie
