### ISSUE TITLE
log in to news server

### ISSUE THREAD

**Issue by jimerickson** [neomutt/neomutt#2722]
Before asking a question, please check:

- NeoMutt Guide: https://neomutt.org/guide/
- Google:        https://www.google.com j/

when attempting to log in to news.eternal-september.org neomutt always returns "SCRAM-SHA-1 authentication failure". I have the following line in my neomuttrc for the nntp server:
````
set news_server =  nntp://johndoe:XXXXXXXX@news.eternal-september.org:119 
````
obviously i am doing something wrong but what is it?

**Comment by gahr** [comment]
Can you please try with `set nntp_authenticators = user`?

**Comment by jimerickson** [comment]
thank you so much!! that works great!
