### ISSUE TITLE
can't log in to news.eternal-september.org

### ISSUE THREAD

**Issue by jimerickson** [neomutt/neomutt#2723]
Before asking a question, please check:

- NeoMutt Guide: https://neomutt.org/guide/
- Google:        https://www.google.com j/

i currently can't login to news.eternal-september.org. any attempt to do so yields 'SCRAM-SHA-1 authentication failure". i have the following line in my .neomuttrc :
````
set news_server =  nntp://jimerickson:XXXXXXXXXX@news.eternal-september.org:119 
````
this is as per the eternal-september website instructions for mutt. what am i doing wrong?

**Comment by gahr** [comment]
Dup of #2722
