### ISSUE TITLE
macro not working as expected with limit

### ISSUE THREAD

**Issue by karlsebal** [neomutt/neomutt#2728]
## Expected Behaviour

I want to create a macro via `macro index X "l ~f somebody"` According to [documentation](https://neomutt.org/guide/configuration.html#10-%C2%A0keyboard-macros), a macro should »behave as if you had typed _sequence_«

## Actual Behaviour

the limit command does not delete the former search as it does when typing manually. Say, former search was all (`a`), line now shows `a ~f somebody` and another try just appends the search again.

workaround for me is `macro index X "l ~f somebody <home><delete>"` and doing `l a` manually beforehand.

## How often does this happen?

- Always

## When did it start to happen?

I just noticed.

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.0-52-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.13.1-unknown
libnotmuch: 5.2.0
hcache backends: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-WmwApX/neomutt-20191207+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

```

## Extra Info

* Operating System and its version ubuntu 20.04
* Were you using multiple copies of NeoMutt at once? no.
* Were you using 'screen' or 'tmux'? no.
* Is your email local (maildir) or remote (IMAP)? imap

**Comment by gahr** [comment]
This is working fine, and it is literally »behave as if you had typed sequence«. The problem is that your sequence is
<kbd>l</kbd> <kbd>space</kbd> <kbd>~</kbd> ....

What you want is `macro index X "l~f somebody"`

**Comment by karlsebal** [comment]
Oh, thank you! I could not conclude this from the documentation -- maybe a hint would be fine since whitespace is ignored in general.

**Comment by gahr** [comment]
> maybe a hint would be fine since whitespace is ignored in general.

Sure, are you willing to open a PR with your suggestion? Thanks
