### ISSUE TITLE
Run shell command in background

### ISSUE THREAD

**Issue by joshuachp** [neomutt/neomutt#2729]
I wanted to sync a mailbox on startup and with a macro. To sync the mailbox I'm currently using OfflineIMAP. 

My current solution is to delay the call to OfflienIMAP and use it as a sysemd service (since I also need a timer) and start it with a `nohup` background process.
```bash
startup-hook 'echo `nohup systemctl --user start offlineimap-oneshot.service &> /tmp/nohup &`'

macro index,pager c "<shell-escape>nohup systemctl --user start offlineimap-oneshot.service &> /tmp/nohup &<enter>"
```
To me this seems to be an over complicated solution. 

Is there a better way to run a command in the background from neomutt?

**Comment by gahr** [comment]
FTR - running a command in the background is achieved using standard shell notation: `&`.
