### ISSUE TITLE
Bindable command to unsubscribe from a mailing list

### ISSUE THREAD

**Issue by nobrowser** [neomutt/neomutt#273]
Reading [this thread](https://mail.haskell.org/pipermail/haskell-cafe/2016-December/125809.html), debaters justify the obnoxious practice of appending a "footer" to mailing lists messages by the need to make unsubscribe easy for newbies.  But all the information is there to make the MUA do it!  Maybe *mutt can be the first there.

**Comment by flatcap** [comment]
> obnoxious practice of appending a "footer"

Yuck!

It sounds like a good idea, but it may require a bit of thought to be versatile.

You can also add a "subscribe" option for people copied onto lists.

A quick search shows that the headers of various "mailing lists" vary a great deal.
Some give two options: web link or email address.

I came up with an idea (a while back) for a very specific mailing list handler -- a GitHub Assistant.
GitHub encodes quite a lot of useful info into the headers -- it'd be nice to be able to extract this and add icons to the index:
https://github.com/neomutt/flatcap-brain-dump/blob/master/github-assistant.txt


## neomutt

```
Precedence: list
List-Id: Teaching an Old Dog New Tricks <neomutt-devel-neomutt.org>
List-Unsubscribe: <http://mailman.neomutt.org/mailman/options/neomutt-devel-neomutt.org>, <mailto:neomutt-devel-request@neomutt.org?subject=unsubscribe>
List-Archive: <http://mailman.neomutt.org/pipermail/neomutt-devel-neomutt.org/>
List-Post: <mailto:neomutt-devel@neomutt.org>
List-Help: <mailto:neomutt-devel-request@neomutt.org?subject=help>
List-Subscribe: <http://mailman.neomutt.org/mailman/listinfo/neomutt-devel-neomutt.org>, <mailto:neomutt-devel-request@neomutt.org?subject=subscribe>
Errors-To: neomutt-devel-bounces@neomutt.org
Sender: neomutt-devel <neomutt-devel-bounces@neomutt.org>
```

## mutt

```
Precedence: bulk
List-Post: <mailto:mutt-dev@mutt.org>
List-Unsubscribe: send mail to majordomo@mutt.org, body only "unsubscribe mutt-dev"
Sender: owner-mutt-dev@mutt.org
```

## github

```
Precedence: list
X-GitHub-Sender: riesebie
X-GitHub-Recipient: flatcap
X-GitHub-Reason: mention
List-ID: neomutt/neomutt <neomutt.neomutt.github.com>
List-Archive: https://github.com/neomutt/neomutt
List-Post: <mailto:reply+00012bd8aaf1c14@reply.github.com>
List-Unsubscribe: <mailto:unsub+00012bd8aaf1c141@reply.github.com>, <https://github.com/notifications/unsubscribe/AAEr2D4t06_JQ-R>
X-GitHub-Recipient-Address: rich@flatcap.org
```

## debian

```
X-Distro-Tracker-Package: mutt
X-Distro-Tracker-Keyword: bts
List-Id: <mutt.tracker.debian.org>
X-Debian-Package: mutt
X-Debian: tracker.debian.org
X-PTS-Package: mutt
X-PTS-Keyword: bts
Precedence: list
List-Unsubscribe: <mailto:control@tracker.debian.org?body=unsubscribe%20mutt>
```

## suse

```
X-Bugzilla-Reason: CC
X-Bugzilla-Type: changed
X-Bugzilla-Watch-Reason: None
X-Bugzilla-Classification: openSUSE
X-Bugzilla-Product: openSUSE Tumbleweed
X-Bugzilla-Component: Basesystem
X-Bugzilla-Version: Current
X-Bugzilla-Keywords:
X-Bugzilla-Severity: Major
X-Bugzilla-Who: lpechacek@suse.com
X-Bugzilla-Status: NEW
X-Bugzilla-Priority: P5 - None
X-Bugzilla-Assigned-To: werner@suse.com
X-Bugzilla-QA-Contact: qa-bugs@suse.de
X-Bugzilla-Target-Milestone: ---
X-Bugzilla-Flags:
X-Bugzilla-Changed-Fields: attachments.created
X-Bugzilla-NTS-Support-Num:
X-Bugzilla-URL: http://bugzilla.suse.com/
```

**Comment by nobrowser** [comment]
I would start with handling just the mailto: case, which seems to be what mailman does, and so the most widespread.  majordomo lists like mutt-users can easily change their human-readable blurb to include a mailto: link instead of a bare address.

**Comment by guyzmo** [comment]
to be honest, I don't think this should be a feature of neomutt. The cases are so different for each mailing list handler, that an external tool would better do the job.

For example I got an ugly [`muttrc` hack](http://starship.python.net/crew/jwt/mailman/) to handle quick approval of mail to moderate on the lists I'm an admin of:

```
macro index X ':set fast_reply=yes^M:set editor="touch %s"^Mv/confirm ^Mrf^A^K^Myqd:reset fast_reply^M:set editor="vim %s"^M'
macro pager X ':set fast_reply=yes^M:set editor="touch %s"^Mv/confirm ^Mrf^A^K^Myqd:reset fast_reply^M:set editor="vim %s"^M'
```

I'm pretty sure something close (and cleaner) can be worked out to handle list unsubscription. But TBH, I wouldn't want my MTA to have that as a feature, as a macro eventually integrating an external tool, why not — the same way we can display HTML messages.

**Comment by nobrowser** [comment]
Newbies don't write mutt macros.  That said, here is evidence that nothing, not even the link right there in the email body, will work:

[https://sympa.inria.fr/sympa/arc/caml-list/2016-12/msg00103.html](https://sympa.inria.fr/sympa/arc/caml-list/2016-12/msg00103.html)

So, I suppose I give up :-1:

**Comment by guyzmo** [comment]
they don't but one thing is that mutt is aimed at powerusers, not newbies, and another is that newbies can copy/paste ☺
