### ISSUE TITLE
Fix simple typo: dsize -> size

### ISSUE THREAD

**Issue by timgates42** [neomutt/neomutt#2734]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate

1. Examine mutt/string.c, test/string/mutt_str_copy.c, test/string/mutt_strn_copy.c.
2. Search for `dsize`.

# Expected Behaviour

1. Should read `size`.

automated PR generated by https://github.com/timgates42/meticulous/

**Comment by brunnre8** [comment]
Can you please disable that bot?

The spelling is correct and as designed... 'dsize' == 'destination_size' but generally one doesn't use quite that long identifiers in C...
