### ISSUE TITLE
Multiple file attachments with Vifm or Ranger

### ISSUE THREAD

**Issue by anufrievroman** [neomutt/neomutt#2738]
Would be great to use Vifm or Ranger file managers for file attachments instead of mutt's built-in file manager, because of multiple files issue and general ease of use.
I've made [repository with a bash script that does just that](https://github.com/anufrievroman/Neomutt-File-Picker).
I feel like it could be easily integrated into neomutt, but I have no knowledge to contribute directly to neomutt myself, sorry.

**Comment by gahr** [comment]
I was surprised to see that the attachment dialog doesn't support navigating around, tagging entries (files) and attaching them all when you quit. I am not sure whether it's a bug or it was never supported.

Anyway, I think we could add your script somewhere in the contrib/ directory of this repo, what do you think? Do you want to have a look and come up with a PR for inclusion?

**Comment by anufrievroman** [comment]
I imagine an implementation could be like putting **filepicker** script was somewhere in neomutt's files, and in muttrc we could just write:
`bind compose A use_filemanager`

and `use_filemanager` function would be defined somewhere as:
`<shell-escape><path_to_filepicker><enter><enter-command>source $HOME/.config/mutt/tmpfile<enter><shell-escape><path_to_filepicker> clean<enter> `

But once again, unfortunately I have no knowledge to implement it myself.
Or do you mean I should just drop the script somewhere in contrib/ folder and maybe someone will look at it later? Sorry, I don't contribute to big projects often, not sure how it is supposed to work.

**Comment by gahr** [comment]
Yeah, I suggest you just drop it in there under a dedicated folder, together with an example rc file to source that perhaps bind a macro. Just as a sample.

But let me look at NeoMutt’s file browser first and see why tagging multiple files does not work already.

**Comment by gahr** [comment]
I have fixed the possibility to attach multiple files by tagging them in the file browser in #2744. Would that work for you?

**Comment by anufrievroman** [comment]
Thank you! That's great. I'll check it. Though, it will take me some time to do it, so feel free to close the issue.

**Comment by jindraj** [comment]
There has been similar question [Neomutt run command to attach file on macro key press](https://unix.stackexchange.com/a/612194/85046) on unix stackexchange. The solution are 2 macros. This might be interesting for people looking for similar solution.

**Comment by gahr** [comment]
Hi @anufrievroman, as @flatcap made me realize, attaching multiple files works already, by tagging multiple files and finishing with enter... what functionality is missing in your opinion?

**Comment by anufrievroman** [comment]
@gahr but then which key it tagging multiple files? Sorry if I missed it.

Ideally, I'd like to use an external file manager (Vifm, Ranger, nnn etc) that I use for all other file operations for these reasons:
- I can use bookmarks to jump directly where I want.
- mutt's file picker has strange keybindings (no "l", "h" to go forward/backward), and I still have no idea which key tags multiple files if this was working.
- no idea how to do various things, for example, display hidden files.
- general aesthetics: it displays all the unnecessary permissions info, file and folder are of the same colors.
Perhaps this all might be configurable but I didn't find it in the manual or help, sorry if it is there.

That is why I propose a solution similar to what @jindraj linked, but seems like the script in his link does not support multiple files and spaces in names, while [mine](https://github.com/anufrievroman/Neomutt-File-Picker) does.
In general, I feel like many who uses mutt are also using terminal file managers, so that it would only be natural if they could work together. Would be nice if this was an native options in mutt, instead of a script from the internet.

**Comment by gahr** [comment]
<kbd>t</kbd> toggles tags on files. Make sure `%t` is part of your `folder_format` so you have a visual indication of which files are tagged. When you're done navigating around and tagging the files you want to attach, press <kbd>enter</kbd>.

**Comment by gahr** [comment]
> I can use bookmarks to jump directly where I want.

Perhaps you can use [`macro`s](https://neomutt.org/guide/configuration.html#10-%C2%A0keyboard-macros) to `change-dir` to specific places.

> mutt's file picker has strange keybindings (no "l", "h" to go forward/backward), and I still have no idea which key tags multiple files if this was working.

You can [`bind`](https://neomutt.org/guide/configuration.html#bind) the keys you prefer.

> no idea how to do various things, for example, display hidden files.

The [`mask`](https://neomutt.org/guide/reference#3-186-%C2%A0mask) decides which files are shown and which are hidden.

> general aesthetics: it displays all the unnecessary permissions info, file and folder are of the same colors.

See if [`folder-format`](https://neomutt.org/guide/reference#folder-format) helps.

Having said that, I understand the will to use an external program you're more comfortable with. Please look at out `contrib` directory for examples and open a PR for inclusion :)

**Comment by gerazov** [comment]
Would really like to see this feature - it is a bit redundant and inefficient to setup all keybindings (and bookmarks) from Vifm if we could just plug it in. 

A similar feature is already implemented to use Vim as the pager, rather than remapping stuff.
