### ISSUE TITLE
Doc issue in  "Attachment Searching and Counting"

### ISSUE THREAD

**Issue by rionda** [neomutt/neomutt#2739]
The documentation in https://neomutt.org/guide/mimesupport#attachments is a bit imprecise.

The example configuration says "The MIME elements contained within a message/* or multipart/* are still examined, even if the containers themselves don't qualify.", which is not completely true: for multipart/alternative, one has to set `$count_alternatives` to `yes` (available since 45eb05c8ac6179e63cc6048ddf85017e6aeea72e, while before this revision there was not even a way to have enable this recursion.) 

The fix would be to change the example to say something like: "The MIME elements contained
within a message/* or multipart/* are examined, independently of whether the containers themselves qualify or not, wit the exception of MIME elements contained within a multipart/alternative, which are only examined if $count_alternative is set to yes."

**Comment by gahr** [comment]
Thanks Matteo, does my change look reasonable to you?

**Comment by rionda** [comment]
Hi Pietro, yes, it looks fine to me. Thanks.

**Comment by rionda** [comment]
(Reopening just so that it gets closed when the pull request gets merged)
