### ISSUE TITLE
Notmuch Address Query is not completely displayed, half of it is cut out.

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#274]
When i set my query_command like this:

```
set query_command="notmuch address '%s'"
```
and search for "Richard Russon" with the `query` function, the result is kind of not completely displayed. Instead the right half is cut off.  What can i do to fix this?

![neomutt-notmuch-query](https://cloud.githubusercontent.com/assets/9417950/21501199/2bca2652-cc46-11e6-8140-c256b9517d61.png)

**Comment by flatcap** [comment]
Ah, try tweaking: [`$query_format`](https://www.neomutt.org/guide/reference#query-format)
It defaults to 25 chars for the address.

**Comment by toogley** [comment]
Ah, thank you. :)
