### ISSUE TITLE
group-chat-reply not preserving To:/Cc 

### ISSUE THREAD

**Issue by rafaelleru** [neomutt/neomutt#2745]
## Expected Behaviour

Preserve list in to:/Cc: when using group-chat-reply

I was trying both to use a bound key in the pager, a bound key in the index, and also using `exec group-chat-reply` to response to an email to various folks, but the list of To/Cc is not being preserved by using the function group-chat-reply

## Steps to Reproduce

1 - Receive an email containing at least one email in the Cc field
2 - Add this configuration to neomuttrc file:

```
bind    index   R           group-chat-reply
bind    pager   R           group-chat-reply
``` 
3 - Try to reply to the given mail pressing R and check if Cc is being presereved.
4 - try to  group-chat-reply`

## How often does this happen?

- Always
## NeoMutt Version

```
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.0-54-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20201114)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.14.0-unknown
GnuTLS: 3.6.15
libnotmuch: 5.3.0
storage: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet --sqlite --autocrypt

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-mZ0PwY/neomutt-20201120+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.4 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +regex +sasl
  +smime +sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version Ubuntu 20.04
* Were you using multiple copies of NeoMutt at once? NNo 
* Were you using 'screen' or 'tmux'? tmux
* Is your email local (maildir) or remote (IMAP)? maildir

**Comment by gahr** [comment]
Thanks for spotting that! I introduced the bug 1.5 years ago, which I guess gives us a good indication of how much this functionality is used 👍 

Does the devel/issue-2745 branch work for you?

**Comment by rafaelleru** [comment]
I will try to build and test that branch, I was using the one packed for ubuntu. :+1:

**Comment by rafaelleru** [comment]
Hi @gahr I just built neomutt from source using branch devel/issue-2745. I can confirm that group-chat-reply is working fine in that branch.

Thanks.

Can I know when this will be merged? I would like to use standard neomutt instead of having to build it.

Regards. :D

**Comment by gahr** [comment]
Thanks for double checking. I have merged the bug fix. We usually release on Fridays, but I can't tell which one we'll pick for the next release :)
