### ISSUE TITLE
Sidebar order loss for fake mailboxes upon changing account

### ISSUE THREAD

**Issue by atreyasha** [neomutt/neomutt#2750]
## Expected Behaviour

I set up `neomutt` using the `mutt-wizard` [framework](https://github.com/LukeSmithxyz/mutt-wizard). By default, this sets up `neomutt` such that the sidebar only shows one account at a time. It also creates keybindings to change between the various accounts. In my case, I have the keybindings `i1`, `i2` and `i3` to change between accounts 1, 2 and 3.

If I press `i1` repeatedly; the sidebar order should stay exactly the same, for example as shown below:

```
account_name
=========
Inbox
Drafts
Sent
...
```

PS: `account_name` and `=========` are fake mailboxes for decorative purposes.

## Actual Behaviour

If I press `i1` once, the sidebar order is correct and as intended:

```
account_name
=========
Inbox
Drafts
Sent
...
```

If I press `i1` once more and multiple times, the sidebar order is altered and my Inbox folder moves up to the top of the sidebar:

```
Inbox
account_name
=========
Drafts
Sent
...
```

## Steps to Reproduce

1. Install `NeoMutt 20201127` and set up the following configuration files, `mutt-wizard.muttrc` can be found [here](https://github.com/LukeSmithxyz/mutt-wizard/blob/master/share/mutt-wizard.muttrc) too.

    i. `~/.config/mutt/muttrc`:

    ```shell
    # source mutt-wizard upstream defaults
    source /usr/share/mutt-wizard/mutt-wizard.muttrc
    # set preferred text editor
    set editor=vim
    # set formats for index and the sidebar
    set index_format="%4C %Z %{%b %d} %-15.15L (%?l?%4l&%4c?) %s"
    set sidebar_format = '%D%?F? [%F]?%* %?N?%N/? %?S?%S?'
    # declare sidebar sorting method
    set sidebar_sort_method=unsorted
    # prevent scrolling outside of pager
    set pager_stop=yes
    # number of index lines to show
    set pager_index_lines = 10
    # number of context lines to show when opening email
    set pager_context = 3
    # scroll in menus
    set menu_scroll
    # show pretty tildes
    set tilde
    # set keybinding for reverse search
    bind index,pager \Cn search-opposite
    # disable upstream macro for notmuch search
    bind index \Cf noop
    # enable macro for global mbsync
    macro index O "<shell-escape>mbsync -aV<enter>" "run offlineimap to sync all mail"
    # always sign outgoing messages
    set crypt_autosign = yes
    # always encrypt if recipient's keys are present
    set crypt_opportunistic_encrypt = yes
    # PGP encrypted messages will be encrypted for yourself to keep
    set pgp_self_encrypt = yes
    # source private email files
    source accounts.muttrc
    ```

    ii. `~/.config/mutt/accounts.muttrc`:

    ```shell
    # start by sourcing account_1
    source ~/.config/mutt/accounts/account_1.muttrc
    # set up keybindings for other accounts
    macro index,pager i1 '<sync-mailbox><enter-command>source ~/.config/mutt/accounts/account_1.muttrc<enter><change-folder>!<enter>;<check-stats>'
    macro index,pager i2 '<sync-mailbox><enter-command>source ~/.config/mutt/accounts/account_2.muttrc<enter><change-folder>!<enter>;<check-stats>'
    macro index,pager i3 '<sync-mailbox><enter-command>source ~/.config/mutt/accounts/account_3.muttrc<enter><change-folder>!<enter>;<check-stats>'
    ```

    iii. Here is a sample for `~/.config/mutt/accounts/account_*.muttrc` excluding private and specific account information:

    ```shell 
    unmailboxes *
    named-mailboxes "account_name" "=account"
    named-mailboxes "===================" "=break"
    named-mailboxes "Inbox" "=INBOX"
    named-mailboxes "Drafts" "=Drafts"
    named-mailboxes "Sent" "=Sent"
    ```

    iv. The fake mailboxes `account_name` and `===================` were formatted as per information from https://github.com/neomutt/neomutt/issues/2586#issuecomment-674391923. A sample tree structure from the actual mailbox folders is shown below:

    ```
    .
    ├── account
    │   ├── cur
    │   ├── new
    │   └── tmp
    ├── break
    │   ├── cur
    │   ├── new
    │   └── tmp
    ├── Drafts
    │   ├── cur
    │   ├── new
    │   └── tmp
    ├── INBOX
    │   ├── cur
    │   ├── new
    │   └── tmp
    └── Sent
        ├── cur
        ├── new
        └── tmp
    ```

2. Launch `neomutt`, which should bring you into `account_1`. Then, press `i1` repeatedly and notice the `Inbox` folder suddenly moves up in the sidebar.

### Related issues

I looked through the issues and #2743 and #2725 seem similar and/or related.

### Workarounds attempted

 I tried the latest `master` branch with https://github.com/neomutt/neomutt/commit/63120ca5b43afd5edc3e420b1af15812566c5ab4 which fixes #2743, but this did not resolve my issue.

I found that this issue does not occur when I comment away `unmailboxes *` inside my `~/.config/mutt/accounts/account_*.muttrc`, so this could possibly be relevant. This however does not fix the issue completely for me, since commenting `unmailboxes *` results in mailboxes/accounts accumulating in the sidebar, which is not the desired behaviour in my case.

Additionally, I am quite certain this issue is not related to `mutt-wizard`; which is why I am posting here. However, I do apologize in advance if I made a mistake here.

## How often does this happen?

- Always

## When did it start to happen?

This happened and continues to happen from `NeoMutt 20200925` until `NeoMutt 20201127`.

`NeoMutt 20200821` does not have this issue, which is why I am using it now (see below).

## NeoMutt Version

```
NeoMutt 20200821
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.80-2-lts (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.14.0
GnuTLS: 3.6.14
libnotmuch: 5.2.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +regex +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version

    Arch Linux, Kernel: 5.4.80-2-lts

* Were you using multiple copies of NeoMutt at once?

    No

* Were you using 'screen' or 'tmux'?

    No

* Is your email local (maildir) or remote (IMAP)?

    Local

**Comment by gahr** [comment]
I can see this too

**Comment by gahr** [comment]
Here's the reason why this is happening:
* when we handle `unmailboxes *`, we cannot really remove the currently open mailbox altogether, because the mailbox's contents are still visible in the index, so we just mark it as hidden
* when we re-add the same mailbox later with `named-mailboxes...`, we find the old mailbox and we just make it visible again, so we don't really *create* a new mailbox
* this interferes with us keeping track of the order of *creation* that is used to sort mailboxes using `unsorted` method both in the sidebar and in the browser (you'll see the same bug if you navigate the mailboxes in the browser)

I'm looking into a possible fix.

**Comment by gahr** [comment]
@ atreyasha , can you please give the branch devel/issue-2750 a go?

**Comment by atreyasha** [comment]
Hi @gahr, thank you for the prompt response and fix. This fixes the issue for me :heart:
