### ISSUE TITLE
Attachments downloaded twice

### ISSUE THREAD

**Issue by komond** [neomutt/neomutt#2751]
I use neomutt version 20191207, which comes by default on Ubuntu 20.04.

When I hit Enter on a message header, the attachments get downloaded (the increasing percentage is shown).

Then, when I attempt to open the attachments (using the "v" keyboard shortcut), they get downloaded all over again. This is an undesirable behavior, and increases bandwidth requirement and waiting time when the attachments are large. Is there anyway to get neomutt to save its downloaded attachment somewhere?

Or alternatively, is there a way to tell neomutt to not download attachments when one hits Enter on the message header, and let it download only when we hit "v"?

Thank you.

**Comment by gahr** [comment]
Hi @komond this is a known issue, see #2004. There was an attempt to enhance the IMAP code so it would only download the needed parts, but the code was abandoned. I'll close this as a dup.
