### ISSUE TITLE
Update highlighted mailbox in sidebar when calling 'change-folder'

### ISSUE THREAD

**Issue by matthewhughes934** [neomutt/neomutt#2753]
## What would you like to be able to do?

When changing folder with `change-folder`, and with the sidebar enabled I would like the highlighted mailbox to change accordingly (as if I had navigated with e.g. `sidebar-{prev,next}`+ `sidebar-open`). This would make it easier to see in the sidebar which mailbox is currently active.

## What needs to change in NeoMutt?

Be able to notify the sidebar when the mailbox is changed so it can update accordingly.

## Have you tried any alternative methods?

I don't _think_ this would be possible with alternative methods, but I may've missed something.

**Comment by riesebie** [comment]
Did you set `color sidebar_indicator $foreground-colour $background_colour` ? See [Simple Colors](https://neomutt.org/guide/configuration.html#11-2-%C2%A0simple-colors) **Table 3.8**.

**Comment by matthewhughes934** [comment]
> Did you set `color sidebar_indicator $foreground-colour $background_colour` ? See [Simple Colors](https://neomutt.org/guide/configuration.html#11-2-%C2%A0simple-colors) **Table 3.8**. 

Thanks, I didn't know about that setting (it looks to default the same
value as, which is neat). That satisfies my requirement when navigating
between folders in a mailbox, however when I navigate to the top level
of a mailbox (the inbox for me) the cursor doesn't follow.

I might try and get some screenshots up to make it clearer.

**Comment by matthewhughes934** [comment]
Ok, got it working as I wanted using the `named-mailboxes` command. I am using neomutt with several different email addresses and each had declared `mailboxes "="` which would show as the email address in the sidebar using `"%B"` in `sidebar_format`. It was this email address that would not be highlighted as expected when navigating with `sidebar-{prev,next}`.

I tried changing this to `=INBOX` which would then be highlighted correctly, but the sidebar would then have several `INBOX` entries, so it wasn't clear at a glance which inbox belonged to which address. Now I have `named-mailboxes "<full_email>" "=INBOX"` using `"%D"` in `sidebar_format` which gives me what I want.
