### ISSUE TITLE
[NONEXISTENT] Invalid folder: sent (Failure)

### ISSUE THREAD

**Issue by hejops** [neomutt/neomutt#2758]
## Expected Behaviour

Mailboxes are loaded and mail can be browsed.

## Actual Behaviour

All inboxes can be loaded correctly, except for `sent`.

## Steps to Reproduce

```
set folder = "imaps://imap.gmail.com:993"
set spoolfile = "+INBOX"
named-mailboxes "INBOX" =INBOX
named-mailboxes "sent" =sent
mailboxes "+sent" "+INBOX" "+Bandcamp" "+Film" "+Trash"
set record = ""

Structure of $HOME/.mail:
$HOME/.mail/Bandcamp
$HOME/.mail/Film
$HOME/.mail/INBOX
$HOME/.mail/sent
$HOME/.mail/Trash
```

## How often does this happen?

- Always

## When did it start to happen?

I only just started implementing mailboxes today (2020-12-07), so I might be a little unfamiliar with how they work.

## NeoMutt Version

20201127

## Extra Info

I've tried most of the solutions offered in https://github.com/neomutt/neomutt/issues/1958, but none have worked.

* Operating System and its version
Manjaro 20.2
* Were you using multiple copies of NeoMutt at once?
No
* Were you using 'screen' or 'tmux'?
No
* Is your email local (maildir) or remote (IMAP)?
IMAP

**Comment by gahr** [comment]
In my gmail account that mailbox is called `[Gmail]/Sent Mail`, so you probably want `named-mailboxes sent '+[Gmail]/Sent Mail'`

**Comment by gahr** [comment]
Also, you don't need both `named-mailboxes` and `mailboxes`. The former replaces the latter.

**Comment by hejops** [comment]
Thanks, that solved the issue for me

**Comment by KM7KK** [comment]
I found the best solution was to eliminate "Invalid Inbox error" using Gmail is to replace it with ="All Mail".  This will eliminate the error.  Below are my mailboxes from .neomuttrc:

mailboxes ="All Mail" ="Sent Mail" =Drafts =Spam =Trash
