### ISSUE TITLE
Limit gets recomputed when returning to index

### ISSUE THREAD

**Issue by miseran** [neomutt/neomutt#2763]
## Expected Behaviour

When using an expensive limit (e.g. `~b`) and returning from the pager to the index, the index should show immediately.

## Actual Behaviour

Neomutt takes a long time to return to the index, for about as long as it took to initially apply the limit, presumably since it is recomputing it.

## How often does this happen?

- Always

## When did it start to happen?

Commits 86afffa524992e2ddda49a1f09c477cf1d4dc88f and d8d765f32030c69f433a82d3622fceab04bda14d.

## NeoMutt Version

```
NeoMutt 20201127
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.80-2-lts (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.15.0
GnuTLS: 3.6.15
libnotmuch: 5.3.0
storage: kyotocabinet, gdbm, bdb, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --bdb --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +regex +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by gahr** [comment]
That makes sense, but I fear we can't get both a fast cached limit and a correct one that takes into consideration what might have changed in the mailbox when we quit the pager. Those commits fix #2631. How do you suggest we achieve the best of both worlds?

**Comment by gahr** [comment]
Perhaps it's possible to figure whether an email was previously matched within the limit, and not do the search again.

**Comment by gahr** [comment]
Also, I think this only happens if the mailbox you're returing to in the index has new mail.

**Comment by miseran** [comment]
For me at least, it happens even when there is no new mail. Perhaps a good solution would be to only recompute when the mailbox has changed.

**Comment by igor47** [comment]
Was participating in a thread on neomutt-users about this. For me and another poster on the list, the confusing behavior is not the time it takes to re-compute the limit (which might also be pretty annoying) but mostly that messages that were previously shown in the limit screen might suddenly disappear after a new message arrives (taking the cursor position in the view with it).

I guess the problem in the original changes (https://github.com/neomutt/neomutt/pull/2634) was that it's difficult to know which messages have already been limited, and so that change re-computes the limit on all messages. I wonder if adding some state to the mail structure to keep track would solve both issues?

**Comment by gahr** [comment]
> I wonder if adding some state to the mail structure to keep track would solve both issues?

Thanks, this might be a good idea. So, this is how it could work (perhaps):

1. add a `limited` flag to emails
2. when we apply a limit, flag matching emails as both `visible` and `limited` 
3. when we rescan the mailbox to reapply the current limit, don't change emails flagged as `limited`
5. clear the `limited` flag only when when the current limit changes

Anybody want to take a chance at implementing it, perhaps by modifying slightly the algorithm over at #2634?

**Comment by igor47** [comment]
okay, i don't really know c, but i took a stab at it!

**Comment by gahr** [comment]
Thanks very much! We'll have a look shortly!
