### ISSUE TITLE
alias file email addresses not autocompleting - SOLVED

### ISSUE THREAD

**Issue by northern-arizona** [neomutt/neomutt#2765]
When I am in the To: field and type `name<tab>`, there is no autocompletion for many of the email addresses in my alias file.

For example, I made a test alias:
`alias doe-john John Doe <john.doe@gmail.com>`
In neomutt, when I start to compose an email, at the To: field, I type `doe<tab>`, there is no autocompletion. 

Other aliases autocomplete just fine. 

Here is my due diligence so far, aside from lots of google searching:

(1) I have checked my aliases.txt for the presence of spaces, brackets, etc, and all the aliases look like they are formatted correctly.

(2) My ~/.mutt/muttrc includes:
```
set alias_file=~/.mutt/aliases.txt
set sort_alias=alias
set reverse_alias
source $alias_file
```
What could be the problem?

**Comment by northern-arizona** [comment]
Found the problem.

I had both abook and aliases set up. I had used mutt-wizard by Luke Smith to set up neomutt, which also included abook integration. So, I was looking at my aliases file in a text editor and trying various aliases to autocomplete with <Tab>. But, my neomutt was configured to autocomplete from my abook file, which did not have the same list of aliases.

My bad.

**Comment by flatcap** [comment]
Glad you've fixed your problem :-)
Thanks for letting us know.
