### ISSUE TITLE
Subject separate from tree?

### ISSUE THREAD

**Issue by iKarith** [neomutt/neomutt#277]
At the moment, `$index_format` does not include a string for the tree characters--they're simply assumed to be part of the subject.  That's not always desirable if, say, you want to do something with %y or %Y ala Gmail.

Changing this, I realize, is somewhat complex because it alters established behavior.  Currently, `%s` includes the tree, if the tree would make sense to display.  You could create a new expando for the tree, but either this introduces the need to update configs if you wish the tree to be displayed, or you need to add a variable for whether or not the subject includes tree characters which only makes sense if you understand that it's there so that people need not update their configs for a new default.

The feature is desired all the same.  :)

**Comment by flatcap** [comment]
We need examples...

Here's a normal conversation (from our devel mailing list):
```
Sven      Enter PGP passphrase
Elimar    └─>
Sven        └─>
Elimar        └─>
Guillaume       ├─>
Sven            └─>Re: Enter PGP passphrase -> GPGME
Elimar            └─>
```

Inserting labels, makes a mess of the tree:
```
Sven      LABEL Enter PGP passphrase
Elimar    LABEL └─>
Sven         └─>  
Elimar         └─>  
Guillaume        ├─>
Sven             └─>Re: Enter PGP passphrase -> GPGME
Elimar    LABEL         └─>
```

Giving them a fixed width helps:
```
Sven      LABEL    Enter PGP passphrase
Elimar    LABEL    └─>
Sven                 └─>
Elimar                 └─>
Guillaume                ├─>
Sven                     └─>Re: Enter PGP passphrase -> GPGME
Elimar    LABEL            └─>
```

Ideal situation, separate "tree", "label" and "subject" expandos:
```
Sven      LABEL Enter PGP passphrase
Elimar    └─>LABEL
Sven        └─>
Elimar        └─>
Guillaume       ├─>
Sven            └─>Re: Enter PGP passphrase -> GPGME
Elimar            └─>LABEL 
```

**Comment by iKarith** [comment]
I'd say you have captured what I'm after.  I'm working on a relatively narrow screen by today's standards, barely 90 columns wide, so ideally I need to minimize the widths of everything to ensure that I can read date, sender, labels, and as much subject as I can fit.  Anything else in the index is mostly unnecessary--I mark things like unread/deleted/both with colors, for example, because it saves precious characters.

**Comment by guiniol** [comment]
I have the same issue, and I think the visual solution I would go for is the second one:
```
Sven      LABEL    Enter PGP passphrase
Elimar    LABEL    └─>
Sven                 └─>
Elimar                 └─>
Guillaume                ├─>
Sven                     └─>Re: Enter PGP passphrase -> GPGME
Elimar    LABEL            └─>
```

However, the fixed width could change per thread. As in, it changes depending on max length of tags in the thread. Not sure how tricky to get  that would be.

**Comment by nobrowser** [comment]
@iKarith : to save a little bit of horizonal space (not much), check out the new "tochars" feature.

**Comment by flatcap** [comment]
Sorry, this enhancement didn't attract someone to write some code.
This issue will now be closed, but listed on the [Closed Discussions](https://www.neomutt.org/dev/discussions) page.
