### ISSUE TITLE
Variable / hook to pipe whole message through an external program and read back, immediately before encryption

### ISSUE THREAD

**Issue by Hugo-Heagren** [neomutt/neomutt#2772]
## What would you like to be able to do?

My desired workflow:

1. Write email in asciidoc, in vim. (doesn't have to be asciidoc, but I like it)
2. Add any attachments I want to manually.
3. Press send. No manual manipulation of parts or attachments. (e.g. group-alternatives). I would be happy to rebind `y` to a macro if that made it work.
4. A multipart email is somehow generated from my asciidoc. This needs to retain all manually-added attachments, _add_ (or otherwise appropriately handle) any inline attachments and reference them properly in the html, and be able to generate a new text/plain part from my original asciidoc. (e.g. commonmark) This behaviour needs to be configurable (e.g. stylesheets for asciidoc).
5. This new multipart email is then encrypted (and otherwise processed) by neomutt as it at the moment, respecting all settings.
6. The email is actually sent

The actual new feature in neomutt is the ability to process the message _as a whole_ once it is composed, but before neomutt does any processing (in particular, any encryption which would make such processing impossible).

## What needs to change in NeoMutt?

Neomutt needs a configurable way to process messages as whole emails just before neomutt encrypts / sends them.

I think the best way to achieve this is some way of passing the whole message to an external program which handles the formatting, just before it is encrypted / sent.

It would be _possible_ to handle all / most of the conversion, parsing and attaching in neomutt, but it would be a lot to add. It would also be more flexible to just call something external. That way users can use whatever they want to format their mail however they want, including writing their own scripts.

This could be a variable like sendmail, just the path to a program which reads from stdin and writes back to stdout, or it could be a hook which behaves similarly but only when the sent message matches. (though personally I would want to use this for all my outgoing mail). 

So, I think neomutt needs a hook / variable which is the path to a program which the whole message is piped into, and then read back from before it is encrypted.

## Have you tried any alternative methods?

At the moment I use [multiMarkMaker](https://github.com/Hugo-Heagren/multi-mark-maker) which I wrote for exactly this purpose. However, as @dcpurton pointed out in #2387, an approach like this won't work with neomutt's (excellent) PGP facilities. NeoMutt's PGP settings are very powerful, and I would rather be able to use them than have to reimplement something similar again in a wrapper script which I use in sendmail.

My suggestion keeps all the mail-handling and pgp settings of neomutt, but allows for good config of the processing.

A macro like @dcpurton uses in the above mentioned issue works for some cases. However, such a macro:
- is not easily configurable or portable in the way that an external program with a config file is.
- does not handle all cases. For example, the issue I'm currently working on in mmm is for all inline media referenced in the body of html emails to attach automatically (or with confirmation) and be referenced by the html in the standard way. Having a single program which handles all this (a sort of 'email formatter'?) makes it easier to handle everything just right.

Apart from whether the macro works or not, there _is_ currently a facility to pipe a mesage out to an external program. This is fine, unless I want inline attachments in my html (implemented as usual, just attached with Content-disposition: inline). I could pipe my message out to an external program which produced the new message in the right format, but when I then attach this new message it will attach and send as a single attachment, not a series. To achieve such a series you need to add the attachments separately. At time of writing, this also _doesn't_ actually work, for the very reason that is cited in #2387 and answered in the subsequent pull request #2770.

I'm slightly incredulous that such a thing as I suggest doesn't exist already, but if it's in the docs I can't find it.

I'd be happy if there were another way which covered all the cases so I'm very open to suggestions!

**Comment by flatcap** [comment]
Hi @Hugo-Heagren 
Just a note to say that we haven't forgotten you.

@dcpurton's made a start on understanding the attachment code and
(with a little encouragement :-) [expanded the scope of his PR](https://github.com/neomutt/neomutt/pull/2774)

**Comment by Hugo-Heagren** [comment]
#3173 was merged, so thisbug is redundant now. Thanks!
