### ISSUE TITLE
Upstream changes tracking

### ISSUE THREAD

**Issue by ngortheone** [neomutt/neomutt#2781]
This issue tracks patches listed here:
https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0001-allow-to-abort-on-question-about-multipart-alternati-patch

 Patch | PR | Status
------------ | -------------|-------------
| [0001-Allow-to-abort-on-question-about-multipart-alternati.patch ](https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0001-allow-to-abort-on-question-about-multipart-alternati-patch) | -- | not needed
| [0002-Clarify-pattern-completion-uses-complete.patch ](https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0002-clarify-pattern-completion-uses-complete-patch) | https://github.com/neomutt/neomutt/pull/2778| done 
|  [0003-mutt.man-H-clarify-that-a-From_-line-in-the-draft-fi.patch ](https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0003-mutt-man-h-clarify-that-a-from_-line-in-the-draft-fi-patch) |https://github.com/neomutt/neomutt/pull/2793 | done
|  [0004-Add-view-pager-function-to-attachment-menu.patch ](https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0004-add-view-pager-function-to-attachment-menu-patch)|https://github.com/neomutt/neomutt/pull/2802 | done
|  [0005-Ensure-mutt_extract_token-never-returns-a-NULL-dest-.patch ](https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0005-ensure-mutt_extract_token-never-returns-a-null-dest-patch)| https://github.com/neomutt/neomutt/pull/2782 | done
|  [0006-Add-mutt_buffer_rewind-function.patch ](https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0006-add-mutt_buffer_rewind-function-patch)| https://github.com/neomutt/neomutt/pull/2789/ | done
|  [0007-Fix-pager-dropped-input-on-SigWinch-flag-handling.patch ](https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0007-fix-pager-dropped-input-on-sigwinch-flag-handling-patch)|https://github.com/neomutt/neomutt/pull/2794 | done
|  [0008-Add-a-mutt_error-when-copy-save-messages-fails.patch ](https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0008-add-a-mutt_error-when-copy-save-messages-fails-patch)|https://github.com/neomutt/neomutt/pull/2798 | done
|  [0009-Add-skip-headers-to-skip-past-message-headers-in-pag.patch ](https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0009-add-skip-headers-to-skip-past-message-headers-in-pag-patch)| https://github.com/neomutt/neomutt/pull/2804| done
|  [0010-Abort-IMAP-open-if-condstore-qresync-updates-fetch-f.patch](https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0010-abort-imap-open-if-condstore-qresync-updates-fetch-f-patch)|https://github.com/neomutt/neomutt/pull/2792 | done
|  [0011-Create-ssl_verify_host_override.patch](https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0011-create-ssl_verify_host_override-patch)| -- | abandoned 
|  [0012-Add-a-sanity-check-for-qresync.patch](https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0012-add-a-sanity-check-for-qresync-patch)|https://github.com/neomutt/neomutt/pull/2806| in progress
|  [0013-Fix-smtp-debug-segfault-on-invalid-SmtpAuthenticator.patch ](https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0013-fix-smtp-debug-segfault-on-invalid-smtpauthenticator-patch)| https://github.com/neomutt/neomutt/pull/2791 | done

**Comment by flatcap** [comment]
When you have a look at 11, you'll find that the config system is radically different (improved :-) from Mutt's.
Config definitions are split up by component.
The 'ssl' config lives in `conn/config.c`.

For a slightly out-of-date overview of the config, see `design*.md`:
- https://github.com/neomutt/flatcap-brain-dump/tree/master/config

For the scariest diagram imaginable, see:
- https://github.com/neomutt/gfx/blob/master/arch/README.md#config-and-inheritance

**Comment by ngortheone** [comment]
I am not going to work on patch 11:
- I think this is an evil feature 
- it adds more complexity which we do not need in the perspective of the upcoming refactoring
