### ISSUE TITLE
Error 554 when sending to non-protonmail providers

### ISSUE THREAD

**Issue by Ragnyll** [neomutt/neomutt#2784]
I am using protonmail as my email provider and using protonmail bridge to send mail from my machine. When I send mail to emails on non-protonmail email providers (like gmail) I get the following failure.
```
SMTP session failed: 554 5.0.0 Error: transaction failed, blame it on the weather: sending was canceled by user
```
Why would this fail only on non-protonmail providers?

I've tried sending to another email i set up on protonmail and it sends the message fine.

Here are my imap and smtp confs:
```
# vim: filetype=neomuttrc
set mbox_type="Maildir"
set folder="~/.mail/account"
set spoolfile=+INBOX
set record=+Sent
set postponed=+Drafts
set trash=+Trash
set mail_check=10 # seconds
set header_cache = "~/.mutt/cache/headers"
set message_cachedir = "~/.mutt/cache/bodies"
set certificate_file = "~/.mutt/certificates"

mailboxes "=INBOX" "=Sent" "=Archive" "=Trash"

# ================  SMTP  ====================
set ssl_starttls=yes
set ssl_force_tls=yes
set send_charset="us-ascii:utf-8"
set smtp_url = "smtp://account@protonmail.com:bridgepassword@127.0.0.1:1025/"
set smtp_authenticators = "gssapi:login"
set move = no
# set imap_keepalive = 900
```

**Comment by ngortheone** [comment]
Just to make sure that I understand the issue:

Sending from your Protonmail account -> any Protonmail mailbox - works fine
Sending Protonmail account -> any non-protonmail mailbox - not fine.

Is that right?

Do you have more logs from proton bridge? It seem like the issue is somewhere between protonbridge and neomutt's SMTP code

**Comment by Ragnyll** [comment]
> Sending from your Protonmail account -> any Protonmail mailbox - works fine

yes. To test this I set up a second protonmail account and was able to succesfully send to it from neomutt.

>  Sending from your Protonmail account -> any non-protonmail mailbox - not fine.

correct. I just tried sending to my gmail account and the smtp session failed as described in the issue description.

Heres some bridge logs i've scooped up. I've sanitized them of some ids, but if you think i need to get something else in there lemme know

```
{"level":"info","msg":"IMAP server listening at 127.0.0.1:1143","pkg":"imap","time":"2021-01-24T14:51:25-06:00"}
{"level":"info","msg":"API listening at 127.0.0.1:1042","pkg":"api","time":"2021-01-24T14:51:25-06:00"}
{"currentEventID":"curreventID","level":"info","msg":"New event processed","newEventID":"neweventid","newID":"newId","pkg":"store","pollCounter":1,"time":"2021-01-24T14:51:59-06:00","userID":"userid"}
{"level":"warning","msg":"No channel is listening to outgoingNoEncryption data UUID:tesmsg","pkg":"bridgeUtils/listener","time":"2021-01-24T14:52:00-06:00"}
{"error":"timed out waiting for result","level":"error","msg":"Failed to determine whether to send unencrypted, assuming no","time":"2021-01-24T14:52:15-06:00"}
``` 

What seems to me (this is a hypothesis, i could be wrong) is happening is that its sending to other protonmail accounts work because its able to send using the encryption methods protonmail expects. But when sending to gmail it's not sure what to do.

**Comment by Ragnyll** [comment]
@ngortheone  I took the plunge into the bridge code and changed a preference that got the mail to send. I'll post the solution here (for posterity) and close the issue but it's worth documenting here in case others hit the issue. Perhaps what im doing is "unsafe" but i'll check with the bridge team and post back later. 

*Solution*
This does seem to be a bridge "feature". It seems that by default the bridge does not allow you to send emails to providers that cannot be encrypted. Changing the `"report_outgoing_email_without_encryption"` preference to `false`  in the [prefs.json file](https://github.com/ProtonMail/proton-bridge#preferences) allows me to send mail to non protonmail providers. 

*Explanation*
The error is thrown by the bridge code [here](https://github.com/ProtonMail/proton-bridge/blob/25a8c1962b7f860ae7645366dce85289fc10e113/internal/smtp/user.go#L392) where it asks the bridge if it should send to an unencrypted user by checking the result of [another function](https://github.com/ProtonMail/proton-bridge/blob/25a8c1962b7f860ae7645366dce85289fc10e113/internal/smtp/user.go#L502-L521) which looks for the preference [ReportOutGoingNoEncryptionKey](https://github.com/ProtonMail/proton-bridge/blob/master/internal/smtp/backend.go#L111-L113). The function times out thus returning false and cancels the send just like the initial error stated. This behavior seems to show that by default it does not allow sending to non encrypted providers.

**Comment by ngortheone** [comment]
Thanks for reporting @Ragnyll

**Comment by rprimus** [comment]
Mon Jan 25 09:21:18 GMT 2021

@Ragnyll - have a look at setting up a [`send-hook`](https://neomutt.org/guide/configuration.html#send-hook) for email to non-protonmail users.
