### ISSUE TITLE
Being able to mark unread/read in read-only NNTP access

### ISSUE THREAD

**Issue by da-x** [neomutt/neomutt#2787]
I'm using neomutt to read mailing lists via read-only NNTP.

Is there a solution to tracking unread/read mail state? Neomutt seems to want to use the server for that and obviously that can't work. Also, it appears that it does not use its local nntp cache either, or maybe I missed something.

Thanks.

**Comment by flatcap** [comment]
Hi @da-x

NNTP works a bit differently from email, as you've spotted.
What you need to do is `<change-newsgroup>` to open the browser,
then `<subscribe>` to the newsgroups you want to follow.

Subscribing will create a `~/.newsrc` file which tracks which emails you've read.
When you leave a group, NeoMutt will ask you if you want to 'catch up' (mark them all as read).
(There's an option for that).

Here's a simple setup, where I've subscribed to three groups
(and also used the `mailboxes` command to show them in the sidebar)

```sh
set newsrc = "~/.newsrc"          # File containing list of subscribed newsgroups
set news_cache_dir = "~/.neomutt" # Directory for cached news articles

# set catchup_newsgroup = ask-yes   # Mark all articles as read when leaving a newsgroup
# set nntp_context = 1000           # Maximum number of articles to list (0 for all articles)
# set nntp_poll = 60                # Interval between checks for new posts

set news_server = "news://nntp.lore.kernel.org"

set folder = "$news_server"

mailboxes +org.kernel.vger.linux-doc
mailboxes +org.kernel.vger.netdev
mailboxes +org.kernel.vger.selinux

set sidebar_indent_string = "  "
set sidebar_short_path    = yes
set sidebar_visible       = yes
set sidebar_delim_chars   = "/."

bind index,pager \CP sidebar-prev
bind index,pager \CN sidebar-next
bind index,pager \CO sidebar-open
```

To see all the nntp config, run:
```
neomutt -D -O | grep -i -C1 nntp
```

**Comment by da-x** [comment]
I will try that! Thanks

**Comment by da-x** [comment]
I have `bind browser,index \Cy catchup`. However when hitting C-y I get a message - "Mailbox is read-only".

I also tried the minimal configuration you posted using `neomutt -F <config>`, and got the same result - I can enter the newsgroup, however when qutting neomutt my `~/.newsrc` file remains empty, and C-y doesn't work. Maybe I am missing something. The version of neomutt is the one from Fedora 32: `neomutt-20201127-1.fc32.x86_64`.

**Comment by flatcap** [comment]
> "Mailbox is read-only"

Ah, that's to do with subscription.
Subscribing tells NeoMutt to track which emails you've read.
(and which groups to watch for new posts)

Unsubscribed groups can be browsed, but they're read-only.

Go to the browser `<change-newsgroup>` + `?`
In the browser, `<tab>` will switch between the "subscribed list" and "all groups" list.
Then, `<subscribe>`  (<kbd>s</kbd>)or `<unsubscribe>` (<kbd>u</kbd>)

**Comment by da-x** [comment]
This works. As soon as I bound `change-newsgroup` to a key, I was able to use it to enter browser mode and subscribe. Now I muttrc tracks my NNTP read state. Thanks!

**Comment by flatcap** [comment]
You're welcome
