### ISSUE TITLE
neomutt on Debian Bullseye (20201120+dfsg.1-1) not retaining multipart/alternative MIME on forward 

### ISSUE THREAD

**Issue by N0NB** [neomutt/neomutt#2788]
(This message was sent to the Debian User mailing list and the one reply pointed me to the `count_alternatives` variable, but that had no effect on the forwarded MIME that I could tell.  My apologies if I missed this in the documentation.)

Last month I upgraded this desktop from Buster to Bullseye.  It was a fresh installation since something went wrong on that particular day with `apt dist-upgrade`.  Oh well.

## Expected Behaviour

Anyway, with the current neoumtt package whenever I forward an email that is MIME encoded and has an HTML attachment wrapped in a `multipart/alternative` MIME block, the HTML attachment is dropped.  The message I am forwarding is to a local hobbyist mailing list and I was notified by one of the list members a few weeks back that he could not open the HTML mail as usual and my investigation has revealed the problem began with the newest version of neomutt in Bullseye.  My `~/.mutt/muttrc` is unchanged since March 27, 2020 and this feature had worked without issue for years until the upgrade to the neomutt version in Bullseye.

Here are the attachment views from the last message I forwarded prior to the upgrade to Bullseye and the first one afterward.

This is the attachment view from my Sent folder of the forwarded message as neomutt on Buster created the forwarded message:

```
I     1 <no description>                           [multipa/mixed, 7bit, 84K]
I     2 ├─><no description>              [text/plain, quoted, us-ascii, 0.2K]
I     3 └─>The ARRL Letter for November 19, 2020  [message/rfc822, 7bit, 83K]
I     4   └─><no description>                 [multipa/alternativ, 7bit, 81K]
I     5     ├─><no description>         [text/plain, quoted, iso-8859-1, 27K]
I     6     └─><no description>               [text/html, quoted, utf-8, 53K]
I     7 signature.asc                        [applica/pgp-signat, 7bit, 0.6K]
```

This is the attachment view from my Inbox folder of the same message as received on November 19:

```
I     1 <no description>                      [multipa/alternativ, 7bit, 81K]
I     2 ├─><no description>               [text/plain, 7bit, iso-8859-1, 26K]
I     3 └─><no description>                   [text/html, quoted, utf-8, 54K]
```

## Actual Behaviour

Due to Thanksgiving in the USA, the next message was on December 3, after upgrading to the version of neomutt in Bullseye.  Here is the attachment view from my Sent folder:

```
I     1 <no description>                           [multipa/mixed, 7bit, 31K]
I     2 ├─><no description>              [text/plain, quoted, us-ascii, 0.2K]
I     3 └─>The ARRL Letter for December 3, 2020   [message/rfc822, 7bit, 30K]
I     4   └─><no description>                [text/plain, quoted, utf-8, 27K]
I     5 signature.asc                        [applica/pgp-signat, 7bit, 0.6K]
```

Notice the "multipa/alternativ" and "text/html" are omitted.

Here is the attachment view from my Inbox folder for the same December 3 message which is identical to the November 19 messagei in terms of MIME blocks:

```
I     1 <no description>                      [multipa/alternativ, 7bit, 82K]
I     2 ├─><no description>               [text/plain, 7bit, iso-8859-1, 27K]
I     3 └─><no description>                   [text/html, quoted, utf-8, 54K]
```

I cannot discern a change in the received messages MIME blocks, so the issue may reside with neomutt in my estimation.

If NeoMutt crashed, did your OS create a 'coredump' file?

No crash.

## Steps to Reproduce

Whenever I attempt to forward (`f` command) an email with a `multipart/alternative` MIME block.

I can bounce the message (`b` command) to one of my private accounts and the HTML attachment is received just fine and can be viewed in Evolution.  When I try to bounce the message to the list it must get dumped by the mail handling system along the line as it never even appears in the moderation queue (I'm one of the target mailing list (GNU Mailman) moderators), so this isn't an option.

As for MIME handling in my `muttrc` I have:

```
set mime_forward="ask-no"
# unset mime_forward_decode
```

which are unchanged for years, and, yes, I do answer the question with `y` when I want to forward with MIME attachments.

## How often does this happen?

- Always

  Yes, when attempting to forward such a message.

- Sometimes

- On a particular email
  If the email isn't private, please attach it to this issue.

  November 19, 2020 and December 3, 2020 copies attached.

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

  20180716+dfsg.1-1+deb10u1  (version on Debian Stable up until at least November 19, 2020).

- When I changed my config
  Can you narrow down **what** you changed?

  No changes to my config since March 2020 as noted above.

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20201120
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.10.0-1-amd64 (x86_64)
ncurses: ncurses 6.2.20201114 (compiled with 6.2.20201114)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.14.0-unknown
GnuTLS: 3.6.15
libnotmuch: 5.3.0
storage: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet --sqlite --autocrypt

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-Ulxxh7/neomutt-20201120+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.4 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +regex +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version

Debian GNU/Linux `bullseye/sid`

* Were you using multiple copies of NeoMutt at once?

  No.
 
* Were you using 'screen' or 'tmux'?

  Yes, `tmux`, which I have used for years with both `neomutt` and `mutt` without this issue ever cropping up.

* Is your email local (maildir) or remote (IMAP)?

  Maildir.

## Attachments
[ARRL_Letter_03_Dec_2020.txt](https://github.com/neomutt/neomutt/files/5876968/ARRL_Letter_03_Dec_2020.txt)
[ARRL_Letter_19_Nov_2020.txt](https://github.com/neomutt/neomutt/files/5876969/ARRL_Letter_19_Nov_2020.txt)

**Comment by flatcap** [comment]
@dcpurton 
Please could you have a look at this.
Thanks.

**Comment by dcpurton** [comment]
I can reproduce this. The version in buster is 20180716. If I build this (6a147a62cf39c2a12cf2e96a8a62f378164548fa) then emails do forward intact. But with the current head, this is completely broken. Only the text/plain body is forwarded as an attachment. All other email structure is lost and no attachments are forwarded.

I can do a bisect.

**Comment by N0NB** [comment]
Thanks!

I'm glad it wasn't just me!

- Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Web: https://www.n0nb.us
Projects: https://github.com/N0NB
GPG fingerprint: 82D6 4F6B 0E67 CD41 F689 BBA6 FB2C 5130 D55A 8819

**Comment by dcpurton** [comment]
4e434fe5564430ad23d00eb7886f8b5283eefd4c is the first bad commit

```
commit 4e434fe5564430ad23d00eb7886f8b5283eefd4c
Author: Richard Russon <rich@flatcap.org>
Date:   Sat Jul 4 00:13:02 2020 +0100

    send: get Config from a ConfigSubset
    
    Eliminate all Config variables from libsend.
    
    Instead, use a ConfigSubset and the `cs_subset` functions.
    
    This will enable NeoMutt to use Account- and Mailbox-specfic config.

 config/mbtable.c |   2 +-
 mutt/charset.c   |   2 +-
 send/header.c    |  39 +++--
 send/send.c      | 437 +++++++++++++++++++++++++++++++++++++------------------
 send/sendlib.c   |  99 +++++++++----
 send/sendmail.c  |  82 ++++++-----
 send/smtp.c      | 104 ++++++++-----
 7 files changed, 512 insertions(+), 253 deletions(-)
```

**Comment by flatcap** [comment]
I've found the problem: a typo I introduced when converting the config code.

Please can you give branch [[devel/forward]](https://github.com/neomutt/neomutt/tree/devel/forward) a try.

Thanks for digging @dcpurton.
Thanks for the detailed bug report, @N0NB.

**Comment by dcpurton** [comment]
@flatcap seems to work for me now.

**Comment by flatcap** [comment]
Great :-)
