### ISSUE TITLE
How is Message-ID generated and is there a way to customize it?

### ISSUE THREAD

**Issue by GarkGarcia** [neomutt/neomutt#2790]
What's the format used by NeoMutt to generate the `Message-ID` header of messages? Furthermore, is there a way to change it?

I'm concerned because I'm trying to configure NeoMutt for anonymity. I access multiple mail-boxes from NeoMutt (let's say `public@publicemailaccount.domain` and `personal@personaldomain.domain`) and I've noticed the `Message-ID` headers of the messages I send from `public@publicemailaccount.domain` expose the domain-name of `personal@personaldomain.domain`. I couldn't find any references in the documentation on how to change the `Message-ID` header or even what's the default format, please let me know if I've missed something or if there's a way around this that doesn't require changing the format of `Message-ID`.

**Comment by gahr** [comment]
The function that generates the message-id is `gen_msgid`, in send/sendlib.c. You can tweak the part that goes after the final `@` sign by setting the `hostname` variable. Example, `set hostname=foobar` generated `Message-ID: <20210128072404.qexrylk3cnggjjhc@foobar>` here.

**Comment by brunnre8** [comment]
Keep in mind that this is not a silver bullet... if you have an rdns entry people on the receiving end can query your host and get the domain name just the same (and in fact most do so automatically). You also advertise the hostname of the server in the smtp transaction (HELO)

```
Received: from smtp.github.com (out-17.smtp.github.com [192.30.252.200])
```

**Comment by flatcap** [comment]
Upstream Mutt discussed this recently, in excruciating detail.
There were worried that their Message-Id generation wasn't random enough and might leak some info.

Eventually they refactored the generator and made the format configurable.
We haven't merged their work yet, but if someone wants a fairly easy task, I can guide them.

**Comment by GarkGarcia** [comment]
> Keep in mind that this is not a silver bullet... if you have an rdns entry people on the receiving end can query your host and get the domain name just the same (and in fact most do so automatically). You also advertise the hostname of the server in the smtp transaction (HELO)
> 
> ```
> Received: from smtp.github.com (out-17.smtp.github.com [192.30.252.200])
> ```

Yep, the issue was that I forgot to reset `hostname` properly when switching accounts (I was using the same `hostname` for multiple accounts in multiple email providers).

>  There were worried that their Message-Id generation wasn't random enough and might leak some info.

I was thinking about this too. The format used by NeoMutt at the moment seems to be `"<year><month><day><hour><minutes><seconds>.<random string>@<hostname>"`, so it may expose the users local timezone. Also, currently the `Date` header exposes the system's timezone too. The problem is that timezone can be used to infer the approximate location of the sender, so it may be used in conjunction with other techniques to deanonymize the sender.

This could be mitigated by manually setting the `TZ` environment variable to a fixed timezone such as `+0000` (so that the time information in the `Message-ID` and the `Date` headers don't expose the user's personal timezone), but the time difference between the `Date` header and the first `Recieved` header could still be used to fingerprint the client. There's [an excellent report by researchers from the Tor project](https://archive.org/details/thunderbird-tor) that highlights all of this. They recommend not sending the `Date` header at all (at the time the report was written, MSA would simply fill-in missing headers before forwarding the message, I'm not sure if that's the case anymore) and use a hash of the message to generate the `Message-ID` header (instead of the system's time).

**Comment by cwfoo** [comment]
Related issue: #3060  Add "message_id_format" variable for customizing generated Message-IDs
