### ISSUE TITLE
"Could not find any mime.types file." when search with "~b"

### ISSUE THREAD

**Issue by pkyoung** [neomutt/neomutt#2803]
My apology if this is a kind of FAQ, I couldn't find from search.

Whenever I make search with `~b something`,
"Could not find any mime.types file." error message is shown  many times 
for some messages with significant time delay.

And with `limit`ed messages from `~b something` pattern,
it takes again significant time when coming back from `pager` to `index` with the same message.

How can I avoid this?

--

I copied packaged `mime.types` to $HOME/.mime.types, and the above error message has gone.
But now it still takes quite long time with message
1. `Executing command on matching messages... ###/### (xx%)` when firstly searching
2. `Sorting mailbox...` when going back from pager to index (about 15sec)

**Comment by pkyoung** [comment]
What I found so far is that I could avoid delay by
tagging first while search with `tag-pattern`, and then `limit` to tagged messages.

Alternatively, body search might not be a good idea, 
instead I could use query with notmuch.

**Comment by flatcap** [comment]
> Whenever I make search with `~b something`,
> ... significant time delay.

Yep.  Searching the body is slow.
NeoMutt caches some of the email headers, but `~b` searches will take time.

>  "Could not find any mime.types file." error message

NeoMutt is searching for the `mime.types` file, it looks in:

- `/etc/mime.types`
- `/usr/local/etc/mime.types`
- `/usr/share/neomutt/mime.types`
- `~/.mime.types`

> instead I could use query with notmuch

Yes.  The Notmuch database stores the mime types, so it can be queried extremely quickly.
In NeoMutt, running `vfolder-from-query`, then entering "mimetype:text/html" will do the trick.

You can run that function:
- Manually `:exec vfolder-from-query`
- Binding it to a key (in config): `bind index V vfolder-from-query`

**Comment by pkyoung** [comment]
Thank you for the reply, but I can't understand the point yet.
mime related error message was resolved by putting mime.types file in ~/.mime.types.
(sorry about misleading issue title)

But still it takes significant time for `Sorting mailbox...` whenever I come back to `index` from `pager`,
when `limit`ed by `~b`, i.e. in detail,

I have around 200 mails in my INBOX, and I `limit` by `~b something`.
Assuming there are 50 `limit`ed messages now,
whenever I read a message and come back to `index`, it takes quite long time to sort mailbox.

It is the same for the vfolder, queried by `vfolder-from-query mimetype:text/html`

**Comment by gahr** [comment]
I think you're describing #2763. I have gotten around to rethink how to optimize this, alas.

**Comment by pkyoung** [comment]
@gahr Yes, right. I will close this issue since it is duplicated to #2763 

BTW, thank you, all developers for the great program. 
As a one-week-user of the neomutt, this is the best and perfect mail client I've ever used.
