### ISSUE TITLE
neomutt aborts message editing when a reply-hook sets the editor

### ISSUE THREAD

**Issue by otizonaizit** [neomutt/neomutt#2805]
[mailbox.txt](https://github.com/neomutt/neomutt/files/5912589/mailbox.txt)
[muttrc.txt](https://github.com/neomutt/neomutt/files/5912590/muttrc.txt)

I observe a behaviour similar to the one in #2715, but I found a simple way to reproduce it, so I am opening a new issue, also because I am not sure the two things are indeed related.

Let's start with a very simple configuration file

```
set autoedit=yes
set edit_headers=yes
set include=yes
reply-hook . 'set editor="vi"'
reply-hook '~t ^changeme@test\.org' 'set editor="nano"'
```

The purpose of this is to set `vi` as a default editor, and switch to `nano` when replying to some special address (of course my real use case is not so stupid, but this is the minimal reproducer I could come up with). The `autoedit`, `edit_headers` and `include` variables are set because to reproduce the bug I need neomutt to start the editor right away on reply, without prompting. This configuration file is also attached to this issue as [muttrc.txt](https://github.com/neomutt/neomutt/files/5912590/muttrc.txt).

Now I want run neomutt loading the previous config file and using the mailbox attached ([mailbox.txt](https://github.com/neomutt/neomutt/files/5912589/mailbox.txt)), which looks like this:

```
From xxx@xxx.org Tue Feb  2 16:19:57 2021
Date: Tue, 2 Feb 2021 16:19:52 +0100
From: test <test@test.org>
To: changeme@test.org
Subject: test
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii; format=flowed
Content-Disposition: inline
User-Agent: NeoMutt/20201127
Status: RO
Content-Length: 5
Lines: 1



test

```

The command is:

```
neomutt -F muttrc.txt -f mailbox.txt
```

when you reply to the mail by hitting `r`, the first time everything will work: `nano` opens with the quoted text. If you now exit `nano` without saving by hitting `CTRL-X` and try to reply again with `r`, neomutt will shortly show an error on the prompt and then show `Aborted unmodified message`. Each successive try to reply by hitting `r` will end the same way: the editor `nano` is not even called, an error is flashed and then the prompt shows  `Aborted unmodified message`. When you exit neomutt the flashed error messages will be visible in the terminal. After I tried this 4 times, the errors were like this:

```
sh: 1: charset: not found
sh: 1: �Kƀ�: not found
sh: 1: {әU: not found
sh: 1: ���ЁU: not found
sh: 1: r�ЁU: not found

```
I can reproduce this consistently. The only thing that may change is that the successful reply sometimes happens the first time, sometimes the second time, but I consistently get more aborted messages than successful replies.
If you run this with debugging on the error does not happen and everything runs as normal. I am not sure that this is true in case of more complex configurations. When I originally tried to replicate the issue with my standard configuration, running with debugging would also fail, but with a different error:

```
[2021-02-02 16:02:29]<E> mutt_edit_file() Error running "@<94><F6>AE>U '/run/user/1002/mutt/POSTEO/28090/neomutt-dv4-1002-28106-16616848913190828207'"
```
where it seems that mutt is trying to run some garbage instead of the editor command that we'd expect...

I tried several neomutt versions, from current master to `20201127` to older ones, and I could consistently reproduce the error. Given that this must be relatively new (I just noticed it a couple of days ago), it may be some updated linked library?

## NeoMutt Version

This is on a Debian unstable, both with the Debian package as well as on a self-compiled version from github.

```
NeoMutt 20201127
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.10.0-2-amd64 (x86_64)
ncurses: ncurses 6.2.20201114 (compiled with 6.2.20201114)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.14.0-unknown
GnuTLS: 3.7.0
libnotmuch: 5.3.0
storage: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet --sqlite --autocrypt

Compilation CFLAGS: -g -O2 -ffile-prefix-map=/build/neomutt-ZiyeR0/neomutt-20201127+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.4 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +regex +sasl
  +smime +sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

I know this bug report is a mess, but I couldn't find a better way to report it. Still, right now I am forced to not use reply-hooks at all...

**Comment by flatcap** [comment]
Thanks for the detailed report, @otizonaizit.
The bug dates back about 6 months, but because of its subtle nature, nobody had spotted it.

Now I need to check the behaviour of **all** the hooks.
