### ISSUE TITLE
Use user's XDG config directory

### ISSUE THREAD

**Issue by guyzmo** [neomutt/neomutt#281]
As differenciation from mutt comes (new config options, [multiple config files](https://github.com/neomutt/neomutt/issues/234), [scripting language][0]) it would be a good idea to read configuration from standard XDG_HOME configuration folder, where the configuration entry point will be sourced from and be the reference for relative configuration sourcing (or script loading).

[0]:https://github.com/neomutt/neomutt/issues/153

**Comment by flatcap** [comment]
As @darnir told you on IRC, we do check `$XDG_CONFIG_HOME` and `$XDG_CONFIG_DIRS.`
As for the relative file sourcing, I'm definitely in favour of it -- it's been discussed recently in #76 
It shouldn't impact existing config files.

**Comment by guyzmo** [comment]
ok, I'm obviously closing this, but is there an issue for the `source` command?
or shall #234 be considered for it? or shall we make a new issue for the `source` command?

**Comment by mvdan** [comment]
I can't get this to work. I don't have `$XDG_CONFIG_HOME` set, but even if I set it to `$HOME/.config`, it still won't pick up `.config/mutt/muttrc`.

@flatcap if I'm missing something obvious, could you please give a pointer? Does neomutt fall back to `$HOME/.config` if the env var isn't set?

In any case, I would say this should be in the manpage, where it says:

> ~/.muttrc or ~/.mutt/muttrc

**Comment by flatcap** [comment]
Hi @mvdan, it does work, but things are changing.

The docs are here: https://www.neomutt.org/guide/configuration.html
(and they're also installed with neomutt).

the last version of neomutt read `$XDG_CONFIG_HOME/neomutt/config` but upstream mutt adopted the changes (which came as a bit of surprise to me), so the next version of neomutt (and current git) will read from dir `$XDG_CONFIG_HOME/mutt` and look for the first file in order: 
- `neomuttrc-YYYYMMDD`
- `neomuttrc`
- `muttrc-1.7.2`
- `muttrc`

As for the manpage, I haven't touched that yet.
I **really** like good documentation, but it's demoralising work -- do a good job and nobody notices.

After the next release, I'd like to see issue #282 completed -- it would change mutt to load config files relative to each other.

**Comment by mvdan** [comment]
@flatcap ah, thanks for the explanation. I did try `.config/neomutt/muttrc`, but `config` hadn't occured to me.

I'll try again once the new release is out :)

> I really like good documentation, but it's demoralising work -- do a good job and nobody notices.

Given that I looked at the manpage only, I would say I did notice. I did look at the online docs, but only during my transition from mutt half a year ago.
