### ISSUE TITLE
How to move letter to another account?

### ISSUE THREAD

**Issue by asakura42** [neomutt/neomutt#2811]
Hello. I use multiple accounts with Maildir format. How can I copy/move letter to another account without physically `cp` or `mv`? Does NeoMutt have this option?

Edit: Dunno how to name it properly: mailbox or account, so...

**Comment by gahr** [comment]
I think you are looking for `save-message`, which is bound to `s` by default?

**Comment by asakura42** [comment]
> I think you are looking for `save-message`, which is bound to `s` by default?

Yep! Thanks.
