### ISSUE TITLE
Changed password in pass and no longer working

### ISSUE THREAD

**Issue by cookEbox** [neomutt/neomutt#2814]
Didn't want to put this as a bug as I'm not sure I haven't done something stupid. I've been using Linux for 9 months and I am aware there is still a lot of things I haven't considered.

Changed my password for outlook on another device then updated pass (UNIX password manager). When I call pass in the terminal I get the result I am expecting (i.e. a correct password).

Neomutt now fails to login "No authenticators or incorrect credentials".

-------------------------------------------------------------------------------------------------------

# Mutt Configuration (part of...)
source ~/.mutt/gpg.rc    
set my_pass=\`pass *******@outlook.com\` 

## IMAP settings
set folder = "imaps://outlook.office365.com:993"
set imap_user = *******@outlook.com
set imap_pass=$my_pass
set imap_check_subscribed = yes 
set imap_list_subscribed = yes 
set timeout=5
set mail_check=90
set imap_keepalive=180
unset imap_passive
set from = *******@outlook.com
set realname ="***********"
set sort='reverse-date'
set date_format="%d/%m/%y %H:%M"
set index_format="%2C %Z %d %-15.15F %s (%-4.4c)"

## SMTP settings
set smtp_url = "smtp://*******@outlook.com@smtp-mail.outlook.com:587"
set smtp_pass=$my_pass
set ssl_starttls =yes

## Hook
account-hook $folder "set imap_user=*******@outlook.com imap_pass=$my_pass"

-------------------------------------------------------------------------------------------------------------

I have replaced \`pass *******@outlook.com\` with my password still doesn't work but when I replace $my_pass with my password (copied from the terminal from pass) neomutt loads emails fine.

Also removing set my_pass and replacing all $my_pass with '' also works I just have to type my password in every time I want to send email. 

I have also tried to reinstalling a less recent version of neomutt from pacman cache but still no luck. Any advice much appreciated!

**Comment by gahr** [comment]
Does your new password include any special characters that could confuse NeoMutt's parser? You could try with
```
set my_pass="`pass *******@outlook.com`"
```

**Comment by cookEbox** [comment]
Thanks, glad I didn't flag this as a bug and glad I prefaced this as a noob. 

Password contained other characters, changed password and it works so simple don't know how I didn't spot it. 

Thanks again
