### ISSUE TITLE
Eliminate the Sidebar's Global Config Variables

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#2819]
This is a step towards Account- and Mailbox-specific config.

The Config System is [documented here](https://neomutt.org/dev/config).

At the end, it explains how to eliminate global config variables.
These two commits are where it has been applied to the Send library.

- [4e434fe556 send: get Config from a ConfigSubset](https://github.com/neomutt/neomutt/commit/4e434fe5564430ad23d00eb7886f8b5283eefd4c)
- [47a7ab79af send: no variable](https://github.com/neomutt/neomutt/commit/47a7ab79af5b3e2755c0e75dda168664bf835135)

This diagram is a little out-of-date, but it shows the layout of the Sidebar functions.
**Key**:
- **Blue club** - Sidebar config that is global
- **Red circle** - Sidebar config that will be Account-specific (soon)

<a href="https://flatcap.org/mutt/sidebar1.svg"><img width="800" src="https://flatcap.org/mutt/sidebar1.svg"></a>

## Sidebar Entry Points

The left-most circles are the entry points into the Sidebar.
In each of these, create a `ConfigSubset` and initialise it to the global config scope: `NeoMutt->sub`.

Each of the functions marked with a club or dot needs to be passed this `sub`.

## Config Elimination

1. Replace each reference to `C_SomeName` with a call to a config helper function
2. Remove the globals in `sidebar/config.c` entirely and update `config_init_sidebar()`.

**Comment by ngortheone** [comment]
This is very exciting.
