### ISSUE TITLE
Allow the 'source' command to use relative paths

### ISSUE THREAD

**Issue by guyzmo** [neomutt/neomutt#282]
Add the source command that will source external configuration files.

## Syntax

* to source a file located **relatively** to current configuration file:

```
source path/to/file
```

* to source a file in an **absolute** location:

```
source /path/to/file
```

as referenced by issues #281, #234 and #76.

**Comment by flatcap** [comment]
... and typing `:source muttrc` will look in Mutt's current directory.

**Comment by guyzmo** [comment]
current situation:

muttrc_1:
```
source muttrc_2
```

will lookup `$PWD/muttrc_2`.
That means, relatively to the path that was setup as `PWD` when mutt was spawned.

---

Another related issue, there's no detection of cyclic sourcing, and if we do:

muttrc_test:
```
source test_muttrc
```

test_muttrc
```
source muttrc_test
```

you'll endup with:

```
% mutt -F test_muttrc
Error in test_muttrc, line 1: muttrc_test: Too many open files
Error in muttrc_test, line 1: source: errors in test_muttrc
Error in test_muttrc, line 1: source: errors in muttrc_test
Error in muttrc_test, line 1: source: errors in test_muttrc
…
source: errors in test_muttrc
Press any key to continue...
```
