### ISSUE TITLE
imap_qresync breaks imap keyword support

### ISSUE THREAD

**Issue by falsifian** [neomutt/neomutt#2823]
## Expected Behaviour

* When I type `l~YJunk`, neomutt list messages with the `Junk` IMAP keyword.
* When I select a particular message and press the key I've bound to the `modify-labels` command, neomutt shows existing IMAP keywords. (Per https://neomutt.org/feature/custom-tags)

## Actual Behaviour

* No messages are listed.
* No keywords are listed.

I also think I've observed keywords being changed in strange ways, but I'm not yet confident that's neomutt's fault.

## Steps to Reproduce

(Note: I'm running my own IMAP server. dovecot 2.3.11.3 on OpenBSD 6.8.)

* Put `set imap_qresync=yes` in `~/.neomuttrc`, and configure it to connect to my imap server. (Mostly-complete `.neomuttrc` included below.)

* Delete my neomutt caches: `rm -r ~/.cache/neomutt/*`

* Run `neomutt`.

  * The first time, it works. If I search for the `Junk` tag using `l~YJunk`, there are many results. If I select a message I know has the label and use the `modify-labels` command (bound to `), I see the keyword there.

* Exit neomutt.

* Run `neomutt` again.

  * This time, it's broken. If I search with `l~YJunk`, there are no results. If I select the message and press `, I don't see the keyword.

## How often does this happen?

The above steps reproduce it always.

In general use, I've found the keywords sometimes work and sometimes don't.

## When did it start to happen?

I'm not sure. I can't remember a time when I've been really sure IMAP keyword support was working for me.

## NeoMutt Version

```
NeoMutt 20210205
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: OpenBSD 6.9 (amd64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.16
libidn2: 2.3.0 (compiled with 2.3.0)
LibreSSL: LibreSSL 3.3.1
OpenSSL: LibreSSL 3.3.1
storage: kyotocabinet, tdb

Configure options: --mandir=/usr/local/man --with-ui=ncurses --docdir=/usr/local/share/doc/neomutt --with-lock=flock --idn=0 --idn2 --fmemopen --ssl --tdb --debug --kyotocabinet

Compilation CFLAGS: -O2 -pipe -g  -I/usr/local/include -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set -fcntl +flock +fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn -inotify 
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +regex -sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version

OpenBSD current

* Were you using multiple copies of NeoMutt at once?

No

* Were you using 'screen' or 'tmux'?

tmux

* Is your email local (maildir) or remote (IMAP)?

IMAP

Here's a copy of ~/.neomuttrc with my aliases removed for privacy:

```
##
## IMAP, and folder configuration
##

set folder=imaps://exoco.falsifian.org/
set imap_user=falsifian
set imap_pass=`cat "$HOME/w/misc-sec/exoco_mail_password"`
set imap_qresync=yes
set spoolfile=+INBOX  # Show IMAP inbox on startup.
set ssl_force_tls=yes

# Where to save draft ("postponed") and sent messages.

set postponed=+Drafts
set record=+Sent


##
## Aliases
##

# (Various lines like "alias X Y@example.com")


##
## Miscellaneous
##

set from="James Cook <falsifian@falsifian.org>"
# See [[id:1f3563db-cb6d-4976-af8d-063c43b2c12e][Try updating neomutt to
# include commit 231ac261.]] In theory the default is already no, but I see
# neomutt advertising new mail automatically, so let's try setting this
# explicitly.
#
# Actually, even this doesn't seem to work. Hrmph.
set imap_idle=no
set index_format="%[%FT%RZ] %Z %-15.15L %s"
set pager_index_lines=5
set pager_stop
set mark_old=no
set send_charset="utf-8"

bind index "\Ca" toggle-read
unbind * d  # Make it (hopefully) really hard to accidentally delete messages.

# Caching. 2020-09-15 I tried some values for header_cache_backend.
# Neomutt complained everything I tried was invalid except "kyotocabinet".
set header_cache_backend="kyotocabinet"
# Use the same directory for both caches. (The manual says this will work.)
set header_cache="~/.cache/neomutt"
set message_cachedir="~/.cache/neomutt"

# Per-recipient settings, and generic default settings. (Without the default
# send-hook, the per-recipient settings would stick, since they last until the
# end of the session.)

send-hook . 'unmy_hdr From: ; set signature="echo James|"'
send-hook '~t ^(agora-.*@agoranomic.org\|agora@listserver.tue.nl)$' 'my_hdr From: Falsifian <agora@falsifian.org> ; set signature="echo Falsifian|"'

# Header weeding and ordering
ignore *
unignore from date subject to cc list-id reply-to
hdr_order subject from date to cc list-id reply-to

# From https://neomutt.org/feature/custom-tags
bind index,pager \` modify-labels

# I tried these but got something about an SSL I/O error. So, instead, I'm relying on my OS's mail sending ability.
#set smtp_user="falsifian"
#set smtp_url="smtps://falsifian@exoco.falsifian.org:587"
```

**Comment by ngortheone** [comment]
@falsifian can this bug be reproduced on [previous release](https://github.com/neomutt/neomutt/releases/tag/20201127) of neomutt?

Trying to understand if we broke it with some recent changes

**Comment by falsifian** [comment]
@ngortheone yes, I built and installed the 20201127 version from OpenBSD ports and I observe the same thing.

```
NeoMutt 20201127
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: OpenBSD 6.9 (amd64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.16
libidn2: 2.3.0 (compiled with 2.3.0)
LibreSSL: LibreSSL 3.3.1
OpenSSL: LibreSSL 3.3.1
storage: kyotocabinet, tdb

Configure options: --mandir=/usr/local/man --with-ui=ncurses --docdir=/usr/local/share/doc/neomutt --with-lock=flock --idn=0 --idn2 --fmemopen --ssl --tdb --debug --kyotocabinet

Compilation CFLAGS: -O2 -pipe -g  -I/usr/local/include -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set -fcntl +flock +fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn -inotify 
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +regex -sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by gahr** [comment]
Does it work if you set your own custom labels? (hint: it works here, I'm currently waiting for my IMAP to tag something as Junk)

**Comment by falsifian** [comment]
I'm not sure what you mean by custom labels. I've actually been setting `Junk` manually, through neomutt (haven't gotten around to automating anything). In any case, I see the same problem with a new manually-applied label `test20210223`. (I applied the label using neomutt, then went through the steps to reproduce but with `test20210223` instead of `Junk`, and the problem was indeed reproduced.)

Could it have something to do with the IMAP server? I could try with my GMail account and see if I have the same problem. Conversely, I could give you a temporary account on my dovecot server.

**Comment by gahr** [comment]
Cool thanks, now I get it - I could reproduce this.

**Comment by gahr** [comment]
So here's the thing:

1. we don't store email tags in the headers cache, as we assume those are somewhat transient (think \Answered, \Seen, etc)
2. with qresync, we don't re-fetch tags from IMAP unless IMAP tells us the message has changed since we last saw it
3. the message hasn't changed, so we lose the tags

Possibly, we can look into caching those flags that are not defined by the IMAP standard as being "system flags" (those starting with \).

**Comment by falsifian** [comment]
Thanks for diagnosing. Let me know if I can help further.

(Does neomutt re-fetch system flags like \Seen every time, even with qresync? Otherwise I'm curious how they work, because neomutt doesn't seem to lose those like it uses my custom flags.)

**Comment by gahr** [comment]
Flag changes cause the message mod-sequence number to change, so we can discover these changes even with CONDSTORE / QRESYNC.
