### ISSUE TITLE
Pager Not Showing Message Body

### ISSUE THREAD

**Issue by ghost** [neomutt/neomutt#2826]
Neomutt is not displaying the contents of any email message. It seems like it's trying to use lynx to view them and is complaining about not having access to some file. Here's an example -

```
Date: Tue, 23 Feb 2021 13:29:37 -0500 (EST)
From: Discount Electronics <deals@discountelectronics.com>
To: jpbaiocchi@protonmail.com
Subject: Pop-Up Deal $275 HP i5 15.6" Laptops
X-Mailer: Roving Constant Contact 2012 (http://www.constantcontact.com)

[-- Autoview using lynx -assume_charset='utf-8' -display_charset=utf-8 -dump '/tmp/neomutt.html' --]
[-- Autoview stderr of lynx -assume_charset='utf-8' -display_charset=utf-8 -dump '/tmp/neomutt.html' --]

Can't Access `file://localhost/tmp/neomutt.html'
Alert!: Unable to access document.

lynx: Can't access startfile
```

Note I am using Protonmail and configured my neomutt with Mutt-Wizard (https://github.com/LukeSmithxyz/mutt-wizard)

**Comment by ngortheone** [comment]
hi @user1180 

There was somewhat related thread in the mailing list recently
https://mailman.neomutt.org/pipermail/neomutt-users-neomutt.org/2021-February/000989.html

But I think your problem might hide in `mailcap` file. 
it looks like neomutt saves file to `-dump '/tmp/neomutt.html' ` but lynx is trying to open `file://localhost/tmp/neomutt.html'`

Can you show your mailcap file?

P.S. plaintext email messages should still work fine. But again this depends on mailcap file.

**Comment by gahr** [comment]
This mailcap entry from [mw](https://github.com/LukeSmithxyz/mutt-wizard/blob/341fccfd0c3bd8341587f297518b3f82d0672112/share/mailcap#L3.) works fine here

```
text/html; lynx -assume_charset=%{charset} -display_charset=utf-8 -dump %s; nametemplate=%s.html; copiousoutput;
```

Can you please double check yours?

**Comment by gahr** [comment]
@user1180 any news?
