### ISSUE TITLE
Setting up provider-agnostic labels/inboxes

### ISSUE THREAD

**Issue by hejops** [neomutt/neomutt#2838]
There are a few ways to work with Gmail's labels and filters (e.g. `from:noreply@example.com is:important`), the easiest and most obvious one being the `mailboxes` setting. [Server-side searches](https://neomutt.org/guide/advancedusage#gmail-patterns) and [label synchronisation](https://github.com/gauteh/lieer) are also possible.

Does neomutt have capabilities for such filters/labels, or is this better done using tools like notmuch?

**Comment by gahr** [comment]
Hi @hejops , what exactly would you like to be able to do with gmail labels, in addition to searching/filtering which, as you mentioned, can already be done?

**Comment by gahr** [comment]
Oh, thanks for the clarification.

Mh I guess the closer you can get without NotMuch is to stick with IMAP, keep all your emails in a single mailbox, apply [tags](https://neomutt.org/feature/custom-tags), then `limit` using the `~Y` [pattern](https://neomutt.org/guide/advancedusage.html#patterns).

You can of course add shortcuts to those actions in form of [macros](https://neomutt.org/guide/configuration.html#macro).

I hope this helps.

**Comment by hejops** [comment]
Ah, I see. I mostly use notmuch for indexing anyway, but I can see myself using this IMAP alternative on a work machine. Thanks!
