### ISSUE TITLE
spaces in argument to change-vfolder cause the prefix to be deleted

### ISSUE THREAD

**Issue by bshanks** [neomutt/neomutt#2852]
## Expected Behaviour
```
:exec change-vfolder
notmuch://?query=(tag:inbox) or (to:postmaster and tag:new)
```

(at this point i should be shown a vfolder constructed from that query)

## Actual Behaviour

Every time the spacebar is typed, all input given so far is deleted.

When i complete giving the input and press the enter key, the only thing remaining on the input line is "tag:new)". Then an error is displayed:

"tag:new) is not a mailbox"

Interestingly, this happens if this is done manually, but the same thing also happens if it is done via a macro, eg

```macro index q "<change-vfolder>notmuch://?query=(tag:inbox) or (to:postmaster and tag:new)<enter>"```

The same behavior is observed using change-folder instead of change-vfolder.

This behavior is NOT observed when entering spaces into the To: header when composing a new message.

## Steps to Reproduce

See above.

## How often does this happen?

Always

## When did it start to happen?

Ever since I first installed neomutt a few weeks ago.

## NeoMutt Version
```
NeoMutt 20200626
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.8.0-7642-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.13.1-unknown
GnuTLS: 3.6.13
libnotmuch: 5.2.0
storage: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet --sqlite --autocrypt

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-Oya3gM/neomutt-20200626+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +regex +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

* Operating System and its version
`Linux pop-os 5.8.0-7642-generic #47~1614007149~20.10~82fb226-Ubuntu SMP Tue Feb 23 02:59:01 UTC  x86_64 x86_64 x86_64 GNU/Linux`

* Were you using multiple copies of NeoMutt at once?
No

* Were you using 'screen' or 'tmux'?
No

* Is your email local (maildir) or remote (IMAP)?
Maildir

**Comment by flatcap** [comment]
Hi @bshanks, tl;dr there's a workaround at the end :-)

This is part bug, part feature.

When you enter text, and that text is a Mailbox, NeoMutt enables a special binding:
```
bind editor <Space> mailbox-cycle
```

This means that when you press <kbd>c</kbd> to change folder,
you can then hit <kbd>\<space\></kbd> to auto-complete Mailboxes with new mail.

Not many people have Mailboxes with spaces in, so it's not often a problem.

The **workaround** is to disable this binding:
```
bind editor <space> noop
```

**Comment by bshanks** [comment]
Thanks! The workaround works. 

Also, another related question:
- In Neomutt, if Neomutt is waiting for me to provide a line of input (for example, after typing ':', or when giving the "To: " for a new message, or when doing a <change-folder> or <change-vfolder>), if the line is empty and then i type the <BackSpace> key, the prompt disappears, almost as if i had typed Control-G (but not quite, see below). In Mutt, the behavior in this case is to do nothing (the empty prompt remains). What is going on there? Is it possible to configure this behavior?
- If I do NOT use the workaround above (so <Space> is still bound to mailbox-cycle), and then have "set sidebar_new_mail_only", then when i start Neomutt, everything seems to work, and if I type "c" to change folder and then press <Space> in the editor, it cycles through mailbox with new mail (but not virtual mailboxes). However, if i type the BackSpace key when the editor line is empty, something is reloaded, and the sidebar changes (but is not empty), and now if i type "c" to change folder, then when I press <Space> in the editor, it just blanks the line (as if there were no mailbox with new mail; but there is) (this doesn't happen if i press Control-G, so i guess backspacing on an empty editor line is distinct from Control-G). What's going on there?

Thanks

**Comment by jindraj** [comment]
>In Neomutt, if Neomutt is waiting for me to provide a line of input (for example, after typing ':', or when giving the "To: " for a new message, or when doing a change-folder or change-vfolder), if the line is empty and then i type the BackSpace key, the prompt disappears, almost as if i had typed Control-G (but not quite, see below). In Mutt, the behavior in this case is to do nothing (the empty prompt remains). What is going on there? Is it possible to configure this behavior?

Yes, this is where neomutt and mutt differs in default behaviour you can configure it using [abort_backspace](https://neomutt.org/guide/reference.html#3-1-%C2%A0abort_backspace) config variable.

**Comment by bshanks** [comment]
Thanks!
