### ISSUE TITLE
why is the following setting after regex in account -hook ignored?

### ISSUE THREAD

**Issue by vcheburkin** [neomutt/neomutt#2859]
In my config I wrote:
```
mailboxes imaps://user@imap.google.com
account-hook . unset imap_user; unset imap_pass; unset smtp_pass; unset smtp_url; set record=+outbox; set trash=+Trash;
account-hook google set smtp_url=smtps://smtp.google.com; set record=imaps://user@imap.google.com/Sent; set trash=imaps://user@imap.google.com/Trash;
```
I run `neomutt -f imaps://user@google.com -Q smtp_url` and I receive:
```
No authenticators available or wrong credentials
set smtp_url = ""
```

when I wrote
```
account-hook google bug; set smtp_url=smtps://smtp.google.com; set record=imaps://user@imap.google.com/Sent; set trash=imaps://user@imap.google.com/Trash;
```
and run `neomutt -f imaps://user@google.com -Q smtp_url` and I receive:
```
No authenticators available or wrong credentials
set smtp_url = "smtps://smtp.google.com"
```

Why? In docs:
```
       account-hook regex command

              This hook is executed whenever you access a remote mailbox. Useful to  adjust  configura‐
              tion settings to different IMAP or POP servers.
```

but nothing about the meaningless word between `regex` and `command`...

**Comment by flatcap** [comment]
I think there might be more than one problem, here.
First, let's reorder your config:
```
account-hook . unset imap_user; unset imap_pass; unset smtp_pass; unset smtp_url; set record=+outbox; set trash=+Trash;
account-hook google set smtp_url=smtps://smtp.google.com; set record=imaps://user@imap.google.com/Sent; set trash
mailboxes imaps://user@imap.google.com
```

`account-hook`s set the config needed to connect to a server,
to they need to come before the `mailboxes` command.

The next problem is those semicolons (`;`) that separate commands.

When NeoMutt reads the config:
```
account-hook google set x = "apple"; set y = "banana"
```

it sees two commands:
```
account-hook google set x = "apple"
```

which it saves for later, and
```
set y = "banana"
```

which it performs immediately.
Adding "quotes" will help:

```
account-hook . "unset imap_user; unset imap_pass; unset smtp_pass; unset smtp_url; set record=+outbox; set trash=+Trash;"
account-hook google "set smtp_url=smtps://smtp.google.com; set record=imaps://user@imap.google.com/Sent; set trash
mailboxes imaps://user@imap.google.com"
```

Please can you give that a try.

**Comment by vcheburkin** [comment]
Nothing changed:
```
user@virtual:~> neomutt -f imaps://user@imap.google.com -Q smtp_url
Could not find the host "imap.google.com"
set smtp_url = ""
vc@breaker:~> cat .muttrc
mailboxes imaps://user@imap.google.com
account-hook . "unset imap_user; unset imap_pass; unset smtp_pass; unset smtp_url; set record=+outbox; set trash=+Trash;"
account-hook google "set smtp_url=smtps://user@smtp.google.com; set record=imaps://user@imap.google.com/Sent; set trash"
user@virtual:~>
```

**Comment by flatcap** [comment]
> meaningless word 'regex'

'regex' is a common abbreviation for "Regular Expression", a style of pattern matching.
https://en.wikipedia.org/wiki/Regular_expression
A common one used in hooks is dot `.` (which matches any character)
```
account-hook . commands
```

will be executed for **every** account change, because the `.` matches any character in every account name.
This is a good idea for setting default options, e.g.

```
folder-hook .    "set favourite options"
folder-hook work "set other options"
```

**Comment by flatcap** [comment]
Can you move `mailboxes` to the end of the config

**Comment by vcheburkin** [comment]
Hmm... 
Ok, how do I reset the variables if not.?
In mutt, -Q works like neomutt, but the value is there and works. 
I try to move mailboxes to end and it's work! Thank you!

**Comment by flatcap** [comment]
>  In mutt, -Q works like neomutt, but the value is there and works.

Yes.  We're working hard to improve the code (it's a BIG job).
Unfortunately, that means that the `mailboxes` command is run immediately when it's read.
(Mutt delays this until the config has been read)
NeoMutt will work like Mutt, some time in the future when we finish our work.

>  Ok, how do I reset the variables if not.?

Whenever you change folder, the hooks are run in the order they were in the config file.
You can always `unset` variables with a hook.

```sh
account-hook .                "set x y z"                 # All accounts
account-hook flatcap          "set a; unset y"            # Account 'flatcap'
account-hook (google|flatcap) "set b; unset z"            # Accounts 'flatcap' OR 'google'
```

>  I try to move mailboxes to end and it's work! Thank you!

You're welcome :-)
