### ISSUE TITLE
NeoMutt with Gmail: why is there a leak of my computer's hostname and IP address?

### ISSUE THREAD

**Issue by cwfoo** [neomutt/neomutt#2867]
I am using NeoMutt's built-in SMTP support for sending emails using my Gmail account. However, I noticed that my computer's hostname and IP address are leaked to the recipient. The recipients of my emails are able to see something like this:

```
Received: from <my-computers-hostname> ([<my-ip-address>])
        by smtp.gmail.com with ESMTPSA id xxxxx.2021.03.27.11.59.59
        for <mailing-list@example.net>
        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);
        Sat, 27 Mar 2021 12:00:00 -0700 (PDT)
``` 

Where `<my-computers-hostname>` is my computer's hostname (`/etc/hostname`), and `<my-ip-address>` is my computer's IP address.

What is the cause of this leak, and what I can I do to stop it?

I would strongly prefer to avoid setting up Postfix or Exim to deal with this problem.

**Comment by gahr** [comment]
That's how SMTP works: you connect to a SMTP server to send an email, and that server adds a Received header to the email as it passes it on to the next SMTP server, so you can trace the path an email went through. You can setup reverse DNS for your IP address so you get a "nice" entry. Here's one of my emails, where you see my server's hostname (ptrcrt.ch).
```
Received: from ptrcrt.ch (ptrcrt.ch. [2a02:2770:8:0:21a:4aff:fe7e:c6be])                                                                                             
        by smtp.gmail.com with ESMTPSA id                                                                                                                            
        cb17sm8547891edb.10.2021.03.29.02.15.52                                                                                                                      
        for <foo@bar.baz>                                                                                                                                           
        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);                                                                                                 
        Mon, 29 Mar 2021 02:15:52 -0700 (PDT) 
```

**Comment by reportaman** [comment]
@gahr @flatcap What is a foolproof workaround for this?
