### ISSUE TITLE
neomutt takes forever "Sorting mailbox..." on termux

### ISSUE THREAD

**Issue by matthiasbeyer** [neomutt/neomutt#2891]
## Expected Behaviour

Opening neomutt

## Actual Behaviour

Takes (seemingly) forever "Sorting mailbox..."
I waited for about 15 minutes on a mailbox that is about 500 messages.
No crash, though.

## Steps to Reproduce

* neomutt with notmuch
* in termux
* open neomutt without flags

## How often does this happen?

- Always

## When did it start to happen?

- When I setup neomutt on termux (never had it running before)

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20210205
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.14.180-perf-g302b184 (aarch64)
ncurses: ncurses 6.2.20200725 (compiled with 6.2.20200725)
libiconv: 1.16
OpenSSL: OpenSSL 1.1.1i  8 Dec 2020
libnotmuch: 5.3.0
storage: gdbm
compression: zstd

Configure options: --host=aarch64-linux-android --prefix=/data/data/com.termux/files/usr --with-mailpath=/data/data/com.termux/files/usr/var/mail --notmuch --disable-gpgme --disable-idn --zstd --sasl --ssl --gdbm --gss

Compilation CFLAGS:  -fstack-protector-strong -Oz -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/data/data/com.termux/files/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme +gss +hcache -homespool -idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/data/data/com.termux/files/usr/var/mail"
PKGDATADIR="/data/data/com.termux/files/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/data/data/com.termux/files/usr/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

> Operating System and its version

Android 10, termux from fdroid (up to date as of time of writing this)

> Were you using multiple copies of NeoMutt at once? 

No

> Were you using 'screen' or 'tmux'?

Reproducible with and without tmux. 

> Is your email local (maildir) or remote (IMAP)?

Local, notmuch.

---

If someone can guide me through the steps of debugging this, I'd love to help out! Maybe some termux-specific knowledge is required tho.

**Comment by flatcap** [comment]
>  I waited for about 15 minutes on a mailbox that is about 500 messages.

Argh!

> If someone can guide me through the steps of debugging this

The simplest way is to run with logging: `neomutt -d6` will write to `~/.neomuttdebug0`
That'll produces a LOT of output.  See if there are any lengthy gaps.

**Note**: Logging at that level may include personal info, so check carefully before posting any logs

**Comment by matthiasbeyer** [comment]
It seems to block on `nm_db_do_open()`:

```
[2021-04-11 12:20:48]<1> sb_window_observer() state
[2021-04-11 12:20:48]<1> sb_window_observer() state
[2021-04-11 12:20:48]<1> sb_window_observer() state
[2021-04-11 12:20:48]<1> sb_window_observer() state
[2021-04-11 12:20:48]<1> sb_window_observer() state
[2021-04-11 12:20:48]<N> sb_window_observer() focus
[2021-04-11 12:20:48]<N> sb_mailbox_observer() mailbox
[2021-04-11 12:20:48]<2> mutt_window_reflow() entering
[2021-04-11 12:20:48]<1> nm_mbox_check_stats() nm: count
[2021-04-11 12:20:48]<1> nm_db_do_open() nm: db open 'path=/data/data/com.termux/files/home/REDACTED/INBOX' [READ] (timeout 5)
```

After that there is no output anymore.

**Comment by flatcap** [comment]
Hmm... I don't know much about Notmuch.
Do the command-line notmuch commands work quickly?
e.g.
```
notmuch search something
notmuch new
```

**Comment by matthiasbeyer** [comment]
Yes they do. I might be onto something tho, and am re-creating my notmuch database right now (by removing everything and `muchsync --init`ing it from another device). Might help. I will report back.

**Comment by matthiasbeyer** [comment]
Okay, so I re-created the database and all files, but the issue still exists. Same log output even.

**Comment by flatcap** [comment]
Sorry, that's the limit of my knowledge.
Time to poke the experts.
/cc @Austin-Ray @jindraj

**Comment by jindraj** [comment]
@flatcap sure, I was just looking at this issue.

@matthiasbeyer Are you running neomutt as the same user as mbsync/notmuch?

Neomutt needs to have access to the notmuch database and to maildir and files in it. Can you please check file permissions and ownership on notmuch database?

here's what I've got when I change ownership of notmuch database. Looks similar to your's output.
```
[2021-04-11 13:33:05]<2> mutt_window_reflow() entering
[2021-04-11 13:33:05]<M> mx_mbox_open() Reading notmuch://?query=is:inbox&type=threads...
[2021-04-11 13:33:05]<1> nm_mdata_new() nm: initialize mailbox mdata 0x7fed14815200
[2021-04-11 13:33:05]<1> nm_mbox_open() nm: reading messages...[current count=0]
[2021-04-11 13:33:05]<2> nm_db_get_filename() nm: db filename '/Users/jindraj/.mail/gmail'
[2021-04-11 13:33:05]<1> nm_db_do_open() nm: db open '/Users/jindraj/.mail/gmail' [READ] (timeout 5)
```

**Comment by matthiasbeyer** [comment]
> Are you running neomutt as the same user as mbsync/notmuch?

Yes. I just open termux on my phone and `muchsync`/`neomutt` or `notmuch` right away.
I do not use `mbsync`, though.

> Can you please check file permissions and ownership on notmuch database?

Yes, everything looks as expected. All files and directories match the user reported by `whoami` and have `drwx------`/`rwx------` as permissions.

What I just noticed, though, is: the mail files are symlinks:

```
$ ls $HOME/REDACTED/INBOX/cur/REDACTED -l
lrwxrwxrwx 1 u0_a128 u0_a128 126 Apr 11 13:14 REDACTED/INBOX/cur/REDACTED -> /data/data/com.termux/files/home/REDACTED/.notmuch/muchsync/tmp/.l2s.REDACTED
```

`muchsync` did not report any errors, though. The file seems to be valid and there: I can `cat` it and see an email. I just `muchsync`ed again and it cleanly exits with `0`.

After consulting the `muchsync` manpage once more: It says it creates hardlinks for deduplication of mails. I'm not 100% positive that information is up-to-date and we should probably get in touch with the maintainer(s) of muchsync for this, ... because AFAIK, termux does not support hardlinks and it _seems_ to "work" anyways (hence exit zero).

**Comment by jindraj** [comment]
Is your `nm_default_uri` se to correct directory?

You can set it as following and it'll be read from notmuch configuration:
```set nm_default_uri      = "notmuch://`notmuch config get database.path`"```

**Comment by matthiasbeyer** [comment]
Grrrrr...

That solved the issue.

So apparently, the `nm_default_uri` was wrong in two ways: It was set to `notmuch://path=/.../home/mymaildir/MAILBOX/INBOX`. That's wrong because of the `path=` and because it should actually point to `mymaildir` here.

I don't know where this setting came from, maybe some weird copy-paste issue.

---

That being said, maybe we can work together to make this error visible somehow. Right now, it just blocks at `nm_db_do_open()`. Maybe there's a way to give feedback to the user that there is an issue and the DB won't open?

**Comment by Austin-Ray** [comment]
> That being said, maybe we can work together to make this error visible somehow. Right now, it just blocks at nm_db_do_open(). Maybe there's a way to give feedback to the user that there is an issue and the DB won't open?

There actually is a way, but looks like a refactoring error changed a small timeout to a very long timeout!
