### ISSUE TITLE
sidebar and S/MIME interfere with each other

### ISSUE THREAD

**Issue by RichiH** [neomutt/neomutt#29]
I never used sidebar before, but I gave it a try, now.

When signing email in the compose view, sidebar and signature key info are rendered upon each other.

Unsigned:
````
xxx@xxxxx.x972/1100|    Security: None
xxx@xxxxx.xxx/INBO0|
````

Signed:
````
xxx@xxxxx.x972/1100|    Security: Sign (S/MIME)
xxx@ sign as: b4f63045.0
````

**Comment by flatcap** [comment]
Hmm, I'd thought I'd got all of those.
I can't repeat your problem in my latest version of Sidebar -- I'm confident it's already fixed.
I'm planning another release very soon.  I'll leave this issue open until you can test that.

**Comment by RichiH** [comment]
> I'll leave this issue open until you can test that.

Sounds good; thanks :)

**Comment by flatcap** [comment]
Whilst rebuilding the master patchset, I found out why you see a bug and I don't.
The fix got put into my bug-fix branch.  It should have been in Sidebar as well.

**Comment by flatcap** [comment]
The new release: NeoMutt-20160530 should fix this problem.
The patch is in both NeoMutt and the separate Sidebar patch.
