### ISSUE TITLE
using nm_query_window_duration setting results in time window duration +1

### ISSUE THREAD

**Issue by lemmerk** [neomutt/neomutt#2900]
## Expected Behaviour

yesterday i decided to give the nm_query_window_* settings a shot. i like the idea but the result was somewhat unexpected.
i used the following settings:

```
set nm_query_type = "threads"
set nm_query_window_duration = 1
set nm_query_window_timebase = "month"
bind index < vfolder-window-backward
bind index > vfolder-window-forward
```

i expect to see 1 months worth of emails when viewing a notmuch tag.
when using '<' and '>' to navigate from one month to the next, i expect to see 1 month of emails.

## Actual Behaviour

i always see 2 months worth of emails.
when viewing in april i see the following emails:
beginning of march to end of april

navigate back one time window:
beginning of february to end of march

navigate back one time window:
beginning of january to end of february

hence i see every month in duplicate when using the vfolder-window-* keys to navigate into the past.

to get the results i expected using notmuch search, i need to use:
```notmuch search date:0months..``` to list all emails in 'this month'.
this is also true for the other time units such as week. unfortunately it is impossible to set ```nm_query_window_duration = 0``` as that disables the feature.

when setting ```nm_query_window_duration = 2``` i see 3 months worth of emails and navigating 'back in time' moves 2 months at a time.

perhaps there is a setting i should have set or perhaps i misunderstood something in the manual.

## Steps to Reproduce

```
set nm_query_type = "threads"
set nm_query_window_duration = 1
set nm_query_window_timebase = "month"
bind index < vfolder-window-backward
bind index > vfolder-window-forward
```

## How often does this happen?

- Always

## When did it start to happen?

- When I changed my config

```
set nm_query_type = "threads"
set nm_query_window_duration = 1
set nm_query_window_timebase = "month"
bind index < vfolder-window-backward
bind index > vfolder-window-forward
```

## NeoMutt Version

```
NeoMutt 20210205
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.11.10-gentoo-dist (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
GPGME: 1.14.0
OpenSSL: OpenSSL 1.1.1j  16 Feb 2021
libnotmuch: 5.2.0
storage: gdbm, bdb, lmdb

Configure options: --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/neomutt-20210205 --with-sysroot=/ --libdir=/usr/lib64 CCACHE=none --full-doc --enable-nls --enable-notmuch --enable-autocrypt --enable-gpgme --disable-pgp --disable-smime --enable-bdb --enable-gdbm --disable-kyotocabinet --disable-qdbm --disable-tokyocabinet --disable-idn --disable-gss --enable-lmdb --enable-sasl --with-ui=ncurses --sysconfdir=/etc/neomutt --enable-ssl --disable-gnutls --disable-testing

Compilation CFLAGS: -march=skylake -O2 -pipe -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I//usr/include -DNCURSES_WIDECHAR -I/include -I//usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss +hcache -homespool -idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl -pgp +regex +sasl 
  -smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc/neomutt"
```

## Extra Info

* Operating System and its version: gentoo up to date as of 2021-04-17
* Were you using multiple copies of NeoMutt at once?: no
* Were you using 'screen' or 'tmux'?: no
* Is your email local (maildir) or remote (IMAP)?: local

**Comment by Austin-Ray** [comment]
> perhaps there is a setting i should have set or perhaps i misunderstood something in the manual.

No, your understanding seems correct. It looks like the feature isn't able to produce the equivalent of `date:0months..`.

It takes the configuration values and produces statements in the form `date:<nm_query_window_duration><nm_query_window_timebase>..`. so `set nm_query_window_duration = 1` and `set nm_query_window_timebase = "month"` becomes `date:1months..`

I'll see if I can get it to allow `0` as a value without breaking existing user's configurations.
