### ISSUE TITLE
[question]  sidebar cannot correctly display for Asian character

### ISSUE THREAD

**Issue by Freed-Wu** [neomutt/neomutt#2907]
## Expected Behaviour

gnome-terminal

![Screenshot-20210421013444-1366x768](https://user-images.githubusercontent.com/32936898/115440307-2f4c4180-a242-11eb-8033-8108a0c76146.png)

## Actual Behaviour

qterminal
![Screenshot-20210421011459-1366x768](https://user-images.githubusercontent.com/32936898/115439251-f2337f80-a240-11eb-87e1-ec2d67b05137.png)

the divider char '|' cannot align.

## Steps to Reproduce

neomuttrc:
```
set folder = imaps://imap.qq.com:993
set imap_user = $EMAIL
set imap_pass = $EMAIL_PASS
set sendmail = msmtp

set sidebar_format = '%B%* %n%o/%S'
set sidebar_short_path
set sidebar_delim_chars = '/'
set sidebar_folder_indent
set sidebar_indent_string = '├── '
set postponed = +Drafts
set record = '+Sent Messages'  # sent
set trash = '+Deleted Message'  # trash
mailboxes +INBOX +Drafts '+Sent Messages' '+Deleted Message' +Junk \
+其他文件夹 +其他文件夹/github +其他文件夹/bugzilla +其他文件夹/wakatime \
+其他文件夹/people +其他文件夹/class +其他文件夹/vertification \
+其他文件夹/QQ邮件订阅
```

shell
```
qterminal
neomutt
```

## How often does this happen?

- Always

## When did it start to happen?

- When I try to change my terminal emulator.

## NeoMutt Version

```
20200320
```

## Extra Info

* Operating System and its version
* Were you using multiple copies of NeoMutt at once?
* Were you using 'screen' or 'tmux'?
* Is your email local (maildir) or remote (IMAP)?

Linux 5.11.7
No
use tmux, but it is not related to it.
IMAP

Perhaps it's bug of qterminal, so I use 'question' not 'bug' in title, wish can get a correct answer.

**Comment by ngortheone** [comment]
@Freed-Wu can you try another terminal emulator to see if this is terminal related?
I know for a fact that [Alacritty](https://github.com/alacritty/alacritty) shows hieroglyphs without issues. 
Try running neomutt in Alacritty report back.

Thanks.

**Comment by flatcap** [comment]
Hmm... I may have seem something similar before.

In the `gnome-terminal` settings
Profile settings, Compatability, there's a setting: "Ambiguous-width characters".
This can be "narrow" or "wide"

This determines the behaviour of the terminal when it's sent characters that it doesn't understand.

If you set this to "wide", I suspect you'll see the same problems in `gnome-terminal`.

See if there's a `qterminal` option that controls this.

**Comment by Freed-Wu** [comment]
thanks all.
it is normal in alacritty which is a good terminal although cannot support firacode.
In gnome-terminal, I found the option named ambiguous . If set it to be wide, the result will be bad.

![Screenshot-20210425034357-1366x768](https://user-images.githubusercontent.com/32936898/115971328-6ee49780-a57a-11eb-9bfd-2ed0dae12d7c.png)


So it should be the course of qterminal which cannot support ambiguous width.
Thanks all.
