### ISSUE TITLE
attachment filenames in quoted-printable

### ISSUE THREAD

**Issue by xunam** [neomutt/neomutt#2920]
## Expected Behaviour

Some mailers produce messages where attachment filenames are encoded in quoted-printable when they contain non-ASCII characters. I expect these filenames to be decoded when displaying the list of attachments and when saving them.

## Actual Behaviour

NeoMutt displays the names of such attachments as raw quoted-printable like `=?UTF-8?Q?....?=` and uses that as default filenames when saving.

## Steps to Reproduce

Not very clear, this depends on the mailer used. The last occurrences are apparently sent from Yahoo Mail, MS Outlook, Zimbra... The relevant header always looks like

```
Content-Disposition: attachment;
 filename="=?UTF-8?Q?...encoded_stuff...?="
```

## How often does this happen?

Whenever the name of an attachment is encoded as above.

## When did it start to happen?

I don't know, but it's been a long time, although I only bother reporting this behaviour now.

## NeoMutt Version

```
NeoMutt 20210205
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.111 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.36 (compiled with 1.36)
GPGME: 1.14.0-unknown
OpenSSL: OpenSSL 1.1.1k  25 Mar 2021
libnotmuch: 5.3.0
storage: lmdb
compression: zlib

Configure options: --prefix=/nix/store/sdzpvpn1z1qk3x1ykrdkdckijzfnnx37-neomutt-20210205 --enable-autocrypt --gpgme --gss --lmdb --notmuch --ssl --sasl --with-homespool=mailbox --with-mailpath= --disable-include-path-in-cflags ac_cv_path_SENDMAIL=sendmail --zlib

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls +gpgme +gss +hcache +homespool +idn +inotify
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl
  +smime +sqlite +start_color +sun_attachment +typeahead
MAILPATH="mailbox"
PKGDATADIR="/nix/store/sdzpvpn1z1qk3x1ykrdkdckijzfnnx37-neomutt-20210205/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/nix/store/sdzpvpn1z1qk3x1ykrdkdckijzfnnx37-neomutt-20210205/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version : Linux, NixOS 20.09
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? yes, tmux
* Is your email local (maildir) or remote (IMAP)? local in maildirs

**Comment by flatcap** [comment]
Try config: `set rfc2047_parameters = yes`

Docs: https://neomutt.org/guide/reference#rfc2047-parameters

**Comment by xunam** [comment]
Sorry, I didn't know about this setting !
That is exactly what I was after, thanks a lot.
