### ISSUE TITLE
config file `set my_var+=val` doesn't extend custom vars

### ISSUE THREAD

**Issue by ebblake** [neomutt/neomutt#2937]
## Expected Behaviour

Split the assignment of a long line for a my_* variable in .neomuttrc, by writing two set lines for shorter portions to be concatenated into the final value.

The documentation in 'man neomuttrc' claims:

       set { variable=value | variable+=increment | variable-=decrement } [ ... ]

              NeoMutt  knows  four  basic types of variables: boolean, number,
              string, string list and quadoption. Boolean variables can be set
              (true),  unset  (false), or toggled. Number variables can be as‐
              signed a positive integer value. Value of number  variables  can
              be  incremented "+=" and decremented "-=". String list variables
              use "+=" for appending increment to the string list and "-=" for
              removal decrement from the string list.

              String  variables  consist of any number of printable characters
              and must be enclosed in quotes if they contain spaces  or  tabs.
              You  may also use the escape sequences “\n” and “\t” for newline
              and tab, respectively. Content of a string variables can be  ex‐
              tended using "+="

## Actual Behaviour

The docs are misleading; "four basic types" is incompatible with a list of 5 elements "boolean, number, string, string list, and quadoption".
And that's a grammar error, either you want "Content of string variables" or "Content of a string variable".
But those doc problems are secondary; I'm filing this because the docs say that string variables can be extended using +=, but in practice, I encountered overwrites rather than appending.

If NeoMutt crashed, did your OS create a 'coredump' file?

no crash

## Steps to Reproduce

```
$ cat tmp
set folder = /dev/null
set my_foo = "abc"
set my_foo += "def"
$ MAIL=/dev/null neomutt -n -Ftmp -z -e 'echo $my_foo\n' -d5
Debugging at level 5 to file '/home/eblake/.neomuttdebug0'
Mailbox is empty
$ cat ~/.neomuttdebug0
[2021-05-19 16:57:06] NeoMutt-20210205 debugging at level 5
[2021-05-19 16:57:06]<M> log_file_open() Debugging at level 5 to file '/home/eblake/.neomuttdebug0'

WARNING:
    Logging at this level can reveal personal information.
    Review the log carefully before posting in bug reports.

[2021-05-19 16:57:06]<1> log_translation() Translation: NONE
[2021-05-19 16:57:06]<2> mutt_window_reflow() entering
[2021-05-19 16:57:06]<2> source_rc() Reading configuration file '/home/eblake/.mutt/tmp'
[2021-05-19 16:57:06]<2> mutt_window_reflow() entering
[2021-05-19 16:57:06]<M> parse_echo() def

[2021-05-19 16:57:07]<E> main() Mailbox is empty
[2021-05-19 16:57:07]<E> main() Mailbox is empty
[2021-05-19 16:57:07] Closing log.
# vim: syntax=neomuttlog
```
Observe that in the log, parse_echo only saw "def" instead of the intended "abcdef", because the second set of my_foo did not append even though it used +=.

Workaround - do the concatenation myself, although it requires more typing.
```
set my_foo = $my_foo"def"
```

## How often does this happen?

- Always

## When did it start to happen?

This is my first time using neomutt. so I don't know how long the problem has been around.

## NeoMutt Version

```
NeoMutt 20210205
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.11.18-300.fc34.x86_64 (x86_64)
ncurses: ncurses 6.2.20200222 (compiled with 6.2.20200222)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.15.1
GnuTLS: 3.6.15
libnotmuch: 5.3.0
PCRE2: 10.36 2020-12-04
storage: tokyocabinet, lmdb
compression: lz4, zlib, zstd

Configure options: --sysconfdir=/etc --full-doc SENDMAIL=/usr/sbin/sendmail ISPELL=/usr/bin/hunspell --autocrypt --gnutls --gpgme --gss --disable-idn --idn2 --lmdb --lua --lz4 --notmuch --pcre2 --sasl --tokyocabinet --zlib --zstd

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pcre2 +pgp +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
Fedora 34, neomutt through COPR
* Were you using multiple copies of NeoMutt at once?
Not for this bug report
* Were you using 'screen' or 'tmux'?
Not for this bug report
* Is your email local (maildir) or remote (IMAP)?
Irrelevant for this bug report.

**Comment by jindraj** [comment]
Thank you for reporting this Eric. I'm not sure If I remember correctly but the plus equals was implemented only for neomutt config option variables - leaving custom variables `my_` unsupported.

The docs should be fixed mentioning this until my_var +=/-= is implemented.

**Comment by flatcap** [comment]
Yes, @jindraj's correct, the `my_var`s are handled separately from the rest of the config.

Integrating them into our new config system won't be hard, but it's low priority,
(unless we get a volunteer :-) -- I'm happy to mentor.
