### ISSUE TITLE
IRC should be migrated from Freenode 

### ISSUE THREAD

**Issue by fredster33** [neomutt/neomutt#2939]
This is semi (?) a security issue, but not really. 

TL;DR: Freenode has been described as "under control of a malicious party". See also https://gist.github.com/joepie91/df80d8d36cd9d1bde46ba018af497409. Optimally, the IRC channel(s) should be migrated to https://libera.chat/. 

_note: this is based off of a template I'm using to mass-inform communities and projects of this change. Apologies if this sounds very depersonalized. I am not using an automated "bot" to post these, rather, this is copy-pasted._

**Comment by flatcap** [comment]
Flame bait.
No thanks.
