### ISSUE TITLE
Have the keymap functions accept arguments

### ISSUE THREAD

**Issue by guyzmo** [neomutt/neomutt#294]
Currently, the commands that can be ran within neomutt are just single token, and they take parameters in an interactive manner. It makes macro writing unnecessarily complex and tough to read. But it's also an important step towards implementing a [scripting language] to be able to expose neomutt's internals as an API.

[scripting language]:https://github.com/neomutt/neomutt/issues/153

## Current status

Many runtime functions use interactive inputs to ask for parameters to work, for example:

```
:exec pipe-message → "Pipe to command:"
:exec shell-escape → "Shell command:"
:exec limit → "Limit to messages matching:"
…
```

## Suggested change

It would be a good idea to make it possible to replace those interactive values enquiring with proper command arguments:

```
:exec pipe-message /usr/bin/less
:exec shell-escape "uname -a"
:exec limit !~D
…
```

## Nice to have

And along this change, it could be a good idea to provide the `!` modifier to function calls (like in vim) to prevent a function from asking for confirmation, or for avoiding the `Press any key to continue...`:

```
:exec shell-escape! "touch /tmp/foo"
```

## Implementation suggestions

To implement these features, there are two things that would need to be changed:

in [keymap.c:mutt_parse_exec()][mutt_parse_exec], that would mean extending the parsing of the command to split it with parameters, and eventually extract from it: 

[mutt_parse_exec]:https://github.com/neomutt/neomutt/blob/neomutt/keymap.c#L1089,L1129

- a command name,
- the list of parameters (using a `LIST*` would be great),
- whether the command shall be quiet (using the `!` modifier)

then, a bigger change would be needed, as it would mean changing all the prototypes of all the functions declared in `functions.h` to feature two new arguments, it being the list of parameters and the quiet mode.

**Comment by flatcap** [comment]
@guyzmo  Are you planning to implement this?

**Comment by guyzmo** [comment]
yes, that's a must have for the 2nd stage of lua scripting, to expand command calls to keybind commands as well. So I'd vote for keeping that in the backlog of refactoring/scripts.

**Comment by flatcap** [comment]
It's a good idea, but nobody seems to have any time to code it.
If someone volunteers to work on it we can re-open the issue.
This issue will now be closed and listed on the [closed discussions page](https://www.neomutt.org/dev/discussions)
