### ISSUE TITLE
The github aboutbox on the project page still say freenode

### ISSUE THREAD

**Issue by mscherer** [neomutt/neomutt#2944]
## Expected Behaviour

The about box on https://github.com/neomutt/neomutt should say "libera.chat"

## Actual Behaviour

The about box on https://github.com/neomutt/neomutt still list freenode, while it was changed today.

## Steps to Reproduce

Open https://github.com/neomutt/neomutt, and search for the word "freenode" 

## How often does this happen?

- Always

## When did it start to happen?

As soon as I started to search for it

**Comment by flatcap** [comment]
Thanks!  Fixed.
