### ISSUE TITLE
Dividing line not showing since commit b18b3e76 for message preview

### ISSUE THREAD

**Issue by dharrigan** [neomutt/neomutt#2949]
## Expected Behaviour

When I select a message to view, I am expecting that the dividing line shows between the index and the message, as demonstrated here:

![split-line-showing-censored](https://user-images.githubusercontent.com/427150/120338649-f644c980-c2e3-11eb-8a09-62fcaf26d1fe.png)

## Actual Behaviour

Since commit b18b3e76, this dividing line is no longer showing, i.e:

![split-line-missing-censored](https://user-images.githubusercontent.com/427150/120338746-0d83b700-c2e4-11eb-94e6-367dfbdcabf7.png)

## Steps to Reproduce

Build from latest, or go back to commit b18b3e76 to reproduce. If you go back a step further, i.e., to commit a018544aeb, all is well.

## How often does this happen?

Always

## When did it start to happen?

Since commit b18b3e76

## NeoMutt Version

Building from master, same issue.

```
NeoMutt 20210205-414-c05e80
```

<sub>Edit: Remove \`s from commit hashes so that GitHub can turn them into links (@flatcap)</sub>

**Comment by flatcap** [comment]
Sorry about that, @dharrigan.

`master` is under heavy development, atm -- I'm busy reworking how Windows manage themselves.
If I can't finish it soon, I'll try to push a temporary fix.

**Comment by dharrigan** [comment]
No worries :-) I look forward to when it's done :-)

-=david=-

**Comment by flatcap** [comment]
I've had a quick look and come up with a fix.
Please can you give branch [[devel/ibar]](https://github.com/neomutt/neomutt/tree/devel/ibar) a try.
Thanks

**Comment by dharrigan** [comment]
Tested. Works :-)
