### ISSUE TITLE
reorganize neomutt's sources tree

### ISSUE THREAD

**Issue by guyzmo** [neomutt/neomutt#295]
* reformat the source directory to have an easy to look structure:
  * `./src` for the `.c` and `.h` files
  * `./scripts` for the script helpers
  * have make put all the `.o` in `build/` (or `.obj` or anywhere but in plain sight)
* reformat the source files themselves so they're consistent with a style guide cf #224

**Comment by guyzmo** [comment]
I improved building experience by doing:

```
(pushd build; autoreconf --install .. ; ../configure --enable-debug --enable-everything; popd)
(pushd build; make && gdb ./mutt ; popd)
```

it's still generating all the autoconf 💩 within the sources, but at least the makefiles and objects are all built within `build/`.

**Comment by darnir** [comment]
Is this still under debate?

In my opinion, this is one of the first things we must look at before any other form of refactoring. As @guyzmo mentioned in #321, with a separate tracking branch, merging upstream changes is will not be that difficult. And I think this should be done *before* we make any changes to the build system. That way, whatever direction we decide for the build system, we have a stable base on which we create our build scripts.

**Comment by toogley** [comment]
Also @d-k-c expressed his love for this change on IRC.

As far as i understood @flatcap 's merging process of upstream comments, its at least only half way automatized, he does at least one part manually (at the moment). I think that's one of the biggest points preventing this issue from being implemented - that means, when we can automtize big parts of merging upstream stuff (e.g. automatically look for the correct file/dir names this issue will be much easier to realize.

**Comment by guyzmo** [comment]
moving files is a use case git is pretty good at, as long as you move files in a single commit without modifications in them, so merging is not really an issue here. The only issue is with the changes in the autoconf crap, that might conflict or become wrong when upstream will add/remove files from there. But hopefully this happens very rarely.

**Comment by guyzmo** [comment]
Basically, the first simplest step we could do would b to move everything from the root of the sources into an `src` directory, so it becomes like:

```
contrib/
doc/
src/
.*
ABOUT_NLS
BEWARE
COPYRIGHT
Changelog.*
INSTALL
LICENSE.md
NEWS
PATCHES
README.*
TODO
UPDATING*
```

we could also move or merge some of the above root-level documentation into a directory.

**Comment by darnir** [comment]
I agree with @guyzmo. Git is good at handling these changes. And if you keep a separate staging branch, `rerere` will help handle any merge conflicts and replay them automatically

`configure.ac` changes should be rare enough that we can handle them manually. And they're usually not very large changes.

**Comment by toogley** [comment]
@guyzmo Does that mean, git allows us to to apply upstreams commits **directly** to our codebase even when the path is differnt? By "directly" i mean without asking everytime to correct sth, without any complaints?

**Comment by guyzmo** [comment]
yes, upon rebase, it will replay the patch through the thread of commits before the move happened, then apply the move on that file. If you've got two branches like:

```
A:                ,->[neomutt move]--->[neomutt head]
B: --->[mutt head]-+->[new patch]
```

and you do a `git rebase B` when you're onto `A`, you'll get:

```
A': --->[mutt head]--->[new patch]--->[neomutt move']--->[neomutt head']
```

if you do a merge, the same principle will apply:

```
A:                 ,->[neomutt move]--->[neomutt head]-+->[neomutt head']
B: --->[mutt head]-+->[new patch]----------------------'
```

but without rewriting history and with a merge commit.

Conflicts would happen *only* within those files' changes, like within the autools crap.

> @darnir: configure.ac changes should be rare enough that we can handle them manually. And they're usually not very large changes.

if we move all the autotools stuff to stay the same but just moved within an `src` directory, yes, I agree. If we create subdirs to make the code modularized, or if we want some autoconf stuff to remain at the root of the sources (so you can run `autoreconf` at the root), not so much.

**Comment by darnir** [comment]
We should ideally rework the entire `autotools` setup. However, my point was that upstream will rarely make very large changes to their build system. So we can manually make the same edits on our side without too much trouble.

**Comment by toogley** [comment]
maybe it makes sense to first untangle the documentation generation script from the need to use autotools?

**Comment by guyzmo** [comment]
@darnir that's the topic of the discussion of #321 (staying with a reworked autotools being a possible way to go)
@toogley I'm opinion-less about that.

**Comment by flatcap** [comment]
For now, I think this issue is done.
We've tidied away pretty much everything we can.
