### ISSUE TITLE
Coloring is broken when zooming

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#2950]
## Expected Behaviour

After opening a message in mutt, I zoom (using the Terminal's zoom feature).

## Actual Behaviour

After zooming, custom coloring is broken (i.e., returns to default white text).

## Steps to Reproduce

I open a message that triggers the hook adding color, then zoom. Here is the relevant line in my neomuttrc file:

```
# This colors the body text green if there is at least one attachment.
message-hook '~X 1-' 'set my_bdy_colour=green'
```

## How often does this happen?

Always (when the color is triggered).

## When did it start to happen?

I just started to test NeoMutt's master branch

## NeoMutt Version

```
NeoMutt 20210205-415-d729f6
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.0-64-generic (x86_64)
ncurses: ncurses 6.1.20190803 (compiled with 6.1.20190803)
libidn: 1.33 (compiled with 1.33)
OpenSSL: OpenSSL 1.1.1c  28 May 2019
libnotmuch: 5.2.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by scottkosty** [comment]
> er, that only sets a `my_` var
> What `color` config are you using?
> 
> Do you also have 'default' `message-hook` to unset the `my_` var?

Oops, I think the following chunk is more self-contained:

    message-hook . 'set my_bdy_colour=default'
    message-hook '~X 1-' 'set my_bdy_colour=green'
    message-hook '~l=bscott!~P' 'set my_hdr_colour=blue'
    message-hook . 'color body $my_bdy_colour default .'

I'm not sure why I use a variable. I suppose I could just run the `color body` command each time.

In case it would be helpful, I could make a minimal example neomuttrc file.

**Comment by flatcap** [comment]
Hmm... that's weird.
It's like the colours have stayed in place, but the text has moved.

**Comment by flatcap** [comment]
Bisected to: bec2b3fb4 menu: redraw all windows

**Comment by flatcap** [comment]
Please can you give [[devel/zoom]](https://github.com/neomutt/neomutt/tree/devel/zoom) a try.

It's a quick hack.
I'm currently working on something that should fix the problem properly.

**Comment by scottkosty** [comment]
Thanks for the quick reply, flatcap! I tried the branch and it fixes the coloring issue, but introduces (from what I can tell) a new issue: If I zoom in a lot, I can't scroll down to the bottom. For example, I zoom in a lot and press <Enter> and it doesn't move past 53% (just an example) rather than going all the way down to the bottom.

I'm happy to wait for the long-term fix.

**Comment by flatcap** [comment]
Hmm... yeah, I see the same.
Ok, thanks.

**Comment by flatcap** [comment]
@scottkosty
Please can you give this another try; I can't repeat it any more.

Thanks

**Comment by scottkosty** [comment]
@flatcap I can't reproduce anymore either. I'll keep an eye out and report back if I see a similar issue.
