### ISSUE TITLE
Minor flashing/blinking in status bar when changing directory with Maildir

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#2953]
## Expected Behaviour

With Maildir, I do "c" to choose a directory and then select it. If the directory is large, I see "Scanning ..." when loading it.

## Actual Behaviour

 I now see "flashing" (i.e., "Scanning..." then blank then "Scanning...") in these messages.

## Steps to Reproduce

Use "c" to select a large directory (e.g., 30K - 100K messages).

## How often does this happen?

- When switching to large directories.

## When did it start to happen?

When I upgraded to NeoMutt master. I used to use the previous release, 20210205.

## NeoMutt Version

```
NeoMutt 20210205-441-8f2d1c
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.11.0-18-generic (x86_64)
ncurses: ncurses 6.2.20201114 (compiled with 6.2.20201114)
libidn: 1.33 (compiled with 1.33)
OpenSSL: OpenSSL 1.1.1j  16 Feb 2021
libnotmuch: 5.3.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version

Ubuntu 21.04.

* Is your email local (maildir) or remote (IMAP)?

Maildir. I tried but cannot reproduce on remote (IMAP).

Here is a screencast: https://www.dropbox.com/s/r78tvak5jqktsa4/flashing-in-status-bar.mkv?dl=0
I can try to bisect if that would help.
This is a minor issue. I think you're in the middle of some refactoring of status messages and refreshes. Perhaps it's best to just wait to see if this issue goes away? I don't want you to spend time on it unnecessarily.

**Comment by flatcap** [comment]
> I can try to bisect if that would help

No thanks.
I can guess what's causing this.

> Perhaps it's best to just wait to see if this issue goes away?

Yeah :-)

Thanks for the report, though.

**Comment by scottkosty** [comment]
> > Perhaps it's best to just wait to see if this issue goes away?
> 
> Yeah :-)

Sounds good! Feel free to close.

> Thanks for the report, though.

Sure, thanks for the quick reply!

**Comment by scottkosty** [comment]
Did a quick test and it works well. Thanks!
