### ISSUE TITLE
Dataloss: drafts can be clobbered when more than one

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#2955]
## Expected Behaviour

I was working with multiple drafts in Maildir and wanted to open the second draft.

## Actual Behaviour

In the postpone menu, when I open the second draft (or third), it appears as if the first draft was opened. I then "postpone" (because I thought I accidentally selected the first draft), and then it appears that the second draft is overwritten by the first draft.

## Steps to Reproduce

In Maildir (I haven't tested on IMAP), postpone two drafts. Then go to the postpone menu and try to open the second draft. It should appear as though the first draft was opened, and if you postpone it it overwrites the second one with a duplicate of the first one.

## How often does this happen?

- It appears to be "always" when working with multiple drafts and working with the second, third, etc. draft (but not the first).

## When did it start to happen?

- When I upgraded from 20210205.

A bisect lead me to 1d7794c3.

## NeoMutt Version

```
NeoMutt 20210205-442-013b1a
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.11.0-18-generic (x86_64)
ncurses: ncurses 6.2.20201114 (compiled with 6.2.20201114)
libidn: 1.33 (compiled with 1.33)
OpenSSL: OpenSSL 1.1.1j  16 Feb 2021
libnotmuch: 5.3.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

If you can't reproduce, please let me know and I'll narrow down if it is an issue with one of my configs.

* Were you using multiple copies of NeoMutt at once?

No.

* Were you using 'screen' or 'tmux'?

No.

* Is your email local (maildir) or remote (IMAP)?

I only tested with Maildir.

Thanks as always for all the work on NeoMutt!

**Comment by gahr** [comment]
I could reproduce with imap.

**Comment by gahr** [comment]
Thanks for the detailed report, I'll have a look

**Comment by flatcap** [comment]
Thanks for the detailed bug report, as always, @scottkosty :heart:
Keep 'em coming :-)

**Comment by scottkosty** [comment]
Thanks for the quick reply and patch! I just tested current master (87b38b55) and it works better, no draft is lost. However, the draft appears to be duplicated for me when I postpone it. For example, if I have two drafts, and I open one and then postpone it, I then have three drafts. Perhaps the old draft should be removed upon opening?

**Comment by gahr** [comment]
I would expect the first one to at least be marked as deleted.

**Comment by scottkosty** [comment]
It also happens for me on IMAP. Currently, if I retrieve a draft, it is never marked for delete. I need to remember to retrieve and then manually navigate to the directory and delete the message. Otherwise I see the draft is still there and then i think "oh shoot did I forget to send this?".

**Comment by gahr** [comment]
I'll open a new issue to track this, thanks.
