### ISSUE TITLE
pager_resolve_help_mapping may we hide the HelpBar

### ISSUE THREAD

**Issue by allomorphy** [neomutt/neomutt#2957]
👋 folks

I checked docs and source and could not quickly find a way to hide the Help Bar, you know the helpful
`i:Exit  -:PrevPg  <PageDown>:NextPg  v:View Attachm.  r:Reply  <Down>:Next  ?:Help`

Many of us learnt these moves some years ago 😉, so is it possible to reclaim this real estate?

Thanks for any clues
Best wishes
Eric

**Comment by gahr** [comment]
Are you looking for `:set nohelp`?

**Comment by allomorphy** [comment]
Boom and in a ✨ more than a decade of aggravation vanished  
🙏  @gahr
