### ISSUE TITLE
"Re: your mail" when replying to empty subject

### ISSUE THREAD

**Issue by protist** [neomutt/neomutt#299]
When mutt users reply to an email with an empty subject, mutt changes the subject to `Re: your mail`. IMO this is wrong for several reasons. Firstly, this subject is entirely fabricated. It implies that the first email had a subject `your mail`, which is incorrect.

Secondly, since no other mail client does this, it makes it look like the mutt user manually typed in that subject. The wording of `Re: your mail` looks obnoxious to me, and IMO feels like the user is criticising the original mail for having no subject.

Finally, the text is hard-coded, and hence not localised. Users in other languages are forced to use this string.

I found a (trivial) [patch](https://github.com/williamsmj/mutt-empty-subject-patch/blob/master/mutt-empty-subject.patch) to fix this, and use the "correct" subject of `Re: ` instead. Would it be possible to change this in neomutt?

**Comment by guyzmo** [comment]
Like whoever wrote that feature originally, I find this is not a wrong
feature. The purpose of a subject is to help skim and sort your mail
efficiently (it's also very useful to keep the content of a mail
focused, but that's another topic), when people don't put subjects
they're misbehaving.

The point of the `Re: your mail` subject is to avoid participating in
this misbehaviour, and put some placeholder as subject. You might find
it obnoxious, but I find it factual.

But most importantly, it's not aimed at being sent as is. In the compose
page, you can edit the subject or when you're editing your mail content
you can edit them as well (:set edit_headers).

> Finally, the text is hard-coded, and hence not localised. Users in
> other languages are forced to use this string.

That can be an issue, though there's currently an effort in neovim to
localise the UI, so I guess this will be fixed eventually.

> I found a (trivial) [patch](https://github.com/williamsmj/mutt-empty-subject-patch/blob/master/mutt-empty-subject.patch) 
to fix this, and use the "correct" subject of `Re: ` instead. Would it be possible to change this in neomutt?

Setting the `Re: your mail` feature as an empty subject? No way I'd
agree with that. But exposing it as a `globals.h` variable, with a
default of `your mail` (to keep existing behaviour as is), while
enabling you to have it do nothing, sure, go for it 👍.

**Comment by gahr** [comment]
+1 in having it as a run-time option - defaulting to "your mail" is fine

**Comment by protist** [comment]
Thank you both for the replies.

> when people don't put subjects they're misbehaving. The point of the `Re: your mail` subject is to avoid participating in this misbehaviour, and put some placeholder as subject. You might find it obnoxious, but I find it factual.

I think your rationale is *exactly* why I find it obnoxious. I feel like I'm emphasising their misbehaviour. I agree that it's factual, but I also think it comes across as didactic and pedantic. I'm currently looking for work, and replying to potential employers in such a way feels wrong and rude. I feel it's akin to pointing out others' grammatical mistakes. It might be factual, but it's also unnecessary and moralising.

>it's not aimed at being sent as is.

Fair point, but I'm generally used to not having to edit headers after replying. It's also worth having a "default" that makes sense, or course. (Although I accept your point that you think this *is* a reasonable default.)

> But exposing it as a `globals.h` variable, with a default of `your mail` (to keep existing behaviour as is), while enabling you to have it do nothing, sure, go for it 👍.

I could also live with it defaulting to `your mail`, and being able to change it in `.muttrc`. I guess this then "respects" the upstream default, and is consistent with previous versions' expectations. However, does the `go for it` part of your comment suggest that I should/could attempt to code this myself? Unfortunately this is beyond my capabilities. 😦

**Comment by gahr** [comment]
@flatcap I think there's not much to be discussed here, short of bikeshedding on the name of the config option..

**Comment by protist** [comment]
Thank you all. I just tested, and this works perfectly. Cheers!

**Comment by ki9us** [comment]
I couldn't find it in the docs and came here on google, so for reference, you can add this to your muttrc:

```
set empty_subject="No subject"
```

> when people don't put subjects they're misbehaving.

The reason I don't put subjects is because it doesn't get pgp-encrypted.  So some encrypted emails will have `Re: Family Photos` and some might say `Re: Illegal secrets`.  I don't want any MITM to get a plaintext summary of the email's encrypted content... so I just leave it blank for all encrypted messages.  

The default `Re: your mail` is the subject of a lot of trying-to-look-legit spam messages these days, so I prefer `Re: No subject` or even just `Re: ` 

Thanks for fixing this!  :heart:
