### ISSUE TITLE
sigfault when adding an attachment

### ISSUE THREAD

**Issue by zsbolyoczki** [neomutt/neomutt#2993]
Hi,

I have tried to attach a file to a mail.
I probably have made a mistake and it ended in segfault.

What I have done:
* wrote the email
* pressed 'a' to attach a file
* pressed '?' for file list
* pressed 'm' for file mask
* I have replaced the default ``!^\.[^.]`` pattern with ``*.png`` and pressed enter
* neomutt crashed: ``Segmentation fault (core dumped)``

OS: Linux Mint 20.1 (Ulyssa)
Neomutt details (installed from the OS repo): 
```
neomutt -v
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.0-77-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.13.1-unknown
libnotmuch: 5.2.0
hcache backends: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-WmwApX/neomutt-20191207+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

What do you need for investigation?

Thank you!

**Comment by flatcap** [comment]
Thanks for the bug report, @zsbolyoczki.

First, a workaround.
The "File Mask" is actually a **regular expression** (regex), not a **file glob** (in technical terms :-)
What you want is something like: `\.png$`
(a literal **dot**, 'png', end-of-line)

I tried, and failed, to repeat the problem with both 2021-02-05 and the current development code.
I think I know what's happening.
I think the regex code is getting upset with `*.png` (but it shouldn't crash!)

> What do you need for investigation?

The gold standard is a backtrace from a debugger, e.g. `gdb`.

How technical are you?

If you're able to, please build NeoMutt from the latest source to see if you can repeat the problem.
A short guide, here: https://neomutt.org/dev/build/build

If that still crashes, we'll need a coredump.
(I think) Linux Mint uses systemd, so try:
```
coredumpctl dump -q > coredump
gdb neomutt coredump
```

then in `gdb`, enter `bt` for a backtrace.

Thanks

**Comment by zsbolyoczki** [comment]
Hi,

Thanks for the quick response. :)
I have compiled the latest one and I confirm that the issue is gone. When I try a glob instead of a regexp I get ``Invalid preceding regular expression`` message and there is no crash.

Should I do the debug for the crashing version?

Have a nice day!


PS: it's not ``./configure --disable-docs`` but ``./configure --disable-doc`` on page https://github.com/neomutt/neomutt/issues/1804 :)

**Comment by flatcap** [comment]
> I have compiled the latest one and I confirm that the issue is gone

Great!

> I get `Invalid preceding regular expression` message and there is no crash

Yep, that's what I see too.

> Should I do the debug for the crashing version?

Thanks for the offer, but I think there's no point.
The new code works and we're getting close to a new release.

**Note**: The version you've built in under development, so if you notice anything odd, please let us know.

Thanks

---

> `--disable-doc`

Fixed :-)
