### ISSUE TITLE
fuzzy address lookup

### ISSUE THREAD

**Issue by 257** [neomutt/neomutt#3]
to get something close what i'm trying to explain here please try the following.

set query_command     = "notmuch-addrlookup --mutt %s |fzf"

you will need: [notmuch-addrlookup](https://github.com/aperezdc/notmuch-addrlookup-c) and [fzf
](https://github.com/junegunn/fzf) of course.

**Comment by flatcap** [comment]
@257 
That sounds useful, but I don't understand what you want from NeoMutt.
If `query_command` works, then there's nothing to do.

For now, NeoMutt is just going to be sets of patches for Mutt.  I'm not going to make binary releases and I'm not going to bundle other software (however good it is).

**Comment by 257** [comment]
query_command in this case doesn't quite work actually. i get a list hits but there is not way to feed that into mutt... fzf also is written in go but i would like to implement this in C and ncurses; not sure if such a thing exist in ncurses actually. any pointers?

**Comment by 257** [comment]
@flatcap: on the second read of your post i think i didn't explain myself properly. using fzf is just for illustration. i didn't mean to ask to have something external bundled and released.

**Comment by flatcap** [comment]
This issue has been closed -- Sorry, but there isn't enough interest in it at the moment.

The idea's now listed on the [Blue Sky Ideas](https://github.com/neomutt/neomutt/wiki/Blue-Sky-Ideas) page.

If, in the future, someone wants to add this feature we will re-open this issue.

**Comment by binaryplease** [comment]
> to get something close what i'm trying to explain here please try the following.
> 
> set query_command = "notmuch-addrlookup --mutt %s |fzf"
> 
> you will need: [notmuch-addrlookup](https://github.com/aperezdc/notmuch-addrlookup-c) and [fzf ](https://github.com/junegunn/fzf) of course.

Try:

```
echo && set query_command = "notmuch-addrlookup --mutt %s |fzf"
```

mutt gets rid of the first line

**Comment by thriveth** [comment]
@binaryplease  That works for me! Specifically, I have set:

`set query_command = "echo && notmuch address %s | fzf --height=10 --query=%s"`

...But it mangles Neomutt's window layout once it's finished - is there a way to force Neomutt to run `<redraw-window>` once fzf has exited?

**Comment by binaryplease** [comment]
> @binaryplease That works for me! Specifically, I have set:
> 
> `set query_command = "echo && notmuch address %s | fzf --height=10 --query=%s"`
> 
> ...But it mangles Neomutt's window layout once it's finished - is there a way to force Neomutt to run `<redraw-window>` once fzf has exited?

Did you ever find a solution?

**Comment by benmaddison** [comment]
@thriveth, @pinpox I was also trying to get the same thing to work. As you have discovered, there is no `<refresh>` or equivalent available in the "Editor" mode, so you can't get the screen to redraw (even with a separate binding) until you're back in a different mode.
I have worked around this by opening `fzf` in a new terminal by way of a wrapper, and getting the results back from it via a named pipe.
See https://github.com/benmaddison/fzf-complete-query for details if you're still looking for a solution...

**Comment by thriveth** [comment]
Thanks @benmaddison! 
I have since moved on to use My4e as my mail client so this is not relevant for me anymore, but it looks like a good solution!

**Comment by pinpox** [comment]
> My4e

Can't find that on google, do you have a link?

**Comment by thriveth** [comment]
@pinpox  Ooops, my bad, typo. Mu4e. A mail-utils client running in Emacs.  

https://www.djcbsoftware.nl/code/mu/mu4e.html
