### ISSUE TITLE
compose to sender patch

### ISSUE THREAD

**Issue by Konfekt** [neomutt/neomutt#30]
Every GUI e-mail client let's you click on the sender's email address to send her an email. 

mutt instead, has only the binding `@` that shows the email address. However, there's a patch

http://mutt-dev.mutt.narkive.com/9m8wXNq2/patch-compose-to-sender

for a compose-to-sender function in mutt.

By a quick grep in this repo's source, the `compose-sender` function is not included. How about it?

**Comment by flatcap** [comment]
Hmm... That sounds useful.
I'm busy trying to bring [harmony to the distros](https://github.com/neomutt/neomutt/issues/28) at the moment.
I shall have a look at the patch as soon as I can.

**Comment by guiniol** [comment]
@Konfekt please test the devel/compose-to-sender branch. You only need to bind `compose-sender`, and it works on a bunch of tagged messages too. Please report any bugs/improvements.

**Comment by Konfekt** [comment]
Great, thanks! There's no Makefile. Where are the build instructions?

**Comment by flatcap** [comment]
> Where are the build instructions?

It's on the todo list :-)

```
autoreconf -i
./configure [OPTIONS]
make
```

**Comment by Konfekt** [comment]
Built with empty options, compiling through with some error messages and producing the error messages
```sh
Error in /home/erpy/.muttrc, line 28: header_cache: unknown variable
Error in /home/erpy/.muttrc, line 29: message_cachedir: unknown variable
Error in /home/erpy/.muttrc, line 30: certificate_file: unknown variable
Error in /home/erpy/.muttrc, line 38: imap_idle: unknown variable
Error in /home/erpy/.muttrc, line 39: imap_keepalive: unknown variable
Error in /home/erpy/.muttrc, line 40: imap_list_subscribed: unknown variable
Error in /home/erpy/.config/mutt/accounts/work, line 7: ssl_starttls: unknown variable
Error in /home/erpy/.muttrc, line 47: source: errors in /home/erpy/.config/mutt/accounts/work
Error in /home/erpy/.muttrc, line 110: locale: unknown variable
source: errors in /home/erpy/.muttrc
Press any key to continue...
"crypt_use_gpgme" set but not built with GPGME support.
```
at start up.

Added
```
bind index              M         compose-sender
```
and reported to work fine, also with tags (t + ;M).

**Comment by flatcap** [comment]
Sorry, I should have offered you some sample options:
```
./configure --enable-pop --enable-imap --enable-smtp --enable-hcache --enable-gpgme --enable-sidebar --enable-notmuch --enable-flock --enable-debug --with-gnutls
```

Glad it works.

**Comment by flatcap** [comment]
#### This enhancement will be in the next release of NeoMutt.

**Comment by Konfekt** [comment]
This turns out to work well and be useful. How about binding it to `M` by default? That is,
```sh
bind index,pager                 M         compose-to-sender
```
