### ISSUE TITLE
header_cache unknown

### ISSUE THREAD

**Issue by bjce** [neomutt/neomutt#3004]
First of all many thanks you to the developpers and maintainers of `mutt`!

I installed neomutt on macos Bigsur 11.2.3 via MacPorts

Here is the content of the `.muttrc` file: 

```
set from="Surname Lastname <username@mail.com>
set imap_user=username@mail.com
set folder=imaps://imap.mail.com
set spoolfile=imaps://imap.mail.com/INBOX  
set record=imaps://imap.mail.com/Sent
set postponed=imaps://imap.mail.com/Drafts
set header_cache_backend=tokyocabinet
#set header_cache=~/.mutt_cache
set header_cache =~/.mutt/cache/headers
set smtp_url="smtps://USER\@mail.com:PASS@smtp.mail.com/" 
```
When running mutt, I get the following error message: 

```
Error in /Users/mymac/.muttrc, line 7: header_cache_backend: unknown variable
Error in /Users/mymac/.muttrc, line 9: header_cache: unknown variable
source: errors in /Users/mymac/.muttrc
```
I then ran `touch ~/.mutt/cache/headers` but it didn't solve the problem

I look at issue [#262](https://github.com/neomutt/neomutt/issues/262):
Has it to do with the command `--with-tokyocabinet`? I tried `mutt --with-tokyocabinet` but got `mutt: illegal option -- - NeoMutt 20200925`

What shall I do to fix the problem?

**Comment by flatcap** [comment]
Welcome to NeoMutt, @bjce.

> I installed neomutt on macos Bigsur 11.2.3 via MacPorts
> header_cache: unknown variable

That sounds like the packager didn't enable the `--with-tokyocabinet` (or similar) when they built NeoMutt.

Please can you paste the output of **`neomutt -v`**
That'll tell me about the build settings of your NeoMutt.

> What shall I do to fix the problem?

If you're patient, you could poke the builder of the package -- most people will want the header cache built-in.

If not, then you'll have to build your own NeoMutt: https://neomutt.org/dev/build/build
It's not too hard, if you're technical, but you'll probably need to install a lot of development tools and libraries.

**Comment by bjce** [comment]
Many thanks for your quick answer @flatcap 

Here is the output of `neomutt -v`:

```
NeoMutt 20200925
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 20.3.0 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libiconv: 1.16
libidn2: 2.3.1 (compiled with 2.3.1)
GPGME: 1.14.0-unknown
OpenSSL: OpenSSL 1.1.1k  25 Mar 2021

Configure options: --prefix=/opt/local --enable-doc --disable-idn --with-ncurses=/opt/local --with-nls=/opt/local --with-ssl=/opt/local --with-zlib=/opt/local --with-gpgme=/opt/local --with-idn2=/opt/local

Compilation CFLAGS: -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk -arch x86_64 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/opt/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss -hcache -homespool +idn -inotify 
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +regex -sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/opt/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/opt/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```
Where are those informations stored? in a file?

I really like to see at how things work under the hood but I'm not a professional developer. So mayb I would go for the easy option for the header cache. Therefore you seem to say that I should poke the builder of the package right? Could you tell me how I could I do that?

**Comment by flatcap** [comment]
> Compile options:
>   -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
>   +getaddrinfo -gnutls +gpgme -gss -hcache -homespool +idn -inotify 
>   -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +regex -sasl 
>   +smime -sqlite +start_color +sun_attachment +typeahead

This shows which features are built into NeoMutt.
Importantly is `-hcache` -- The header cache is disabled

It seems that the builder only enabled crypto (PGP and SMIME), but nothing else.

> Where are those informations stored?

They're in the code, so in the executable.

> poke the builder of the package right?
>Could you tell me how I could I do that?

I've found the package page: https://ports.macports.org/port/neomutt/summary
I also see that someone raised an issue about the header cache: https://trac.macports.org/ticket/61557

**Comment by rionda** [comment]
In macports, to get the header cache, you have to specify, for example, `+kyotocabinet` when installing the port. E.g., `port install +kyotocabined neomutt`. 

Look at all the options (known as "variants" in macports) with `port info neomutt`.

**Comment by flatcap** [comment]
Brilliant!  Thanks, @rionda.

**Comment by bjce** [comment]
Many thanks for your answer @rionda. I just tried it and got the following error message: 

```
 sudo port install +kyotocabinet neomutt
Can't map the URL 'file://.' to a port description file ("Could not find Portfile in /Users/username").
Please verify that the directory and portfile syntax are correct.
Error: A default port name could not be supplied.
Error: Unable to open port: Could not find Portfile in /Users/username
```
However I installed it with brew and it worked

**Comment by rionda** [comment]
The correct syntax was `port install neomutt +kyotocabinet`, sorry for the confusion.

**Comment by bjce** [comment]
@rionda Many thanks!! it worked!!!
