### ISSUE TITLE
inbox-first sorting does not work when namespace separator is '/'

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#301]
When using mutt to access IMAP servers using '/' as a namespace separator, the functionality to sort INBOX before any other folders does not work correctly. Mailboxes view can for example display something like this

```
1       imaps://imap.gmail.com:993/[Gmail]/Trash                                                                       
2       imaps://imap.gmail.com:993/INBOX   
```

This is due to the fact that the inbox-first functionality is only enabled if the two folders to be compared - "[Gmail]/Trash" and "INBOX" in this case - happen to be under the same path, where "same path" means "the same sequence of characters after the last '/' character.

**Comment by darnir** [comment]
Which option enables the INBOX-first sorting? I can't find any reference to it in my muttrc or the docs

**Comment by darnir** [comment]
The fix for this bug broke my mailbox sorting.
Image for reference: http://imgur.com/a/pIcnf

**Comment by gahr** [comment]
Thanks! I fear the sorting isn't stable when mailboxes belong to different paths.. can you please post the full path of your mailboxes?
I'll get this sorted (...) tomorrow.
