### ISSUE TITLE
Neomutt aborts with pattern/exec.c:116: msg_search: Assertion `msg' failed.

### ISSUE THREAD

**Issue by hsanson** [neomutt/neomutt#3011]
## Expected Behaviour

Select messages using a header pattern:

1. Press T for tag-pattern
2. Use pattern `~h Gitlab` to tag all messages that come from Gitlab
3. All messages that match the pattern are tagged.

## Actual Behaviour

Neomutt aborts and closes with the message:

> pattern/exec.c:116: msg_search: Assertion `msg' failed.

## Steps to Reproduce

1. Happens with virtual mailboxes (notmuch)
2. I have background script that uses mbsync to sync local mailboxes with IMAP mailboxes.
3. Happens after the script has triggered and moved some messages from the current virtualbox, that is, the virtualbox still lists messages that have been removed or moved to a different mailbox on disk.
4. Restarting or refreshing the virtual mailbox with $ seems to avoid the issue.

## How often does this happen?

- Sometimes

## When did it start to happen?

- When I upgraded
  Not sure since when it started but currently using latest master commit e300cdaae56583795a17f85cde364b7d2a07e4dc 

## NeoMutt Version

```
NeoMutt 20210205-666-e300cd
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.8.0-59-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.13.1-unknown
OpenSSL: OpenSSL 1.1.1f  31 Mar 2020
libnotmuch: 5.2.0
storage: lmdb
compression: zstd

Configure options: --prefix=/usr --notmuch --lmdb --ssl --sasl --gpgme --zstd --fmemopen

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

コンパイル時オプション:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock +fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss +hcache -homespool +idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

## Extra Info

* Operating System and its version
   KDE Neon with latest updates/upgrades.
* Were you using multiple copies of NeoMutt at once?
  No
* Were you using 'screen' or 'tmux'?
  Tmux
* Is your email local (maildir) or remote (IMAP)?
  Local maildir synced with mbsync and custom script.

**Comment by gahr** [comment]
in pattern/exec.c we assume that mx_msg_open is successful. I'll fix that part.
