### ISSUE TITLE
Duplicate message sent after composing email.

### ISSUE THREAD

**Issue by paniash** [neomutt/neomutt#3015]
This has been seen while using gmail. I am yet to test it on other email providers.

## Expected Behaviour

Compose and send the email. The recipient receives exactly one copy of said email.

## Actual Behaviour

Sending the email to the recipient leads to a duplicate of the message (with the same message-id) being sent after a considerable amount of delay (generally ranges from 10-30 mins).

If NeoMutt crashed, did your OS create a 'coredump' file?

## Steps to Reproduce

1. Compose email and send to `john.doe@gmail.com`.
2. Wait for about 30 mins.
3. Look at sent email and one sees another email (although empty) with the same message-id.

## How often does this happen?

Always. Although this doesn't happen if I send an email to my own email address.

## When did it start to happen?

I've always noticed it since I started using neomutt (about a year ago).

## NeoMutt Version

```
NeoMutt 20210205
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.10.52-1-lts (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.1 (compiled with 2.3.0)
GPGME: 1.15.1
GnuTLS: 3.7.0
libnotmuch: 5.3.0
storage: kyotocabinet, gdbm, bdb, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --bdb --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +regex +sasl
  +smime +sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Artix linux
* Were you using multiple copies of NeoMutt at once? No.
* Were you using 'screen' or 'tmux'? No.
* Is your email local (maildir) or remote (IMAP)? maildir.

## Screenshot
![Imagepipe_0](https://user-images.githubusercontent.com/59497618/127540865-8c3e7ce6-619e-4275-8614-1cd0757b5b37.jpg)

**Comment by gahr** [comment]
Wild guess: this has more to do with how NeoMutt saves the outgoing email to your maildir and how you re-sync maildir from IMAP (mbsync?), leading to duplicates, than with NeoMutt actually *sending* the email twice.

**Comment by PhrantiK** [comment]
@gahr nice one - I had the same problem and your message gave me a nudge in the right direction to fix it. 

I removed this line ````set record = "+sent"```` from my account setup and it's not sending duplicates out now. 

I guess with gmail automatically putting sent messages into the sent mailbox that line is putting a copy into the maildir which is sent when synced with mbsync.

**Comment by gahr** [comment]
Yep, that's what's happening!

**Comment by paniash** [comment]
Awesome! Thanks for the fix @PhrantiK. :-)
