### ISSUE TITLE
Neomutt slow and trying to parse an incorrect file

### ISSUE THREAD

**Issue by blakesweeney** [neomutt/neomutt#3017]
## Expected Behaviour

Neomutt should open and be responsive in a reasonable amount of time.

## Actual Behaviour

When opening neomutt it hangs for a long time (~1 minute). When I tried to debug with `-d6` I see that it is trying to load files that do not exist and takes a long time to open my notmuch database. A section of the log:

```
[2021-08-04 20:54:24]<1> nm_mbox_open() nm: reading messages...[current count=0]
[2021-08-04 20:54:24]<2> nm_db_get_filename() nm: db filename '/Users/blake/.local/share/notmuch/database'
[2021-08-04 20:54:24]<1> nm_db_do_open() nm: db open '/Users/blake/.local/share/notmuch/database' [READ] (timeout 5)
[2021-08-04 20:54:29]<2> get_query_string() nm: true
[2021-08-04 20:54:29]<2> windowed_query_from_query() nm: query:new
[2021-08-04 20:54:29]<2> query_window_reset() entering
[2021-08-04 20:54:29]<2> get_query_string() nm: query (windowed) 'query:new'
[2021-08-04 20:54:29]<2> get_query() nm: query successfully initialized (query:new)
[2021-08-04 20:54:29]<2> append_message() nm: appending message, i=0, id=35c557f5-0626-43a4-b2d3-b7e3f90c3145@dfw1s10mta453.xt.local, path=/Users/blake/.local/share/notmuch/database/<addr>/[Gmail].All Mail/cur/1628016054.53070_4.tea-rex,U=171935:2,
[2021-08-04 20:54:29]<1> append_message() nm: failed to parse message: /Users/blake/.local/share/notmuch/database/<addr>/[Gmail].All Mail/cur/1628016054.53070_4.tea-rex,U=171935:2,
```
I think there are two issues, first it takes a long time to open the database and secondly the file it is trying to load has the wrong path. I suspect neomutt is getting confused because my `folder` (`~/Email`) and `nm_default_url` (`~/.local/share/notmuch/database`) point to different locations and it is choosing to look for email under my `nm_default_url` path instead of `folder`. So when it should actually be loading from `~/Email/` instead of from `~/.local/share/notmuch/database`. 

Some snippets of my configs that may help.

### Notmuch config

```
database.backup_dir=.local/share/notmuch/backups
database.mail_root=/Users/blake/Email
database.path=/Users/blake/.local/share/notmuch/database
```

### Neomutt config

```
set nm_default_url = "notmuch:///Users/blake/.local/share/notmuch/database"
set folder = "~/Email"
```

## Steps to Reproduce

I think using neomutt with notmuch and having `folder` and `nm_default_url` separate will cause the issue.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded to: `20210205` and notmuch version `0.32.2` and moved my notmuch database away from where I keep emails.

## NeoMutt Version

```
NeoMutt 20210205
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 18.7.0 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libiconv: 1.11
libidn: 1.37 (compiled with 1.37)
GPGME: 1.16.0-unknown
OpenSSL: OpenSSL 1.1.1k  25 Mar 2021
libnotmuch: 5.3.0
storage: lmdb
compression: zlib

Configure options: --prefix=/nix/store/hjaa3153mhvy0b5ygzif384asq2q5shs-neomutt-20210205 --enable-autocrypt --gpgme --gss --lmdb --notmuch --ssl --sasl --with-homespool=mailbox --with-mailpath= --disable-include-path-in-cflags ac_cv_path_SENDMAIL=sendmail --zlib

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen -futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache +homespool +idn -inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="mailbox"
PKGDATADIR="/nix/store/hjaa3153mhvy0b5ygzif384asq2q5shs-neomutt-20210205/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/nix/store/hjaa3153mhvy0b5ygzif384asq2q5shs-neomutt-20210205/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version `OSX 10.14`
* Were you using multiple copies of NeoMutt at once? `No`
* Were you using 'screen' or 'tmux'? `No`
* Is your email local (maildir) or remote (IMAP)? `local`

**Comment by scottkosty** [comment]
There's been some considerable changes to the notmuch code of NeoMutt. It might be worth trying the master branch to see if you can reproduce.

**Comment by blakesweeney** [comment]
Thanks, I'll give that a try shortly.

**Comment by blakesweeney** [comment]
Just tried it with `dd58e758` and I see the same behavior. It takes a long time to open and I still see the messages trying to load the incorrect path.

**Comment by scottkosty** [comment]
> Just tried it with [dd58e75](https://github.com/neomutt/neomutt/commit/dd58e7585a017f0266a0a738b89c46c17f6fc3df) and I see the same behavior. It takes a long time to open and I still see the messages trying to load the incorrect path.

Thanks a lot for trying that. It's helpful to know you can reproduce the behavior with that commit.

**Comment by Austin-Ray** [comment]
Can you see if `notmuch search` returns the correct file path for that message? NeoMutt should be getting the path from `notmuch` itself.

I think the correct query should be:
`notmuch search --output=files -- id:35c557f5-0626-43a4-b2d3-b7e3f90c3145@dfw1s10mta453.xt.local`

**Comment by blakesweeney** [comment]
Seems like notmuch is working as I would expect.

```
❯ notmuch search --output=files -- id:35c557f5-0626-43a4-b2d3-b7e3f90c3145@dfw1s10mta453.xt.local        
/Users/blake/Email/<email>/INBOX/cur/1628015978.53070_1.tea-rex,U=7997:2,
/Users/blake/Email/<email>/[Gmail].All Mail/cur/1628016054.53070_4.tea-rex,U=171935:2,

❯ file /Users/blake/Email/<email>/INBOX/cur/1628015978.53070_1.tea-rex,U=7997:2,
/Users/blake/Email/<email>/INBOX/cur/1628015978.53070_1.tea-rex,U=7997:2,: SMTP mail text, ASCII text, with very long lines

❯ file '/Users/blake/Email/<email>/[Gmail].All Mail/cur/1628016054.53070_4.tea-rex,U=171935:2,'
/Users/blake/Email/<email>/[Gmail].All Mail/cur/1628016054.53070_4.tea-rex,U=171935:2,: SMTP mail text, ASCII text, with very long lines
```

Is there a debug build or something I should try out?

**Comment by Austin-Ray** [comment]
Can you try branch [devel/issue-3017](https://github.com/neomutt/neomutt/tree/devel/issue-3017)? It will only link against notmuch 0.32.

**Comment by blakesweeney** [comment]
That fixes the issue with opening neomutt! There is some weirdness with flickering of the display though. I don't have exact steps to reproduce it but basically if start tagging messages or moving between queries/mailboxes too much then neomutt will flicker, like it is redrawing, each time I scroll up and down. I will try isolate what causes it.

**Comment by flatcap** [comment]
> There is some weirdness with flickering of the display though

Ah, that's my fault.
The code's still undergoing some large architectural changes.

It'll get fixed soon.

**Comment by blakesweeney** [comment]
Ok, good to know. Other than that everything seems to work.
