### ISSUE TITLE
Keyword management: edit-label, conflict /doc/manual.xml.head vs /doc/Muttrc.head

### ISSUE THREAD

**Issue by Vrihub** [neomutt/neomutt#303]
In /doc/manual.xml.head the "Keyword management" chapter reads:

    &lt;edit-label&gt; binding (<literal>y</literal> by default)

Wrong: the shipped /etc/Muttrc default configuration file (`/doc/Muttrc.head` in the sources) already defines a macro for the `y` key:

    macro index,pager y "<change-folder>?<toggle-mailboxes>" "show incoming mailboxes list"

so the `<edit-label>` command has no key bounded to it.

**Comment by flatcap** [comment]
Ah, well spotted.  The original label patch **did** have that keybinding.
Some people, when they moved from Mutt to NeoMutt, complained that some of their keybindings had stopped working.  So, we changed the patches to have no keybindings by default.

I've updated the docs.  The website will get refreshed before the next release.
