### ISSUE TITLE
`menu_scroll` causes flickering in index

### ISSUE THREAD

**Issue by Austin-Ray** [neomutt/neomutt#3033]
## Expected Behaviour

Scroll through mailbox smoothly without visual disturbances. 

## Actual Behaviour

NeoMutt flickers when scrolling the index list up or down.

Asciinema recording of it occurring:
[![asciicast](https://asciinema.org/a/A2G9bUpbj6cBCvp6ezPXlMkM1.svg)](https://asciinema.org/a/A2G9bUpbj6cBCvp6ezPXlMkM1)

**Note**: Asciinema sometimes shows the flickering, but sometimes it shows the UI jumping. Not sure why this is. Jumping isn't perceptible to user.

## Steps to Reproduce

1. Open mailbox
2. `set menu_scroll`
3. Scroll until the email list shifts up.

Here's a minimal configuration (swap out the mailbox for whichever you use; it affects maildir as well) and a list of terminals I tested.

```
# .neomuttrc.min
# Configuration for mailbox.
set folder=~/mail
named-mailboxes "neomutt/github" "notmuch://?query=tag:neomutt and tag:github"
set spoolfile="neomutt/github"
set nm_exclude_tags="spam,deleted"

# Functional config.
set menu_scroll
```

Reproducible in:
- alacritty
- xterm
- sakura (occasional flickers)
- terminator
- xfce4-terminal

Not reproducible in:
- st
- rxvt-unicode

## How often does this happen?

Always

## When did it start to happen?

It's been happening for a while, but it didn't bother me enough to report it at the time. The latest release 20210205 is not affected.

## NeoMutt Version

```
NeoMutt 20210205-747-27855a
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.13.10-zen1-x86_64 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.37 (compiled with 1.37)
GPGME: 1.15.1
OpenSSL: OpenSSL 1.1.1l  24 Aug 2021
libnotmuch: 5.3.0
storage: gdbm

Configure options: --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/neomutt-99999999 --with-sysroot=/ --libdir=/usr/lib64 CCACHE=none CC_FOR_BUILD=x86_64-pc-linux-gnu-gcc --full-doc --enable-nls --enable-notmuch --disable-autocrypt --enable-gpgme --disable-pgp --disable-smime --disable-bdb --enable-gdbm --disable-kyotocabinet --disable-qdbm --disable-tokyocabinet --enable-idn --disable-gss --disable-lmdb --enable-sasl --with-ui=ncurses --sysconfdir=/etc/neomutt --enable-ssl --disable-gnutls --disable-testing

Compilation CFLAGS: -O2 -pipe -march=znver1 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I//usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme -gss
  +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster +nls +notmuch
  +openssl -pgp +regex +sasl -smime -sqlite +sun_attachment

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc/neomutt"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by flatcap** [comment]
Sorry, this is a known problem.
The `Menu` is still being updated manually (too often).
Soon it will only update when it receives a notification.

This issue may hurry me along :-)

**Comment by Austin-Ray** [comment]
> Sorry, this is a known problem.

Ah, I didn't see it mentioned anywhere. Was it on IRC?

**Comment by flatcap** [comment]
> Was it on IRC?

Yes, a couple of people have mentioned it.

**Comment by flatcap** [comment]
I've pushed a fix to [[devel/flicker]](https://github.com/neomutt/neomutt/tree/devel/flicker).
Please can you give it a try.
