### ISSUE TITLE
Newb tutorial for building Neomutt

### ISSUE THREAD

**Issue by cdrage** [neomutt/neomutt#304]
Call me a noob, but I'm unable to build Neomutt.

Do we have to patch it against Mutt first before doing `./configure`?

Following basic steps, I would assume that a simple
```
git clone https://github.com/neomutt/neomutt
./configure
```

Would suffice, but there are no targets for make or ./configure :(

```
▶ make
make: *** No targets specified and no makefile found.  Stop.
```

```
▶ ./configure
zsh: no such file or directory: ./configure
```

**Comment by toogley** [comment]
Hey and welcome :)

We have already a [tutorial](https://www.neomutt.org/dev/build) for that  - its short and not for newbies, but it exists.

As far as i remember, there was a step with `autoreconf` required - but its not listed in the above tutorial and i have forgotten what exactly it was. => That means, we have to fix the documentation.

**Comment by cdrage** [comment]
@toogley Yup, that's the tutorial I followed. Unfortunately that step you mentioned is missing so I'm unable to do ./configure && make && make install xD

**Comment by flatcap** [comment]
Ah, sorry.  The missing step is `autoreconf -i`

**Comment by cdrage** [comment]
@flatcap 
Thanks for the help. That answers my question!

Sent a pull request for fix the doc https://github.com/neomutt/neomutt.github.io/pull/15

**Comment by flatcap** [comment]
Instructions fixed.  Thanks.

**Comment by guyzmo** [comment]
FYI, there's a `prepare` script at the root of the sources, so you can do `./prepare` followed by any configure options, and it will issue the autoreconf command first and configure then.
