### ISSUE TITLE
Virtual mailboxes with notmuch queries print zero email count until you open them

### ISSUE THREAD

**Issue by mbwgh** [neomutt/neomutt#3095]
Edit: It appears that the problem is about the reported number of emails in the sidebar.
The virtual mailboxes all show `0` emails, until I navigate to a mailbox. Only when the mail list is populated with the matching messages, the correct number of emails is displayed.

I.e. before:
![2021-10-25-021457_300x66_scrot](https://user-images.githubusercontent.com/28275377/138618479-a4df18ad-7579-4db9-8da8-99ba6c44e74f.png)

And after:
![2021-10-25-021549_351x66_scrot](https://user-images.githubusercontent.com/28275377/138618497-f3438b57-6baf-454a-b63b-51410c78fd0e.png)

I use the following sidebar format string:
```
set sidebar_format="%D%?F? [%F]?%* %?N?%N/?%S"
```

I use virtual mailboxes and notmuch tags to organize mail. It looks like this:
```
...
set nm_exclude_tags=deleted

unmailboxes *
virtual-mailboxes "unread" "notmuch://?query=tag:unread"
virtual-mailboxes "inbox (unsorted)" "notmuch://?query=tag:inbox"
virtual-mailboxes "  mailbox.org" "notmuch://?query=tag:mailbox.org"
...
```

However, since version 20211022 this does not yield any results anymore and the mailboxes appear empty.
The messages are still there and do not have the `deleted` tag, nor do the corresponding files have the `Trashed` flag. The messages can be found by calling `notmuch search` directly or by searching with `tag:inbox` in `neomutt`, for example. I even restored the `.glass` files from a backup, just to be sure.

## Expected Behaviour
Virtual mailboxes should be populated with matching messages.

## Actual Behaviour
Virtual mailboxes are all empty.

If NeoMutt crashed, did your OS create a 'coredump' file?

## Steps to Reproduce
See above excerpt from `neomuttrc`.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded to 20211022
  

## NeoMutt Version

```
NeoMutt 20211022
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.14.10-arch1-1 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.16.0
GnuTLS: 3.7.2
libnotmuch: 5.4.0
storage: kyotocabinet, gdbm, bdb, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --bdb --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme +gss
  +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster +nls +notmuch
  -openssl +pgp +regex +sasl +smime +sqlite +sun_attachment

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version `Linux legion 5.14.10-arch1-1 #1 SMP PREEMPT Thu, 07 Oct 2021 20:00:23 +0000 x86_64 GNU/Linux`
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? local, maildir format

**Comment by Austin-Ray** [comment]
Is `mail_check_stats` enabled?
