### ISSUE TITLE
Arch User Repository

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#31]
@shioyama @darnir @tsuflux
Hello Arch Users,

As there's now a crowd of you, I thought I'd create you an ideas area.
Let me know if you need anything from me.

Here are a few ideas to get you started.

---

Arch user rhinoceros suggested editing the wiki: https://wiki.archlinux.org/index.php/Mutt
This would be a simple way to inform new users and direct them to our packages.  It would need:

- A simple description of NeoMutt
- Why they should use it
- Document the compile options
- Instructions on how to build/install it
- Links to NeoMutt website / GitHub

Lots of the text could be cut'n'pasted from the [NeoMutt Website](http://www.neomutt.org/).

---

There are a lot of [patched versions of Mutt] (https://aur.archlinux.org/packages/?O=0&K=mutt) in the AUR.
How can we benefit from the work?
How can we reduce the confusion?

- Search for patches that NeoMutt doesn't have
- Search for addons (contrib) that NeoMutt could use
- Get maintainers to abandon their old projects and flag them out-of-date
- Add comments to old projects to direct users to NeoMutt

Can old packages be deleted?

---

Drop the versioned [neomutt](https://aur.archlinux.org/packages/neomutt/) AUR package in favour of [neomutt-git](https://aur.archlinux.org/packages/neomutt-git)

- The users aren't going to know which one to choose
- There shouldn't be any difference between them
- neomutt-git is less effort to maintain

If I make a small change to my workflow, then every GitHub commit to would be a release.

---

A couple of packages could be copied in NeoMutt by simply changing the build config:
- https://aur.archlinux.org/packages/mutt-sidebar/
- https://aur.archlinux.org/packages/mutt-kiss/

How easy is it to offer a few presets in the config?

---

What are your thoughts?

**Comment by darnir** [comment]
Let me address some of these points:

1. We should indeed update the Wiki. I will be a little short on time this weekend, else I can volunteer to update that page. My suggestion is to add a new section on NeoMutt and quote parts of the official website.

2. We must scan the AUR for different mutt packages and identify patches we don't already have. I have already started compiling a small list at: https://github.com/darnir/neomutt/wiki/Unsupported-patches
  2.1 Once we have all the patches, we can start talking to each maintainer to move their patches to track the ones NeoMutt provides. The individual packages can stay since they offer different subsets of patches.

3. I would argue that the release and git  versions of the package must both be available. That allows NeoMutt to push patches to master that would not compile against the existing release of Mutt, but in preparation for the next release. Like all the windowing changes that Mutt has going on right now. The git version would only apply to Mutt-HEAD but may incur breakages. The release version remains stable.

4. This point is along the same lines as 2. Once we integrate the patches, we can simply drop the maintainers a line to use the NeoMutt maintained patches.

**Comment by flatcap** [comment]
Hi @darnir 

1, Arch Wiki: If/when you have time.

2, Patches Wiki: Great stuff.  Ideally, you can convince the maintainers to port the patches to NeoMutt, raise a pull-request and **join us**.  There are a **lot** of unappreciated Mutt developers out there.

3:  I'm not sure.  Most of the releases I make should be stable, so I think I'd like to keep the 'neomutt' branch as a release branch.  As for the windowing changes, a neomutt-unstable (or -devel) branch would make it clear that it's not for general use.  But... I'm open to suggestions.

4: Definitely  (and suggest they **join us** :-)

**Comment by darnir** [comment]
Although for the patches, we need an easy way for the packages to selectively apply patches. Agreed we can't support any combination of patches, but atleast provide a way to access the patches directly. The only way I see right now is to download the patches tar file from the latest release. Is there any way we can provide the patchsets directly?

**Comment by flatcap** [comment]
As @paravoid pointed out in [issue-27](https://github.com/neomutt/neomutt/issues/27), the patches don't satisfy everyone.

I'm hoping to fix that with the next release.

I want to release both:
- Separate feature patches, each against Mutt-1.6.1
- Working patchset of all the NeoMutt patches (starting from Mutt-1.6.1).

The [Integration repo](https://github.com/neomutt/integration) is to be the public source of patches.

**Comment by flatcap** [comment]
> Sidebar UTF8

I've largely re-written Sidebar since its previous owner's releaes 20151111.
I'm confident that the utf8 support is solid.
I've tested it with:
- ASCII
- multi-byte, 1-column characters
- multi-byte, 2-column characters

**Comment by tsuflux** [comment]
Sorry for the late reply. @flatcap, I really appreciate the effort you are putting into this project.

1. I will add a little section to the Arch Wiki tomorrow.

2. @flatcap already compiled a pretty comprehensive list of unsupported patches at https://github.com/neomutt/community. Maybe we should merge @darnir's list into it or put it all into a GitHub Wiki for discussion purposes.

3. I prefer having separate releases as they make it more clear when something major changed or a new feature/patch has been added.

4. So for example the mutt-sidebar package would pull its source from this repository but only enable the sidebar during the build? One could argue that the package then must be renamed to neomutt-sidebar-only.

***

I agree that NeoMutt's sidebar is much better and already incorporates all previous sidebar patches.

**Comment by flatcap** [comment]
@tsuflux 

1. Thanks.
2. There are probably a few good things left to find in the community repo.  Mostly, I found the same patches repeated.  It took me quite a long time to make sure each person hadn't added anything new.
3. OK, that's fine.  As long as it isn't too much work (for you).
4. FreeBSD's build system gives the user a curses menu of tickboxes

- [X] Enable Sidebar
- [ ] Enable NotMuch
- etc
 
I was wondering if it were possible to do something similar.  Even if it were environment variables (plus instructions), e.g.
```
export NEOMUTT_BUILD=sidebar-only
make
```
If we could cover the popular choices, from AUR, we could have fewer packages, but with the same level of choice for the user.

Just an idea...  Don't worry if it's completely impractical.

PS @tsuflux please can you send me an email.  I have contact addresses for everyone else that's interested in NeoMutt -- rich@flatcap.org

**Comment by flatcap** [comment]
I've re-enabled the [NeoMutt wiki](https://github.com/neomutt/neomutt/wiki).
Use it however you will :-)

**Comment by shioyama** [comment]
@flatcap Sorry just read this now, about neomutt/neomutt-git, I agree with the others that it should remain the way it is right now. Arch/AUR users generally expect the package/package-git split, and also having just `neomutt` as a package name makes it feel less unstable to users who first install it (even if in practice the two are mostly the same).

**Comment by shioyama** [comment]
One thing: I'm wondering what we should use for the "description" of neomutt in the AUR. Currently I've just used the mutt description as-is:

```
Small but powerful text-based mail client
```

But I feel this is a lost opportunity to explain what neomutt is all about. I'm thinking something like:

```
The New Mutt: powerful text-based mail client with all the best feature patches
```

Or something like that?

**Comment by flatcap** [comment]
@shioyama Good idea.  That's much better.

**Comment by shioyama** [comment]
@flatcap done!

**Comment by shioyama** [comment]
Also updated `neomutt` to the 20160530 release.
