### ISSUE TITLE
Mailbox screen scroll stutter in full size window in a 4K monitor

### ISSUE THREAD

**Issue by RomeuG** [neomutt/neomutt#3119]
## Expected Behaviour

I was scrolling throw my list of mailboxes.
By doing it, it should be smooth, UI refreshed shouldn't be noticed, like in the folders emails list.

## Actual Behaviour

It scrolls, but it stutters a lot, especially when fullscreen in a 4K resolution monitor.

Here is a video of it happening: https://imgur.com/a/HWDGqpV

## Steps to Reproduce

Open Neomutt, go to your mailboxes, start scrolling with the arrow keys up and down.

## How often does this happen?

Depends. The bigger the window is, the more noticeable it is. If I have a very small window doing it, then 

## When did it start to happen?

I tried to check some commits. It definitely started happening since commit `f56d5a4df` (`drop MENU_REDRAW_STATUS`).
The only difference between that commit and the latest version, is that UI refreshes are no longer noticeable, but the stuttering persists.

It should be noted that in commit `5fda0838a` (the one before `f56d5a4df`), this is absolutely not an issue. It does not stutter, even with a full screen in a 4K monitor.

## NeoMutt Version

```
NeoMutt 20211022
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.14.14-zen1-1-zen (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.16.0
GnuTLS: 3.7.2
libnotmuch: 5.4.0
storage: kyotocabinet, gdbm, bdb, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --bdb --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme +gss
  +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster +nls +notmuch
  -openssl +pgp +regex +sasl +smime +sqlite +sun_attachment

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* ArchLinux 5.14.14-zen1;
* Using only one copy of Neomutt at a time;
* No `tmux` or `screen` in the mix;
* Email local;

**Comment by flatcap** [comment]
>  fullscreen in a 4K resolution monitor

hehe, talk about a first world problem :-)

**Comment by RomeuG** [comment]
Indeed! 
I tried a 1080p monitor, and it did not happen at all in the latest version!

**Comment by Austin-Ray** [comment]
I wasn't able to reproduce this on my end. Wonder if it's a configuration difference.

1. What are the values of `mail_check`, `mail_check_stats`, and `mail_check_stats_interval`?
2. What's your terminal emulator?

**Comment by RomeuG** [comment]
Hi!

* My configurations `mail_check` is set to `0`, the others are not included in my configuration. Removing this does not mitigate the issue.
* My terminal emulator is `st`, I also tried it on `urxvt` and `xterm`, the same happens in all of them.

**Comment by Austin-Ray** [comment]
Was able to reproduce in `xterm`

**Comment by RomeuG** [comment]
This has been recently fixed (I cannot reproduce it anymore). You may close this, I have nothing else to add.

**Comment by flatcap** [comment]
That's great news!  Thanks for letting us know.
