### ISSUE TITLE
Title of account or color with multiple accounts

### ISSUE THREAD

**Issue by se7en-x230** [neomutt/neomutt#3120]
I have neomutt setup with 3 different mail accounts and would like to know if there is a way to easy (title or color) see in which account I am.

**Comment by jindraj** [comment]
You can put your account name into `status_format`.

Set account name when you're changing accounts and redefine status_format containing the variable of account name.

**Comment by se7en-x230** [comment]
> You can put your account name into `status_format`.
> 
> Set account name when you're changing accounts and redefine status_format containing the variable of account name.

Excellent thanks

**Comment by flatcap** [comment]
...and for a bit of emphasis you could colour it...
```
set status_format = "[WORK] ..."
color status white brightred '\[WORK\]'
```

See [Status Color](https://neomutt.org/feature/status-color) for more info.

**Comment by flatcap** [comment]
Oh, and you could also `set status_on_top = yes` which does exactly what you think it does.
