### ISSUE TITLE
Open mail in Vim

### ISSUE THREAD

**Issue by gerazov** [neomutt/neomutt#3136]
Awesome project! :sunglasses: I really like how it all works and feels - and especially how easy it is to customize it! :muscle: also kudos to [mutt-wizard](https://github.com/LukeSmithxyz/mutt-wizard) for making it easy to set it all up :+1: 

A bit related to #1047 - I would like to be able to open/view mail in Vim so I can navigate through the text and copy stuff more easily.

So far I was able to remap `l` to show me a pager based preview in a split screen, and `Return` to open the pager in full screen via:

```html
macro index l "<enter-command>set pager_index_lines=20<enter><display-message>"
macro index,pager <Return> "<enter-command>set pager_index_lines=0<enter><display-message>"
```

How can I map `Return` to open the mail in Vim rather than in the pager?

* I actually do remap `j` and `k` differently in both cases, so it's a bit lengthier (but not relevant here):

```html
macro index l "<enter-command>set pager_index_lines=20<enter><enter-command>bind pager j next-entry<enter><enter-command>bind pager k previous-entry<enter><display-message>"
macro index,pager <Return> "<enter-command>set pager_index_lines=0<enter><enter-command>bind pager j next-line<enter><enter-command>bind pager k previous-line<enter><display-message>"
```

**Comment by gahr** [comment]
`set pager=vim`

**Comment by gerazov** [comment]
So easy :sweat_smile: - thanks :pray: 

I now have:
```html
macro index l "<enter-command>set pager=<enter><enter-command>set pager_index_lines=20<enter><display-message>"
macro index,pager <Return> "<exit><enter-command>set pager=nvim<enter><display-message>"
```

And works fine, but when I exit Vim I have a prompt:
```
Command:
```
instead of going back to the index. How can I fix it?

**Comment by gahr** [comment]
`set noprompt_after`

**Comment by gerazov** [comment]
Cool - I added `unset prompt_after` and it works - thanks! :+1:  

The final setting is:

```html
macro index l "<enter-command>set pager=<enter><enter-command>set pager_index_lines=20<enter><display-message>"
macro index,pager <Return> "<exit><enter-command>set pager=nvim<enter><enter-command>unset prompt_after<enter><display-message>"
```
