### ISSUE TITLE
Add option to have `index_format` be a thread summary instead of showing the first email when folded

### ISSUE THREAD

**Issue by guiniol** [neomutt/neomutt#314]
When a thread is folded, the `index_format` only shows information about the first email. There is no way to show, for example, if there is an attachment on one of the emails in the thread.
I would like to have the option to show a summary of the thread: the index_format would show an attachment if one of the mails contained an attachment, new if one of the mails was new, a signature if one of the mail was signed and so on.
Is anyone else interested in this?
Are there some things that should not be summarised?

**Comment by toogley** [comment]
See https://github.com/neomutt/neomutt/issues/315#issuecomment-274281695 for why the `type:blue-sky` label was removed.

**Comment by flatcap** [comment]
It's a useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
