### ISSUE TITLE
Wrong time zone in attribution when using %{fmt}

### ISSUE THREAD

**Issue by rionda** [neomutt/neomutt#3140]
## Expected Behaviour

I set `attribution` to `"On %{!%F, %R %Z}, %n <%a> wrote:\n"`, expecting to see something like

`On 2021-11-19, 09:16 EST, John Doe <john@doe.com> wrote:`

## Actual Behaviour

I see `On 2021-11-19, 09:16 -0500, John Doe <john@doe.com> wrote:`

i.e., the time zone is reported as offset, not as a name. It is as if `%z` from `strftime(3)` was specified, rather than `%Z`.

## Steps to Reproduce

Set `attribution` similar to the above, then reply to a message.

Note that the attribution seems to work correctly (i.e., the time zone name is used) when using `%[fmt]` or `%(fmt)`.

(Side note: in the documentation, it is unclear where the `!` goes to disable locales)

## How often does this happen?

- Always

## When did it start to happen?

I've always seen it, but just thought of reporting it now.

## NeoMutt Version

```
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 19.6.0 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.2.20200212)
libiconv: 1.16
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.16.0-unknown
OpenSSL: OpenSSL 3.0.0 7 sep 2021
libnotmuch: 5.5.0
storage: kyotocabinet
compression: zlib

Configure options: --prefix=/opt/local --enable-doc --disable-idn --with-ncurses=/opt/local --with-nls=/opt/local --with-ssl=/opt/local --with-zlib=/opt/local --with-gpgme=/opt/local --with-idn2=/opt/local --with-kyotocabinet=/opt/local --with-notmuch=/opt/local --with-sasl=/opt/local

Compilation CFLAGS: -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/opt/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme -gss
  +hcache -homespool +idn -inotify -locales_hack -lua -mixmaster +nls +notmuch
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment

MAILPATH="/var/mail"
PKGDATADIR="/opt/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/opt/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

This is on MacOS 10.15.7. NeoMutt compiled from MacPorts.
Single copy of NeoMutt running.
Using tmux.
Happens both on local and imap email.

**Comment by gahr** [comment]
Nice catch - I'll take a look

**Comment by gahr** [comment]
As weird as it might seem, someone [went to great lengths](https://github.com/neomutt/neomutt/blob/be4745d3e86a812b25a39455a7b6456a99b2f112/hdrline.c#L698-L705) to make this very behaviour happen. Now that I think of it, I'm not sure we can go back from an offset to a timezone name (it's not a 1-1 mapping, is it?).

The reason why `%[fmt]` and `%(fmt)` work is because they use the local timezone, which is known by libc.

Does this make sense?

**Comment by gahr** [comment]
I'll close this, @rionda let me know if you have other ideas.

**Comment by rionda** [comment]
@gahr : I think that the documentation of `%{fmt}` should be improved to mention that, in this case, `%Z` behaves like `%z`) . This was quite a surprise for me. 

(Also, as I mentioned in the original submission, the documentation is a bit unclear about where the `!` is supposed to go (and many people may not know what a "leading bang" is))

**Comment by gahr** [comment]
That makes sense, I'll work on the docs
