### ISSUE TITLE
secret-tool Passwords starting with a `#` character are ignored

### ISSUE THREAD

**Issue by dele1972** [neomutt/neomutt#3141]
## Expected Behaviour

- The variable is set with the complete response of `secret-tool`.

## Actual Behaviour

- The variable is empty.

- An external command is called for the variable assignment. It looks to me as if the `#` character of the response of the calling command is evaluated as a comment and thus the variable remains empty.

## Steps to Reproduce

1. Prepare *muttrc*:

    ```set imap_pass = `secret-tool lookup user=foo domain=bar.org` ```

2. __Create fine password__ with *secret-tool* (without a `#` character):

    - `$ secret-tool lookup user=foo domain=bar.org`

    - set password to: `pass` (or something else)

3. __Check if the Var is set correctly__:

    - `$ neomutt -Q imap_pass`

    - output: `set imap_pass = "pass"`

4. __Set a bad password__ with *secret-tool* (starting with a `#` character):

    - `$ secret-tool lookup user=foo domain=bar.org`

    - set password to: `#pass`

5. __Check if the Var is set correctly__:

    - `$ neomutt -Q imap_pass`

    - output: `set imap_pass = ""`

## How often does this happen?

- Always at the start of NeoMutt

## When did it start to happen?

- Since I started using NeoMutt

## NeoMutt Version

```bash
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins und andere.
NeoMutt übernimmt KEINERLEI GEWÄHRLEISTUNG. Starten Sie 'neomutt -vv', um
weitere Details darüber zu erfahren. NeoMutt ist freie Software.
Sie können es unter bestimmten Bedingungen weitergeben; starten Sie
'neomutt -vv' für weitere Details.

System: Linux 5.10.0-1051-oem (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.13.1-unknown
libnotmuch: 5.2.0
hcache backends: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-WmwApX/neomutt-20191207+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Standard Einstellungen:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Einstellungen bei der Kompilierung:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

Um mehr über NeoMutt zu erfahren, besuchen Sie: https://neomutt.org
Falls Sie einen Bug in NeoMutt finden, eröffnen Sie bitte ein Ticket unter:
    https://github.com/neomutt/neomutt/issues
oder senden Sie eine E-Mail an: <neomutt-devel@neomutt.org>
```

## Extra Info

- Operating System and its version:  Ubuntu 20.04 LTS

- Were you using multiple copies of NeoMutt at once? No.

- Were you using 'screen' or 'tmux'? No.

- Is your email local (maildir) or remote (IMAP)? Remote.

**Comment by dele1972** [comment]
## Workaround

In my NeoMutt setting I need a variable call of *secret-tool*. So NeoMutt variables have to be used. For example, 
in my case I specify a user and a domain as value pairs so that I can read the password for the corresponding account with *secret-tool*.

My workaround is to call *secret-tool* in an external bash script and enclose the output in quotes. 
In my case the first parameter is the login name and the second is the domain. 

```bash
#!/bin/bash
{                                                                                                   
  echo "\"";                                                                                        
  secret-tool lookup user=$1 domain=$2;                                                             
  echo "\"";                                                                                        
} | sed ':a;N;s/\n//;ba'
```

I can then use this in the NeoMutt configuration file.

```
set my_PW = `getpw $MYUSER $MYDOMAIN`
```

¯\\\_(ツ)\_/¯

**Comment by flatcap** [comment]
Hi @dele1972,
You've spotted the root of the problem and your workaround is very creative,
but there's a simpler way:
```sh
# Both double-quotes and backticks
set imap_pass = "`my_script.sh`"
```

The backticks are executed and the double-quotes protect the result from being misinterpreted by NeoMutt.

Of course, if your password contains double-quotes or backslashes, then you'd need something to **escape** the problem characters,
e.g.
`my"pass` -> `my\"pass`

**Comment by dele1972** [comment]
Hi @flatcap, thanks for both :)
