### ISSUE TITLE
Changing the limit pattern changes which message is selected

### ISSUE THREAD

**Issue by mgedmin** [neomutt/neomutt#3143]
## Expected Behaviour

When I change the limit pattern in the index, I expect the same message to be selected.

## Actual Behaviour

Instead it seems that NeoMutt remembers the actual position on screen, e.g. when `<limit>~N` showed me messages 42123, 42124 and 42125, and I had 42124 selected, doing `<limit>.` shows me all the messages with message 2 selected.

## Steps to Reproduce

1. Open a large mailbox with some new messages
2. Limit to ~N
3. Select a message
4. Limit to .

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?  I don't remember, but this feels like a very recent change.  I'll try to find some time to bisect.

## NeoMutt Version

```
NeoMutt 20211029
Copyright (C) 1996-2020 Michael R. Elkins ir kiti.
NeoMutt ateina ABSOLIUČIAI BE JOKIOS GARANTIJOS; dėl smulkmenų paleisk 'neomutt -vv.'
NeoMutt yra laisva programinė įranga, ir tu gali laisvai ją platinti su tam
tikromis sąlygomis; rašyk 'neomutt -vv' dėl smulkmenų.

System: Linux 5.13.0-21-generic (x86_64)
ncurses: ncurses 6.2.20201114 (compiled with 6.2.20201114)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.14.0-unknown
GnuTLS: 3.7.1
libnotmuch: 5.4.0
storage: lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --with-mailpath=/var/mail --mixmaster --gnutls --gpgme --gss --sasl --lua --notmuch --full-doc --lmdb

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.4 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Įprastos parinktys:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Kompiliavimo parinktys:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme +gss 
  +hcache -homespool +idn +inotify -locales_hack +lua +mixmaster +nls +notmuch 
  -openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 

MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

Jei norite daugiau sužinoti apie NeoMutt, aplankykite https://neomutt.org
Jei radote NeoMutt klaidą, praneškite apie ją
    https://github.com/neomutt/neomutt/issues
arba paštu į <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version  **Ubuntu 21.10**
* Were you using multiple copies of NeoMutt at once?  **no**
* Were you using 'screen' or 'tmux'?  **no**
* Is your email local (maildir) or remote (IMAP)?  **Maildir**

I have a feeling #3135 is related.

**Comment by viklund** [comment]
I've also encountered this now (I'm running tag:20211029 on OSX, no screen/tmux and Maildir).

If the limit results in X messages beeing displayed, and the message number that's selected is less than X then I retain my selection, but if it's bigger then X I end up with message X selected.

**Comment by viklund** [comment]
I have bisected this on my computer and this is the first bad commit: 456e41d1fb09d36f66714d8da5b1faeb862b6d46.
