### ISSUE TITLE
`%F` should display all participants

### ISSUE THREAD

**Issue by guiniol** [neomutt/neomutt#315]
I would like `%F` (or a new expando? but `%F` with the proper option set should be good) to show all the participants, and use the alias if one is known. Of course, this would stay inside the limits set for `%F`.
Any opinions? I'm unsure about including Cc: or only active participants.

**Comment by toogley** [comment]
the idea of the blue sky label is a feature we would like to have but is unrealistic to implement in the near future. [Source](https://github.com/neomutt/neomutt/issues/85#issuecomment-234319337)

I guess you wouldn't work on it,  if you estimated it as unrealisitc. Therefore the removal of the `type:blue-sky` label.

**Comment by flatcap** [comment]
It's a useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
