### ISSUE TITLE
Mail headers is in wrong order

### ISSUE THREAD

**Issue by vkuznet** [neomutt/neomutt#3156]
With recent upgrade I found that in mail viewer page the order of mail attributes has changed. Originally, I had
```
From:
To:
Date:
Subject:
```
and, now I see this order
```
Subject:
Date:
From:
To:
```

## Expected Behaviour
I think it should be configurable option with some default values. Over the years I adopted the order
```
From:
To:
Date:
Subject:
```
but I understand that it may be user specific. This is why it may be configuration option.

## Actual Behaviour
The order of mail attributes has changed from previous version

## Steps to Reproduce
upgrade from previous neomutt release to version `neomutt @20211029_0+doc+gpgme+idn+mutt+sasl (active)` on macOS. 

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?
`neomutt @20211029_0+doc+gpgme+idn+mutt+sasl (active)` on macOS

## NeoMutt Version

```
neomutt -v
NeoMutt 20211029
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 20.6.0 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libiconv: 1.16
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.16.0-unknown
OpenSSL: OpenSSL 3.0.0 7 sep 2021

Configure options: --prefix=/opt/local --enable-doc --disable-idn --with-ncurses=/opt/local --with-nls=/opt/local --with-ssl=/opt/local --with-zlib=/opt/local --with-gpgme=/opt/local --with-idn2=/opt/local --with-sasl=/opt/local

Compilation CFLAGS: -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk -arch x86_64 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/opt/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme -gss
  -hcache -homespool +idn -inotify -locales_hack -lua -mixmaster +nls -notmuch
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment

MAILPATH="/var/mail"
PKGDATADIR="/opt/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/opt/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version, macOS 11.6.1, neomutt installed via macports
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? remote IMAP

**Comment by jindraj** [comment]
Please take a look at [hdr_order](https://neomutt.org/guide/configuration#12-3-%C2%A0ordering-displayed-headers) neomutt command and try adding following lines into your configuration:
```
unhdr_order *
hdr_order From: To: Subject: Date:
```

**Comment by vkuznet** [comment]
Wow, that's a life saver, so it is exists. Thanks for the tip. Closing the ticket then.
