### ISSUE TITLE
Have sync not ask about deleted emails, but only in the timeout hook

### ISSUE THREAD

**Issue by guiniol** [neomutt/neomutt#316]
I find convenient to regularly sync mail states.
However, if I put sync in the timeout hook, it asks about deleted emails, thus breaking the regular syncing and the flow of my work. I would like an option to have the timeout hook sync be without the deleted emails and the other sync to be full syncs.

**Comment by nobrowser** [comment]
That sounds like an uglification and complication of the code to support one very specific workflow.

I'd suggest instead to add a new function to perform just the operation you find useful, although I'm not that sure we can maintain a consistent view of the folder that way.

:-1:

**Comment by guiniol** [comment]
There already is the `delete` option, which toggles the behaviour.
My idea was to add a second option which would only work for the hook, however, I haven't looked at the hook code and have no idea how ugly that would be.

@nobrowser How do you keep the mail states frequently updated? I actually want this option because I have found read emails not being marked as read on the remote server.

**Comment by toogley** [comment]
@guiniol maybe you can also instead use just a `deleted` notmuch tag? you can ignore this specific tag in all virtual mailboxes

**Comment by guiniol** [comment]
I do want the mails deleted, and synced to the remote server.
However, I sometime delete things I shouldn't. I wouldn't want the timeout hook to happen between my deleting something by mistake and my noticing and undeleting it. Which i why I can't set `delete` to `yes`.

Basically, I would like a `delete=no sync` inside the timeout hook, but somehow doing `delete=no; sync; delete=ask-yes` doesn't work.

**Comment by nobrowser** [comment]
I'm not qualified to answer that because I only use mutt for local folders :-P

**Comment by guiniol** [comment]
So, after a little bit of thinking, I added this to my neomutt and it solved my problem.
```
timeout-hook 'set delete=no; exec sync-mailbox'
shutdown-hook 'set delete=ask-yes; exec sync-mailbox'
macro index,pager \CL ':set delete=ask-yes; exec sidebar-open<enter>'
macro index,pager $        ':set delete=ask-yes; exec sync-mailbox<enter>'
```

Thanks for everyone's comments.
Leaving this here in case it helps someone else down the line.
