### ISSUE TITLE
set ssl_starttls  = no does not disable START_TLS

### ISSUE THREAD

**Issue by adamsteen** [neomutt/neomutt#3161]
## Expected Behaviour

Send an email without START_TLS

## Actual Behaviour

Sending failed
`SMTP session failed: 502 5.5.1 TLS not supported`

SMTP Server
EHLO x220.local
250-Hello x220.local
250-PIPELINING
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-CHUNKING
250-AUTH PLAIN
250 SIZE
STARTTLS
502 5.5.1 TLS not supported

If NeoMutt crashed, did your OS create a 'coredump' file? No

## Steps to Reproduce

i have neomutt configured with the following relevant settings

set smtp_url      = "smtp://$my_user:$my_pass@127.0.0.1:1025"
set ssl_starttls  = no

## How often does this happen?

- Always

## When did it start to happen?
when i upgraded my system, i am not sure what version it was previously running.

## NeoMutt Version

```
NeoMutt 20211029
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: OpenBSD 7.0 (amd64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.16
libidn2: 2.3.0 (compiled with 2.3.0)
LibreSSL: LibreSSL 3.5.0
OpenSSL: LibreSSL 3.5.0
storage: kyotocabinet, tdb

Configure options: --mandir=/usr/local/man --with-ui=ncurses --docdir=/usr/local/share/doc/neomutt --with-lock=flock --idn=0 --idn2 --fmemopen --ssl --tdb --debug --sasl --kyotocabinet

Compilation CFLAGS: -O2 -pipe -g  -I/usr/local/include -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug.
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color.
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop.
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar.
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash.

Compile options:
  -autocrypt -fcntl +flock +fmemopen +futimens +getaddrinfo -gnutls -gpgme -gss.
  +hcache -homespool +idn -inotify -locales_hack -lua -mixmaster +nls -notmuch.
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment.

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"
```

## Extra Info
* Operating System and its version:  OpenBSD 7.0 Current
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? tmux
* Is your email local (maildir) or remote (IMAP)? localhost STMP 1025

**Comment by gahr** [comment]
Do you have `ssl_force_tls` set to true perhaps?

**Comment by adamsteen** [comment]
`ssl_force_tls` is not set in my config.

**Comment by gahr** [comment]
I can repro this.

**Comment by gahr** [comment]
oh, we changed the default of `ssl_force_tls` to true some time ago. You'll need to explicitely `set ssl_force_tls = false` in your config.

**Comment by adamsteen** [comment]
awesome thank you! worked a treat!

thanks for the doco update!
