### ISSUE TITLE
How to send and edit messages in drafts

### ISSUE THREAD

**Issue by faqin** [neomutt/neomutt#3188]
Hello. 
I am using this great tool for the first time, and the whole process is fairly smooth, but I currently encounter the following problems:

Some unfinished or finished emails are put into the postponed folder (Drafts), how to edit them again or send them directly？

Thanks for your help.

**Comment by jindraj** [comment]
Hello faqin,

just start composing a new message, you should be prompted whether you want to recall postponed message.
```
Recall postponed message? ([yes]/no):
```

Answer `yes`, and then you continue where you left off.

**Comment by flatcap** [comment]
That question is controlled by the `$recall` config variable, which defaults to `ask-yes`.
https://neomutt.org/guide/reference#recall

If you add the config: `set recall = no` then neomutt won't prompt you,
you will have to press <kbd>R</kbd> (the `<recall-message>` function).
