### ISSUE TITLE
Switch to modern configuration file format

### ISSUE THREAD

**Issue by nobrowser** [neomutt/neomutt#320]
Something in the JSON / YAML line.

Even s-expressions would be an improvement :-)

**Comment by toogley** [comment]
Does this provide some functional advantages?

**Comment by guyzmo** [comment]
Well, this suggestion is wrong for soooo many reasons, I'll focus just on the most obvious:

- A muttrc is not only a description file, it's also running actions,
- Syntax support is already implemented in vim, emacs…
- JSON/YAML/TOML/ini and other are usually ok solutions, mostly because you can use ready made parsers to help you serialise your configuration,
- Mutt configuration is a language available as commandline in the UI (through the `:` command) in a fashion very similar to vim's `ex`, making configuration step away from that language to some description language would be a downgrade in features ;
- Also we're currently adding the ability to script configuration using lua, and neither JSON or YAML et al. would make this possible.

shall continue?

**Comment by nobrowser** [comment]
@guyzmo : #4 is valid, should have thought about that.

#5: what does that mean?  Can you give me an example, or a link to an example?

**Comment by toogley** [comment]
@nobrowser can you explain why do you think that would be useful? i mean what does the current state of the art not provide, what YAML/JSON does?

**Comment by guyzmo** [comment]
> 5th point: what does that mean?  Can you give me an example, or a link to an example?

Well there's issue #153 and PR #298 that implements it. As a starting
point, I've added the following two commands:

```
:lua …
:lua-source file.lua
```

so you can run lua code within your configuration. The API is not yet
a full coverage of the mutt internals, but you still have all the `:set`
and `:commands`.

**Comment by guyzmo** [comment]
> 5th point: what does that mean?  Can you give me an example, or a link to an example?

Well there's issue #153 and PR #298 that implements it. As a starting
point, I've added the following two commands:

```
:lua …
:lua-source file.lua
```

so you can run lua code within your configuration. The API is not yet
a full coverage of the mutt internals, but you still have all the `:set`
and `:commands`.

**Comment by nobrowser** [comment]
Ok, so the lua project in effect supersedes this proposal.  Good to know.

I'll probably rewrite my entire .muttrc in lua when I can :-P

**Comment by guyzmo** [comment]
all in all, I'd agree with you if we were starting the project from scratch.

but having a custom language to run the commands in mutt is a great thing, and instead of starting over, improving it is a better idea. For example, like my suggestion of #294

**Comment by toogley** [comment]
Hm, as the consensus seems to be to keep muttrc config with its lua parts and further YAML/JSON doesn't show any improvements compared to our current state - i feel like this isn't usitable for the `blue-sky` milestone.

**Comment by nobrowser** [comment]
One problem (which I admit is not a huge one) with the current situation is that no other program than mutt can read the configuration.  This makes it hard to share various bits of information with the rest of the system.  For example, right now I'm pondering how to make the list of my frequent correspondents available both to mutt (as aliases) and to spamassassin (as whitelist).  You can always come up with some preprocessing or code generation trick, but it's just harder than it could be.

**Comment by toogley** [comment]
@nobrowser aah, now i understand you. i think that is possible if you start using notmuch. But i think this issue is the wrong place to disuss that (because it doesn't have to do with the issue) 

Do you want to ask on the users mailinglist or open another issue?

**Comment by guyzmo** [comment]
ok, then it's a [XY problem]. You don't really need the configuration to be in JSON or whatever, but you need it to have some information shared between the two.
Actually mutt aliases is matching an earlier format that were existing before mutt (I think it's in use by pine and abook etc.. but don't take my word on it).

I guess this is the kind of problem you'll be able to solve nicely when Lua scripting lands, with some code that parses an alias config of your liking, and calls the mutt alias command with it.

[XY problem]:http://xyproblem.info/

**Comment by guyzmo** [comment]
@nobrowser BTW, about this, as I just discovered, you can also pipe a command in a source command so its output is interpreted as mutt-speak. So basically, you can make your own JSON format for the aliases, and run:

```
source "~/bin/convert_json_to_mutt_alias ~/.alias.json |"
```

such a source code would be only a few lines long.

**Comment by nobrowser** [comment]
@guyzmo  , yes I know about this - this is covered by the "some preprocessing or code generation" clause :-)
