### ISSUE TITLE
use a modern build system like cmake // refactor autotools toolchain

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#321]
### Current state

At the moment, our build system has multiple flaws:

* Its very complicated. That means, we have [configure.ac](https://github.com/neomutt/neomutt/blob/neomutt/configure.ac), the [Makefile](https://github.com/neomutt/neomutt/blob/neomutt/Makefile.am) and everything inside the [m4 dir](https://github.com/neomutt/neomutt/tree/neomutt/m4) where build logic is placed.
* It requires a big toolchain.
* The autotools/automake toolset  in itself is not very good software ([Source](http://stackoverflow.com/a/18291580))

### Therefore

- I think much of the complexity I described above can be reduced
- I think its easier to start from scratch to build up a clean build toolset
- When we are anyways rewriting everything from scratch, i think it makes sense to upgrade to a newer toolset, for instance [cmake](www.cmake.org).

Some Links I think **may** would be useful for that:

* http://stackoverflow.com/questions/2186110/cmake-tutorial
* http://stackoverflow.com/questions/7132862/tutorial-for-converting-autotools-to-cmake?rq=1

### Questions

* Are there alternative, equal good tools existing?
* Or should we just rewrite our Autotools build configs? For that, the following things may be helpful:
    - https://autotools.io/index.html
    - https://www.nostarch.com/autotools.htm

**Comment by guyzmo** [comment]
I agree cmake is quite a nice build toolchain, which is way more flexible and nicer to work with than autotools.

The good side it's that it'll help a lot in making refactoring tasks (like #295) less expensive in terms of invested effort.

The down side is that we'd be drifting further away from the mutt source code, and thus making upstream patch application further more difficult.

**Comment by guyzmo** [comment]
though, on another hand, I might add that switching to cmake could be not that catastrophic, even when a future notmuch patch will modify the build system (adding a new dependency), it wouldn't still impact what we really care about: the `.c`/`.h`.

So I don't think that would be insane to consider doing this sooner that "blue-sky" ☺

**Comment by guyzmo** [comment]
And talking about build system, we might want to narrow our targets to a smaller set of target systems. If it works on all modern unix (free/net/openbsd, darwin, linux), and cygwin/mingw32, with recent gcc and clang, we should be fine. Then I guess most of the libc replacement .c could go away.

**Comment by nobrowser** [comment]
Add solaris to that list and I'll agree.

**Comment by nobrowser** [comment]
The one overriding reason I hear that people stick with autotools is cross-compilation support.

Do we need that (i.e. do people who build mutt need that)?

Or has cmake recently improved in that area?

**Comment by guyzmo** [comment]
> Add solaris to that list and I'll agree.

Well, given that solaris supports recent gcc/clang, it should be fine.
Also focusing on x86, ARM, and best effort with MIPS, PPC and SPARC should be fine if there are people to test those.

Anyway, we should stick with a choice of libc, compilers and fairly recent minimal libc/compiler version. I see no reasons to have a constrained to compile with GCC4 or icc, or some exotic libc.

> Do we need cross-compilation?
> Or has cmake recently improved in that area?

that I cannot tell. But I don't see why the build system would prevent this. I have done fairly big ARM projects fully compiled with CMake. The only pain is having the right toolchain installed, once it's done, it's almost a matter of feeding it with the right include/lib path, and binaries.

**Comment by guyzmo** [comment]
actually you can find many articles on cross-compiling with cmake, and many to switch from autotools to cmake. Just [one article I found][0] giving counter arguments:

- creation of a dist tarball that does not need autotools installed to be installable by the user (just run configure; make install), whereas with cmake, you need cmake
- abiilty to do make uninstall to remove the shit you've sprayed all over the system.

it also raises another issue, it's that documentation is tied to autotools today, and switching away from autotools, will mean to refactor that as well.

[0]:https://blogs.gnome.org/swilmet/2012/09/05/switch-from-cmake-to-autotools/

**Comment by toogley** [comment]
> The down side is that we'd be drifting further away from the mutt source code, and thus making upstream patch application further more difficult.

I'm not so sure about that - because we don't change the actual source code, only the build system. That means, we could still apply upstream fixes. (Of course, that would mean I would wait with the fix for #295)

**Comment by guyzmo** [comment]
> that would mean I would wait with the fix for #295 

actually if we commit on switching to CMake, I would *FIRST* change the build system, and *THEN* move the files in a series of very atomic commit that git would be able to handle in a rerere.

**Comment by toogley** [comment]
@guyzmo Hm, i'm not sure if you understood me correctly.

> actually if we commit on switching to CMake, I would FIRST change the build system, and THEN move the files in a series of very atomic commit that git would be able to handle in a rerere.

> Doing it the other way around would mean spending about a day or two hacking autotools, to then throw that work.

I mostly agree with you. The order you propsed (first cmake, then fix #295) makes sense - but i think we should wait with fixing #295 some time after we have introduced cmake. The reason is that, in my opinion, we profit a lot from upstream's work. If we fix #295, integrating upstream's work will be harder (because we have to change the directories in **every** patch we receive.)

**Comment by guyzmo** [comment]
> If we fix #295, integrating upstream's work will be harder (because we have to change the directories in every patch we receive.)

actually not, if we make a commit where we move the files, but where we're not amending the files, git knows how to rerere accordingly the patches. The process being: apply the patch to the upstream branch, and rebase the neomutt branch on that patched upstream (or merge in, same effect).

I believe one of the main reasons to move away from autotools to CMake is that autotools makes such refactoring task a huge pain. I know I would spend at least one or two days worth of work doing autotools 💩 just in order to move files around, which shouldn't be more complicated than a `git mv`.

**Comment by nobrowser** [comment]
Why is it so much simpler with cmake?  Do you not have to record the new file locations in the cmake spec files?

**Comment by toogley** [comment]
@guyzmo I'd also be interested in the answer to @nobrowser 's question :)

**Comment by darnir** [comment]
Aye. I support keeping autotools. Unless you can convince me that cmake actually provides more advantages.

**Comment by guyzmo** [comment]
the issue with current autotools setup is that it's a huge pain to actually change anything without breaking the whole build. Just reorganizing the tree as suggested in #295 would end up in a countless hours job.

**Comment by guyzmo** [comment]
As an "easy" first thing to do: if all the libc-patching .c files laid at the root could be moved to a libc-patch subdir, it would be great to get rid of those at the first level.

**Comment by darnir** [comment]
I agree that the `m4` syntax is arcane. But I don't agree that this alone is overwhelming enough to drop autotools. Such re-arranging of the build system happens once and it'll be stuck like this for the next few years (~10).

Also, autotools does indeed support wildcards and lists, just as cmake. And reorganizing the tree will not take as much time as you currently believe. Though, since we are re-organizing, I would like to use the opportunity to completely rewrite the autotools scripts for the build process. This will take about as much time as cmake would anyways. `cmake` has the disadvantage that it requires the tool to be installed on every machine that needs to neomutt. Sure, it's almost always there, but we are adding a new dependency to neomutt, which doesn't exist with autotools.

@guyzmo : When you say, "if the current build toolchain can be made simpler to use", what is it specifically that you have in mind?

**Comment by toogley** [comment]
@darnir do i understand you correctly that people who just want to use neomutt would have to install cmake?

**Comment by guyzmo** [comment]
@darnir: what you say can be done to reorganise the source code, use wildcards, etc.

I've spend a few hours trying to reorganise the source code, and ended up in an autotools nightmare, which I could untangle, but that would be like 2 days of work I could be doing stuff I'm more efficient at. My conclusion: I'm not the right guy to refactor the autotools stuff ☹.

**Comment by guyzmo** [comment]
@toogley for the cmake solution, yes:

step ①: install cmake
step ②: mkdir build; cd build; cmake ..

**Comment by pickfire** [comment]
I suggest kbuild which is used on linux as well as coreboot which provides a nice interface. Simple and easy menu to choose the features used.

**Comment by darnir** [comment]
@toogley : No, people that want to build neomutt from the release tarballs would require cmake. On the other hand, autotools is required only by people that want to build from git.

@guyzmo: I'll give it a shot. I'm extremely busy till next month, but after that I have time and I would be happy to work on refactoring the autotools code to make it cleaner and easier to handle in the future.

**Comment by toogley** [comment]
@darnir can you explain, why people building from the tarball don't need to have installed autotools?

**Comment by guyzmo** [comment]
@toogley because the first step `autoreconf --install`  is there to generate the configure script and the Makefiles, which is an intermediate step to adapt the sources for portability (where are the libs, which features are available, which are not…). Then when you install from a release tarball, you just do `/configure && make` and you're good to go.

`cmake` does this all in one step, so when you're doing a release tarball, you need to install cmake and then run it in the sources to then build and install.

**Comment by toogley** [comment]
@guyzmo Thanks a lot for explaining :)

**Comment by gahr** [comment]
FWIW, I'm also in favour of keeping the current autotools setup. m4 files are touched rarely and are usually imported from elsewhere anyway.

CMake is a pain just as much, as soon as you get past the toy project. Plus it has the "disadvantage" of needing to be installed.

Has anybody actually tried to get any of the AC_CHECK_LIB and similar functionality with CMake alone? If the dependency doesn't provide a CMake module or pkg-config file, you're on your own, and it's not a pleasant situation to be.

My 0.2 CHF ;)

**Comment by guyzmo** [comment]
@gahr my point is mainly that current situation with the build toolchain is a pain and can be simplified, I'm not saying that cmake is *the solution*. I like @darnir's offer to look at it, and try to simplify it so it's not getting in the way of the refactoring process. So I'm ok if autotools is the best tool for the job, as long as the configuration script can be reasonably simple and understandable.

**Comment by flatcap** [comment]
Changing the build system for a small project would be quite easy.

However, NeoMutt gets built on a wide range of platforms.

Anyone offering to change/improve the build system must also be willing to perform the majority of the testing and support work.

Until then, we'll stick with autotools.
