### ISSUE TITLE
tag-thread in pager mode 

### ISSUE THREAD

**Issue by VinceTT** [neomutt/neomutt#322]
Is it possible to tag-thread in pager mode with neomutt 20170113 ?
delete-thread works fine but i am unable to use tag-thread in this mode whereas this works in index mode

**Comment by flatcap** [comment]
> Is it possible to tag-thread in pager mode

No, it isn't (not in plain Mutt, either).  But it's a reasonable thing to ask for.
From the pager, you can already `<tag-message>` and `<delete-thread>`, so it probably wouldn't be hard to add.

We'll see if anyone volunteers.

**Comment by flatcap** [comment]
It's a useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).

**Comment by stefanv** [comment]
@flatcap, do you mind updating the link above to the blue-sky ideas list?  And is that still the best place to list pending ideas?

**Comment by reyman** [comment]
I try with `macro index l "<tag-thread><modify-labels-then-hide>"` and i have no problem to tag all (using notmuch backend) the thread in one time.
