### ISSUE TITLE
Log mutt_{message,error,perror}

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#323]
The output of logging functions `mutt_message()`, `mutt_error()` and `mutt_perror()` doesn't get saved to the debug log.

I don't know how I didn't notice this before, but the logging functions are missing from `.muttdebug0`.  This means that you're missing important info.

**Comment by toogley** [comment]
I will probably finish it in less than 2 weeks i think. (As this is the first time i really look into a real C program I'm a bit cautious about estimations :D)

**Comment by toogley** [comment]
I have a bit trouble to understand your description.

I've found in my `~/.muttdebug0`:

```
[2017-01-27 21:52:54] /home/toogley/mailbox is not a mailbox.
```

Looking who's printing that line:

```
$ grep -r 'mutt_error.*is not a mailbox'
curs_main.c:    mutt_error (_("%s is not a mailbox."), buf);
mx.c:    mutt_error (_("%s is not a mailbox."), ctx->path);
mx.c:      mutt_error (_("%s is not a mailbox."), path);
muttlib.c:      mutt_error (_("%s is not a mailbox!"), s);
```

This means i find at least the following confusing:
> The output of logging functions mutt_error() doesn't get saved to the debug log.

**Comment by flatcap** [comment]
Operator error :-(
