### ISSUE TITLE
Mailboxes entry in muttrc causes error

### ISSUE THREAD

**Issue by zlatsic** [neomutt/neomutt#3233]
I am trying to set up neomutt to browse a Maildir I pulled from Office 365 mailserver. It has a structure with multiple mailboxes so I tried configuring them using the ``mailboxes`` statement. The relevant part of the muttrc looks like this (I more or less followed [this](http://www.elho.net/mutt/maildir/) guide):

```
set mbox_type=Maildir

set folder="~/path/to/maildir"
set mask=".*"
set record=+"Sent Items"
set postponed=+Drafts
set spoolfile=+INBOX
set trash=+"Deleted Items"

mailboxes = +INBOX/folder
```

If I remove the last line, everything works well, the inbox opens and I can see the emails it contains (but I do not have access to the folder mailbox, as expected). With the last line, I get the following output:

```
Unknown Mailbox: /path/to/maildir
Error in muttrc, line 15:
source: errors in muttrc
```

Line 15 is the line with the ``mailboxes`` statement. So I have two questions - the first one would be if I am missing something here? I had the same mailboxes setup when I was accessing the emails with IMAP with no problems (the same account I later pulled into a maildir using isync and am trying to browse now). My second question is regarding the verbosity of the error output - the output I provided does not really specify what exactly went wrong when opening the maildir. Can the verbosity of this output somehow be increased? I tried using the -d flag at level 5 but the log entries are no different than the console output.

**Comment by flatcap** [comment]
> mailboxes = +INBOX/folder

Ah!  I think that `=` is causing trouble -- The `mailboxes` command just takes a list of mailboxes
Remove that and I think it'll work.

**Comment by zlatsic** [comment]
Wow, that solved it, thanks! Interesting that it worked with ``=`` when connecting over IMAP, I suppose it then has a different meaning?

**Comment by flatcap** [comment]
Great.

`=` and `+` are shortcuts for `$folder`
Your local dir isn't a valid maildir, but for IMAP, a path of `imap://` is equivalent to `imap://INBOX` so that works.
