### ISSUE TITLE
Screen doesn't redraw on window resize in attachment menu (receiving and composing)

### ISSUE THREAD

**Issue by dcpurton** [neomutt/neomutt#3238]
## Expected and Actual Behaviour

I use a tiling window manager and if I open another window with Neomutt in the attachment menu (either receiving or composing) the Neomutt window is not redrawn when it resizes.

## Steps to Reproduce

1. Open Neomutt
2. View attachments for an email
3. Trigger a window resize for Neomutt that (say) halves the width of the Neomutt window
4. Observe that the window is not redrawn

## How often does this happen?

Always

**Comment by dcpurton** [comment]
Actually now that I look at things more carefully. I see this in the main message index as well.

e.g., if I have Neomutt open as the right hand window on my screen and another terminal open on the left and then close the terminal on the left, the Neomutt window resizes to the full screen width, but the right hand side of the Neomutt window is left blank.

I use Awesome WM under Debian testing

**Comment by flatcap** [comment]
Thanks.  It's on my todo list.
Historically, the `Menu` controlled the updating of the entire application.
I want to stop that completely and let events cause updates, but it's quite a big step.
