### ISSUE TITLE
hcache: keep multiple mailbox caches open concurrently

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#324]
> This comment, by @sassmann has been transplanted from #244 

> Conversation about HCache speed

While we're at it, I was wondering if we couldn't add an option to mutt which keeps mail headers in memory (up to a specified size). Then switching between mailboxes should be almost instantaneous, once they've been loaded once.
Some people achieve this by running a separate mutt for every mailbox in a screen session.

**Comment by gahr** [comment]
I expect most of the pages used by backends to be resident anyway, and most likely backends will be fast at searching.. is this really a bottleneck?

**Comment by sassmann** [comment]
If you take a look at #244 you'll note that if mailboxes reach a certain size it takes a significant amount of time to re-read and sort the mails. This also applies when simply switching mailboxes inside of mutt.
Avoiding those reloads is the goal here.

**Comment by flatcap** [comment]
It's a useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
