### ISSUE TITLE
Are headers piped when using `pipe-message`?

### ISSUE THREAD

**Issue by sanjayankur31** [neomutt/neomutt#3241]
I currently have a snippet like this in my config to allow me to fetch and open URLs in e-mails with urlscan:

```
macro index,pager \cv "<enter-command> unset pipe_decode<enter><pipe-message>urlscan<enter>" "get URLs"
```

For mailing lists, the `Archived-At` header is used to include the web (Hyperkitty) URL for a message. This URL isn't included in the URL list that urlscan gives me, though. So I was wondering if this is because headers are not piped when using `pipe-message`. Would that be the case? If yes, is there a way to pipe the headers too?

Thanks very much

**Comment by sanjayankur31** [comment]
Turns out this is a urlscan thing---it ignores email headers by default, but can also scan them using `--headers`.

**Comment by flatcap** [comment]
FYI: there are four relevant config variables:
```sh
# Decode the message when piping it
set pipe_decode = no

# Control whether to weed headers when piping an email
set pipe_decode_weed = yes

# Separator to add between multiple piped messages
set pipe_sep = "\n"

# Run the pipe command on each message separately
set pipe_split = no
```
