### ISSUE TITLE
Disable the "Autoview using" line when displaying messages

### ISSUE THREAD

**Issue by replicant0wnz** [neomutt/neomutt#3243]
Would like to disable the "Autoview using" line when viewing a message. Is it currently possible?

**Comment by dcpurton** [comment]
This is no more than a hack, but you can change its color:

```
color attach_headers black black "\\[--\\ Autoview.*\\]$"
```

Of course, this won't work if you have a transparent background for your terminal and it still leaves a blank line.

**Comment by dcpurton** [comment]
> This is no more than a hack, but you can change its colour:
> 
> ```
> color attach_headers black black "\\[--\\ Autoview.*\\]$"
> ```
> 
> Of course, this won't work if you have a transparent background for your terminal and it still leaves a blank line.

@flatcap I notice this hack no longer works with your recent colour changes.

**Comment by dcpurton** [comment]
> @flatcap I notice this hack no longer works with your recent colour changes.

But this still does work:

```
uncolor attach_headers ".*"
color attach_headers brightcolor14 default ".*"
color attach_headers black default "\\[--\\ Autoview.*\\]$"
```

**Comment by flatcap** [comment]
Hmm... it works for me using `master`, using the minimal config below and a sample email.

**Note**:  The autoview line is quite wide so if it gets wrapped, then the colouring gets odd.

**Run**:
```sh
./neomutt -n -F test.rc -f test.mbox
```

**test.rc**
```
ignore *
unignore from: subject to cc date x-mailer x-url user-agent
hdr_order date from to cc subject

auto_view text/html
set mailcap_path = mailcap
color attach_headers black black "\\[--\\ Autoview.*\\]$"
```

**mailcap**
```
text/html; links -dump-width ${COLUMNS:-80} -dump %s; copiousoutput
```

**Comment by flatcap** [comment]
However, a better solution might be to use `$display_filter` -- it's run just before displaying the email in the pager.

**test.rc**
```
set display_filter = "grep -v '\\\[-- Autoview using'"
```

It needs quite a few `\`s, because NeoMutt will interpret one level when it reads the config.
NeoMutt will actually store: `grep -v '\[-- Autoview using'`

Alternatively, you could swap the `"double"` and `'single'` quotes (requiring less escaping).

**test.rc**
```
set display_filter = 'grep -v "\\[-- Autoview using"'
```

**Comment by flatcap** [comment]
> more than one display filter?

Yes, only one, so you could create a script or just chain commands with `|`

```
# Kill Autoview, squash blank lines
set display_filter = "grep -v Autoview | cat -s"
```

**Comment by dcpurton** [comment]
This is a suitable solution for me, as I also wanted to get rid of this line. I just added a section to my existing perl script.

**Comment by flatcap** [comment]
Great!
