### ISSUE TITLE
Neomutt chooses the wrong reply To: address if the origin is sent from an 'alternate' account

### ISSUE THREAD

**Issue by angelus2014** [neomutt/neomutt#3249]
## Expected Behaviour

I have several accounts defined in NeoMutt, one is a Google Workspace account that has an 'alternate' account defined inside it (Outlook). The proper SMTP server has also been defined and I can verify that the mail is sent with the correct address through the correct SMTP server. If I then receive it at another Gmail (or Outlook) account, again the mail looks okay, also if I check the headers. But when I choose 'reply', Neomutt puts the From: address from that account (let's say address2) also in the To: field (which should contain address1b). When trying other e-mail clients (Gmail or Outlook web, Apple Mail or Mailmate), I don't see this behaviour.

## Actual Behaviour

The wrong address is put in To:

## Steps to Reproduce

Take an account that has a second one defined (for example, an Outlook account as alternate inside Gmail) and sent an e-mail to another account and reply.

## How often does this happen?

- On a particular email
As explained above, it only happens with this kind of e-mail. See the attachment for an example.

## When did it start to happen?
I can't really tell as I've just noticed this and never tested/needed something like this before.

## NeoMutt Version

```❯ neomutt -v
NeoMutt 20211029
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 21.2.0 (arm64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.11
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.16.0
OpenSSL: OpenSSL 1.1.1l  24 Aug 2021
libnotmuch: 5.5.0
storage: tokyocabinet, lmdb

Configure options: --prefix=/opt/homebrew/Cellar/neomutt/20211029 --gss --disable-idn --idn2 --lmdb --notmuch --sasl --tokyocabinet --with-gpgme=/opt/homebrew/opt/gpgme --with-lua=/opt/homebrew/opt/lua --with-ssl=/opt/homebrew/opt/openssl@1.1 --with-ui=ncurses

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/opt/homebrew/opt/gpgme/include -I/opt/homebrew/Cellar/libassuan/2.5.5/include -I/opt/homebrew/opt/libgpg-error/include -I/opt/homebrew/Cellar/neomutt/20211029/include -I/opt/homebrew/opt/lua/include/lua5.4 -DNCURSES_WIDECHAR -I/opt/homebrew/opt/openssl@1.1/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme +gss
  +hcache -homespool +idn -inotify -locales_hack +lua -mixmaster +nls +notmuch
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment

MAILPATH="/var/mail"
PKGDATADIR="/opt/homebrew/Cellar/neomutt/20211029/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/opt/homebrew/Cellar/neomutt/20211029/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
macOS 12.1 (ARM, M1)
* Were you using multiple copies of NeoMutt at once?
No.
* Were you using 'screen' or 'tmux'?
Yes, but it also happens outside tmux.
* Is your email local (maildir) or remote (IMAP)?
maildir (synced with isync/mbsync and msmtp)

---
With regards,

Angelo Machils

![Screenshot 2022-02-12 at 18 30 32](https://user-images.githubusercontent.com/7578963/153719669-5e6271d8-3272-41de-a603-77a025fb071b.png)

![Screenshot 2022-02-12 at 18 30 50](https://user-images.githubusercontent.com/7578963/153719676-0e3cfa10-4665-4b8c-9a50-819568e2e2bb.png)

[test_email.txt](https://github.com/neomutt/neomutt/files/8054013/test_email.txt)

**Comment by gahr** [comment]
Can you post the relevant parts of your config file, such as `from` and `alternates`?

**Comment by gahr** [comment]
Does this config achieve what you need?

```
set reply_self = yes
set from = 'Angelo Machils <angelo.machils@gmail.com>'
alternates '^angelo\.machils@bst.bg$' '^angelo\.machils@gmail.com$'
```

**Comment by gahr** [comment]
Perhaps what we should do is only reply to the `to` is `from` is not a user's address too, so here
https://github.com/neomutt/neomutt/blob/5ecb56e228bdb7404ea4df310572fb925fdcb834/send/send.c#L824

we'd do
```diff
--- a/send/send.c
+++ b/send/send.c
@@ -821,7 +821,8 @@ static const struct AddressList *choose_default_to(const struct Address *from,
                                                    struct ConfigSubset *sub)
 {
   const bool c_reply_self = cs_subset_bool(sub, "reply_self");
-  if (!c_reply_self && mutt_addr_is_user(from))
+  if (!c_reply_self && (mutt_addr_is_user(from) &&
+      !mutt_addr_is_user(TAILQ_FIRST(&env->to))))
```

thoughts, @flatcap ?

**Comment by angelus2014** [comment]
> Can you post the relevant parts of your config file, such as `from` and `alternates`?

This is from the Workspace account where the 'alternate' address has been defined (I will refer to this one as account1):
'''# vim: filetype=neomuttrc
# muttrc file for account gsuite
alternates angelo.machils@bst.bg
set realname = "Angelo Machils"
set from = "angelo@machils.org"
set sendmail = "msmtp -a gsuite"
alias me Angelo Machils <angelo@machils.org>
set folder = "$HOME/Mail/gsuite"
set header_cache = $HOME/.cache/mutt/gsuite/headers
set message_cachedir = $HOME/.cache/mutt/gsuite/bodies
set mbox_type = Maildir
set signature = "~/.config/mutt/signatures/1-gmail.sig"
set reverse_name
unset envelope_from_address
set use_envelope_from'''

But when it's received another account (regular gmail, account2), in Neomutt the reply address is wrong. This behaviour is also present when I sent the e-mail directly from the web for account1. If I open this e-mail received on account2 in another e-mail client, the reply To: address is correctly (tested on gmail web, Apple Mail and MailMate).
It's a bit hard for me to explain properly :)


---
With regards,

Angelo Machils

**Comment by angelus2014** [comment]
Thank you for configming and well, kinda :)

On account1 I created that config I posted earlier, to mirror the account setup in my main Google account (machils.org with an incorporated Outlook account, the bst.bg one). If e-mail arrives in to that address, Google puts it in a seperate folder and Neomutt picks that up and if I reply there, the proper From: and To: is populated. *But*, while testing, I noticed that if I sent/reply from that alternate/subaccount to another (totally separate Google account), in the pager for _that_ account, it looks okay (From: bst.bg and To: gmail.com), but when replying back, Neomutt puts the gmail.com address in both the From: and To: (as you saw as well). I did try to put that config from Gahr in the gmail.com configuration (although I think the alternates `'^angelo\.machils@bst.bg$' '^angelo\.machils@gmail.com$'`
 shouldn't be there as the bst.bg is not an alternate for account2, but for account1) and yes, then the reply is populated correctly. But this is just a test, to see if the account1 set up was correct with the 'alternates' and msmtp was using the correct SMTP server. If I use this to sent a mail (or reply) to anyone else who uses Neomutt, he/she will see the same issue. 


---
With regards,

Angelo Machils

**Comment by flatcap** [comment]
> although I think the alternates ... shouldn't be there as the bst.bg is not an alternate for account2, but for account1)

I _did_ wonder about that.

The `alternates` command is "global", so you _could_ work around it.
Each account config could `unalternates *`, then `alternates` the relevant addresses.

**Comment by flatcap** [comment]
The code that handles replies is very delicate and all the interactions are poorly understood.
We need to be very cautious before altering it.

Here's an overview of replying, which unfortunately doesn't mention `alternates`
https://neomutt.org/guide/advancedusage#compose-flow

Here are the docs for sending mail.  They mention the `alternates` in "Group reply".
https://neomutt.org/guide/gettingstarted.html#sending

**Comment by angelus2014** [comment]
Owwww :) So, if I understand correctly, the problem with account2 is a result from the configuration of 'alternates' in account1, somehow messed up how account2 handles the reply?!

Anyway, I put `unalternates *` in the config of account2 and it does the trick. I remove the config from gahr (from account2) and it still seems to work. Does this also mean that other receivers from this bst.bg alternate won't experience problems?

**Comment by flatcap** [comment]
> the problem with account2 is a result from the configuration of 'alternates' in account1,
> somehow messed up how account2 handles the reply?!

Possibly?  Probably?

Mutt is a very old program.  Back when it was created, people had one email address (imagine! :-)
Everything was global and it worked _ok_.

NeoMutt is trying to fix a lot of these problems, but we've still got a long way to go.

> Anyway, I put `unalternates *` in the config of account2 and it does the trick.
> I removed the config from gahr (from account2) and it still seems to work.

That's great.

> Does this also mean that other receivers from this bst.bg alternate won't experience problems?

Sorry, don't know.

If you have a free moment, I'd try to test your three accounts.
Send from A -> B, A -> C, B -> C (and the reverse of each) and check what the replies look like.

**Comment by angelus2014** [comment]
> If you have a free moment, I'd try to test your three accounts. Send from A -> B, A -> C, B -> C (and the reverse of each) and check what the replies look like.

I've tried several options/routes and they all seem to work. Thank you!


---
With regards,

Angelo Machils

**Comment by flatcap** [comment]
> I've tried several options/routes and they all seem to work

Great!  Thanks for letting us know.

> Thank you!

You're welcome.
