### ISSUE TITLE
Get rid of in-house implementations of STD C / POSIX.1 functions

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#325]
This is to track the effort to get rid of in-house implementations of Standard C and POSIX.1 functions which are nowadays available in all target platforms.

The existence of all removed functions were checked on: FreeBSD 11.0, RHEL 6.6, Solaris 11.3, AIX 7.1.

See: #327

**Comment by toogley** [comment]
@gahr can you elaborate why this is needed? I don't have much experience with C, so i couldn't tell why you do this.

**Comment by gahr** [comment]
@toogley The idea is to get rid of code mutt developers have either implemented on their own or borrowed from glibc in the past , with the assumption is that nowadays all the platforms we care about do implement those pieces anyway. The goal is the removal of unused files and lines of code :)

**Comment by toogley** [comment]
@gahr ah, so those functions you remove in this issue are copy-pasted from glibc?

**Comment by gahr** [comment]
> @gahr ah, so those functions you remove in this issue are copy-pasted from glibc?

Most are, some are not, but they were all meant to fill gaps between implementations, and all are APs defined by either standard C or POSIX.1.

**Comment by d-k-c** [comment]
(Raised the point on IRC, just adding a comment here to keep a trace of that)

The "BEWARE" file warns against using "tolower" instead of the ascii_ variant that was implemented in ascii.c. Are we sure that doing `s/ascii_tolower/tolower` is safe?

**Comment by gahr** [comment]
I honestly do not understand the concern. All ISO-8859 share the 0x00-0x7F range with ASCII. Since we're always comparing strings with known ones or for cosmetics' sake - that's use case for tolower in mutt -  and since all compared-to strings are ASCII, I see no problem with using plain `tolower`.

Am I missing anything?

**Comment by guyzmo** [comment]
how different is the specific `mutt` equivalent, what special stuff might it be doing?

**Comment by gahr** [comment]
Nothing - as long as you stay in ASCII space.

**Comment by gahr** [comment]
.. and as far as I can see ;)
