### ISSUE TITLE
Add expando for the current local time

### ISSUE THREAD

**Issue by cbrownstein** [neomutt/neomutt#3255]
## What would you like to be able to do?

I would like to be able to use the `%<fmt>` expando (for the current local time) which is in Mutt. See: http://www.mutt.org/doc/manual/#index-format

> `%<fmt>` | the current local time. “fmt” is expanded by the library function strftime(3); a leading bang disables locales.
> -- | --

NeoMutt currently only has expandos for:

- the date and time of the message, converted to the sender's timezone → `%{fmt}`
- the date and time of the message, converted to the local timezone → `%[fmt]`
- the local date and time the message was received → `%(fmt)`

See: https://neomutt.org/guide/reference.html#3-170-%C2%A0index_format

I use Thunderbird in addition to NeoMutt. In Thunderbird, messages are archived into a folder for the year the user chooses to archive the message, regardless of the date of the message or the date the message was received. 

In Mutt, I use the following save-hook to make it easier for me to archive messages by the current year:

`save-hook . =Archives.%<%Y>`

I can't use this save-hook in NeoMutt because NeoMutt lacks the expando for the current local time.

## What needs to change in NeoMutt?

The `%<fmt>` current local time expando in Mutt needs to be brought into NeoMutt.

## Have you tried any alternative methods?

I haven't.

## Additional Info

None.

**Comment by flatcap** [comment]
Ah!  We _used_ to have that but it was removed and `%<>` got reused to support nested conditionals.
There are only so many useful pairs of characters available for expandos.
([Nexted if](https://neomutt.org/feature/nested-if): read this if you'd like to melt your brain :-)

However, we can workaround your problem

**Comment by flatcap** [comment]
Or how config using backticks:

```sh
save-hook . =Archives.`date +%Y`
```

This would work unless you used it over New Year.

**Comment by cbrownstein** [comment]
> Or how about config using backticks:
> ```
> save-hook . =Archives.`date +%Y`
> ```

I thought about this. I think it's the best solution.

> This would work unless you used it over New Year.

How do you figure? AFAICT, it will always produce the current year, just like `%<%Y>` does in Mutt.

Also: thank you very much for the help and all the time and effort you put into making NeoMutt great.

**Comment by flatcap** [comment]
> > This would work unless you used it over New Year.
> 
> How do you figure?

The hook's value is determined when the config is read.
(I had a few attempts to escape or quote the backticks, but that gave me a prompt of literally ``` `date` ```)

So, if you started NeoMutt on Dec 31<sup>st</sup> and then used the `save-hook` in Jan1<sup>st</sup> !

> thank you very much for the help and all the time and effort you put into making NeoMutt great.

You're welcome.

**Comment by cbrownstein** [comment]
> The hook's value is determined when the config is read.

Ack.

I'm closing this ticket since we have workarounds documented here.
