### ISSUE TITLE
Does $header_cache_backend really need to be set for header caching?

### ISSUE THREAD

**Issue by cbrownstein** [neomutt/neomutt#3259]
According to the NeoMutt Guide Reference section, no header caching will be used if [`$header_cache_backend`](https://neomutt.org/guide/reference.html#header-cache-backend) isn't set.

The same is said in the NeoMutt Guide Optional Features section under the [Header Caching](https://neomutt.org/guide/optionalfeatures.html#header-caching) heading:

> Additionally, [$header_cache_backend](https://neomutt.org/guide/reference.html#header-cache-backend) **must** be set to specify which backend to use. The list of available backends can be specified at configure time with a set of --with-<backend> options. Currently, the following backends are supported: bdb, gdbm, kyotocabinet, lmdb, qdbm, rocksdb, tdb, tokyocabinet.

Despite what the documentation says, header caching works for me with only `$header_cache` set (to a directory). I do not have `$header_cache_backend` set.

So… does `$header_cache_backend` really need to be set for header caching? It doesn't seem so.

This is probably a trivial question I'm asking but, IMO, the documentation should accurately state under what conditions it is actually necessary to set `$header_cache_backend`.

**Comment by flatcap** [comment]
> So… does `$header_cache_backend` really need to be set for header caching?
> It doesn't seem so.

You're right.  That needs fixing.

In fact since we split up the hcache (442faa55a five years ago),
NeoMutt's picked a default backend if `$header_cache_backend` wasn't set.

The code defaults to the first entry...
https://github.com/neomutt/neomutt/blob/f3b9af50105daaa18563e929d4d39bd7a88de372/store/store.c#L107-L114

... in this table (dependent on `./configure` options
https://github.com/neomutt/neomutt/blob/f3b9af50105daaa18563e929d4d39bd7a88de372/store/store.c#L50-L76

**Comment by flatcap** [comment]
FYI: We tend to recommend **lmdb** as a fast modern database.

**Comment by cbrownstein** [comment]
>> So… does $header_cache_backend really need to be set for header caching? It doesn't seem so.
> 
> You're right. That needs fixing.

I volunteer to update the doc, now that I understand better how NeoMutt uses `$header_cache_backend`.

**Comment by flatcap** [comment]
> I volunteer to update the doc

Brilliant!  Thanks

The docs are auto-generated form multiple sources
(if you want to know how complicated that is, have a look at the [right-hand diagram](https://neomutt.org/dev/build/make))

The two you'll need are:
- Config variables: [docs/config.c](https://github.com/neomutt/neomutt/blob/master/docs/config.c#L1509) line 1509+
- Main guide: [docs/manual.xml.head](https://github.com/neomutt/neomutt/blob/master/docs/manual.xml.head#L12400) line 12400+

If you have any question, just ask.
You can also find us on IRC: `#neomutt` on `irc.libera.chat` ([web client](https://kiwiirc.com/nextclient/irc.libera.chat/#neomutt))

Thanks!
