### ISSUE TITLE
notmuch: Ability to toggle tag 

### ISSUE THREAD

**Issue by bbenne10** [neomutt/neomutt#326]
Hoping I'm reaching out via proper avenues to make a feature request. If not, please let me know where I should be posting and I'll happily move this there.

Essentially what I am looking for is a more advanced form of the `modify-labels` function that exists. I would like a way to toggle the presence of a tag (or list of tags) on a message (or set of messages). I currently have a muttrc.keybinds that looks something like this ad infinitum:

```
macro index tt "<modify-labels>+todo\n" "Add tag todo"
macro index tT "<modify-labels>-todo\n" "Remove tag todo"
```
It'd be VERY nice if I could simply combine these two lines into one. Something along the lines of:

```
macro index "<toggle-labels>todo\n" "Toggle tag todo"
```

**Comment by flatcap** [comment]
This is the right place :-)

How about another syntax that doesn't require a new command `!label`
```
macro index tt "<modify-labels>!todo\n" "Toggle tag todo"
```

It shouldn't be too hard to implement.

**Comment by bbenne10** [comment]
In an attempt to help out here, I just looked up the implementation for `modify-labels` and my eyes immediately glazed over.  I should have expected some complexity from such a powerful tool, but that was eye opening. I think I'm going to have to leave this one to someone a bit more familiar with the project 😳

**Comment by toogley** [comment]
> I should have expected some complexity from such a powerful tool

I think its just plain old and a lot of the complexity could be reduced (we are currently working hard to do so. But its hard.. we don't have many developers and a lot of the work is painful.) :D

**Comment by flatcap** [comment]
Mutt, as a whole, is a bit of a mess, but the notmuch code is well-written.
To implement my syntax `!label` you would only need to alter [one function](https://github.com/neomutt/neomutt/blob/neomutt/mutt_notmuch.c#L1324-L1367) in mutt_notmuch.

Take a look.  If you're interested we can talk you through anything else you need to know.

**Comment by guyzmo** [comment]
being a mutt+notmuch user, I can have a look at that, and see if I can provide a patch. I'll look into that a bit later (I'm a bit busy today to be able to do some code ☹).

**Comment by guyzmo** [comment]
…or, @bbenne10, I can help you fixing it!

BTW, don't hesitate to join the `#neomutt` channel on irc.freenode.org IRC network.

**Comment by bbenne10** [comment]
It looks like there's no implementation of `notmuch_message_has_tag` (just `notmuch_message_get_tags`, which returns a tags "object". So that will likely have to be the first step, then it's pretty trivial (since, like the '-' case, we'll always have an indicator of action, we just skip the first character, store the rest as 'tag' and check if it's present and do our thing). I should have enough info to do this (and if not, it's my rusty c skills and no fault of the documentation 😛)

**Comment by flatcap** [comment]
Great!

There's a brief guide to building NeoMutt: https://www.neomutt.org/dev/build
And an even briefer guide to debugging: https://www.neomutt.org/dev/debug
(both works in progress)

Debugging an ncurses program is a little tricky.
Run neomutt in one window, then find the process id and run `cgdb --pid X` in the other window.
(cgdb is a pretty wrapper to gdb)

Any questions, just ask.  Either here or on IRC.
