### ISSUE TITLE
Cursor position lost when limiting to 'all'

### ISSUE THREAD

**Issue by Krakonos** [neomutt/neomutt#3272]
Hi!
Recently, it appears the following workflow in neomutt is broken. I usually search for messages in this way:
1) hit 'l' to limit, type my filter
2) view the messages - in case I want a message in a thread that did not match my filter, I move the cursor there
3) hit 'l' to limit, type 'all' to remove the filtering.

Usually, the cursor stayed at the message and I could view the whole thread, or even threads from around that time.

This approach is very useful when I'm looking for something, can't recall details for a quick search (body search is sloooow), but know a time related event.

## Expected Behaviour

The cursor should stay on the same message when the message is still visible in the view.

## Actual Behaviour

The cursor resets to some other line. I did not find a relationship to which message it resets.

## Steps to Reproduce

See the initial report above.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded - but I don't recall the version, it's been happening for a while.

## NeoMutt Version

```
NeoMutt 20211029
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.16.0-arch1-1 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.16.0
GnuTLS: 3.7.3
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, bdb, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --bdb --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -fdebug-prefix-map=/build/neomutt/src=/usr/src/debug -flto -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme +gss 
  +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster +nls +notmuch 
  -openssl +pgp +regex +sasl +smime +sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: up-to-date archlinux
* Were you using multiple copies of NeoMutt at once? No.
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? IMAP

**Comment by Krakonos** [comment]
Sample terminal session showing the issue. Note at the end, my cursor is at a different message than in the filtering:

[![asciicast](https://asciinema.org/a/80sU3Wx8agpymyuH5E1WLzJjG.svg)](https://asciinema.org/a/80sU3Wx8agpymyuH5E1WLzJjG)

There is nothing special about the muttrc and mbox, the muttrc is simple:

```
set spoolfile="testbox.mbox"
```

**Comment by gahr** [comment]
This should be fixed now on master. Can you please try again?

**Comment by Krakonos** [comment]
Master seems to be fixed for me, thanks for the fix!
