### ISSUE TITLE
Improve documentation for nm_record and nm_record_tags

### ISSUE THREAD

**Issue by rionda** [neomutt/neomutt#3281]
The [documentation for nm_record](https://neomutt.org/guide/reference.html#nm-record) is a bit scant, and unclear.

I believe it would be more complete (from what I understand), to say something like:"When writing a just-sent message to the Neomutt record, also add it to the notmuch DB. Replies inherit tags from the original messages."

The comment to `nm_record` in the `neomuttrc` example in the [notmuch feature page](https://neomutt.org/feature/notmuch) could also be made to match (it is, IMHO, less clear than the sentence above). 

The [documentation for nm_record_tags](https://neomutt.org/guide/reference.html#nm-record-tags) is equally vague and potentially a bit misleading. It also contains an extra spurious sentence ("When set to 0...") that should be removed.

A better description could be: "Tag modifications to be applied to just-sent messages added to the Neomutt record. See the [documentation for <modify-labels>](https://neomutt.org/feature/custom-tags#table-custom-tags-functions) for the syntax." I'm inferring this part from the `neomuttrc` example in the [notmuch feature page](https://neomutt.org/feature/notmuch), which shows a tag preceded by "-", which implies removal. I admit I haven't tested it.

**Comment by flatcap** [comment]
> scant ... unclear ... vague ... misleading

hehe

If you have time to update the docs, that'd be really appreciated...
(or @scottkosty @Austin-Ray)

The source of the config docs is in `docs/config.c`

https://github.com/neomutt/neomutt/blob/f757a4c8dd2a43ee0fb65504c9e66594131c4e78/docs/config.c#L2667-L2678

The source of the feature page is in `docs/manual.xml.head`

https://github.com/neomutt/neomutt/blob/f757a4c8dd2a43ee0fb65504c9e66594131c4e78/docs/manual.xml.head#L15857-L16463

**Comment by rionda** [comment]
Hi @flatcap , 
I did not mean to sound snarky with those adjectives. I'll try to submit a patch, thanks for the pointers (I actually did not know where to find the source for the docs).
