### ISSUE TITLE
Sidebar indent with virtual mailboxes

### ISSUE THREAD

**Issue by rionda** [neomutt/neomutt#3283]
Is there a way to get the sidebar to indent virtual-mailboxes? I tried creating a virtual-mailbox `foo` and another `foo/bar`, and all the indent settings are active and the delimiter chars include the slash, but the `foo/bar` is not shown as `bar` indented under the `foo`.

**Comment by flatcap** [comment]
The notmuch experts might have a better way,
but using leading spaces in the "label" part works:

```
virtual-mailboxes "a"     "notmuch://?query=apple"
virtual-mailboxes " b"    "notmuch://?query=banana"
virtual-mailboxes "  c"   "notmuch://?query=cherry"
virtual-mailboxes "   d"  "notmuch://?query=damson"
```

**Comment by jindraj** [comment]
AFAIK the only solution now is what flatcap suggests. I believe there's already an issue for this. It used to work before, this feature has been touched several times in the past and I think everytime after touching the indentation code some existing usecase has been broken. I personally picked similar approach, turning off indentation and naming mailboxes
"GMail"
"GMail/INBOX"
"GMail/INBOX/work"
"GMail/INBOX/personal"
"GMail/unread"
"GMail/flagged"
"GMail/sent"
"GMail/drafts"
"GMail/spam"
"GMail/trash"
"GMail/work"
"GMail/work/ticketing"

**Comment by rionda** [comment]
Thanks @flatcap and @jindraj. Using the full path seems a pretty usable approach. (Side question: I see that you used `named-mailboxes` instead of `virtual-mailboxes`. Are they effectively equivalent?)

**Comment by flatcap** [comment]
Yes, `named-mailboxes` is the new `virtual-mailboxes`

The notmuch code introduced the `virtual-mailboxes` command.
We created a `named-mailboxes` command to extend the naming to all mailbox types.
Years later, upstream mutt introduced `mailbox -label` (which we haven't ported yet).

**Comment by jindraj** [comment]
One more note to the topic of sidebar indentation and named-mailboxes/virtual-mailboxes

Sidebar indentation works based on `sidebar_delim_chars` and it seems it currently operates only on mailbox definition (in case of virtual-mailboxes/named-mailboxes it's the notmuch query). In following examples I'll set sidebar_delim_chars to two differtent characters **L** (in my config it's present only in some notmuch queries) and **G** (present only in some mailbox names)
`set sidebar_delim_chars="L"`
```
"lists"                                "notmuch://?query=is:maillists" \
"lists/nslcd"                          "notmuch://?query=List:nss-pam-ldapd-users" \
"lists/neomutt"                        "notmuch://?query=List:neomutt.org" \
"lists/neomutt/users"                  "notmuch://?query=List:neomutt-users-neomutt.org" \
"lists/neomutt/developers"             "notmuch://?query=List:neomutt-devel-neomutt.org" \
"lists/github.com"                     "notmuch://?query=List:github.com" \
"lists/github.com/neomutt"             "notmuch://?query=List:neomutt.github.com" \
"lists/github.com/neomutt/neomutt"     "notmuch://?query=List:neomutt/neomutt AND NOT List:neomutt/homebrew-neomutt" \
"lists/github.com/neomutt/management"  "notmuch://?query=List:neomutt/management" \
"lists/github.com/neomutt/homebrew"    "notmuch://?query=List:neomutt/homebrew-neomutt" \
"lists/github.com/neomutt/translators" "notmuch://?query=List:neomutt/translators" \
"lists/github.com/sensu-plugins"       "notmuch://?query=List:sensu-plugins.github.com" \
"lists/github.com/other"               "notmuch://?query=List:github.com AND NOT (List:neomutt OR List:sensu-plugins)" \
"lists/github.com/about-me"            "notmuch://?query=to:@noreply.github.com AND (to:mention@ OR to:author@ OR to:assign@ OR to:comment@ OR to:review_requested@)" \```
```
and here's the result:
```lists [8]                          2/17213
  lists/nslcd                          202
  lists/neomutt [2]                    739
  lists/neomutt/users [2]              592
  lists/neomutt/developers             147
  lists/github.com [5]             2/14551
  lists/github.com/neomutt [3]     2/14284
    lists/github.com/neomutt/neomut2/14124
  lists/github.com/neomutt/management    5
  lists/github.com/neomutt/homebrew     56
  lists/github.com/neomutt/translators  86
  lists/github.com/sensu-plugins       106
      lists/github.com/other [2]       161
```
      
     
However setting `set sidebar_delim_chars="G"` to prove it's not operating on the defined mailbox name won't indent any of the mailboxes named GMail. I 

```sample                                  21
local                                    1
GMail                                    0
GMail/INBOX                           1/27
GMail/INBOX/work                      1/24
GMail/INBOX/personal                   2/5
GMail/unread                           3/3
GMail/flagged [18]                      18
GMail/sent                           10233
GMail/spam                              51
GMail/trash                            770
GMail/work [5]                     1/43455
GMail/work/ticketing                  4802
GMail/orders                             7
GMail/newsletters                    10710
GMail/receipts                         166
GMail/linkedin                        1136
```

**Comment by rionda** [comment]
Right, I am completely ignorant of the any neomutt code, but I'm wondering whether the indent code could check whether the mailbox is a named mailbox and if it is, operate on the description? Or at least, make that depend on a flag (`sidebar_indent_use_description`), as it may break other use cases that currently work.
