### ISSUE TITLE
Characters in a sequence of a macro are "eaten" in the definition of another macro

### ISSUE THREAD

**Issue by rionda** [neomutt/neomutt#3288]
## Expected Behaviour

Use a macro that adds a notmuch tag "starred" to a message, while also having a macro whose sequence is `dd`.

## Actual Behaviour

The tag "starre" is added instead, and other 'd' characters in the definition of the macro are "eaten".

## Steps to Reproduce

Have the following in your `.muttrc`:
```
# We use d as prefix for the dd "trash tag toggle" macro
bind index d   noop
# Macro to star/unstar
folder-hook somefolder "unmacro * S"
folder-hook somefolder "macro index,pager S \"<modify-labels>!starred<enter><sync-mailbox><enter-command>echo 'Toggled starred tag'<enter>\""
# Macro to move message to/from trash
folder-hook somefolder "unmacro * dd"
folder-hook somefolder "macro index,pager dd \"<modify-labels>!trash<enter><sync-mailbox><enter-command>echo 'Toggled trash tag'<enter>\""
```

Try using the `S` macro. See how the `starre` tag is added and the message `Toggle starre tag` is printed: the 'd's were eaten.

If one comments out the definition of the `dd` macro, everything works.

The order of the macro definitions is irrelevant.

## How often does this happen?

- Always

## When did it start to happen?

- When I changed my config
  Can you narrow down **what** you changed?

  I added the above excerpt.

## NeoMutt Version

```
NeoMutt 20211029
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 21.3.0 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libiconv: 1.16
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.16.0-unknown
OpenSSL: OpenSSL 3.0.1 14 Dec 2021
libnotmuch: 5.5.0
storage: kyotocabinet
compression: zlib

Configure options: --prefix=/opt/local --enable-doc --disable-idn --with-ncurses=/opt/local --with-nls=/opt/local --with-ssl=/opt/local --with-zlib=/opt/local --with-gpgme=/opt/local --with-idn2=/opt/local --with-kyotocabinet=/opt/local --with-notmuch=/opt/local --with-sasl=/opt/local

Compilation CFLAGS: -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/opt/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme -gss
  +hcache -homespool +idn -inotify -locales_hack -lua -mixmaster +nls +notmuch
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment

MAILPATH="/var/mail"
PKGDATADIR="/opt/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/opt/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: MacOS Monterey
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? tmux
* Is your email local (maildir) or remote (IMAP)? maildir

**Comment by flatcap** [comment]
hmm... there's something weird going on with your `unmacro *` lines.
I'll have to investigate.

Changing them to list the menus seems to fix the problem.
```
folder-hook . "unmacro index,pager S"
folder-hook . "unmacro index,pager dd"
```

As you're using `dd` in the pager, I'd also change:
```diff
- bind index       d noop
+ bind index,pager d noop
```

**Comment by gahr** [comment]
I have a fix for your particular use-case in #3316, if you want to test it out. Please read the full description there: I haven't found a solution for the more general underlying issue.

**Comment by rionda** [comment]
Thank you, @gahr . 
It seems from the comments in the review that you ended up deciding it was the right fix. =)
I can't test the git version at this time, so up to you if you want to close this bug now or later.

**Comment by gahr** [comment]
Hah, yeah I did :)
