### ISSUE TITLE
Global hooks erroneously expect a pattern

### ISSUE THREAD

**Issue by guiniol** [neomutt/neomutt#329]
Global hooks (`timeout-hook`, `startup-hook`, `shutdown-hook`) should not require a filter pattern since they are global. Yet, in the current implementation, they do expect one.

**Comment by toogley** [comment]
I don't understand the logic of `should not require a filter pattern since they are global.` What has the one to do with the other?

(sry for asking sth which has little to do with the actual issue^^)

**Comment by guiniol** [comment]
> I don't understand the logic of should not require a filter pattern since they are global. What has the one to do with the other?

The standard definition for hooks is `<hook-name> <folder-pattern> <command>` which means that the hook will only trigger if the folder matches the `folder-pattern`. Global hooks, being global, trigger regardless of the current folder, so their definition should be `<hook-name> <command>`.

**Comment by flatcap** [comment]
@toogley https://www.neomutt.org/feature/global-hooks

**Comment by toogley** [comment]
@flatcap aah, sry. I've missed that feature.

@guiniol thanks for the explanation.
