### ISSUE TITLE
Linking messages from nmutt in nvim

### ISSUE THREAD

**Issue by gerazov** [neomutt/neomutt#3293]
Awesome work guys :sunglasses: 

I've been using [nvim-orgmode/orgmode](https://github.com/nvim-orgmode/orgmode) in nvim, which is a emulation of emacs' org mode. In emacs there is a way to link e-mails in the org-mode files. I've also found [Linking to emails in org-mode (using neomutt)](https://mentat.za.net/blog/2018/10/31/using-org-mode-with-neomutt/) which relies on org plugins to send the message-id to emacs.

I was wandering how can the message-id be copied to clipboard from nmutt so that I can paste in nvim? 

Then we could use a macro from nvim to call nmutt and open the message via a push command.

**Comment by jindraj** [comment]
How about defining a macro that runs `pipe-message` and then parse the message-id? Following snippet should do the thing for you.
```
macro index,pager ci \
"<pipe-message>formail -x message-id -z | awk -F '[<>]' '{print $2}'| COMMAND_TO_GET_STDOUT_TO_CLIPBOARD<enter>" \
"copy message id to clipboard"
```

COMMAND_TO_GET_STDOUT_TO_CLIPBOARD depends on Your OS.
- macOS: pbcopy
- linux: xclip

**Comment by flatcap** [comment]
I went for some basic `sed` :-)
```
sed -n -e '/^Message-Id:/s/.*<\(.*\)>.*/\1/p' | copy
```

**Comment by gerazov** [comment]
Thanks guys :pray:

The first command doesn't work:
```
sh: line 1: formail: command not found
sh: line 1: COMMAND_TO_GET_STDOUT_TO_CLIPBOARD: command not found
Press any key to continue...
```
And for the `sed` version - does it change only the `awk` part in the first one?

**Comment by jindraj** [comment]
@flatcap's version is better since you'll need only sed which is most probably already present on the system and replaces both commands from my suggestion (foremail, awk). 

to sum it up, if you're on linux then copy command is xclip. I don't know if it needs some flags or if it works without any.
```
macro index,pager ci \
"<pipe-message>sed -n -e '/^Message-Id:/s/.*<\(.*\)>.*/\1/p' | xclip<enter>" \
"copy message id to clipboard"
```

**Comment by gerazov** [comment]
Ok, I'm getting an error:

```
sh: -c: line 1: unexpected EOF while looking for matching `''
sh: -c: line 2: syntax error: unexpected end of file
Press any key to continue...
```

**Comment by flatcap** [comment]
Argh!  That was a pain.
Creating the `sed` : 30 seconds.
Getting the escaping/quoting right for NeoMutt : 30 minutes.

This works, just substitute in your `copy` program.

```sh
macro index,pager <f5> \
"<pipe-message>sed -n -e '/\^[Mm]essage-[Ii][Dd]:/s/.*<\\(.*\\)>.*/\\1/p' | copy<enter>" \
"copy message id to clipboard"

# vim: syn=neomuttrc
```

**Comment by flatcap** [comment]
> `` sh: -c: line 1: unexpected EOF while looking for matching `'' ``

That took me a while to understand.  the `^` (beginning-of-line) regex is getting "interpreted" by NeoMutt.
See: [Mailbox Shortcuts](https://neomutt.org/guide/advancedusage.html#shortcuts)

**Comment by gerazov** [comment]
Ahaha - I was wandering wtf was going on  :sweat_smile:

Ok here's the working version with `xclip`:
```muttrc
macro index,pager yf \
"<pipe-message>sed -n -e '/\^[Mm]essage-[Ii][Dd]:/s/.*<\\(.*\\)>.*/\\1/p' | xclip -sel clip<enter>" \
"copy message id to clipboard"
```

Now to figure it out on the vim side :+1: 

Thanks for the help :pray:
