### ISSUE TITLE
Changing the value of a variable with a keybind

### ISSUE THREAD

**Issue by Hazza4569** [neomutt/neomutt#3309]
I want to set a keybind to change the value of `pager_index_lines`, so that I can press a key, e.g. F11, and switch in and out of 'fullscreen', so to speak, in the pager.

Is there a way to do this? I haven't been able to work it out from the documentation.

**Comment by gahr** [comment]
This came up in IRC 3.5 years ago. Luckily, I keep my logs around:

```
macro pager,index I ':set pager_index_lines=`dc -e "10 $pager_index_lines -p"`<enter>'
```

**Comment by jindraj** [comment]
I like @gahr's solution the most. It's easy and takes only single line.

----
I remember I created a macros for this some time ago. Source the first macro in your config, then use **,m** to toggle. 

*~/.neomuttrc/toggle/neomuttrc.pager_index_lines_on*
```
set pager_index_lines = $my_pager_index_lines

macro index,browser,alias,generic,pager ,m \
"<enter-command>source $my_cfgdir/toggle/neomuttrc.pager_index_lines_off<enter>\
<enter-command>echo 'Toggle pager lines on'<enter>" \
"Toggle pager lines"
```

*~/.neomuttrc/toggle/neomuttrc.pager_index_lines_off*
```
set pager_index_lines = 0
macro index,browser,alias,generic,pager ,m \
"<enter-command>source $my_cfgdir/toggle/neomuttrc.pager_index_lines_on<enter>\
<enter-command>echo 'Toggle pager lines off'<enter>" \
"Toggle pager lines"
```
----
Or define two separate macros bound to a different keys: one for increase the other for decrease using `set pager_index_lines+=…` and `set pager_index_lines-=…`. Compared to other solutions this allows resizing by defined number of lines.
