### ISSUE TITLE
[RFC] Issue Workflow / Review

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#331]
## Overview

**Important points:**

* We don't want people to waste their time, either
  * writing code we don't want
  * duplicating the work of others

**For most new work some discussion is needed first.**

* What do you want to change?
* Why is that needed?
* What's the best way to do it?

**You can get approval from:**

* IRC
* Issue
* Mailing list

**Who gives approval?**

* Project reviewers (team on github)

**Don't need approval for:**

* Fixing bugs (assign yourself before you start)
* Altering documentation
* Adding to the website
* Adding comment blocks
* Updating translations

**Feedback:**

* We want to know what's going on, so we can plan releases
* People need a little freedom to experiment before others express their opinions

**When does a user want:**

* feedback?
* review?
* merge?

### Coder has an idea

**Open issue {NUM}**

- Coder: "I'd like to..."
- Reviewer: "OK, that's a good idea"

**Create branch in neomutt repo, either:**

- /issue/{NUM}
- /devel/feature-name

**Work:**

- write code
- push code (automatic travis build)
- repeat

### When code is ready for public scrutiny...

**Create pull request**

- Coder: "This relates to #{NUM}" (linking issue and PR)
- A.N.Other: "feedback"
- write code
- push code
- repeat

### When code is ready for review...

- Comment asking for review (or a new tag)
- Reviewer 1: "change this"
- write code
- push code
- Reviewer 1: "approved"
- Reviewer 2: "approved"

### When code is ready for merge..

- Reviewer: merge code

**Comment by guyzmo** [comment]
I think for a new feature ticket, the following template should be suggested:

1. what's wrong with current situation
2. what the feature will improve that situation
3. what's the suggested strategy to implement it
