### ISSUE TITLE
NeoMutt gets stuck when exiting while closing IMAP connection

### ISSUE THREAD

**Issue by jotoho** [neomutt/neomutt#3313]
## Expected Behaviour

Pressing the Q-key should exit NeoMutt within a few seconds at most.

## Actual Behaviour

NeoMutt gets stuck in the process of closing down. 

## Steps to Reproduce

I've not managed to discover a way of reliably reproducing this issue.
My installation of NeoMutt is configured to access mail from two different IMAP mailservers simultaneously. You can [download a copy of my current configuration from my personal nextcloud instance here.](https://nextcloud.jotoho.de/s/j85SDrApic8XicF)

## How often does this happen?

Sometimes, when exiting NeoMutt by pressing Q. Does not happen when exiting via Ctrl+C.

## When did it start to happen?

Sorry, I can't remember any details in that regard.

## NeoMutt Version

Built and installed using the (currently orphaned) [`neomutt-git` AUR package](https://aur.archlinux.org/packages/neomutt-git).

<details>
<summary>Output of `neomutt -v`</summary>

```
NeoMutt 20211029-481-0fac7e
Copyright (C) 1996-2020 Michael R. Elkins und andere.
NeoMutt übernimmt KEINERLEI GEWÄHRLEISTUNG. Starten Sie 'neomutt -vv', um
weitere Details darüber zu erfahren. NeoMutt ist freie Software.
Sie können es unter bestimmten Bedingungen weitergeben; starten Sie
'neomutt -vv' für weitere Details.

System: Linux 5.16.15-arch1-1 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.17.1
OpenSSL: OpenSSL 1.1.1n  15 Mar 2022
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=native -mtune=native -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Standard Einstellungen:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Einstellungen bei der Kompilierung:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme +gss
  +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster +nls +notmuch
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

Um mehr über NeoMutt zu erfahren, besuchen Sie: https://neomutt.org
Falls Sie einen Bug in NeoMutt finden, eröffnen Sie bitte ein Ticket unter:
    https://github.com/neomutt/neomutt/issues
oder senden Sie eine E-Mail an: <neomutt-devel@neomutt.org>
```

</details>

<details>
<summary>Output of `LANG=C neomutt -v`</summary>

```
NeoMutt 20211029-481-0fac7e
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.16.15-arch1-1 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.17.1
OpenSSL: OpenSSL 1.1.1n  15 Mar 2022
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=native -mtune=native -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme +gss
  +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster +nls +notmuch
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

</details>

## Extra Info

* **Operating System and its version**
  Arch Linux (x86-64/amd64; up-to-date)
* **Were you using multiple copies of NeoMutt at once?**
  No.
* **Were you using 'screen' or 'tmux'?**
  I don't even know what those are.
* **Is your email local (maildir) or remote (IMAP)?**
  IMAP
  
When NeoMutt gets stuck like this, it is still possible to close the client by pressing the key combination Ctrl+C.
(It then closes immediately, without the usual "Do you really want to close?" message.)

**Comment by jotoho** [comment]
The message shown while stuck:

![Screenshot_20220320_173949](https://user-images.githubusercontent.com/12120743/159174975-2e84648f-1f2d-4a64-8b48-b591db2c7f5f.png)

**Comment by jotoho** [comment]
I should note that every time this has occured it's always been this server that the client has trouble disconnecting from. Never the other configured one.

**Comment by mschilli87** [comment]
I can confirm that I have seen this kind of behaviour with a specific IMAP server as well.

**Comment by gahr** [comment]
Does NeoMutt get stuck indefinitely or is it just `imap_poll_timeout` with a default of 15 seconds being too long? Can you please try and reduce `imap_poll_timeout` to just a few seconds?

**Comment by jotoho** [comment]
> Does NeoMutt get stuck indefinitely or is it just `imap_poll_timeout` with a default of 15 seconds being too long? Can you please try and reduce `imap_poll_timeout` to just a few seconds?

As far as I can tell, NeoMutt gets stuck indefinitely. `imap_poll_timeout` is not set by my configuration and it stays stuck like that for multiple minutes at least.

I have now set `imap_poll_timeout` to 5 manually and will report back if that changed anything when the issue next occurs.

The mailserver/mailbox this happens with usually doesn't hold any emails for long. I have my other desktop mail client and my other email provider configured to regularily pull any mail from the fhswf server via POP3. Maybe the POP3 retrievals are interfering with NeoMutt? Or maybe the server software is a bit odd. I couldn't say.

> Can you please attach a debugger and see where it's waiting?

I have no experience using gdb, so I would require a bit more explanation on how to do that.

Would it be possible to attach the debugger to the NeoMutt process when the bug is already occuring? Or would I need to do something special every time I start NeoMutt on the off-chance that it happens this time?

**Comment by jotoho** [comment]
That is to say, I've never seen NeoMutt exit on it's own once the bug has occured. I've always needed to interrupt it using Ctrl+C to close it afterwards.

**Comment by mschilli87** [comment]
Just chiming in again to let you know that when this did happen to me (never found a way to reliably reproduce, eventually stopped using that server for othe reasons) I had to kill the process as well to shut down neomutt. Plus, in my case no POP3 clients were involved.

**Comment by gahr** [comment]
> Plus, in my case no POP3 clients were involved.

@mschilli87 : ITYM IMAP ?

**Comment by jotoho** [comment]
> > Plus, in my case no POP3 clients were involved.
> 
> @mschilli87 : ITYM IMAP ?

They're referring to my paragraph where I said that the mailbox is periodically emptied via POP3 by my other desktop client (Evolution) and my main email provider (mailbox.org).
We can probably exclude that as a potential cause.

**Comment by jotoho** [comment]
The only time so far that I've managed to reproduce the closing connection bug in the last days has been while accidentally using the version I've got installed without debug symbols.

This could theoretically be down to:
1. Bad or inconveniently good luck (depending on how you look at it) [probably the most likely]
2. The reduced amount of configure flags used to compile the version with debug symbols compared to neomutt-git.
3. The couple of commits that are included in my debug symbols build but not the installed neomutt-git one.

Here's the link to the backtrace without debug symbols: https://pastebin.com/TrZ7JmAC

**Comment by jotoho** [comment]
status update: neomutt still has to wait for a while with the message before fully exiting but the program closes much quicker than it used to. 

As in, nowadays (archlinux package `community/neomutt` version `20220429-1`) I cannot open and attach gdb fast enough before the process has exited. It is probably just the normal timeout duration.

As far as I'm concerned, this is no longer an issue. Feel free to reopen if anyone else reports having trouble with this.

(I wonder what the cause was. Maybe something like neomutt waiting for the timeout multiple times? Or a more nuanced bug? Perhaps something in a dependency? :shrug:)
