### ISSUE TITLE
<modify-labels-then-hide> seemingly not working

### ISSUE THREAD

**Issue by bbenne10** [neomutt/neomutt#332]
As discussed on IRC, `<modify-labels-then-hide>` doesn't seem to be exhibiting the described behavior. 

A semi-depiction of the bug may be found here: https://asciinema.org/a/1e79rtkzhy910ekizhnslx55a

In this case, the vfolder displayed is from the query "tag:gvu and not tag:deleted" and I'm toggling the "todo" tag. However, this behavior is also exhibited when using the query "tag: inbox and not tag:deleted" is viewed and the tag "inbox" is removed from a message. 

I believe this behavior was initially reported in #121, but have not yet confirmed.

**Comment by guyzmo** [comment]
next step is to determine whether the issue is a regression or a bug that's as old as neomutt.

**Comment by bbenne10** [comment]
The bug still seems present as far back as commit 8ffa4732. There are some other (quite significant) bugs in rendering the index in this commit though, which decrease my confidence that I've properly triaged this. I'll do some more digging and get back to you all.

**Comment by bbenne10** [comment]
Looks like my muttrc contributed the rendering problems, but I'm still debugging.

**Comment by bbenne10** [comment]
Looks to me like this bug was present in mutt-kz and thus was not introduced in neomutt. This leads me to believe that either there's a misunderstanding about the manner in which this feature is intended to work or that the feature was included in documentation but never actually properly implemented.

**Comment by bbenne10** [comment]
https://github.com/neomutt/neomutt/blob/8af113cf940ffe9ed91025f3b47e5ba848cb90bf/README.notmuch#L111

The above link shows that at the time of writing the intended usage involved calling `<sync-mailbox>` after applying the `<quasi-deleted>` state. Closing based on that finding. Sorry for the noise (though maybe this could be better documented somewhere?)
