### ISSUE TITLE
Changing foreground color with ansi escape sequence also changes background color to black

### ISSUE THREAD

**Issue by scorgn** [neomutt/neomutt#3321]
I wrote a script that will parse my emails and add ansi escape sequences to format them. An example here is formatting link labels to be blue so I what text is a link in the original HTML. I'm not able to do this in my neomutt config because there is no special format for these link labels (and I can't write regex to match it).

I added `set allow_ansi` to my config for these color codes to work.

I also have `color normal default default` so that mutt matches my terminal default colors.

The email parser is outputting link labels formatted as such: `"\u001B[34m" + label + "\u001B[0m"`. So, a link with the label "Verify Account" is output as `\u001B[34mVerify Account\u001B[0m`.

I am only setting the foreground color, but the issue that I'm having is that the background color is changing to black as well. The background color is changing to the same background color that mutt originally shows if I don't add `color normal default default` to my config (which seems to be my terminal's black color).

Here is an example:
<img width="274" alt="image" src="https://user-images.githubusercontent.com/26685104/160022993-ceb24a3c-9a71-4b1b-8312-adf6367f5874.png">

## Expected Behaviour
I would expect only the foreground color to change and for the background color to stay the same

## Actual Behaviour
The background color changes to my terminal's black color

## Steps to Reproduce
- Have terminal default background color different than black
- Start with minimal neomutt config with no color effects
- Add the following to your neomutt config
```
set allow_ansi
color normal default default
```
- Open email with body set to `This is a \u001B[34mtest\u001B[0m` (can be achieved by setting program in mailcap file to a program that simply prints that)
- Notice that the background color of the word "test" in the output is changed to black rather than the default terminal background color

## How often does this happen?
- Always

## When did it start to happen?
- When using ansi escape sequences

## NeoMutt Version

```
NeoMutt 20211029
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 21.3.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.11
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.17.1
OpenSSL: OpenSSL 1.1.1m  14 Dec 2021
libnotmuch: 5.6.0
storage: tokyocabinet, lmdb

Configure options: --prefix=/usr/local/Cellar/neomutt/20211029 --gss --disable-idn --idn2 --lmdb --notmuch --sasl --tokyocabinet --with-gpgme=/usr/local/opt/gpgme --with-lua=/usr/local/opt/lua --with-ssl=/usr/local/opt/openssl@1.1 --with-ui=ncurses

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/opt/gpgme/include -I/usr/local/Cellar/libassuan/2.5.5/include -I/usr/local/opt/libgpg-error/include -I/usr/local/Cellar/neomutt/20211029/include -I/usr/local/opt/lua/include/lua5.4 -DNCURSES_WIDECHAR -I/usr/local/opt/openssl@1.1/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme +gss 
  +hcache -homespool +idn -inotify -locales_hack +lua -mixmaster +nls +notmuch 
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/Cellar/neomutt/20211029/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/Cellar/neomutt/20211029/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info
* Operating System and its version
macOS Monterey 12.2.1
* Were you using multiple copies of NeoMutt at once?
No
* Were you using 'screen' or 'tmux'?
No

**Comment by flatcap** [comment]
Thanks for the detailed bug report, @scorgn.

**Good news** and good news.

First, it's **already fixed**.
The colour code has had a overhaul recently.
Tested with a transparent terminal (for good measure).

Second, there's a new **release due soon**.
It was meant to be in a week, but that might be two while we fix some more bugs.

If you can't wait, you could build your own NeoMutt,
You may discover some visual quirks -- we're working on them :-)

**Comment by scorgn** [comment]
Amazing!

I spent a good amount of time looking at the source code for [ansi.c](https://github.com/neomutt/neomutt/blob/f6b6fe6179aa258814f10ec22a2efd33c0457f9c/color/ansi.c#L233) and saw that by all means putting `\u001B[49;` _should_  be changing just the background color to the default color, but it just wasn't working.

It never occurred to me to check the version that I had instead of trunk, now I see the file is completely new altogether.

Excited for the updates, I'll build later today to test it out!

**Comment by ArveMediaconnect** [comment]
Fantastic, came here looking for help with a completely different problem with colours, compiled trunk and the problem disappeared. Looking forward to the next release!
