### ISSUE TITLE
Problem on startup

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#3340]
Maybe? As it stands, on 3e1158ff6280977d0ef57b227e66ee3da41948e0 and 53973f0be4c1013df41686c6f0f48d94642959a9 neomutt refuses to start at all. Which is to say `./neomutt` takes 1.055s real to exit 0. `./neomutt -F /dev/null` opens blank and I can navigate to a mailbox manually, but then doing `:set sidebar=on` (which is invalid, but my first instinct) immediately exits 0: 
[sidebar=on.log](https://github.com/neomutt/neomutt/files/8429145/sidebar.on.log)

As does `:set sidebar_visible` (which is valid):
[sidebar_visible.log](https://github.com/neomutt/neomutt/files/8429149/sidebar_visible.log)

`--asan` changes nothing (there's an error because it's under ptrace, but).

_Originally posted by @nabijaczleweli in https://github.com/neomutt/neomutt/issues/3330#issuecomment-1090535640_

**Comment by flatcap** [comment]
@nabijaczleweli 

I don't see that.  I cleared my env var `$MAIL` and ran:
```
neomutt -n -F /dev/null
```

I get a nearly blank screen (an empty Index).
Running: `:set sidebar=on`  I get `sidebar: unknown variable`
Running: `set sidebar_visible` shows the sidebar (empty)

**Comment by nabijaczleweli** [comment]
I've reduced the configure options to nothing; `git bisect` shows 19869c7c8b938f4062ac5e50810e0da938737765 to be the first bad commit.

**Comment by flatcap** [comment]
Hmm... very interesting.
WIthout errors, it seems fine, but if I `export MAIL=/junk` then run neomutt, bad things happen.

**Comment by flatcap** [comment]
The problem is the `shared->ctx` condtion in this line at the end of the Index Event Loop:
https://github.com/neomutt/neomutt/blob/53973f0be4c1013df41686c6f0f48d94642959a9/index/dlg_index.c#L1361

I added that because when I was testing, something crashed, somewhere, without it.

**Comment by nabijaczleweli** [comment]
Yeah, can confirm removing it does fix it. I've built without it and it seems to work at a cursory glance, will keep running it like this; built with asan/ubsan/whatever so if it does crash, then we'll have a trace.

**Comment by flatcap** [comment]
Thanks.  I need to protect a few other uses of `shared->ctx` to make sure it doesn't crash elsewhere.
