### ISSUE TITLE
Backward incompatibilities in 20220408

### ISSUE THREAD

**Issue by jpalus** [neomutt/neomutt#3343]
After upgrading neomutt to 20220408 I've spotted few incompatibilities, could anyone tell whether they are to be expected? I couldn't spot anything relevant in release notes:
1. When viewing message `'i'` no longer closes it, it's `'q'` now?
2. Solarized color scheme that I've used for years stopped working, I suppose that's part of "colours should be working correctly again"? I believe color scheme came from [here](https://github.com/altercation/mutt-colors-solarized/blob/master/mutt-colors-solarized-light-256.muttrc)
3. My binding to view urls in message stopped working `macro pager \cb <pipe-entry>'urlview'<enter> 'Follow links with urlview'`

**Comment by mschilli87** [comment]
> When viewing message `'i'` no longer closes it, it's `'q'` now?

Huh. was not even aware of the `'i'` binding. `'q'` already worked before for sure.

**Comment by jpalus** [comment]
FWIW default setup in previous version showed this in help line:
![image](https://user-images.githubusercontent.com/484155/162572893-432291d5-bd7f-4d78-815d-6b935c5f0a64.png)

**Comment by mschilli87** [comment]
Actually, `'x'` appears to be yet another alternative binding.

**Comment by flatcap** [comment]
> When viewing message `'i'` no longer closes it, it's `'q'` now?

That's a good one.
The binding from <kbd>i</kbd> to `<change-newsgroup>` (NNTP) has always been there, but it was overridden by `<exit>`.

However, some recent refactoring has lead to the functions being sorted in a different order.
I'll kill the NNTP binding.

**Comment by flatcap** [comment]
> `<pipe-entry>`

Hmm... that's odd.
I knew of `<pipe-message>`, but I hadn't noticed that function before.
Let me find out where it went.

**Comment by flatcap** [comment]
Sorry, I'm not sure how your Pager macro _ever_ worked.
The Pager never supported the `<pipe-entry>` function, only `<pipe-message>`.

`<pipe-entry>` is limited to viewing attachments and the compose screen.

(I've checked the upstream source and it's the same)

**Note**: There's a macro in the default `/etc/neomuttrc`
It does the same, but also sets `$pipe_decode`

```sh
# simulate the old url menu
macro index,pager,attach,compose \cb "\
<enter-command> set my_pipe_decode=\$pipe_decode pipe_decode<Enter>\
<pipe-message> urlview<Enter>\
<enter-command> set pipe_decode=\$my_pipe_decode; unset my_pipe_decode<Enter>" \
"call urlview to extract URLs out of a message"
```

**Comment by flatcap** [comment]
> colours should be working correctly again

This refered to ANSI colours in emails (when you have `set allow_ansi = yes`)
It also introduced some colour merging for the Index (e.g. the indicator line).
These were unreliable in some recent releases.

> Solarized color scheme that I've used for years stopped working
> color scheme: https://github.com/altercation/mutt-colors-solarized/blob/master/mutt-colors-solarized-light-256.muttrc

One of the first lines warns:

> make sure that you are using mutt linked against slang

NeoMutt dropped support for slang in release 2021-10-22.
It was seldom used and poorly understood.

In ncurses, `color123` gives you colour 123 from the terminal's palette.
The theme appears to me to select valid colours.

> Solarized color scheme that I've used for years stopped working

If you can find an example of a `colorNNN` that doesn't do what I've described, please let me know.

**Comment by jpalus** [comment]
> Sorry, I'm not sure how your Pager macro _ever_ worked. `

Not that I know how/why it worked, but it worked fine for both message and attachment until 360454304a13eeca5f52a7d18b0cb6367b491872.

**Comment by flatcap** [comment]
> it worked fine for both message and attachment until 3604543

Oh!  I had a look through the history, but I can't have looked closely enough.
Thanks for the bisect.  I'll try to figure out what I've done wrong.

**Comment by jpalus** [comment]
Regarding colors I've tried to bisect as well but after a number of refs that segfaulted on including mentioned color scheme I gave up.

Did some manual checking and it color scheme entry that appears to influence current behavior the most is:
```
mono  indicator     reverse
```
which I believe shouldn't even apply in my color terminal? After commenting `mono` entries it all seems fine. Can't really tell if anything's broken so good enough for me.

**Comment by flatcap** [comment]
> it worked fine for both message and attachment until 3604543

Right...

I ran the old release of NeoMutt under a debugger to see exactly what was going on.
It wasn't pretty.

**Setup**:
- Config `macro pager <f5> "<pipe-entry>urlview<enter>"`

**Starting place**:
- Index, hit `<view-attachments>`
- Attachments, hit `<enter>` to `<view-attach>`
- Pager, hit `<F5>`

**Results**:
- The macro is parsed to extract `<pipe-entry>`
- This isn't recognised by the Pager menu (code: `OpPager`)
- NeoMutt decides to look for **any** menu that can understand `<pipe-entry>`
- First matching menu is for Compose (code: `OpCompose`)
- Function name is translated into `OP_PIPE`
- The opcode is returned to the Pager
- The Pager coincidentally has a function to handle `OP_PIPE` so it gets called
- Fortunately, the Pager has some special Attachment code to handle piping attachments

Let me see what I can do.

**Comment by jpalus** [comment]
Raised #3349 for color issues.

**Comment by jpalus** [comment]
The only issue that remains with be16c31 is `C-b` binding with `<pipe-entry>` however while in 20220408 it just said "key is not bound" it now behaves strange... first next message is focused and then reply is initiated so basically it now appears to mean "reply to next message in list".

**Comment by flatcap** [comment]
> The only issue that remains ... is `Ctrl-B` binding with `<pipe-entry>`

Working on it

**Comment by flatcap** [comment]
Please can you give branch [[devel/pipe]](https://github.com/neomutt/neomutt/tree/devel/pipe) a try.

Thanks

**Comment by jpalus** [comment]
> Please can you give branch [[devel/pipe]](https://github.com/neomutt/neomutt/tree/devel/pipe) a try.

With this branch all of my issues are gone. Many thanks!

**Comment by flatcap** [comment]
YAY!!!!
Many thanks.
I can make a release now :-)
