### ISSUE TITLE
Run commands before loading rc files

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#335]
When launching mutt, I find it useful to specify configuration commands to be run *before* mutt loads any rc files. This allows to set `my_*` variables that can later be used inside rc files, e.g.,

```
$ cat ~/mutt-hache-bench/muttrc
set header_cache_backend = $my_backend
set header_cache = "~/mutt-hcache-bench/hcache-$my_backend"
$ mutt -F ~/mutt-hcache-bench/muttrc -P "set my_backend=lmdb"
```
In this example, I use ` -P "set my_backend=lmdb"` to change the header cache backend.

What do people think? Would this be a useful addition?

**Comment by flatcap** [comment]
Hmm...  I see two possible alternatives: the classic solution and the NeoMutt Way<sup>tm</sup>.

The Mutt way would be to create your `prefix.rc` and include the last line `source ~/.muttrc`

The NeoMutt way is to use the new multiple config option `mutt -F prefix.rc -F ~/.muttrc`

**Comment by gahr** [comment]
The idea is not to have to modify files to change variables.. it makes it easier to script mutt sessions for benchmark / test. I'm using this to benchmark #244 .

**Comment by gahr** [comment]
@flatcap made me realize that I could achieve the same by setting environ variables. That solves the issue for me. Thanks!
