### ISSUE TITLE
HEX colours

### ISSUE THREAD

**Issue by roland-rollo** [neomutt/neomutt#3350]
Is there any chances to support hex colours by Neomutt? I know that we now have xtm256 colours palette and asking for more is probably an exaggeration, but I like to use more than actual limit is.

## What would you like to be able to do?
I'm not sure if I can do something, I don't know programming.

## Have you tried any alternative methods?

- Macros
- Hooks
- Scripts

**Comment by flatcap** [comment]
> Is there any chance to support hex colours by NeoMutt?

**Good**

Recent versions of ncurses can display RGB colours.

The new colour code is ready to accept RGB colours
It's having a few teething problems, but they'll soon be fixed.

**Bad**

Ncurses is limited to a palette of 256 colours.
That sounds bad, but you can pick which colours they are from the entire RGB spectrum.

---

This is a low-priority task and I'm really busy with other challenges.
To make this happen, we'll need to find a volunteer.
