### ISSUE TITLE
Build fails on macOS 10.15.7

### ISSUE THREAD

**Issue by nickwynja** [neomutt/neomutt#3355]
## Expected Behaviour

Successful compile.

## Actual Behaviour

Introduced with the 'new color objects' (https://github.com/neomutt/neomutt/commit/e42ba8288b87b4d17ec469594015c3a593d66434), build fails with the following errors:

```
gui/mutt_curses.c:48:3: error: unknown type name 'cchar_t'; did you mean 'wchar_t'?
  cchar_t cch = { 0 };
  ^~~~~~~
  wchar_t
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/stddef.h:74:24: note:
      'wchar_t' declared here
typedef __WCHAR_TYPE__ wchar_t;
                       ^
gui/mutt_curses.c:49:3: error: implicit declaration of function 'setcchar' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  setcchar(&cch, L" ", ac->attrs, index, NULL);
  ^
gui/mutt_curses.c:50:3: error: implicit declaration of function 'bkgrndset' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  bkgrndset(&cch);
  ^
gui/mutt_curses.c:50:3: note: did you mean 'bkgdset'?
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/curses.h:535:29: note:
      'bkgdset' declared here
extern NCURSES_EXPORT(void) bkgdset (chtype);                           /* generated */
                            ^
3 errors generated.
make: *** [gui/mutt_curses.o] Error 1
```

## Steps to Reproduce

```
./configure                                     \
     --notmuch                                  \
     --disable-doc                              \
     --lmdb                                     \
     --with-nls=/usr/local/opt/gettext          \
     --with-lmdb=/usr/local/opt/lmdb            \
&& make                                         \
&& sudo make install
```

## How often does this happen?

- Always

## When did it start to happen?

https://github.com/neomutt/neomutt/commit/e42ba8288b87b4d17ec469594015c3a593d66434

## NeoMutt Version

Building from `20220408` tag or `master`

## Extra Info

- macOS 10.15.7
- mac command line tools are up to date

**Comment by nickwynja** [comment]
I see a comment in [this discussion](https://github.com/neomutt/neomutt/discussions/3322#discussioncomment-2438169):

> As jindraj recently discovered, NeoMutt doesn't even compile against decade-old versions of ncurses.

Maybe this is what I'm running into?

**Comment by nickwynja** [comment]
@jindraj Thank you! Appreciate the mention of `brew info ncurses` since my paths were actually:

```sh
export LDFLAGS="-L/usr/local/opt/ncurses/lib"
export CPPFLAGS="-I/usr/local/opt/ncurses/include"
```

**Comment by flatcap** [comment]
**Update**:

It **is** possible to build with this version of ncurses.

Setting this environment variable before building will enable the header that contains `cchar_t`.

```sh
export EXTRA_CFLAGS='-D_XOPEN_SOURCE_EXTENDED'
```
