### ISSUE TITLE
Query: Attach file

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#336]
This bug was reported by Andrew Duchowski (on the neomutt-users mailing list).

On a Mac, I just changed from mutt to neomutt via
upgrades to macOS Sierra and macports.

In mutt, when I used to 'a'ttach a file and then
press '?' to search the list of folders, two things
happened:

1. I would see my ~/Mail foler
2. mutt would remember which dir I was in if I
   wanted to 'a'ttach again

Now, in neomutt, when I 'a'ttach a file, two
things happen:

1. I see my remote mail spoolfile (e.g., exchange)
   and now I have to press '=' to get to my local
   ~/Mail dir
2. neumutt no longer remembers where I was looking
   at for attachments, consequently I have to press
   '=' again and then descend down a possibly long
   directory branch to get to where I was just a
   second ago.

Is there a .muttrc switch to revert back to the
old functionality?

**Comment by gahr** [comment]
I'll look into this

**Comment by gahr** [comment]
I get the same behaviour with plain mutt (1.7.2). Can you please post the output of `mutt -D -S`?

**Comment by gahr** [comment]
The reason I got the same behaviour with mutt is because I have `folder` set to my imap server.

The change is due to [ae65f34]. As @flatcap suggested, we could restore the old behaviour when attaching a file - in which case is likely that one wants to browse the local filesystem, not a remote IMAP server directory tree.

**Comment by coiby** [comment]
> 2\. neumutt no longer remembers where I was looking
>     at for attachments, consequently I have to press
>     '=' again and then descend down a possibly long
>     directory branch to get to where I was just a
>     second ago.

This issue still occurs in version 20200501-1.
