### ISSUE TITLE
Double height message line on index when archiving last message from pager

### ISSUE THREAD

**Issue by nickwynja** [neomutt/neomutt#3363]
## Expected Behaviour

Message row is highlighted as per usual.

## Actual Behaviour

When on the last item, within the pager, and I archive the item with `y` (see my custom macro below), the message archives as expected but the item that is now that last item is given a double row height.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/1012017/163444032-5754fe90-e94d-4f61-92bd-982448bf491f.png">

```
macro index,pager y \
    "<enter-command>set resolve=no<enter><clear-flag>N<save-message>+Archive<enter><enter-command>set resolve=yes<enter><sync-mailbox>" \
    "move message to archive"
```

## Steps to Reproduce

1. Select the last message in the index
2. Open the message in the pager
3. Archive message using above macro

## How often does this happen?

- Only when on the last message and archiving from the pager

## When did it start to happen?

- Sometime since `20211029`

## NeoMutt Version

```
NeoMutt 20220408-13-4319dd-dirty
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 19.6.0 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libiconv: 1.11
libidn: 1.38 (compiled with 1.38)
libnotmuch: 5.2.0
storage: lmdb

Configure options: --notmuch --lmdb --with-nls=/usr/local/opt/gettext --with-lmdb=/usr/local/opt/lmdb

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -I/usr/local/opt/gettext/include -DNCURSES_WIDECHAR -I/usr/local/opt/lmdb/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme -gss 
  +hcache -homespool +idn -inotify -locales_hack -lua -mixmaster +nls +notmuch 
  -openssl +pgp +regex -sasl +smime -sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* macOS 10.15.7

**Comment by nickwynja** [comment]
This can also happen when archiving the second-to-last item.

<img width="598" alt="image" src="https://user-images.githubusercontent.com/1012017/163459284-9082fb14-bd77-4a2c-8680-41d4f83ba8cb.png">

In this case, it appears the item took up multiple lines. This height is the same amount of messages that archived before any redrawing happened.

**Comment by flatcap** [comment]
Please can you give branch [[devel/double]](https://github.com/neomutt/neomutt/tree/devel/double) a try.

Thanks

**Comment by nickwynja** [comment]
@flatcap This works! Thanks for the fix.
