### ISSUE TITLE
Unable to unbind q key in index

### ISSUE THREAD

**Issue by Ram-Z** [neomutt/neomutt#3371]
## Expected Behaviour

Trying to unbind the `q` key in index to make it slightly harder to close NeoMutt by mistake.

I suppose there's a wider "cannot 'unbind' keys using `noop`" issue, but I have not tested further.

## Actual Behaviour

Unable to unbind `q`.

## Steps to Reproduce

* Run either:
  * `neomutt -nF /dev/null -e "bind index q noop"`
  * `neomutt -nF /dev/null -e "unbind index q"`
* Press `q`
  * neomutt quits when it shouldn't
 
## How often does this happen?

- Always

## When did it start to happen?

Behaviour introduced in 6df2664e. See also https://github.com/neomutt/neomutt/pull/3316.

## NeoMutt Version

Discovered in system installed version below, but then bisected to commit listed above.

<details><summary>First bad Version</summary>

```
NeoMutt 20211029-507-6df266
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.17.3-arch1-1 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libidn: 1.38 (compiled with 1.38)

Configure options: 

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR -I/usr/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme -gss 
  -hcache -homespool +idn +inotify -locales_hack -lua -mixmaster +nls -notmuch 
  -openssl +pgp +regex -sasl +smime -sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```
</details>

<details><summary>System Version</summary>

```
NeoMutt 20220415
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.17.3-arch1-1 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.17.1
GnuTLS: 3.7.4
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, bdb, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --bdb --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/neomutt/src=/usr/src/debug -flto=auto -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme +gss 
  +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster +nls +notmuch 
  -openssl +pgp +regex +sasl +smime +sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```
</details>

**Comment by flatcap** [comment]
Ah, interesting!

There are actually two bindings of <kbd>q</kbd>: Index and Generic (the menu nobody understands).

In the old code, we bound <kbd>q</kbd> to `noop` in the Index, so <kbd>q</kbd> was recognised and did exactly nothing.
In the new code, we delete the <kbd>q</kbd> binding, so NeoMutt looks at the Generic menu and finds a <kbd>q</kbd> there (bound to `<exit>`).

**Workaround**:  As a temporary fix, you can unbind the Generic menu too:
```
neomutt -nF /dev/null -e "unbind index q" -e "unbind generic q"
```

---

To fix this we might need to kill the Generic binding and make sure the other menus that need <kbd>q</kbd> have their own copy.

**Comment by Ram-Z** [comment]
Thanks, I did not know about the Generic "menu".

Unbinding <kbd>q</kbd> from the generic "menu"  also unbinds it for all other menus in addition to the Index, including Compose, which means I can't cancel sending an email. I was really just trying to avoid quitting `neomutt` with <kbd>q</kbd>

Something like this worked though:
```
neomutt -nF /dev/null -e 'macro index q "<enter-command>echo ''Press x to quit!''<enter>"'
```

i.e. actually map <kbd>q</kbd> to some "almost noop" action.

**Comment by Ram-Z** [comment]
> To fix this we might need to kill the Generic binding and make sure the other menus that need q have their own copy.

Or prevent `<exit>` from quitting the application, there's `<quit>` for that. The generic menu can then keep the <kbd>q</kbd> binding and Index overrides this to `<quit>`.

**Comment by flatcap** [comment]
Hmm... I'm not sure about that.

At the application level:
- `<quit>` Means save and close
- `<exit>` Means close without saving changes

Generic Menu:
- <kbd>q</kbd> -> `<exit>`

Index Menu:
- <kbd>q</kbd> -> `<quit>`
- <kbd>x</kbd> -> `<exit>`

---

References:

- [`OpGeneric`](https://github.com/neomutt/neomutt/blob/main/functions.c#L281=), [`GenericDefaultBindings`](https://github.com/neomutt/neomutt/blob/main/functions.c#L926=)
- [`OpIndex`](https://github.com/neomutt/neomutt/blob/main/functions.c#L341=), [`IndexDefaultBindings`](https://github.com/neomutt/neomutt/blob/main/functions.c#L976=)
- [`OP_QUIT`](https://github.com/neomutt/neomutt/blob/main/opcodes.h#L247=)
- [`OP_EXIT`](https://github.com/neomutt/neomutt/blob/main/opcodes.h#L152=)

**Comment by Ram-Z** [comment]
Fair enough, I wasn't thinking of "saving" vs "not-saving", but rather of menu vs application, i.e. `<exit>` as "exit the current menu" and `<quit>` as "quit the application wherever we are (also save unless <kbd>%</kbd>)"
