### ISSUE TITLE
LMDB header cache not being used on a specific (huge) IMAP folder

### ISSUE THREAD

**Issue by wizeman** [neomutt/neomutt#3387]
## Expected Behaviour

I've enabled the header cache with the LMDB backend.
I was expecting the cache to be used on all of my IMAP folders.

## Actual Behaviour

This seems to work fine except for an IMAP folder of mine which has around 3.3 million emails.
In this folder, all headers are downloaded every time I open the folder, i.e., the cache seems to get written to, but not read from.

I've actually found out what was the source of the problem.

While investigating, this is what I found out:

On another folder, which has around ~300K emails, the header cache database was using ~900 MB.
On the folder with the non-working header cache, which has around ~3.3M emails (~10x bigger), I was expecting the header cache to be around ~9000 MB (also 10x bigger), but instead it had almost exactly 2048 MB.

This pointed to some kind of artificial limitation (e.g. some kind of limit in the code or the OS).

Indeed, after looking around the LMDB and Neomutt sources, I found this line of code:

https://github.com/neomutt/neomutt/blob/d19b1f8d13778df402cf99c730d7847712d89335/store/lmdb.c#L39-L41

As you can see, this is a hard-coded limitation, and apparently not enough for my beloved IMAP folder.

Note that another person has ran into a similar issue before:

https://github.com/neomutt/neomutt/issues/267

The last comment even says the following:

> Wow!
>
> Well, I'll double the size. Fortunately that won't impact other users.
> (and you can reopen this bug when you get to 1 million emails).

Unfortunately Github doesn't allow me to reopen the above bug, so I am filing this new one instead.

However, note that in issue #267, there was a visible error message, but in my case there wasn't. So in my case it was harder than necessary to find the root cause because there was no indication that anything was wrong, except for the bad performance.

I was going to suggest simply increasing this constant to a larger value (e.g. 100 GiB), however other people have had problems with the 2 GB limit before, because it was too big:

https://github.com/neomutt/neomutt/issues/473

I would guess issue #473 most likely happened because the user was running on a Raspberry Pi 2, hence he was very likely using a 32-bit CPU (or at least, a 32-bit kernel and userland even on the later versions of the RPi2 which had a 64-bit CPU), in which a 2 GB mmap() call can easily fail due to running out of virtual address space.

So I would say that this constant either should be increased (in 64-bit mode only), or it should be configurable by the user (with the appropriate warnings for the user not to set too large a limit in 32-bit mode, and not too small a limit when the folder has many emails).

**Comment by flatcap** [comment]
Wow!  That's a lot of emails.
(but I thought that last time :-)

Thanks for debugging and all the research!

From the [LMDB Docs](http://www.lmdb.tech/doc/group__mdb.html#gaa2506ec8dab3d969b0e609cd82e619e5)

> The size of the memory map is also the maximum size of the database.

and

> The value should be chosen as large as possible, to accommodate future growth of the database.

I suppose 100GiB should be enough for anyone :-)
Something like this, might do:

```c
#include <stdint.h>
#if (UINTPTR_MAX == 0xffffffff)
// 32-bit, limit to 2GiB
const size_t LMDB_DB_SIZE = 2147483648;
#elif (UINTPTR_MAX == 0xffffffffffffffff)
// 64 bit, limit to 100GiB
const size_t LMDB_DB_SIZE = 107374182400;
#else
#error
#endif
```

I'll see what the other devs think, tomorrow.

**Comment by gahr** [comment]
That sounds reasonable enough. We should probably research a bit what other users of LMDB are doing and whether there are some intrinsic limitations in lmdb or on mmap'ing such (potentially) large address spaces.
