### ISSUE TITLE
`debug_file` ignored

### ISSUE THREAD

**Issue by balejk** [neomutt/neomutt#3394]
## Expected Behaviour

Launching `neomutt -d 2` will log to `~/.config/neomutt/debug0` with `set debug_file = "~/.config/neomutt/debug"` in `neomuttrc`.

## Actual Behaviour

`neomutt` logs to `~/.neomuttdebug0`.

## Steps to Reproduce

Specify custom `debug_file` in `neomuttrc` and launch `neomutt -d 2`. Log is written to the default location.

## How often does this happen?

- Always

## NeoMutt Version

```
NeoMutt 20220415
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.15.34_1 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libidn: 1.38 (compiled with 1.38)
GPGME: 1.15.1
OpenSSL: OpenSSL 1.1.1n  15 Mar 2022
libnotmuch: 5.6.0
storage: rocksdb, gdbm, tdb
compression: zlib

Configure options: --ssl --gpgme --notmuch --gdbm --lua --sasl --zlib --tdb --rocksdb --testing

Compilation CFLAGS: -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe  -D_FILE_OFFSET_BITS=64 -DLARGEFILE_SOURCE=1 -g -fdebug-prefix-map=/builddir/neomutt-20220415=. -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.4 -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme -gss 
  +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster +nls +notmuch 
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

The `-l` switch works as expected. I'm running `neomutt` on musl based Void Linux.

**Comment by flatcap** [comment]
Thanks for the bug report.

Good find!
Setting the level (by the command line) triggers a bug that causes the log to be started.

**Comment by Spacefreak18** [comment]
is this really a bug? 

if you run neomutt with logging, and you put an unknown variable into your rc file, you will see that neomutt logs the parsing of the config file.

If this is changed there will be a chicken and egg problem, how do you log the parsing of the rc file to a file, if you don't know the file to log it to until you've parsed the rc file?

and this link says debug_file can be specified on the command line, it says nothing about the rc file.
https://neomutt.org/guide/reference#debug-file

**Comment by flatcap** [comment]
> chicken and egg problem

Not quite (if it were working correctly).

There are three ways you can affect the logging, during startup:
- Config file (either `.neomuttrc` or `-F other.rc`)
- Command line: `-d` and `-l` options
- Command line extras, e.g. `-e 'set debug_file=xyz'`

Immediately after starting NeoMutt, log messages will be sent to `stdout` (the screen).
Soon after parsing the command line, we switch the logger to 'queueing' mode.
When we finally have all the info, we open the log file and flush the queue.

The bug caused `-d NUM`, on the command line, to open the log file too early.
