### ISSUE TITLE
Macro variable for "current folder"

### ISSUE THREAD

**Issue by achilleas-k** [neomutt/neomutt#3400]
Bottom line: I want to have a macro / keybinding that can call `mbsync` on a specific folder.

I have neomutt configured with a maildir managed by isync.  A macro that starts `mbsync` on all accounts is pretty straightforward. 
 But `mbsync` also supports syncing specific folders with `mbsync channel:box`, e.g., `msbync Work:INBOX`.

The core issue is that sometimes I want to do a sequence of operations with a quick sync in between then.  This is usually a `toggle-new` or `flag-message` followed by a `save-message`.  If there's no sync between the two operations, when a sync does occur, the message will be moved but the first operation will not be performed, so the flag or read status doesn't persist.

Running a sync between the two operations fixes this, but doing a full sync of all folders can take some time.  If I had a macro that could run `mbsync` on just the current folder, I could do all the operations I needed on the messages in the current folder, run a quick sync, then move messages around knowing that the first operations have been synced to the server.

How can I set a macro to do an mbsync of the _current folder_?
Is there a variable I can put in a macro that names the current folder?

Alternatively, is there something I'm missing or am I doing something wrong that's causing my core issue?  I'm open to any solutions.

I'm also considering switching to a pure IMAP-based setup so that I can just do a `sync-mailbox` and know everything's synced to the server, but that makes everything a bit slower.

**Comment by kmarius** [comment]
You could just set up a bunch of `folder-hook`s (one for each folder) to set a variable or the whole macro.

**Comment by achilleas-k** [comment]
I considered this but that would require about 30 hooks and I would need to maintain it as I add new ones from time to time.  I suppose it's not completely unreasonable though, I was just hoping for a more automated solution.  I guess I could script it externally.

Thanks for the tip.

**Comment by kmarius** [comment]
I have moved most of my configuration to lua where this quite simple because I am already generating a list of all the mailboxes for the sidebar. Maybe that would be an option?

**Comment by achilleas-k** [comment]
> It's a reasonable request. We've had similar ideas before.

If you'd like to reopen this as a feature request, I could give it a try sometime in the next couple of months.

**Comment by flatcap** [comment]
> I could give it a try sometime

Great!

> sometime in the next couple of months

oh

> reopen this as a feature request

When you've got some free time, ping me and I'll be happy to get you started.

**Comment by achilleas-k** [comment]
> When you've got some free time, ping me and I'll be happy to get you started.

Sounds good!
