### ISSUE TITLE
Current position changes when displaying message

### ISSUE THREAD

**Issue by guiniol** [neomutt/neomutt#341]
Under some conditions (not sure which, and I received new email during my investigations which stopped the issue triggering), when displaying a message, neomutt shows the right message but think its position is on another message. This shows when going back to the index (the selected message is not the message that was being read) or when moving to the next message (the next message is not the message following the message that was being read. When this happens, the erroneous position is always the same, even when closing and reopening the message, and the message displayed when trying to show the next message is the message following the one when going back to the index.

This is with neomutt 20170128 (1.7.2), and the bug disappeared before I could try with older versions of neomutt...

**Comment by guyzmo** [comment]
next time it happens, could you try hitting <kbd>Control</kbd>-<kbd>L</kbd>? Sometimes displaying can look fishy with some 3-byte unicode characters.

**Comment by guiniol** [comment]
@guyzmo I can, but I'm pretty sure it was the position being wrong. It took me back to almost the beginning of my mailbox, always in the same place, and I had to scroll back down. Except for the position, everything looked right.

**Comment by guyzmo** [comment]
were you able to reproduce the error? And nail a way to make it reprocduceable?

**Comment by guiniol** [comment]
Not by my own volition, but it does happen once in a while. And rivarun on irc was (maybe) having the same bug.
I can attach a gdb but I'm not sure where to put a breakpoint, and I haven't had time to figure it out. I need to spend more time in the pager/index code/event loop. Simply doing `continue`s does not work as gdb complains about not knowing the scope of the function at some point (not sure of the exact message) and refuses to `continue`.

**Comment by guyzmo** [comment]
ok I'll keep those tags on as long as you're not providing a way for someone else to actually reproducing the issue.

**Comment by guiniol** [comment]
No worries. I'll try to debug it on my own too.

**Comment by gahr** [comment]
@guinol how do you mean that this happens in index-only too? I thought it was when getting back from the pager into the index. Thanks for clarifying!

**Comment by guiniol** [comment]
@gahr I'm pretty sure I've had it jump around in the index only too. I'll have to check next time it appears.

**Comment by guiniol** [comment]
btw, it's guiniol, with and `i`. You just mentionned someone else ☺

**Comment by gahr** [comment]
Sorry for that, blame it on the phone ;)

**Comment by guiniol** [comment]
@gahr no worries, just saying ^^

**Comment by dset0x** [comment]
I have been seeing the same problem as @guiniol . Note that `next-entry` jumps to #(message-that-`exit`-would-jump-to + 1), so neomutt really acts as if exiting a different message.

**Comment by dset0x** [comment]
In an inbox with 9 messages {0..8}.

* Pager on #8. `exit` jumps to #2.
* Pager on #8. `toggle-weed` jumps to #2 and toggles weeding.
* Pager on #8. `next-entry` jumps to #3.
* Pager on #8. `next-entry` jumps to #1.

Works as expected when {0..7} is in the pager.

**Comment by nobrowser** [comment]
Is this with IMAP or local store? if local, mbox or maildir?

**Comment by paretje** [comment]
I have the same issue. Some time ago I checked with what version the 
issue started. I determined the last "good" version was the one shipped 
with the 1.7.1-2 package in Debian. Although, I sometimes had the 
feeling the cursor had jumped after receiving mail, but the position in 
or after the exiting the pager was all right.

It might to be related to something in the default config shipped with 
the Debian package, as it didn't seem to happen without it (neomutt 
20170421). I'm currently checking, but kind of started to suspect it 
might be `set sort=thread`.

To answer @nobrowser's question: I use a local maildir with notmuch.

**Comment by paretje** [comment]
It seems to be related to `set sort=thread` indeed. I have used mutt the whole day, and the issue didn't occur.

**Comment by flatcap** [comment]
Upstream have made some changes to how the refreshes are done.
Does this problem still occur?

**Comment by guiniol** [comment]
I've had it a week or so ago, but that was on a release version, so I don't know if it included the mentioned changes. I'll keep an eye out.

**Comment by romanofski** [comment]
I've ran into that a lot recently and it can drive you up the wall. You're reading one message in a thread and pop you're somewhere else in the index. I'm almost certain it is a bug, but I can't correctly reproduce it for now. Maybe my observations help tho:

* I've compiled the latest HEAD 2d51490b3609c9f7c84951f66d2134bdadbfda95 with debug symbols:

      ./prepare
      ./configure --enable-debug --enable-notmuch --enable-gpgme --enable-imap --with-sasl --with-ssl --enable-smtp --enable-hcache

* I've got getmail setup, which uses IDLE to monitor my IMAP inbox and continuously delivers mails to `notmuch-deliver` via maildrop into a maildir. Operating System is Fedora 25.

* I've used gdb to watch `menu->current`, pressed either `next_undeleted` or `tag-entry` and observed the "jumping around". We're starting from mail 58 and you can see it then jumps to number 5:
````
Hardware watchpoint 2: menu->current

Old value = 58
New value = 59
0x000000000042c945 in mutt_index_menu () at curs_main.c:2270
2270            if ((menu->current = ci_next_undeleted(menu->current)) == -1)
(gdb)
Continuing.
Detaching after fork from child process 7920.

Hardware watchpoint 2: menu->current

Old value = 59
New value = -1
0x0000000000424502 in update_index (menu=menu@entry=0x1bf63a0, ctx=0x1b86bc0, check=check@entry=1,
    oldcount=60, index_hint=index_hint@entry=59) at curs_main.c:411
411       menu->current = -1;
(gdb)
Continuing.

Hardware watchpoint 2: menu->current

Old value = -1
New value = 5
update_index (menu=menu@entry=0x1bf63a0, ctx=0x1b86bc0, check=check@entry=1, oldcount=60,
    index_hint=index_hint@entry=59) at curs_main.c:427
427     }
(gdb)
Continuing.

Breakpoint 1, mutt_index_menu () at curs_main.c:2295
2295            menu->current++;
(gdb)
Continuing.

Hardware watchpoint 2: menu->current

Old value = 5
New value = 6
````
Maybe the problem can be found somewhere inside `update_index`? I try again to isolate what is changing the value and under what circumstances.

**Comment by romanofski** [comment]
I've done some more digging. I don't have a reproducer although I can reproduce it from time to time locally. It seems during the runtime the array which holds the headers get corrupted.

I don't know when this happens, but once it is corrupted, when the user goes to the next unread message `update_index` is called and on line 419 `menu->current` is set to the wrong number. Is it maybe because the function calls `mutt_sort_headers` which stuffs it up? I don't know. The header which is "wrong" looks like this:
````
{security = 0
 mime = true
 flagged = false
 tagged = false
 deleted = false
 purge = false
 quasi_deleted = false
 changed = false
 attach_del = false
 old = false
 read = true
 expired = false
 superseded = false
 replied = false
 subject_changed = true
 threaded = true
 display_subject = true
 recip_valid = true
 active = true
 trash = false
 xlabel_changed = false
 zhours = 10
 zminutes = 0
 zoccident = false
 searched = false
 matched = false
 attach_valid = false
 collapsed = false
 limited = false
 num_hidden = 1
 recipient = 0
 pair = 2098176
 date_sent = 1498621033
 received = 1498621066
 offset = 0
 lines = 0
 index = 91
 msgno = 8
 virtual = 8
 score = 0
 env = 0x16e99f0
 content = 0x16e8a90
 path = 0x16e48e0 "cur/1498621066.M562175P31610V"
 '0' <repeats 12 times>
 "FD05I000000000026B57D.khan:2,S"
 tree = 0x0
 thread = 0x16d0570
 attach_total = 0
 refno = 0
 data = 0x16e9030
 free_cb = 0x493a70 <deinit_header>
 maildir_flags = 0x0}
````

So the problem doesn't seem to occur when you just stay on the index and go to the next message. I can reproduce it in the pager by looking at an email and press next. Note the next mail is always a new mail. Furthermore I can also reproduce it by calling the header weeding, but don't know under which circumstances that happens ...

I don't know the code so I'm basically, clueless what to watch out for ...

**Comment by erbrecht** [comment]
I've got the same issue. Can't figure out how to reproduce it either. In my minimal investigation, it seems that there is not exactly a pattern to which message I land on when exiting the pager. For example:

- exiting message 10218, I end up on 9487 in the index
- exiting message 10230, I end up on 9486 in the index
- exiting message 10235, I end up on 9489 in the index
- exiting message 10238, I end up on 9496 in the index
- exiting message 10239, I end up on 9494 in the index

I was half-expecting to see it always jump by the same number, but that's not the case.

I'm on Arch, using the latest tagged release (20170714), with a local maildir store, and isync/mbsync for fetching from IMAP. This happens to me every day at some point, so if there is some specific troubleshooting I can do, I'd be glad to help.
