### ISSUE TITLE
Adding different icons, automatically display all mailboxes, creating, deleting, and renaming mailboxes.

### ISSUE THREAD

**Issue by SingularisArt** [neomutt/neomutt#3413]
How can I get my NeoMutt to look like [this](https://github.com/GideonWolfe/dots/raw/main/screenshots/neomutt.png)?

![neomutt](https://raw.githubusercontent.com/GideonWolfe/dots/main/screenshots/neomutt.png)

NOTE: I am not syncing my mail.

# Icons

How can I set different icons for different things? Like how this man does [here](https://github.com/GideonWolfe/dots/tree/main/dotfiles/config/neomutt#index).
I would like to have a certain icon for read emails, a certain icon for unread emails, etc.

# Mailboxes

## Getting all mailboxes

How can I automatically get my mailboxes from Gmail? I know I can use `mailboxes "=..."`, but how can I have NeoMutt automatically list all of those for me?

## Creating, Deleting, and Renaming mailboxes

Is it possible for NeoMutt to:
1. Create mailboxes
2. Delete mailboxes
3. Rename mailboxes

If so, does Gmail see that and modify their mailboxes?

## Adding icons and emojis in front of mailboxes like the inbox, starred, etc

For example, let's say I would like to add a star emoji in front of the starred folder. How would I go about and do that? (Just like the link above)

# Accepting google calendar invites

Is it possible for NeoMutt to accept google calendar invites, or do I have to create a different program for that? If so, how would I go about doing that?

**Comment by flatcap** [comment]
> How can I get my NeoMutt to look like this?

Damn!  That's nice!

After a quick dig around I found:
- User: @GideonWolfe.
- Dot files: https://github.com/GideonWolfe/dots/tree/main/dotfiles/config/neomutt
- Blog post: https://gideonwolfe.com/posts/workflow/neomutt/intro/

I'll have a think about your other questions when I have a bit more time.

**Comment by SingularisArt** [comment]
The thing is those dotfiles you posted don't show how he got those icons. I've got everything else except those.

**Comment by flatcap** [comment]
I can't be certain, but it might be [NerdFonts](https://www.nerdfonts.com/).
They re-package lots of useful icons into favourite fonts.

**Comment by dcpurton** [comment]
It is Nerd Fonts. You can see his urxt configuration which specifies the terminal don't in use.

**Comment by SingularisArt** [comment]
Yeah. I use the font that he uses as well.
Do you know where I can go to find out more about my other questions? I tried looking at the NeoMutt documentation, but I couldn't find anything related to my questions?

**Comment by SingularisArt** [comment]
I found the answer to the first question on how to change the icons based on what the email is.
I found [this](https://github.com/ceuk/mutt_dotfiles) repo that does exactly that.

**Comment by flatcap** [comment]
> Getting all mailboxes

Config:
```
# Ask the server for a list of subscribed folders
set imap_check_subscribed = yes
```

- https://neomutt.org/guide/reference#imap-check-subscribed

> Icons

These are the defaults; you can add icons here:

Config:
```
set crypt_chars = "SPsK "
set flag_chars = "*!DdrONon- "
set from_chars = ""
set status_chars = "-*%A"
set to_chars = " +TCFLR"
```

- https://neomutt.org/guide/reference#crypt-chars
- https://neomutt.org/guide/reference#flag-chars
- https://neomutt.org/guide/reference#from-chars
- https://neomutt.org/guide/reference#status-chars
- https://neomutt.org/guide/reference#to-chars

> Creating, Deleting, and Renaming mailboxes

This can be done from the Mailbox Browser.
From the Index, hit <kbd>c</kbd> to (`<change-folder>`), then <kbd>?</kbd> to open the browser.

The browser has two views <kbd>\<Tab\></kbd> switches between them.
The "directory" view allows you to:
- <kbd>C</kbd> - `<create-mailbox>`
- <kbd>d</kbd> - `<delete-mailbox>`
- <kbd>r</kbd> - `<rename-mailbox>`

> Adding icons and emojis in front of mailboxes

You need the `named-mailboxes` command.

Config:
```
named-mailboxes  "❤️ Neo" "+neo"
```

- https://neomutt.org/guide/configuration.html#mailboxes

I _think_ there's a way to combine these with the `imap_check_subscribed` config.

> Accepting google calendar invites

You can pipe emails or attachments to external programs.

---

That's all I know.
Perhaps someone else can fill in any gaps.

**Comment by SingularisArt** [comment]
You are a GENIUS! Thank you so MUCH!!!

**Comment by SingularisArt** [comment]
Quick question, how would I create a mapping for creating, renaming, and deleting mailboxes? I've tried `macro browser Q "<create-mailbox>" "create mailbox"`, but it just doesn't work. Any idea?

**Comment by flatcap** [comment]
That works for me, but only in the "directory" view.
I get a prompt: `Create mailbox: `

In the "mailbox" view, I get the (unhelpful) error message: `Create is only supported for IMAP mailboxes`

**Comment by SingularisArt** [comment]
What is the directory view?

**Comment by flatcap** [comment]
In the browser, you can tell which mode you're in by looking at the status bar:

- `Mailboxes [2]`
  A list of mailboxes that you've subscribed to

- `Directory [imaps://host.com/], File mask: !^\.[^.]`
  A directory view of the server (all mailboxes)

**Comment by SingularisArt** [comment]
How do I get into the directory view? (I'm sorry if I'm asking stupid questions. I just have a hard time understanding the docs.)

**Comment by flatcap** [comment]
<kbd>\<Tab\></kbd> switches between the two views of the browser.

**Comment by SingularisArt** [comment]
How can I remap it from `<Tab>` to another key? Also, could you quickly give me a brief summary of all the modes in NeoMutt?
