### ISSUE TITLE
Use <Esc> for cancelling current prompt input/operation

### ISSUE THREAD

**Issue by gerazov** [neomutt/neomutt#3426]
## What would you like to be able to do?

As a Vim user it's in my muscle memory to press the `<Esc>` key to cancel the current operation, e.g. search, operator pending mode etc.

It would be great if neomutt supports this as well, e.g. cancelling the creation of a new mail message (in the To or Subject prompts), cancelling current command input, current search input etc.

## What needs to change in NeoMutt?

Currently if I start the process of composing a new mail message, I get asked to fill out the `To:` and then a `Subject:` and then the message. If I press `<Esc>` at any time within these two prompts I get the `^[` which is equivalent to the `<Esc>`. The same is true for the Search prompt or when entering new commands.

Since typing `^[` in the prompts is not really something would find useful(?) it would be great if this just cancels the current input/operation.

**Comment by gahr** [comment]
See also #1511

**Comment by gerazov** [comment]
Thanks for the pointer :pray: 

It seems the question is a dupe (and I checked :sweat_smile:) of https://github.com/neomutt/neomutt/issues/1510

Closing ...
