### ISSUE TITLE
Configuring search to also search the To field

### ISSUE THREAD

**Issue by gerazov** [neomutt/neomutt#3427]
Simple search works for the Subject and From fields but keeps skipping the To field in messages. 

Since I've setup for my replies to be in the same folder, it would be helpful if I could search the To field as well. This is my `muttrc` setup based on [this](https://unix.stackexchange.com/questions/131529/how-can-i-configure-mutt-to-display-my-replies-within-threads):

```mutt
# store reply in current folder
folder-hook . 'set record="^"'  
```

For example if I search for `Stefan` I only get the first of these two messages and if I press `n` to go to the next match the second one is skipped:

![Screenshot_20220603_161136](https://user-images.githubusercontent.com/15214418/171871385-f2a21573-914b-4b6b-94f4-ff3e074788f5.png)

If I search for `дипломска` both messages are found.

Any help would be greatly appreciated - I was trying to find out if there are some settings to it in the Guide and the Reference but couldn't ... :sweat_smile:

**Comment by gahr** [comment]
You can use patterns to search different parts of your emails: https://neomutt.org/guide/advancedusage.html#patterns

**Comment by gerazov** [comment]
Thanks :pray: 

I guess simple search is what happens when I press `/`

Can I set it up so it also searches `To` without having to input the patterns?

**Comment by flatcap** [comment]
> I guess simple search is what happens when I press `/`

Yes

> Can I set it up so it also searches `To` without having to input the patterns?

Yes, config:

```sh
# From: OR Subject: OR To:
set simple_search = "~f %s | ~s %s | ~t %s"
```

**Comment by gerazov** [comment]
Ok great - works like a charm :love_you_gesture:

**Comment by flatcap** [comment]
> Maybe can be added to the docs?

It's already there, just not very findable:

https://neomutt.org/guide/advancedusage.html#simple-searches
https://neomutt.org/guide/reference.html#simple-search

If you'd like to contribute something clearer, you could help others :-)
