### ISSUE TITLE
Reorganize contrib

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#3431]
Our [contrib](https://github.com/neomutt/neomutt/tree/main/contrib) dir is messy. It contains outdated, unmaintained, probably unfinished one-off pieces of work (not being particularly generous here, on purpose).

This is to
* stop dumping stuff into it
* **keep** - leave the unmaintained parts alone
* **move** - elect stuff we care about to some `data` directory, to be installed in `datadir`
* **kill** - this stuff is broken / doesn't have value for us

| What  | Notes | Decision (**keep**, **move**) |
| ------------- | ------------- | -- |
| [account-command](https://github.com/neomutt/neomutt/tree/main/contrib/account-command) | New stuff, we want users to use them  | **move** |
| [colorschemes](https://github.com/neomutt/neomutt/tree/main/contrib/colorschemes) | Seem to be working | **move** |
| [hcache-bench](https://github.com/neomutt/neomutt/tree/main/contrib/hcache-bench) | @gahr wrote this, it's supposed to work, but of marginal utility to anyone else | **kill** |
| [keybase](https://github.com/neomutt/neomutt/tree/main/contrib/keybase) | upstream is [here](https://github.com/JakkinStewart/KeybaseMutt) | **kill** |
| [logo](https://github.com/neomutt/neomutt/tree/main/contrib/logo) | do we use it for the desktop entry? | **move** |
| [lua](https://github.com/neomutt/neomutt/tree/main/contrib/lua) | partial | **kill** |
| [oauth2](https://github.com/neomutt/neomutt/tree/main/contrib/oauth2) | outdated? | update and **move**? | 
| [samples](https://github.com/neomutt/neomutt/tree/main/contrib/samples) | won't dare exploring | **kill** |
| [vim-keys](https://github.com/neomutt/neomutt/tree/main/contrib/vim-keys) | people might find them useful | **keep** |
| [guix-neomutt.scm](https://github.com/neomutt/neomutt/blob/main/contrib/guix-neomutt.scm) | we don't know what it is | **kill** |
| [smime_keys](https://github.com/neomutt/neomutt/blob/main/contrib/smime_keys) | referenced in online material | **keep** |

**Comment by holmanb** [comment]
I'm moving discussion from #3444 to here.

@gahr thanks for working on this. Are you interested in any help (code or discussion) here?

I'm mostly interested in making sure helper scripts land on the fs in a state that allows use without manual decompression, which is a side effect of the current directory location under multiple distro packaging schemes.

**Comment by gahr** [comment]
Do I understand that the distros you are talking about gzip everything in docdir? I understand gzipping manual pages, but why anything else?

I don’t think I need help here, we just need to take a decision :)

**Comment by nicolasbock** [comment]
On Debian for example:

```
ubuntu@test:~$ dpkg -L neomutt | grep oauth2
/usr/share/doc/neomutt/oauth2
/usr/share/doc/neomutt/oauth2/mutt_oauth2.py.README.gz
/usr/share/doc/neomutt/oauth2/mutt_oauth2.py.gz
```

So yes, gzipping docdir affects at least Gentoo and Debian.

**Comment by nicolasbock** [comment]
And to answer your question as to why: I think the rational is that `docdir` only contains docs such as man pages, which will be gunzipped transparently via the `man` command. Example scripts should probably go elsewhere.

**Comment by gahr** [comment]
Where do those distros want docs other than man pages, e.g., html or pdf?

**Comment by flatcap** [comment]
> /usr/share/doc/neomutt/oauth2/mutt_oauth2.py.gz

Good, that settles it.
I like the data/contrib separation, but I think they should both be installed in the datadir, `/usr/share/neomutt/...`
