### ISSUE TITLE
Add more 'sponsor' options?!

### ISSUE THREAD

**Issue by angelus2014** [neomutt/neomutt#3432]
I would like to sponsor this project, but at the moment, the only way is through paypal. There is also a way through GitHub which is already something I'm using to sponsor other projects. I would suggest expanding the ways to sponsor this project.

---
With regards,

Angelo Machils

**Comment by flatcap** [comment]
Thanks for the nudge, @angelus2014, I've been meaning to get it sorted for ages.

I've created a [Sponsorship](https://neomutt.org/sponsor) page.
The NeoMutt project now accepts:
- GitHub sponsorship
- Patreon
- PayPal
- BitCoin :-)

I'll make an announcement once I've added a bit more detail to the page.
Thanks

**Comment by flatcap** [comment]
Thanks :heart:
