### ISSUE TITLE
Display BCC in the pager for sent messages

### ISSUE THREAD

**Issue by gerazov** [neomutt/neomutt#3435]
The `BCC` header doesn't get displayed in the pager for the messages I sent. Is this expected behavior and can it be configured? In the reference I've only found `bcc_write` but it doesn't seem to change things.

**Comment by gahr** [comment]
The `write_bcc` allows you to set the header in the copy saved in the `record` folder.

**Comment by gerazov** [comment]
I've tried setting this (*I corrected the question with the right name of the variable) but still no BCC header appears.

**Comment by gahr** [comment]
You could also `<edit-or-view-raw-message>` the sent message to see the raw source and double check whether the header is there.

**Comment by gerazov** [comment]
Great - it works! :partying_face: 

Apparently `bcc` is ignored by default. I ran:
```
unignore bcc
```

And there it is :+1: I'm putting Sven's draconian header weeding in my muttrc :sweat_smile: 

thanks :pray:
