### ISSUE TITLE
mutt_oauth2.py: Allow .muttrc to configure oauth

### ISSUE THREAD

**Issue by holmanb** [neomutt/neomutt#3441]
## What would you like to be able to do?
I'm kicking the tires with [mutt_oauth2.py](https://github.com/neomutt/neomutt/blob/main/contrib/oauth2/mutt_oauth2.py), and I see the [instructions](https://github.com/neomutt/neomutt/blob/34dc388b40666eb4d0db66596455330fc2664512/contrib/oauth2/mutt_oauth2.py#L47) require [modifying the script](https://github.com/neomutt/neomutt/blob/34dc388b40666eb4d0db66596455330fc2664512/contrib/oauth2/mutt_oauth2.py#L61) for to make it usable. The option to make use of this script without manually editing would be nice, that way the users can pass args via the command in their `.muttrc`.

## What needs to change in NeoMutt?

I assume arg parsing can be written that does optional override of a default value in case users who use the existing method would prefer to continue doing so.

It should be a trivial addition. Basically the intention is that `--encryption-pipe` and `--decryption-pipe` be added, where each takes a variable length list of strings (or a single string per arg if it is really preferred that way).

Any objections? I can propose a patch myself unless someone else would rather do it.

**Comment by flatcap** [comment]
> I'm kicking the tires with mutt_oauth2.py

Thanks, somebody needs to :-)

> instructions require modifying the script to make it usable
> `--encryption-pipe` and `--decryption-pipe` be added

Yes please.

I don't _really_ understand how oauth2 fits into NeoMutt,
so if you've any other suggestions for better integration, I'd love hear them.

Thanks

**Comment by holmanb** [comment]
Completed
