### ISSUE TITLE
commit 34dc388 causes massive increase in startup time

### ISSUE THREAD

**Issue by aabacchus** [neomutt/neomutt#3445]
Please see the discussion in https://github.com/neomutt/neomutt/issues/3410#issuecomment-1163625445 and https://github.com/neomutt/neomutt/issues/3410#issuecomment-1163636961.

Commit: 34dc388b40666eb4d0db66596455330fc2664512

**Comment by flatcap** [comment]
Hmm.. `ps` shows
```sh
# Before the change
 711228 mutt        20   0 20.4T 35336 22596 S   0.0  0.4  0:00.04 ./neomutt -n -F a2
# After
 711167 mutt        20   0 20.4T  372M 22772 S   0.0  4.8  0:01.34 ./neomutt -n -F a2
```

Memory usage has leapt from 35MiB to 372MiB.  \*\*\*\*!

**Comment by flatcap** [comment]
Please can you give branch [[devel/buffer]](https://github.com/neomutt/neomutt/tree/devel/buffer) a try.
It seems to fix the problem.  I'll have a closer look in the morning.

Thanks

**Comment by aabacchus** [comment]
For me the increase in memory usage is more like 3.2x, but 2b9bee7fc854c8db2aa9465322b9ada57eb869f5 seems to have fixed the slowdown. I noticed a very slight slowdown even without ASAN; I suspect the ASAN interceptor alloc functions are significantly slower than the libc ones, so the effect was more emphasised.
