### ISSUE TITLE
Invalid charset being detected when composing e-mails

### ISSUE THREAD

**Issue by antekone** [neomutt/neomutt#3454]
## Expected Behaviour

NeoMutt should respect the `send_charset` (together other `*_charset` settings).

## Actual Behaviour

NeoMutt sometimes uses "us-ascii" charset even if the `send_charset` setting is set to only "UTF-8".

## Steps to Reproduce

  1. Create a `/tmp/testconfig` file with a minimal NeoMutt config:
  
```
    set charset="utf-8"
    set send_charset="utf-8"
    set assumed_charset="utf-8"
    set attach_charset="utf-8"
```
  
  2. Launch NeoMutt in compose mode:
  
    $ neomutt -F /tmp/testconfig test@test.com

  3. Use subject "test",
  4. Write "test" as the message body,
  5. Detected charset of the message is "text/plain, 7bit, us-ascii". Shouldn't it be UTF-8, despite the fact that I haven't used any UTF-8-specific characters?

  6. Checkout git commit 36b8da34df (last "good" commit),
  7. Repeat steps 1-5
  8. Detected charset is "text/plain, 7bit, utf-8", which is what I would expect.

I've made a short video demonstrating the issue: https://www.youtube.com/watch?v=LsrwuXpfpEY

## How often does this happen?

- Always

## When did it start to happen?

- Since commit f341587c29.

## NeoMutt Version

All NeoMutts including and after f341587c29 seem to be affected.

```
NeoMutt 20220429-52-36b8da
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.15.0-40-generic (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libidn: 1.38 (compiled with 1.38)
GPGME: 1.16.0-unknown
GnuTLS: 3.7.3
libnotmuch: 5.6.0
storage: tokyocabinet

Configure options: --prefix=/home/antek/bin/neomutt --enable-notmuch --enable-lua --with-lua=/usr --with-notmuch=/usr --gpgme --tokyocabinet --sqlite --autocrypt --mixmaster --idn --gnutls --with-ui

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.4 -I/usr/include -I/home/antek/bin/neomutt/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme -gss 
  +hcache -homespool +idn +inotify -locales_hack +lua +mixmaster +nls +notmuch 
  -openssl +pgp +regex -sasl +smime +sqlite +sun_attachment 

MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/home/antek/bin/neomutt/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/home/antek/bin/neomutt/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version

Ubuntu 22.04

* Were you using multiple copies of NeoMutt at once?

No

* Were you using 'screen' or 'tmux'?

Nope

* Is your email local (maildir) or remote (IMAP)?

Maildir

```
$ locale                     
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=pl_PL.UTF-8
LC_TIME=pl_PL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pl_PL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pl_PL.UTF-8
LC_NAME=pl_PL.UTF-8
LC_ADDRESS=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_MEASUREMENT=pl_PL.UTF-8
LC_IDENTIFICATION=pl_PL.UTF-8
LC_ALL=
```

**Comment by gahr** [comment]
Code smell over at https://github.com/neomutt/neomutt/commit/f341587c29207d7f069e52b4f88c4c307b41e5ac#diff-40d37604343a18848b93c7374f048c8cd627b21727d1d3a60b410304fe99fb78L231-R233

**Comment by flatcap** [comment]
Agreed.  I seem to have put in some debugging code, but not removed it.

Please can you give branch [[devel/charset]](https://github.com/neomutt/neomutt/tree/devel/charset) a try.

Thanks

**Comment by antekone** [comment]
Wasn't expecting such speed :)

e5909b754 (HEAD) -- works
9b6a0e4e5 -- doesn't work

So the change e5909b754^ e5909b754 indeed seems to fix the issue!

Thanks!
