### ISSUE TITLE
Allow setting indent_string to default (including a space) with text_flowed

### ISSUE THREAD

**Issue by flergbarn** [neomutt/neomutt#3457]
## What would you like to be able to do?

Use "> " instead of the default ">" as the `indent_string` when composing format=flowed emails. The `indent_string` documentation mentions this being disabled _"because the quoting mechanism is strictly defined for format=flowed."_, but [RFC3676](https://datatracker.ietf.org/doc/html/rfc3676#section-4.5) seems to suggest that both indents with and without a space are equivalent, unless I am misreading?

This would help with the auto-formatting of quote depth when reading neomutt-originated emails that use format=flowed in clients like gmail (and general readability of quoted text).

**Comment by gahr** [comment]
I think you are reading that wrong. The space you're seeing after `>` is caused by space stuffing, see section 4.4 of that same RFC. A quote string of `> ` would mean that a quoted-quoted paragraph would start with `> > `, which is invalid.

**Comment by flergbarn** [comment]
I don't think I'm reading the RFC incorrectly in terms of explicitly allowing a space between the indent character and the line content (and treating the content of that line identically as a line without the space), but now that you point it out I see the obvious issue with having the `indent_string` set to `> ` for a quote depth of more than one, as that would treat all the quote levels beyond the most recent one as space-stuffed.

That said, I still think it would be nice to have an option by which a single space between the `>` and content of the line could be preserved for readability while additional quote depth would omit the extra space to remain compatible with format=flowed. So the initially quoted text would look like this:

`> Line of quoted text`

And subsequent quote depth for this line like this:

`>> Line of quoted text`

I understand that this might be outside the scope of neomutt's quote indent functionality and instead more easily relegated to the external editor.

**Comment by gahr** [comment]
Yes, you can end up having a number of `>` followed by a space, but that's the result of space-stuffing, not of having `> ` as a quote character. What we could have is a choice to *always* space-stuff lines. Does this diff achieve what you want?

```diff
diff --git a/rfc3676.c b/rfc3676.c
index 7855279e6..c4c2c961c 100644
--- a/rfc3676.c
+++ b/rfc3676.c
@@ -439,7 +439,7 @@ static void rfc3676_space_stuff(const char *filename, bool unstuff)
     }
     else
     {
-      if ((buf[0] == ' ') || mutt_str_startswith(buf, "From "))
+      if (true || (buf[0] == ' ') || mutt_str_startswith(buf, "From "))
         fputc(' ', fp_out);
       fputs(buf, fp_out);
     }
```

**Comment by flergbarn** [comment]
Thanks for this. It seems that it would be, but I was unable to compile successfully on MacOS. Finally I decided on an alternative approach using a vim autocommand to achieve the same effect, and I admit this is probably the better solution.
