### ISSUE TITLE
IMAP: mailbox closed

### ISSUE THREAD

**Issue by rr-** [neomutt/neomutt#346]
I am enthusiastic to see an actively maintained fork of mutt.
Unfortunately the ages old issue with random closing of IMAP mailboxes is still present here.

http://mutt-users.mutt.narkive.com/gy14Cvl9/mailbox-closed-mutt-behaviour

Can neomutt be configured to connect every n minutes and during mailbox syncing (`$`) rather than maintaining active connection at all times that gets randomly killed?

**Comment by guyzmo** [comment]
hm… wouldn't it be possible to check if the connection is still alive, and if it's not respawn it, before doing any action using the socket? Having the socket opened allows for a more seamless "instantaneous" behaviour, you get mail as soon as it's available, and I guess mutt+IMAP users like it (I'm not using the feature).

**Comment by rr-** [comment]
Reconnecting of course would be great as well :+1:

**Comment by rr-** [comment]
I can confirm it works but after relogging, the mails in the inbox are gone and it shows empty list.
