### ISSUE TITLE
list-unsubscribe ignores reverse_name

### ISSUE THREAD

**Issue by KenMacD** [neomutt/neomutt#3461]
## Expected Behaviour

I am attempting to use the `list-unsubscribe` function to unsubscribe from company spam emails. These emails do have a proper 'To:' header. If I use 'reply' the `From:` header of the reply is set correctly. I would expect that same for `list-unsubscribe`.

## Actual Behaviour

Instead the default `from` set in my configuration is used.

## Steps to Reproduce

* Open an email with a List-Unsubscribe header
* `:exec list-unsubscribe`
* look at resulting email

## NeoMutt Version

20220429

## Extra Info

* Is your email local (maildir) or remote (IMAP)? maildir

**Comment by mjsir911** [comment]
This bit me too!

**Comment by gahr** [comment]
Thanks, let me have a look.
