### ISSUE TITLE
multiple timeout-hooks cause crash

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#347]
This minimal config file causes mutt to crash.
**crash.rc**
```
timeout-hook 'exec beep'
timeout-hook 'exec previous-undeleted'
```

Steps to reproduce:
- start mutt
- source crash.rc
- wait for timeout

Reproducable?
- Always

**Comment by guiniol** [comment]
I'll check it out, it's probably my fault from when I removed the first arg of timeout-hook
