### ISSUE TITLE
Cannot set multiple recipients when composing email

### ISSUE THREAD

**Issue by hsanson** [neomutt/neomutt#3473]
## Expected Behaviour

I am trying to add multiple recipients into the To:, Cc:, or Bcc: by selecting email addresses from my addressbook. I expect to get all selected addresses to stay in the To:, Cc:, or Bcc: separated by commas.

## Actual Behaviour

When trying to set multiple recipients in  To:, Cc:, or Bcc:  using addressbook autocompletion the last selected email replaces all other entries. 

## Steps to Reproduce

1. Compose or reply an email.
2. Have addressbook configured (e.g. query_command).
3. Type beginning of an email or name followed by tab.
4. Select email from list.
5. Type "," followed by another email or name followed by tab.
6. Select another email from list.
7. See that the last selecter email replaces the previous one instead of leaving both separated by comma.

## How often does this happen?

- Always

## When did it start to happen?

Doing git bisect I found the issue started in the following commit:

```diff
5b865cbcd83e9499ad8f2b1f7006dce1a466419 is the first bad commit
commit d5b865cbcd83e9499ad8f2b1f7006dce1a466419
Author: Richard Russon <rich@flatcap.org>
Date:   Sat Jun 4 14:57:40 2022 +0100

    fix message window leaks

    Stop leaking my new message windows and their data.

 enter/window.c    | 20 ++++++--------------
 progress/window.c |  1 +
 2 files changed, 7 insertions(+), 14 deletions(-)
```

## NeoMutt Version

```
NeoMutt 20220429-114-d5b865
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.13.0-52-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.16.0-unknown
OpenSSL: OpenSSL 1.1.1f  31 Mar 2020
libnotmuch: 5.2.0
storage: lmdb
compression: zstd

Configure options: --prefix=/usr --notmuch --lmdb --ssl --sasl --gpgme --zstd --fmemopen

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

コンパイル時オプション:
  -autocrypt +fcntl -flock +fmemopen +futimens +getaddrinfo -gnutls +gpgme -gss
  +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster +nls +notmuch
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

I use khard as addressbook:

```
set query_command ="khard email --parsable -d formatted_name %"
```

**Comment by flatcap** [comment]
argh!
sorry, that's a known problem (to me).
I'm busy trying to refactor the text entry to break up the deps, see #3305
I'll move this up the priority list.

**Comment by flatcap** [comment]
Please can you give branch [[devel/address]](https://github.com/neomutt/neomutt/tree/devel/address) a try.

Thanks

**Comment by hsanson** [comment]
Seems to be working fine. Thanks.

I will continue using this branch for the rest of the week to see if I detect any issues.
