### ISSUE TITLE
set text_flowed with set fo+=w in Vim doesn't (always?) work

### ISSUE THREAD

**Issue by angelus2014** [neomutt/neomutt#3496]
Hello,

For some time I'm using Neomutt for my e-mail and I've set `set text_flowed` in Neomutt and `set fo+=w` in Vim. After testing this a couple of times, I assumed that it was always working, but it isn't. Most (all?) of the times the setting in Vim is ignored and the resulting e-mail has hard returns at the end of every line. If I enter `:set fo+=w` inside Vim (when opened from Neomutt), then it always works. I'm not even sure if this is a Neomutt or Vim issue tbh.

Result of `:set fo?`
From Vim (started on it's own): tcq
From Vim (started from within Neomutt): tcql
From Vim (started from within Neomutt and manually setting `set fo+=w`): tcqlw

Am I missing a setting? What is the best way to avoid creating an e-mail with hard returns (which makes it look very ugly to read on the receiving end)?

Thank you in advance!

---
With regards,

Angelo Machils

**Comment by gahr** [comment]
What's in your `editor` variable? I have something like `vim -c 'setlocal textwidth=70 colorcolumn=75 ft=mail fo+=aw listchars=tab:→\\ ,trail:↓ list'`.

**Comment by angelus2014** [comment]
@gahr Thank you! In my variable, it just said 'vim'. With your tip is works fine now! :)


---
With regards,

Angelo Machils

**Comment by chrisbra** [comment]
instead of using long `-c` arguments, you should rather make use of Vim Filetype plugins :)

**Comment by gahr** [comment]
I also noticed that if I only `set editor=vim`, vim recognizes a filetype=mail, even when composing an email from scratch in an empty buffer. I don't know how it figures that.

**Comment by chrisbra** [comment]
It does so from the temp file name: 

https://github.com/vim/vim/blob/master/runtime/filetype.vim#L1100-L1101

BTW: I have documented this in the past briefly here: https://www.256bit.org/~chrisbra/cms/vim_as_e-mail_editor.html

**Comment by gahr** [comment]
That's the thing I was looking for and couldn't find. I thought we were shipping it, but it's upstream. Thanks!

**Comment by tjex** [comment]
There's a succinct write up of this here that I found: https://incenp.org/notes/2020/format-flowed-neomutt-vim.html
