### ISSUE TITLE
sasl license issue - package to be removed from Debian

### ISSUE THREAD

**Issue by aradici** [neomutt/neomutt#3514]
Currently neomutt depends on libsasl2-2 which is licensed under CMU's BSD-4 clause (and it also has an advertisement clause in place); this issue will cause neomutt to be removed from Debian on Sep 10th 2022.

See https://bugs.debian.org/1000482

We had the same issue with mutt, but eventually upstream supported gsasl and I switched to that, which removed the cyrus-sasl dependency.

Could you please have a look at the bug and determine what's the best solution for neomutt?
Do you think having gsasl support is feasible?

Thanks!

**Comment by gahr** [comment]
My personal opinion:

The dependency on SASL is optional, you can disable it at configure time (`./configure —without-sasl`). This is perhaps the simpler short term solution.

I think we’d be happy to accept patches to support using gsasl as a backend, but I don’t see us considering it a priority soon.

**Comment by aradici** [comment]
Thanks for the quick response, I've now removed SASL support from the Debian neomutt

**Comment by 4nd3r** [comment]
> I've now removed SASL support from the Debian neomutt

And with this you broke NeoMutt in Debian Sid for everyone who depend on SASL.
Meanwhile `mutt` already uses gsasl.
Just sayin'

**Comment by gahr** [comment]
> Meanwhile `mutt` already uses gsasl. Just sayin'

Thanks for pointing that out. This should make it easier to backport https://gitlab.com/muttmua/mutt/-/commit/68caf9140c8217ecf6c848460c4b4d27996b2922 into NeoMutt. Any takers?

**Comment by mschilli87** [comment]
@gahr: That information was already provided by @aradici in the initial post:
> We had the same issue with mutt, but eventually upstream supported gsasl and I switched to that, which removed the cyrus-sasl dependency.

**Comment by gahr** [comment]
missed that, thanks.

**Comment by flatcap** [comment]
> Meanwhile `mutt` already uses gsasl. Just sayin'

Yeah, it's new and not well tested.

> This should make it easier to backport

I've merged the upstream GNU SASL support.
The code looks OK and compiles, but I don't have anything to test it against.

If you have a mail server with SASL support, please can you give it a try.
Thanks :heart:
