### ISSUE TITLE
Switching between mailboxes is slow 

### ISSUE THREAD

**Issue by 4nd3r** [neomutt/neomutt#3517]
## Expected Behaviour

Switching between mailboxes is fast, almost instantaneous (with caching).

## Actual Behaviour

Switching between mailboxes is slow.
Displays `Sorting mailbox...` in the bottom very long time (~2 seconds).
Doesn't matter how many mails in mailbox, slow with 5 and 1000.
Happens with IMAP mailboxes and local mboxes.

## Steps to Reproduce

Open NeoMutt and switch between mailboxes.

## How often does this happen?

Always.

## When did it start to happen?

When I upgraded to [20220415](https://github.com/neomutt/neomutt/releases/tag/20220415) (yes, I finally decided to report it).

Something in 6bad3733ee2d59d04db522d396e4b999b28a2811 (#3344) changed how mailboxes are opened. I'm not using `-Z` flag.

## NeoMutt Version

```
NeoMutt 20220429-178-3b62e6
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.19.0-1-amd64 (x86_64)
ncurses: ncurses 6.3.20220423 (compiled with 6.3.20220423)
libidn: 1.41 (compiled with 1.41)
GPGME: 1.17.1
GnuTLS: 3.7.7
storage: lmdb
compression: zstd

Configure options: --prefix=/usr/local --disable-doc --disable-nls --gnutls --gpgme --lmdb --sasl --zstd

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme -gss 
  +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster -nls -notmuch 
  -openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"
```

## Extra Info

* Operating System and its version: Debian Sid
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? Both

**Comment by gahr** [comment]
Can you repro it with an empty config file? Can you tell what part of the config file is triggering it? Any heavy folder-hook or something?

**Comment by 4nd3r** [comment]
I think I found culprit.

```
mailboxes `echo ~/Documents/mail/*`
```

In that folder I have 32 read-only mboxes.

**Comment by gahr** [comment]
I can reproduce this with a bunch of mboxes with ~1k messages each

**Comment by gahr** [comment]
Oh, I didn't introduce that in https://github.com/neomutt/neomutt/commit/6bad3733ee2d59d04db522d396e4b999b28a2811. @4nd3r are you sure this is the bad commit?

**Comment by gahr** [comment]
I double checked: both reverting my commit and the above change fixes the issue.. I'm looking into this.

**Comment by 4nd3r** [comment]
> are you sure this is the bad commit?

This is what I got with bisecting.

**Comment by gahr** [comment]
> > are you sure this is the bad commit?
> 
> This is what I got with bisecting.

Thanks, I confirmed that. I have a fix on the [devel/issue-3517](https://github.com/neomutt/neomutt/tree/devel/issue-3517) branch, if you want to give it a go!

**Comment by 4nd3r** [comment]
> I have a fix on the [devel/issue-3517](https://github.com/neomutt/neomutt/tree/devel/issue-3517) branch, if you want to give it a go!

Tested. Works. Thank you.
