### ISSUE TITLE
configure test for db_env_create fails

### ISSUE THREAD

**Issue by nikicoon** [neomutt/neomutt#3525]
## Expected Behaviour

I'm trying to build neomutt 20220429 in pkgsrc on NetBSD with bdb 4 (actually trying to fix the bdb option for the package).
db.h is picked up, but the test for db_env_create fails:
```
ld: /tmp//ccDkYIYE.o: in function `main':
conftest__.c:(.text.startup+0x5): undefined reference to `db_env_create'
child process exited abnormally
============
The failed code was:
extern void db_env_create(void);
int main(void) {
db_env_create();
return 0;
}
============
Failed: gcc -O2 -fPIC -D_FORTIFY_SOURCE=2 -I/usr/include/krb5 -I/usr/include -I/usr/pkg/include -D_XOPEN_SOURCE_EXTENDED=1 -I/usr/pkg/include/ncurses -I/usr/pkg/include/db4 -I/usr/pkg/include/glib-2.0 -I/usr/pkg/include/gio-unix-2.0 -I/usr/pkg/lib/glib-2.0/include -I/usr/pkg/include/lua-5.4 -I/usr/include/readline -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR -Wl,-zrelro -L/usr/lib -Wl,-R/usr/lib -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -std=c99 -O2 -fPIC -D_FORTIFY_SOURCE=2 -I/usr/include/krb5 -I/usr/include -I/usr/pkg/include -D_XOPEN_SOURCE_EXTENDED=1 -I/usr/pkg/include/ncurses -I/usr/pkg/include/db4 -I/usr/pkg/include/glib-2.0 -I/usr/pkg/include/gio-unix-2.0 -I/usr/pkg/lib/glib-2.0/include -I/usr/pkg/include/lua-5.4 -I/usr/include/readline -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/pkg/include/db4 -I/include conftest__.c -o conftest__ -ldb-4.8 -L/lib -L/usr/pkg/lib/db4 -lidn -lssl -lcrypto -lncursesw -lnotmuch -llua5.4 -lsasl2 -lgpgme -L/usr/pkg/lib -lgpgme -Wl,-R/usr/pkg/lib -lassuan -lgpg-error -L/usr/pkg/lib -lgpg-error -lintl -liconv
ld: cannot find -ldb-4.8
child process exited abnormally
============
The failed code was:
extern void db_env_create(void);
int main(void) {
db_env_create();
return 0;
}
============
```

which results in a build with only bdb failing at configure time:
```
Checking for BerkeleyDB in /usr/pkg/include/...no
Checking for BerkeleyDB in /usr/pkg/include/db-5-3...no
Checking for BerkeleyDB in /usr/pkg/include/db53...no
Checking for BerkeleyDB in /usr/pkg/include/db5.3...no
Checking for BerkeleyDB in /usr/pkg/include/db-5...no
Checking for BerkeleyDB in /usr/pkg/include/db5...no
Checking for BerkeleyDB in /usr/pkg/include/...no
Checking for BerkeleyDB in /usr/pkg/include/db-6-2...no
Checking for BerkeleyDB in /usr/pkg/include/db62...no
Checking for BerkeleyDB in /usr/pkg/include/db6.2...no
Checking for BerkeleyDB in /usr/pkg/include/db-6...no
Checking for BerkeleyDB in /usr/pkg/include/db6...no
Checking for BerkeleyDB in /usr/pkg/include/...no
Checking for BerkeleyDB in /usr/pkg/include/db-4-8...no
Checking for BerkeleyDB in /usr/pkg/include/db48...no
Checking for BerkeleyDB in /usr/pkg/include/db4.8...no
Checking for BerkeleyDB in /usr/pkg/include/db-4...no
Checking for BerkeleyDB in /usr/pkg/include/db4...yes
Checking for db.h...ok
Checking libs for db_env_create...no
no
Error: Unable to find BerkeleyDB
Try: 'configure --help' for options
*** Error code 1

Stop.
```

## How often does this happen?

- Always

I can provide more details. So far it seems to me as if the bdb piece of our package's Makefile has some old autoconfigure parts left over, the part about BDB_ :
```
### Header cache
###
.if !empty(PKG_OPTIONS:Mtokyocabinet)
.include "../../databases/tokyocabinet/buildlink3.mk"
CONFIGURE_ARGS+=        --tokyocabinet
CONFIGURE_ARGS+=        --disable-gdbm
CONFIGURE_ARGS+=        --disable-bdb
.else
BDB_ACCEPTED=           db4 db5
BUILDLINK_TRANSFORM+=   l:db:${BDB_TYPE}
.include "../../mk/bdb.buildlink3.mk"
CONFIGURE_ARGS+=        --bdb
CONFIGURE_ARGS+=        --disable-gdbm
# BDB_INCLUDE_DIR_ and BDB_LIB_DIR don't have to be particularly accurate
# since the real -I and -L flags are added by buildlink already.
CONFIGURE_ENV+=         BDB_INCLUDE_DIR=${BDBBASE}/include
CONFIGURE_ENV+=         BDB_LIB_DIR=${BDBBASE}/lib
CONFIGURE_ENV+=         BDB_LIB=${BDB_LIBS:S/^-l//:M*:Q}
.endif
```

**Comment by flatcap** [comment]
Hmm...
I've just checked our source and that function has been in use since the header cache was invented (in 2005).
I don't know how old BDB v4 is, but I suspect it must be too old.
(I'm current using v5.3.28 on Fedora Linux)

However, there are plenty of alternatives...
There are three modern databases that are faster:
- LMDB (which we recommend)
- RocksDB
- TDB (Trivial Database)

Hope that helps

**Comment by nikicoon** [comment]
Sorry, I forgot to add: the function exists. I just do not understand why this is not being picked up by the linker in the test (with db4-4.8.30).

**Comment by flatcap** [comment]
Your `config.log` shows:

> ld: cannot find -ldb-4.8

If `configure` can't find them, adding `--with-bdb=path` might help (Location of BerkeleyDB)

--

In `auto.def` we do our best to find what the libraries are called and where they live:

https://github.com/neomutt/neomutt/blob/9120e744af1e7289680411072f9dcc9e52e9da9e/auto.def#L942-L953

**Comment by nikicoon** [comment]
But the config.log also says:

Checking for BerkeleyDB in /usr/pkg/include/db4...yes
Checking for db.h...ok
Checking libs for db_env_create...no

which means it only fails at the test for the function, it does find db in general. I'll see what can be changed about this to pick this up.

**Comment by gahr** [comment]
We try our best to locate the directories, but we assume the library is called `db-$maj.$min`
https://github.com/neomutt/neomutt/blob/9120e744af1e7289680411072f9dcc9e52e9da9e/auto.def#L959

I don't see that here, although I see its libtool cousin `libdb4-4.8.la`.
https://github.com/NetBSD/pkgsrc/blob/ae3cc00e6d3c4ba4f292713b4dcfa39db6a4a453/databases/db4/PLIST#L17-L24

**Comment by nikicoon** [comment]
> Also, please note that for db5, NetBSD _does_ provide the library in the form we expect it: https://github.com/NetBSD/pkgsrc/blob/ae3cc00e6d3c4ba4f292713b4dcfa39db6a4a453/databases/db5/PLIST#L20

Thanks. I think it makes more sense to support db5 in the package, I'll see what others have to say about this.

**Comment by gahr** [comment]
> > Also, please note that for db5, NetBSD _does_ provide the library in the form we expect it: https://github.com/NetBSD/pkgsrc/blob/ae3cc00e6d3c4ba4f292713b4dcfa39db6a4a453/databases/db5/PLIST#L20
> 
> Thanks. I think it makes more sense to support db5 in the package, I'll see what others have to say about this. However, the issue persists with db5. I'll see if I can provide more information.

This was an error from my side. I expect you to have the same issues with db5. On the other hand, I might have a fix on [devel/issue-3525](https://github.com/neomutt/neomutt/tree/devel/issue-3525), can you please give it a try?

**Comment by nikicoon** [comment]
I've backported this to the last release, and it addresses something which wasn't an issue, the error message stays the same (for both 4.8 and 5.3).

**Comment by gahr** [comment]
@nikicoon can you please give it another go?

**Comment by nikicoon** [comment]
Checking for db.h...ok                                                                                                                                                                         
Checking libs for db_env_create...-ldb4-4.8 

this worked, thanks!

(now the build fails with:
gmake: *** No rule to make target 'all-data', needed by 'all'.  Stop.
gmake: *** Waiting for unfinished jobs....

but I am pretty sure this is due to my incomplete cherry-picking for the configure phase from master to latest release.

**Comment by gahr** [comment]
> (now the build fails with: gmake: *** No rule to make target 'all-data', needed by 'all'. Stop. gmake: *** Waiting for unfinished jobs....
> 
> but this is due to my incomplete cherry-picking for the configure phase from master to latest release.

yes, this is most likely due to #3433
