### ISSUE TITLE
Mbox file can't be read by neomutt while mutt is able to

### ISSUE THREAD

**Issue by Porkepix** [neomutt/neomutt#3539]
## Expected Behaviour

Read an mbox file extracted from Google Mail

## Actual Behaviour

Neomutt seems to not be able to read anything from it

## Steps to Reproduce

`neomutt -R -f /my_mbox_file`

## How often does this happen?

- Always

## When did it start to happen?

First time I install neomutt, I wanted to give a try to terminal client, especially to browse that mbox file.

## NeoMutt Version

```
NeoMutt 20220429
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.19.12-arch1-1 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libidn2: 2.3.3 (compiled with 2.3.2)
GPGME: 1.17.1
GnuTLS: 3.7.4
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, bdb, lmdb
compression: lz4, zlib, zstd
```

## Extra Info

* ArchLinux
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* It writes it contains 0 messages but reads the size of the file correctly: `[Msgs:0 1459M]`
* Mutt can correctly read the exact same file and display advancement while reading it. I also believe it spends more time opening the file and displaying the loading at the bottom.

**Comment by flatcap** [comment]
Hmm...
I've just given this a test with gmail and I see the problem.

Gmail isn't saving the emails in mbox format -- that would require them to start with a `From ` header.
They're in maildir format.

If you create a maildir mailbox, e.g. `mkdir -p mail/cur mail/new mail/tmp`
then put the downloads in the `mail/cur` directory, neomutt will be happy to read them: `neomutt -f mail`

I gave upstream mutt a try.
I don't know which version you have, but the latest, like neomutt, refuses to open the file.

Hope this helps

**Comment by flatcap** [comment]
Hmm...
When I "Download message", the email gets saved with a `.eml` suffix.
This is from the `...` menu when reading the email.
(There doesn't seem to be a way to save multiple emails from the index)

Please could you download an email you don't mind being public, e.g. a mailing list, or spam (scrubbing any personal info)
and attach it to this issue (you may need to rename it to `.txt`).

Thanks

**Comment by Porkepix** [comment]
> Hmm... When I "Download message", the email gets saved with a `.eml` suffix. This is from the `...` menu when reading the email. (There doesn't seem to be a way to save multiple emails from the index)

It's from Google Takeout, where you export a whole account in an archive. Regarding the emails, it exports a `.mbox`, here a 1.5GB file.

> Please could you download an email you don't mind being public, e.g. a mailing list, or spam (scrubbing any personal info) and attach it to this issue (you may need to rename it to `.txt`).

No because it's not the way I did (see above), and also because that's from a previous job so I don't have access to the email account anymore.

**Comment by flatcap** [comment]
OK.  I've used 'takeout' to export some emails into mbox format and now I can repeat the problem.

The mbox has `From ` lines of the format:
```
From example@example.com Mon Oct 10 11:18:22 +0000 2022
```
but NeoMutt's strict parser is expecting the format:
```
From example@example.com Mon Oct 10 11:18:22 2022
```
without the `+0000` timezone info.

That's something we can fix :-)

Thanks for your help.

**Comment by flatcap** [comment]
@gahr
This line in `PREX_MBOX_FROM_LAX` doesn't match Gmail's mbox format.
https://github.com/neomutt/neomutt/blob/b6c591a227aeea64ea0f30fd8cfbb396e5992f90/mutt/prex.c#L256

Changing it to either:
```c
"([+]?[[:alnum:] ]*)"     // Timezone (which we skip)
"([^[:space:]]*)"         // Timezone (which we skip)
```

works.  Any thoughts?

**Comment by gahr** [comment]
Thanks, I went for a slightly more explicit approach of trying to match either TZ style in #3540 :)
