### ISSUE TITLE
mutt_oauth2.py: broken on updating token

### ISSUE THREAD

**Issue by motorto** [neomutt/neomutt#3550]
Trying to update the token that I got from mutt_oauth2.py fails.

## Expected Behaviour

Token should be updated

## Actual Behaviour

It fails on a Google, and Microsoft account.

```
mutt_oauth2.py $XDG_CONFIG_HOME/neomutt/accounts/gmail.tokens
Traceback (most recent call last):
  File "/home/cerqueira/.local/bin/mutt_oauth2.py", line 366, in <module>
    update_tokens(response)
  File "/home/cerqueira/.local/bin/mutt_oauth2.py", line 189, in update_tokens
    writetokenfile()
  File "/home/cerqueira/.local/bin/mutt_oauth2.py", line 136, in writetokenfile
    sub2 = subprocess.run(ENCRYPTION_PIPE, check=True, input=json.dumps(token).encode(),
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1706, in _execute_child
    args = list(args)
TypeError: 'NoneType' object is not iterable
```

## Steps to Reproduce

1. Create a token with `mutt_oauth2.py` (the client_id and secret_id are from thunderbird)
  

```
  mutt_oauth2.py --authorize \
		--encryption-pipe "gpg --encrypt --recipient my_email@gmail.com" \
		--provider google --verbose --email "my_email@gmail.com" \
		--client-id "406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com" \
		--client-secret "kSmqreRr0qwBWJgbf5Y-PjSU" \
		--authflow "localhostauthcode" \
		$XDG_CONFIG_HOME/neomutt/accounts/gmail.token
```

2.  Let it expire
3. Try to run the script again to update the token

```
mutt_oauth2.py $XDG_CONFIG_HOME/neomutt/accounts/gmail.token
```

## How often does this happen?

- Always

* Operating System and its version
  - Void Linux
  - Python 3.10.8

**Comment by dkwo** [comment]
Same here, also on Void.

**Comment by dkwo** [comment]
@motorto Using the script from mutt repo works fine for me, after editing the gpg, cliend and secret fields (those are not really secrets anyway).

**Comment by motorto** [comment]
> @motorto Using the script from mutt repo works fine for me, after editing the gpg, cliend and secret fields (those are not really secrets anyway).

```
mutt_oauth2.py $XDG_CONFIG_HOME/neomutt/accounts/gmail.token --client-id XXXXXXX  
--client-secret "XXXXXX" 
--provider google 
--encryption-pipe="gpg --encrypt --recipient me@mail.com"
 --decryption-pipe="gpg --decrypt"
```

Passing client-id, client-secret , encryption-pipe, decryption-pipe to the script makes it work properly on updating tokens (at least on my version of "mutt_oauth2.py")
