### ISSUE TITLE
How to open NeoMutt in a certain mailbox

### ISSUE THREAD

**Issue by wgmayer0** [neomutt/neomutt#3565]
- I use gmail as my email provider.
- I use `isync` (`mbsync`) on arch linux to sychronize mail.
- I have a keybinding set up to move to the "All Mail" folder in gmail: `macro index ga "<change-folder>=[Gmail]/All<tab><enter>"`.

How can I set up NeoMutt so that it opens in the "All Mail" folder automatically at launch? I prefer to only work in that folder. Thanks!

**Comment by gahr** [comment]
`set spoolfile='+[Gmail]/All Mail'`
