### ISSUE TITLE
Hostname set with trailing `.` - causes SMTP send error with Outlook

### ISSUE THREAD

**Issue by ianisl** [neomutt/neomutt#3568]
Hi,

After upgrading my system (WSL2 Kernel upgraded to the store version 1.0.0.0), I started to get errors while trying to send messages via Outlook's SMTP servers.

Error : `SMTP session failed: 501 5.5.4 Invalid domain name [<some-url>]`

The issue appears to be caused by the value of the `localhost` variable in neomutt. 
My hostname is `t14s` but `:set ?hostname` outputs `t14s.` in neomutt. Removing the trailing `.` by setting `:set hostname=t14s` solves the issue.

## Expected Behaviour

`hostname` should match the system's hostname

## Actual Behaviour

`hostname` is set to the system's hostname followed by a trailing dot, causing issue with some SMTP servers.

## How often does this happen?

- Always

## When did it start to happen?

- When I changed my config
  Upgraded WSL2 Kernel to the Windows store version (v `1.0.0.0`)

## NeoMutt Version

```
NeoMutt 20220429-247-c6aae8
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.15.74.2-microsoft-standard-WSL2 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.13.1-unknown
OpenSSL: OpenSSL 1.1.1f  31 Mar 2020
storage: tokyocabinet

Configure options: --with-mailpath=/var/mail --gpgme --ssl --gss --mixmaster --sasl --tokyocabinet --disable-doc

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme
  -gsasl +gss +hcache -homespool +idn +inotify -locales_hack -lua +mixmaster
  +nls -notmuch +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment

MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

(Note that I also got the issue with older versions of Neomutt)

## Extra Info

* Operating System and its version : WSL2 with Ubuntu 20.04.3 LTS 
* Were you using multiple copies of NeoMutt at once? : No
* Were you using 'screen' or 'tmux'? : I am using tmux, but tested outside of a tmux session and have the same issue.

**Comment by gahr** [comment]
I can't reproduce this on FreeBSD. What's the output of compiling and running this program on your system?
```c
#include <stdio.h>
#include <sys/utsname.h>

int main()
{
  struct utsname utsname = { 0 };
  uname(&utsname);
  printf("%s\n", utsname.nodename);
  return 0;
}
```

**Comment by ianisl** [comment]
Your program produces the correct output, i.e. `t14s`, without the trailing `.`

I ran neomutt in gdb. This line is responsible for adding the trailing `.` to hostname (line `236` in `init.c`) :

```c
sprintf((char *) fqdn, "%s.%s", NONULL(ShortHostname), mutt_buffer_string(domain));
```

**Comment by gahr** [comment]
Can you try to debug into getdnsdomainname? I can see how we could end up returning an empty string if hostname ends with a dot here: https://github.com/neomutt/neomutt/blob/c6aae8acd7c252eda2a892ab56201f65ff046ee7/conn/getdomain.c#L144

**Comment by ianisl** [comment]
I set a breakpoint to this line :

https://github.com/neomutt/neomutt/blob/c6aae8acd7c252eda2a892ab56201f65ff046ee7/conn/getdomain.c#L144

The returned value of `hostname` is `.`.
I also checked the value of `lookup_result->ai_canonname` which is `t14s.`. That seems to be the culprint as you suggested.

**Comment by gahr** [comment]
Thanks! I have no idea why you get `t14s.` back, but I think it’s reasonable not to append a dot and an empty string to your hostnamr. I’ll fix it this way.

**Comment by ianisl** [comment]
Thanks! When I find some time tomorrow I'll continue investigating why I get `t14s.`, will come back here if I get something.

**Comment by gahr** [comment]
Can you please give the [devel/issue-3568](https://github.com/neomutt/neomutt/tree/devel/issue-3568) branch a try?

**Comment by ianisl** [comment]
> Can you please give the [devel/issue-3568](https://github.com/neomutt/neomutt/tree/devel/issue-3568) branch a try?

I'll try this as soon as I have the opportunity --- in 2-3 days max.

**Comment by ianisl** [comment]
Hey, sorry it took me so long to get back to you about this issue. This has apparently be merged into `main`, but I can confirm that I correctly get `t14s` (without the trailing dot) with the last commit.
