### ISSUE TITLE
Problem displaying narrow no-break spaces under freebsd 11

### ISSUE THREAD

**Issue by alarig** [neomutt/neomutt#357]
I’ve upgraded from freebsd 10.2 to freebsd 11 and since then I see 'M-}' instead of ' ' in the mails.
vim and weechat are displaying this character correctly. I’ve tested it with the versions 20161104 and 20170128.
All other non ASCII characters are displayed correctly.

Thanks,
\-- 
alarig

**Comment by gahr** [comment]
I'll take this, as I have a similar setup.

**Comment by gahr** [comment]
I can reproduce with neomutt (the branch), 20161126, and 20161104.

**Comment by gahr** [comment]
So, the issue is with out pager not able to display `U+202F NARROW NO-BREAK SPACE`, which is `0xe2 0x80 0xaf` in utf-8. Mutt-1.7.2 does *not* have this problem.
