### ISSUE TITLE
NeoMutt failing to determine hostname on startup causing long hang

### ISSUE THREAD

**Issue by rrueger** [neomutt/neomutt#3574]
Many thanks for reading this issue and for everyone's hard work on NeoMutt. It is a great piece of software that I use every day.

## Expected Behaviour

NeoMutt to open "instantly".

## Actual Behaviour

Opening NeoMutt whilst having a bad internet connection causes a long hang (minutes), even though I use Maildir.

In fact, even without a config loaded:

    neomutt -F <(echo) -d5

or

    touch /tmp/empty; neomutt -F /tmp/empty -d5

both hang.

## Steps to Reproduce

When opening NeoMutt, NeoMutt tries to figure out my hostname with the routines `get_hostname()` and `mutt_getaddrinfo_a()`.

I can see this from the `.neomuttdebugN` file

    [2022-12-07 00:25:03]<3> parse_attach_list() added message/external-body [4]
    [2022-12-07 00:25:03]<1> get_hostname() Setting $hostname
    [2022-12-07 00:25:03]<1> mutt_getaddrinfo_a() timeout
    [2022-12-07 00:26:02]<1> get_hostname() Hostname: <myhostname>

Here one can see that NeoMutt hangs for roughly one minute. Notably, at some point NeoMutt does find my real hostname.

Whilst NeoMutt is hanging the regular `hostname` command has no issue instantly returning my hostname.

## How often does this happen?

This correlates with my internet connection not working properly. When my laptop (`NetworkManager`) thinks it is connected, but actually using the internet (or intranet) doesn't work.

## How to fix this problem

If I set the variable `hostname` in my config then NeoMutt does not hang.

    neomutt -F <(echo 'set hostname = myhostname') -d5

Whilst this is a fix, it would be good if NeoMutt could more robustly handle network errors in such cases (maybe by just calling `hostname` under the hood?). Setting hostnames in configs is a little tedious when using NeoMutt on different machines.

## When did it start to happen?

This has been an issue for a while. Just recently it has gotten to be a bigger issue, because my laptop's networking has become more temperamental (independent of NeoMutt), probably owing to kernel/bios upgrades or the likes.

## NeoMutt Version

```
NeoMutt 20220429
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.0.11-arch1-1 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libidn2: 2.3.4 (compiled with 2.3.2)
GPGME: 1.17.1
GnuTLS: 3.7.4
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, bdb, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --bdb --lmdb --kyotocabinet --gdbm --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/neomutt/src=/usr/src/debug -flto=auto -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme +gss 
  +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster +nls +notmuch 
  -openssl +pgp +regex +sasl +smime +sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

## Extra Info

* Operating System and its version: Archlinux on `6.0.11-arch1-1`
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? `tmux`
* Is your email local (maildir) or remote (IMAP)? `maildir`

It should be noted that this issue occurs when I open NeoMutt with no configuration file or any options.

**Comment by rrueger** [comment]
Thank you for your quick response!

To prevent configuration proliferation, could NeoMutt make a system call to `hostname`, which appears to be more stable across network instabilities?

Or perhaps NeoMutt could (be configured to) read `/etc/hostname`, which is usually defined (on Linux)?

**Comment by flatcap** [comment]
NeoMutt does quite a lot to get a fully-qualified domain name for the machine.

The highest priority is `$hostname`, so the config:
```
set hostname = "laptop.example.com"
```
will prevent NeoMutt from trying any DNS at all.

---

I've tweaked @gahr's fix and it seems to run OK.
If it works for you, I'll merge it.

Thanks

**Comment by rrueger** [comment]
Thank you!

I have installed the version from commit 93b0a4e9

    $ neomutt -v
    NeoMutt 20220429-251-93b0a4-dirty

I will run it as my daily driver until my networking has responsiveness issues again.
I will report back on if NeoMutt hangs or not.

**Comment by rrueger** [comment]
Seems to work well!

NeoMutt `20220429-251-93b0a4-dirty` does not hang when Neomutt `20220429` does.

**Comment by flatcap** [comment]
Great!  Thanks.  Merged.
