### ISSUE TITLE
Is there a way to display all available mailboxes in sidebar

### ISSUE THREAD

**Issue by AxelBohm** [neomutt/neomutt#3577]
To me it's a bit of nuisance having to list `mailboxes "Inbox" "Drafts" "Trash" ....` manually. Especially since I recently started to organize my mail more into different mailboxes. Is there an easy way to have neomutt just use all of them? Something along the lines of `mailboxes *`?

**Comment by gahr** [comment]
If your backend is IMAP, you can `set imap_check_subscribed`; if you run on local maildirs, what is your concept of "all available mailboxes"? What would an algorithm to find them look like, in your view?

**Comment by AxelBohm** [comment]
I do use offlineimap. but `set imap_check_subscribed`gives me an empty sidebar.. (I don't know if there are other ways to navigate mailboxes, but I use the sidebar)
By "all available mailboxes", I mean all the ones in my local mail folder, which coincides with the mailboxes I see when I log into webmail.

**Comment by gahr** [comment]
NeoMutt has no way of knowing what are the mailboxes in your local mail folder. But you can use a shell command to list them, like this:
```
mailboxes `find /path/to/your/local/mail/folder -type d -name cur | xargs dirname | xargs`
```

**Comment by AxelBohm** [comment]
Amazing! Thank you so much such!

**Comment by alexindigo** [comment]
Hey @gahr thanks for the suggestion, I'm curious if there is a way to display all folders from IMAP account?

Thank you.

**Comment by alexindigo** [comment]
Thank you, I was looking for something more static, but I'll try to utilize that as well.
