### ISSUE TITLE
Is message flag "A" undocumented?

### ISSUE THREAD

**Issue by milanglacier** [neomutt/neomutt#3579]
I note that there's a message flag "A" that doesn't appear in the manual (I don't see it in table 2.9 and table 2.10 for the full manual located at `/usr/share/doc/neomutt/manual.html` ).

While it is not hard to guess that flag "A" means that this message has attachments (but I am not completely sure), but I think this information should also appear in table 2.9 as well.

**Comment by flatcap** [comment]
Hmm... you've got me confused.
There shouldn't **be** any `A`s.
Perhaps a small screenshot would help.

---

Many of the display flags are configurable:
They default to:
```
set crypt_chars  = "SPsK "
set flag_chars   = "*!DdrONon- "
set from_chars   = ""
set status_chars = "-*%A"
set to_chars     = " +TCFLR"
```
(the `A` in `status_chars` refers to the Status Bar)

You can check your settings, by:
```
neomutt -Q flag_chars
```

**Comment by milanglacier** [comment]
> Many of the display flags are configurable: They default to:
> 
> ```
> set crypt_chars  = "SPsK "
> set flag_chars   = "*!DdrONon- "
> set from_chars   = ""
> set status_chars = "-*%A"
> set to_chars     = " +TCFLR"
> ```

I checked those chars, they are all kept the same as the default. I didn't change them. This is my screenshot:

<img width="1440" alt="Screen Shot 2022-12-13 at 22 38 25" src="https://user-images.githubusercontent.com/45728125/207499877-28ac2ade-2181-4043-8b8b-bda16a3a6566.png">

Note that all messages that have "A" flag contain attachments (for example `*.patch` file)

**Comment by milanglacier** [comment]
On 22/12/13 07:42PM, milanglacier wrote:
>
>> Many of the display flags are configurable: They default to:
>>
>> ```
>> set crypt_chars  = "SPsK "
>> set flag_chars   = "*!DdrONon- "
>> set from_chars   = ""
>> set status_chars = "-*%A"
>> set to_chars     = " +TCFLR"
>> ```
>
>I checked those chars, they are all kept the same as the default. I didn't change them. This is my screenshot:
>
><img width="1440" alt="Screen Shot 2022-12-13 at 22 38 25" src="https://user-images.githubusercontent.com/45728125/207499877-28ac2ade-2181-4043-8b8b-bda16a3a6566.png">
>
>Note that all messages that have "A" flag contain attachments (for example `*.patch` file)

my index_format is `"%2C %Z %?X?A& ? %D %-15.15F %s (%-4.4c)"`, I copied
it from mutt-wizard.

**Comment by milanglacier** [comment]
>my index_format is `"%2C %Z %?X?A& ? %D %-15.15F %s (%-4.4c)"`, I copied
>it from mutt-wizard.

I think I have figured out the reason. It lies in "%?X?A& ?" which is a
ternary operator check if there are attachments (indicated by "X") then
outputs "A" if true else outputs " "

**Comment by flatcap** [comment]
Aha!  That makes sense :-)

If you can spare an extra column, you can even use emojis:
```
<X?📎&  >
```
This replaces the `A` with a paperclip.
(there are two spaces after the `&` to match the width)

And if you really want to go crazy, you can install: https://www.nerdfonts.com/
Then you can replace all the letter chars, above, with meaningful symbols.
