### ISSUE TITLE
Disable unnecessary options

### ISSUE THREAD

**Issue by wgmayer0** [neomutt/neomutt#3583]
Is there a way to disable You are on the last message" and "You are on the first message" as well as "Key is not bound.  Press '?' for help."? Thanks

**Comment by auouymous** [comment]
I use this patch to make the first/last messages beep and keep pager open.

```patch
--- a/index/functions.c
+++ b/index/functions.c
@@ -1761,8 +1761,7 @@ static int op_next_entry(struct IndexSharedData *shared, struct IndexPrivateData
   const int index = menu_get_index(priv->menu) + 1;
   if (index >= shared->mailbox->vcount)
   {
-    mutt_message(_("You are on the last message"));
+    mutt_error(_("You are on the last message"));
-    notify_send(shared->notify, NT_INDEX, NT_INDEX_EMAIL, NULL);
     return FR_ERROR;
   }
   menu_set_index(priv->menu, index);
@@ -1803,8 +1803,7 @@ static int op_prev_entry(struct IndexSharedData *shared, struct IndexPrivateData
   if (index < 1)
   {
-    notify_send(shared->notify, NT_INDEX, NT_INDEX_EMAIL, NULL);
-    mutt_message(_("You are on the first message"));
+    mutt_error(_("You are on the first message"));
     return FR_ERROR;
   }
   menu_set_index(priv->menu, index - 1);
```

This patch should eliminate the messages, not beep and keep pager open.

```patch
--- a/index/functions.c
+++ b/index/functions.c
@@ -1761,8 +1761,6 @@ static int op_next_entry(struct IndexSharedData *shared, struct IndexPrivateData
   const int index = menu_get_index(priv->menu) + 1;
   if (index >= shared->mailbox->vcount)
   {
-    mutt_message(_("You are on the last message"));
-    notify_send(shared->notify, NT_INDEX, NT_INDEX_EMAIL, NULL);
     return FR_ERROR;
   }
   menu_set_index(priv->menu, index);
@@ -1803,8 +1803,6 @@ static int op_prev_entry(struct IndexSharedData *shared, struct IndexPrivateData
   if (index < 1)
   {
-    notify_send(shared->notify, NT_INDEX, NT_INDEX_EMAIL, NULL);
-    mutt_message(_("You are on the first message"));
     return FR_ERROR;
   }
   menu_set_index(priv->menu, index - 1);
```

The `notify_send` lines cause pager to close, so keeping them would provide default behavior, just without the messages.

**Comment by wgmayer0** [comment]
If I install the patch, will I be able to update neomutt still?

**Comment by auouymous** [comment]
How are you building? I use Gentoo which has a patches directory and it automatically applies them when compiling neomutt. If you are building from a git clone you can use `git checkout -- index/functions.c` before running `git pull origin`, and then run `patch -p1 < the-patch.patch` to apply it.

**Comment by wgmayer0** [comment]
Gotcha, I am using arch linux and just upgrading through pacman package manager. Don't know anything about Gentoo but have read that everything has to be compiled from scratch

**Comment by auouymous** [comment]
You have to compile neomutt to use this patch. I don't use Arch but there is a neomutt-git package in AUR, however, https://wiki.archlinux.org/title/Patching_packages suggests you might have to edit the build file of the package to add custom patches.

**Comment by wgmayer0** [comment]
@flatcap would it be possible to make a setting to turn these features off in the main neomutt package?

**Comment by scottkosty** [comment]
@wgmayer0  Is the main annoyance the message itself, or is there a forced pause before you can enter another action?

**Comment by wgmayer0** [comment]
The message itself has always annoyed me but the forced pause is definitely the main annoyance so I would say both!

**Comment by auouymous** [comment]
> the forced pause is definitely the main annoyance

Does `set sleep_time = 0` fix it?

**Comment by wgmayer0** [comment]
will give it a try!

**Comment by wgmayer0** [comment]
Yes that fixed it. Thanks! Still would be nice to turn off the text!

**Comment by gahr** [comment]
I don't know.. it looks to me like the messages are pretty harmless. Different people will have different opinions on whether they are useful or useless, but we also probably don't want to let the number of config options explode (as if it isn't already...) so one can configure every little immaterial aspect such as this one :) For me it's either we keep or we remove the messages, but I wouldn't allow it to be configurable.

**Comment by wgmayer0** [comment]
Ok thanks for looking into it. Turning off the delay was great. Never knew that was an option but it solved another problem for me which was the delay when an email was getting deleted. Thank you!

**Comment by flatcap** [comment]
Sorry for taking an age to get around to this, but...

There **is** a way to kill certain messages, if you're willing to get your hands dirty.
**See**: [Testing a Translation](https://neomutt.org/dev/translate#testing-a-translation)

You could create a custom translation `.mo` file.
Edit a translation file in the source, e.g. `po/en_GB.po`
Replace the `msgstr` line **with a single space character**, for any messages you don't like:
```diff
 #: menu/move.c:387
 msgid "You are on the first entry"
-msgstr "You are on the first entry"
+msgstr " "
```

Then run `./configure; make po/en_GB.mo`
(that's `.mo` the compiled translation file)

By setting a couple of environment variables, `LANG`, `TEXTDOMAINDIR`, neomutt will use these translations.
**Note**: If it doesn't work in `en_GB.utf-8/LC_MESSAGES`, try `en/LC_MESSAGES`

If you're an English speaker, you'll probably never have to update this file.

**Comment by flatcap** [comment]
As for a config option, I'm with @gahr on this.
We already have >400 config options, so I'd be reluctant to add any more,

Perhaps in the future we might drop these messages.
(I see that Vim doesn't need them)

**Comment by wgmayer0** [comment]
Yep - I agree
