### ISSUE TITLE
<edit-type> in macro

### ISSUE THREAD

**Issue by rionda** [neomutt/neomutt#3587]
From time to time, I want to open a text/html attachment with a different program than what I have specified in mailcap. The reason for doing this is that sometimes I want to load the images in the html, and sometimes I don't. 

To achieve this goal, I decided to create a `index,pager` macro that, upon press, would look for attachments of type text/html, change their type to text/myhtml with `<edit-type>`, and then use `<view-mailcap>` to invoke the program that I specify in my mailcap for the text/myhtml type.

The macro looks, currently, like this:
```
macro index,pager V "<view-attachments><search>html<enter><edit-type>text/myhtml<enter><search>myhtml<enter><view-mailcap><exit><clear-flag>N"
```

The issue is that `<edit-type>` from the macro does not seem to do its job. Specifically, it seems to *add* 'text/html' to the charset, which ends up being 'utf-8text/myhtml', while the mime type is still 'text/html'.

I believe the reason is that `<edit-type>` prompts for edits starting from the current value of mime type and charset, e.g., proposing 'text/html; charset=utf-8', thus 'text/myhtml' is appended to it.

I'm wondering whether there is a way, in a macro, to delete all the proposed text, or alternatively, to just set the mime type without *editing* the current one.

**Comment by auouymous** [comment]
`<edit-type><kill-line>text/myhtml<enter>` does what you want. Or you can use other commnds at http://www.mutt.org/doc/manual/#editing to jump to beginning of line, and remove the type to preserve the charset.
