### ISSUE TITLE
me@neomutt.org

### ISSUE THREAD

**Issue by jwilk** [neomutt/neomutt#3590]
```console
$ grep -B1 '>me@neo' docs/manual.xml.head 
        NeoMutt is Copyright © 1996-2021 Michael R. Elkins
        <email>me@neomutt.org</email> and others.
```

This looks suspcious. The address is `me@mutt.org` in upstream docs.
I guess search-and-replace in cd7ffd1d3c1f20e726884c99fec9a3b19f88266f went a little too far?

**Comment by gahr** [comment]
Thanks, and sorry!

**Comment by flatcap** [comment]
Argh!  Five years without being noticed.  Embarrassing :-(
