### ISSUE TITLE
Wrong default for `rfc2047_parameters` documented

### ISSUE THREAD

**Issue by whitney-cumber** [neomutt/neomutt#3595]
The release notes[0] for neomutt-20220407 states

```
New default: set rfc2047_parameters = yes
```

and querying the config variable from neomutt's default config

```
$ neomutt -F /dev/null -Q rfc2047_parameters
set rfc2047_parameters = yes
```
confirms that.

However, my local man page, the online reference/guide[1], and the online man page[2] all still state that the default is `no`.

[0] https://neomutt.org/2022/04/08/release
[1] https://neomutt.org/guide/reference#rfc2047-parameters
[2] https://neomutt.org/man/neomuttrc  (sections don't have anchors so you have to scroll down)

**Comment by flatcap** [comment]
Good spot! 
Thank you very much :heart:

Preparing the docs involves strange, _secret_, rituals.
Some day, we'll get around to simplifying them :-)
