### ISSUE TITLE
Sidebar interferes with new messages detection

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#36]
@bitstreamout (transferred to its own issue)

Feedback from a mutt user here:

> New messages detection does not work in the current version of mutt on openSUSE Tumbleweed. As a long time mutt user I'm used to shuffle through the list of folders containing new/unread messages using the 'c' followed by 'space' key sequence. I narrowed it down to the configure option "--enable-sidebar", which enables some pseudo graphical functionality for - I guess - mutt newbies. Rebuilding the otherwise unchanged package with "--disable-sidebar" produces a normally working mutt again.

> I strongly recommend to disable this code until it gets fixed. Thx.

maybe I should disable the NeoMutt port of this patch and use the former, ported upstream as this had never this side effect.

For the user's bug report see http://bugzilla.opensuse.org/show_bug.cgi?id=982129

**Comment by flatcap** [comment]
This sounds like another problem caused by the `sidebar_refresh` option.
I'm trying to put out a release today (that probably won't fix this).
I'll start investigating tomorrow.

**Comment by duck** [comment]
This is a known issue.  See #16  for a discussion.  For me, setting `sidebar_refresh_time=1` cleared up the issue.  I would recommend chasing this issue vs rolling back to the older patch.

**Comment by bitstreamout** [comment]
Maybe a workaround could help here, see attached patch ... this patch also uses ncurses alternate character for vertiacal line for the ascii character "|" (the divider of the sidebar)

[x.txt](https://github.com/neomutt/neomutt/files/291039/x.txt)
