### ISSUE TITLE
Remove first argument from mutt_debug

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#362]
`mutt_debug` is only called by the `dprint(N,X)` macro. The macro is defined as

```c
#  define dprint(N,X) do { if(debuglevel>=N && debugfile) mutt_debug X; } while (0)
```

and a common use is

```c
 dprint (1, (debugfile, "mutt_lookup_mime_type: Internal error, count = %d.\n", count));
````

It's pretty clear that:
1) `mutt_debug` is only called with `debugfile` as its first argument
2) if `dprint` was called with anything else than `debugfile` as part of the function call construction appearing in its second argument `X`, an inconsistent check would be done within the `dprint` body (check for `debugfile`, call `mutt_debug` with a `FILE*`pointing to something else)

My proposal is to get rid of the first argument of `mutt_debug` and hardcode the check and the use of `debugfile` within its body.

Thoughts?

**Comment by flatcap** [comment]
Only last night, I was thinking the same -- your psychic powers are far-reaching!

Whoever created the prototype for `dprint` needs to go back to school. \*shudder\*.

If we're going to change all the `dprint`s, then we might as well adopt @d-k-c's replacement.
It was a nice of bit of work, but when he posted it to mutt devel, it was deemed "too invasive".

**Comment by d-k-c** [comment]
The patches I sent upstream can be found here:
http://marc.info/?l=mutt-dev&r=2&b=201608&w=2

Kevin made some remarks on patch 1/8, so maybe it can be skipped. My patchset was a bit more invasive than what you suggest, so we can make it step and step and indeed start by just getting rid of debugfile in mutt_debug.

When this is done, to keep cleaning the debug part, I would also suggest to replace the numbers by some enum (like TRACE, VERBOSE, A_BIT_LESS_VERBOSE...) but as you can see I could not really come up with good names :p

**Comment by gahr** [comment]
[@d-k-c 's take](https://github.com/d-k-c/mutt/commit/10eb3348b2c094c43d019c8084c5eae21a3fe6c8.patch) was indeed a more complete approach. Let him do the dirty work :)
