### ISSUE TITLE
Names of `auto_view` and `implicit_autoview` should be unified

### ISSUE THREAD

**Issue by whitney-cumber** [neomutt/neomutt#3626]
Spelling of `autoview`/`auto_view` is inconsistent between the command `auto_view` and the option `implicit_autoview`.

Honestly, I don't know which spelling version is better, so I leave that for the owners to decide.
(I'm willing to provide a PR if a decision would be made.)

**Comment by flatcap** [comment]
Nearly a year ago I renamed a **lot** of config, inserting underscores along word boundaries.
I skipped `implicit_autoview`, but I hadn't considered the `auto_view` command.

Please can you rename `$implicit_autoview` to `$implicit_auto_view`

Thanks!
