### ISSUE TITLE
Disable compose menu

### ISSUE THREAD

**Issue by wgmayer0** [neomutt/neomutt#3627]
Is it possible to have neomutt disable the compose menu? After I am done typing my message in vim I would like to be able to save and quit and have the message automatically send without me having to manually press `y`

**Comment by wgmayer0** [comment]
I forget what setting I have enabled, but I can do all of that in vim, no
problem!

**Comment by gahr** [comment]
`edit_headers`

**Comment by gahr** [comment]
You could
```
bind index m noop # Disable the default binding of "m" to "mail"
macro index m <mail><send-message>
```

**Comment by wgmayer0** [comment]
Thanks!

**Comment by flatcap** [comment]
@auouymous 
With `set edit_headers = yes`, you can even attach files or sign/encrypt your email from your editor:

See: [Editing the Message Header](https://neomutt.org/guide/gettingstarted.html#edit-header)

**Comment by wgmayer0** [comment]
Yep

**Comment by wgmayer0** [comment]
I am going to do some more research but off the top of your head is there a
good way to do this with reply, forward and group reply?

**Comment by gahr** [comment]
Forward should be exactly the same as <mail>. Group reply asks for a confirmation, you need to look into that. I haven't check the reference to see if that can be disabled.

**Comment by wgmayer0** [comment]
I was able to write a hook for sending messages but it doesn't seem to work for replies and forwards.

```
send-hook .* <send-email>
```

**Comment by auouymous** [comment]
> With `set edit_headers = yes`, you can even attach files from your editor:

I've always used edit_headers, but didn't know it could be be used to attach files. Thanks!
