### ISSUE TITLE
Get unread count outside of neomutt

### ISSUE THREAD

**Issue by plokid** [neomutt/neomutt#3637]
## What would you like to be able to do?

Which is mentioned in #2089 since it has been three years.

**Comment by flatcap** [comment]
> Which is mentioned in #2089

So let's wait for an answer in **that** issue.
I mean, you only asked **yesterday**.

> it has been three years

NeoMutt is a **LOT** of code with few developers.

**Comment by alexindigo** [comment]
@flatcap looks like that issue didn't resolve into anything useful.
