### ISSUE TITLE
Threaded view "not enabled"

### ISSUE THREAD

**Issue by ArchieLinux** [neomutt/neomutt#3650]
Sorry if this answer is already available (having spent hours searching I can't find it)...

I installed neomutt through mutt-wizard and all has gone well. But whenever I try to use message thread features (Esc+V or Esc+v) I get an error message telling me that threading is "not enabled."

I see nowhere I can "enable" it. What simple line of configuration instruction must I be missing?

THANKS!

**Comment by gahr** [comment]
`set use_threads=yes` ?

**Comment by ArchieLinux** [comment]
Worked like a charm - many thanks! Didn't find this (simple) intuitive solution anywhere else - must not be looking in any of the right places. :roll_eyes:

**Comment by ArchieLinux** [comment]
Thanks for your prompt solution!

**Comment by gahr** [comment]
It’s hidden here: https://neomutt.org/feature/use-threads
 :)
