### ISSUE TITLE
User input during macros possible?

### ISSUE THREAD

**Issue by whitney-cumber** [neomutt/neomutt#3665]
I try to mimic a "save" and "save as" feature:

Assume we start with `set attach_save_without_prompting` set.

Then `s` bound to `<save-entry>` in the attachment menu, does not ask a filename question (lets call that the "save" binding).

Now for the "save as" binding: It toggles `$attach_save_without_prompting` then does `<save-entry>` and then restores `$attach_save_without_prompting`.  Something like
```
macro attach S '<enter-command><enter><save-entry><enter-command><enter>'
```
(the part between `<enter-command>` and `<enter>` doesn't really matter here, its `set`ting some variables.)
However, `<save-entry>` expects user input and thus uses `<enter-command>` as filename (which becomes `=sententer-command`; `<` is the `=sent` mailbox).

Flipping the two bindings (i.e. starting with `set attach_save_without_prompting = no`) does not help, as sometimes the "save" binding does have a user question, e.g. if a file with that name is already present.

**Question**

Is it possible in a macro to wait for user input before continuing with it (like a `<wait-for-user-input>` function)?
Or is there another solution to the problem "change config variable, do something, then restore the config", where "do something" is not fully scripted but needs some user input?

(I know I can do this
```
macro attach s <enter-command>set attach_save_without_prompting<enter><save-entry>
macro attach S <enter-command>unset attach_save_without_prompting<enter><save-entry>
```
which is a sort of workaround but might not work in other situations)

**Comment by flatcap** [comment]
**Note**: This is quite rambling :-)

---

In short, no.
I don't think Vim can do that, and it's our design model :-)

Macros are very literal.  When they're executed they dump a load of keys into a keyboard buffer.
When the code asks for keystrokes, it isn't aware of where they come from.

> `<wait-for-user-input>`

So, we'd toggle a flag somewhere, and temporarily ignore the keyboard buffer.
Then later...
How would it get re-enabled?
What would trigger that?

For some arbitrary commands:
```
<apple><banana><wait-for-user><ask-question><unwait-for-user><cherry><damson>
```

We're not actually working though **this** macro, we've just dumped it into the buffer.
`<apple>` occurs, then `<banana>`, then `<wait-for-user>` turns off the very buffer that we're reading and everything stops.

The keyboard handling is already quite complicated.
It'd probably require quite a lot of investigation to see if this is possible.

**Comment by whitney-cumber** [comment]
Original question has been answered (and the answer was: no user input during macros is not possible).  Closing this.
