### ISSUE TITLE
`$vfolder_format` not used in the code

### ISSUE THREAD

**Issue by whitney-cumber** [neomutt/neomutt#3667]
Doing a quick `grep -r vfolder_format` on the code base (626085e279667ffd093e84682c9f12c529683c5b) it seems that `vfolder_format` is not used:
```
notmuch/config.c:  { "vfolder_format", DT_STRING|DT_NOT_EMPTY|R_INDEX, IP "%2C %?n?%4n/&     ?%4m %f", 0, NULL,
docs/manual.xml.head:                <entry><literal>vfolder_format</literal></entry>
docs/manual.xml.head:set vfolder_format = "%6n(%6N) %f"
docs/config.c:{ "vfolder_format", DT_STRING, "%2C %?n?%4n/&     ?%4m %f" },
ChangeLog.md:  - notmuch: sync vfolder_format to folder_format

```

Is this a dormant/deprecated config variable?

## NeoMutt Version

The commit examined was
```
626085e279667ffd093e84682c9f12c529683c5b
```

**Comment by flatcap** [comment]
Ah,  yes.  It's deprecated, but that happened before we invented the `DT_DEPRECATED` flag.
Please could you kill it :-)

Historically, the notmuch backend was maintained out-of-tree and had its own format string.
Now, it's much better integrated.

**Comment by whitney-cumber** [comment]
What do you mean by "kill it"? Remove all its occurrences from the code base or add somewhere a `DT_DEPRECATED` so it shows up like https://neomutt.org/guide/reference#escape?

**Comment by flatcap** [comment]
Please add a `DT_DEPRECATED`, dated `2018-11-01` and remove any references in the docs.
Thanks!
