### ISSUE TITLE
imap4 partial fetch request

### ISSUE THREAD

**Issue by rusnasonov** [neomutt/neomutt#367]
This task taken from mutt issue tracker
https://dev.mutt.org/trac/ticket/3465

It's very  useful feature, if you have folders with many email and you don't want download all them

**Comment by gahr** [comment]
This would sum up to
1. download only the headers (if not cached) on SELECT (when opening a mailbox)

**Comment by flatcap** [comment]
Just getting the headers seems like a very light way to work.

An alterntive is NNTP's approach which gets a fixed number of emails.
It's lacking a paging system, though -- e.g. it'll just pull the latest 100 emails.
(I don't know if IMAP's capable of this, or not, but I imagine so).

**Comment by flatcap** [comment]
> Just getting the headers seems like a very light way to work.

In a completely positive, this is a great idea, kind of way.
(Sorry, I was tired when I wrote that).

**Comment by flatcap** [comment]
It's a useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
