### ISSUE TITLE
Attachment Filename shown is truncated 

### ISSUE THREAD

**Issue by rewolff** [neomutt/neomutt#3675]
Sorry. I keep on messing up my system with trying to install more recent versions  of programs. I'm using 20200821-98-60f56b , and it works fine for me. 

## Expected Behaviour
I expect neomutt to show me the full name of an attachment. 
Many virusses send <anything>.rar <anything>.zip or as in this case <anything>.lzh attachments. Apparently windows users click on the attachment, it gets unpacked and (like here) inside is an attachment called <anything>.pdf.exe , and cliking on the file with ".pdf" name executes local code on the windows machine compromising the machine. 

I usually spot these before saving the attachment because neomutt correctly displays the filename. 

The "story" in this virus mail was: Please quote the products in this PDF. I wanted to double check that it wasn't a virus like described above. I'm a company and most of my clients don't work like that, but it is possible that one does.... Lo-and-behold! This one actually has a PDF attachment, not a zip! 

## Actual Behaviour
neomutt displays the filename without the extension.  This mislead me to save the file, and examine the PDF. People using a gui might be tempted to click on the resulting file and not realize what is going on. 

## Steps to Reproduce

I'll put up a screenshot of how it looks on my machine 

## How often does this happen?
- Always
- On a particular email
  If the email isn't private, please attach it to this issue. -- Will do. 

## When did it start to happen?
first time I notice this. 

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.15.0-56-generic (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGme: 1.13.1-unknown
libnotmuch: 5.2.0
hcache backends: tokyocabinet

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} {--libexecdir=${prefix}/lib/x86_64-linux-gnu} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet

Compilation CFLAGS: -g -O2 -fdebug-prefix-map=/build/neomutt-WmwApX/neomutt-20191207+dfsg.1=. -fstack-protector-strong -Wformat -Werror=format-security -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3 -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta +mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Ubuntu 20.04.5 LTS
* Were you using multiple copies of NeoMutt at once? Probably. 
* Were you using 'screen' or 'tmux'? No. 
* Is your email local (maildir) or remote (IMAP)? local: Maildir. (but mailbox shows the same effect: I already opened the problem Email in a saved mailboxfile and it exhibits the same behaviour. ) 

*** WARNING *** 

There is likely a virus in the attached email  "neomutt.bug.txt". (I tried different extensions but then couldn't upload) 

![neomutt_filename_display](https://user-images.githubusercontent.com/1678121/217230896-da49c3c6-5a8a-45df-81f0-0dda11682481.png)
[neomutt.bug.txt](https://github.com/neomutt/neomutt/files/10674441/neomutt.bug.txt)

**Comment by rewolff** [comment]
Isn't it a better idea to "process" the filename before printing? So that the users can always see the important bits? 
```
Arabian Aluminium Products Co.<...>.lzh
``` is 40 characters and shows what I need to know to know. 

I consider this a security issue, no matter what the length that would have fixed it for this particular Email example. If there is a big "known bug" in say the PDF interpreter or JPG library on my system and I know about it (but for some reason, can't upgrade (yet)) then I don't want to go and save suspicious files and maybe accidentally open them. In this case I'm a commandline user and open the file with the appropriate tool which in this case didn't crash, buffer-overflow-or-whathever. 
But many other people rely on the extension to launch whatever program seems appropriate for that extension. 

As I did, it isn't unreasonable to look at the extension in mutt, consider: "ok, that's safe for me to click on", and then save-and-click without looking at the filename again. 

I'm not reporting this for /me/. I hopefully remember to look again at what I saved before launching it.  Your suggestion solves it for ME for this particular Email, but not "in general".

**Comment by flatcap** [comment]
Yes, I get it.

It's odd, that in the 24 years `$attach_format` has been in Mutt, nobody's thought to fix this problem :-)

After a quick discussion on IRC, we've decided that we should do both:
- Alter the default `$attach_format` to `%d` so that it's not truncated
- Add a new expando `%f` that offers smart abbreviation

**Would you be interested in making the changes?**

---

Preventing unnecessary truncation will help most people immediately.
Here a long filename is always visible until the window gets very narrow:

```
 A     1 a-very-long-name-for-a-file.txt.exe                     [applica/octet-stre, base64, 1.0M]
 A     1 a-very-long-name-for-a-file.txt.exe               [applica/octet-stre, base64, 1.0M]
 A     1 a-very-long-name-for-a-file.txt.exe         [applica/octet-stre, base64, 1.0M]
 A     1 a-very-long-name-for-a-file.txt.exe   [applica/octet-stre, base64, 1.0M]
 A     1 a-very-long-name-for-a-file.txt.exe[applica/octet-stre, base64, 1.
 A     1 a-very-long-name-for-a-file.txt.exe[applica/octet-stre, base
 A     1 a-very-long-name-for-a-file.txt.exe[applica/octet-stre
 A     1 a-very-long-name-for-a-file.txt.exe[applica/octe
 A     1 a-very-long-name-for-a-file.txt.exe[applic
 A     1 a-very-long-name-for-a-file.txt.exe[
 A     1 a-very-long-name-for-a-file.tx
```

https://github.com/neomutt/neomutt/blob/e26e9d7ab4cf0dbab6f73466ea9b359d297731c7/mutt_config.c#L170-L172

---

Adding smart abbreviation means altering `attach_format_str()`.

https://github.com/neomutt/neomutt/blob/e26e9d7ab4cf0dbab6f73466ea9b359d297731c7/attach/dlg_attach.c#L243-L260

To know the "right" size, we'll also need to parse the `prec` (precision) field.
We can refactor some code for this from `mutt_format_s_x()`:

https://github.com/neomutt/neomutt/blob/e26e9d7ab4cf0dbab6f73466ea9b359d297731c7/gui/curs_lib.c#L758-L780

Then we can add a function to do the actual abbreviation.

**Comment by rewolff** [comment]
1) My work is pretty busy.  Free time is hard to come by. 
2) If my work is going to be ignored... I don't really feel like putting in the work. I've contributed to one too many projects and then gotten my effort ignored. It seems that won't be the case here. 
3) I was going to say: If you could point me in the right direction.... You have. Great! 

OK I'll try to look into it. With a bit of effort you can find my Email address, remind me in a week if you haven't heard from me. Or just follow up on this issue, that triggers and email too.

**Comment by flatcap** [comment]
> 1.
> 2.

Yes, I understand and sympathise.

> 3. If you could point me in the right direction.... You have. Great!

I'm always happy to help others help NeoMutt :-)

The code is fairly well documented, but diving into a new codebase is always tricky.
Have a look around, have a think, **ask lots of questions** (here, irc, or by email).

> OK I'll try to look into it

Thanks! :heart:

---

IRC: `#neomutt` on `irc.libera.chat` ([web client](https://kiwiirc.com/nextclient/irc.libera.chat/#neomutt))

**Comment by rewolff** [comment]
The easiest hint: "I think it should be in the source file named ... " is already worth VERY much for someone who will need to delve into the code for the first time. 

I think I patched "mutt" in the past to do something I needed. Hmm. Maybe that was "parsing filenames". Some subjects/filenames are actually =UTF=... unreadable when you look at the ascii bytes in the Email. Quite possibly neomutt does it correctly for subjects, but just today I got an Email where I did end up with the =UTF=... file with no extension. (it ended up being html: please confirm your Email address here: <mymail> password: <input type=text>.... ). Anyway. Separate issue. Will discuss in new "issue" when this is done.

**Comment by whitney-cumber** [comment]
> I think I patched "mutt" in the past to do something I needed. Hmm. Maybe that was "parsing filenames". Some subjects/filenames are actually =UTF=... unreadable when you look at the ascii bytes in the Email. Quite possibly neomutt does it correctly for subjects, but just today I got an Email where I did end up with the =UTF=... file with no extension. (it ended up being html: please confirm your Email address here: password: .... ). Anyway. Separate issue. Will discuss in new "issue" when this is done.

Not sure what you are referring to, but it sounds a little like `set $rfc2047_parameters = yes` might help with that problem:

https://neomutt.org/guide/reference#rfc2047-parameters

**Comment by rewolff** [comment]
Thanks for the tip. Seems to work .

**Comment by flatcap** [comment]
> remind me in a week

ping

**Comment by rewolff** [comment]
Work overload. Sorry. I'm not leaving the office before 10PM when I dont' have external appointments (3 days a week) Working sat/sun as well. Keep pinging me. Catching up atm.

**Comment by flatcap** [comment]
No worries.
Hope things calm down soon.
