### ISSUE TITLE
tls_get_client_cert triggers user-password authentication even if not wanted

### ISSUE THREAD

**Issue by luchr** [neomutt/neomutt#3681]
## Expected Behaviour

If one uses the config (with neomutt compile options `+gnutls` and `+sasl`)
```
set smtp_url = 'smtps://...'
unset smtp_user
unset smtp_pass
set ssl_starttls = no
set ssl_client_cert = '..../cert_with_key.pem'
set smtp_authenticators='ANONYMOUS'
```

one expects: Authentication with the client certificate and no user/password questions. Especially if the server does not support user/password-auth.

## Actual Behaviour

Client-cert-Auth works perfectly. But after the perfect authentication, neomutt asks for an username and then there is the error: `SMTP server does not support authentication`   
Obviously it does not, because the auth is done by client certificates.

## Analysis

The reason for this is quite simple:
1. The method `tls_get_client_cert`  calls  https://github.com/neomutt/neomutt/blob/ed188b29cff6ff3c974d04c444894f95f3d360f9/conn/gnutls.c#L734-L736  `mutt_account_getuser` and suddenly neomutt prompts the user to enter a username and the the account.flags have then a user flag (even if the empty username was entered)
2. `smtp_open` sees the user-flag https://github.com/neomutt/neomutt/blob/ed188b29cff6ff3c974d04c444894f95f3d360f9/send/smtp.c#L1060-L1069  to trigger the error message.

## My Solution
I solved the problem for my use case by deleting the  `mutt_account_getuser` call in 1.

I don't even understand the comment in 1. in the source code; if one want's a username neomutt offers a lot of methods to set the user. If one does not want a username (`unset smtp_user`) then neomutt should make this explicit wish come true.

**Comment by balejk** [comment]
@flatcap Any news/thoughts on this? I am having the same problem (with OpenSSL, but the codebase seems similar and the workaround is the same).
