### ISSUE TITLE
Allow colouring the pager status line (`$pager_format`)

### ISSUE THREAD

**Issue by whitney-cumber** [neomutt/neomutt#3685]
## What would you like to be able to do?

I'd like to be able to colour the pager's status line (defined by `$pager_format`) similar to the `$status_format`

## Additional Info

Similar issues:

https://github.com/neomutt/neomutt/issues/3680 (colouring headers)
https://github.com/neomutt/neomutt/issues/3672 (status_format caveats)
https://github.com/neomutt/neomutt/issues/3660 (allow different colours in attachment menu)
https://github.com/neomutt/neomutt/issues/3617 (allow different colours in sidebar)

**Comment by auouymous** [comment]
You can color `pager_format` with `color status`. The following colors `... (%P)` in status_format and pager_format.

```
color status <fg> <bg> "([(]all[)])$" 1
color status <fg> <bg> "[(](top|end|[0-9]+%)[)]$" 1
```

Or `%S ...` in pager_format.

```
color status <fg> <bg> "^(-)" 1
color status <fg> <bg> "^([NrD!*])" 1
```

It is easy to color any field with the proper regex.
