### ISSUE TITLE
Cannot `unhook index-format-hook`

### ISSUE THREAD

**Issue by whitney-cumber** [neomutt/neomutt#3688]
## Expected Behaviour

Being able to delete index-format-hooks using `unhook` like for `send-hook`.

## Actual Behaviour

`unhook` gives an error/warning message: `unhook: unknown hook type: index-format-hook`.

## Steps to Reproduce

0. `neomutt -F /dev/null`
1. Enter `:unhook index-format-hook` which results in:  `unhook: unknown hook type: index-format-hook`

## NeoMutt Version

```
20220429-371-e26e9d
```

**Comment by flatcap** [comment]
More concerning, though, are the config errors I get:
```
Error in .muttrc, line 1: No Context
...
```

When NeoMutt reads the config, it's trying to compile a pattern, but there isn't a `Context` yet (an open Mailbox).

**Comment by flatcap** [comment]
Hmm... it doesn't seem to affect the working.
I just need to investigate why the check is still there.
