### ISSUE TITLE
Hide/configure the key hints at the top?

### ISSUE THREAD

**Issue by eremt** [neomutt/neomutt#3689]
Sorry if this is a duplicate or already answered in the docs, I tried really hard to find an answer. I would like to hide the bar with hints at the top but can't find any setting for it. Is this possible?

**Comment by flatcap** [comment]
Yep, config:

```sh
set help = no
```

> I tried really hard to find an answer

No worries.  There are SO many options :-)

**Comment by eremt** [comment]
> Yep, config:
> 
> ```shell
> set help = no
> ```
> 
> > I tried really hard to find an answer
> 
> No worries. There are SO many options :-)

Fantastic, knew it would be there somewhere. Thank you!
