### ISSUE TITLE
Use `mutt_buffer_init` in hook.c

### ISSUE THREAD

**Issue by guiniol** [neomutt/neomutt#369]
A couple of buffer are being initialised using `memset` instead of the `mutt_buffer_init` dedicated function. This is mostly cosmetic but should be fixed.

**Comment by guyzmo** [comment]
as we're at it couldn't we change a few things:

1. `BUFFER` into `buffer_t` in [`mutt.h`]
2. make `mutt_buffer_init()` inline (defined in [`muttlib.c`] (which would then need to move in the header).

I think the first change would be a good improvement towards readability, and the second one is debatable.

[`mutt.h`]:https://github.com/neomutt/neomutt/blob/master/mutt.h#L129,L135
[`muttlib.c`]:https://github.com/neomutt/neomutt/blob/master/muttlib.c#L1903,L1906

**Comment by guiniol** [comment]
> 1. `BUFFER` into `buffer_t` in `mutt.h`

I didn't realise that we were moving from all caps to type_t, but I like the second style better, so that's fine by me.

> 2. make `mutt_buffer_init()` inline (defined in `muttlib.c` (which would then need to move in the header).

That's a good change too.

This turns the PR into a bigger "fix the buffer def and init" but that's fine by me. I'll also check for other places where `mutt_buffer_init` should have been used.

**Comment by gahr** [comment]
Could we please have a separate discussion about s/BUFFER/buffer_t/? I'm not sure there's consensus yet..

**Comment by guiniol** [comment]
@gahr very well.
Let's merge this and we can revisit the rest once we have a coding style decided.

**Comment by guyzmo** [comment]
of course, it makes totally sense. I just wanted to say it out loud so we can think about it and decide to make it happen.

**Comment by guiniol** [comment]
I guess this is good to go, so @neomutt/reviewers please review
