### ISSUE TITLE
Date parsing not compatible with BSD date

### ISSUE THREAD

**Issue by alexpearce** [neomutt/neomutt#37]
The `make` build [calls the `date` command](https://github.com/neomutt/neomutt/search?utf8=%E2%9C%93&q=%22date+-d%22&type=Code) as of release 20160530 (issue #32):

```
  date=`head -n 1 $(top_srcdir)/ChangeLog.neomutt | LC_ALL=C cut -d ' ' -f 3-5` && \
  date=`date -d "$$date" "+%Y-%m-%d" &&  \
  # ...
```

Use of the `-d` flag is not compatible with BSD `date`, as [found on OS X](http://stackoverflow.com/questions/9804966/date-command-does-not-follow-linux-specifications-mac-os-x-lion), and I can't see a similar flag that could be used in its place.

One alternative is to do the parsing in Python, which is cross-platform, assuming it's available.

```shell
$ date="May 23 2016"
$ python -c "from datetime import datetime as dt; print(dt.strptime('$date', '%B %d %Y').strftime('%Y-%m-%d'))"
2016-05-23
```

This is causing the current Homebrew build for 20160530 to fail, see neomutt/homebrew-neomutt#11.

**Comment by flatcap** [comment]
[expletive]  There was I trying to be clever.

This works in FreeBSD (the only BSD I have to hand):
```
date -jf "%b %d %Y" "`head -n 1 ChangeLog.neomutt | cut -b7-17`" "+%F"
```

But it might be simpler if I just change the format of the ChangeLog to something more parseable.

**Comment by flatcap** [comment]
OK, I've pushed a new commit: 7742cc7e48b8fa967c75ecc9f5fc6609a4af1bc5
Can you cheat your build process: Leave the version number the same, but reference this commit?

**Comment by alexpearce** [comment]
That did the trick 👍

**Comment by flatcap** [comment]
Keep the workaround, for now.
This release was a bit rushed (and poorly tested), so I'm probably going to release a new version fairly soon.

**Comment by alexpearce** [comment]
OK, thanks.
