### ISSUE TITLE
Allow colouring the postponed menu

### ISSUE THREAD

**Issue by whitney-cumber** [neomutt/neomutt#3704]
## What would you like to be able to do?

The postponed menu (which is shown when answering yes to the question "Recall postponed message?" or by calling `<recall-message>`) is not coloured.  I'd like to colour it.

The entry lines of the messages is the same as the entry line for the index (`$index_format`), so maybe just use those colours?!?

**Comment by flatcap** [comment]
Yes, that should be easy.
A quick scan of the code shows that postpone shares all the same code:

**Setup:**
https://github.com/neomutt/neomutt/blob/20cebbe5dc0ad263d4bdbaac2761435b68107753/postpone/dlg_postpone.c#L174

**Use:**
https://github.com/neomutt/neomutt/blob/20cebbe5dc0ad263d4bdbaac2761435b68107753/postpone/dlg_postpone.c#L101-L108

In fact, just adding `MUTT_FORMAT_INDEX` to the `flags` param of `mutt_make_string()` might be enough.
