### ISSUE TITLE
Corrupted signatures after sending failed

### ISSUE THREAD

**Issue by rayfordshire** [neomutt/neomutt#3705]
## The Problem

For signed mails, NeoMutt adds a broken signature each time sending fails.

## Steps to Reproduce

0. Need a S/MIME certificate (PGP key might work, too)
1. Use this `neomuttrc`
```
set crypt_use_gpgme = yes
set sendmail = "/bin/false"
```
Enable GPGME backend (classic might work, too).
The sendmail config makes sure sending fails.

2. Send a signed mail to someone
```
~/tmp/neomutt/build_plain/neomutt -F neomuttrc-smime -s 'Signing issue' foo@example.org
```
3. Select S/MIME singing and a valid certificate.
4. Press send (`y`)
5. Sending should have failed
6. Press send (`y`) again
7. Press send (`y`) again
8. Press send (`y`) again
9. ...
10. Notice that each time an additional multipart-signed layer is added to the mail.
11. Set `sendmail` (or `smtp_url`) to a valid command/server
12. Send the mail
13. The receving site now has multiple signed layers, all but one which are broken.  NeoMutt prints for these broken parts
```
[-- Error: Missing or bad-format multipart/signed signature --]
```

## Expected Behaviour

NeoMutt should either

a) not generate additional signatures for successive send attempts (and the first on should be valid)
b) properly remove the signature after a broken send attempt

**Comment by dcpurton** [comment]
I can confirm that this **does** occur with GPG signed emails also.

I can try and have a look at this as it's probably my fault.

**Comment by flatcap** [comment]
> I can try and have a look at this

Thanks!

**Comment by dcpurton** [comment]
Happily I don't think this was my fault :).

@rayfordshire, can you please check if https://github.com/neomutt/neomutt/pull/3709 fixes things for you?
