### ISSUE TITLE
Postponing encrypted messages corrupts headers

### ISSUE THREAD

**Issue by rayfordshire** [neomutt/neomutt#3711]
## Expected Behaviour

Proper handling of encrypted postponed messages

## Actual Behaviour

Headers are mangled, see below.

## Steps to Reproduce

Use the following `neomuttrc-enc-postpone`:
```
set crypt_use_gpgme
set crypt_protected_headers_write
set postpone_encrypt
set postponed=/tmp/postponed
```

1. `neomutt -F neomuttrc-enc-postone`
2. Compose new message with
   a) subject "Menu"
   b) body "Mail à la carte" (some non-ASCII, Latin 1 Supplement text, note the grave on the A)
3. After exiting the editor the attachments read:
   ```
   -- Attachments
   - I     1 /tmp/neomutt-1233355          [text/plain, 8bit, iso-8859-1, 0.1K]
   ```
4. Select Sign+Encrypt in S/MIME menu `<smime-menu>`
5. Postpone the message: `<postpone-message>`
6. Recall the message: `<recall-message>`; you should be asked for a passphrase (if not cached)
7. Back in the compose menu, note
   a) Subject is "..."
   b) Attachments changed (charset and name)
   ```
   -- Attachments
   - A     1 smime.p7m            [text/plain, 8bit, utf-8, 0.1K]
   ```
8. Send the mail (to someone/somewhere where you can retrieve it)
9. Retrive said the massage
10. Figure out how to get the headers of the encrypted message part, NeoMutt currently refuses to show them to you (see #3706): They are:
```
Content-Type: text/plain; protected-headers=v1; charset=utf-8;
	name="smime.p7m"; smime-type=enveloped-data
Content-Disposition: attachment; filename="smime.p7m"
Content-Transfer-Encoding: quoted-printable
Subject: ...
MIME-Version: 1.0
```

The expected headers are

```
Content-Type: text/plain; protected-headers=v1; charset=iso-8859-1;
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Subject: Menu
MIME-Version: 1.0
```

Please note:
* wrong charset
* additional parameters to Content-Type
* wrong Content-Disposition
* wrong subject

As one consequence, when viewing the mail with NeoMutt, the `à` is mangled to `\340`.
Other mailers, e.g. Thunderbird, refuse to show the message to the reader and only show an attachment.

Not tested but might also be present when using the classic backends instead of GPGME and when using PGP instead of S/MIME.

## NeoMutt Version

```
20220429-395-a1d277
```

**Comment by dcpurton** [comment]
In this case I can't reproduce this with GPG.

```
$ ./neomutt -Q send_charset -Q crypt_use_gpgme -Q crypt_protected_headers_write -Q crypt_protected_headers_read -Q crypt_protected_headers_save
set send_charset = "us-ascii:iso-8859-1:utf-8"
set crypt_use_gpgme = yes
set crypt_protected_headers_write = yes
set crypt_protected_headers_read = yes
set crypt_protected_headers_save = yes
```

After composing the email, my attachment list reads:

```
-- Attachments                                                                                            
- I     1 /tmp/neomutt-binky-1000-582279-2768599212687713064          [text/plain, 8bit, iso-8859-1, 0.1K]
```

After postponing and recalling the message, everything is as expected:

- The Subject is `Subject: Menu`
- Attachment name and charset remain as expected

After sending and receiving the email, everything is as expected. The mail can be decrypted and read as normal.

In Neomutt, the following steps normalise the display of Subject everywhere:

- In the mail index the Subject is initially `Subject: ...` (this is pre-decryption, so expected)
- Open the mail and the Subject is still `Subject: ...` (this is slightly unexpected)
- Toggle showing all headers and Subject is now `Subject: Menu` (I guess the cache is now updated and the actual subject read)

Indeed you can't easily see the mime structure of the decrypted attachment, but I think this is a slightly specialised case of #3706. The attachment list shows the `text/plain` attachment (which is the root of the decrypted email) but already decoded and without MIME headers. Perhaps there's some combination of settings to pipe an attachment in a decoded format so you can see it's MIME headers (@flatcap ?). But I definitely want it decoded when I'm looking at it in the attachment menu.

Anyway, if I save the message out and manually decrypt it I get the expected:

```
Content-Type: text/plain; charset=iso-8859-1; protected-headers=v1
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Subject: Menu
MIME-Version: 1.0

Mail =E0 la carte.
```

Conclusion?

Beats me. SMIME specific?

**Comment by rayfordshire** [comment]
Thanks @dcpurton for comprehensive testing with PGP.

>  S/MIME specific?

Maybe, there is a difference between PGP and S/MIME when it comes how Signing+Encryption is combined:

PGP/MIME generates only *one* layer which combines encryption and signing.
S/MIME on the other hand generates *two* layers, the inner with the signature (this is a multipart) and the outer with the encryption layer.

> The attachment list shows the text/plain attachment (which is the root of the decrypted email) but already decoded and without MIME headers.

Please note that in contrast to the PGP case, the root part of an decrypted S/MIME email is the `multipart/signed` which is not shown in the attachment menu.

You might try setting `set pgp_retainable_sigs = yes`, which – if I understand the documentation correctly – adapts the S/MIME approach to PGP, i.e. one layer of encryption and one layer for the signature.

---

And just to be sure, I've retested this with `20220429-396-9f56e7` which has the patch of #3709 but the issue remained.

**Comment by dcpurton** [comment]
> You might try setting `set pgp_retainable_sigs = yes`, which – if I understand the documentation correctly – adapts the S/MIME approach to PGP, i.e. one layer of encryption and one layer for the signature.

Interesting. I read the docs the same as you.

I set this, and as far as I can see it makes no difference to the email at all! There doesn't seem like there is an extra signed layer.

But I only have one PGP key (albeit connected to multiple emails). So I can only really test sending to myself which might affect things.

And of course when encrypting on postpone it's encrypting to myself, anyway.

**Comment by rayfordshire** [comment]
> > You might try setting `set pgp_retainable_sigs = yes`, which – if I understand the documentation correctly – adapts the S/MIME approach to PGP, i.e. one layer of encryption and one layer for the signature.
> 
> Interesting. I read the docs the same as you.
> 
> I set this, and as far as I can see it makes no difference to the email at all! There doesn't seem like there is an extra signed layer.

If you tested it with only postponed messages, then the reason is that postponed messages are only encrypted but not signed, so there is really only one layer. If you, however, observed this with a properly send message, then there is another bug somewhere.
