### ISSUE TITLE
How to adapt NeoMutt to compose two messages in two different languages?

### ISSUE THREAD

**Issue by s-peppler** [neomutt/neomutt#3714]
I often correspond with people of different language backgrounds and as such the messages I compose have different languages (the messages itself are mono lingual, but different messages can have different languages).

How can I configure NeoMutt to switch between different languages when composing messages?

What I mean is that there are some configuration variables like `$greeting`, `$attribution`, `$date_format`, `$signature`, ... whose value depend on the recipients target language, e.g. `$greeting` should be "Hello" or "¡Hola!" depending on whether the mail will be send to an English speaker or a Spanish one.

Is there some kind of syntax like in `.desktop` files to achieve this?
```
set greeting[en] = "Hello"
set greeting[es] = "¡Hola!"
```

Note:
* This is distinct to the locale NeoMutt is running under which is the language of the UI for me.
* `$attribution_locale` does not help, as it allows to only to switch the date format.
* It might be related to multilingual messages.

**Comment by flatcap** [comment]
> Is there some kind of syntax like in `.desktop` files to achieve this?
> ```
> set greeting[en] = "Hello"
> set greeting[es] = "¡Hola!"
> ```

Unfortunately not, though I've made a note.

---

So you want to set a group of config variables.
Possibly with some overlapping bits.

First, I'd create one config file per language: `french.rc`, `spanish.rc`, ...
Each of these would set any language-specific settings.
You may want an `english.rc` (or whatever, for your native language)

To give yourself some feedback, you could change your `$status_format` and `$compose_format` to match, e.g.

**`.neomuttrc`**
```sh
# We'll use these private config variables, later 
set my_status_format = "-%r-NeoMutt: %D [Msgs:%?M?%M/?%m%?n? New:%n?%?o? Old:%o?%?d? Del:%d?%?F? Flag:%F?%?t? Tag:%t?%?p? Post:%p?%?b? Inc:%b?%?l? %l?]---(%?T?%T/?%s/%S)-%>-(%P)---"
set my_compose_format = "-- NeoMutt: Compose  [Approx. msg size: %l   Atts: %a]%>-"
```

**`french.rc`**
```sh
set greeting = "Bonjour!"
set status_format = "[FRENCH] $my_status_format"
set compose_format = "[FRENCH] $my_compose_format"
```

If you're using a modern terminal, like [Kitty](https://sw.kovidgoyal.net/kitty/), you could even replace `[FRENCH]` with :fr: 

---

Now we need a way to `source` the config; NeoMutt has several ways.

### Hooks

Change the language when you **compose** or **reply to an email**:

```
# This hook always matches.  These are your default settings: 
send-hook . "source $HOME/.neomutt/english.rc"

# Whenever I compose, or reply to, "pierre", the French settings will be used. 
send-hook pierre@example.fr "source $HOME/.neomutt/french.rc"
```

Change the language when you **change folder**:

```
# This hook always matches.  These are your default settings: 
folder-hook . "source $HOME/.neomutt/english.rc"

# When composing from a certain folder, use these settings:
folder-hook =french "source $HOME/.neomutt/french.rc"
```

### Macros

Change the language **manually**:

```
macro index,pager <F1> "<enter-command>source $HOME/.neomutt/french.rc<enter>"
```

**Comment by s-peppler** [comment]
Thanks @flatcap for the extensive answer. It was not quite what I was expecting but so far works for my use case. Thank you!

Is there a also a way to redo the initial processing of the mail? Here is what I mean: after I entered From and Subject and end in the editor I notice that I had the wrong language.  Is there a way to redo that step without re-entering the recipients and subject?

**Comment by gahr** [comment]
I guess `set edit_headers` would be the hacker’s answer to that :)

**Comment by s-peppler** [comment]
@gahr maybe I don't understand the answer but how would `edit_headers` allow me to translate the "On XY, someone wrote" in the body?

**Comment by gahr** [comment]
> Here is what I mean: after I entered From and Subject and end in the editor I notice that I had the wrong language. Is there a way to redo that step without re-entering the recipients and subject?

Sorry - I was answering to this. `edit_headers` allows you to... edit the headers without aborting and starting from scratch.

**Comment by s-peppler** [comment]
So I guess the answer is "that is currently impossible, you have to recompose the message from the beginning".  Closing this issue.
