### ISSUE TITLE
Neomutt does not return `$my_var` when queried with `neomutt -Q`

### ISSUE THREAD

**Issue by rayfordshire** [neomutt/neomutt#3731]
## Expected Behaviour

Neomutt should return the value of `$my_var`, e.g. something like `set my_var = "foo"`.

## Actual Behaviour

Neomutt says that there is no such variable as `$my_var`.

## Steps to Reproduce

neomuttrc
```
set my_var = 'foo'
```

```
$ neomutt -F neomuttrc -Q my_var
No such variable: my_var 
```

**Comment by flatcap** [comment]
I'm not sure if I was aware this was possible, which probably means I broke it long ago with the config system replacement.

**Comment by flatcap** [comment]
Thanks for the PR.
I started bisecting during "TV Time" and the problem went WAAAAAY back!
