### ISSUE TITLE
Linking failed with `./configure --debug-mail` due to missing symbols

### ISSUE THREAD

**Issue by rayfordshire** [neomutt/neomutt#3732]
## Expected Behaviour

`./configure --debug-mail && make` succeeds.

## Actual Behaviour

`./configure --debug-mail && make` fails the linking stage due to missing symbols:

* `add_flag()`
* `get_content_disposition()`

These are defined in `debug/graphviz.c`, which is not linked unless `--debug-graphviz` is given to configure.

And while we are at it: Maybe add a `--debug-all` option to `./configure` which enables all the debug options. (Note: `--debug` does nothing wrt libdebug?)

**Comment by flatcap** [comment]
Oh, sorry.
The `--debug-*` options are all the result of some need at the time.
Even I don't turn them on _that_ often, so they get neglected.

I'll try to make some time, to fix this.

Also, I'll probably create a GitHub action to do a weekly test build of all the `--debug-*` options so they don't get out-of-date again.

**Comment by flatcap** [comment]
Or I can use your hard work, thanks :-)

**Comment by flatcap** [comment]
Please can you give #3733 a try -- it now builds with or without email/graphviz.

I've tweaked the order of your fixes so that it doesn't leak if the pointers are `NULL`.

**Comment by rayfordshire** [comment]
> I've tweaked the order of your fixes so that it doesn't leak if the pointers are NULL.

Funny, I fixed them, too, (but over in #3730) since @gahr pointed them out to me.

> Please can you give https://github.com/neomutt/neomutt/pull/3733 a try -- it now builds with or without email/graphviz.

Compiles and, more importantly, links without errors.
