### ISSUE TITLE
neomutt violates RFC 5322

### ISSUE THREAD

**Issue by mjk-gh** [neomutt/neomutt#3745]
## Expected Behaviour
neomutt honors correct RFC5322 group addressing syntax. Relevant quotes from RFC5322:

```
When it is desirable to treat several mailboxes as a single unit
(i.e., in a distribution list), the group construct can be used.  The
group construct allows the sender to indicate a named group of
recipients.  This is done by giving a display name for the group,
followed by a colon, followed by a comma-separated list of any number
of mailboxes (including zero and one), and ending with a semicolon.
```

```
[...]
3.4. Address Specification
[...]
group           =   display-name ":" [group-list] ";" [CFWS]
```

## Actual Behaviour
Neomutt automatically removes the trailing semicolon.

If NeoMutt crashed, did your OS create a 'coredump' file?
==> No coredump.

## Steps to Reproduce
Start neomutt, send an e-mail with (for instance) the To: field containing `undisclosed-recipients:;" (or a non-trivial group list), and the e-mail will be sent without the mandatory semicolon at the end of the group list.

## How often does this happen?

- Always

## When did it start to happen?
Unknown.

## NeoMutt Version

```
NeoMutt 20201127
```
(Cannot easily test newer versions)

## Extra Info

* Devuan Chimaera 4.0
* Were you using multiple copies of NeoMutt at once?
  ==> No
* Were you using 'screen' or 'tmux'?
  ==> screen, but that should not matter here.

* Is your email local (maildir) or remote (IMAP)?
Remote (IMAP).

**Comment by rayfordshire** [comment]
Tried to debug this, this is what I found:

Culprit seems to be this check in `mutt_addr_write()`:

https://github.com/neomutt/neomutt/blob/0e9c4e8599b49bfa04df8ab1928af55876169017/address/address.c#L1030-L1031

This prevents the "null address" (`struct Address` with all fields zero) from passing through.  However, that address is used in `mutt_addrlist_parse()` to indicate a semicolon:

https://github.com/neomutt/neomutt/blob/0e9c4e8599b49bfa04df8ab1928af55876169017/address/address.c#L495-L499

That check was added in e3b74e51b0b7b983d7e4f5334f7c63fd5823a8b4 "Do not add comments to address group terminators" which fixed #2548.  I have no clue where to go from here, so someone with expertise should take over.
