### ISSUE TITLE
`unbind pager` overrides mappings in index, generic, and maybe others

### ISSUE THREAD

**Issue by whitney-cumber** [neomutt/neomutt#3755]
## Expected Behaviour

`unbind foo` should only ever touch bindings in menu *foo* and leave all other menus unaltered. 

## Actual Behaviour

Some bindings are overridden.

## Steps to Reproduce

1. `neomutt -F /dev/null`
2. `:bind index <enter> mail`
3. Check that `<enter>` is bound to function `<mail>` in the index menu, e.g. with `?`/`<help>`
4. `:unbind pager` this should (only) remove (almost) all mappings from pager
5. Check `<enter>` in the index meun again, this time it is bound to `<display-message>`

Similar, `:bind pager : next-line` is overridden by `:unbind index`.  There are probably other combinations/keys, too.

**Comment by gahr** [comment]
Same as #3770
