### ISSUE TITLE
`unbind foo` does not unbind all key bindings

### ISSUE THREAD

**Issue by whitney-cumber** [neomutt/neomutt#3756]
## Expected Behaviour

`unbind foo` should remove all key bindings of menu *foo*. Currently, some keys are resevered, namely these:

Menu | Key | Bound Function
-- | -- | --
generic | `<enter>` | `<select-entry>`
generic | `<return>` | `<select-entry>`
generic | `:` |cg `<enter-command>`
generic | `?` |cg `<help>`
generic | `q` |cg `<exit>`
alias | `?` |cg `<help>`
alias | `q` |cg `<exit>`
attach | `?` |cg `<help>`
attach | `q` |cg `<exit>`
browser | `?` |cg `<help>`
browser | `q` |cg `<exit>`
editor | `<backspace>` | `<backspace>`
editor | `\177` | `<backspace>`
index | `<enter>` | `<display-message>`
index | `<return>` | `<display-message>`
index | `?` |cg `<help>`
index | `q` |cg `<exit>`
compose | `?` |cg `<help>`
compose | `q` |cg `<exit>`
pager | `?` |cg `<help>`
pager | `q` |cg `<exit>`
pager | `:` |cg `<enter-command>`
pgp | `?` |cg `<help>`
pgp | `q` |cg `<exit>`
smime | `?` |cg `<help>`
smime | `q` |cg `<exit>`
postpone | `?` |cg `<help>`
postpone | `q` |cg `<exit>`
query | `?` |cg `<help>`
query | `q` |cg `<exit>`
mix | `?` |cg `<help>`
mix | `q` |cg `<exit>`

I think `unbind foo` should unbind *all* mappings even those above.
If that is not feasible for you, I suggest to drop everything except `:` which is enough to pull yourself out of this situation.

## Actual Behaviour

Some key bindings survive / get reset.

## Additional Note

Unbinding all would probably also fix #3755 .

**Comment by gahr** [comment]
Same as #3770
