### ISSUE TITLE
Add support for IMAP ID extension

### ISSUE THREAD

**Issue by timothyqiu** [neomutt/neomutt#3769]
## What would you like to be able to do?

Use neomutt with [NetEase Mail](https://mail.163.com/) via IMAP. NetEase is one of the biggest email service providers in China.

## What needs to change in NeoMutt?

NetEase [requires](https://help.mail.163.com/faqDetail.do?code=d7a5dc8471cd0c0e8b4b8f4f8e49998b374173cfe9171305fa1ce630d7f67ac211b1978002df8b23) IMAP clients to identify themselves via ID command ([RFC2971](https://datatracker.ietf.org/doc/rfc2971/)).

## Have you tried any alternative methods?

I'm not aware of any ways to send arbitary IMAP commands.

**Comment by flatcap** [comment]
Hmm... another one.

A Mutt user, Jia Qingtong, [proposed a patch](https://gitlab.com/muttmua/mutt/-/merge_requests/155) for this a year ago.
There was some discussion, but nobody seemed actively against the patch.
Unfortunately, Mutt's maintainer has taken a step back so no new features are getting merged.

It's a small feature and it would be off by default.
Let's see what **our** users think :-)

PS  It should be a simple job to port the patch to NeoMutt.

**Comment by gahr** [comment]
I and @flatcap had a brief discussion on IRC about this (btw, you all are welcome to join us on Libera/#neomutt).

First, a side note: I think NetEase is misbehaving here. The RFC [specifically states](https://www.rfc-editor.org/rfc/rfc2971.html#section-3) that "Implementations MUST NOT make operational changes based on the data sent as part of the ID command or response".

Having said that, we agree that it would be nice to be able to tell NeoMutt to send ID info, but we wouldn't go as far as allowing configuring each and every possible field. We'd just expose a `imap_send_id` boolean config (name TBD) and hard-code a couple of fields such as "NeoMutt" and the current version.

First off, though, we'd like to know *what* would make NetEase happy: @timothyqiu do you know what's the minimal set of fields that would turn off that warning for you?

**Comment by timothyqiu** [comment]
I've tried to connect manually in Python. NetEase accepts any fields in the parameter list, as long as the list is not empty.

These works:

```
ID ("name" "Client" "version" "1.2.3")
ID ("name" "Client")
ID ("foo" "bar")
ID ("" "")
```

These won't work:

```
ID NIL
ID ()
```
