### ISSUE TITLE
Creating buffer.c

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#377]
This task is more investigation, than coding (to start with).
There are 9 functions that deal with `BUFFER`s:

```c
int mutt_extract_token (BUFFER *, BUFFER *, int);
BUFFER *mutt_buffer_new (void);
BUFFER * mutt_buffer_init (BUFFER *);
BUFFER * mutt_buffer_from (char *);
void mutt_buffer_free(BUFFER **);
int mutt_buffer_printf (BUFFER*, const char*, ...);
void mutt_buffer_add (BUFFER*, const char*, size_t);
void mutt_buffer_addstr (BUFFER*, const char*);
void mutt_buffer_addch (BUFFER*, char);
```

I wonder if they can be moved into `buffer.c` and their headers into `buffer.h`?
What do the functions depend upon?
What's the minimum we can change to achieve this?

**Comment by nobrowser** [comment]
Taking this as the first step towards general header break up.

**Comment by nobrowser** [comment]
I think you missed at least some.  The code I worked on in pattern.c takes BUFFERs for error tracking purposes.

**Comment by guyzmo** [comment]
@nobrowser there are a huge number of functions that take buffers it's like one of the main types, but I guess @flatcap wants to gather all basic buffer manipulation in one place, eventually breaking general headers like `protos.h`, with the compilation unit being not clear (is it defined in `main.c`? `muttlib.c`? `init.c`? some place else?).

**Comment by gahr** [comment]
I've been thinking for a while about adding small string optimization to buffers. However, that would require making them opaque. Just dropping it here so I don't forget, I'm fine if it's going to me taken care of separately (or even not at all if there's no consensus).

**Comment by nobrowser** [comment]
gahr, can you explain what optimization you mean? thanks.

**Comment by gahr** [comment]
@nobrowser, google for small string optimization

**Comment by flatcap** [comment]
@gahr 
Hmm... a quick google shows lots of interesting ideas.
I think that would first need a good bit of research into how we use strings.
I think that should be discussed on the mailing list.

**Comment by flatcap** [comment]
@nobrowser 
The functions I mentioned are self-contained.  There may be others.
I suppose I'd like to see two files that don't contain: `#include <mutt.h>` :-)

**Comment by nobrowser** [comment]
@flatcap, ok, I get it now.

Is there a branch?  What should it be named?

**Comment by flatcap** [comment]
As a member, you can create a branch.
Call it: "devel/SHORT-NAME" -- buffer, or buffer-refactor -- whatever you can be bothered to type.

When you're ready for others' views, then you can create a pull-request.

**Comment by nobrowser** [comment]
Hi again.

Finally I am working on this.  And immediately I hit a style issue that we completely missed in that big discussion: transitive include dependencies.  IMO **THESE ARE MADNESS** and must be avoided.  What I mean is: if a file mentions, say, isspace(), then THAT file MUST #include <ctypes.h>, and NOT rely on another include file to accidentally drag it in.  It requires some discipline: you really have to add the include immediately after writing the code that needs it, otherwise you forget and compiler won't tell you.

Sorry for the capitalization <grin>.  I care about this possibly more than about all the piddly syntactic stuff.

**Comment by guyzmo** [comment]
@nobrowser on that topic *I* think we can be a bit relaxed on a few includes, like the few "stdlib" ones we expose through `mutt.h`, i.e.: `stdio.h`, `stdlib.h`, `stdint.h` etc. But if it does not belong in `mutt.h` (so it's exposed everywhere), then I agree one should never rely on another header for the usage of a given function.

**Comment by flatcap** [comment]
There's a tool I've been playing with called `iwyu` (Include What You Use), which deals with this problem head-on.  It analyses your file and tells you what it should include.  (It also tells you WHY each file should be included).

Of course Mutt, being Mutt, the tool gets a bit upset :-)

Using `iwyu` would lead to some large lists of `#include`s to start with, but it will probably help us split things up.

**Comment by nobrowser** [comment]
I'll have to look up iwyu: it sounds super useful.
