### ISSUE TITLE
How to cause moving mails from "new" to "cur" without closing Neomutt?

### ISSUE THREAD

**Issue by ZaxonXP** [neomutt/neomutt#3771]
Hi,

I have some scripts which change my status bar of my window manager
when the files are found in any of the "new" mailbox. When I open
Neomutt and there is new mail it is marked with "N" letter and the
message is in the "new" folder of the mailbox. However when I open the
message the "N" status is gone, but the message is not moved from
"new" to "cur" folder until I close Neomutt.

Is there a way to force moving the mail without closing Neomutt?

Kind regards,
Piotr

**Comment by auouymous** [comment]
`sync-mailbox` is bound to `$` by default and will move the files.

**Comment by ZaxonXP** [comment]
I forgot that this `$` do it. Thanks for reminding. :)
