### ISSUE TITLE
after background mailbox sync Delete flag cleared

### ISSUE THREAD

**Issue by JonJFineman** [neomutt/neomutt#3772]
## Expected Behaviour

After neomutt mailbox sync mail message flags should be preserved.

## Actual Behaviour

I had deleted a few messages and was reading another one. After the mail_check timer the messages I had deleted where undeleted.

If NeoMutt crashed, did your OS create a 'coredump' file?

## Steps to Reproduce

Delete a message (don't manual sync mailbox).
Read another message while waiting for offlineimap and mail_check timer to run.
If is not clear if you have to run the "." command to get the display to change.
When returning to the message view the deleted messages will have the delete flag cleared.

## How often does this happen?

- Always

- Sometimes
Almost always.

- On a particular email
  If the email isn't private, please attach it to this issue.

## When did it start to happen?

- When I upgraded
  Which version did you use to use?
About a month ago with that git commit.

- When I changed my config
  Can you narrow down **what** you changed?
If you set check_new = no it does not happen.

## NeoMutt Version

```
PUT YOUR "neomutt -v" OUTPUT HERE

./neomutt -v
NeoMutt 20220429-521-00cbe5-dirty
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: OpenBSD 7.3 (amd64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.17
libidn2: 2.3.0 (compiled with 2.3.0)
GPGME: 1.18.0
LibreSSL: LibreSSL 3.7.2
OpenSSL: LibreSSL 3.7.2
libnotmuch: 5.6.0
storage: tdb

Configure options: --autocrypt --with-lock=flock --fmemopen --gpgme --notmuch --ssl --sasl --sqlite --idn=0 --idn2 --tdb --debug

Compilation CFLAGS: -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -DNCURSES_WIDECHAR -I/usr/local/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt -fcntl +flock +fmemopen +futimens +getaddrinfo -gnutls +gpgme 
  -gsasl -gss +hcache -homespool +idn -inotify -locales_hack -lua -mixmaster 
  +nls +notmuch +openssl +pgp +regex +sasl +smime +sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

Does not happen with IMAP.
I have side pane enabled.

* Operating System and its version
kern.version=OpenBSD 7.3 (GENERIC.MP) #1122: Sun Mar 19 22:01:58 MDT 2023 deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP
and
Debian unstable Bookworm 12

* Were you using multiple copies of NeoMutt at once?
no
* Were you using 'screen' or 'tmux'?
no
* Is your email local (maildir) or remote (IMAP)?
maildir

**Comment by auouymous** [comment]
Does it happen with 5d0db19ef054bcc261b565dbb918a1dc33438985? If not, does it happen with 2523464c1d6b293dc5f512944ed84f96823c6c9d. If so, it would be the incomplete patch from #3560 that was most likely pushed by accident.

**Comment by JonJFineman** [comment]
It does not happen with 5d0db19, and it does happen with 2523464. Which seems to be reverse of your statement.

What build is 3560 fixed in?

**Comment by auouymous** [comment]
That is exactly my statement, your issue was caused by the #3560 patch that was accidentally pushed (I'm assuming). You will need to use 5d0db19ef054bcc261b565dbb918a1dc33438985 until it is reverted or more patches are pushed to fix the bugs it added.

**Comment by auouymous** [comment]
This should be fixed in latest commit.

**Comment by JonJFineman** [comment]
Yes it is. Thanks.
