### ISSUE TITLE
Samples directory removed, but still referenced in docs

### ISSUE THREAD

**Issue by antonok-edm** [neomutt/neomutt#3778]
The `samples` directory was removed in https://github.com/neomutt/neomutt/commit/2369ec390985004ee25965f3d9d9830e3e947b64.

However, the documentation still recommends to `source` some of those files.
For example, `gpg.rc` and `smime.rc`: https://github.com/neomutt/neomutt/blob/a932adbc6a4a4dca9fa254c02c0b60bf7602f614/docs/manual.xml.head#L3484-L3485

I opened this issue because I'd sourced `gpg.rc` in my own configuration, which is now broken.

Is there a recommended path forward for users who relied on these scripts in the past?

**Comment by flatcap** [comment]
Sorry about that.

The recommended path is to use GPGME instead.
It supports GPG/PGP and S/MIME without having to set over 20 `pgp_` and `smime_*_command` configs.
Unless you're a crypto-wizard, it will do everything you need.

Config, just:
```
set crypt_use_gpgme = yes
```

Old files, should you need anything from them:
- [gpg.rc](https://raw.githubusercontent.com/neomutt/neomutt/f108e9726e265d092fbdc488716bb04b1c7234c1/contrib/samples/gpg.rc)
- [smime.rc](https://raw.githubusercontent.com/neomutt/neomutt/f108e9726e265d092fbdc488716bb04b1c7234c1/contrib/samples/smime.rc)

I'll fix up the docs when I have a second.

**Comment by gahr** [comment]
Fixed in d67c876ae5411781bf2240289fd7abc97cd002f4
