### ISSUE TITLE
Segfault saving an alias

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#378]
```
$ cat ~/alias/muttrc
set alias_file=~/alias/aliases
$ touch ~/alias/aliases
```

Launch mutt, 'a' in the index, go through all confirmations: `Alias As, Address, Personal Name, summary [.....]
 Accept? ([yes]/no):`, Type 'y', i get `Bus error` and a crash dump.

Mutt 1.7.2 works just fine.

**Comment by gahr** [comment]
This [commit](https://github.com/neomutt/neomutt/commit/83f7558efab3dcd7b7e227a727ef95f711363f50) introduced
```diff
-WHERE char *AliasFile;
+WHERE LIST *AliasFiles;
```

and the `alias_file` config is set as a string pointing to `AliasFiles` [here](https://github.com/neomutt/neomutt/blob/master/init.h#L126).

Result:
```
(gdb) p *AliasFiles                                                                                                                                              
$8 = {data = 0x61672f656d6f682f <error: Cannot access memory at address 0x61672f656d6f682f>, next = 0x7361696c612f7268}                                          
(gdb) p (char *)AliasFiles                                                                                                                                       
$9 = 0x802d4ac20 "/home/gahr/alias/aliases" 
```

mutt crashes while trying to [access the `data` element](https://github.com/neomutt/neomutt/blob/master/alias.c#L350) during an iteration over the list.

**Comment by gahr** [comment]
@guyzmo will you please take care of this? Thanks!

**Comment by guyzmo** [comment]
oh, sure, thank you. We might want to think a bit more on how we want aliases to work. Because alias files are just a special case of muttrc, I applied the same principle as muttrc. 

Do we want multiple alias files support?
If yes, which file shall mutt modify if there are several?

**Comment by guyzmo** [comment]
I think I'll revert it to a string, because as we support several muttrc, (and alias is a special case of muttrc), if an user want several aliases, he can load them with the other muttrcs. But the alias file target points to the file mutt will write to, and mutt cannot chose which file to change, it needs a single option. 
Therefore, single non-list value should be kept for `alias_file`, not a list.

Any argument to keep it a list?

**Comment by gahr** [comment]
> Any argument to keep it a list?

No, changing it to a list was an error. You get to decide which muttrc file in your `Muttrc` list gets promoted to store aliases, if `alias_file` is not set.

**Comment by guyzmo** [comment]
👌

**Comment by guyzmo** [comment]
so, upsream's behaviour with aliases is a bit weird:

default is set to use `~/.muttrc` as alias file but when you load a muttrc file, then that setting gets overwritten with the loaded muttrc, [happening here](https://github.com/neomutt/neomutt/blob/mutt/default/init.c#L3486,L3490).
 
Here I see three options to cope with our Muttrc list implementation with a scalar AliasFile variable:

1. mimic the original behaviour, and replace the AliasFile variable with either the front or the back of the stack
2. default AliasFile to NONE (i.e. unset) and have that behaviour happen only when alias_file is unset
3. use whatever is in AliasFile, and disrupt the original (weird) behaviour

what would be preferable?

**Comment by guyzmo** [comment]
ok, after discussion with @flatcap:

I'm implementing ②:

- `AliasFile` defaults to `NONE` ;
- when `AliasFile` is set to `NONE`, it uses the latest loaded muttrc ;
- if then no muttrc is loaded, exit gracefully with an error.
