### ISSUE TITLE
Intermittent failure in parallel `make install`

### ISSUE THREAD

**Issue by carlocab** [neomutt/neomutt#3783]
## Expected Behaviour

Trying to build NeoMutt with `./configure && make -j$(nproc) install` should succeed.

## Actual Behaviour

The installation _sometimes_ fails with
```
install: mkdir $PREFIX/share: File exists
```
It seems that there might be a race condition in one of the `Makefile`s.

If NeoMutt crashed, did your OS create a 'coredump' file? N/A

## Steps to Reproduce

Run `./configure --prefix=/tmp/neomutt-test && make -j$(nproc) install`.

## How often does this happen?

Sometimes

## When did it start to happen?

While building version 20230322. I'm not sure if earlier versions are affected, but I didn't notice this occurring previously.

## NeoMutt Version

```
NeoMutt 20230322
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 21.6.0 (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libiconv: 1.11
libidn2: 2.3.4 (compiled with 2.3.4)
GPGME: 1.19.0
OpenSSL: OpenSSL 1.1.1t  7 Feb 2023
libnotmuch: 5.6.0
storage: tokyocabinet, lmdb

Configure options: --prefix=/usr/local/Cellar/neomutt/20230322 --gss --disable-idn --idn2 --lmdb --notmuch --sasl --tokyocabinet --with-gpgme=/usr/local/opt/gpgme --with-lua=/usr/local/opt/lua --with-ssl=/usr/local/opt/openssl@1.1 --with-ui=ncurses

Compilation CFLAGS: -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/local/opt/libgpg-error/include -I/usr/local/Cellar/libassuan/2.5.5/include -I/usr/local/Cellar/gpgme/1.19.0/include -I/usr/local/Cellar/cyrus-sasl/2.1.28_1/include -I/usr/local/include/lua -I/usr/local/Cellar/neomutt/20230322/include -I/usr/local/Cellar/neomutt/20230322/include -DNCURSES_WIDECHAR -I/usr/local/Cellar/neomutt/20230322/include -I/usr
/local/Cellar/openssl@1.1/1.1.1t/include -I/usr/local/Cellar/libidn2/2.3.4_1/include -I/usr/local/Cellar/neomutt/20230322/include -I/usr/local/Cellar/tokyo-cabinet/1.4.48/include -I/usr/local/Cellar/krb5/1.20.1/include

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme
  -gsasl +gss +hcache -homespool +idn -inotify -locales_hack +lua -mixmaster
  +nls +notmuch +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/Cellar/neomutt/20230322/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/Cellar/neomutt/20230322/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version macOS 11, 12, and 13 (i.e. this affects multiple versions of macOS)
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? N/A

**Comment by gahr** [comment]
We can probably mkdir -p all over the place. I can take a look on Monday

**Comment by flatcap** [comment]
We already do!

https://github.com/neomutt/neomutt/blob/47ea003cc41da76a7259c63c138536ddc48a429e/Makefile.autosetup#L31

**Comment by carlocab** [comment]
If it helps, CI logs are available at https://github.com/Homebrew/homebrew-core/actions/runs/4517769789.

Errors are here:
https://github.com/Homebrew/homebrew-core/actions/runs/4517769789/jobs/7959277944#step:7:581 (in `install-contrib`)
https://github.com/Homebrew/homebrew-core/actions/runs/4517769789/jobs/7959278012#step:7:581 (in `install-data`)
https://github.com/Homebrew/homebrew-core/actions/runs/4517769789/jobs/7959278054#step:7:583 (in `install-contrib`)
https://github.com/Homebrew/homebrew-core/actions/runs/4517769789/jobs/7959278087#step:7:584 (in `install-contrib`)

**Comment by flatcap** [comment]
Thanks, that pointed me at a possible problem.

The targets `install-contrib` and `install-data` both install files under `$(DESTDIR)$(datadir)`
(There are no other duplicate dirs in the install)

I think that two `install`s are racing to create this dir.
I've altered the `Makefile` to make that dir a separate build target.
That _should_ mean that, in parallel installs, only **one** thread is trying to create the common dir.

Please can you give branch [[devel/makefile]](https://github.com/neomutt/neomutt/tree/devel/makefile) a try.

Thanks

**Comment by gahr** [comment]
Good catch!

**Comment by carlocab** [comment]
> Please can you give branch [[devel/makefile]](https://github.com/neomutt/neomutt/tree/devel/makefile) a try.

Yes, that seems to work. Of course, one can never be sure with these bugs, but I've run multiple successful builds in Homebrew CI, when previously I would get at least one failing build per run.

**Comment by flatcap** [comment]
YES!
Thanks for your help debugging.

> one can never be sure with these bugs

Indeed :-)
