### ISSUE TITLE
No commands are exposed to Lua in `mutt.command`

### ISSUE THREAD

**Issue by kmarius** [neomutt/neomutt#3784]
## Expected Behaviour

NeoMutt commands should be exposed to Lua via the `mutt.command` table.

## Actual Behaviour

The table is empty.

## Steps to Reproduce

```lua
:lua local c = 0; for _ in pairs(mutt.command) do c = c + 1; end; print(c)
``` 
prints `0` (used to be `60`)

## When did it start to happen?

When I upgraded from `20220429` to `20230322`

## NeoMutt Version

```
NeoMutt 20230322
```

## Extra Info

This looks wrong as `c` doesn't change between iterations. CLion crashed when I tried loading the project so I couldn't actually try it.

https://github.com/neomutt/neomutt/blob/a8bdba23b1bc8f560dd01f1e0ef5f8ef9db392bd/mutt_lua.c#L432-L435

**Comment by flatcap** [comment]
Argh!  Sorry about that.
Please can you give branch [[devel/lua]](https://github.com/neomutt/neomutt/tree/devel/lua) a try.

Thanks

**Comment by kmarius** [comment]
@flatcap That worked, thanks!

**Comment by flatcap** [comment]
No problem.
There'll be a bug-fix release fairly soon.
