### ISSUE TITLE
Lua version issue

### ISSUE THREAD

**Issue by azinsharaf** [neomutt/neomutt#3786]
building from source ( `./configure --everything --disable-doc ` ) returns:
```
Checking for lua ...not found
Checking for lua-5.4 ...not found
Checking for lua-5.3 ...not found
Checking for lua-5.2 ...not found
Error: Unable to find LUA
```
but `lua5.4` already installed.
```
❯ which lua5.4
/usr/bin/lua5.4
```
Does neomutt look for lua that has `-` in its name?
```
❯ which lua-5.4
lua-5.4 not found
```

## NeoMutt Version
from source `2023-03-22`

## Extra Info

* Operating System and its version: WSL (Ubuntu 22.04 LTS)
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No

**Comment by azinsharaf** [comment]
same error using :
`❯ ./configure --everything --disable-doc --with-lua=/usr/bin/lua5.4`

**Comment by flatcap** [comment]
That's the binary, but do you have the development headers and library installed?
The package is called `liblua5.4-dev`

**Comment by azinsharaf** [comment]
oh cool, installing the package fixed it. Thanks!

**Comment by flatcap** [comment]
No problem
