### ISSUE TITLE
S/MIME - encrypt to self on outgoing email

### ISSUE THREAD

**Issue by RichiH** [neomutt/neomutt#38]
Could you adopt https://www.mandarb.com/mutt/patch-1.5.19-ow.smime-encrypt-self.1 or similar?

https://github.com/karelzak/mutt-kz/issues/92 implies that it does not work with 1.6.1 in its current form.

https://www.mandarb.com/mutt/patch-1.5.6-ow.smime_from.1 might also be of value.

**Comment by RichiH** [comment]
http://marc.info/?l=mutt-dev&m=110865683826622

**Comment by flatcap** [comment]
Thanks for the suggestion.  It sounds reasonable.

Currently, I'm busy. I shall try to look at it soon.
Until then, if someone wants to volunteer some code...

**Comment by RichiH** [comment]
@flatcap any update on this? I just got bitten by sending an email which I would need to read again...

**Comment by flatcap** [comment]
Sorry, no progress.
I'm busy today; I shall try to look at it tomorrow.

If the patch still works (or needs only a little work), I'll put it in a devel branch.
I'll let you know.

**Comment by flatcap** [comment]
Well that was unexpected.  The [patch applied](https://github.com/neomutt/neomutt/tree/issue/38) and worked!

However, it took a while to figure out how to test it.
I ended up using two certificates with different passwords.
I encrypted to one as the recipient and to myself as fcc.

It appears to be working as expected.
Please give [this branch](https://github.com/neomutt/neomutt/tree/issue/38) a test and let me know how you get on.

**Comment by flatcap** [comment]
Hi @RichiH 
Have you had a chance to test it? [issue/38](https://github.com/neomutt/neomutt/tree/issue/38)

If it works, and you're quick, I might have time to get it into the release on Friday.

**Comment by RichiH** [comment]
@flatcap I tried to make things compile several times, failed, and am seriously out of playtime atm...

@evgeni @mfvescovi @paravoid: Could one of you poke the magic buttons? @flatcap's Friday carrot sounds nice.

**Comment by flatcap** [comment]
Not to worry, I'll add it anyway.
It's unlikely to impact anyone else even, if it were unstable.

**Comment by evgeni** [comment]
@RichiH @flatcap sorry, I was away. you still need a build of that?

**Comment by flatcap** [comment]
@evgeni
Thanks, but I put it in Saturday's release, so there's no need to build [issue/38].

I'm just waiting on some feedback.

**Comment by RichiH** [comment]
A new package for upstream release would be nice, yes :)
