### ISSUE TITLE
neomutt opens mailboxes much slower than mutt

### ISSUE THREAD

**Issue by sesse** [neomutt/neomutt#3800]
Hi,

I've noticed that neomutt is pretty slow in opening mailboxes. Opening a medium-ish (~15K messages) Maildir box (and then immediately quitting) on my Debian machine uses approx. 1050 ms user CPU time (plus ~500ms system CPU time). mutt (2.0.5) is almost twice as fast, using approx. 600 ms user CPU time. This is with all files in the OS cache.

A quick profiling indicates that most of this slowdown comes from using regexes in the RFC822 parsing (in particular for dates). Regexes are handy for quick one-offs, but much slower than a hand-written parser which was used before. Is it possible to revert back to a hand-rolled parser, if nothing else for the simple cases?

This is neomutt 20201127, but I compiled neomutt from git today (2023-04-04) and it's even worse; 1310 ms.

**Comment by gahr** [comment]
Thanks for profiling it. Does it improve if you configure with `--pcre2`?

**Comment by sesse** [comment]
With PCRE2, it goes down again to 1030 ms (and the profile changes around a fair bit, of course). So it's better, but still slow.

**Comment by gahr** [comment]
I see that too, on my 10k emails test maildir,

| Mutt | NeoMutt |
| ----- | -------- |
| 0.61s | 2.95s |

**Comment by sesse** [comment]
Would you be interested in taking a patch for a fast-path parser if I could get one to work? I.e., something that goes through a plain C path for the simple, well-formed, common cases, and then defers to the regex for the rest. Something like 90–95% of my test mailbox is pretty well-formed, something like

Date: Wed, 17 Sep 2003 08:23:05 +0800

with maybe a comment afterwards and GMT instead of the numeric time zone.

For the I/O, having io_uring would be _really_ nice (even more so for the cold-cache case on rotating disks!), but I have no idea how hard that is to integrate, and it would be Linux-only.

**Comment by gahr** [comment]
> Would you be interested in taking a patch for a fast-path parser if I could get one to work?

I would like to avoid maintaining two parsers.. let me have a look into this some more :)

**Comment by gahr** [comment]
Ok, I rebuilt NeoMutt without address sanitizer and a couple of debug options, now I get results in line with what you reported, with Mutt being ~ 2x faster

| Mutt | NeoMutt |
| ----- | -------- |
| 0.61s | 1.28s |

**Comment by flatcap** [comment]
I just did some timings myself using some Linux Kernel Mailing List headers.
**Data (35MiB):** https://flatcap.org/mutt/dates.xz

**test src:** https://gist.github.com/flatcap/8eb120833f9b25886ff89beea61cd154
**build:**
- build neomutt with pcre2
- `gcc -I. -o test_parse_date test_parse_date.c libmutt.a -lpcre_8`

**Results:** `mutt_date_parse_date()` took 20s to parse 14132174 date lines - that's 700K/s.

**Comment by sesse** [comment]
With PCRE2, the profile does indeed move around and dates are less important, yes. Here's a partial profile of opening a mailbox (it doesn't sum to 100% Because Reasons, so you'll have to multiply a bit mentally):

```
-   46,17%     0,00%  neomutt          neomutt               [.] mx_mbox_open                                              ▒
     mx_mbox_open                                                                                                          ▒
     maildir_mbox_open                                                                                                     ▒
   - maildir_read_dir                                                                                                      ▒
      - 43,64% maildir_delayed_parsing                                                                                     ▒
         - 42,45% maildir_parse_message                                                                                    ▒
            - 42,41% maildir_parse_stream                                                                                  ▒
               - 40,88% mutt_rfc822_read_header                                                                            ▒
                  - 27,92% mutt_rfc822_parse_line                                                                          ▒
                     + 10,21% mutt_addrlist_parse                                                                          ▒
                     + 8,91% mutt_parse_content_type                                                                       ▒
                     + 2,73% mutt_istr_equal                                                                               ▒
                     + 2,26% mutt_extract_message_id                                                                       ▒
                     - 1,62% mutt_date_parse_date                                                                          ▒
                          0,61% mutt_date_check_month                                                                      ▒
                  - 5,45% rfc2047_decode_envelope                                                                          ▒
                     + 2,93% rfc2047_decode_addrlist                                                                       ▒
                     + 2,41% rfc2047_decode                                                                                ▒
                    2,63% mutt_rfc822_read_line                                                                            ▒
                    0,74% mutt_str_skip_email_wsp                                                                          ▒
                    0,52% cs_subset_regex                                                                                  ▒
           0,59% progress_update                                                                                           ▒
      - 1,46% maildir_move_to_mailbox                                                                                      ▒
         - 0,62% log_disp_curses                                                                                           ▒
              cs_subset_number                                                                                             ▒
        1,01% maildir_parse_dir    
```

Or flat:

```
   4,88%  neomutt          libpcre2-8.so.0.10.1  [.] pcre2_match_8                                                         ◆
   4,78%  neomutt          libc-2.31.so          [.] __strchr_avx2_rtm                                                     ▒
   4,20%  neomutt          neomutt               [.] gen_string_hash                                                       ▒
   4,13%  neomutt          neomutt               [.] mutt_str_copy                                                         ▒
   2,90%  neomutt          libc-2.31.so          [.] _int_free                                                             ▒
   2,32%  neomutt          libc-2.31.so          [.] _int_malloc                                                           ▒
   2,20%  neomutt          libc-2.31.so          [.] __vfscanf_internal                                                    ▒
   2,16%  neomutt          neomutt               [.] next_token                                                            ▒
   2,08%  neomutt          neomutt               [.] union_hash_find_elem                                                  ▒
   1,94%  neomutt          neomutt               [.] mutt_rfc822_read_line                                                 ▒
   1,91%  neomutt          libc-2.31.so          [.] __strcasecmp_l_avx                                                    ▒
   1,89%  neomutt          neomutt               [.] mutt_addrlist_clear                                                   ▒
   1,87%  neomutt          libc-2.31.so          [.] malloc_consolidate                                                    ▒
   1,68%  neomutt          neomutt               [.] mutt_str_is_email_wsp                                                 ▒
   1,52%  neomutt          libc-2.31.so          [.] __memmove_avx_unaligned_erms_rtm                                      ▒
   1,35%  neomutt          libc-2.31.so          [.] __strcmp_avx2_rtm                                                     ▒
   1,27%  neomutt          neomutt               [.] mutt_rfc822_parse_line                                                ▒
   1,23%  neomutt          libc-2.31.so          [.] cfree@GLIBC_2.2.5                                                     ▒
   1,20%  neomutt          libc-2.31.so          [.] unlink_chunk.constprop.0                                              ▒
   1,17%  neomutt          libc-2.31.so          [.] _IO_fgets                                                             ▒
   1,16%  bash             bash                  [.] utf8_mbsmbchar                                                        ▒
   1,06%  neomutt          libc-2.31.so          [.] __strlen_avx2_rtm                     
```

**Comment by sesse** [comment]
I noticed neomutt compiles by default without any optimization; setting CFLAGS="-O2 -g" takes me down to 800ms or so, slowly nearing mutt. This patch buys a couple of percent on top of that:

```diff
diff --git a/mutt/string.c b/mutt/string.c
index 53112979b..dff368ab4 100644
--- a/mutt/string.c
+++ b/mutt/string.c
@@ -687,16 +687,6 @@ char *mutt_str_skip_email_wsp(const char *s)
   return (char *) s;
 }
 
-/**
- * mutt_str_is_email_wsp - Is this a whitespace character (for an email header)
- * @param c Character to test
- * @retval true It is whitespace
- */
-bool mutt_str_is_email_wsp(char c)
-{
-  return c && strchr(" \t\r\n", c);
-}
-
 /**
  * mutt_str_lws_len - Measure the linear-white-space at the beginning of a string
  * @param s String to check
diff --git a/mutt/string2.h b/mutt/string2.h
index f7f147e2b..76653c9a1 100644
--- a/mutt/string2.h
+++ b/mutt/string2.h
@@ -62,7 +62,6 @@ const char *mutt_str_find_word(const char *src);
 const char *mutt_str_getenv(const char *name);
 bool        mutt_str_inline_replace(char *buf, size_t buflen, size_t xlen, const char *rstr);
 bool        mutt_str_is_ascii(const char *str, size_t len);
-bool        mutt_str_is_email_wsp(char c);
 size_t      mutt_str_len(const char *a);
 char *      mutt_str_lower(char *str);
 size_t      mutt_str_lws_len(const char *s, size_t n);
@@ -103,4 +102,14 @@ int         mutt_istrn_cmp(const char *a, const char *b, size_t num);
 bool        mutt_istrn_equal(const char *a, const char *b, size_t num);
 const char *mutt_istrn_rfind(const char *haystack, size_t haystack_length, const char *needle);
 
+/**
+ * mutt_str_is_email_wsp - Is this a whitespace character (for an email header)
+ * @param c Character to test
+ * @retval true It is whitespace
+ */
+static inline bool mutt_str_is_email_wsp(char c)
+{
+  return c == ' ' || c == '\t' || c == '\r' || c == '\n';
+}
+
 #endif /* MUTT_LIB_STRING2_H */
```

**Comment by sesse** [comment]
Here's a very hacky patch to reduce the flood of syscalls somewhat, I think it helps maybe 50–100ms (but I have no guarantees it is correct!):

```diff
--- a/email/parse.c
+++ b/email/parse.c
@@ -1188,11 +1188,13 @@ struct Envelope *mutt_rfc822_read_header(FILE *fp, struct Email *e, bool user_hd
     }
   }
 
-  while ((loc = ftello(fp)) != -1)
+  loc = 0;
+  while (loc != -1)
   {
     line = mutt_rfc822_read_line(fp, line, &linelen);
     if (*line == '\0')
       break;
+    loc += linelen;
     p = strpbrk(line, ": \t");
     if (!p || (*p != ':'))
     {
```

ftell() unfortunately needs to ask the OS every time, in case someone else repositioned the underlying file handle. So there's a ton of lseek() calls to get the offset.

**Comment by sesse** [comment]
Some more low-hanging strchr() fruit:

```diff
diff --git a/address/address.c b/address/address.c
index 7e4f56b2b..5b760864b 100644
--- a/address/address.c
+++ b/address/address.c
@@ -45,7 +45,7 @@ const char AddressSpecials[] = "@.,:;<>[]\\\"()";
  * is_special - Is this character special to an email address?
  * @param ch Character
  */
-#define is_special(ch) strchr(AddressSpecials, ch)
+#define is_special(ch) (ch == '@' || ch == '.' || ch == ',' || ch == ':' || ch == ';' || ch == '<' || ch == '>' || ch == '[' || ch == ']' || ch == '\\' || ch == '"' || ch == '(' || ch == ')')
 
 /**
  * AddressError - An out-of-band error code
```

Reducing config lookups by a lot (which require a lot of hashing of the same string, over and over; this can probably be done much better for static strings, too):

```diff
diff --git a/email/parse.c b/email/parse.c
index 2bcc1ff9f..a0ab88806 100644
--- a/email/parse.c
+++ b/email/parse.c
@@ -112,6 +112,8 @@ static void parse_parameters(struct ParameterList *pl, const char *s, bool allow
   struct Parameter *pnew = NULL;
   const char *p = NULL;
   size_t i;
+  const struct Slist *const c_assumed_charset =
+    cs_subset_slist(NeoMutt->sub, "assumed_charset");
 
   struct Buffer *buf = mutt_buffer_pool_get();
   /* allow_value_spaces, especially with autocrypt keydata, can result
@@ -164,8 +166,6 @@ static void parse_parameters(struct ParameterList *pl, const char *s, bool allow
           s++;
           for (; *s; s++)
           {
-            const struct Slist *const c_assumed_charset =
-                cs_subset_slist(NeoMutt->sub, "assumed_charset");
             if (c_assumed_charset)
             {
               // As iso-2022-* has a character of '"' with non-ascii state, ignore it
diff --git a/email/rfc2047.c b/email/rfc2047.c
index 43648fe7d..779acacde 100644
--- a/email/rfc2047.c
+++ b/email/rfc2047.c
@@ -780,10 +780,11 @@ void rfc2047_decode_addrlist(struct AddressList *al)
   if (!al)
     return;
 
+  const struct Slist *const c_assumed_charset = cs_subset_slist(NeoMutt->sub, "assumed_charset");
+
   struct Address *a = NULL;
   TAILQ_FOREACH(a, al, entries)
   {
-    const struct Slist *const c_assumed_charset = cs_subset_slist(NeoMutt->sub, "assumed_charset");
     if (a->personal && ((strstr(a->personal, "=?")) || c_assumed_charset))
     {
       rfc2047_decode(&a->personal);
diff --git a/mutt_logging.c b/mutt_logging.c
index 78e0442eb..75ac4b888 100644
--- a/mutt_logging.c
+++ b/mutt_logging.c
@@ -87,7 +87,13 @@ void mutt_clear_error(void)
 int log_disp_curses(time_t stamp, const char *file, int line,
                     const char *function, enum LogLevel level, ...)
 {
-  const short c_debug_level = cs_subset_number(NeoMutt->sub, "debug_level");
+  static bool fetched_debug_level = false;
+  static short c_debug_level;
+  if (!fetched_debug_level)
+  {
+    c_debug_level = cs_subset_number(NeoMutt->sub, "debug_level");
+    fetched_debug_level = true;
+  }
   if (level > c_debug_level)
     return 0;
```

After all of these patches, neomutt is ever so slightly faster than mutt here (with warm cache on both sides). That is not to say it shouldn't be much faster still, though :-)

With cold cache, both of them are very slow—10+ seconds real time.

**Comment by gahr** [comment]
+1 to making `mutt_str_is_email_wsp` inline and to reading `assumed_charset` outside the loop. The other two suggested patches are wrong, though: in `mutt_rfc822_read_header` we need to be able to get back to the begin of the line in case it isn't a real header line. Not saying this can't be done w/o lseek, but it'll require some more work; the last patch assumes `debug_level` never changes at runtime, which is a feature we support.

**Comment by sesse** [comment]
Not surprised some of them are wrong :-) Note that `mutt_str_is_email_wsp` is also changed to using a simple series of ifs. The compiler is able to convert that into indexing into a bit field, which is much faster than anything strchr can do (although Clang creates somewhat more compact code than GCC here).

The idea of doing without lseek() is that we keep track of the offset ourselves, through the `loc += linelength` patch. But I'm not sure at all whether that is actually the right byte position. The best thing here would probably be to avoid synchronous I/O totally, though, and read the first 4 kB or so of the file into RAM asynchronously and parse it that way, but that's a bigger project than one night :-)

I think expanding `is_special()` was something like 1% here, but it's not large, and I haven't set up anything to measure everything finely. I guess the problem is that there are so many small places, so a bunch of 1% wins are needed to get it down to a good level (and then new wins would have to go by multithreading).

**Comment by sesse** [comment]
Given how often debug_level is checked, perhaps it's possible to cache it in a global variable and then clear that cache whenever any variable is set?

**Comment by gahr** [comment]
> I guess the problem is that there are so many small places, so a bunch of 1% wins are needed to get it down to a good level

I agree with this - we have been busy refactoring and trying to make the code nice, but we haven't really worked on small optimizations (yet).

Would you like to contribute in that direction? A PR would be best :)

**Comment by sesse** [comment]
I can send the patches so far as individual PRs, at least? I can't promise going all the way, though.

I did a small io_uring microbenchmark; open 15k files in a Maildir and read the first 4 kB, with fopen+fread+fclose versus io_uring. For in-cache, io_uring was about twice as fast (it's possible to go lower with direct file descriptors and such, I didn't bother), but cold-cache on my rotating drives, the difference was 15-40x! So there's definitely some promise there if one is comfortable with going async.

**Comment by gahr** [comment]
> I can send the patches so far as individual PRs, at least? I can't promise going all the way, though.

sure, thanks!

Btw, are you aware of our header_cache? I recommend you use it if you often open big mailboxes

**Comment by sesse** [comment]
I used to use the header_cache; I don't remember why I don't anymore (my .muttrc is 20+ years old by now…). The header_cache helps by a couple hundred ms, but it's not a gamechanger on hot cache, at least. With cold cache, it might help a fair amount (I haven't tested).

**Comment by flatcap** [comment]
> async

That would be the dream...

We're getting closer to the day when threads would be possible.
Mutt's code is a mess of spaghetti and global variables.
We've made a lot of progress modernising the code: eliminating globals, more apis, notifications.
But we've still got a way to go.

**Comment by sesse** [comment]
You don't need threads to do async I/O, though. (You would need it to do header parsing in parallel.) But yes, I realize this isn't necessarily easy at all.

**Comment by sesse** [comment]
I sent a few PRs. With some luck, I didn't mess up too badly. (I tried running the test suite, but a bunch of tests fail here even with an unmodified tree…)

**Comment by flatcap** [comment]
> but a bunch of tests fail here

You'll need the test files for some tests.

Files and instructions, here: https://github.com/neomutt/neomutt-test-files

The tests get run automatically on every PR.
You can find them in the "ASAN Tests" and "Build and Test" checks.

**Comment by sesse** [comment]
Ah. I tried searching around, but couldn't fint it. Now everything seems to pass, at least on one of the branches:

SUCCESS: All unit tests have passed.

**Comment by flatcap** [comment]
Thanks for the PRs.

I sent you an invitation to join NeoMutt, to the address in the commit headers: `sgunderson@XXX`, but it bounced.
```
<sgunderson@XXX>: host aspmx.l.google.com[2a00:1450:4025:402::1b] said:
    550-5.1.1 The email account that you tried to reach does not exist. Please
    try 550-5.1.1 double-checking the recipient's email address for typos or
    550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1
    https://support.google.com/mail/?p=NoSuchUser
    r13-20020a170906a20d00b0092d6e62eb2bsi864943ejy.197 - gsmtp (in reply to
    RCPT TO command
```

I resent the email to the address on your website.

**Comment by sesse** [comment]
Sorry, I switched addresses many years ago (out of necessity); the old one still lingers in a few machines and places.

Thanks for the invitation! Unfortunately, I won't be staying; I'll send my patches until I can't find anything obvious to speed up, and then probably be on my my way. I have too many other projects languishing already :-)

**Comment by sesse** [comment]
I'm going to close this; after the current PRs, it's about where mutt is (perhaps slightly faster). Further discussion can happen on the concrete patches; thanks for being to fast about reviewing them!

**Comment by flatcap** [comment]
Thank **you** very much!
