### ISSUE TITLE
[RFC] change UPPERCASE types into type_t or struct Type

### ISSUE THREAD

**Issue by guyzmo** [neomutt/neomutt#381]
Because the usage is to use `ALL_UPPER_CASE` to either macro definitions or global constants, whereas typing is better suited with:

- `type_t` for opaque types, and
- `struct Type` for public type (not using a typedef)

following up on discussion in #369.

**Comment by gahr** [comment]
I would avoid _t for non-opaque types.

**Comment by guyzmo** [comment]
what do you mean by *non-opaque* types ? types you directly access members from instead of using function handlers?

**Comment by gahr** [comment]
Yes, types you know the internals of. The rationale is that with foo_t is not clear wheter you have a pod type, a struct, or a pointer. I would raher spell struct Foo.

**Comment by gahr** [comment]
.. as it shows, it's too late for me to type anything that makes any sense.. let's talk tomorrow :)

**Comment by guyzmo** [comment]
so you'd be against typedef'ing the `struct {}` types?

**Comment by d-k-c** [comment]
Some explanations about that can be found in Linux's Coding Style:
https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst#5-typedefs

But Linux has to deal with portability (but in a difference sense than Neomutt, because the kernel has different implementations of some structs for different architectures, while Neomutt, as a userspace application, tries to have one implementation to rule them all).

In Neomutt context, if we follow the typedef-for-opaque philosophy, I would argue that most structures should not be opaque, but that doesn't mean we can make/use accessors on these structs.
Maybe, some day, eventually, we will be able to split the UI and the core (ie. the core would be a library). In that situation, the UI would interact with the lib using opaque types and accessors. But I should stop daydreaming :)

**Comment by gahr** [comment]
As much as it hurts to say so, I completely agree with Linus here :)

**Comment by gahr** [comment]
>  I would argue that most structures should not be opaque

I think so too

**Comment by flatcap** [comment]
How does this look?

| Current Name          | Current typedef | New Name           |     
| :-------------------- | :-------------- | :----------------- |                               
| struct account        | ACCOUNT         | struct Account     |                               
| struct address_t      | ADDRESS         | struct Address     |                               
| struct alias          | ALIAS           | struct Alias       |                               
| struct attachptr      | ATTACHPTR       | struct AttachPtr   |                               
| struct body           | BODY            | struct Body        |                               
| struct body_cache     | body_cache_t    | struct BodyCache   |                               
| struct buffer         | BUFFER          | struct Buffer      |                               
| struct buffy_t        | BUFFY           | struct Buffy       |                               
| struct ciss_url       | ciss_url_t      | struct CissUrl     |                               
| struct _connection    | CONNECTION      | struct Connection  |                               
| struct content        | CONTENT         | struct Content     |                               
| struct _context       | CONTEXT         | struct Context     |                               
| struct enter_state    | ENTER_STATE     | struct EnterState  |                               
| struct envelope       | ENVELOPE        | struct Envelope    |                               
| struct group_t        | group_t         | struct Group       |                               
| struct hash           | HASH            | struct Hash        |                               
| struct header         | HEADER          | struct Header      |                               
| struct list_t         | LIST            | struct List        |                               
| struct _mbchar_table  | mbchar_table    | struct MbCharTable |                               
| struct menu_t         | MUTTMENU        | struct Menu        |                               
| struct _message       | MESSAGE         | struct Message     |                               
| struct mutt_thread    | THREAD          | struct MuttThread  |                               
| struct mutt_window    | mutt_window_t   | struct MuttWindow  |                               
| struct parameter      | PARAMETER       | struct Parameter   |                               
| struct pattern_t      | pattern_t       | struct Pattern     |                               
| struct pgp_keyinfo    | pgp_key_t       | struct PgpKeyinfo  |                               
| struct progress       | progress_t      | struct Progress    |                               
| struct regexp         | REGEXP          | struct Regex       |                               
| struct replace_list_t | REPLACE_LIST    | struct ReplaceList |                               
| struct rx_list_t      | RX_LIST         | struct RxList      |                               
| struct state          | STATE           | struct State       |

**Comment by gahr** [comment]
> How does this look?

so beautiful I want o cry ;)

**Comment by flatcap** [comment]
Here's batch 2.
All that's left is a handful of typedef'd functions and 4 typedef'd enums.

| Current Name                 | Current typedef       | New Name                   |
| :--------------------------- | :-------------------- | :------------------------- |
| struct _ansi_attr            | ansi_attr             | struct AnsiAttr            |
| struct color_line            | COLOR_LINE            | struct ColorLine           |
| struct color_list            | COLOR_LIST            | struct ColorList           |
| struct crypt_entry           | crypt_entry_t         | struct CryptEntry          |
| struct crypt_keyinfo         | crypt_key_t           | struct CryptKeyinfo        |
| struct crypt_module*         | crypt_module_t        | struct CryptModule         |
| struct entry                 | ENTRY                 | struct Entry               |
| struct flowed_state          | flowed_state_t        | struct FlowedState         |
| struct folder_t              | FOLDER                | struct Folder              |
| struct group_context_t       | group_context_t       | struct GroupContext        |
| struct hook                  | HOOK                  | struct Hook                |
| struct imap_header_data      | IMAP_HEADER_DATA      | struct ImapHeaderData      |
| struct mixchain              | MIXCHAIN              | struct Mixchain            |
| struct myvar                 | myvar_t               | struct MyVar               |
| struct pgp_entry             | pgp_entry_t           | struct PgpEntry            |
| struct pgp_signature         | pgp_sig_t             | struct PgpSignature        |
| struct pgp_uid               | pgp_uid_t             | struct PgpUid              |
| struct query                 | QUERY                 | struct Query               |
| struct type2                 | REMAILER              | struct Remailer            |
| struct rfc1524_mailcap_entry | rfc1524_entry         | struct Rfc1524MailcapEntry |
| struct score_t               | SCORE                 | struct Score               |
| struct sidebar_entry         | SBENTRY               | struct SbEntry             |
| struct smime_key             | smime_key_t           | struct SmimeKey            |

**Comment by flatcap** [comment]
The more I look, the more I find...
My original searches missed all the anonymous structs that were typedef'd.
Here they are:

| Current typedef       | New Name                 |
| :-------------------- | :----------------------- |
| ATTACH_MATCH          | struct AttachMatch       |
| CHILD_CTX             | struct ChildCtx          |
| compose_redraw_data_t | struct ComposeRedrawData |
| COMPRESS_INFO         | struct CompressInfo      |
| CONTENT_STATE         | struct ContentState      |
| event_t               | struct Event             |
| FETCH_CTX             | struct FetchCtx          |
| hcache_db_ctx_t       | struct HcacheDbCtx       |
| hcache_lmdb_ctx_t     | struct HcacheLmdbCtx     |
| imap_auth_t           | struct ImapAuth          |
| IMAP_CACHE            | struct ImapCache         |
| IMAP_COMMAND          | struct ImapCommand       |
| IMAP_DATA             | struct ImapData          |
| IMAP_HEADER           | struct ImapHeader        |
| IMAP_LIST             | struct ImapList          |
| IMAP_MBOX             | struct ImapMbox          |
| IMAP_STATUS           | struct ImapStatus        |
| NEWSRC_ENTRY          | struct NewsrcEntry       |
| NNTP_ACACHE           | struct NntpAcache        |
| NNTP_DATA             | struct NntpData          |
| NNTP_HEADER_DATA      | struct NntpHeaderData    |
| NNTP_SERVER           | struct NntpServer        |
| pager_t               | struct Pager             |
| pager_redraw_data_t   | struct PagerRedrawData   |
| pattern_cache_t       | struct PatternCache      |
| pop_auth_t            | struct PopAuth           |
| POP_CACHE             | struct PopCache          |
| POP_DATA              | struct PopData           |
| SASL_DATA             | struct SaslData          |
| SHA1_CTX              | struct Sha1Ctx           |
| sslsockdata           | struct SslSockData       |
| TUNNEL_DATA           | struct TunnelData        |

**Comment by flatcap** [comment]
For completeness, here are the remaining plain structs and their new names:

| Current struct         | New Name                 |
| :--------------------- | :----------------------- |
| b64_context            | B64Context               |
| binding_t              | Binding                  |
| browser_state          | BrowserState             |
| command_t              | Command                  |
| compile_options        | CompileOptions           |
| coord                  | Coord                    |
| crypt_cache            | CryptCache               |
| crypt_module_functions | CryptModuleFunctions     |
| crypt_module_specs     | CryptModuleSpecs         |
| dn_array_s             | DnArrayS                 |
| enriched_state         | EnrichedState            |
| extkey                 | Extkey                   |
| fgetconv_not           | FgetConvNot              |
| fgetconv_s             | FgetConvS                |
| folder_file            | FolderFile               |
| hash_elem              | HashElem                 |
| hash_walk_state        | HashWalkState            |
| hdr_format_info        | HdrFormatInfo            |
| header_cache           | HeaderCache              |
| history                | History                  |
| keymap_t               | Keymap                   |
| line_t                 | Line                     |
| maildir                | Maildir                  |
| mapping_t              | Mapping                  |
| md5_ctx                | Md5Ctx                   |
| mh_data                | MhData                   |
| mh_sequences           | MhSequences              |
| m_update_t             | MUpdate                  |
| mx_ops                 | MxOps                    |
| nm_ctxdata             | NmCtxdata                |
| nm_hdrdata             | NmHdrdata                |
| nm_hdrtag              | NmHdrtag                 |
| option_t               | Option                   |
| pattern_flags          | PatternFlags             |
| pgp_cache              | PgpCache                 |
| pgp_command_context    | PgpCommandContext        |
| q_class_t              | QClass                   |
| range_regexp           | RangeRegex               |
| resize                 | Resize                   |
| rfc2231_parameter      | Rfc2231Parameter         |
| smime_command_context  | SmimeCommandContext      |
| syntax_t               | Syntax                   |
| sysexits               | Sysexits                 |
| _tlssockdata           | TlsSockData              |
| tz_t                   | Tz                       |
| uri_tag                | UriTag                   |

**Comment by flatcap** [comment]
A final batch

## Renamed struct/enum/union

| Old Name           | New Name          |
| :----------------- | :---------------- |
| Capability_Aliases | CapabilityAliases |
| Capability_Alias   | CapabilityAlias   |
| CryptKeyinfo       | CryptKeyInfo      |
| div_type           | DivType           |
| DnArrayS           | DnArray           |
| FgetConvS          | FgetConv          |
| format_flag        | FormatFlag        |
| group_state_t      | GroupState        |
| hash_key           | HashKey           |
| hcache_ops_t       | HcacheOps         |
| history_class_t    | HistoryClass      |
| imap_auth_res_t    | ImapAuthRes       |
| IMAP_COMMAND_TYPE  | ImapCommandType   |
| key_cap_t          | KeyCap            |
| mdb_txn_mode       | MdbTxnMode        |
| NmCtxdata          | NmCtxData         |
| NmHdrdata          | NmHdrData         |
| NmHdrtag           | NmHdrTag          |
| packet_tags        | PacketTags        |
| pattern_exec_flag  | PatternExecFlag   |
| pgp_ring_t         | PgpRing           |
| pop_auth_res_t     | PopAuthRes        |
| sb_src             | SidebarSrc        |
| Sysexits           | SysExits          |
| url_scheme_t       | UrlScheme         |
| validate           | Validate          |
| XDGType            | XdgType           |

## Renamed enum constants

| Old Name          | New Name          |
| :---------------- | :---------------- |
| kXDGConfigDirs    | XDG_CONFIG_DIRS   |
| kXDGConfigHome    | XDG_CONFIG_HOME   |
| ADDR              | GS_ADDR           |
| NONE              | GS_NONE           |
| RX                | GS_RX             |
| txn_read          | TXN_READ          |
| txn_uninitialized | TXN_UNINITIALIZED |
| txn_write         | TXN_WRITE         |

## Renamed struct members

| Old Name       | New Name        |
| :------------- | :-------------- |
| firstMessage   | first_message   |
| hideQuoted     | hide_quoted     |
| lastCached     | last_cached     |
| lastLine       | last_line       |
| lastLoaded     | last_loaded     |
| lastMessage    | last_message    |
| lineInfo       | line_info       |
| maxLine        | max_line        |
| newMailCount   | new_mail_count  |
| QuoteList      | quote_list      |
| SearchBack     | search_back     |
| SearchCompiled | search_compiled |
| searchDir      | search_dir      |
| SearchFlag     | search_flag     |
| SearchRE       | search_re       |
| WrapMargin     | wrap_margin     |
