### ISSUE TITLE
figure out how many // clang-format [off/on] lines we have to use for clang-format

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#382]
Like i said in [this issue](https://github.com/neomutt/neomutt/issues/224), automatically applying clang-format to our codebase doesn't work, because then diffs like this may happen:

```diff
-#define digitp(p)   (*(p) >= '0' && *(p) <= '9')
-#define hexdigitp(a) (digitp (a)                     \
-                      || (*(a) >= 'A' && *(a) <= 'F')  \
-                      || (*(a) >= 'a' && *(a) <= 'f'))
-#define xtoi_1(p)   (*(p) <= '9'? (*(p)- '0'): \
-                     *(p) <= 'F'? (*(p)-'A'+10):(*(p)-'a'+10))
-#define xtoi_2(p)   ((xtoi_1(p) * 16) + xtoi_1((p)+1))
+#define digitp(p) (*(p) >= '0' && *(p) <= '9')
+#define hexdigitp(a)                                                           \
+  (digitp(a) || (*(a) >= 'A' && *(a) <= 'F') || (*(a) >= 'a' && *(a) <= 'f'))
+#define xtoi_1(p)                                                              \
+  (*(p) <= '9' ? (*(p) - '0') : *(p) <= 'F' ? (*(p) - 'A' + 10)                \
+                                            : (*(p) - 'a' + 10))
+#define xtoi_2(p) ((xtoi_1(p) * 16) + xtoi_1((p) + 1))
```

That means, for this part of the code, we have to surround it with `// clang-format off` and `// clan-format on`.  That means we have to figure ot in how many places we have to do that.

**Comment by toogley** [comment]
I think, i can tackle this somewhere in the future..

**Comment by toogley** [comment]
I work on the branch [devel/fix-codingstyle-clang-format](https://github.com/neomutt/neomutt/tree/devel/fix-codingstyle-clang-format) on this issue.

**Comment by toogley** [comment]
@neomutt/reviewers how should i handle `ifndef` walls?

from [lib.h](https://github.com/neomutt/neomutt/blob/master/lib.h):
```
#ifndef _LIB_H
# define _LIB_H

# include <stdio.h>
# include <string.h>
# ifdef HAVE_UNISTD_H
#  include <unistd.h> /* needed for SEEK_SET */
# endif
# include <sys/types.h>
# include <sys/stat.h>
# include <time.h>
# include <limits.h>
# include <stdarg.h>
# include <stdbool.h>
# include <signal.h>

# ifndef _POSIX_PATH_MAX
#  include <limits.h>
# endif
```
if i don't put a `// clang-format [off/on]` line into it, clang-format will reformat that to:
```
#ifndef _LIB_H
#define _LIB_H

#include <stdio.h>
#include <string.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h> /* needed for SEEK_SET */
#endif
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>
#include <limits.h>
#include <stdarg.h>
#include <stdbool.h>
#include <signal.h>

#ifndef _POSIX_PATH_MAX
#include <limits.h>
#endif
```

putting `clang-format [off/on]` in lib.h is IMHO not a nice solution, because either we have to use a lot of those comments all over the code or we don't put anything in there and try to life with the ugly  reformatting.

**Comment by gahr** [comment]
I would not indent preprocessor directives surrounded by #ifndef , as that is used all around our header files as include guard.

**Comment by guyzmo** [comment]
generally speaking I like to have indented preprocessor directives, with the `#` at column 0. With the exception of guards (for which I prefer the usage of `#pragma once`, even if it's not in standard).

The places where it's really useful is in places where there's a high cyclometric complexity in the preprocessor code. But when it happens, we shouldn't try to make the macros readable, we should get rid of them.

But for the sake of simplicity, if clang-format does not allow it, then it shall go away.
