### ISSUE TITLE
Maildir: Custom field delimiter

### ISSUE THREAD

**Issue by asdf8dfafjk** [neomutt/neomutt#3832]
Hello, I'd like to make a feature request. Please let me know what you think. I should note that my knowledge of email standards and neomutt user facing configuration is very little. (and no knowledge of its source code)

Rough proposal:

mbsync allows a variable `FieldDelimiter` to be set in it's config file which is a character that is used instead of `:` in the filename of fetched maildir email files. However, when neomutt either marks an email read (by transferring from `new/` to `cur/`) or copies/moves it, it uses the `:` character again. My proposal is to allow a configuration variable, a la `confirmappend` whose present value would dictate what field delimiter is to be used for saving the maildir email file. 

Assuming this is sane, is this something that would be acceptable to you?

If it is acceptable to you, would you allow a "drive-by" PR by me where you point me to the list of places where such a setting might be needed and I, figure out the exact change, make it, test it and submit a patch? 

The goal is to minimize collective time spent while also adding what is hopefully a useful feature. 

My motivation behind this is that I'd like to sync all my emails using syncthing after removing them from my provider's cloud. Windows and Android don't allow `:` character in files. 

Sorry for not using the template, I wrote it in vi before posting it. 

 

#### What would you like to be able to do?

A Custom field delimiter which can be used in place of `:`

 

#### What needs to change in NeoMutt?

 Don't know on source level but from user perspective, an option to allow such a delimiter and neomutt using that in place of colon when it wants to save a maildir file. 

#### Have you tried any alternative methods? 

Can't think of one ... 

 

#### Additional Info.

 I know C and Rust so I can work on this

**Comment by flatcap** [comment]
After a bit of discussion on IRC... we like the idea.
We think NeoMutt should be strict -- Create a config variable for the delimiter, then should only read and write that character.

Some pointers to get started:
Maildir has its own config:
https://github.com/neomutt/neomutt/blob/78f126127b47b266712c2d19026c53cc6e4dc5bb/maildir/config.c#L37

If you create a new `DT_STRING` config, then you can restrict it with a validator function:
https://github.com/neomutt/neomutt/blob/78f126127b47b266712c2d19026c53cc6e4dc5bb/notmuch/config.c#L110-L112
https://github.com/neomutt/neomutt/blob/78f126127b47b266712c2d19026c53cc6e4dc5bb/notmuch/config.c#L53-L65

Feel free to ask lots of questions

**Comment by flatcap** [comment]
Merged in #3852
