### ISSUE TITLE
imap/imap.c runtime error: null pointer passed as argument 1, which is declared to never be null

### ISSUE THREAD

**Issue by croyleje** [neomutt/neomutt#3833]
## Expected Behavior
When deleting messages from INBOX messages should be moved to the TRASH folder.

## Actual Behavior
When messages are deleted a run time error is thrown.
`Copying 1 message to [Gmail]/Trash...imap/imap.c:1660:5: runtime error: null pointer passed as argument 1, which is declared to never be null`

Then another runtime error is received directly after this error.
`imap/imap.c:1663:5: runtime error: null pointer passed as argument 1, which is declared to never be null`

Neomutt does not crash and the messages do appear to be moved but the error throw the display off so it become unusable until you logout and back in.

## Steps to Reproduce
Delete a message from the INBOX of a Gmail (Remote) account.

## How often does this happen?
Seems to happen every time when deleting from the INBOX but when deleting from the SPAM folder or the TRASH folder it only seems to happen sometimes.

## When did it start to happen?
Started after Arch maintainers enabled the `--ubsan` build flag.

## NeoMutt Version
NeoMutt 20230407

```
NeoMutt 20230407
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.2.12-arch1-1 (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libidn2: 2.3.4 (compiled with 2.3.4)
GPGME: 1.19.0
GnuTLS: 3.8.0
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --ubsan --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/neomutt/src=/usr/src/debug/neomutt -flto=auto -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.3 -I/usr/include -I/usr/include -I/usr/include -DNCURSES_WIDECHAR -I/usr/include/p11-kit-1 -I/usr/include -I/usr/include -fsanitize=undefined -O0 -fno-omit-frame-pointer -fno-common

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme
  -gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster
  +nls +notmuch -openssl +pgp +regex +sasl +smime +sqlite +sun_attachment

Devel options:
  ubsan

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info
Arch Linux 6.2.12-arch1-1
Problem only seems to occur on remote (IMAP) accounts.

PLEASE SEE issue #3774 

This issue appears to be related to the referenced issue #3774 I have also messaged the Arch package maintainers to notify them of the issues.  As previously stated in my comments on the similar issue I am unsure who should be dealing with this issue but I can confirm building Neomutt without the `--ubsan` flag does fix the issue.

If there is any other information I can supply please ask.

Thank you,

Jason C.

**Comment by gahr** [comment]
Can you please give the branch devel/issue-3833 a try?
