### ISSUE TITLE
neomutt startup is very-very slow

### ISSUE THREAD

**Issue by 4nd3r** [neomutt/neomutt#3860]
I have following in my `neomuttrc`:
```
mailboxes \
$spool_file \
$record \
$trash \
=Archive \
`find ~/Documents/mail -type f | sort -r | paste -sd ' '`
```

`~/Documents/mail` contains ~20 years of mail archive as regular mbox files and since **2023-05-12** startup takes ~30 seconds.

`neomutt -d5` generated 4.8G `.neomuttdebug0` containing 37268323 lines starting with:
`is_from() Could not parse From line: ...`

`git bisect` says:
3cd41dd39ae65a4bee46033e70c302fcd678e23c is the first bad commit.

If I remove `~/Documents/mail` part then everything is blazing fast again.

**Comment by gahr** [comment]
Thanks for the report. How much does it take to start up w/ `~/Documents/mail` if you revert https://github.com/neomutt/neomutt/commit/3cd41dd39ae65a4bee46033e70c302fcd678e23c?

(btw, I think you should get the same `is_from() Could not parse From line: ...` lines with and without that commit).

**Comment by 4nd3r** [comment]
It's not possible to revert 3cd41dd39ae65a4bee46033e70c302fcd678e23c:
```
$ git revert 3cd41dd39ae65a4bee46033e70c302fcd678e23c
Auto-merging email/parse.c
CONFLICT (content): Merge conflict in email/parse.c
Auto-merging email/parse.h
Auto-merging pattern/exec.c
CONFLICT (content): Merge conflict in pattern/exec.c
error: could not revert 3cd41dd39... Use Buffer in mutt_rfc822_read_line()
```

But if I check out commit before that (76c62b1716d317427fa844a668516b477f0ce22d), then startup takes ~3 seconds (which I consider fine). And with `-d5` there are no `is_from()...` lines in `.neomuttdebug0`.

**Comment by gahr** [comment]
interesting.. let me double check

**Comment by gahr** [comment]
I can repro that - thanks for the pointers! Definitely a bug.

**Comment by 4nd3r** [comment]
@gahr much better now, thanks
