### ISSUE TITLE
No messages matched criteria

### ISSUE THREAD

**Issue by SingularisArt** [neomutt/neomutt#3867]
Hello, I am having trouble getting a macro to work properly. The macro is meant to search for emails using notmuch. However, when I enter my search criteria, I receive an error message saying "No messages matched criteria". Strangely, when I remove the `path:'singularisartt@gmail.com'` portion from the macro, the error message disappears. I want to search through all my emails on a specific Gmail account using notmuch, but I am unsure how to fix this issue. Any help would be greatly appreciated. You can find my neomutt config [here](https://github.com/SingularisArt/Singularis/tree/master/aspects/email/files/.config/neomutt) in case that's needed. Thank you.

```mutt
macro index / "<enter-command>unset wait_key<enter><shell-escape>printf 'Search mail: '; read x; echo \$x >~/.cache/mutt_terms<enter><limit>~i \"\`notmuch search path:'singularisartt@gmail.com/**' --output=messages \$(cat ~/.cache/mutt_terms) | perl -le '@a=<>;s/\^id:// for@a;$,=\"|\";print@a' | perl -le '@a=<>; chomp@a; s/\\+/\\\\+/ for@a;print@a' \`\"<enter>" "search mail (using notmuch)"
```

**Comment by SingularisArt** [comment]
I created the following bash script:

```bash
#!/usr/bin/env bash

echo "printf 'Search mail: '; read x; echo \$x >~/.cache/mutt_terms"
echo "notmuch search path:'singularisartt@gmail.com/**' --output=messages \$(cat ~/.cache/mutt_terms)"
```

Along with the following macro:
```mutt
macro index / "<enter-command>source ~/.local/bin/neomutt/search_mail|<enter>" "search mail (using notmuch)"
```

But when I run `/`, I get the message `source: file ~/.local/bin/neomutt/search_mail| could not be sourced`. Am I doing something wrong in the bash script?

**Comment by flatcap** [comment]
Try changing the prompt to:
```
read -p "Search: " SEARCH
```

I think your prompt string might be confusing neomutt

**Comment by SingularisArt** [comment]
I still get the same issue

**Comment by flatcap** [comment]
What's the literal output of your script?

**Comment by SingularisArt** [comment]
Here's the output of my script running outside of neomutt (running search with "hi"):
```
thread:000000000000060f   2022-11-17 [1/1(2)] Reddit; "Me watching the latest Reddit video hearing ..." (inbox)|thread:00000000000005dd   2022-11-14 [1/1(2)] HUGO; [HUGO] Summary (inbox)|thread:00000000000004b1   2022-10-28 [1/1(2)] Reddit; "Here's the Tuna you've been waiting for" (inbox)
```

**Comment by flatcap** [comment]
ok, that's fine, but it's not something that NeoMutt can parse.
My script outputs NeoMutt commands...
Literal strings, such as:
```
echo "No Matches"
```

or

```
push '<limit>~i ABCDEF@example.com<enter>'
```

**Comment by flatcap** [comment]
> `<enter-command>source ~/.local/bin/neomutt/search_mail<enter>`

That's missing the `|` so NeoMutt's trying to understand your shell script.

> `cat "$out_path"` 

This needs to output something that NeoMutt can read, like: `push '<limit>...'`

**Comment by SingularisArt** [comment]
I found a somewhat workable solution. Instead of creating an outside script, I just change my `Archive` folder, then I do my searching. My main goal was to search through all my mail on that gmail account. Here's the final macro:
```mutt
macro index / \
        "<enter-command>unset wait_key<enter><change-folder>=Archive<enter><shell-escape>read -p 'Search mail: ' x; echo \$x >~/.cache/mutt_terms<enter><limit>~i \"\`notmuch search --output=messages \$(cat ~/.cache/mutt_terms) | perl -le '@a=<>;s/\^id:// for@a;$,=\"|\";print@a' | perl -le '@a=<>; chomp@a; s/\\+/\\\\+/ for@a;print@a' \`\"<enter>" \
        "Search mail (using notmuch)"
```
