### ISSUE TITLE
Initialize history from config files

### ISSUE THREAD

**Issue by thfi** [neomutt/neomutt#3876]
In various situations, such as when selecting a folder to change to, a user may use the arrow keys to access the history of previously chosen alternatives. This history is initially empty but is filled with every new, for example, folder the user changes to.

Sticking to the example of folders, users may have folders they use quite often. Thus instead of entering those value anew, there should be a way to pre-initialize the history with user-defined values as set in the configuration file, for example my six most common folders.

In the example of folders auto-completion does not do the trick in more elaborate situations, where I want to change or copy to a folder on a different server, requiring to enter "imaps://mail.example.com/Family" instead of "=Family" if it was on the current mail server.

**Comment by flatcap** [comment]
> This history is initially empty

Ah, then you probably want to `set save_history = 50`
See: https://neomutt.org/guide/gettingstarted#editing-history

There are four config variables that control how much history is saved, and where:

```sh
# Number of history entries to keep in memory per category
set history = 10

# File to save history in
set history_file = "~/.mutthistory"

# Remove duplicate entries from the history
set history_remove_dups = no

# Number of history entries to save per category
set save_history = 0
```

**Comment by thfi** [comment]
Thank you for the feedback. Being able to save the history helped me to find a solution.
For future reference for anyone who has a similar issue of wanting a pre-initialized history, here is my approach:

1. Create a 'history' file called `~/.mutt/permanent_history` and add elements in the format as found in the 'real' history file for entries you want to have pre-initialized.
   Example:
   ```
   3:imaps://mail.example.com/MySpecialMailFolder|
   3:+OtherMailFolder|
   ```
2. Take care that the 'permanent' history (file `~/.mutt/permanent-history`) is integrated into the 'real' history (here: `~/.mutt/history`), e.g. every time you log in. So, in a file like `~/.bashrc`, add the following line:
   ```bash
   cat ~/.mutt/{permanent-,}history | sort -u >/tmp/.mutt-history-${USER} && mv /tmp/.mutt-history-${USER} ~/.mutt/history
   ```
