### ISSUE TITLE
Fix safe_calloc calls

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#388]
Similar to #372.

1. do not cast returns
2. do not check results
3. put `number` and `size` arguments in the correct order

**Comment by toogley** [comment]
@gahr why is this necessary or advantageous?

**Comment by gahr** [comment]
@toogley the reason why casting a return of void* to T* is dangerous go back in time, when a function for which a declaration was not provided was assumed to return int. The cast suppressed a potential warning about the conversion from the presumed int to T*.

Nowadays, I would say that the cast is not needed at all. Code that is not needed is better removed ;)

So, it's not strictly necessary, but I'd still support the fact that not having it (the cast) is better custom.

**Comment by gahr** [comment]
As for not checking the results, it makes reasoning about the code easier. safe_ functions cannot fail, and putting checks around their returns only make that fact unclear. Again, useless code is better removed than kept.

**Comment by toogley** [comment]
@gahr thanks :)
