### ISSUE TITLE
Problems with umlauts when recieving some messages, but not in others

### ISSUE THREAD

**Issue by Ma94xx** [neomutt/neomutt#3883]
Hi there! 
I recently installed and configured neomutt with proton-bridge, and so far almost everything is working out fine (still figuring out how delete messages from the "All messages" folder lol) and I really like the project. Nevertheless, I'm struggling with one thing and I can't help it: 

When receiving mails from some people, german umlauts like "ä,ö,ü,ß" are replaced with backslashes and some number. The odd thing is, this only happens in some mails, but not in others. When receiving mails from a friend of mine, which uses protonmail as well, everything is displayed correct. Also there are no issues in typing and sending those characters (at least I couldn't reproduce it). When using the protonmail webinterface, the same mail that is wrongly displayed just works fine, so I guess I misconfigured something in neomutt. 

Typing neomutt -v outputs:
`System: Linux 6.3.4-arch2-1 (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libidn2: 2.3.4 (compiled with 2.3.4)
GPGME: 1.20.0
GnuTLS: 3.8.0
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd
`

**Comment by flatcap** [comment]
> Typing neomutt -v outputs:

Hmm... unfortunately, you've cut off the top line which has the actual NeoMutt version.

> Problems with umlauts ... some messages, but not in others

Do you have any emails that you can share?

In the Index, you can <kbd>C</kbd> (`<copy-message>`) to save an email to a file: `test.mbox`
You can edit out anything personal, though try not to alter the headers too much.

Check it still shows the problem with: `neomutt -f test.mbox`

You can attach the email to this issue (you may need to rename it to `.txt`)

Thanks

**Comment by Ma94xx** [comment]
Oh, sry: 
`NeoMutt 20230517`

And I've added a mail in the attachment
[umlautmail.txt](https://github.com/neomutt/neomutt/files/11642599/umlautmail.txt)

**Comment by flatcap** [comment]
Hmm... it works for me.

I think it's probably just your mailcap settings -- how the html email is being interpreted.
Here's a minimal config that works correctly:

**test.rc**
```sh
ignore *
unignore from: subject to cc date x-mailer x-url user-agent
set weed = yes

auto_view text/html
set mailcap_path = "my_mailcap"
```

**my_mailcap** (either of these lines work correctly)
```sh
text/html; elinks -dump -dump-color-mode 1 -dump-width ${COLUMNS:-80} %s; nametemplate=%s.html; copiousoutput
# text/html; w3m -cols ${COLUMNS:-80} -I %{charset} -T text/html; nametemplate=%s.html; copiousoutput;
```

Run:
```sh
neomutt -n -F test.rc -f testdir  # maildir containing umlautmail.txt
````

Hope this helps

**Comment by Ma94xx** [comment]
Thanks a lot! That worked :) 
The body is now displayed correctly in all mails (new and old), but subject lines are still showing "??" instead of "äüöß". It seems that only older messages are affected, since the mail I've attached shows the correct subject.

**Comment by Ma94xx** [comment]
Well, so I restarted the computer and now it works perfectly, lol. So thanks a lot!
