### ISSUE TITLE
<sync-mailbox> "Unable to write" when email (in a Maildir) was marked for deletion but was already deleted on the file system (by mbsync)

### ISSUE THREAD

**Issue by aurelf** [neomutt/neomutt#3884]
## Expected Behaviour

1) Marked a mail in a Maildir folder for deletion ("d") in mutt. 
2) Also deleted the file on another client, synchronized to the Maildir (with mbsync to synchronize an IMAP server). 
3) When syncing mailbox, if the file is already deleted, mutt should log a warning, but let me continue. 

Note that I have this in my config:
```
set trash="~/Maildir/Trash"
set maildir_trash
```
So email deletion is actually moving the email to trash.
I expect that if another email client deleted the mail it was already moved there and nothing is actually needed to do.

## Actual Behaviour

1) Mutt prints "Unable to write", aborts syncing mailbox, which is also required to change folder and quit. So I have to kill mutt and relaunch. 

Debug logs contain: 
```
[2023-06-02 12:56:29]<M> sync_mailbox() Writing /home/<User>/Maildir/<folder>...
[2023-06-02 12:56:29]<5> msgwin_recalc() recalc done, request WA_REPAINT
[2023-06-02 12:56:29]<5> msgwin_repaint() repaint done
[2023-06-02 12:56:29]<P> maildir_sync_message() rename: No such file or directory (errno = 2): No such file or directory
```

## Steps to Reproduce

1) Mark mail in a Maildir folder for deletion ("d") in mutt. 
2) Delete the file manually (or through synchronization)
3) Attempt syncing mailbox

## Proposed fix 
Looks similar to #3040 but not duplicate as far as I can tell. 

Mutt should check if file still present before attempting to rename it in maildir.c:maildir_sync_message()
 https://github.com/neomutt/neomutt/blob/f5d4edf914e2fed867cb74442b6dbf2b20db8339/maildir/maildir.c#L450

My proposed fix (tested and works for me against current Arch neomutt version)

```diff
--- neomutt-20230517/maildir/maildir.c	2023-05-17 13:46:41.000000000 +0200
+++ neomutt-20230517_af/maildir/maildir.c	2023-06-04 00:06:54.456200149 +0200
@@ -392,6 +392,7 @@
   struct Buffer *partpath = NULL;
   struct Buffer *fullpath = NULL;
   struct Buffer *oldpath = NULL;
+  struct stat st = { 0 };
   char suffix[16] = { 0 };
   int rc = 0;
 
@@ -447,6 +448,11 @@
     /* record that the message is possibly marked as trashed on disk */
     e->trash = e->deleted;
 
+    if (stat(buf_string(oldpath),&st) == -1){
+      mutt_warning("File already removed (just continuing).");
+      goto cleanup;
+    }
+
     if (rename(buf_string(oldpath), buf_string(fullpath)) != 0)
     {
       mutt_perror("rename");

```

If the patch looks right I can make a PR.

**Comment by aurelf** [comment]
Just to add, the patch has been working well for me for a week.

**Comment by flatcap** [comment]
Thanks for the patch, @aurelf -- it looks reasonable.

I'm currently trying to refactor the backends, starting with maildir, but that's going to take some time.

Meanwhile, please create a PR and we can get your fix merged.
