### ISSUE TITLE
What's the difference between nm_config_file and nm_config_profile?

### ISSUE THREAD

**Issue by rionda** [neomutt/neomutt#3888]
What the title says =). 
The [docs](https://neomutt.org/feature/notmuch#4-%C2%A0variables) seem essentially the same.

**Comment by gahr** [comment]
They are the `config_file` and `profile` [arguments](https://github.com/neomutt/neomutt/blob/d0fdd26246988a0efe98b6158461c60c59de35fd/notmuch/db.c#L129-L133) for notmuch_database_open_with_config. As far as I can see from [their source code](https://git.notmuchmail.org/git?p=notmuch;a=blob;f=lib/open.cc;hb=95a4bf38173311597bcc4fa7f597d58bb11ed119#l117), `profile` is used if `config_file` is not specified. I'll refer you to notmuch for more info :)
