### ISSUE TITLE
remove configuration flags which don't depend on external dependencies

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#389]
@d-k-c  said in [issue #310](https://github.com/neomutt/neomutt/issues/310#issuecomment-275164875):

> Remove some configuration flags and their corresponding ifdefs. I think that options that don't depend on external dependencies should be built-in: smtp, imap, pop, debug, sidebar, compressed, etc.

**Comment by toogley** [comment]
This issue was meant as a tracking issue, because IMHO its one of the easiest things to realize (compared to e.g. removing global variables or so).

Does anyone disagree with this change?

**Comment by gahr** [comment]
Sounds reasonable, as long as default behaviour doesn't change. Example, if --enable-sidebar currently defaults to off and we remove the autoconf switch, I'd like to have sidebar_visible default to no.

**Comment by somini** [comment]
The debug configuration flag should remain in theory, but I'm not sure it's worth it to keep non--debug builds.

**Comment by toogley** [comment]
@somini good point. What exactly does the debug flag do? does it more than enabling the -D option?

**Comment by gahr** [comment]
... most of which are in regex.c.. (I can't... resist... the urge... to killl...)

**Comment by toogley** [comment]
@flatcap i don't understand why you've deleted all mutt_debug() operations. In my understanding, mutt_debug() did just write to `.muttdebug0` - which isn't harming anything IMHO. so i don't understand why you removed the additional debugging information completely instead of just removing the #ifdef DEBUG.

**Comment by flatcap** [comment]
@toogley That was **just a bit of fun**.  I WILL NOT COMMIT THAT BRANCH.

I was just curious to see what DEBUG actually did -- I'm not sure I've ever asked that question of a large project before.

I figured that the simplest way to see the `#ifdef`s and `mutt_debug()`s was to delete them and look at the diff.

**Comment by toogley** [comment]
@flatcap aaah, okay. 👍

**Comment by xdgc** [comment]
* On 14 Feb 2017, Tobias Angele wrote: 
> @somini good point. What exactly does the debug flag do? does it more than enabling the -D option?

The theory is that a non-debug version is more performant, because
dprint()s are never compiled.  I'm sure this is true on older systems.
I'm not sure it's true on anything modern.

I'm not sure why it's desirable to remove either, though.

-- 
David Champion • dgc@bikeshed.us

**Comment by gahr** [comment]
> I'm not sure why it's desirable to remove either, though.

I agree with this.

**Comment by flatcap** [comment]
Let me reiterate: It was never my intention to remove any of the debug code from NeoMutt.

As a visualisation method, I *did* remove it from a test branch.  I've deleted the branch.

**Comment by flatcap** [comment]
Fixed in 07b78f9
