### ISSUE TITLE
keywords.patch cause crash if standard mailbox does not exist

### ISSUE THREAD

**Issue by bitstreamout** [neomutt/neomutt#39]
/var/mail/root: No such file or directory (errno = 2)                                                                                                                   
                                                     Program received signal SIGSEGV, Segmentation fault.
                                                                                                         mutt_scan_labels (ctx=0x0) at headers.c:363
363       for (i = 0; i < ctx->msgcount; i++)
Missing separate debuginfos, use: zypper install krb5-debuginfo-1.14-3.1.x86_64 libassuan0-debuginfo-2.4.2-1.1.x86_64 libcom_err2-debuginfo-1.42.13-3.3.x86_64 libffi4-debuginfo-5.3.1+r231346-1.3.x86_64 libgcc_s1-debuginfo-5.3.1+r231346-1.3.x86_64 libgdbm4-debuginfo-1.11-5.20.x86_64 libgio-2_0-0-debuginfo-2.46.2-2.1.x86_64 libglib-2_0-0-debuginfo-2.46.2-2.1.x86_64 libgmime-2_6-0-debuginfo-2.6.20-4.4.x86_64 libgmodule-2_0-0-debuginfo-2.46.2-2.1.x86_64 libgobject-2_0-0-debuginfo-2.46.2-2.1.x86_64 libgpg-error0-debuginfo-1.21-1.1.x86_64 libgpgme11-debuginfo-1.6.0-2.2.x86_64 libidn11-debuginfo-1.32-1.3.x86_64 libkeyutils1-debuginfo-1.5.9-4.3.x86_64 libncurses5-debuginfo-6.0-0.x86_64 libnotmuch4-debuginfo-0.20.2-1.4.x86_64 libopenssl1_0_0-debuginfo-1.0.2g-1.1.x86_64 libsasl2-3-debuginfo-2.1.26-12.1.x86_64 libstdc++6-debuginfo-5.3.1+r231346-1.3.x86_64 libtalloc2-debuginfo-2.1.5-2.1.x86_64 libuuid1-debuginfo-2.27.1-2.10.x86_64 libxapian22-debuginfo-1.2.23-1.2.x86_64

**Comment by bitstreamout** [comment]
Simple fix

[x.txt](https://github.com/neomutt/neomutt/files/293234/x.txt)

**Comment by flatcap** [comment]
Thanks for the report and the patch.

**Comment by flatcap** [comment]
#### This bug is now fixed and will be in the next release of NeoMutt.
