### ISSUE TITLE
'No OAUTH refresh command defined' when sending email

### ISSUE THREAD

**Issue by pwaring** [neomutt/neomutt#3910]
I've recently built the latest release ([20230517](https://github.com/neomutt/neomutt/releases/tag/20230517)) from source due to the Ubuntu package having a regression whereby NeoMutt would segfault every time I sent an email if it was saved to the same folder ([2023440](https://bugs.launchpad.net/ubuntu/+source/neomutt/+bug/2023440) on Launchpad, [3129](https://github.com/neomutt/neomutt/issues/3129) on NeoMutt GitHub issues). I used the following configuration options:

```
./configure --ssl --prefix=~/neomutt --disable-doc
```

Everything now works, however whenever I send an email the following message is displayed twice in the status bar for a few seconds (highlighted in red):

No OAUTH refresh command defined

I've never seen this error message before and I've never used OAUTH - I'm connecting via IMAPS using a username and password to an Exim/Dovecot mail server than I run myself. There's no mention of OAUTH anywhere in my config file.

Is this something I need to be concerned about, or is the error message incorrect? I've searched for the full error message in the issue tracker but can't find any related issues.

My config file is (with credentials and personal information replaced):

```
set realname="Me"
set from="me@example.org"
set signature="~/signature"

set imap_user="me@example.org"
set imap_pass="123456"

set folder="imaps://example.org"
set smtp_url=smtp://$imap_user:$imap_pass@example.org:587

set editor="vim -c 'set tw=72'"

set query_command="abook --datafile ~/addressbook --mutt-query '%s'"
macro index a     "|abook --datafile ~/addressbook --add-email\n" 'add sender to abook'
macro pager a     "|abook --datafile ~/addressbook --add-email\n" 'add sender to abook'
bind editor <Tab> complete-query

set use_from=yes
set use_envelope_from=yes

set forward_format="Fwd: [%s]"

set spoolfile="=INBOX"

set move="no"

set sort="threads"
set beep_new="yes"
set check_new="yes"
set metoo="no"
set mail_check="60"
set timeout="120"
set hidden_host="yes"
set pager_index_lines="10"

# theme
color normal white default
color quoted green default
color quoted1 cyan default
color quoted2 green default
color quoted3 cyan default
color indicator white red
color signature cyan default
color hdrdefault yellow default
color status white blue
color message white default
color error red default
color body cyan default "(ftp|http)://[^ ]+"
color body cyan default [-a-z_0-9.]+@[-a-z_0-9.]+

color tree magenta default
color tilde magenta default
color markers brightcyan default
color attachment brightmagenta default
color search black green
color underline brightgreen default

color index magenta default '(~n 1-1)'
color index green default '(~n 2-2)'
color index brightblue default '(~n 3-3)'
color index white default '(~n 4-9)'
color index brightred default '(~n 10-99)'

# headers
ignore *
unignore From:
unignore To:
unignore Reply-To:
unignore Subject:
unignore Date:
unignore CC:
unignore BCC:
unignore List-Id:

auto_view text/html

set record="=INBOX"
```

**Comment by seabass-labrax** [comment]
By default, Neomutt will try OAUTH and will fail because, as you said, you don't use OAUTH with your server. You can add this to your Neomutt configuration to make sure Neomutt only tries plain authentication:

`set smtp_authenticators="plain"`

See neomuttrc(5) for (a few) more details :)

**Comment by seabass-labrax** [comment]
If you're wondering why the error message appears twice before the email is sent, that's because Neomutt tries two different authentication methods for OAUTH: `smtp_auth_oauth` and `smtp_auth_xoauth2`. The latter is used by Microsoft; everyone else uses the former.

``` c
static const struct SmtpAuth SmtpAuthenticators[] = {
  // clang-format off
  { smtp_auth_oauth, "oauthbearer" },
  { smtp_auth_xoauth2, "xoauth2" },
  { smtp_auth_plain, "plain" },
  { smtp_auth_login, "login" },
#ifdef USE_SASL_CYRUS
  { smtp_auth_sasl, NULL },
#endif
#ifdef USE_SASL_GNU
  { smtp_auth_gsasl, NULL },
#endif
  // clang-format on
};
```

**Comment by pwaring** [comment]
Thanks, I've added that to my configuration now and the error message has disappeared. I've had my config file for a very long time - 20+ years now - so it's probably missing a few things that have changed. :)
