### ISSUE TITLE
Getting flag counts in sidebar without loading the mailbox first (like new counts) over IMAP

### ISSUE THREAD

**Issue by nabijaczleweli** [neomutt/neomutt#3964]
I already have `mail_check_stats` set and it shows
```
Mailing lists               N│
```
but only when I open it for the first time do I get
```
Mailing lists            18!N│
```

I'm on Dovecot IMAP – is there a config I'm missing that's not outlined in the sidebar guide? Do I need to enable additional tracking on the server? Does neomutt need to store a flag on the mailbox? I'm not really an IMAP Enjoyer:tm: so idk how this works at all, but I'd like to have at least just the exclamation if number+exclamation isn't possible.

**Comment by flatcap** [comment]
I've just `grep`d the code and [RFC3501](https://datatracker.ietf.org/doc/html/rfc3501) and I _think_ the answer is no.

In `imap_status()` we send an IMAP `STATUS` command.
We request:
- UNSEEN - The number of messages which do not have the `\Seen` flag set.
- RECENT - The number of messages with the `\Recent` flag set.
- MESSAGES - The number of messages in the mailbox.

https://github.com/neomutt/neomutt/blob/be4d3552a61e50edfc9799721449c5295456f4a5/imap/imap.c#L1122-L1123

According to the RFC, getting the number of `\Flagged` messages isn't allowed.

https://datatracker.ietf.org/doc/html/rfc3501#section-6.3.10

Perhaps this changed in a later RFC.
Perhaps this is supported by some mail servers.

You could add `FLAGGED` to that line of code and check the logs to see what happens :-)

**Comment by nabijaczleweli** [comment]
```
2 STATUS INBOX (UIDNEXT UIDVALIDITY UNSEEN RECENT FLAGGED MESSAGES)
2 BAD Error in IMAP command STATUS: Invalid status item FLAGGED (0.001 + 0.000 secs).
3 STATUS INBOX (UIDNEXT UIDVALIDITY UNSEEN RECENT MESSAGES)
* STATUS INBOX (MESSAGES 1576 RECENT 0 UIDNEXT 990439 UIDVALIDITY 1592769264 UNSEEN 36)
3 OK Status completed (0.004 + 0.000 + 0.003 secs).
```

**Comment by nabijaczleweli** [comment]
And looks like they don't keep this as metadata anyway and the only way to find this is to do `SEARCH FLAGGED` which. Not great on a 2G-uncompressed mailbox. Thanks for bridging me into where I needed to look.
