### ISSUE TITLE
No way to turn off "GPGME: CMS protocol not available" warnings

### ISSUE THREAD

**Issue by jidanni** [neomutt/neomutt#398]
User cannot stop
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849762
Debian Bug report logs - #849762
mutt: complains about GPGME

There is no command line to stop it.

The muttrc man page mentions some variables,

and some can only be used in .muttrc

(but maybe also with -e??!!)

anyway, assume the user is on a read-only filesystem.

If one uses 2>/dev/null one will miss real errors.

The user does not have any use for PGP and just wants to turn off this error.

**Comment by gahr** [comment]
If for whatever reason gpgme is not working on that system, the first thing to try would be to turn it off. Does launching neomutt with the `-e "set crypt_use_gpgme=no"` option helps?

**Comment by jidanni** [comment]
That works! Thanks.
I didn't try it because the man page said it was already "no".

       crypt_use_gpgme
              Type: boolean
              Default: no

$ mutt -D|grep use_gpg
GPGME: CMS protocol not available
crypt_use_gpgme is set
pgp_use_gpg_agent is unset

if "is set" means "yes" then the man page is wrong.


Also please change

       Note that you need to set this option in .muttrc;  it
              won't have any effect when used interactively.

to mention -e too!

**Comment by gahr** [comment]
Yep the manual could be a bit clearer.

**Comment by riesebie** [comment]
> $ mutt -D|grep use_gpg 
> GPGME: CMS protocol not available 
> crypt_use_gpgme is set the Debian 
> pgp_use_gpg_agent is unsett of 

@jidanni  those seetings are placed in /etc/Muttrc.d/gpg.rc which is a part of Debian's mutt installation. Nothing wrong in the source code.

**Comment by gahr** [comment]
@riesebie thanks for the clarification, I'll close this.

**Comment by kilobyte** [comment]
"set crypt_use_gpgme=no" break the new fancy pinentry integration, but otherwise GPG keeps working.

So it appears that gpgme actually **is** working, just this message is bogus.

**Comment by flatcap** [comment]
At startup Mutt checks for both "OpenPGP" and "CMS" protocols, complaining but not stopping if either is missing:
```c
static void init_pgp (void)
{
  if (gpgme_engine_check_version (GPGME_PROTOCOL_OpenPGP) != GPG_ERR_NO_ERROR)
    mutt_error (_("GPGME: OpenPGP protocol not available"));
}

static void init_smime (void)
{
  if (gpgme_engine_check_version (GPGME_PROTOCOL_CMS) != GPG_ERR_NO_ERROR)
    mutt_error (_("GPGME: CMS protocol not available"));
}
```

I haven't looked any deeper, but it might be possible to only check for the protocols we need.

**Comment by sebastianw** [comment]
Hi, this error is still happening on Debian Stretch. I'm unsure what to do with it. Disabling gpgme is probably the wrong way to "fix" this? Is this bug still valid as it is marked closed?

**Comment by gahr** [comment]
GPGME comes with both PGP and S/MIME support. If S/MIME isn't available, you'll get that error message when the module is initialized. We might want to turn that into a warning, but it shouldn't be something you need to worry about :)

**Comment by mmitch** [comment]
I can't comment on the Debian bug (it is still open, but archived), so I'll just put this info here:

Instead of disabling `gpgme` completely, another workaround (or even a solution ;-) is to install all its dependencies to make mutt's `GPGME_PROTOCOL_CMS` check succeed:

```
% apt-get install gpgsm
% apt-mark auto gpgsm
```

On my systems this made the warning message disappear while `pinentry` is still being used for key entry.

**Comment by jidanni** [comment]
$ w3m -dump https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849762 | grep Done
Done: Elimar Riesebieter <riesebie@lxtec.de>

So it is not still open.
Anyway it is easy to unarchive Debian bugs if necessary...
