### ISSUE TITLE
failed redraw (aka half-drawn) after op_shell_escape

### ISSUE THREAD

**Issue by lucilanga** [neomutt/neomutt#3980]
Neomutt fails to properly redraw main window when returning from a shell command. It only draws half of the screen.

This bug only occurs if certain cases are met.
Firstly the behavior  seems related to the famous half screen draw bug that has been around and debugged for quite a while.
Secondly it seems to occur only for tilling window managers.
It doesn't matter if it's under tmux/screen, I'm running neomut under tmux most of the time, but the debug was done in single terminal only. See below for alternate reproducer.

While my primary intention was to fix the behavior of shell escape alone, it is possible this fixes other half-drawn related issues like #1208.

How to reproduce:

Tilling window manager. Terminal doesn't matter (tried with foot, alacritty, xterm) the behavior is the same.
1st pass:
1. Open one terminal run neomutt - it should take all the desktop space.
2. Run another application say a pdf reader  - it should split the desktop space with neomutt terminal window.
3. close it - mutt terminal win will take all the desktop space. neomutt redraws correctly as it should be.

2nd pass:
Now:
1. open one term run neomutt
2 run again the same application taking half of the screen etc.
3. open a shell  (defkey "!")  -> we're thrown into a half screen shell
4. close the pdf reader
5. close the shell
6. mutt window half redrawn.

The main problem is SIGWINCH is not triggered when coming back after curses shutdown.
It does however work on the "1st pass", so I'm unsure if this is a curses bug.
I wasn't able to reproduce this in a floating window mode, I don't know that is can be either.
However coming across bug #1208 I was able to reproduce this in a tmux env regardless of WM.
The steps are similar: run neomutt inside tmux, make a new vertical or horizontal pane, run a shell, close pane, close shell -> same half drawn issue.

PS. I tested this on sway and i3 and lastly with tmux, I couldn't find any half draw issues except for #1208. I'm interested to see if there are other similar reports to this issue.

**Comment by roccoblues** [comment]
Hey, I noticed that the corresponding PR is merged. Can this issue be closed?
