### ISSUE TITLE
Open mailbox requires two returns instead of one

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#3983]
## Expected Behaviour

I was trying to change mailboxes. I selected the one I wanted and pressed `<Enter>` and expected the selected mailbox to open, as is the behavior in the current release.

## Actual Behaviour

The only thing that happened is that the mailbox that I want was filled in on the bottom prompt "Open mailbox: <mailbox>". I had to press `<Enter>` again for the mailbox to be open.

## Steps to Reproduce

Press `c` then `<Tab>`. Then select a mailbox and press `<Enter>`.

## How often does this happen?

- Always

## When did it start to happen?

- When I tested the current master. Before, I was using a version close to release.

If this behavior is indeed unexpected, I'd be happy to do a bisect if it would help.

## NeoMutt Version

```
NeoMutt 20230517-300-186c63
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.2.0-26-generic (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libidn2: 2.3.2 (compiled with 2.3.2)
OpenSSL: OpenSSL 3.0.2 15 Mar 2022
libnotmuch: 5.6.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/local/include -DNCURSES_WIDECHAR -O2

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme 
  -gsasl -gss +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster 
  +nls +notmuch +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Is your email local (maildir) or remote (IMAP)?

I could reproduce the issue with both.

**Comment by flatcap** [comment]
Argh!  A typo in our refactoring.
Branch [[devel/browser]](https://github.com/neomutt/neomutt/tree/devel/browser) should fix that.

Thanks

**Comment by scottkosty** [comment]
Thanks for the quick fix. Tested and works well!
