### ISSUE TITLE
Ability to set/clear IMAP tags

### ISSUE THREAD

**Issue by ajkessel** [neomutt/neomutt#4027]
neomutt can see IMAP tags (e.g. by adding %g to index_format), but there does not appear to be any way to set or clear those tags. If it's possible to do this, I suggest it should be better documented; if not, I would request that this ability be implemented, so, for example, the user could set/clear IMAP tags used by another MUA like Thunderbird.

**Comment by mschilli87** [comment]
Are you looking for `set-flag` (`w` by default) and `clear-flag` (`W` by default) or are tags and flags two different things?

**Comment by ajkessel** [comment]
As best I can tell, set-flag/clear-flag don't impact IMAP flags/tags. set-flag/clear-flag see D/N/O/r/*/! but not arbitrary IMAP tags that are seen with %g in the format string. Thunderbird tags, for example, show up as "$label1" "$label2" etc in the %g string, but I can't figure out any way for neomutt to alter those tags.

**Comment by ajkessel** [comment]
It looks like perhaps what I'm looking for is <modify-labels> which is provided by [notmuch ](https://neomutt.org/feature/custom-tags#:~:text=add%2C%20remove%2C%20or%20toggle%20tags%20IMAP%3A%20edit%20the%20tags,would%20be%20shown%20when%20requerying.) but I'm running neomutt under cygwin which doesn't package notmuch.

**Comment by gahr** [comment]
`<modify-labels>` works fine with IMAP. The paragraph you’re quoting explains what it does on the different backends. Admittedly, the wording is perhaps not great.
The caveat is that not all IMAP servers support custom labels (that’s how they are called in the IMAP world).

**Comment by ajkessel** [comment]
Oh, you're right! This does exactly what I want. But it is hard to find the functionality, and as far as I can tell it's only documented in connection with notmuch, which made me think you needed to install notmuch to even access them.

**Comment by gahr** [comment]
> as far as I can tell it's only documented in connection with notmuch

Well, if you look for `modify-labels` [here](https://neomutt.org/guide/reference.html), it says "notmuch/imap". Also, if you read [the introduction here](https://neomutt.org/feature/custom-tags) it says that the imap and notmuch backends support the feature.

 As I said, it could be clearer. Here's the code for that page, if you want to improve it: https://github.com/neomutt/neomutt.github.io/blob/main/_feature/custom-tags.html

**Comment by ajkessel** [comment]
OK, I see. As a neomutt newbie, the notmuch stuff is very confusing to me. I read “notmuch/imap” to mean that the feature existed when using notmuch in connection with IMAP, not as a freestanding IMAP feature. The section you linked there makes it a bit clearer — when Googling for this issue, I didn’t see that intro. I’ll take a look and see if I can suggest an improvement.

**Comment by ajkessel** [comment]
Am I correct that if you want to remove a tag with a macro, you can only do that with notmuch? IMAP backend only provides the ability to hand-edit IMAP tags?
