### ISSUE TITLE
search-previous (locate previous regex match)

### ISSUE THREAD

**Issue by tjex** [neomutt/neomutt#4028]
## What would you like to be able to do?

It would be great to navigate to the previous regex match. 

Currently, when searching with regex: `/` , we can navigate to the next match with `n`, but not to the previous match. 
After looking at the command outputs via `?`, `search-previous` doesn't seem to exist? `search-next` exists.

I would envisage a functionality similar to vim, where `n` takes you to the next regex occurence (as is currently in neomutt) and `N` would take you to the previous (would of course require unbinding `N` from mark email unread / new)

## What needs to change in NeoMutt?

A new function to search backwards in the table of results returned by the regex search function.
Wouldn't need a default mapping - as `N` is the "logical" or "popular" choice. This could be left to the user to map. 

## Have you tried any alternative methods?

No as I don't see any function for the operation that I could bind to.

**Comment by flatcap** [comment]
It's called opposite (I have no idea why :-) but it's not bound by default.
The four functions are:

| Function            | Binding                                    | Description                                 |
| :------------------ | :----------------------------------------- | :------------------------------------------ |
| `<search>`          | <kbd>/</kbd>                               | search for a regular expression             |
| `<search-reverse>`  | <kbd>\<Esc\>/</kbd> (<kbd>\<Alt-/\></kbd>) | search backwards for a regular expression   |
| `<search-next>`     | <kbd>n</kbd>                               | search for next match                       |
| `<search-opposite>` | none                                       | search for next match in opposite direction |

By default, <kbd>N</kbd> is bound to `<toggle-new>`, but this'll do what you want:

```sh
bind index,pager N search-opposite
```

**Comment by tjex** [comment]
ahhhh nice! thanks 🙌

**Comment by alejandro-colomar** [comment]
For symmetry with `<Esc>/`, I've bound it to `<Esc>n` in my muttrc.
