### ISSUE TITLE
Completion is not triggered by tab

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#4032]
## Expected Behaviour

In the prompt after 'c' (to change mailboxes), I expect Tab to do completion.

## Actual Behaviour

It does not complete. It shows a character in the prompt, which perhaps means it tried to interpret the Tab literally, or didn't catch it?

## Steps to Reproduce

Type "c", then type Tab.

## How often does this happen?

- Always

## When did it start to happen?

Bisect leads to 1ced43be.

## NeoMutt Version

```
NeoMutt 20230517-336-9d05db
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.2.0-32-generic (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libidn2: 2.3.3 (compiled with 2.3.3)
OpenSSL: OpenSSL 3.0.8 7 Feb 2023
libnotmuch: 5.6.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --asan --prefix=/usr/local

Compilation CFLAGS: -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/local/include -DNCURSES_WIDECHAR -fsanitize=address -fno-omit-frame-pointer -fno-common -g -O0

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme 
  -gsasl -gss +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster 
  +nls +notmuch +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 

Devel options:
  asan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by flatcap** [comment]
Thanks.  Sorry, I think I know what I've done.
Do you have `bind editor <tab> complete-query` ?

Please can you:
```
bind editor <tab> complete
```
and check that completion works correctly.

There was some magic in the completion that allowed `<complete-query>` to work as `<complete>` if it wasn't in an "alias" mode.
I'll replicate that in the new code.

**Comment by scottkosty** [comment]
Yes, you guessed correctly! It does indeed work with the change.

One minor note, which does not seem relevant but just in case. I have `<Tab>` (note the upper-case 'T').

**Comment by scottkosty** [comment]
I may have spoken too fast. That fixes the issue with changing folders, but it doesn't restore behavior for completing the address entry for me.

**Comment by flatcap** [comment]
> I have `<Tab>` (note the upper-case 'T').

I thought about that before, but I've just checked.
Yes, named keys are case-insensitive.

> it doesn't restore behavior for completing the address entry for me.

No, I just needed to check that that was the only thing I'd broken :-)

Please can you give #4034 / branch [[devel/complete]](https://github.com/neomutt/neomutt/tree/devel/complete) a try.

Thanks

**Comment by scottkosty** [comment]
> Please can you give #4034 / branch [[devel/complete]](https://github.com/neomutt/neomutt/tree/devel/complete) a try.

Tested and works well! Thanks!
