### ISSUE TITLE
Question about object name for highlight

### ISSUE THREAD

**Issue by tapirpad** [neomutt/neomutt#4042]
I recently decided to compile neomutt from source instead of using the one in my distro repository. Everything works well, but there is one small thing that is bugging me. There is a difference in the highlight between the two version. Here is the comparison.

NeoMutt 20211029
![Screenshot_20230921_153127](https://github.com/neomutt/neomutt/assets/55569482/f81d513b-c9a2-45b7-8e8c-193ac8fcd231)

NeoMutt 20230517-389-f692ca
![Screenshot_20230921_153010](https://github.com/neomutt/neomutt/assets/55569482/2e9b95f0-b8b7-4254-b4f2-ab04c8363b96)

Is this difference because the recent version introduce a new object name for the arrow? I have been searching for the object name so I can change the highlight but couldn't find it.

**Comment by flatcap** [comment]
Hi @tapirpad,

The arrow's colour is controlled by `color tree [attrs] fg bg`

> NeoMutt 20211029

Ah yes.  A **lots** happened since 2021 :-)

The colours got a major overhaul to improve the code and make them behave more consistently.
One important change want to make `default` behave as a transparent colour,
so a `green default` object on a `default blue` background is `green blue`.

The base colour is `color normal`
This sets the colour for anything using `default`.

Try setting: `color normal black black` to see if that helps.

For fun, try setting: `color normal red blue` to see where the background colours are showing through.

**Comment by tapirpad** [comment]
Thank you, @flatcap ! 
I was able to change the color of the arrow using `color tree [attrs] fg bg`.

I also tried experimenting with your last suggestion. It seems `color normal default default` will match the terminal background and foreground color, which makes things convenient. 

However, I found that `color tree` does not respect `color normal`. 

I put some examples below. In these examples, I only set `color normal` and nothing else.

`color normal default default`

![Screenshot_20230922_053521](https://github.com/neomutt/neomutt/assets/55569482/f7982099-6306-4982-92e9-19ef134d24f0)

`color normal red blue`

![Screenshot_20230922_054003](https://github.com/neomutt/neomutt/assets/55569482/79a240e1-084d-4eaa-bdc9-15fbcb308d06)

It is not a problem for me since I will rewrite the color anyway, but I thought you may want to know this.

**Comment by flatcap** [comment]
> However, I found that `color tree` does not respect `color normal`.

Oh.  Thanks.  I'll take a look at that.

**Comment by flatcap** [comment]
I've given the tree colours a bit of a workout and they seem correct to me.
I tested all 16 combinations.

**config**:
```perl
uncolor *
color indicator default blue

macro index <f1> "<enter-command>color normal default default<enter>"
macro index <f2> "<enter-command>color normal red     default<enter>"
macro index <f3> "<enter-command>color normal default yellow <enter>"
macro index <f4> "<enter-command>color normal red     yellow <enter>"

macro index <f5> "<enter-command>color tree   default default<enter>"
macro index <f6> "<enter-command>color tree   cyan    default<enter>"
macro index <f7> "<enter-command>color tree   default magenta<enter>"
macro index <f8> "<enter-command>color tree   cyan    magenta<enter>"
```
