### ISSUE TITLE
A language server for neomuttrc

### ISSUE THREAD

**Issue by Freed-Wu** [neomutt/neomutt#4052]
Before asking a question, please check:

- NeoMutt Guide: https://neomutt.org/guide/
- Google:        https://www.google.com/

In <https://neomutt.org/contrib>

> Participation
>
> NeoMutt is a fantastic program. It’s versatile, configurable, scriptable…
>
> This is your chance to help other NeoMutt users…
>
>     Have you got a config file that everybody should be using?
>     Have you written a script that makes life easier?
>
> If you are a GitHub user, you can propose your improvements as a pull request at the repository of this site, or raise a NeoMutt issue to tell us about your idea.

I create [a language server](https://github.com/Freed-Wu/mutt-language-server) for neomuttrc. Can it be hosted on this organization for visibility just like [neomutt.vim](https://github.com/neomutt/neomutt.vim)?

- It can help the project to get more bug reports to improve this project
- and increase [bus factor](https://en.wikipedia.org/wiki/Bus_factor).

**Comment by flatcap** [comment]
Hi @Freed-Wu,

Sorry it's taken a while to respond; thanks for persevering!
I live in the dark ages and don't use LSP myself.
I had to find someone to show me that your server is as good as it sounds.

And it is!

Thank you for taking the time to create it.

I've just sent you an invite to join NeoMutt.
As a member, I _think_ you'll be able to transfer the repo to the neomutt org.

Thanks! :heart:

**Comment by flatcap** [comment]
@rbmarliere Kindly created a screencast:

[![asciicast](https://asciinema.org/a/610645.svg)](https://asciinema.org/a/610645)

**Comment by Freed-Wu** [comment]
> Done

Thanks!

**Comment by flatcap** [comment]
If you've got any questions about NeoMutt, or you'd just like to chat,
you can find us on IRC: `#neomutt` on `irc.libera.chat` ([web client](https://kiwiirc.com/nextclient/irc.libera.chat/#neomutt))
(we're most active during European daylight hours)
