### ISSUE TITLE
Please update your GPG keys used for signing release tags

### ISSUE THREAD

**Issue by vt-alt** [neomutt/neomutt#4062]
Your [gpg key](https://github.com/flatcap.gpg) 5FAF0A6EE7371805 used for signing release tag `20231006` is expired:
```
$ curl -s https://github.com/flatcap.gpg | gpg --show-key
pub   rsa4096 2016-04-08 [SC] [expired: 2023-06-20]
      86C2397270DD7A561263CA4E5FAF0A6EE7371805
uid                      Richard Russon (NeoMutt) <rich@flatcap.org>

```
Can you please update it so release tags could be verified.
Thanks,

**Comment by vt-alt** [comment]
I found updated key on your web site.

https://flatcap.org/id/richard.russon.neomutt.asc

**Comment by flatcap** [comment]
Sorry about that.
When I updated my keys I uploaded **my** key, but not the NeoMutt key.
Done.

`gpg --refresh-keys` should now help everyone else.

**Comment by vt-alt** [comment]
Thanks!
