### ISSUE TITLE
Interrupted system call error with non-ssl imap makes neomutt unusable

### ISSUE THREAD

**Issue by EdwardBetts** [neomutt/neomutt#407]
I read my mail via IMAP using the dovecot IMAP server on my laptop. The connection is not using ssl.

Mutt keeps crashing with this message: "Error talking to localhost (Interrupted system call)". It didn't used to do this. 

The problem goes away if I configure dovecot to use ssl.

I used git bisect to find when this problem started, it is commit 1f19f808dbcfe1cb02e4806a9f583ae9c657b7e5.

Steps to reproduce:
1. run an IMAP server with ssl disabled.
2. mutt -f imap://localhost/
3. while true; do echo WINCH; killall -WINCH mutt; sleep 1; done

Sending WINCH to mutt is a harmless windows resize signal. It will trigger the bug quicker.

**Comment by gahr** [comment]
@EdwardBetts , I can test with a local dovecot over plain port 143. I have been running the loop for over a minute but I can't get it to crash. How long does it usually take?

Also, can you post your `mutt -v` and `mutt -DS`? Thanks!

**Comment by EdwardBetts** [comment]
Normally within seconds.

Try with these settings:

set mail_check=1
set timeout=2
unset ssl_starttls

[mutt-v.txt](https://github.com/neomutt/neomutt/files/780343/mutt-v.txt)
[mutt-D.txt](https://github.com/neomutt/neomutt/files/780344/mutt-D.txt)

**Comment by gahr** [comment]
`unset ssl_starttls` did it. Thanks, I can now reproduce.

**Comment by EdwardBetts** [comment]
How come the "Interrupted system call" error only happens with SSL disabled?

**Comment by EdwardBetts** [comment]
I often get "Mailbox closed" after the "Interrupted system call" error. The message list disappears and the status bar says "(no mailbox)".

**Comment by gahr** [comment]
> How come the "Interrupted system call" error only happens with SSL disabled?

Because of the difference between how the [plain](https://github.com/neomutt/neomutt/blob/master/mutt_socket.c#L428) and the [ssl](https://github.com/neomutt/neomutt/blob/master/mutt_ssl.c#L319) sockets handle EINTR.

**Comment by EdwardBetts** [comment]
The raw_socket_write function starts with mutt_allow_interrupt (1) and ends with mutt_allow_interrupt (0). The ssl_socket_read doesn't call mutt_allow_interrupt. Does that mean interrupts are permitted within raw_socket_write but disallowed within ssl_socket_read?

**Comment by gahr** [comment]
Well, interrupts are surely enabled inside `raw_socket_write`. Their enabledness inside `ssl_socket_write` depends on the caller.. however, even if we figured out that in this code path interrupts are disabled by the time we get to `ssl_socket_write`, I would not feel confident to remove the enabling within `ssl_socket_write`.

**Comment by EdwardBetts** [comment]
It doesn't make sense to check errno if read/write didn't return -1.
