### ISSUE TITLE
Header color behaviour changed: background only changed where text is present

### ISSUE THREAD

**Issue by rixx** [neomutt/neomutt#4076]
## Expected Behaviour

I'm coloring my email headers with different background colors, like this (and so on):

```
# header
color header      black       color39      "^"
color header      black       color35      "^(Subject)"
```

In neomutt 2023-05-17, this looked like this, coloring the entire line, as intended:

![DeepinScreenshot_select-area_20231018122623](https://github.com/neomutt/neomutt/assets/2657547/68d53b70-1a53-47b1-932d-f00e4f63fa47)

## Actual Behaviour

As of updating to 2023-10-06, only the text-part of the line is coloured:

![2023-10-18T12:29:44+02:00](https://github.com/neomutt/neomutt/assets/2657547/c4eaa013-a795-4945-9458-50b02a2b5795)

This is very visually busy (aka ugly) and cannot be changed. I made sure that I didn't set `header_color_partial` in my configuration anywhere, and also `set header_color_partial = no` does not change this behaviour (as it shouldn't!). Of course, with `set header_color_partial = yes`, even less of the line is colored in, as intended and documented.

## When did it start to happen?

Update to 20231006. Downgrading fixes the problem.

## NeoMutt Version

<details>
<summary>20231006</summary>

```
NeoMutt 20231006
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.5.7-arch1-1 (x86_64)
ncurses: ncurses 6.4.20230520 (compiled with 6.4.20230520)
libidn2: 2.3.4 (compiled with 2.3.4)
GPGME: 1.22.0
GnuTLS: 3.8.1
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --ubsan --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/neomutt/src=/usr/src/debug/neomutt -flto=auto -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.3 -I/usr/include -I/usr/include -I/usr/include -DNCURSES_WIDECHAR -I/usr/include/p11-kit-1 -I/usr/include -I/usr/include -fsanitize=undefined -fno-omit-frame-pointer -fno-common -g -O0

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme 
  -gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster 
  +nls +notmuch -openssl +pgp +regex +sasl +smime +sqlite +sun_attachment 

Devel options:
  ubsan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```
</details>

## Extra Info

* Operating System and its version: Arch Linux, current
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? local

**Comment by flatcap** [comment]
Sorry about that.  Good news, though.
It's already been fixed (fdc654efc); there'll be Bug-Fix Release very soon.
