### ISSUE TITLE
Warning "brightdefault: no such color"

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#4095]
## Actual Behaviour

When I open NeoMutt I get the following warning:

    brightdefault: no such color

I wonder if maybe this warning is correct and it just went unreported before?

## Steps to Reproduce

Here's a minimal config to reproduce the issue:

```
set realname = 'Scott Kostyshak'
set imap_user = 'scott.kostyshak@gmail.com'
set imap_pass = "`gpg --use-agent --quiet --batch -d ~/.mdp/per.gpg`"

set folder = "~/.mail"

set smtp_url = "smtp://scott.kostyshak@smtp.gmail.com:587/"
set smtp_pass = $imap_pass

set spoolfile = +INBOX
color body brightdefault default "^diff --git.*"
```

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded to 20231103.

## NeoMutt Version

```
NeoMutt 20231103
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.2.0-36-generic (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libidn2: 2.3.3 (compiled with 2.3.3)
OpenSSL: OpenSSL 3.0.8 7 Feb 2023
libnotmuch: 5.6.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/local/include -DNCURSES_WIDECHAR -I/usr/local/include -O2

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme 
  -gsasl -gss +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster 
  +nls +notmuch +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 
  +truecolor 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Is your email local (maildir) or remote (IMAP)?

I can reproduce on both.

**Comment by flatcap** [comment]
> I wonder if maybe this warning is correct and it just went unreported before?

Yes and yes.

`default` is transparent; `bright-default` can only be seen by people on hallucinogenic drugs :-)

---

Historically, `default`s meaning wasn't clear.
It might:
- Do nothing (leaving the background colour)
- Set to the `normal` colour
- Be transparent (causing colours to be merged)

About 18 months ago, I made `default` mean transparent, **everywhere**.
The recent colour refactoring made the checking a bit stricter.

The foreground and background colours of an object are considered separately.
The priority order, from highest to lowest, is:

- Object colour
- `normal` colour
- Terminal colour

Where multiple objects are overlaid, one is given higher priority.
e.g. tree chars + indicator: indicator is on top

**Comment by scottkosty** [comment]
Thanks a lot for those details! That makes sense. Thanks for doing the coloring restructuring. It sounds like it wasn't fun but will have some nice long-run benefits!

**Comment by giaume** [comment]
New color definition makes much more sense.
I replaced `brightdefault default` by `bold default default` in my config file to get the same result, i.e. bold :)

**Comment by lucrocha** [comment]
Note, https://neomutt.org/guide/configuration says explicitly: "The value brightdefault is also valid"

**Comment by flatcap** [comment]
Well spotted, @lucrocha.
Fixed.
