### ISSUE TITLE
mutt_draw_statusline() causes some characters to display incorrectly

### ISSUE THREAD

**Issue by skeirik2** [neomutt/neomutt#41]
This is my first time writing up an issue (for any github project). I looked around for some kind of new issue guidelines, but didn't find any (let me know if anything is missing...).

To the point, I occasionally send/receive email in Chinese, and would like to be able to display Chinese characters in the statusbar (or any other bar really). I noticed that when migrating from mutt 1.6.1 to neomutt 1.6.1, my statusbar in the mutt pager was all garbled. For reference, here was the config:

`set pager_format = " %C - %[%H:%M] %20v %s %?H? [%H] ?"`

Strangely enough, reading this line from the source file was problematic, but typing it in at the command line gave the expected output. Since the configuration file was utf-8 encoded, I suspected other non-ascii characters would also cause problems. I tried typing in the following at the mutt command line:

`set pager_format = " 测试 %C - %[%H:%M] %20v %s %?H? [%H] ?"`

and found that only the Chinese characters were garbled. Eventually, I discovered in mutt 1.6.1 and neomutt 1.6.1 the function to draw the status bar had changed from `mutt_paddstr()` to `mutt_draw_statusline()`. When I replaced the new function with the old one, everything printed out as expected. For reference, in my version of neomutt cloned a few days ago, there was a call to `mutt_draw_statusline()` in pager.c at lines 1859 and 1865.

I haven't looked too deeply into what `mutt_draw_statusline()` is doing, but at first glance, it seems to be calling `mutt_format_string()` to draw the text. From what I can tell, `mutt_format_string()` calls `mbrtowc()` so it _should_ be able to handle multibyte characters...

Here is a screenshot of reading this statusline `" 测试 %C - %[%H:%M] %20v %s %?H? [%H] ?"` from my config. file:

![example](https://cloud.githubusercontent.com/assets/7319434/15767438/8f211cb0-290d-11e6-8c5f-dd38d7249325.png)

**Comment by flatcap** [comment]
@skeirik2 Thanks for the detailed bug report.

> I looked around for some kind of new issue guidelines, but didn't find any

That's an item on my todo list :-)

> `mutt_paddstr()` -> `mutt_draw_statusline()`

That change came from the [status-color](http://www.neomutt.org/feature/status-color/) patch.

I've had a quick look through the code and I think I see the problem.  `mutt_draw_statusline()` is writing out the bytes of the status bar, individually.  Some terminals work out that it's a UTF-8 character (mine does), others get confused (yours).

I'll see what I can do.

**Comment by flatcap** [comment]
@skeirik2 
Please can you test a program for me: [test-msg.c.txt](https://github.com/neomutt/neomutt/files/299542/test-msg.c.txt)
Rename it to .c
You may also want to edit the file to change the locale setting.

```
gcc -Wall -o test-msg test-msg.c -lncursesw
./test-msg
```

The output _should_ show something like:
```
apple 测试 banana
apple XXX banana
````
Where XXX is garbage.
The first line is printed as one string.
The second line is printed one byte at a time.

If the first string is printed correctly, then I know how to fix the bug.

**Comment by skeirik2** [comment]
So... I tested the program with en_GB.UTF-8 and en_US.UTF-8 locales and got the following output:

![test](https://cloud.githubusercontent.com/assets/7319434/15809211/99297a18-2b51-11e6-8776-44785ab7da4d.png)

It seems like in the second line it is highlighted or something? Honestly... this output makes no sense to me...

**Comment by flatcap** [comment]
Hmm... Very curious.
Well, I'm making some changes.  Hopefully they'll fix your problem.

**Comment by skeirik2** [comment]
Thanks for that! For reference, I'm running mintty in Cygwin. I did some googling to see if there were any relevant unicode bugs in mintty, but I didn't really find anything (in any case, unicode works most of the time, even it mutt).

**Comment by flatcap** [comment]
> I'm running mintty in Cygwin

OK, thanks.

> I did some googling to see if there were any relevant unicode bugs in mintty

It's a problem all terminals have with escape sequences, unicode, etc.  If a sequence consists of n bytes and you're on a slow connection, how long should the terminal wait to see what the user wants.

Please can you try this [bug-fix build](https://github.com/neomutt/neomutt/tree/issue/41):
```
git clone -b issue/41 https://github.com/neomutt/neomutt.git
cd neomutt
autoreconf --install
./configure [YOUR-CONFIGURE-OPTIONS]
make
```

**Comment by flatcap** [comment]
@skeirik2 
I've just released [NeoMutt-20160611](https://github.com/neomutt/neomutt/releases/latest).
Please can you see if this fixes your problem.

**Comment by skeirik2** [comment]
@flatcap 
Sorry I didn't notice your bugfix build message earlier... I think the system didn't mail me because it wasn't a new comment. Anyway, I tried both builds... The latest build still has the problem (the code for `mutt_draw_statusline()` seems to be identical?), but the bug-fix build worked beautifully. Thanks for this update!

**Comment by flatcap** [comment]
@skeirik2 
/me looks embarrassed.  I forgot to include the fix I put in the bug-fix.  Sorry.
I'll push the changes **now**.

**Comment by skeirik2** [comment]
No problem. Thanks so much for your help! As far as I am concerned, the issue can be closed.

**Comment by flatcap** [comment]
#### This bug is now fixed and will be in the next release of NeoMutt.
