### ISSUE TITLE
Issues with IMAP and reconnect

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#410]
This is a spinoff of #346, as mentioned:

> @rr- I can confirm it works but after relogging, the mails in the inbox are gone and it shows empty list.

I can also sometimes reproduce weird behaviours after reconnecting, but it is not yet clear to me where the problem is. Using the issue to track investigation.

**Comment by gahr** [comment]
I might have tracked down the issue to the fact that IMAP does not *always* get back in status SELECTED after a reconnect. Investigating.

**Comment by rr-** [comment]
Information: this behavior seems to be very dependent on the IMAP server. Since I have switched from `gmail.com` to `mailbox.org`, the problem seems to no longer occur.

**Comment by oblitum** [comment]
Related (`imap_poll_timeout=0`): https://github.com/neomutt/neomutt/commit/64a58521149601999b0d9e5ff4b0f39ef549a066#commitcomment-24265591

**Comment by l29ah** [comment]
It's seems to be still an issue.

**Comment by oblitum** [comment]
@l29ah yeah, it is, I still have to reconnect manually sporadically.

**Comment by ElDeveloper** [comment]
I can also vouch for this still being an issue, specially noticeable in flaky internet connections. Which often leads to other problems like the problem described in #1038.

I ended up switching to rely on offlineimap and the overall user experience has improved a whole lot!

**Comment by amacfie** [comment]
Does neomutt have something like this commit from mutt? https://gitlab.com/muttmua/mutt/-/commit/44711a243ee8fe7dc5e206d0175a5026599275ef
