### ISSUE TITLE
Inbox opens slower after progress changes

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#4114]
## Expected Behaviour

My inbox opens fast.

## Actual Behaviour

Inbox now opens a bit slower and (unnecessarily?) shows progress.

- Always

## When did it start to happen?

bf5d12dde

Before the merge, there was no progress shown and it was a smooth "bootup" of NeoMutt. I prefer this before behavior, both because of the speed and the fast progress is unnecessary. Is it possible to only show the progress if the operation takes longer than, e.g., half a second? I think that might look a bit smoother.

## NeoMutt Version

```
NeoMutt 20231103-83-f551f5
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.2.0-37-generic (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libidn2: 2.3.3 (compiled with 2.3.3)
OpenSSL: OpenSSL 3.0.8 7 Feb 2023
libnotmuch: 5.6.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/local/include -DNCURSES_WIDECHAR -I/usr/local/include -O2

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme 
  -gsasl -gss +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster 
  +nls +notmuch +openssl +pgp +regex +sasl +smime -sqlite +truecolor 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Is your email local (maildir) or remote (IMAP)?

maildir.

**Comment by flatcap** [comment]
Argh, sorry.
I've been working with a modified Maildir and hadn't noticed.

I'd introduced a 0.1s delay at the end of the progress bar to aid visibility.
Unfortunately the current Maildir creates and destroys quite a few progress bars, so those 0.1s add up.

Please can you give branch [[devel/progress]](https://github.com/neomutt/neomutt/tree/devel/progress) a try.

Thanks

**Comment by flatcap** [comment]
> Is it possible to only show the progress if the operation takes longer than, e.g., half a second?

No, but it had crossed my mind.
(though how we decide if an action is going to take long, might be a challenge)

The Progress Bar has its own window, which is pushed into the Message Window stack.
Perhaps we could use `$time_inc`.
`set time_inc = 1000` (1 sec), then **if** after 1s we haven't reached at least 50%, then show the Window. 

We could combine this with a change to the default for `$time_inc`
Maybe, `500` (0.5s), fairly smooth updates, but quick actions would be invisible.

**Comment by scottkosty** [comment]
Thanks! I just tested devel/progress and that works great. I don't even see the progress bar. Let's close this on merge. Thank you!

**Comment by flatcap** [comment]
done, f800045b6

I'll keep thinking about making it smarter.
