### ISSUE TITLE
Office 365, Outlook emails

### ISSUE THREAD

**Issue by chenle02** [neomutt/neomutt#4143]
Hello Everyone,

I'm excited to share that NeoMutt has released a new version today, as I saw on GitHub. It's great to see that this project remains active and thriving! I was a daily user of NeoMutt for over two years but had to stop using it for the past two years. The reason was that my university email, which uses Microsoft Office 365, doesn't support the older IMAP protocol. I encountered significant challenges in configuring it correctly, especially with the authentication process, and eventually, I had to abandon it. With the recent updates to the project, I'm curious to know if there are any new features or improvements that now allow for smooth integration with Office 365?

Thank you so much!
Le

**Comment by gahr** [comment]
Hi @chenle02 , what are the difficulties you are encountering with Office 365? Authentication using OAuth should work using https://github.com/FrankGruellich/neomutt/blob/main/contrib/oauth2/mutt_oauth2.py. It's not something I do myself, but I've heard it said multiple times :)

**Comment by Knusper** [comment]
So the thing is, that some places who run microsoft exchange have indeed stopped offering imap access. 

For using mutt you need a Exchange -> Imap bridge - and DavMail comes to the rescue.

https://davmail.sourceforge.net/

Enjoy!

**Comment by gahr** [comment]
Please reopen if you need any more info.
