### ISSUE TITLE
Respect `umask` when saving attachments

### ISSUE THREAD

**Issue by doronbehar** [neomutt/neomutt#4148]
## What would you like to be able to do?

I use [Syncthing](https://syncthing.net) to sync documents, that sometimes I get on email. I run `syncthing` as a system service, with it's own user and group both named `syncthing`. My unix user is part of the `syncthing` group, and my most of my files at `~/documents` belong to the `syncthing` group - thus enabling the `syncthing.service` sync those files.

I aliased `neomutt` to `sg syncthing -c neomutt`, but still, it seems that attachments are saved with the permissions `500` by default, and there is no way to change that, and it doesn't matter what is my `umask`.

## What needs to change in NeoMutt?

It would have been great if `neomutt` would have honored `umask`, or if it would have been possible to configure it to honor `umask` settings.

## Have you tried any alternative methods?

- Macros: I was thinking of using a macro for that, but I don't know how the macro will know the path of the file I just saved with the `<save-entry>` command - seems impossible to me.
- Hooks: I didn't find a `<save-entry>` hook in the docs.
- Scripts: I could write a script that would completely override the interface with which I save attachments, but I'm not sure how to do that.

**Comment by roccoblues** [comment]
> It would have been great if `neomutt` would have honored `umask`, or if it would have been possible to configure it to honor `umask` settings.

I had a brief look into this. Seems like we override the `umask` during startup: https://github.com/neomutt/neomutt/blob/8e3ea66819fce92a334947009ed89351dbf1fab3/main.c#L557

However, even if we wouldn't do that, we explicitly create files with permission `0600` so no matter the `umask` you could never *add* bits for the group.

https://github.com/neomutt/neomutt/blob/8e3ea66819fce92a334947009ed89351dbf1fab3/mutt/file.c#L575

**Comment by doronbehar** [comment]
Thanks for the links! Indeed only deleting the `umask` line in `main.c` doesn't help the attachments scenario. Removing the `0600` argument in the `mutt/file.c` file, does make the running shell's umask be honored by mutt.

Now with the provided pointers, it should be fairly easy to create a configuration option that will make `neomutt` honor `umask` at least for saving attachments. I'd like to work on that, if you'd accept the feature.

**Comment by roccoblues** [comment]
> Now with the provided pointers, it should be fairly easy to create a configuration option that will make `neomutt` honor `umask` at least for saving attachments.

Based on my experience nothing is "easy" in NeoMutt land. 😏 

> I'd like to work on that, if you'd accept the feature.

Thank you for working on this already! I left some early thoughts. I'm also just a contributor so we need @flatcap's opinion here.
