### ISSUE TITLE
Subject debris in replies

### ISSUE THREAD

**Issue by nobrowser** [neomutt/neomutt#4156]
## Expected Behaviour

Replying to a message in a thread. The existing message has an attribution prefix in Subject:

```
Re: Foo Bar Baz
```

Expected: my reply should get the same Subject

## Actual Behaviour

An additional `Re:` prefix is added, resulting in

```
Re: Re: Foo Bar Baz
```

## Steps to Reproduce

Hit either `r` while paging though a personal message, or `L` while paging through a list message. Compose a reply message in the configured editor, exit the editor, inspect the preview headers.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded. Before: 20230517, now: 20231221

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20231221
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.2.9-x86_64-linode160 (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libidn2: 2.3.3 (compiled with 2.3.3)
PCRE2: 10.42 2022-12-11
storage: lmdb
compression: lz4

Configure options: --prefix=/usr/local --disable-doc --disable-pgp --disable-smime --lmdb --pcre2 --lz4

Compilation CFLAGS: -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -DNCURSES_WIDECHAR -I/usr/local/include -O2

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme
  -gsasl -gss +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster
  +nls -notmuch -openssl +pcre2 -pgp -sasl -smime -sqlite +truecolor

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: devuan daedalus

* Were you using multiple copies of NeoMutt at once: no

* Were you using 'screen' or 'tmux': `tmux` locally, `ssh` within `tmux`, `neomutt` within `ssh`

* Is your email local (maildir) or remote (IMAP): maildir

**Comment by nobrowser** [comment]
Additionally, I see some subtle changes in how Subject lines with `Re:` are *rendered* in the index view. Threads that used to render cleanly (ie. only spell out the subject on the first message in the thread) now show both the original subject on the first message and the prefixed subject on the 2nd message. This is minor, but I am guessing this is related to the issue.

**Comment by flatcap** [comment]
This may have already been fixed (merged yesterday)

- #4147
  b5640bbe6 envelope: manage subject/real_subj together

It fixed a bug in the config that affected regexes.

Please can you give `main` a try.

**Comment by nobrowser** [comment]
Ok will test main for my daily read tomorrow. Happy New Year!

**Comment by nobrowser** [comment]
And that seems to fix it, thanks! Both aspects now both to normal.

**Comment by flatcap** [comment]
Great, thanks for testing.
There'll be a new release out soon.
