### ISSUE TITLE
Manual sync "$" should be reflected immediately in status bar.

### ISSUE THREAD

**Issue by Knusper** [neomutt/neomutt#4157]
My status bar configuration is the following:

```
# status bar
set status_format="-%r- %f [Msgs:%?M?%M/?%m%?n? New:%n?%?o? Old:%o?%?d? Del:%d?%?F? Flag:%F?%?t? Tag:%t?%?p? Post:%p?%?b? Size: %l?]---(%s/%S)-%>-(%P)---"
set status_on_top=yes
```

I am accessing a IMAP mailbox with neomutt.   When I have read and maybe flagged some messages, I want to sync these changes with the mailbox, so I press `$` in the index view.  

## Expected Behaviour

 Status bar indicator `%r` changes  from `-*-` to `---` to indicate that the changes have been synced.

## Actual Behaviour

However, the status bar indicator `%r` does not change from `-*-` to `---`.  This only happens when I move to another message (e.g. by pressing the arrow keys)

## How often does this happen?

It does not happen when I marked messages for deletion.  Only when changing the status of messages "read / unread / flagged".

## When did it start to happen?

I haven't used `neomutt` for IMAP mailboxes in a very long time, so I don't know.
On my other machine with a very very old neomutt version that accesses a local maildir it does not happen.

## NeoMutt Version

```
NeoMutt 20231221
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.2.0-37-generic (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
GPGME: 1.16.0-unknown
GnuTLS: 3.7.3
libnotmuch: 5.6.0
storage: tokyocabinet

Configure options: --prefix=/home/edmundherenz/local --disable-idn2 --gpgme --lua --notmuch --with-ui --gnutls --tokyocabinet --sqlite --disable-autocrypt

Compilation CFLAGS: -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.4 -I/home/edmundherenz/local/include -I/home/edmundherenz/local/include -DNCURSES_WIDECHAR -I/home/edmundherenz/local/include -I/usr/include/p11-kit-1 -O2

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme 
  -gsasl -gss +hcache -homespool -idn +inotify -locales_hack +lua -mixmaster 
  +nls +notmuch -openssl +pgp +regex -sasl +smime +sqlite +truecolor
```

**Comment by flatcap** [comment]
Please can you give branch [[devel/status]](https://github.com/neomutt/neomutt/tree/devel/status) a try.

Thanks

**Comment by Knusper** [comment]
I'll try on the weekend.

**Comment by Knusper** [comment]
Tested and works as expected! Thanks!
