### ISSUE TITLE
get mail address from abook fail when forget add Comma

### ISSUE THREAD

**Issue by wanderl5** [neomutt/neomutt#4179]
## Expected Behaviour

when i compose an email, i usually need to specify multiple recipients, i will type in head char and use tab to query from abook to auto complete;

## Actual Behaviour
 it always works ok, but when i forget to type "," between recipients and press tab , then it will get error like:
"cannot open xxx@gmail.com: No such file"

## Steps to Reproduce

- compose new mail, not add comma between recipients and press tab

## How often does this happen?

- Always

## When did it start to happen?

- when compose or reply a mail

## NeoMutt Version

NeoMutt 20231221
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.1.0-14-amd64 (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libidn2: 2.3.3 (compiled with 2.3.3)

Configure options: --disable-doc

Compilation CFLAGS: -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -DNCURSES_WIDECHAR -I/usr/include -O2

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme 
  -gsasl -gss -hcache -homespool +idn +inotify -locales_hack -lua -mixmaster 
  +nls -notmuch -openssl +pgp +regex -sasl +smime -sqlite +truecolor 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

**Comment by gahr** [comment]
I think it's ok to close this?

**Comment by wanderl5** [comment]
it's ok now, Thx a lot.
