### ISSUE TITLE
Configure default subject prefix for reply messages

### ISSUE THREAD

**Issue by rakab** [neomutt/neomutt#4187]
Wouldn't it make more sense if there would be an option to set the default prefix for reply messages in the config? I think currently this is hard-coded here:
https://github.com/neomutt/neomutt/blob/911705318c0275172eb5527a137910954d86d7f3/send/send.c#L1082

It would be nice to be able to control this from the config, like it's done for `forward_format` for example.

**Comment by ossilator** [comment]
no. this is actually standardized, and translations or other customizations are misguided. translation should be done on the receiving end.

**Comment by rakab** [comment]
At which level should the translation happen, on mailserver, during the sync or inside neomutt? For example currently I have my mailbox filled with messages with "Re:" and German "Aw:" prefixes. Isn't this the very reason why the default `reply_regex` contains multiple options for the prefixes, like `"^((re|aw|sv)(\\[[0-9]+\\])*:[ \t]*)*"` ?

**Comment by ossilator** [comment]
in the displaying MUA, i.e., neomutt in your case.

that regex is a workaround for MUAs (well, predominantly outlook, as usual) not sticking to the standard.

**Comment by rakab** [comment]
I see, thanks for the clarifications!
