### ISSUE TITLE
Neomutt time to time: Fetching message headers...

### ISSUE THREAD

**Issue by szaszg** [neomutt/neomutt#4192]
My relevant config lines:
```
set imap_user = xrixxrax.crixcrax@putty.putty
set imap_pass = *****
set folder = imaps://10.1.11.22//
set spoolfile = imaps://10.1.11.22//
unmailboxes *
mailboxes =INBOX
set imap_check_subscribed

\# Specify where to save and/or look for postponed messages.
set postponed = "+Work In Progress"
set record = "+Sent Items"

folder-hook +INBOX$       "set sort=threads"
folder-hook "+Sent Items" "set sort=reverse-date"

\# Allow Mutt to open a new IMAP connection automatically.                                                                                                                                                       
unset imap_passive
set imap_peek = "no"
set imap_rfc5161 = "yes"
set imap_fetch_chunk_size = 65536
set imap_idle = "no"
\# Keep the IMAP connection alive by polling intermittently (time in seconds).
set imap_keepalive = 300
\# How often to check for new mail (time in seconds).
set mail_check = 30
set timeout = 60

set header_cache = ~/.mutt/cache
set message_cachedir = ~/.mutt/cache
```

## Expected Behaviour

If the format of cache (header and/or message) changed, neomut should rebuild the caches offline, converting the old format to new.

## Actual Behaviour

If I upgrading neomutt (built a fresh from git), sometimes neomutt refetch all message headers (Fetching message headers...). 

## Steps to Reproduce

Start a new version of neomutt :)

## How often does this happen?

- Sometimes

## When did it start to happen?

Not relevant.

## NeoMutt Version

```
NeoMutt 20240201
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.5.5stork (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libidn2: 2.3.3 (compiled with 2.3.3)
OpenSSL: OpenSSL 3.0.11 19 Sep 2023
libnotmuch: 5.6.0
storage: gdbm
compression: lz4

Configure options: --prefix=/home/gergely/bin/neomutt --disable-doc --disable-idn --fmemopen --ssl --locales-fix --homespool --sasl --gdbm --notmuch --lua --with-lua=/usr --sqlite --lz4

Compilation CFLAGS: -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.2 -I/home/gergely/bin/neomutt/include -I/home/gergely/bin/neomutt/include -DNCURSES_WIDECHAR -I/home/gergely/bin/neomutt/include -I/home/gergely/bin/neomutt/include -O2

Compile options:
  -autocrypt +fcntl -flock +fmemopen +futimens +getaddrinfo -gnutls -gpgme 
  -gsasl -gss +hcache +homespool +idn +inotify +locales_hack +lua -mixmaster 
  +nls +notmuch +openssl +pgp +regex +sasl +smime +sqlite +truecolor 
```

## Extra Info

* Operating System and its version:  Linux stork 6.5.5stork_\\#\2_ SMP PREEMPT_DYNAMIC Tue Oct  3 18:43:16 +01 2023 x86_64 GNU/Linux Debian GNU/Linux 12 (bookworm)
* Were you using multiple copies of NeoMutt at once:? No
* Were you using 'screen' or 'tmux'? screen
* Is your email local (maildir) or remote (IMAP)? IMAP

**Comment by gahr** [comment]
Sometimes the structures that we cache in the header cache change and this invalidates the cache. We don't retain the old structures in the new code. We don't have a better way to migrate an older cache to a newer version. In my opinion, a full invalidation is the safest solution (cache coherency is hard). This is definitely not a bug. At best, the experience could be improved, but I doubt we have developers' time and interest in doing it.

**Comment by szaszg** [comment]
Uhum i see...

But very annoying when I update the program and firs start a have to wait more then 15 minutes, when neomutt refetch all headers.

And after some day, when i open "sent" messages folder an another suprising "coffe break".

Not a bug... but "this one just sucks more" :).

**Comment by gahr** [comment]
I see you use gdbm. See if performance increases using lmdb.

**Comment by gahr** [comment]
Yeah it can definitely be, depending on your connection with the IMAP server.
