### ISSUE TITLE
Search/Limit search To: not From: in sent mails

### ISSUE THREAD

**Issue by szaszg** [neomutt/neomutt#4194]
## What would you like to be able to do?

Search/search-reverse/Limit should search the To: field instead of From: when the mail is *outgoing*.

**Comment by gahr** [comment]
To formalize this a bit more: do you mean to say you'd like `~f` to become `~t` when the current folder matches the `record` setting? Would you also change `~t` to match `~f`? What about `~C`? Also, wow would you match `Cc` only, i.e., `~c`?

I'm not sure I buy the proposal.

**Comment by ossilator** [comment]
> I'm not sure I buy the proposal.

me neither. i think it would be extremely confusing.

i suppose the use case is "uniform command for finding conversations with a particular person", but this proposal doesn't seem like a good solution for that.

**Comment by szaszg** [comment]
:)

Not. I'm not want ~t become ~f or annything around -C.

When i want to see messages from a particular e-mail addres, i just type 'l' ("Limit to messages matching:") and type a fragment of the e-mail address: e.g.: "neomutt". Now i see all messages come from blahblah@neomut... (o.k. and maybe some other, when e.g. in the subject includes the word "neomutt")

When I open my sent folder and do the same, a see nothing. Because limit search only in "from:", but not in "to:".

O.k. I know i can use the "~t " magic thing, but:
 - I don't think there's much benefit in searching "from:" for outgoing mails
 - IMHO users secretly hope that: when search in outgoing mail folder, the pattern matches recipients' addresses instead their own address (I understand that this is consistent, but at least from an "average" point of view, it's funny, right?)
 - so by default we do not need any "magic", only if somebody want to search for recipients in  inbox (~t) or for sender in outbox (~f)

So i think neomutt now search by default (if we do not type any magic ~t ~c whatever) in:
- from:
- subject:
- date:
- .. (i don't know the exact list)

And i think it will be better, if neomutt when user search in "sent folder" (or even more advanced if the search try to match an "outgoing message"), uses "to:" instead of "from:" for pattern matching (and of curse all other fields)

I hope, now it is a little bit cleaner ;)

btw: IMHO this "feature" works in "other sucking mail clients" this way too... e.g.: if i type an email address in Groupwise's "fast search field" it match "to:" address's of "outgoing" messages and "from:" address's of "incoming" messages.

**Comment by gahr** [comment]
> When i want to see messages from a particular e-mail addres, i just type 'l' ("Limit to messages matching:") and type a fragment of the e-mail address: e.g.: "neomutt". Now i see all messages come from blahblah@neomut... (o.k. and maybe some other, when e.g. in the subject includes the word "neomutt")

I see - you're relying on [simple_search](https://neomutt.org/guide/reference.html#3-435-%C2%A0simple_search). Feel free to tweak it to include `~f` and `~t` , or modify it using a [folder-hook](https://neomutt.org/guide/configuration.html#folder-hook) so  it does what you want based on the folder you're in.

Hope this helps.

**Comment by szaszg** [comment]
Thanks.
>Hope this helps.
Yes... and no ;) This is a "diy" workaround.

IMHO neomutt "simple_search" by default should work like other "big" email clients "simple search"'s. So simple search by default should use  “ ~f %s | ~s %s ” for incoming messages and “ ~t %s | ~s %s ” for outgoing messages, or at least “ ~f %s | ~s %s ” on messages in "not sent" folders and “ ~t %s | ~s %s ” for messages in "sent" folders.

I think this could be a good enhancement for users.  (for a better user experience:)

**Comment by gahr** [comment]
> Yes... and no ;) This is a "diy" workaround.

Yes, NeoMutt is very much a DIY mailer: the config is there so you can change it.

> I think this could be a good enhancement for users. (for a better user experience:)

Yes, it *could* be. Or not. Depending on each user's preference. It's hard to tell, and I'm a bit reluctant to propose a change in `simple_search`. If we did want the change, I'd suggest to make it `~f %s | ~C %s | ~s %s` always.
