### ISSUE TITLE
folder-hook on named-mailboxes doesn't match regex against label or mailbox consistently

### ISSUE THREAD

**Issue by dorsiflexion** [neomutt/neomutt#4201]
## Steps to Reproduce

- `neomutt -Z` → said mailbox opens
- delete email
- press `q` (quit)

## Expected Behaviour

- email gets deleted
- neomutt quits without any further user input

## Actual Behaviour

- one gets asked if they want to purge the email(s)

## How often does this happen?

- Always

## Config

- no global `delete` setting, i.e. `ask-yes` globally
```
folder-hook 'address@example.com' 'source "$XDG_CONFIG_HOME/neomutt/accounts/address@example.com"'
```
`$XDG_CONFIG_HOME/neomutt/accounts/address@example.com` (among other irrelevant options): 
```
set delete = yes
```

## NeoMutt Version

```
NeoMutt 20240201
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.7.9-hardened1-1-hardened (x86_64)
ncurses: ncurses 6.4.20230520 (compiled with 6.4.20230520)
libidn2: 2.3.7 (compiled with 2.3.4)
GPGME: 1.23.2
GnuTLS: 3.8.3
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --ubsan --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/neomutt/src=/usr/src/debug/neomutt -flto=auto -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.3 -I/usr/include -I/usr/include -I/usr/include -DNCURSES_WIDECHAR -I/usr/include -I/usr/include/p11-kit-1 -I/usr/include -I/usr/include -fsanitize=undefined -fno-omit-frame-pointer -fno-common -g -O0

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme
  -gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster
  +nls +notmuch -openssl +pgp +regex +sasl +smime +sqlite +truecolor

Devel options:
  ubsan

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

The [Documentation](https://neomutt.org/guide/configuration#9-%C2%A0setting-variables-based-upon-mailbox) says:
> The command is executed before loading any mailboxes matching regex .

As there are no exceptions stated there, this behaviour is not to be expected.

Yes, the regex is correct. The account file is sourced and `delete` is set if I enter the mailbox manually. Also, `neomutt -f …` sources everything correctly.

**Comment by roccoblues** [comment]
Hi,

can you run NeoMutt with debug logging `-d5` and post the result here? Make sure to remove any sensitive data.

Thanks!

**Comment by dorsiflexion** [comment]
I'm digging a little further and just found out what the actual problem is: For named-mailboxes the `folder-hook` regex is sometimes matched against the label, sometimes against the mailbox.

Here is what I mean by label and mailbox: from the man page: `named-mailboxes label mailbox [label mailbox ... ]`

When starting neomutt (`-Z` or not doesn't matter), the `folder-hook` regex is only matched against the mailbox. I can verify that by having a regex that matches only the label, which fails, vs. having a regex that matches both, where the log explicitly says it matches against the mailbox.

When navigating the sidebar (i.e. `sidebar-{prev,next,open}`), the `folder-hook` regex is matched against the label, too. Because the regex from above that only matched the label now succeeds.

I will later hand in a config example and a debug log.

**Comment by dorsiflexion** [comment]
Strange. According to the debug log, the mailbox is added before the hook executes. So I'm not quite sure if that was the reason to do it this way:
```
[2024-03-19 14:13:00]<1> mailbox_add() Adding mailbox: '+mailboxa' label 'labela', poll [UNSPECIFIED], notify [UNSPECIFIED]
[…]
[2024-03-19 14:13:00]<1> mutt_folder_hook() folder-hook 'mailboxa' matches '/home/username/.local/share/mail/mailboxa'
```

**Comment by roccoblues** [comment]
Can you give the branch `roccoblues/hook-functions` a try and see if that fixes the issue? Thanks.

**Comment by dorsiflexion** [comment]
That fixes this issue for me. 👌
