### ISSUE TITLE
All drafts are deleted if you delete one.

### ISSUE THREAD

**Issue by jb55** [neomutt/neomutt#4210]
I was trying to figure out why all my drafts were getting wiped out, I was able to reproduce it and I found the behavior very confusing. It's such a bad experience I suspect it must be a bug?

When I cancel *any* draft it wipes out all existing drafts. Steps to reproduce below.

## Steps to Reproduce

1. Start a draft, save it.

2. Start another draft, save it.

Open the second draft, and instead of postponing it again, don't.

The entire ~/postponed file is now empty and all drafts are gone.

3. If you try this one the first draft instead of the second, it won't nuke everything, but it will duplicate it.

## Expected Behaviour

I expected to only have one of the drafts deleted

## Actual Behaviour

All drafts are deleted

## How often does this happen?

- Always

## NeoMutt Version

```
NeoMutt 20231221
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.7.5 (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.23.2-unknown
OpenSSL: OpenSSL 3.0.13 30 Jan 2024
libnotmuch: 5.6.0
storage: lmdb
compression: zlib, zstd

Configure options: --prefix=/nix/store/k4hgwwrzf4s1yv7aq6gd4fks66vahs9a-neomutt-20231221 --enable-autocrypt --gpgme --gss --lmdb --notmuch --ssl --sasl --with-homespool=mailbox --with-mailpath= --disable-include-path-in-cflags --zlib --zstd

Compilation CFLAGS: -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -DNCURSES_WIDECHAR -O2

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme 
  -gsasl +gss +hcache +homespool +idn +inotify -locales_hack -lua -mixmaster 
  +nls +notmuch +openssl +pgp +regex +sasl +smime +sqlite +truecolor 

MAILPATH="mailbox"
PKGDATADIR="/nix/store/k4hgwwrzf4s1yv7aq6gd4fks66vahs9a-neomutt-20231221/share/neomutt"
SENDMAIL="sendmail"
SYSCONFDIR="/nix/store/k4hgwwrzf4s1yv7aq6gd4fks66vahs9a-neomutt-20231221/etc"
```

## Extra Info

- I'm using notmuch, but I doubt that matters?

**Comment by gahr** [comment]
I can reproduce it, but only with a local draft folder in mbox format.

You can get two equally bad behaviours:

**All drafts are gone**
1. compose, subject=test1, postpone
2. compose, NeoMutt asks to recall, don't recall, subject=test2, postpone
3. compose, NeoMutt asks to recall, recall, the folder view lists test1 and test2, **pick test1**, discard, don't postpone
4. compose, NeoMutt asks to recall, recall -> **No postponed messages** error

**Duplicated drafts**
1. compose, subject=test1, postpone
2. compose, NeoMutt asks to recall, don't recall, subject=test2, postpone
3. compose, NeoMutt asks to recall, recall, the folder view lists test1 and test2, **pick test2**, discard, don't postpone
4. compose, NeoMutt asks to recall, recall, the folder view lists **test1 twice**

**Comment by flatcap** [comment]
Thanks for the bug-report, @jb55.
I'm really sorry about your data loss.

I've recalled the last release, 2024-03-23.

It's been caused by a fix I made to the history: af74f5448, which introduced an `O_TRUNC` into `mutt_file_fopen_full()`.

That's easily reverted, but I still need to figure out how to re-fix the history.

**Comment by jb55** [comment]
On Mon, Mar 25, 2024 at 04:14:53PM -0700, Richard Russon wrote:
>Thanks for the bug-report, @jb55.
>I'm really sorry about your data loss.

I had a few fairy large code reviews queued up and now they are all gone 🥲

In the meantime I will just make sure to never cancel a draft 😅

>It's been caused by a fix I made to the history: af74f5448, which
>introduced an `O_TRUNC` into `mutt_file_fopen_full()`.

It seems like the issue is still there with this change.

I was also able to reproduce the draft duplication by not-postponing the
first saved draft instead of the second 🤔. very odd.

**Comment by flatcap** [comment]
Please can you give branch [[devel/mbox]](https://github.com/neomutt/neomutt/tree/devel/mbox) a try.

PR #4125 Explains some of the ugliness behind the scenes.

Thanks

**Comment by jb55** [comment]
On Tue, Mar 26, 2024 at 07:21:05AM -0700, Richard Russon wrote:
>Please can you give branch [[devel/mbox]](https://github.com/neomutt/neomutt/tree/devel/mbox) a try.

This fixes it for me! Thanks!

**Comment by flatcap** [comment]
Great!  Thanks!
