### ISSUE TITLE
add a mention bot to github

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#423]
The GIthub of [NixOS](https://github.com/NixOS/nixpkgs/pull/23085#issuecomment-281790667) has a really nice bot, who's basically mentioning people who have already worked in the part of the files the PR is changing .

Although our current development team is rather small, i think it might be valuable in the future.

 BTW: [here](https://github.com/facebook/mention-bot)'s the corresponding Github repo.

**Comment by guiniol** [comment]
That sounds neat. I have two concerns, but they are not very big:
- we have to be careful not to become specialists, ie that person wrote code in this file so now, he's in charge of that file and doesn't really look outside. I don't actually think there's a big risk (the code is not large enough), but it's worth noting.
- I would think we haven't committed in a lot of places, so we have to be careful that upstream doesn't get mentioned, I don't think they would like it. This would change after cleaning up the indents and whoever did that would be the default guy mentioned.

**Comment by flatcap** [comment]
It's a nice idea for big projects
I'm sure we can steal some ideas...

> we have to be careful that upstream doesn't get mentioned

Yes, that would be bad.
We'd need a whitelist of our users (or a blacklist of theirs).

> This would change after cleaning up the indents

I was planning to use a "dummy" user for the mass transformations.
