### ISSUE TITLE
`view-raw-part` to view a raw part

### ISSUE THREAD

**Issue by alejandro-colomar** [neomutt/neomutt#4230]
## What would you like to be able to do?

View a MIME part raw.

While debugging code for protecting headers, I need to be able to verify a message with the signature manually.  It would be nice if I can get the raw MIME part so that I can save it as a file, save the signature as another file, and verify the signature manually.

## What needs to change in NeoMutt?

Similar to `view-raw-message`, I'd maybe add a `view-raw-part` command.

## Have you tried any alternative methods?

- Macros
- Hooks
- Scripts

Yeah; nothing useful, I think.

## Additional Info

<https://github.com/neomutt/neomutt/issues/4229>

**Comment by flatcap** [comment]
If you just want to save it, then this might work OK:

```
set pipe_decode = no
<pipe-entry>cat > file<enter>
```

I haven't checked, but I guess `<save-entry>` would automatically do the decoding.

**Comment by alejandro-colomar** [comment]
> If you just want to save it, then this might work OK:
> 
> ```
> set pipe_decode = no
> <pipe-entry>cat > file<enter>
> ```
> 
> I haven't checked, but I guess `<save-entry>` would automatically do the decoding.

It doesn't.  `pipe-entry` (`|` on the part index) or `pipe-message` (`|` on the pager) + `cat` do NOT show the protected headers to stdout.

`pipe_decode` defaults to no, and I didn't change it in my muttrc(5).

**Comment by alejandro-colomar** [comment]
Since it's easy to manually extract the part with `view-raw-message`, by cutting at the right points, and then replacing the end-of-lines by `\r\n`, as mentioned in <https://github.com/neomutt/neomutt/issues/4229>, this is less of a problem.  I'll close it as wontfix, at least for now.

**Comment by flatcap** [comment]
Oh, sorry.  I nearly got around to commenting in time...

`<view-raw-part>` wouldn't be particularly useful to anyone except developers (except the two of us :-)
but it'd would be very simple to implement and add very little code.

So if you think it'd be useful, I don't have any objections.

**Comment by alejandro-colomar** [comment]
I think it could be useful.  Let's revisit this after a couple of months.  We have a lot of food in the plate already.  :)
