### ISSUE TITLE
`crypt_protected_headers_write` should be removed, or at least default to `yes`

### ISSUE THREAD

**Issue by alejandro-colomar** [neomutt/neomutt#4236]
As seen in recently reported security vulnerabilities, we need to protect more headers.

Link: <https://github.com/neomutt/neomutt/issues/4223>
Link: <https://github.com/neomutt/neomutt/issues/4226>

This makes me wonder...

`crypt_protected_headers_write` defaults to `no`.  This is insecure.  Is there any reason why we would want to support the feature?

I strongly suggest:

-  Change the default behavior to `yes`.  This is a silent breaking change.

And secondarily, it might be good to

-  Remove the variable.  This is a Breaking Change.

Although the latter suggestion would be more controversial.

**Comment by flatcap** [comment]
> Change the default behavior to `yes`

That sounds reasonable...

> Remove the variable

We can easily do that too.
The config system has a flag `D_INTERNAL_DEPRECATED` which means options can be silently ignored.

**Comment by alejandro-colomar** [comment]
> > Change the default behavior to `yes`
> 
> That sounds reasonable...
> 
> > Remove the variable
> 
> We can easily do that too. The config system has a flag `D_INTERNAL_DEPRECATED` which means options can be silently ignored.

Hmmm, sounds good!  I'll add those changes to the current PR (<https://github.com/neomutt/neomutt/pull/4227>).

**Comment by alejandro-colomar** [comment]
The default has been changed to `yes` in 43c11a6a2a7130103b706a72c58fd123823fda98:

```
commit 43c11a6a2a7130103b706a72c58fd123823fda98
Author: Alejandro Colomar (@alejandro-colomar) <alx@kernel.org>
Date:   Mon Apr 8 17:52:04 2024 +0200

    $crypt_protected_headers_write: Change default to 'yes'
    
    Link: <https://github.com/neomutt/neomutt/issues/4236>
    Link: <https://github.com/neomutt/neomutt/issues/4223>
    Link: <https://github.com/neomutt/neomutt/issues/4226>
    Reviewed-by: наб <nabijaczleweli@nabijaczleweli.xyz>
    Cc: Richard Russon <rich@flatcap.org>
    Signed-off-by: Alejandro Colomar <alx@kernel.org>
```
