### ISSUE TITLE
Why are lists trimmed (to 10)?

### ISSUE THREAD

**Issue by alejandro-colomar** [neomutt/neomutt#4252]
https://github.com/neomutt/neomutt/blob/63f1e496504b3bfe9126f959d43de1de73eb4a95/send/header.c#L514

I found that neomutt(1) doesn't really support more than 10 references.  This seems to be arbitrary.  Is there a reason why we allow unlimited entries in for example `Cc:` but only up-to 10 `In-Reply-To:` or `References:`?

**Comment by alejandro-colomar** [comment]
Here's a blame of it:

```
commit 646d479fe2f5da84bd3f168a21efc6ac05c02673
Author: UPSTREAM Aron Griffis <agriffis@n01se.net>
Date:   Thu Jul 10 09:38:25 2008 -0400

    Unify mutt_write_references
    
    copy.c and sendlib.c have independent and different implementations of writi
ng
    references to a file.  Choose the one in sendlib since it's conservative wit
h
    mallocs and supports trimming the list.
    
    Signed-off-by: Aron Griffis <agriffis@n01se.net>
```

**Comment by flatcap** [comment]
Actually, it looks like that commit just parameterises the `10`.
There's a `TrimRef` in the original commit:
https://github.com/neomutt/neomutt/blob/1a5381e07e97fe482c2b3a7c75f99938f0b105d4/sendlib.c#L1017

All the emails I can find seem to have zero or one `References:` or `In-Reply-To:`
The language in [RFC5322 3.6.4](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6.4) seems to imply we'd only ever see one of each of them.

`References:` is one of the header fields that we cache in memory,
but there are lots of other ways a rogue email could use lots of memory.

So... don't know :-)

**Comment by alejandro-colomar** [comment]
> Actually, it looks like that commit just parameterises the `10`. There's a `TrimRef` in the original commit:
> 
> https://github.com/neomutt/neomutt/blob/1a5381e07e97fe482c2b3a7c75f99938f0b105d4/sendlib.c#L1017
> 
> All the emails I can find seem to have zero or one `References:` or `In-Reply-To:` The language in [RFC5322 3.6.4](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6.4) seems to imply we'd only ever see one of each of them.

I read the opposite there.  It's usual to only find one, but the language allows several:

```
The "References:" and "In-Reply-To:" fields each contain one or more
unique message identifiers, optionally separated by CFWS.
```

And just today I received a mail that responded to two mails at once, and had two `In-Reply-To`s.

And people seem to tallk about the technical possibility <https://stackoverflow.com/questions/36438139/multiple-in-reply-to>, although admitting that MUAs probably don't support it well.

> 
> `References:` is one of the header fields that we cache in memory, but there are lots of other ways a rogue email could use lots of memory.
> 
> So... don't know :-)

Hmmm :-(

**Comment by ossilator** [comment]
alejandro is correct.

as far as the limitation of the count of references goes, one needs to ask oneself what they are good for in the first place, given that there is an in-reply-to header anyway? the answer is as usual historical, references coming from [usenet](https://www.rfc-editor.org/rfc/rfc1036#section-2.2.5). but they still serve a function, as one can reconstruct threads with missing messages thanks to them. and obviously, there is a point where this stops making sense, because a thread with too many missing messages just isn't all that useful. note that the linked rfc also encourages trimming.

**Comment by alejandro-colomar** [comment]
Thanks!  That makes sense.

**Comment by ossilator** [comment]
> I just discovered this in [RFC5322 3.6](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6)

this pertains to the occurrences of the headers, not their contents, so it doesn't seem relevant here.

**Comment by alejandro-colomar** [comment]
> > I just discovered this in [RFC5322 3.6](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6)
> 
> this pertains to the occurrences of the headers, not their contents, so it doesn't seem relevant here.

It also documents their contents, a few pages below:
<https://datatracker.ietf.org/doc/html/rfc5322#section-3.6.4>

**Comment by alejandro-colomar** [comment]
And since there's a reference to CFWS, here's what it means:
<https://stackoverflow.com/a/42193413/6872717>
