### ISSUE TITLE
When forwarding a message, it should probaly add a References header field

### ISSUE THREAD

**Issue by alejandro-colomar** [neomutt/neomutt#4257]
When forwarding a message, it should probably have a `References` header field, so that it can be correctly threaded.  No?

Similar to how replies add `In-Reply-To`.

**Comment by ossilator** [comment]
no, i don't think so. it _isn't_ the same thread, just some forwarded content from another one. in fact, it can be quite disastrous when the spun off thread gets mixed up with the original one.

in cases where it's really desired, the link-threads function can be used manually. i do that on a somewhat regular basis.

one could extract and correlate message-ids from embedded messages, and create weak links (similar to those based on subjects) from that. but the UI should make it really clear that these are not regular thread links.

**Comment by alejandro-colomar** [comment]
I'm reopening for consideration of something I found:

thunderbird(1) does precisely this:

It adds a references header, and threads the fwd with the original message.

**Comment by alejandro-colomar** [comment]
Ahh, thunderbird(1) not only it adds a References; it adds both References and In-Reply-To, so it's just like a reply regarding these headers.

**Comment by alejandro-colomar** [comment]
@ossilator , @flatcap , @gahr  How about a new configuration option?  I hate having configuration options, but this seems a place where it makes sense that each one would want a different behavior.

**Comment by gahr** [comment]
I am not in favour of this. https://www.rfc-editor.org/rfc/rfc5322#section-3.6.4 speaks of replies explicitly, not of forwards.

**Comment by alejandro-colomar** [comment]
@sdaoden, do you know what other MUAs do in this regard?

**Comment by gahr** [comment]
Right, and this sentence to me suggests that headers that identify a conversation of which the original message is part of, should not be in the forwarded message:

"A forwarded message in this sense does not appear to have come from the original sender, but is an entirely new message from the forwarder of the message."

But now I'm curious: if the recipient of the message can link it to an existing thread in his mailbox via References, why the message needs to be forwarded to him in the first place? Are we talking about A, B, C having a thread, at a certain point A replies only to B, and B wants to forward it to C? I guess a reply with a modified recipient would fit better, no?

**Comment by alejandro-colomar** [comment]
> But now I'm curious: if the recipient of the message can link it to an existing thread in his mailbox via References, why the message needs to be forwarded to him in the first place? Are we talking about A, B, C having a thread, at a certain point A replies only to B, and B wants to forward it to C? I guess a reply with a modified recipient would fit better, no?


No, the recipient of the forwarded mail doesn't need it to be threaded.  It's the sender of the forwarded email.

That is:

I receive a message from Bob.

I forward it to Alice.

I want to have both of them together, so that when I see the message from Bob, I can also see the conversation I had with Alice about it.

**Comment by gahr** [comment]
Oh, in that case, avoid leaking information to Alice that she's not supposed to see, I guess you'd only want to keep References in the copy you keep for yourself, not in the mail you send to Alice.

**Comment by alejandro-colomar** [comment]
> Oh, in that case, avoid leaking information to Alice that she's not supposed to see, I guess you'd only want to keep References in the copy you keep for yourself, not in the mail you send to Alice.

When you forward a message, you already get a copy of the Message-ID header in the forwarded message, so that wouldn't leak any more.

(Or maybe I forward it because I have the following.  Anyway, I don't mind leaking that.)

```rc
$ cat .config/mutt/pager.muttrc 
unignore Date
unignore Return-Path From To Cc Bcc Sender Reply-To
unignore Mail-Followup-To X-Original-To
unignore Subject
unignore Message-Id References In-Reply-To
```

**Comment by alejandro-colomar** [comment]
Maybe I should just do that, if I'm the only weirdo that want to do this.  :-)

**Comment by sdaoden** [comment]
not really.  alpine and the one i maintain support "forward-as-attachment", alpine supports multiple forwards via MIME digest.  alpine is much more sophisticated as we are (for now), it seems it can selectively forward text MIME parts (from looking at the code), whereas we simply attach the entire message.  I think we both only copy the subject to the new message.  (With my simple thing users can select which headers to include in the forwarded message in the non-forward-as-attachment code, separate from which headers are selected when viewing messages.  At least.)
Otherwise no idea, but i agree with the others beside that.

**Comment by alejandro-colomar** [comment]
> not really. alpine and the one i maintain support "forward-as-attachment", alpine supports multiple forwards via MIME digest. alpine is much more sophisticated as we are (for now), it seems it can selectively forward text MIME parts (from looking at the code), whereas we simply attach the entire message. I think we both only copy the subject to the new message. (With my simple thing users can select which headers to include in the forwarded message in the non-forward-as-attachment code, separate from which headers are selected when viewing messages. At least.) Otherwise no idea, but i agree with the others beside that.

Thanks!  I'll manually do it myself, I guess.

For anyone that arrives to this bug report and wonders how to do it:

If you want to forward any header fields, `unignore` them.  They will be automagically forwarded.
Then, for adding the In-Reply-To header field, just unignore the Message-ID, and do the obvious manual copy in the editor.
