### ISSUE TITLE
save-hook only works once?

### ISSUE THREAD

**Issue by martonbalazs** [neomutt/neomutt#4258]
## Expected Behaviour

Did
`:save-hook .* =foo`
which changes the default mailbox to save to "foo" as expected.

Then did
`:save-hook .* =bar`
hoping that the default mailbox now becomes "bar".

## Actual Behaviour
Instead, it stays "foo". I.e., save-hook only seems to work once.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded from 20240329-2 to 20240416-1 (on Arch)
## NeoMutt Version

```
NeoMutt 20240416
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.6.27-1-lts (x86_64)
ncurses: ncurses 6.4.20230520 (compiled with 6.4.20230520)
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.23.2
GnuTLS: 3.8.5
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --ubsan --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/neomutt/src=/usr/src/debug/neomutt -flto=auto -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.3 -I/usr/include -I/usr/include -I/usr/include -DNCURSES_WIDECHAR -I/usr/include -I/usr/include/p11-kit-1 -I/usr/include -I/usr/include -fsanitize=undefined -fno-omit-frame-pointer -fno-common -g -O0

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme 
  -gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster 
  +nls +notmuch -openssl +pgp +regex +sasl +smime +sqlite +truecolor 

Devel options:
  ubsan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

```

## Extra Info

* Operating System and its version
Arch, updated
* Were you using multiple copies of NeoMutt at once?
No
* Were you using 'screen' or 'tmux'?
No
* Is your email local (maildir) or remote (IMAP)?
maildir

Could there be a connection to #4180 ?

**Comment by martonbalazs** [comment]
Sorry, I'm not very familiar with the release cycle but this bug still seems to be present in 2024-10-02. Can we hope that the fix makes it into a release soon? Many thanks.

**Comment by flatcap** [comment]
hmm... sorry.
I'll take another look.

**Comment by martonbalazs** [comment]
Thanks so much and please let me know if I can be of help.

**Comment by flatcap** [comment]
Please can you give branch [[devel/save-hook]](https://github.com/neomutt/neomutt/tree/devel/save-hook) a try.

Thanks

**Comment by martonbalazs** [comment]
Thanks, the error is gone, it works! (But I had to remove the two xsltproc lines from Makefile as I got
`I/O error : unsupported protocol: https
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/xhtml/chunk.xsl"
compilation error: file ./docs/chunk.xsl line 3 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/xhtml/chunk.xsl
make: *** [Makefile:1040: docs/index.html] Error 5`
and I couldn't figure out what was going on here (sorry I'm not very experienced in compiling) and then fed empty html files into docs/ for make install to run when it was missing them).

**Comment by flatcap** [comment]
> it works!

Brilliant!

> I had to remove the two xsltproc lines from Makefile

Ah, the docs...
There are two ways to handle this:

1. Disable the docs: `./configure --disable-doc ...`
2. Install the DocBook style sheets.
    The package name varies by distro, e.g.
    - Debian: `docbook-xsl`
    - Fedora: `docbook-style-xsl`
