### ISSUE TITLE
Newline in attribution no longer properly handled

### ISSUE THREAD

**Issue by jkorb** [neomutt/neomutt#4271]
## Expected Behaviour

I have a newline character "\n" in my string for ```attribution```. This used to be printed as a newline in reply messages, but since the latest upgrade it prints as a "?".

## Actual Behaviour

When including a "\n" in the string for ```attribution```, a "?" is printed instead.

## Steps to Reproduce

1. Put the following into muttrc

```
set   attribution = "On %d, %n wrote:\n"
```

2. Create a reply message. The relevant line is printed as something like:

```
On 24.04.2024 16:38, Jon Doe wrote:?
```

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

neomutt-20240329-2

Downgrading fixes the issue.

I tried the neomutt-git AUR package, which is on 250e6180f342db1d95700c641c8433af7c0ca80c and the bug persists.

## NeoMutt Version

```
NeoMutt 20240329
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.8.7-arch1-1 (x86_64)
ncurses: ncurses 6.4.20230520 (compiled with 6.4.20230520)
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.23.2
GnuTLS: 3.8.4
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --ubsan --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/neomutt/src=/usr/src/debug/neomutt -flto=auto -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.3 -I/usr/include -I/usr/include -I/usr/include -DNCURSES_WIDECHAR -I/usr/include -I/usr/include/p11-kit-1 -I/usr/include -I/usr/include -fsanitize=undefined -fno-omit-frame-pointer -fno-common -g -O0

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme 
  -gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster 
  +nls +notmuch -openssl +pgp +regex +sasl +smime +sqlite +truecolor 

Devel options:
  ubsan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

* Operating System and its version Arch Linux (6.8.7-arch1-1)
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? tmux (3.4)
* Is your email local (maildir) or remote (IMAP)? local

**Comment by flatcap** [comment]
Thanks for the bug report.
Just in the nick of time!
I was going to make a new release in the morning.

Please can you give branch [[devel/newline]](https://github.com/neomutt/neomutt/tree/devel/newline) a try (#4272).

Thanks

**Comment by jkorb** [comment]
> Thanks for the bug report. Just in the nick of time! I was going to make a new release in the morning.
> 
> Please can you give branch [[devel/newline]](https://github.com/neomutt/neomutt/tree/devel/newline) a try (#4272).
> 
> Thanks

Wow that was quick. Thanks so much, @flatcap ! I can confirm that the problem is solved on  [[devel/newline]](https://github.com/neomutt/neomutt/tree/devel/newline).
