### ISSUE TITLE
Do we need to handle <stddef.h> specially?

### ISSUE THREAD

**Issue by alejandro-colomar** [neomutt/neomutt#4284]
https://github.com/neomutt/neomutt/blob/585158a5542cbe4c81d1ce43d0eec142bc76b9c8/.clang-format#L16

- Link: <https://github.com/neomutt/neomutt/issues/525>

The commit <https://github.com/neomutt/neomutt/commit/ac6ef83f322960e83251f04fddf65322b627919c> claims to workaround a bug in `sasl.h`, which supposedly is missing an `#include <stddef.h>` for `size_t`.

However, I can see the include in my system:

```sh
alx@debian:~$ apt-file search sasl/sasl.h
libsasl2-dev: /usr/include/sasl/sasl.h    
alx@debian:~$ grep stddef /usr/include/sasl/sasl.h
#include <stddef.h>  /* For size_t */
```

And the include has been there since 2012, according to a git-blame(1) on the source repository:

```sh
alx@debian:/tmp/cyrus-sasl$ find | grep /sasl.h
./include/sasl.h
alx@debian:/tmp/cyrus-sasl$ git blame ./include/sasl.h | grep stddef
67a188693 (Ken Murchison           2012-12-20 18:14:50 -0500  124) #include <stddef.h>  /* For size_t */
```

```diff
$ git show 67a188693
commit 67a188693796a14e3a76ac603104807fbbfddfc4
Author: Ken Murchison <murch@andrew.cmu.edu>
Date:   Thu Dec 20 18:14:50 2012 -0500

    sasl.h: #include <stddef.h> for size_t on NetBSD

diff --git a/include/sasl.h b/include/sasl.h
index fef4d510..8b8a63fb 100755
--- a/include/sasl.h
+++ b/include/sasl.h
@@ -121,6 +121,8 @@
 #ifndef SASL_H
 #define SASL_H 1
 
+#include <stddef.h>  /* For size_t */
+
 /* Keep in sync with win32/common.mak */
 #define SASL_VERSION_MAJOR 2
 #define SASL_VERSION_MINOR 1
```

Are you sure we need commit <https://github.com/neomutt/neomutt/commit/ac6ef83f322960e83251f04fddf65322b627919c> special-casing stddef.h?

And if we do, are you sure it's sasl's fault?

**Comment by flatcap** [comment]
Dunno.  Probably not.

Try:
- Removing the rule from `.clang-format`
- Running `clang-format` **everything**
- Thoroughly test the build

If you push to a branch `[devel/XYZ]` most of the GitHub Actions will get run.
e.g. **Build and Test**, **ASAN**

There are a couple of other manual builds you'll need to check too:

- **FreeBSD** (CirrusCI)
  Edit the file `.cirrus.yml` and delete lines 5,6 (`only_if...`, `skip...`)
  (that'll force it to trigger on push)
- **MacOS**
  1. Go to the Actions Tab
  2. Click "Show more workflows"
  3. Select macOS
  4. Click "Run workflow" (right-hand-side)
  5. Select your branch

If all the Actions succeed, then the change is probably good enough.
