### ISSUE TITLE
Host certificate file does not work

### ISSUE THREAD

**Issue by pete3215** [neomutt/neomutt#429]
Hi,

I have been using mutt for a while now and included a setting that included the mailserver certificate instead of using the CA model. Details can be found here https://gist.github.com/bnagy/8914f712f689cc01c267#tofu

Basically this works by manually accepting and saving the cert the first time you use this setting. You can also reject the CA cert and only accept and save the host certificate directly. 

This has worked fine with the normal mutt but after I switched to neomutt this stopped working.

Now I get a warning, showing the CA certificate of my provider and asking to accept it. If I reject I do not get asked if I want to accept the host certificate instead but an error is shown:

> SSL failed: error:0906D06C:PEM routines:PEM_read_bio:no start line

The correct host cert is in the specified file, but it seems neomutt only accepts the CA certificate. Is there a way to get this to work the way I want it? Is this a bug? Or is ther another way to do this in neomutt?

I use arch linux with the following config:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=neomutt

**Comment by pete3215** [comment]
This issue also affects mutt since version 1.8
https://dev.mutt.org/trac/ticket/3916#ticket

**Comment by gahr** [comment]
That's what I suspected. There've been some changes in handling certificates, [3ba3210] comes to mind.

**Comment by gahr** [comment]
I'll look into this

**Comment by gahr** [comment]
I confirm that your use case stopped working with 541c486.

**Comment by pete3215** [comment]
Thanks for looking into this. Let me know if I can help with testing any patches.

**Comment by gahr** [comment]
I'll track this, but let's see how the discussion on https://dev.mutt.org/trac/ticket/3916 evolves.

**Comment by gahr** [comment]
@pete3215 Hi, I just imported the two patches suggested upstream. I don't mean to merge them as-is - I just want to be up-to-date on this. I'd be grateful if you could give it a go! Thanks a lot!

**Comment by pete3215** [comment]
Works in neomutt as expected.
I guess upstream still wants to get some changes in though.

**Comment by gahr** [comment]
Yes, I'm following the discussion as well :)
