### ISSUE TITLE
Doubts about paranoic defensive programming style

### ISSUE THREAD

**Issue by alejandro-colomar** [neomutt/neomutt#4293]
Regarding code like

<https://github.com/neomutt/neomutt/blob/371a8ade3422fca138044ff4a9ce3bea127d843d/mutt/memory.c#L115-L118>

If that conditions happens to be true, we're in Big trouble.  That's a programmer error somewhere; not just a run-time error.

Returning as if nothing happened is of dubious value.  If we want to be truly paranoic, we should probably abort/exit right now, as we do if realloc(3) has a run-time error a few lines below that.

<https://github.com/neomutt/neomutt/blob/371a8ade3422fca138044ff4a9ce3bea127d843d/mutt/memory.c#L132-L137>

If the program continues running as if nothing happened, what can we expect from the calling code?  It already passed an invalid value that should never happen; will it be able to handle it well?

I'm of the opinion that either not coding for programmer errors, or at most coding an abort, is the right thing to do.  But coding aborts/exits all around would be a lot of churn and I'm not sure.

Do you have any opinions?  If it were my code, I would just nuke it all.  :-)

**Comment by flatcap** [comment]
It's a tricky situation...

Ultimately, I'm running a project with few users.
If something doesn't quite work right, or outright fails, a user _might_ raise an issue.
If NeoMutt crashes, or an assertion fails, the user is more likely to abandon NeoMutt altogether.

This makes me lean towards defensive programming.

Yes, `realloc()` and friends are a mess, but there are some things we could still do...

- Perhaps we could flag functions with `__attribute__((nonnull))` (as a stepping stone)
  I think Coverity can leverage this sort of thing.

- There may still be a few custom list implementations that should use `TAILQ`

- There are LOTS of arrays that would be safer using `ARRAY` (gahr's baby).
  Reduce the amount of memory handling to a few "safe" places.
 
---

\[Aside\] - If you want to see a real mess, look at the file-opening code.

**Comment by alejandro-colomar** [comment]
> It's a tricky situation...
> 
> Ultimately, I'm running a project with few users. If something doesn't quite work right, or outright fails, a user _might_ raise an issue. If NeoMutt crashes, or an assertion fails, the user is more likely to abandon NeoMutt altogether.
> 
> This makes me lean towards defensive programming.

Hmmm, I understand.

> Yes, `realloc()` and friends are a mess, but there are some things we could still do...

Well, as long as it works, since it's supposedly dead code, I guess we can keep it dead around; I don't mind too much.

>     * Perhaps we could flag functions with `__attribute__((nonnull))` (as a stepping stone)
>       I think Coverity can leverage this sort of thing.

I'm poking the LLVM people to improve their _Nullable qualifier, which I think is better than [[gnu::nonnull]].  However, it's still not in a usable state.  Let's see if we can use that in a few years from now.

> 
>     * There may still be a few custom list implementations that should use `TAILQ`
> 
>     * There are LOTS of arrays that would be safer using `ARRAY` (gahr's baby).
>       Reduce the amount of memory handling to a few "safe" places.
> 
> 
> [Aside] - If you want to see a real mess, look at the file-opening code.

:-)

Thanks!
