### ISSUE TITLE
C dialect

### ISSUE THREAD

**Issue by alejandro-colomar** [neomutt/neomutt#4295]
Hi!

I'm preparing some patches for which I need some "interesting" C features, and I'd like to know what dialect I should choose.  Either GNU C, or ISO C11 would work for me.  Do you have any preferences?  I would go for ISO C11.

That is, I need to chose between _Generic(3) and GNU magic builtins, and I prefer _Generic(3).

Any opinions?

**Comment by flatcap** [comment]
Yes, I'd prefer C11, too.
If there are any platforms that can't manage a decade-old standard, then tough :-)

Likewise, we should probably _specify_ [POSIX:2008](https://pubs.opengroup.org/onlinepubs/9699919799/) too.
(we already use a few bits from this)

**Comment by alejandro-colomar** [comment]
Great!  Thanks for confirming.  :-)
