### ISSUE TITLE
Compressed Folder Patch

### ISSUE THREAD

**Issue by riesebie** [neomutt/neomutt#43]
Running release 20160530 with +USE_COMPRESSED. If i source the contributed muttrc.compress I get:

Error in /home/users/riesebie/.neomutt/muttrc.compress, line 14: badly formatted command string
The same for every hook.

If I source the same file with i.e. Debian's mutt-patched I can open compressed folders well.

**Comment by flatcap** [comment]
That probably means one of %f of %t is missing.
Can you show me the line?

**Comment by riesebie** [comment]
open-hook   '\.gz$'  "gzip -cd  '%f' >  '%t'"

**Comment by flatcap** [comment]
OK, found it.  My fault, obviously :-)
Sorry about that.

**Comment by riesebie** [comment]
* Richard Russon <notifications@github.com> [2016-06-06 10:18 -0700]:

> OK, found it.  My fault, obviously :-)
> Sorry about that.

Would be nice to know where the rub is ;-)

-- 
  We all know Linux is great... it does infinite loops in 5 seconds.
        -Linus Torvalds

**Comment by flatcap** [comment]
I've got some ongoing development on the compress patch.  As my changes weren't ready, I reverted them and released what I thought was a stable version.  Stupid, stupid, stupid!

I was converting some functions that returned 0 and -1 to booleans.  I'll commit the fix shortly.

```diff
diff --git c/compress.c w/compress.c
index 641bf1f..b486755 100644
--- c/compress.c
+++ w/compress.c
@@ -466,7 +466,7 @@ comp_valid_command (const char *cmd)
        if (!cmd)
                return 0;
 
-     return (strstr (cmd, "%f") && strstr (cmd, "%t")) ? 0 : -1;
+   return (strstr (cmd, "%f") && strstr (cmd, "%t")) ? 1 : 0;
 }
 
 /**
```

**Comment by riesebie** [comment]
That patch fixes this issue ;-)

Thanks
