### ISSUE TITLE
Pressing return doesn't view text/html attachment with mailcap

### ISSUE THREAD

**Issue by adrianVmariano** [neomutt/neomutt#430]
My distro switched me from mutt to neomutt and I immediately noticed that I could no longer view html attachments using my mailcap rule.   (If I select a message, hit "v" and then hit "enter" the HTML is simply shown in text.)  I finally dug into this issue and I noticed that the help text for <Enter> says "view-attach" and describes this as "view attachment using mail cap entry if necessary".  I observe another command, "m" which is bound to "view-mailcap" which says "force viewing of attachment using mailcap".   

So I don't understand if this is a bug or if things are working as intended, but when I press return, I just see the text of the HTML, which is mostly useless.   Is use of mailcap deemed "not necessary" in this case because the attachment has a "text" type?  

Pressing "m" invokes my mailcap rule and displays the HTML as desired.

**Comment by guyzmo** [comment]
Hello @adrianVmariano and thank you for reporting your issue,

could you please give some more details on your issue?

* what is your distro?
* what version of neomutt are you running (`mutt -v`)?
* could you attach the output of `mutt -DS` to show your configuration?
* can you provide the mailcap lines that used to work and no longer are?
* and can you tell exactly what behaviour you're expecting vs the behaviour you're having?

**Comment by adrianVmariano** [comment]
First of all, the mailcap lines still work fine when mutt actually uses them.  It's just that mutt is deciding not to use them.  

This is the relevant line from /etc/mailcap:

text/html; /usr/bin/sensible-browser %s; description=HTML Text; nametemplate=%s.html

At risk of repeating what I already wrote above:  I look at my summary list of messages which shows the subject lines.  I select a message by hitting return.   I hit "v" and see a list of the message parts.  I use the arrow key to move the selection to the part that says "text/html" and hit return.  

At this point what I *expect* (and what used to happen) is that the mailcap rule is used to pass the HTML part of the message to my browser.  What *actually* happens is the HTML content is displayed in mutt's internal pager.  

The reason I know that mailcap is working is that if instead of hitting return I type "m" then the HTML content is passed to the browser as desired.   So it would appear that the "view-attach" command is for some reason deciding that it should not use mailcap for text/html attachments.  

Distro: ubuntu 16.10

Output from mutt -v:

Mutt 1.6.2-neo (2016-08-21)
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.

System: Linux 4.8.0-39-generic (x86_64)
libidn: 1.33 (compiled with 1.33)
hcache backend: tokyocabinet 1.4.48

Compiler:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.2.0-1ubuntu12' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.2.0 20160824 (Ubuntu 6.2.0-1ubuntu12) 

Configure options: '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=\${prefix}/include' '--mandir=\${prefix}/share/man' '--infodir=\${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=\${prefix}/lib/x86_64-linux-gnu' '--libexecdir=\${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-mailpath=/var/mail' '--enable-compressed' '--enable-debug' '--enable-fcntl' '--enable-hcache' '--enable-gpgme' '--enable-imap' '--enable-smtp' '--enable-pop' '--enable-sidebar' '--enable-nntp' '--enable-notmuch' '--disable-fmemopen' '--with-curses' '--with-gnutls' '--with-gss' '--with-idn' '--with-mixmaster' '--with-sasl' '--without-gdbm' '--without-bdb' '--without-qdbm' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/mutt-yAqLvu/mutt-1.6.2=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2'

Compilation CFLAGS: -Wall -pedantic -Wno-long-long -g -O2 -fdebug-prefix-map=/build/mutt-yAqLvu/mutt-1.6.2=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security

Compile options:
+CRYPT_BACKEND_CLASSIC_PGP +CRYPT_BACKEND_CLASSIC_SMIME +CRYPT_BACKEND_GPGME 
+DEBUG +DL_STANDALONE +ENABLE_NLS -EXACT_ADDRESS -HOMESPOOL -LOCALES_HACK 
-SUN_ATTACHMENT +HAVE_BKGDSET +HAVE_COLOR +HAVE_CURS_SET +HAVE_GETADDRINFO 
+HAVE_GETSID +HAVE_ICONV +HAVE_LANGINFO_CODESET +HAVE_LANGINFO_YESEXPR 
+HAVE_LIBIDN +HAVE_META +HAVE_REGCOMP +HAVE_RESIZETERM +HAVE_START_COLOR 
+HAVE_TYPEAHEAD +HAVE_WC_FUNCS +ICONV_NONTRANS +USE_COMPRESSED +USE_DOTLOCK 
+USE_FCNTL -USE_FLOCK -USE_FMEMOPEN -USE_GNU_REGEX +USE_GSS +USE_HCACHE 
+USE_IMAP +USE_NOTMUCH +USE_NNTP +USE_POP +USE_SASL +USE_SETGID +USE_SIDEBAR 
+USE_SMTP +USE_SSL_GNUTLS -USE_SSL_OPENSSL 
-DOMAIN
MIXMASTER="mixmaster"
-ISPELL
SENDMAIL="/usr/sbin/sendmail"
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/mutt"
SYSCONFDIR="/etc"
EXECSHELL="/bin/sh"

patch-compress-neo-git
patch-cond-date-neo-git
patch-fmemopen-neo-git
patch-ifdef-neo-git
patch-index-color-neo-git
patch-initials-neo-git
patch-keywords-neo-git
patch-limit-current-thread-neo-git
patch-lmdb-neo-git
patch-multiple-fcc-neo-git
patch-nested-if-neo-git
patch-new-mail-neo-git
patch-nntp-neo-git
patch-progress-neo-git
patch-quasi-delete-neo-git
patch-sidebar-neo-git
patch-skip-quoted-neo-git
patch-smime-encrypt-to-self-neo-git
patch-status-color-neo-git
patch-timeout-neo-git
patch-tls-sni-neo-git
patch-trash-neo-git
patch-sensible-browser-neo-UNKNOWN

To learn more about NeoMutt, visit: http://www.neomutt.org/
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or contact the lead developer: Richard Russon <rich@flatcap.org>

Output from mutt -D (my version does not accept -S):

abort_nosubject=ask-yes
abort_unmodified=yes
alias_file="~/.muttrc"
alias_format="%4n %2f %t %-10a   %r"
allow_8bit is set
allow_ansi is unset
arrow_cursor is unset
ascii_chars is unset
askbcc is unset
askcc is unset
ask_follow_up is unset
ask_x_comment_to is unset
assumed_charset=""
attach_charset=""
attach_format="%u%D%I %t%4n %T%.40d%> [%.7m/%.10M, %.6e%?C?, %C?, %s] "
attach_sep="\n"
attach_split is set
attribution="On %d, %n wrote:"
auto_tag is unset
autoedit is unset
beep is set
new_mail_command=""
beep_new is unset
bounce=ask-yes
bounce_delivered is unset
braille_friendly is unset
catchup_newsgroup=ask-yes
certificate_file="~/.mutt_certificates"
charset="utf-8"
check_mbox_size is unset
check_new is set
collapse_unread is set
compose_format="-- Mutt: Compose  [Approx. msg size: %l   Atts: %a]%>-"
config_charset=""
confirmappend is set
confirmcreate is set
connect_timeout=30
content_type="text/plain"
copy=yes
crypt_autoencrypt is unset
crypt_autopgp is set
crypt_autosign is unset
crypt_autosmime is set
crypt_confirmhook is set
crypt_opportunistic_encrypt is unset
crypt_replyencrypt is set
crypt_replysign is unset
crypt_replysignencrypted is unset
crypt_timestamp is set
crypt_use_gpgme is unset
crypt_use_pka is unset
crypt_verify_sig=yes
date_format="!%a, %b %d, %Y at %I:%M:%S%p %Z"
default_hook="~f %s !~P | (~P ~C %s)"
delete=yes
delete_untag is set
digest_collapse is set
display_filter=""
dotlock_program="/usr/bin/mutt_dotlock"
dsn_notify=""
dsn_return=""
duplicate_threads is set
edit_headers is unset
editor="startemacs"
encode_from is unset
envelope_from_address=""
escape="~"
fast_reply is unset
fcc_attach=yes
fcc_clear is unset
folder="~/letters"
folder_format="%2C %t %N %F %2l %-8.8u %-8.8g %8s %d %f"
followup_to is set
followup_to_poster=ask-yes
force_name is unset
forward_decode is set
forward_decrypt is set
forward_edit=yes
forward_format="[%a: %s]"
forward_quote is unset
from="Adrian Mariano <radian@cox.net>"
gecos_mask="^[^,]*"
group_index_format="%4C %M%N %5s  %-45.45f %d"
hdrs is set
header is unset
header_cache=""
header_cache_compress is set
help is set
hidden_host is unset
hide_limited is unset
hide_missing is set
hide_thread_subject is set
hide_top_limited is unset
hide_top_missing is set
history=10
history_file="~/.mutthistory"
honor_disposition is unset
honor_followup_to=yes
hostname="alpaca"
idn_decode is set
idn_encode is set
ignore_linear_white_space is unset
ignore_list_reply_to is unset
imap_authenticators=""
imap_check_subscribed is unset
imap_delim_chars="/."
imap_headers=""
imap_idle is unset
imap_keepalive=300
imap_list_subscribed is unset
imap_login=""
imap_pass=""
imap_passive is set
imap_peek is set
imap_pipeline_depth=15
imap_servernoise is set
imap_user=""
implicit_autoview is unset
include=ask-yes
include_onlyfirst is unset
indent_string="> "
index_format="%4C %Z %{%b %d} %-15.15L (%?l?%4l&%4c?) %s"
inews=""
ispell="ispell"
keep_flagged is unset
keywords_legacy is set
keywords_standard is unset
locale="C"
mail_check=5
mail_check_recent is set
mail_check_stats is unset
mail_check_stats_interval=60
mailcap_path="~/.mailcap:/usr/share/mutt/mailcap:/etc/mailcap:/etc/mailcap:/usr/etc/mailcap:/usr/local/etc/mailcap"
mailcap_sanitize is set
maildir_header_cache_verify is set
maildir_trash is unset
maildir_check_cur is unset
mark_old is set
markers is set
mask="!^\\.[^.]"
mbox="~/mbox"
mbox_type=mbox
menu_context=0
menu_move_off is set
menu_scroll is unset
message_cache_clean is unset
message_cachedir=""
message_format="%s"
meta_key is unset
metoo is unset
mh_purge is unset
mh_seq_flagged="flagged"
mh_seq_replied="replied"
mh_seq_unseen="unseen"
mime_forward=no
mime_forward_decode is unset
mime_forward_rest=yes
mime_subject is set
mix_entry_format="%4n %c %-16s %a"
mixmaster="mixmaster-filter"
move=no
narrow_tree is unset
net_inc=10
news_cache_dir="~/.mutt"
news_server=""
newsgroups_charset="utf-8"
newsrc="~/.newsrc"
nntp_authenticators=""
nntp_context=1000
nntp_listgroup is set
nntp_load_description is set
nntp_user=""
nntp_pass=""
nntp_poll=60
nm_open_timeout=5
nm_default_uri=""
nm_hidden_tags="unread,draft,flagged,passed,replied,attachment,signed,encrypted"
nm_exclude_tags=""
nm_unread_tag="unread"
nm_db_limit=0
nm_query_type="messages"
nm_record is unset
nm_record_tags=""
pager="builtin"
pager_context=0
pager_format="-%Z- %C/%m: %-20.20n   %s%*  -- (%P)"
pager_index_lines=0
pager_stop is unset
pgp_auto_decode is unset
pgp_autoinline is unset
pgp_check_exit is set
pgp_clearsign_command="gpg --no-verbose --batch --quiet --output - %?p?--passphrase-fd 0? --armor --textmode --clearsign %?a?-u %a? %f"
pgp_decode_command="gpg --status-fd=2 %?p?--passphrase-fd 0? --no-verbose --quiet --batch --output - %f"
pgp_decrypt_command="gpg --status-fd=2 %?p?--passphrase-fd 0? --no-verbose --quiet --batch --output - %f"
pgp_decryption_okay="^\\[GNUPG:\\] DECRYPTION_OKAY"
pgp_encrypt_only_command="/usr/lib/mutt/pgpewrap gpg --batch --quiet --no-verbose --output - --encrypt --textmode --armor --always-trust -- -r %r -- %f"
pgp_encrypt_sign_command="/usr/lib/mutt/pgpewrap gpg %?p?--passphrase-fd 0? --batch --quiet --no-verbose --textmode --output - --encrypt --sign %?a?-u %a? --armor --always-trust -- -r %r -- %f"
pgp_entry_format="%4n %t%f %4l/0x%k %-4a %2c %u"
pgp_export_command="gpg --no-verbose --export --armor %r"
pgp_getkeys_command=""
pgp_good_sign="^\\[GNUPG:\\] GOODSIG"
pgp_ignore_subkeys is set
pgp_import_command="gpg --no-verbose --import %f"
pgp_list_pubring_command="gpg --no-verbose --batch --quiet --with-colons --with-fingerprint --with-fingerprint --list-keys %r"
pgp_list_secring_command="gpg --no-verbose --batch --quiet --with-colons --with-fingerprint --with-fingerprint --list-secret-keys %r"
pgp_long_ids is set
pgp_mime_auto=ask-yes
pgp_replyinline is unset
pgp_retainable_sigs is unset
pgp_show_unusable is set
pgp_sign_as=""
pgp_sign_command="gpg --no-verbose --batch --quiet --output - %?p?--passphrase-fd 0? --armor --detach-sign --textmode %?a?-u %a? %f"
pgp_sort_keys=address
pgp_strict_enc is set
pgp_timeout=300
pgp_use_gpg_agent is unset
pgp_verify_command="gpg --status-fd=2 --no-verbose --quiet --batch --output - --verify %s %f"
pgp_verify_key_command="gpg --verbose --batch --fingerprint --check-sigs %r"
pipe_decode is unset
pipe_sep="\n"
pipe_split is unset
pop_auth_try_all is set
pop_authenticators=""
pop_checkinterval=60
pop_delete=ask-no
pop_host=""
pop_last is unset
pop_pass=""
pop_reconnect=ask-yes
pop_user=""
post_indent_string=""
post_moderated=ask-yes
postpone=ask-yes
postponed="=postponed"
postpone_encrypt is unset
postpone_encrypt_as=""
preconnect=""
print=ask-no
print_command="enscript -G -fDejaVuSansMono10"
print_decode is set
print_split is unset
prompt_after is set
query_command=""
query_format="%4c %t %-25.25a %-25.25n %?e?(%e)?"
quit=yes
quote_regexp="^([ \t]*[|>:}#])+"
read_inc=10
read_only is unset
realname="Adrian Mariano"
recall=ask-yes
record="=log"
reflow_space_quotes is set
reflow_text is set
reflow_wrap=78
reply_regexp="^(re([\\[0-9\\]+])*|aw):[ \t]*"
reply_self is unset
reply_to=ask-yes
resolve is set
resume_draft_files is unset
resume_edited_draft_files is set
reverse_alias is unset
reverse_name is unset
reverse_realname is set
rfc2047_parameters is unset
save_address is unset
save_empty is set
save_history=0
save_name is unset
score is set
score_threshold_delete=-1
score_threshold_flag=9999
score_threshold_read=-1
search_context=0
send_charset="us-ascii:iso-8859-1:utf-8"
sendmail="/usr/sbin/sendmail -oem -oi"
sendmail_wait=0
shell="/usr/bin/zsh"
save_unsubscribed is unset
show_new_news is set
show_only_unread is unset
sidebar_divider_char="|"
sidebar_delim_chars="/."
sidebar_folder_indent is unset
sidebar_format="%B%*  %n"
sidebar_indent_string="  "
sidebar_new_mail_only is unset
sidebar_next_new_wrap is unset
sidebar_short_path is unset
sidebar_sort_method=mailbox-order
sidebar_visible is unset
sidebar_width=0
sig_dashes is set
sig_on_top is unset
signature="~/.signature"
simple_search="~f %s | ~s %s"
skip_quoted_offset=0
sleep_time=1
smart_wrap is set
smileys="(>From )|(:[-^]?[][)(><}{|/DP])"
smime_ask_cert_label is set
smime_ca_location="/etc/ssl/certs/ca-certificates.crt"
smime_certificates="~/.smime/certificates"
smime_decrypt_command="openssl smime -decrypt -passin stdin -inform DER -in %f -inkey %k -recip %c"
smime_decrypt_use_default_key is set
smime_default_key=""
smime_encrypt_command="openssl smime -encrypt -%a -outform DER -in %f %c"
smime_encrypt_self=no
smime_encrypt_with="aes256"
smime_get_cert_command="openssl pkcs7 -print_certs -in %f"
smime_get_cert_email_command="openssl x509 -in %f -noout -email"
smime_get_signer_cert_command="openssl smime -verify -in %f -noverify -signer %c -out /dev/null"
smime_import_cert_command="smime_keys add_cert %f"
smime_is_default is unset
smime_keys="~/.smime/keys"
smime_pk7out_command="openssl smime -verify -in %f -noverify -pk7out"
smime_sign_command="openssl smime -sign -md %d -signer %c -inkey %k -passin stdin -in %f -certfile %i -outform DER"
smime_sign_digest_alg="sha256"
smime_sign_opaque_command=""
smime_timeout=300
smime_verify_command="openssl smime -verify -inform DER -in %s %C -content %f"
smime_verify_opaque_command="openssl smime -verify -inform DER -in %s %C || openssl smime -verify -inform DER -in %s -noverify 2>/dev/null"
smtp_authenticators=""
smtp_pass=""
smtp_url=""
sort=mailbox-order
sort_alias=alias
sort_aux=date
sort_browser=alpha
sort_re is set
spam_separator=","
spoolfile="/var/mail/adrian"
ssl_ca_certificates_file="/etc/ssl/certs/ca-certificates.crt"
ssl_client_cert=""
ssl_force_tls is unset
ssl_min_dh_prime_bits=0
ssl_starttls=yes
ssl_use_sslv3 is unset
ssl_use_tlsv1 is set
ssl_use_tlsv1_1 is set
ssl_use_tlsv1_2 is set
ssl_verify_dates is set
ssl_verify_host is set
ssl_ciphers=""
status_chars="-*%A"
status_format="-%r-Mutt: %f [Msgs:%?M?%M/?%m%?n? New:%n?%?o? Old:%o?%?d? Del:%d?%?F? Flag:%F?%?t? Tag:%t?%?p? Post:%p?%?b? Inc:%b?%?l? %l?]---(%s/%S)-%>-(%P)---"
status_on_top is unset
strict_threads is unset
suspend is set
text_flowed is unset
thorough_search is set
thread_received is unset
tilde is unset
time_inc=250
timeout=600
tmpdir="/tmp"
to_chars="? ++FL"
ts_icon_format="M%?n?AIL&ail?"
ts_enabled is set
ts_status_format="adrian's mail (mutt)"
trash=""
tunnel=""
uncollapse_jump is unset
use_8bitmime is unset
use_domain is set
use_envelope_from is set
use_from is set
use_ipv6 is set
user_agent is set
visual="/usr/bin/emacs"
vfolder_format=" %6n(%6N) %f "
virtual_spoolfile is unset
wait_key is set
weed is set
wrap=0
wrap_headers=78
wrap_search is set
wrapmargin=0
write_bcc is set
write_inc=10
xlabel_delimiter=""
x_comment_to is unset

**Comment by sileht** [comment]
I have reproduce it with 'implicit_autoview unset' and 'no auto_view' configured.

debian/ubuntu package was having debian/patches/upstream/611410-no-implicit_autoview-for-text-html.patch applied. But according https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816706 it have been removed since package 1.6.0-1

Mutt upstream have closed their related bug (https://dev.mutt.org/trac/ticket/3496) but don't really fix the issue. They talks about mutt_is_autoview(), while the bug is in mutt_needs_mailcap().

mutt_needs_mailcap() always return 0 for text/* minetypes, so if no autoview are configured the raw html is displayed. Debian workaround was to use 'text/* except text/html' minetypes.

A workaround is to set "implicit_autoview=yes"  or "auto_view text/html".

So, the question is should we fix this or not ? Should we consider text/html as a human unreadable content or not ?

I'm in favour of yes, because reading raw text/html mail is not my cup of tea :)

**Comment by guyzmo** [comment]
@sileht I agree with your position, and thank you for the historic on this.
My opinion: `text/html` should only be seen like any special data format that needs an external program to be shown. If you want to see it nicely, you should setup your mailcap rule and the `auto_view text/html`. That's how I'm setup (with `lynx -dump -stdin`), and thus I never ran into that issue.

Though I think the debian patch isn't great. The same way, I don't need to view `text/calendar` and a bunch of others. But I'd rather read `text/markdown` as is. So maybe a good compromise would be to add a `mailcap_text_as_application` list with the list of `text/*` that should be considered as `application/*`. And a sane default would be `['text/html', 'text/xml', 'text/calendar']` (those are the three I've seen in my Mailbox that are just WTF… though theoretically the two others are supposed to be `application/xml` and `application/ics`).

**Comment by sileht** [comment]
debian have reintroduced the patch :) https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823971

anyways this is still good to have ithis n neomutt.

**Comment by gahr** [comment]
In my opinion, a solution where mime/types are hard-coded into the source code is a no-go. If you look at the [IANA registered](http://www.iana.org/assignments/media-types/media-types.xhtml#text) `text/*` MIME types, I don't see many of that fit the description of "auto viewable in the pager".

Perhaps we should be better off in only automatically displaying text/plain, and let everything else be handled by mailcap?

**Comment by Natureshadow** [comment]
>source code is a no-go

to be no-go (adjective)
a no-no (noun)

**Comment by gahr** [comment]
... so, make everything with a copiousoutput property be displayed through mailcap in the pager, and everything else only through the attachment browser
