### ISSUE TITLE
Doubts about some `*const` pointers

### ISSUE THREAD

**Issue by alejandro-colomar** [neomutt/neomutt#4301]
https://github.com/neomutt/neomutt/blob/20fe7bdc2cedb156cf1b6f8bf1aa8dce8eeb2968/email/envelope.h#L70-L71

What's the use of these `*const`s if you have to cast them away all the time?

@nabijaczleweli

**Comment by flatcap** [comment]
The idea of b5640bbe65491010211807956b8458ae8542b89e was to ensure that the `subject` and `real_subj` are kept in sync.
The `const` is a hint to call `mutt_env_set_subject()` rather than altering them directly.

**Comment by nabijaczleweli** [comment]
FTR the fields are const, not the pointers

**Comment by alejandro-colomar** [comment]
> FTR the fields are const, not the pointers;

I'm not sure what you mean by this.  `char *const p` means "p is a constant pointer to char", so the pointer _is_ const.

Maybe you meant the the pointees aren't const, which I agree.

> don't cast the const away, use the setter

Except that I count 10 casts outside of the setter.  I'm not sure if something that requires adding 10 casts (+ the ones in the setter) is an improvement.  Casts are the thing that hides most bugs by far, since they disable almost all compiler warnings.

**Comment by nabijaczleweli** [comment]
as far as i can tell, there's const-casts on both in the setter, merger, and deserialiser, all three of which are Envelope's member functions (or, as close as they can be), and entirely within the scope of the functions that should bypass the const.

there's an outlier in `rfc2047_{de,de}code_envelope(struct Envelope *env)`, which juggles `subject` to conform to unfortunate memory management requirements and then calls the setter. also a member (or, sure, friend), also fine.

this reads to me as being perfectly as-designed (only Envelope members (and friends) are allowed to edit these directly) and as-desired (the shit works so everyone else is forced to use the setters so IMAP works)
not sure where you're getting "cast away all the time" here, they're removed in 3.5 functions that edit them and everyone else uses them as-listed, and is forced to use the setters

**Comment by alejandro-colomar** [comment]
> as far as i can tell, there's const-casts on both in the setter, merger, and deserialiser, all three of which are Envelope's member functions (or, as close as they can be), and entirely within the scope of the functions that should bypass the const.
> 
> there's an outlier in `rfc2047_{de,de}code_envelope(struct Envelope *env)`, which juggles `subject` to conform to unfortunate memory management requirements and then calls the setter. also a member (or, sure, friend), also fine.

Hmmm, okay.

> 
> not sure where you're getting "cast away all the time" here,

Just a way of speaking.

It's not _all_ the time, but a non-trivial amount: 7/52

```c
$ grep -rn 'real_subj\>' | pee 'wc -l > /dev/tty' 'cat' | grep '(char' | wc -l
52
7
````

> this reads to me as being perfectly as-designed (only Envelope members (and friends) are allowed to edit these directly) and as-desired

Yup; just that the design implies some slightly dangerous stuff, IMHO.

But I guess since it's your design, you it's your prerogative.

> (the shit works so everyone else is forced to use the setters so IMAP works)

I would have probably just not forced anything, and just document that the setters should be used.  But I know that you prefer C++, so I guess, it's all right.  At least now I understand why it's `*const` + casts.

And FTR, I would just remove IMAP from neomutt(1), but that' not going to happen.  It would certainly simplify it a lot.  :)
