### ISSUE TITLE
Is it possible to edit the automatic title when forwarding or replying a message?

### ISSUE THREAD

**Issue by lamons** [neomutt/neomutt#4314]
I noticed that when forwarding messages with NeoMutt, it uses a title like "[original title]" instead of the more common "Fwd: original title". Is it possible to change this behavior?

**Comment by mschilli87** [comment]
Just change the `forward_format` config option (default: `[%a: %s]`) in your `.neomuttcr`:

```
set forward_format="Fwd: %s"
```
