### ISSUE TITLE
autocrypt breaks command line argument `-e "push foo"`

### ISSUE THREAD

**Issue by immae** [neomutt/neomutt#4316]
## Expected Behaviour

I’m trying to run `neomutt -e "push foo"` (example). I expect to have  that in the status bar:

![2024-05-27_15_34_04](https://github.com/neomutt/neomutt/assets/510202/c8673af8-08b4-4605-a50e-7fe900eaf331)

which corresponds to the "f" key and oo typed.

## Actual Behaviour

Nothing happens, and the "push foo" is completely ignored

## Steps to Reproduce

The config `set autocrypt = yes` is the one line that needs to be enabled in the neomutt config to reproduce the issue

## How often does this happen?

- Always

## When did it start to happen?

When I upgraded: the issue appeared somewhere between 20230517 and 20231103. I’m still working on trying to figure out the exact release / commit

## Extra Info

* Operating System and its version: NixOS
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? yes (tmux)
* Is your email local (maildir) or remote (IMAP)? IMAP

**Comment by immae** [comment]
gi-bissected on the code with that:
```
git clean -fxd
./configure --enable-autocrypt --gpgme --gss --lmdb --notmuch --ssl --sasl --with-homespool=mailbox --with-mailpath= --disable-include-path-in-cflags --zlib
make
./neomutt -F my-config-file-with-autocrypt -e "push foo"
```

and looking at the status bar. The offending commit is 3cd93da8cc76a536f83fd9cfc2173c0d7842881b

Here is the minimal my-config-file-with-autocrypt file I’m able to provide so far:
```
set spoolfile="imaps://immae@example.com/"
set folder="imaps://immae@example.com/"
set imap_pass=`pass show IMAP`
            
set autocrypt = yes
set autocrypt_dir = $XDG_DATA_HOME/neomutt/autocrypt
```
commenting the autocrypt line works fine. Uncommenting it fails.

**Comment by immae** [comment]
Checked with only `./configure --enable-autocrypt` and local spooldfile / folder (no more imap), same issue, same commit

**Comment by roccoblues** [comment]
Thanks for the detailed bug report!

I think I understand what is happening:
autocrypt initialization can ask for user response ("/tmp/foo does not exist. Create it?"). To not use the provided command (`-e "push foo"`) as input for the question the old code set/unset the global `OptIgnoreMacroEvents`. This is necessary because it all uses the same input buffer. The new code uses `mutt_flushinp()` to just flush the input buffer. Effectively removing the passed command.

We might be able to just pass `GETCH_IGNORE_MACRO` down the line during the autocrypt initialization. I'll try to play around with it.

**Comment by immae** [comment]
@roccoblues : I tried your patch and it seems to work perfectly, thank you for that :+1:

**Comment by gahr** [comment]
I'm sorry, apparently we still don't have a robust fix for this, see https://github.com/neomutt/neomutt/pull/4326#issuecomment-2212537146 and subsequent comments.

**Comment by roccoblues** [comment]
So this is the commit that introduced this: https://github.com/neomutt/neomutt/commit/3b2790cb5c808e71ed7978f54b4fbb15de77a289.

@gahr and me are currently trying to wrap our head around to understand if the assumptions are correct. The fix might be as simple as removing the flushing of the input buffer.
