### ISSUE TITLE
Cannot open an .mbox file with neomutt (although it works with mutt)

### ISSUE THREAD

**Issue by bjce** [neomutt/neomutt#4321]
First of all thank you very much for maintaining neomutt which is such a great piece of software.

Here is the problem I encountered:

I want to open a 10GB `.mbox` file that I downloaded from my gmail account. When I use the command 
```
neomutt -f 10GB_mboxfile.mbox
```
neomutt takes 10-20 seconds to open and when finally opened, there is no file listed in the the application. I have the following dummy `.mbox` (which I modified from a gmail mbox file): 

```
From 9999999999999999@xxx Tue Mar 09 17:00:00 +0500 2019  
X-GM-THRID: 99999999999999999
X-mail-Labels: Archived,Sent,Opened
MIME-Version: 1.0
Date: Tue, 09 Mar 2019 17:00:00 +0500
Message-ID: <ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ@mail.mail.com>
Subject: THETITLE
From: My Name <My_Name@mail.com>
To: destination@mail.com
Content-Type: multipart/alternative; boundary="0000000000009999999999999"

--0000000000009999999999999
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable


ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ da=
s ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ

--0000000000009999999999999
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<div>ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ=
ZZ das ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ=
>

--0000000000009999999999999--
```

I am trying to open it with neomutt as follows:
```
neomutt -f themboxfile.mbox
```
neomutt opens but then no message is listed in the app. How is it possible to open this file with neomutt? (Although opening the same file works with mutt...)

N.B. I copied the question that I posted on SO there: https://unix.stackexchange.com/questions/777971/cannot-open-an-mbox-file-with-neomutt-although-it-works-with-mutt?noredirect=1#comment1488047_777971 and I was advised there to submitt a bug report.

**Comment by gahr** [comment]
You sample mbox file works fine here:
```
   1  (0.6K)   N     [Mar  9 19 12:00] My Name                             THETITLE
```

What version of NeoMutt are you running? Does it work if you launch NeoMutt with an empty config file? Please try `neomutt -F /dev/null -f themboxfile.mbox`

**Comment by bjce** [comment]
Thank you very much for you answer

The version of neomutt (which I installed via `apt get install neomutt` on Ubuntu LTS 22.04) is the following:

```
$ neomutt --version
neomutt: invalid option -- '-'
NeoMutt 20211029
```
I tried the following:
```
$ neomutt -F /dev/null -f themboxfile.mbox
```
but there is no email in the neomutt UI. Is the version of neomutt to old?

**Comment by gahr** [comment]
Yeah it would be great if you could try on the latest release or by building from the main branch. We aren't going to be able to fix a past release anyway :)

**Comment by bjce** [comment]
Ok I uninstalled neomutt and re-installed it with nix package manager. it installed `NeoMutt 20231221` which worked without problem. Thanks a lot for your support @gahr. I also edited the stackoverflow question accordingly
