### ISSUE TITLE
when modify mail filter fetch from history will clear old filter

### ISSUE THREAD

**Issue by wanderl5** [neomutt/neomutt#4325]
when i search for emails using mail filter, i will modify filter fetch from history, but when i modify, it will always clear old ones, but i just append some filter conditions;
eg: ~f bob@tom, i want add subject conditions contain "pay bill", so i will use "up arrow" to recall filter "~f bob@tom", then i input " ~s pay bill"
in actual , old one "~f bob@tom" was cleared which is not my purpose;

## Expected Behaviour

append additional conditions

## Actual Behaviour

clear old filter

If NeoMutt crashed, did your OS create a 'coredump' file?

## Steps to Reproduce

1.filter with from: ~f bob@tom
2.use "up arrow" to  recall filter "~f bob@tom" and append conditions by input " ~s pay bill"

## How often does this happen?

- Always

## When did it start to happen?

- When I filter emails

## NeoMutt Version

```
NeoMutt 20231221
Copyright (C) 1996-2022 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.1.0-18-amd64 (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libidn2: 2.3.3 (compiled with 2.3.3)

Configure options: --disable-doc

Compilation CFLAGS: -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -DNCURSES_WIDECHAR -I/usr/include -O2

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme 
  -gsasl -gss -hcache -homespool +idn +inotify -locales_hack -lua -mixmaster 
  +nls -notmuch -openssl +pgp +regex -sasl +smime -sqlite +truecolor 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by gahr** [comment]
I can't reproduce that. Recalling a previous filter and appending to it works fine here. What do you mean exactly by 
> in actual , old one "~f bob@tom" was cleared which is not my purpose;\

What if you recall the second filter, doesn't it show `~f bob@tom  ~s pay bill`?

**Comment by wanderl5** [comment]
Sorry, maybe I didn't state it clearly enough;
when i use filter like "~f bob", it works fine, then i want add some filter such as " ~s bill"
i will recall the filter, and it will show the last filter, "~f bob" in this case, and then i input space , then "~f bob" will be cleared.

**Comment by gahr** [comment]
oh, so the act of pressing the space key after having recalled the history clears the line.

* Is this reproducible with the latest version?
* Can you please report the bindings that include `<Space>` from the `:bind` output?

**Comment by wanderl5** [comment]
yeah, currently, my bind alia:   bind  alias <Space> tag-entry
is this why it clears the filter?

**Comment by gahr** [comment]
Ah! I had an epiphany and I **now** understand what you are describing.
Please can you be very precise about the sequence of actions you take? I can reproduce what you're seeing with this:

1. press <kbd>l</kbd> to enter `limit`, then enter `~f bob`
2. press <kbd>l</kbd> to enter `limit` **again**
3. do **not** press <kbd>Up</kbd> to recall the previous `~f bob` limit, NeoMutt suggests that for you already
4. press space to add to the previous limit
5. the line is killed

This is expected. Pressing any character kills the previous filter so you  can enter a new one. If you **do** press <kbd>Up</kbd> at point 3, then you still see `~f bob` but a space doesn't kill the line.

Can you please confirm?

**Comment by wanderl5** [comment]
confirm，it's ok, thx; 
now i press `up` to avoid killing the line.
