### ISSUE TITLE
Toggle `pager_index_lines`

### ISSUE THREAD

**Issue by jdujava** [neomutt/neomutt#4333]
I find `pager_index_lines` useful, but sometimes I want to just view the message and hide the `pager_index_lines`. I've come up with the following macro:
```ini
set pager_index_lines = 10
macro pager \Cf '<enter-command>set pager_index_lines=`echo $((10 - $pager_index_lines))`<enter>' "toggle pager_index_lines"
```
While this works alright, it could be desirable to have dedicated function to toggle `pager_index_lines` (cleaner config code, easier to setup for users, ...).

**Comment by gahr** [comment]
I agree it would be nice to be able to "toggle" numeric values, i.e., switch from the current value to 0 and back. I would use that for `wrap`, too.

**Comment by gahr** [comment]
Hi @jdujava , I've implemented toggling numeric configs in the [devel/issue-4333](https://github.com/neomutt/neomutt/tree/devel/issue-4333) branch. Can you please give it a try?

**Comment by jdujava** [comment]
Can confirm that `toggle pager_index_lines` works nicely. Thanks @gahr!.
