### ISSUE TITLE
System tray

### ISSUE THREAD

**Issue by avidseeker** [neomutt/neomutt#4334]
## What would you like to be able to do?
Have a system tray icon for neomutt to be alerted of new mails. It can then be run in tmux with detach/attach.

## Have you tried any alternative methods?
* Scripts that check for email
* Tmux detach

## Additional Info
[Profanity](https://github.com/profanity-im/profanity) is another CLI tool that has tray support. Its implementation details could be useful.

**Comment by gahr** [comment]
Profanity has a tray when it's built with GTK support. NeoMutt is purely console based.

Have you looked at [`new_mail_command`](https://neomutt.org/guide/reference#3-260-%C2%A0new_mail_command)?

**Comment by avidseeker** [comment]
I think `new_mail_command` would definitely suffice If I'm using a scriptable status bar like Polybar. But for desktop environments like KDE and Gnome, they depend on system tray.

If there is a minimal GUI commandline toolkit like `zenity` that creates a script-able system tray entry, that would solve the problem.

**Comment by gahr** [comment]
What's wrong with using zenity?

**Comment by avidseeker** [comment]
I'm not sure zenity has tray support?

**Comment by gahr** [comment]
No idea - I guess I can close this?

**Comment by avidseeker** [comment]
Then I think this is a more suitable topic for discussion, if it's possible to move it there.

**Comment by gahr** [comment]
I honestly don't think there's much to discuss. NeoMutt offers you a way to invoke a shell command when there's new mail. I think we stop there. We won't support notifying the gnome / kde / whatever system tray or anything that requires X11.
