### ISSUE TITLE
Behavior with unparsable values of the "Expires" header

### ISSUE THREAD

**Issue by a3nm** [neomutt/neomutt#4344]
This issue is to report a minor problem that confused me about how neomutt seems to handle the `Expires` header.

Considering the following mbox file, which is adapted from a real email I received:

```
From test@example.com Sat Jul  6 16:20:16 2024
From: test@example.com
To: test2@example.com
Subject: 
Expires: Thursday, 02 January 2025 16:15:00 +0000
Status: O
Content-Length: 5
Lines: 1

BLAH
```

Using a neomutt built from master, this email is considered to be expired (as can be seen, e.g., with the `color index black red ~E` directive and adding another mail to the mbox file). This puzzled me because the `Expires` value is in the future.

Looking more into it, what seems to happen is that `mutt_date_parse_date` on the value of `Expires` returns -1, which indicates that the parsing failed. It appears that this is the email sender's fault: the value of `Expires` should have been an RFC-5322 datetime value (see https://www.ietf.org/archive/id/draft-billon-expires-08.html). It looks like `mutt_date_parse_date` has a fallback (with `PREX_RFC5322_DATE_LAX`) but which also doesn't manage to parse this value.

It further appears that, in `email/parse.c`, the value of `-1` which is returned when failing to parse the date is always considered to be less than `mutt_date_now()`, so messages with an unparseable `Expires` value are always considered as expired.

This is not very improvement but I would think that it's better to not consider/show messages as expired if the `Expires` field contains an unparseable date. In `email/parse.c`, I guess this would mean testing for the return value of `-1` for `mutt_date_parse_date`.

(Also, it would be better if `mutt_date_parse_date` managed to parse the incorrect date format used by this sender. It doesn't look like the current heuristics are bulletproof: trying to use the defaut format of `date -d '2 months'` on my system, namely "Fri Sep  6 21:58:57 CEST 2024", also returns `-1`. I'd understand if it's not considered feasible for neomutt to understand every possible broken date format, however.)

I hope this report is useful. Thanks in any case for developing neomutt!

**Comment by gahr** [comment]
Hi @a3nm, thanks a lot for the detailed report!

For sure interpreting a failure to parse a date as it being in the past is a bug.

As for the heuristics, do you know which mailer produced the email? I'm willing to support more formats if they are likely to happen more than once in a lifetime, so to speak :)

Also, TIL about the `expires` header :)

**Comment by gahr** [comment]
Hi @a3nm, thanks a lot for the detailed report!

For sure interpreting a failure to parse a date as it being in the past is a bug.

As for the heuristics, do you know which mailer produced the email? I'm willing to support more formats if they are likely to happen more than once in a lifetime, so to speak :)

Also, TIL about the `expires` header :)

**Comment by a3nm** [comment]
Hi, thanks for the prompt feedback!

The mail comes from the French low-cost train company Ouigo (https://www.ouigo.com/). In that email there is a header: "X-Mailer: Numberly PowerMTA 5.5". I'm not sure whether the bad value is specific to Ouigo, or if all users of this Numberly PowerMTA thing may have it.

I also didn't think that `Expires` was in common use, but there seems to be an initiative https://www.zerocarbon.email/ to encourage email senders to add the header so that email providers can avoid keeping emails around indefinitely. I don't know whether it will gain traction.

Anyways, about the date being in the past, the fix seems quite simple: in [this test](https://github.com/neomutt/neomutt/blob/accac212a1eaa80250a112425218df7cf90e5710/email/parse.c#L806) it should be checked that the value returned by `mutt_date_parse_date` is not -1.

**Comment by gahr** [comment]
Feel free to open a PR if you wish. Otherwise, I'll get to it later today or tomorrow. I'll take a look at that mailer, too. Thank you!

**Comment by a3nm** [comment]
Thanks! sorry I didn't find the time to do the actual PR. This looks great, thanks for the quick fix! :)
