### ISSUE TITLE
Current stable of  BerkeleyDB apparently not supported "ouf-of-the-box"

### ISSUE THREAD

**Issue by fekir** [neomutt/neomutt#4345]
## Expected Behaviour

Compile successfully with version 18.1.40 released in 2020

## Actual Behaviour

I get following error message

~~~
Checking for BerkeleyDB in /usr/include/...no (expecting 5.3, got 18.1)
Checking for BerkeleyDB in /usr/include/db-5-3...no
Checking for BerkeleyDB in /usr/include/db53...no
Checking for BerkeleyDB in /usr/include/db5.3...no
Checking for BerkeleyDB in /usr/include/db-5...no
Checking for BerkeleyDB in /usr/include/db5...no
Checking for BerkeleyDB in /usr/include/...no (expecting 6.2, got 18.1)
Checking for BerkeleyDB in /usr/include/db-6-2...no
Checking for BerkeleyDB in /usr/include/db62...no
Checking for BerkeleyDB in /usr/include/db6.2...no
Checking for BerkeleyDB in /usr/include/db-6...no
Checking for BerkeleyDB in /usr/include/db6...no
Checking for BerkeleyDB in /usr/include/...no (expecting 4.8, got 18.1)
Checking for BerkeleyDB in /usr/include/db-4-8...no
Checking for BerkeleyDB in /usr/include/db48...no
Checking for BerkeleyDB in /usr/include/db4.8...no
Checking for BerkeleyDB in /usr/include/db-4...no
Checking for BerkeleyDB in /usr/include/db4...no
~~~

## Steps to Reproduce

Install version 18.1 of BerkeleyDB, and configure with

> ./configure --sasl --bdb  --gss --pgp --sqlite --disable-idn --idn2 --zlib --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info

(other dependencies might be required)

## How often does this happen?

- Always

## When did it start to happen?

I guess whe my environment updated the default BerkeleyDB to version 18.1

## NeoMutt Version

> 20240425

## Extra Info

* Operating System and its version -> Windows 10, cygwin
* Were you using multiple copies of NeoMutt at once? -> no
* Were you using 'screen' or 'tmux'? -> irrelevant
* Is your email local (maildir) or remote (IMAP)? -> irrelevant

**Comment by fekir** [comment]
Root cause seems to be https://github.com/neomutt/neomutt/pull/1064

Either version 18.1 should be added to the list of version, or this verification should be optional (I guess optional would be better)

Current workaround is to specify `--with-bdb-version=18.1` during configure

**Comment by gahr** [comment]
> Current workaround is to specify `--with-bdb-version=18.1` during configure

Yep - that was made explicitly so one can select one among many installed versions. I don't consider it a workaround :)

I can add 18 to the fallback list, though. I'll do that later today or tomorrow.

**Comment by fekir** [comment]
I'm not sure if "whitelisting" all db version is the best approach 

The parameter was added if more than one version is installed, in my case there is already only one.

I believe it would be better not to enlist all versions, but granted, it is easier to add this one than to rewrite some logic

At least there are not that many db versions around

**Comment by gahr** [comment]
Finding BDB is pretty involved. It's a combination of finding [a path name and a library name](https://github.com/neomutt/neomutt/blob/accac212a1eaa80250a112425218df7cf90e5710/auto.def#L839-L840). We currently do that by brute-forcing on the list of whitelisted versions. I'm not sure if searching for any numerical combination would lead to more readable code :)

**Comment by fekir** [comment]
I thought that without  #1064 the code would compile, as it would not reject the found library, but I admit I did not test it

**Comment by gahr** [comment]
No, without #1064 it would *only* accept the pre-defined set of versions, without any way to override it. And it would pick the highest version it finds.
