### ISSUE TITLE
`<tag-thread>` + `<save-message>` skips a thread instead of going to the next one

### ISSUE THREAD

**Issue by ahmedelgabri** [neomutt/neomutt#4349]
## Expected Behaviour

I have a macro that looks like this

```
macro index,pager Y "<tag-thread><save-message>=Personal/Archive<enter>" "Archive conversation"
```

I expect that when I type <kbd>Y</kbd> I move to the next thread

## Actual Behaviour

What actually happens is that it skips a thread and goes to the one after

If I remove `<tag-thread>` it works fine

```
macro index,pager Y "<save-message>=Personal/Archive<enter>" "Archive conversation"
```

## Steps to Reproduce

- Add a macro `macro index,pager Y "<tag-thread><save-message>=Personal/Archive<enter>" "Archive conversation"`
- Open `neomutt` and type <kbd>Y</kbd>
- It should skip a thread

if it matters I have also these set (_but nothing in my config changed between versions_)

```
set use_threads = reverse
set sort = 'last-date'
set collapse_all
set uncollapse_new = no
set uncollapse_jump = yes
set thread_received = yes
```

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded from `NeoMutt 20240416` to `NeoMutt 20240425`

## NeoMutt Version

```
NeoMutt 20240425
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 23.5.0 (arm64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libiconv: 1.11
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.23.2
OpenSSL: OpenSSL 3.0.13 30 Jan 2024
libnotmuch: 5.6.0
storage: lmdb
compression: zlib, zstd

Configure options: --prefix=/nix/store/i91bmkzcfl1dc4crz8ldc4ilfgirdv1n-neomutt-20240425 --enable-autocrypt --gpgme --gss --lmdb --notmuch --ssl --sasl --with-homespool=mailbox --with-mailpath= --disable-include-path-in-cflags --zlib --zstd --lua

Compilation CFLAGS: -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/nix/store/y394a6wkxy29mj8xa1xyqib7shynvsz7-gpgme-1.23.2-dev/include -I/nix/store/bmxzcgda9qa2dska0wg6dksgwhh65yrf-libgpg-error-1.49-dev/include -I/nix/store/p637c3fmxnylp3hbp5b5crwjdl1gkdfr-cyrus-sasl-2.1.28-dev/include -I/nix/store/jcq37yid023kpdcknwpyydpd949x80fj-lua-5.2.4/include -I/nix/store/i91bmkzcfl1dc4crz8ldc4ilfgirdv1n-neomutt-20240425/include -I/nix/store/i91bmkzcfl1dc4crz8ldc4ilfgirdv1n-neomutt-20240425/include -I/nix/store/i91bmkzcfl1dc4crz8ldc4ilfgirdv1n-neomutt-20240425/include -I/nix/store/i91bmkzcfl1dc4crz8ldc4ilfgirdv1n-neomutt-20240425/include -DNCURSES_WIDECHAR -I/nix/store/i91bmkzcfl1dc4crz8ldc4ilfgirdv1n-neomutt-20240425/include -I/nix/store/i91bmkzcfl1dc4crz8ldc4ilfgirdv1n-neomutt-20240425/include -I/nix/store/r9dm9dhafnipff77yl4bv1ncjgh4afsi-openssl-3.0.13-dev/include -I/nix/store/3cvd65asw8l9j12qmnzsr95ngpp20hq8-libidn2-2.3.7-dev/include -I/nix/store/bm4l5lgnp3pa2z6xxbmackvymcz8gw36-lmdb-0.9.33-dev/include -I/nix/store/i91bmkzcfl1dc4crz8ldc4ilfgirdv1n-neomutt-20240425/include -I/nix/store/gy55m5myy53xjfciqrv7d029l5j6dvyk-zstd-1.5.6-dev/include -I/nix/store/8amn4l7zsjglb9pw18jf1cw2vg9rbal8-libkrb5-1.21.2-dev/include -O2

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme 
  -gsasl +gss +hcache +homespool +idn -inotify -locales_hack +lua -mixmaster 
  +nls +notmuch +openssl +pgp +regex +sasl +smime +sqlite +truecolor 

MAILPATH="mailbox"
PKGDATADIR="/nix/store/i91bmkzcfl1dc4crz8ldc4ilfgirdv1n-neomutt-20240425/share/neomutt"
SENDMAIL="sendmail"
SYSCONFDIR="/nix/store/i91bmkzcfl1dc4crz8ldc4ilfgirdv1n-neomutt-20240425/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: macOS Sonoma 14.5 & Monterey 12.7.5
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? Yes `tmux`, but it happens also without using `tmux`
* Is your email local (maildir) or remote (IMAP)? maildir

**Comment by gahr** [comment]
See https://neomutt.org/guide/reference#3-396-%C2%A0resolve

**Comment by ahmedelgabri** [comment]
> See https://neomutt.org/guide/reference#3-396-%C2%A0resolve

@gahr Not sure I understand, how is this related? `resolve` is set to `true` already, and my config didn't change between versions. Currently, it skips one unread thread and goes to the next one (so basically it jumps 2 threads) 

Here is visually what happens (all messages are unread)

```
N Jul 10 John Doe Some msg <-- cursor is here
N Jul 10 John Doe Some msg <-- I expect it to go here after typing Y
N Jul 10 John Doe Some msg <-- But it goes here
```

**Comment by gahr** [comment]
@ahmedelgabri here's what happens

1. `<tag-thread>` triggers `resolve`, so you tag the first thread and move to the second one
2. `<save-message>` saves **the second thread** to "=Personal/Archive", then triggers the second `resolve`
3. you end up in the 3rd thread

I have double checked and this happens with both 20240416 and main.

**Comment by ahmedelgabri** [comment]
> 2. `<save-message> `saves the second thread to "=Personal/Archive", then triggers the second resolve

This doesn't happen for me. The 2nd thread remains in INBOX as is. It literally just skips it.

> I have double checked and this happens with both 20240416 and main.

That's odd, because it only started to break for me after `20240425` and this has been my setup for years, untouched.

Ok, if that's the case what's the correct way to do this right now?

**Comment by gahr** [comment]
It might be some other config interfering with this. I have tested with an empty config (only `use_threads=yes`) and it behaves as I have explained.

Can you please try with an empty config and keep adding pieces of your config to it until the problem appears?

**Comment by ahmedelgabri** [comment]
Ok will try this and see if it works, thanks

**Comment by ahmedelgabri** [comment]
> > Ok, if that's the case what's the correct way to do this right now?
> 
> What you could do is `"<untag-pattern>.<enter><tag-thread><tag-prefix><save-message>=Personal/Archive<enter>" "Archive conversation"`
> 
> 1. first you untag any tagged messages (just to be sure)
> 2. then you tag the thread
> 3. then you apply `<save-message>` to all tagged messages

@gahr I tried this and it behaves exactly the same as my current macro and skips a thread.

**Comment by gahr** [comment]
Very weird - I suggest to bisect your config, then.

**Comment by ahmedelgabri** [comment]
@gahr can you test with `set use_threads = reverse` because I think this is the only option which we when I remove everything works fine.

**Comment by ahmedelgabri** [comment]
I have no idea what changed between versions and this is still driving me crazy, I have been bisecting my config, and the only thing that affects this is `set use_threads = reverse` which I already have in my config for +8 months

**Comment by ahmedelgabri** [comment]
Thanks @gahr that was it!
