### ISSUE TITLE
in browser.c one line won't ever be executed.

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#435]
In [browser.c](https://github.com/neomutt/neomutt/blob/master/browser.c#L254), we have the assignment

```c
int optional = (flags & MUTT_FORMAT_OPTIONAL);
```

But later, in the same method, we have:

```c
  if (optional)
    mutt_FormatString (dest, destlen, col, cols, ifstring, folder_format_str, data, 0);
  else if (flags & MUTT_FORMAT_OPTIONAL)
mutt_FormatString (dest, destlen, col, cols, elsestring, folder_format_str, data, 0);
```

That means, the second mutt_FormatString won't ever be executed (because its case is already handled inside the first `if(optional)`). Therefore this is a bug - but i don't know how to fix that.

Of course, we could just remove the else part there, but i'm not sure if that is a good solution.

**Comment by guyzmo** [comment]
if you look at the big switch statement in between, you'll see `optional` being assigned `0`. When optional is set to `0` by code in there, `flags & MUTT_FORMAT_OPTIONAL` will still hold the same original value, and the first condition will be false, and the `else if` will be valued.

**Comment by toogley** [comment]
@guyzmo Aaah, okay.
