### ISSUE TITLE
list of architectures/operating system's mutt does run on

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#436]
@flatcap said he's being reluctant to change the build system, because he doesn't know which Operating system or architecture that would break.

## cmake supported platforms

* https://gitlab.kitware.com/cmake/cmake/tree/master/Modules/Platform

---------------------------------------------------------------------------------------

### confirmed

I think it makes sense to orientate ourselves at [NetBSD](http://netbsd.net/releases/formal-7/NetBSD-7.0.2.html#system-families), because it probably supports every platform debian, freeBSD, OpenBSD, etc. support and beyond.

* acorn26 acorn32 algor alpha amd64 amiga amigappc arc atari bebox cats cesfic
cobalt dreamcast emips epoc32 evbarm evbmips evbppc evbsh3 ews4800mi hp300 hppa
hpcarm hpcmips hpcsh i386 ibmnws iyonix landisk luna68k mac68k macppc mipsco
mmeye mvme68k mvmeppc netwinder news68k newsmips next68k ofppc pmax prep rs6000 sandpoint sbmips sgimips shark sparc sparc64 sun2 sun3 vax x68k xen

@0-wiz-0 do you know if neomutt builds on every of those architectures? Do they have currently any problems with neomutt?

---------------------------------------------------------------------------------------

## Operating Systems

([Source](https://github.com/neomutt/neomutt/blob/b03b3c7e7ec0b06365dca6ab929d5f1538d2b9fd/INSTALL#L7-L27))

### confirmed

* FreeBSD
* Linux
* Mac OS X
* NetBSD
* OpenBSD

### confirmation missing

* SCO Unix -  Latest release: 2015, recent versions are based on FreeBSD
* Solaris

### not desirable to support (IMHO)

(I have the release dates from wikipedia)

* BSDI - seems to be legacy
* Digital Unix (OSF/1) - discontinued, proprietary
* QNX - proprietary, Latest release: 2014
* IRIX - discontinued
* HP-UX - proprietary
* DYNIX/ptx - legacy system
* AIX - proprietary, Latest release: October 5, 2015
* Data General Unix (DG/UX) - discontinued in 2001
* UnixWare - proprietary, Latest release:  June 10, 2013
* Convex - [old Supercomputer](https://en.wikipedia.org/wiki/Convex_Computer)
* Ultrix - proprietary, Latest release: 1995
* Atari MiNT - open source. Latest release: 18 March 2013
* MkLinux - Latest release: August 5, 2002
* SunOS - proprietary, Latest release: November 1994

**Comment by guyzmo** [comment]
QNX is supported by CMake AFAICT.

**Comment by toogley** [comment]
@guyzmo yep, it does - at least it has a [QNX module](https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/Platform/QNX.cmake)

**Comment by 0-wiz-0** [comment]
I can't confirm that neomutt builds on all architectures mentioned above. However, they share the same compiler and mostly the same headers (except for CPU specific ones), so I don't expect trouble.
A list of confirmed builds or breakages when building from pkgsrc is at https://bulktracker.appspot.com/pkgresults/mail/neomutt
We really should get more build hardware :-(

**Comment by toogley** [comment]
@0-wiz-0 thanks for the update.

**Comment by flatcap** [comment]
@toogley Please can you promote this info to a webpage (probably in /dev)

**Comment by toogley** [comment]
@flatcap okay, I'll do.

**Comment by flatcap** [comment]
https://www.neomutt.org/dev/architectures
