### ISSUE TITLE
Forwarding mail -- pager isn't repainted

### ISSUE THREAD

**Issue by Knusper** [neomutt/neomutt#4361]
Press `f` to forward a mail, and type the first few letters of a recipient that you have aliased.  A list of recipients starting with those letters is shown. Select the recipient with `<Enter>`.

## Expected Behaviour

The recipient is added to the recipient list,  and we see the pager. Mutt awaits further input in the To: field.

## Actual Behaviour

The behaviour depends on whether a display filter is used or not:

- With display filter, I get a pager, but only the mini index is populated, while the panel showing the mail content is empty.  
- Without display filter, I get the index view.

In both cases mutt awaits further input in the To: field, and I can proceed as normal.  So more a cosmetical bug.

However, I sometimes want to forward mails to multiple recipients based on the content, so it would help to see the content again before adding another recipient.

## Steps to Reproduce

All the "cosmetical" settings I use: https://bitbucket.org/Knusper2000/workspace/snippets/dqyM7n

The display filter I use: https://git.sthu.org/?p=shutils.git;a=blob_plain;f=dotfiles/mutt/scripts/ciscoclean;hb=HEAD

## How often does this happen?

- Always

## NeoMutt Version

```

```NeoMutt 20240329
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.5.0-35-generic (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
GPGME: 1.16.0-unknown
GnuTLS: 3.7.3
libnotmuch: 5.6.0
storage: tokyocabinet

Configure options: --prefix=/home/edmundherenz/local --disable-idn2 --gpgme --lua --notmuch --with-ui --gnutls --tokyocabinet --sqlite --disable-autocrypt

Compilation CFLAGS: -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.4 -I/home/edmundherenz/local/include -I/home/edmundherenz/local/include -DNCURSES_WIDECHAR -I/home/edmundherenz/local/include -I/usr/include/p11-kit-1 -O2

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme 
  -gsasl -gss +hcache -homespool -idn +inotify -locales_hack +lua -mixmaster 
  +nls +notmuch -openssl +pgp +regex -sasl +smime +sqlite +truecolor 

```

**Comment by gahr** [comment]
I can reproduce this, but I'm not familiar with the windowing logic. Let me assign this to @flatcap and wait for him to come back from vacation.

**Comment by flatcap** [comment]
Please can you give branch [[devel/pager-repaint]](https://github.com/neomutt/neomutt/tree/devel/pager-repaint) a try (PR #4405)

Thanks

**Comment by Knusper** [comment]
Will do the coming days.

**Comment by Knusper** [comment]
OK - so I am now back in office.  I understand this has been tested already?

**Comment by flatcap** [comment]
Yes, and merged.
If you have time to build and test `main` that'd be appreciated.
Thanks!
