### ISSUE TITLE
Multiple problems 

### ISSUE THREAD

**Issue by Kantuck837** [neomutt/neomutt#4363]
Gentlemen:

I'm working on installing neomutt, and got the point it shows mail, but before it actually shows neomutt with mail, it gives me this: (Note I blocked out my email account with <EMAILADDRESS> for security reasons)

/home/kantuck/.config/mutt/muttrc:2: Unknown option header_cache_backend
/home/kantuck/.config/mutt/accounts/<EMAILADDRESS>.muttrc:8: Unknown option header_cache
/home/kantuck/.config/mutt/muttrc:4: source: file /home/kantuck/.config/mutt/accounts/<EMAILADDRESS>.muttrc could not be sourced
source: errors in /home/kantuck/.config/mutt/muttrc

It pauses, then a 'enter' shows a normal display. Can you help? What's needed to help me though this? 

--
some of my info: 

(base) kantuck@zeus:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Bunsenlabs
Description:	BunsenLabs GNU/Linux 12 (Boron)
Release:	12
Codename:	boron
(base) kantuck@zeus:~$ 
--
(base) kantuck@zeus:~$ neomutt -v
NeoMutt 20240425-103-5a12fb
(stuff deleted)

System: Linux 6.1.0-23-amd64 (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libidn2: 2.3.3 (compiled with 2.3.3)

Configure options: --disable-doc

Compilation CFLAGS: -std=c11 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -DNCURSES_WIDECHAR -I/usr/include -O2

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme 
  -gsasl -gss -hcache -homespool +idn +inotify -locales_hack -lua +nls -notmuch 
  -openssl +pgp +regex -sasl +smime -sqlite +truecolor 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

**Comment by gahr** [comment]
You need to bring in at least one Header Cache backend at configure time, e.g., `./configure --lmdb`. See how the output from `neomutt -v` gives you `-hcache`.
