### ISSUE TITLE
fedora builds are broken (neomutt-1.8.0-20170225.fc25.x86_64)

### ISSUE THREAD

**Issue by mrunge** [neomutt/neomutt#438]
I'm using the packages from 
https://copr.fedorainfracloud.org/coprs/flatcap/neomutt/

Last weekend, neomutt was updated to neomutt-1.8.0-20170225.fc25.x86_64
displaying an email works once, but I can not display an email afterwards.

Pressing '?' does not work at all, I'm getting a message in bottom line:
����/mutt-sofja-1000-13288-6067559085332765643: No such file or directory (errno = 2)

Fun fact, when adding -d 2 in as command line option, everything works

**Comment by flatcap** [comment]
Hmm... I create (and use) the Fedora packages.  I have no idea what's happening.
What was the last version you used? (version, or rough date)

Do you have header-caching enabled?  Can you delete the cache (or rename it temporarily).

**Comment by mrunge** [comment]
I've used the previous version, and I'm quite sure I was updating regularly.

yes, I have header_cache enabled.

After playing with it again, I can not reproduce the issue any more. I'm closing this for now, sorry for the noise.

**Comment by flatcap** [comment]
Not a problem :-)

**Comment by mrunge** [comment]
Unfortunately, I have to re-open this.

How do I submit useful output, if the issue does not occur, when launching with debug enabled?
Disabling  caches does not help either.

**Comment by mrunge** [comment]
Builds are not broken in general, something seems to get into strange state. Once it get's re-ordered again, everything works as expected. Q is still: how to trigger both events

**Comment by blentz** [comment]
I'm seeing this same issue, but I have no additional info on how to reproduce it just yet.

**Comment by flatcap** [comment]
@blentz Thanks for letting us know.

**Comment by blentz** [comment]
I can confirm that running with '-d1' or -d2' works around the issue. With the flags allows me to open messages, without the flags messages don't open and sounds the terminal bell.

**Comment by flatcap** [comment]
OK, the problem's been introduced by the new hostname lookup code (#420).

A temporary workaround is to add a line to `/etc/hosts` with your hostname, e.g.
```
127.0.0.1  laptop.example.com
```

**Comment by flatcap** [comment]
This is very irritating.  Yesterday, I could reproduce the problem (maybe ~2% of the time).
Today, I can't trigger it.  I haven't managed to trigger it in a debugger at all :-(

Something is trampling over `$tmpdir`, but in the code almost nobody references it.

@mrunge, @blentz 
- Are you using IMAP?
- Are you setting `tmpdir` ?
- What's the output of `grep "^hosts:" /etc/nsswitch.conf`

**Comment by mrunge** [comment]
@flatcap 
I'm not using IMAP, not setting tmpdir

  ```
grep "^hosts:" /etc/nsswitch.conf
  hosts:      files mdns4_minimal [NOTFOUND=return] dns myhostname mymachines
```

Hard coding IP address <-> name in /etc/hosts seems to be a workaround.

**Comment by flatcap** [comment]
OK, I found the problem and @sileht fixed it.
I ran mutt 300,000 times overnight without any problems.

**Comment by mrunge** [comment]
*THANK YOU*, 

the updated package fixes the issue for me. Reading https://github.com/neomutt/neomutt/issues/453 it was quite a piece of work to reproduce.

**Comment by flatcap** [comment]
You're welcome :-)
