### ISSUE TITLE
Attach file prompt does not forgive exiting file chooser

### ISSUE THREAD

**Issue by madduck** [neomutt/neomutt#4385]
## Expected Behaviour

When attaching a MIME part, I should be able to exit the file chooser using tab completion and choose a file to attach (this works). I should also be able to exit the file chooser and re-enter it using tab completion to attach a file.

## Actual Behaviour

If I re-enter the file chooser to select a file to attach, and then hit `<enter>`, no file is attached.

## Steps to Reproduce

In the compose window of a new message:

1. Call `<attach-file>` (`a`)
2. Enter e.g. `/etc/fstab`
3. Hit `<tab>` twice to enter the file chooser, verify that `fstab` is being offered as a choice. Hitting `<enter>` now would attach `/etc/fstab`, and this works
4. Let's not hit enter. Let's attach another file instead, so quit the file chooser (`q`) and find yourself back at the "Attach file" prompt, which now reads: `Attach file: /etc/fstab_`
5. Remove the file name (`^W`) and enter the file chooser to get a complete listing of `/etc` with `<tab><tab>`
6. Select e.g. `motd` in the file chooser and hit `<enter>`
7. Observe that no file has been attached, and you're left at the "Attach file" prompt, which reads: `Attach file: /etc/_`.
8. To actually attach `/etc/motd` at this point, you need to restart the procedure: `^G` `a` `/etc/motd<enter>`

## How often does this happen?

- Always

## When did it start to happen?

I think it's always been the case since switching from Mutt to Neomutt sometime in 2022.

## NeoMutt Version

```
NeoMutt 20240425
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.10.4-amd64 (x86_64)
ncurses: ncurses 6.5.20240427 (compiled with 6.5.20240427)
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.18.0
GnuTLS: 3.8.5
libnotmuch: 5.6.0
PCRE2: 10.42 2022-12-11
storage: tokyocabinet, lmdb
compression: lz4, zlib, zstd

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --autocrypt --disable-paths-in-cflags --full-doc --gnutls --gpgme --gsasl --gss --lmdb --lua --lz4 --notmuch --mixmaster --pcre2 --sqlite --tokyocabinet --zlib --zstd

Compilation CFLAGS: -g -O2 -Werror=implicit-function-declaration -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5 -O2

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme 
  +gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua +mixmaster 
  +nls +notmuch -openssl +pcre2 +pgp -sasl +smime +sqlite +truecolor 

MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

* Operating System and its version: Debian sid
* Were you using multiple copies of NeoMutt at once? Probably
* Were you using 'screen' or 'tmux'? Nope
* Is your email local (maildir) or remote (IMAP)? Maildir

**Comment by flatcap** [comment]
Thanks for the detailed bug report.

I've pushed a simpler-than-I-expected fix to branch [[devel/browser]](https://github.com/neomutt/neomutt/tree/devel/browser).
I just need to check that there aren't any side-effects from my "fix".

If you've got a second to give it a test, that'd be great.

Thanks

---

Technical background:

In the Browser, a lot of code has changed from Mutt.

There were two major architectural problems:

1. The dialog had a big `switch` statement for every possible function.
1. Auto-completion was done in the `enter_string()` function

Both caused huge dependency problems in the code.
In NeoMutt:

1. Dialogs have function dispatchers that delegate the work
2. Auto-completion is abstracted into an API 

---

NeoMutt before the Auto-Completion API:

<img src="https://raw.githubusercontent.com/neomutt/gfx/refs/heads/main/arch/enter-field.svg">

[source](https://github.com/neomutt/gfx/blob/main/arch/README.md#auto-completion)

**Comment by madduck** [comment]
> I've pushed a simpler-than-I-expected fix to branch [[devel/browser]](https://github.com/neomutt/neomutt/tree/devel/browser). I just need to check that there aren't any side-effects from my "fix".
> 
> If you've got a second to give it a test, that'd be great.

I compiled it here and can confirm that the problem I described is gone. Thank you!

**Comment by flatcap** [comment]
Great!  Thanks
