### ISSUE TITLE
Is it possible to use `content-transfer-encoding: 8bit`?

### ISSUE THREAD

**Issue by Dook97** [neomutt/neomutt#4389]
I send a lot of unicode email which neomutt always converts to quoted-printable. Is it possible to make neomutt use `content-transfer-encoding: 8bit` for outgoing mail?

**Comment by gahr** [comment]
I don't think that's safe. Nothing assures that the MTAs you encounter in the path from source to destination implement rfc1426. See also the notes at the end of section 5 here: https://datatracker.ietf.org/doc/html/rfc1521#section-5

**Comment by Dook97** [comment]
> Nothing assures that the MTAs you encounter in the path from source to destination implement rfc1426

I don't think that's an issue realistically. The standard has been there since the 90s and I regularly receive 8bit encoded mail from others.

**Comment by gahr** [comment]
Interestingly, we might have something already: https://neomutt.org/guide/reference.html#3-11-%C2%A0allow_8bit

**Comment by Dook97** [comment]
I tried setting this option:

```
set use_8bit_mime = yes
set assumed_charset = "utf-8"
set allow_8bit = yes
```

and since the description of `allow_8bit` is a little confusing I also tried

```
set use_8bit_mime = yes
set assumed_charset = "utf-8"
set allow_8bit = no
```

None of these did the trick.

**Comment by gahr** [comment]
I have

```
set charset=utf-8
set use_8bit_mime=none # but this doesn't matter to me, I'm not using sendmail
set allow_8bit=yes
```

and I was able to send an email with

```
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
```

**Comment by gahr** [comment]
If that doesn't work fro you, you might try to debug [set_encoding](https://github.com/neomutt/neomutt/blob/main/send/sendlib.c#L351) and see why it doesn't pick 8bit.

**Comment by gahr** [comment]
Try with `charset` instead of `assumed_charset`.

**Comment by Dook97** [comment]
Thanks. I sign my mail with PGP and have just noticed that if I turn signing off 8bit encoding is used with

```
set use_8bit_mime       = yes
set allow_8bit          = yes
set assumed_charset     = "utf-8"
set send_charset        = "utf-8"
set charset             = "utf-8"
```

Is this intentional?

**Comment by gahr** [comment]
ah yes - I can see that when the message is wrapped in a `multipart/signed`, it gets converted to `quoted-printable`. See https://neomutt.org/guide/reference.html#3-340-%C2%A0pgp_strict_enc. I am not familiar with that part to comment, sorry.

**Comment by gahr** [comment]
And turning that off doesn't help either:
https://github.com/neomutt/neomutt/blob/b994413e2663dab426d07571f4f14f404394ef8c/ncrypt/crypt.c#L834-L837

**Comment by gahr** [comment]
This is the case since the introduction of the support for GPGME:
https://github.com/neomutt/neomutt/commit/1afaa74a19eea54937d7cf6069c5091a9c382736#diff-32b07e3e63e959389fb1db2fba52753d7714d5bf2bb7e7935253c425e51e42e0

**Comment by gahr** [comment]
The pgp code is like that since the [dawn of time](https://github.com/neomutt/neomutt/commit/1a5381e07e97fe482c2b3a7c75f99938f0b105d4).

**Comment by gahr** [comment]
And here's the reason: https://www.rfc-editor.org/rfc/rfc3156.html#section-3 
Quoting:  "For this reason all data signed according to this protocol MUST be constrained to 7 bits (8-bit data MUST be encoded using either Quoted-Printable or Base64)."

**Comment by Dook97** [comment]
Thank you!
