### ISSUE TITLE
Option index_format: Conditional expando is missing '&' or '?'

### ISSUE THREAD

**Issue by mgedmin** [neomutt/neomutt#4395]
## Expected Behaviour

Use Neomutt like always.

## Actual Behaviour

My `set index_format` customizations and macros now cause an error.

## Steps to Reproduce

1. `set index_format="%4C%?M?+& ?%Z %[%m-%d] %-15.15F %?M?<%4M>&(%4c)? %s"`

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use? 20240416

This error first started showing up in 20240425.  It was [reported on the mailing list](https://mailman.neomutt.org/pipermail/neomutt-users-neomutt.org/2024-April/001391.html) with a [promise of a fix](https://mailman.neomutt.org/pipermail/neomutt-users-neomutt.org/2024-April/001392.html), so I didn't report it, until I realized that the fix got dropped somewhere between that email and today's new release.

## NeoMutt Version

```
NeoMutt 20241002
Copyright (C) 2015-2024 Richard Russon ir kiti.
NeoMutt ateina ABSOLIUČIAI BE JOKIOS GARANTIJOS; dėl smulkmenų paleisk 'neomutt -vv.'
NeoMutt yra laisva programinė įranga, ir tu gali laisvai ją platinti su tam
tikromis sąlygomis; rašyk 'neomutt -vv' dėl smulkmenų.

System: Linux 6.8.0-45-generic (x86_64)
ncurses: ncurses 6.4.20240113 (compiled with 6.4.20240113)
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.18.0
GnuTLS: 3.8.3
libnotmuch: 5.6.0
storage: lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --with-mailpath=/var/mail --mixmaster --gnutls --gpgme --gss --sasl --lua --notmuch --full-doc --lmdb

Compilation CFLAGS: -std=c11 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.4 -I/usr/include -DNCURSES_WIDECHAR -I/usr/include -I/usr/include/p11-kit-1 -isystem /usr/include/mit-krb5 -O2

Kompiliavimo parinktys:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme 
  -gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua +nls +notmuch 
  -openssl +pgp +regex +sasl +smime -sqlite +truecolor 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

Jei norite daugiau sužinoti apie NeoMutt, aplankykite https://neomutt.org
Jei radote NeoMutt klaidą, praneškite apie ją
    https://github.com/neomutt/neomutt/issues
arba paštu į <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: **Ubuntu 24.04 **
* Were you using multiple copies of NeoMutt at once?  **no**
* Were you using 'screen' or 'tmux'?  **no**
* Is your email local (maildir) or remote (IMAP)?  **maildir**

**Comment by gahr** [comment]
Make it `"%4C%<M?+& >%Z %[%m-%d] %-15.15F %<M?<%4M>&(%4c)> %s"`. I'm not sure at which point the (undocumented?) format of `?..?..&..?` conditional was decommissioned.

**Comment by gahr** [comment]
oh, but that's a separate issue :)

**Comment by mgedmin** [comment]
Do you still need my verification after https://github.com/neomutt/neomutt/issues/4286#issuecomment-2451583923?  I thought that was the same issue?

(I've already changed my format strings to use `«   3»` for thread counts, messing up VIm's %s/// in the process, so my git history is a bit of a mess.  I can try to dig out the old format strings if there's still need, but it would be a pain.)

**Comment by flatcap** [comment]
It's the same issue, but I'd like everyone to be happy :-)

> it would be a pain

Don't worry.
I tested the format string that you reported and it was good.
