### ISSUE TITLE
Typing with vim editor ecounters a probable bug

### ISSUE THREAD

**Issue by TomHsiung** [neomutt/neomutt#4410]
## Bug description

When writing or replying to an email with the Vim editor in NeoMutt, the software forces me to start a new line when I am typing the 74th letter. Because the Vim editor provides me with the number of lines and characters, I know this issue happens at the 74th letter.

PS: You can type a constant letter but make sure there is at least one space before the 74th letter, in order to reproduce the problem.

The sentence is not finished but the software forces the cursor to jump to a new line.

## How often does this happen?
- Always

## When did it start to happen?

After upgrading from the version 20040425 to the latest version by Homebrew on Macs.

## NeoMutt Version

```
NeoMutt 20241002
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 24.1.0 (x86_64)
ncurses: ncurses 6.5.20240427 (compiled with 6.5.20240427)
libiconv: 1.17
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.23.2
OpenSSL: OpenSSL 3.3.2 3 Sep 2024
libnotmuch: 5.6.0
PCRE2: 10.44 2024-06-07
storage: tokyocabinet, lmdb
compression: zlib

Configure options: --sysconfdir=/usr/local/etc --autocrypt --gss --disable-idn --idn2 --lmdb --nls --notmuch --pcre2 --sasl --sqlite --tokyocabinet --zlib --with-idn2=/usr/local/opt/libidn2 --with-lua=/usr/local/opt/lua --with-ncurses=/usr/local/opt/ncurses --with-ssl=/usr/local/opt/openssl@3 --with-sqlite=/usr/local/opt/sqlite --with-iconv=/usr/local/opt/libiconv --disable-debug --disable-dependency-tracking --prefix=/usr/local/Cellar/neomutt/20241002 --libdir=/usr/local/Cellar/neomutt/20241002/lib

Compilation CFLAGS: -std=c11 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/local/opt/libgpg-error/include -I/usr/local/Cellar/libassuan/3.0.1/include -I/usr/local/Cellar/gpgme/1.23.2_2/include -I/usr/local/Cellar/neomutt/20241002/include -I/usr/local/include/lua -I/usr/local/Cellar/neomutt/20241002/include -I/usr/local/Cellar/neomutt/20241002/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/neomutt/20241002/include -DNCURSES_WIDECHAR -I/usr/local/opt/ncurses/include -I/usr/local/opt/libiconv/include -I/usr/local/Cellar/openssl@3/3.3.2/include -I/usr/local/Cellar/libidn2/2.3.7/include -I/usr/local/Cellar/pcre2/10.44/include -I/usr/local/opt/lmdb/include -I/usr/local/Cellar/tokyo-cabinet/1.4.48/include -I/usr/local/Cellar/neomutt/20241002/include -O2

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme
  -gsasl +gss +hcache -homespool +idn -inotify -locales_hack +lua +nls +notmuch
  +openssl +pcre2 +pgp +sasl +smime +sqlite +truecolor

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/Cellar/neomutt/20241002/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by gahr** [comment]
I think vim is detecting that you're writing an email and sets up some configuration, such as `testwidth`.

Try `:set ft? textwidth?` in your vim, and see what you get.

**Comment by TomHsiung** [comment]
> I think vim is detecting that you're writing an email and sets up some configuration, such as `testwidth`.
> 
> Try `:set ft? textwidth?` in your vim, and see what you get.

Thanks for the reply, pal.

Oh! That's tricky because it had never happened before the upgrade (Vim has been upgraded along with NeoMutt by Homebrew too). With the command you mentioned, the feedback is

>  filetype=mail
>   textwidth=72

How do we fix this problem? Many thanks

**Comment by TomHsiung** [comment]
> filetype plugin on
> autocmd FileType mail setlocal textwidth=0

Adding these two lines to ~/.vimrc solved the problem. Many thanks.

**Comment by gahr** [comment]
I don't know what's changed, but this has been there since the dawn of time :)
https://github.com/vim/vim/blob/991657e87db9a6212e14b10594ca0a008d1ccd1c/runtime/ftplugin/mail.vim#L20-L22

**Comment by TomHsiung** [comment]
> I don't know what's changed, but this has been there since the dawn of time :) https://github.com/vim/vim/blob/991657e87db9a6212e14b10594ca0a008d1ccd1c/runtime/ftplugin/mail.vim#L20-L22

Amazing, man.

> " many people recommend keeping e-mail messages 72 chars wide
> if &tw == 0
>   setlocal tw=72
> endif

I don't like it. Hmmm... Anyway, the issue has been resolved, and thanks a bunch. I will close the issue now.
