### ISSUE TITLE
Sended emails with bad PGP signature (NeoMutt 20241002). Encryption works with gpgme.

### ISSUE THREAD

**Issue by clarintux** [neomutt/neomutt#4413]
## Expected Behaviour

Send email from my email address to my email address und only sign whitout encryption. Others clients on the same machine are able to sign properly. BTW encryption works as expected.
Here my neomuttrc:

```
set crypt_use_gpgme=yes
set postpone_encrypt = yes
set pgp_self_encrypt = yes
set crypt_use_pka = no
set crypt_autosign = yes
set crypt_autoencrypt = no
set crypt_autopgp = yes
set pgp_use_gpg_agent = yes
set pgp_sign_as=0x............
set crypt_verify_sig=yes
set crypt_replysign=yes
set crypt_replyencrypt=yes
set crypt_replysignencrypted=yes
```

## Actual Behaviour

The signature contained an error. Neomutt and other clients display "BAD signature" or "signature cointained an error" on the received emails. This error occour only sending on Neomutt.

## Steps to Reproduce

1. If crypt_autosign is not set, you can press "p" before sending.
2. Then press "s" for sign.
3. Press "y" for sending.
4. Verify the (bad..) PGP-signature on the received email.

## How often does this happen?

- Always, but I have only tested from my email address to my email address

## NeoMutt Version

```
NeoMutt 20241002
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.7.4-gnu-1 (x86_64)
ncurses: ncurses 6.5.20240427 (compiled with 6.5.20240427)
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.23.2
GnuTLS: 3.8.7
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --ubsan --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/neomutt/src=/usr/src/debug/neomutt -flto=auto -std=c11 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.3 -I/usr/include -I/usr/include -I/usr/include -DNCURSES_WIDECHAR -I/usr/include -I/usr/include/p11-kit-1 -I/usr/include -I/usr/include -fsanitize=undefined -fno-omit-frame-pointer -fno-common -g -O0

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme
  -gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua +nls +notmuch
  -openssl +pgp +regex +sasl +smime +sqlite +truecolor

Devel options:
  ubsan

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* SO: Parabola GNU/Linux
* Were you using multiple copies of NeoMutt at once?  No.
* Were you using 'screen' or 'tmux'?  No.
* Is your email local (maildir) or remote (IMAP)?  IMAP

**Comment by gahr** [comment]
Can you please make your public key available and send me an email at gahr@gahr.ch?

**Comment by gahr** [comment]
Thanks - I got your email. I confirm that it's giving me a bad signature. Your email doesn't have a `MIME-Version: 1.0` header, which is kind of surprising...

I confirm that adding MIME-Version to the main part and to the multipart/signed part make the signature valid.

I have no idea how you can end up without that header, though.

Can you please try with a minimal config and build up from there until you get something invalid?

**Comment by clarintux** [comment]
I found the problem in the server configuration:

/^Mime-Version:/                IGNORE

Whit Mime-Version stripped out, Neomutt had problems. I have solved the problem removing this line in my own server...
Thank you!

So..is the Mime-Version necessarely needed?

**Comment by gahr** [comment]
> So..is the Mime-Version necessarely needed?

Yes, but..

* yes: `MIME-Version: 1.0` is mandated by [RFC1521](https://datatracker.ietf.org/doc/html/rfc1521#section-3)
* but: the issue here is not with the header being mandatory or not. The issue is that what you signed is not what comes out at the other end of the pipeline, so NeoMutt **correctly** says that the signature is not valid: the email body is **not** what was signed. I wonder what your other email clients are saying about those emails. If they're failing at detecting that the mail has been "tampered with" (by your sever), then they're not doing a good job..
