### ISSUE TITLE
certificate_file is ignored

### ISSUE THREAD

**Issue by 4nd3r** [neomutt/neomutt#4414]
## Expected Behaviour
Accepted certificates are stored in file set with `certificate_file`.

In my case:
```
$ neomutt -D | grep certificate_file
set certificate_file = "~/.cache/neomutt/certificates"
```
## Actual Behaviour
Certificates are stored in `~/.mutt_certificates`.

## Steps to Reproduce
First bad commit is a5eaeb51b14c484fa52f6f519446253dea5667ca.

## NeoMutt Version
Built from main.

```
$ neomutt -v
NeoMutt 20241002-24-af3843
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.11.4-amd64 (x86_64)
ncurses: ncurses 6.5.20240427 (compiled with 6.5.20240427)
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.23.2
GnuTLS: 3.8.6
storage: lmdb
compression: zstd

Configure options: --prefix=/usr/local --disable-doc --disable-nls --disable-pgp --gnutls --gpgme --gsasl --lmdb --zstd

Compilation CFLAGS: -std=c11 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -DNCURSES_WIDECHAR -I/usr/local/include -I/usr/include/p11-kit-1 -O2

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme 
  +gsasl -gss +hcache -homespool +idn +inotify -locales_hack -lua -nls -notmuch 
  -openssl -pgp +regex -sasl +smime -sqlite +truecolor 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

## Extra Info

* Operating System and its version: Debian Sid
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? IMAP

**Comment by flatcap** [comment]
Hmm... that's very odd.
I can't seem to repeat the problem with either 'main' or `2024-10-02`.

Also, I think something went wrong with your bisect.
That commit is 3 years old and it didn't alter `$certificate_file` :-)

The only possible cause I can think of, is that you've got some `mailboxes` commands **before** you set `$certificate_file`.
NeoMutt tries to connect when it reads `mailboxes` -- that's been the case for a few years, though.

**Comment by 4nd3r** [comment]
> The only possible cause I can think of, is that you've got some mailboxes commands before you set `$certificate_file`.

You are correct. Moved `mailboxes` to the end of `neomuttrc` and problem solved.

Sorry for the noise.

**Comment by flatcap** [comment]
No worries :-)
