### ISSUE TITLE
No +sidebar after installation

### ISSUE THREAD

**Issue by yongli-abc** [neomutt/neomutt#4418]
Hi, I've installed using homebrew. After installation, `neomutt -v` shows no `+sidebar` option. Not sure this is expected?

**Comment by gahr** [comment]
Yes, the sidebar is not a compile-time option that we show with `+` or `-`. It's always there. Try `:toggle sidebar-visible` if you don't see it.

**Comment by flatcap** [comment]
`neomutt -v` used to list two blocks of options.

The first was a list of all the features that were **always** enabled.
Historically, they were separate patches, then they became always on.

A year ago we dropped the list (154c5410a) -- it hadn't changed in years.
I'll check the docs for any remaining references to `+sidebar`, etc.

**Comment by flatcap** [comment]
Done:
- https://github.com/neomutt/neomutt/commit/946176df1f0926cc1f434988094e8904773afca5
- https://github.com/neomutt/neomutt.github.io/commit/20d0be4334ff3db43b972e6a84c265e9e14ffa0a
