### ISSUE TITLE
Date in quote reply is incorrect (ignores timezone)

### ISSUE THREAD

**Issue by alejandro-colomar** [neomutt/neomutt#4419]
## Expected Behaviour

I replied to a message with the following Date header:
```email
Date: Mon, 9 Sep 2024 11:28:04 +0300
```

That date, translated to UTC, is:
```sh
$ date -u -d 'Mon, 9 Sep 2024 11:28:04 +0300'
Mon Sep  9 08:28:04 UTC 2024
```

I expect that when I start a reply, neomutt(1) should add a reply that starts with the correct date, in the original timezone.

## Actual Behaviour

When I replied to that message, neomutt(1) added the following quote:

```
On Mon, Sep 09, 2024 at 11:28:04AM GMT, Stefan Puiu wrote:
> ...
```

which takes the hour from the original message, and discards the timezone information, making it a different date.

Reply to a message.

neomutt(1) misinterprets the date.

## Steps to Reproduce

I don't have any configuration for the format of the date, so a default configuration should be enough to trigger this.

Just reply to any email that's not in the UTC timezone.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

I don't remember.  I've noticed now, but it seems that it has happened for several months already, and I changed my neomutt(1) several months ago, so I don't know for sure.

- When I changed my config
  Can you narrow down **what** you changed?

## NeoMutt Version

```
$ neomutt -version
NeoMutt 20240425-77-707b65
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.11.4-amd64 (x86_64)
ncurses: ncurses 6.5.20240427 (compiled with 6.5.20240427)
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.18.0
GnuTLS: 3.8.5
libnotmuch: 5.6.0
storage: lmdb
compression: zlib, zstd

Configure options: --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules {{--libdir=/lib/x86_64-linux-gnu}} {{--libexecdir=/lib/x86_64-linux-gnu}} --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --gnutls --gss --idn2 --mixmaster --gsasl --lmdb --zlib --zstd

Compilation CFLAGS: -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.4 -I/usr/include -I/usr/include -DNCURSES_WIDECHAR -I/usr/include -I/usr/include/p11-kit-1 -I/usr/include -isystem /usr/include/mit-krb5 -O2

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme 
  +gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua +mixmaster 
  +nls +notmuch -openssl +pgp +regex -sasl +smime -sqlite +truecolor 

MAILPATH="/var/mail"
MIXMASTER="mixmaster"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

This is built from a branch where I added code for reading the protected Message-ID (but that code doesn't touch anything about the date).  It branches off main in 20fe7bdc2ced ("fix return types").

## Extra Info

* Is your email local (maildir) or remote (IMAP)?

Local.  mbsync(1) FTW!  :)

**Comment by gahr** [comment]
What's in your `attribution_intro`, `attribution_trailer`, `attribution_locale`, and your environment locale?

**Comment by alejandro-colomar** [comment]
> What's in your `attribution_intro`, `attribution_trailer`, `attribution_locale`,

```rc
alx@debian:~/.config/mutt$ grep -rn attribution
alx@debian:~/.config/mutt$ 
```

> and your environment locale?

```sh
alx@debian:~$ locale
LANG=C.utf8
LANGUAGE=
LC_CTYPE="C.utf8"
LC_NUMERIC="C.utf8"
LC_TIME="C.utf8"
LC_COLLATE="C.utf8"
LC_MONETARY="C.utf8"
LC_MESSAGES="C.utf8"
LC_PAPER="C.utf8"
LC_NAME="C.utf8"
LC_ADDRESS="C.utf8"
LC_TELEPHONE="C.utf8"
LC_MEASUREMENT="C.utf8"
LC_IDENTIFICATION="C.utf8"
LC_ALL=
```

**Comment by gahr** [comment]
TZ?

**Comment by gahr** [comment]
> > What's in your `attribution_intro`, `attribution_trailer`, `attribution_locale`,
> 
> ```
> alx@debian:~/.config/mutt$ grep -rn attribution
> alx@debian:~/.config/mutt$ 
> ```

Can you please tell me what NeoMutt says when you write `set attribution_intro?`, etc? It might be set by some system-wide config file or anything else. I'd rather see what NeoMutt sees.

**Comment by gahr** [comment]
> I replied to a message with the following Date header:
> 
> ```
> Date: Mon, 9 Sep 2024 11:28:04 +0300
> ```

is this how NeoMutt renders the date in the pager, or is this the actual content of the raw email?

**Comment by alejandro-colomar** [comment]
> > I replied to a message with the following Date header:
> > ```
> > Date: Mon, 9 Sep 2024 11:28:04 +0300
> > ```
> 
> is this how NeoMutt renders the date in the pager, or is this the actual content of the raw email?

I pasted that from the pager, but the raw email is identical:

```
alx@debian:~/mail/migadu/foss/Inbox$ grep -rl 'Message-ID: <CACKs7VB_GEt_u463R4JvWveghBBscQeqaWtKrMmxNSQ2mn+-VA@mail.gmail.com>' | xargs grep ^Date:
Date: Mon, 9 Sep 2024 11:28:04 +0300
```

> `./neomutt -D | grep attribution` would do, too

alx@debian:~$ neomutt -D | grep attribution
set attribution_intro = "On %d, %n wrote:"
set attribution_locale = ""
set attribution_trailer = ""
set forward_attribution_intro = "----- Forwarded message from %f -----"
set forward_attribution_trailer = "----- End forwarded message -----"

(That's the default, I expect, since I didn't change anything.)

> TZ?

```sh
alx@debian:~$ env | grep TZ
alx@debian:~$ 
```

```sh
$ date +%Z
CET
```

**Comment by gahr** [comment]
Ok, it's fine: if you look at the [attribution_intro's docs](https://neomutt.org/guide/reference.html#3-31-%C2%A0attribution_intro), they'll point you to the [index_format's doc](https://neomutt.org/guide/reference.html#index-format), which tells you that `%d` is `Date and time of message using [date_format](https://neomutt.org/guide/reference.html#date-format) and sender's timezone`.

I suspect you don't have a time-zone formatter inyour `date_format`?

Also, it suggests to switching to `%{fmt}`, which can be better parametrized.

Yes, we still ship with `attribution_intro` defaulting to using `%d` instead of `%{...}`.

**Comment by alejandro-colomar** [comment]
@gahr

> Ok, it's fine: if you look at the [attribution_intro's docs](https://neomutt.org/guide/reference.html#3-31-%C2%A0attribution_intro), they'll point you to the [index_format's doc](https://neomutt.org/guide/reference.html#index-format), which tells you that `%d` is `Date and time of message using [date_format](https://neomutt.org/guide/reference.html#date-format) and sender's timezone`.
> 
> I suspect you don't have a time-zone formatter inyour `date_format`?

I don't change it either.  It's the default:

```muttrc
alx@debian:~$ neomutt -D | grep date_format
set date_format = "!%a, %b %d, %Y at %I:%M:%S%p %Z"
```

> 
> Also, it suggests to switching to `%{fmt}`, which can be better parametrized.

Yeah, I've read that today.

> 
> Yes, we still ship with `attribution_intro` defaulting to using `%d` instead of `%{...}`.

This is still a bug somewhere.  I have older mails that behave as expected.  It broke only earlier this year.

**Comment by gahr** [comment]
> I don't change it either. It's the default:

Oh right, I just realized it has the timezone in the attribution, just the wrong one.

> I have older mails that behave as expected

Can you please forward an example of a mail that works and one that breaks to me?

**Comment by alejandro-colomar** [comment]
> > I don't change it either. It's the default:
> 
> Oh right, I just realized it has the timezone in the attribution, just the wrong one.
> 
> > I have older mails that behave as expected
> 
> Can you please forward an example of a mail that works and one that breaks to me?

I've bounced you mails (both original and my reply), and replied saying which is the good and the bad.  I suspect that it doesn't have to do with the mail, but with the date --and thus the neomutt(1) version that I used-- where I replied.

**Comment by gahr** [comment]
> but with the date --and thus the neomutt(1) version that I used-- where I replied

... and the config. Although I'm sure you're sure you haven't changed anything :)

**Comment by gahr** [comment]
most importantly: does it work *now*?

**Comment by gahr** [comment]
Ah - 20240425. Does it work with the latest release?

**Comment by gahr** [comment]
This is probably #4341.

**Comment by gahr** [comment]
I can repro the bug on 20240425, and it's been fixed.
