### ISSUE TITLE
fix indendation of manual.xml.head using libtidy

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#442]
This is just an issue to make sure i don't forget this.

Basically, http://www.html-tidy.org/ allows reindenting xml files which would greatly help our xml file mess.

**Comment by guyzmo** [comment]
or simply using vim `gg=G` to reindent it properly.

**Comment by toogley** [comment]
@guyzmo Ah, i forgot that vim can do this too^^ 

But yes, i agree. This is even better at the moment, because libtidy removed lines in between the sections. (but i'm sure this can be turned off).

**Comment by gahr** [comment]
xmllint - part of libxml2 - does proper indentaion too. Just tossing it here for the record ;)

**Comment by flatcap** [comment]
Much as I love vim, it's not the right tool here (unless you set `equalprg=tidy`).
I've used (lib)tidy a lot, but I couldn't get it to understand the `screen` sections which need to be left intact.
`xmllint` understood the `screen`s, so it's winning for me.

**Comment by toogley** [comment]
@flatcap do you want to fix the indendation of the manual also with the clang-format fix?

**Comment by flatcap** [comment]
@toogley 
Yes, that'd be a good time to do it.

I'm about to start tidying the code.
If you have time, please can you make the changes.
Hopefully, it'll just be a five minute job + a quick scan of the built html.

Also, for extra points, please can you alter `doc/makedoc.c` to output correctly indented XML.

**Comment by toogley** [comment]
@flatcap 

> I've used (lib)tidy a lot,  but I couldn't get it to understand the screen sections which need to be left intact.

Do you mean, that libtidy changes `<section>` to e.g. `<sect1> ` ? Can you further explain why that's a problem?

---------

regarding fixing `doc/makedoc.c` maybe i can do this in some months or so, i don't know. For the next month or so i will be in a heavy exam phase, so i won't have much time for neomutt.

**Comment by flatcap** [comment]
The `<screen>` sections are like html's `<pre>`.  Their content should be left alone.
Indenting, or reformatting, the contents of screen tags will mess the html.

Try running tidy on the manual, then looking at the "screenshots" in the sidebar intro.

> For the next month or so i will be in a heavy exam phase

OK, not to worry.  Good luck!

**Comment by toogley** [comment]
@flatcap aah, okay.thanks for the explanation.

>    For the next month or so i will be in a heavy exam phase
>
> OK, not to worry. Good luck!

Thanks :)

**Comment by toogley** [comment]
sorry, i don't think i can finish this issue in the next days/weeks.
