### ISSUE TITLE
Re-use of buffer for both compressed and uncompressed data

### ISSUE THREAD

**Issue by alejandro-colomar** [neomutt/neomutt#4434]
https://github.com/neomutt/neomutt/blob/4ebb12a2bd7ee37f28355cf535813aac53594030/compress/lz4.c#L46-L50

Hi @flatcap ,

While trying to fix the sign mismatch issues, I noticed that we use these structures for holding both compressed and uncompressed data.  I'm thinking that it might be better to have two separate types, one for compressed data (which would use `unsigned char *`, and one for uncompressed data (which would use `char *`.

What do you think?

**Comment by flatcap** [comment]
Hmm...

I think that the compression layer should _probably_ **only** use `unsigned char *`.
Only the callers know the type of their uncompressed data.

In NeoMutt's case the caller is the Header Cache.
There _are_ plenty of strings, but there are also plenty of serialised `int`s, etc.

---

Fixing sign problems is notoriously painful, so I'm happy to accept a few `(char *)` casts, for now.

But... if you want to dig deeper, I wish you luck and look forward to the PR :-)

**Comment by alejandro-colomar** [comment]
Hmmm, having serialized ints makes me agree with you on `unsigned char *`.  I'll keep it simple for now.  :-)

**Comment by alejandro-colomar** [comment]
On the other hand, how about embracing the GNU extension that `sizeof(void) == 1`?  I think it's better than the casts.

For now, I'll use the casts, but I suggest considering using this GNU extension in the future.

**Comment by alejandro-colomar** [comment]
I've just dropped the patch and reverted to void* (which was my original proposal).  I'll close this issue.
