### ISSUE TITLE
Attachment regex search does not work when 'set arrow_cursor = yes'

### ISSUE THREAD

**Issue by protostork** [neomutt/neomutt#4435]
## NeoMutt Version

```
NeoMutt 20241002
```

Similar symptom / problem to #4231 but only on arrow_cursor and not fixed in latest version 20241002.

## Steps to Reproduce

Highlight any multipart message with an html part, then turn on arrow_cursor current line highlighting: 
`:set arrow_cursor = yes`

In the pager press "v", then in the attachment page type "/" then "html" then <Enter>.

## Expected Behaviour

It should find and highlight the relevant attachment matching 'html' in its mimetype.

## Actual Behaviour

It shows 'Not found' in the message bar, even though a text/html attachment exists. 

If you `:set arrow_cursor = no` before searching, you get the expectd behaviour.

## How often does this happen?

- Always (when set arrow_cursor is true)

## When did it start to happen?

Not entirely sure, but it seems like maybe a little bit less than one year.

## Extra Info

* On Arch-based Linux with single instance of neomutt running, not in tmux or screen, with a local maildir

**Comment by flatcap** [comment]
Thanks for the bug report.

If happy building NeoMutt, please can you give branch [[devel/compose]](https://github.com/neomutt/neomutt/tree/devel/compose) a try.

Thanks

**Comment by protostork** [comment]
Hi, thanks for the quick response and fix - alas I didn't make it in time to try the compose branch, sorry. 

I just tried the 'main' branch though (which you have merged 'compose' into, including the change in compose/attach.c) and built this from source, but it didn't seem to work for me (i.e., when I have arrow_cursor enabled, it still didn't jump to the correct attachment). 

It could be something with my setup, though I tried without with a clean conf and could still reproduce the error (and avoid the error with arrow_cursor=no). If there any other info I can provide that might help, please let me know.

**Comment by flatcap** [comment]
> alas I didn't make it in time to try the compose branch, sorry.

No worries.
I wanted to make a release and I was convinced that I'd fixed _something_ :-)

> I just tried the 'main' branch
> could still reproduce the error

*ahem*.  Yeah, I've spotted why that's the case.
In my haste I fixed the Compose Attachments, not the View Email Attachment.

I've pushed another commit which fixes 12 other dialogs, including the Attachments Dialogs.

Please can you give branch [[devel/attach]](https://github.com/neomutt/neomutt/tree/devel/attach) a try.

Thanks

**Comment by protostork** [comment]
Superb, thank you, that fix works perfectly now in the attachments view! Looking forward to a new release whenever you feel the need :)

**Comment by flatcap** [comment]
Brilliant.  Thanks for testing.
