### ISSUE TITLE
Issues with mail titles wrapping around into left menu area

### ISSUE THREAD

**Issue by christian-heusel** [neomutt/neomutt#4443]
## NeoMutt Version

```
neomutt -v
NeoMutt 20241114
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.11.9-rc1-1home (x86_64)
ncurses: ncurses 6.5.20240427 (compiled with 6.5.20240427)
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.24.0
GnuTLS: 3.8.8
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --ubsan --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/neomutt/src=/usr/src/debug/neomutt -flto=auto -std=c11 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include/lua5.3 -I/usr/include -I/usr/include -I/usr/include -DNCURSES_WIDECHAR -I/usr/include -I/usr/include/p11-kit-1 -I/usr/include -I/usr/include -fsanitize=undefined -fno-omit-frame-pointer -fno-common -g -O0

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme 
  -gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua +nls +notmuch 
  -openssl +pgp +regex +sasl +smime +sqlite +truecolor 

Devel options:
  ubsan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Expected Behaviour

Lines are self-contained

## Actual Behaviour

For some mails with long titles they wrap around into the next line and left menu area, see the following video as a showcase:

https://github.com/user-attachments/assets/7a348995-6461-493d-b7d5-d9ec9d357b15

## Steps to Reproduce

Have the following index format (as I do) and scroll through some mails with long titles:
```
set index_format="%4C %Z %?X?A& ? %D %-15.15F %s (%-4.4c)"
```

## How often does this happen?

- [ ] Always

- [x] Sometimes

- [ ] On a particular email
  If the email isn't private, please attach it to this issue.

## When did it start to happen?

- [x] When I upgraded 
  Which version did you use to use? I upgraded from `20241002-1` to `20241114-1` via my package manager

- [ ] When I changed my config
  Can you narrow down **what** you changed?

## Extra Info

* Operating System and its version: Arch Linux (rolling)
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? local

**Comment by flatcap** [comment]
Please can you give branch [[devel/overflow]](https://github.com/neomutt/neomutt/tree/devel/overflow) a try.

I'll have a closer look in the morning, but I _think_ this fixes the problem.

Thanks

**Comment by christian-heusel** [comment]
The fix seems to work 😊
