### ISSUE TITLE
Make the debug level configurable within neomutt

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#445]
Starting neomutt with the option `-d 2` enables debug logging (if enabled by the build).
Often, the user hasn't enabled this logging when then encounter a problem.
Often, restarting will leave neomutt in a slightly different state to the one that caused the problem.

I propose changing the internal `debuglevel` variable into a user-configurable `$debug_level`

Use case: User sees some unexpected behaviour
- `set debug_level=5`
- repeat actions to repeat error

When `debug_level` is set > 0, a new log file will be opened.
When `debug_level` is set to 0, the log file will be closed.

**Comment by guyzmo** [comment]
then debugfile should be configurable as well!

**Comment by sileht** [comment]
+1 for the idea

I like the idea to have an configurable debugfile. I don't like the current behavior I would prefer to always append to the same file.

I can work on this, if nobody step in.

**Comment by toogley** [comment]
> I can work on this, if nobody step in.

@sileht Nobody has assigned theirselfes to this issue yet, therefore you can of course work on this.

I'll assign you to it, so that people know this is WIP.

Thanks! :)
