### ISSUE TITLE
sidebar-next and sidebar-prev moves only the underline, but not the highlight, from entry to entry

### ISSUE THREAD

**Issue by ckhung** [neomutt/neomutt#4455]
## NeoMutt Version
NeoMutt 20241114
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.10.6-amd64 (x86_64)
ncurses: ncurses 6.5.20240427 (compiled with 6.5.20240427)
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.24.0
GnuTLS: 3.8.8
libnotmuch: 5.6.0
PCRE2: 10.42 2022-12-11
storage: tokyocabinet, lmdb
compression: lz4, zlib, zstd

Configure options: --build=x86_64-linux-gnu --prefix=/usr {--includedir=${prefix}/include} {--mandir=${prefix}/share/man} {--infodir=${prefix}/share/info} --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules {--libdir=${prefix}/lib/x86_64-linux-gnu} --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --autocrypt --disable-paths-in-cflags --full-doc --gnutls --gpgme --gsasl --gss --lmdb --lua --lz4 --notmuch --pcre2 --sqlite --tokyocabinet --zlib --zstd

Compilation CFLAGS: -g -O2 -Werror=implicit-function-declaration -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -std=c11 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -DNCURSES_WIDECHAR -isystem /usr/include/mit-krb5 -O2

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme 
  +gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua +nls +notmuch 
  -openssl +pcre2 +pgp -sasl +smime +sqlite +truecolor 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

## Expected Behaviour

After binding some keys (see ~/.muttrc at end), I press the tab key to bring up the sidebar and use the up and down arrow keys in order to  move among folders. I expect the highlight to move from entry to entry when the arrow keys are pressed. Pressing enter on a non-empty folder should open its content on the right (main) panel.

## Actual Behaviour

The highlight remains still at the first entry all the time. However, there is an underline moving from entry to entry when the arrow keys are pressed. Pressing enter on a any folder, including non-empty ones, causes neomutt to complain "No mailbox is open".

## Steps to Reproduce

See above.

## How often does this happen?

Always

## When did it start to happen?

Neomutt does not see my mail folders at all without a ~/.muttrc . I think it is because of some utf7 <-> utf8 conversion problem (which I would like to raise as a separate issue). Therefore I create a minimal ~/.muttrc as follows:

```
# set sidebar_visible
set sidebar_format = "%B%<F? [%F]>%* %<N?%N/>%S"
set mail_check_stats
# mailboxes `ls -d ~/Mail/*`

bind index,pager <Up> sidebar-prev
bind index,pager <Down> sidebar-next
bind index,pager <Enter> sidebar-open
bind index,pager <Tab> sidebar-toggle-visible

mailboxes +0-INBOX +1-Draft +2-Sent +3-Sent-Backup +7-Trash
```
I also commented out ```set mixmaster="mixmaster-filter"``` in the system config /etc/neomuttrc to suppress a deprecation warning. Other than that I changed nothing in the system config.

## Extra Info

OS is debian testing (trixie), xfce4.
Have tried and seen the same behavior on lxterminal, xfce4-terminal, and sakura.

![a](https://github.com/user-attachments/assets/a106b62e-3445-488c-9c46-6cbce90228a5)

**Comment by gahr** [comment]
There are a few issues here

1. the expectation that the highlight moves is misplaced: the highlight stays with the currently open mailbox
2. you don't have a `spool_file` set, so when NeoMutt starts up, it doesn't open any mailbox. It probably tries to open /var/mail/$LOGIN and fails. I suggest to add `set spool_file = +0-INBOX`

Having said that, I can reproduce the fact that `Enter` doesn't try to open the current sidebar entry, but still tries to open the selected message. Because you don't have an open mailbox, it fails.

I think there might be an issue with rebinding some pre-defined keys. Try with a different key, e.g., `bind index,pager O sidebar-open`.

**Comment by gahr** [comment]
I've opened #4456 to investigate why `<Enter>` can't be bound to anything else.
