### ISSUE TITLE
Can't bind <Enter> in the index

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#4456]
## NeoMutt Version

```
NeoMutt 20241114-78-c90a55
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: FreeBSD 14.1-RELEASE-p5 (amd64)
ncurses: ncurses 6.2.20210220 (compiled with 6.2.20210220)
libiconv: 1.17
OpenSSL: OpenSSL 3.0.13 30 Jan 2024
PCRE2: 10.43 2024-02-16
storage: lmdb
compression: zlib, zstd

Configure options: CC=clang19 CXX=clang++19 --disable-nls --pgp --disable-idn2 --fmemopen --disable-gpgme --lmdb --ssl --pcre2 --with-ssl=/usr/local --with-ncurses=/usr --zlib --zstd --disable-autocrypt --disable-doc --compile-commands

Compilation CFLAGS: -std=c11 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/local/include -DNCURSES_WIDECHAR -I/usr/include -I/usr/local/include -I/usr/local/include -MJ$(@:.o=.o.json) -O2

Compile options:
  -autocrypt +fcntl -flock +fmemopen +futimens +getaddrinfo -gnutls -gpgme 
  -gsasl -gss +hcache -homespool -idn -inotify -locales_hack -lua -nls -notmuch 
  +openssl +pcre2 +pgp -sasl +smime -sqlite +truecolor 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Expected Behaviour

I would expect to be able to bind `<Enter>` to any function of my choice.

## Actual Behaviour

`<Enter>` stays bound to `select-entry`.

If NeoMutt crashed, did your OS create a 'coredump' file?

## Steps to Reproduce

`bind index,pager <Enter> quit`

## How often does this happen?

- Always

## When did it start to happen?

It was noticed while investigating #4455

**Comment by flatcap** [comment]
I checked the order of the function dispatchers and that seems ok -- the Index has priority.

https://github.com/neomutt/neomutt/blob/e5ca674623883752ecdac7bf79b4543974eef308/index/dlg_index.c#L1371-L1382

Then I tried unbinding and binding both `<enter>` and `<return>`, and it worked.

```
unbind generic <enter>
unbind generic <return>
bind   index   <enter>  next-entry 
bind   index   <return> next-entry
```

For my OS/Distro/Ncurses version, I only needed the last line.

**Notes**:

- <kbd>\<Ctrl-J\></kbd> acts as `<display-message>`
- <kbd>\<Ctrl-M\></kbd> acts as `<next-entry>`

**Comment by gahr** [comment]
I confirm that my keyboard (or whatever that is between the keyboard, the macOS host, the sshwifty session, the shell on the VPS, tmux, NeoMutt) is sending `Enter` instead of `Return`. Thanks for checking!

**Comment by flatcap** [comment]
Of course, it's only just occurred to me... :-)
We should have run
```
:exec what-key
```

```
Char = <Return>, Octal = 15, Decimal = 13
```

**Comment by gahr** [comment]
`Char = <Return>, Octal = 15, Decimal = 13`
