### ISSUE TITLE
Automatically listing ~/Mail content in the sidebar?

### ISSUE THREAD

**Issue by ckhung** [neomutt/neomutt#4457]
As the title says, I would like neomutt to list all the subdirectories in ~/Mail in my sidebar. I cannot find a clear description of what neomutt does about ~/Mail in https://neomutt.org/guide/ . I have found blog posts, etc. and learned that I can put the "mailboxes" command in ~/.muttrc and manually list all subdirectories, each prefixed with "+". This works fine. I also tried: ```mailboxes ` ls ~/Mail | sed 's/^/+/' ` ``` but it only shows the single file mentioned in ```set spool_file = ...``` . BTW, each subdirectory in my ~/Mail is actually a symbolic link to a utf7 encoded Maildir subdirectory created by mbsync/isync, but this should not matter, right?

Also, how can I contribute to the guide? I would like to add clarifications that would help readers avoid confusions or misplaced expectations like #4455. (I am a computer teacher and a free-software-tutorial type blogger.)

**Comment by gahr** [comment]
> As the title says, I would like neomutt to list all the subdirectories in ~/Mail in my sidebar.

For imap we have a similar thing, i.e., `imap_check_subscribed`. For Maildir I don't know, usually people tend to want to specify what to see, and in which order. Also, does ~/Mail usually contain Maildir directories?

> I also tried: mailboxes ` ls ~/Mail | sed 's/^/+/' ` but it only shows the single file mentioned in set spool_file = ... 

I'd need to see your config and the contents of ~/Mail to try and guess what's wrong.

> Also, how can I contribute to the guide?

Thanks for the offer! We need more people documenting and writing tutorials! The source for the [guide](https://neomutt.org/guide/) is in [docs/manual.xml.head](https://github.com/neomutt/neomutt/blob/main/docs/manual.xml.head), in a very friendly DocBook/XML format :)

**Comment by flatcap** [comment]
> list all the subdirectories in ~/Mail in my sidebar

Here's minimal example using \`backticks\` to execute `find` (GNU version).

```
set sidebar_folder_indent = yes
set sidebar_short_path    = yes
set sidebar_visible       = yes
set folder                = "~/mail"

mailboxes `find ~/mail -name cur -printf "\"%h\"\n" | sort | paste -s`
```

> Also, how can I contribute to the guide?

Might I also suggest the [Translations](https://neomutt.org/translate), which have fallen behind a little.
(No pressure, just if you think it'd be a good use of your time :-)

Thanks!

**Comment by ckhung** [comment]
@flatcap sure, I can help with zh_TW (Chinese, traditional). How do I begin?

Now if you would please bear with me for a more detailed description of my usage scenario. My university is moving away from zimbra to MS outlook / office 365. Having investigated the cumbersome steps of exporting all mails from outlook, which will become a hefty "barrier of exit", I decided to accumulate all mails at my own linux server as they arrive in the first place. Using mbsync/isync (creating local maildir) + neomutt seems to be the recommended way.

I used to use pine last century and felt comfortable with its fluent navigation:  arrow keys to choose a mailbox, enter key to open the chosen mailbox and also open a message, arrow keys again to choose a message, left arrow to exit a message and also to exit a mailbox, returning to the index of all mailboxes, including INBOX AND other mailboxes that do not receive mails directly from outside. I wish to do this, maybe with a few more keystrokes, in neomutt.

As I write I suddenly realize that maybe I need to change my mental model with maildir? Mails are now individually scattered and then maybe organized by mu by overlapping tags/keys instead of being partitioned into mailboxes, and therefore only mailboxes that serve as INBOXes for different mail addresses are more relevant? Is this the way you use neomutt? Do you move read mails to separate mailboxes and visit these from time to time?

Here is my current version of ~/.muttrc:
```
set sidebar_format = "%B%<F? [%F]>%* %<N?%N/>%S"
set mail_check_stats

bind index,pager <Tab> sidebar-toggle-visible
bind index,pager \CP sidebar-prev
bind index,pager \CN sidebar-next
bind index,pager \CO sidebar-open

mailboxes ` ls ~/Mail | sed 's/^/+/' `
set spool_file = +0-INBOX
```

Thank you for your help and patience.

**Comment by ossilator** [comment]
i achieved a quite pine-like navigation using this setup:

```
bind pager <left> exit
bind pager <right> view-attachments
bind pager <up> previous-line
bind pager <down> next-line
bind pager p previous-entry
bind pager n next-entry
bind pager q quit

macro index <left> c?
bind index <right> display-message
bind index <up> previous-entry
bind index <down> next-entry
bind index x sync-mailbox
bind index ' ' next-page

bind generic <left> exit
bind generic <right> select-entry
macro generic q "<exit>q"
```

see also https://gitlab.com/muttmua/trac-tickets/-/blob/master/tickets/open/1078-pinelike_arrow_navigation.txt

**Comment by flatcap** [comment]
> sure, I can help with zh_TW (Chinese, traditional). How do I begin?

Email on its way!

> Do you move read mails to separate mailboxes and visit these from time to time?

Yes, that's how I do it, but...

> Mails are now individually scattered and then maybe organized by mu by overlapping tags/keys

this is how the cool kids do it :-)
Notmuch, like mu, is an email indexer, labeller, searcher and it's built into NeoMutt.

You can create fixed virtual folders in config, e.g. `mailboxes "notmuch://?query=neomutt"`

or dynamically search with the function `<vfolder-from-query>`

**Comment by ckhung** [comment]
Thank you all. I will use @ossilator 's key binding for now and study notmuch or mu later. Will also do zh_TW translation little by little.
