### ISSUE TITLE
display filter acting on headers has strange side effect

### ISSUE THREAD

**Issue by nobrowser** [neomutt/neomutt#4459]
## NeoMutt Version

```
NeoMutt 20241114-124-aed421
Copyright (C) 2015-2024 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.10.2-x86_64-linode165 (x86_64)
ncurses: ncurses 6.4.20221231 (compiled with 6.4.20221231)
libidn2: 2.3.3 (compiled with 2.3.3)
PCRE2: 10.42 2022-12-11
storage: lmdb
compression: lz4

Configure options: --prefix=/usr/local --disable-doc --disable-pgp --disable-smime --lmdb --pcre2 --lz4

Compilation CFLAGS: -std=c11 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -DNCURSES_WIDECHAR -I/usr/local/include -O2

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme
  -gsasl -gss +hcache -homespool +idn +inotify -locales_hack -lua +nls -notmuch
  -openssl +pcre2 -pgp -sasl -smime -sqlite +truecolor

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

## Expected Behaviour

I am trying to set up a `display-filter` which adds a (pseudo-)header. It's supposed to help with the now ancient problem of cleaning the Subject from junk inserted by "helpful" mailing list ops. Namely, I want to leave the exisiting Subject line as it is, but insert an additional `X-Neat-Subject:` header with the junk removed, if it's easy to do; I plan to then colorize this new pseudo-header.

My testing of the filter via `cat` on freestanding message files shows that it works exactly as designed. But ...

## Actual Behaviour

When viewing most (but not all) messages in neomutt internal pager, the blank line separating headers and body gets omitted, with the side effect that the first paragraph of the body is colorized the same as the headers are. This happens only if "weeding" is in effect; when I toggle weeding off with the `h` key everything looks good (but too many headers of course).

If this happens for a particular message seems to depend somehow on the MIME structure, in particular, plain, non-MIME messages seem to work.

## Steps to Reproduce

View the messages below with `display_filter` set to `clean-subject`, also linked below.

Scripts: https://gist.github.com/nobrowser/7f408add4427376cccd33e69667d7519

Messages: https://gist.github.com/nobrowser/a765ed4821741852e2a74dde2a18a0b1

## How often does this happen?

- Sometimes

- On a particular email

## When did it start to happen?

- When I changed my config

Easy, adding `display_filter`. This is my first time doing so, I can't say how long this problem has existed.

## Extra Info

* Operating System and its version
devuan "daedalus"

* Were you using multiple copies of NeoMutt at once?
no

* Were you using 'screen' or 'tmux'?
tmux locally on laptop, sshing to a server with neomutt

* Is your email local (maildir) or remote (IMAP)?
local

**Comment by gahr** [comment]
I havent't started investigating yet, but wouldn't [subjectrx](https://neomutt.org/guide/advancedusage.html#display-munging) be useful to you?

**Comment by nobrowser** [comment]
@gahr : 

> [subjectrx]

Indeed, thank you. I have a sneaking suspicion that the problem has nothing to do with Subject and would occur with any display filter at all, so you may still go ahead with your investigation, though :-)

-- 
Ian

**Comment by gahr** [comment]
> I have a sneaking suspicion that the problem has nothing to do with Subject and would occur with any display filter at all

I have a sneaking suspicion that you haven't debugged your script. Apply this diff, and see for yourself how /tmp/filtered.txt is missing an empty line in the broken cases. Then `set display_filter=less` and see how NeoMutt sends all lines correctly.

```diff
--- clean-subject.py.orig       2024-12-01 20:39:32.923745000 +0000
+++ clean-subject.py    2024-12-01 20:41:46.881660000 +0000
@@ -4,10 +4,16 @@
 import re
 from email.header import decode_header
 
+files = []
+
+def my_write(what):
+    for f in files:
+        f.write(what)
+
 def pass_through():
     while line := sys.stdin.readline():
-        sys.stdout.write(line)
-    sys.stdout.write("\n")
+        my_write(line)
+    my_write("\n")
     sys.exit(0)
 
 def gen_multiline():
@@ -29,14 +35,16 @@
 JUNK_PAT = r"(?i:^((re|aw|sv):|\[[- a-z0-9]+\]) *)"
         
 def main():
+    f = open("/tmp/filtered.txt", "w")
+    files.extend([sys.stdout, f])
     junk_re = re.compile(JUNK_PAT)
     for line in gen_multiline():
         # check for end of headers
         if len(line) <= 1:
-            sys.stdout.write(line)
+            my_write(line)
             pass_through()
         # echo back anything
-        sys.stdout.write(line)
+        my_write(line)
         # if not subject header, keep looking
         if not line.lower().startswith("subject:"):
             continue
@@ -50,7 +58,7 @@
         while m := junk_re.match(raw_subject):
             raw_subject = raw_subject[m.end(0):]
         # output neat header and the rest
-        sys.stdout.write(f"X-Neat-Subject: {raw_subject}\n")
+        my_write(f"X-Neat-Subject: {raw_subject}\n")
         pass_through()
 
 if  __name__ == "__main__":
```

**Comment by nobrowser** [comment]
As I said, I have run it with `cat message | script` in all cases ... but never mind, I'm set with other ways (including subejctrx, for which thanks again), and this is too fragile anyway.

-- 
Ian

**Comment by gahr** [comment]
I'm sorry, what do you mean? Is there anything wrong in my analysis you would like to point out?

**Comment by gahr** [comment]
> I tested my filter script by catting a message file into it and observing the output.

NeoMutt doesn't `display_filter` the original message, but - as you noticed - it applies weeding and ignore/unignore. In particular, headers might be re-ordered. Hint: change your bad email not to have Subject as the last header, or change your good email to have Subject as the last header. Your script messes things up when it adds the cleaned up subject as the last header.

HTH
