### ISSUE TITLE
Thread tree doesn't draw until cursor navigates through that email

### ISSUE THREAD

**Issue by ElDeveloper** [neomutt/neomutt#446]
* **bug reports**

    * Expected behavior: the thread tree should always be visible.
    * Actual behavior: a thread will be grouped together, but the tree won't show on screen, only a tiny piece for the email at the top of the thread.
    * Steps to reproduce: This happens sporadically and not with every thread.
    * Used program versions: NeoMutt 20170225-6-dc9f31 (1.8.0)
    * Operating System and its version: macOS Sierra 10.12.13.

I was able to capture this behavior in a gif, notice how at first only the email at the top shows an arrow, but as soon as I move to the next email the thread tree is drawn. When this happened, I was in the pager viewing the email at the top.

![neomutt](https://cloud.githubusercontent.com/assets/375307/23470361/0759a652-fe5b-11e6-9c6d-4259c7f92997.gif)

edit: Note, I just saw this again, and I noticed that you have to be in the pager and move to the next email to force the tree to be redrawn.

**Comment by P-EB** [comment]
Do you remember some context that might be useful when this bug occured?

**Comment by ElDeveloper** [comment]
I have seen this happen a couple of times, but I haven't figured out what is common between the occurrences. Sometimes I am in the pager when I notice, sometimes I am in the index when I notice. Just in case, these are my compilation flags:

```
NeoMutt 20170225-6-dc9f31 (1.8.0)
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.

System: Darwin 16.4.0 (x86_64)
hcache backends: kyotocabinet

Compiler:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Configure options: '--with-ssl' '--enable-pop' '--enable-imap' '--enable-smtp' '--with-sasl' '--enable-hcache' '--prefix=/usr/local/' '--with-kyotocabinet' 'LDFLAGS=-L/usr/local/lib/ -L/usr/local/Cellar/openssl/1.0.2d_1/lib/' 'CPPFLAGS=-I/usr/local/include/ -I /usr/local/Cellar/openssl/1.0.2d_1/include/'

Compilation CFLAGS: -Wall -pedantic -Wno-long-long -g -O2 -fno-delete-null-pointer-checks

Compile options:
+CRYPT_BACKEND_CLASSIC_PGP +CRYPT_BACKEND_CLASSIC_SMIME -CRYPT_BACKEND_GPGME 
-DEBUG +DL_STANDALONE +ENABLE_NLS -EXACT_ADDRESS -HOMESPOOL -LOCALES_HACK 
-SUN_ATTACHMENT +HAVE_BKGDSET +HAVE_COLOR +HAVE_CURS_SET -HAVE_FUTIMENS 
+HAVE_GETADDRINFO +HAVE_GETSID +HAVE_ICONV +HAVE_LANGINFO_CODESET 
+HAVE_LANGINFO_YESEXPR -HAVE_LIBIDN +HAVE_META +HAVE_REGCOMP +HAVE_RESIZETERM 
+HAVE_START_COLOR +HAVE_TYPEAHEAD +HAVE_WC_FUNCS +ICONV_NONTRANS 
-USE_COMPRESSED +USE_DOTLOCK +USE_FCNTL -USE_FLOCK -USE_FMEMOPEN -USE_GNU_REGEX 
-USE_GSS +USE_HCACHE +USE_IMAP -USE_NOTMUCH -USE_NNTP +USE_POP +USE_SASL 
+USE_SETGID -USE_SIDEBAR +USE_SMTP -USE_SSL_GNUTLS +USE_SSL_OPENSSL 
-DOMAIN
-MIXMASTER
-ISPELL
SENDMAIL="/usr/sbin/sendmail"
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/mutt"
SYSCONFDIR="/usr/local/etc"
EXECSHELL="/bin/sh"

patch-attach-headers-color-neomutt
patch-compose-to-sender-neomutt
patch-compress-neomutt
patch-cond-date-neomutt
patch-encrypt-to-self-neomutt
patch-fmemopen-neomutt
patch-forgotten-attachments-neomutt
patch-forwref-neomutt
patch-ifdef-neomutt
patch-index-color-neomutt
patch-initials-neomutt
patch-keywords-neomutt
patch-kyoto-neomutt
patch-limit-current-thread-neomutt
patch-lmdb-neomutt
patch-multiple-fcc-neomutt
patch-nested-if-neomutt
patch-new-mail-neomutt
patch-nntp-neomutt
patch-notmuch-neomutt
patch-progress-neomutt
patch-quasi-delete-neomutt
patch-reply-with-xorig-neomutt
patch-sensible-browser-neomutt
patch-sidebar-neomutt
patch-skip-quoted-neomutt
patch-status-color-neomutt
patch-timeout-neomutt
patch-tls-sni-neomutt
patch-trash-neomutt

To learn more about NeoMutt, visit: http://www.neomutt.org/
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

**Comment by nobrowser** [comment]
@ElDeveloper , re your edit to the top of this issue.  Does that mean that you had just moved in pager mode from a message in another thread to the root message of a new thread?

**Comment by ElDeveloper** [comment]
@nobrowser that's not quite what I meant. I was browsing my emails through the index (without reading any one email), then noticed the thread that's shown in the gif, opened the email at the top (Richard's email, received at 8:26), moved to the next email (without leaving the pager) and then the tree was redrawn. I hope this description helps.

**Comment by flatcap** [comment]
Upstream have made some changes to the index redrawing.
Have you seen the problem in a recent version of NeoMutt?

**Comment by ElDeveloper** [comment]
From some testing that I have just done right now, I can no longer get
to reproduce this. If I see this again, I'll reopen the issue.

**Comment by ElDeveloper** [comment]
I just saw this happen again, though I'm not sure under what conditions.
