### ISSUE TITLE
corrupted attachment file when saving with overwrite

### ISSUE THREAD

**Issue by lucilanga** [neomutt/neomutt#4469]
Latest master, save a 10k size attachment under some name, say file.txt, overwrite that file with a 100k attachment,  everything should be  fine so far. Overwrite again with the 10k attachment to see the resulting file being a 100k file, containing first 10k correctly written but the rest are leftovers from the second overwrite, when instead, the final file should have been truncated before the write. There are no issues with append behaviour.

This is related to ceee73f7 when we replaced `fopen()` with `mutt_file_fopen()`.
The problem is `mutt_file_fopen(_full)` has only `O_CREAT | O_EXCL | O_NOFOLLOW` for what was fopen with `mode = "w"` before.

I also found 865dfe0a where `O_TRUNC` was dropped, I'm not entirey sure why but possibly causing the reverse behaviour or something similar eg. truncating when it should have not.

We do have `O_CREAT` combined with `O_EXCL` which should fail on existing file but it does not because of that NFS test in `safe_open/rename()`

Unfortunately I do not remember when this was working fine, and I believe it's easier to spot this with text files than with binary files. Eg a pdf file will cope just fine with extra garbage, I believe images will work fine too.

Adding `O_TRUNC` to the flags (or replacing `mutt_file_fopen()` with `fopen()` in `save_attachment_open()` ) works fine for this specific case.

**Comment by flatcap** [comment]
Damn!
Thanks for the detailed bug report.

What I'd like to do is analyse the 169 calls to `fopen()`.
But, I'd like to get a release out next week.
So I've created a quick hack for `save_attachment_open()`

Please can you give branch [[flatcap/fopen]](https://github.com/neomutt/neomutt/tree/flatcap/fopen) a try.

Thanks!

---

> we replaced `fopen()` with `mutt_file_fopen()`

The plan was centralise all the file opens and closes.
`mutt_file_fopen()` and `mutt_file_fclose()` are macros that record the `FILE`, `LINE` and `FUNCTION` of the **caller**.

e.g.

```
[2024-12-06 22:26:01]<2> rfc1524_mailcap_parse() File opened (fd=7): /home/mutt/.mutt/mailcap-dev
[2024-12-06 22:26:01]<2> rfc1524_mailcap_parse() File closed (fd=7)
```

> 865dfe0 where O_TRUNC was dropped ... possibly causing the reverse behaviour

IIRC, it broke the history

---

![image](https://github.com/user-attachments/assets/3e74d4eb-740e-4e01-9e4d-ff4e6d3e31c8)

Throughout NeoMutt, we use all the possible `mode`s for `fopen()`:
- `r`, `r+`
- `w`, `w+`
- `a`, `a+`

In `mutt_file_fopen_full()`, `mode`s of `w` and `w+` are diverted to `fdopen()`,
whereas `r`, `r+`, `a` and `a+` are handled by `fopen()` -- even though the latter two are also writing modes.

---

> We do have `O_CREAT` combined with `O_EXCL` which should fail on existing file
> but it does not because of that NFS test in `safe_open/rename()`

This complexity dates back to `safe_fopen()` in the initial commit **twenty-seven** years ago.

While we need to be cautious about creating and updating files,
I can't seriously believe we need to jump through so many hoops.

NeoMutt isn't a high-performance real-time app competing for resources.
Even if all of its files are on NFS, there's unlikely to be much contention.
