### ISSUE TITLE
UI: Page down key in pager can jump to next message

### ISSUE THREAD

**Issue by alejandro-colomar** [neomutt/neomutt#4476]
Hi!

This is behavior inherited from mutt(1), but which I find terribly annoying:

When reading a message (in the pager), pressing `<PageUp>` repeatedly eventually brings you to the begining of the message and stops there (nice).
However, pressing `<PageDown>` will eventually jump into the next message, without notice.  (This is unlike enter key, which cannot go beyond the bottom of the message.)

I would like it to stay at the end of the message, and consider it a hard boundary.  If I wanted to go to the next message, I would press the down arrow myself.  I really prefer going back to the index, seeing where I am and where I'll go, and then going into the message myself; otherwise, I can lose track of stuff.  Usually, when I accidentally jump into a new message by doing down, I `^C` out of neomutt(1) without saving and start again, to not mark as unread messages which I didn't want to read.

Would you mind a breaking change to fix this problem?

**Comment by flatcap** [comment]
Does `set pager_stop = yes` help?

**Comment by alejandro-colomar** [comment]
> Does `set pager_stop = yes` help?

Yes it does.  Thanks!  (I didn't know about that knob.)

I wonder if that should be the default behavior, but well, I don't mind too much now that I know I can tweak it.

**Comment by flatcap** [comment]
> I wonder if that should be the default behavior

Possibly, but changing the default without irritating lots of users could be tricky :-)

**Comment by alejandro-colomar** [comment]
> > I wonder if that should be the default behavior
> 
> Possibly, but changing the default without irritating lots of users could be tricky :-)

Indeed.  :-)
