### ISSUE TITLE
Compose Preview memory leak

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#4478]
We seem to be leaking all the lines of the preview text.

<details>
<summary>vim quicklist (from ASAN)</summary>

```
main.c:1429:               main
index/dlg_index.c:1370:    dlg_index
index/functions.c:3280:    index_function_dispatcher
index/functions.c:2193:    op_resend
send/send.c:1584:          mutt_resend_message
send/send.c:2633:          mutt_send_message
compose/dlg_compose.c:441: dlg_compose
gui/mutt_window.c:643:     window_redraw
gui/mutt_window.c:605:     window_repaint
gui/mutt_window.c:599:     window_repaint
compose/preview.c:314:     preview_repaint
compose/preview.c:169:     draw_preview
mutt/file.c:819:           mutt_file_read_line
```

</details>

The culprit seems to be:

https://github.com/neomutt/neomutt/blob/7b49f7c3fff84aef847a45e862483966e7df0776/compose/preview.c#L170

I think we should be passing in `line` so the memory gets reused.
(we'll still need to free it at the end of this function)

**Comment by roccoblues** [comment]
You're totally right, sorry. I'm surprised that didn't show up in our CI ASAN runs.
