### ISSUE TITLE
xstlproc hangs long when building (failed to load external entity)

### ISSUE THREAD

**Issue by Knusper** [neomutt/neomutt#450]
During a build, which I do with 

    ./configure --prefix=${HOME}/local/ \
            --enable-sidebar  --enable-hcache --enable-smtp \
            --with-curses=/usr --with-ssl=/usr --with-gnutls=/usr --with-sasl=/usr \
            --with-tokyocabinet && make

The build process seems to stall for a long time on some `xstlproc` calls:

    http://docbook.sourceforge.net/release/xsl/current/common/l10n.xml:2: warning: failed to load   external entity "http://docbook.sourceforge.net/release/xsl/current/common/l10n.dtd"
<!DOCTYPE l:i18n SYSTEM "l10n.dtd">

I don't know what is happening there, since the URL does  resolve.  But, anyway, the build process should also be fast on machines that have, for various reasons, no access to some http resources.

**Comment by flatcap** [comment]
`xsltproc` uses the DTDs (Document type definitions) to validate the DocBook XML.

By default, the `Makefile` runs `xsltproc` with the `--nonet` argument, which means you'll need a local copy of the DTDs.  On Fedora, the package is called "docbook-dtds".

Without the `--nonet` arg, `xlstproc` would download the definitive DTDs as specified in the XML header.

**Comment by Knusper** [comment]
Although it seems a bit ugly,  using `xstlproc` with the `--path` argument while shipping the required DTDs with neomutt could be a solution?

**Comment by flatcap** [comment]
As the DTDs are packaged by the distros, I'd rather just list them as a build requirement.

**Comment by toogley** [comment]
@flatcap but then i think we should at least improve the makefile someday so that its clear that it doesn't actually download `http://docbook.sourceforge.net/release/xsl/current/common/l10n.xml`

**Comment by renlord** [comment]
FWIW, I tried compiling on Archlinux today and it doesnt look like it was able to resolve the DTD, I had to untoggle --nonet manually in the Makefile so it compiles.
