### ISSUE TITLE
SASL passwords seemingly cropped to 127 characters

### ISSUE THREAD

**Issue by guyzmo** [neomutt/neomutt#454]
This issue is just as a reflection of the issue on upstream, as the OP is using neomutt (from debian unstable):

 * https://dev.mutt.org/trac/ticket/3921

cc/ @ivucica

**Comment by P-EB** [comment]
The whole thing resides in ACCOUNT struct having a 128 char (including \0) long string for imap_pass.

We probably could push it to a bigger length.

**Comment by gahr** [comment]
@guyzmo Could you please just merge in [f0e3b28](https://dev.mutt.org/trac/changeset/f0e3b28750656f7b97e509e70af754c16e44daee)? Thanks!

**Comment by flatcap** [comment]
@gahr I'll pull the change from [mutt/default] before the release.
