### ISSUE TITLE
Update package in ubuntu repository

### ISSUE THREAD

**Issue by Kinmarui** [neomutt/neomutt#458]
Hi,

are there any chances that you update package in ubuntu repository? I've installed mutt but as I can see I got version `1.6.2-neo (2016-08-21)` and as I understand there were lots of improvements in 1.8 version 

I have tried to build neomutt myself following [1] and succeed but when I run application polish characters are not displayed properly which worked fine for package installed from repository. 

Also it complains that it doesn't know some of variables which worked for 1.6 version do you have available `.muttrc` file for new version? Variable for which it reports problem `ssl_starttls, ssl_force_tls, imap_user, imap_pass, header_cache, message_cachedir, certificate_file, smtp_url, imap_keepalive`

[1]: https://www.neomutt.org/dev/build

**Comment by flatcap** [comment]
> are there any chances that you update package in ubuntu repository?

Debian have the latest version of neomutt in testing.
Sorry, I don't know how Ubuntu fits in.

> I have tried to build neomutt myself
> when I run application polish characters are not displayed properly

Ah, there are two versions of the curses library: ncurses and ncurses**w**.
Check that you have the 'w' (wide characters) version installed.

**Comment by Kinmarui** [comment]
Thanks for such quick replay.

I changed ncurses-dev to libncursesw5-dev which is apparently proper version on ubuntu [ncursesw] and encoding works correctly.

About fact that neomutt doesn't recognize some variables. Did I missed muttrc file somewhere which shows simple configuration with 1 mailbox. Or maybe there is page on migrating mutt config to neomutt? Or I missed some flags during compilation and don't have all features? Or do I need to go through [configuration] page and lookup everything? 

[ncursesw]: http://stackoverflow.com/questions/26186824/how-to-install-the-ncursesw-development-libraries
[configuration]: https://www.neomutt.org/guide/configuration.htm

**Comment by flatcap** [comment]
> neomutt doesn't recognize some variables

NeoMutt has only added things to Mutt (though there isn't a guide to the "Neo" stuff, yet).

> Or do I need to go through configuration page and lookup everything?

Yes.  That "configuration guide" is little more than notes, so far.
It's hard to encourage people to write docs :-(

This is from my build script (it should cover all your missing options):

	--enable-pop
	--enable-imap
	--enable-smtp
	--with-tokyocabinet
	--enable-gpgme
	--enable-sidebar
	--enable-notmuch
	--enable-compressed
	--enable-debug
	--with-gnutls

**Comment by Kinmarui** [comment]
sorry but this is my first time building apps using make. where should I add those options?

**Comment by flatcap** [comment]
```
autoreconf -i
./configure [LOTS OF OPTIONS]
make
```

**Comment by Kinmarui** [comment]
not sure if you got notification that I edited previous comment

I added those flags to ./configure command but got
`configure: error: *** GPGME not found ***`
does it matter which version I will install or can I get i.e. python-gpgme

**Comment by flatcap** [comment]
I don't know what the gpgme package is called in debian / ubuntu (most likely gpgme-dev).
You can live without it.

**Comment by Kinmarui** [comment]
isn't it required to be able to use gpg in configuration instead of plaintext password?

**Comment by Kinmarui** [comment]
I resolved problems with dependency but now when I run make I got
```
gcc -DPKGDATADIR=\"/usr/local/share/mutt\" -DSYSCONFDIR=\"/usr/local/etc\" -DBINDIR=\"/usr/local/bin\" -DMUTTLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H=1 -I.  -I. -I. -I./imap  -Iintl -I./intl  -Wall -pedantic -Wno-long-long -g -O2 -fno-delete-null-pointer-checks -MT curs_main.o -MD -MP -MF .deps/curs_main.Tpo -c -o curs_main.o curs_main.c
curs_main.c: In function ‘mutt_index_menu’:
curs_main.c:1767:12: error: ‘OP_MAIN_ENTIRE_THREAD’ undeclared (first use in this function)
       case OP_MAIN_ENTIRE_THREAD:
            ^~~~~~~~~~~~~~~~~~~~~
curs_main.c:1767:12: note: each undeclared identifier is reported only once for each function it appears in
curs_main.c:1801:12: error: ‘OP_MAIN_MODIFY_LABELS’ undeclared (first use in this function)
       case OP_MAIN_MODIFY_LABELS:
            ^~~~~~~~~~~~~~~~~~~~~
curs_main.c:1802:12: error: ‘OP_MAIN_MODIFY_LABELS_THEN_HIDE’ undeclared (first use in this function)
       case OP_MAIN_MODIFY_LABELS_THEN_HIDE:
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
curs_main.c:1876:12: error: ‘OP_MAIN_VFOLDER_FROM_QUERY’ undeclared (first use in this function)
       case OP_MAIN_VFOLDER_FROM_QUERY:
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
curs_main.c:1889:12: error: ‘OP_MAIN_WINDOWED_VFOLDER_BACKWARD’ undeclared (first use in this function)
       case OP_MAIN_WINDOWED_VFOLDER_BACKWARD:
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
curs_main.c:1909:12: error: ‘OP_MAIN_WINDOWED_VFOLDER_FORWARD’ undeclared (first use in this function)
       case OP_MAIN_WINDOWED_VFOLDER_FORWARD:
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
curs_main.c:1931:12: error: ‘OP_MAIN_CHANGE_VFOLDER’ undeclared (first use in this function)
       case OP_MAIN_CHANGE_VFOLDER:
            ^~~~~~~~~~~~~~~~~~~~~~
curs_main.c:1935:12: error: ‘OP_SIDEBAR_OPEN’ undeclared (first use in this function)
       case OP_SIDEBAR_OPEN:
            ^~~~~~~~~~~~~~~
curs_main.c:3195:12: error: ‘OP_SIDEBAR_NEXT’ undeclared (first use in this function)
       case OP_SIDEBAR_NEXT:
            ^~~~~~~~~~~~~~~
curs_main.c:3196:12: error: ‘OP_SIDEBAR_NEXT_NEW’ undeclared (first use in this function)
       case OP_SIDEBAR_NEXT_NEW:
            ^~~~~~~~~~~~~~~~~~~
curs_main.c:3197:12: error: ‘OP_SIDEBAR_PAGE_DOWN’ undeclared (first use in this function)
       case OP_SIDEBAR_PAGE_DOWN:
            ^~~~~~~~~~~~~~~~~~~~
curs_main.c:3198:12: error: ‘OP_SIDEBAR_PAGE_UP’ undeclared (first use in this function)
       case OP_SIDEBAR_PAGE_UP:
            ^~~~~~~~~~~~~~~~~~
curs_main.c:3199:12: error: ‘OP_SIDEBAR_PREV’ undeclared (first use in this function)
       case OP_SIDEBAR_PREV:
            ^~~~~~~~~~~~~~~
curs_main.c:3200:12: error: ‘OP_SIDEBAR_PREV_NEW’ undeclared (first use in this function)
       case OP_SIDEBAR_PREV_NEW:
            ^~~~~~~~~~~~~~~~~~~
curs_main.c:3204:12: error: ‘OP_SIDEBAR_TOGGLE_VISIBLE’ undeclared (first use in this function)
       case OP_SIDEBAR_TOGGLE_VISIBLE:
            ^~~~~~~~~~~~~~~~~~~~~~~~~
curs_main.c:3210:12: error: ‘OP_SIDEBAR_TOGGLE_VIRTUAL’ undeclared (first use in this function)
       case OP_SIDEBAR_TOGGLE_VIRTUAL:
            ^~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:850: polecenia dla obiektu 'curs_main.o' nie powiodły się
```

**Comment by flatcap** [comment]
> isn't it required to be able to use gpg in configuration

There are two ways to use gpg.
- (preferred): gpgme libraries which mutt calls
- (basic): mutt runs the command-line gpg commands and parses the output

The build errors come from a unclean source directory.
`make clean` sometimes doesn't do a good enough job.
If you used git to download the source, you can use `git clean -xdf` (**NOTE**: this will clean out EVERYTHING but the source).

**Comment by Kinmarui** [comment]
After re downloading src it worked. but when I run it it shows me certificate for my mail provider (1 from 2) but when I accept it it says ~ "Warning: couldn't save certificate" and asks me for password (while still displaying first certificate info). When I enter password it says ~ "Login wasn't successful". If I reject first certificate it shows me second one.

I tried running it with sudo but no change. I've also double checked paths to folders for cache and certificates from my config file.

**Comment by toogley** [comment]
@Kinmarui if you compiled mutt with +DEBUG, you can run:

```
mutt -d 2 && cat  ~/.muttdebug0
```

**Comment by ysangkok** [comment]
Regarding Ubuntu, currently configure succeeds although CF_CURSES_LIBS is undefined, if libncursesw5-dev is not installed... It will failed with unresolved symbols at link-time.
