### ISSUE TITLE
List of maildirs with new mail not working

### ISSUE THREAD

**Issue by raphaelfournier** [neomutt/neomutt#46]
I use a mutt+offlineimap setup. With neomutt, when I press "." on the index, which is mapped to `buffy-list`, it does not yield any result, even if there _is_ new mail in other folders. There was no problem in mutt and mutt-kz.

I observed that in both situations : 
- incoming mail has been just fetched (I have not yet entered the folder)
- if I had previously entered the folder and closed neomutt (so that new mail could be considered as "seen" or "old").

Relevant part of my .muttrc:

```
mailboxes `find ~/Mail/RFS/* -maxdepth 0 -type d | grep -v "tmp\|new\|cur" |xargs`
mailboxes `find ~/Mail/CNAMnet/* -maxdepth 0 -type d | grep -v "tmp\|new\|cur\|Spam" |xargs`
```

Perhaps related to #19 ?

**Comment by flatcap** [comment]
@raphaelfournier 
Thanks for the bug report.  I'll start at the end:

> Perhaps related to #19 ?

Probably :-)

I'm putting together a release (due out tomorrow).
Hopefully this will fix your problem.  If not, I'll investigate.

**Comment by raphaelfournier** [comment]
As far as I can tell, it works for me now.

**Comment by flatcap** [comment]
Thanks.

**Comment by raphaelfournier** [comment]
I am reopening the issue, because I think observed a bugged behavior with a more recent version: `buffy-list` does not seem to respect the `mailboxes` directive. Typically, using the example above (cf my message from June 10th), I have in my muttrc:

``mailboxes `find ~/Mail/RFS/* -maxdepth 0 -type d | grep -v "tmp\|new\|cur\|Flux" |xargs` ``,

where Flux.* are some folders I'd like to exclude (they may receive new emails, but I don't want to be notified). `buffy-list` notifies me nonetheless when there are unread emails in Flux.* folders. 

Surprisingly, commenting the whole line does not change anything, while `buffy-list` should this time ignore mails in `~/Mail/RFS/INBOX`, which it does not.

Is there a new behavior or a caching feature for `buffy-list`?

**Comment by P-EB** [comment]
I don't think we changed anything directly, but maybe we did. Do you have some time to "bissect" the thing?

Cheers

**Comment by raphaelfournier** [comment]
I have little time this month but will have a bit more next month. I am willing to learn but I have never bissected a bug. Could you give me a standard procedure to follow to help you?

**Comment by flatcap** [comment]
hi @raphaelfournier I nearly posted something last night, but it was late and I was tired.
I've committed a fix to the index/pager code (a03fa19) which should sort out all the notifications
(and given it a lot of testing).

I now understand your problem better, but don't understand what could have happened.
The `mailboxes` command adds mailboxes to a list and the `<buffy-list>` command reads from that list.
If all your mailboxes are local there shouldn't have been a problem (IMAP can find its own list of mailboxes).

If you're happy compiling neomutt, please give it a try.
If not, don't worry, there'll be a new release in a week's time.

**Comment by toogley** [comment]
@raphaelfournier is this bug still relevant for you?

**Comment by raphaelfournier** [comment]
Oh sorry for leaving this opened. In December, I got a more recent version and the problem seems solved. 
Beware: it already happened last year that the problem solved by upgrading, and then reappeared (see messages above). I haven't bissected the problem.
