### ISSUE TITLE
Use external gettext

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#460]
* **feature requests**

    * Why do you not like the current state?

Mutt bundles an old implementation of the gettext library in the `intl` subdirectory. It is a pain to maintain and adds little value. I think it's reasonable to assume that anybody using Mutt with i18n has a gettext runtime installed.  

    * What would you like to see to change?

Get rid of the `intl` subdirectory and rely on the system's gettext.

**Comment by flatcap** [comment]
This commit "fixes" the build for me (see the log message :-)
If it's no good, delete it.

**Comment by guyzmo** [comment]
I do like the idea

**Comment by gahr** [comment]
Merged
