### ISSUE TITLE
PDF attachment given type of "text/plain"

### ISSUE THREAD

**Issue by dset0x** [neomutt/neomutt#461]
When attaching a PDF generated by libreoffice, neomutt 20170225-7-013f9d (1.8.0) assigns it a type of `
text/plain, quoted, utf-8`, while
```
$ file -ib foo.pdf
application/pdf; charset=binary
```

**Comment by dset0x** [comment]
Interestingly, `PDF document, version 1.3` are detected as `application/octet-stream, Encoding: base64`. This one was a `version 1.4`.

**Comment by gahr** [comment]
Uhm.. I don't seem to be able to reproduce with a sample PDF v1.4 file downloaded from here:
https://svn.apache.org/repos/asf/tika/trunk/tika-parsers/src/test/resources/test-documents/testPDF_Version.5.x.pdf

Do you also get text/plain if you attach this one?

**Comment by dset0x** [comment]
@gahr Yes, I also get text/plain with this one. Would you be able to point me to how neomutt resolves the type so that I can try and see what's happening?

**Comment by gahr** [comment]
It's [mutt_make_file_attach](https://github.com/neomutt/neomutt/blob/master/sendlib.c#L1358), which calls [mutt_lookup_mime_type](https://github.com/neomutt/neomutt/blob/master/sendlib.c#L939).

**Comment by dset0x** [comment]
Hm, this is a build I'm running from the sources and it tries to use `/usr/local/share/mutt/mime.types` which doesn't exist. Then the guesswork on the type takes over. Placing the file there fixes the issue.

This probably renders the bug invalid, so feel free to close. Thanks for the quick replies.

**Comment by gahr** [comment]
Oh, that would explain, yes. Thanks!

**Comment by dset0x** [comment]
However, isn't it something the user should be made aware of if that file is missing? Although it's my fault for running like this, I just sent two embarrassingly broken e-mails. On the other hand it's probably not the application's fault that a file it ships is not there.

**Comment by gahr** [comment]
Yup, a line in the logfile stating that no mime.types file could be found would be neat. Wanna open an issue (or better yet push request) for that?
