### ISSUE TITLE
Limit or search by alias

### ISSUE THREAD

**Issue by mingsu** [neomutt/neomutt#464]
Is there any method to **limit or search** mail items by **alias**. Can `notmuch` do this?

Because I can't remember the mail address, and lots of people didn't setup his name as the `real name`.

**Comment by guyzmo** [comment]
as far as I'm aware, there is no such thing (but don't take my word on it, but if you did not find an answer in the manual there you go…).

But you can use a tool such as notmuch to perform advanced searches in your mailbox, which won't help you look up a name by its alias, but you'll be able to find occurences in body or other headers. And if you tag your mail, then it'll be even more easier.

**Comment by mingsu** [comment]
Is it possible to integrate this to neomutt? I do think this is very useful and important.

Or use a `macro` to run a external command like bash script to find the **email address** via the **real name**, and pipe the address to `<limit>`? could it possible?
To me, I don't know how to write this macro, I tried this:

`macro index K "<limit> <shell -escape>echo EMAILADD<enter>" `

where`echo EMAILADD` is to present the external function to find email address, just for testing the macro.

**Comment by flatcap** [comment]
Sorry, this enhancement didn't attract someone to write some code.
This issue will now be closed, but listed on the [Closed Discussions](https://www.neomutt.org/dev/discussions) page.
