### ISSUE TITLE
autoconf says 'yes' when libraries are missing

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#465]
Example:
- `./configure --enable-lua`
- User has no lua libraries

Result:
`lua: yes`
`-USE_LUA`

`configure` is displaying the user's choice rather even when it's not possible.
`config.h` contains the right defines, the build succeeds, but without the requested library.

I think there are 8 possible test combinations:
- `--enable-X`, `--disable-X`, `--enable-everything`, X is unspecified
- User has X libs, User doesn't have X libs

**Comment by gahr** [comment]
This only happens if the check for X in configure.ac fails silently. This does *not* happen for gpgme, as the configure script fails if `--enable-gpgme` was given but gpgme wasn't found:

```
checking for gpgme-config... no                                                                                                                                 
checking for GPGME - version >= 1.0.0... no                                                                                                                     
configure: error: *** GPGME not found *** 
```

As far as I could experience, this issue is Lua-specific.

**Comment by flatcap** [comment]
Thanks.  Examples updated to lua - the one that was actually causing us the problems.

**Comment by flatcap** [comment]
All the combinations seem to work now.
