### ISSUE TITLE
Wish: more intelligent pasting

### ISSUE THREAD

**Issue by phmarek** [neomutt/neomutt#469]
It happens much too often that the mouse cursor is in the wrong window during pasting.

If some text gets sent to `mutt` it can have quite a lot of effects - pasting a link like `http://...` would switch the headers, tag two messages, and then ask whether to print the current message, for example.

Please use the `xterm` escape sequences (below) to switch the terminal to _bracketed paste mode_. Then `mutt` will receive two escape sequences as start and end delimiter, and can decide to ignore the paste -- this would be most of the time, although pasting a command in might make sense.

From `/usr/share/doc/xterm/ctlseqs.txt.gz`:
```
CSI ? Pm h
            Ps = 2 0 0 4  -> Set bracketed paste mode.
CSI ? Pm l
            Ps = 2 0 0 4  -> Reset bracketed paste mode.

Bracketed Paste Mode
When bracketed paste mode is set, pasted text is bracketed with control
sequences so that the program can differentiate pasted text from typed-
in text.  When bracketed paste mode is set, the program will receive:
   ESC [ 2 0 0 ~ ,
followed by the pasted text, followed by
   ESC [ 2 0 1 ~ .

```

**Comment by kdave** [comment]
Accidental pastes happened to me as well. The paste functionality is useful when the command line is active (paste address, message id, subject) but almost never otherwise. I'm not sure if the behaviour should be configurable,  would basically become to completely ignore or the above.

**Comment by guyzmo** [comment]
This is definitely a great idea.

II think this would make a great feature, and have no impact on expected behaviour of the tool… Who really pastes whole command chains blindly into mutt?

I think it's rather easy, though as with every behaviour change this should come with an option (sorry @d-k-c), and ultimately I think it should become the default when `$TERM` is set to `xterm`.

**Comment by phmarek** [comment]
> default when `$TERM` is set to `xterm`
No, that's a bad policy.
`mutt` might be within `konsole` (`xterm-256color`), behind `screen` or `tmux`, on a serial line (even `dumb`), etc.

Please don't do such guess-work.

BTW, these escape sequences are supported for `xterm` only; so I'd rather suggest to **default** to that behaviour if the terminal supports it. Yeah, right, this has the exact same outcome, but for the right reasons ;)

**Comment by guyzmo** [comment]
I meant `xterm.*` of course. I think tmux has a bracketed paste mode itself. For screen I'm not sure, for serial/dumb line, I don't think there's such thing, as bracketed mode is a special thing AFAICT.

If there's a termcap declaration for bracketed paste support, then that's *definitely* what should be supported. 😉

**Comment by flatcap** [comment]
Sorry, this enhancement didn't attract someone to write some code.
This issue will now be closed, but listed on the [Closed Discussions](https://www.neomutt.org/dev/discussions) page.
