### ISSUE TITLE
hcache error: Cannot allocate memory

### ISSUE THREAD

**Issue by viric** [neomutt/neomutt#473]
* Bug reports
    * Expected behavior
hcache should work
    * Actual behavior
hcache fails. It runs a mmap() call with 2GB. Strace lines:
open("/home/viric/.hcache", O_RDWR|O_CREAT, 0644) = 4
mmap2(NULL, 2147483648, PROT_READ, MAP_SHARED, 4, 0) = -1 ENOMEM (Cannot allocate memory)
The .hcache file I am using is 8KB big. Erasing this file creates it anew for 8KB and fails the same way.
    * Steps to reproduce
Use the hcache in a system with 1GB of RAM.
    * Used program versions
NeoMutt 20170128 (1.7.2)
    * Operating System and its version
NixOS 17.03 on Raspberry Pi 2

**Comment by viric** [comment]
The terminal has this text: `hcache_open_lmdb: mdb_env_open: Cannot allocate memoy`

**Comment by guyzmo** [comment]
is it actually crashing?

**Comment by viric** [comment]
It is not crashing.

**Comment by flatcap** [comment]
Hmm... It may be because LMDB is trying to `mmap()` more memory than exists.
If you're building your own neomutt, try changing: `hcache-lmdb.c` line 31:
from
```c
const size_t LMDB_DB_SIZE = 2147483648;
```
to
```c
const size_t LMDB_DB_SIZE = 536870912;
```

**Comment by gahr** [comment]
Perhaps I should make it configurable and use HeaderCachePageSize as gdbm does. Although the name would be a bit misleading in the case of lmdb, where the value is actually the max db size.

**Comment by gahr** [comment]
Or maybe a better approach would be to handle the failure and reduce the map size by >> 1 until it succeeds.

**Comment by gahr** [comment]
a0777aa should fix that. Unfortunately I cannot test it, as on my system mmap succeeds no matter what.

**Comment by gahr** [comment]
@viric please feel free to reopen if you get around to test my patch.
