### ISSUE TITLE
Make sure mutt_debug calls are \n-terminated

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#474]
Some mutt_debug calls in hcache-lmdb.c are not \n-terminated. Check other occurrences and fix them all (if any) in a sweeping commit.

**Comment by gahr** [comment]
I won't probably have time to take care of this for some time. Any takers?

**Comment by flatcap** [comment]
OK, I've got it.  I found 18 `mutt_debug()`s without `\n`.
There were a few more, but the parameter names implied that a `%s` might contain a `\n`.

For reference, I found them by:
- Unfold all source lines: `clang-format -i` with `ColumnLimit: 9999`
- Join strings in vim: `argdo %s/"\n\s\+"//e`
- Save to a file: `grep -Hn 'mutt_debug'`  (~700 matches)
- Filter in vim: `%s/\\"//g`  `:g/^[^"]\+"[^"]\+\\n"/d`  (~40 matches)
- Use the file as an error file in vim: `:cf %` to look through the remainder

I'll commit them shortly.

**Comment by flatcap** [comment]
Fixed in b1e2280
