### ISSUE TITLE
Unable to override nm_query_type in virtual mailbox

### ISSUE THREAD

**Issue by flokli** [neomutt/neomutt#484]
I set `nm_query_type` to `threads`, and defined some virtual mailboxes like this:

`notmuch://?query=tag:flokli and (tag:inbox or tag:new)`

The results are displayed in threads. When changing `nm_query_type` to `messages`, results are displayed in messages, so this works as expected.

The documentation mentions its also possible to override the query type per virtual folder, so something like ``notmuch://?type=messages&query=tag:flokli and (tag:inbox or tag:new)`` should always display results as messages, regardless of the `nm_query_type`.

Currently, the custom type however seems to be ignored, and the value for `nm_query_type` is always used, instead of the override, which is a bug.

NeoMutt 20170306 (1.8.0) and notmuch 0.23.5 on Arch Linux amd64 here.

**Comment by flatcap** [comment]
NotMuch contributors @julian-klode @bbenne10 @paretje @wpettersson
Would you be interested in investigating this?
