### ISSUE TITLE
Unable to get sidebar_whitelist to work

### ISSUE THREAD

**Issue by r2ro** [neomutt/neomutt#485]
In trying to get my sidebar to show a few mailboxes even if they don't contain new mail. I have the following in my .muttrc:

set imap_check_subscribed = yes  " Checks/Shows all (way too many)
set sidebar_new_mail_only = yes  " limit sidebar to mailboxes with new mail
sidebar_whitelist +Devel +Family "show these regardless of new mail

The whitelisted mailboxes don't show up. It continues to show only those with new mail in them.

I'm using NeoMutt 20170306 (1.8.0) installed via Homebrew on OSX El Capitan 10.11.6 using: --with-sidebar-patch --with-notmuch-patch --with-gettext

I've tried just about every combo of things I could think of to get it to work without success so far, so i'm thinking it may be broken?  Or I just overlooked something.

**Comment by sassmann** [comment]
Looking at the man page example
sidebar screenshot:
|fruit  |fruit
|fruit/apple                              |  apple
|fruit/banana                           |  banana
sidebar_whitelist fruit fruit/apple

Not sure what your mailbox names look like, but could it be that your whitelist entry should look like this?
sidebar_whitelist Devel Family

**Comment by r2ro** [comment]
I tried that as well, but still no luck.     It took me a while to find that example on the site.   The muttrc man page that gets installed does not actually have an entry for sidebar_whitelist.  It is only referenced once under  sidebar_new_mail_only as  "see also: sidebar_whitelist"  which doesn't exist.  So I've been chasing my tail on this one. lol

**Comment by flatcap** [comment]
OK, the whitelist feature is _sort of_ working (but needs fixing).
If you specify the full path, then it will force the display of a folder. e.g.
```
set folder = /home/flatcap/mail
mailbox =apple =banana =cherry
set sidebar_new_mail_only = yes
sidebar_whitelist /home/flatcap/mail/banana
```

Notes:
- The sidebar isn't expanding '+' or '=' to $folder, nor '~' to $HOME
- If you run `sidebar_whitelist` in mutt, hit <kbd>Ctrl-L</kbd> to refresh
- I've tested it with both local maildirs and IMAP.

**Comment by r2ro** [comment]
That worked for me, thanks.    The corresponding unsidebar_whitelist has the same issue as well.
