### ISSUE TITLE
sidebar_sort_method = new  re-sorts folders on sidebar-next

### ISSUE THREAD

**Issue by r2ro** [neomutt/neomutt#486]
When using my sidebar-next key bind, some sidebar folders get re-sorted.   In this case, it kept re-sorting (swapping) Devel and All Mail making the rest of the folders unreachable when using my key bind <down>

![screen shot 2017-03-24 at 18 29 58](https://cloud.githubusercontent.com/assets/37695/24316912/0b95c90e-10c0-11e7-9bd1-4e1c0672198c.png)
![screen shot 2017-03-24 at 18 29 16](https://cloud.githubusercontent.com/assets/37695/24316914/0ed62fdc-10c0-11e7-8cdd-dc13ea399c8a.png)

```
set imap_check_subscribed = yes " Checks/Shows all (way too many)
set sidebar_new_mail_only = yes " limit sidebar to mailboxes with new mail
set sidebar_sort_method   = new
sidebar_whitelist imaps://imap.gmail.com:993/Devel imaps://imap.gmail.com:993/Family " imap path used due to bug

bind index,pager <down>  sidebar-next
bind index,pager <up>    sidebar-prev
bind index,pager <right> sidebar-open
```

I'm using NeoMutt 20170306 (1.8.0) installed via Homebrew on OSX El Capitan 10.11.6 using: --with-sidebar-patch --with-notmuch-patch --with-gettext

**Comment by somini** [comment]
I can't reproduce this, but the relevant code is here:
https://github.com/somini/neomutt/blob/e8b36424abe21486a137276abdfd471c31c71017/sidebar.c#L312

This seems like a clear case of non-stable sorting. I would recommend use that `mutt_inbox_cmp` and the `mutt_strcoll` fallback when the counts are similar.

@r2ro If I create a branch can you compile mutt and test it yourself? I can't really reproduce your bug with local folders.

**Comment by r2ro** [comment]
@somini  That would be cool.

**Comment by somini** [comment]
I'll try to create this in the next few days. If I forget you can prod me here.
