### ISSUE TITLE
nntp: crossposting feature

### ISSUE THREAD

**Issue by hvkls** [neomutt/neomutt#487]
The VVV patch has always lacked a crossposting feature, i.e. posting and replying to multiple newsgroups at once with the same message. It's as if you had multiple To: recipients, but the recipients were newsgroups, and like group-reply, respectively.

Sounds like a cool new trick for that old dog, doesn't it?

**Comment by flatcap** [comment]
That sounds useful and it's probably quite simple to add.
However, I'm not sure if any of the regular coders are NNTP users.

> Sounds like a cool new trick for that old dog, doesn't it?

hehe, good thinking :-)

**Comment by flatcap** [comment]
I recently had a look at NNTP and you can cross-post already.
When you hit <kbd>P</kbd> to Post, you can add other groups to the "To:" field.

Even if you had something else in mind, this enhancement didn't attract someone to write some code.
This issue will now be closed, but listed on the [Closed Discussions](https://www.neomutt.org/dev/discussions) page.
