### ISSUE TITLE
Bool-ification of functions

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#492]
The C standard C99 defines a boolean type `bool` and truth values `true` and `false`.

A quick analysis of neomutt's code found ~230 functions that appear to only have two possible return values.  They are candidates for being "bool-ified".

The work will involve a bit of investigation and a little code editing.

After investigation, some functions won't be suitable:
- Analysis was wrong -- more return values
- Altering this function will mean altering many others (list them if possible)

If so, leave a comment.

Example work:

- Function returns `1` or `0`
  - Change the returns to `true` or `false`
  - Check the callers test the return value correctly
  - Rename the function to make it more clearly boolean

- Function returns `0` or `-1` (a common occurrence)
  - Change the returns to `true` or `false`
  - Change the callers to accept `true` or `false`
  - Update the function comment
  - Rename the function to make it more clearly boolean

Before starting work, add a comment below claiming a set of functions.
If you have any questions, please ask here, dev mailing list or on IRC.

When you have completed a task, please create a pull-request referencing this issue.

## Work To Do

- [x] Set 6 -- @flatcap
  1. imap_mailbox_create() -- **not suitable**
  2. parse_unreplace_list() -- **not suitable**
  3. mutt_var_value_complete() -- **not suitable**
  5. nntp_auth() -- **not suitable**

- [x] Set 7 -- @flatcap
  2. imap_fetch_message() -- **not suitable**
  3. mutt_rx_sanitize_string() -- **done**
  4. mutt_ts_capability() -- **done**
  5. select_prev_new() -- **done**

- [x] Set 8 -- @flatcap
  1. data_object_to_stream() -- **not suitable**
  2. check_idn() -- **done**
  3. read_material() -- **not suitable**
  4. parse_spam_list() -- **not suitable**
  5. check_uidl() -- **not suitable**

- [x] Set 9 -- @flatcap
  1. imap_browse() -- **not suitable**
  2. imap_search() -- **not suitable**
  3. mh_sync_message() -- **not suitable**
  4. print_val() -- **done**
  5. imap_rename_mailbox() -- **not suitable**  

- [x] Set 10 - @flatcap
  1. check_certificate_cache() -- **done**
  2. _maildir_commit_message() -- **not suitable**
  3. parse_regex() -- **not suitable**
  4. nntp_active_fetch() -- **not suitable**
  5. mutt_dump_variables() -- **not suitable**

- [x] Set 11 - @flatcap
  1. trash_append() -- **not suitable**
  2. link_threads() -- **done**
  3. nm_close_mailbox() -- **not suitable**
  4. mutt_check_charset() -- **done**
  6. write_one_header() -- **not suitable**
  7. mutt_option_set() -- **not suitable**
  8. close_mailbox() -- **not suitable**
  10. maildir_add_to_context() -- **done**

- [x] Set 12 - @flatcap
  1. mutt_comp_can_read() -- **done**
  2. parse_setenv() -- **not suitable**
  3. select_next_new() -- **done**
  4. tls_set_priority() -- **not suitable**
  5. tls_init() -- **done**
  6. pop_reconnect() -- **done**
  7. compare_flags() -- **done**
  8. nm_close_message() -- **not suitable**
  9. fetch_tempfile() -- **not suitable**
  10. perform_or() -- **done**

- [x] Set 13 - @flatcap
  1. fetch_message() -- **not suitable**
  2. mbox_open_mailbox_append() -- **not suitable**
  3. parse_unsubscribe() -- **not suitable**
  4. _lua_mutt_get() -- **not suitable**
  5. safe_rename() -- **not suitable**
  6. safe_symlink() -- **not suitable**
  8. mutt_ssl_starttls() -- **not suitable**
  9. imap_open_mailbox_append() -- **not suitable**
  10. imap_open_mailbox() -- **not suitable**

- [x] Set 14 - @flatcap
  1. perform_and() -- **done**
  2. mutt_copy_header() -- **not suitable**
  3. crypt_key_is_valid() -- **done**
  4. parse_alternates() -- **not suitable**
  5. imap_subscribe() -- **not suitable**
  6. tls_check_preauth() -- **not suitable**
  7. imap_read_literal() -- **not suitable**
  8. mbox_has_new() -- **done**
  9. is_context_available() -- **done**
  10. match_reference() -- **done**

- [x] Set 15 - @flatcap
  1. mh_sync_mailbox_message() -- **not suitable**
  2. nntp_fetch_headers() -- **not suitable**
  3. parse_overview_line() -- **not suitable**
  4. url_ciss_tostring() -- **not suitable**
  5. mutt_socket_readchar() -- **not suitable**
  6. prepare_sidebar() -- **done**- [x] Set 6 -- @flatcap
  1. imap_mailbox_create() -- **not suitable**
  2. parse_unreplace_list() -- **not suitable**
  3. mutt_var_value_complete() -- **not suitable**
  5. nntp_auth() -- **not suitable**

- [x] Set 7 -- @flatcap
  2. imap_fetch_message() -- **not suitable**
  3. mutt_rx_sanitize_string() -- **done**
  4. mutt_ts_capability() -- **done**
  5. select_prev_new() -- **done**

- [x] Set 8 -- @flatcap
  1. data_object_to_stream() -- **not suitable**
  2. check_idn() -- **done**
  3. read_material() -- **not suitable**
  4. parse_spam_list() -- **not suitable**
  5. check_uidl() -- **not suitable**

- [x] Set 9 -- @flatcap
  1. imap_browse() -- **not suitable**
  2. imap_search() -- **not suitable**
  3. mh_sync_message() -- **not suitable**
  4. print_val() -- **done**
  5. imap_rename_mailbox() -- **not suitable**  
  7. check_for_mailing_list() -- **done**
  8. mutt_account_fromurl() -- **done**
  9. imap_open_connection() -- **not suitable**
  10. imap_compile_search() -- **not suitable**

- [x] Set 16 - @flatcap
  1. state_putws() -- **done**
  2. db_trans_end() -- **done**
  3. pop_fetch_message() -- **not suitable**
  4. mutt_command_complete() -- **not suitable**
  5. mbox_commit_message() -- **not suitable**
  6. get_initials() -- **done**
  7. mutt_ssl_socket_setup() -- **not suitable**
  8. mutt_mkdir() -- **not suitable**
  9. fold_one_header() -- **not suitable**
  10. execute_commands() -- **not suitable**

- [x] Set 17 - @flatcap
  1. mutt_atol() -- **not suitable**
  2. copy_delete_attach() -- **done**
  3. var_to_string() -- **not suitable**
  4. url_parse_query() -- **done**
  6. cmd_handle_untagged() -- **done**
  7. string_is_address() -- **done**
  8. crypt_write_signed() -- **done**
  9. get_field_text() -- **not suitable**
  10. select_next() -- **done**

- [x] Set 18 - @flatcap
  1. set_signer() -- **done**
  2. finish_source() -- **not suitable**
  3. tls_socket_open() -- **not suitable**
  4. crypt_is_numerical_keyid() -- **done**
  5. mutt_pop_list() -- **done**
  6. mutt_copy_body() -- **not suitable**
  7. check_all_msg() -- **done**
  8. compare_certificates() -- **done**
  9. tls_compare_certificates() -- **not suitable**
  10. is_bound() -- **done**

- [x] Set 19 - @flatcap
  1. url_pct_decode() -- **not suitable**
  3. init_context() -- **done**
  4. addrcmp() -- **done**
  6. setup_paths() -- **done**
  7. pgpring_string_matches_hint() -- **done**
  8. address_uses_unicode() -- **done**
  9. mutt_convert_string() -- **done**
  10. mutt_match_spam_list() -- **done**

- [x] Set 20 -- @flatcap
  1. update_header_tags() -- **done**
  3. add_to_replace_list() -- **done**
  4. add_quote_suffix() -- **done**
  5. select_prev() -- **done**
  6. raw_socket_open() -- **not suitable**
  7. remove_filename() -- **done**
  8. external_body_handler() -- **not suitable**
  9. get_database_mtime() -- **done**
  10. addresses_use_unicode() -- **done**

- [x] Set 21 -- @flatcap 
  1. mmdf_commit_message() -- **not suitable**
  2. hostname_match() -- **done**
  3. pop_parse_path() -- **not suitable**
  4. menu_dialog_dokey() -- **done**
  5. mutt_account_getuser() -- **done**
  6. pgp_check_traditional_one_body() -- **not suitable**
  7. smtp_fill_account() -- **done**
  9. count_body_parts_check() -- **done**
  10. cmd_queue_full() -- **done**

- [x] Set 22 -- @flatcap
  1. parse_subscribe() -- **not suitable**
  2. imap_delete_mailbox() -- **not suitable**
  3. fetch_uidl() -- **not suitable**
  4. imap_has_flag() -- **done**
  5. ssl_init() -- **done**
  6. pgp_parse_pgp2_sig() -- **not suitable**
  7. parse_attach_list() -- **not suitable**
  8. mutt_add_to_rx_list() -- **not suitable**
  9. smtp_code() -- **done**
  10. mh_valid_message() -- **done**

- [x] Set 23 -- @flatcap 
  1. open_append_mailbox() -- **not suitable**
  2. main_change_folder() -- **done**
  3. mix_chain_add() -- **done**
  4. mutt_addr_is_user() -- **done**
  5. imap_check_capabilities() -- **done**
  6. pgp_parse_pgp3_sig() -- **not suitable**
  8. mutt_label_complete() -- **not suitable**
  10. group_remove_adrlist() -- **not suitable**

- [x] Set 24 -- @flatcap
  1. check_certificate_expiration() -- **done**
  2. parse_unalternates() -- **not suitable**
  3. mutt_account_getpass() -- **done**
  4. mutt_needs_mailcap() -- **done**
  5. check_msg() -- **done**
  7. release_db() -- **done**
  8. query_save_attachment() -- **done**
  9. is_day_name() -- **done**
  10. user_in_addr() -- **done**

- [x] Set 25 -- @flatcap
  1. pop_sync_mailbox() -- **not suitable**
  2. check_attachments() -- **done**
  3. mkwrapdir() -- **done**
  4. mx_toggle_write() -- **done**
  5. pgp_use_gpg_agent() -- **done**
  6. update_tags() -- **done**
  7. tunnel_socket_open() -- **not suitable**
  8. imap_get_mailbox() -- **done**
  9. imap_sync_message() -- **not suitable**
  10. bcache_path() -- **done**

- [x] Set 26 -- @flatcap
  1. mbox_to_udomain() -- **done**
  2. compare_stat() -- **done**
  3. mutt_group_match() -- **done**
  4. create_hcache_dir() -- **done**
  5. mutt_alias_complete() -- **not suitable**
  6. parse_group_context() -- **not suitable**
  7. parse_unlists() -- **not suitable**
  8. nntp_open_mailbox() -- **not suitable**
  9. tls_check_stored_hostname() -- **not suitable**
  10. mh_read_dir() -- **not suitable**

- [x] Set 27 -- @flatcap
  1. imap_parse_path() -- **done**
  2. parse_group() -- **not suitable**
  3. check_boundary() -- **done**
  4. addr_hook() -- **done**
  5. mutt_filter_unprintable() -- **not suitable**
  6. mutt_matches_list() -- **done**
  7. ssl_socket_open() -- **not suitable**
  8. init_header() -- **done**
  9. rfc822_valid_msgid() -- **done**
  10. feature_enabled() -- **done**

- [x] Set 28 -- @flatcap
  1. pop_open_mailbox() -- **not suitable**
  3. line_compare() -- **done**
  4. maildir_mh_open_message() -- **not suitable**
  5. is_display_corrupting_utf8() -- **done**
  6. mutt_limit_current_thread() -- **done**
  7. md5_stream() -- **not suitable**
  8. parse_replace_list() -- **not suitable**
  9. mutt_comp_can_append() -- **done**

**Comment by gahr** [comment]
* nntp_fetch_message() - std unix semantics, returns 0 on success, 1 on error

**Comment by flatcap** [comment]
## Work Done

These functions have been converted / checked.
Thanks, @gahr :heart:

- [x] Set 1
  1. check_for_mailing_list_addr() - **done**
  2. nntp_fetch_message() - **not a boolean**
  3. convert_nonmime_string() -  **not a boolean**
  4. mutt_query_variables() - **not a boolean**
  5. tls_negotiate() - **not a boolean**

- [x] Set 2
  1. pgp_key_is_valid() - **done**
  2. imap_append_message() - **not a boolean**
  3. is_parent() - **done**
  4. eat_message_range() - **done**
  5. rfc1524_expand_filename() - **not a boolean**

- [x] Set 3
  1. imap_cmd_idle() - **not a boolean**
  2. parse_lists() - **not a boolean**
  3. ssl_negotiate() - **not a boolean**
  4. nntp_date() - **not a boolean**
  5. is_ascii() - **done**

- [x] Set 4
  1. imap_mailbox_rename() - **not a boolean**
  2. imap_get_literal_count() - **not a boolean**
  3. active_get_cache() - **not a boolean**
  4. update_message_path() - **not a boolean**
  5. update_header_flags() - **not a boolean**

- [x] Set 5
  1. complete_all_nm_tags() - **not a boolean**
  2. mutt_nm_tag_complete() - **done**
  3. mutt_sasl_client_new() - **not a boolean**
  4. imap_create_mailbox() - **not a boolean**
  5. mh_read_token() - **not a boolean**

- [x] Set 29
  1. mutt_is_mail_list() - **done**
  2. mutt_is_message_type() - **done**
  3. mutt_is_subscribed_list() - **done**

- [x] Misc
  1. pgp_cansign() - **done**
  1. mx_is_mh() - **done**
  1. mutt_is_text_part() - **done**
  1. mutt_match_rx_list() - **done**
  1. pgp_id_is_valid() - **done**
  1. mx_is_notmuch() - **done**
  1. first_mailing_list() - **done**
  1. mx_is_pop() - **done**
  1. mx_is_nntp() - **done**
  1. mx_is_maildir() - **done**
  1. pgp_canencrypt() - **done**
  1. mutt_nm_query_complete() - **done**
  1. mx_is_imap() - **done**
  1. pgp_id_is_strong() - **done**

**Comment by flatcap** [comment]
To complement this issue, I've committed aef72db - **bool-ify structs**
- Convert all struct members that are used as booleans, to "bool".

**Comment by flatcap** [comment]
Closed by:
- 29bb0d1 - 46 functions that already returned 0/1 for failure/success
- de18985 - 12 functions that returned -1 on failure but were essentially boolean
