### ISSUE TITLE
neomutt doesn't color mail adresses correctly, if it contains unusual characters.

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#496]
From the mail adress `taskwarrior-user+subscribe@googlegroups.com`, neomutt only recognizes `subscribe@googlegroups.com` as part of an email adress, although thats only one part of it.

![neomutt](https://cloud.githubusercontent.com/assets/9417950/24822658/12b828f2-1bf7-11e7-87b8-cd58bd6eeb1e.png)

**Comment by guiniol** [comment]
This can be fixed easily by tweaking your coloration rule. For examples, for emails, I have
```
color body green default [\-\.+_a-zA-Z0-9]+@[\-\.a-zA-Z0-9]+
```

**Comment by toogley** [comment]
@guiniol Ah, i see. Initially, i thought that the url parsing code in `url.c` is responsible for that - at least for the "identifiying the email address" part.  (which is not the case, i guess)

That means, i agree with you. But still, i think this should be the default.

**Comment by guiniol** [comment]
I think some of the default config files are distro specific, but we could always change the default file WE ship.

**Comment by flatcap** [comment]
Upstream have made some changes to how the refreshes are done.
Does this problem still occur?
