### ISSUE TITLE
MIME headers, rfc 2047 decoding is applied

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#498]
The [TODO](https://github.com/neomutt/neomutt/blob/b7c0d9abd67f23fb16f36834eb66ff25d06a2560/TODO) file says:

> When displaying MIME headers, rfc 2047 decoding is applied (which
>  should not happen), and rfc 2231 decoding is not applied (which
>  should happen).

Is this still relevant?

**Comment by flatcap** [comment]
This upstream file hasn't been touch in over 8 years.
It doesn't seem to be important to them, so I don't think we should worry about it.

**Comment by toogley** [comment]
@flatcap Hm, i disagree with your conclusion. The maintainers have changed in between. So of course, Kevin and other maintainers maybe don't care about this TODO file. But when some mutt developers don't care about this, is this a good argument for us to also not care about it? I don't think so.

I think, the basis of our conclusion -  whether we close those TODO issues or not -  should not rely upon whether some (mutt) developer cares about it or not. I think the basis of our conclusion should be the **technical relevance**. Therefore I've openend all those issues. And therefore, i asked for the relevance. 

Because, after all, some mutt developer cared once about it enough to append the issue into the TODO file. right?

**Comment by flatcap** [comment]
You're right, of course, but I don't have the in-depth knowledge of email RFCs to be able answer the question.  I carefully read all the issues you raised and thought about them.  I'm not sure how many people are qualified to comment on them.

This comment was added to the TODO list 18 years ago.
If it were a problem, even an occasional problem, I suspect someone would have noticed.

Sorry.
