### ISSUE TITLE
neomutt uses mailbox handling functions to access message/rfc822 type attachments.

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#499]
The [TODO](https://github.com/neomutt/neomutt/blob/b7c0d9abd67f23fb16f36834eb66ff25d06a2560/TODO) file says:

> - In the "attachment" menu, assume this:
> 
> 	1 [text/plain, 7bit, 1.1K]           <no description>
> 	2 [message/rfc822, 7bit, 6.1K]       A test message
> 	3 [text/plain, 7bit, 0.1K]           |-><no description>
> 	4 [message/rfc822, base64, 2.5K]     |-><no description>
> 	5 [message/rfc822, base64, 2.7K]     `-><no description>
> 
>   (please note the "message/rfc822" attachments encoded as
>   Base64; that's illegal, but Sun's Mailtool sends that
>   kind of messages); then go to, say, attachment "4",
>   delete it, and go to the main menu; you won't be able to
>   quit the mailbox (ok, 'x' works, but 'q' doesn't).
> 
>   The problem here lies in the fact that mutt uses mailbox
>   handling functions to access message/rfc822 type
>   attachments.  We'd need to perform an additional
>   decoding step before using these functions to fix this
>   bug.
> 
>   Please note that mutt's just assuming RFC-compliant mail
>   here.  Fixing this stuff may become a PITA.

Is this still relevant?

**Comment by flatcap** [comment]
This upstream file hasn't been touch in over 8 years.
It doesn't seem to be important to them, so I don't think we should worry about it.
