### ISSUE TITLE
24bits (true color) support

### ISSUE THREAD

**Issue by timofonic** [neomutt/neomutt#5]
https://dev.mutt.org/trac/ticket/3674
https://github.com/jonas/tig/issues/227

Many apps already support 24bit /true color) console support :)

What about NeoMutt?

PS: Will you refactorize the code and add Lua support? And rewrite to C++14? Hahaha, I'm joking...

**Comment by flatcap** [comment]
@timofonic 

> Many apps already support 24bit /true color) console support :)
> What about NeoMutt?

Alas, it can't be done.  (Obviously that's not true, it would just be massively impractical).
Mutt uses ncurses/slang to do most of the drawing work and that includes the colours.
As I understand it, neither support 24bit colour.  When they do, it wouldn't be a lot of work to make Mutt 24 colourful!

> PS: Will you refactorize the code and add Lua support? And rewrite to C++14? Hahaha, I'm joking...

Hehe, I'd love to but getting even simple things into Mutt is hard work.

For now, I've marked this Issue "won't fix" and I'll close it shortly.  Thanks for playing :-)

**Comment by XVilka** [comment]
Note that almost any single terminal now supports those. It would never land in ncurses and terminfo while the current maintainer of them is in charge. But the rest are fine and you can see Midnight Commander as a good example of Slang library user with proper RGB color support.

**Comment by XVilka** [comment]
Note, that starting from 6.1 version ncurses supports direct RGB color. So adoption now is nearly 100%.

**Comment by flatcap** [comment]
Holy ****!
This comes just after I figure our how to cheat, to make RGB and attributes a possibility.
Now, the only obstable is (neo)mutt itself.

Thanks for the heads up, @XVilka.

**Comment by MaskRay** [comment]
Want to see the feature
