### ISSUE TITLE
BODY struct should probably have a pointer to its corresponding HEADER struct.

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#500]
The [TODO](https://github.com/neomutt/neomutt/blob/b7c0d9abd67f23fb16f36834eb66ff25d06a2560/TODO) file says:

> - BODY struct should probably have a pointer to its                                                                                                                       
>       corresponding HEADER struct.  this is needed for                                                                                                                        
>       mh/maildir mailboxes so the correct pathname can be                                                                                                                     
>       found.  Or perhaps all we need is a .hdr member of the                                                                                                                  
>       STATE struct so that all of the MIME handlers can look                                                                                                                  
>       up the corresponding HEADERs if need be?          

Is this still relevant? 

I'm not sure if [that](https://github.com/neomutt/neomutt/blob/b7c0d9abd67f23fb16f36834eb66ff25d06a2560/mutt.h#L767) is meant by this entry. (I ask just to be sure. My i don't trust my C experience to decide that by myself. :D)

**Comment by flatcap** [comment]
This upstream file hasn't been touch in over 8 years.
It doesn't seem to be important to them, so I don't think we should worry about it.
