### ISSUE TITLE
make patterns generic and  introduce generic menu limiting, menu pattern searching

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#503]
The [TODO](https://github.com/neomutt/neomutt/blob/b7c0d9abd67f23fb16f36834eb66ff25d06a2560/TODO) file says:

> - make patterns generic (I have patches for this -tlr), and
>   introduce generic menu limiting, menu pattern searching, and the
>   like.
> 
>   Note: This still requires some thought, since we'd have to store
>   per-entry data in the menu structure.  As an alternative, we could
>   extend the tag method to do something to more general flags. The
>   latter approach would make the implementation of proper
>   tag-prefix behaviour more simple: Functions should only be applied
>   when a message is tagged and visible.  Additionally, we must not
>   access a menu's max field directly any more: Adding an entry to a
>   menu will require re-allocating and possibly updating the v2r
>   array.  How do we handle "in-the-middle additions" properly?  Do
>   they happen at all?

Is this still relevant?

**Comment by flatcap** [comment]
This upstream file hasn't been touch in over 8 years.
It doesn't seem to be important to them, so I don't think we should worry about it.
