### ISSUE TITLE
imap: new and better imap_format string for IMAP browsing

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#505]
The [TODO](https://github.com/neomutt/neomutt/blob/b7c0d9abd67f23fb16f36834eb66ff25d06a2560/imap/TODO) file says:

> [ -- browsing -- ]
> 
> * We should maybe add a new imap_format string for IMAP browsing, without all
>   the stat variables but with tags like how many messages are in the folders,
>   how many subfolders, that weird \Marked tag, etc.

is this still relevant? I'm not sure if this is part of #181 ?

**Comment by flatcap** [comment]
This upstream file hasn't been touch in over 8 years.
It doesn't seem to be important to them, so I don't think we should worry about it.
