### ISSUE TITLE
imap: Partial index loading, using server-side threading and sorting

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#506]
The [TODO](https://github.com/neomutt/neomutt/blob/b7c0d9abd67f23fb16f36834eb66ff25d06a2560/imap/TODO) file says:

> [ -- speed -- ]
> 
> * Partial index loading, using server-side threading and sorting

Is this still relevant? Furthermore, i'm confused by the `server-side`, because mutt is usually run on the client side. So i'm not sure if that really applies to mutt.

**Comment by flatcap** [comment]
This upstream file hasn't been touch in over 8 years.
It doesn't seem to be important to them, so I don't think we should worry about it.

**Comment by toogley** [comment]
is there a technical reason to close this? I mean, the "partial index loading" sounds useful. Although i understand, that it may be very hard to realize.

**Comment by flatcap** [comment]
We can reopen this as an enhancement, if you like.  It's not going to be an easy task.

I don't want to sound pessimistic, but it's unlikely to be picked up.

**Comment by toogley** [comment]
Okay, then i think we can leave it like it is.
