### ISSUE TITLE
imap: Partial message loading, including parsing BODYSTRUCTURE for the view-attachments menu

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#507]
The [TODO](https://github.com/neomutt/neomutt/blob/b7c0d9abd67f23fb16f36834eb66ff25d06a2560/imap/TODO) file says:
 
> [ -- speed -- ]
> 
> * Partial message loading, including parsing BODYSTRUCTURE for the
>   view-attachments menu

is this still relevant?

**Comment by flatcap** [comment]
This upstream file hasn't been touch in over 8 years.
It doesn't seem to be important to them, so I don't think we should worry about it.
