### ISSUE TITLE
imap: Possibly opening multiple connections for mailbox polling

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#509]
The [TODO](https://github.com/neomutt/neomutt/blob/b7c0d9abd67f23fb16f36834eb66ff25d06a2560/imap/TODO) file says:

> [ -- new mail detection -- ]
> 
> * Possibly opening multiple connections for mailbox polling, now that
>   we have IDLE support.

is this still relevant?

**Comment by flatcap** [comment]
This upstream file hasn't been touch in over 8 years.
It doesn't seem to be important to them, so I don't think we should worry about it.
