### ISSUE TITLE
index view misalignment when compiled with sidebar support (neomutt-20160611)

### ISSUE THREAD

**Issue by grobian** [neomutt/neomutt#51]
Mutt 1.6.1 (2016-06-11, Gentoo 1.6.1-r2, NeoMutt 3d90396616d009a7dcbfbb17d8a74b3eee70bd9a)

The index doesn't use the full terminal width when sidebar support is compiled in, e.g.:
```
08-Jun   l Alexander Berntsen    +Facilitating user contributed ebuilds (Was[97]
Thu-09   l Michael Palimaka       Last rites: app-i18n/xsim               (2,4K)
Thu-09   l Michael Palimaka       Last rites: media-gfx/wings             (2,4K)
Thu-09   l Michael Palimaka       Last rites: media-gfx/fbv               (2,5K)
Thu-09   l Michael Palimaka       Last rites: sys-apps/dmtcp              (2,4K)
Thu-09   l Michael Palimaka       [PATCH] cmake-utils.eclass: do not pass(3,0K) 
Sat-11   l Benda Xu              +RFC: kernel-2.eclass Prefix support       [14]
Sat-11   l Pacho Ramos            Packages up for grabs                   (2,4K)
Sun-12  sl Andrew Savchenko       ├─>                                     (3,6K)
Sun-12   l Michał Górny           ├─>                                     (2,4K)
Sun-12  sl Andrew Savchenko       │ └─>                                   (3,8K)
Sun-12  sl Craig Inches           ├─>                                     (5,9K)
Sun-12  sl Mike Frysinger         │ └─>                                   (3,2K)
Sun-12  sl M. J. Everitt          │   └─>                                 (4,7K)
Mon-13   l Alexander Berntsen     └─>                                     (3,4K)
Sun-12   l Pacho Ramos            Lastrites: app-cdr/dvd95, app-portage/e(4,0K) 
Mon-13   l Robin H. Johnson       Automated Package Removal and Addition (8,8K) 
Tue-14   l Ashish Gupta           Re: Packages up for grabs               (3,6K)
```

Weird drawing artifacts appear when scrolling through an expanded thread, the top of visible message of the thread appears to be one char short, however when scrolling up, it's aligned properly.
When compiling mutt --without-sidebar this misalignment doesn't happen, so it's something related to the sidebar code path.  Toggling the visibility of sidebar doesn't fix this misalignment.
Relevant config:
```
set index_format = "%<[12m?%<[7d?%<[12H?%[%H:%M ]&%[%a-%d]>&%[%d-%b]>&%[%b-%y]> %Z %-21.21F %?M?+& ?%s %* %?M?[%M]&(%c)?"
```

**Comment by flatcap** [comment]
Hmm...  I didn't notice any problems with my version.  Perhaps I wasn't looking closely enough.

**Comment by grobian** [comment]
this may be because we're on the windowing patches branch

**Comment by flatcap** [comment]
I've just compiled the gentoo branch and set your index_format, but I still can't reproduce the problem.
Also, I followed the instructions in the Gentoo build script and ended up with exactly the same source code.

I'll keep looking...

**Comment by grobian** [comment]
Configure options: '--prefix=/gentoo/prefix64/usr' '--build=x86_64-pc-solaris2.11' '--host=x86_64-pc-solaris2.11' '--mandir=/gentoo/prefix64/usr/share/man' '--infodir=/gentoo/prefix64/usr/share/info' '--datadir=/gentoo/prefix64/usr/share' '--sysconfdir=/gentoo/prefix64/etc' '--localstatedir=/gentoo/prefix64/var/lib' '--disable-dependency-tracking' '--disable-silent-rules' '--docdir=/gentoo/prefix64/usr/share/doc/mutt-1.6.1-r2' '--htmldir=/gentoo/prefix64/usr/share/doc/mutt-1.6.1-r2/html' '--libdir=/gentoo/prefix64/usr/lib' '--enable-pgp' '--disable-debug' '--enable-gpgme' '--enable-imap' '--enable-nls' '--enable-nntp' '--disable-pop' '--enable-sidebar' '--enable-smime' '--enable-smtp' '--without-idn' '--without-gss' '--with-curses=/gentoo/prefix64/usr' '--enable-compressed' '--enable-external-dotlock' '--enable-nfs-fix' '--sysconfdir=/gentoo/prefix64/etc/mutt' '--with-docdir=/gentoo/prefix64/usr/share/doc/mutt-1.6.1-r2' '--with-regex' '--with-exec-shell=/gentoo/prefix64/bin/sh' '--enable-fcntl' '--disable-flock' '--without-wc-funcs' '--enable-hcache' '--without-tokyocabinet' '--without-qdbm' '--without-gdbm' '--with-bdb' '--with-ssl' '--with-sasl' '--with-mailpath=/gentoo/prefix64/var/spool/mail' 'build_alias=x86_64-pc-solaris2.11' 'host_alias=x86_64-pc-solaris2.11' 'CFLAGS= -O2 -pipe' 'LDFLAGS='

I'll run some additional tests myself.

**Comment by grobian** [comment]
Yup, just confirmed by recompiling on the above Solaris box with --disable-sidebar that it works correctly without.  So not a Solaris oddity.

**Comment by flatcap** [comment]
Good (on the Solaris front).

I just don't see how the problem's happening.
The only thing the Sidebar's telling the Index Panel is the width available.  That happens once.  That implies that some emails are triggering a bug.  But that doesn't explain why disabling Sidebar fixes it.

Aha!  Right, I can reproduce the problem now.  My terminal was too wide.

**Comment by flatcap** [comment]
I don't understand the Sidebar link yet, but the problem is this commit:
- Add spacing to truncated multi-column characters when using soft-fill.

Reverting it fixes the problem.

**Comment by flatcap** [comment]
Please give [issue/51](https://github.com/neomutt/neomutt/compare/issue/51) a try.
A small patch for the wide-string truncation that takes into account index-color.
