### ISSUE TITLE
doc: Re-check complete manual for consistency.

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#510]
The [TODO](https://github.com/neomutt/neomutt/blob/b7c0d9abd67f23fb16f36834eb66ff25d06a2560/doc/TODO) file says:

> * Re-check complete manual for consistency. The same things need to be
>   consistently marked up, e.g. an item either always as <literal/> or
>   always <emphasis/> (decide clearly which to use for what), make sure
>   all option refs are links, things are consistently quoted.
>   E.g. it has:
> 
>     If the filename begins with a tilde (``&tilde;'')
> 
>   and
> 
>     If the filename ends with a vertical bar (&verbar;)
> 
>   We need to choose either style and use it.

is this still relevant?

**Comment by flatcap** [comment]
This upstream file hasn't been touch in over 8 years.
It doesn't seem to be important to them, so I don't think we should worry about it.
