### ISSUE TITLE
doc: template to improve consistency

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#511]
The [TODO](https://github.com/neomutt/neomutt/blob/b7c0d9abd67f23fb16f36834eb66ff25d06a2560/doc/TODO) file says:

> * Think about some way of templating to a) help improve consistency
>   (i.e. some sort of macro to refer to key, options, functions, etc.)
>   and b) reduce typing overhead.
> 
>     <link linkend="pipe-split">&dollar;pipe&lowbar;split</link>
> 
>   is neither fun to read nor to write. This would give us lots of
>   options to improve it (e.g. an automated index). We depend on
>   perl already to build docs, think about/look for simple perl
>   templating engine.

is this still relevant?

**Comment by flatcap** [comment]
This upstream file hasn't been touch in over 8 years.
It doesn't seem to be important to them, so I don't think we should worry about it.
