### ISSUE TITLE
doc: trim the TOC for the option reference

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#512]
The [TODO](https://github.com/neomutt/neomutt/blob/b7c0d9abd67f23fb16f36834eb66ff25d06a2560/doc/TODO) file says:

> * Find a way (XSLT?) to trim the TOC for the option reference; it's
>   ugly but we probably want to keep the TOC depth as-is for other
>   sections.

is that still relevant?

**Comment by flatcap** [comment]
This upstream file hasn't been touch in over 8 years.
It doesn't seem to be important to them, so I don't think we should worry about it.
