### ISSUE TITLE
doc: group sections by topic instead of per task.

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#513]
The [TODO](https://github.com/neomutt/neomutt/blob/b7c0d9abd67f23fb16f36834eb66ff25d06a2560/doc/TODO) file says:

> * Some sections maybe should be better grouped by topic, instead of
>   one section per task (e.g. hooks should be grouped under a section
>   'hooks' in the config chapter).

is this still relevant?

**Comment by flatcap** [comment]
This upstream file hasn't been touch in over 8 years.
It doesn't seem to be important to them, so I don't think we should worry about it.
