### ISSUE TITLE
Deleting an email and executing sync-mailbox changes current email

### ISSUE THREAD

**Issue by ElDeveloper** [neomutt/neomutt#516]
* **bug reports**

    * Expected behavior: When emails are marked for deletion and I execute `sync-mailbox`, the cursor should not change focus (so as long as the email under focus is not marked for deletion).

    * Actual behavior: The cursor changes focus from the current email to another arbitrary email. This happens in the pager and in the index. I don't remember this happening in previous versions.

    * Steps to reproduce: mark an email for deletion (the email should be listed below your current cursor position), then `sync-mailbox` and you should see the cursor move positions.

    * Used program versions:

```
NeoMutt 20170306-97-7656f1-dirty (1.8.0)
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.

System: Darwin 16.4.0 (x86_64)
hcache backends: gdbm

Compiler:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.38)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Configure options: '--with-ssl' '--enable-pop' '--enable-imap' '--enable-smtp' '--with-sasl' '--enable-hcache' '--prefix=/usr/local/' '--with-gdbm' 'LDFLAGS=-L/usr/local/lib/ -L/usr/local/Cellar/openssl/1.0.2d_1/lib' 'CPPFLAGS=-I/usr/local/include/ -I /usr/local/Cellar/openssl/1.0.2d_1/include/'

Compilation CFLAGS: -Wall -pedantic -Wno-long-long -g -O2 -fno-delete-null-pointer-checks

Compile options:
+CRYPT_BACKEND_CLASSIC_PGP +CRYPT_BACKEND_CLASSIC_SMIME -CRYPT_BACKEND_GPGME 
-DEBUG +DL_STANDALONE +ENABLE_NLS -EXACT_ADDRESS -HOMESPOOL -LOCALES_HACK 
-SUN_ATTACHMENT +HAVE_BKGDSET +HAVE_COLOR +HAVE_CURS_SET -HAVE_FUTIMENS 
+HAVE_GETADDRINFO +HAVE_GETSID +HAVE_LANGINFO_CODESET +HAVE_LANGINFO_YESEXPR 
-HAVE_LIBIDN +HAVE_META -HAVE_REGCOMP +HAVE_RESIZETERM +HAVE_START_COLOR 
+HAVE_TYPEAHEAD +HAVE_WC_FUNCS +ICONV_NONTRANS -USE_COMPRESSED +USE_DOTLOCK 
+USE_FCNTL -USE_FLOCK -USE_FMEMOPEN -USE_GSS +USE_HCACHE +USE_IMAP -USE_LUA 
-USE_NOTMUCH -USE_NNTP +USE_POP +USE_SASL +USE_SETGID -USE_SIDEBAR +USE_SMTP 
-USE_SSL_GNUTLS +USE_SSL_OPENSSL 
-DOMAIN
-MIXMASTER
-ISPELL
SENDMAIL="/usr/sbin/sendmail"
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/mutt"
SYSCONFDIR="/usr/local/etc"
EXECSHELL="/bin/sh"

patch-attach-headers-color-neomutt
patch-compose-to-sender-neomutt
patch-compress-neomutt
patch-cond-date-neomutt
patch-encrypt-to-self-neomutt
patch-fmemopen-neomutt
patch-forgotten-attachments-neomutt
patch-forwref-neomutt
patch-ifdef-neomutt
patch-index-color-neomutt
patch-initials-neomutt
patch-keywords-neomutt
patch-kyoto-neomutt
patch-limit-current-thread-neomutt
patch-lmdb-neomutt
patch-lua-neomutt
patch-multiple-fcc-neomutt
patch-nested-if-neomutt
patch-new-mail-neomutt
patch-nntp-neomutt
patch-notmuch-neomutt
patch-progress-neomutt
patch-quasi-delete-neomutt
patch-reply-with-xorig-neomutt
patch-sensible-browser-neomutt
patch-sidebar-neomutt
patch-skip-quoted-neomutt
patch-status-color-neomutt
patch-timeout-neomutt
patch-tls-sni-neomutt
patch-trash-neomutt

To learn more about NeoMutt, visit: http://www.neomutt.org/
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>

```

    * Operating System and its version: Mac OSX 10.12.3.

**Comment by flatcap** [comment]
Hmm... sorry, I don't see this.
I've tried in both the index and the pager.  I deleted a spread of emails: before, around, or after the current email.  Then I ran `sync-mailbox`.  Each time the cursor was correctly positioned afterwards.

What sort settings are you using?

**Comment by ElDeveloper** [comment]
Thanks for checking @flatcap! I was able to capture this in a gif:

![neomutt-bug](https://cloud.githubusercontent.com/assets/375307/25243034/82cb9684-25b0-11e7-8007-f8263921fb04.gif)

If you pay close attention, you can see that at first my cursor is over an email received at 13:38 (I move the cursor to the one below and then back - my cursor is highlighted in yellow). At this point I have also marked some emails for deletion (highlighted in red), when I `sync-mailbox` the emails are deleted, but the cursor is now on an email received at 13:46.

As for settings, my muttrc can be found [here](https://gist.github.com/ElDeveloper/933c5861f0124833e3f42fd99abeb35b).

**Comment by flatcap** [comment]
I've just run the same tests using your config and my cursor stays in the right place.
*sigh*
I'll keep thinking...

**Comment by ElDeveloper** [comment]
Thanks, really appreciate it, just noticed that while trying to remove sensitive information from my .muttrc, I removed two things:

```
set imap_check_subscribed
set postponed="+[Gmail]/Drafts"
set trash="+[Gmail]/Trash"
set record=~/.mutt/sent
```

Maybe it has something to do with the trash folder, but that's just a wild guess.

**Comment by flatcap** [comment]
I tried with and without trash -- no difference.
Also, my imap mailbox used the subscription list from the server.

**Comment by flatcap** [comment]
I *have* seen problem in the past with the cursor being badly placed, just not recently.
How the code maintains the cursor position is an awful mess -- something I dare not touch :-)

**Comment by flatcap** [comment]
Upstream have made some changes to how the refreshes are done.
Does this problem still occur?

**Comment by ElDeveloper** [comment]
Just checked this with the tip in neomutt (master 43b949fb) and this
still happens.

**Comment by nshi** [comment]
I'm also experiencing the same behavior using NeoMutt 20200313 on Mac, installed via homebrew. Whenever I delete a message from my Gmail inbox, it randomly jumps to another message. Any updates on this? Thanks.
