### ISSUE TITLE
in current master, setting my_user produces an error

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#520]
* **bug reports**

    * Steps to reproduce

```
$ cat testMuttrc
set my_user = "test"
$ ./mutt -F muttrc
Error in /home/toogley/src/neomutt/testMuttrc, line1:
source: errors in /home/toogley/src/neomutt/testMuttrc
Press any key to continue...
```

* Used program versions

`Neomutt 20170306-213-de1898 (1.8.0)`

At least the [UPDATING](https://github.com/neomutt/neomutt/blob/master/UPDATING) showed no removal of this option.

**Comment by gahr** [comment]
Confirmed. It's because of the first diff chunk in init.c of fa7443c.
