### ISSUE TITLE
improving the status:* labels for pull requests.

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#529]
In this issue, i talk **only** about the `status:*` labels and how i'd like to improve them. Currently, i feel that the process of managing pull requests is

* confusing, because important labels are not precisely defined. For instance, what's the difference between `status:ready` and `status:backlog`?

* inconvenient. I see labels as method to communicate between project members and especially from the reviewers team and other participants. That means, at the moment, I have to read the conversation to figure out what the current status is and even then, the status is sometimes unknown. (Kind of, its of course not really bad. But i think its worth to improve)

Therefore, would like to suggest mainly a new "review & merge worflow" which i have drawn in a state diagram below. I feel i can communicate that better visually.

![test_neomutt_pull_requests_review](https://cloud.githubusercontent.com/assets/9417950/25072559/df454b62-22d1-11e7-9cc3-943c397e1f44.png)

That means, i would also **suggest** some changes in our "labeling workflow":

* the labels for "review & merge" should be only used on pull requests, not issues.

* **only** persons of the github reviewers team should change those "review & merge workflow" labels. The reviewing people are the only people who decide if PR's are merged or not. Therefore also only those people should set those labels. The other labels, can be also set by other people.

* In my diagram, everything except ("good" and "merged") and the conditional should be `status` labels. (i don't care if they are prepended by "status", i just mean to be consistent.) ".

* At the moment, every Pull request is labeled with `status:backlog`. I would change that to `status:in-progress` or so and only when people call for the @neomutt/reviewers team, the label should (ideally automatically) change to `status:needs-review`.

* i also like comments like https://github.com/neomutt/neomutt/pull/202#issuecomment-294319440 when such a label is changed, because it was not self-explanatory, in my humble opinion.

* do not use any other label for this "review & merge workflow", e.g. the `status:discuss` or `status:new-bug`. Those two labels should maybe removed or renamed.

* the idea of these suggested changes is to simplify the "review & merge workflow" to "what has to be done before this PR can be merged?" and nothing more. (KISS principle)

Therefore i ask the questions specifically directed at @neomutt/reviewers:

* Do you feel my suggestions are improving the current state?
* What is your general opinion on this topic?
* What do you *not* like about these suggestions?
* @gahr I'm not sure how good this style of workflow works with issues and branches as a replacement of pull requests, therefore my suggestion to use pull requests every time. Do you like using the "branch/issue" workflow better instead of pull requests? 

[**EDIT**: after thinking again about this, i don't think its really necessary to have a PR every time (although, i consider that more clean)]

**Comment by toogley** [comment]
It seems that you @neomutt/reviewers are not interested in these suggestions? Therefore, i guess, i can close this?

**Comment by flatcap** [comment]
Thanks for your work, @toogley.
As you can see, it's hard to motivate people into project management.
