### ISSUE TITLE
Keybase support for neomutt?

### ISSUE THREAD

**Issue by JakkinStewart** [neomutt/neomutt#53]
Is there any interest in adding Keybase support to neomutt? If anyone is unaware, [Keybase](https://keybase.io/) is a new platform for managing keys. It is attempting to simplify PGP key management and make it more available to the masses.
Unfortunately, it's command line output is drastically different from gpg, making it very difficult to send inline signatures or messages. It does seem to be possible to create a "hacky" script to create attachments for neomutt to use.
I'll be looking into the pgp files on my own time to see about modifying them to allow for keybase, but, as I'm still new to C, I'm not sure how much headway I'll make.

**Comment by flatcap** [comment]
@JakkinStewart 

> Is there any interest in adding Keybase support to neomutt?

You're the first person to mention it :-)

> It does seem to be possible to create a "hacky" script to create attachments for neomutt to use.

If you can get something to work, however "hacky", I'd love to see it.  I'm keen to try out all ideas in NeoMutt.
Use the comments to add questions and tell us about your progress.

**Comment by JakkinStewart** [comment]
I've been able to create a python script to work with keybase and the temporary mutt files in /tmp.
The script uses keybase's '-i' and '-o' flags to read and overwrite the temp files in /tmp. That way the original text is overwritten there won't be a security leak.
Unfortunately, the script can only encrypt and sign emails, but not decrypt or verify them. (As of right now, I only know how to make macros for the "index" and "compose" tags. I don't know what any of the others mean.)
So I created two bash scripts that will take a piped version of the email and decrypt or verify them against keybase.
I've included my edited .muttrc and my scripts [here](https://github.com/JakkinStewart/KeybaseMutt).
Its a long way from being mature, but it works for now.

**Comment by flatcap** [comment]
That looks like a good start.
I'll announce it at the next release and we'll see if we can find some more Keybase users to test it.

**Comment by flatcap** [comment]
@JakkinStewart 
I'm making a release on Friday.  Would you like your scripts to be included?

I see a repo [JakkinStewart/KeybaseMutt](https://github.com/JakkinStewart/KeybaseMutt) and a [Gist](https://gist.github.com/JakkinStewart/eaf0451c0e78984514fad97bf0458c9a).

Is there any reason the Gist isn't in the main repo?
Is there anything else?

**Comment by JakkinStewart** [comment]
Sorry for the late response, haven't logged in for a while. You can feel free to include the scripts.
As for the why the gist isn't included, life got in the way and I never got around to placing it into the main repo. I'll do that next.

**Comment by flatcap** [comment]
Aha!  Welcome back.
I've:
- Created a new branch [contrib/keybase](https://github.com/neomutt/neomutt/tree/contrib/keybase)
- Committed your changes
- Invited you to join NeoMutt

Once you've accepted the invitation, you can commit directly to NeoMutt -- Be careful :-)
Anything you put in that contrib directory will be released in doc/contrib/keybase

Please can you merge the gist into README.md (that way the instructions will show up when the branch is viewed on GitHub).

Then, re-read it imagining that you are a complete newbie to Keybase, checking it makes sense.
Once that's done, I can put it in the next release.

Any questions?
(I'm also in #neomutt on irc.freenode.net if you want to say hello).

**Comment by flatcap** [comment]
Lovely job!  Merged.
