### ISSUE TITLE
Followup issue of PR: "refactoring // cleanup of legacy files"

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#530]
(updated on 07. december 2017)

Followup issue of #497 

* ~~What should we do with `UPDATING.kz ` ? I'm not sure if a merge into `UPDATING` is a good idea? or should we just delete it?~~

* What about [txt2c.c](https://github.com/neomutt/neomutt/blob/master/txt2c.c) and [txt2c.sh](https://github.com/neomutt/neomutt/blob/master/txt2c.sh) ?

* ~~What about [m4/funcdecl](https://github.com/neomutt/neomutt/blob/master/m4/funcdecl.m4) ?~~

* ~~What about [instdoc.sh.in](https://github.com/neomutt/neomutt/blob/master/doc/instdoc.sh.in) ? Shouldn't that be done in the Makefile?~~

* ~~what about [contrib/ca-bundle.crt](https://github.com/neomutt/neomutt/blob/master/contrib/ca-bundle.crt) ? Isn't that normally installed by the distributions?~~

* ~~what about the [contrib/iconv](https://github.com/neomutt/neomutt/tree/master/contrib/iconv) folder?~~

* what about the [language](https://github.com/neomutt/neomutt/blob/master/contrib/language50.txt) files [in the contrib dir](https://github.com/neomutt/neomutt/blob/master/contrib/language.txt) ?

----------

Remaining to fix:

(**Note**: The basic idea of this issue is to integrate documentation files which are not related to the manual, the manpages or the website into the manual, some manpage or the website.)

* [README.SSL](https://github.com/neomutt/neomutt/blob/master/README.SSL)
* [doc/PGP-Notes.txt](https://github.com/neomutt/neomutt/blob/master/doc/PGP-Notes.txt)
* ~~[doc/applying-patches.txt](https://github.com/neomutt/neomutt/blob/master/doc/applying-patches.txt)~~
* [smime-notes.txt](https://github.com/neomutt/neomutt/blob/master/doc/smime-notes.txt)
* ~~[patch-notes.txt](https://github.com/neomutt/neomutt/blob/master/doc/patch-notes.txt)~~

**Comment by gahr** [comment]
m4/funcdecl is used by autoconf.ac

**Comment by toogley** [comment]
@gahr initially, my reason to ask was that the file last edited 17 years ago. But only now i realized that that is a really silly reason to think a file is legacy.
