### ISSUE TITLE
from_chars strange effect

### ISSUE THREAD

**Issue by nobrowser** [neomutt/neomutt#533]
I'm the original author of the from_chars patch, so I think I know how it should work.

In my `.muttrc` I have:

`from_chars=">+-\r"`

In mutt.org mutt plus my patch, this adds a `>` prefix to the `%F` column of mails I sent. (I'm one of those people who like to have sent mails in the inbox.)  It leaves untouched index entries of mails I received.

But in neomutt, it prefixes the `%F` column of received mails with a question mark.  This feels as if some code, perhaps related to i18n or wide chars, misinterprets the `\r`.

I'll eventually assign myself after a few days if nobody takes it.

**Comment by nobrowser** [comment]
The problem is that there is confusion about whether the configuration variable `Fromchars` is a plain string, or a multi-byte character table.

I remember when @flatcap initially merged my patch, he said that he modified it such that multi-byte character could be used for the prefixes.  And at present in `HEAD`, the variable is declared in `init.h` as a `DT_MBCHARTBL`.  But at the point where it is used -- namely in the function `make_from_prefix` in `hdrline.c` -- it is used very much like a plain string.

I tried to change the code in `make_from_prefix`, but I don't know how to convert a multi-byte character with `snprintf` to get it into a normal string buffer.  Anyone able to lend a hand/brain?

**Comment by nobrowser** [comment]
How is [this](https://github.com/neomutt/neomutt/blob/master/init.c#L287) not completely broken?  Where is `d` getting set?  (It _should_ be the first argument to `mbrtowc`, methinks, instead of `NULL`.)

**Comment by d-k-c** [comment]
Well, it seems this piece of code is only interested in determining how many bytes are in a multi-byte char, but the value itself is copied the old-fashion way (L301-303). As for `d`, it's allocated line 284, and set line 302. Does that answer your question or I'm completely off?

**Comment by nobrowser** [comment]
@d-k-c you do answer my question.

The confusion was mine: I assumed that function was decoding into wide chars (UCS-4) while it apparently just copies the encoded representation (UTF-8 or whatever).

**Comment by flatcap** [comment]
I've just had a chance to look at the code.
We started with @nobrowser's patch, which I tweaked to allow multi-byte chars.  Everyone was happy :-)
Then upstream adopted it and extended it to flag_chars, from_chars, status_chars, to_chars.

There are two problems:
- `\r` isn't magic any more -- a small tweak to `parse_mbchar_table()` will fix that
- An extra space -- a check in `make_from_prefix()` can eliminate this

**Comment by nobrowser** [comment]
@flatcap , thanks for the archaeological research :-)

I note that the reason I chose the strange way of configuring the feature (instead of the natural way, ie. a separate string variable for each case) was that a feature proposed on the `mutt-users` mailing list (this one or a different one, I don't remember) was shot down because 

> We already have too many configuration variables.

And I agree.

Then they add more, breaking my code. LOL
