### ISSUE TITLE
Could  '^g' be remapped?

### ISSUE THREAD

**Issue by Alok** [neomutt/neomutt#535]
I use vim and I'm used to esc exiting things. I see that [`mutt_getch()`](https://github.com/neomutt/neomutt/blob/0b1fcd44bcabb08c7a5a9b796a93aea9aec653cd/curs_lib.c#L155) (line 155) is hardcoded to recognize `^G`. Could that be made remappable?

**Comment by flatcap** [comment]
There was a thread on mutt-dev recently: [For vi-like binding users, use Esc key to abort commands](https://marc.info/?t=148804080800003)

The conclusion was that the changes would be too intrusive (and possibly quite a bit of work).

I'm not saying no, but I'd need some solid convincing.

**Comment by guyzmo** [comment]
well, as discussed a few times, I believe the `abort-key` should be made bindable like any other key. Whether you want it on <kbd>C-c</kbd> or <kbd>C-g</kbd> does not really matter (though it might be dumb to put it straight on a alphanum key).

another related topic that I believe has been discussed on neomutt, was to warn users against conflicts in keybindings (if you want to bind <kbd>C-g</kbd><kbd>g</kbd> but <kbd>C-g</kbd> is already bound to abort-key…).

**Comment by Alok** [comment]
About the only convincing I have is that it seems more architecturally pure to make it remappable and that I use vim and my fingers itch when escape doesn't do anything.

**Comment by guyzmo** [comment]
actually the abort-key binding could be set on several keys as well (<kbd>esc</kbd>, <kbd>C-g</kbd>, <kbd>C-c</kbd>…)

**Comment by flatcap** [comment]
Sorry, this enhancement didn't attract someone to write some code.
This issue will now be closed, but listed on the [Closed Discussions](https://www.neomutt.org/dev/discussions) page.
