### ISSUE TITLE
Require POSIX compliance?

### ISSUE THREAD

**Issue by d-k-c** [neomutt/neomutt#538]
I was working on cleaning up some stuff in configure.ac, but I went too far and I ended up reading C99 standard and POSIX manual. Time to take a step back!

It seems that Mutt is in a strange situation. We check for a lot of stuff in our configure, have some workarounds if some of them are not defined, but it seems that in the end we require a system that is POSIX compliant. For instance, a lot of POSIX headers are included unconditionally like sys/time.h which is included in init.c without checking if HAVE_SYS_TIME_H is defined or not.

My point is that it looks to me like Mutt already requires a POSIX compliant system in order to build. If this is the case and we agree on that, then we could make the configure more focused on checking real dependencies, like external libs for header caches or crypto features; remove checks for C99/POSIX features (test it just once), and remove HAVE_FOOBAR in the code that we know always end up to be set to 1.

I started some work here, if you want to take a look but I think last commit breaks the compilation:
https://github.com/d-k-c/neomutt/tree/devel/configure-diet

I'd like more inputs. Do some of you use systems that are not POSIX compliant but still manage to build Mutt?

**Comment by gahr** [comment]
I'm totally in favor of removing useless tests from configure.ac. However, please do not put too many constraints on a system. There are many operating systems out there that implement (a huge part of) the SUS without claiming compliance to (the latest|any) POSIX standard(s).

Your latest [commit](https://github.com/d-k-c/neomutt/commit/c23b703e7a09ed4cfbccb47d051ce905e88e148b) breaks the build on FreeBSD, where _POSIX_VERSION is [defined](https://svnweb.freebsd.org/base/head/sys/sys/unistd.h?revision=314436&view=markup#l97) to `200112L`.

**Comment by flatcap** [comment]
How far back to the BSD's LTS versions go?
Debian's too?

Are these the oldest we'll need to consider?

BTW, time for `./configure`:
- before: **6.3**s
- after: **3.5**s

**Comment by gahr** [comment]
Here's a list of [supported FreeBSD releases](https://www.freebsd.org/security/security.html#sup). I don't see us switching that defined to `200809L` anytime soon. My point is that we don't need to be strict about POSIX compliance.

Let's just get rid of the header files and functions checks for things that are in POSIX, and let's defer failure to compile time rather than configure time. How worse can it be?

**Comment by flatcap** [comment]
@gahr 
I've had a think about this...  What you're suggesting is to reduce `configure` to just an "option setter".
Hmm... that would certainly make it a lot simpler.  At that point, would we need autoconf at all?

As for the "fail-at-compile-time"...
Part of me wants to say, "that's ugly, we should check first"
But a bigger part is saying, "dump all the tests and we can reinstate the ones we need"

Upstream mutt supported a huge number of platforms -- in the past.
Some of those platforms have died off.  Some moved with the times.

I'm happy with dumping any tests that aren't needed for Linux/BSD/MacOS -- cater for the 99%.
After a year, I haven't heard of any exotic platforms.  **When** we do, we can accommodate them.

**Comment by d-k-c** [comment]
@gahr I used this version because some stuff are only specified in the 2008 version, but maybe the spec is partially implemented in FreeBSD.

To keep us safe, maybe we could start by dropping all checks for stuff that are in POSIX 2001, and determine on the case-by-case basis for the rest? What do you think of this?

**Comment by gahr** [comment]
@d-k-c I think it's the wrong approach. The fact that we use APIs defined by POSIX does not mean that non-strict-POSIX systems won't be able to build neomutt. Even more so when most systems can't be bothered by going through a POSIX compliance test.

If we deem the APIs to be common enough, let's just use them and perhaps fail to compile. If we are not sure and want to provide in-house alternatives, the current way is the way to go.
But please let's not say "we won't build unless you advertise yourself as POSIX-xyz compliant.

**Comment by d-k-c** [comment]
Sorry I've stated it poorly, but I think we have the same point: drop tests for the API we deem common enough (ie. all the stuff that are in POSIX 2001), and don't add additional check on POSIX version (unlike my PR).

**Comment by gahr** [comment]
I probably misread your previous comment. We're on the same page ;)

**Comment by flatcap** [comment]
FYI: I've scraped a list of functions from the relevant specifications.
[This gist](https://gist.github.com/flatcap/8384158209f4576d3f213f393dc3b7e0) contains:
- [c99.txt](https://gist.github.com/flatcap/8384158209f4576d3f213f393dc3b7e0#file-c99-txt) - All the functions defined by C99
- [2001.txt](https://gist.github.com/flatcap/8384158209f4576d3f213f393dc3b7e0#file-2001-txt) - Additional functions, not in C99, defined by IEEE Std 1003.1-2001
- [2008.txt](https://gist.github.com/flatcap/8384158209f4576d3f213f393dc3b7e0#file-2008-txt) - Additional functions, not in 2001, defined by IEEE Std 1003.1-2008

There are just 4 occurrences of '2008 functions' in the mutt code:
- `fmemopen()`/`open_memstream()` -- protected by `USE_FMEMOPEN`
- `futimens()` -- protected by `HAVE_FUTIMENS`
- `wcscasecmp()` -- simplified in-house version
- `mkdtemp()` -- somebody removed the in-house replacement d6a1070 :-)

**Comment by gahr** [comment]
Wow, that's cool stuff! Bookmarked ;)

**Comment by gahr** [comment]
Uhm.. perhaps the crawling needs some fixing. I see va_* appearing in the 2001.txt list, although they are all c89 excepy va_copy, which is c99.

**Comment by gahr** [comment]
Oh, perhaps the 2001 and 2008 are lists *including* the std c functions? They both contain printf.

**Comment by flatcap** [comment]
I've moved va_* to c99.
There aren't any duplicates (though there are a lot of different *printf's.
`sort * | uniq -d | wc -l` shows 0

I've promoted them to the management repo (for now): [README](https://github.com/neomutt/management/blob/master/standard-functions/README.md)

Feel free to correct/improve.

**Comment by gahr** [comment]
Sorry, my bad. I was looking at it on the phone and didn't notice that any of those links open to a page where all the three files are shown :/

**Comment by flatcap** [comment]
PR #564 strips out all the POSIX:2001 tests.

There are a few functions left in the code that aren't compliant:

1. Functions used conditionally within features
    `fmemopen`, `open_memstream`
2. Functions from POSIX:2008/GNU/BSD that are tested for, but used conditionally
    `fgets_unlocked`, `futimens`, `flock`
3. Functions from POSIX:2008 that are tested for, but used unconditionally
    `mkdtemp`, `strsep`

There used to be a compatibility version of `mkdtemp` in our code.  We may need to re-instate it.
`strsep` is used unconditionally in upstream mutt.

**Comment by gahr** [comment]
As I said, I don't think the distinction should be made on the basis of POSIX compliance, but rather on whether a certain functionality is widely available. If `strsep` is available on all platforms we're able to test and on which we have active users, then let's use it, no matter if it's in c99, c11, posix 2001, 2008, or any other standards.

**Comment by nobrowser** [comment]
But how do you know it behaves exactly as you expect on every platform where it exists? That way we may have to *introduce* new configure tests, and not  eliminate them.

**Comment by d-k-c** [comment]
Agreed with @gahr, let's drop the check as it doesn't bring much value.

And there are no garantees that `malloc` really does a memory allocation even if we check it with `AC_CHECK_FUNC`. Our stand here is that we assume that people use sane systems that are at least POSIX-2001 compliant (even if we don't explicitely check for that dependency), because we don't want to carry custom implementations for functions available on 99.9% of the systems on which people want to run Mutt.

**Comment by flatcap** [comment]
Hmm... I'd rather leave the 2001 test in.
It's a very low hurdle, but it defines our baseline build requirement.
We can give developers an explicit list of headers/functions they may use (including the sanctioned extras listed above).

Moving forward, I agree we should allow functions based general availability.

**Comment by gahr** [comment]
Please have a look at [this](http://www.gnu.org/software/libc/manual/html_node/Version-Supported.html), especially at the ***Usage Note***. Then  please reconsider leaving that check in.

**Comment by flatcap** [comment]
Ok, fair enough.
@gahr Are you happy with the other commits?

**Comment by gahr** [comment]
I haven't looked at the details (like, reviewed it line by line), but the approach looks good to me.
