### ISSUE TITLE
Sidebar and DB_ENV problems

### ISSUE THREAD

**Issue by rapha8l** [neomutt/neomutt#54]
Hi, I'm building neomutt on Debian with : ./configure --program-prefix=neo --enable-sidebar --enable-notmuch --enable-compressed --enable-pop --enable-imap --enable-smtp --enable-exact-address --enable-hcache --enable-quick-build --disable-full-doc --enable-locales-fix

At first run, I get "sidebar_delim: unknown variable" (which is not much a problem)
But also : "DB_ENV->rep_set_request: Invalid min or max values" which I can't see where it can come from

The display is almost broken,  first message appears as a ghost on first line, and navigating between lines makes everything "move" in a strange way

Thanks

Raphaël

**Comment by flatcap** [comment]
Hi @rapha8l, thanks for the report.

> sidebar_delim: unknown variable

Some of the config was renamed, a while back, to better match Mutt.
There's a list of changes in the [Sidebar Intro](http://www.neomutt.org/sidebar-intro.html#intro-sidebar-config-changes).

> DB_ENV->rep_set_request: Invalid min or max values

Hmm... I don't know what that is.  I'll investigate.

**Comment by rapha8l** [comment]
Thanks a lot, 
I forgot to tell that the conf works well with mutt (1.6) and mutt kz.
If needed, I may add a screenshot

**Comment by flatcap** [comment]
> the conf works well with mutt (1.6) and mutt kz.

Ah, that's good to know.

I've had a quick look and I don't know what's going on.

The error comes from the BDB (the Berkeley DataBase) libraries, but by default Mutt doesn't use them
You're configuring Mutt to use caching (--enable-hcache).  I'm wondering if you have the BDB devel libraries installed, but not Mutt's default which is TokyoCabinet.

What's the output of these commands:

```
./mutt -v | grep "^hcache"
ldd mutt
```

> I may add a screenshot

I don't think that would help me, it's always interesting to see other people's desktops :-)

**Comment by rapha8l** [comment]
./mutt -v | grep "^hcache"                                                                               
hcache backend: Berkeley DB 5.3.28: (September  9, 2013)

ldd ./mutt                                                           
        linux-vdso.so.1 (0x00007ffcf37f0000)
        libncursesw.so.5 => /lib/x86_64-linux-gnu/libncursesw.so.5 (0x00007fd2241b9000)                                                                                libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fd223f8f000)                                                                                      libidn.so.11 => /lib/x86_64-linux-gnu/libidn.so.11 (0x00007fd223d5a000)
        libnotmuch.so.4 => /usr/lib/x86_64-linux-gnu/libnotmuch.so.4 (0x00007fd223b35000)                                                                              libdb-5.1.so => /usr/lib/x86_64-linux-gnu/libdb-5.1.so (0x00007fd2237b4000)                                                                                    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd22340f000)                                                                                              libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd22320b000)
        libgmime-2.6.so.0 => /usr/lib/x86_64-linux-gnu/libgmime-2.6.so.0 (0x00007fd222f99000)                                                                          libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fd222d45000)                                                                      libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fd222a34000)
        libtalloc.so.2 => /usr/lib/x86_64-linux-gnu/libtalloc.so.2 (0x00007fd222820000)                                                                                libxapian.so.22 => /usr/lib/x86_64-linux-gnu/libxapian.so.22 (0x00007fd22241b000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd22209b000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd221e85000)                                                                                      libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd221c67000)                                                                                  /lib64/ld-linux-x86-64.so.2 (0x0000559180d5c000)                                                                                                               libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fd221a63000)                                                                      libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007fd221861000)                                                                      libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fd2214d8000)                                                                              libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd2212bd000)                                                                                              libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007fd2210a5000)                                                                                          libgpgme-pthread.so.11 => /usr/lib/x86_64-linux-gnu/libgpgme-pthread.so.11 (0x00007fd220e67000)                                                                libassuan.so.0 => /usr/lib/x86_64-linux-gnu/libassuan.so.0 (0x00007fd220c54000)                                                                                libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fd220a40000)                                                                              libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fd220836000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fd2205c6000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fd2203c1000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd2200c2000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fd21fe9b000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fd21fc83000)

I'll try for the screenshot :-)

**Comment by flatcap** [comment]
Aha!  Try installing the devel libs for TokyoCabinet.  As root:
```
apt-get install libtokyocabinet-dev
```
Then re-rerun configure with the same options and re-run make.
This time Mutt should be compiled with a working database backend.

**Comment by rapha8l** [comment]
Thanks a lot for your quick answer.
Indeed, it worked perfectly well and resolved the visual glitches I encountered
Still the sidebar_delim which works with plain mutt, but it's not much a problem

Thanks again !

**Comment by flatcap** [comment]
Great.

> sidebar_delim

I mentioned that.  There were some config renames:
There's a list of changes in the [Sidebar Intro](http://www.neomutt.org/sidebar-intro.html#intro-sidebar-config-changes).

**Comment by rapha8l** [comment]
I'll have a look thanks
