### ISSUE TITLE
Compilation fails on Mac OS X

### ISSUE THREAD

**Issue by hvkls** [neomutt/neomutt#543]
(Please find details on my system below)

Issue 1: cannot find iconv

I tried
./configure --with-libiconv-prefix=/opt/local
./configure --with-libiconv-prefix=/opt/local/lib
./configure --with-libiconv-prefix=/opt/local/include
and finally resorted to symlinks in /usr/local/{include,lib} to the originals in /opt/local/{include,lib}. This worked, but there is something wrong nonetheless.

Issue 2: cannot compile on architecture x86_64

clang: warning: optimization flag '-fno-delete-null-pointer-checks' is not supported
mv -f .deps/main.Tpo .deps/main.Po
gcc  -Wall -pedantic -Wno-long-long -g -O2 -fno-delete-null-pointer-checks  -L/opt/sdk/lib -L/var/sdk/lib -L/opt/lib -L/usr/local/lib -L/usr/lib -L/var/lib -L/lib -L. -L/opt/lib -L/opt/local/lib -o mutt addrbook.o alias.o ascii.o attach.o base64.o browser.o buffer.o buffy.o charset.o color.o commands.o complete.o compose.o copy.o crypt_mod.o crypt.o cryptglue.o curs_lib.o curs_main.o date.o edit.o editmsg.o enter.o filter.o flags.o from.o getdomain.o group.o handler.o hash.o hdrline.o headers.o help.o history.o hook.o init.o keymap.o lib.o main.o mbox.o mbyte.o menu.o mh.o muttlib.o mutt_idna.o mutt_sasl_plain.o mx.o pager.o parse.o pattern.o postpone.o query.o recvattach.o recvcmd.o rfc1524.o rfc2047.o rfc2231.o rfc3676.o rfc822.o safe_asprintf.o score.o send.o sendlib.o signal.o sort.o status.o system.o thread.o url.o version.o mutt_notmuch.o patchlist.o conststrings.o  crypt_gpgme.o crypt_mod_pgp_gpgme.o crypt_mod_smime_gpgme.o pgp.o pgpinvoke.o pgpkey.o pgplib.o gnupgparse.o pgpmicalg.o pgppacket.o crypt_mod_pgp_classic.o smime.o crypt_mod_smime_classic.o sidebar.o compress.o resize.o pop.o pop_lib.o pop_auth.o nntp.o newsrc.o smtp.o bcache.o account.o mutt_socket.o mutt_tunnel.o mutt_ssl.o mutt_sasl.o hcache_kc.o hcache.o md5.o  -Limap -limap -lncursesw -L/opt/local/lib -dynamic -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lssl -lcrypto -lz -lsasl2  -lkyotocabinet -lidn  -lintl -Wl,-framework -Wl,CoreFoundation -liconv -L/opt/local/lib -lgpgme -lassuan -lgpg-error -lnotmuch -lncursesw -lnotmuch 
ld: warning: directory not found for option '-L/opt/sdk/lib'
ld: warning: directory not found for option '-L/var/sdk/lib'
ld: warning: directory not found for option '-L/lib'
Undefined symbols for architecture x86_64:
  "_SSL_CTX_set1_param", referenced from:
      _ssl_set_verify_partial in mutt_ssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Information on my system:

Mac OS X 10.11.6 (El Cap.) w/ MacPorts 2.4.1

uname -a
Darwin noname 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64

port contents libiconv | grep -v share
Port libiconv contains:
  /opt/local/bin/iconv
  /opt/local/include/iconv.h
  /opt/local/include/libcharset.h
  /opt/local/include/localcharset.h
  /opt/local/lib/libcharset.1.dylib
  /opt/local/lib/libcharset.a
  /opt/local/lib/libcharset.dylib
  /opt/local/lib/libiconv.2.dylib
  /opt/local/lib/libiconv.a
  /opt/local/lib/libiconv.dylib

**Comment by flatcap** [comment]
Hi @hvkls,

For now please copy this file [gpgme.m4](https://github.com/neomutt/neomutt/raw/b8622bb44069e816e2876d9b124ef9a84768953b/m4/gpgme.m4) into the m4 source dir.

**Comment by flatcap** [comment]
Sorry, ignore the previous answer.

**Comment by flatcap** [comment]
First:  Did the previous release (2017-03-06) compile correctly?
Since then, we've changed the build process a bit, but not _what_ we compile.

---

**libiconv**:  In the previous release, we shipped `m4/iconv.m4` which locates and tests for the iconv libraries.
This **didn't** look in `/opt/local`.  Now, the build takes that file from your build environment.

If you want to specify alternate library dirs, try:
```
./configure 'LDFLAGS=-L/opt/local/lib' 'CFLAGS=-I/opt/local/include'
```

---

The next bit is confusing:

> clang: warning: optimization flag '-fno-delete-null-pointer-checks' is not supported
> gcc -Wall -pedantic -Wno-long-long -g -O2 -fno-delete-null-pointer-checks ...
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Which compiler are you using?
Is clang pretending to be gcc?

---

> Undefined symbols for architecture x86_64:
> "_SSL_CTX_set1_param", referenced from: _ssl_set_verify_partial in mutt_ssl.o

This is from new, upstream, code.
If `configure` finds the header file `openssl/x509_vfy.h` it defines the symbol: `HAVE_SSL_PARTIAL_CHAIN`

Is `SSL_CTX_set1_param()` defined in `<openssl/ssl.h>` ?

**Comment by darnir** [comment]
If this is a OSX system, then yes, clang is pretending to be gcc. I've seen this in the past, gcc is just an alias to clang on Mac systems. 

On 22 April 2017 3:19:18 PM GMT+02:00, Richard Russon <notifications@github.com> wrote:
>First:  Did the previous release (2017-03-06) compile correctly?
>Since then, we've changed the build process a bit, but not _what_ we
>compile.
>
>---
>
>**libiconv**:  In the previous release, we shipped `m4/iconv.m4` which
>locates and tests for the iconv libraries.
>This **didn't** look in `/opt/local`.  Now, the build takes that file
>from your build environment.
>
>If you want to specify alternate library dirs, try:
>```
>./configure 'LDFLAGS=-L/opt/local/lib' 'CFLAGS=-I/opt/local/include'
>```
>
>---
>
>The next bit is confusing:
>
>> clang: warning: optimization flag '-fno-delete-null-pointer-checks'
>is not supported
>> gcc -Wall -pedantic -Wno-long-long -g -O2
>-fno-delete-null-pointer-checks ...
>> clang: error: linker command failed with exit code 1 (use -v to see
>invocation)
>
>Which compiler are you using?
>Is clang pretending to be gcc?
>
>---
>
>> Undefined symbols for architecture x86_64:
>> "_SSL_CTX_set1_param", referenced from: _ssl_set_verify_partial in
>mutt_ssl.o
>
>This is from new, upstream, code.
>If `configure` finds the header file `openssl/x509_vfy.h` it defines
>the symbol: `HAVE_SSL_PARTIAL_CHAIN`
>
>Is `SSL_CTX_set1_param()` defined in `<openssl/ssl.h>` ?
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/neomutt/neomutt/issues/543#issuecomment-296372742

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by flatcap** [comment]
Ah, good to know.
Then we probably need to change this check in `configure.ac`
```sh
if test "$CC" = "gcc"; then
        CFLAGS="$CFLAGS -fno-delete-null-pointer-checks"
fi
```

**Comment by hvkls** [comment]
> If configure finds the header file openssl/x509_vfy.h it defines the symbol: HAVE_SSL_PARTIAL_CHAIN
I'm not sure if I got you right; there is no HAVE_SSL_PARTIAL_CHAIN here in openssl/x509_vfy.h

> Is SSL_CTX_set1_param() defined in <openssl/ssl.h> ?
int SSL_CTX_set1_param(SSL_CTX *ctx, X509_VERIFY_PARAM *vpm);
int SSL_set1_param(SSL *ssl, X509_VERIFY_PARAM *vpm);

**Comment by flatcap** [comment]
Sorry, `configure` defines `HAVE_SSL_PARTIAL_CHAIN` which is used in the mutt code.

> int SSL_CTX_set1_param(SSL_CTX *ctx, X509_VERIFY_PARAM *vpm);

Hmm... The header file has the function, but when you link with `-lssl` the function isn't found.
Could there be more than one version of the SSL libraries installed?

**Comment by gahr** [comment]
@hvkls Any chance you can upgrade to macOS 10.12 (Sierra)?

Apple LLVM version 8.1.0 (clang-802.0.41) *handles* `-fno-delete-null-pointer-checks` just fine. The flag is not supported, so you'll get this warning (but not an error):

`clang: warning: optimization flag '-fno-delete-null-pointer-checks' is not supported [-Wignored-optimization-argument]`

I use [homebrew](https://brew.sh/) to install 3rd party stuff on macOS and I can build neomutt as follows:

```sh
# install dependencies (see note 1)
% brew install autoconf automake gettext gpgme openssl

# tell autostuff where to find autopoint, as homebrew doesn't symlink it into /usr/local/bin
% setenv AUTOPOINT /usr/local/Cellar/gettext/0.19.8.1/bin/autopoint

# autostuff (see note 2)
% ./prepare --enable-imap --enable-gpgme --with-ssl=/usr/local/opt/openssl/

# build neomutt
% make
```

***Notes***
1. Because of #542 you'll need `gpgme` installed even if you don't plan on using it. 
2. Homebrew's OpenSSL is keg-only, so it's not symlinked to `/usr/local`, which is why you need to pass the `/usr/local/opt/openssl`to `--with-ssl`.

Hope this helps.

**Comment by Vaelatern** [comment]
@flatcap You should know that on many systems, like Void and OpenBSD, the default CC is `cc`
Name checks like `"${CC}" = "gcc"` don't work so well on such systems.
```
$ cc -v
Reading specs from /usr/lib/gcc-lib/amd64-unknown-openbsd6.0/4.2.1/specs
Target: amd64-unknown-openbsd6.0
Configured with: OpenBSD/amd64 system compiler
Thread model: posix
gcc version 4.2.1 20070719
```
```
$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-unknown-linux-gnu/6.3.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: /builddir/gcc-6.3.0/configure --build=x86_64-unknown-linux-gnu --enable-java-gc=boehm --enable-fast-character --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --libexecdir=/usr/lib --libdir=/usr/lib --enable-threads=posix --enable-__cxa_atexit --disable-multilib --with-system-zlib --enable-shared --enable-lto --enable-vtable-verify --enable-linker-build-id --enable-serial-configure --disable-werror --disable-nls --enable-checking=release --disable-libstdcxx-pch --with-isl --with-linker-hash-style=gnu --disable-libunwind-exceptions --disable-target-libiberty --with-default-libstdcxx-abi=gcc4-compatible --enable-languages=c,c++,objc,obj-c++,fortran,lto,java,go
Thread model: posix
gcc version 6.3.0 (GCC)
```

On one piece of software, I changed the check thus:
```
-if [ "$CCNAME" = "gcc" ]; then
+if [ "$(${CCNAME} --version | grep -c \(GCC\))" -gt 0 ]; then
```

**Comment by flatcap** [comment]
> clang: warning: optimization flag '-fno-delete-null-pointer-checks' is not supported [-Wignored-optimization-argument]

The flag was added to 'fix' a very strange interaction between gcc and mutt.  gcc was optimising-away some crucial checks -- leading to crashes.  clang didn't suffer from the problem.

> if [ "$(${CCNAME} --version | grep -c \(GCC\))" -gt 0 ]; then

@Vaelatern Thanks, that's a better idea

**Comment by hvkls** [comment]
@gahr

> Any chance you can upgrade to macOS 10.12 (Sierra)?

Not in the near future!

> Because of #542 you'll need gpgme installed even if you don't plan on using it.

I had that already installed.


@flatcap & @gahr

I've been able to compile NeoMutt 20170421-dirty (1.8.2) in the meantime. A combination of

_export CPPFLAGS_, export _LDFLAGS_, and _./configure --with-ssl=/opt/local/include/openssl_

got it through, somehow.

**Comment by Vaelatern** [comment]
@flatcap I might recommend instead: `if [ "$(${CCNAME} --version | grep -c 'gcc version')" -gt 0 ]; then` since that string was present on both OpenBSD and a Linux Distro.

**Comment by gahr** [comment]
@hvkls wouldn't --prefix=/opt/local help in your case?

**Comment by hvkls** [comment]
Thanks for the suggestion, but /opt/local is managed by[MacPorts](https://www.macports.org) here, I prefer to keep my own stuff in a separate place.

**Comment by hvkls** [comment]
New error 1 as of 2017-05-31 with notmouch:

gcc -DPKGDATADIR=\"/opt/share/mutt\" -DSYSCONFDIR=\"/opt/etc\" -DBINDIR=\"/opt/bin\" -DMUTTLOCALEDIR=\"/opt/share/locale\" -I.  -I. -I. -I/opt/local/include -I/opt/sdk/include -I/var/sdk/include -I/var/include -I/usr/include -I/usr/local/include -I/var/include -I/var -I/usr/include/gnutls -I/usr/lib/ssl/include -I/usr/include/ncursesw -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/var/stash/include -I. -I/opt/include -I/opt/local/include  -I/opt/local/include/openssl/include  -Wall -pedantic -Wno-long-long -g -O2 -fno-delete-null-pointer-checks -MT mutt_notmuch.o -MD -MP -MF .deps/mutt_notmuch.Tpo -c -o mutt_notmuch.o mutt_notmuch.c
clang: warning: optimization flag '-fno-delete-null-pointer-checks' is not supported
mutt_notmuch.c:47:10: fatal error: 'sys/sysmacros.h' file not found
#include <sys/sysmacros.h>
         ^

**Comment by flatcap** [comment]
> mutt_notmuch.c:47:10: fatal error: 'sys/sysmacros.h' file not found

Ah, sorry about that.  It's a false positive from IWYU.
It can be safely removed.  I'll remove before the release.

**Comment by hvkls** [comment]
The error is gone. Thank you once more!
