### ISSUE TITLE
Proposal for motto

### ISSUE THREAD

**Issue by Alok** [neomutt/neomutt#55]
Neomutt.org has the header:

The NeoMutt Project
“Bringing together all the Mutt Code”

I think this is better:

The Neomutt Project
"Teaching an old dog new tricks"

and then the original text in smaller font.

**Comment by flatcap** [comment]
@Alok
Oh, that's good!
Unless someone voices an object (unlikely), I'll change the motto for the next release.

Thank you.

**Comment by JakkinStewart** [comment]
I voice my approval of the new motto. :-)

**Comment by bitstreamout** [comment]
Hmm ... IMHO there is no reason at all to become rude or be seen from the other side to be rude and even if it is somekind of funny ... at least I want that all the stuff goes upstream ;)

**Comment by alexpearce** [comment]
I think ‘old dog’ generally has mildly negative connotations, but it would be best to ask the mutt maintainers either way, as they're the ones who may or may not be offended by it.

Otherwise, you could have something like “Same mutt, new tricks”. The hint to the saying is still there, but it's not explicit. Downside is that neomutt isn't the “same mutt”; it's much nicer!

**Comment by riesebie** [comment]
Is there really a need for a new motto? “Bringing together all the Mutt Code” meets the project to the full extent!

**Comment by darnir** [comment]
I didn't say anything at first when a motto was proposed. Let things 
take their way. But now that there's objections and arguments, my 
suggestion would be simply to let the old one stay. At this point, we 
really shouldn't be wasting our energies on the motto for the project.  
The actual code and patches is what is important and deserves our 
efforts

On 06/20, Elimar Riesebieter wrote:
>Is there really a need for a new motto? “Bringing together all the Mutt Code” meets the project to the full extent!
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/neomutt/neomutt/issues/55#issuecomment-227078529
-- 
Thanking You,
Darshit Shah

**Comment by flatcap** [comment]
It's funny, it's appropriate, it's common English expression.
I'm still in favour of the new motto (though less than before).

I'll drop a quiet email to the Mutt maintainers and see if they're outraged.

**Comment by pickfire** [comment]
Do we need to vote here? If yes, I vote for the new motto.

**Comment by flatcap** [comment]
**Update**: No objections from the Mutt devs :-)

**Comment by scottkosty** [comment]
I don't think we're taking a vote here, but I support the new motto.

**Comment by flatcap** [comment]
Apologies @Alok I've made a release but not changed the motto.
There are so many code changes that managing them was causing my brain to melt. As a result, anything that isn't code isn't in this new release.  I'm planning to make another release in about a week when I've tidied up the mess I've made.  **Then**, I will give the new motto the ceremony it deserves :-)
