### ISSUE TITLE
configure related tasks

### ISSUE THREAD

**Issue by d-k-c** [neomutt/neomutt#552]
Management task to keep track of development on configure/autools

- [ ] kill prepare.sh & document build process
- [ ] remove MUTTLIBS, rely only on LIBS (or find out why they should stay separate)
- [x] remove build flags that don't have external dependencies (#389). Please keep related `#ifdef HAVE_` in the code for now, so don't forget to keep the definitions for these symbols. See #528 for details.
  - [x] --enable-sidebar (#528)
  - [x] --enable-compressed
  - [x] --enable-pop
  - [x] --enable-imap
  - [x] --enable-nntp
  - [x] --enable-smtp
- [ ] add a developer flag `--enable-everything-available` that selects if available the following features: gpgme, gpg, smime, notmuch, lua, header cache backends, sasl, ssl, idn, gss. See #547 for the concept, limited to hcache for now.
- [ ] make `mutt -v` expand `--enable-everything`. So instead of `Configure options: --enable-everything`, it would display `Configure options: --enable--notmuch`. Same thing for `--enable-everything-available` once implemented.

**Comment by toogley** [comment]
>  kill prepare.sh 

why? I find its useful.

**Comment by flatcap** [comment]
I imagine all the developers have their own script / aliases to build neomutt their way.
`prepare.sh` doesn't really add anything.

Now that we're stripping out lots of configure options, there's less value that `prepare.sh` could add.
Anywhere a doc says "run prepare.sh", it might as well say run "autoreconf -i; ./configure [OPTIONS]"

**Comment by toogley** [comment]
Ah, okay. well that's true. => i'm fine with the removal.

**Comment by flatcap** [comment]
@d-k-c  Have you made any progress with MUTTLIBS vs LIBS?
I'd like to see that (user-visible bit) tidied up.

**Comment by d-k-c** [comment]
Not yet, I was quite busy moving to a new place. I'll give it a shot as soon as possible

**Comment by flatcap** [comment]
I think this can be closed now.
`prepare.sh` will go away when the autotools dies.
`LIBS` vs `MUTTLIBS` has been sorted
#547 --enable-everything-available has been closed (no thanks)
PR #946 expanded `--everything` in the autosetup build.
