### ISSUE TITLE
Sidebar new doesn't update

### ISSUE THREAD

**Issue by riesebie** [neomutt/neomutt#558]
Since neomutt-20170421 I have to scroll the sidebar to update the sidebar-new number. 
    * Expected behavior
Update the sidebar-new number after reading a new mail
    * Actual behavior
Updates after scroll the sidebar
    * Steps to reproduce
Just use the sidebar feature with sidebar_format='%B%?F? ?%* %6S%?N?(%N)?%?F?[%F]?'
    * Used program versions
NeoMutt 20170428-lxtec (1.8.2)
    * Operating System and its version
Debian sid

**Comment by l2dy** [comment]
Did you set `mail_check_stats`?

**Comment by riesebie** [comment]
`mail_check_stats = yes
mail_check_stats_interval = 30`

**Comment by riesebie** [comment]
Well, setting `mail_check_stats_interval = 1` does what I want. But why did the older versions worked with  `mail_check_stats_interval = 30` ?
