### ISSUE TITLE
what to do with the OPS files?

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#562]
In #528 a discussion about the further changes to the OPS files occured. I moved them from there into this separate issue, for clarity. 

@flatcap 
> I'm considering changing the format of the OPS file.

@d-k-c 
> Could you give more info on changing the format of the OPS file? I think OPS files should be dropped. I understand why there were here before, because it was easier to keep the enum and the strings in sync, but now that Mutt uses C99 we can use the enum values as array indexes of HelpStrings and get rid of keymap*.h generation.

(**Note**: I've removed the corresponding comments in #528)

**Comment by flatcap** [comment]
I was just planning something simple for now:
- Allowing horizontal whitespace (for alignment)
- Allowing comments and empty lines

As we make more features persistent (without config), we could combing more OPS files.
Comments would help keep things categorised.

As for removing the OPS files completely... I couldn't figure out **how**. 
`OPS` and `init.h` are too widely reused. ([diagram](https://www.neomutt.org/images/make.png))

**Comment by flatcap** [comment]
What is the preferred C way of keeping a list of enums and a list of strings in sync?

**Comment by gahr** [comment]
Something like this:

```c
#include <stdio.h>

#define ItemList \
Item(Foo) \
Item(Bar) \
Item(Baz)

#define Item(x) x,
enum ItemEnum {
	ItemList
	ItemCount
};
#undef Item

#define Item(x) #x,
const char * const ItemStrings[] = {
	ItemList
};
#undef Item

int main(void) {
	for (size_t i = 0; i < ItemCount; ++i)
	{
		printf("EnumItem # %zu is: %s\n", i, ItemStrings[i]);
	}
	return 0;
}
```

*output:*
```
EnumItem # 0 is: Foo
EnumItem # 1 is: Bar
EnumItem # 2 is: Baz
```

**Comment by flatcap** [comment]
I've extended your example to split the name from the string.
Also, I've added a conditional list.
```c
#include <stdio.h>

#define MuttList \
  Item(OP_COMPOSE_EDIT_BCC,         "edit the BCC list") \
  Item(OP_COMPOSE_EDIT_CC,          "edit the CC list") \
  Item(OP_COMPOSE_EDIT_DESCRIPTION, "edit attachment description")

#ifdef USE_SIDEBAR
#define SidebarList \
  Item(OP_SIDEBAR_NEXT,     "move the highlight to next mailbox") \
  Item(OP_SIDEBAR_NEXT_NEW, "move the highlight to next mailbox with new mail") \
  Item(OP_SIDEBAR_OPEN,     "open highlighted mailbox")
#endif

#define Item(e,s) e,
enum ItemEnum
{
  MuttList
#ifdef USE_SIDEBAR
  SidebarList
#endif
  ItemCount
};
#undef Item

#define Item(e,s) s,
const char *const ItemStrings[] = {
  MuttList
#ifdef USE_SIDEBAR
  SidebarList
#endif
};
#undef Item

int main(void)
{
  for (size_t i = 0; i < ItemCount; ++i)
  {
    printf("EnumItem # %zu is: %s\n", i, ItemStrings[i]);
  }

  printf("OP_COMPOSE_EDIT_BCC = %s\n", ItemStrings[OP_COMPOSE_EDIT_BCC]);
#ifdef USE_SIDEBAR
  printf("OP_SIDEBAR_NEXT_NEW = %s\n", ItemStrings[OP_SIDEBAR_NEXT_NEW]);
#endif

  return 0;
}
```

**Comment by d-k-c** [comment]
If you really want to go this way, I would change the second definition of Item to look like:

```
#define Item(e, s) [e] = s,
```

But I don't think this is the right way of doing it in our case. To me it would make sense to use a macro if it was used everywhere, but we have this weird OPS file to create a couple `(enum value, help string)`, but the op code is also present in `functions.h`, with a binding name and a default keybinding, and in a C file where the operation is actually implemented. So once again, we are in this weird in-between where some stuff are defined and generated through a Perl script, and other stuff are in regular C files. We should start by something simple to move all that in the Sea^H^H^HC world

I would go for something basic: add keymap_defs.h that contains ops like this:
```
enum mutt_ops { /* enum name optional */
	OP_NULL,
	OP_END_COND,
	OP_ATTACH_VIEW_MAILCAP,
	OP_ATTACH_VIEW_TEXT,
	OP_ATTACH_COLLAPSE,
/* [...] */
#ifdef USE_SIDEBAR
	OP_SIDEBAR_NEXT,
	OP_SIDEBAR_NEXT_NEW,
#endif
        OP_MAX,
};
```

and help strings in `help.c`:
```
static const char *help_strings[] = {
	[OP_NULL]                                     = N_("null operation"),
	[OP_END_COND]                          = N_("end of conditional execution (noop)"), 
        [OP_ATTACH_VIEW_MAILCAP]    = N_("force viewing of attachment using mailcap"),
	[OP_ATTACH_VIEW_TEXT]          = N_("view attachment as text"),
	[OP_ATTACH_COLLAPSE]            = N_("Toggle display of subparts"),
/* [...] */
#ifdef USE_SIDEBAR
	[OP_SIDEBAR_NEXT]                   = N_("move the highlight to next mailbox"),       
	[OP_SIDEBAR_NEXT_NEW]         = N_("move the highlight to next mailbox with new mail"),
        [OP_MAX]                                      = NULL,
};
```
After that, when everything is in C files, let's reconsider if we want a macro to define the OPS, and by that I mean everything related to OPS: help strings, function name, default keybinding, etc.

**Comment by gahr** [comment]
To me, what's important is that the OPS list mustn't be repeated. Or various instances will quickly fall out of sync. Hence the macro. Given the mechanism, you can do whatever you want, like extend what flatcap did with function names, default keybindings, whatever. But pretty please let's have a single place where all these are stored.

**Comment by flatcap** [comment]
Absolutely.  While OPS is very good at reducing the duplication, it's completely opaque to a new reader.
@gahr's code is an abuse of the pre-processor (isn't that what C's all about :-), but a new coder could understand it.  In that way, it's an improvement.

> #define Item(e, s) [e] = s,

Ah, nice.

> but the op code is also present in functions.h, with a binding name and a default keybinding, and in a C file where the operation is actually implemented. So once again, we are in this weird in-between where some stuff are defined and generated through a Perl script, and other stuff are in regular C files.

Yes, this is just one part of what would be needed.

> We should start by something simple to move all that in the C world

Definitely

**Comment by flatcap** [comment]
Here's my future vision... (likely to change)

Three separate repos: code, docs, contrib.
They would be packaged separately too.

## Code

- All the roff-formatted comments are turned into strings
  This makes them available to mutt (to be used in help, etc).
- DRY principle - Definitions appear in one place only
- The help strings are easily extractable -- using a simple sed/perl script

## Docs

- Lots of static content
- Content generated from source code strings
- Build process is just assembling the parts

The doc repo could have the source repo as a git submodule (a fixed release version)

## Contrib

- Most of this isn't version-dependent
- Nothing is **built**

**Comment by flatcap** [comment]
Fixed by the creation of `opcodes.h` in 19da63de
