### ISSUE TITLE
Segfault when trying to unset a variable using lua

### ISSUE THREAD

**Issue by darnir** [neomutt/neomutt#567]
I built neomutt using the current git master. I'm trying to unset a variable using lua, my lua scrip looks like this:
```lua
-- Switch Mutt accounts
function switch_account(name)
	if name == "UdS" then
		_switch_account {
			user="username",
			pass="UdS/password",
			url="urlhere"
		}
	elseif name == "mlists" then
		_switch_account {
			user = "usernme",
			pass = "GMail/darnirmlist",
			url  = "imaps://imap.gmail.com",
			record = "",
			postponed = "[Gmail]/Drafts",
			trash = "[Gmail]/Trash"
		}
	end
end

function _switch_account(opt)
	_switch_to_imap_account(opt.user,
							get_pass(opt.pass),
							opt.url,
							opt.inbox or opt.url.."/INBOX",
							opt.record or opt.url.."/Sent",
							opt.postponed or opt.url.."/Drafts",
							opt.trash or opt.url.."/Trash")
end

function _switch_to_imap_account(user, pass, url, inbox, record, drafts, trash)
	mutt.set("imap_user", user)
	mutt.set("imap_pass", pass)
	mutt.set("folder", url)
	mutt.set("spoolfile", inbox)
	mutt.set("record", record)
	mutt.set("postponed", drafts)
	mutt.set("trash", trash)
end
```

Using such a function when I invoke switch_account("mlists"), mutt segfults and crashes.

A preliminary look into mutt with `gdb` shows me this:

The `_lua_mutt_set()` method is invoked to set a mutt config variable. This method in turn calls the `lua_tostring()` method to get the value from the lua interpreter. Since the value passed to the variable was "", the interpreter correctly returns an empty string back to mutt.

However, we pass this empty string pointer to `safe_strdup`. Here the real issue arises. `safe_strdup` checks if the pointer is `NULL` _or_ if the string passed to it is empty and in both cases it returns `NULL`. However, this time we indeed wanted an empty string. The `NULL` returned by `safe_strdup` is passed to `strfcpy` which attempts to dereference it and causes a segfault.

Now the question is where exactly do we fix this? Should `safe_strdup` return an empty string (may break expectations in other parts of the code), or should `strfcpy` handle the `NULL` pointer cases gracefully? I think the former is a better solution.

**Comment by guyzmo** [comment]
simpler way to replicate the issue:

```config
lua mutt.set('record', '')
```

crash backtrace:

```
#0   in strfcpy (dest=dest@entry=0x7fffffffbfb0 "\320؍", src=0x0, dlen=<optimized out>, dlen@entry=1024) at ../lib.c:1162
#1   in mutt_option_set (val=0x8dd7d0, err=err@entry=0x7fffffffc3f0) at ../init.c:439
#2   in _lua_mutt_set (l=0x8e5668) at ../mutt_lua.c:131
#3   in  () at /usr/lib/liblua.so.5.3
#4   in  () at /usr/lib/liblua.so.5.3
#5   in  () at /usr/lib/liblua.so.5.3
#6   in  () at /usr/lib/liblua.so.5.3
#7   in  () at /usr/lib/liblua.so.5.3
#8   in  () at /usr/lib/liblua.so.5.3
#9   in lua_pcallk () at /usr/lib/liblua.so.5.3
#10 in mutt_lua_parse (tmp=<optimized out>, s=0x7fffffffc730, data=<optimized out>, err=0x7fffffffc780) at ../mutt_lua.c:383
#11 in mutt_parse_rc_line (line=<optimized out>, token=0x7fffffffc7a0, err=0x7fffffffc780) at ../init.c:3023
#12 in mutt_parse_rc_line (line=line@entry=0x7fffffffc7c0 "lua mutt.set('record', '')", token=token@entry=0x7fffffffc7a0, err=err@entry=0x7fffffffc780)
    at ../init.c:3042
#13 in mutt_enter_command () at ../commands.c:614
#14 in mutt_index_menu () at ../curs_main.c:2804
#15 in main (argc=1, argv=<optimized out>, environ=<optimized out>) at ../main.c:899
```

The guilty code being [there](https://github.com/neomutt/neomutt/blob/master/init.c#L439). I'm cooking a patch to `NONULL` this.

> Now the question is where exactly do we fix this? Should safe_strdup return an empty string (may break expectations in other parts of the code), or should strfcpy handle the NULL pointer cases gracefully? I think the former is a better solution.

Generally speaking I might agree with you. But in the Mutt's case, that choice has been made by our peers about 19 years ago (*when I was drinking my first beers and fighting my first kernel panics*), so that means whatever we prefer doesn't matter, it's better to follow their choice.
