### ISSUE TITLE
Segfault when saving attachments with a slash in the name

### ISSUE THREAD

**Issue by lkmorlan** [neomutt/neomutt#569]
Take a message with a slash in the subject and send it to yourself as an attachment. view-attachments on the message. Highlight the message attachment and press "s" for save. mutt will suggest the subject as the filename. Press enter to accept and you get a segfault. 

Because of the slash it should error out or it should remove the slash when creating the suggested save filename.

Debian NeoMutt 20170113 (1.7.2)

**Comment by gahr** [comment]
I can reproduce with `20170113` but not with `20170428`. Can you please upgrade your version?

**Comment by gahr** [comment]
This was (accidentally) fixed by #343 .

**Comment by lkmorlan** [comment]
Thank you
