### ISSUE TITLE
notmuch search shows no results

### ISSUE THREAD

**Issue by Alok** [neomutt/neomutt#57]
Silly question, but how do I map `/` to open a query and then show the results for it in a vfolder? (changed to reflect more relevant question better)

**Comment by 4nd3r** [comment]
`macro pager \027 <do><some><stuff>` ?

**Comment by Alok** [comment]
That pops up the search bar, but now I get the issue that `notmuch` always shows 0 found for *any* query at all.

**Comment by scottkosty** [comment]
Does `notmuch search` work for you on the command line? Have you run `notmuch new` yet to build the index?

**Comment by Alok** [comment]
Yes to both. I have a hook that runs `notmuch new` every time I run `offlineimap`. I get results with `notmuch search`, but running it in `mutt` gives nothing, even for the same query.

**Comment by scottkosty** [comment]
I see. I'm not sure then. I'm still using mutt-kz until pioneers like you get bugs like this fixed (thank you!) :)

**Comment by flatcap** [comment]
Sorry, I don't know either.

Probably time to wake the master: @karelzak :-)
He wrote the notmuch patch so he'll know what to do.

**Note:** He's often busy, so be patient.

**Comment by karelzak** [comment]
You need <vfolder-from-query> mutt command, by default is mapped to <Esc>X   (see help in browser for the current mapping). It's also in README.notmuch.

**Comment by karelzak** [comment]
Note that vfolder is the result of the notmuch search, you cannot use notmuch to search with-in vfolder. It does not make sense. The query is always global (like "notmuch search" on command line). 

The standard mutt search (/) works as expected for all possible context types, but you cannot use notmuch specific statements in the '/' query.

**Comment by Alok** [comment]
I have this mapping and it doesn't work:

```
macro index / "<vfolder-from-query>"
```

**Comment by scottkosty** [comment]
That mapping works with mutt-kz, which does suggest that something is broken in neomutt if it doesn't work for you.

**Comment by raphaelfournier** [comment]
I have a similar issue but not exactly the same: "some" queries in neomutt do not show the same results as notmuch on the command line. 

`notmuch search tag:waiting` yields 3 threads (command-line), while the same query in mutt-kz or neomutt yields 1 result.
`notmuch search tag:foobar` yields 2 threads, while it's 0 in mutt-kz/neomutt. 

All those tags were added from inside neomutt.

**Comment by flatcap** [comment]
@scottkosty 
> That mapping works with mutt-kz

There _shouldn't_ be a difference between mutt-kz and neomutt.

@raphaelfournier 
> "some" queries in neomutt do not show the same results as notmuch on the command line

Thanks guys.  I'll promote this to a Bug :-)

If you have the time to find any more clues, it would be appreciated.

**Comment by Alok** [comment]
Did anyone ever find a fix for this? It's made neomutt unusable for me =(.

**Comment by flatcap** [comment]
No, sorry.  I'll look into it.

**Comment by flatcap** [comment]
Please can you run `mutt -d 2` to enable debugging, then find a query that doesn't work.
What is:
- The query string you typed into mutt? (or the virtual folder name)
- The query log line, that mutt saves to `~/.muttdebug0` (look for `nm: query 'XXX'`)
- The result of the command line (using the same query): `notmuch search --output=messages 'XXX' | wc -l`

This command will list all your tags:
`notmuch dump | sed -e 1d -e 's/ -- .*//' -e 's/ /\n/g' | sort | uniq -c | sort -nr`

I'm in our IRC channel if you have time to experiment: #neomutt on irc.freenode.net

**Comment by Alok** [comment]
My search is mapped to the following:

`macro index / "<vfolder-from-query>"`

I searched for my own name `alok` and got the following vfolder: `Folder: notmuch:///Users/alokbeniwal/.mail?query=alok`, which gives no results.

`notmuch search --output=messages 'alok' | wc -l` gives 11388.

`notmuch dump | sed -e 1d -e 's/ -- .*//' -e 's/ /\n/g' | sort | uniq -c | sort -nr` gives:

```
 21267 +inbox
   6109 +unread
   1108 +replied
    824 +attachment
     14 +flagged
     11 +signed
```

[Here's the full debug log as a Gist.](https://gist.github.com/44c5df6f668d56c4e0acd2f212077e6e)

It only gives this for the query log line:

```
[2016-12-12 03:28:10] nm: query 'alok'
[2016-12-12 03:28:10] nm: query successfully initialized
```

If I can do anything else, let me know. It's 4 AM here, so I'll be asleep soon for the next ~8 hours.

**Comment by flatcap** [comment]
OK, thanks.  I'll shall experiment some more.
Sleep well, I'll catch you later.

PS I'm in England (timezone UTC)

**Comment by flatcap** [comment]
I'm struggling to see what's going wrong.  Almost nothing has changed since mutt-kz.
Your logs look exactly the same as mine, except I get some results.

What's your config? `mutt -D | grep nm_`

Which version of notmuch libraries are you using?
This will show you the major version: `ldd mutt | grep notmuch`

> libnotmuch.so.4 => /lib64/libnotmuch.so.4

Then look for the minor: `ls -l /lib64/libnotmuch.so.4`

> /lib64/libnotmuch.so.4 -> libnotmuch.so.4.4.0

**Comment by Alok** [comment]
config:

```
nm_open_timeout=5
nm_default_uri=""
nm_hidden_tags="unread,draft,flagged,passed,replied,attachment,signed,encrypted"
nm_exclude_tags=""
nm_unread_tag="unread"
nm_db_limit=0
nm_query_type="messages"
nm_record is unset
nm_record_tags=""
```

libs: I'm on a mac, so `ldd` isn't available and `otool -L mutt | grep notmuch` gave the error:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'mutt': No such file or directory.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
```

**Comment by flatcap** [comment]
OK, the config looks sensible.
The version of notmuch matters because the code is slightly different for v4.3.0 and later.
(but I don't know where to look on a mac).

The only other thought, for now, is to backup, wipe and rebuild the notmuch database.
It's unlikely to fix the problem, but I'd like to rule it out.

**Comment by Alok** [comment]
I'll try that. What commands would I need to do that?

**Comment by flatcap** [comment]
It _should_ be as simple as:
```
cd /Users/alokbeniwal/.mail
mv .notmuch .notmuch.backup
notmuch new
```

notmuch will see there's no database and rebuild it.
The only tags you've got are the ones that are automatically added, so you won't be losing anything.

**Comment by karelzak** [comment]
I just re-compiled the current https://github.com/neomutt/neomutt and I'm not able to reproduce the problem. Maybe you can try "strace -o log <mutt...>" to see more details.

It's strange that "notmuch search" or "notmuch count" works and mutt returns nothing.

**Comment by Alok** [comment]
`strace` unfortunately does not work on macOS.

**Comment by flatcap** [comment]
Have you tried rebuilding the database?

I don't know how to use `otool`, but the error message suggests you need to give it the full path to mutt.
`which mutt` will tell you where.

**Comment by Alok** [comment]
Giving the full path worked.  I get this:

'/usr/local/opt/notmuch/lib/libnotmuch.4.dylib (compatibility version 4.4.0, current version 4.4.0)`

I have yet to try rebuilding the database.

**Comment by Alok** [comment]
It appears that regenerating the `notmuch` database (somehow) fixed the issue. I have no idea why, because that same database is presumably queried when I search on the command line, and *that* worked, but screw it, it works.

**Comment by papey** [comment]
Having the same problem here, rebuilding the database change nothing. Ask for details if needed.

```
mutt -v       
NeoMutt 20170714 (1.8.3)
```

```
notmuch --version                     
notmuch 0.24.2
```

**Comment by octanou** [comment]
Exact same problem for me, also trying to rebuilt database but no luck. 

NeoMutt 20201127
notmuch 0.30

**Comment by scottkosty** [comment]
@papey can you also reproduce on a newer NeoMutt version? Perhaps this bug came back?

**Comment by octanou** [comment]
Found the issue on my end, nothing related to mutt but bogus conf that limited search results by date ... 
Can at least confirm that it works fine on NeoMutt 20210205 / Notmuch 0.31.4. 
Sorry for the noise !

**Comment by scottkosty** [comment]
@octanou great, thanks for confirming!

**Comment by Tonus1** [comment]
Hi
Got something similar :
notmuch request gives 5 hits and in mutt just 1
It could be that special characters are not well managed.

When searching for `subject:fer` it will not give (in mutt) a string followed by a `&` like `fer&`

Itwould not print something preceeded with `’`

**Comment by Tonus1** [comment]
Actually, searching like a regexp gives the match : 
`/fer/` gives all the results.
Hope this helps.
