### ISSUE TITLE
status color broken

### ISSUE THREAD

**Issue by 4nd3r** [neomutt/neomutt#571]
bisecting gave me bd6ee7d65575e1f0579bd652d0401a795e1f0ecb:
```
git checkout bd6ee7d65575e1f0579bd652d0401a795e1f0ecb
make
./mutt
```
no status coloring, checking out commit before that:
```
$ git checkout 86e76686c744577bd36786d69e9ae448e97484e1
$ make
$ ./mutt
```
all OK

**Comment by 4nd3r** [comment]
also, status gets colored when in pager and `pager_index_lines` is set.

**Comment by flatcap** [comment]
@4nd3r Thanks for the bisect.  Please can you give [[issue/571](https://github.com/neomutt/neomutt/tree/issue/571)] a test.

**Comment by 4nd3r** [comment]
yes, this fixes issue
