### ISSUE TITLE
Feature requests: new_mail_command notification show sender and subject of new mail?

### ISSUE THREAD

**Issue by jiang-qian** [neomutt/neomutt#572]
The new_mail_command patch of neomutt is really nifty! I am now able to get a notification via notify-send when I'm working on some other virtual-desktops.

However, if I read the online documentation correctly, the content of the notification comes from $status_format, which, as far as I can see, could tell how many new mails are in which folder/mailbox, but not the sender of a new mail or its subject. It will be a lot more informative if the $new_mail_command can send notification with sender's name and subject, just like notifications from Android phone.

Would that be technically difficult to implement?

**Comment by flatcap** [comment]
> Would that be technically difficult to implement?

Unfortunately, yes.

This feature is quite simple and by the time it learns of new mail, it doesn't know where it came from.
We'd love to make this feature more useful, but we're a small bunch of developers with little time.

**Comment by jiang-qian** [comment]
Thank you Mr. Russon for letting me know.

**Comment by AdrienLemaire** [comment]
That's something I'd be quite interested in having. For example, to trigger `notify-send -u critical` when the subject of an email contains 'Internal Server Error'.

**Comment by jindraj** [comment]
I would say the situation didn't change.

It's easy if you're notmuch user to move notifications out of neomutt to notmuch post-new hook.
```
	QUERY=("tag:inbox")
	QUERY+=("AND tag:notify")
	QUERY+=("AND tag:important")
	QUERY+=("AND NOT query:{lists,junk}")

	search_result=$(notmuch search --format=json "${QUERY[*]}")

	readarray -t authors < <(jq '.[] | .authors' <<<$search_result)
	readarray -t subjects < <(jq '.[] | .subject' <<<$search_result)

	for i in "${!authors[@]}"
	do
		/usr/local/bin/terminal-notifier \
			-title "${authors[i]}" \
			-message "${subjects[i]}" \
			-activate 'com.googlecode.iterm2' \
			-sound 'submarine' \
			-appIcon 'https://neomutt.org/images/mutt-48x48.png'
			sleep 0.3
	done
	notmuch tag -notify -- tag:notify
```
Then changing the search filter … `' OR ( tag:inbox and subject:…whatever you want)'`

**Comment by AdrienLemaire** [comment]
@jindraj thanks for the reply and the example.

I believe I'd have to stop using `imaps://imap.gmail.com/` as folder in order to be able to use notmuch.
Needing to store all my emails locally isn't very appealing. Maybe this'll motivate me to move out of gmail and use my own mail server at some point.

**Comment by jindraj** [comment]
speaking of gmail and notmuch: https://github.com/gauteh/lieer/
it synces your emails using gmail api and it offers bidirectional tags sync.

notmuch tags = gmail labels
