### ISSUE TITLE
how to disable "warning in muttrc"

### ISSUE THREAD

**Issue by Alok** [neomutt/neomutt#583]
I bind `gi`, `gg`, and a few other chords to be like gmail. Now when I launch `mutt`, I get a warning about aliasing. How do I disable that warning?

**Comment by toogley** [comment]
As far as i know, this isn't possible at the moment.

**Comment by flatcap** [comment]
The trick, for now is to unbind the mapping that's overwritten.
It would have been helpful if you'd told us what the error message said.
I guess, that this might help:
```
bind index,pager g noop
```

Vim, and probably other editors, have a timeout, which allows them to map both 'x' and 'xy'.
Commit: 744fe99 was just a quick fix to tell the user when a mapping was being overwritten.

**Comment by somini** [comment]
Yeah, I was the one who created this feature (#451).

I think this is the correct behaviour, specially if you have a big muttrc, otherwise you can accidentally alias commands.

With @Alok bindings, the group reply (g) binding is lost.

**Comment by ahmedelgabri** [comment]
It will be nice if we can turn off the warnings I have the same issue as @Alok with the exactly the same keybindings.

**Comment by guyzmo** [comment]
well, you should rather unbind the `g` command as suggested above. The issue is not the warning, but the fact that you're asking something mutt cannot resolve !

**Comment by ahmedelgabri** [comment]
I actually had a couple more than just those `g` ones.

So to get this straight, every time I bind keys now they won't override the default bindings by default & I have to unbind first?

**Comment by somini** [comment]
They override the defaults, but now you get a warning. 
The old version overrode the defaults silently, so you could lose keybindings. Now the defaults are overridden so that you know that some keybindings are invalid. If you don't mind, unbind them first.

**Comment by oblitum** [comment]
I did override it on purpose, this completely screw up my workflow....

**Comment by oblitum** [comment]
If it warned but started up mutt anyway, but warns and stops execution to ask for continuing.
