### ISSUE TITLE
--enable-imap, --enable-sidebar documented for configure, but do not exist

### ISSUE THREAD

**Issue by ivucica** [neomutt/neomutt#584]
## Expected behavior

--enable-imap and --enable-sidebar are either not documented at https://www.neomutt.org/dev/build, or exist in configure script

## Actual behavior

Trying to pass --enable-imap and --enable-sidebar results in:

    configure: WARNING: unrecognized options: --enable-imap, --enable-sidebar

## Steps to reproduce

    ./autoreconf -i
    ./configure --enable-imap --enable-sidebar --with-gss --with-sasl

## Used program versions

    $ git describe
    neomutt-20170428-91-gd7f0ba48

## Operating System and its version

    $ cat /etc/os-release
    PRETTY_NAME="Debian GNU/Linux stretch/sid"
    NAME="Debian GNU/Linux"
    ID=debian
    HOME_URL="https://www.debian.org/"
    SUPPORT_URL="https://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"

The system may or may not be fully up-to-date :wink:

**Comment by gahr** [comment]
Both the imap and sidebar features are now enabled unconditionally, see [0f47b178] and [135b1bfa].

**Comment by ivucica** [comment]
@gahr That does not mean the issue is resolved, as the documentation still refers to it.

Can you please update https://www.neomutt.org/dev/build?

**Comment by gahr** [comment]
Sorry I didn't mean to close it, just comment :)

**Comment by ivucica** [comment]
No worries! Thanks for looking at this.

**Comment by gahr** [comment]
Fixed in [37](https://github.com/neomutt/neomutt.github.io/issues/37).
