### ISSUE TITLE
Drop some more 'obsolete?' configure options

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#590]
Following on from #557 (remove --enable-mailtool configure option), I have a few more suggestions...
**All** these options were in mutt's initial commit, back in 1998.

1. `--enable-locales-fix` : The result of isprint() is unreliable

2. `--enable-nfs-fix` : Work around an NFS with broken attributes caching

3. `--disable-warnings` : Turn off compiler warnings (not recommended)
  The description says it all.  Any warnings should be fixed.

4. `--with-exec-shell=SHELL` : Specify alternate shell (ONLY if /bin/sh is broken)
  Mutt is hard-coded to run this shell with `-c` to execute commands.
    1. What Unix-like systems wouldn't have `/bin/sh`?
    2. Should we replace it with a muttrc option? (which would still allow sysadmins to override it)
      Can we use `$shell`?
    3. Should the `-c` argument be configurable?

5. `--enable-exact-address` : Enable regeneration of email addresses
  What **IS** this?  Can we just:
    1. Enable it?
    2. Drop it?
    3. Muttrc it?

**Comment by somini** [comment]
Alternate shells are a big problem, because they might not have the same semantics.
Vim plugins have loads of bugs that boil down to "My `$SHELL` is fish/csh, this is broken". I think we should stick to `/bin/sh`, at least the semantics are standard. I think a configure time option for something other than `/bin/sh` is a bit overkill, but can't hurt. Putting it on muttrc is asking for trouble.

**Comment by gahr** [comment]
Please do not drop `--enable-locales-fix`, we (FreeBSD) still need that.

**Comment by P-EB** [comment]
Except for `--enable-locales-fix`, I agree on the need too remove all these configs, including alternate shells without replacement.

**Comment by guiniol** [comment]
I agree, especially on the shell. Even if it's not pure sh, it's a symlink to bash or dash or something, but it's there.

**Comment by toogley** [comment]
> 5. `--enable-exact-address` : Enable regeneration of email addresses
> What **IS** this? Can we just:

[Our manual](https://www.neomutt.org/guide/optionalfeatures.html#exact-address) has an entry for that:

> 8. Exact Address Generation
>
> Mutt supports the “ Name <user@host>”address syntax for reading and writing messages, **the older “ user@host (Name)” syntax is only supported when reading messages. The --enable-exact-address switch can be given to configure to build it with write-support for the latter syntax.** +exact_addressin the output of mutt -vindicates whether it's supported.

However, i haven't looked at the code.

**Comment by toogley** [comment]
@gahr but i guess we can make `--enable-locales-fix` persistent?

**Comment by gahr** [comment]
I wouldn't, it's a pessimization if your libc is correct.
