### ISSUE TITLE
Running timeout-hook 'exec sync-mailbox' exits some screens

### ISSUE THREAD

**Issue by digimokan** [neomutt/neomutt#591]
Asked about this issue in IRC a few weeks ago.  Approx five or so months ago the syntax timeout-hook . 'exec sync-mailbox' was made invalid.  The current syntax, timeout-hook 'exec sync mailbox', still syncs my mailboxes but has a some side effects that were not present before.  Side effects: when I am in the help menu and the timeout hook runs, it will exit out of the help menu.  Same exit effect happens when viewing a text/plain or text/html message from the attachments menu (it will exit back to the attachments menu).  Also, after opening a message in the pager from the index menu, the message pager will "skip" forward or backward one line, at odd intervals that are not tied to my timeout.

I use mbsync to sync my mailboxes to/from my local machine every 15 sec.  I also use a timeout of 1 with the above timeout hook (I know it's quick, but I get a very responsive index view that way, without having to manual sync).

- System: Arch Linux
- Neomutt: 20170428 (1.8.2) from AUR
- .muttdebug0 available on request

**Comment by flatcap** [comment]
Sorry, I've reverted my "fix".  I thought I'd got away with a simple solution.
I'll keep thinking...

**Comment by digimokan** [comment]
I still have the same issue with neomutt 20180223 (from the Arch repos).

**Comment by roccoblues** [comment]
Trying to cleanup some older issues here. Can anyone comment if this issue still persists with the latest version? Thanks!
