### ISSUE TITLE
One office365 account hangs at the end of fetching headers

### ISSUE THREAD

**Issue by lrosenman** [neomutt/neomutt#597]
I have access to 2 office365 accounts (work, and redcross).  When I try to read my work office 365 INBOX I'll get to the last hunk of headers (at this writing 5170 of 5174) and neomutt will just hang. 

The same config (modulo credentials) works just fine for my redcross account. 

Ideas?  (I have neomutt built with debugging on homebrew).

version: NeoMutt 20170428 (1.8.2)
MacOS Sierra 10.12.5
lrosenman:.mutt lrosenman$ mutt -v
```
NeoMutt 20170428 (1.8.2)
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.

System: Darwin 16.6.0 (x86_64)
hcache backends: tokyocabinet

Compiler:
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Configure options: '--disable-dependency-tracking' '--disable-warnings' '--prefix=/usr/local/Cellar/neomutt/20170428' '--with-ssl=/usr/local/opt/openssl' '--with-sasl' '--with-gss' '--enable-imap' '--enable-smtp' '--enable-hcache' '--with-tokyocabinet' '--enable-sidebar' '--enable-gpgme' '--disable-nls' '--enable-debug' 'CC=clang'

Compilation CFLAGS: -g -O2

Compile options:
+CRYPT_BACKEND_CLASSIC_PGP +CRYPT_BACKEND_CLASSIC_SMIME +CRYPT_BACKEND_GPGME
+DEBUG +DL_STANDALONE -ENABLE_NLS -EXACT_ADDRESS -HOMESPOOL -LOCALES_HACK
-SUN_ATTACHMENT +HAVE_BKGDSET +HAVE_COLOR +HAVE_CURS_SET -HAVE_FUTIMENS
+HAVE_GETADDRINFO +HAVE_GETSID +HAVE_LANGINFO_CODESET +HAVE_LANGINFO_YESEXPR
-HAVE_LIBIDN +HAVE_META -HAVE_REGCOMP +HAVE_RESIZETERM +HAVE_START_COLOR
+HAVE_TYPEAHEAD +HAVE_WC_FUNCS +ICONV_NONTRANS -USE_COMPRESSED +USE_DOTLOCK
+USE_FCNTL -USE_FLOCK -USE_FMEMOPEN +USE_GSS +USE_HCACHE +USE_IMAP -USE_LUA
-USE_NOTMUCH -USE_NNTP -USE_POP +USE_SASL +USE_SETGID +USE_SIDEBAR +USE_SMTP
-USE_SSL_GNUTLS +USE_SSL_OPENSSL
-DOMAIN
-MIXMASTER
-ISPELL
SENDMAIL="/usr/sbin/sendmail"
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/Cellar/neomutt/20170428/share/mutt"
SYSCONFDIR="/usr/local/Cellar/neomutt/20170428/etc"
EXECSHELL="/bin/sh"

patch-attach-headers-color-neomutt
patch-compose-to-sender-neomutt
patch-compress-neomutt
patch-cond-date-neomutt
patch-encrypt-to-self-neomutt
patch-fmemopen-neomutt
patch-forgotten-attachments-neomutt
patch-forwref-neomutt
patch-ifdef-neomutt
patch-index-color-neomutt
patch-initials-neomutt
patch-keywords-neomutt
patch-kyoto-neomutt
patch-limit-current-thread-neomutt
patch-lmdb-neomutt
patch-lua-neomutt
patch-multiple-fcc-neomutt
patch-nested-if-neomutt
patch-new-mail-neomutt
patch-nntp-neomutt
patch-notmuch-neomutt
patch-progress-neomutt
patch-quasi-delete-neomutt
patch-reply-with-xorig-neomutt
patch-sensible-browser-neomutt
patch-sidebar-neomutt
patch-skip-quoted-neomutt
patch-status-color-neomutt
patch-timeout-neomutt
patch-tls-sni-neomutt
patch-trash-neomutt

To learn more about NeoMutt, visit: http://www.neomutt.org/
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```
lrosenman:.mutt lrosenman$

What can I provide to help?

**Comment by flatcap** [comment]
Hmm... NeoMutt hasn't really touched IMAP.
There are a few things you could try.

Your neomutt is `+DEBUG`, so try running `mutt -d 2` and have a look in `~/.muttdebug0`
Increase the debug level if there's still nothing "obvious".
**Note**: Be careful if you paste debug logs, they may contain private info / passwords.

Recently, upstream mutt made some IMAP improvements which are in **our** latest devel release - 2017-05-26.  It's probably worth trying that (if you're happy to compile your own neomutt).

Have you tried a vanilla version of mutt?

**Comment by lrosenman** [comment]
I have NOT tried vanilla mutt.  I build my own via HomeBrew, how can I switch to the development release using that?

I'd prefer to try that prior to sending debug logs for something that y'all may have fixed already.

**Comment by guyzmo** [comment]
you can try `brew install --HEAD neomutt` if that does not work, do `brew edit neomutt` and add the reference to the git repository. Have a look at homebrew's documentation (or other formulas) for more details about that.

**Comment by guyzmo** [comment]
An alternative solution you might want to consider, is using an external tool for fetching your IMAP mails locally, with offlineimap or mbsync.

**Comment by lrosenman** [comment]
I prefer to use real IMAP as I move between machines and having ONE view works well.

lrosenman:~ lrosenman$ brew install --HEAD neomutt --with-debug
==> Installing neomutt from neomutt/neomutt
==> Cloning https://github.com/neomutt/neomutt.git
Updating /Users/lrosenman/Library/Caches/Homebrew/neomutt--git
==> Checking out branch master
==> ./prepare --disable-dependency-tracking --disable-warnings --prefix=/usr/local/Cellar/neomutt/HEAD-9302fe1 --with-ssl=/usr/local
==> make
Last 15 lines from /Users/lrosenman/Library/Logs/Homebrew/neomutt/02.make:
		perl ./gen-map-doc ./manual.xml.tail ../OPS* \
	) > manual.xml
sed -e 's,[@]docdir[@],/usr/local/Cellar/neomutt/HEAD-9302fe1/share/doc/mutt,' ./Muttrc.head > Muttrc
clang -E -I. -I.. -I/usr/local/Cellar/neomutt/HEAD-9302fe1/include -I.. -DSYSCONFDIR=\"/usr/local/Cellar/neomutt/HEAD-9302fe1/etc\" -DBINDIR=\"/usr/local/Cellar/neomutt/HEAD-9302fe1/bin\" -I/usr/local/opt/openssl/include -D_MAKEDOC -C ../init.h | ./makedoc -c >> Muttrc
xsltproc --nonet -o manual.html ./html.xsl manual.xml
xsltproc --nonet ./chunk.xsl manual.xml > /dev/null 2>&1
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl"
compilation error: file ./html.xsl line 3 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl
make[2]: *** [manual.html] Error 5
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [index.html] Error 5
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/neomutt/homebrew-neomutt/issues

lrosenman:~ lrosenman$

**Comment by flatcap** [comment]
There's an extra build requirement for the docs.
The package, on my machine, is called: `docbook-dtds`

BTW, we're all in `#neomutt` on irc.freenode.net if you'd prefer.

**Comment by lrosenman** [comment]
brew install docbook
brew install docbook-xsl

got past that one, now:
==> make
Last 15 lines from /Users/lrosenman/Library/Logs/Homebrew/neomutt/02.make:
clang  -g -O2  -L/usr/local/opt/openssl/lib -o pgpewrap pgpewrap.o
clang  -g -O2  -L/usr/local/opt/openssl/lib -o mutt account.o addrbook.o alias.o ascii.o attach.o base64.o bcache.o browser.o buffer.o buffy.o charset.o color.o commands.o complete.o compose.o compress.o copy.o curs_lib.o curs_main.o date.o edit.o editmsg.o enter.o filter.o flags.o from.o getdomain.o group.o handler.o hash.o hdrline.o headers.o help.o history.o hook.o init.o keymap.o lib.o main.o mbox.o mbyte.o md5.o menu.o mh.o muttlib.o mutt_idna.o mutt_sasl_plain.o mutt_socket.o mutt_tunnel.o mx.o newsrc.o nntp.o pager.o parse.o pattern.o pop.o pop_auth.o pop_lib.o postpone.o query.o recvattach.o recvcmd.o rfc1524.o rfc2047.o rfc2231.o rfc3676.o rfc822.o safe_asprintf.o score.o send.o sendlib.o sidebar.o signal.o smtp.o sort.o status.o system.o thread.o url.o version.o conststrings.o resize.o mutt_ssl.o mutt_sasl.o  -Lhcache -lhcache  -ltokyocabinet -Lncrypt -lncrypt -Limap -limap -lncurses -dynamic -Wl,-search_paths_first -lkrb5 -lssl -lcrypto -lz -lsasl2  -liconv -L/usr/local/opt/gpgme/lib -lgpgme -L/usr/local/opt/libassuan/lib -lassuan -L/usr/local/opt/libgpg-error/lib -lgpg-error
Undefined symbols for architecture x86_64:
  "_libintl_setlocale", referenced from:
      _folder_format_str in browser.o
      _mutt_builtin_editor in edit.o
      _main in main.o
      _init_common in libncrypt.a(crypt_gpgme.o)
      _crypt_entry_fmt in libncrypt.a(crypt_gpgme.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [mutt] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/neomutt/homebrew-neomutt/issues

lrosenman:~ lrosenman$

**Comment by lrosenman** [comment]
I get the same errors from the 20170526 branch as on head.

**Comment by lrosenman** [comment]
once we fixed the brew build, the -HEAD version works just fine  with this O365 account.

**Comment by gahr** [comment]
Fixed by upstream.
