### ISSUE TITLE
Debian Packages available

### ISSUE THREAD

**Issue by riesebie** [neomutt/neomutt#60]
Hi all,

I am pleased to announce the availability of neomutt packages for
Debian. Hints for installation you'll find at [1].

I've packaged neomutt for Debian. A Debian ITP [2] is filed. The
binaries are build in a sid environment. The sources are fetched
from neomutt branch. I'll update packages as needed. Please test 
the packages and let me know of any further glitches you find. If 
you want, you can open an issue here. The Debian Bug Tracking 
System is not involved as the package isn't uploaded yet, but will 
be soon.

Thanks in advance for your cooperation

Elimar

[1] http://www.lxtec.de/debarchiv
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825821

--
  The path to source is always uphill!
                                -unknown-

**Comment by flatcap** [comment]
Hurrah!

Please can you/someone write some installation instructions and I'll put them on the website.

**Comment by riesebie** [comment]
* Richard Russon <notifications@github.com> [2016-06-23 12:53 -0700]:

> Hurrah!
> 
> Please can you/someone write some installation instructions and I'll put them on the website.

http://www.lxtec.de/debarchiv

Elimar

P.S.: We have to think about a mailing list. We're contributing to a
MUA......

-- 
  355/113: Not the famous irrational number pi,
           but an incredible simulation!
	                -unknown

**Comment by flatcap** [comment]
> We have to think about a mailing list. We're contributing to a MUA......

**Mailing list:**
- Logical, given what we do
- Anyone could make contact (not just GitHub users)
- People could contact the team, not just me.
- A small cost to host, setup and maintain.

**GitHub Issues**
- It's very public.
- All of the important people are watching the project.
- I'm happy for practically anything to be asked there.

For now, the GitHub Issues are working for me, but I'm open to persuasion.

**Comment by flatcap** [comment]
> Website:
> The current build is as of commit 20801c1 (20.06.2016)

Does this mean you're going to follow git (rather than the numbered releases)?

It's just that I haven't decided what I'm doing there, yet.
I asked some questions in issue #47 but haven't had any answers yet.

**Comment by soraver** [comment]
This works pretty nice, thanks @riesebie 
I recompiled these packages in both jessie and wheezy.

1) first add the repository to /etc/apt/sources.list:
```
deb http://www.lxtec.de/debarchiv experimental main
deb-src http://www.lxtec.de/debarchiv experimental main
```
2) add the gpg key
`wget -q -O - http://www.lxtec.de/debarchiv/riesebie.key | sudo apt-key add -`

3.) Update apt 
`sudo apt-get update`

4) Download the dependencies
`sudo apt-get build-dep neomutt`

5) Build neomutt
`sudo apt-get source -b -t experimental neomutt`

> Here I had a problem on wheezy. I had to setup backports and update my distro to backports, and then build-deb and source -b.
> The second problem on wheezy was that it couldnt add the gpg key properly, so I had to apt in insecure mode.
> So in wheezy:
> 
> 4) Download the dependencies
> `sudo apt-get build-dep neomutt --allow-unauthenticated`
> 
> 5) Build neomutt
> `sudo apt-get source -b -t experimental neomutt --allow-unauthenticated`

6) Install the actual packages
`dpkg -i neomutt_*.deb`

have fun!

**Comment by demure** [comment]
Nice, I look forward to these being in the debian repository :+1:

**Comment by paravoid** [comment]
The stock mutt Debian package has been uploaded into experimental today, incorporating all of neomutt:
- https://lists.debian.org/debian-devel-changes/2016/07/msg01218.html
- http://anonscm.debian.org/cgit/pkg-mutt/mutt.git/log/

This is a continuation of the original mutt package's lineage so I'd expect it to still conflict with @riesebie's neomutt packages (but I wouldn't know, I haven't tested them).

I think this issue can be closed — this isn't an upstream issue anyway,

**Comment by riesebie** [comment]
Today I've uploaded neomutt-20160709 Debian packages to [ my lxtec repo](http://www.lxtec.de/debarchiv) ;-)

**Comment by riesebie** [comment]
Issue reopened. Closed accidently, sigh...

**Comment by riesebie** [comment]
Debian's pkg-mutt-maintainers have released a package including the patchset provided by neomutt. There is no need to maintain an additional neomutt package.
