### ISSUE TITLE
Consider requerying when sync-mailbox notmuch vfolders

### ISSUE THREAD

**Issue by julian-klode** [neomutt/neomutt#601]
When using notmuch vfolders, and you remove a tag from a message that is part of the current query, it does not disappear when you sync-mailbox unless you quasi-delete it. This has some disadvantages:

- If you quasi-deleted a message, you can't undelete it later on in case you accidentally removed the label and want to re-add it.
- You cannot write generic macros for tagging. For example, if I have tags "inbox" and "later", and the action "+inbox -later" and "-inbox +later", I need two variants for each: In inbox, the -inbox hides the message; in later, the -later one should hide the message. You can use folder-hooks to some extent, but it's not that pretty.

So it might be a good idea to just re-issue the query when syncing the mailbox, and preserve the position (if possible, probably keep ids of current message +/- 10 and then jump to the closest match after requerying).

**Comment by julian-klode** [comment]
It might be too expensive to reopen in sync-mailbox, or someone might rely on sync-mailbox to not add new emails (which could happen if new ones were tagged in the background), so maybe it might be a good idea to have a new function for that.

**Comment by julian-klode** [comment]
Alternatively, and what I initially thought about, but then discarded is automatically setting the quasi-delete state based on whether the message would be in the query results. I initially thought that's not possible but here's a new idea.

If you modify-labels-smart (let's call it this for now), after modifying, run a new query for `id:MSGID and (ORIGINAL-QUERY)`. Then do the following:

- If the message is *not* in the returned results, quasi-delete it
- Otherwise, undo the quasi-delete

That practically solves the issue in the least intrusive way, and maintains the current performance.

**Comment by flatcap** [comment]
Can this be closed now?

**Comment by julian-klode** [comment]
I think we might want to keep it open. The commit is a workaround that solves most issues, but perhaps requerying might be more practical long term (if it's fast enough)
