### ISSUE TITLE
NeoMutt 1.8.3 (feature ‘Ifdef’): outdated documentation

### ISSUE THREAD

**Issue by floand** [neomutt/neomutt#607]
#### bug report

The syntax for conditional config feature (_Ifdef_):
```
ifdef symbol "config-command [args]"
ifndef symbol "config-command [args]" 
```
as mentioned on [homepage](https://www.neomutt.org/feature/ifdef) and in comment of function [parse_ifdef](https://github.com/neomutt/neomutt/blob/master/init.c#L825), doesn’t work any longer with _NeoMutt 20170602 (1.8.3)_.

**Steps to reproduce:**
1. build _NeoMutt_ with `--enable-lua`, set up minimal _muttrc_ one liner
`ifdef USE_IMAP 'lua print("+imap")' `
2. invoke _NeoMutt_ in batch mode
`mutt -B`

**Expected behaviour:**
- since _NeoMutt_ is always built with `--enable-imap` from now on, the output of: “+imap”

**Actual behaviour**
- currently (with version 1.8.3) condition fails and therefore nothing is printed

**Reason:**
With “old” syntax the function [feature_enabled](https://github.com/neomutt/neomutt/blob/master/version.c#L478) compares apples and oranges — in this case "USE_IMAP" and "imap".

**Workaround:**
Use compile options strings from [comp_opts](https://github.com/neomutt/neomutt/blob/master/version.c#L98) structure, e.g. `ifdef imap 'lua print("+imap")' ` for conditional config options (but **not** for versions prior _NeoMutt-1.8.3_). Run `mutt -v` to see such strings.

**Comment by flatcap** [comment]
Sorry about that, @floand.  It's a side-effect of my tidying up of `mutt -v`.
I've made a small fix to the code.  I'll update the docs and let people know tomorrow.

**Comment by floand** [comment]
@flatcap, don’t say sorry. I have to say, thanks for your and all others passion/work.
These side-effect can be handled by users as mentioned.

**Comment by flatcap** [comment]
You're welcome.

For reference the current list of compile-time symbols is:
attach_headers_color, bkgdset, color, compose_to_sender, compress, cond_date, curs_set, debug, dotlock, encrypt_to_self, exact_address, fcntl, flock, fmemopen, forgotten_attachments, forwref, futimens, getaddrinfo, getsid, gnutls, gpgme, gss, hcache, homespool, iconv_nontrans, ifdef, imap, index_color, initials, keywords, libidn, limit_current_thread, lmdb, locales_hack, lua, meta, mixmaster, multiple_fcc, nested_if, new_mail, nls, nntp, notmuch, openssl, pgp, pop, progress, quasi_delete, regcomp, reply_with_xorig, resizeterm, sasl, sensible_browser, setgid, sidebar, skip_quoted, smime, smtp, start_color, status_color, sun_attachment, timeout, tls_sni, trash, typeahead, wc_funcs

**Comment by floand** [comment]
Thanks, only a little one remains as far as I can see:

[neomutt-1.8.3_issue607_fix-remained-comment.patch.txt](https://github.com/neomutt/neomutt/files/1050416/neomutt-1.8.3_issue607_fix-remained-comment.patch.txt)

**Comment by flatcap** [comment]
Aha!  Well spotted.  There was one more in `init.h`.
I've added them to my trivial-fixed branch (which will get merged before the next release).
Thanks.
