### ISSUE TITLE
cruft removal: buffy variable is ignored/inverted when entering browse mode

### ISSUE THREAD

**Issue by nobrowser** [neomutt/neomutt#609]
I proposed this patch (against 1.5.24, so probably will not apply on master) on the mutt-users list, in [this thread](https://marc.info/?l=mutt-users&m=143372308926626&w=2) almost 2 years ago now.  After the ultra-conservative crowd there rejected it, I have been carrying it around ever since, and this has been one (very small) part of the reason for my exile from Debian to Gentoo.  Currently this is the last thing that keeps me from switching to neomutt as my real MUA, and so probably from contributing again.

[mutt-buffy-patch.txt](https://github.com/neomutt/neomutt/files/1050080/mutt-buffy-patch.txt)

**Comment by gahr** [comment]
I think I know what it's doing and it's something I have been wanted to look into and fix for a long time, too. But I'm not sure. Could you please elaborate a bit on the what / how / why?

**Comment by nobrowser** [comment]
So, basically the `buffy` argument to `_mutt_enter_fname` indicates whether the context is such that a mailbox name (rather than a general file name) is expected.  This is clear from the way it it passed down to `_mutt_get_field` in the case of user actually typing something.  But in the other case, when user enters just '?' and gets a menu, `buffy` is just ignored - wrongly, I think, and most likely just by historical accident.  This means user gets a menu of all files even in contexts asking for a mailbox.

As a consequence, the "conventional" `y` macro which switches from the index view to the browser view has to hack around that by putting `<toggle-mailboxes>` at the end.  This is the only reason why typing `y` in the index mode has the same result as starting with `-y` in the command line args; otherwise many more people would notice the inconsistency :-P

Unfortunately the existence of this conventional macro and the fact that every distro includes it in their `/etc/Muttrc` (with the hack) is also the main argument _against_ the patch; if the macro (and user written macros that depend on the flea) is not adjusted, users will see a regression, not a fix.

I think it comes down to which group of users the project expects to be more numerous: those relying in some way on `/etc/Muttrc`, or those who write their configuration from scratch.

**Comment by flatcap** [comment]
This project is about improving things, so...
Merged.  Thanks.

**Comment by nobrowser** [comment]
Thanks.  I am preparing a neomutt gentoo package for myself right now :-)

I'll be back within a few days.

**Comment by gahr** [comment]
Thanks for this :)
