### ISSUE TITLE
NeoMutt Branching Explained

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#61]
## Branch Descriptions

Currently there are 53 branches in the NeoMutt repo.

---

Branches for **Mutt-1.5.24**:

- **1 Bug-Fixes**, [[feature5/bug-fixes](https://github.com/neomutt/neomutt/tree/feature5/bug-fixes)]
    * These are bug-fixes to Mutt, that haven't been accepted upstream.
      They are independent of all our features.
- **15 Features**, e.g. [[feature5/sidebar](https://github.com/neomutt/neomutt/tree/feature5/sidebar)]
    * This is where most of NeoMutt lives.  Each feature lives in a separate
      branch which is derived from Mutt-1.5.24.  This separation makes it easy
      to maintain the feature patches.
- **1 NeoMutt**, [[neomutt5](https://github.com/neomutt/neomutt/tree/neomutt5)]
    * This branch is what's bundled as NeoMutt.  All the Bug-Fixes and Feature
      branches are merged into this branch.  The only non-merge commits are for
      NeoMutt customisations, such as a README, and changes to the contact
      details.

This set of branches is quite simple and don't change often.

**Note**:  The branch names have the suffix '5'.

---

Branches for **Mutt-1.6.1**:

- **1 Bug-Fixes**, [[feature/bug-fixes](https://github.com/neomutt/neomutt/tree/feature/bug-fixes)]
    * These are bug-fixes to Mutt, that haven't been accepted upstream.
      They are independent of all our features.
- **19 Features**, e.g. [[feature/sidebar](https://github.com/neomutt/neomutt/tree/feature/sidebar)]
    * This is where most of NeoMutt lives.  Each feature lives in a separate
      branch which is derived from Mutt-1.6.1  This separation makes it easy
      to maintain the feature patches.
- **2 Devel Features**, e.g. [[devel/new-mail](https://github.com/neomutt/neomutt/tree/devel/new-mail)]
    * These feature branches are under development.  They may change without
      warning.  Once stable, the branch will be rebased onto Mutt-1.6.1, tidied
      up and renamed to [feature/new-mail].
- **1 Contrib**, e.g. [[contrib/vim-keybindings](https://github.com/neomutt/neomutt/tree/contrib/vim-keybindings)]
    * These branches will add value to Mutt, but not code.
- **1 NeoMutt**, [[neomutt](https://github.com/neomutt/neomutt/tree/neomutt)]
    * This branch is what's bundled as NeoMutt.  All the Bug-Fixes, Feature and
      Contrib branches are merged into this branch.  The only non-merge commits
      are for NeoMutt customisations, such as a README, and changes to the
      contact details.

**Note**:  Some features were branched from Mutt-1.6.1.  Some old features were
branched from Mutt-1.6.0 and then had the Mutt-1.6.1 changes merged in.  The
results are the same.

**Note**: The devel branches aren't merged into NeoMutt.

---

Miscellaneous Branches:

- **2 Mutt**, e.g.  [[mutt/default](https://github.com/neomutt/neomutt/tree/mutt/default)]
    * These branches track the two upstream Mutt branches: default and stable.
      The only change is the addition of [Travis CI](https://travis-ci.org/neomutt/neomutt)
      config to do automated testing.
- **1 Coverity**, [[coverity](https://github.com/neomutt/neomutt/tree/coverity)]
    * Before a release is made, NeoMutt is merged into the Coverity branch.
      This runs a deep [static analysis](https://scan.coverity.com/projects/neomutt-neomutt)
      of the code.
- **9 Issues**, e.g. [[issue/26](https://github.com/neomutt/neomutt/tree/issue/26)]
    * When fixing bugs it's useful to create a temporary workspace for testing
      possible fixes.  Generally, these branches aren't actually merged into the
      feature.

**Note**:  Not much is done with the Coverity reports, yet.

**Comment by flatcap** [comment]
## When X Changes, Do Y

A change, committed to one branch, often ends up in several places.
The branch names are denoted by [name].

### Bug-Fixes to Mutt

This is a bug-fix that isn't dependent on any of the features.

- Commit to: [feature/bug-fixes]
- Merge into: [neomutt]
- Backport to 1.5.24?  If important (and possible).
  * Commit to: [feature5/bug-fixes]
  * Merge into: [neomutt5]

### Features that exist in NeoMutt 1.5.24

A commit to an old feature.  These features existed before Mutt 1.6.0 was
released: cond-date, fmemopen, ifdef, index-color, initials,
limit-current-thread, nested-if, notmuch, progress, quasi-delete, sidebar,
skip-quoted, status-color, tls-sni, trash.

- Commit to: [feature/{NAME}]
- Merge into: [neomutt]
- Backport to 1.5.24?  If possible.
  * Commit to: [feature5/{NAME}]
  * Merge into: [neomutt5]

### Features that only exist in NeoMutt 1.6.1

A commit to a new feature.  These features were introduced after Mutt-1.6.0 was
released: compress, keywords, lmdb, nntp.

- Commit to: [feature/{NAME}]
- Merge into: [neomutt]
- Backport to 1.5.24?  No.

### NeoMutt

A commit to NeoMutt, e.g. a change to the README.

- Commit to: [neomutt]
- Backport to 1.5.24?  If important (and possible).
  * Commit to: [neomutt5]

### Mutt Stable

A new stable version of Mutt has been released.
This must be merged into all the feature branches.

- Commit to: [mutt/stable]
- Merge into: [feature/{ALL}]
- Merge all features into: [neomutt]

### Mutt Default

New changes have been committed to the Mutt development branch.
Most changes are ignored, for now.  However there are some changes to the
sidebar that we should adopt.

- Commit to: [mutt/default]
- Update Sidebar?  If important (and possible).
  * Commit to: [feature/sidebar]
  * Merge into: [neomutt]
  * Backport to 1.5.24?  Unlikely, but possible
    - Commit to: [feature5/sidebar]
    - Merge into: [neomutt5]

### Devel Feature

Updates to NeoMutt features under development.

- Commit to: [devel/{NAME}]
- No action required

**Comment by flatcap** [comment]
## Releases

Here are some diagrams showing possible release strategies.
For simplicity's sake, only two features and one devel branch are shown.
Commits are shown as circles.
Merges are shown in grey.

---

### Periodic Release

After a period of time, all the features are merged into NeoMutt and a release is made.
The features are merged immediately before a release is made.

![release](https://cloud.githubusercontent.com/assets/76760/16353956/4d08705a-3a7c-11e6-9301-22bb3b59a80f.png)

**History**
- Two commits are made to the features
- Features are merged into NeoMutt
- Release **R<sup>1</sup>** is made
- More commits are made to the features.
- Time passes (// on diagram)
- Features are merged into NeoMutt
- Release **R<sup>2</sup>** is made

---

### Release with Hotfixes

There are periodic releases, as before, but now fixes to features are immediately merged into the NeoMutt branch.  Distros using git HEAD can benefit immediately.

![hotfix](https://cloud.githubusercontent.com/assets/76760/16353958/4d0b6594-3a7c-11e6-8a64-b8172a186086.png)

**History**
- Two commits are made to the features
- Features are merged into NeoMutt
- Release **R<sup>1</sup>** is made
- A commit is made to a feature
- The commit is merged into NeoMutt
- This becomes Hotfix **H<sup>1</sup>**
- A commit is made to a another feature
- The commit is merged into NeoMutt
- This becomes Hotfix **H<sup>2</sup>**
- Some release criteria are met...
- Release **R<sup>2</sup>** is made

---

### Advanced

This is the same as the hotfix method, but also incorporated the latest development features.

![advanced](https://cloud.githubusercontent.com/assets/76760/16353957/4d0b532e-3a7c-11e6-8ffc-c57ba86bb6fd.png)

**History**
- Two commits are made to the features
- Features are merged into NeoMutt
- Release **R<sup>1</sup>** is made
- Release is merged into Advanced
- A commit is made to a feature
- The commit is merged into NeoMutt
- This becomes Hotfix **H<sup>1</sup>**
- A commit is made to a another feature
- The commit is merged into NeoMutt
- This becomes Hotfix **H<sup>2</sup>**
- The hotfixes are merged into Advanced
- A commit is made to a development feature
- The commit is merged into Advanced
- Release **R<sup>2</sup>** is made
- Release is merged into Advanced

**Comment by pickfire** [comment]
@flatcap I think it's better to put these useful information in wiki.

**Comment by flatcap** [comment]
@pickfire 
I will, but after discussion.
I want to be sure everyone understands how things fit together.

**Comment by grobian** [comment]
How is the integration managed of all patches together?  Where do the patches come from that can be applied on top of vanilla mutt sources?

From the looks of this, everything should be in neomutt, so alternative to applying a dozen patches, a tarball of neomutt branch should be possible?

**Comment by flatcap** [comment]
> Where do the patches come from that can be applied on top of vanilla mutt sources?

Each feature branch is exactly Mutt-1.6.1 + that feature (nothing else).  Therefore, I can do:
```
git diff mutt-1.6.1 feature/sidebar > sidebar.patch
git diff mutt-1.6.1 neomutt > combined_neomutt.patch
```

I have some clumsy shell scripts to automate some of this.

> a tarball of neomutt branch should be possible?

GitHub auto-generates a lot of source bundles.  e.g.
- NeoMutt branch (Git HEAD) -- https://github.com/neomutt/neomutt/archive/neomutt.zip
- Sidebar branch -- https://github.com/neomutt/neomutt/archive/feature/sidebar.zip
- Latest release (tag) -- https://github.com/neomutt/neomutt/archive/neomutt-20160611.zip

These should build to the same as the patches.

I thought the distros would be better off (happier?) with the patches because we can store metadata in them.  It seems that they're all quite happy to use **all** the NeoMutt patches.

**Comment by flatcap** [comment]
This what an unstable branch might look like.
All the commits that are merged into Advanced are also merged into Unstable.
In addtition it has commits cherry-picked from the Default branch.
**Note:** Some Default-branch commits are ignored.

![unstable](https://cloud.githubusercontent.com/assets/76760/16359011/67012226-3b1d-11e6-999a-10bdb84c8eb7.png)

Gentoo's patches resemble the Unstable branch.
They include the new Mutt windows code.
They don't include the Mutt mailbox re-architecting.  Some of the features will be broken by these changes, so they'll have to wait.

**Comment by pickfire** [comment]
@flatcap Do you use `dot` to draw this too? I would be surprised if yes and I hope that you can show me the souce.

**Comment by flatcap** [comment]
@pickfire 
No.  I don't think it would be possible in dot, though I'd love to be proved wrong.
I drew it in Inkscape (svg editor).
Diagrams' source:
- [branches.svg.txt](https://github.com/neomutt/neomutt/files/333519/branches.svg.txt)
- [unstable.svg.txt](https://github.com/neomutt/neomutt/files/333517/unstable.svg.txt)

**Comment by pickfire** [comment]
Ah, thanks a lot, I tried inkscape editor but I was just curious if you can even draw it in dot.

**Comment by SantiagoTorres** [comment]
It seems that there's not much discussion here anymore. Would it make sense to start wiki-fying everything? 

I think we can move these contents there and continue this in the discussion section (though it doesn't feel like it will change a lot). Thoughts?

**Comment by flatcap** [comment]
> Would it make sense to start wiki-fying everything?

Yes, please.  If I can offload that to a willing volunteer, I can get on with other tasks.

**Comment by SantiagoTorres** [comment]
I copied all of the content over to the wiki now. You can find it on:

- [Branch categories](https://github.com/neomutt/neomutt/wiki/Branch-Categories)
- [Release Procedure](https://github.com/neomutt/neomutt/wiki/Branch-Categories)
- [Alternative release procedures](https://github.com/neomutt/neomutt/wiki/Alternative-Release-Procedures)
- [How to use branches](https://github.com/neomutt/neomutt/wiki/How-to-use-branches)
- [unstable branches](https://github.com/neomutt/neomutt/wiki/Unstable-Branches)

I'll close this and continue the discussion over there. Thanks!
