### ISSUE TITLE
[Regression] compose window has hard-coded white text on black background

### ISSUE THREAD

**Issue by protist** [neomutt/neomutt#610]
* **bug reports**

    * Expected behaviour: compose screen text should follow `muttrc`
    * Actual behaviour: some colours are hard-coded
    * Steps to reproduce: compose a new email
    * Used program versions: 20170602-1, not seen in 20170428-1
    * Operating System and its version: Arch Linux, up-to-date.

I have the following set in my `muttrc`:
```
color normal     black        color231
```
Previously, in neomutt 20170428-1, this produced black text on a white background, as expected.

However, in the latest neomutt 20170602-1, some of the text in the compose screen is hard coded to white text with a black background (see screenshot below). I tested reverting to the previous version as above, and changing `color normal` is indeed reflected in all text in the compose window.

![regression](https://cloud.githubusercontent.com/assets/646668/26767121/1cbf8d10-49e0-11e7-82ed-ca4ac3ca0543.png)

Also, while I mention this, I might as well mention a possibly related bug. When calling `terminator --new-tab -x "mutt 'foo'"`, I get a large amount of black background (see screenshot below). However, I *don't* see this with `mutt 'foo'`. Also, this issue was present in the previous version of neomutt as well. It's plausibly just related to the `terminator` terminal emulator, as I can't replicate it with `konsole -e mutt 'foo'`.

![new_compose](https://cloud.githubusercontent.com/assets/646668/26767280/c895252c-49e1-11e7-8a1b-c7d9d76cef01.png)

**Comment by flatcap** [comment]
Hmm...  This is an upstream change, which defines some new objects to colour:
c6bb866: "Add color commands for the compose menu headers and security status"

It defines some new 'color compose' objects:
- header
- security_encrypt
- security_sign
- security_both
- security_none

If these aren't set, a bug in their code meant blocks of 'default' colour were used.

Branch [issue/610] should fix things.  Please can you give it a try.

**Comment by flatcap** [comment]
As for the "large blank space" bug -- that does sound like the terminal's fault, so I'm not going to investigate.
If you do, I suggest first trying a vanilla (upstream) mutt, then some old versions of neomutt.
If you can find a old version that didn't cause the problem, we can track down the problem.

**Comment by protist** [comment]
Thank you @flatcap for the quick and clear response.

> It defines some new 'color compose' objects

I tried manually setting these, and it fixes the problem.

> Branch issue/610 should fix things. Please can you give it a try.

I reverted the above changes, installed the branch, and it also works fine now.

> As for the "large blank space" bug -- that does sound like the terminal's fault, so I'm not going to investigate.

No problem at all. I mainly mentioned it because I thought you might have some immediate, off-the-cuff insight. I tested a bit more and it's intermittent… so I think I'll just leave this one alone too, given it's not a very big irritation for me.

Feel free to close this issue as you like. Thanks again.

**Comment by protist** [comment]
Oh, actually, one slight difference between the two alternative solutions…

From the index view, if I begin to compose an email with `m`, the `To: ` heading in the prompt is white on black with the master branch + `color compose` set, whereas it is black on white with the `issue/610` branch. I don't really know which is "correct" but I guess your fix is probably more consistent.

**Comment by mvdan** [comment]
@flatcap I still see somewhat similar breakage, just when updating from `20170602-1` to `20170609-1` on Arch:

![2017-06-09-11 40 44](https://user-images.githubusercontent.com/3576549/26972238-cf50c112-4d08-11e7-8391-b5fad1c110fc.png)

Should I open a new issue?

**Comment by mvdan** [comment]
Also, you can see the config I'm using to repro this breakage here: https://github.com/mvdan/dotfiles/tree/master/.config/mutt

**Comment by flatcap** [comment]
@mvdan Argh!
Yeah, I spotted that immediately after I released.
I've trampled over that release (evil, I know).
Please re-pull and re-compile and the problem should go away.

**Comment by mvdan** [comment]
@flatcap fixed, thanks :)
