### ISSUE TITLE
Can I use set crypt_opportunistic_encrypt with pgp_autoinline?

### ISSUE THREAD

**Issue by protist** [neomutt/neomutt#62]
I just found
```
set crypt_opportunistic_encrypt = yes
```
which is extremely useful. However, [the manual](http://www.neomutt.org/manual/reference.html#crypt-opportunistic-encrypt) states that "while this is set, encryption settings can't be manually changed". Indeed, the following setting now does nothing.
```
set pgp_autoinline = yes
```
However, sending PGP email as inline is necessary for me, since not all clients can read PGP/MIME. For example, AFAIK the only FOSS email client for Android that can read PGP email only supports inline (K-9 + APG). Is there no way to default to inline with `crypt_opportunistic_encrypt` also set?

**Comment by flatcap** [comment]
I could reproduce your problem and it seems that the workaround is simple.
'p' shows the PGP menu where you can select 'i' Inline.

But you're right, this is a bug.  A Mutt bug :-)

I suggest creating a Bug Report in Mutt's Trac (you'll need to create a login): https://dev.mutt.org/trac/report

As it's not a bug that NeoMutt's introduced, I'm not going to fix it.
Sorry, but my time's limited and running NeoMutt takes a lot of it.

I'll leave the bug open and if someone wants to fix it I'll happily help them (by answering questions).

**Comment by protist** [comment]
That seems perfectly reasonable. I was more curious as to whether I was configuring it correctly. If you want, I'm happy for you to close this bug and I'll file it upstream. Cheers.

**Comment by protist** [comment]
[Fixed](https://dev.mutt.org/trac/ticket/3846#comment:8) upstream.

**Comment by flatcap** [comment]
Thanks @protist, I'll merge the fix into the next release.
