### ISSUE TITLE
source mutt.vim inside neomutt.vim + file PR at vim repo

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#622]
re https://github.com/neomutt/neomutt/issues/280#issuecomment-275604878

- [ ] source mutt.vim from neomutt.vim
- [ ] include contact info and license into neomutt.vim
- [ ] file PR to include neomutt.vim at [vim/vim](https://github.com/vim/vim)

**Comment by flatcap** [comment]
> source mutt.vim from neomutt.vim

This is a bit of a problem.

The sensible way to maintain `neomutt.vim` is to auto-generate it from the code.  (This would be quite easy)

If we want to create a skeleton `neomutt.vim` with just the Neo bits, we'd have to have a list of the Mutt bits.

**Comment by toogley** [comment]
@flatcap For the long run, i think its anyways better to use only a `neomutt.vim`

**Comment by flatcap** [comment]
@guiniol has created a standalone `neomuttrc.vim` which has its own repo: [neomutt.vim](https://github.com/neomutt/neomutt.vim)

The file has also been forwarded to upstream Vim.

**Comment by flatcap** [comment]
Committed to vim upstream: https://github.com/vim/vim/commit/01164a65
