### ISSUE TITLE
notmuch: autocompletion of "to/cc/bcc" addresses

### ISSUE THREAD

**Issue by anarcat** [neomutt/neomutt#629]
Right now when you compose an email in Neomutt, the autocompletion command (`TAB`) in the `To:` field yields the list of aliases. Yet the Notmuch feature provides a way more powerful autocompletion system through the `notmuch-address` command. This is used in the Emacs notmuch client and I use it all the time, it's one of those things that make me go back to Emacs instead of switching back to mutt (along with #628).

I'm not sure how that completion works or how customizable it is, but it would seem to me like a key feature to add.

Thanks!

**Comment by anarcat** [comment]
it seems this is already doable, by binding the `query_command` parameter. this worked for me:

```
set query_command = "notmuch-address %s"
```

although the output is trimmed at 25 columns for some odd reason...

by default, `<Tab>` runs the `complete` command which looks into aliases. to complete using the `query_command`, you need to use the `^T` shortcut. to reverse the two, use this:

```
bind editor <Tab> complete-query
bind editor ^T complete
```

this means this is basically resolved. :) thanks!

**Comment by toogley** [comment]
> although the output is trimmed at 25 columns for some odd reason...

If i recall correctly, you can fix that with:

    set query_format="%4c %t %-70.70a %-70.70n %?e?(%e)?"

**Comment by anarcat** [comment]
On 2017-06-09 12:19:55, Tobias Angele wrote:
>> although the output is trimmed at 25 columns for some odd reason...
>
> If i recall correctly, you can fix that with:
>
>     set query_format="%4c %t %-70.70a %-70.70n %?e?(%e)?"

Confirmed, thanks!

**Comment by RichardKraus** [comment]
It might be worth noting that notmuch can also query for a regex (see `man 7 notmuch-search-terms`):
```notmuch address from:/<regex>/```
This means that youre able to tab complete with only part of the recipients name if you
```set query_command = "echo '' && notmuch address from:/%s/"```
(applying the echo 'n-1' fix) or similar
