### ISSUE TITLE
$sidebar_refresh_time

### ISSUE THREAD

**Issue by riesebie** [neomutt/neomutt#63]
introduced in commit `ef54f6a` `$sidebar_refresh_time` was disabled. The behavior now is that the side bar refreshes only if you navigate to a mailbox and  open it. Is there any progress to make the sidebar refresh again?

**Comment by flatcap** [comment]
@riesebie 
Sorry for the slow reply.

> The behavior now is that the side bar refreshes only if you navigate to a mailbox and open it

It _should_ be updating every `$timeout` seconds (by default this is quite large).
Ages ago, there were a lot of calls that caused the Sidebar to update **way** too often.  `$sidebar_refresh_time` was introduced to put a limit on that.

> Is there any progress to make the sidebar refresh again?

Sorry, not yet.  It requires me to set aside a good block of time, which I've been putting off for ages.
