### ISSUE TITLE
collection & suggestions of unexpressive variables/functions/structs/whatever

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#634]
I want to start a process for renaming unexpressive variables/structs/functions/whatever part of mutt into sth more readable/expressive.

For that, i've created this gist here: https://gist.github.com/toogley/b3dcd63b44a01f6660fd2eef268f64a8

I'll improve and extend that in the future. Therefore, please comment with

* other examples with unexpressive names
* and suggestions which increase the readability of the object.

**Comment by gahr** [comment]
Was this superseded by #582? Can this be closed?

**Comment by toogley** [comment]
@gahr i don't think it is, see the gist.
