### ISSUE TITLE
lua: linking to the wrong library and various unpolished install issues

### ISSUE THREAD

**Issue by Elv13** [neomutt/neomutt#638]
While it is totally possible to get it to work (and I did), the process isn't very polished yet. Here's a few "bug report" to document the issues I had when porting my muttrc to Lua (thanks *a lot* for this feature, it was in my TODO list for a decade. disclaimer: I am one of AwesomeWM maintainers)

* It require Lua >=5.2 in `./configure`, but 5.1 is the most used version of Lua (thanks to luajit2.0). Gentoo uses lua5.1 as the default target because Lua isn't designed to support `.so` and many programs don't compile when there is multiple versions (see https://github.com/awesomeWM/awesome/issues/1757).

* Also, `./configure` says Lua is enabled when `LUA_VERSION` is set, however it doesn't actually enable it (`USE_LUA` isn't set in `configs.h`).

* Even when correctly compiled, the executable cannot be executed due to linking to the wrong file

* I don't think you can use static lua libraries yet, but I may be mistaken. It would be nice to be able to have Lua in `mutt` binary to avoid the mess (but it would break some `.so` Lua libraries) 

Expected behavior:

mutt is linked correctly

Actual behavior:

mutt isn't linked correctly, but make didn't print an error (just linked to a file that doesn't exist)

Steps to reproduce:

    ./configure --enable-everything  --enable-lua --without-kyotocabinet --without-qdbm --without-bdb --prefix=$HOME/prefix LUA_INCLUDE=-I/home/email/prefix/include/ LUA_LIB=/home/email/prefix/lib/liblua.so

Lua installed with

    make linux INSTALL_TOP=$HOME/prefix CFLAGS=-fPIC -j TO_LIB="liblua.so"

Only `liblua.so` is created and installed

Result:

    TERM="xterm-256color" LD_LIBRARY_PATH=$HOME/prefix/lib/ ./mutt
    ./mutt: error while loading shared libraries: liblua.so.5.3: cannot open shared object file: No such file or directory

Operating System and its version:

Gentoo Linux

**Comment by flatcap** [comment]
Thanks for the feedback @Elv13.
We're still figuring out the {what,how,why} of Lua.
I'm sure we'll have lots of questions for you soon :-)
