### ISSUE TITLE
index-color: using bright in index makes index_* bright

### ISSUE THREAD

**Issue by 4nd3r** [neomutt/neomutt#64]
comment out all color lines and add:

```
color index brightyellow default ~A
color index_subject green default ~A
```

run mutt and observe: subject is also bright(green).

**Comment by flatcap** [comment]
Congratulations!  You win the prize (there's no prize) for the most interesting bug.

I've had a quick look through the code and even though I sort-of know what's causing the problem, I can't see where.

**Comment by toogley** [comment]
still happens with `NeoMutt 20161104 (1.7.1)`

**Comment by guyzmo** [comment]
just checked with latest. indeed quite interesting one. I can see two ways to theoretically solve the issue:

- reset all colour attributes when applying a format (including bright, underlined, inversed etc.)
- when applying a colour force all the attributes to the expected value (not bright, not inversed etc.)

**Comment by flatcap** [comment]
Even though this is a bug, this issue has been closed.

To fix it will require major changes to mutt.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
