### ISSUE TITLE
"folder" setting has "/INBOX" in it, but 'c?' doesn't descent down below INBOX

### ISSUE THREAD

**Issue by psprint** [neomutt/neomutt#640]
* **bug reports**
    I do:
    ```
    set folder                      = imaps://mydomain/INBOX
    ```
    and then invoke folder switching, via c?

* Expected behavior
    Subfolders of INBOX to be shown

* Actual behavior
    Only INBOX shows, I have to descent to it to see INBOX subfolders. On original `mutt`, this works, appending "/INBOX" causes c? to automatically descent to subfolders
* Steps to reproduce
    Do:

    ```
    set folder                      = imaps://mydomain/INBOX
    ```

    and then press: c?

* Used program versions

    NeoMutt 20170609-29-71984f (1.8.3)

* Operating System and its version

    OSX 10.11.5

* Why do you not like the current state?

    Because constant entering to "INBOX" is needed

* What would you like to see to change?

    Like original `mutt`, to immediately see subfolders of "INBOX", if `$folder` has trailing `/INBOX`

**Comment by P-EB** [comment]
This one is my fault.

I fixed the behaviour so it goes back to what it previously was,  but I had to rollback one line from @gahr 's commit d28e8e1 .

I'd need some review to ensure I didn't break the behaviour he wanted to introduce.
