### ISSUE TITLE
Merge the out-of-tree Gmail Search patch

### ISSUE THREAD

**Issue by drzraf** [neomutt/neomutt#644]
https://people.spodhuis.org/phil.pennock/software/mutt-patches/

> gmailcustomsearch: GMail's IMAP X-extension for custom search
>   Gmail has powerful native search which does not fit the normal IMAP search model. Google have exposed this functionality over IMAP with a custom extension. This patch adds the =/ operator, to perform a server-side search using this extension.n

* Why do you not like the current state?
Because I can't use the full power of "my"^W"their" IMAP server

* What would you like to see to change?
Because it help in the daily life to, eg, filter message according to a powerful and extended set of criterium letting the server do the hard work and without the need of keeping a fully synced local copy

**Comment by flatcap** [comment]
Thanks for the suggestion @drzraf.
We'll take a look.

**Comment by flatcap** [comment]
@drzraf The patch was pretty simple, so I've tidied it up and pushed to branch [[devel/gmail](https://github.com/neomutt/neomutt/tree/devel/gmail)]
I don't have a suitable GMail account any more, so it needs some testers.

/cc @philpennock (patch author)

**Comment by flatcap** [comment]
GMail API: https://developers.google.com/gmail/imap/imap-extensions

In case anyone would like to improve the patch.

**Comment by d-k-c** [comment]
It seems to work with some limitations, like patterns with spaces that fail to compile if string is unquoted (not specific to GMail's search, but it's easy to miss that one): 

> =/has:attachment and in:inbox

and it doesn't behave exactly like the search bar in the webapp, as searching for emails located in another folder will fail, but I guess this is a limitation of IMAP SEARCH.

**Comment by philpennock** [comment]
The description on the web-page for the patch does note:
> Note that to get the nearest equivalence to typing into the search box, you first need to navigate to the "[Gmail]/All Mail" folder; by default, the IMAP server-side implementation seems to add folder constraints, which is obviously correct for IMAP -- you can't return message references that don't make sense in a given context.

**Comment by flatcap** [comment]
Please can someone document this for us.
We don't need much, just a quick explanation of what it can do, its limitations and a few examples.

**Comment by drzraf** [comment]
Isn't this:
> gmailcustomsearch: GMail's IMAP X-extension for custom search
>   Gmail has powerful native search which does not fit the normal IMAP search model. Google have exposed this functionality over IMAP with a custom extension. This patch adds the =/ operator, to perform a server-side search using this extension.

enough?
I'm sorry I can't test git's neomutt ATM, but new inputs may come when the patch reach Mutt's Gmail users.

**Comment by flatcap** [comment]
I was hoping for a bit more (a PR would be nice :-)

In @d-k-c's post he used:

> has:attachment and in:inbox

What other keywords exist?
How does the logic work?  'and' is clearly there, what about 'or' and '()'s?

**Comment by drzraf** [comment]
https://support.google.com/mail/answer/7190?hl=en

**Comment by philpennock** [comment]
The keywords are outwith the control of neomutt and can change at any time, so a pointer to upstream and suggested keywords in case that link breaks, to allow it to be found again, are probably best.

Key is to ensure you switch to the `[All Mail]` folder (which might need to be enabled) before running the search, because IMAP searches can only return results in the current folder whereas GMail defaults to searching all mail.  There's not much that mutt can do with its current model to get away from that.

**Comment by flatcap** [comment]
I agree that GMail's API _could_ change, so a link to the definitive source is needed.
But self-contained documentation in Mutt is needed.

Can someone **please** write a paragraph of documentation for this feature and give a few examples.

**Comment by philpennock** [comment]
Something like this?  Written off the cuff, have not provided source format markup:

---
=/ "search terms" invokes server-side search, passing along the search terms provided. Search results are constrained by IMAP to be within the current folder. At present this only supports Gmail's search API IMAP extension. The search language is entirely up to the mail provider and changes at their discretion. Using ~/ will silently fail.

For Gmail, the documentation can currently be found at <https://support.google.com/mail/answer/7190?hl=en>. You will need to (once) use a web-browser to visit Settings/Labels and enable "Show in IMAP" for "All Mail". When searching, visit that folder in mutt to most closely match Gmail search semantics.

Examples for Gmail:
 * =/ "list:foo.example.org has:attachment is:important" -- matches the foo.example.org mailing-list per Gmail's definitions, and has an attachment, and has been marked as important.
 * =/ "{has:purple-star has:yellow-star} older_than:2m" -- is older than two months and has either a purple-star or a yellow-star

**Comment by flatcap** [comment]
Lovely job :-)

**Comment by flatcap** [comment]
Merged. Thank you @philpennock , @drzraf.
