### ISSUE TITLE
ld missing commandline arg for libtinfow.so

### ISSUE THREAD

**Issue by 257** [neomutt/neomutt#65]
```shell
git pull
./prepare
./confgiure "$see_config_log_for_args"
make
```
[configure.log](https://gist.github.com/8cbe436cdc4a2754c1b749b0fa39f7b6)
[make.log](https://gist.github.com/efc73d23bb5058d25667aa2734931dee)

**Comment by 257** [comment]
this might help;

build system is gentoo. ncurses can be built in two different ways depending on whether tinfo USE flag is set or not:

 tinfo : Build curses library (libncurses) sep from the low-level terminfo library (libtinfo) -- usually needed only for binary packages -- but it is binary compatible in either mode

**Comment by flatcap** [comment]
Does vanilla Mutt compile correctly?

**Comment by 257** [comment]
would that be mutt/stable?

**Comment by flatcap** [comment]
Yes.  I'm wondering what I've introduced to break the build.

**Comment by 257** [comment]
same error with mutt/stable.

**Comment by flatcap** [comment]
OK, then.  Sorry to sound lazy, but that's Mutt's problem.

**Comment by 257** [comment]
what's the latest building fine for you?

**Comment by flatcap** [comment]
The current NeoMutt source in git builds for me, but if mutt/stable doesn't build then it's bug Mutt needs to fix.  I'm sorry. I don't have the time to fix everything :-(

**Comment by 257** [comment]
and your system?

**Comment by flatcap** [comment]
I'm on Fedora 24.  The Travis build box is Ubuntu (Trusty 14.04).

It's odd, because @grobian (Gentoo NeoMutt maintainer) hasn't mentioned any problems.

**Comment by grobian** [comment]
we do have a tinfo patch for this IIRC

**Comment by grobian** [comment]
https://github.com/neomutt/integration/blob/patches/gentoo/0001-ncurses-tinfo.patch

**Comment by flatcap** [comment]
@grobian 
Thanks.
@257 I'm sorry, I'm forgetful / an idiot :-)

**Comment by flatcap** [comment]
I'll promote that patch into the "all distros" for the next release.

**Comment by grobian** [comment]
I'll try to submitt it to mutt-dev again, maybe more luck this time

**Comment by 257** [comment]
@grobian there is an ebuild for neomutt? these come up empty:
eix neomutt
e-file neomutt

**Comment by grobian** [comment]
it's called "mutt" in Gentoo ;)

**Comment by 257** [comment]
i see sidebar but no notmuch use flag?
@flatcap neomutt builds with @grobin's patch applied here.

**Comment by flatcap** [comment]
NeoMutt is the base and some distros add their own patches.
There's [a diagram](https://github.com/neomutt/neomutt/issues/28).
The patch you need is in Gentoo (at the bottom).  I'll move it into Bugs-Common, at the top.

**Comment by grobian** [comment]
@257: I'll add it

**Comment by grobian** [comment]
@257 it's in 1.6.1-r2, which is still keyword-masked, want to release it in ~arch soon.

**Comment by 257** [comment]
thanks

**Comment by bitstreamout** [comment]
Stupid question: as libtinfo and libtinfow are binary comptible, that is that libncursesw can be linked with libtinfo why there exists a libtinfow at all? This works here well.   Beside this for the libncursesw.so and libncurses.so I use not a symbolic link but linker scripts wich looks like

/* GNU ld script */
INPUT(/lib64/libncursesw.so.5 AS_NEEDED(-ltinfo))

nevertheless a check for tgetent which is in libtinfo(w)

https://github.com/neomutt/integration/blob/patches/suse/0007-mutt-1.5.21-tinfo.patch

seems to be useful.

**Comment by 257** [comment]
@grobian still don't see 'notmuch' USE for mutt. i'm syncing to 'git://git.gentoo.org/gentoo-portage' though. any idea?

**Comment by grobian** [comment]
@257 https://gitweb.gentoo.org/repo/gentoo.git/tree/mail-client/mutt/mutt-1.6.1-r2.ebuild

**Comment by 257** [comment]
@grobian eix had me fooled :) thanks.
