### ISSUE TITLE
Old flag in new (unseen) messages in /cur (Maildir)

### ISSUE THREAD

**Issue by epilys** [neomutt/neomutt#650]
When syncing my e-mails with offlineimap (which stores mails in Maildir `/new `with empty flags `:2,` even though they are new) and tagging them with a notmuch post-new hook (which moves mails from `/new` to `/cur` because they have an info field `:2,`), mails stop being flagged as N in neomutt and show up as O. This is because they are in `/cur` instead of `/new`, but not have an S flag (ie their filenames end up at `:2,`). This is really inconvenient when you don't use the Old flag at all in your workflow (I have mark_old unset). Is it easy/possible to make a `disable_old` option and treat old mails as new? I'd be interested in doing this.

I think this [offlineimap issue](https://github.com/OfflineIMAP/offlineimap/issues/80) describes why this is happening. Since it's not possible to change the rest of the stack, maybe configuring it in neomutt is a good idea. I don't know why Old is still used if you unset `mark_old` anyway.

**Comment by flatcap** [comment]
fixed by 2466dac
