### ISSUE TITLE
Build fails because hcache_tc.o: In function `hcache_tokyocabinet_close':

### ISSUE THREAD

**Issue by Knusper** [neomutt/neomutt#652]
I configure - after running `./prepare`:

`./configure --prefix=${HOME}/local/ --enable-sidebar --enable-smtp --with-curses=/usr --with-ssl=/usr --with-gnutls=/usr --with-sasl=/usr  -with-tokyocabinet --with-domain=ktop.suse`

Then I run make and the build fails:
```
hcache_tc.o: In function `hcache_tokyocabinet_close':
/home/knusper/compiled-projects/neomutt-neomutt-20170428/hcache_tc.c:92: undefined reference to `mutt_debug'
hcache_tc.o: In function `hcache_tokyocabinet_open':
/home/knusper/compiled-projects/neomutt-neomutt-20170428/hcache_tc.c:39: undefined reference to `mutt_debug'
```

**Comment by flatcap** [comment]
hmm... that would only happen if `hcache_tc.c` had been compiled with debug enabled, but not the rest of the build.  Were some files left over from a previous build?

**Comment by Knusper** [comment]
I downloaded the tar.gz and ran prepare - before I ran `make uninstall && make clean` on the directory of the older release.

**Comment by Knusper** [comment]
Please close this embarissing bug - I just saw `neomutt-neomutt-20170428/` - thats old.
