### ISSUE TITLE
x-labels/Keywords capabilities do not match the manual

### ISSUE THREAD

**Issue by evgmik** [neomutt/neomutt#653]
* **bug reports**

commit 92e6dc1d89f7187eeea1412e51598600925e23f5 breaks 'keyword feature' described in the [feature keyword](https://www.neomutt.org/feature/keywords) manual. 
As much as I can see the problem is due to mass deletion starting at line 456 in copy.c

    * Expected behavior
      Neomutt should save Keywords: header when 'set keywords_standard = yes';
      Labels from: 'X-Keywords', 'Keywords', ' X-Mozilla-Keys' should be processed and used for completion suggestions in <edit-label>;
      '$xlabel_delimiter'  should be reflected in tag separation saved in X-Labels:.

    * Actual behavior
      Keywords: header is not saved when 'keywords_standard = yes';
      '$xlabel_delimiter' has no effect anymore for tags saved in X-Labels:. X-Labels always treated as a 'free form' i.e. one long line.
      Labels from: 'X-Keywords', 'Keywords', ' X-Mozilla-Keys'  are not loaded or used
    * Steps to reproduce
      edit mail message and introduce  'X-Keywords', 'Keywords', ' X-Mozilla-Keys' , and 'X-Label' headers;
     ~~~~~
      set keywords_standard = yes;
      set xlabel_delimiter = ", ";
     ~~~~
      execute edit-label on a mail message, change tags/labels. Observe that labels from   'X-Keywords', 'Keywords', ' X-Mozilla-Keys'  are not offered. Edit labels to your liking. Sync maildir and observe that   'Keywords:' header is not set. 
    * Used program versions
       Compiled 'master' marked as 
       commit 74920a6c56080d99af0e11bc50b6fa4ae7d3be5c
    * Operating System and its version
        Irrelevant

**Comment by P-EB** [comment]
Poking @xdgc as it's his work.
