### ISSUE TITLE
high resolution icon

### ISSUE THREAD

**Issue by aradici** [neomutt/neomutt#655]
Currently mutt/neomutt provides a xpm icon, which is not really highres (http://bugs.debian.org/854127); any chance we could have a high resolution icon for neomutt?

Thanks!

**Comment by flatcap** [comment]
I've added three `png`s and an `svg` of the Mutt logo (32px, 64px, 128px) in `contrib/logo`
How high-res do icons need to be these days for HiDPI displays?
I can add some more, if needed.

**Comment by aradici** [comment]
The bigger that we have in Debian is 256x256, but 128x128 is pretty good. If you have something of that size feel free to add it, otherwise I think you can resolve this issue

**Comment by flatcap** [comment]
fixed by a7ad313
