### ISSUE TITLE
add a command to verify a signed message

### ISSUE THREAD

**Issue by aradici** [neomutt/neomutt#656]
This is a nice to have feature, from the debian bug report:
http://bugs.debian.org/456212

+++++++++
I would like to be able to invoke a command to verify the signature of
the current message in the index or pager.

I know it's possible to do this with a macro that temporarily resets
crypt_verify_sig to yes, redisplays the message, and then sets it
back, but that's an ugly hack.
+++++++++

This was reported upstream in bugs.mutt.org/3260 but it didn't get much traction

**Comment by P-EB** [comment]
I'm a bit uncertain about the benefits of such a feature as mutt already checks the signature when you open a message.

**Comment by aradici** [comment]
yes, but the user in this particular case wanted to check from the index, rather than opening the message

**Comment by gahr** [comment]
`check-traditional-pgp` does that in the index. Its default mapping is `^P`. However, the `s` in the flags does not automatically turn `S` - this might be investigated.

Is that what you need or am I missing something?

**Comment by flatcap** [comment]
Moving this to the long-term wish list.
