### ISSUE TITLE
feature request: using $my_vars in macro <shell-escape>'s

### ISSUE THREAD

**Issue by demure** [neomutt/neomutt#658]
According to my conversation with @flatcap, currently a variable in `<shell-escape>` is passed to the shell as a literal string. Having the ability to interpolate variables into a ` <shell-escape>` could allow for some useful/flexible macros.

Example of what I tried to implement:

    macro index \Co     "<shell-escape>offlineimap -a $my_account -f INBOX -u quiet &>/dev/null<enter>" "run offlineimap to sync current inbox."

With each of my accounts has a hook to set `$my_account`.

The above would allow me to avoid having a static macro which each account over writes via hooks, which feels less clean.

Maybe we could use a `<$my_var>` in a `<shell-escape>` to tell mutt what to interpolate?

**Comment by somini** [comment]
My workaround for this limitation is redefining the macro on a folder hook, after changing the variable name.

This could lead to so many issues I think it should be punted to the Lua API.

**Comment by flatcap** [comment]
Some thoughts...

Might this change break an existing user's commands?
Perhaps if they were using shell variables of the same name as mutt variables?

If the user wants to specify a _shell_ variable, what would they do?  Escape it?

```
command $mutt_var \$HOME
```

**Comment by demure** [comment]
since the `<shell-escape>` already does something special for `<enter>` and other `<>` tags, I was thinking this might work:
`macro index \Co     "<shell-escape>offlineimap -a <$my_account> -f INBOX -u quiet &>/dev/null<enter>" "run offlineimap to sync current inbox."`

**Comment by somini** [comment]
I'm leaning to using the Lua API to avoid this headaches. Something like:
```
function run_offlineimap()
  arguments = ["offlineimap","-a",mutt.get("my_account"),"-f","INBOX","-u","quiet"]
  call?(arguments)
end
```
And then attaching this function to a keybinding. I'm not sure the Lua API is advanced enough to do this.

**Comment by somini** [comment]
Just checked, no command to execute `shell-escape` exposed to the Lua API.
https://github.com/neomutt/neomutt/blob/master/init.h#L4554

I tried the hack:
```lua
os.execute('echo ' .. mutt.get('folder') .. ' | tee ~/TSTLUA')
```
and it works, but the output is just dumped into the terminal, and stdin is not redirected, so it's ugly.

**Comment by flatcap** [comment]
It's an interesting idea, but nobody seems to have any time to code it.
If someone volunteers to work on it we can re-open the issue.
This issue will now be closed and listed on the [closed discussions page](https://www.neomutt.org/dev/discussions)
