### ISSUE TITLE
Macros give constant visual feedback

### ISSUE THREAD

**Issue by protist** [neomutt/neomutt#66]
I actually noticed this a month or so ago, but have only just got around to write up an issue (sorry!). In the current release of NeoMutt, the actuall command that is triggered by a macro is printed on the screen. Hence, I have a macro defined as

    g1 "<change-folder>=alias-inbox/main<enter>"  "go to main inbox"

When I press `g1` in mutt, I literally see the text `Open mailbox: =alias-inbox/main` being typed out. This isn't terrible in this example, but is fairly slow for longer macros. In previous versions on NeoMutt, macros operated silently, and this appeared to be quite quicker (but I haven't benchmarked).

**Comment by andrewalker** [comment]
Same happens with me. Quite slower, and a bit weird.

**Comment by scottkosty** [comment]
I also have noticed this change and am using mutt-kz (I have not switched to using neomutt yet), in case that provides any clues.

**Comment by scottkosty** [comment]
For you neomutt users then, an interesting question is do you see this when you do not enable any of neomutt's features?

**Comment by protist** [comment]
To double-check, I installed vanilla mutt, both the latest stable version 1.6.1, and the latest development head r6710.bf1c73de2b7c. Both of these do *not* give any visual feedback when running macros. I can also confirm that vanilla mutt is *sooooo* much snappier than neomutt. There is a severe slowdown introduced by this bug.

**Comment by protist** [comment]
Huh… I found this bug in the AUR's [neomutt](https://aur.archlinux.org/packages/neomutt/) package. I tested the AUR's [neomutt-git](https://aur.archlinux.org/packages/neomutt-git/), which installs the latest development version, but it's been fixed in there!

*However*, in the git version, the addendum to issue #16 is back. That is, in the stable neomutt release, `mutt -Z` works as expected, but fully prints macros and is laggy. However, in the unstable neomutt-git, `mutt -Z` fails (with `No mailbox with new mail.`), but doesn't print macros and is snappy again. What a dilemma!

I'm happy to troubleshoot more! Just tell me how!

**Comment by flatcap** [comment]
Thanks for the investigation @protist.

I'm guessing that the sidebar is trying to refresh itself after each character is drawn -- that might explain the behaviour.  I think the macro string is probably **always** drawn, but it's usually wiped again before the next screen refresh happens.

Kevin McCarthy (Mutt maintainer) has just finished his Sidebar updates in Mutt and I've merged them into NeoMutt.  They should fix a lot of the refresh problems.

I've just tried a **very** long macro and it worked instantly without any visible text on screen.
I've got a lot of merges to do and a lot of checks to do, but I'll be pushing the changes soon.

**Comment by protist** [comment]
No worries; I'd be glad to help find a fix to this. Looks like you've got your hands full, so I'm happy to wait and see how things settle. Please let me know if you want help tracking down a solution to `mutt -Z`.

Also, FWIW, I don't have `set sidebar_refresh_time` in muttrc (I'm not sure if that is relevant).

**Comment by Alok** [comment]
I have the latest version, and I no longer get this bug.

**Comment by protist** [comment]
Yes, as per my comment [above](https://github.com/neomutt/neomutt/issues/66#issuecomment-230147873) the latest version seems fine now. I'll close this issue.
