### ISSUE TITLE
"color index_subject..." is bleeding to the next line

### ISSUE THREAD

**Issue by jmtd** [neomutt/neomutt#664]
I have `color index_subject brightwhite  default '~O'`, and if the subject is truncated, then the colour bleeds into the next line down (in my case, over the next email's number):

![neomutt_bug_color_index_subject](https://user-images.githubusercontent.com/63694/27913604-981cbcae-6258-11e7-97bb-88a9fd458291.png)

Note in the example that email 597 has the subject brighwhite, the subject is truncated at the end of the line, and the number 598 is alsounintentionally brightwhite.

By contrast, email 604 matches, the subject is brightwhite, the subject is not truncated, and so email 605 is unmolested. (Email 605 is a mail *from* me, but that is not relevant, elsewhere in this mailbox I can see the bug manifest where this is not the case).

Specific neomutt version is Debian package 1.8.3+neomutt20170609-2

**Comment by fbellet** [comment]
It seems that the function that formats the index string simply truncates the output buffer to the number of columns of the terminal, ignoring the escape sequence that may be located at the end of the input buffer to restore the terminal attributes. Does this patch work for you ?

**Comment by 4nd3r** [comment]
similar to #64

**Comment by flatcap** [comment]
Fixed by #685
