### ISSUE TITLE
Adding this project to an openSUSE YaST repository?

### ISSUE THREAD

**Issue by rlue** [neomutt/neomutt#668]
Hello all,

I just made the leap to Linux (openSUSE Tumbleweed) from Mac OS, so forgive my lack of knowledge on the matter:

I'd like to install neomutt on my system using the YaST package manager (`zypper`), but have not found any official or community-maintained repositories containing the package. All I've found so far is [a small handful of repositories maintained by individual users](https://software.opensuse.org/package/neomutt), which I worry may not be updated consistently as new releases of NeoMutt come out.

Is there another repo managed by the neomutt maintainers, so that I can keep up with updates without having to manually check the neomutt site or having to build from source? And if not, what would it take to get one?

Thanks in advance.

**Comment by toogley** [comment]
I guess https://www.neomutt.org/distro/fedora can help here? I guess that's the most frequently updated RPM repository, because its run by the project leader.

**Comment by flatcap** [comment]
A quick search finds: https://software.opensuse.org/package/neomutt 
It has the latest NeoMutt version in both Tumbleweed and Leap 42.2 (and the previous version in Leap 42.3)
Are these what you're looking for?

They're maintained by @sassmann (who's a NeoMutt member) and @devmotion
Guys, would you be interested in adding a "Distro Page" - https://www.neomutt.org/distro.html
Is there anything I can do to help streamline the release process for OpenSuse?

**Comment by rlue** [comment]
Much appreciated; I did not realize @sassman and @devmotion were team.

**Comment by sassmann** [comment]
I'm not really involved in openSUSE anymore but the OBS is a cool tool for building RPMs. So my RPMs are more or less regularly updated but I only use/test the Fedora ones. Occasionally they contain test patches as well. Therefore I'd rather not advertise my own RPMs.
It's more of a personal playground that everyone is free to join. :)
