### ISSUE TITLE
Change in "change folder" due to drop of VirtIncoming

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#669]
After 1116748c, if I press 'c', I am given the following prompt:

    Open mailbox ('?' for list): notmuch:///home/scott/.mail?query=date:yesterday..

where before I was given

    Open mailbox ('?' for list):

Was this change in behavior intended? I wasn't sure, but noticed the commit message that the changes should not have a visible effect.

I am on Ubuntu 16.04 and use the following prepare command:

    ./prepare --enable-imap --with-ssl --with-sasl --enable-notmuch --enable-smtp --enable-debug --with-tokyocabinet

If you cannot reproduce, let me know and I can spend some more time figuring out a minimal .muttrc to post.

**Comment by flatcap** [comment]
> changes should not have a visible effect

That was the plan.  The virtual folders _used_ to be kept in a separate list.
I have a plan to group the mailboxes (but there are a few other steps first).

I'll have a think about the prompt.  It'll be easy to filter out the virtual folders, but...
I'm wondering if a notmuch user might _want_ to be offered a virtual folder.

New mail would appear in one real and possibly several virtual folders.
Which would a user rather be prompted with?
Which would _you_ prefer?

Thanks for letting me know.

**Comment by scottkosty** [comment]
> Which would a user rather be prompted with?
> Which would you prefer?

I'm really not sure. I liked having the previous prompt so that I could easily press "tab" and be given a list of folders to change to. But I can easily add a macro that does this. Perhaps we could ask some other notmuch users? @julian-klode @bbenne10 @paratje @WPettersson

**Comment by bbenne10** [comment]
I've somewhat embraced the use of tags and queries over folders and so I don't even *use* this menu. (I have "bind index,pager / vfolder-from-query" set to do a search and show me my results rather than use defined folders of them)

I imagine that the macro is easy enough to add, but I don't particularly have a deeper opinion on the matter at all. While the concept of "folder" is key to mutt, I tend to create and throw away virtual folders pretty regularly...

**Comment by bbenne10** [comment]
(that being said - 1116748 looks to have a lot of negative code, which is awesome!)

**Comment by scottkosty** [comment]
> (that being said - 1116748 looks to have a lot of negative code, which is awesome!)

+1

**Comment by scottkosty** [comment]
I've been thinking about this the last couple of days. I think the reason I like the previous behavior is that I don't like seeing notmuch anywhere unless I call it. I'm not sure where the output

    notmuch:///home/scott/.mail?query=date:yesterday..

comes from. I looked in my muttrc settings and I don't know what causes that to appear. That is why I find it strange. I'm just switching from my INBOX (it's not virtual) or any other mailbox (also not virtual or notmuch-related). Do other notmuch users see the same string? If not, then it must be a config variable I have set somewhere.

But again, if it would be a pain to show the simple output of no predefined path, then I could get used to it by making a macro. I'm just not sure if anyone would prefer the new behavior.

@karelzak any thoughts?

**Comment by flatcap** [comment]
Commit 212eadf restores the original behaviour -- `<change-folder>` will ignore virtual folders.
(but keeps all the simplification changes).

I _meant_ to get that into last week's release.  Sorry.

**Comment by scottkosty** [comment]
Great, thanks for that!

**Comment by gahr** [comment]
I understand this has been solved? Feel free to reopen if it's not.
