### ISSUE TITLE
Mailto handling

### ISSUE THREAD

**Issue by cryptomaniac512** [neomutt/neomutt#67]
Hi,

I like clickable 'mailto:' urls, but mutt can't work with this.

For example create mutt.desktop file for working with xdg-open:
`[Desktop Entry]`
`Type=Application`
`Categories=Email`
`Name=Mutt`
`Exec=i3-sensible-terminal -t Mutt -e mutt`
`StartupNotify=true`
`Icon=mutt`
and create string in mimeapps.list
`x-scheme-handler/mailto=mutt.desktop`

If I click on mailto elsewhere mutt runs but not for sending mail. Similarly when you run the xdg-mail with attributes.

I found a variety of solutions in the forums, like this:
In desktop file
`Exec=i3-sensible-terminal -t Mutt -e mutt %u`
or [this script](https://github.com/pazz/scripts/blob/master/mailto-mutt)

But all these solutions does not work correctly.

Is there a solution for this problem?
I found [this project](http://mailtomutt.sourceforge.net/) but do not know how to build it and how to work with this.

Sorry for my bad English.

**Comment by cryptomaniac512** [comment]
I wrote "does not work correctly" because forums users are with this and maybe they are satisfied...
But in my case, everything is bad. xdg-email refuses to work with an error, or simply launches mutt.

**Comment by ilintault** [comment]
For those of you on OS X check this:

https://github.com/ilintault/mailtomutt

**Comment by parchd-1** [comment]
@cryptomaniac512 - try  `Exec=i3-sensible-terminal -x mutt %u` instead. `-e` doesn't expect extra parameters to the command.
It is now working perfectly for me (although I never click on mailto urls, so this was all just out of curiosity for me).

**Comment by flatcap** [comment]
It's a good idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).

**Comment by tgy** [comment]
+1 this would be great, parsing the mailto to start writing a new mail
