### ISSUE TITLE
Impossible to join threads from a notmuch vfolder

### ISSUE THREAD

**Issue by guyzmo** [neomutt/neomutt#672]
* Expected behavior

when doing `&` or `#` on a thread it should join or split a thread.

  * Actual behavior

the index is changed accordingly, but it cannot persist the changes on `$`.

  * Steps to reproduce

1. tag a mail
2. move to a mail in a thread
3. hit `;&` to join that tagged mail in a thread

or

1. move to a mail in a thread
2. hit `#` to split that thread

**Comment by flatcap** [comment]
Thanks for the suggestion, but have a lot of work ahead of us before we could ever benefit from a framework like libyui.
