### ISSUE TITLE
Every mbox "unread"

### ISSUE THREAD

**Issue by hvkls** [neomutt/neomutt#674]
NeoMutt 20170714 (1.8.3) on Mac OS X 10.11.6 El Cap.

This version marks every mbox defined "unread", not just those actually containing unread mail.

Edit: I went back to 20170707-1-383dc2.

**Comment by flatcap** [comment]
Hmm... That's very strange.
Not only that, but very little changed between 0707 and 0714.
Do you know how to (and do you have time to) "git bisect" between the two versions?

**Comment by hvkls** [comment]
I'm running into problems here:

```
# git bisect start
# git bisect bad
# git bisect good 180546cb
Bisecting: 139 revisions left to test after this (roughly 7 steps)
[fa4b54ea4f9b56dacb8c4c6d08acd070992cbeca] build: remove unnecessary steps
git bisect good
Bisecting: 69 revisions left to test after this (roughly 6 steps)
[be347fd960c417448b7b00260af692f6808ed778] bcache: cast to avoid implicit signed/unsigned comparison in bcache_path
# make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /opt/src/neomutt/.build-aux/missing aclocal-1.15 -I m4
 cd . && /bin/sh /opt/src/neomutt/.build-aux/missing automake-1.15 --foreign
configure.ac:16: error: required file './compile' not found
configure.ac:16:   'automake --add-missing' can install 'compile'
configure.ac:20: error: required file './config.guess' not found
configure.ac:20:   'automake --add-missing' can install 'config.guess'
configure.ac:20: error: required file './config.sub' not found
configure.ac:20:   'automake --add-missing' can install 'config.sub'
configure.ac:8: error: required file './install-sh' not found
configure.ac:8:   'automake --add-missing' can install 'install-sh'
configure.ac:8: error: required file './missing' not found
configure.ac:8:   'automake --add-missing' can install 'missing'
Makefile.am: error: required file './depcomp' not found
Makefile.am:   'automake --add-missing' can install 'depcomp'
make: *** [Makefile.in] Error 1
# autoreconf -i
# git bisect good
Bisecting: 34 revisions left to test after this (roughly 5 steps)
error: The following untracked working tree files would be overwritten by checkout:
	doc/pgpewrap.1
	doc/pgpring.1
	doc/smime_keys.1
Please move or remove them before you switch branches.
Aborting
```

I can't remember how I got there, but I think you might want to check this one first:

```
dc210ead2eef0af349094b34065ad1f5e8858b89 is the first bad commit
commit dc210ead2eef0af349094b34065ad1f5e8858b89
Author: Richard Russon <rich@flatcap.org>
Date:   Sat Jul 8 12:40:15 2017 +0100

    fix: stop allowing duplicate mailboxes

:100644 100644 d51948214451abf8d4a71939c3ca4c2271583246 346bb99954376f282424e0f81cb0cdcc93a78df3 M	buffy.c
```

**Comment by flatcap** [comment]
Thanks, I'll take a close look at that.

**Comment by flatcap** [comment]
The bisect seems to be breaking because of build products left from the earlier builds.
I tend to `git clean -xdf` before each build (note this will delete ALL non-repo files).

I'm careful when pushing to master to make sure that all commits build for a selection of configs.
(you can `git bisect skip` if you come across an exception, though).

I've just looked at the commit you mentioned an that's just a fix to the parsing of the mailboxes code.
The mistake prevented mutt from de-duping the `mailboxes` command.  I'm certain that can't be your problem.

Would you mind retrying that bisect?
I'm in IRC, if you need a hand.

Thanks.

**Comment by hvkls** [comment]
Using `git bisect skip` (and losing SSL on the way), I could narrow it down to that `buffy.c` change once more.

Here's my mailbox command:

`mailboxes ! $(ls -1 $HOME/Mail/* | egrep -v "(gz|nntp|sent|Drafts|Sent|Templates|Trash|msgid.cache|sbd|sdb|save|save.nntp|save.nntp.mac|debian)" | tr   "\012" " ")`

**Comment by flatcap** [comment]
Oh.  I'm very confused.
Thanks for taking the time to check.
I'll have a think.

**Comment by nobrowser** [comment]
@hvkls : do you have `check_mbox_size` set?

**Comment by hvkls** [comment]
@nobrowser 

I don't use the sidebar; I'm talking about the mailbox view.

I like my `check_mbox_size` set to `yes`, as mutt, on startup, shows me the folders with eventually postponed unread mail. 

`check_mbox_size=no` works as expected, but I don't have this (well, for me) key advantage, as only newly arriving mails would be announced, not the old unread mail.

**Comment by nobrowser** [comment]
Thanks, that's very useful info.  Either @flatcap or myself will get this sorted out soonish.

**Comment by nobrowser** [comment]
Well @hvkls I don't have a solution yet, this is just part of the investigation, but: since the commit in question should only change anything if you have duplicate mailboxes in your muttrc, it seems you do have them.  Is that right?  Look closely.

**Comment by hvkls** [comment]
@nobrowser you were right. I've split my .muttrc into several files over time, and two of them contained the same `mailboxes` command. Once the duplicate code was removed, everything started working as expected. As it is a dynamic command, I hadn't noticed the duplicity in years!
