### ISSUE TITLE
The "change-folder" was okay with v20170609 broken with v20170714

### ISSUE THREAD

**Issue by dcrossleyau** [neomutt/neomutt#677]
I updated to v20170714 today, from v20170609. Using "mbox_type=Maildir". On macOS Sierra 10.12.5

This standard macro was okay, but now does not show a list of mailboxes:
```macro index c "<change-folder>?<toggle-mailboxes>" "open a different folder"```

Instead it just shows the directory listing of the folder in which mutt was started.

Other macros do operate properly. For example "save-message" does properly show the list of mailboxes from which to choose.
```macro index M "<save-message>?<toggle-mailboxes>" "move a message to a mailbox"```

The list of mailboxes is shown properly in the Sidebar, and navigation with Next/Previous is okay.

However "Open" does not open that mailbox.

**Comment by flatcap** [comment]
Ah!  Recently we fixed some odd behaviour of the browser.
This behaviour meant that you needed your macro to do this:
`macro index c "<change-folder>?<toggle-mailboxes>" "open a different folder"`

With the "fixed" behaviour, the macro looks like:
`macro index c "<change-folder>?" "open a different folder"`

We updated the /etc/Muttrc with the new macro.

**Comment by dcrossleyau** [comment]
Thanks, that fixed it.
