### ISSUE TITLE
Give line number to $editor with $edit_headers

### ISSUE THREAD

**Issue by qsuscs** [neomutt/neomutt#678]
The format string for `$editor` can only substitute the file name.  When `$edit_headers` is set, one usually wants to begin editing at the first body line.  It would be nice if this could be given, e.g. `set editor="emacsclient +%d %s"`.

**Comment by flatcap** [comment]
As a quick workaround (for vim, I don't know emacs), you can:
`set editor="vim '+/^$/+1' %s"

When starting, Find the first blank line and move to offset `+1`

**Comment by qsuscs** [comment]
Yes, exactly.  Unfortunately, emacsclient offers only “Evaluate the FILE arguments as ELisp expressions” (no, this is the mail file) and the `[+LINE[:COLUMN]]` optional argument.

**Comment by nobrowser** [comment]
This is quite the wrong approach with Emacs (take it from an expert, LOL).  Instead, you want to make sure the buffer is put into Message mode, you can do it with something like the following (adapted from my own `.emacs`):

```
(let ((mutt-file-regexp (format ".*/mutt-%s-%d-[-0-9]+\\'" hostname (user-real-uid))))
  (add-to-list 'auto-mode-alist `(,mutt-file-regexp . message-mode)))
```

I'm in the middle of moving my blog where I have written on this topic at length, I'll post in this thread when it is available again.

**Comment by flatcap** [comment]
It's an interesting idea, but nobody seems to have any time to code it.
If someone volunteers to work on it we can re-open the issue.
This issue will now be closed and listed on the [closed discussions page](https://www.neomutt.org/dev/discussions)

**Comment by qsuscs** [comment]
Just for the record, once Emacs automatically switches the buffer to message-mode (see comment above), the missing piece is `(add-hook 'mail-mode-hook 'mail-text)`, which makes it jump to the beginning of the body.
