### ISSUE TITLE
previous-unread-mailbox

### ISSUE THREAD

**Issue by mkoskar** [neomutt/neomutt#681]
There is `<next-unread-mailbox>` already and it just occurred to me why not be able to jump in other direction too?

**Comment by flatcap** [comment]
20 years and nobody thought of that :-)

There's one simple reason in the code.  Our mailboxes are in a singly-linked list (you can only search fowards).  It's still easily done though.

**Comment by somini** [comment]
If you use the sidebar, it's possible to use `<sidebar-prev-new><sidebar-open>`. But this doesn't work when the sidebar is hidden.

**Comment by flatcap** [comment]
Moving this to the long-term wish list.
