### ISSUE TITLE
Allow patterns for index_label (Index Color)

### ISSUE THREAD

**Issue by spcmd** [neomutt/neomutt#684]
This is a feature request, because currently we can't use patterns for` index_label`.

I wish we could use patterns, that way we could do something like this (example):

```
color index_label green default 'spotify'
color index_label red default 'youtube'
```

**Comment by guiniol** [comment]
If you use the notmuch tags, you can already use the `index_tag` for that.
e.g.:
```
color index_tag green default "spotify"
```
Shouldn't be too hard to adapt that for `index_label`, probably.

**Comment by sileht** [comment]
I can do this easily once the imap keywords patch is merged

**Comment by flatcap** [comment]
> I can do this easily once the imap keywords patch is merged

Done :-)

@sileht Are you still interested in this?

**Comment by flatcap** [comment]
Moving this to the long-term wish list.
