### ISSUE TITLE
Convert pgpewrap into a shell script

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#686]
* **feature requests**

 * Why do you not like the current state?
The `pgpewrap` executable is a C program that's compiled and linked as part of NeoMutt's build system. All it does is invoke an additional program with some arguments expansion, e.g.,
```sh
$ /pgpewrap echo -- -r apple banana cherry
-r apple -r banana -r cherry
```

 * What would you like to see to change?
Let's simplify our build system by turning this program into a simple shell script.

**Comment by nobrowser** [comment]
What is this used for?  Does mutt itself call this?  If not maybe it should just be dropped, or moved to a `contrib` subdirectory?

**Comment by d-k-c** [comment]
It's used to be shipped by Mutt and some users might use it in their muttrc, so we must cautious and keep it to avoid breaking their setups

**Comment by flatcap** [comment]
It's in the default config for users who aren't using gpgme.
And them **only** when signing/encrypting to multiple recipients.

```
set pgp_encrypt_sign_command = "pgpewrap gpg2 %?p?--passphrase-fd 0? --batch --quiet --textmode --output - --encrypt --sign %?a?-u %a? --armor --always-trust -- -r %r -- %f"
```

NeoMutt provides an expando for the recipients `%r` which is space separated.
gpg requires `-r recip1 -r recip2` etc

pgpewrap simply does a little parameter shuffling.

**Comment by nobrowser** [comment]
Actually it turns out this is really hard to do _correctly_ in a (plain POSIX) shell script.  By a nice coincidence, this super-long Usenet article was posted just today:

[Learning Bash Shell Scripting](https://groups.google.com/d/msg/comp.unix.shell/dDxiug8RWac/Y1zzwafEBQAJ)

See if you can read to the end of it!  It does get easier in bash or ksh because they have built-in hashes, or in the Plan 9 rc shell because it has built-in Perl-like lists.  But I don't think we can assume any of these are installed on our target, and even if they are we don't know where (`/bin`, `/usr/bin`, `/usr/local/bin`, `/opt` or what).

So how about a Perl script?  Perl is installed pretty much on any target and the path doesn't matter because we can use the `perl -x` trick.

Or we could close this as "won't fix". ;-)

**Comment by gahr** [comment]
Uhm.. this one passes sh -n but I'm not a shell expert so I might be missing something.. also, this is quite naive and ugly, but kind of working:

```sh
#!/bin/sh

# what to put between arguments after first double-dash
repeat=""

# states:
# 0 - before first double dash
# 1 - just encountered double dash
# 2 - after first double dash
# 3 - after second double dash
status=0

# piece-wise constructed command line
cmd=""
for arg in $@
do
    if test "$arg" = "--"
    then
        if test $status -eq 0
        then
            status=1
        elif test $status -eq 1
        then
            status=2
        elif test $status -eq 2
        then
            repeat=""
            status=3
        fi
    else
        if test $status -eq 0 -o $status -eq 3
        then
            cmd="$cmd $arg"
        elif test $status -eq 1
        then
            repeat=$arg
            status=2
        else
            cmd="$cmd $repeat $arg"
        fi
    fi
done

$cmd
```

**Comment by nobrowser** [comment]
Have you tested what happens when your arguments contain spaces, or quotes?

**Comment by gahr** [comment]
Yes, I was missing double quotes around `$@`.

Now the original C and the new SH one give the same results for:

`./pgpewrap echo "one two" -- -t "three four" "five six"`
`./pgpewrap echo "one two" -- -t "three four" 'five "quotes six'`

If there's anything else you're seeing I have missed, please do point me to it :)

**Comment by flatcap** [comment]
Despite `pgpewrap`s own advice the usage string is:

`pgpewrap COMMAND [ PREFIX-OPTIONS ] [ -- FLAG RECIPIENT-LIST [ -- SUFFIX-OPTIONS ] ]`

Run a command with some options, a repeat group and some options on the end.
With 2 prefix options, 3 recipients and 2 suffix options, it runs:

`COMMAND PREFIX1 PREFIX2 -FLAG RECIP1 -FLAG RECIP2 SUFFIX1 SUFFIX2`

After a bit of testing, I've found some slight differences between `pgpewrap` and `gahr.sh`
(I think `gahr.sh` has the correct behaviour in each case)

`pgpewrap COMMAND ARG1 --` fails with an error
`gahr.sh COMMAND ARG1 --` runs `COMMAND ARG1`

`pgpewrap COMMAND ARG1 -- FLAG` runs `COMMAND ARG1 FLAG`
`gahr.sh COMMAND ARG1 -- FLAG` runs `COMMAND ARG1`

`pgpewrap COMMAND ARG1 -- FLAG RECIP1 --` fails with an error
`gahr.sh COMMAND ARG1 -- FLAG RECIP1 --` runs `COMMAND ARG1 FLAG RECIP1`

**Comment by nobrowser** [comment]
```
 matica!19 ~$ ./numargs 1 2 3
3
 matica!20 ~$ ./numargs 1 '2 3'
2
 matica!21 ~$ sh gahr.sh ./numargs 1 2 3
3
 matica!22 ~$ sh gahr.sh ./numargs 1 '2 3'
3
 matica!23 ~$ cat numargs 
#! /bin/sh

printf '%d\n' $#
```

And this is enough to bust it, I don't even actually have to test the features.

If the original C version behaves the same ... it is broken too.  The difference is that you _can_ do it right in C (and in Perl).

**Comment by d-k-c** [comment]
The point is to have a replacement with the same behaviour as the C version, not to "fix" something just for the sake of it and potentially break user configs (in some corner cases) in the meantime. So no, your test is not enough to bust it, please show evidence that `gahr.sh` and `pgpewrap` don't behave the same way to state that.

**Comment by nobrowser** [comment]
I'm sorry - if you're worried about not changing anything, then it should just not be replaced.

Un-assigning myself.

**Comment by gahr** [comment]
@nobrowser, I see where you're coming from, but please don't lose sight of the use case. Pgpewrap is not *currently* working as a general pass-through. It's used - perhaps, is there really anyone not using gpgme nowadays? - for the construction of a very particular kind of command line invokation.

So my question stand: if you see any reason why the current C thing cannot be replaced by a script - mine, or an improved or even totally different implementation - please let me know.

**Comment by nobrowser** [comment]
I have just done what I *should* have done before posting the above, namely looking at `pgpewrap.c`.  As I wasn't really surprised to find, it uses and array of strings for the args, and `execv(2)` to call the original program.  Thus, it will behave correctly in the above test, unlike `gahr.sh`.

Now, I get your point that this test is contrived.  But IMO it is not a very long way at all from this case to one that matters in practice.  What happens if the argument is a filename, and happens to have a space in it?

As I said, it is easy with a Perl script, or anything that has data structures other than strings.

**Comment by flatcap** [comment]
The shellscript was a nice idea, but perl/python would be much more reliable.
However, `pgpewrap` isn't a general purpose program, it's extremely specific.

Working around the "command has a space" problem is simple enough.
Keep `$cmd` / `$1` separate from the args.  As for the other arguments...

- None of the `gpg` flags contain spaces, `--batch --quiet --output` ...
- The recipients are listed in long id format, `0x69AD1D636AC292E820658C16EBC150E4B5DA63DF`
  (I haven't checked the code deeply, but it seems Mutt will always use the fingerprint or long id)
- The only argument that _can contain spaces_ is the cache dir containing the email.

And guess what?

Mutt doesn't escape the filename that it passed to gpg.
If it contains spaces, the command fails and the email cannot be sent!

Here's an actual command line passed to `pgpewrap`

`pgpewrap gpg2 --batch --quiet --output - --encrypt --textmode --armor --always-trust -- -r 0x69AD1D636AC292E820658C16EBC150E4B5DA63DF 0x86C2397270DD7A561263CA4E5FAF0A6EE7371805 -- /home/mutt/.cache/mutt/mutt-laptop-1001-18186-2108137942718249097`

**Comment by nobrowser** [comment]
Why should it escape args for `gpg`?  `gpg` will see a single arg, doesn't matter if it contains spaces or not.  It's only when the shell gets its dirty hands into the game that spaces matter.

If `pgpewrap` is truly a special purpose tool, it's shouldn't be in `/usr/bin` IMO.  Now I of course understand that moving it would break existing configs, so probably can't be done.  But, I see it has a manpage.  How about we add a Big Fat Warning (TM) to the manpage, to the effect of "**NEVER** use this for anything else than wrapping `pgp` or `gpg` calls from `mutt`!"  (Plus optional explanation why.)  If we do this I can Ack on the script (but I still take no responsibility for it, grin).

**Comment by libBletchley** [comment]
I don't like PERL, but one factor in favor of PERL is that mutt already depends on PERL for the `smime_keys` script.  (Although I do think it'd be a good idea to ditch the script and expand the mutt executable https://github.com/neomutt/neomutt/issues/738).

Anyway, so long as we're using `/bin/sh`, I do see a new defect: if $cmd contains a space, then the first word of $cmd will try to execute, not $cmd.  It needs quotes.

This line is not POSIX:
`
if test "$arg" = "--"
`
It should be:
`
if test "$arg" == "--"
`
These lines use command substitution needlessly, causing a needless subshell:
```
status=`expr $status + 1`
```
Probably better to use: `status=$((status+1))`

OTOH, that whole script could be simplified as:
`
#!/bin/sh

printf '%s ' "$@" | {
    read cmd cmdterm option args

    "$cmd" "$(for arg in $args; do printf '%s ' "$option $arg"; done)"
}
`

**Comment by gahr** [comment]
> if $cmd contains a space, then the first word of $cmd will try to execute, not $cmd

yes.. and if you're using spaces in your exeutable files names you're calling for problems this small script isn't supposed to deal with.

> Also this line is not POSIX:
> if test "$arg" = "--"
> It should be:
> if test "$arg" == "--"

According to [POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html), s1 = s2 is POSIX.

> These lines use command substitution needlessly, causing a needless subshell:

Yep, thanks!

> The innermost if could be made into a case statement

Yes it could, but should it? Probably just a matter of style...
