### ISSUE TITLE
Question: <save-message> equivalent for threads?

### ISSUE THREAD

**Issue by ahmedelgabri** [neomutt/neomutt#687]
I'm trying to find a way to archive a whole thread, but can't seem to find a straight forward way to do this, for example there is `<save-message>` but I don't think there is a `<save-thread>`? Maybe I'm missing something here.

**Comment by riesebie** [comment]
* Ahmed El Gabri <notifications@github.com> [2017-07-25 10:06 -0700]:

> I'm trying to find a way to archive a whole thread, but can't seem
> to find a straight forward way to do this, for example there is
> `<save-message>` but I don't think there is a `<save-thread>`?
> Maybe I'm missing something here.

You can use <tag-thread> which is bound to ESC-t by default and then
do what ever you want with that thread.

-- 
  Numeric stability is probably not all that 
  important when you're guessing;-)

**Comment by nerdyshelties** [comment]
You use Esc-t, then use ;s to move the thread. You have to use ";" 
after tagging but before the command you with to apply to the tagged 
messages, to tell Mutt the next command applies to tagged messages.
If that doesn't work for you, look in help to see what keys the commands 
"tag thread" and "next command applies to tagged messages" are bound to.

**Comment by ahmedelgabri** [comment]
So a macro like this should work?

```
macro index,pager Y "<tag-thread><save-message>=Personal/Personal.Archive<enter>" "Archive thread"
```

**Comment by flatcap** [comment]
Nearly.  You need to add `<tag-prefix>` -- meaning "apply the next command to all tagged emails"
```
macro index,pager Y "<tag-thread><tag-prefix><save-message>=Personal/Personal.Archive<enter>" "Archive thread"
```

But there's a problem.  It doesn't work if the thread is collapsed -- I must be missing something.
I've checked old versions of NeoMutt and Mutt but they all work the same: `<tag-prefix><ACTION>` only works on the root emails.

**Comment by ahmedelgabri** [comment]
> Nearly. You need to add `<tag-prefix>` -- meaning "apply the next command to all tagged emails"

Thanks!

> But there's a problem. It doesn't work if the thread is collapsed -- I must be missing something.
I've checked old versions of NeoMutt and Mutt but they all work the same: `<tag-prefix><ACTION>` only works on the root emails.

There is no way around this?

**Comment by flatcap** [comment]
> There is no way around this?

Not a the moment.

I'm just getting some second opinions, but it seems like this is a bug.  And bugs get fixed :-)

**Comment by ahmedelgabri** [comment]
Cool, thanks @flatcap :)

**Comment by pprw** [comment]
`set auto_tag = yes`

always apply actions for all tagged emails (no need to use tag-prefix)
