### ISSUE TITLE
colors are broken in 20170714

### ISSUE THREAD

**Issue by nicolasbock** [neomutt/neomutt#689]
I upgraded from `20170609` to `20170714`. Since the upgrade the colors are not always updated correctly. For instance, when I move the indicator in the index from a read message to an unread message and back, the color of the highlighted message becomes light gray on black instead of white on red. Moving the indicator one more time fixes the coloring. Here are my color settings:
~~~
color hdrdefault brightblue default
color quoted brightblue default
color signature brightblue default
color attachment brightred default
color prompt brightmagenta default
color message brightred default
color error brightred default
color indicator white red 
color status brightgreen blue
color tree white default
color normal white default
color markers red default
color search white default
color tilde brightmagenta default
color index brightblue default ~F
color index brightgreen default "~F (~N | ~O)"
color index yellow default "(~N | ~O)"
color sidebar_new yellow default
~~~

**Comment by flatcap** [comment]
I've just tried your colours and they work for me -- I didn't really think they'd be the problem.
However, I'm not sure what might be.  I'll have a think.

Has your config changed at all?
How repeatable is it?  [Always|Often|Rarely]
Are you certain it always worked correctly in 20170609?
What sort of folder is it?  IMAP, Maildir, NotMuch?

If you have a little time to `git bisect` it would be very much appreciated.

**Comment by nicolasbock** [comment]
Hi @flatcap 

I bisected and am told that 2d51490b3609c9f7c84951f66d2134bdadbfda95 is the first bad commit. It does have to do with colors, so I am encouraged that it might be the one :smile:. But I haven't looked at it in detail.

Hope this helps!

**Comment by flatcap** [comment]
thanks @nicolasbock!
@fbellet any thoughts what might be going wrong?

**Comment by Kdecherf** [comment]
Hello there,

I have this issue too with two different behaviors.

Here is a normal view with my configuration (`color indicator color233 color19`):
![2017-08-01-002936_1920x1080](https://user-images.githubusercontent.com/226063/28801254-f122776a-7650-11e7-8b5b-4f96222f3cd9.png)

First issue:

* Go down twice (_ID 27 here_)
* Message with ID 26 has been partially redrawn with a color which is not defined in my configuration (_it seems to be `color15`_)
_note: we don't see it on this screenshot, but the subject keeps the correct color_

![2017-08-01-002928_1920x1080](https://user-images.githubusercontent.com/226063/28801385-90397a74-7651-11e7-9ea6-cb44502db782.png)

Second issue:

* Go up
* The indicator now uses `color15` as fg and no bg.

![2017-08-01-002932_1920x1080](https://user-images.githubusercontent.com/226063/28801417-b757045a-7651-11e7-910d-9abe571ab069.png)

These glitches are only triggered when passing through read messages with tree indicator.

A full window redraw (_e.g. triggered by a resize_) fixes these glitches.

The two issues disappear when I remove `color tree` from my configuration file. Also the second issue disappear when I only remove `color indicator` and keep `color tree`.

Current setting:

```
# ...
color tree color193 default
color indicator color233 color193
# ...
```

**Comment by flatcap** [comment]
@Kdecherf Thanks for the examples, they're very clear.

I'll try again to repeat it.  At worst case I'll revert the colour fix, for the next release.
- 2d51490 - menu: fix the thread tree color

**Comment by fbellet** [comment]
Hi,

I could not reproduce the bug myself. Would it be possible to have a minimal muttrc file that triggers this bug (when starting neomutt with the command : mutt -n -F muttrcfile -f mbox). I would be interested to know if the normal color and the index colors are defined too. The kind of terminal (xterm, gnome-terminal, rxvt,...) would be interesting, their default foreground and background colors, as well as the version of the OS/ncurses.

The idea of this patch is to create a new color on-demand for the tree element, that combines the fixed foreground color of the tree element with the dynamic background color of the index line (depending on the status of the message), where the tree element is drawn. This new color15 that appears may be defined elsewhere in your muttrc file ? 

Do you see a different behavior if the terminal is wide enough to not truncate the subject of the message 25 ?

**Comment by nicolasbock** [comment]
Hi @fbellet 

I can confirm that by removing the `color tree` entry in my mutt configuration the issue disappears. However, removing only `color indicator` does not fix it.

I am using gnome-terminal-3.22.2 with the `solarized-dark` built-in color scheme and ncurses-6.0 on Gentoo Linux.

Hope this helps!

**Comment by Kdecherf** [comment]
Hi @fbellet 
You can find my current colorscheme here: https://github.com/Kdecherf/user-config/blob/master/.mutt/ivy-league.theme Colorscheme of my terminal is available here: https://github.com/Kdecherf/user-config/blob/master/.Xdefaults
I'll try to provide a minimal muttrc to reproduce the issue.
I'm using urxvt 9.22 with ncurses 6.0 on Exherbo. TERM is set to `rxvt-unicode-256color`.

`color15` does not exist at all in my configuration.

**Comment by fbellet** [comment]
@Kdecherf, @nicolasbock, I tried to follow your setup as close as possible, but I still cannot reproduce locally the bug you observe.

Could you try to replace
```
ATTRSET(mutt_combine_color(ColorDefs[MT_COLOR_TREE], attr));
```
by 
```
{
 mutt_combine_color(ColorDefs[MT_COLOR_TREE], attr);
 ATTRSET(ColorDefs[MT_COLOR_TREE]);
}
```
in menu.c around line 109, to check if the problem comes from the allocation of the new color, or from its use.

**Comment by nicolasbock** [comment]
No, unfortunately this didn't help @fbellet. Is there some debugging code I can insert to help?

**Comment by fbellet** [comment]
OK, then could you try to replace `#ifdef HAVE_USE_DEFAULT_COLORS` by `#if 0` in function mutt_combine_color() ? Maybe the late and repeated call to the curses function use_default_colors() is problematic.

**Comment by nicolasbock** [comment]
Hi @fbellet, yes, that did it! Removing this part of the code fixes the coloring issues I am seeing.

**Comment by fbellet** [comment]
That's good news. I'll try to fix this problem in the proper way, by putting the call to use_default_colors() earlier in mutt setup. This curses initialization function is normally called when reading the muttrc file, when some colors definitions contain the keyword `default`. But with this patch to the tree element colors, it may happen that a _combined_ color will require the default background color of the indicator, that's not been defined explicitly in the muttrc file, hence without prior call to use_default_colors().

**Comment by flatcap** [comment]
Nice detective work guys!
@fbellet It's a bit late now, but if you need to test things, you're welcome to create a "devel/*" branch with anything you like in it.

**Comment by Kdecherf** [comment]
#702 fixes this issue :+1:

**Comment by gahr** [comment]
Reported as fixed.
