### ISSUE TITLE
Option for robust macros with shell-escapes

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#69]
This is a feature request for an option that, if set, would cause a macro to end after any <shell-escape> that exits with error (perhaps other commands as well, such as <pipe-message>).

motivation: I have several macros with shell-escapes, and although I can report the error to the mutt user and e.g. set the muttrc wait_key option so that I know the user sees that the script exited with error, in some cases it makes for some frustration that mutt continues executing the macro after there was an error. For example, suppose I have a macro such as:

`macro compose [u "<shell-escape>foo<enter><send-message>"`

If 'foo' exits with error, I don't want for mutt to send the message. There are some hackish ways around this particular case (e.g. set a sendmail command that checks for a temporary file that 'foo' wrote containing the exit code), but I hope this case illustrates my point well enough.

Framed in another way, I would like for a way that <shell-escape>abc<def> is really interpreted as a shell would interpret `<shell-escape>abc && def`. Currently it is interpreted as `<shell-escape>abc ; def`.

I don't know much about how this would be implemented, but I'll give some uneducated ideas:
I'm guessing that a goal of macros is to be as true as possible to if the user had just typed in all the keys themself. In this case, it would seem to contradict my desired feature (because if a user keeps typing after an error, that is still of course input that should be interpreted). If this principle cannot be violated (with an option that defaults to the current behavior), then what about the following?

A muttrc variable "wait_on_error" of type "number" that designates the number of seconds that mutt would gobble any keystrokes after an error? For example, if set to "1", any keystroke after a <shell-escape> exits non-zero, would be gobbled up (= "not interpreted") for the duration of one second. This way, the behavior of macros would be the same as if the user types the macro (1000 wpm) directly themselves.

Note to @flatcap, I don't expect you to spend the time to implement this. I'm just curious if you're open to the idea. I'm guessing there might be reasons why such an option would be a bad idea. I hope not though. If you are open to the idea, then perhaps someone else interested in robust macros would want to work on implementing it.

**Comment by flatcap** [comment]
A good idea, well argued :-)

If you're only going for the simple case `X && Y {&& Z ...}` then it should be quite easy to implement.

**Comment by scottkosty** [comment]
@flatcap thanks for the feedback! I'm glad you are open to the idea. Hopefully someone else takes an interest in implementing it.

**Comment by flatcap** [comment]
Sorry, this enhancement didn't attract someone to write some code.
This issue will now be closed, but listed on the [Closed Discussions](https://www.neomutt.org/dev/discussions) page.

**Comment by guyzmo** [comment]
TBH to overcome this issue, we have lua scripting. By definition macros are dumb, and thus not able to handle error cases. Scripts are meant to be smarter and able to handle cases.

**Comment by scottkosty** [comment]
@guyzmo thanks for the idea. Is there a simple example of a lua script that just calls vanilla mutt functions but stops if an error? I would be interested in studying that.

**Comment by flatcap** [comment]
This issue has probably been forgotten about, but there's news!
**The key/macro queues are now cleared on error.**

When this issue was opened, this fix wasn't possible.
(all the function handlers were scattered).

---

Whilst making lots of key-handling changes, I merged 71785b144.

Each Dialog uses multiple Function Dispatchers to delegate the work of `<functions>`.
If a callback function fails, the dispatcher clears the queues of keys/macros.

**Scene**: Index, last entry selected
**Macro**: `<next-entry><next-entry><delete-entry>`

**Result**: First `<next-entry>` fails, so the `<next-entry>` and `<delete-entry>` never happen.

**Comment by scottkosty** [comment]
Thanks for the pleasant surprise!
