### ISSUE TITLE
Drop --without-wc-funcs

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#690]
**feature requests**

   * Why do you not like the current state?

Mutt works around the lack of of a `<wchar.t>` implementation by providing its own version of `wcwidth`. This can be forced through the configure flag `--without-wc-funcs` and is achieved with the help from `wcwidth.c`, which implements the missing function for version 5 (!) of UTF-8.

   * What would you like to see to change?

Can we assume that any system we want to be able to run on provides those functions? If so, we could drop the configure flag, `utf8.c`, and `wcwidth.c`.

I'll be happy to kill the dead code if we agree.

**Comment by d-k-c** [comment]
I think it's fair to assume we want to run on systems that provides these functions and headers. Unicode 9 has been released last June, so I guess it's time for an upgrade!

**Comment by gahr** [comment]
`s/9/10/` :-)

**Comment by d-k-c** [comment]
Too bad I can't read a date properly ^^
