### ISSUE TITLE
dyld: Library not loaded - Notmuch

### ISSUE THREAD

**Issue by tdehaeze** [neomutt/neomutt#693]
Hi everyone,

I just updated everything using Brew, and now I can't launch neomutt.

```
> mutt
dyld: Library not loaded: /usr/local/opt/notmuch/lib/libnotmuch.4.dylib
  Referenced from: /usr/local/bin/mutt
  Reason: image not found
[1]    94571 abort      mutt
```

When I look into the folder `/usr/local/opt/notmuch/lib/` I got `libnotmuch.5.0.0.dylib libnotmuch.5.dylib     libnotmuch.dylib`.

I don't really know what to do appart from adding `libnotmuch.4.dylib` to the folder, but that seems a bad option. (I tried `ln -s libnotmuch.5.0.0.dylib libnotmuch.4.dylib` and neomutt is now running correctly, but I don't know the consequences...)

Thanks :)

**Comment by riesebie** [comment]
It seems that libnotmuch was updated after compiling neomutt. In that case you have to rebuild neomutt against libnotmuch5.

**Comment by tdehaeze** [comment]
That was that. Thanks
