### ISSUE TITLE
Tagged actions on collapsed threads don't work

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#697]
**Note:** This bug exists in upstream Mutt, too.

**Working example:**
- View mail in the index
- Emails are threaded: `set sort=threads`
- All threads are open (not collapsed)
- Tag one thread: `<tag-thread>`
- Perform an action, e.g. `<tag-prefix><flag-message>`

**Result:**
- All the emails in the thread are now flagged

**Broken example:**
- View mail in the index
- Emails are threaded: `set sort=threads`
- All threads are closed (collapsed)
- Tag one thread: `<tag-thread>`
  This correctly tags all the emails in the thread
- Perform an action, e.g. `<tag-prefix><flag-message>`

**Result:**
- Only the root email is flagged

Related to #687 
/cc @ahmedelgabri

**Comment by gahr** [comment]
On the other hand, `<tag-prefix><save-message>` works just fine and correctly moves all the messages in the thread.

**Comment by ahmedelgabri** [comment]
> On the other hand, `<tag-prefix><save-message>` works just fine and correctly moves all the messages in the thread.

Only if the thread is open (not collapsed)

**Comment by gahr** [comment]
Not here ;)

**Comment by ahmedelgabri** [comment]
@gahr I wonder how are you doing it then :) because that was the main issue here #687 

That's what I have & it only works if the thread is open (not collapsed)

```
macro index,pager Y "<tag-thread><tag-prefix><save-message>=Personal/Personal.Archive<enter>" "Archive thread"
```

**Comment by gahr** [comment]
As I said, `<tag-thread><tag-prefix><save-message>` works for me. `<tag-thread><tag-prefix><flag-message>` does not.

**Comment by ahmedelgabri** [comment]
For me `<tag-thread><tag-prefix><save-message>` works only when the thread is open (not collapsed) & that's what is this issue is all about if I understand correctly.

**Comment by gahr** [comment]
Yes, cool, I'm just pointing out that I'm having a different behavior, so it's not *consistently* failing to work for collapsed threads. Just adding a piece of info, not saying that the issue is invalid or something..

**Comment by ahmedelgabri** [comment]
I just thought you had a solution or something, sorry for the misunderstanding :)
