### ISSUE TITLE
Kill ascii.h functions

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#699]
* **feature requests**

* Why do you not like the current state?

The `ascii_strcasecmp` and `ascii_strncasecmp` functions declared in `lib/ascii.h` are problematic for a couple of reason:

  1. they do not state what they do, should any characters not be confined within the ASCII character set
  2. they use the standard C function `tolower` (to case-convert the strings to lowercase before comparison), which does take the current `LC_CTYPE` locale into consideration

As such, I'd say that the `ascii` prefix is incorrect at best, and useless anyway.

* What would you like to see to change?

I propose to remove the two aforementioned functions and replace any calls to the correspective Std 1003.1, 2001 POSIX.1's `strcasecmp` and `strncasecmp`.

The third function of `ascii.h`, `ascii_strlower` is used only within `ncrypt/crypt_gpgme.c`. I suggest to convert it to a macro or static inline function and move it there.

**Comment by gahr** [comment]
Edit: I suggest to replace `ascii_strcasecmp` and `ascii_strncasecmp` by their `mutt_strcasecmp` and `mutt_strncasecmp`, which in turn call the POSIX one after wrapping their argument through `NONULL`.

**Comment by flatcap** [comment]
Yes, using the NONULL wrappers sounds good.  Go for it.
