### ISSUE TITLE
vfolder-from-query seems broken

### ISSUE THREAD

**Issue by 257** [neomutt/neomutt#7]
i get 0 results for any Query invoked in command mode. notmuch works though since i get my vfolders as before (before == with mutt-kz).

**Comment by flatcap** [comment]
@257 Hmm... I'm sorry, I don't see a problem.
Plus, I don't think I've changed any code that might have affected the Query function.

I've just tested mutt-1.5.24, mutt-tip (latest dev) and neomutt-20160320.
I created a small address file 'animals.txt', then

    set query_command="grep '%s' ~/animals.txt"

Pressing '**m**' (start mail), then '**hor\<Tab\>**' lists some animals containing '**hor**'.
As expected.

Back in the index, pressing '**Q**' (start query), '**hor\<Enter\>**' lists some animals containing '**hor**'.
As expected.

What else can you tell me about your problem?

**Comment by 257** [comment]
hmm, Query: interface is used for both 'query external program for addr'
and vfolder-from-query. vfolder-from-query is what i  was referring to.
'Q' (query external...) works fine here.

**Comment by karelzak** [comment]
I can confirm it does not work, need more investigation.

**Comment by karelzak** [comment]
```
 static int main_change_folder(MUTTMENU *menu, int op, char *buf, size_t bufsz,
                          int *oldcount, int *index_hint)
 {
   mutt_expand_path (buf, bufsz);
-  set_curbuffy(buf);
+#ifdef USE_SIDEBAR
+  if (sb_set_open_buffy (buf) == NULL)
+    return -1;
+#endif
```

The code assumes that sidebar has clue about all folders, but this is not true because for notmuch folders may be generated on-the-fly. In this case sidebar should be out of game...

**Comment by 257** [comment]
@karelzak what do you think of changing the prompt to qaddr (or whatever) so user can see it's querying for addr or perfoming vfolder-from-query?

**Comment by karelzak** [comment]
All you need is:
```
diff --git a/curs_main.c b/curs_main.c
index 6fcdcd6..c2ff15c 100644
--- a/curs_main.c
+++ b/curs_main.c
@@ -598,8 +598,7 @@ static int main_change_folder(MUTTMENU *menu, int op, char *buf, size_t bufsz,
 {
   mutt_expand_path (buf, bufsz);
 #ifdef USE_SIDEBAR
-  if (sb_set_open_buffy (buf) == NULL)
-    return -1;
+  sb_set_open_buffy (buf);
 #endif
   if (mx_get_magic (buf) <= 0)
   {

```

**Comment by karelzak** [comment]
@flatcap see https://github.com/karelzak/mutt-kz/commit/8c824f5aa19fcdab6b0de26f7e07c8775dfb385c

.. not sure how to force github to accept pull requests from another repository if the repository is not directly based on fork. I use "git remote" for neo stuff and it works as expected, unfortunately github is not smart enough for this work flow :-(

**Comment by flatcap** [comment]
@karelzak Thanks.
I've pushed the change up to NeoMutt.

@257 Please can you try the new version:
[git](https://github.com/neomutt/neomutt) or [source zip](https://github.com/neomutt/neomutt/archive/neomutt.zip)

Thanks, Rich.

**Comment by 257** [comment]
works here, thanks.
