### ISSUE TITLE
sidebar_format padding/alignment goes beyond the divider

### ISSUE THREAD

**Issue by lasombra** [neomutt/neomutt#70]
It seems that with the new set of patches from today, commit `b706e5986237ab93edb1bbfa27a7bf91c1186976`, the` sidebar_format` padding/alignment got weird.

When setting padding or right align it goes beyond the divider. To check that, set `sidebar_format` to `%B %?N?(%N)?%**%S`.

It will look something like this:
```
INBOX *************************** |
```

**Comment by flatcap** [comment]
Thanks for the quick feedback.  I'm on it.

**Comment by flatcap** [comment]
Sorry about that.  Fixed.

**Comment by lasombra** [comment]
No worries. Just tested. Working again :)

Thanks for the quick fix.

**Comment by lasombra** [comment]
It seems that the default `sidebar_format` is not being applied. I just commented it out and I'm now back to not seeing it. If I add `set sidebar_format = '%B%?F? [%F]?%* %?N?%N/?%S'` then it works fine.

**Comment by flatcap** [comment]
Ah, yes.  Upstream have changed the default `sidebar_format` to be less labour intensive.
For this release I'm going to announce the change, but put in a workaround.

**Comment by riesebie** [comment]
> Sorry about that. Fixed.

With commit a41814b I get:
```
debian-newmaint       0| 
debian-powerpc        0| 
debian-user           0|
```
Release 20160611:
```
debian-newmaint       1/259| 
debian-powerpc       3/1498| 
debian-user          2/2161|
```
```
$ mutt -D | grep sidebar
sidebar_divider_char="|"
sidebar_delim_chars="/."
sidebar_folder_indent is unset
sidebar_format="%B%?F? [%F]?%* %?N?%N/?%S"
sidebar_indent_string="  "
sidebar_new_mail_only is unset
sidebar_next_new_wrap is unset
sidebar_short_path is unset
sidebar_sort_method=mailbox-order
sidebar_visible is set
sidebar_width=28
```

I can't investigate yet. Have time only at Sat/Sun....

**Comment by riesebie** [comment]
> sidebar_format="%B%?F? [%F]?%* %?N?%N/?%S"

running as follows within mutt:
```
: set ?sidebar_format
```
gives
```
sidebar_format="%B%<F? [%F]>%* %<N?%N/>%S"
```

So there is something wrong with reading the regex from muttrc. Some question marks are replaced by  `<` or `>`. Escaping the `?` by `\?` doesn't help.

**Comment by flatcap** [comment]
@riesebie 
Sorry, there are some other Upstream changes and new variables to control the sidebar.
The extra stats that we take for granted aren't enabled by default.
Try:
```
set mail_check_stats = yes
set mail_check_stats_interval = 60
```

**Comment by riesebie** [comment]
> ```set mail_check_stats = yes```

was unset. Setting it works ;-)
