### ISSUE TITLE
Please accept :se as a synonym for :set

### ISSUE THREAD

**Issue by joshtriplett** [neomutt/neomutt#701]
This is a minor item, but a very regularly encountered pain point for me.

Vim accepts commands starting with a colon, just like mutt does. However, vim allows abbreviating commands using any unambiguous prefix. In particular, you can write `:se` instead of `:set`. I regularly find myself typing this in mutt and expecting it to work (e.g. `:se mime_forward=yes`), only to get an error, and have to go back and change it to `:set`.

I don't know if mutt should *in general* move to accepting unambiguous prefixes, but please consider accepting `:se` in particular as a synonym for `:set`.

**Comment by flatcap** [comment]
I feel your pain :-)
Most of the developers are vim users, but we haven't done much to help ourselves.

To get things started, here are a list of all the NeoMutt commands and their shortest prefixes.
At this point, <kbd>\<tab\></kbd>-completion would do the job, but just accepting the short version would be better.

Some commands, like set, need priority, `:s` or `:se`.

Which other commands do users most often type in?


| Command             | Shortest Prefix           |
| :------------------ | :------------------------ |
| account-hook        | **ac**[count-hook]        |
| alias               | **ali**[as]               |
| alternates          | **alternate**[s]          |
| alternative_order   | **alternati**[ve_order]   |
| append-hook         | **ap**[pend-hook]         |
| attachments         | **at**[tachments]         |
| auto_view           | **au**[to_view]           |
| bind                | **b**[ind]                |
| charset-hook        | **ch**[arset-hook]        |
| close-hook          | **cl**[ose-hook]          |
| color               | **co**[lor]               |
| crypt-hook          | **cr**[ypt-hook]          |
| exec                | **e**[xec]                |
| fcc-hook            | **fcc-h**[ook]            |
| fcc-save-hook       | **fcc-s**[ave-hook]       |
| finish              | **fi**[nish]              |
| folder-hook         | **fo**[lder-hook]         |
| group               | **g**[roup]               |
| hdr_order           | **hd**[r_order]           |
| iconv-hook          | **ic**[onv-hook]          |
| ifdef               | **ifd**[ef]               |
| ifndef              | **ifn**[def]              |
| ignore              | **ig**[nore]              |
| lists               | **li**[sts]               |
| lua                 | **lua**[]                 |
| lua-source          | **lua-**[source]          |
| macro               | **mac**[ro]               |
| mailboxes           | **mailb**[oxes]           |
| mailto_allow        | **mailt**[o_allow]        |
| mbox-hook           | **mb**[ox-hook]           |
| message-hook        | **me**[ssage-hook]        |
| mime_lookup         | **mi**[me_lookup]         |
| mono                | **mo**[no]                |
| my_hdr              | **my**[_hdr]              |
| nospam              | **n**[ospam]              |
| open-hook           | **o**[pen-hook]           |
| pgp-hook            | **pg**[p-hook]            |
| push                | **pu**[sh]                |
| reply-hook          | **rep**[ly-hook]          |
| reset               | **res**[et]               |
| save-hook           | **sa**[ve-hook]           |
| score               | **sc**[ore]               |
| send-hook           | **send-**[hook]           |
| send2-hook          | **send2**[-hook]          |
| set                 | **set**[]                 |
| setenv              | **sete**[nv]              |
| shutdown-hook       | **sh**[utdown-hook]       |
| sidebar_whitelist   | **si**[debar_whitelist]   |
| source              | **so**[urce]              |
| spam                | **sp**[am]                |
| startup-hook        | **st**[artup-hook]        |
| subjectrx           | **subj**[ectrx]           |
| subscribe           | **subs**[cribe]           |
| tag-formats         | **tag-f**[ormats]         |
| tag-transforms      | **tag-t**[ransforms]      |
| timeout-hook        | **ti**[meout-hook]        |
| toggle              | **to**[ggle]              |
| unalias             | **unali**[as]             |
| unalternates        | **unalternate**[s]        |
| unalternative_order | **unalternati**[ve_order] |
| unattachments       | **unat**[tachments]       |
| unauto_view         | **unau**[to_view]         |
| uncolor             | **unc**[olor]             |
| ungroup             | **ung**[roup]             |
| unhdr_order         | **unhd**[r_order]         |
| unhook              | **unho**[ok]              |
| unignore            | **uni**[gnore]            |
| unlists             | **unl**[ists]             |
| unmailboxes         | **unmailb**[oxes]         |
| unmailto_allow      | **unmailt**[o_allow]      |
| unmime_lookup       | **unmi**[me_lookup]       |
| unmono              | **unmo**[no]              |
| unmy_hdr            | **unmy**[_hdr]            |
| unscore             | **unsc**[ore]             |
| unset               | **unset**[]               |
| unsetenv            | **unsete**[nv]            |
| unsidebar_whitelist | **unsi**[debar_whitelist] |
| unsubjectrx         | **unsubj**[ectrx]         |
| unsubscribe         | **unsubs**[cribe]         |
| unvirtual-mailboxes | **unv**[irtual-mailboxes] |
| virtual-mailboxes   | **v**[irtual-mailboxes]   |

**Comment by gahr** [comment]
There are two ways we can go:
1. accept any unambiguous prefix for any command except-set-for-which-we-accept-se-as-well
2. implement prefixes on a as-needed basis

I'd go for 2. and just add `se` as a synonym for `set`, if that's really needed.

**Comment by flatcap** [comment]
The PR allows all the abbreviations, above, and `:se` for `:set`.
Enjoy.

**Comment by flatcap** [comment]
@gahr and @flatcap have discussed this a bit more on IRC...
[these are excepts from their conversation]

When the compile options change, or a new command is added, the abbreviations could change.
If they're not stable, they're a lot less useful.

Commands aren't likely to change often
There are only two compile symbols that affect the commands: Lua and NotMuch
(all the rest are now hard-coded)

Ultimately though, neomutt isn't an editor
People aren't likely to be running lots of commands manually

:se (set) and :so (source) would save me a lot of grief
but I don't want to see a lot of random (undocumented) aliases growing, either

how about a command to set aliases?
we could include se->set and so->source in the default rc
and people could define their own

ooh, that's interesting

too bad "alias" is already defined
define se set 

the parsing of the command line is a bit limited, 
so you might only be able to abbreviate existing commands

and you shouldn't be able to redefine an existing command
it'd have to be like vim's "noremap" 

**define \<alias\> \<command\>**
where alias must not be an existing command and command must be an existing command
alias might be an existing alias, in which case it's redefined
**undefine \<alias\>**
where alias might be an existing alias to undefine, and silently ignore it if it's not 

another great use of stailq :)

**Comment by flatcap** [comment]
We prefer the idea of a `define` command to create your own shortcuts.

If anyone would like to help write it, please let us know (and @gahr and @flatcap are a bit busy, atm).
Help will be freely given :-)

**Comment by moritzschmitt** [comment]
I'm happy to give it a try to implement the `define` command.

**Comment by gahr** [comment]
@moritzschmitt Hi Moritz, any update on this? I'm willing to help if you need support!

**Comment by flatcap** [comment]
Moving this to the long-term wish list.
