### ISSUE TITLE
Mutt won't launch with the latest version of notmuch 0.25

### ISSUE THREAD

**Issue by protist** [neomutt/neomutt#703]
* **bug reports**

    * Expected behavior: mutt should launch
    * Actual behavior: mutt won't launch, with the following error: `mutt: error while loading shared libraries: libnotmuch.so.4: cannot open shared object file: No such file or directory`
    * Steps to reproduce: attempt to launch mutt
    * Used program versions:
         * neomutt 20170714-3
         * notmuch, notmuch-mutt, notmuch-runtime 0.25-1
    * Operating System and its version: Arch Linux, up to date

Reverting to the previous notmuch-runtime 0.24.2-1 fixes this problem. This version of notmuch-runtime provided the following files:
```
/usr/lib/libnotmuch.so -> libnotmuch.so.4.4.0
/usr/lib/libnotmuch.so.4 -> libnotmuch.so.4.4.0
/usr/lib/libnotmuch.so.4.4.0
```
The newest version of notmuch-runtime provides the following instead:
```
/usr/lib/libnotmuch.so -> libnotmuch.so.5.0.0
/usr/lib/libnotmuch.so.5 -> libnotmuch.so.5.0.0
/usr/lib/libnotmuch.so.5.0.0
```

**Comment by flatcap** [comment]
Hmm... This sounds a lot like: #693 - Library not loaded - Notmuch
NotMuch has been upgraded, but it hasn't caused NeoMutt to be rebuilt.

**Comment by protist** [comment]
Huh, exactly right! I rebuilt neomutt from the AUR PKGBUILD, and it's perfect now. Thank you. I know you don't use Arch, so for the AUR, you'll just need to manually bump pkgrel, i.e. make it 4. This will make force everyone to rebuild it locally. Thanks again.

**Comment by flatcap** [comment]
Done, thanks.
