### ISSUE TITLE
failing to sign emails with gpg subprocess

### ISSUE THREAD

**Issue by renlord** [neomutt/neomutt#704]
* **bug reports**

    * Expected behavior
Email should just be signed using GPG subprocess and sending should be successful

    * Actual behavior
Mutt logs "Can't open PGP subprocess!: No such file or directory (errno = 2)"
Debug Level 5 Logs:
`[2017-08-06 10:01:42] pgp.c:1088: mutt_mktemp returns "/var/folders/b2/3nvv88c50pb293sj44gj3_j00000gn/T//mutt-[hostname]-501-17118-5709327483014293745".
[2017-08-06 10:01:42] pgp.c:1094: mutt_mktemp returns "/var/folders/b2/3nvv88c50pb293sj44gj3_j00000gn/T//mutt-[hostname]-501-17118-3851100219726500363".
[2017-08-06 10:01:42] Can't open PGP subprocess!: No such file or directory (errno = 2)
[2017-08-06 10:01:42] Can't open PGP subprocess!: No such file or directory (errno = 2)`

    * Steps to reproduce
1. Write an email to be signed with GPG
2. On summary page after (:wq) prior to send, push send

    * Used program versions
NeoMutt 20170714 (1.8.3)
gpg (GnuPG) 2.1.22
gpg-agent (GnuPG) 2.1.22

    * Operating System and its version
Mac OS X v10.12.6

**Comment by flatcap** [comment]
NeoMutt doesn't do the encryption itself, it delegates to a external gpg program.
It sounds like you don't have gpg installed.

What are your settings:
`mutt -D | grep "^pgp.*command"`

**Comment by renlord** [comment]
My apologies. Thanks for prompting me to check with the command above.
I've since added the necessary gpg commands.

I assumed that running `brew install --with-gpgme neomutt` will setup the pgp configs.

**Comment by flatcap** [comment]
Ah, if you want to use gpgme, then you just need to: `set crypt_use_gpgme = yes` in your config.

**Comment by soubheek** [comment]
> Ah, if you want to use gpgme, then you just need to: `set crypt_use_gpgme = yes` in your config.

Thanks for your help @flatcap .
