### ISSUE TITLE
missing m4 files?

### ISSUE THREAD

**Issue by aduitsis** [neomutt/neomutt#705]
Just tried to build release 20170714, got failure because some macros, namely

```
configure.ac:181: warning: macro 'AM_PATH_GPGME' not found in library
configure.ac:837: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library
configure.ac:838: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:840: warning: macro 'AM_ICONV' not found in library

```

are missing, and so I get 
```
./configure: line 10236: syntax error near unexpected token `0.17'
./configure: line 10236: `AM_GNU_GETTEXT_VERSION(0.17)'
```

when trying to configure. I can see that previous releases did have some files under m4/, but they were gone around commit 16f557cdf36ea89971877efc226acc53fd76e9c5 . For example, gpgme.m4 is no longer there.

I would like to respectfully submit that this may be a bug, if someone for example does not have gpgme, which would mean that there is no gpgme.m4 in the system. Same I suppose with the other m4 files.

Many thanks,
Athanasios

**Comment by gahr** [comment]
Hi @aduitsis , the warning about gpgme is harmless - you can safely build neomutt without gpgme support.
Gettext, on the other hand, is now required. Is configure not picking up the one installed in your system? If so, could you give us some insight on your system and the packages installed?

**Comment by aduitsis** [comment]
In that case, mea maxima culpa. Hadn't realized that gettext is required, assumed that it was optional as well.
