### ISSUE TITLE
Mac OS X: ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by hvkls** [neomutt/neomutt#706]
Hi there!

Today's compilation attempt has failed:

Darwin blackice 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64
...
Mac OS X 10.11.6 El Cap.
...
Latest commit e4144b3  2 days ago @flatcap flatcap resync translations
...
configure: Summary of build options:

  Version:           20170714
  Host OS:           darwin15.6.0
  Install prefix:    /opt
  Compiler:          gcc
  CFlags:            -Wall -pedantic -Wno-long-long -g -O2 -fno-delete-null-pointer-checks -I/opt/include -I/opt/local/include -I/opt/sdk/include -I/var/sdk/include -I/var/include -I/usr/include -I/usr/local/include -I/var/include -I/var -I/usr/include/gnutls -I/usr/lib/ssl/include -I/usr/include/ncursesw -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/var/stash/include -I.  -I/opt/local/include -I/opt/local/include/openssl/include
  LDFlags:           -L/opt/lib -L/opt/local/lib -L/opt/sdk/lib -L/var/sdk/lib -L/opt/lib -L/usr/local/lib -L/usr/lib -L/var/lib -L/lib -L. -L/opt/local/include/openssl/lib
  Libs:              -lidn -lsasl2  -llua  -lnotmuch -lncursesw -L/opt/local/lib -dynamic -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lssl -lcrypto -lz -liconv
  Header cache libs: -Lhcache -lhcache  -lkyotocabinet

  GPGME:             yes
  PGP:               yes
  SMIME:             yes
  Notmuch:           yes
  Header Cache(s):   kyotocabinet 
  Lua:               yes
...
Making install in hcache
gcc  -Wall -pedantic -Wno-long-long -g -O2 -fno-delete-null-pointer-checks  -L/opt/lib -L/opt/local/lib -L/opt/sdk/lib -L/var/sdk/lib -L/opt/lib -L/usr/local/lib -L/usr/lib -L/var/lib -L/lib -L. -L/opt/local/include/openssl/lib -o mutt_md5 mutt_md5.o -L../lib -lmutt -lidn -lsasl2  -llua  -lnotmuch -lncursesw -L/opt/local/lib -dynamic -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lssl -lcrypto -lz -liconv
ld: warning: directory not found for option '-L/opt/sdk/lib'
ld: warning: directory not found for option '-L/var/sdk/lib'
ld: warning: directory not found for option '-L/lib'
ld: warning: directory not found for option '-L/opt/local/include/openssl/lib'
Undefined symbols for architecture x86_64:
  "_libintl_gettext", referenced from:
      _default_perror in libmutt.a(message.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [mutt_md5] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

**Comment by gahr** [comment]
Could you please provide this additional info:

- full `./configure` line and output
- what are you using to install dependencies? Homebrew? Macports?
- do you have gettext installed?

Thanks!

**Comment by hvkls** [comment]
Sure, here we go!

autoreconf --install --force ; ./configure --prefix=/opt --sysconfdir=/opt/etc --enable-gpgme --enable-notmuch --  enable-sidebar --enable-compressed --enable-pop --enable-imap --enable-smtp --enable-nntp --enable-locales-fix --enable-hcache --with-regex  --enable-mailtool --with-gss --enable-smime --with-ssl=/opt/local/include/openssl --with-gnutls=/opt/local/include/gnutls --with-sasl --enable-buffy-size --enable-inodesort --with-kyotocabinet --with-libiconv-prefix=/opt/local --enable-lua --enable-debug ;  make all ; make install
...
configure.ac:839: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:839: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:839: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
configure: WARNING: unrecognized options: --enable-sidebar, --enable-compressed, --enable-pop, --enable-imap, --enable-smtp, --enable-nntp, --enable-hcache, --with-regex, --enable-mailtool, --enable-buffy-size, --enable-inodesort
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /opt/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking for prefix... /opt
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for gcc option to accept ISO C99... none needed
checking for library containing strerror... none required
checking how to run the C preprocessor... gcc -E
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... ranlib
checking for ar... ar
checking whether byte ordering is bigendian... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking size of off_t... 8
checking for sendmail... /opt/local/sbin/sendmail
checking for gpgme-config... /opt/local/bin/gpgme-config
checking for GPGME - version >= 1.1.0... yes
checking for gpgme_op_export_keys... no
checking for a sed that does not truncate output... /opt/local/bin/gsed
checking for a Lua interpreter with version >= 5.2... lua
checking for lua... /opt/local/bin/lua
checking for lua version... 5.3
checking for lua platform... unknown
checking for lua script directory... ${prefix}/local/share/lua/5.3
checking for lua module directory... ${exec_prefix}/local/lib/lua/5.3
checking if LUA_VERSION is defined... yes
checking lua.h usability... yes
checking lua.h presence... yes
checking for lua.h... yes
checking lualib.h usability... yes
checking lualib.h presence... yes
checking for lualib.h... yes
checking lauxlib.h usability... yes
checking lauxlib.h presence... yes
checking for lauxlib.h... yes
checking luaconf.h usability... yes
checking luaconf.h presence... yes
checking for luaconf.h... yes
checking for Lua header version... 5.3
checking if Lua header version matches 5.3... yes
checking if LUA_VERSION is defined... yes
checking for library containing exp... none required
checking for library containing dlopen... none required
checking for library containing lua_load... -llua
checking for notmuch_database_open in -lnotmuch... yes
checking for notmuch api version 3... yes
checking for ispell... no
checking for initscr... no
checking for waddnwstr in -lncursesw... yes
checking for initscr in -lncursesw... yes
checking for tgetent in -lncursesw... yes
checking ncursesw/ncurses.h usability... no
checking ncursesw/ncurses.h presence... no
checking for ncursesw/ncurses.h... no
checking ncurses/ncurses.h usability... no
checking ncurses/ncurses.h presence... no
checking for ncurses/ncurses.h... no
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking for start_color declaration... yes
checking for typeahead declaration... yes
checking for bkgdset declaration... yes
checking for curs_set declaration... yes
checking for meta declaration... yes
checking for use_default_colors declaration... yes
checking for resizeterm declaration... yes
checking for use_extended_names... yes
checking for ANSI C header files... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking ioctl.h usability... no
checking ioctl.h presence... no
checking for ioctl.h... no
checking sysexits.h usability... yes
checking sysexits.h presence... yes
checking for sysexits.h... yes
checking sys/syscall.h usability... yes
checking sys/syscall.h presence... yes
checking for sys/syscall.h... yes
checking for fgets_unlocked... no
checking for fgetc_unlocked... no
checking for strsep... yes
checking for mkdtemp... yes
checking for sig_atomic_t in signal.h... yes, non volatile
checking whether sys_siglist is declared... yes
checking for wcscasecmp... yes
checking for futimens... no
checking where to put the documentation... ${datarootdir}/doc/mutt
checking for gethostent... yes
checking for setsockopt... yes
checking for getaddrinfo... yes
checking for library containing getaddrinfo_a... no
checking for krb5-config... /opt/local/bin/krb5-config
checking GSSAPI implementation... MIT
checking for deflate in -lz... yes
checking for X509_STORE_CTX_new in -lcrypto... yes
checking for SSL_new in -lssl... yes
checking for RAND_status... yes
checking for RAND_egd... yes
checking whether SSL_set_mode is declared... yes
checking whether SSL_MODE_AUTO_RETRY is declared... yes
checking whether X509_V_FLAG_PARTIAL_CHAIN is declared... yes
checking for library containing sasl_encode64... -lsasl2
checking kclangc.h usability... yes
checking kclangc.h presence... yes
checking for kclangc.h... yes
checking for kcdbopen in -lkyotocabinet... yes
checking whether NLS is requested... yes
checking for msgfmt... /opt/local/bin/msgfmt
checking for gmsgfmt... /opt/local/bin/msgfmt
checking for xgettext... /opt/local/bin/xgettext
checking for msgmerge... /opt/local/bin/msgmerge
checking for ld used by GCC... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... yes
checking for CFLocaleCopyCurrent... yes
checking for GNU gettext in libc... no
checking for iconv... yes
checking for working iconv... yes
checking how to link with libiconv... -liconv
checking for GNU gettext in libintl... yes
checking whether to use NLS... yes
checking where the gettext function comes from... external libintl
checking how to link with libintl... -lintl -Wl,-framework -Wl,CoreFoundation
checking for iconv... (cached) yes
checking for working iconv... (cached) yes
checking how to link with libiconv... -liconv
checking for iconv declaration... 
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking stringprep.h usability... yes
checking stringprep.h presence... yes
checking for stringprep.h... yes
checking idna.h usability... yes
checking idna.h presence... yes
checking for idna.h... yes
checking for library containing stringprep_check_version... -lidn
checking for idna_to_unicode_utf8_from_utf8... no
checking for idna_to_unicode_8z8z... yes
checking for idna_to_ascii_from_utf8... no
checking for idna_to_ascii_8z... yes
checking for idna_to_ascii_lz... yes
checking for idna_to_ascii_from_locale... no
checking for wchar_t functions... yes
checking for fmemopen... no
checking for open_memstream... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/Makefile
config.status: creating doc/Makefile
config.status: creating imap/Makefile
config.status: creating m4/Makefile
config.status: creating po/Makefile.in
config.status: creating hcache/Makefile
config.status: creating ncrypt/Makefile
config.status: creating lib/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
configure: WARNING: unrecognized options: --enable-sidebar, --enable-compressed, --enable-pop, --enable-imap, --enable-smtp, --enable-nntp, --enable-hcache, --with-regex, --enable-mailtool, --enable-buffy-size, --enable-inodesort
configure: Summary of build options:

  Version:           20170714
  Host OS:           darwin15.6.0
  Install prefix:    /opt
  Compiler:          gcc
  CFlags:            -Wall -pedantic -Wno-long-long -g -O2 -fno-delete-null-pointer-checks -I/opt/include -I/opt/local/include -I/opt/sdk/include -I/var/sdk/include -I/var/include -I/usr/include -I/usr/local/include -I/var/include -I/var -I/usr/include/gnutls -I/usr/lib/ssl/include -I/usr/include/ncursesw -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/var/stash/include -I.  -I/opt/local/include -I/opt/local/include/openssl/include
  LDFlags:           -L/opt/lib -L/opt/local/lib -L/opt/sdk/lib -L/var/sdk/lib -L/opt/lib -L/usr/local/lib -L/usr/lib -L/var/lib -L/lib -L. -L/opt/local/include/openssl/lib
  Libs:              -lidn -lsasl2  -llua  -lnotmuch -lncursesw -L/opt/local/lib -dynamic -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lssl -lcrypto -lz -liconv
  Header cache libs: -Lhcache -lhcache  -lkyotocabinet

  GPGME:             yes
  PGP:               yes
  SMIME:             yes
  Notmuch:           yes
  Header Cache(s):   kyotocabinet 
  Lua:               yes

( \
		(gcc -v >/dev/null 2>&1 && gcc -v) || \
		(gcc --version >/dev/null 2>&1 && gcc --version) || \
		(gcc -V >/dev/null 2>&1 && gcc -V) || \
		echo "unknown compiler"; \
	) 2>&1 | ./txt2c.sh cc_version >conststrings_c;
echo "-Wall -pedantic -Wno-long-long -g -O2 -fno-delete-null-pointer-checks" | ./txt2c.sh cc_cflags >>conststrings_c
grep ac_cs_config= config.status | \
		cut -d= -f2- | \
		sed -e 's/^"//' -e 's/"$//' | \
		./txt2c.sh configure_options >> conststrings_c
mv -f conststrings_c conststrings.c
version=`git describe --dirty --abbrev=6 --match "neomutt-*" 2> /dev/null | sed -e 's/^neomutt-[0-9]\{8\}//' -e 's/g//'`; \
	echo 'const char *GitVer = "'$version'";' > git_ver.h.tmp; \
	cmp -s git_ver.h.tmp git_ver.h || mv git_ver.h.tmp git_ver.h; \
	rm -f git_ver.h.tmp
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
...
MacPorts base version 2.4.1 (as of right now)
...
  gettext @0.19.8.1_0 (active)
  p5.24-locale-gettext @1.70.0_0 (active)

**Comment by gahr** [comment]
```
checking for GNU gettext in libintl... yes
checking whether to use NLS... yes
checking where the gettext function comes from... external libintl
checking how to link with libintl... -lintl -Wl,-framework -Wl,CoreFoundation
```

so, does it look like it's not picking up the correct linker flags when linking `mutt_md5`?

**Comment by gahr** [comment]
Does it help to add `$(INTLLIBS)` to `mutt_md5_LDADD` at `hcache/Makefile.am` :45?

```make
mutt_md5_LDADD = $(LIBMUTT) $(INTLLIBS)
```

**Comment by gahr** [comment]
I confirm that I can reproduce on FreeBSD:

```
/usr/local/libexec/ccache/cc -DHAVE_CONFIG_H -I. -I..  -I..  -I/usr/local/include -I/usr/local/include  -Wall -pedantic -Wno-long-long -O2 -g -Wall -MT mutt_md5.o -MD -MP -MF .deps/mutt_md5.Tpo -c -o mutt_md5.o mutt_md5.c
mv -f .deps/mutt_md5.Tpo .deps/mutt_md5.Po
/usr/local/libexec/ccache/cc  -Wall -pedantic -Wno-long-long -O2 -g -Wall  -L/usr/local/lib -L/usr/local/lib -o mutt_md5 mutt_md5.o -L../lib -lmutt -lncursesw -lssl -lcrypto -lz
../lib/libmutt.a(message.o): In function `default_perror':
/usr/home/gahr/github/neomutt/lib/message.c:90: undefined reference to `libintl_gettext'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by flatcap** [comment]
OK, I see what I broken.
`mutt_md5.c` includes the new library: `#include "lib/lib.h"`
This has references to the intl stuff.

Changing the header to `#include "lib/md5.h"` will probably fix things.
