### ISSUE TITLE
vfolder list empty

### ISSUE THREAD

**Issue by mrschyte** [neomutt/neomutt#707]
I've just switched from mutt-kz and noticed that the vfolder list is empty when using the change-vfolder command.

I have defined `macro index y <sync-mailbox><change-vfolder>?` in my muttrc.

The expected behavior is that when I press y in the pager the change-vfolder command shows me a list of available virtual folders. The problem is that the list seems to be empty. This was working fine with mutt-kz and I do have a list of vfolders set up which I can switch to if I type the exact name.

> NeoMutt 20170714-87-e4144b (1.8.3)
> Copyright (C) 1996-2016 Michael R. Elkins and others.
> Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
> Mutt is free software, and you are welcome to redistribute it
> under certain conditions; type `mutt -vv' for details.
> 
> System: Linux 4.12.4-1-ARCH (x86_64)
> ncurses: ncurses 6.0.20170527 (compiled with 6.0)
> libidn: 1.33 (compiled with 1.33)
> hcache backends: gdbm
> 
> Compiler:
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/lto-wrapper
> Target: x86_64-pc-linux-gnu
> Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
> Thread model: posix
> gcc version 7.1.1 20170630 (GCC) 
> 
> Configure options: '--prefix=/usr' '--sysconfdir=/etc' '--enable-debug' '--enable-pgp' '--enable-gpgme' '--enable-notmuch' '--enable-pop' '--enable-imap' '--enable-smtp' '--enable-hcache' '--enable-sidebar' '--with-gss=/usr' '--with-ssl=/usr' '--with-sasl' '--with-curses=/usr' '--with-regex' '--with-idn' '--with-gdbm' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now' 'CPPFLAGS=-D_FORTIFY_SOURCE=2'
> 
> Compilation CFLAGS: -Wall -pedantic -Wno-long-long -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fno-delete-null-pointer-checks
> 
> Default options:
>   +attach_headers_color +compose_to_sender +compress +cond_date 
>   +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
>   +initials +keywords +limit_current_thread +lmdb +multiple_fcc +nested_if 
>   +new_mail +nntp +pop +progress +quasi_delete +regcomp +reply_with_xorig 
>   +sensible_browser +sidebar +skip_quoted +smtp +status_color +timeout +tls_sni 
>   +trash 
> 
> Compile options:
>   +bkgdset +color +curs_set +debug +fcntl -flock -fmemopen +futimens 
>   +getaddrinfo -gnutls +gpgme +gss +hcache -homespool -iconv_nontrans +idn 
>   -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +resizeterm 
>   +sasl +smime +start_color +sun_attachment +typeahead 
> MAILPATH="/var/mail"
> PKGDATADIR="/usr/share/mutt"
> SENDMAIL="/usr/sbin/sendmail"
> SYSCONFDIR="/etc"
> 
> To learn more about NeoMutt, visit: http://www.neomutt.org/
> If you find a bug in NeoMutt, please raise an issue at:
>     https://github.com/neomutt/neomutt/issues
> or send an email to: <neomutt-devel@neomutt.org>
>

**Comment by esovetkin** [comment]
The pull request #712 solves related problem. Namely, pressing "x" and "?" to list the virtual folders.

Listing by pressing "y" still doesn't work.

**Comment by esovetkin** [comment]
Ah, ok. #712 actually solves the issue. The problem remains if one uses

macro index y <sync-mailbox><change-folder>?

I'll open a separate issue with it.
