### ISSUE TITLE
c shortcut issue

### ISSUE THREAD

**Issue by rapha8l** [neomutt/neomutt#71]
Hi,

I pull the sources yesterday, and since then the behaviour of the "c" shortcut has changed in a strange way : 
It used to suggest mail directories that have new mails. It still does, but after having changed directory, it never suggests another maildir that have new mails, but only the current one.
I hope I've been clear enough

Thanks

Raphael

**Comment by flatcap** [comment]
I understand and I can reproduce the bug.
It's odd, because the `<next-unread-mailbox>` command works correctly.

Unfortunately, I can only reproduce it with my **real** mail, not my test setup.
This might mean it's an IMAP problem.

**Comment by rapha8l** [comment]
Hi,
Thanks for your reply !
I'm using offlineimap, is there anything I can do ?

**Comment by flatcap** [comment]
> is there anything I can do

Not yet, thanks.  I should have enough information to find and fix the bug.

**Comment by flatcap** [comment]
OK, found it.  I missed an upstream fix. I've pushed the changes to GitHub: 52559f8
Please can you build the new version and check that it works for you.

**Comment by rapha8l** [comment]
Hello,

It works great, thanks a lot for your quick fix !
