### ISSUE TITLE
Google chrome - open attachment - not working

### ISSUE THREAD

**Issue by ldrahnik** [neomutt/neomutt#717]
Hi,
i tried this guide http://enricorossi.org/blog/2010/google_chrome_as_mutt_html_viewer/ but seems like that solution for me does not work. Could you help me someone?

Mutt 1.8.3 (2017-05-23)

mailcap:

```
text/html; /usr/bin/google-chrome %s & sleep 2; test=test -n $DISPLAY'; needsterminal;
```
google chrome:

```
file:///tmp/mutt.html

Your file was not found

It may have been moved or deleted.
ERR_FILE_NOT_FOUND
```

Thank you
Lukas

//EDIT: w3m works fine ```[-- Autoview using /usr/bin/w3m -I 'UTF-8' -dump -T text/html ''/tmp/mutt.html'' --]```

**Comment by flatcap** [comment]
Hmm... The string you quoted has an unbalanced `'` (single quote)
Removing it works for me:

`text/html; /usr/bin/google-chrome %s & sleep 2; test=test -n $DISPLAY; needsterminal;`

**Comment by ldrahnik** [comment]
Thank you, u re right. Now my string looks like:
```
text/html; /usr/bin/google-chrome %s & sleep 2; test=test -n "$DISPLAY"; needsterminal;
```

but still i have:

```
file:///tmp/mutt.html

Your file was not found

It may have been moved or deleted.
ERR_FILE_NOT_FOUND
```

When i use `s <filename.html>` to save attachment and next execute command in terminal window: `/usr/bin/google-chrome <filename.html>` everything works.

```
Google Chrome
Version 60.0.3112.90 (Official Build) (64-bit)
```

**Comment by ldrahnik** [comment]
@flatcap Works for u without or with this error?

```
9008:9042:0816/172324.139443:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
                                                                                                          Created new window in existing browser session.
```

**Comment by flatcap** [comment]
I see the same error message -- that's something from chrome, not neomutt, but it works.

One problem could be timing.  If you don't have `$wait_key` set, then the sequence will be:
- create tmp file
- spawn chrome
- wait two seconds
- delete tmp file
- return to the email

If chrome isn't running, it might not read the file before neomutt deletes it.

Try increasing the sleep in the mailcap.  That may fix the problem.
Adding "set wait_key" to your muttrc might also do it, but that'll be irritating.

**Comment by ldrahnik** [comment]
Now my string looks like:

~/.mutt/mailcap

```
text/html; /usr/bin/google-chrome %s & sleep 1; test=test -n "$DISPLAY"; nametemplate=%s.html; needsterminal
```

```nametemplate=%s.html``` is needed for saving files with .html extension

~/.mutt/muttrc

```
...
auto_view text/html                             	 # view html automatically
alternative_order text/plain text/enriched text/html     # save html for last

set mailcap_path 	= ~/.mutt/mailcap
...
```

That was my silly mistake cus i thought that mailcap file name is `mailcap` located in root by default but no, its not. (https://wiki.archlinux.org/index.php/mutt)
