### ISSUE TITLE
Neomutt thinks `mbox_type` is `mbox` when it should be `maildir`

### ISSUE THREAD

**Issue by s-gilles** [neomutt/neomutt#719]
This occurs with neomutt from the gentoo_neomutt overlay for gentoo.

I store my mail locally, in maildir format, and until recently I
had never set the `mbox_type` variable in my config. Prior to commit
eebf72008a790dc3214d89beeea4daf815c2b5bc , this wasn't a problem,
but since that commit, `:set ?mbox_type` shows `mbox`, and
`save-message` has become unusable.

In particular, if I'm in maildir foo and want to move a message to
bar, I `s`, then `=bar/`, then `Return`, on which I get the error
message

    '=bar/' is a directory, need a filename for mbox.

The fix is to add `set mbox_type = maildir` to my config somewhere,
but that used to not be necessary (and since I don't want mbox, I
wouldn't have guessed to set a variable with "mbox" in the name).

**Comment by r3lgar** [comment]
Can't reproduce.

Can you post here how your mail hierarchy looks like (with at least one real file name)? You can use `app-text/tree` for that.

**Comment by r3lgar** [comment]
Hm, really.

With `set mbox_type = Maildir` it asks for `=bar` creation, without any `mbox_type` declaration it throw an error `'=bar/' is a directory, need a filename for mbox.`

But I have disabled `mbox` USE flag in my NeoMutt build.

What will @flatcap say?

**Comment by flatcap** [comment]
I've just pushed a "fix" to the problem.  By trimming the trailing `/` from the completed name, NeoMutt now tries to do the right thing:
- Maildirs are recognised
- Otherwise `$mbox_type` is honoured

**Comment by s-gilles** [comment]
I'm using https://github.com/neomutt/gentoo-neomutt , which is linked from https://www.neomutt.org/distro.html .
