### ISSUE TITLE
Get message-id after send

### ISSUE THREAD

**Issue by ymuv** [neomutt/neomutt#72]
Hello. 
I using mutt in some script.  (like 
`echo some text | mutt -s  THEME mail@example.com`

Can I get Message-Id of this message to stdout(or stderr).

Currently I do:

```
if (first run)
  export MESSAGE_ID="some_message"
  echo text | mutt  -e "my_hdr Message-ID:$MESSAGE_ID" -s  THEME mail@example.com
else
  echo "text" | mutt  -e "my_hdr In-Reply-To: $MESSAGE_ID\nReferences: $MESSAGE_ID" -s HEADER  mail@example.com
endif
```

 Thanks

**Comment by flatcap** [comment]
I can see how that would be useful to you.
I'm just not sure how many **other people** would find it useful.

If someone writes the code, I'll happily accept it.

**Comment by flatcap** [comment]
It's useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
