### ISSUE TITLE
Modify fcc_clear to retain signatures

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#727]
* **feature requests**

3.76. fcc_clear

Type: boolean 
Default: no

When this variable is set , FCCs will be stored unencrypted and unsigned, even when the actual message is encrypted and/or signed. (PGP only)

   * Why do you not like the current state?

While storing an unencrypted email might make sense as the original encrypted version would be unreadable, I don't see an advantage in removing a signature too.

   * What would you like to see to change?

I'd like to modify the behaviour of `fcc_clear` to just store the cleartext email if it's encrypted. Any signed (but not encrypted) emails would be stored as-is.

**Comment by gahr** [comment]
@neomutt/downstream-packagers @neomutt/reviewers what are your thoughts on this?

**Comment by grobian** [comment]
@nicolasbock your call I think :)

**Comment by nicolasbock** [comment]
Do I understand this correctly that the current behavior of `fcc_clear` is to strip the email from both encryption _and_ signature? If that's the case, I think this request makes sense. The email can still be read if it's signed but not encrypted and there is value in the signature. So I am all for it :smile:!

**Comment by gahr** [comment]
@nicolasblock, yes that is correct: if the email is either signed or encrypted (or both), the pre-pgp'd cleartext version is saved.

**Comment by nicolasbock** [comment]
@gahr I left you a comment in your commit  https://github.com/neomutt/neomutt/commit/b76b16d7e11d6d6c053562d02e696097cff4b791.

**Comment by gahr** [comment]
@nicolasbock yeah we might want to track that in a separate issue ;)

**Comment by nicolasbock** [comment]
I think that's fine. Your patch looks good to me with the caveat that it only covers 'half' the cases :smile:

**Comment by gahr** [comment]
However, the more I think about it, the more I am of the opinion that (encrypt to self)[https://www.neomutt.org/feature/encrypt-to-self] is a more elegant approach..

**Comment by nicolasbock** [comment]
Ok that's an excellent point! Now that you mention it... I completely agree. Do you want to drop this issue then and leave `fcc_clear` as it is?

**Comment by gahr** [comment]
Let's keep it open some more and see wheter the discussion brings anything else ;)

**Comment by gahr** [comment]
Current situation is ok, as it turns out.
