### ISSUE TITLE
fcc_clear should give a means to record how a msg was encrypted

### ISSUE THREAD

**Issue by libBletchley** [neomutt/neomutt#729]
When configured as "set fcc_clear = yes", mutt saves the message without encryption but neglects to record how the message was sent.  The problem is that mutt then hides from the user whether a message was encrypted.  It's useful to know how a message was sent.  I suggest that when the fcc_clear feature is invoked, it create a new header in the saved message.  Possible proposals/examples:
`
X-Encrypted-To: pgp key id XYZ
`
`
X-Encrypted-To: s/mime key id foo
`
`
X-Encryption-Cmd: /usr/bin/gpg    --batch  --quiet  --no-verbose --output - --encrypt --textmode --armor --always-trust -- -r %r -- %f"
`

If the whole GPG (or openssl) commandline is put in the stored email, users can see what parameters were actually used for troubleshooting/diagnosis.

It would also be useful if the "P" flag would appear in the pager for these cases as well.

If there is any objection to adding headers in the stored message that were not actually sent, an alternative approach would be to have a log file that records this information along with the msg id.

**Comment by libBletchley** [comment]
An alternative idea: introduce the option to store both encrypted and cleartext versions of a message.  ATM, users add themselves as a recipient by defining `encrypt-to` in `$HOME/.gnupg/gpg.conf` in order to be able to read msgs they compose.  That would no longer be necessary if both an encrypted and cleartext version were stored.  Then the ciphertext would serve to show how the msg was encrypted and also serve diagnosis purposes, while the cleartext version would give convenience (faster searching which would not decrypt all mail, and also relieve the user of typing their password to review something they sent).  The user would have all advantages but at the cost of storage space.

**Comment by libBletchley** [comment]
The following workaround generally works as a way to track whether encryption was used:
```
fcc-hook '~C edward@snowden.info ~G' +sent_mail/pgp_keyid_`gpg --list-keys --with-colons edward@snowden.info | awk -F: '/@/ && max<$6 {max=$6; field=$5} END{print field}'`
```
This workaround should not diminish the need for the enhancement request, however.  These are the issues with the workaround:
 * forces sloppy organization
 * operates with the invalid assumption that the e-mail address used for the recipient is associated to a pubkey
 * assumes that it's also the latest key on the keyring
 * assumes that PGP was used and not SMIME

A sender can always choose a different key then that given by the assumptions, and be left with misleading information in storage.

**Comment by libBletchley** [comment]
This is the equivalent workaround hack for s/mime, which presumes an e-mail address is associated to a PGP key or an S/MIME key, but never both:
```
fcc-hook '~C edward@snowden.info ~G' +sent_mail/smime_keyid_`awk '/edward@snowden.info/{print $2}' $smime_certificates/.index`
```

**Comment by flatcap** [comment]
Moving this to the long-term wish list.
