### ISSUE TITLE
with notmuch unconditionally segfaults when displaying a message

### ISSUE THREAD

**Issue by bitstreamout** [neomutt/neomutt#73]
Compare with bug http://bugzilla.opensuse.org/show_bug.cgi?id=986534 :
```
#2  0x800248a6 in mutt_copy_header (in=0x80201708, h=0x80303c30, out=0x802015a8, flags=786582, prefix=0x0) at copy.c:435
435	    fputs (nm_header_get_tags(h), out);
(gdb) print *((struct nm_hdrdata *) h->data)
$1 = {folder = 0x41 <error: Cannot access memory at address 0x41>, tags = 0x12430 <error: Cannot access memory at address 0x12430>, 
  tags_transformed = 0x0, tag_list = 0x19, oldpath = 0x6863694d <error: Cannot access memory at address 0x6863694d>, 
  virtual_id = 0x206c6561 <error: Cannot access memory at address 0x206c6561>, magic = 2054447437}
```

**Comment by flatcap** [comment]
Thanks.  I've found the line that's causing the crash:
> copy.c
> fputs (nm_header_get_tags(h), out);

I don't yet know who's corrupting the tags.

**Comment by flatcap** [comment]
I've found it and fixed it.
NotMuch was using pointers that weren't its to use!

**Comment by darnir** [comment]
If it's fixed, can we close this issue?

**Comment by flatcap** [comment]
Yes, downstream is happy.

**Comment by darnir** [comment]
There's multiple other issues I saw that seem to be resolved but are still open here. I was hesitant to close them preemptively.

**Comment by flatcap** [comment]
I was sort of waiting for some time to clean them all up.
Use your initiative -- we can always re-open them.
