### ISSUE TITLE
indicate to recipients when they've missed an e-mail using sequence numbers

### ISSUE THREAD

**Issue by libBletchley** [neomutt/neomutt#732]
* Why do you not like the current state?

E-mail is unreliable.  Some messages do not reach recipients despite being accepted by the recipients mail server.  This is largely due to poor spam controls and largely impacts users who running their own mail server or using alternate From: fields.  Mutt (and all MUAs for that matter) have no mechanism to make mail lost in this scenario detectable.

    * What would you like to see to change?

For each recipient e-mail address, Mutt should maintain a sequence number.  Users should be able to have that sequence number automatically inserted into outbound messages, either by prefixing or suffixing the Subject: field, msg id field, or in a separate custom field.  Recipients will know a msg is missing when there is a break in the sequence.  Users will want to use the sequence numbers for some recipients but not others, so it insertion should be controllable by hooks.  Obviously it would get complicated if there are multiple visible recipients, but certainly it would be useful to have this feature available for single-recipient cases.

As a bonus, this mechanism could improve spam filtering.  E.g. if a message arrives with a spent sequence number or a wildly different sequence number than expected, it would be useful information to a spam scoring robot.

**Comment by gahr** [comment]
I am sorry, I read your proposal a few times already and I think I still don't understand what you mean.

Do you mean that for any ordered pair (Sender, Receiver) there should be a unique monotonously increasing sequence number being assigned, so that when Receiver receives a message from Sender he can check `NewId` with `LastReceivedId`, and if `NewId != LastReceivedId+1` he can assume that some mail got lost?

**Comment by libBletchley** [comment]
Indeed.  So if bob e-mail alice, she might see this in her pager:

Subject: (msg 1) how goes it?
Subject: (msg 2) all is good
Subject: (msg 3) call me
Subject: (msg 5) still waiting for your answer

If Alice's pager looks like this, she can see that message 4 is missing, and likely in her spam box.

**Comment by gahr** [comment]
By ordered pair I meant that ghe sequences for a->b and b->a are distinct.

Have you thought of what happens if either a, b, or both use any other mailer in addition to mutt?
If a replies using his mobile phone, webmailer, thunderbird, Mail.app, ... just once the sequence will lose track of messages.

I don't personally think this approach will be of any use in a real world scenario, sorry.

**Comment by libBletchley** [comment]
If a sender doesn't use mutt (and thus w/out the sequence number insertion), those particular messages would obviously not have the benefit of dropped msg detection, which would not affect the loss detectability of mutt-transmitted messages.

I've been doing this for years and it has had good results.  I have a script that creates the sequence numbers and invokes mutt from the commandline.  Every document I send to my accountant is mutt-transmitted with a sequence number.  Any break in the numbering and the accountant knows a document didn't arrive.  And indeed when I use mutt interactively to e-mail my accountant, those e-mails lose the protection.  But document loss is unaffected (still detectable).

So it's proven to work in the real world.  I'm curious what real world solution you have in mind.  Would you call your accountant periodically and name the various documents, asking if she received them?  Or do you have some kind of return receipt header, which AFAIK would only work for MS Outlook recipients?

It's wrong to have a wrapper script doing the numbering when the job is best delegated to the MUA responsible for composition, which has all information available to perform the task.  If I want messages that are interactively composed in mutt to have the same benefit that my accountant and I have had with documents, I would have to manually track and assign the numbers.  That's not the best solution.

**Comment by gahr** [comment]
I understand your use case and I'm sure this method is working fine for you. I'm just not convinced that your use case is general enough to call for an in-code solution.
Perhaps I just never experienced the use case.

Just my thoughts, let's see what's the others' opinion.

**Comment by nobrowser** [comment]
I think this is a neat idea but it doesn't necessarily belong to the MUA.

**Comment by libBletchley** [comment]
> I think this is a neat idea but it doesn't necessarily belong to the MUA.

Part of assessing whether this feature belongs in the MUA is to consider what existing tools already cover the use case.  So if you know of one, please mention it here.  Otherwise, what tool do you have in mind?  If you're thinking the MTA should do this, there are problems with that:

* Placement of the sequence numbers would become limited to the metadata, because it couldn't tamper with a cryptographic body.  Yet forcing it in the metadata forces exposure (maybe bob doesn't want mallory to know how many messages he sent to alice).

* How would the MTA know whether the sender wants to use a sequence number?  For the MTA to know the authors intent would require a protocol change, no?  This would greatly complicate the task.

The first of the two reasons seems to imply that the functionality should be in the MUA.  It's the MUA that encrypts or signs the message, and some senders would require the sequence number to be embedded in that payload.

**Comment by gahr** [comment]
> Placement of the sequence numbers would become limited to the metadata, because it couldn't tamper with a cryptographic body. Yet forcing it in the metadata forces exposure (maybe bob doesn't want mallory to know how many messages he sent to alice).

Wasn't your proposal all about having sequence numbers in the subject? AFAIK, rfc822 headers are non covered by pgp.

**Comment by libBletchley** [comment]
> Are you now implying that the proposed mechanism should be able to insert such sequence numbers anywhere in the headers / body of a message?

I was deliberately vague on that.  Since there is no RFC for this, mutt would ideally give the user freedom to choose where the number is placed.  OTOH, giving the user total flexibility would be a burden to code.  

Perhaps a good balance is to put it in the Subject: line after the initial composition.  If the user wants it in the body, they can edit before sending and move it to the body.  Or you offer a simple boolean setting like "sequence_number_in_body".  I don't have a strong opinion on that ATM.  This should get some deeper analysis before being implemented.

**Comment by libBletchley** [comment]
Here is a workaround for those that are able to use a `send-hook` (which excludes myself because I have `$autoedit` set).  Add a `send-hook` that calls a shell script to set the signature:

`send-hook '~t alice' "set signature=~/scripts/mutt_counter_alice.sh|"`

Use this for the shell script:
```
#!/bin/bash

# to reset: sqlite3 ~/db/mutt.db "drop table mom_web_counter;"

sqlite3 ~/db/mutt.db "
  create table if not exists alice_counter (counter integer primary key autoincrement);
  insert into alice_counter default values;
  delete from alice_counter where counter < (select max(counter) from alice_counter);
  select 'msg #'||max(counter) from alice_counter;"
```
Since I have `$autoedit` set, I would have to use a `send2-hook`, but then I could never re-edit a msg because it would advance the counter.  A workaround to the workaround might be to not use sqlite, but instead search sigs in the FCC folder and derive the highest number for a particular recipient.

**Comment by gahr** [comment]
Flat-file version:

```sh
#!/bin/sh
FILE=alice_counter
echo $((`cat $FILE 2> /dev/null` + 1)) > $FILE
cat $FILE
```

**Comment by nobrowser** [comment]
I would do the SQL version differently: no deletes or updates, just append a record for each new value.  You can add other columns like a timestamp and you'll have a useful history.

Of course, even that is quite easy to do with a flat file and Unix tools, just not as efficiently.
