### ISSUE TITLE
What about using libyui? TUI+GUI support in one!

### ISSUE THREAD

**Issue by timofonic** [neomutt/neomutt#735]
Hello.

Thanks for your project, it seems quite interesting.

I use console most of the time, but sometimes I prefer the GUI approach. I often use remote shells and in those cases, I use console apps and many of them use ncurses/s-lang or whatever (as you may know, some programs use minimal parts of ncurses, but that's another topic).

What about using [libyui](https://github.com/libyui/)? This way, your program will be available for TUI (ncurses) and GUI (Gtk, Qt). it would make your program a lot more flexible and adapt better to different Desktop Environments. Originally it was developed for OpenSUSE's YaST, but it can be used by any project ;)

Kind regards.

**Comment by toogley** [comment]
I think that is at the moment not possible, because our UI is (as far as i know) too tightly integrated in our code base, meaning that its very difficult to replace it. That means, the refactoring we're doing at the moment (reducing scope of code, simplifications, etc.) has to be "finished" before we can even think about that. Therefore i don't think this is a realistic target.

**Comment by flatcap** [comment]
Wow!  That's certainly an interesting project (probably ten years too late, but interesting).
If only they had some examples  to show.

As @toogley says, we've got a long way to go to sort out the UI.
A modern program should have a separation between data and display.

When we get sorted, I'm confident that a GUI is **not** the direction we'll be heading.
NeoMutt wants to be the 'vim' of email clients -- light, flexible, scriptable.
I don't think adding a GUI would appeal to most of our users.

**Comment by r3lgar** [comment]
>NeoMutt wants to be the 'vim' of email clients -- light, flexible, scriptable.

In theory, if we will use libyui, we can provide a possibility integrating GUI as a module.

But this is really a difficult task.

**Comment by toogley** [comment]
However, if we can simplify our codebase by reusing libyui, i think we should consider it. (However, the separation between data and display is of course more important)

**Comment by gahr** [comment]
Aside from the separation of logic/UI, the mutt UI is not designed around the common desktop semantics of dialogs, labels, menus... I don't think libyui's concepts will ever fit.

**Comment by flatcap** [comment]
Thanks for the suggestion, but have a lot of work ahead of us before we could ever benefit from a framework like libyui.
