### ISSUE TITLE
version.sh regression

### ISSUE THREAD

**Issue by paravoid** [neomutt/neomutt#74]
NeoMutt's version.sh regresses from stock mutt by returning an empty string when ./configure is called from a different directory (such in the case of a "build" directory).

Re-adding this piece of code from the original mutt at the top fixes this issue:

```
# Switch to directory where this script lives so that further commands are run
# from the root directory of the source.  The script path and srcdir are double
# quoted to allow the space character to appear in the path.
srcdir=`dirname "$0"` && cd "$srcdir" || exit 1
```

**Comment by flatcap** [comment]
Thanks, committed.
