### ISSUE TITLE
add Memory Hole support to protect metadata

### ISSUE THREAD

**Issue by libBletchley** [neomutt/neomutt#741]
* Why do you not like the current state?

PGP/MIME and S/MIME messages needlessly expose metadata such as the `Subject:` line.

    * What would you like to see to change?

Project "Memory Hole" has emerged to address the problem by embedding normally exposed metadata in a newly introduced MIME attachment.  Project lives here:

  http://modernpgp.org/memoryhole/

Even though the standard is still in the draft stages, it's designed in a way that does not break non-compliant MUAs.  So it could be added to mutt now.  Note that it has already has been implemented in Enigmail, with a switch.

S/MIME caveat:

The S/MIME standard already includes header protection using a different approach than Memory Hole.  See https://github.com/ModernPGP/memoryhole#alternatives-considered.  So it should first be investigated whether mutt is currently S/MIME compliant (as it seems to not have that support).  It should also be investigated whether mutt should take that direction instead, or whether the user should have a choice between the two techniques.  Note that Memory Hole is designed to work for both S/MIME and PGP/MIME.

**Comment by gahr** [comment]
Is the project still alive? I see that the draft expired 1.5 years ago and the last commit to the repository was 1 year ago.

**Comment by libBletchley** [comment]
I didn't realize it was a stale project.  Perhaps mutt should just focus on S/MIME standards compliance.

OTOH, now I see that the Makefile for that project has the comment "Fix mbox generation so mutt recognizes output".  I'm confused.. is mutt already supporting this?

**Comment by ge-fa** [comment]
This gets more and more widespread use, Enigmail does ship it now enabled by default.

**Comment by duckdalbe** [comment]
+1

I'd love to see this implemented! Memoryhole will only take off if more MUAs support it. Currently TB/enigmail appears to be the only one with some others having patches.

Also the project is active, only the website is not. See e.g. https://wiki.gnupg.org/OpenPGPEmailSummit201607/MemoryHole
Maybe it would help if more people would nag about the lagging documentation.

**Comment by gahr** [comment]
> Also the project is active, only the website is not. See e.g. https://wiki.gnupg.org/OpenPGPEmailSummit201607/MemoryHole

This is still one year ago

**Comment by duckdalbe** [comment]
> This is still one year ago

True. Nonetheless there's activity around the project. E.g. enigmail is shipping the feature already, other projects are discussing using or implementing it (e.g. https://0xacab.org/schleuder/schleuder/issues/74). Which in my eyes means it's de facto alive.
Doesn't that suffice in order to consider implementing the feature in neomutt?

**Comment by gahr** [comment]
> Doesn't that suffice in order to consider implementing the feature in neomutt?

Far from me to veto anything (even if I had the right, which I don't). I am just cautious because the spec looks incomplete at best... but yeah, please go ahead and implement it :)

**Comment by flatcap** [comment]
> will only take off if more MUAs support it
> suffice in order to consider implementing the feature in neomutt?

It sounds interesting and there are certainly plenty of "cautious" people using NeoMutt.

However, NeoMutt doesn't have many developers and those we do have a quite busy.
If you'd like to see this feature, then you'll need someone to _drive_ the project.

You'll need to understand:
- Memory Hole spec
- How TB/Enigmail work
  * Contact their developers for advice
- How NeoMutt works from a user's perspective
  * Where/when would the Memory Hole stuff happen?
    - Sending mail
    - Replying to mail
    - Resending mail
    - Postponing mail
    - etc
- How/where Memory Hole would fit into NeoMutt
  (We can help advise you, here)

and crucially, you'll need developer(s) to do the work.

**Comment by dkg** [comment]
memoryhole is definitely alive.  the people who work on it/consider it are mainly active within [the autocrypt project](https://autocrypt.org) today.  While memoryhole is not officially part of autocrypt, discussion about it is more likely to get traction on the typical autocrypt channels ([mailing list](https://lists.mayfirst.org/mailman/listinfo/autocrypt), `#autocrypt` on `irc.freenode.net`).

**Comment by libBletchley** [comment]
**neomutt should lead, not follow**
Regardless of other projects use of memoryhole, there's no reason neomutt can't be the _leader_.  IMO neomutt /should/ be a leader.  The rationale is that a feature-rich tool for expert users and hackers deployed in mom's basements (neomutt) need not be influenced by limitations of corp-produced dumb user GUI MUAs (confused users, corporations trying to profit, etc).  It is really the best MUA to empower advanced users, and showcase how capable an MUA can be.  I choose to use mutt because it empowers me in ways most MUAs don't or couldn't.
**decision separation needed**
There are three separate decisions here, which should be independently decided.
 * Should mutt be capable of protecting outbound metadata, and parsing inbound metadata from non-mutt composed msgs?
 * Is memoryhole the best approach, or the S/MIME approach?
 * Who should do the work?

If ppl agree to favor security on the first question, then I'm not sure if `status:blocked` is right for this ticket.  I think it should be `status:approved` (if there is such a thing) and it should sit that way until someone gets the urge to do the work.  I'm confused about the meaning of `status:blocked`.  When a bug is "blocked", I normally understand that to mean that the bug cannot be fixed until another "blockING" bug is first fixed.  But that doesn't seem to be the case here.

**Comment by flatcap** [comment]
You make a good case...

> neomutt should lead, not follow

Absolutely...

> (labor) Who should do the work?

This is the problem.

There are LOTS of viewers of the project, but very few actually contribute.
I encourage anyone who shows interest in contributing, but it's time-consuming
(and emotionally draining when they wander off without doing anything).

Part of the problem is that the code is hard to understand.
We're working on fixing this, but it's taking time.

> status:blocked

Don't worry about that.  We have a lot of labels, which we don't use consistently :-)

> status:approved

Sounds like a reasonable idea.
We just need a Triage Manager to keep track of things for us.

**Comment by flatcap** [comment]
Thanks for telling us about Memory Hole, @libBletchley.
We'd love to add support, but we simply don't have the developers.
If someone volunteers to work on it we can re-open the issue.
This issue will now be closed and listed on the [closed discussions page](https://www.neomutt.org/dev/discussions)

**Comment by marmarek** [comment]
Is anyone working on it, are there any preliminary or similar patches? I can help with some development and testing, but won't manage to do the whole thing alone.

**Comment by flatcap** [comment]
Hi @marmarek.  You're in luck.
While we've been busy re-architecting NeoMutt, upstream have added Memory Hole support.
I haven't tested it myself, but the code is now in `master`.

**Note**: `master` is currently under heavy development and not suitable for general use.

If you do give it a try, please let us know how you get on :-)

**Comment by marmarek** [comment]
Thanks!
Looks to be working, with those settings:
```
set crypt_protected_headers_subject="Encrypted Message"
# save decrypted headers back to local inbox
#set crypt_protected_headers_save=yes
# protect headers of outgoing messages, mask with $crypt_protected_headers_subject
set crypt_protected_headers_write=yes
# handle protected headers in incoming messages (index etc)
set crypt_protected_headers_read=yes
```

One issue I see is in pager I still see "Encrypted Message" subject but only below, after `[-- The following data is PGP/MIME encrypted --]`, the actual header. This kind of makes sense (to know what is really encrypted and what isn't), but looks weird.

**Comment by dkg** [comment]
Over in the Autocrypt project, we've been experimenting with using `...` instead of `Encrypted message`, to avoid potential misleading guidance (what if a cleartext message has this subject line?) and localization problems.

[This deltachat bug report](https://github.com/deltachat/deltachat-core/pull/449) explains more detail.

**Comment by flatcap** [comment]
Thanks for the feedback.

**Comment by marmarek** [comment]
Another thing:
 * replying to encrypted email should keep subject - regardless of its being hidden or not (if actual subject was already sent in clear, there is little point in hiding it in response) - otherwise the thread is very annoying to read if anyone use not Memory Hole compatible client. Maybe it's already possible with some `send-hook` magic?
