### ISSUE TITLE
Error 2,S: Invalid argument (errno = 22) when trying to send an email on my Mac

### ISSUE THREAD

**Issue by AndreasAZiegler** [neomutt/neomutt#743]
* **bug reports**

    * Expected behavior
      By pressing the button "y" sending of the email without an error
    * Actual behavior
     By pressing the button "y", I get the following message:
`
 /Volumes/Data/.mail/personal/sent/tmp/cur.1504595776.R2120509153651692214.Andreass-MacBook-Pro:2,S: Invalid argument (errno = 22)`
    * Steps to reproduce
    Pressing button "y" after finished composing an email
    * Used program versions
    NeoMutt 20170714 (1.8.3) installed with Homebrew
    * Operating System and its version
   Mac OS X 10.11.6

**Comment by flatcap** [comment]
It seems to be failing when it saves a copy to your 'sent' folder.
There are two variables that control the behaviour:
- `$record` which folder to save in: '~/.mail/personal/sent'
- `$mbox_type` which format the folder is, yours seems to be 'maildir'

Check that all three maildir directories exist:
- /Volumes/Data/.mail/personal/sent/cur
- /Volumes/Data/.mail/personal/sent/tmp
- /Volumes/Data/.mail/personal/sent/new

If they don't, NeoMutt should probably create them (a bug).

**Comment by AndreasAZiegler** [comment]
<img width="491" alt="screen shot 2017-09-05 at 8 33 37 pm" src="https://user-images.githubusercontent.com/6949508/30059350-bb1d35c0-9279-11e7-90d3-5ba3ed33c25c.png">
As you can see in the screenshot, the maildir directories exist. I use the same folder (.mail) also for my mutt on my Linux (I have a dual boot system with Mac OS X and Arch Linux) and there neomutt works like a charm. The folders .mail/* were actually created by neomutt on Arch Linux.

**Comment by flatcap** [comment]
In MacOS, can you create/delete files in those dirs?

**Comment by AndreasAZiegler** [comment]
Yes, in Mac OS X I have read and write access.

**Comment by flatcap** [comment]
Hmm...  I'm stuck now.
I've traced through the code and I can't understand why the file creation is failing.

https://github.com/neomutt/neomutt/blob/neomutt-20170714/mh.c#L1483

I'll keep thinking...

**Comment by roccoblues** [comment]
Trying to cleanup some older issues here. Can anyone comment if this issue still persists with the latest version? Thanks!
