### ISSUE TITLE
nntp_user & nntp_pass

### ISSUE THREAD

**Issue by flob82** [neomutt/neomutt#744]
* **bug reports**

    * Expected behavior
Auth with nntp server by using nntp_user and nntp_pass
    * Actual behavior
This two variables nntp_user & nntp_pass seems to be broken
    * Steps to reproduce
When set this two variables i can't connect with the news server
The only way i can connect is to set news_server = 'news://user:pass@adress'
    * Used program versions
debian mutt package : 1.7.2-1
    * Operating System and its version
Debian Stretch (9.1)

Great jobs neomutt's team ;)

**Comment by gahr** [comment]
I can't reproduce. Using this minimal config file

```
set news_server=news.giganews.com
set nntp_user=user@example.org
set nntp_pass=foobar
exec change-newsgroup
```

NeoMutt tells me, in this order:

```
Connected to news.giganews.com. Posting is ok.
Authenticating (USER)...  
USER authentication failed.
```

If I comment the `nntp_user` and `nntp_pass` lines in the config, NeoMutt tells  me:

```
Connected to news.giganews.com. Posting is ok.
Username at news.giganews.com: gahr
```

and waits for my input.

Could you please try to reproduce with a similar minimal example?

**Comment by flob82** [comment]
You're right, same here.


>[2017-09-14 12:13:35] Connected to news.giganews.com. Posting is ok.
[2017-09-14 12:13:36] 4> STAT
[2017-09-14 12:13:36] 4< 480 authentication required
[2017-09-14 12:13:36] nntp_auth: available methods: USER
[2017-09-14 12:13:36] nntp_auth: trying method USER
[2017-09-14 12:13:36] Authenticating (USER)...
[2017-09-14 12:13:36] 4> AUTHINFO USER user@example.org
[2017-09-14 12:13:37] 4< 381 more authentication required
[2017-09-14 12:13:37] 4> AUTHINFO PASS *
[2017-09-14 12:13:42] 4< 481 Invalid username or password

But with my news server and your config

>[2017-09-14 12:17:03] Looking up news.free.fr...
[2017-09-14 12:17:03] Connecting to news.free.fr...
[2017-09-14 12:17:03] Connected to news.free.fr:119 on fd=4
[2017-09-14 12:17:03] 4< 201 news-1.free.fr (1-2) NNRP Service Ready - newsmaster@proxad.net (no posting)
[2017-09-14 12:17:03] 4> CAPABILITIES
[2017-09-14 12:17:03] 4< 500 What?
[2017-09-14 12:17:03] 4> MODE READER
[2017-09-14 12:17:03] 4< 201 news-1.free.fr (1-2) NNRP Service Ready - newsmaster@proxad.net (no posting)
[2017-09-14 12:17:03] Connected to news.free.fr. Posting is NOT ok.

Well the issue comes with the news server not neomut i think.
Thanks :)

**Comment by gahr** [comment]
Alright, the server doesn't support CAPABILITIES. Do you have anything else in the config? Cause I go through anyway:
```
 15 [2017-09-14 10:53:51] Connected to news.free.fr:119 on fd=7
 16 [2017-09-14 10:53:51] 7< 200 news-1.free.fr (4-2) NNRP Service Ready - newsmaster@proxad.net (posting ok)
 17 [2017-09-14 10:53:51] 7> CAPABILITIES^M
 18 [2017-09-14 10:53:51] 7< 500 What?
 19 [2017-09-14 10:53:51] 7> MODE READER^M
 20 [2017-09-14 10:53:51] 7< 480 Authentication required for command
 21 [2017-09-14 10:53:51] Connected to news.free.fr. Posting is ok.
 22 [2017-09-14 10:53:52] 7> STAT^M
 23 [2017-09-14 10:53:52] 7< 480 Authentication required for command
 24 [2017-09-14 10:53:52] nntp_auth: available methods: (null)
 25 [2017-09-14 10:53:52] nntp_auth: trying method USER
 26 [2017-09-14 10:53:52] Authenticating (USER)...
 27 [2017-09-14 10:53:52] 7> AUTHINFO USER user@example.org^M
 28 [2017-09-14 10:53:52] 7< 381 PASS required
 29 [2017-09-14 10:53:52] 7> AUTHINFO PASS foobar^M
 30 [2017-09-14 10:53:52] 7< 502 news-1.free.fr: Access denied to your node - newsmaster@proxad.net
 31 [2017-09-14 10:53:52] No authenticators available
```

**Comment by flob82** [comment]
No i'm trying with your config file, but exec change-newsgroup not working.
The debian's package seems have less function ?

**Comment by gahr** [comment]
I'm out of ideas for now, sorry...
