### ISSUE TITLE
attachments refused on inline pgp msgs (quick fix possible)

### ISSUE THREAD

**Issue by libBletchley** [neomutt/neomutt#747]
**bug report**

 * Expected behavior

When a PGP/inline msg is composed with an attachment, Mutt should accept the message and attach the file in a MIME fashion.

 * Actual behavior

Mutt gives this error when the user tries to attach a file:
```
Message can't be sent inline.  Revert to using PGP/MIME? ([yes]/no)
```
But in fact that error is making a false statement.  Not using PGP/MIME doesn't imply that MIME is unusable.  Specifically, as a real-world example, both `hushmail.com` and `protonmail.ch` recipients require PGP/inline, but it is still possible to send them encrypted MIME attachments with the ciphertext of the msg body inlined.

This is the workaround, which incidentally proves that it's possible to attach to a PGP/inline msg successfully:
1) encrypt the attachment manually using GPG on the commandline
2) encrypt a textfile for the body of the msg in the same manner.
3)
```
mutt -a "$encrypted_attachment_filename"\
          -i  "$encrypted_msg_body_filename" \
          -e 'unhook *'			    \
          -e 'unmy_hdr *'		    \
          -e 'unset pgp_autoencrypt'	    \
          -e 'set nopgp_autoencrypt'	    \
          -e 'unset pgp_create_traditional' \
          -e "set from = $mail_from"	    \
          -e "set realname = '$realname'"   \
          -s "proof of PGP inline attachment" -- "$hm_or_protonmail_recipient"
```
_Protonmail Warning_: if someone wants to try the above with a protonmail recipient, it's important to make sure that the name of the attachment ends with `.asc`, `.gpg`, or `.pgp`, otherwise protonmail will not treat the msg properly (that's a protonmail bug).

_Hushmail Warning_: Sadly there is also a bug in hushmail, whereby hushmail fails to strip off the file extension.  So if the attachment is named `foo.pdf.asc`, it should be improperly renamed to `foo.pdf` before sending to a hushmail recipient.

_To developers_: As far as implementation of this feature goes, it should probably just use the proper filename extension, and leave the hushmail problem for Hush Communications to fix.
 * Steps to reproduce

Compose a PGP inline msg, attach a file, and try to send.

 * Used program versions
Mutt 1.5.23
 * Operating System and its version
Jessie

**Why it's a bug**
Some will be tempted to call this an enhancement rather than a bug.  I intend to call it a bug because the error message is a lie.  Even if PGP inline attachment capability is not implemented, the error message should at least change to something like "sorry, we could do this but it's not implemented".

**Quick fix**
The quick fix is to simply change the error msg to be accurate.  Then the bulk of this request can be treated as an enhancement.  If this option is taken, I suggest the error msg link to this bug report so users can learn about the workaround.

**Comment by libBletchley** [comment]
For reference, this is what it looks like on the receiving side when sending an attachment to a protonmail user using PGP/MIME: 
![protonmime](https://user-images.githubusercontent.com/18015852/32510161-ed53ba94-c3ef-11e7-91a8-eff362596f73.png)

**Comment by gahr** [comment]
`<only-half-joking>` perhaps we should just drop support for inline pgp altogether (deemed deprecated, wrong, evil, a loooong time ago) and stop worry? `</only-half-joking>`

**Comment by libBletchley** [comment]
PGP/MIME is quite old.. I don't get why a new project like protonmail would start off using old standards.  I think it was only 2 yrs ago that they became PGP/MIME compliant for msgs w/out attachments.
