### ISSUE TITLE
Forwarding attachment causing segfault in 20170907

### ISSUE THREAD

**Issue by timorunge** [neomutt/neomutt#749]
# **bug reports**

## Expected behavior

Forwarding attachments should work and not cause a segfault; problem was introduced in 20170907. Release 20170714 (fae981c4db274f810a980ec803503b9da5d5e6ca) is working fine.

## Actual behavior

Forwarding an attachment causes an segfault. 

## Steps to reproduce

Try to FWD an attachment. 

## Used program versions

Neomutt 20170907 (4dfb37183cf33b5ed76e213d009a797dd713738d)

## Operating System and its version

macOS Sierra - 10.12.6 (16G29).

**Comment by flatcap** [comment]
> Release 20170714 (fae981c) is working fine.

Thanks for the report.

If you're happy building your own neomutt, please can you give the master branch a test.
I found and fixed a bug (a day after the release) that broke resending/bouncing.

**Comment by timorunge** [comment]
Thanks!
I can confirm that running 659cd2d is working fine.

**Comment by flatcap** [comment]
Thanks.  Time for another release :-)

**Comment by protist** [comment]
FWIW I can confirm that this bug is present in 20170907 and fixed by master ad75ef17 , in Arch Linux too. Thank you!

**Comment by flatcap** [comment]
Fixed in: 659cd2d
