### ISSUE TITLE
mutt-1.6.2 + neomutt-20160709, Gentoo patchset fails to compile with --disable-sidebar

### ISSUE THREAD

**Issue by grobian** [neomutt/neomutt#75]
```
clang -DPKGDATADIR=\"/Users/fabian/Gentoo-10.10/usr/share/mutt\" -DSYSCONFDIR=\"/Users/fabian/Gentoo-10.10/etc/mutt\" -DBINDIR=\"/Users/fabian/Gentoo-10.10/usr/bin\" -DMUTTLOCALEDIR=\"/Users/fabian/Gentoo-10.10/usr/share/locale\" -DHAVE_CONFIG_H=1 -DPREFIX=\"/Users/fabian/Gentoo-10.10/usr/..\" -I.  -I. -I. -I./imap -I/Users/fabian/Gentoo-10.10/usr/include/gpgme -I/Users/fabian/Gentoo-10.10/usr/include -Iintl -I/Users/fabian/Gentoo-10.10/usr/include -I/Users/fabian/Gentoo-10.10/usr/include// -I./intl  -Wall -pedantic -Wno-long-long -march=native -O2 -pipe -c -o signal.o signal.c
sendlib.c:2396:53: error: use of undeclared identifier 'SidebarWidth'
    mutt_FormatString (cmd, sizeof (cmd), 0, COLS - SidebarWidth, NONUL...
                                                    ^
1 error generated.
```
this is with --disable-sidebar

tracking this here, need to look into it later.

**Comment by grobian** [comment]
crossref: https://bugs.gentoo.org/show_bug.cgi?id=588460

**Comment by flatcap** [comment]
Sorry, I don't test NeoMutt as much as I'd like, but the build...  I run thousands of test builds.
This [build-fix.diff.txt](https://github.com/neomutt/neomutt/files/356001/build-fix.diff.txt) will help.
I'll integrate it into the patch-sets shortly.

**Comment by flatcap** [comment]
I've pushed a fix: a631572
Let me know if you need anything else doing.

**Comment by grobian** [comment]
thanks, care if I tag neomutt-20160710 and use that to fix our ebuilds?

**Comment by flatcap** [comment]
> care if I tag neomutt-20160710 and use that to fix our ebuilds?

No problem

**Comment by grobian** [comment]
done, thanks again for looking into it before I could :)
