### ISSUE TITLE
Leaky notmuch abstraction: Files get moved to new/

### ISSUE THREAD

**Issue by julian-klode** [neomutt/neomutt#750]
The notmuch abstraction relies a bit on maildir support, but in contrast to normal maildirs does not necessarily rely on flags in filenames, instead they are reported as tags. For example, the "unread" tag sets MUTT_READ to 0. There also is no difference between new and old emails, as we generally don't have a label for that.

Now, despite using labels to indicate read state, and not even having a difference between new and old, neomutt still moves files marked as new (not having unread tag) from cur/ to new/. This seems unnecessary and confusing.

The decision seems to be made in rename_maildir_filename() in mutt_notmuch.c which has:

  snprintf(newpath, newsz, "%s/%s/%s%s", folder,
           (h->read || h->old) ? "cur" : "new", filename, suffix);

But I don't see h->old ever being true, despite emails being stored in cur/ at the moment.

**Comment by julian-klode** [comment]
Although there might be other places this is happening, I'm not entirely sure, this one only seems to be called when syncing duplicates?

**Comment by flatcap** [comment]
That function has been in our notmuch code since the beginning.
@karelzak (notmuch author): Do you remember why the files are renamed?

/cc @neomutt/notmuch-users
