### ISSUE TITLE
smarten send-hook to avoid quiet failures when autoedit is set

### ISSUE THREAD

**Issue by libBletchley** [neomutt/neomutt#753]
**feature request**

 * Why do you not like the current state?

When someone has `autoedit` set, `send-hook` is _quietly_ rendered useless.  There is no feasible and sensible use case for a `send-hook` to quietly coexist with `autoedit` set.  Users get stung, because it's a bizarre limitation that is not communicated to the user at the time the behavior manifests.  The user will spend some time being baffled as to why their `send-hook` fails to execute, which requires digging into the manual.

 * What would you like to see to change?

*possible fix 1*
The muttrc parser should give a warning or error if it encounters a `send-hook` after `autoedit` is set.  And likewise in the other sequence, if `autoedit` is set when at least one `send-hook` already exists, the user should get a warning or error.

*possible fix 2*
Smarten mutt to know that when `autoedit` is set, send-hook must execute after the first edit operation and not subsequent edits.

**Comment by gahr** [comment]
I might be missing something obvious, but isn't `send2-hook` what you're looking for?

**Comment by libBletchley** [comment]
> I might be missing something obvious, but isn't send2-hook what you're looking for?

If the `send2-hook` could replace `send-hook`, then I would call for the removal `send-hook`.  But this bug report was inspired by the need to execute something exactly one time, in this case in particular:

  https://github.com/neomutt/neomutt/issues/732#issuecomment-329236463

It may be only rare corner cases for which `send-hook` exists (in light of `send2-hook`), but the more significant problem is that mutt accepts incompatible settings w/out warning, leaving users baffled, getting unexpected behavior.

Your question does inspire another thought: suppose mutt could pass a msg id on the CLI of this call:
```
set signature="~/scripts/mutt_counter_alice.sh <msg id>|"
```
then perhaps the script could be sophisticated enough to only advance the counter for new msg id's, which would then have the effect of a one-time executed `send-hook`.  I've had other cases in the past where mutt shells to run something, and I would have liked to pass along some info about the msg, but had to do without because, AFAIK, it's not possible.  Or is it?
