### ISSUE TITLE
Unexpected query result when $mbox_type is set to Maildir

### ISSUE THREAD

**Issue by floand** [neomutt/neomutt#754]
The command line query:

`neomutt -n -F /dev/null -m Maildir -Q mbox_type`

should print `mbox_type=Maildir` instead of `mbox_type=Folder` because the latter isn’t
a valid mailbox format and cannot be used as such.

This behaviour probably exists since commit f6208feb3f5d5f2308f599a9b2a137a7e0478285 and I noticed that the above
query works as expected with the patch below.

```diff
diff --git a/init.c b/init.c
index 5d4f8507..4618b812 100644
--- a/init.c
+++ b/init.c
@@ -2841,7 +2841,7 @@ static int parse_set(struct Buffer *tmp, struct Buffer *s, unsigned long data,
             p = "MH";
             break;
           case MUTT_MAILDIR:
-            p = "Folder";
+            p = "Maildir";
             break;
           default:
             p = "unknown";
@@ -3914,7 +3914,7 @@ int var_to_string(int idx, char *val, size_t len)
         p = "MH";
         break;
       case MUTT_MAILDIR:
-        p = "Folder";
+        p = "Maildir";
         break;
       default:
         p = "unknown";
```

**Comment by flatcap** [comment]
Thanks, @floand 
That's my fault.  I've been trying to sort out the naming of globals.
I need to be a bit more careful with my search'n'replaces :-)
