### ISSUE TITLE
queue.h: inclusion of sys/cdefs.h prevents compilation on musl libc.

### ISSUE THREAD

**Issue by hanetzer** [neomutt/neomutt#755]
As stated in the title. Last version I had that compiled on musl libc was 'NeoMutt 20170714 (1.8.3)'.
I'd give you a build failure log, but its just 'sys/cdefs.h: no such file or directory.'

I see that queue.h you ship is the bsd one, right? why not use the system's sys/queue.h, which afaict
is largely equivalent, and is identical on both my musl and glibc rootfs's, unless I'm missing something
it should do what you need.

**Comment by gahr** [comment]
Code was merged.
