### ISSUE TITLE
index_format %{fmt} shows always UTC date and time

### ISSUE THREAD

**Issue by riesebie** [neomutt/neomutt#757]
* **bug reports**

    * Expected behavior
      `%{fmt}` shows the date and time of the message is converted to sender's time zone
    * Actual behavior
      `%{fmt}` shows always UTC date and time      
    * Steps to reproduce
       `set index_format="%3C %Z  %{%d.%m.%y  %H:%M}   %-30.30n (%3l) %s"`
    * Used program versions
       neomutt-20170912
    * Operating System and its version
      Linux 4.13.2

**Comment by riesebie** [comment]
20170714 seems to show the correct date and time, though.

**Comment by flatcap** [comment]
Thanks @riesebie 
If you have the time to bisect that'd really be appreciated.

**Comment by riesebie** [comment]
117276d21ef6bcc0520007c0a7cd9275857498dc is the first bad commit                                                                                                                                     
commit 117276d21ef6bcc0520007c0a7cd9275857498dc                                                                                                                                                      
Author: Richard Russon <rich@flatcap.org>
Date:   Wed Aug 9 17:17:51 2017 +0100

    lib: move some date/string functions

**Comment by riesebie** [comment]
BTW
[fmt]  shows the date and time of the message is converted to the local time zone -> correct
(fmt) shows the local date and time when the message was received. -> correct
\<fmt\> empties the whole index -> **_not_** correct, of course.

According to the manual \<fmt\> has to show the local time.

**Comment by flatcap** [comment]
> \<fmt\> empties the whole index -> not correct, of course.

Ah, that was 're-purposed' by the [nested-if feature](https://www.neomutt.org/feature/nested-if).

**Comment by riesebie** [comment]
> Ah, that was 're-purposed' by the [nested-if feature.](https://www.neomutt.org/feature/nested-if)

Ok, so should we remove the respective line in the maual?

**Comment by flatcap** [comment]
[[issue/757](https://github.com/neomutt/neomutt/tree/issue/757)] should fix the problem.
I've updated the docs, too.

**Comment by riesebie** [comment]
No, see  [scrot](https://www.lxtec.de/debarchiv/UTC.png). Index time should be 22:46 not 21:46.

**Comment by riesebie** [comment]
Uuups, my fault. wrong build. Sorry @flatcap  :-)

**Comment by riesebie** [comment]
All good.
