### ISSUE TITLE
default color not utilized for indicator

### ISSUE THREAD

**Issue by libBletchley** [neomutt/neomutt#758]
**possible bug**

This is a muttrc excerpt:
```
color index       brightyellow  red     "(~h X-Spamgourmet:.*last.one|~h X-TrashMail-Forwards:.*0.of) ~N"
color indicator   brightwhite  default
```
 * Expected behavior
When the indicator is positioned on a message that matches the first color spec, the default background is documented to be "transparent", which implies that the red background color would show.

 * Actual behavior
The background color is black.

 * Steps to reproduce
Receive a msg with this header
```
X-Spamgourmet: (foo: message 3 of 3 -last one!-)
```
Make sure it's marked as _new_ and position the indicator over it.

 * Used program versions
mutt 1.5.23

 * Operating System and its version
Jessie

**Comment by flatcap** [comment]
Sorry for the slow reply.
Unfortunately this is a limitation of the colours in (neo)mutt.
"default" doesn't mean transparent (like it would in vim), it just means the normal colour.
The colour of the item "underneath" is lost.
