### ISSUE TITLE
XDG specification

### ISSUE THREAD

**Issue by pickfire** [neomutt/neomutt#76]
A lot of applications have recently decide to follow the XDG Base Directory Spectification. Will neomutt plan to support it? Full spectification: http://standards.freedesktop.org/basedir-spec/latest/

**Comment by darnir** [comment]
I would be interested in seeing this support land in NeoMutt. Hopefully mutt upstream accepts it as welll

**Comment by pickfire** [comment]
@flatcap What about asking in mutt ml to see if they are against it?

**Comment by flatcap** [comment]
I'm not against it, but I think getting Mutt to change will be tough.

> asking in mutt ml

If you want an honest opinion, there, I suggest asking yourself.
Don't mention NeoMutt, or me.  I'd be interested in the responses you get.

As for the change... It shouldn't be too hard.  I suppose you just put the XDG directories first any time you search for config/data.

**Comment by pickfire** [comment]
Haha, yeah, I think they will keep the tradition.

**Comment by mhinz** [comment]
I try to whip up a first patch for XDG support in the next hours.

**Comment by flatcap** [comment]
merged

**Comment by riesebie** [comment]
What is the real advantage to follow those _X_D_esktop_G_roup specifications? I am running neomut on machines which never saw any X-app. I am using my .mutt dir as well as .vim and .tmux dirs. So why should one dive one or two dirs deeper?

**Comment by flatcap** [comment]
> What is the real advantage to follow those _X_D_esktop_G_roup specifications?

Don't know.  Next question :-)

If all my config files are in one directory, it's easy to use version control.
Or I could share one config dir over several accounts/machines.

As for why we've adopted it.  Someone asked for it.  It was simple to achieve. Someone else wrote the code.

> So why should one dive one or two dirs deeper?

You don't need to.  NeoMutt will continue to look for its config files in all the old places.
I've update [the docs](http://www.neomutt.org/manual/configuration.html#configuration-files) to show the order in which NeoMutt searches for config files.

**Comment by pickfire** [comment]
@riesebie Well, no wants like to have their home folder flooded with hidden configurations (100+), a seperate configuration would make it looks tidier.

**Comment by riesebie** [comment]
@flatcap Well, I have all my neomutt config in a git repo placed in $HOME/.mutt. Thanks for updating the docs ;-)

@pickfire To be honest, my $HOME isn't a catwalk. My mutt, tmux, zsh, vim configs are all seperated. So what? Most GUI configs are stored in XDG_CONFIG's but mutt?

**Comment by mhinz** [comment]
@riesebie Not sure why you're mentioning GUIs all the time. :-) Looking at my `.config` I see wide-spread programs like htop, git, neovim, fish, etc. And now neomutt!

The reasons were already mentioned: 1) Not cramming up `$HOME` and 2) version control (without the need of extra programs to set up symlinks on a new box etc.

**Comment by pickfire** [comment]
@riesebie I think I understand what you mean, `mutt` isn't a graphical app, but the **XDG_CONFIG_HOME** isn't just about graphical apps. If it was me, I rather my `~/.config` be 69 folders/files than adding them together in `$HOME` to become 110 (from what I counted).

Well, the `$HOME/.mutt` is still in one of the path that neomutt searches. The old settings is preserved so no worries.

**Comment by riesebie** [comment]
All this pretty much sounds like:
"My neighbor sweeps the pavement twice a week so I have to do so!"
I prefer $HOME/.mutt/ ;-))

**Comment by iKarith** [comment]
Theoretically configuration portability is also an advantage of the XDG basedir spec.  However, I'd argue NeoMutt still falls a little short on this because while XDG environment variables are searched for mutt/config (rather than mutt/muttrc which I'd argue would've made more sense), you must still specify full paths to commands like source.  That means if for some reason you have a machine whose config dir is not $HOME/.config, your elegant and modular NeoMutt configuration is going to be hard-coding paths or trying to run embedded shell scripts to determine where your config files are.

Merely an observation.  I'm unsure if resolving this quibble is actually a good idea or not.

**Comment by flatcap** [comment]
hi @iKarith 

> ... your elegant and modular NeoMutt configuration is going to be hard-coding paths or trying to run embedded shell scripts to determine where your config files are.

Yes, I know.  The solution is quite simple (but not yet implemented).
`source` commands should be relative:
- Run from NeoMutt -> relative to NeoMutt's current directory
- Run from a file -> relative to that file's location.

Fortunately, this change shouldn't affect existing config files.

**Comment by iKarith** [comment]
Hi @flatcap,

Is this functionality for `source` planned, or simply being considered?

For the time being (since I'm building a NeoMutt configuration from scratch), I've done this:

```
set my_cfg_dir=`echo "${XDG_CONFIG_HOME:-$HOME/.config}/neomutt"`
```

It works.  It seems that a lot of the things added to NeoMutt exist to make that kind of thing unnecessary, which is the only reason I brought it up.

**Comment by flatcap** [comment]
Hi @iKarith 

> Is this functionality for source planned, or simply being considered?

Considered.
We have millions of ideas, but few coders.
It's quite easy to do, but everyone seems busy, atm (I can't imagine why :-)

**Comment by iKarith** [comment]
What could *possibly* be more important this time of the year, seriously?

I do wonder, though, if having the behavior of source change based on interactive vs. muttrc usage is entirely the best plan.  It makes sense to do it, and I certainly won't object to having less embedded subshell in my config, but I can also see a case for violating the principle of least surprise.

There's a precedent for + and = at the start of filename paths to make them relative to `$folder`.  If I had a brilliant suggestion of another character that could be relative to a $config_dir which defaulted to ${XDG_CONFIG_HOME:-$HOME/.config}, I'd offer it.
