### ISSUE TITLE
notmuch: query syntax not checked and folder URIs silently truncated

### ISSUE THREAD

**Issue by chschneide** [neomutt/neomutt#765]
I encountered two unexpected and probably connected behaviours with notmuch:

notmuch queries both in vfolder-from-query and in virtual-mailboxes query strings do not seem to be properly checked for syntax errors.  For example, there is no error message, when parentheses are not matched or a query ends with "and".

Examples for vfolder-from-query that I would expect to print an error message.  Instead, the first one delivers nothing and the second one lists all of my spam mails:
"tag:spam and"
"(tag:spam"

When using vfolder-from-query or creating "virtual-mailboxes" with very long queries, probably > 255 characters(???), the query seems to be truncated and the rest of the query string is ignored.  Together with the abovementioned problem, this leads to either empty virtual mailboxes or virtual mailboxes with unexpected content.

Example for vfolder-from-query
"tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam and tag:spam"

tested with: neomutt 1.7.2 (debian stretch) and 1.8.3 (debian buster)

**Comment by chschneide** [comment]
The problem has gotten a lot worse in more recent releases, as the URI for a notmuch query became a lot longer, when extra strings were added.  After some digging, I believe to have found the (or at least one) point in the code, where the notmuch URI is truncated:

mutt_notmuch.c -> nm_normalize_uri():
strncpy(new_uri, buf, new_uri_sz) is called with new_uri_sz == 256.

The only time nm_normalize_uri() is called is in buffy.c, where the buffer size is determined by _POSIX_PATH_MAX.

Increasing the buffer size for this occurance does not seem to be sufficient to solve the notmuch query problem.  When mutt queries the number of messages in virtual folders etc., some truncation appears to happen again.  Globally increasing _POSIX_PATH_MAX was also unsuccessful.

A bigger problem is that the use of strncpy with potentially too large source string leads to copies that are not null-terminated anymore, which can introduce all sorts of extra problems.

**Comment by flatcap** [comment]
Hi @chschneide 
Sorry I missed you on IRC.

A while back, someone offered to fix this, but then didn't get back to me.
More recently, I had a quick look -- increasing some string lengths.
(this wasn't in a compile-able state)

This shouldn't be hard to do, but it'll require patience to read through a **lot** of code to make sure that the strings aren't truncated anywhere else.

**Comment by chschneide** [comment]
Hi Richard,

Thanks for your email.  I also looked through some code and it appears 
that only the notmuch code has problems!?  But it is true that a lot of 
code needs to be reviewed and fixed.

I am not really a C programmer but program mainly in C++, so this might 
not be anything the core developers would consider:  Why aren't all the 
strings protected against overflows?  In a conceptually simple case, you 
could track the string length and max. length by using appropriate 
structs (rebuilding somewhat the C++ std::string).  There will be a 
tiny performance penalty, but considering the (security) problems that 
C strings cause all the time it should be worth it!?

Christian

**Comment by flatcap** [comment]
Hi Christian,

> it appears that only the notmuch code has problems!?

They show up most easily in notmuch.
If you were to move you email to a **very** deep directory, then that would fail too.

> Why aren't all the strings protected against overflows?

Mutt (the basis for NeoMutt) was written over twenty years ago.
Unfortunately, the code hasn't moved with the times -- we're trying to sort that.

> you could track the string length and max. length
> (rebuilding somewhat the C++ std::string).

We've considered a lot of ideas, like this.
Changing **one** string in **one** struct would mean changing a lot of code
and would probably require us to change other structs, etc.

> it should be worth it!?

Certainly, but it's a huge job and the team of _developers_ is quite small.
Currently, we're modernising small pieces of code that we can isolate and test.
We're working our way into the tangled heart of NeoMutt :-)

**Comment by flatcap** [comment]
I've trawled through the code replacing all the small buffers (#1229)

No promises, but...
The new branch `devel/buffer-size` will probably (I'm not a Notmuch user) fix this problem.

If you have time, please could you give it a try.
