### ISSUE TITLE
first time mailbox opening with LMDB is awfully slow

### ISSUE THREAD

**Issue by 4nd3r** [neomutt/neomutt#77]
not sure if bug and didn't want to spam to #68.

mailbox size: 202 items and 3 megabytes with bodies, server side (imap)
tokyocabinet 1.4.48: less than second
Berkeley DB 5.3.28: less than second
lmdb 0.9.14: ~6 seconds

it gets worse with larger mailboxes, 3 seconds vs 3 minutes with ~3000 items etc.

**Comment by flatcap** [comment]
Thanks.  That's some good testing.
The 'L' apparently stands for "lightning" -- perhaps we should sue :-)

Are there any other clues?  Is it using a **lot** of memory?

I only did a bit of light testing.  I'll create something bigger.
Let me know if you discovery anything else.

**Comment by 4nd3r** [comment]
opening mailbox with 4060 items.

LMDB:
<pre>
$ cat /proc/12814/status | grep Vm
VmPeak:  1107572 kB
VmSize:  1107572 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:     32388 kB
VmRSS:     32388 kB
VmData:    16368 kB
VmStk:       136 kB
VmExe:       744 kB
VmLib:      5156 kB
VmPTE:       152 kB
VmPMD:        16 kB
VmSwap:        0 kB
</pre>
when finished, `VmSize` tropped to normal (59120 kB).
I think this behaviour is normal, since it's lmdb (M stands for Memory, right).

BDB goes fast, both VmPeak and VmSize stay around 60000 kB.

> The 'L' apparently stands for "lightning" -- perhaps we should sue :-)

you don't want wrath of Howard Chu upon you! openldap & co upstream is quite... well, let's say they aren't always friendly. probably hit back that lmdb integration in mutt is bad, you don't understand how lmdb works and someone should learn to code or something.

**Comment by P-EB** [comment]
I tried right now with 8k mails, it took little time.

Can you give me steps to reproduce your issue?

**Comment by 4nd3r** [comment]
not many special steps here, really. built with `--enable-hcache --with-lmdb`, deleted existing cache files and opened quite a big mailbox over IMAP. SSD, mail server in the same network. and I use Debian Stable aka Jessie. maybe something with -dev package versions? Jessie ships with `0.9.14-1`.

**Comment by P-EB** [comment]
Thanks. I'll do some test on a jessie server.

**Comment by P-EB** [comment]
I'm sorry, I'm unable to reproduce your issue with my imap INBOX (9k mails). :(

**Comment by neverpanic** [comment]
See https://dev.mutt.org/trac/ticket/3691#comment:4 for a possible explanation for poor cache build speed.

**Comment by P-EB** [comment]
Hey,

I saw that there was one transaction per write, but I was unable to see the real overhead. (My server has very fast disks, and my computer uses a SSD, I guess that can explain).

I'll try to think about a patch for this issue. :)

**Comment by P-EB** [comment]
I had a look to your patch, it looks nice. But wouldn't we be more efficient if we rewrote the cache API?

Cheers

**Comment by neverpanic** [comment]
Yes, but rewriting the cache API would mean we'd have to adjust all the places and patches that use it, such as maildir support, IMAP support, POP support, the NNTP patch, etc. If we do that without a clear commitment from upstream mutt to accept this patch later on, we'll create an environment where there suddenly need to be two versions of all patches, which is what I'd like to avoid.

**Comment by P-EB** [comment]
I understand.

**Comment by neverpanic** [comment]
@4nd3r can you try again with f05c6df4a73a62c4cb6e3ae76957ebe605da42c9 from the devel/lmdb branch to see if that improved things?

**Comment by 4nd3r** [comment]
@neverpanic thank you very much!

first open is now really fast and faster than others when opening mailbox over IMAP with 12k+ messages.

also reading from cache also seems to be faster.

**Comment by flatcap** [comment]
#### This bug is now fixed and will be in the next release of NeoMutt.

**Comment by gahr** [comment]
Too bad I didn't see this report before.. mind to @ me if anybody else comes up with lmdb? Thanks!

**Comment by flatcap** [comment]
Thanks.  Will do.
