### ISSUE TITLE
Null pointer dereference in mbox_to_udomain()

### ISSUE THREAD

**Issue by jwilk** [neomutt/neomutt#778]
neomutt crashes on this mbox:

    $ printf 'From Wed Nov 0 0: 0\nTo:=??B??=:\n' > nullptr.mbox
    $ mutt -R -f nullptr.mbox >/dev/null 2>&1
    Segmentation fault

GDB says it's a null pointer dereference:

    (gdb) up
    #1  0x800629bd in mbox_to_udomain (mbx=0x801d2dc8 "", user=0xbfffc64c, domain=0xbfffc648) at mutt_idna.c:61
    61        p = strchr(buff, '@');
    (gdb) print buff
    $1 = 0x0
    (gdb) bt
    #0  __strchr_sse2_bsf () at ../sysdeps/i386/i686/multiarch/strchr-sse2-bsf.S:97
    #1  0x800629bd in mbox_to_udomain (mbx=0x801d2dc8 "", user=0xbfffc64c, domain=0xbfffc648) at mutt_idna.c:61
    #2  0x800630a6 in mutt_addr_for_display (a=0x801d0930) at mutt_idna.c:305
    #3  0x800a2e5c in mutt_get_name (a=0x801d0930) at sort.c:118
    #4  0x8003dab9 in make_from (env=0x801d2d48, buf=0xbfffc6e8 "Oct 31", len=1024, do_lists=1) at hdrline.c:304
    #5  0x8003ee9e in hdr_format_str (dest=0xbfffd234 "\016\034", destlen=1024, col=16, cols=180, op=76 'L', src=0xbfffd040 " (%?l?%4l&%4c?) %s", prefix=0xbfffd634 "-15.15", ifstring=0xbfffd1b4 "", elsestring=0xbfffd134 "", data=3221215044, flags=(MUTT_FORMAT_MAKEPRINT | MUTT_FORMAT_ARROWCURSOR | MUTT_FORMAT_INDEX)) at hdrline.c:925
    #6  0x80061a4f in mutt_expando_format (dest=0xbfffd7e4 "\016\"   1\016\033 \016\035N F\016\033 \016 Oct 31\016\033 \b\214◈\315\004", destlen=1023, col=16, cols=180, src=0xbfffd040 " (%?l?%4l&%4c?) %s", callback=0x8003dfb0 <hdr_format_str>, data=3221215044, flags=(MUTT_FORMAT_MAKEPRINT | MUTT_FORMAT_ARROWCURSOR | MUTT_FORMAT_INDEX)) at muttlib.c:1355
    #7  0x8004055a in _mutt_make_string (dest=0xbfffd7e4 "\016\"   1\016\033 \016\035N F\016\033 \016 Oct 31\016\033 \b\214◈\315\004", destlen=1024, s=0x801c7a58 "%4C %Z %{%b %d} %-15.15L (%?l?%4l&%4c?) %s", ctx=0x801c2968, hdr=0x801ce9e0, flags=(MUTT_FORMAT_MAKEPRINT | MUTT_FORMAT_ARROWCURSOR | MUTT_FORMAT_INDEX)) at hdrline.c:1358
    #8  0x80028abc in index_make_entry (s=0xbfffd7e4 "\016\"   1\016\033 \016\035N F\016\033 \016 Oct 31\016\033 \b\214◈\315\004", l=1024, menu=0x801d4e90, num=0) at curs_main.c:667
    #9  0x80057051 in menu_make_entry (s=0xbfffd7e4 "\016\"   1\016\033 \016\035N F\016\033 \016 Oct 31\016\033 \b\214◈\315\004", l=1024, menu=0x801d4e90, i=0) at menu.c:283
    #10 0x80057479 in menu_redraw_index (menu=0x801d4e90) at menu.c:357
    #11 0x800290db in index_menu_redraw (menu=0x801d4e90) at curs_main.c:872
    #12 0x80029a30 in mutt_index_menu () at curs_main.c:1072
    #13 0x8005329d in main (argc=1, argv=0xbffff674, env=0xbffff688) at main.c:936

Tested with git master (9dc0ee067b71fc7678128bebe0b2fd30c9b3dd2d).

Found using [American Fuzzy Lop](http://lcamtuf.coredump.cx/afl/).

**Comment by flatcap** [comment]
Thanks again @jwilk.
Keep them coming :-)
