### ISSUE TITLE
Null pointer dereference in mutt_substrdup()

### ISSUE THREAD

**Issue by jwilk** [neomutt/neomutt#780]
NeoMutt crashes on this message:

    $ printf 'From Wed Nov 0 0: 0\n0000:%879d\0%169d\0%2160d\0%2773d\0%148d\n0\n:' 0 0 0 0 0 > nullptr.mbox
    $ neomutt -e 'unignore *' -R -f nullptr.mbox
    <press Enter to view the message>
    Segmentation fault

GDB says it's a null pointer dereference in mutt_substrdup():

    (gdb) up
    #1  0x801346d5 in mutt_substrdup (begin=0x807e7001 "", end=0x807e7000 ":") at string.c:347
    347       memcpy(p, begin, len);
    (gdb) print p
    $1 = 0x0
    (gdb) bt
    #0  __memcpy_sse2_unaligned () at ../sysdeps/i386/i686/multiarch/memcpy-sse2-unaligned.S:582
    #1  0x801346d5 in mutt_substrdup (begin=0x807e7001 "", end=0x807e7000 ":") at string.c:347
    #2  0x8010333e in write_one_header (fp=0x807e5ef0, pfxw=0, max=1, wraplen=180, pfx=0x0, start=0x807e6ffe "0\n:", end=0x807e7000 ":", flags=262294) at sendlib.c:1923
    #3  0x801035f5 in mutt_write_one_header (fp=0x807e5ef0, tag=0x0, value=0x807e7008 "0000:", '0' <repeats 195 times>..., pfx=0x0, wraplen=180, flags=262294) at sendlib.c:2004
    #4  0x80089912 in mutt_copy_hdr (in=0x807df868, out=0x807e5ef0, off_start=0, off_end=6162, flags=262294, prefix=0x0) at copy.c:324
    #5  0x80089a5b in mutt_copy_header (in=0x807df868, h=0x807df9c8, out=0x807e5ef0, flags=262294, prefix=0x0) at copy.c:387
    #6  0x8008a3e1 in _mutt_copy_message (fpout=0x807e5ef0, fpin=0x807df868, hdr=0x807df9c8, body=0x807df570, flags=76, chflags=262294) at copy.c:650
    #7  0x8008a8ad in mutt_copy_message (fpout=0x807e5ef0, src=0x807d3950, hdr=0x807df9c8, flags=76, chflags=262294) at copy.c:768
    #8  0x8007f4e1 in mutt_display_message (cur=0x807df9c8) at commands.c:169
    #9  0x80093a07 in mutt_index_menu () at curs_main.c:2152
    #10 0x800ba29d in main (argc=1, argv=0xbf9627f4, env=0xbf962810) at main.c:936

Tested with git master (9dc0ee067b71fc7678128bebe0b2fd30c9b3dd2d).

Found using [American Fuzzy Lop](http://lcamtuf.coredump.cx/afl/).

**Comment by flatcap** [comment]
Thanks, @jwilk.
More please :-)
