### ISSUE TITLE
Out-of-bounds read in mutt_display_message()

### ISSUE THREAD

**Issue by jwilk** [neomutt/neomutt#784]
Build NeoMutt with `-fsanitize=address` and run:

    $ printf 'From Wed Nov 0 0: 0\nContent-Type:*\n' > oob.mbox
    $ neomutt -R -f oob.mbox

Then press Enter to view the message.
AddressSanitizer reports:

    =================================================================
    ==25915==ERROR: AddressSanitizer: global-buffer-overflow on address 0x803c40a4 at pc 0x80138b39 bp 0xbf87ab78 sp 0xbf87ab6c
    READ of size 4 at 0x803c40a4 thread T0
        #0 0x80138b38 in mutt_display_message .../neomutt/commands.c:87
        #1 0x801687e5 in mutt_index_menu .../neomutt/curs_main.c:2152
        #2 0x801c4093 in main .../neomutt/main.c:936
        #3 0xb6f58285 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18285)
        #4 0x80113ae0  (.../neomutt/neomutt+0x24ae0)
    
    0x803c40a4 is located 60 bytes to the left of global variable 'sysexits_h' defined in 'muttlib.c:1827:3' (0x803c40e0) of size 136
    0x803c40a4 is located 0 bytes to the right of global variable 'BodyTypes' defined in 'globals.h:347:19' (0x803c4080) of size 36

Tested with git master (9dc0ee067b71fc7678128bebe0b2fd30c9b3dd2d).

Found using [American Fuzzy Lop](http://lcamtuf.coredump.cx/afl/).

**Comment by flatcap** [comment]
Thanks @jwilk.
