### ISSUE TITLE
imap should use fetch BODYSTRUCTURE 

### ISSUE THREAD

**Issue by sileht** [neomutt/neomutt#786]
* Why do you not like the current state?

When you open the pager all attachements are downloaded when usually you just need the first text/plain attachment.

%X in index_format in unusable with IMAP, because it downloads open all attachements of all messages just to get the number of attachements.

* What would you like to see to change?

I would like to use BODYSTRUCTURE and BODY.PEEK[<ID>]. The idea to fill the Body objects tree
without the body->content set. And only set body->content on demand.
"On demand" means: loading the part needed by the pager when you open it, or lading an attachment when you open it in the attachment browser.

NOTE: I already have written the BODYSTRUCTURE parser according the rfc3501 my working branch is here: https://github.com/sileht/neomutt/tree/devel/bodystruct.
It's far to be ready, most of the structure is not kept in memory for now, but the parser have successfully parsed all my mails. I have done that as initial step to ensure I will be able to propose a PR.

**Comment by gahr** [comment]
I would love to see this done, thanks for working on this!

**Comment by sileht** [comment]
I just got %X working this morning :)

**Comment by scottkosty** [comment]
Related to #2004.
