### ISSUE TITLE
digest_collapse seems broken on current devel builds

### ISSUE THREAD

**Issue by fourjay** [neomutt/neomutt#789]
``digest_collapse`` seems to have broken a few devel releases ago

* **bug reports**
    * Expected behavior

v on message digest email shows a list of messages
j and k navigate through the message digest list a message at a time

    * Actual behavior

Tree view is expanded with all the MIME subtypes
j and k navigate through all the message parts rather then advancing from message to message

set ?digest_collapse indicates it is set, but digest is not collapsed
re-setting it does not produce a change. Un setting it does not produce a change

    * Steps to reproduce

I subscribe to several digested mailing lists. A month ago the digest list was collapsed. This started occuring with  more recent devel builds (my distro does not provide neomutt, so I regularly pull from source and rebuild) 

    * Used program versions

 mutt -v
```
NeoMutt 20170907-2-13ff84 (1.9.0)
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.

System: Linux 4.4.87-25-default (x86_64)
ncurses: ncurses 5.9.20140201 (compiled with 5.9)
hcache backends: tokyocabinet

Compiler:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/4.8/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.8 --enable-ssp --disable-libssp --disable-plugin --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --enable-linker-build-id --enable-linux-futex --program-suffix=-4.8 --without-system-libunwind --with-arch-32=i586 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 4.8.5 (SUSE Linux)

Configure options: '--enable-imap' '--with-ssl' '--with-tokyocabinet' '--disable-doc' '--disable-po'

Compilation CFLAGS: -Wall -pedantic -g -O2

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +keywords +limit_current_thread +multiple_fcc +nested_if +new_mail
  +nntp +pop +progress +quasi_delete +regcomp +reply_with_xorig
  +sensible_browser +sidebar +skip_quoted +smtp +status_color +timeout +tls_sni
  +trash

Compile options:
  +bkgdset +color +curs_set -debug +fcntl -flock -fmemopen +futimens
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool -idn -locales_hack -lua
  +meta -mixmaster +nls -notmuch +openssl +pgp +resizeterm -sasl +smime
  +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/mutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: http://www.neomutt.org/
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

    * Operating System and its version

open suse leap 42.3

**Comment by fourjay** [comment]
Should also note that in the digest tree view I *can* collapse an entry with ``v``

**Comment by flatcap** [comment]
Thanks for the report @fourjay 

> I subscribe to several digested mailing lists

Are any of them public?  If so, could you post a sample email somewhere?
(or if it's not too big, rename it to .txt and attach it to this issue)

If you're feeling very generous (and have some time),
you could also `git bisect` the code to narrow down which commit broke things.

Thanks

**Comment by fourjay** [comment]
Here's a short sample (edited out some names and elidided the base64 blobs). Probably unneeded, but it seemed polite. While it's not truly a "public" list, it's not really all that private.

[edited_digest.txt](https://github.com/neomutt/neomutt/files/1342500/edited_digest.txt)

**Comment by flatcap** [comment]
Thanks.  It's always handy to see exactly what the reporter is seeing.
The problem was introduced by the upstream commit:
63accf1f2 Change recvattach to allow nested encryption

**Comment by flatcap** [comment]
@fourjay Please can you give the [[issue/789](https://github.com/neomutt/neomutt/tree/issue/789)] branch a test.  `digest_collapse` should now work.

**Comment by fourjay** [comment]
Yes, this works. Thanks!

**Comment by fourjay** [comment]
I've started seeing this again, more or less as reported before

**Comment by fourjay** [comment]
This is OK, and missattributed (FWIW, a workstation rebuild had me using distro mutt rather then neomutt, I apologize).
