### ISSUE TITLE
Sorting by From address needs improved

### ISSUE THREAD

**Issue by grarpamp** [neomutt/neomutt#790]
Sorting by From needs some options to actually sort by the email address itself, NOT the GECOS field, since there are many "Jane Doe" that are different humans with different addresses, and the current sort and subsort methods make a mess of that. For many neomutt users, the address is canonical in mind, not the more arbitrary GECOS, thus improve handling to match.

There should be means to do this for all possible address fields: envelope-From, body-From, and the first address of the body To / Cc / Bcc .

There should be some options to group multiple addresses together in the same lexical position defined by the first group member, and further sorted by the otherwise prevailing sort order within each group. ie: User knows all these are one human and configures them into one group that would appear in the 'q' position when sorted by address... qjd004@g.h , jd001@a.b , jd002@c.d , adj003@e.f . It may even be useful to give the group definition an artificial "Jane Doe" GECOS field to be used in the index display overriding the actual text of the individual group members, however raw header and message displays would always display the actual text as usual.

There could even be option to sort primary by @domain, then user@ within.

There are some related issues with imparted sorting, and raw presenting, of meta GECOS characters that might also be part of this work... single / double quotes, left / right carets, raw addresses, etc.

Here's the original ticket from mutt four years ago...
https://dev.mutt.org/trac/ticket/3649

**Comment by flatcap** [comment]
Moving this to the long-term wish list.
