### ISSUE TITLE
Integer overflow in mutt_mktime()

### ISSUE THREAD

**Issue by jwilk** [neomutt/neomutt#794]
On 32-bit systems, signed integer overflow in `mutt_mktime()` is possible.
To reproduce, build NeoMutt with `-fsanitize=undefined` and run:

    $ printf 'From Wed Nov 0 0: 200' > intoverflow.mbox
    $ export UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_stacktrace=1
    $ neomutt -R -f intoverflow.mbox 2>&1 >/dev/null | cat
    date.c:276:5: runtime error: signed integer overflow: 68812040 * 60 cannot be represented in type 'long int'
        #0 0x8030208c in mutt_mktime .../neomutt/lib/date.c:276
        #1 0x801c6e41 in is_from .../neomutt/from.c:185
        #2 0x80206bb6 in mbox_parse_mailbox .../neomutt/mbox.c:290
        #3 0x80208e90 in mbox_open_mailbox .../neomutt/mbox.c:458
        #4 0x80229cb2 in mx_open_mailbox .../neomutt/mx.c:480
        #5 0x80202a88 in main .../neomutt/main.c:929
        #6 0xb7089285 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18285)
        #7 0x8015dd70  (.../neomutt/neomutt+0x6ad70)

Tested with git master (0df7d370d81b174e87ca3a29ba3e92e81acd76f1).

Found using [American Fuzzy Lop](http://lcamtuf.coredump.cx/afl/).

**Comment by flatcap** [comment]
It turns out that there was already a check in place to prevent this overflow...
It was just comparing the time against the wrong value.

Thanks, @jwilk.
