### ISSUE TITLE
crash when <pipe-message> on deleted message

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#796]
Steps to reproduce:

1. Open two separate instances of mutt.
2. Open an email in instance 2.
3. In instance 1, delete that email, and sync.
4. In instance 2, do :exec pipe-message
5. For the command to pipe to, put e.g. "echo" and press enter.

Result: SIGSEGV

I can reproduce on recent master (0df7d370 with "neomutt" binary) and with NeoMutt 20170912.

I did a bisect, which led to 4ed2b6f0. Before that commit, when I did the above recipe I would get the following:

> /home/scott/.mail/INBOX/cur/1506565365_2.13864.chro,U=39124,FMD5=7e33449f656h1e6l9m79b29t3f82c57e:2,S: No such file or directory (errno = 2)

Then if I press e.g. "q" to go back to Inbox, I see
Mailbox was externally modified.  Flags may be wrong.

To me, that behavior (of giving the error) makes sense. On current upstream mutt I don't think it gives an error anymore. I think it just doesn't do anything, but doesn't crash.

gdb gives this bt:

```
Thread 1 "neomutt" received signal SIGSEGV, Segmentation fault.
0x0000000000454a47 in snprintf (__fmt=0x4dad56 "%s/%s", __n=256, __s=0x7fffffffabb0 "\001") at /usr/include/x86_64-linux-gnu/bits/stdio2.h:64
64	  return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
(gdb) bt
#0  0x0000000000454a47 in snprintf (__fmt=0x4dad56 "%s/%s", __n=256, __s=0x7fffffffabb0 "\001") at /usr/include/x86_64-linux-gnu/bits/stdio2.h:64
#1  maildir_mh_open_message (msgno=<optimized out>, is_maildir=1, msg=<optimized out>, ctx=<optimized out>, ctx=<optimized out>) at mh.c:1447
#2  0x000000000045cacb in mx_open_message (ctx=ctx@entry=0x7ce550, msgno=112) at mx.c:1201
#3  0x000000000042173e in mutt_copy_message (fpout=0x820ca0, src=0x7ce550, hdr=hdr@entry=0x820b50, flags=0, chflags=16) at copy.c:766
#4  0x0000000000417be3 in pipe_msg (h=h@entry=0x820b50, fp=<optimized out>, decode=decode@entry=0, print=print@entry=0) at commands.c:384
#5  0x0000000000417ca5 in _mutt_pipe_message (h=h@entry=0x820b50, cmd=cmd@entry=0x7fffffffadc0 "copy_message_id", decode=0, print=print@entry=0, 
    split=<optimized out>, sep=<optimized out>) at commands.c:418
#6  0x0000000000418d86 in mutt_pipe_message (h=0x820b50) at commands.c:506
#7  0x000000000046b58e in mutt_pager (banner=banner@entry=0x0, 
    fname=fname@entry=0x7fffffffbe40 "/tmp/neomutt-steph-1000-10495-10518590499035943711", flags=flags@entry=66, extra=extra@entry=0x7fffffffbe10)
    at pager.c:2867
#8  0x0000000000418512 in mutt_display_message (cur=0x820b50) at commands.c:232
#9  0x0000000000427d8d in mutt_index_menu () at curs_main.c:2152
#10 0x0000000000409a16 in main (argc=1, argv=<optimized out>, env=<optimized out>) at main.c:936
(gdb) 
```

**Comment by gahr** [comment]
@scottkosty, thanks for the report. I could reproduce the issue. Could you please test the [devel/issue-796](https://github.com/neomutt/neomutt/compare/devel/issue-796) branch and see whether it fixes the issue for you?

**Comment by scottkosty** [comment]
Thanks for the quick response and for looking into it. I tested devel/issue-796 branch, and I see the same behavior:

```
$ ./neomutt -v | head -n 1
NeoMutt 20170912-49-e713df
$ ./neomutt 
Segmentation fault (core dumped)
```

**Comment by sileht** [comment]
@scottkosty have you get a try to https://github.com/neomutt/neomutt/pull/797

**Comment by scottkosty** [comment]
@sileht thanks for your work on this issue. I just tried the patch and it does not fix the crash for me:

```
$ ./neomutt -v | head -n 1
NeoMutt 20170912-1406-71b7f4
$ ./neomutt 
Segmentation fault (core dumped)
```
