### ISSUE TITLE
sidebar_delim config rename

### ISSUE THREAD

**Issue by 257** [neomutt/neomutt#8]
has this changed from patches that mutt-kz uses? it's not recognized here. (--enable-sidebar _is_ ON).

**Comment by flatcap** [comment]
Yes, it has been renamed to **sidebar_divider_char**
Some of the names were changed to make them clearer (and more like the Mutt names).
The [Sidebar readme](https://github.com/neomutt/neomutt/wiki/sidebar#variables) lists all the variables.

I thought that it was important to fix the names before Sidebar gets merged into Mutt.
Sorry about that.

**Comment by 257** [comment]
thanks for the info.
