### ISSUE TITLE
Notifications infrastructure

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#802]
This issue is to trigger discussion and track the progress in the development of an infrastructure to allow us (developers) to show NeoMutt users general notifications.

These could be of many kinds, including:

* deprecation warnings
* heads-up regarding upcoming features or changes
* calls for testing 
* you name it

**Comment by libBletchley** [comment]
Perhaps warn of incompatible configuration settings, as mentioned here:

https://github.com/neomutt/neomutt/issues/753

**Comment by libBletchley** [comment]
We might consider giving notice upon receipt of a non-zero exit code from an external process such as that of a `message-hook`-triggered filter.  The particular scenario I have in mind is this:
https://github.com/neomutt/neomutt/issues/897.  In that case, the error output overwrites the screen.  A better approach would be to properly display the unfiltered message, and create an error notification.

**Comment by gahr** [comment]
From #897
> . But I do think the error handling could improve so that error output is handled by the new notification logic: #802, while unfiltered content is presented.

This is still in a very early stage of discussion, but I don't see it as a runtime notification system. The way I see it, it's more about fixed compile-time / startup things. I wouldn't expect the notifications list to change while running.

**Comment by gahr** [comment]
#1059 will do this and much more.
