### ISSUE TITLE
Initial <tab> completion of IMAP folders displays them unsorted

### ISSUE THREAD

**Issue by module0x90** [neomutt/neomutt#803]
**bug reports**

* Expected behavior
Display the list of IMAP folders in the same sorted way as subsequented presses of TAB do.
* Actual behavior
The initial TAB completion of the IMAP folder is messed up, not in alphanumerical order.
* Steps to reproduce
      1. Have one email highlighted/selected in the mail index. 
      2. Press <kbd>s</kbd> (default hotkey "save-message") to save message.
      3. Press <kbd>=</kbd> 
      4. Press <kbd>TAB</kbd> to complete the IMAP server.
      5. Press <kbd>TAB</kbd> again *twice* to get to the list of folders.
The folders are now listed in a chaotic way. Pressing TAB twice, will then first show the subscribed mailboxes, then a sorted list of folders - what should have shown initially.
* Used program versions
NeoMutt 20170912 (1.9.0), pacman says "local/neomutt 20170912-1"
* Operating System and its version
Arch Linux, up2date.

**Comment by flatcap** [comment]
Hmm... Well spotted.  Thanks for the bug report @module0x90.

**Comment by gahr** [comment]
@module0x90 Could you give the branch `devel/issue-803` a try?

**Comment by module0x90** [comment]
Just tried it and this bug is resolved.

Many thanks to you and the team!
October 9, 2017 2:41 PM, "Pietro Cerutti"  wrote:
	@module0x90 (https://github.com/module0x90) Could you give the branch devel/issue-803 a try?

**Comment by gahr** [comment]
Thanks!

**Comment by module0x90** [comment]
OT: I am also very pleased that this version I am now on 20171006-5-566126 (before 20170912) is much snappier when saving into different IMAP folders. Difficult to automate this in any way...
The older version it seems took longer and longer with every save.. 16172 emails in Archive, 16256 in Sent  and other workflow folders up to 50 max. Small setup, I guess.
