### ISSUE TITLE
notmuch-specific pattern ~Y crashes on IMAP mailbox

### ISSUE THREAD

**Issue by xunam** [neomutt/neomutt#805]
I just remarked that when using the `~Y` pattern for coloring index lines for messages that have a specific tag, `neomutt` crashes when connecting to an IMAP mailbox.

*Expected behavior*

The `~Y` pattern should be ignored in mailboxes where it does not apply.

*Actual behavior*

Segfault.

*Steps to reproduce*
```
echo 'color index cyan default ~Ykilled' > muttrc
mutt -F muttrc
```
Then connect to an IMAP mailbox.

*Used program versions*

Observed with `NeoMutt 20170912 (1.9.0)` and an up-to-date version from the `default` branch `NeoMutt 20170912-54-4426a0`.

*Operating System and its version*

Up-to-date Arch Linux.

*Additional observations*

I explored the issue a bit with `gdb`, it appears that the problem is in `pattern.c` at lines 1716-1722 (as of revision 4426a0b047a6ee931e6387993dcbfbd5d9f0802b) where the case `MUTT_NOTMUCH_LABEL` is handled. Then `nm_header_get_tags` returns an invalid pointer because it assumes incorrectly that the header is from a notmuch folder. There should be a test for the kind of folder.

**Comment by flatcap** [comment]
Thanks for the bug report @xunam.
You were spot on with the debugging.
