### ISSUE TITLE
<echo> function and variable interpolation in formats

### ISSUE THREAD

**Issue by nobrowser** [neomutt/neomutt#810]
I just added a macro to my `.muttrc` to toggle one of the many config variables (permanently, not just for the duration of another macro).  It works, of course, but there's something I don't like: there's no feedback. If I wasn't sure what the value of the variable was before I execute the macro, I am still not sure after.  To help with this, I propose adding either, or possibly both, of the following:

1. A function (in the mutt sense, i.e. something I can call from a macro) to echo an arbitrary string on the bottom line.  There should be a way to interpolate mutt variables into this string.

2. A new % thingy for index_format and so on, which interpolates mutt variables into that part of the UI.

I'm posting it here for discussion if it is worthwhile; if met with approval, I'll assign it to myself and I promise quick turn-around ;-)

**Comment by flatcap** [comment]
For your macro, there's a simple solution: add a `:set ?VARIABLE<enter>` to the end.
(I do a similar thing with my vim macros)

> A function ... to echo an arbitrary string on the bottom line.

There _was_ an echo patch floating around (I doubt it'll still apply cleanly).

> A new % thingy

An "expando" in mutt terminology.
What format should that take?

If we're limiting this to `<echo>` command and `$status_format`, then we can use something like: `%{from}`

Would we want to add formatting, too? `%-15.15{from}`

I like the idea.

**Comment by nobrowser** [comment]
Thinking about the status line formatting, thanks.  And thanks for the `:set` hint too.  Of course I thought of it myself a few minutes after I posted the above :-)

**Comment by flatcap** [comment]
Implemented as `echo`

**Comment by Amudtogal** [comment]
Coming back to this, I could not find documentation for the echo function (at least not with the Algolia search).
I was trying to echo the `From` header of a message in a `send2-hook`, but could not figure out how which expando to apply.
Thanks guys for keeping up the great work!
