### ISSUE TITLE
Sidebar display multiple (but not all) components.

### ISSUE THREAD

**Issue by lrosenman** [neomutt/neomutt#813]
I have mailboxes in a hierarchy in my IMAP server:
e.g. (not the full list):
```
lists
lists/neomutt
lists/neomutt/devel
lists/neomutt/users
lists/noaa
lists/noaa/changes
lists/waze
lists/waze/beta
lists/exim
lists/exim/users
lists/exim/announce
lists/exim/dev
lists/mailman
lists/mailman/announce
lists/mailman/users
lists/openssl
lists/openssl/announce
lists/openssl/users
lists/mutt
lists/mutt/users
lists/cone
lists/lopsa-us-tx-austin
lists/ietf
lists/ietf/sieve
lists/pgsql
lists/pgsql/novice
lists/pgsql/docs
lists/pgsql/announce
lists/pgsql/bugs
lists/pgsql/hackers
lists/pgsql/general
lists/pgsql/committers
lists/pgsql/sql
lists/pgsql/advocacy
lists/pgsql/jdbc
lists/pgsql/odbc
lists/pgsql/www
lists/pgsql/jobs
lists/SprintBuzz
lists/spi
lists/spi/private
lists/spi/general
lists/SpamAssassin
lists/SpamAssassin/users
lists/SpamAssassin/commits
lists/pfsense
lists/pfsense/users
lists/pfsense/security
lists/isoc
lists/isoc/pubsoft
lists/isoc/memberpubpol
lists/surbl
lists/surbl/discuss
lists/php
lists/php/announce
lists/freebsd
lists/freebsd/ports-developers
lists/freebsd/doc-svn
lists/freebsd/developers
lists/freebsd/ports-commiters
lists/freebsd/jobs
lists/freebsd/rc
lists/freebsd/mobile
lists/freebsd/x11
lists/freebsd/ports-bugs
lists/freebsd/amd64
lists/freebsd/advocacy
lists/freebsd/virtualization
lists/freebsd/ports-announce
lists/freebsd/wireless
lists/freebsd/arch
lists/freebsd/scsi
lists/freebsd/arm
lists/freebsd/net
lists/freebsd/fs
lists/freebsd/proliant
lists/freebsd/stable
lists/freebsd/cvs-all
lists/freebsd/announce
lists/freebsd/current
lists/freebsd/security
lists/freebsd/java
lists/freebsd/usb
lists/freebsd/cloud
lists/freebsd/ports
lists/freebsd/acpi
lists/freebsd/hackers
```

I have the sidebar set to : 
```
set sidebar_visible=yes
set sidebar_sort_method=alpha
set sidebar_width=30
set sidebar_folder_indent=yes
set sidebar_short_path=yes
set sidebar_indent_string=".."
set sidebar_new_mail_only
sidebar_whitelist INBOX
mono sidebar_highlight reverse
color sidebar_highlight yellow red
color progress white red

# ctrl-n, ctrl-p to select next, prev folder
# ctrl-o to open selected folder
bind index \CP sidebar-prev
bind index \CN sidebar-next
bind index \CO sidebar-open
bind index \CU sidebar-open
# b toggles sidebar visibility
macro index b '<enter-command>toggle sidebar_visible<enter>'
macro pager b '<enter-command>toggle sidebar_visible<enter>'
```

when it displays, it shows only the last component of the path (users for example).

I'm wondering if there is some way to get it to display the last 2 components.

**Comment by flatcap** [comment]
I had a bit of a play around with this.  I thought I might be able to use some combination of `/` and `.` separators to fool the sidebar.  Nope.

I can think of a couple of ways to improve the sidebar.

1. Make the truncation dependent on the previous line.
    Make sure that there's enough context to be able to identify **which** "announce" mailbox you're looking at.

2. Turn `$sidebar_short_path` into a number, e.g.
    +2 : strip at most 2 leading segments
    -2 : leave a minimum of 2 trailing segments

**Comment by lrosenman** [comment]
I like number 2, if I have a vote :)

**Comment by gahr** [comment]
Or an additional numeric config `sidebar_strip_component` defaulting to -1 not to break existing settings. Anyhow, I like the idea!

**Comment by lrosenman** [comment]
@gahr I like that even better (sidebar_strip_component).

**Comment by gahr** [comment]
Larry, wanna give it a go and cook up a patch? ;)

**Comment by lrosenman** [comment]
That's asking a lot for a guy that's mostly an admin and port maintainer. :( 

I haven't even looked at the NeoMutt codebase.

**Comment by gahr** [comment]
Fair enough - let’s see if there are any takers ;)

**Comment by flatcap** [comment]
@justinvasel 
Thanks, merged.

Are you interested in implementing the second half of the proposal?
Where `sidebar_strip_component = -N` => just the **last N** components.

**Comment by justinvasel** [comment]
Yeah I can probably take a crack at that soon. We may as well leave this issue open for now.

**Comment by lrosenman** [comment]
Any news on this?

**Comment by lrosenman** [comment]
Hrm.  Maybe I need to find the time and skills to add this.  @justinvasel  any news?

**Comment by justinvasel** [comment]
Hey @lrosenman, sorry for the radio silence. I'm still happy to give this a go, but probably won't have time until the week after next. If someone would like the functionality before then, feel free to have at it. Cheers.
