### ISSUE TITLE
View source of a message in read-only mailbox

### ISSUE THREAD

**Issue by reisradomil** [neomutt/neomutt#815]
Sometimes it is useful to see the complete raw message, e.g. to debug a mail problem or looking for spurious encoded stuff.
Currently there is no command to view the source of a message.
For read-write mailboxes there is the 'edit' command which can be abused for that.
However, this fails for read-only mailboxes with the message 'Mailbox is read-only.'

Interestingly enough, mutt is able to detect if the 'edit' command has modified the message.
It prints 'Message not modified!' in case the message was not modified.

Question: Did I miss something or is it currently not possible to view the message source from within neomutt?

Idea: Enhance the 'edit' command to print a notice if the message is from a read-only mailbox but still open the message (as it does at the moment).
If the use still modifies the message politely reject those when the editor closes.

reis

**Comment by flatcap** [comment]
How about if neomutt sets the temporary file as read-only?
The editor will force the user to save a copy and neomutt won't have deal with saving a tmp file.

**Comment by gahr** [comment]
I'm all for this!

**Comment by reisradomil** [comment]
Since you flagged this as easy, I'm willing to give it a shot and implement that feature.

**Comment by flatcap** [comment]
That's great.  Thanks.
First you'll need a copy of the source, a heap of building dependencies, a debugger...
(If you use IRC, I'll be around for a few more hours today : #neomutt on irc.freenode.net)

How good are your programming/debugging skills?
How much would you like to discover yourself?

**Comment by reisradomil** [comment]
This is how I would implement that feature:
* Implement a function `view-raw-message` which opens a message as a read-only file in the editor. (regardless if the mailbox is read-only or not)
* Implement a function `edit-or-view-raw-message` which is a dispatcher for either `edit` or `view-raw-message` depending whether the mailbox is writeable or not.
* Bind the key `e` to `edit-or-view-raw-message`. This yields still the old behaviour (i.e. `edit`) in a writeable mailbox, so does not break backwards compatibility.

Reasoning behind introducing `view-raw-message`:
1. Naming a function which only views a message in a read-only mailbox `edit` is quite misleading.
Renaming `edit` to `edit-or-view-raw-message` will likely break some config files out there, so is not a solution.
2. Some people might want to ensure that a message is not accidentally edited in a writeable mailbox (e.g. if their editor does some kind of autosaving).
3. It allows a clear separation of the intension viewing and editing a message. Personally I never wanted to edit a message but viewing happens every now and then.

Reasoning behind introducing `edit-or-view-raw-message`:
1. AFAIK it is not possible to bind a key to different actions depending on whether the mailbox is read-only or not. To avoid having two key bindings (lets say `e` for `edit` and `E` for `view-raw-message`) we introduce this little helper function which acts as a dispatcher.
2. People who still want a dedicated key for `view-raw-message` (to ensure they don't edit it accidentally) can still bind it to a key of their liking.

Thoughts about this? (Naming suggestions are also welcome).

I also had a look into the source.

The `mutt_index_menu()` function in `curs_main.c` line 908 seems to be the dispatcher which is invoked when executing the `edit` mutt-function.
The relevant case is `OP_EDIT_MESSAGE` on line 2873 which essentially calls `mutt_edit_message()` from `edit_msg.c`.

Questions:

Q1: Is it correct that all possible invocations (bound to a key, in a macro, in a configfile, as `:exec edit`, ...) of the `edit` function (as mutt function not as a C function) go through the C-function `mutt_index_menu()`? (I didn't look for code which calls function based on some pointer hackery or reflection stuff.)

Q2: Besides the `READONLY` check in the `OP_EDIT_MESSAGE` case there is also an ACL check for `MUTT_ACL_INSERT`. What kind of ACL is this? More precisely, do I need to any ACL-permission for the `view-raw-message` case?

Q3: To introduce the new functions `view-raw-message` and `edit-or-view-raw-message`, is it enough to add an entry in `functions.h` and `opcodes.h` and write corresponding case in `mutt_index_menu()`?

Q4: Is it allowed to rename `mutt_edit_message()` to `mutt_edit_or_view_message()` or would this break some API/ABI some third party code might relay on?

best reis

**Comment by chrisbra** [comment]
If I need this, I usually use `:set pipe_decode=no` and then pipe the message to whatever program I need (e.g. less)

**Comment by reisradomil** [comment]
chrisbra's suggestion works in that use case and for editors/readers which accept input from stdin.

If it still seems be nice to have a more integrated solution as outlined above (i.e. a more uniform handling of the 'e' key-stroke), I would still be willing to implement this if someone gives me some support regarding my questions.

**Comment by gahr** [comment]
Thank you @reisradomil, I think this is going to be a nice enhancement.

> Q1: Is it correct that all possible invocations (bound to a key, in a macro, in a configfile, as :exec edit, ...) of the edit function (as mutt function not as a C function) go through the C-function mutt_index_menu()?

Yes, that seems the only place where `OP_EDIT_MESSAGE` is used. The function `edit` is available in both `OpMain` and `OpPager` (see `functions.h`), `mutt_index_menu` handles both.

> Q2: Besides the READONLY check in the OP_EDIT_MESSAGE case there is also an ACL check for MUTT_ACL_INSERT. What kind of ACL is this? More precisely, do I need to any ACL-permission for the view-raw-message case?

ACL is finer-grained than READONLY. I'd say for edit-message requires `CHECK_READONLY` and `!CHECK_ACL(MUTT_ACL_INSERT, ...)` - as it is now. For `view-raw-message`  I think you'll need the same checks which are done for `OP_DISPLAY_MESSAGE`.

> Q3: To introduce the new functions view-raw-message and edit-or-view-raw-message, is it enough to add an entry in functions.h and opcodes.h and write corresponding case in mutt_index_menu()?

I think so. I'd reproduce the cases where `OP_EDIT_MESSAGE` is handled, and adjust the capabilities checks accordingly.

> Q4: Is it allowed to rename mutt_edit_message() to mutt_edit_or_view_message() or would this break some API/ABI some third party code might relay on?

I don't see a necessity for the change, but if you feel strongly about it, please go ahead :)

> Q5: Is the documentation file doc/manual.xml.head written by hand or is there some tool (sphinx/asciidoc/...) which generates it?

It's currently hand-written.

Please let us know if you need further guidance!

**Comment by reisradomil** [comment]
I have now the following code (slightly simplified)

```c
/* file: curs_main.c */
mutt_index_menu()
{
 ...
 case (op) {
   ...
   OP_EDIT_OR_VIEW_RAW_MESSAGE:
   OP_EDIT_RAW_MESSAGE:
   OP_VIEW_RAW_MESSAGE:
     ...
     /* `mode` gets set depending on whether we should edit or view the raw message */
     ViewOrEditRawMessage mode = ...;
     mutt_edit_message(Context, tag ? NULL : CURHDR, mode);
     ...
   ...
  }
}

/* file: editmsg.c */
mutt_edit_message(struct Context *ctx, struct Header *cur, ViewOrEditRawMessage mode)
{
   ...
   if (mode == EDIT_RAW_MESSAGE)
   {
     ...
   }
   ...
}
```

The variable `mode` in the case-statement gets set depending on whether we should edit or only view the raw message. This depends on whether the mailbox is read-only and which of the three operations (edit, view, edit-or-view) was given. It is then passed to `mutt_edit_message()` which does all the heavy work.

The question is what type `ViewOrEditRawMessage` should be. I see three possibilities:

1. Misuse `OP_EDIT_RAW_MESSAGE` and `OP_VIEW_RAW_MESSAGE` and pass those to `mutt_edit_message()`.
   In this case `ViewOrEditRawMessage` would be `mutt_ops` (defined in `opcodes.h`), which also contains lots of other enum values unused by our functions.
2. Use a `bool`. `true` == read-only, `false` == edit.
3. Introduce a dedicated enum `ViewOrEditRawMessage` with the two constants `EDIT_RAW_MESSAGE` and `VIEW_RAW_MESSAGE`.

In my opinion 3. is the cleanest solution as it does not hijack an unrelated enum and the calling side has a meaningful name (compare `mutt_edit_message(Context, NULL, true)` with `mutt_edit_message(Context, NULL, VIEW_RAW_MESSAGE)`)

The question is where to put the enum `ViewOrEditRawMessage` as its needed in two files `curs_main.c` and `editmsg.c`?
Introduce a `editmsg.h` with the enum and also move the declaration of `mutt_edit_message()` to it?
Note: The function declaration of `mutt_edit_message()` is in `protos.h`.

Whats your opinion about this?
