### ISSUE TITLE
homebrew support?

### ISSUE THREAD

**Issue by neonfrontier** [neomutt/neomutt#82]
Just a suggestion, would love to see this added to the homebrew library.

I believe [this](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) is the homebrew contributing guide.

**Comment by flatcap** [comment]
So would we, but...  Apparently there are some rules: 20 forks + 20 watchers + 50 stars.
We need some more forking developers :-)

**Comment by neonfrontier** [comment]
Didn't know that, but thank you so much for the formula! :)

**Comment by alexpearce** [comment]
> Apparently there are some rules: 20 forks + 20 watchers + 50 stars.
We need some more forking developers :-)

Indeed, but even the [Neovim Homebrew repo](https://github.com/neovim/homebrew-neovim), which ours is based off and is much more popular, doesn't quite meet the requirements (though I suspect being 1 watcher too short might be acceptable).
