### ISSUE TITLE
NeoMutt is slow to start up

### ISSUE THREAD

**Issue by sjl** [neomutt/neomutt#827]
NeoMutt takes five seconds to start up on my machine, even with `-n -F /path/to/empty/file` to use a completely blank muttrc:

```
sjl at garbagebox in ~/Desktop
><((°> time /usr/local/bin/mutt -n -F /tmp/empty-muttrc -d5 -D -S
Debugging at level 5.
abort_noattach=no
...lots of options...
        5.02 real         0.00 user         0.00 sys
```

I'm using the `20170912` version from Homebrew, MacOS High Sierra (I tried a few earlier ones too and the problem was still there).  This started happening after I upgraded to High Sierra, so possibly something changed there?

The debug file just says:

```
[2017-10-08 17:49:04] NeoMutt/20170912 (1.9.0) debugging at level 5
[2017-10-08 17:49:09] Reading configuration file '/tmp/empty-muttrc'.
```

Note the five second gap in between the lines.

I tried `dtruss`ing it but nothing stands out.

**Comment by gahr** [comment]
The usual suspect is DNS resolution. I would try to debug and see how much it takes for `int getdnsdomainname(char *d, size_t len)` to resolve your machine name.

**Comment by flatcap** [comment]
OK, the only thing that can cause a delay is the hostname lookup.
NeoMutt is looking for the host's Fully Qualified Domain Name.

First it calls `gethostname()`

Then, there are three possible routes:
1. NeoMutt was compiled with `--with-domain=example.com`
    Not commonly used.
2. System has `getaddrinfo_a()` function
    We set the timeout at 0.1s
3. System only has `getaddrinfo()`
    This can take a while to timeout.

Please can you try, `host $(hostname)` -- see if it takes ages.
Or try enabling `--with-domain` to confirm that `getaddrinfo()` is the problem.

**Comment by sjl** [comment]
`host $(hostname)` returns quickly:

```
bash-3.2$ time host $(hostname)
Host garbagebox.local not found: 3(NXDOMAIN)

real    0m0.044s
user    0m0.003s
sys     0m0.005s
```

Recompiling NeoMutt with `--with-domain=example.com` does fix the slowdown though.  What are the consequences of using this?

**Comment by gahr** [comment]
See 3.114 here: https://www.neomutt.org/guide/reference

**Comment by flatcap** [comment]
Looking through the code, the FQDN is seldom used.
It's the last resort if `$from` isn't set and it's used when neomutt tries to expand addresses like "rich@laptop".

> What are the consequences of using this?

As a single user, there shouldn't be any.
Obviously this won't be any use to packagers.

As @gahr points out, the hard-coded domain can be overridden setting `$hostname`

If you have the time to investigate further, I've cut out neomutt DNS code: [test-dns.c](https://gist.github.com/flatcap/fa4308849f68d9883ddfef7887fe289d)
`getaddrinfo()` uses [NSS](https://en.wikipedia.org/wiki/Name_Service_Switch) to lookup the hostname.
([more info](https://skarnet.org/software/s6-dns/getaddrinfo.html))

A tweak to `/etc/nsswitch.conf` may be all that's needed.

**Comment by DebXWoody** [comment]
short: MacBook-Stefan
hostname: MacBook-Stefan.local

The function getaddrinfo needs 5s

**Comment by flatcap** [comment]
I did some more experiments on this.
I wondered if a `SIGALRM` signal from `alarm(2)` might be able to interrupt the system call.
The answer, on Linux at least, is no.

@gahr has suggested moving the name lookup to after we read the config.
Then, `set hostname` would mean we could skip `getaddrinfo()` completely.

**Comment by flatcap** [comment]
I've recently refactored the startup code.
The DNS lookup is now done as a last resort.

NeoMutt uses the first of:
- User config
- System config
- Compiled-in domain: `./configure --with-domain=example.com`
- System mailname: `/etc/mailname`, `/etc/mail/mailname`
- DNS lookup

This will be in the next release.
