### ISSUE TITLE
Build error on development release

### ISSUE THREAD

**Issue by Vaelatern** [neomutt/neomutt#828]
When running make, the following is the last output I see (this is the second run, so extra lines are minimized):

```
ar cr libncrypt.a ncrypt/crypt.o ncrypt/crypt_mod.o ncrypt/cryptglue.o ncrypt/crypt_gpgme.o ncrypt/crypt_mod_pgp_gpgme.o ncrypt/crypt_mod_smime_gpgme.o ncrypt/crypt_mod_pgp_classic.o ncrypt/gnupgparse.o ncrypt/pgp.o ncrypt/pgpinvoke.o ncrypt/pgpkey.o ncrypt/pgplib.o ncrypt/pgpmicalg.o
ncrypt/pgppacket.o ncrypt/crypt_mod_smime_classic.o ncrypt/smime.o
ar cr libimap.a imap/auth.o imap/auth_anon.o imap/auth_cram.o imap/auth_login.o imap/auth_plain.o imap/browse.o imap/command.o imap/imap.o imap/message.o imap/utf7.o imap/util.o imap/auth_sasl.o
xsltproc --nonet -o doc/ ./doc/chunk.xsl doc/manual.xml > /dev/null 2>&1
ranlib libncrypt.a
ranlib libimap.a
xsltproc --nonet -o doc/manual.html ./doc/html.xsl doc/manual.xml
make: *** [doc/Makefile:60: doc/index.html] Error 5
make: *** Waiting for unfinished jobs....
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl"
compilation error: file ./doc/html.xsl line 3 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl
make: *** [doc/Makefile:45: doc/manual.html] Error 5
```

It seems that xsltproc is convinced it needs to ask the network, but it can't because it was told not to. I don't know if that makes sense, I am unfamiliar with the libary (and the dependency is new to this version).

This is using Void Linux's build system, by the way.

**Comment by flatcap** [comment]
Hmm... I know what's causing the problem, but I don't know why it would have _just_ started happening.

The docs are in DocBook format and they're rendered into HTML at build time.
This requires the DocBook DTDs (the build has a `--nonet` option to prevent unexpected net access).
I've just checked.  It's always been a build requirement.

I don't know what it's called in Void, but it's
- docbook-dtds in Fedora
- docbook-xml Debian

**Comment by gahr** [comment]
docbook-xsl on FreeBSD, if that helps :)

**Comment by gahr** [comment]
well, that's because it's not the DTDs that it's missing, but the XSLs

**Comment by Vaelatern** [comment]
Void just updated libxslt to 1.1.31 yesterday, so that might have something to do with it.
I'm experimenting to see why I only now have difficulties with finding OpenSSL (I'm using libressl, but it's never been a problem before)...
```
Checking for openssl/bio.h...ok
Checking for openssl/err.h...ok
Checking for openssl/ssl.h...ok
Checking libs for X509_STORE_CTX_new...-lcrypto
Checking libs for SSL_new...-lssl
Checking libs for deflate...no
Error: Unable to find OpenSSL
Try: 'configure.autosetup --help' for options
```

**Comment by gahr** [comment]
Looks like zlib is missing, I’ll have a look tomorrow.

**Comment by gahr** [comment]
I conjecture that this might be due to the fact that your distribution ships zlib bundled within libc.

Our autoconf machinery does try to locate `deflate` in `libz`, but does not fail if it can’t find it. This last no-failure bit I missed when translating the checka to Autosetup.

I’ll fix it tomorrow.

**Comment by gahr** [comment]
Anybody please feel free to fix it if you come to it sooner :)

**Comment by ObiWahn** [comment]
I had this issue with the tag (20250404). Installing `docbook-xsl` on debian solved the issue for me. Maybe you can check somehow during the configure phase if everything is available.
