### ISSUE TITLE
Crash when using Torify and NeoMutt

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#83]
NeoMutt (under Torify) crashes when opening an email.
The crash happens in [fmemopen_read](http://sprunge.us/RaCG)
Details: i686 machine
Need to make fmemopen a configure option.

**Comment by pickfire** [comment]
Tested in `Linux peak 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux`, with `./prepare && make`. No issues with `torify ./mutt` and `torify oldmutt`.

**Comment by flatcap** [comment]
@pickfire Thanks.
Might be just a 32-bit problem.
Recompiling without fmemopen fixed the problem for the user.

**Comment by pickfire** [comment]
@flatcap I didn't compile with `fmemopen`, maybe that's why. If you can give me the step to reproduce, I will definitely try it.

**Comment by flatcap** [comment]
It's part of glibc.  If it exists (and it probably does) it will be compiled in automatically.
Look for "patch-fmemopen-neo-git" in `mutt -v`

**Comment by pickfire** [comment]
@flatcap Yes, it's there. My version can be found here https://transfer.sh/87uJy/v and I didn't get into the mail server as I didn't compiled it with smtp and imap. Maybe because of that?

And just heard of glibc, can mutt actually be compiled using musl-libc?

**Comment by flatcap** [comment]
hang on.  scratch that.  The patch line will show up whether fmemopen is used, or not.  I'll have to add that to the list of things to fix.

> can mutt actually be compiled using musl-libc

No idea.  Let me know if you find out.

**Comment by SantiagoTorres** [comment]
On Wed, Jul 20, 2016 at 08:39:09AM -0700, Ivan Tham wrote:
> @flatcap Yes, it's there. My version can be found here https://transfer.sh/87uJy/v and I didn't get into the mail server as I didn't compiled it with smtp and imap. Maybe because of that?
> 
> And just heard of glibc, can mutt actually be compiled using musl-libc?

If your distribution is using musl as the underlying libc, then you
might be already be running it.

It might be a good idea to test mutt with a statically-compiled musl for
hardening. 

@flatcap, would this be worthy of a ticket?

**Comment by flatcap** [comment]
It's not really _NeoMutt_-oriented, but I don't mind.  Go for it.

**Comment by pickfire** [comment]
@flatcap Haha, it just seems like all the features are showing up.

@SantiagoTorres Seems like what you said. My system is using libc, it doesn't work. Every library  needs to be recompiled with musl if I am correct.

**Comment by flatcap** [comment]
There's 2013 chart, from NetBSD pkgsrc, that says mutt doesn't compile with musl:
http://wiki.musl-libc.org/wiki/Pkgsrc_results

**Comment by flatcap** [comment]
I've added a `./configure` option `--disable-fmemopen`
