### ISSUE TITLE
Some [-Wunused-result]

### ISSUE THREAD

**Issue by riesebie** [neomutt/neomutt#837]
Building either with clang-5.0 or gcc 7.2.0 I see some unused-result warnings. Respective buildlogs can be found [here](https://www.lxtec.de/buildlogs/) .

**Comment by gahr** [comment]
Yep, this is known. Not sure how / if we want to fix those.

**Comment by flatcap** [comment]
I'd love to see these fixed, but each of them could require a bit of careful analysis.
Is this function likely to fail (neomutt is safely ignoring the result),
or would its failure cause problems (a bug in neomutt).

Currently, we build with: `-Wno-unused-result -Werror` ([build script](https://github.com/neomutt/travis-build/blob/0238b289ea9d6291de0e9264b60a0fa2960513f0/build#L8-L9))
Ignore that one specific error, but fail if there are any others.

I'd welcome fixes for any of these warnings,
but for now I'm going to close this as "won't-fix".
