### ISSUE TITLE
Deprecation: mutt_sasl_done uses sasl_done()

### ISSUE THREAD

**Issue by seishinryohosha** [neomutt/neomutt#841]
`mutt_sasl_done` from `mut_sasl.h` calls `sasl_don()` which is deprecated.
From the current header.

> \* This function is DEPRECATED in favour of sasl_server_done/
> \* sasl_client_done.

The new functions return SASL_OK (0) or SASL_CONTINUE (1)
--> https://www.cyrusimap.org/sasl/sasl/reference/manpages/library/sasl_client_done.html?highlight=sasl_client_done

It's only called once in neomutt:
main.c -> 944

Is it somehow planned to catch the SASL_CONTINUE state?
Unfortunately the documentation isn't that clear, what this state actually means.

**Comment by gahr** [comment]
By looking at their implementations, it looks to me like `sasl_client_done` returns `SASL_CONTINUE` if the server-side of the library was init’d and `sasl_server_done` wasn’t called yet.
Other than that, the two functions are equivalent, so yeah, I’d say let’s change that!

**Comment by seishinryohosha** [comment]
So one approach would be to wait for e.g. a second and try it again?
Try it indefinitely or try it e.g. 10 times and bail out after that?

Have you other approaches?

**Comment by gahr** [comment]
No, what I'm saying is that we don't have the server side of a SASL session opened, so it'll never return `SASL_CONTINUE` for us.

If you had both sides opened:

```
int rc;
rc = sasl_client_done();
assert(rc == SASL_CONTINUE);
rc = sasl_server_done();
assert(rc == SASL_OK);
```

or

```
int rc;
rc = sasl_server_done();
assert(rc == SASL_CONTINUE);
rc = sasl_client_done();
assert(rc == SASL_OK);
```

**Comment by seishinryohosha** [comment]
I meant it in a very defensive way:
Maybe someday in the future we'll use server side and to already handle the case.
But this may be to defensive ;)

**Comment by gahr** [comment]
In which case, waiting and retrying wouldn't help. One would need to call *both* the `_done()` functions.

**Comment by seishinryohosha** [comment]
Sure
