### ISSUE TITLE
Solaris Quirks

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#843]
There are two places in the code that have comments relating to Solaris.

---

https://github.com/neomutt/neomutt/blob/3f42b5f780515f8c7cf54ac76e5157a446004ecb/mutt_regex.h#L33-L38

Does the `REG_WORDS` constant still exist in modern versions of Solaris?

---

https://github.com/neomutt/neomutt/blob/3f42b5f780515f8c7cf54ac76e5157a446004ecb/lib/buffer.c#L177-L184

Is `realloc(3)` safe to use with a size of `0` in current versions of Solaris?

---

/cc @0-wiz-0 @qsuscs

**Comment by 0-wiz-0** [comment]
My resident Solaris expert tells me:

1. `REG_WORDS` still exists, in `/usr/include/regex.h`
2. `realloc()` with size 0 on solaris frees the original ptr (if not `NULL`); that's different to what e.g. Darwin does (returns a minimum size object). Safe, but you have to know what to expect in both cases :)

**Comment by flatcap** [comment]
Thanks @0-wiz-0.
I shall adjust the comments.
