### ISSUE TITLE
Smart wrap problem

### ISSUE THREAD

**Issue by tcpaiva** [neomutt/neomutt#844]
* **bug reports**

    * Expected behavior
When reading e-mails, lines should wrap between words if "smart_wrap" is set.

    * Actual behavior
Lines wrap in the middle of the word. 

    * Steps to reproduce
According to flatcap, who helped me to dig into the problem at #neomutt irc channel, lines starting with space do not "smart wrap".

    * Used program versions
neomutt (1.8.3)

    * Operating System and its version
Ubuntu 16.04.3

**Comment by gahr** [comment]
The (intermediate fix)[https://github.com/neomutt/neomutt/commit/f5e472b13a98fb84173e058fed462d3109508bb0] was brought to completion. It shouldn't be hard to check whether there are other spaces in between index 0 and `Wrap`.

**Comment by Austin-Ray** [comment]
Since no one has stepped up for the issue, I would like to try my hand at it.

**Comment by flatcap** [comment]
@Austin-Ray 
Great.  Be warned though!
You may find you just need to adjust one line, by one character, and it works.
Or, you may go insane trying to figure it out :-)

I found that lines starting with whitespace didn't **word**-wrap.

Good:
```
This long line gets
wrapped
```

Leading space, bad:
```
␣However this line isn't so pret
ty
```

**Comment by Austin-Ray** [comment]
The merged PR resolves this issue so I am closing the issue.
