### ISSUE TITLE
Never create anything in root dir during built!

### ISSUE THREAD

**Issue by riesebie** [neomutt/neomutt#845]
* **bug reports**

    * Expected behavior
Never create anything in root dir during built!

    * Actual behavior
While built /hcache is created => Why? Let the user decide which hcachedir to use.

    * Steps to reproduce
Just compile neomutt => One needs root access to create /hcache. Otherwise build fails, though.

    * Used program versions
NeoMutt 20171006

    * Operating System and its version
Debian sid

**Comment by gahr** [comment]
Looks like `$(PWD)` isn't reliable enough in all cases.
