### ISSUE TITLE
Force offline caching

### ISSUE THREAD

**Issue by kiplingw** [neomutt/neomutt#850]
It would be nice if there was some way to force NeoMutt to always maintain a cache of all, or specific, IMAP folders. Currently NeoMutt won't download all IMAP messages into its offline cache unless you give it a need to directly access them. At present the only workaround that I am aware of is to search a folder using the message body query with a search key that doesn't match anything (e.g. "~b 123foo") so that it caches everything.

**Comment by flatcap** [comment]
It's a lovely idea, but unfortunately it's not practical.  Yet...
We're working to make neomutt more modular.  (It'll take time).
- Header cache library - nearly independent of neomutt
- Connection library - some dependencies
- IMAP library - lots of dependencies

When these three are separated from neomutt, it will be trivial for someone to create a offline-cacher.

**Comment by kiplingw** [comment]
Thanks flatcap. In the mean time I'm trying to make do with mbsync(1).
