### ISSUE TITLE
document that's only text/plain is human readable in neomutt 

### ISSUE THREAD

**Issue by sileht** [neomutt/neomutt#859]
(Upstream) Mutt considers all text/* as human readable. But in fact most text/* are not (they are html/xml/css/cvs/javascript...)

Neomutt considers only text/plain as human readable.

To add more text/XXXX as human readable, I use that in my mailcap:

  text/x-diff; cat '%s'; copiousoutput;
  text/x-patch; cat '%s'; copiousoutput;

This difference should be documented.

**Comment by ng-0** [comment]
However when I include this in my ~/.mailcap and restart neomutt, the message is still

```
[-- text/x-patch is unsupported (use 'v' to view this part) --]
```

**Comment by ng-0** [comment]
A possible solution in my case could be a hack on the mime.types file as mentioned here: https://www.neomutt.org/guide/mimesupport

**Comment by ng-0** [comment]
And I just realized that my problem is that I need to adjust either the guix package or my system configuration to include a file in etc:
```
user@abyayala ~/src/ticketfrei-nrw$ neomutt -nF /dev/null -Q mailcap_path
mailcap_path="~/.mailcap:/gnu/store/ald7bma1zrzr43wls6qhk1pg76awygbg-neomutt-20171013/share/neomutt/mailcap:/gnu/store/ald7bma1zrzr43wls6qhk1pg76awygbg-neomutt-20171013/etc/mailcap:/etc/mailcap:/usr/etc/mailcap:/usr/local/etc/mailcap"
```

history made me assume that ~/.mailcap is read.

**Comment by gahr** [comment]
Doesn’t `auto_view` help?

**Comment by ng-0** [comment]
Good idea, I'll try to add that back in. I have some mutt / neomutt mixture with almost 20 years old configs now.

**Comment by sileht** [comment]
Indeed, I miss that part, I also have this in my muttrc:

 auto_view text/x-diff
 auto_view text/x-patch
