### ISSUE TITLE
the IMAP keywords new support in 2017-10-13 is NOT documented

### ISSUE THREAD

**Issue by lrosenman** [neomutt/neomutt#861]
* the IMAP keywords support is not documented.

    * Expected behavior
         Documentation for the new Expando's and commands would be present
    * Actual behavior
          no user-facing documentation is available.
    * Steps to reproduce
    * Used program versions
          20171013
    * Operating System and its version
          macOS 10.13

Please document the new expando's and commands (%j/%J?  edit-imap-keywords?  Etc.

**Comment by lrosenman** [comment]
It seems that the functions <modify-tags> are doc'd to touch IMAP, the %g expando is NOT doc'd to use IMAP keywords.

Some examples would be a good thing(tm) IMO.

**Comment by lrosenman** [comment]
the Tags: display seems to be tied to notmuch, and if you force that issue, there are segfaults as well.  @flatcap helped me some on IRC, but there are still dragons there.

**Comment by flatcap** [comment]
Fixed by:
- cf87550a imap/notmuch tags: Add some documentation
- a9a9c709 English and other cleanups
