### ISSUE TITLE
--with-sysroot is not supported by new build system

### ISSUE THREAD

**Issue by Vaelatern** [neomutt/neomutt#869]
This has come up because Void Linux tells `gnu-configure` scripts to work with `--with-sysroot=$XBPS_CROSS_BASE` where `$XBPS_CROSS_BASE` is a subdirectory wherin architecture specific packages are installed for the sake of the compiler and linker.

I could duplicate this with (I believe) `--with-lua=$XBPS_CROSS_BASE/` because the lua package is installed under ther (`$XBPS_CROSS_BASE/usr/include/lua` etc.). However it would also involve me manually, just for neomutt, handling flags such as `--host` and `--build`, and I'd rather not do that for long, since it is a rather fragile way of doing things.

Is there any option of `--with-sysroot` support being added?

For reference, the cross build error can be seen at the very bottom of: https://build.voidlinux.eu/builders/armv7l-musl_builder/builds/5085/steps/shell_3/logs/stdio

**Comment by flatcap** [comment]
The old (autoconf) configure never had a `--with-sysroot` option (I've just checked).
gcc has a `--sysroot=DIR` option, so you might be able to:
```
./configure.autosetup EXTRA_CFLAGS="--sysroot=DIR"
make EXTRA_CFLAGS="--sysroot=DIR"
```

autosetup was designed with cross-compiling in mind,
so @gahr will probably tell us the correct solution in the morning :-)

**Comment by Vaelatern** [comment]
Just confirming, autosetup will use the host compiler for makedoc instead of the target compiler, yes? And I'm just invoking configure incorrectly?

**Comment by gahr** [comment]
Uhm.. I'm not sure I understand the issue.. afaics,`--with-sysroot` is a gcc's flag, not autoconf's. Isn't `./configure.autosetup [....] CFLAGS=--with-sysroot=DIR` enough?

**Comment by Vaelatern** [comment]
We pass `--with-sysroot` to all our autoconf builds. It's possible that autoconf is magical enough to append it to `CFLAGS`.

**Comment by Vaelatern** [comment]
`armv7l-linux-gnueabihf-gcc: error: unrecognized command line option '--with-sysroot=/usr/armv7l-linux-gnueabihf'`
It appears that it's not a `gcc` option.

**Comment by Vaelatern** [comment]
Also even when I discovered with the help of IRC that it's `--sysroot`, configure fails:
```
Host System...armv7l-unknown-linux-gnueabihf
Build System...x86_64-unknown-linux-gnu
C compiler...ccache armv7l-linux-gnueabihf-gcc -specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1  -fstack-protector-strong -D_FORTIFY_SOURCE=2  -O2 -pipe -march=armv7-a -mfpu=vfpv3 -mfloat-abi=hard   -I/usr/armv7l-linux-gnueabihf/usr/include
C++ compiler...ccache armv7l-linux-gnueabihf-c++ -specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1 -fstack-protector-strong -D_FORTIFY_SOURCE=2  -O2 -pipe -march=armv7-a -mfpu=vfpv3 -mfloat-abi=hard   -I/usr/armv7l-linux-gnueabihf/usr/include
Build C compiler...cc
Checking for stdlib.h...ok
Checking whether the C compiler accepts -std=c99...yes
Checking for install...ok
Checking for sendmail...no
Checking for sys/types.h...ok
Checking for sys/param.h...ok
Checking endian...unknown
Checking for minix/config.h...not found
Checking for sys/types.h...ok
Checking if -D_FILE_OFFSET_BITS=64 is needed...yes
Checking for signal.h...ok
Checking for ioctl.h...not found
Checking for sys/ioctl.h...ok
Checking for sys/syscall.h...ok
Checking for sysexits.h...ok
Checking for fgetc_unlocked...ok
Checking for futimens...ok
Checking for getaddrinfo...ok
Checking for getsid...ok
Checking for iswblank...ok
Checking for mkdtemp...ok
Checking for strsep...ok
Checking for vasprintf...ok
Checking libs for gethostent...none needed
Checking libs for setsockopt...none needed
Checking libs for getaddrinfo_a...-lanl
Checking for xsltproc...ok
Checking for gpgme.h...ok
Checking libs for gpgme_new...-lgpgme
Checking for gpgme_op_export_keys...ok
Checking for sasl/sasl.h...ok
Checking libs for sasl_encode64...-lsasl2
Checking for include/lua53/lua.h...no
Checking for include/lua5.3/lua.h...no
Checking for include/lua/lua.h...no
Checking for include/lua.h...no
Checking for include/lua52/lua.h...no
Checking for include/lua5.2/lua.h...no
Checking for include/lua/lua.h...no
Checking for include/lua.h...no
Error: Unable to find Lua
Try: 'configure.autosetup --help' for options
```

**Comment by Vaelatern** [comment]
There also appears to be an undocumented flag: `--sysconfdir=/etc` since builds with this flag succeed in properly installing under `/etc`, and else it seems to favor `${PREFIX}/etc`

**Comment by gahr** [comment]
> There also appears to be an undocumented flag: --sysconfdir=/etc since builds with this flag succeed in properly installing under /etc, and else it seems to favor ${PREFIX}/etc

This is going to be addressed  by #892

**Comment by gahr** [comment]
#892 was merged.

**Comment by gahr** [comment]
... which only resolved part of the issue, I guess..

**Comment by gahr** [comment]
@Vaelatern are you guys working around this somehow? Is this still badly needed? What do you suggest?

**Comment by Vaelatern** [comment]
We are not cross building neomutt, but instead have the note:
```
nocross="https://build.voidlinux.eu/builders/armv7l_builder/builds/5375 no longer gnu-configure, but needs /etc set correctly and also to know how to cross build documentation"
```

We do have a workaround in a sort for the various libraries, but it was inadequate to successfully cross build.
```
        configure_args="${configure_args} --with-lua=$XBPS_CROSS_BASE/"
        configure_args="${configure_args} --with-ncurses=$XBPS_CROSS_BASE/"
        configure_args="${configure_args} --with-notmuch=$XBPS_CROSS_BASE/"
        configure_args="${configure_args} --with-ssl=$XBPS_CROSS_BASE/"
        configure_args="${configure_args} --with-gdbm=$XBPS_CROSS_BASE/"
        configure_args="${configure_args} --with-gpgme=$XBPS_CROSS_BASE/"
```

**Comment by Vaelatern** [comment]
I'd be willing to test if put on a branch, yes.

**Comment by gahr** [comment]
Alright, I'll work on it. Thanks.

**Comment by gahr** [comment]
@Vaelatern would you please give [devel/issue-869](https://github.com/neomutt/neomutt/tree/devel/issue-869) a go?

**Comment by Vaelatern** [comment]
So it still fails because `Error: Unknown option --with-sysroot`, would it be possible to change the flag name from `--sysroot` to `--with-sysroot` so as to maintain maximum compatibility with preexisting tools?

**Comment by gahr** [comment]
Fair enough, pushed.

**Comment by Vaelatern** [comment]
With this I was able to cross build. Excellent!

**Comment by gahr** [comment]
Wonderful, thanks a lot for testing!

**Comment by gahr** [comment]
#1101 was merged.
