### ISSUE TITLE
sidebar, unread counter and multiple accounts

### ISSUE THREAD

**Issue by VinceTT** [neomutt/neomutt#872]
In default configuration, i must wait check_mail_stats_interval to refresh the unread counters in my sidebar when i change account with macro. Is it possible to automatically or manually exec 'check_mail_stats' in order to refresh these counters instantly without reducing interval at 1 second ?

**Comment by Austin-Ray** [comment]
I use `$` to update the unread counter with my virtual mailboxes. Could you see if that shortcut exhibits the behavior you desire?

**Comment by VinceTT** [comment]
Yes but only for the current active mailbox, the others displayed in sidebar always shows '0 mail unread' until check_mail_stats occurs. It happens when i change account with macro and that my sidebar change the list of  displayed local mailboxes.

**Comment by flatcap** [comment]
Creating an `<update-all-the-stats>` command wouldn't be too hard.

**Comment by uinput** [comment]
Wouldn't something like this suffice?
```c
{ "update-all-the-stats", mutt_buffy_check, 1 },
```

**Comment by flatcap** [comment]
Implemented as `<check-stats>`
