### ISSUE TITLE
Crash in mutt_pattern_exec()

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#874]
This was reported by summit_ on IRC, who provided the following backtrace:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000558864263662 in mutt_pattern_exec (pat=pat@entry=0x55886494f6f0, flags=flags@entry=MUTT_MATCH_FULL_ADDRESS, ctx=ctx@entry=0x5588648eacb0,
    h=h@entry=0x5588649d5ec0, cache=cache@entry=0x7ffff5523340) at pattern.c:1689
1689              set_pattern_cache_value(cache_entry, match_user(pat->alladdr, h->env->from, NULL));
 -------------
(gdb) p h->env
$2 = (struct Envelope *) 0x0
```

Steps to reproduce:
- '#' (break-thread)
- '\<enter\>' (view-message)

Crash occurred in `mutt_pattern_exec()` when `~P` pattern was evaluated.
A backtrace showed that `h->env` was NULL.

Update from summut_:

> thanks, but that hasn't fixed it  :/

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  mutt_pattern_exec (pat=pat@entry=0x565506a20750, flags=flags@entry=MUTT_MATCH_FULL_ADDRESS, ctx=ctx@entry=0x565506ab2a80, h=h@entry=0x5655079acd60, cache=cache@entry=0x7ffc1b6515e0) at pattern.c:1715
1715              set_pattern_cache_value(cache_entry, match_user(pat->alladdr, h->env->from, NULL));
(gdb) p pat->alladdr
$1 = false
(gdb) p h->env->from
Cannot access memory at address 0x49
(gdb) p h->env
$2 = (struct Envelope *) 0x41
(gdb) p *h
$3 = {security = 0, mime = false, flagged = false, tagged = false, deleted = true, purge = false, quasi_deleted = false, changed = true, attach_del = false, old = false, read = false, expired = false, superseded = false,
  replied = false, subject_changed = false, threaded = false, display_subject = false, recip_valid = false, active = false, trash = false, xlabel_changed = false, zhours = 0, zminutes = 0, zoccident = false, searched = false,
  matched = false, attach_valid = false, collapsed = false, limited = false, num_hidden = 94923199794608, recipient = -22496, pair = 22101, date_sent = 94923184554256, received = 94923184554256, offset = 33, lines = 112346032,
  index = 22101, msgno = 127585616, virtual = 22101, score = 0, env = 0x41, content = 0x1b0, path = 0x0, tree = 0x5655079ace10 "\260", thread = 0x5655079acf30, attach_total = -12976, refno = 22101, tags = {stqh_first = 0x565506b24820,
    stqh_last = 0x565506b24820}, data = 0x21, free_cb = 0x565506b25040, maildir_flags = 0x5655079acdb0 "\260\001"}
```

> i think one of the callers must have corruptable state or smthing
> in fact - following the stracktrace all the way back shows that h->env is always 0x41 so something isn't setting it appropriately
> i can also reproduce this with no config other than to connect to an imap server and it still segfaults in the same way
> i have to go now though - thanks for your time

**Note:**  A first attempt to fix this, #846 didn't work.

**Comment by ThomasAdam** [comment]
I was just bitten by this, and in my fly-by-patch analysis, I can see this has nothing to with `h->env`.  I think, @flatcap that's a red-herring.

Digging further down the stacktrace, I've wound up in `imap/imap.c:imap_sync_mailbox()` where we're iterating over `ctx->msgcount`.  In looking at this, we see:

```
(gdb) p ctx->msgcount
$14 = 739
```

The code in `imap_sync_mailbox()` assigns the a `struct Header *h` variable off the `ctx->hdrs` list, going from 0 -> `ctx->msgcount`.

It looks as though there's an issue with how we're counting messages?   Certainly the root cause is that accessing `ctx->hdrs[739]` in this case (the upper value of `ctx->msgcount`) is off-by-one.   Here:

```
(gdb) p ctx->msgcount
$14 = 739

(gdb) p *ctx->hdrs[739]->env
Cannot access memory at address 0x48
```

So this is why we end up all the way in `mutt_pattern_exec()` with garbage -- we're propagating it from way down.

The following "botch" fixes the issue for me:

```
diff --git a/imap/imap.c b/imap/imap.c
index 87abaca5..651bea25 100644
--- a/imap/imap.c
+++ b/imap/imap.c
@@ -1508,7 +1508,7 @@ int imap_sync_mailbox(struct Context *ctx, int expunge)
 #endif

   /* save messages with real (non-flag) changes */
-  for (int i = 0; i < ctx->msgcount; i++)
+  for (int i = 0; i < ctx->msgcount - 1; i++)
   {
     h = ctx->hdrs[i];
```

I am not saying this is the correct thing to do -- but I do think it's a better band-aid than what fixed #846 as that's littering the code base in the wrong way, IMO.

Assuming no one else beats me to digging into this further, I'll leave it here for others to look at.

**Comment by gahr** [comment]
I don't see how the original `for` loop could end up accessing `ctx->hdrs[i]` when `i == ctx->msgcount`.

**Comment by flatcap** [comment]
> I was just bitten by this,

Can you give us some more details.
I've spent ages trying to repeat this, but have failed.

> nothing to with h->env
> littering the code 

I didn't think that was the problem,
but given the general flakiness of the code, checking pointers before use is still worth doing.

> The following "botch" fixes the issue for me:

Really?  So, the msgcount is off-by-one.

```diff
-  for (int i = 0; i < ctx->msgcount; i++)
+  for (int i = 0; i < ctx->msgcount - 1; i++)
```

No, the loop is correct as it is.
If we alter it, then the last email will be ignored (in any other condition than when the bug occurs)

But this might be in order:
```diff
   for (int i = 0; i < ctx->msgcount; i++)
   {
     h = ctx->hdrs[i];
+    if (!h)
+      continue;
```

**Comment by ThomasAdam** [comment]
I wish I could give more information, other than I break a thread, and press 'enter' to view the email, and kaboom, NeoMutt segfaults.  I've not had to do anything special, and I don't think it's linked to different compiled-in features or anything like that.

I'll see if checking for `h == NULL` has the same effect, but it didn't seem to help when I was trying to debug this.  Will let you know.

Thanks!
Thomas
