### ISSUE TITLE
backtab does not work with slang

### ISSUE THREAD

**Issue by prometheanfire** [neomutt/neomutt#878]
The particular binding I use backtabs with (that does not work with slang) is:

    bind index,pager <backtab> next-unread-mailbox

**Comment by flatcap** [comment]
Thanks for the bug report @prometheanfire.

Building from master, using config:

```
bind index <tab>     next-entry
bind index <backtab> previous-entry
```

Then view the help page <kbd>?</kbd>

Using curses, I see:
```
<Tab>     next-entry     move to the next entry
<BackTab> previous-entry move to the previous entry
```

Using slang, I see:
```
<Tab>     next-entry     move to the next entry
<backtab  previous-entry move to the previous entry
```

Note the missing `>`

**Comment by flatcap** [comment]
I did a little testing.  This bug is in upstream mutt, too.
(I tested mutt-1.9.1, 1.8.0, 1.7.0, 1.6.0, 1.5.24)

**Comment by prometheanfire** [comment]
Perhaps it's fixed in the mutt gentoo package as I was using 1.9.1 on gentoo before this.  But at least it's reproducible :D

**Comment by flatcap** [comment]
I just spun up my Gentoo VM and had a closer look.

By default, Gentoo's Mutt uses curses (and `<backtab>` works).
When I `USE="slang"`, Mutt doesn't understand `<backtab>` any more.

There's further evidence in the header files.
curses.h contains a definition for `KEY_BTAB`, but slang.h doesn't.

Conclusion: It's a limitation of slang.
