### ISSUE TITLE
Release 2017-10-13 fails to build on macOS <= 10.6

### ISSUE THREAD

**Issue by lbschenkel** [neomutt/neomutt#879]
I am the maintainer of NeoMutt in MacPorts. I have updated it to the latest version, 2017-10-13, and I was notified by the buildbots that it fails to build on macOS versions 10.6 and earlier:

https://build.macports.org/builders/ports-10.6_x86_64_legacy-builder/builds/44056/steps/install-port/logs/stdio
```
/usr/bin/gcc-4.2 -o neomutt account.o addrbook.o alias.o attach.o bcache.o body.o browser.o buffy.o charset.o color.o commands.o complete.o compose.o compress.o conststrings.o copy.o curs_lib.o curs_main.o edit.o editmsg.o enter.o envelope.o filter.o flags.o from.o getdomain.o group.o handler.o hdrline.o headers.o help.o history.o hook.o init.o keymap.o main.o mbox.o mbyte.o menu.o mh.o muttlib.o mutt_idna.o mutt_sasl_plain.o mutt_socket.o mutt_tags.o mutt_tunnel.o mx.o newsrc.o nntp.o pager.o parameter.o parse.o pattern.o pop.o pop_auth.o pop_lib.o postpone.o query.o recvattach.o recvcmd.o rfc1524.o rfc2047.o rfc2231.o rfc3676.o rfc822.o safe_asprintf.o score.o send.o sendlib.o sidebar.o signal.o smtp.o sort.o state.o status.o system.o thread.o url.o version.o resize.o mutt_ssl.o libmutt.a libncrypt.a libimap.a -L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64  -lidn -lz -lssl -lcrypto -lncursesw -lintl -liconv
Undefined symbols:
  "_wcscasecmp", referenced from:
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
      _text_enriched_handler in handler.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make: *** [neomutt] Error 1
```
I have updated the port to use `autosetup` to build, so I'm not sure if this regression was due to a code change or due to the build system change. 

**Edit**: it looks like it's due to autosetup, since I saw that the code has a replacement for `wcscasecmp` and I don't see any checks for the presence of this function in the log file I linked to.

**Comment by gahr** [comment]
Thanks for the report, @lbschenkel ! Can you please try the branch `devel/issue-879` and see whether it fixes the build for you? Unfortunately, I don't have access to such a system.

**Comment by lbschenkel** [comment]
Thanks, I don't have access to these versions as well but I will ask for help in the MacPorts community to test this change and I'll get back to you.

**Comment by lbschenkel** [comment]
Hi @gahr, one user reported back saying that the patch worked. However, I think he also might have uncovered a different issue — once I get the `config.log` I'll see if I can reproduce it and report it as a new ticket. 

I would appreciate if you could anticipate the timing of the next release (either a "full" or a "patch") so I can decide if I should incorporate this patch and have a special bug fix release downstream or just wait for the next upstream, in case you plan to do it soon.

**Comment by flatcap** [comment]
> timing of the next release

I wasn't planning a release, but given how many tweaks we've made to the build...
None of the changes look too risky.

Can you hang on 'til next Friday?

**Comment by lbschenkel** [comment]
Actually it turned out that the new preliminary revision I've made downstream to test the patch has been merged and now published to users, so I no longer have the option to wait for the next upstream (I was trying to avoid adding a patch file I would need to subsequently remove). This means that from my perspective there's no need to rush.
