### ISSUE TITLE
consider removing hard-coded color commands from pgp tags; and when a message-hook filter fails, mutt should display the unfiltered content

### ISSUE THREAD

**Issue by libBletchley** [neomutt/neomutt#897]
I have this config line, which worked fine with older versions of mutt:
```
message-hook '~f .*@hushmail.com'  "set display_filter='dos2unix'"
```
The purpose of that line is to deal with the fact that we see a caret-M ("`^M`") at the end of each line if receiving an encrypted message that was sent from a hushmail server.

   * Expected behavior
The message should display correctly without being junked up with `^M`s.  And even if `dos2unix` (or any other filter tool) were to have a non-zero exit code, I would expect mutt to display the unfiltered content.  In fact this worked as expected in the previous version of mutt that was distributed with Debian Jessie.

    * Actual behavior
Now after entering the PGP password to decrypt the message, this blob appears on the screen, and the plaintext is no longer shown:
```
PGP message successfully decrypted.dos2unix: Binary symbol 0x1B found at line 8                                                             
                                                                               dos2unix: Skipping binary file stdin
                                                                                                                   Press any key to continue...
```
The knee-jerk thought is that the bug is in dos2unix, not mutt.  So to test that theory, I saved the pgp attachment to a file, and ran the same command mutt is configured to run: `gpg --decrypt --passphrase-fd 0 --pinentry-mode loopback --no-verbose --quiet  --batch  --output - message.html.pgp | dos2unix` and it worked fine (no error).  So it seems mutt is now introducing a "Binary symbol 0x1B" somehow.

   * Steps to reproduce
1. put your public key on the hushmail keyring at hushtools.com, and make sure the key contains your external email address
2. have a hushmail user send you an encrypted email to the address on the key you just submitted
3. add this to your configs `message-hook '~f .*@hushmail.com'  "set display_filter='dos2unix'"`
4. when the encrypted message arrives, run it through this sed command before opening it:
```
sed -e 's@^Content-Type: text/plain.*@Content-Type: application/pgp; format=text; x-action=encrypt@'
```
5. Try to open it in mutt.

Note about step 4: it may not be necessary to do step 4.  That sed command is what my procmail recipe runs on all inbound hushmail msgs to make mutt treat them as encrypted messages.  It's possible that over the years hushmail has fixed that (in which case the sed command would have no impact).. I have no idea ATM.

   * Used program versions
failing version: NeoMutt 20170113 (the current Debian Stretch version)
working version: whatever version of mutt is distributed with debian jessie

   * Operating System and its version
Debian Stretch

Note there are two bugs here:

1. binary content sent to the message filter (regression)
2. when a msg filter fails, mutt fails to show the unfiltered content (probably always existed)

**Comment by gahr** [comment]
Thanks for the detailed report. Any chance you can put here or upload somewhere a sample email that exhibits this behaviour? Since PGP comes into play before the filter, an unencrypted version (post pgp —decrypt) would be best and should do the trick just as well.

**Comment by libBletchley** [comment]
In the course of trying to create a usable and minimal reproducer, I encountered this bug: https://github.com/neomutt/neomutt/issues/900.

Perhaps I can get around that.  I'll see what I can come up with.

**Comment by gahr** [comment]
I have the vague feeling that something's off with your PGP setup... same as for #900, would you consider switching to GPGMe?

**Comment by libBletchley** [comment]
Just as with bug 900, switching to gpgme makes no difference.  The only thing left for me to try is a bleeding-edge version of neomutt.

**Comment by libBletchley** [comment]
I ran `configure.autosetup` and got: `Error: Unable to find xsltproc`

This is in the INSTALL file:
```
- For building the manual, mutt needs the DocBook XSL stylesheets
  as well as the DocBook DTD as of version 4.2 installed locally.
```
I already have the `docbook-xsl` package installed (it's a requirement of okular).  What am I missing?

**Comment by gahr** [comment]
Uhm, that's installed by libxslt on FreeBSD, dunno about Debian.

**Comment by gahr** [comment]
https://packages.debian.org/search?keywords=xsltproc does this help?

**Comment by libBletchley** [comment]
Thanks, i got past the xsltproc error.  Now I have this: `Error: Unable to find ncursesw library`

I do have the `libncursesw5` package installed.  So I tried this: `./configure.autosetup --with-ncurses=/lib/x86_64-linux-gnu/libncursesw.so.5` and same problem: `Error: Unable to find ncursesw library`.

**Comment by gahr** [comment]
I think it's custom on Linux to provide shared libraries and headers in two different libraries. I think you're looking for `libncursesw5-dev`.

**Comment by gahr** [comment]
https://www.neomutt.org/distro/debian mentions using `apt-get build-dep mutt` to install all build dependencies.

**Comment by libBletchley** [comment]
Thanks, that should normally make it easy.. but things are getting dicey:
```
  $ aptitude build-dep mutt
  Unable to satisfy the build-depends: Build-Depends: libgpgme11-dev
  Unable to apply some actions, aborting
```

**Comment by gahr** [comment]
I am totally not familiar with Debian, so I can't help much. Do you have `libncursesw5-dev` installed by now? Does it still say `Error: Unable to find ncursesw library` ?

**Comment by libBletchley** [comment]
I had the `libncurses5-dev` package installed before I even started.  ATM i'm stuck.  `./configure.autosetup` gives "Error: Unable to find ncursesw library" and `aptitude --log-level=debug build-dep mutt` gives:
```
Unable to satisfy the build-depends: Build-Depends: libgpgme11-dev
Unable to apply some actions, aborting
```
even though I've been able to install `libgpgme11-dev`.

**Comment by gahr** [comment]
Can you post your config.log?

**Comment by libBletchley** [comment]
```
Invoked as: ./configure.autosetup 
Failed: cc -g -O2 -std=c99 -c -std=c99 conftest__.c -o conftest__.o
conftest__.c:1:26: fatal error: minix/config.h: No such file or directory
 #include <minix/config.h>
                          ^
compilation terminated.
child process exited abnormally
============
The failed code was:
#include <minix/config.h>
int main(void) {

return 0;
}
============
Failed: cc -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -c -std=c99 -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ conftest__.c -o conftest__.o
conftest__.c: In function ‘main’:
conftest__.c:8:6: error: #error little
     #error little
      ^~~~~
child process exited abnormally
============
The failed code was:
#include <sys/types.h>
#include <sys/param.h>
int main(void) {

			#if !defined(BIG_ENDIAN) || !defined(BYTE_ORDER)
				#error unknown
			#elif BYTE_ORDER != BIG_ENDIAN
				#error little
			#endif
		
return 0;
}
============
Failed: cc -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -c -std=c99 -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ conftest__.c -o conftest__.o
conftest__.c: In function ‘main’:
conftest__.c:3:12: error: size of array ‘_x’ is negative
 static int _x[sizeof(off_t) == 4 ? 1 : -1] = { 1 };
            ^~
child process exited abnormally
============
The failed code was:
#include <sys/types.h>
int main(void) {
static int _x[sizeof(off_t) == 4 ? 1 : -1] = { 1 };
return 0;
}
============
Failed: cc -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -c -std=c99 -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ conftest__.c -o conftest__.o
conftest__.c:1:19: fatal error: ioctl.h: No such file or directory
 #include <ioctl.h>
                   ^
compilation terminated.
child process exited abnormally
============
The failed code was:
#include <ioctl.h>
int main(void) {

return 0;
}
============
Failed: cc -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -std=c99 -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ conftest__.c -o conftest__
/tmp/cc6jRcWi.o: In function `main':
/home/user/tools/src/neomutt/conftest__.c:3: undefined reference to `getaddrinfo_a'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void getaddrinfo_a(void);
int main(void) {
getaddrinfo_a();
return 0;
}
============
Failed: cc -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -std=c99 -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include conftest__.c -o conftest__ -L/usr/lib -lintl -lanl
/usr/bin/ld: cannot find -lintl
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:

        #include <libintl.h>
        extern int _nl_msg_cat_cntr;
        extern int *_nl_domain_bindings;
        int main(void)
        {
            bindtextdomain("", "");
            return * gettext("");
        }
    
============
Failed: cc -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -std=c99 -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ conftest__.c -o conftest__ -lintl -lanl
/usr/bin/ld: cannot find -lintl
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:

        #include <libintl.h>
        extern int _nl_msg_cat_cntr;
        extern int *_nl_domain_bindings;
        int main(void)
        {
            bindtextdomain("", "");
            return * gettext("");
        }
    
============
Failed: cc -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -std=c99 -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ conftest__.c -o conftest__ -L/usr/lib -lanl
/tmp/ccoSC0ZV.o: In function `main':
/home/user/tools/src/neomutt/conftest__.c:3: undefined reference to `waddnwstr'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void waddnwstr(void);
int main(void) {
waddnwstr();
return 0;
}
============
Failed: cc -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -std=c99 -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ conftest__.c -o conftest__ -lncursesw -L/usr/lib -lanl
/usr/bin/ld: cannot find -lncursesw
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void waddnwstr(void);
int main(void) {
waddnwstr();
return 0;
}
============
Failed: cc -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -std=c99 -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ conftest__.c -o conftest__ -lncurses -L/usr/lib -lanl
/tmp/ccpseio5.o: In function `main':
/home/user/tools/src/neomutt/conftest__.c:3: undefined reference to `waddnwstr'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void waddnwstr(void);
int main(void) {
waddnwstr();
return 0;
}
============
Failed: cc -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -std=c99 -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ conftest__.c -o conftest__ -lcurses -L/usr/lib -lanl
/tmp/ccfQJ4Vb.o: In function `main':
/home/user/tools/src/neomutt/conftest__.c:3: undefined reference to `waddnwstr'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void waddnwstr(void);
int main(void) {
waddnwstr();
return 0;
}
============
```

**Comment by mgedmin** [comment]
@libBletchley note that libncurses5-dev and libncurses**w**5-dev are different packages.  Be sure you have the wide-char version installed too!

If `sudo aptitude build-dep mutt` fails, can you try `sudo apt-get build-dep mutt` instead?

**Comment by libBletchley** [comment]
@mgedmin 
Good catch!  Indeed I did not have libncurses**w**5-dev, and to my surprise `apt-get build-dep mutt` works.  I suppose that's an aptitude bug I should report.  So now `./configure.autosetup` works, ending with:
```
Summary of build options:

  Version:           20171013
  Host OS:           linux-gnu
  Install prefix:    /usr
  Compiler:           cc
  CFlags:            -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__  -I/usr/include
  LDFlags:           -L/usr/lib
  Libs:              -lidn -lncursesw -lanl 
  Header cache libs: 

  GPGME:             no
  PGP:               yes
  SMIME:             yes
  Notmuch:           no
  Header Cache(s):   
  Lua:               no
```
What next?  Instructions say to run `make install`, skipping the `make all` that normally runs before that.  I don't really want to install the thing and muddy things w/the official debian version.

**Comment by gahr** [comment]
config.log seems to confirm @mgedmin's suspects, in that the compiler cannot find libncursesw.so

```
Failed: cc -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -std=c99 -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ conftest__.c -o conftest__ -lncursesw -L/usr/lib -lanl
/usr/bin/ld: cannot find -lncursesw
```

**Comment by gahr** [comment]
Ah, I came late to the party. @libBletchley good to know you could configure it. Please just run `make`, it will create a `neomutt` executable in the working directory.

**Comment by libBletchley** [comment]
okay, i simply ran `make`.  Looks like possibly an unhappy ending:
```
...
map smime undefined at ./doc/gen-map-doc line 62, <XML> line 21.
map mixmaster undefined at ./doc/gen-map-doc line 62, <XML> line 22.
xsltproc --nonet -o doc/ ./doc/chunk.xsl doc/manual.xml > /dev/null 2>&1
xsltproc --nonet -o doc/manual.html ./doc/html.xsl doc/manual.xml
Error: no ID for constraint linkend: "header-cache".
Error: no ID for constraint linkend: "header-cache-backend".
Error: no ID for constraint linkend: "header-cache".
Error: no ID for constraint linkend: "mix-entry-format".
LC_ALL=C w3m -dump -O UTF8 doc/manual.html > doc/manual.txt || \
LC_ALL=C lynx -dump -nolist -with_backspaces \
        -display_charset=us-ascii doc/manual.html > doc/manual.txt || \
LC_ALL=C elinks -dump -no-numbering -no-references \
        doc/manual.html | sed -e 's,\\001, ,g' > doc/manual.txt
sed -e 's,@docdir@,/usr/share/doc/neomutt,' ./doc/neomuttrc.head \
    > doc/neomuttrc
cc -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_MAKEDOC -E -C -I. ./init.h | doc/makedoc -c \
    >> doc/neomuttrc
cc -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_MAKEDOC -E -C -I. ./init.h | doc/makedoc -m | \
        cat ./doc/neomuttrc.man.head - \
        ./doc/neomuttrc.man.tail > doc/neomuttrc.man
```

**Comment by gahr** [comment]
`./configure.autosetup --gpgme`

**Comment by libBletchley** [comment]
Bleeding-edge version 20171013-49-42f391 still fails in the same way.. dos2unix chokes.

**Comment by gahr** [comment]
Ok so we figured it's not about PGP or GPGMe. Let's put them aside and concentrate on dos2unit's input. Can you post that?

**Comment by libBletchley** [comment]
I changed the config to this: `message-hook '~f .*@hushmail.com'  "set display_filter='tee -a /tmp/sample_msg.txt'"` which produced a file with the same contents that was fed to `dos2unix`.  The file is attached:
[sample_msg.txt](https://github.com/neomutt/neomutt/files/1424037/sample_msg.txt)

**Comment by libBletchley** [comment]
I repeated the process with the old working version of mutt, and it produced the same output.  And so I fed the old mutt output to the new `dos2unix` and it choked on the binary.  This means `dos2unix` changed and there is no regression in mutt.

**workaround**
Adding a `-f` to `dos2unix` to force processing of binary input works in the case of filtering hushmail msgs in mutt.

**remaining problems**
Perhaps it should still be investigated why mutt is producing binary data, as users install filters with an expectation that the filter input is plaintext.  And there's also still the issue of handling cases where a filter returns with a non-zero exit code, in which case I believe mutt should show the unfiltered content.

**Comment by mgedmin** [comment]
That's a terminal control command.  ESC ] is "Operating System Command (OSC)", but OSC 9 is not defined by http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Operating-System-Commands.  Was that one of the digits you changed?

Maybe consider an alternative filter that leaves doesn't get confused by terminal control sequences, e.g. `tr -d '\r'`?

**Comment by libBletchley** [comment]
Ah, sorry, i shouldn't have tampered with that number.  It's `9;5491425466969332505`.  Indeed I can see the shade of black in the background change on the lines that have that code.

**Comment by mgedmin** [comment]
What terminal program do you use?  What's the value of the `TERM` environment variable?  I'm now very curious about OSC 9, but it's hard to google for, and the hits I find seem unlikely ([ConEmu on windows uses these](https://conemu.github.io/en/AnsiEscapeCodes.html#OSC_Operating_system_commands) for all sorts of things; [iTerm2 uses these for Growl notifications](https://blog.vucica.net/2017/07/what-are-osc-terminal-control-sequences-escape-codes.html)).

**Comment by libBletchley** [comment]
IMO, the elegant fix of defering the terminal control command injection until after the filter runs is perhaps not worth the effort.  But I do think the error handling could improve so that error output is handled by the new notification logic: https://github.com/neomutt/neomutt/issues/802, while unfiltered content is presented.

**Comment by libBletchley** [comment]
> What terminal program do you use? What's the value of the TERM environment variable?
I use _terminator_ for the terminal, and _GNU screen_ within that, giving a `$TERM` of `screen.xterm-256color`.

**Comment by libBletchley** [comment]
> What terminal program do you use? What's the value of the TERM environment variable?

I use _terminator_ for the terminal, and _GNU screen_ within that, giving a `$TERM` of `screen.xterm-256color`.

**Comment by mgedmin** [comment]
> IMO, the elegant fix of defering the terminal control command injection until after the filter runs is perhaps not worth the effort.

If even possible -- it might be gpg that's adding those terminal control sequences.

> I use terminator for the terminal, and GNU screen

Terminator uses libVTE which [doesn't know anything about OSC 9](https://github.com/GNOME/vte/blob/d8146f747f3b55aff3e5b838f77da08653d117a3/src/caps.cc#L228-L229).

GNU screen doesn't either, according to https://www.gnu.org/software/screen/manual/html_node/Control-Sequences.html

I remain mystified.

**Comment by libBletchley** [comment]
This is a screen capture of a hushmail msg in my terminal (w/sensitive bits clipped).  You can see the alternating shade of the black background.

![mutt_hushmail_screencap](https://user-images.githubusercontent.com/18015852/32319068-812ea020-bfb9-11e7-93c8-bac9b1d9cbb2.png)

**Comment by flatcap** [comment]
OK, I understand what's going on now.  It took a couple of hours, though.
It's been a part of the upstream code since 2001.

NeoMutt is inserting the strange escape sequence.  It does it so that it can confidently identify the PGP lines it's added.
There are a couple of solutions, neither are particularly good:

1. Filter out the escape sequence using the `ansifilter` program
   `message-hook '~g' "set display_filter='ansifilter | tee -a /home/mutt/work/neo/sample_msg.txt'"

2. Apply the patch in #924, which prevents the escape sequence being inserted when using `$display_filter`
   This PR is a hack, not a solution.

Either way, you'll have to add your own colouring config to compensate:
    `color body magenta default '^\[-- .* --\]$'`

**Comment by flatcap** [comment]
OK, there's been a change of plan.
After a lot of discussion on IRC, I've made the decision to not fix this.

We thought up and shot down a **lot** of possible alternatives, but...

- Mutt's behaved this way for a long time
- The escape sequence was introduced to avoid false positives when colouring headers
- Simple workarounds exist
  * `ansifilter`
  * `sed 's/^\x1b]9;[0-9]\+\x7//'`

For your specific case, I found a better solution: `tr -d '\r'`
This deletes those CR chars and it doesn't care about the escape sequences.

I'll document `$display_filter`, the escape sequence and the possible workarounds.
I'll move the PR to the [neomutt-old](https://github.com/neomutt/neomutt-old) repo.

**Comment by libBletchley** [comment]
> Mutt's behaved this way for a long time

That's conventional wisdom.  I would hope that old bugs would not persist on the basis of being old.

> The escape sequence was introduced to avoid false positives when colouring headers

That's kind of reasonable.. but OTOH, it seems like overengineering; overengineering that can still go wrong.  That is, what if the user is on a mono terminal- wouldn't those codes be printed literally?

> Simple workarounds exist

Fair enough.. that's actually the strongest argument.  It should have very low priority in the triage.

**Comment by flatcap** [comment]
> > Mutt's behaved this way for a long time

> That's conventional wisdom and should be scrapped.

It was less of an excuse, more an expression of surprise.

> I would hope that old bugs would not persist on the basis of being old.

Certainly not.
There are so many features and so many users of (Neo)Mutt...
Whatever changes we make, they're certain to break someone's workflow.
We just want to cause as little harm as possible.

> what if the user is on a mono terminal- wouldn't those codes be printed literally?

They **shouldn't** be.
The standard practices for escape sequences that aren't understood/supported is to completely ignore them.  Which is why NeoMutt can get away with this.

> > The escape sequence was introduced to avoid false positives when colouring headers

> That's kind of reasonable.. but OTOH, it seems like overengineering;

Quite possibly, but it makes absolutely sure that someone can't send an malicious email that will be highlighted the same as a safe email, e.g. an email body starting:
```
[-- PGP Good signature from X --]
...
```

> > Simple workarounds exist

If we find it causes problems for more people we can always reopen this issue.

**Comment by andreas-bulling** [comment]
This seems to be the only mentioning of this problem before: I am trying to install the latest neomutt HEAD with homebrew (July 20) but receive the following error:

`make install
Last 15 lines from /Users/user/Library/Logs/Homebrew/neomutt/02.make:
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test/neomutt-test] Error 1
make: *** Waiting for unfinished jobs....
installing /usr/local/Cellar/neomutt/HEAD-22813cd/share/locale/nl/LC_MESSAGES/neomutt.mo
installing /usr/local/Cellar/neomutt/HEAD-22813cd/share/locale/pl/LC_MESSAGES/neomutt.mo
installing /usr/local/Cellar/neomutt/HEAD-22813cd/share/locale/pt_BR/LC_MESSAGES/neomutt.mo
installing /usr/local/Cellar/neomutt/HEAD-22813cd/share/locale/ru/LC_MESSAGES/neomutt.mo
installing /usr/local/Cellar/neomutt/HEAD-22813cd/share/locale/sk/LC_MESSAGES/neomutt.mo
installing /usr/local/Cellar/neomutt/HEAD-22813cd/share/locale/sv/LC_MESSAGES/neomutt.mo
installing /usr/local/Cellar/neomutt/HEAD-22813cd/share/locale/tr/LC_MESSAGES/neomutt.mo
installing /usr/local/Cellar/neomutt/HEAD-22813cd/share/locale/uk/LC_MESSAGES/neomutt.mo
installing /usr/local/Cellar/neomutt/HEAD-22813cd/share/locale/zh_CN/LC_MESSAGES/neomutt.mo
installing /usr/local/Cellar/neomutt/HEAD-22813cd/share/locale/zh_TW/LC_MESSAGES/neomutt.mo
Error: no ID for constraint linkend: "mix-entry-format".`
