### ISSUE TITLE
sidebar colour config renames

### ISSUE THREAD

**Issue by 257** [neomutt/neomutt#9]
similar to https://github.com/neomutt/neomutt/issues/8 i guess; missing compared to mutt-kz.

**Comment by flatcap** [comment]
Here's a list of the [Sidebar colours](https://github.com/neomutt/neomutt/wiki/sidebar#colors).
If you build the Mutt docs, there's a sections "Config Changes" in the Sidebar Introduction.
I knew I'd documented the changes somewhere.

**Comment by 257** [comment]
thanks, it's all good now.
