### ISSUE TITLE
decrypt-copy command does not save the decrypted contents

### ISSUE THREAD

**Issue by libBletchley** [neomutt/neomutt#900]
* Expected behavior
The `decrypt-copy` command should do what it's documented to do: "make decrypted copy".  That's actually the full documentation from [the manual](http://www.mutt.org/doc/manual/), documented only in the key bindings table.

 * Actual behavior
It takes the same action as the `copy-message` command.  That is, both the `decrypt-copy` and `copy-message` commands prompt for a GPG password, and both of them throw away the decrypted output from gpg and store the original encrypted content.

 * Steps to reproduce
1. Put the cursor on a "P"-indicated message (in my case it was a hushmail-composed msg)
2. Type `:exec decrypt-copy`
3. Save it as `decrypted_msg.mbox`
4. Type `:exec copy-message`
5. Save it as `encrypted_msg.mbox`
6. Run `diff encrypted_msg.mbox decrypted_msg.mbox`
Notice there are no differences when there should be a world of difference.  Open decrypted_msg.mbox in a text editor and notice that it's encrypted.

Used this config: `set pgp_decrypt_command="/usr/bin/gpg --decrypt --passphrase-fd 0 --pinentry-mode loopback --no-verbose --quiet  --batch  --output - %f"`

 * Used program versions
NeoMutt 20170113 (the current Debian Stretch version)
$ gpg --version
```
gpg (GnuPG) 2.1.18
libgcrypt 1.7.6-beta
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/blee/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```
 * Operating System and its version
Debian Stretch

**Comment by gahr** [comment]
I can't reproduce that behaviour. Could you please try:
* a more recent version of NeoMutt
* using GPGMe as a backend?

**Comment by libBletchley** [comment]
> using GPGMe as a backend?

I didn't know about gpgme, but it looks like something I should be using anyway.  What do you suggest for the `pgp_decrypt_command` variable?

**Comment by gahr** [comment]
With PGPMe you don't have to specify any of the pgp_* variables. Just set `set crypt_use_gpgme = yes` and you should be good to go.

**Comment by libBletchley** [comment]
Does having the pgp_* variables defined interfere with `set crypt_use_gpgme = yes`?  I would expect a setting of `set crypt_use_gpgme = yes` to cause pgp_* vars to be ignored.  Anyway, I have made the change, and the bug still manifests.

Note that I previously had this in my config file for smime settings:
```
# This is needed after migrating to stretch because it changes the
# default to using gpgsm.  Although gpgsm is probably better, I already
# have keys and profiles in place with openssl and smime-keys.
#
unset crypt_use_gpgme
```
As you can see, I was confusing gpgme with gpgsm.  But correcting that didn't help.

**Comment by libBletchley** [comment]
Even when I remove all instances of `set pgp_*_command`, and I have `set crypt_use_gpgme = yes`, and a build with +CRYPT_BACKEND_GPGME, it still fails.

I still have a lot of customizations like: `send-hook  '=t @mac.hush.com'     	    'set pgp_create_traditional=yes'`.  Would that stop gpgme from working?  I'm assuming not, so the only thing left for me to try is a bleeding-edge neomutt.

**Comment by gahr** [comment]
I would try with a minimal muttrc, and incrementally add suspect settings like anything mentioning pgp.

**Comment by libBletchley** [comment]
I'm no longer being redundantly asked for a gpg password, so gpgme must be in play.  And so a minimal config wouldn't make a difference.

**Comment by libBletchley** [comment]
So I have a bleeding-edge version now, gpgme enabled, and `decrypt-copy` still produces an encrypted msg.
