### ISSUE TITLE
segmentation fault when doing a "copy-message" to an unpermitted path

### ISSUE THREAD

**Issue by libBletchley** [neomutt/neomutt#901]
* Expected behavior
If you tell mutt to write a file to a directory where you do not have write permission, mutt should simply state the problem and take no action.
 * Actual behavior
Mutt crashes with a segmentation fault:
```
/foo.txt: Permission denied (errno = 13)Segmentation fault
```
 * Steps to reproduce
Select a message as a user, and issue the `copy-message` command.  Specify the file is `/foo.txt` (assuming the user does not have write permission to `/`.
 * Used program versions
NeoMutt 20170113 (the current Debian Stretch version)
 * Operating System and its version
Debian stretch

**Comment by gahr** [comment]
Would you please try to test a newer version? The current master branch gives me `/foo.txt: Permission denied (errno = 13)`, and no crash.

**Comment by libBletchley** [comment]
When I repeat this in a version of neomutt that is only 2 weeks old, there is no crash, just a proper error msg.
