### ISSUE TITLE
Warn mutt-S/MIME users when they're about to (unwittingly) hack iOS users

### ISSUE THREAD

**Issue by libBletchley** [neomutt/neomutt#903]
I've accidentally discovered a security bug in iPhones while using mutt's very flexible behavior w.r.t address matching on S/MIME certs.  That is, mutt will allow a sender's e-mail address to mismatch the address associated to the S/MIME signing key.  This can cause problems for iPhone users.  Here is the reproducer:

1. Create an S/MIME key pair and import it into mutt using the `smime_keys` script.
2. Compose a message to an iPhone 5* user and S/MIME sign it.  Be sure to use an address that differs from the address that is included in the metadata of the S/MIME certificate that is used for signing.
3. Have the recipient import (aka "install" in mail.app terms) the certificate from the signature.
4. Compose another message in mutt, this time using the proper `From:` address that matches that of the S/MIME certificate that you sign it with.
5. Have the recipient import the certificate again from the signature, but this time from the 2nd message.
6. Send more properly signed messages (with `From:` address matching that of the cert).  When opened these messages will put mail.app in an infinite loop.

(*) Tested on iPhone 5 -- it's unclear if other devices are impacted.

**3 feature requests**

1. Create a new warning that will check consistency between the `From:` field and the S/MIME signing key.  Perhaps the warning should offer these remedies for the user to choose from:
* Update `From:` field to match the cert.
* Select a different S/MIME key.
* Ignore and send.

2. Smarten the default key mechanism to be more sensible.  The `set smime_default_key` variable should not be hard and fast.  Instead, mutt should first look at the `From:` field and choose (by default) the key to be one that matches.  If there is no match, only then should the `set smime_default_key` variable apply.  At the same time, the user must ultimately have control, and so the setting of the `smime_sign_as` variable (if it is set) should trump all.

3. For transparency, add some humanity to the `sign as:` field.  Instead of: `sign as: f43da3cb.0`, show `sign as: f43da3cb.0 (bob@theagency.net)`

**Bug**
The `smime_sign_as` variable is secretly documented in a ["Thawte and Mutt - playing nicely?" article](http://equiraptor.com/smime_mutt_how-to.html), but does not appear in the mutt manual.  Yet mutt does not error when parsing config files that set that variable, which indicates that it must be an actual variable that's simply undocumented.  And worse, the article describes it the same way as the mutt manual describes the `smime_default_key` variable.  So the documentation should be updated to include it.

**Comment by gahr** [comment]
> Bug
The smime_sign_as variable is secretly documented in a "Thawte and Mutt - playing nicely?" article, but does not appear in the mutt manual.

`smime_sign_as` is a synonym for `smime_default_key`.
