### ISSUE TITLE
crypt_use_gpgme does not default as documented

### ISSUE THREAD

**Issue by libBletchley** [neomutt/neomutt#904]
The [documentation for crypt_use_gpgme](https://dev.mutt.org/doc/manual.html#crypt-use-gpgme) states that gpgme is disabled by default, but in the absence of a setting for `crypt_use_gpgme` neomutt uses it.  It's evident because when I try to send an inline PGP message to a protonmail recipient, mutt refuses and attempts to force the use of PGP/MIME.  I could only workaround the problem by explicitly placing `unset crypt_use_gpgme` in my config file.

Either the behavior is wrong, or the documentation is wrong.  IMO, it's the behavior that should change.  GPGME has the very unacceptable limitation of being unable to sign messages and being unable to send _inline_ PGP msgs, particularly in light of the fact that everyone using hushmail ~~or protonmail~~ can [only](https://gpgtools.tenderapp.com/discussions/problems/31290-hushmail-receives-encryptedasc-attachment) receive the inlined style.  These limitations are too severe to be a default behavior.  (edit: protonmail now has pgp/mime capability)

Note that it's an annoyance that with GPG versions > 2.1 mutt causes duplicate password prompting (https://github.com/neomutt/neomutt/issues/898) which can be remedied using gpgme.  I see 2 sensible approaches ATM:

**solutions**
1. When GPGME is disabled, neomutt should stop prompting for a GPG password when it knows GPG will prompt the user graphically.  This is perhaps harder than it sounds, because it may be insufficient to query for the gpg version, as the later versions may do a textual prompt in the absence of X11.  Supposedly mutt has its own prompt b/c gpg's textual prompt doesn't appear on the screen.

2. Remove the variable `crypt_use_gpgme`, and make GPGME the default action whenever there is no overriding `pgp_*_command` (instead of ignoring them).  Then a user can have total control over the configuration, and achieve a hybrid config by defining `pgp_sign_command`, pgp_encrypt_sign_command, and  `pgp_encrypt_only_command` to micromanage the behavior just in situations where GPGME does poorly.

IMO option 2 is the most sensible.  It simplifies the config (one less variable) while actually giving more control, and also avoids the problem of allowing conflicting options and failing to warn users of such conflicts.

* Used program versions
NeoMutt 20170113 (the current Debian Stretch version)

* Operating System and its version
Debian stretch

**Comment by gahr** [comment]
Please post the ouputs from `neomutt -v` and `neomutt -DS`, plus any additional `:set...` commands you specify interactively to reach this point.

**Comment by libBletchley** [comment]
I've reproduced the problem in a more recent version.
```
$ ./neomutt -v
NeoMutt 20171013-49-42f391
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type `neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type `neomutt -vv' for details.

System: Linux 4.9.0-4-amd64 (x86_64)
ncurses: ncurses 6.0.20161126 (compiled with 6.0)
libidn: 1.33 (compiled with 1.33)

Compiler:
cc (Debian 6.3.0-18) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Configure options: --gpgme

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include 

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set -debug +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme -gss -hcache -homespool +idn -locales_hack -lua 
  +meta -mixmaster +nls -notmuch -openssl +pgp +resizeterm -sasl +smime 
  +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="false"
SYSCONFDIR="/etc"
```
I've attached the `neomutt -DS` output:
[muttcfg.txt](https://github.com/neomutt/neomutt/files/1431653/muttcfg.txt)

As far as interactive commands, I'll have to guess at the hooks that would have run.  These settings may be relevant:
```
send2-hook '^%C inline'                     'set pgp_create_traditional=yes'
send2-hook '!~g !~G !^%C pgp ^%C smime !~t keyserv' 'push <smime-menu>e'
alias -group pgp   -group inline   alice-proton  Alice  <alice@protonmail.com>
```
If I compose a new msg to a protonmail user who is not aliased, the interactive PGP menu excludes the _(i)nline_ option (indicating GPGME is set).  If I reply to a PGP msg from a protonmail user, only then is mutt fooled into the PGP inline config, which then leads to it refusing to send (this may be another bug -- b/c if GPGME is really in action, then replies should perhaps switch to PGP/MIME but ideally in a non-silent way).  In any case, I must add this to my config to get rid of GPGME: `unset crypt_use_gpgme`.

**Comment by libBletchley** [comment]
We can blame this on Debian package maintainers.  I found this in `/etc/Muttrc.d/gpg.rc`:
```
# Note from the Debian mutt maintainers: starting from 1.7.0-2 GPGME is enabled
# by default. More info in NEWS.Debian.
# THe pgp_* commands are left here for people who disable gpgme in their
# ~/.muttrc
set crypt_use_gpgme=yes
```
Yikes!

In NEWS.Debian:
```
mutt (1.7.0-2) unstable; urgency=medium

  Starting from this version, we enable 'crypt_use_gpgme=yes' by default.
  The GPGME delegates all crypto support to gnupg, which is designed to hold
  your crypto data securely.

  The drawback is that inline signatures are no longer supported in favour of
  PGP/MIME. If you need to sign your email with inline signatures please use
  'set crypt_use_gpgme=no' in your .muttrc.

  To solve #828751 we also had to add '--pinentry-mode loopback' to all commands
  in gpg.rc, that breaks compatibility with gpg v1, if you are still using gpg
  v1 please remove that option from the invocations of the command in
  /etc/Muttrc.d/gpg.rc

 -- Antonio Radici <...@debian.org>  Wed, 07 Sep 2016 21:02:51 +0100
```

**Comment by gahr** [comment]
I'm closing this, as I think if you would like to pursue solution 2, it would be better to do that in a separate dedicated issue. Thanks!

**Comment by libBletchley** [comment]
> it would be better to do that in a separate dedicated issue

I've opened https://github.com/neomutt/neomutt/issues/913
