### ISSUE TITLE
"ifdef" ignores user-defined variables

### ISSUE THREAD

**Issue by mjk-gh** [neomutt/neomutt#905]
* Expected behavior
"ifdef" should honor user-defined variables. In the example below, it should honor the
variable "my_positive", and mutt thusly should show the index in black on green.

    * Actual behavior
"ifdef" ignores user-defined variables. In the example below, it ignores the
variable "my_positive", and mutt thusly shows the index in green on black.

    * Steps to reproduce
$ mutt -v | grep -o .ifdef
+ifdef
$ cat << EOF > ~/.muttrc
set my_positive = 1
ifdef my_positive "color normal black yellow"
ifndef my_positive "color normal yellow black"
EOF
$ mutt -n

    * Used program versions
mutt 1.8.3+neomutt20170609-2+b1

    * Operating System and its version
Debian GNU/Linux, testing, amd64

**Comment by gahr** [comment]
@mjk-gh, could you please give the branch devel/issue-905 a try?

**Comment by mjk-gh** [comment]
Quickly tested (w/o Debian patches/compile time options): Works like a charm! Thank you!

**Comment by gahr** [comment]
Thanks for the prompt test!
