### ISSUE TITLE
Compile/Link issues on master

### ISSUE THREAD

**Issue by lrosenman** [neomutt/neomutt#907]
* **bug reports**

    * Expected behavior
      Clean Compile
    * Actual behavior
      link errors: https://pastebin.com/D6XJ1eX0
    * Steps to reproduce
      git clone https://github.com/neomutt/neomutt.git neomutt
      PATH=$PATH:/usr/local/Cellar/gettext/0.19.8.1/bin
      autoreconf -i
      ./configure '--prefix=/usr/local/Cellar/neomutt/20171027' '--with-ssl=/usr/local/opt/openssl' '--with-sasl' '--with-gss' '--with-kyotocabinet' '--enable-gpgme' '--enable-debug' 'CC=clang'
      make
    * Used program versions
     master as of 10:06am US/CDT (UTC-5) 2017-10-31
    * Operating System and its version
     macOS High Sierra (10.13)

**Comment by gahr** [comment]
Does the devel/issue-907 branch fixes the issue for you? @lbschenkel @lrosenman

**Comment by lbschenkel** [comment]
Yes, I can build this branch.

**Comment by lrosenman** [comment]
Sorry for the lack of response, I was offline as I out of town, and on crappy internet.  I see the issue was resolved.  Thank!
