### ISSUE TITLE
SIGPIPE when using imap

### ISSUE THREAD

**Issue by immae** [neomutt/neomutt#909]
I get a SIGPIPE at random time (usually after ~1 day of use) when I use mutt with imap.

This is a summary of the subsequent discussion in IRC (channel neomutt):

Running it with gdb gives this backtrace and `p *data`:
https://paste.ee/p/Lfcp4

`p *conn`: https://paste.ee/p/cR0yn

`p *data->ssl` and `p *data->ctx` both give `<incomplete type>`

**Comment by immae** [comment]
(gdb is still open, please contact immae on IRC for further investigation)

**Comment by immae** [comment]
> can you also inspect and see whether the connection to the imap server is still open, from the operating system's point of view?

`sudo netstat --all --program | grep 29661` is empty

**Comment by gahr** [comment]
So, your peer closes the connection while you're writing to the socket, which causes the SIGPIPE. I'm wondering why it's not being ignored, as `mutt_signal_init` seems to [imply](https://github.com/neomutt/neomutt/blob/master/signal.c#L119-L122).

**Comment by gahr** [comment]
Could you please try to send neomutt a PIPE signal manually and see how it behaves?

**Comment by immae** [comment]
Maybe gdb is responsible for catching the signal before mutt?

**Comment by immae** [comment]
Sending a SIGPIPE is ignored by mutt

**Comment by gahr** [comment]
So this was an artifact of debugging. SIGPIPE was correctly caught by gdb but would otherwise have been ignored by neomutt. I'll close this pending fresh info on the actual crash.
