### ISSUE TITLE
HCACHEVER is 0x on macOS Sierra

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#914]
* **bug reports**

    * Expected behavior
`make hcache/hcversion.h` generates a header file containing the hashing of the structures required by the header cache. With current master as of fe03e2b1, it should be `0xabf39e6c`. The script `hcache/hcachever.h` has logic to figure out the supported way to generate an md5 hash in a format compatible to binutils'. If OpenSSL is installed, it uses `openssl md5 -r`.

    * Actual behavior
MacOSX (my version is 10.12.6) ships with OpenSSL version 0.9.8zh, which does not support the `-r`flag. This was introduced in version 1.1.0.

    * Steps to reproduce
`% make hcache/hcversion.h && tail -1 hcache/hcversion.h` reports `#define HCACHEVER 0x`

    * Used program versions
master as of fe03e2b1.

    * Operating System and its version
macOS Sierra 10.12.6

**Comment by gahr** [comment]
@lbschenkel @lrosenman might I ask you for a double check on your macOS instances? Thanks!

**Comment by lbschenkel** [comment]
I cannot really tests this because I have High Sierra (10.13) installed and `/usr/bin/openssl` **does** support `md5 -r`. The port for MacPorts also uses MacPorts' `openssl`, not the system version, so at least in MacPorts land we're not affected by this in any platform.

**Comment by gahr** [comment]
Makes sense, thanks anyway!
