### ISSUE TITLE
mutt starts extremely slow now

### ISSUE THREAD

**Issue by bitstreamout** [neomutt/neomutt#92]
I see in the strace

stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2335, ...}) = 0
read(4, "ferences: <bug-696351-6237@http."..., 8192) = 8192
lseek(4, 458752, SEEK_SET)              = 458752
lseek(4, 458752, SEEK_SET)              = 458752

repeating a lot of time even for folders with only one message.   The only change is the read() line. If this is for caching then *please* in background :)

**Comment by bitstreamout** [comment]
Indeed mutt reads *all* mails I've around even those I've archived.  It should not do that as I've a *lot* of mail folders each of them with  a large archive.

**Comment by bitstreamout** [comment]
This is not usable :(

**Comment by flatcap** [comment]
Argh!
Is `$mail_check_stats` set? (Mutt/NeoMutt default to unset).
That will cause the sidebar to investigate all the folders.

Without it, the sidebar won't display the following until you open the folder:
- `%S` size/total number of messages
- `%N` number of new messages
- `%F` number of flagged messages.

I'm in #neomutt on irc.freenode.net if you want to work through this

**Comment by flatcap** [comment]
I've just run strace on neomutt-git, 20160723, 0709, 0611 and mutt-stable, mutt-default.
I don't see any significant differences in the amount of reads or lseeks.
Also, I've just tested maildir directory of 1000 folders each containing 1000 emails and it's fairly responsive.

Any more clues you can give me?

Which version are you running? 20160723?  git?
Which was the last good version for you?

**Comment by bitstreamout** [comment]
On Tue, Jul 26, 2016 at 07:26:56AM -0700, Richard Russon wrote:
> I've just run strace on neomutt-git, 20160723, 0709, 0611 and mutt-stable, mutt-default.
> I don't see any significant differences in the amount of reads or lseeks.
> Also, I've just tested maildir directory of 1000 folders each containing 1000 emails and it's fairly responsive.
> 
> Any more clues you can give me?

This part

 +  if (check_stats &&
 +      (mailbox->stats_last_checked < sb->st_mtime))
 +  {
 +    if ((ctx = mx_open_mailbox (mailbox->path,
 +                                M_READONLY | M_QUIET | M_NOSORT | M_PEEK,
 +                                NULL)) != NULL)
 +    {
 +      mailbox->msg_count       = ctx->msgcount;
 +      mailbox->msg_unread      = ctx->unread;
 +      mailbox->msg_flagged     = ctx->flagged;
 +      mailbox->stats_last_checked = ctx->mtime;
 +      mx_close_mailbox (ctx, 0);
 +    }
 +  }
 +

of neomutt-distro-20160723/features-common/0007-feature-sidebar.patch is evil
that is if I comment it out the old behaviour is back.

IMHO there should be a if (option (OPTSIDEBAR)) { ... } surround.


> 
> Which version are you running? 20160723?  git?
> Which was the last good version for you?

mutt 1.6.2 + neomutt-distro-20160723

Werner

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Comment by flatcap** [comment]
thanks, I'll investigate...

**Comment by flatcap** [comment]
hmm... that's upstream code and the `if (check_stats)` part refers to `$mail_check_stats`.

I don't think `if (option (OPTSIDEBAR)) { ... }` is the solution, here.  I think would disable **all** checking of mbox mailboxes even if you opened one.

I'll keep looking...

**Comment by bitstreamout** [comment]
I'm now using a small patch with

+  if (!option (OPTSIDEBAR))
+    return rc;

before the mentioned part.

**Comment by flatcap** [comment]
Please can you give mutt-default a try?
With and without `$mail_check_stats` set.

**Comment by flatcap** [comment]
Also, roughly how big are your mboxes?  How many 1000s of emails should I test?

**Comment by bitstreamout** [comment]
On Tue, Jul 26, 2016 at 07:54:30AM -0700, Richard Russon wrote:
> hmm... that's upstream code and the `if (check_stats)` part refers to `$mail_check_stats`.
> 
> I don't think `if (option (OPTSIDEBAR)) { ... }` is the solution, here.  I think would disable **all** checking of mbox mailboxes even if you opened one.
> 
> I'll keep looking...

Hmmm .. strange as I do not set mail_check_stats:

  werner/mutt> grep mail_check_stats ~/.muttrc /etc/Muttrc ~/.mutt/*
  werner/mutt>

... but from <F1> I see

 3.128. mail_check_stats

    Type: boolean
    Default: yes

    When set, mutt will periodically calculate message statistics of a
    mailbox while polling for new mail. It will check for unread, flagged,
    and total message counts. Because this operation is more performance
    intensive, it defaults to unset, and has a separate option,
    $mail_check_stats_interval, to control how often to update these
    counts.

ouch ... this is a job for an background thread or maybe process with
shared memory wth the main process as at startup this makes mutt unusable
here for 20 seconds.

Werner

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Comment by bitstreamout** [comment]
On Tue, Jul 26, 2016 at 07:54:30AM -0700, Richard Russon wrote:
> hmm... that's upstream code and the `if (check_stats)` part refers to `$mail_check_stats`.
> 
> I don't think `if (option (OPTSIDEBAR)) { ... }` is the solution, here.  I think would disable **all** checking of mbox mailboxes even if you opened one.
> 
> I'll keep looking...

in neomutt-distro-20160723/bugs-neomutt/0012-neomutt-customisations.patch
there is

 @@ -1518,7 +1518,7 @@ struct option_t MuttVars[] = {
    ** When \fI$$mark_old\fP is set, Mutt does not consider the mailbox to contain new
    ** mail if only old messages exist.
    */
 -  { "mail_check_stats", DT_BOOL, R_NONE, OPTMAILCHECKSTATS, 0 },
 +  { "mail_check_stats", DT_BOOL, R_NONE, OPTMAILCHECKSTATS, 1 },
    /*
    ** .pp
    ** When \fIset\fP, mutt will periodically calculate message

I guess this is the cause ;)

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Comment by flatcap** [comment]
Oh ****!
Sorry, that was a temporary measure I introduced in 20160709 and removed for 0723.
It was meant to ease the change to the upstream version of sidebar whilst I updated all the docs.

**Comment by flatcap** [comment]
That change was reverted in git and I clearly missed it when creating the patches.
