### ISSUE TITLE
[FR] Safe autosync

### ISSUE THREAD

**Issue by RichiH** [neomutt/neomutt#921]
Not having read states etc synced back to IMAP makes multi-seat setups cumbersome and is horrible with mobile clients.

The old, and valid, concern is that autosync of any sort could delete email accidentally marked as deleted.

My proposed workaround would be an autosync which only syncs states which are on a safe list of commands; the user being able to change said list.

The lack of a background loop could be addressed with the next issue, which I will open in a second.

**Comment by libBletchley** [comment]
Normally I would say it's a bad idea for mutt to have implemented _imap_ or _pop3_ in the first place, since those jobs are best delegated to _fetchmail_.  But what's interesting with your request is that if implemented, it would create justification for mutt doing imap.

**Comment by nicowilliams** [comment]
@libBletchley POP3 should be implemented by an external program, sure, because that's the point of POP3: to fetch mail.  But IMAP is not about fetching mail.  It's about remotely accessing your mailbox.  If you have multiple devices accessing your email, then IMAP is for you.

**Comment by RichiH** [comment]
Just to make sure: This has not been moved to the long-term wish-list, correct?

**Comment by flatcap** [comment]
Correct.
To put it on that list, I'd like to see a clear plan and a clear benefit.
