### ISSUE TITLE
[FR] Create hooks for SIGUSR1 and SIGUSR2

### ISSUE THREAD

**Issue by RichiH** [neomutt/neomutt#922]
Currently, there's no way to control mutt from the outside. Hooks for SIGUSR[12] could solve that.

This idea is not exactly new; see also:
* https://dev.mutt.org/trac/ticket/2202
* https://github.com/neomutt/neomutt/pull/625
* https://github.com/neomutt/neomutt/issues/921

**Comment by flatcap** [comment]
While playing with the signal handling, I knocked this up: [devel/usr1](https://github.com/neomutt/neomutt/compare/devel/usr1)
It works when you're in the index or the pager, but it will only fire on `$timeout`.
It's just a quick hack.  I haven't investigated how it interacts with other commands / connections.

SIGUSR1 and SIGUSR2 trigger `$usr1_command` and `$usr2_command` to be parsed.
e.g.
```
set usr1_command = "set sidebar_width = 20"
set usr2_command = "set sidebar_width = 40"
```

**Comment by gahr** [comment]
How about Neomutt opens a pipe and accepts command from there? It could be checked synchronously in the event loop and we could avoid playing with signal handlers, where you can do very little safely.

**Comment by RichiH** [comment]
https://www.youtube.com/watch?v=vgk-lA12FBk

**Comment by flatcap** [comment]
> Neomutt opens a pipe and accepts command from there

Hmm... I like this idea better, but both suffer from NeoMutt's modal nature.
Whatever commands are queued, the user needs to be sure they aren't going to cause side-effects.
Commands for the index may not apply if the user is in the pager.

**Comment by nicowilliams** [comment]
And then there's `SIGINFO`, though that one is less portable, sadly.

**Comment by RichiH** [comment]
Valid point; `SIGINFO` could be implemented on supported platforms and come with a disclaimer.

**Comment by craftyguy** [comment]
There's also `SIGRTMIN`, which some other projects (e.g. i3blocks) use. I think it might be a more portable alternative to `SIGINFO`?

**Comment by nicowilliams** [comment]
@craftyguy What makes SIGINFO useful is that you can set a control key in the tty to generate that signal.

Certainly, mutt could have hooks for most signals, and maybe that's just as well.  But SIGINFO is useful because it can be generated by the tty, therefore it can be elicited by the user on the tty.

**Comment by craftyguy** [comment]
@nicowilliams interesting, thanks for the lesson :)

**Comment by nicowilliams** [comment]
Usually it's `^T` that is bound to generating `SIGINFO`, FYI.

**Comment by craftyguy** [comment]
I see. I don't really have any preference which signal(s) y'all decide on, since my primary way of interacting with neomutt this way is using something like `pkill` to generate the signal in a script.

**Comment by nicowilliams** [comment]
A hook on any and all asynchronous signals that may be caught would be fine.

**Comment by flatcap** [comment]
Fascinating and educational as this is, I think we've wandered from the path a little... :-)

Pressing <kbd>Ctrl-T</kbd> which is captured by the terminal, which generates `SIGINFO` which is trapped by NeoMutt, which runs a command...  seems a little complicated.
Why not bind a key in NeoMutt?

NeoMutt can pass some information out when hooks are triggered.
We want a way to pass information **into** NeoMutt.

Each signal we use could pass one bit of information into NeoMutt.
The signals can only trigger pre-defined actions within NeoMutt.
Also, as @gahr points out, signal handling is quite messy and limited.
Signals interrupt library calls and can only pass data via atomically-locked structs.

Alternatively, using a fifo has two main advantages:
- The external user can define what they want to happen
- The code can pick a 'safe' time to read from the fifo and perform the actions

**Comment by flatcap** [comment]
Moving this to the long-term wish list.

**Comment by pfactum** [comment]
Was this implemented in code as per commits referenced here?

**Comment by flatcap** [comment]
@pfactum 
No.  The idea seemed interesting, but not interesting enough for anyone to work on it.

The commits you see are just a quick hack I created.
The `fifo` idea still sounds like a better solution.
