### ISSUE TITLE
Syntax highlighting broken while composing email with vim in neomutt

### ISSUE THREAD

**Issue by mimaoffice** [neomutt/neomutt#927]
Since the new version of `neomutt` (20171027) the syntax highlighting in `vim` is broken while composing emails. The problem is caused by the fact, that the temporary filename for the email begins now with `neomutt-`... and no more with `mutt-...`.

One could solve the problem by modifying the `vim` config file `/usr/share/vim/vimNN/filetype.vim`, but this is not the best solution...

What do you suggest?

Bests, Michele

PS: I'm using `neomutt` on a macOS X 10.12.6 installed with MacPorts.

**Comment by lbschenkel** [comment]
Chiming in: there's also NeoVim to consider. Although we can try to get all mainstream editors to recognize NeoMutt, it might take months/years for these changes to be pulled downstream and be visible to users. I think a more pragmatic solution would be for NeoMutt to leverage the existing "knowledge" of the installed base of editors and keep using the `mutt` prefix when composing mail (or maybe make it configurable at build time?).

**Comment by chrisbra** [comment]
Neomutt runtime files have been included in Vim as of https://github.com/vim/vim/commit/01164a6546b4c635daf96a1f17d1cb2d07f32a66
Neovim will merge those eventually
