### ISSUE TITLE
Open attachments in the background

### ISSUE THREAD

**Issue by RichiH** [neomutt/neomutt#93]
It would be nice if neomutt could open an attachment in the background without blocking the main session until you close whatever program was used to open the attachement.

Yes, there are scripts to hack this in, but meh.

Putting temp files into `/run/`, if it exists, would do away with the security and space considerations.

**Comment by flatcap** [comment]
The second part is easy:
```
set tmpdir = "/run/user/$UID"
```

As for the first part...
Sorry, it's unlikely to happen.
That doesn't sound like a simple change and I'm the only one coding.

**Comment by duck** [comment]
Maybe the first could be handled with distributing a helper script?  I use `mutt_bgrun` for years and it works great.  You can find it at http://www.spocom.com/users/gjohnson/mutt/  .  I think that v1.4 is the latest, but that is from a few years ago.

**Comment by pickfire** [comment]
Yes, the seems like a feature that could help a lot, maybe it can be done using mailcap.

**Comment by legrostdg** [comment]
> The second part is easy:

>      set tmpdir = "/run/user/$UID"

I tried this, it does not seem to work: (don't know why $UID seems to be unset, "echo $UID" returns 1000):

    Could not create temporary file /run/user//mutt-capeo-1000-1610-10011680583951307519

**Comment by flatcap** [comment]
@nuclearsandwich is working on this in the [devel/bg-attach-open](https://github.com/neomutt/neomutt/compare/devel/bg-attach-open) branch.

**Comment by nuclearsandwich** [comment]
> nuclearsandwich is working on this in the devel/bg-attach-open branch.

I did indeed! I was quite tired yesterday when I pushed the initial spike.

> Maybe the first could be handled with distributing a helper script?

I've borrowed this approach and created a separate binary called `mutt_launch` although when more folks review it later there's a pretty good chance we could do this within the mutt binary if we really wanted to.

### What it does

It first closes file-descriptors 3-256 without checking for errors. This is 100% a brute force approach. We could read open descriptors from `/proc` but that won't work on Mac OS X and possibly some other targets for neomutt.

Then it fork and dup all standard io to `/dev/null` so the opened viewer process doesn't write to the tty mutt is currently using before exec'ing the viewer process with `/bin/sh -c`.

The parent process prints a success message and exits, allowing the viewer to reparent and continue running without blocking Mutt.

### Work to do

- [ ] fork again so a mutt_launch process can wait for the viewer to close and clean up the tempfile. This _could_ be optional if using a tmpfs, but removing tempfiles after viewing appears to be the current behavior and so should be the default.

- [ ] accept tempfile name separately from command and store it in the first fork (viewer parent) mutt_launch process to be unlinked after the viewer closes.

- [ ] add configuration and code to mutt to make use of `mutt_launch`. My guess is that this will end up being a flag in the mailcap file similar to copiousoutput along the lines of "backgroundlaunch". 

- [ ] use `safe_calloc` and `safe_malloc` and any other cross-platform/safe functions from lib.c. I took a stab at this but my lack of familiarity with automake left me unsure of the best way to compile in lib.o.

- [ ] decide whether or not to keep this as a separate binary or make it a mutt_launch_in_background or somesuch function of mutt and update the build, docs, and packaging accordingly.

**Comment by nuclearsandwich** [comment]
> I tried this, it does not seem to work: (don't know why $UID seems to be unset, "echo $UID" returns 1000):

At least on the Debian system I'm sitting in front of. `$UID` only has a value in `bash` and not `/bin/sh` or fish (my default interactive shell).

You could try using [backticks](https://www.neomutt.org/manual/configuration.html#ex-rc-backtick) to get the current uid from the `id` command or any other one liner.

```
 set tmpdir = "/run/user/`id -u`"
```

**Comment by flatcap** [comment]
> closes file-descriptors 3-256 ... brute force approach

I thought there was a smarter way to do this.
I remembered the LVM2 code warning of leaked file descriptors, but, it uses `/proc`

https://git.fedorahosted.org/cgit/lvm2.git/tree/tools/lvmcmdline.c#n2160

One improvement is to use `getrlimit()` -- the user may not have 256 file descriptors.
https://git.fedorahosted.org/cgit/lvm2.git/tree/tools/lvmcmdline.c#n1977

> add configuration and code to mutt to make use of mutt_launch. My guess is that this will end up being a flag in the mailcap file similar to copiousoutput along the lines of "backgroundlaunch".

We can't make changes to `mailcap` because it's used by too many other programs.
So the choices are:
- Pass options on the launcher's command line
- Set environment variables (for the child only)

> use safe_calloc and safe_malloc and any other cross-platform/safe functions from lib.c.

Hmm... these don't really add much value.  I'd be tempted to cut'n'paste any that you **really** need, keeping the launcher's dependencies light.

**Comment by nuclearsandwich** [comment]
> Hmm... these don't really add much value. I'd be tempted to cut'n'paste any that you really need, keeping the launcher's dependencies light.

Gotcha. I hadn't really dug into them and assumed they added cross platform logic that I could use for free. I'll actually look and see what they offer.

**Comment by nuclearsandwich** [comment]
> We can't make changes to mailcap because it's used by too many other programs.
> So the choices are:

I hadn't actually read the [mailcap rfc](https://tools.ietf.org/html/rfc1524 ) and assumed that names like "needsterminal" and "copiousoutput" were generic rather than specified. So yeah, that's out.

Borrowing the entire workflow from mutt_bgrun, mutt_launch users could specify mutt_launch in their mailcap files. For example

```
application/pdf; xpdf %s
```

would become

```
application/pdf; mutt_launch xpdf %s
```

(caveat: mutt_launch invocation will probably change to explicitly specify tempfile name for easier cleanup.)

> Set environment variables (for the child only)

@flatcap can you elaborate on this a little? I don't follow

**Comment by nuclearsandwich** [comment]
Pushed some changes that handle file descriptors using the current value from getrlimit and confirm that the error when closing is indeed `EBADF` if there's an error.

Since the mailcap flag I was envisioning to signal that mutt_launch should be used wasn't a valid approach, I need to revisit how, if at all, mutt_launch integrates with mutt internals. I'm half tempted at this point to try and not require any special code within mutt. In order to answer that question for myself, I'm going to try and add doxygen documentation as discussed in #199 to at least the global functions transitively through `mutt_view_attachment` in order to up my understanding of what they do and determine if mutt_launch will need special treatment by them.

**Comment by flatcap** [comment]
> > Set environment variables (for the child only)

> @flatcap can you elaborate on this a little? I don't follow

We're going to want to pass information to the launcher.
```
MIME-TYPE; launcher [LAUNCHER ARGS] -- PROGRAM [PROGRAM ARGS] %s;
```

To change the launcher's behaviour, we could:

- set environment variables
  - neomutt sets env vars
  - runs the launcher (which inherits the environment)
  - unsets the vars (so they're not leaked)

Alternatively, we could be devious:
- "magically" add args into the mailcap file
  - neomutt detects the "launcher" in the mailcap
  - it interferes with the command line adding some options
  - then runs launcher

**Comment by RichiH** [comment]
> application/pdf; mutt_launch xpdf %s

That means all other programs using mailcap now need to call mutt_ launch.

An option in the config and then always doing it that way might be better.

Richard

Sent by mobile; excuse my brevity.

**Comment by RichiH** [comment]
Neat, thanks!

Richard

Sent by mobile; excuse my brevity.

**Comment by nuclearsandwich** [comment]
> An option in the config and then always doing it that way might be better.

The caveat to "always" doing it is that attachments that do use terminal / text mode viewers still need to be synchronous. while re-reading rfc1524 yet again I actually noticed that custom flags are actually supported. There's probably a way to be "smart" about it but it wouldn't be without complication.

>  Any other fields beginning with "x-" may be included for local or
   mailer-specific extensions of this format.  Implementations should
   simply ignore all such unrecognized fields to permit such extensions,
   some of which might be standardized in a future version of this
   document.

I'm inclined toward the following solutions in descending order of enthusiasm

1. a custom flag "x-" in the mailcap. This would allow us to maintain the mutt_launch interface as a mostly internal thing.

2. specifically providing guidance to users on adding mutt_launch to their mailcap files when spawning a graphical application in in the background is desired. This means that users have to learn the mutt_launch (simple for now) interface as well as opt into background launching for each entry that uses a graphical program. This is exactly how mutt_bgrun works now, with the added feature of plugging file descriptor leaks and improving the handling of temp files.

3. a config flag that when enabled opens all viewers in the background. I need to spend more time with the source to say with certainty whether or not this can be done well. The `use_pager` and `use_mailcap` flags give us some hints but I'm not sure if they'll be enough and think that this approach can be grown into from either of the more manual ones above.

**Comment by nuclearsandwich** [comment]
Quick update on where I'm at: I've been mostly focused on documenting the functions involved in the current attachment viewing so I don't mistakenly scramble any of that. I'll definitely want review on the docs as I'm still learning the codebase and don't want to unwittingly commit incorrect docs.

I'm now moving into the rfc1524 entry parser to have it extract a flag for running in background.
Soliciting opinions for what the flag should be called. `x-backgroundlaunch` is what I'll be using in the meantime.

**Comment by RichiH** [comment]
Open, not launch.

Else I wonder if it should be in the mutt namespace.

Richard

Sent by mobile; excuse my brevity.

**Comment by nuclearsandwich** [comment]
> Open, not launch.

to be clear hear, are you proposing `x-backgroundopen` rather than `x-backgroundlaunch`? If so, what's the reasoning?

**Comment by nuclearsandwich** [comment]
I've been making slow WIP commits on this between other projects. The `mutt_view_attachment` function is a fairly long one with lots of interacting conditionals and I'm still figuring out where the background open flag fits in with the existing context.

**Comment by RichiH** [comment]
Sorry for the belated answer; I think it's better to call it `open` as the first information on every line is filetype, not application. As that's the defining config stanza, the action should be relative to that.

**Comment by toogley** [comment]
@RichiH possible solution for now: https://www.mattcutts.com/blog/ppt-attachments-in-mutt/

**Comment by flatcap** [comment]
Thanks for contributing, but this enhancement seems abandoned.
The code branch will be archived in the [neomutt-old](https://github.com/neomutt/neomutt-old) repo.
This issue will now be closed and listed on the [closed discussions page](https://www.neomutt.org/dev/discussions)

**Comment by nuclearsandwich** [comment]
Sorry I wasn't able to get this all the way across the line. I do think about it often but haven't had the time to get back to it.

**Comment by madduck** [comment]
For those interested, I came up with what I believe to be a slick hack: https://git.madduck.net/etc/mutt.git/commitdiff/76227d1c302ee76d82c037e923c70edc61fd5aea

**Comment by flatcap** [comment]
Thanks @madduck

**Comment by coiby** [comment]
> For those interested, I came up with what I believe to be a slick hack: https://git.madduck.net/etc/mutt.git/commitdiff/76227d1c302ee76d82c037e923c70edc61fd5aea

Thank you! I noticed the latest version (20191207-3) of neomutt will automatically delete temporary attachment files after exiting. So `&` is suffcient. For those who are interested in this issue, I provide a simplified solution which remove notifier on [Arch Wiki](https://wiki.archlinux.org/index.php/Mutt#Open_attachments_or_view_HTML_email_in_the_background).

**Comment by brianbuccola** [comment]
@coiby, I tried your `&` solution from the Arch Wiki (before even stumbling on this neomutt issue), and unfortunately it doesn't work, since mutt deletes the temporary file before it can be opened.

Instead I followed [this solution from Stack Exchange](https://unix.stackexchange.com/questions/65381/how-to-tell-mutt-not-to-wait-for-an-attachment-program-to-return) (without the `folder-hook`):

```mailcap
application/*; mkdir -p /tmp/mutt \; cp %s /tmp/mutt \; xdg-open /tmp/mutt/$(basename %s) &>/dev/null &
```
