### ISSUE TITLE
folder-hook executes "too soon"

### ISSUE THREAD

**Issue by yourealwaysbe** [neomutt/neomutt#931]
Using neomutt r8261.51fea281d-1 with Arch Linux  4.13.9-1-ARCH.  In my muttrc
```
folder-hook . 'set sort=reverse-threads; set sort_aux=last-date-received; push <collapse-all>'
folder-hook . 'push <first-entry>'
```
earns the message "Not available in this menu" each time the folder is changed.  If i switch the order
```
folder-hook . 'push <first-entry>'
folder-hook . 'set sort=reverse-threads; set sort_aux=last-date-received; push <collapse-all>'
```
the message goes away, but after sending a mail and returning to the mailbox, neomutt appears to go into message compose mode and "To: irst-entry>" is displayed in the status bar, awaiting my input.  The latter does not happen everytime (say 50% of the time).

Expected behaviour: when opening a folder, threads are sorted in reverse order, collapsed, and the cursor is on the first message in the box. 

It feels like the folder hooks are being run concurrently with the folder change, and kicking in before the folder change has finished.  This may be related to #227 and the recent commits addressing it.  The folder-hook has worked fine for years until a week or two ago (i update each week).

**Comment by flatcap** [comment]
Sorry for the slow reply.
I've given this a try and sorry, I can't repeat it.
Which ever way I had the `folder-hook`s it still worked.

> "To: irst-entry>"

Hmm... that's a classic sign of an interrupted macro.

> The folder-hook has worked fine for years until a week or two ago

I've a couple of suggestions, depending on your time, skills and patience.
- Strip down your config to the absolute minimum
  It's possible that some other config is interfering with the hooks.
- `git bisect` the code and find the commit where the problem begins.
  If your problem is reasonably repeatable, this shouldn't take too long.

Thanks.

**Comment by yourealwaysbe** [comment]
Thanks for looking into this.  I found i could workaround by using exec blah instead of push <blah> on both lines.

I tried to reproduce the old error.  For the first ordering i get "threading not enabled" each time (reliably), for the second ordering things work as expected.  I will get back to you if i find time to bisect.

I discovered with the following config

    folder-hook . 'push <collapse-all>'

(and nothing else) that trying to send an email will fail when pressing 'y' after composing (obviously, there's no smtp configured), but instead of a notification of the failure, neomutt will act as if i pressed 'c' and then entered 'ollapse-all>'.  Is this expected?

**Comment by yourealwaysbe** [comment]
I have tracked down the cause of the issue with the config file only containing
    folder-hook . 'push <collapse-all>'
It is commit 4aaf1ef7670b37c54320161a8fc3386479588dc0, which has the comment "call the folder-hook before saving to $record".

My hunch is that calling the folder-hook on the record folder causes some folder-hooks to fail, since they're written on the assumption that the index of that folder is being opened (e.g. push collapse-all) rather than the folder merely being accessed to save something too.

I'm not sure the mutt docs are precise about exactly when folder-hooks should be called, but my impression from them is that it should be called when opening an index.
Calling push collapse-all is an [example folder-hook](https://dev.mutt.org/doc/manual.html#ex-folder-hook-push) in the mutt docs, hence i would argue that it should work without issue.

**Comment by kashyapc** [comment]
I can confirm mvdan's experience above. I too see the _same_ experience -- whenever I send an email, I see the: `Not available in this menu`. It really _is_ annoying. I've been seeing this for a few days, but ignored it.  Thought  I accidentally pressed multiple keys. But I tried to carefully send an email to myself, and could reproduce it consistently.

That's my version of 'neomutt': `neomutt-20171215-1.fc26.x86_64`

**Comment by flatcap** [comment]
@mvdan @kashyapc 
Your problems are caused by config that's set during a `folder-hook`.
The hook is called when saving an email to `$record` -- this didn't use to happen.
The fix in branch [issue/931-sort](https://github.com/neomutt/neomutt/compare/issue/931-sort) should help.

**Comment by kashyapc** [comment]
So it turns out, if I remove the `folder-hook` entry for `sort_aux`, I don't see the issue I mentioned earlier anymore:

    - folder-hook INBOX set sort_aux=reverse-last-date-received
    + set sort_aux=reverse-last-date-received

**Comment by kashyapc** [comment]
Even with Git / master (I'm here, to be more precise): 

    $> git describe
    neomutt-20171215-163-g2f727544

I see the issue mentioned here: https://github.com/neomutt/neomutt/issues/931#issuecomment-355507610

**Comment by mvdan** [comment]
> The fix in branch record-folder-hook should help.

@flatcap was that comment directed at us, asking us to build and test that branch to see if it fixes the issue?

**Comment by flatcap** [comment]
@kashyapc @mvdan 
Earlier today I reverted the `folder-hook` change that was causing some problems.
Please can you try `master` again and let me know if you still have problems.
Thanks.
