### ISSUE TITLE
MacOS build on Travis (Developer needed)

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#938]
We use [TravisCI](https://travis-ci.org/neomutt/neomutt) to do automated builds of NeoMutt.
This helps us quickly find lots of build bugs.

Unfortunately, though, we've recently come across a few build bugs that are specific to MacOS.

Travis supports MacOS, but we need help setting it up.
If possible, I'd like to see both Homebrew and MacPorts supported.

Having a test platform for MacOS would mean no more release-day surprises.

Please help :-)

/cc @alexpearce @lbschenkel @lrosenman @evgeni

**Comment by lbschenkel** [comment]
That's great. Although I'm the maintainer of the port in MacPorts, I'm not really familiar or involved with the infrastructure set-up (buildbots, etc.) but I'll relay your message to the list and figure out what we can do.

**Comment by flatcap** [comment]
@lbschenkel Thanks.

It **should** be quite simple.

For Linux, the Travis VM has most common build tools pre-installed.
Travis also clones our source locally.

Then we install our build deps, e.g. LMDB, etc
Finally we perform our normal build steps.

**Comment by lbschenkel** [comment]
I have relayed your issue to the MacPorts list.

My two cents: Theoretically all you need is a clean macOS with MacPorts installed, and then you need to put the source package (`.tar.gz`) in the MacPorts distfiles directory, and you need a patched version of the [Portfile](https://github.com/macports/macports-ports/blob/master/mail/neomutt/Portfile) in an empty directory (you need to change the version and the checksums). If you run `port destroot` in that same directory it will build it and the result will be in `work/destroot`.

This port has "variants" that result in different switches being applied when building. NeoMutt has quite a few, you can choose the variants to turn on (or off, in case it's enabled by default) by using `port destroot +variant1 +variant2 -variant3`.

Normal MacPorts require `sudo` to run `port` (because it will switch to a sandboxed user for the duration of the build), but if that is an issue MacPorts can be reconfigured so you don't do that.

**Comment by flatcap** [comment]
> This port has "variants"

Our main Travis build does 29 compiles, testing a wide variety of configure options.
Travis has a build matrix that us to do this easily.
It'd be good to test all the combinations that you allow your users to use.

**Comment by lbschenkel** [comment]
In theory all combinations of the variants listed in the `Portfile` I linked can be turned on/off independently (unless your `autosetup` script reject specific combinations), but I think some combinations will be redundant/unnecessary. In case it's not clear what the variants do, I can clarify.

The MacPorts buildbots only build the default variants, which result in the default binaries that you get. If you're asking for alternative variants, then MacPorts will download the source and build it locally. For this reason, some less popular combination of variants could have no users and actually be broken. To the best of my knowledge they're not, but I cannot test them all and I end up fixing them when somebody complains. Right now there are zero tickets for NeoMutt on MacPorts, so at least we don't have any known issues.

**Comment by jmroot** [comment]
Unfortunately there's a combinatorial explosion - 17 variants that can be on or off means there are 131072 combinations. A lot are just adding support for various databases and such though, so the default set plus "everything on" and a couple more for slang instead of ncurses and gnutls instead of openssl is probably sufficient.

**Comment by jmroot** [comment]
Our repo's CI config should be helpful to you: https://github.com/macports/macports-ports/blob/master/_ci

About the first half of bootstrap.sh is setting up and configuring MacPorts. The rest is less relevant for your simpler case of building one port. You should just be able to `port sync` and then `cd path/to/yourport && port install`.

**Comment by flatcap** [comment]
@jmroot 
hehe, yeah.  We've reduced the number of build options in neomutt to avoid the need for astronomical numbers of builds.  All the features that had no build dependencies are now built by default: IMAP, POP, SMTP, Compress, ...

Also, there's good isolation between the header cache database backends, so we trust that one build will cover them all.

Also, we expect that packagers will make some decisions for their users, e.g. curses vs slang.

**Comment by lbschenkel** [comment]
@jmroot is there a way to disable or comment out the port checksum verification? I guess it's not an issue for NeoMutt, and it would make things easier.

**Comment by jmroot** [comment]
If you fetch from git there's no (additional) checksum step.

**Comment by lbschenkel** [comment]
@flatcap I took out all the unnecessary stuff from the `Portfile`, and just tested right now by doing a build of the latest commit in `master`:
```
PortSystem          1.0
PortGroup           github 1.0

github.setup        neomutt neomutt c468d8f92757ca16f028188d4388407e754f14c0
name                neomutt-devel
version             git
fetch.type          git

depends_build       port:docbook-xml-4.2 port:docbook-xsl port:libxslt port:w3m
depends_lib         path:lib/libssl.dylib:openssl \
                    port:gettext \
                    port:libiconv \
                    port:ncurses \
                    port:zlib
depends_run         path:share/curl/curl-ca-bundle.crt:curl-ca-bundle
# needed by smime_keys
depends_run-append  path:bin/perl:perl5

configure.cmd       ./configure.autosetup
configure.args      --disable-idn \
                    --with-ncurses=${prefix} \
                    --with-nls=${prefix} \
                    --with-ssl=${prefix}

# disable auto-detection of ccache, as MacPorts already adds it
configure.env-append CCACHE=none

default_variants    +idn +mutt
if {${install.user} ne "root"} {
    default_variants-append     +homespool
}

variant db4 description {Support Berkeley DB database} {
    configure.args-append       --with-bdb=${prefix}
    configure.cppflags-append   "-I${prefix}/include/db48"
    configure.ldflags-append    "-L${prefix}/lib/db48"
    depends_lib-append          port:db48
}
variant gdbm description {Support GNU dbm database} {
    configure.args-append       --with-gdbm=${prefix}
    depends_lib-append          port:gdbm
}
variant gnutls description {Use GnuTLS} {
    configure.args-replace      --with-ssl=${prefix} --with-gnutls=${prefix}
    depends_lib-replace         path:lib/libssl.dylib:openssl port:gnutls
}
variant gpgme description {Enable GPGME crypto support} {
    configure.args-append       --with-gpgme=${prefix}
    depends_lib-append          port:gpgme
}
variant gss description {Support GSS API (Kerberos)} {
    configure.args-append       --with-gss=${prefix}
    depends_lib-append          port:kerberos5
}
variant homespool description {Spool mail in home directory (allows installing without root privileges)} {
    configure.args-append       --homespool
}
variant idn description {Internationalized Domain Name support} {
    configure.args-replace      --disable-idn --with-idn=${prefix}
    depends_lib-append          port:libidn
}
variant kyotocabinet description {Support Kyoto Cabinet database} {
    configure.args-append       --with-kyotocabinet=${prefix}
    depends_lib-append          port:kyotocabinet
}
variant lmdb description {Support LMDB database} {
    configure.args-append       --with-lmdb=${prefix}
    depends_lib-append          port:lmdb
}
variant lua description {Lua scripting support} {
    configure.args-append       --with-lua=${prefix}
    depends_lib-append          port:lua
}
variant mutt description {Create 'mutt' symlink} {
    post-destroot {
        file link -symbolic ${destroot}${prefix}/bin/mutt neomutt
    }
}
variant notmuch description {Notmuch support} {
    configure.args-append       --with-notmuch=${prefix}
    depends_lib-append          port:notmuch
}
variant qdbm description {Support QDBM database} {
    configure.args-append       --with-qdbm=${prefix}
    depends_lib-append          port:qdbm
}
variant sasl description {Simple Authentication and Security Layer support} {
    configure.args-append       --with-sasl=${prefix}
    depends_lib-append          port:cyrus-sasl2
}
variant slang description {Use S-lang instead of ncurses} {
    configure.args-append       --with-ui=slang --with-slang=${prefix}
    depends_lib-replace         port:ncurses port:slang2
}
variant tokyocabinet description {Support Tokyo Cabinet database} {
    configure.args-append       --with-tokyocabinet=${prefix}
    depends_lib-append          port:tokyocabinet
}

post-extract {
    reinplace -W ${worksrcpath}/contrib "s|/usr/bin/|${prefix}/bin/|g" \
              smime_keys
    reinplace -W ${worksrcpath}/contrib "s|/usr/lib/|${prefix}/lib/|g" \
              gpg.rc pgp5.rc smime.rc
}
post-destroot {
    move ${destroot}${prefix}/etc/neomuttrc \
         ${destroot}${prefix}/etc/neomuttrc.sample
    # install mime.types in ${prefix}/etc as previous versions used to do
    copy ${destroot}${prefix}/share/doc/neomutt/mime.types \
         ${destroot}${prefix}/etc/mime.types.sample
    # install examples in ${prefix}/share/examples
    xinstall -d ${destroot}${prefix}/share/examples
    move ${destroot}${prefix}/share/doc/neomutt/samples \
         ${destroot}${prefix}/share/examples/neomutt
}
```
I hope that this is mostly self-explanatory, but I will be glad to clarify any questions you might have.

**Comment by flatcap** [comment]
@lbschenkel Thanks it looks lovely, but I have no clue how the MacPorts build fits together :-)

I've just created a branch [devel/macports](https://github.com/neomutt/neomutt/tree/devel/macports) with a [.travis.yml](https://github.com/neomutt/neomutt/blob/devel/macports/.travis.yml) in it.

Commented out are all the deps I install in the Linux build.

If anyone wants to start experimenting, let me know and I'll give you commit privs.

**Comment by lbschenkel** [comment]
I can try giving it a shot.

**Comment by flatcap** [comment]
Thanks.  As a member you already have privs.
Each commit you make to that branch will be automatically built.
Travis: https://travis-ci.org/neomutt/neomutt/branches

Note: there's sometimes a lag before the build starts (due to the load on Travis)

**Comment by l2dy** [comment]
@lbschenkel I pushed a prototype to the [devel/macports](https://github.com/neomutt/neomutt/tree/devel/macports) branch.

**Comment by jmroot** [comment]
The build failed because the github portgroup is still being included; just need to remove it as it's not being used. Also the log with port -v is longer than travis likes, it seems.

**Comment by lbschenkel** [comment]
Hey, I made a small tweak and got a green build: https://travis-ci.org/neomutt/neomutt/builds/299828630

**Comment by flatcap** [comment]
Nice work!  Thanks.
Please can you make one more small change.
After a successful build, can you run `neomutt -v`

**Comment by lbschenkel** [comment]
Will do.

**Comment by lbschenkel** [comment]
https://travis-ci.org/neomutt/neomutt/jobs/299892962

**Comment by flatcap** [comment]
Fantastic.  Thank you all.

**Comment by mojca** [comment]
@l2dy might be able to help you if you need any clarification of our setup. As @jmroot pointed out, you could start with our ci setup, but you could simplify it a lot. For example, there's no need to install `getopt`, no need to install `mpbb` etc.

Basically all you need to do is install macports, `cd` to the folder where you have your own version of a `Portfile` that fetches from git and then run a couple of different `port install` commands with different variants.

**Comment by flatcap** [comment]
@mojca Thanks for the info.
@l2dy and @lbschenkel have got a basic build working.
The next step is to get it to perform a wider set of compiles (there's no rush on this, though).

For now, this will allow me (a non-Mac user) to do some regular testing.
Thanks.

**Comment by flatcap** [comment]
Branch renamed to [distro/macports](https://github.com/neomutt/neomutt/tree/distro/macports).
Backed up to [management repo](https://github.com/neomutt/management/tree/master/travis).
