### ISSUE TITLE
Renaming functions

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#945]
So far we've taken over a hundred functions moved then into a library.
All of them are fully documented and independent of neomutt.
As such, they can be easily unit-tested.

Now it's time to sort out the naming.
These are my suggestions, all of which are open to discussion.

## 1. Rename the directory

`lib` is meaningless.  These are utility functions so, perhaps:

* `util/` and `libutil`
* `utils/` and `libutils`

## 2. Pick a library prefix

Name all of our functions to prevent clashes with any of the standard libraries.
Ideally the prefixes want to be short, but meaningful.

* `mutt_`
* `util_` (or `utils_`)
* `m_`
* `m`
* `u_`
* `u`
* `mu_`
* `mu`
* \<none\> (rely on the library prefixes)

I quite like `u_` or `mu_`.

## 3. Pick library prefixes

The functions in the library are grouped into files by type.
Suggested prefixes:

| File        | Prefix   |
| :---------- | :------- |
| `base64.c`  | `b64`    |
| `buffer.c`  | `buffer` |
| `date.c`    | `date`   |
| `file.c`    | `file`   |
| `hash.c`    | `hash`   |
| `list.c`    | `list`   |
| `mapping.c` | `map`    |
| `md5.c`     | `md5`    |
| `memory.c`  | `mem`    |
| `sha1.c`    | `sha1`   |
| `string.c`  | `str`    |

`buffer` hasn't been abbreviated because it refers to `struct Buffer`

## 4. Rename the functions

* Apply the library prefixes
* Tidy up some of the more ridiculous naming, e.g. `safe_`
* Ignore the static functions
* Ignore some 'magic' functions, e.g. `mutt_debug()`

| Original function          | Tidied base name   | New function              |
| :------------------------- | :----------------- | :------------------------ |
| mutt_from_base64           | decode             | mu_b64_decode             |
| mutt_to_base64             | encode             | mu_b64_encode             |
|                            |                    |                           |
| mutt_buffer_addch          | addch              | mu_buffer_addch           |
| mutt_buffer_addstr         | addstr             | mu_buffer_addstr          |
| mutt_buffer_free           | free               | mu_buffer_free            |
| mutt_buffer_from           | from               | mu_buffer_from            |
| mutt_buffer_init           | init               | mu_buffer_init            |
| mutt_buffer_new            | new                | mu_buffer_new             |
| mutt_buffer_printf         | printf             | mu_buffer_printf          |
| mutt_buffer_reset          | reset              | mu_buffer_reset           |
|                            |                    |                           |
| imap_make_date             | make_imap          | mu_date_make_imap         |
| imap_parse_date            | parse_imap         | mu_date_parse_imap        |
| is_day_name                | is_day_name        | mu_date_is_day_name       |
| mutt_check_month           | check_month        | mu_date_check_month       |
| mutt_local_tz              | local_tz           | mu_date_local_tz          |
| mutt_make_date             | make_date          | mu_date_make_date         |
| mutt_mktime                | make_time          | mu_date_make_time         |
| mutt_normalize_time        | normalize_time     | mu_date_normalize_time    |
| mutt_parse_date            | parse_date         | mu_date_parse_date        |
|                            |                    |                           |
| mutt_basename              | basename           | mu_file_basename          |
| mutt_concatn_path          | concatn_path       | mu_file_concatn_path      |
| mutt_concat_path           | concat_path        | mu_file_concat_path       |
| mutt_copy_bytes            | copy_bytes         | mu_file_copy_bytes        |
| mutt_copy_stream           | copy_stream        | mu_file_copy_stream       |
| mutt_decrease_mtime        | decrease_mtime     | mu_file_decrease_mtime    |
| mutt_dirname               | dirname            | mu_file_dirname           |
| mutt_lock_file             | lock               | mu_file_lock              |
| mutt_mkdir                 | mkdir              | mu_file_mkdir             |
| mutt_quote_filename        | quote_filename     | mu_file_quote_filename    |
| mutt_read_line             | read_line          | mu_file_read_line         |
| mutt_regex_sanitize_string | sanitize_regex     | mu_file_sanitize_regex    |
| mutt_rename_file           | rename             | mu_file_rename            |
| mutt_rmtree                | rmtree             | mu_file_rmtree            |
| mutt_sanitize_filename     | sanitize_filename  | mu_file_sanitize_filename |
| mutt_set_mtime             | set_mtime          | mu_file_set_mtime         |
| mutt_touch_atime           | touch_atime        | mu_file_touch_atime       |
| mutt_unlink                | unlink             | mu_file_unlink            |
| mutt_unlink_empty          | unlink_empty       | mu_file_unlink_empty      |
| mutt_unlock_file           | unlock             | mu_file_unlock            |
| safe_fclose                | fclose             | mu_file_fclose            |
| safe_fopen                 | fopen              | mu_file_fopen             |
| safe_fsync_close           | fsync_close        | mu_file_fsync_close       |
| safe_open                  | open               | mu_file_open              |
| safe_rename                | rename             | mu_file_rename            |
| safe_symlink               | symlink            | mu_file_symlink           |
|                            |                    |                           |
| hash_create                | create             | mu_hash_create            |
| hash_delete                | delete             | mu_hash_delete            |
| hash_destroy               | destroy            | mu_hash_destroy           |
| hash_find                  | find               | mu_hash_find              |
| hash_find_bucket           | find_bucket        | mu_hash_find_bucket       |
| hash_find_elem             | find_elem          | mu_hash_find_elem         |
| hash_insert                | insert             | mu_hash_insert            |
| hash_walk                  | walk               | mu_hash_walk              |
| int_hash_create            | int_create         | mu_hash_int_create        |
| int_hash_delete            | int_delete         | mu_hash_int_delete        |
| int_hash_find              | int_find           | mu_hash_int_find          |
| int_hash_insert            | int_insert         | mu_hash_int_insert        |
|                            |                    |                           |
| mutt_list_clear            | clear              | mu_list_clear             |
| mutt_list_find             | find               | mu_list_find              |
| mutt_list_free             | free               | mu_list_free              |
| mutt_list_insert_after     | insert_after       | mu_list_insert_after      |
| mutt_list_insert_head      | insert_head        | mu_list_insert_head       |
| mutt_list_insert_tail      | insert_tail        | mu_list_insert_tail       |
| mutt_list_match            | match              | mu_list_match             |
|                            |                    |                           |
| mutt_getnamebyvalue        | get_name           | mu_map_get_name           |
| mutt_getvaluebyname        | get_value          | mu_map_get_value          |
|                            |                    |                           |
| md5_buffer                 | buffer buf         | mu_md5_buf                |
| md5_finish_ctx             | finish_ctx         | mu_md5_finish_ctx         |
| md5_init_ctx               | init_ctx           | mu_md5_init_ctx           |
| md5_process_block          | process_block      | mu_md5_process_block      |
| md5_process_bytes          | process_bytes      | mu_md5_process_bytes      |
| md5_read_ctx               | read_ctx           | mu_md5_read_ctx           |
| md5_stream                 | stream             | mu_md5_stream             |
|                            |                    |                           |
| safe_calloc                | calloc             | mu_mem_calloc             |
| safe_free                  | free               | mu_mem_free               |
| safe_malloc                | malloc             | mu_mem_malloc             |
| safe_realloc               | realloc            | mu_mem_realloc            |
|                            |                    |                           |
| sha1_final                 | final              | mu_sha1_final             |
| sha1_init                  | init               | mu_sha1_init              |
| sha1_transform             | transform          | mu_sha1_transform         |
| sha1_update                | update             | mu_sha1_update            |
|                            |                    |                           |
| imap_wordcasecmp           | word_casecmp       | mu_str_word_casecmp       |
| is_email_wsp               | is_email_wsp       | mu_str_is_email_wsp       |
| lwslen                     | lws_len            | mu_str_lws_len            |
| lwsrlen                    | lws_rlen           | mu_str_lws_rlen           |
| mutt_atoi                  | atoi               | mu_str_atoi               |
| mutt_atol                  | atol               | mu_str_atol               |
| mutt_atos                  | atos               | mu_str_atos               |
| mutt_remove_trailing_ws    | remove_trailing_ws | mu_str_remove_trailing_ws |
| mutt_skip_whitespace       | skip_whitespace    | mu_str_skip_whitespace    |
| mutt_strcasecmp            | strcasecmp         | mu_str_strcasecmp         |
| mutt_strchrnul             | strchrnul          | mu_str_strchrnul          |
| mutt_strcmp                | strcmp             | mu_str_strcmp             |
| mutt_strcoll               | strcoll            | mu_str_strcoll            |
| mutt_stristr               | stristr            | mu_str_stristr            |
| mutt_strlen                | strlen             | mu_str_strlen             |
| mutt_strlower              | strlower           | mu_str_strlower           |
| mutt_strncasecmp           | strncasecmp        | mu_str_strncasecmp        |
| mutt_strncmp               | strncmp            | mu_str_strncmp            |
| mutt_str_adjust            | adjust             | mu_str_adjust             |
| mutt_str_append_item       | append_item        | mu_str_append_item        |
| mutt_str_replace           | replace            | mu_str_replace            |
| mutt_substrcpy             | substr_cpy         | mu_str_substr_cpy         |
| mutt_substrdup             | substr_dup         | mu_str_substr_dup         |
| next_word                  | next_word          | mu_str_next_word          |
| rfc822_dequote_comment     | dequote_comment    | mu_str_dequote_comment    |
| rstrnstr                   | rstrnstr           | mu_str_rstrnstr           |
| safe_strcat                | strcat             | mu_str_strcat             |
| safe_strdup                | strdup             | mu_str_strdup             |
| safe_strncat               | strncat            | mu_str_strncat            |
| skip_email_wsp             | skip_email_wsp     | mu_str_skip_email_wsp     |
| strfcpy                    | strfcpy            | mu_str_strfcpy            |
| strnfcpy                   | strnfcpy           | mu_str_strnfcpy           |

Some of the string functions look a bit odd where we've wrapped an existing libc string function, but the rest look ok.

`u_date_make_imap` and `u_date_parse_imap` retain the string "imap" since they refer to the date format in RFC3501.

**Comment by libBletchley** [comment]
The coding standards I've worked with require function names to be a _noun_, the reason being that functions return an object, and exceptionally boolean functions return the meaning of truth.  I've not touched C code for a long time, but my first thought when I see all those leading `u_`s is that it looks like an abbreviation for _unsigned_.  So I wonder if going the cryptic route could alienate newcomers.

**Comment by flatcap** [comment]
> The coding standards I've worked with require function names to be a noun

That sounds reasonable.

The table above is an attempt to quick-fix the problem.
Many of Mutt's functions were poorly designed and named.
Renaming them will only get us only a bit of uniformity.

If you have the time and patience to analyse all 100 of the functions and suggest better names, I'll gladly consider them :-)

> boolean functions are named to indicate the meaning of truth (to be readable in an if statement).

We're slowly working through all of NeoMutt boolean functions:
Converting them to bool/true/false and fixing the name to be "truth-y".

> u_s is that it looks like an abbreviation for unsigned

Hmm... maybe.  Perhaps `mu_` is wiser.

> It's fortunate that mutt is a quite short name for the project, so I would leverage that in the names.

True, but there are 1000 non-static functions in NeoMutt.
If they're all called `mutt_X` that does little to help segregate them.
I'd like to see each library having its own prefix.  A sort of namespacing.

> I would have thought base 64 operations would be available in the standard libraries.

Not that I can find.  OpenSSL and GnuTLS have their own versions (called different things, obviously).
Also NeoMutt has two **versions** of base64 encoding:
- MIME encoding
- UTF7 support (IMAP)

**Comment by gahr** [comment]
My .2$:

> 1. Rename the directory

How about we get back to `libmutt`? I came to hate general names like helpers and utils, which usually mean nobody's found a good name for the thing. Anyway, anything that has little chance of clashing is good, so definitely not `libutil`.

> 2. Pick a library prefix

I'd go for `mu_`.

> 3. Pick library prefixes
> 4. Rename the functions

They look good :)

**Comment by flatcap** [comment]
I originally wanted to use the name `libmutt` for something else, but I've changed my mind.
So, `libmutt` and `mutt/` are fine.

**Comment by flatcap** [comment]
Final decision:

**base64**

| Old function     | New function    |
| :--------------- | :-------------- |
| mutt_from_base64 | mutt_b64_decode |
| mutt_to_base64   | mutt_b64_encode |

**buffer**

| Old function       | New function       |
| :----------------- | :----------------- |
| mutt_buffer_addch  | mutt_buffer_addch  |
| mutt_buffer_addstr | mutt_buffer_addstr |
| mutt_buffer_free   | mutt_buffer_free   |
| mutt_buffer_from   | mutt_buffer_from   |
| mutt_buffer_init   | mutt_buffer_init   |
| mutt_buffer_new    | mutt_buffer_new    |
| mutt_buffer_printf | mutt_buffer_printf |
| mutt_buffer_reset  | mutt_buffer_reset  |

**date**

| Old function        | New function             |
| :------------------ | :----------------------- |
| mutt_check_month    | mutt_date_check_month    |
| is_day_name         | mutt_date_is_day_name    |
| mutt_local_tz       | mutt_date_local_tz       |
| mutt_make_date      | mutt_date_make_date      |
| imap_make_date      | mutt_date_make_imap      |
| mutt_mktime         | mutt_date_make_time      |
| mutt_normalize_time | mutt_date_normalize_time |
| mutt_parse_date     | mutt_date_parse_date     |
| imap_parse_date     | mutt_date_parse_imap     |

**debug**

| Old function | New function |
| :----------- | :----------- |
| mutt_debug   | mutt_debug   |

**file**

| Old function               | New function                |
| :------------------------- | :-------------------------- |
| mutt_basename              | mutt_file_basename          |
| mbox_check_empty           | mutt_file_check_empty       |
| mutt_concatn_path          | mutt_file_concatn_path      |
| mutt_concat_path           | mutt_file_concat_path       |
| mutt_copy_bytes            | mutt_file_copy_bytes        |
| mutt_copy_stream           | mutt_file_copy_stream       |
| mutt_decrease_mtime        | mutt_file_decrease_mtime    |
| mutt_dirname               | mutt_file_dirname           |
| safe_fclose                | mutt_file_fclose            |
| safe_fopen                 | mutt_file_fopen             |
| safe_fsync_close           | mutt_file_fsync_close       |
| mutt_lock_file             | mutt_file_lock              |
| mutt_mkdir                 | mutt_file_mkdir             |
| safe_open                  | mutt_file_open              |
| mutt_quote_filename        | mutt_file_quote_filename    |
| file_read_keyword          | mutt_file_read_keyword      |
| mutt_read_line             | mutt_file_read_line         |
| mutt_rename_file           | mutt_file_rename            |
| mutt_rmtree                | mutt_file_rmtree            |
| safe_rename                | mutt_file_safe_rename       |
| mutt_sanitize_filename     | mutt_file_sanitize_filename |
| mutt_regex_sanitize_string | mutt_file_sanitize_regex    |
| mutt_set_mtime             | mutt_file_set_mtime         |
| safe_symlink               | mutt_file_symlink           |
| mutt_touch_atime           | mutt_file_touch_atime       |
| to_absolute_path           | mutt_file_to_absolute_path  |
| mutt_unlink                | mutt_file_unlink            |
| mutt_unlink_empty          | mutt_file_unlink_empty      |
| mutt_unlock_file           | mutt_file_unlock            |

**hash**

| Old function     | New function          |
| :--------------- | :-------------------- |
| hash_create      | mutt_hash_create      |
| hash_delete      | mutt_hash_delete      |
| hash_destroy     | mutt_hash_destroy     |
| hash_find        | mutt_hash_find        |
| hash_find_bucket | mutt_hash_find_bucket |
| hash_find_elem   | mutt_hash_find_elem   |
| hash_insert      | mutt_hash_insert      |
| int_hash_create  | mutt_hash_int_create  |
| int_hash_delete  | mutt_hash_int_delete  |
| int_hash_find    | mutt_hash_int_find    |
| int_hash_insert  | mutt_hash_int_insert  |
| hash_walk        | mutt_hash_walk        |

**list**

| Old function           | New function           |
| :--------------------- | :--------------------- |
| mutt_list_clear        | mutt_list_clear        |
| strict_cmp_stailq      | mutt_list_compare      |
| mutt_list_find         | mutt_list_find         |
| mutt_list_free         | mutt_list_free         |
| mutt_list_insert_after | mutt_list_insert_after |
| mutt_list_insert_head  | mutt_list_insert_head  |
| mutt_list_insert_tail  | mutt_list_insert_tail  |
| mutt_list_match        | mutt_list_match        |

**mapping**

| Old function        | New function       |
| :------------------ | :----------------- |
| mutt_getnamebyvalue | mutt_map_get_name  |
| mutt_getvaluebyname | mutt_map_get_value |

**mbyte**

| Old function  | New function          |
| :------------ | :-------------------- |
| mutt_charlen  | mutt_mb_charlen       |
| get_initials  | mutt_mb_get_initials  |
| is_shell_char | mutt_mb_is_shell_char |
| my_mbstowcs   | mutt_mb_mbstowcs      |
| my_wcstombs   | mutt_mb_wcstombs      |
| my_wcswidth   | mutt_mb_wcswidth      |
| my_wcwidth    | mutt_mb_wcwidth       |
| my_width      | mutt_mb_width         |
| width_ceiling | mutt_mb_width_ceiling |

**md5**

| Old function      | New function           |
| :---------------- | :--------------------- |
| md5_buffer        | mutt_md5_buf           |
| md5_finish_ctx    | mutt_md5_finish_ctx    |
| md5_init_ctx      | mutt_md5_init_ctx      |
| md5_process_block | mutt_md5_process_block |
| md5_process_bytes | mutt_md5_process_bytes |
| md5_read_ctx      | mutt_md5_read_ctx      |
| md5_stream        | mutt_md5_stream        |

**memory**

| Old function | New function     |
| :----------- | :--------------- |
| safe_calloc  | mutt_mem_calloc  |
| safe_free    | mutt_mem_free    |
| safe_malloc  | mutt_mem_malloc  |
| safe_realloc | mutt_mem_realloc |

**sha1**

| Old function   | New function        |
| :------------- | :------------------ |
| sha1_final     | mutt_sha1_final     |
| sha1_init      | mutt_sha1_init      |
| sha1_transform | mutt_sha1_transform |
| sha1_update    | mutt_sha1_update    |

**string2**

| Old function            | New function                |
| :---------------------- | :-------------------------- |
| mutt_str_adjust         | mutt_str_adjust             |
| mutt_str_append_item    | mutt_str_append_item        |
| mutt_atoi               | mutt_str_atoi               |
| mutt_atol               | mutt_str_atol               |
| mutt_atos               | mutt_str_atos               |
| rfc822_dequote_comment  | mutt_str_dequote_comment    |
| find_word               | mutt_str_find_word          |
| is_ascii                | mutt_str_is_ascii           |
| is_email_wsp            | mutt_str_is_email_wsp       |
| lwslen                  | mutt_str_lws_len            |
| lwsrlen                 | mutt_str_lws_rlen           |
| next_word               | mutt_str_next_word          |
| mutt_remove_trailing_ws | mutt_str_remove_trailing_ws |
| mutt_str_replace        | mutt_str_replace            |
| rstrnstr                | mutt_str_rstrnstr           |
| skip_email_wsp          | mutt_str_skip_email_wsp     |
| mutt_skip_whitespace    | mutt_str_skip_whitespace    |
| mutt_strcasecmp         | mutt_str_strcasecmp         |
| safe_strcat             | mutt_str_strcat             |
| mutt_strchrnul          | mutt_str_strchrnul          |
| mutt_strcmp             | mutt_str_strcmp             |
| mutt_strcoll            | mutt_str_strcoll            |
| safe_strdup             | mutt_str_strdup             |
| strfcpy                 | mutt_str_strfcpy            |
| mutt_stristr            | mutt_str_stristr            |
| mutt_strlen             | mutt_str_strlen             |
| mutt_strlower           | mutt_str_strlower           |
| mutt_strncasecmp        | mutt_str_strncasecmp        |
| safe_strncat            | mutt_str_strncat            |
| mutt_strncmp            | mutt_str_strncmp            |
| strnfcpy                | mutt_str_strnfcpy           |
| mutt_substrcpy          | mutt_str_substr_cpy         |
| mutt_substrdup          | mutt_str_substr_dup         |
| imap_wordcasecmp        | mutt_str_word_casecmp       |

**Comment by toogley** [comment]
Curiosity: why mutt_* instead of mu_* functions?

**Comment by libBletchley** [comment]
@toogley 
> Curiosity: why mutt_* instead of mu_* functions?

I'm not sure, but IMO "mu_" could risk being misinterpreted as "**M**ember function, returning **U**nsigned integer".. it could even be hungarian notation for that, perhaps.

**Comment by flatcap** [comment]
It was agreed that `mu_` would imply a directory of `mu` and a library of `libmu.a`.
That sounds a bit weird.

In retrospect, I should have insisted on `util_`, `util/` and `libutil.a` as the naming's getting a little complicated.

**Comment by toogley** [comment]
@flatcap can't we change it again?

**Comment by flatcap** [comment]
Yes.  But these big changes mean fixing all the PRs and branches which takes a while.
Soon.
