### ISSUE TITLE
lib/mbyte.c does not exists

### ISSUE THREAD

**Issue by reisradomil** [neomutt/neomutt#947]
The commit "Add missing source file to po/POTFILES.in" 7e2efa280d44a8da024e454140b2a8d90aaf7da5 introduced lib/mbyte.c in po/POTFILES.in. However, this file does not exists and thus lets make fail with

```
make[3]: *** No rule to make target '../lib/mbyte.c', needed by 'neomutt.pot-update'.  Stop.
```

Note that there is a file mbyte.c in the root directory.

**Comment by flatcap** [comment]
That, my friend, is because flatcap is an idiot :-)
In one of my many branches, I noticed that POTFILES.in was missing a file.
I pushed the fix thinking that the corresponding code was already in master.
I've (force) fixed master.
