### ISSUE TITLE
Change in change-folder/? behaviour

### ISSUE THREAD

**Issue by tbrk** [neomutt/neomutt#951]
In NeoMutt 20170113 (1.7.2) running on Debian doing a `change-folder` and then pressing `?` drops to the file system (pressing `tab` shows the list of watched mailboxes) as in standard Mutt.

In NeoMutt 20171027 running on MacOS/brew doing a `change-folder` and then pressing `?` shows the list of watched mailboxes.

Is this change in behaviour intentional?

**Comment by tbrk** [comment]
This behaviour (showing the list of watched mailboxes rather than the filesystem) persists in the latest clone of NeoMutt. Is it intentional?

**Comment by flatcap** [comment]
Yes, sorry.  We changed that when we modified the browser.
A lot of people use the <kbd>y</kbd> macro that was in the default config file.

It used to be:
`macro index y "<change-folder>?<toggle-mailboxes>" "show incoming mailboxes list"`
We swapped around the browser and changed the macro to:
`macro index y "<change-folder>?" "show incoming mailboxes list"`

**Comment by tbrk** [comment]
I see. Thanks for your response. I have the mapping
`macro index <left> "c?"`
which used to drop quickly into the file browser, but now it shows the incoming mailboxes list. I haven't been able to figure out a new macro to replicate the original behaviour (i.e., to drop into the file browser in the current directory). Is it even possible after the changes?

**Comment by flatcap** [comment]
I've just run Mutt and NeoMutt side-by-side...

From an IMAP folder, I pressed <kbd>c?</kbd>
As I expected, the starting views differed:
- Mutt: IMAP directory view
- NeoMutt: IMAP mailbox view

Now, pressing <kbd>Tab</kbd> swaps between the two views.
Neither displays the local filesystem view.

Pressing: <kbd>c</kbd><kbd>Ctrl-u</kbd><kbd>~</kbd><kbd>Enter</kbd> shows me the filesystem view in both Mutt and NeoMutt.

Pressing: <kbd>Tab</kbd> now swaps between the Filesystem view and the IMAP mailboxes view in both Mutt and NeoMutt.

Here's where the two differ.
Starting back in the Index, if you _go back_ to the browser <kbd>c?</kbd>, then:
- Mutt: shows the Filesystem view (and toggles to the IMAP mailboxes view)
- NeoMutt: shows the IMAP mailbox view (and toggles to the IMAP directories view)

In Mutt, the behaviour of <kbd>c?</kbd> isn't consistent -- it depends on your previous visits.

I don't think I was aware of that before (Neo)Mutt's a complicated beast :-)
I'll see what the other devs think, tomorrow.

**Comment by tbrk** [comment]
I hadn't even thought about IMAP! I download all my mail into (local) maildir folders. In fact, my use case is working with maildir directories: a shortcut (previously `c?` via a macro) switches to browsing directories, one presses `enter` to view the contents of a folder, and the same shortcut returns to browsing directories from the previous location. I've seen the internals of (Neo)Mutt and I sympathise! It'd be great though to have another way of navigating as before. Thanks!

**Comment by flatcap** [comment]
> I've seen the internals of (Neo)Mutt and I sympathise

hehe, it's getting better.  We're aggressively tidying / refactoring /documenting the code.

> It'd be great though to have another way of navigating as before

I'll have a think how to make a consistent interface for the browser.
(ideas welcome :-)

**Comment by DebXWoody** [comment]
@tbrk 
Did you try: `macro index <left> "c?<tab>"`

**Comment by tbrk** [comment]
@DebXWoody, I got so caught up in the change in behavior that I didn't even think of that simple solution. Thanks! I'll update my muttrc and upgrade neomutt on my Debian box.
