### ISSUE TITLE
non-modifiable artifacts not commented as such

### ISSUE THREAD

**Issue by libBletchley** [neomutt/neomutt#952]
I was making some changes and edited `Makefile`, did a rollback, then did some investigation on why the rollback apparently didn't happen, only to discover that I edited a bit of auto-generated code.  Auto-generated code should normally contain a fairly loud header at the top to prevent this, and ideally it should also say what produced it so that someone tempted to edit the code knows where to look.

Similarly, I edited `autosetup/default.auto`, which was under version control but part of another project (https://github.com/neomutt/neomutt/pull/949#issuecomment-343959314).  I'm not sure why a file that comes from another project and regarded as unchangeable is under version control in neomutt, but if that is the correct organization then it too should have a loud header comment saying not to edit, and ideally state where upstream it comes from so as to know where the edit should go.

**Comment by flatcap** [comment]
> I ... edited Makefile

OK.  `Makefile` has always been auto-generated.
Mutt is an autotools project and NeoMutt is an autosetup project.
Also, `Makefile` isn't under revision control, which should be a clue.

> Auto-generated code should normally contain a fairly loud header at the top to prevent this

Yes a big warning would be nice, but `Makefile` is generated by pre-processing `Makefile.autosetup`.
If we want a header in `Makefile`, it would also be visible in `Makefile.autosetup`!

> I'm not sure why a file that comes from another project and regarded as unchangeable

Our build process depends on other projects.
Some are expressed as build dependencies.
Others have to be bundled locally as we can't rely on everyone having the right packages.

Most of the files in the `m4/` directory are 3rd-party.
All the files in the `autosetup/` directory are 3rd-party.

Generally speaking, it's not expected for developers to need to change the build.

If you have any questions, or need help, please ask.  We're always around in IRC.
It'll save you time and it'll probably save us time, too.
