### ISSUE TITLE
Enhance struct Buffer

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#961]
Scope of this ticket is to enhance how `struct Buffer` is used and behaves, with the ultimate goal to reduce the number of malloc/free calls related to using this structure.

1. make sure all instances of `struct Buffer` are allocated on the stack
2. make sure internal members are updated only via functions, not manually
3. implement Small String Optimization to avoid most (re)allocations

Goals 1. and 2. somewhat collide, as the only way to achieve 2. in C would be to make `Buffer` an opaque struct. This, however, would collide with goal 1. and would require either a pool of preallocated buffers or the allocation of buffers on the heap.

I'll have a think. Comments are welcome.

**Comment by flatcap** [comment]
There are ~80 functions that take (buf, buflen) and another ~180 with very similar (char*,int) pairs.
The large majority of these functions fill the buffer using `snprintf()` or `strfcpy()`.
We could replace `snprintf()` with `mutt_buffer_printf()` and create a new `mutt_buffer_strfcpy()`.

Using `struct Buffer`, the caller wouldn't care about the length any more.
If the function needs to add lots of small pieces, they might use `mutt_buffer_alloc()` to reserve some space.

---

An (clumsy) alternative to your SSO, would be:
```c
#define FIXED_BUFFER_INIT(var, size) \
  char var##_data[size];             \
  struct Buffer var;                 \
  var.data = var##_data;             \
  var.dptr = var##_data;             \
  var.dsize = size;                  \
  var.fixed_size = true;
```

**Comment by gahr** [comment]
This was a nice experiment but tests seem to indicate that it won't bring a great performance boost. Closing for now. If I get back to it, it'll be easier to start anew than to maintain my branch in sync.
