### ISSUE TITLE
Notmuch integration not working with Mutt 1.9.1

### ISSUE THREAD

**Issue by komond** [neomutt/neomutt#963]
I am a user of Ubuntu 14.04. I was using NeoMutt all the while, downloaded from this PPA: https://launchpad.net/~jonathonf. Yesterday, there was an update to 1.9.1-1~14.04.york0   on this PPA. After I installed the update neomutt seems to have a problem working with notmuch. When I start neomutt I get the following error messages:

Error in /etc/Muttrc.d/notmuch.rc, line 6: change-vfolder: no such function in map
Error in /etc/Muttrc.d/notmuch.rc, line 9: entire-thread: no such function in map
Error in /etc/Muttrc.d/notmuch.rc, line 12: modify-labels: no such function in map
Error in /etc/Muttrc.d/notmuch.rc, line 15: vfolder-from-query: no such function in map
Error in /usr/lib/mutt/source-muttrc.d|, line 6: source: errors in /etc/Muttrc.d/notmuch.rc
Error in /etc/Muttrc, line 141: source: errors in /usr/lib/mutt/source-muttrc.d|
source: errors in /etc/Muttrc
Error in /home/raghavan/.muttrc-prefs, line 24: nm_default_uri: unknown variable
Press any key to continue...

Could I please get some help with this?

**Comment by flatcap** [comment]
Hi @komond.  Sorry about this.

Debian is currently trying to sort Mutt and NeoMutt into two separate packages.
It seems that the 'Mutt' package has been reverted to plain upstream Mutt (which doesn't have Notmuch).
Your PPA provider has probably automatically rebuilt this causing your downgrade.

Debian are working on a separate NeoMutt package which should be available soon (I'm told :-)

There are probably other PPAs with NeoMutt in them, but we don't seem to have many Ubuntu users to ask.
I suggest contacting JonathonF (the PPA owner) to see if he can help out.

Please let us know how you get on (and if there's anything we can do to help).

**Comment by komond** [comment]
Thanks for your quick response. I understand what you are saying. 

However, I also tried downloading neomutt's latest tar file, building it, and running it. Even this binary refused to recognize notmuch-specific configuration variables like nm_default_uri.

**Comment by flatcap** [comment]
There are two parts to Notmuch support:
- Build dependencies, called something like `notmuch-dev` (I don't have Ubuntu to hand)
- Configure option, either: (we're in the process of moving to autosetup)
   * ./configure --enable-notmuch
   * ./configure.autosetup --notmuch

If all goes well, then `neomutt -v` should show `+notmuch`.

**Comment by komond** [comment]
Thank you so much for your help. 

  ./configure.autosetup --enable-notmuch

did the trick for me (after installing notmuch-dev). I guess this option is not specified in the INSTALL file.

**Comment by flatcap** [comment]
> I guess this option is not specified in the INSTALL file.

Sorry, that file has become out-of-date as we improved the build process.
We tend to point people to our [distro pages](https://www.neomutt.org/distro.html).
As yet, we haven't had an Ubuntu user to offer some instructions.

> Thank you so much for your help.

No problem.
