### ISSUE TITLE
autosetup problems with doc/ dir

### ISSUE THREAD

**Issue by aradici** [neomutt/neomutt#964]
When the package is build by:
    dh $@ --builddirectory=debian/build

Then this exports all the directories to debian/build and launches the relevant build commands there, including configure.autosetup, make, etc

Unfortunately it seems that the doc/ directory is not copied, so the build files when it comes to add doc/

I don't know exactly what copies the directory, but it worked with autoconf and it is not working with autosetup

**Comment by flatcap** [comment]
This simple patch against neomutt-20171027 fixes your out-of-tree build.

**Note**: This has already been fixed in master.

**Comment by aradici** [comment]
Sorry for not checking master, I was only using the tar file :(
