### ISSUE TITLE
/usr/lib/neomutt binaries incorrectly named

### ISSUE THREAD

**Issue by aradici** [neomutt/neomutt#965]
currently neomutt builds 3 binaries and ship them in /usr/lib/neomutt:
* pgpewrap
* pgpring
* smime_keys

Unfortunately the man pages of those binaries are pgpewarp_neomutt, so the binaries should be built with the _neomutt prefix, otherwise it will overlap with mutt (which ships the same binaries with the same names)

**Comment by flatcap** [comment]
Argh! :-)

Yes, there will be multiple binaries with the same name, but there shouldn't be a clash.
The binaries are in `/usr/lib/neomutt` but they're not expected to be on the PATH.
(They're referenced in the default config file by their full path)

If the binary and man pages **must** match, then I'll go back to:
- `/usr/bin/pgpewrap_neomutt`
- `/usr/share/man/man1/pgpewrap_neomutt.1`
etc

**Comment by aradici** [comment]
yes they won't clash becuase they are in different directories, but then the manpage will clash :) The manpage have to be named like the binaries, so I would say to go to _neomutt for the binaries as well

**Comment by gahr** [comment]
> The manpage have to be named like the binaries

Do they? Why?

**Comment by aradici** [comment]
I suppose if you have /usr/bin/pgpewrap_neomutt and you want to know the options, you would do "man pgpewrap_neomutt", which will require to have a manpage named like that, unless I'm missing something

**Comment by aradici** [comment]
I think at the moment we decided to keep these names as is, if there is the need (i.e.: someone opens a bug or tells us that it is against the policy, we will rename them).

**Comment by flatcap** [comment]
OK, thanks.
