### ISSUE TITLE
virtual mailbox view periodically reverts to full imap inbox view

### ISSUE THREAD

**Issue by craftyguy** [neomutt/neomutt#969]
My setup:

muttrc contains:
```
timeout-hook 'exec sync-mailbox'
set timeout=5
set virtual_spoolfile=yes
virtual-mailboxes "inbox"                 "notmuch://?query=tag:inbox" 
```

I have an external program (mbsync) that periodically (2min) updates a single maildir over imap.

On startup, neomutt correctly uses my 'inbox' virtual mailbox, which is a notmuch query on `tag:inbox`.

#### Expected behavior
I expect the pager view to always stay at my 'inbox' virtual mailbox unless I explicitly change to another virtual mailbox, or open a mail, 

#### Actual behavior
Periodically the view will automatically change to show my imap 'inbox' mailbox, which has _all_ emails in it. This change happens without me doing anything. This occurs whether or not the term window running neomutt is in focus.

I have notices that if `timeout` is 5 seconds, the issue happens after anywhere from a few seconds to a handful of minutes. If I change `timeout` to something longer, like 120 seconds, it can take a few hours to happen. This seems to suggest there's some race condition between `sync-mailbox`, the maildir being updated externally by mbsync, and the notmuch query to display the virtual mailbox.

#### Used program versions
neomutt-20171013

#### System and its version
Arch Linux

**Comment by flatcap** [comment]
@neomutt/notmuch-users Please can you take a look and find out what's going on.

**Comment by bremner** [comment]
Richard Russon <notifications@github.com> writes:

> @neomutt/notmuch-users Please can you take a look and find out what's going on.
>
> -- 

Sorry, I don't know enough about mutt internals to contribute much at
this point. If you can narrow things down to unwanted libnotmuch
behaviour I'm happy to take a look.

d
