### ISSUE TITLE
could you support /etc/mailname?

### ISSUE THREAD

**Issue by aradici** [neomutt/neomutt#974]
We talked about this in the chat, given that /etc/mailname is present on both Debian and Ubuntu, I was wondering if you could support /etc/mailname to determine the Fqdn.

I wrote this patch for the latest neomutt stable:
https://anonscm.debian.org/cgit/pkg-mutt/neomutt.git/tree/debian/patches/debian-specific/882690-use_fqdn_from_etc_mailname.patch

But probably this one for the latest mut stable might apply cleanly at this point, given that you sync often to mutt head:
https://anonscm.debian.org/cgit/pkg-mutt/mutt.git/tree/debian/patches/debian-specific/882690-use_fqdn_from_etc_mailname.patch

Or you could write any similar variation and I'll happily drop mine!

If you are interested I opened a similar bug to mutt upstream:
https://dev.mutt.org/trac/ticket/3980

**Comment by flatcap** [comment]
Note to self (or anyone who wants an easy task):

Debian looks for `/etc/mailname`
OpenBSD looks for `/etc/mail/mailname`

`libmutt` has functions `mutt_file_read_keyword()` or `mutt_file_read_line()` which may be of use.

Rather than configure which one to read, it might be simpler to look for both.

**Comment by aradici** [comment]
the proposed fix in the mutt upstream code is to do
set hostname="`cat /etc/mailname`" in /etc/Muttrc which could also make sense

**Comment by gahr** [comment]
Yes, although that would be something distro maintainers would need to do basing on where - if anywhere - that file is in a particular distribution.

So, it’s either we support some common use cases or say “not our business” and let distros - or end users - deal with that.

I don’t have a strong opinion. My mild opinion is we should go either the full-way or no-way-at-all. The full-way way would be to try as hard as we can to figure out the hostname, so adding support for mailname files would bring us closer to that.

The no-way-at-all way would be to drop utsname, getaddrinfo, ndis lookup etc altogether and only support the hostname variable.

I’m all ears ;)

**Comment by flatcap** [comment]
I'm not too worried about adding this, for now.
We already have a precedent: nntp reads `/etc/nntpserver`

Is `/etc/mailname` always going to be the case?
Or should the code reference `SYSCONFDIR/mailname`?
`/usr/local/etc/mailname` for example?

**Comment by gahr** [comment]
Neither [Debian](https://wiki.debian.org/EtcMailName) nor the smtpd reference you mentioned talk about sysconfdir.. I think we should be fine with the patch as is.
