### ISSUE TITLE
Folder-hooks for outgoing folder are run upon sending mail, but after return to index, hooks for original folder are not.

### ISSUE THREAD

**Issue by mjk-gh** [neomutt/neomutt#977]
*  Actual behavior
When an email is sent (with "record" set), folder-hooks for the outoing mail folder are executed, but upon return to the index of the currently viewed folder, neither the default folder-hooks nor the folder-hooks for the currently viewed folder are executed.

When the email is not sent, but postponed instead, the outoing folder-hooks do not seem to be executed (or at least nothing +INBOX-related seems to be changed afterwards).

    *  Expected behavior
From a user's point of view, I expect that sending an email doesn't change anything regarding the currently viewed folder.

The manual states:

> It is often desirable to change settings based on which mailbox you are
> **reading**. The folder-hook command provides a method by which you can execute any
> configuration command. regex is a regular expression specifying in which
> mailboxes to execute command before **loading**.

So, if folder-hooks are supposed to be just for _reading_, then don't execute the outgoing folder-hooks at all when sending mail. If they are supposed to be for _loading_, then running the outgoing folder-hooks when sending mail can at least be considered, but then the default folder-hooks as well as the folder-hooks for the currently viewed folder need to be executed afterwards.

    * Steps to reproduce

As an example, define different folder hooks for +INBOX$ and +out$, and set record to "+out":

```
set record="+out"
folder-hook +INBOX$ "set sort=threads"
folder-hook +out$   "set sort=reverse-date"
```
_(See attachment for full .muttrc, sensitive information replaced by "XXX")_

- Start `mutt -f+INBOX`
- Check in the status line that the sort order is "threads"
- Compose a mail, and send it (default key "y")
- mutt will return to the index for +INBOX
- The status line now shows that the sort order is "reverse-date"

```
BUG in markdown?
This code block seems to be needed, as otherwise,
the items below appear as subitems of the list above.
```

    *  Used program versions
neomutt 20171027+dfsg.1-1

    *  Operating System and its version
Debian testing (amd64)

**Attachment**
[muttrc.txt](https://github.com/neomutt/neomutt/files/1523330/muttrc.txt)

_{ EDIT 2017-12-02: Minor typo }_

**Comment by mjk-gh** [comment]
The described bug seems to be a regression from an older version, namely "mutt 1.8.3+neomutt20170609-2+b1", in which this bug does not occur; the currently viewed folder does not get changed in any way after sending an email.

Debian packages for this version:
- Source: http://snapshot.debian.org/archive/debian/20170624T221511Z/pool/main/m/mutt/mutt_1.8.3%2Bneomutt20170609.orig.tar.gz
- Patches: http://snapshot.debian.org/archive/debian/20170626T035020Z/pool/main/m/mutt/mutt_1.8.3%2Bneomutt20170609-2.debian.tar.xz
- Binary: http://snapshot.debian.org/archive/debian/20170720T160309Z/pool/main/m/mutt/mutt_1.8.3%2Bneomutt20170609-2%2Bb1_amd64.deb
**Caveat:** Debian package "mutt" is actually "neomutt" up to and including version 1.8.3+neomutt20170609-2+b1. Starting with version 1.9.1-1, package "mutt" is the original mutt,
and neomutt is available in the newly created package "neomutt".

Debian packages for the originally reported version which exhibits the described bug:
- Source: http://snapshot.debian.org/archive/debian-debug/20171126T151517Z/pool/main/n/neomutt/neomutt_20171027%2Bdfsg.1.orig.tar.gz
- Patches: http://snapshot.debian.org/archive/debian-debug/20171126T151517Z/pool/main/n/neomutt/neomutt_20171027%2Bdfsg.1-1.debian.tar.xz
- Binary: http://snapshot.debian.org/archive/debian/20171126T161408Z/pool/main/n/neomutt/neomutt_20171027%2Bdfsg.1-1_amd64.deb

**Comment by flatcap** [comment]
Thanks for all the info.
I've traced it back to 4aaf1ef7 which was for #886 (call the folder-hook before saving to $record).
The first release with this was 2017-10-27.
