### ISSUE TITLE
Feature idea: Save or restricted sync

### ISSUE THREAD

**Issue by RichiH** [neomutt/neomutt#98]
With the introduction of timeout, it's possible to sync maildir state back to the server regularly.

There are some options I don't consider too risky, like marking as read/new or moving. Others, like deletion, are riskier to me. I know that others feel differently, so this might need to be configurable.

Anyway, a way to only sync the bits and pieces the user considers safe while keeping potentially unsafe sync operations for manual syncing could be nice.

I am not sure about the overall usefulness, which is why this is a feature idea, not a request.

**Comment by flatcap** [comment]
OK, I think I understand.

I haven't used offlineimap, but doesn't that do two-way synchronisation?

For comparison, rsync has options like `--delete-after` : delete if and only if everything else has succeeded.  An rsync solution would be quite easy to arrange.

> I am not sure about the overall usefulness, which is why this is a feature idea, not a request.

Well let's invite discussion and see what happens :-)

**Comment by RichiH** [comment]
Sorry, yes, the implied context is using an Maildir with offlineimap.

I wasn't talking about execution order, more about doing parts of a full sync at all (or not), but that's also intriguing...

**Comment by flatcap** [comment]
It's useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
