### ISSUE TITLE
query_command ignores the first line of output

### ISSUE THREAD

**Issue by esovetkin** [neomutt/neomutt#983]
I have noticed the following issue, when using the following address autocomplete command:
```
set query_command="notmuch address %s"
set query_format="%4c %t %-70.70a %-70.70n %?e?(%e)?"
```

The query result of the bash command:
```
notmuch address <query>
```
contains one more result comparing to the `query_command` output in mutt (the very first line is being lost).

When the query output contains only one resulting line then no completion in mutt is done at all.

p.s. I am using 20171013 version.

**Comment by flatcap** [comment]
[According to the guide](https://www.neomutt.org/guide/advancedusage.html#query):

> It should return a one line message, then each matching response on a single line, each line containing a tab separated address

The first line is a header which is ignored.
If we find that the first line contains `<tab>`s, then it might be possible to use it.

**Comment by esovetkin** [comment]
Thanks, I missed that there should be a header! The following query command solves the issue:
```
set query_command="echo 'dummy' ; notmuch address %s"
```
