### ISSUE TITLE
Add support for proxy

### ISSUE THREAD

**Issue by pickfire** [neomutt/neomutt#99]
I normally use `torify mutt` but then it looks ugly since a lot of random error pop out from tor that destroys the view of mutt. Support for `socks5` proxy would be nice.

**Comment by flatcap** [comment]
It's useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).

**Comment by mdosch** [comment]
@pickfire 

```
cat /usr/local/bin/email 
#! /bin/bash
torify neomutt 2>/dev/null
```

Works well for me.
