### ISSUE TITLE
changing folders in this nifty way bypasses folder-hook

### ISSUE THREAD

**Issue by nobrowser** [neomutt/neomutt#993]
I noticed something odd quite a long time ago, but I haven't fingered it until today.

Here are four increasingly complex ways to switch to another folder:

1. execute the change-folder command from the index menu (bound to `c`) and just accept the default
2. same from the pager menu
3. in the index menu, enter the mailbox browser with `c ?` or `y` , change the highlighted line and hit `Enter`
4. same as 3 but from the pager

folder-hook is run in cases 1-3, but _not_ in case 4.  I see this with 20170707 (aka 0ae25de) but I have no reason to think it changed recently.  This could be dangerous as the folder-hook is a universal way to change settings, some of which may not be obvious until too late (as the first example, you can compose and send a message with unexpected headers).
I wish I could assign myself but `curs_main.c` is a swamp  ...  8-O

**Comment by flatcap** [comment]
Nice find!

There's one other method: `<sidebar-open>`, but that seems to trigger the hook from the index or the pager.

> ... curs_main.c is a swamp ...

Yes, it is :-)

**Comment by flatcap** [comment]
This is a bit annoying.
When I first tested it, I could repeat it reliably.
Then a while later, I couldn't.
Later still it happened again.

I looked through the code and the hook is being called unconditionally just before the mailbox is opened.
If the hook isn't reached, then the folder wouldn't be opened -- which would be noticeable.

**Comment by gahr** [comment]
> same as 3 but from the pager

This does trigger a `folder-hook` on pattern `.` here.

**Comment by nobrowser** [comment]
It's possbile this is just a symptom of a memory corruption somewhere else.  Has anyone tried to run neomutt with valgrind or a similar tool?
